### ISSUE TITLE
Email templates

### ISSUE THREAD

**Issue by jbrooksuk** [cachethq/Cachet#100]
We'll need an email template setting up for notifications and team member invitations later on. Any template we use should:

- Be able to pick up on theme overrides.
- Work across all major email clients.
- Responsive so that it's easily readable on phones, tablets etc.
- Not be restrictive on layout, for instance a notification will look different to a team member invitation etc.

**Comment by joecohens** [comment]
Can we close this one?

**Comment by jbrooksuk** [comment]
Yes :)
