### ISSUE TITLE
Settings/Theme

### ISSUE THREAD

**Issue by jzielke** [cachethq/Cachet#1005]
I can't uncheck the show dashboard option in Settings/Theme. When I uncheck it, and save, it comes back as checked.  It was not checked originally, so I checked it and saved to see what it did on the status page.  Not it will not save or display unchecked.

**Comment by jbrooksuk** [comment]
What version are you on?

**Comment by jzielke** [comment]
version v1.2

I did look at the tables and the field is not getting saved.  All other fields work fine in the application.

**Comment by jbrooksuk** [comment]
This is fixed in V2, stay tuned.
