### ISSUE TITLE
Customize email templates

### ISSUE THREAD

**Issue by peterlaws** [CachetHQ/Cachet#1009]
Sorry if this has been suggested already.

Currently, the email that subscribers get are very basic. Will there be a way to edit this, what it states, layout, etc?

eg.

Subject

> New Incident Reported.

Body

> New incident has been reported on Name Status Page.
> Investigating
> This is a test incident
> Name Status Page is powered by Cachet.
> Unsuscribe from email updates.
> Name Status Page

I also noticed that the email subject has "New Incident Reported" which is very ambiguous. Maybe include the incident title to the subject, as I do not see the title of the incident mentioned anywhere else?

**Comment by wngravette** [comment]
Changing the layout/appearance of the emails would simply be a matter of editing the relevant views.

**Comment by jbrooksuk** [comment]
@wngravette feel free to submit a PR with your suggested changes :)

**Comment by jbrooksuk** [comment]
The email system isn't the best, we're completely aware :)

**Comment by wngravette** [comment]
No problem, I may just even be able to whip something up within the next few days. Cheers.

**Comment by jbrooksuk** [comment]
Thanks @wngravette, I'm moving this to 2.1.0 but if you're able to do it before we ship, that'd be awesome.

**Comment by peterlaws** [comment]
> Changing the layout/appearance of the emails would simply be a matter of editing the relevant views.

I assume the email subjects are hardcoded, right?

**Comment by wngravette** [comment]
Indeed, at app/Handlers/Events/ in the relevant files.

**Comment by jbrooksuk** [comment]
Renamed this issue.

**Comment by AntoineAugusti** [comment]
@peterlaws Are you going to tackle this? If not, what do we need to do precisely?

**Comment by jbrooksuk** [comment]
@AntoineAugusti:

1. Store email contents in a table.
2. Use Twig or something to allow customization, unless we want to stick with Blade? Twig is a good templating language for things like this.
3. We'll need a panel in the dashboard that allows editing of templates.
4. Change the email handling code to first grab the content, compile and then send.

**Comment by AntoineAugusti** [comment]
@jbrooksuk This seems a lot of work. Are you sure a lot of people are going to want to edit the basic email template?

**Comment by jbrooksuk** [comment]
@AntoineAugusti it is, which is why we've not done it ourselves yet :)

**Comment by srikanth88infy** [comment]
May I know if there are any updates regarding this feature? I would love to know how can I tweak a basic template. Can anyone point me how can I achieve this?

**Comment by jbrooksuk** [comment]
@srikanth88infy you can manually edit the respective views?

**Comment by peterlaws** [comment]
If we do that, we would need to keep modifying the files each update, if we update via git?

I edited them, and when I upgraded, git complained that it wouldn't update due to inconsistency with these files.

**Comment by jbrooksuk** [comment]
You can stash files, then re-apply but you do run the risk of them not applying again. We'll get round to this eventually, I'm sure :)

**Comment by srikanth88infy** [comment]
@peterlaws Could you point me how could I manually modify the email templates?

**Comment by peterlaws** [comment]
Just navigate to ``/resources/views/emails/`` within your Cachet root directory, all the templates are there.

**Comment by srikanth88infy** [comment]
@peterlaws  Thank you!!! :)

**Comment by nkuehn** [comment]
+1 for this - as a minimum it would be very helpful to customize  the subject line via a template.  Maybe this here are two separate issues - one for the hardcoded subject line and one for general customizability of the email templates? 

Specific Issue in case is the we'd like to mention the affected component in the subject line ( there are very critical components an less critical ones and I always tend to get a heart attack on "new incident reported" email subject lines that turn out to be just some helper tool failure ).

**Comment by userguy** [comment]
+1

**Comment by joecohens** [comment]
Emails have a new design now and subject making it more informative.

Subject: [New Incident] Investigating: Degraded performance in the API
Design: 
<img width="658" alt="screen shot 2016-05-28 at 12 43 24 pm" src="https://cloud.githubusercontent.com/assets/1803556/15628848/d75ad66e-24d1-11e6-9d63-f027a2bb653e.png">

**Comment by GrahamCampbell** [comment]
This new design will be available in v2.3.0-RC3, and later.

**Comment by jbrooksuk** [comment]
💥

**Comment by luiseduardobrito** [comment]
+1

**Comment by GrahamCampbell** [comment]
:)

**Comment by CosmicPuppy** [comment]
+1

**Comment by jbrooksuk** [comment]
Along with the new notification system, your theme colours will transfer across to the email template. Aside from that, you'll need to go into Cachet's code to customise it 👍

**Comment by Majklas** [comment]
any news on this?
