### ISSUE TITLE
Setup wizard

### ISSUE THREAD

**Issue by jbrooksuk** [cachethq/Cachet#101]
Rather than the current setup page, we may be better off with a "wizard" style setup. Again using the same inspiration, this is what I have in mind:

![screenshot 2014-12-28 10 34 36](https://cloud.githubusercontent.com/assets/246103/5563630/39715e82-8e7d-11e4-9f6c-ddacc6cf3d20.png)

Pros to a wizard:

- We can add more setup stages, team member lists etc.
- It's cleaner since each stage is under a new section.
- Visible progress.

Cons:

- May look like there is more to do, will users always finish installation?
- JavaScript is required to deal with the transition of stages.

**Comment by joecohens** [comment]
https://github.com/cachethq/Cachet/pull/308
