### ISSUE TITLE
Using Docker: PHP Fatal error (memory)

### ISSUE THREAD

**Issue by ThePooN** [cachethq/Cachet#1018]
Hello,

I installed Cachet yesterday using Docker and everything was working perfectly, until some hours ago.
I'm getting in the /var/log/nginx/errors.log file (from Docker) errors like this:
```
2015/10/07 15:04:09 [error] 78#0: *15 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Allowed memory size of 134217728 bytes exhausted (tried to allocate 82 bytes) in /var/www/html/bootstrap/cache/compiled.php on line 9645" while reading response header from upstream, client: XX.XX.XX.XX, server: localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "XX.XX.XX.XX:XX"
```

I can edit the PHP config, but this shouldn't be happening, right?

Thanks

**Comment by jbrooksuk** [comment]
Ping @cachethq/docker

**Comment by djdefi** [comment]
Seems like the app is running out of memory, not really a Docker issue per se.  

It would be possible to increase the php `memory_limit`, however that may just delay the issue from occurring again if there is a memory leak.

**Comment by n0mer** [comment]
@ThePooN how much free RAM on your docker host?

Looks like nginx ran out of memory

**Comment by ThePooN** [comment]
https://img.cartooncraft.fr/UjRD/89a1ca
Is that enough?

**Comment by n0mer** [comment]
i doubt 32Mb is enough

**Comment by ThePooN** [comment]
actually, it is 32Gb

**Comment by n0mer** [comment]
![screenshot](https://img.cartooncraft.fr/UjRD/89a1ca)

you're right

**Comment by djdefi** [comment]
This is a limit in the php config, there is plenty of RAM on the system itself.

I guess we could add an `ENV` variable to specify a different php.ini `memory_limit` 

I have not run into this issue myself, been running Cachet in Docker for months now

**Comment by n0mer** [comment]
i'm not either PHP dev or Cachet expert, but looks like we've got memory leak :)

* http://stackoverflow.com/questions/561066/fatal-error-allowed-memory-size-of-134217728-bytes-exhausted-codeigniter-xml

> People, changing the memory_limit by `ini_set('memory_limit', '-1');` is NOT a solution at all.
Please don't do that. Obviously php has a memory leak somewhere and you are telling the server to just use all the memory that it wants. The problem has not been fixed at all. If you monitor your server, you will see that it is now probably using up most of the RAM and even swapping to disk.
You should probably try to track down the exact bug in your code and fix it.

**Comment by ThePooN** [comment]
i can upload you my mysql database if you want.

**Comment by jbrooksuk** [comment]
Why would Cachet be leaking memory? We don't have any long running processes, perhaps the queue but that's Laravel?

**Comment by ThePooN** [comment]
I can try to set the limit to -1 and see how many memory it uses.

**Comment by GrahamCampbell** [comment]
Please direct all docker issues to https://github.com/cachethq/Docker/issues.

**Comment by ThePooN** [comment]
I'm gotta reinstall and see what happens - still with docker - with a different database. Will open a new issue in the Docker repo if this happens again. Thanks for your support.

**Comment by n0mer** [comment]
it is memory issue, not docker

try to start the same cachet instance on host itself, and see what happens

**Comment by ThePooN** [comment]
already too late. i wasn't satisfied of my actual db setup anyway.
