### ISSUE TITLE
External API support (Maintenance & Incidents)

### ISSUE THREAD

**Issue by peterlaws** [CachetHQ/Cachet#1023]
(Not sure where to post proper feature requests?)

Would be neat if you could (optionally) post maintenance & incidents to external API's, such as Twitter, etc.

Very useful. Has this been asked before?

**Comment by jbrooksuk** [comment]
2.0.0 won't support this out of the box, but we've made this much easier to implement by making use of events. We fire an event for all sorts of actions now.

**Comment by smithkyle** [comment]
Looking forward to this for Slack integration!

**Comment by GrahamCampbell** [comment]
Moving to the 2.2 milestone.

**Comment by mrbase** [comment]
@smithkyle made a simple "one account" package for posting to slack https://github.com/mrbase/cachet-slack-integration/ - multi account support is on the roadmap

**Comment by jbrooksuk** [comment]
@CachetHQ/owners what do you think about closing this because of the event integrations we have? As @mrbase has shown it's possible to add a package to do it. We could make it easier but yeah...

**Comment by jbrooksuk** [comment]
Ping @CachetHQ/owners.

**Comment by joecohens** [comment]
Maybe we can also provide webhooks, so people can listen to events and code external integrations?

**Comment by jbrooksuk** [comment]
Webhooks would be fancy.
