### ISSUE TITLE
Redesign status page components

### ISSUE THREAD

**Issue by jbrooksuk** [CachetHQ/Cachet#1031]
- [x] Header - perhaps an optional setting for a full-width header?
- [x] Footer - it's not quite right, doesn't look right when you have buttons in there etc.
- [ ] Schedule maintenance - we could improve it.

**Comment by jbrooksuk** [comment]
@joecohens want to give this a go?

**Comment by joecohens** [comment]
Sure!

**Comment by SanketDG** [comment]
Hi, I am very new to this project, how can I access the single pages you describe?

**Comment by jbrooksuk** [comment]
If you're using V2 (currently in RC) you can go directly to an incident by clicking on the timestamp next to the title.

**Comment by SanketDG** [comment]
@jbrooksuk Thanks, now I might have got this wrong, but how are those single pages ugly?

**Comment by jbrooksuk** [comment]
> how are those single pages ugly?

I don't find them as polished as I do other parts of Cachet :)

**Comment by jbrooksuk** [comment]
Ping @joecohens on this. We could do with at least a bit of :lipstick:

I don't think we should bother with the subscribing page as this will be removed in favour of the modal.

**Comment by jbrooksuk** [comment]
Closing this. I'm making some tweaks over the weekend anyway.
