### ISSUE TITLE
Language and Date

### ISSUE THREAD

**Issue by Lumiahna** [cachethq/Cachet#1034]
Hi,
I'm having an issue with my status page.
I set the language into French, but the date seems to be display in English ( day and month are in English instead of French) .
I didn't find a file to edit and to translate that,
How can I do that ?
Thx for your awesome project (: .

Conf: Debian 7 / Apache

**Comment by jbrooksuk** [comment]
![image](https://cloud.githubusercontent.com/assets/246103/10485037/5b846a4a-7280-11e5-878c-0e6b69d598c0.png)

Go to your Settings on the dashboard and change the date format.

**Comment by Lumiahna** [comment]
Hi,
I did it 
Set Timezone: Paris
Date Format: l j F Y
Incident Timestamp Format: l j F Y H:i:s
Site language: English
But it seems to be display in English, I mean: day ( monday, tuesday, ...) and months .
Check it on http://status.2fy.eu
thx

**Comment by jbrooksuk** [comment]
Oh I see. Lemme investigate further.

**Comment by jbrooksuk** [comment]
@joecohens looking at this, it'd require rewriting most of the date stuff and make use of `Carbon::setLocale` and also `formatLocalized`... :see_no_evil:

**Comment by joecohens** [comment]
Mmm this is odd. We can't use Carbon set locale because Carbon use the Datetime locale that means people will have to install the langs on their own OS. That's why we are using https://github.com/jenssegers/date package so we won't force people to install langs on their OS. Let me check what's happening here.

**Comment by Lumiahna** [comment]
My vps is in French, and I misstype Site language: , ofc It was French instead of English.
But day/month are in English instead of French ...
