### ISSUE TITLE
Activity Overview

### ISSUE THREAD

**Issue by jbrooksuk** [cachethq/Cachet#1038]
We could add an activity overview, similar to GitHub's contributions display:

![image](https://cloud.githubusercontent.com/assets/246103/10513052/e12ea2b6-733c-11e5-810a-d36777d867f1.png)

**Comment by jbrooksuk** [comment]
Probably put this in the dashboard? I don't see it being useful on the status page, unless anyone has a use-case?

**Comment by TheoBearman** [comment]
Agreed.

**Comment by jbrooksuk** [comment]
Not really sure if this is useful.
