### ISSUE TITLE
Unable to upgrade to 2.0.0-beta2

### ISSUE THREAD

**Issue by clreinki** [cachethq/Cachet#1040]
I'll be straight-up and say I don't know if there is a problem on my machine or with the code.  However, when trying to upgrade my 1.2.0 installation by checking out the 2.0.0-beta2 tag via git, I then run "composer install -o --no-dev" and get the below error:
![2015-10-15 14_04_26-cachet on escesxi01 ccs k12 in us](https://cloud.githubusercontent.com/assets/12813987/10522868/822117aa-7345-11e5-80fe-ccda936ea4e7.png)

**Comment by jbrooksuk** [comment]
Ping @GrahamCampbell.

**Comment by GrahamCampbell** [comment]
Delete the services.json file.

**Comment by clreinki** [comment]
I do not have a services.json file

**Comment by jbrooksuk** [comment]
`rm -rf bootstrap/cache/*`

**Comment by clreinki** [comment]
That did it.  Thank you!
