### ISSUE TITLE
Icons are not all consistent

### ISSUE THREAD

**Issue by jbrooksuk** [cachethq/Cachet#1045]

**Comment by GrahamCampbell** [comment]
lol

**Comment by jbrooksuk** [comment]
:trollface:

**Comment by jbrooksuk** [comment]
<img width="155" alt="chrome" src="https://cloud.githubusercontent.com/assets/246103/10617644/7591997a-7763-11e5-8259-dcf6ab8d3f9f.png">

<img width="458" alt="firefox" src="https://cloud.githubusercontent.com/assets/246103/10617643/75849c16-7763-11e5-991b-a36a73a21816.png">
