### ISSUE TITLE
Allow people to subscribe vs creating subscriber

### ISSUE THREAD

**Issue by ktastrophy** [cachethq/Cachet#1052]
As an admin I can manually create subscribers and a verification email goes out as expected. The verification email however doesn't work unless the "Allow people to sign up to email notifications is checked." This means in order to create subscribers we have to allow anyone who can see the status page to be able to subscribe themselves.

Do we want to cover the case that only admins can create subscribers?

**Comment by mmollick** [comment]
Just tested this, looks like confirmations and unsubscribes are dependent on that option being enabled. Seems like a bug to me, since notifications are able to be sent when the option is disabled. Pretty simple fix gonna send a PR in a minute.

**Comment by jbrooksuk** [comment]
Thanks @mmollick
