### ISSUE TITLE
Button design in footer since #1055

### ISSUE THREAD

**Issue by TheoBearman** [cachethq/Cachet#1056]
Sorry to be really nitpicky but there appears to be an extra space before the words 'Dashboard', 'RSS' and 'Atom' when the links are hovered over.

![xaa](https://cloud.githubusercontent.com/assets/6546590/10716655/d7ae7c68-7b37-11e5-8776-dde6a4e2b5b9.png)

**Comment by GrahamCampbell** [comment]
The extra space is intentional, but we just need to fix the underlining bit, since we of course still want the icons themselves to be clickable.

**Comment by GrahamCampbell** [comment]
Maybe we need to make them buttons again @joecohens, but with the background the same colour as the footer?

**Comment by TheoBearman** [comment]
How necessary is it for the icon itself to be clickable? If not, we can just float the icon to the left with some CSS?

**Comment by GrahamCampbell** [comment]
> How necessary is it for the icon itself to be clickable?

I just think it feels intuitive to have the icon and the text, and the space in between to be clickable, like if it were to be a button. That's why I'm suggesting we actually make it a button. :)

**Comment by TheoBearman** [comment]
Makes sense - we will need a distinguishing icon for RSS and Atom though, although we will obviously have the names associated with the buttons on hover.

**Comment by joecohens** [comment]
Tbh I was tempted to remove the icons :stuck_out_tongue: and I'm thinking making the subscribe button outlined

**Comment by GrahamCampbell** [comment]
That works too. :)

**Comment by jbrooksuk** [comment]
Do it :+1:
