### ISSUE TITLE
Include date of scheduled maintenance in email

### ISSUE THREAD

**Issue by svenmueller** [cachethq/Cachet#1057]
Currently when scheduling a maintenance, the sent email doesn't contain the maintenance date. Would be nice if the subscriber could see the date also in the email itself.

**Comment by joecohens** [comment]
Are we sure about this? I'm looking at the code and we have a scheduled_at https://github.com/cachethq/Cachet/blob/master/resources/views/emails/incidents/maintenance-html.blade.php#L10

**Comment by joecohens** [comment]
Maybe we are missing a text saying `the scheduled maintenance will be at`?

**Comment by svenmueller** [comment]
looks like it was added in a later version: https://github.com/cachethq/Cachet/commit/b68647df8eba8b8450f55a6ebe52e2fdd1027676#diff-daf631c07d2ae386bb01155338fcc1a1

**Comment by GrahamCampbell** [comment]
That commit is included in v2.0.0-beta1, v2.0.0-beta2, v2.0.0-RC1, and future releases.
