### ISSUE TITLE
Upgrading existing installation

### ISSUE THREAD

**Issue by peterlaws** [cachethq/Cachet#1059]
Sorry if this has been brought up before....

I used ``git clone`` initially to install, and as you can not use that on an already existing directory, what is the best way to upgrade to a new/beta version? My artisan has no ``update`` command.

Thanks

**Comment by jbrooksuk** [comment]
Usually:

1. `git pull origin master`
2. `composer install -o --no-dev`
3. `php artisan migrate`
4. `rm -rf ./bootstrap/cache/*`
5. Done :)

**Comment by peterlaws** [comment]
Lucky I ``cp``'d the directory beforehand...

> Generating optimized autoload files
php artisan optimize --force
PHP Fatal error:  Class 'McCool\LaravelAutoPresenter\LaravelAutoPresenterServiceProvider' not found in /var/www/Cachet/vendor/laravel/framework/src/Illuminate/Foundation/ProviderRepository.php on line 146
  [Symfony\Component\Debug\Exception\FatalErrorException]
  Class 'McCool\LaravelAutoPresenter\LaravelAutoPresenterServiceProvider' not found

**Comment by jbrooksuk** [comment]
This is the `bootstrap/cache/*` thing.
