### ISSUE TITLE
Version of existing instance

### ISSUE THREAD

**Issue by srikanth88infy** [cachethq/Cachet#1061]
Is there a way to find out the version number of the currently running Cachet instance?

**Comment by jbrooksuk** [comment]
If you've cloned it from Git, you should be able to do `git log -n1` and see what the commit hash is.

**Comment by srikanth88infy** [comment]
@jbrooksuk Thank you! I'm currently on 1.2.0 and would like to upgrade to the latest. Wondering if there is any documentation I can follow.

**Comment by jbrooksuk** [comment]
We've yet to release V2, the docs will be ready soon.

**Comment by peterlaws** [comment]
Could you add the version in the app itself, obviously within the admin area, near the footer or under the left options?

**Comment by jbrooksuk** [comment]
I've thought about doing that @peterlaws but we don't actually store a version number anywhere yet.

**Comment by jbrooksuk** [comment]
@cachethq/owners any ideas on how we could do this effectively?

**Comment by TheoBearman** [comment]
Any way we could tie this to the GitHub version tags? Just my two cents...

**Comment by jbrooksuk** [comment]
> Any way we could tie this to the GitHub version tags? Just my two cents...

Nope, because someone is guaranteed not to install via Git.

**Comment by TheoBearman** [comment]
Fair.

**Comment by joecohens** [comment]
I think the best option would be to define the version either on a service provider or in a config so we can display it on the admin area.

**Comment by jbrooksuk** [comment]
We'll just have to be sure to update it :laughing:

**Comment by jbrooksuk** [comment]
Defined as a constant?
