### ISSUE TITLE
Incident updates

### ISSUE THREAD

**Issue by mmollick** [cachethq/Cachet#1062]
The #1031 issue got me thinking about the single view for incidents and how Cachet handles updating incidents in general.

Right now the previous updates are just overwritten, I feel like it might be better to keep previous updates to the incidents. We could display the most recent activity on the main feed but display the full incident activity on the single view.

What does everyone else think about this idea?

**Comment by jbrooksuk** [comment]
This is already planned for V3 (if not before).
