### ISSUE TITLE
component is not assigned to incident

### ISSUE THREAD

**Issue by anmai02** [cachethq/Cachet#1063]
- this happens with v2.0.0-RC1 (also with v2.0.0-beta2) -

create a new incident on the UI at dashboard/incidents/add:
 - select a component
 - set a status for the component
 - save incident

-> the incident does not have the component assigned, in the incident table the field component_id has thge value 0.
-> the status of the component itself is updated properly

could temporarily fix it at ReportIncidentCommandHandler.php, line 37:
old: 'component' => $command->component_id,
new: 'component_id' => $command->component_id,

**Comment by jbrooksuk** [comment]
Thanks for this! :)

**Comment by anmai02** [comment]
thanks :-)
