### ISSUE TITLE
Remove config() calls from naughty places

### ISSUE THREAD

**Issue by GrahamCampbell** [cachethq/Cachet#1072]

**Comment by jbrooksuk** [comment]
Rather, inject the config?

**Comment by GrahamCampbell** [comment]
Yes, the actual config values, rather than the config repository though.

Say, you had a class called Mailer, and it always mailed to the same person, and you wanted to load the value from the config, rather than injecting the config repository, just setup a binding so the Mailer object gets constructed with the actual email address passed to it as a parameter.

That way, things really are truely separated. It should also make testing such classes easier if we can ever be arsed to write tests for stuff. :P
