### ISSUE TITLE
Polling for services

### ISSUE THREAD

**Issue by funky-monkey** [cachethq/Cachet#1081]
Hi, 

Is it possible to actually poll for external API or do I just updater manually? What I mean is; can I add a JSON response/link to my API so Cachet checks if it is available via statuscodes? I could not find anything in the documentation about this...

Best, 
Sidney

**Comment by jbrooksuk** [comment]
Not as part of Cachet, but [cachet-monitor](https://github.com/CastawayLabs/cachet-monitor) will.

**Comment by funky-monkey** [comment]
Great stuff! Thanks!

Sidney

**Comment by bolshoy** [comment]
@funky-monkey use an "active" monitoring tool like sensu or collectd
