### ISSUE TITLE
The requested resource could not be found but may be available again in the future

### ISSUE THREAD

**Issue by jsinh** [cachethq/Cachet#1085]
Hello,

I have got a instance of Cachet running on Ubuntu 14.04 / MySQL in Azure Environment recently.

It took me longer than expected to get it up and working with my limited understanding of Linux Environment.

Now it works and i created some demo components, incident and metrics in there. I started building up my code which need to connect with this Cachet API and report things from our health check process for our custom workflow.

When I try to hit any of the API resources (including /ping - data "pong!"), I am getting a common not so helpful error or message as follows:

> {"errors":[{"id":"589b6981-6039-4a2c-a626-b448c7a01b7a","status":404,"title":"Not Found","detail":"The requested resource could not be found but may be available again in the future."}]}

Not sure what is wrong, please help me out here so I can access this instance's Cachet API from my other process. Let me know if you need any other information about the setup of Cachet
Thanks,
Jaspal

**Comment by GrahamCampbell** [comment]
Are you including the version in the uri?

**Comment by jsinh** [comment]
That's a very quick response. I appreciate it.

Yes I have double checked. I am including the version in the URL.
In .NET (that is where I am trying to access the API) we have base address and fragment address.

Base address is set to : http://[domainname]/api/v1
Fragment address is set to: /ping

Site runs on HTTP (not HTTPS)
Any idea?

**Comment by GrahamCampbell** [comment]
https://demo.cachethq.io/api/v1/ping

**Comment by GrahamCampbell** [comment]
What version of cachet do you have? Our demo is using the current master branch.

**Comment by jsinh** [comment]
While setting it up, in git I switched to v1.2.1 so that should be the one currently in use.

**Comment by GrahamCampbell** [comment]
Hmmm, the ping endpoint should still exist on 1.2.1. Are you using cachet under a subfolder? Laravel's known to be a bit dodgie under that situation? Is the website public? Can I try to visit it?

**Comment by jsinh** [comment]
Not sure what you mean by subfolder. It resides at /var/www/Catchet

It runs with simple command as `php -S 0.0.0.0:3234 -t public` and then backed up with Nginx to make public on port 80.

yes offcourse you can access it - its at http://status.agrisync.com

For the sake of search crawling and other concerns - I will edit this reply to remove the actual URL after we resolve this issue, i hope you don't mind.

**Comment by jsinh** [comment]
Do you need token - the one that i use from clicking on "username" > Profile > API Token?

**Comment by GrahamCampbell** [comment]
http://status.agrisync.com/api/v1/ping

**Comment by GrahamCampbell** [comment]
Seems to be working for me?

**Comment by GrahamCampbell** [comment]
Looks like https being broken is due to you missconfiguring CloudFlare.

**Comment by jsinh** [comment]
agreed, when I hit on the browser it works (ping / pong) but does not works when hit from code (.NET using "HttpClient" class).

Should I bypass cloudflare for this subdomain, will that solve the issue?

**Comment by GrahamCampbell** [comment]
Try this config:

![image](https://cloud.githubusercontent.com/assets/2829600/10859228/9c2bb46a-7f53-11e5-8ae1-d1d7e7ca1c42.png)

**Comment by GrahamCampbell** [comment]
> agreed, when I hit on the browser it works (ping / pong) but does not works when hit from code (.NET using "HttpClient" class).

Possible CloudFlare is blocking it because it's a bot. Turn down the security for the subdomain using a page rule. Set it to "low".

**Comment by jsinh** [comment]
from the screen shot you mean to select SSL (with SPDY) to "Flexible" right?

**Comment by GrahamCampbell** [comment]
Also, if it's a new subdomain, it can take CloudFlare upto 24 hours for https to start working if you;re on the free plan. In my experience, it normally takes between 30 mins and 2 hours.

**Comment by jsinh** [comment]
But the site is hosted on HTTP and we are not planning to use HTTPS for this one in near future, is that relevant?

**Comment by GrahamCampbell** [comment]
Set ssl to "off" then. :)

**Comment by GrahamCampbell** [comment]
I'd assume that can be done for a page rule for just that subdomain - I've never tried though.

**Comment by GrahamCampbell** [comment]
Let me know how you get on. I'll be around tomorrow. I'm off for now though.

**Comment by jsinh** [comment]
I have not created any page rules before, will try to see if I can figure that out. Thanks for the help till now. I got some directions so would be great for me to take it further.

**Comment by jsinh** [comment]
Alright, the general rule for SSL (with SPDY) is set to "Flexible" (even tried with off)
and added a page rule to set everything off for a pattern that matches the intended URL tried immediately and also after a few hours, but still no luck.

![2015-10-31_12-25-06](https://cloud.githubusercontent.com/assets/1277539/10862361/d1ee3ce0-7fca-11e5-8021-7fc35da6194b.png)

**Comment by GrahamCampbell** [comment]
You need a `*` on the end otherwise cloudflare only matches the first part, and things like `/foo` arn't mathed.

**Comment by GrahamCampbell** [comment]
Are you sure you're actually hitting the correct url?

**Comment by jsinh** [comment]
Yeah i added * at the end of the above pattern in page rule. Still no change in the result.

**Comment by jsinh** [comment]
Further update,

I replaced the `HttpClient` with a third party library to make API call and it worked. Which is very weird, what would be missing in case of using `HttpClient`.

The problem is `HttpClient` is default, .NET object to do HTTP request / response mean no dependency on third party API or libraries to achieve the same.

Why I want to keep this constraint cause, I am actually building up a .NET library that can be used to call Cachet API and would release it to NuGet.org so everyone in .NET world can use it in case they wish to use Cachet.

**Comment by jsinh** [comment]
Ok got it, that was the HttpClient object playing bad. I had to setup some header values right and it worked.

Thanks again for the quick help and reply to help diagnose the issue. Appreciate it.

**Comment by jbrooksuk** [comment]
> I am actually building up a .NET library that can be used to call Cachet API and would release it to NuGet.org so everyone in .NET world can use it in case they wish to use Cachet.

This is awesome, thank you :)
