### ISSUE TITLE
Docs: Invalid JSON in https://docs.cachethq.io/docs/get-components

### ISSUE THREAD

**Issue by andygrunwald** [cachethq/Cachet#1086]
The example JSON response at https://docs.cachethq.io/docs/get-components is not valid.
At the end of the key meta -> pagination -> links -> previous_page the comma is not valid (because there is no other attribute following.

The json ...
```json
{
    "meta": {
        "pagination": {
            ...
            "links": {
                "next_page": null,
                "previous_page": null,
            }
        }
    },
    "data": [
        {
            "id": 1,
            ...
        }
    ]
}
```

... should be ....
```json
{
    "meta": {
        "pagination": {
            ...
            "links": {
                "next_page": null,
                "previous_page": null
            }
        }
    },
    "data": [
        {
            "id": 1,
            ...
        }
    ]
}
```

See screenthot from http://jsonlint.com/ as well:
<img width="477" alt="screen shot 2015-10-31 at 13 16 20" src="https://cloud.githubusercontent.com/assets/320064/10863563/9c4e786e-7fd1-11e5-9e1a-6fe79f4eb062.png">

PS: Is the documentation available as a Github Repo (ReST, Markdown, LaTeX, whatever)? Or only available at http://readme.io/? Because then i would make a PR for this change, because i don`t want to create a account at readme.io for (only) this.

**Comment by andygrunwald** [comment]
The same applies for https://docs.cachethq.io/docs/get-incidents

**Comment by GrahamCampbell** [comment]
Thanks. :)
