### ISSUE TITLE
Docs: Wrong JSON response in https://docs.cachethq.io/docs/subscribers

### ISSUE THREAD

**Issue by andygrunwald** [cachethq/Cachet#1087]
In https://docs.cachethq.io/docs/subscribers there is a wrong JSON Response for *Result Format*.
The key *data* is an array in the *Result Format* chapter.
But if you use the *Try It Out* section, the response for *data* is only one subscriber (which make sense, because you only can apply one email).
See screenshot below.

Currently the JSON looks like ...
```json
{
    "data": [
        {
            "id": 1,
            "email": "support@alt-three.com",
            "verify_code": "1234567890",
            "verified_at": "2015-07-24 14:42:24",
            "created_at": "2015-07-24 14:42:24",
            "updated_at": "2015-07-24 14:42:24"
        }
    ]
}
```

but it should be

```json
{
    "data": {
        "id": 1,
        "email": "support@alt-three.com",
        "verify_code": "1234567890",
        "verified_at": "2015-07-24 14:42:24",
        "created_at": "2015-07-24 14:42:24",
        "updated_at": "2015-07-24 14:42:24"
    }
}
```

Screenshot:
![screencapture-docs-cachethq-io-docs-subscribers-1446300795227](https://cloud.githubusercontent.com/assets/320064/10864072/f833bf4e-7fe1-11e5-8b9a-953f8be228bd.png)

**Comment by GrahamCampbell** [comment]
Thanks. You you can use the "suggest edits" feature on our docs?

**Comment by andygrunwald** [comment]
@GrahamCampbell For this i need an account at Readme.io. Currently i have none and (until now) i don`t plan do create one.
I would create a PR if this docs are in a git / versionized way (restructured text, markdown, whatever)

**Comment by jbrooksuk** [comment]
Fixed.
