### ISSUE TITLE
Docs: Missing "places" attribute in response in https://docs.cachethq.io/docs/get-metrics

### ISSUE THREAD

**Issue by andygrunwald** [cachethq/Cachet#1088]
If you hit "Try it" in https://docs.cachethq.io/docs/get-metrics you see a "places" attribute in the response.
This "places" attribute is not shown in "Result Format" above.

JSON should be ...
```
{
    "meta": {
        ...
    },
    "data": [
        {
            "id": 1,
            "name": "Coffee",
            "suffix": "Cups",
            "description": "Cups of coffee consumed.",
            "default_value": "0.000",
            "calc_type": 1,
            "display_chart": 1,
            "created_at": "2015-08-01 12:00:00",
            "updated_at": "2015-08-01 12:00:00",
            "places": 2
            "points": []
        }
    ]
}
```

I tried to suggest that edit, but i can`t submit the form.
"An error occured". Without proper reason why.
Further more the page was empty (no content) in the "suggest" edit page.

**Comment by GrahamCampbell** [comment]
Ping @jbrooksuk.

**Comment by jbrooksuk** [comment]
I've just got rid of points from the metrics api.
