### ISSUE TITLE
Docs: /metrics/:id returns points

### ISSUE THREAD

**Issue by andygrunwald** [cachethq/Cachet#1089]
In https://docs.cachethq.io/docs/get-a-metric `/metrics/:id` is described as "Returns a single metric, without points.".

But if you hit "Try it" in the example below you see that "points" are added as well:
A snippet:

```json
...
        "updated_at": "2015-10-31 14:30:02",
        "places": 2,
        "points": [
            {
                "id": 1,
                "metric_id": 1,
                "value": 7,
                "created_at": "2015-10-31 14:30:02",
                "updated_at": "2015-10-31 14:30:02"
            },
...
```

Next to this, the "places" attribute is available as well (see https://github.com/cachethq/Cachet/issues/1088).

**Comment by jbrooksuk** [comment]
I think I may just remove the points again to be honest.

**Comment by jbrooksuk** [comment]
Done!
