### ISSUE TITLE
Update system

### ISSUE THREAD

**Issue by jbrooksuk** [CachetHQ/Cachet#109]
We need some way of updating Cachet from an existing installation. This will keep Heroku users up to date and make it easier for manual installations to stay up to date too.
- [ ] Option to turn off update checking.
- [ ] Only check for updates whilst we've not got an active version to update too already.
- [x] Visual notification that an update is available.
- [x] Use GitHubs releases API to find the latest version.
- [ ] Download the update to `./app/storage/updates`
- [ ] Copy over the new files, which have changed.
- [ ] Run `composer update`
- [ ] Option to allow `dev-master` style updates that will use the `master` branch, with a **big** warning.

**Comment by jbrooksuk** [comment]
I think we should do this before V1, but just before we release. The reason is that we can get get a solid release setup on the go, when we can make use of GitHub releases. The update system can then look for that using the API.

**Comment by jbrooksuk** [comment]
GitHub has just added [two new API methods](http://www.programmableweb.com/news/github-adds-two-new-methods-to-releases-api/elsewhere-web/2015/02/22), which is perfect for this update system.

**Comment by joecohens** [comment]
@jbrooksuk Just in time!

**Comment by jbrooksuk** [comment]
@joecohens I think we'll need to implement this with some test releases on a test project I'd say.

**Comment by jbrooksuk** [comment]
@joecohens I'm tempted to move this feature to V2 as well. At the moment Cachet is quite easy to get updated, plus the architecture changes that we've spoken about for V2 will make this much easier for us. I'll Slack you more of my thoughts.

**Comment by ConnorVG** [comment]
Is someone working on this or does no one mind if I take a crack at it this weekend?

**Comment by jbrooksuk** [comment]
Please be my guest!

Most installations should be done via Git, keep that in mind :)

**Comment by ConnorVG** [comment]
I have a few diff based update ideas for this. I'll mull it over.

**Comment by GrahamCampbell** [comment]
Don't take too much crack. :trollface:

**Comment by jbrooksuk** [comment]
Thinking about it, upgrading Cachet should be:

```
$ cd $cachet_dir
$ git pull
$ git checkout LATEST_TAG
$ composer install --no-dev
$ php artisan app:update
```
