### ISSUE TITLE
Docs: "places" attribute is mandatory in https://docs.cachethq.io/docs/metrics

### ISSUE THREAD

**Issue by andygrunwald** [cachethq/Cachet#1090]
The "Try" form in https://docs.cachethq.io/docs/metrics does not work.
Even per curl request.

The missing information:
The "places" attribute is mandatory.
Just try to create a Metric here: https://demo.cachethq.io/dashboard/metrics/add

If you apply "places" in your request as well, it works.

**Comment by jbrooksuk** [comment]
Hmm, ideally places should default to 2, IMHO.

@cachethq/owners should we have the commands default the values? Or override the requests?

**Comment by joecohens** [comment]
I think we have to either set the default in the model (with a mutator) or in the handler, in that way the commands can still receive the whole payload. Kind of what we do with some dates, what do you think?

**Comment by jbrooksuk** [comment]
Hmm, mutation would be better IMHO, because we're keeping it altogether

**Comment by jbrooksuk** [comment]
@joecohens actually, we should do what we do with the `components.enabled` field and pass it through as a default value to the command, via Binput.

**Comment by joecohens** [comment]
:+1:
