### ISSUE TITLE
New API Client in Go(lang)

### ISSUE THREAD

**Issue by andygrunwald** [cachethq/Cachet#1091]
Hey,

i want to inform you that i wrote a Go(lang) client library for Cachet.
You can find it at https://github.com/andygrunwald/cachet.

I would love to get some feedback (about the docs, readme and so on).

Maybe you want to include this in the Client Libraries table at https://docs.cachethq.io/docs/client-libraries.

Andy

**Comment by andygrunwald** [comment]
I suggested an edit for https://docs.cachethq.io/docs/client-libraries as well.

**Comment by jbrooksuk** [comment]
Merged, thanks! :)
