### ISSUE TITLE
Docs: Provide (minimal) rights for MySQL users to harden the access

### ISSUE THREAD

**Issue by andygrunwald** [cachethq/Cachet#1094]
Cachet is able to run with a MySQL database as backend.
I`d like to "harden" the user rights for every system that i run in production as much as possible.

It would be nice to know what grants a mysql user needs to work with Cachet.
Some questions in my mind:
* Are CREATE / DROP TABLE grants needed (for temporary table creation)?
* Can i use two different users to create the schema and to use cachet in normal operations? (with this the normal operations user can get only SELECT, INSERT, UPDATE grants (for example)

It would be nice if the docs can provide such information.
This would be limit possible attack scenarios.

**Comment by jbrooksuk** [comment]
1. `CREATE`, `ALTER` and `DROP` are needed for migrations to run.
2. You can, but it requires some hacking. I believe that Laravel lets you setup a `read` and `write` connection, but you'd have to do this yourself.

We should add this to the documentation somewhere.

**Comment by jbrooksuk** [comment]
https://docs.cachethq.io/docs/frequently-asked-questions#section-mysql-permissions
