### ISSUE TITLE
"Getting Started with Vagrant / Docker": Dockerfile + Vagrantfile missing

### ISSUE THREAD

**Issue by andygrunwald** [cachethq/Cachet#1097]
I just wanted to try Cachet and chose the Docker / Vagrant way.
This way is suggested in the Readme (https://github.com/cachethq/Cachet#installation-upgrades-and-documentation) and in the docs: https://docs.cachethq.io/docs/get-started-with-vagrant

Sadly i can`t find a Vagrantfile / Dockerfile.
It seems that this was removed in https://github.com/cachethq/Cachet/commit/11d77328dccbcf6a9627aad6bc4636e71087b6ee

Is there an alternative?
What was the reason to remove this?

**Comment by jbrooksuk** [comment]
You need to look over at https://github.com/CachetHQ/Docker

**Comment by jbrooksuk** [comment]
Our docs haven't yet been fully updated for V2 :)

**Comment by andygrunwald** [comment]
@jbrooksuk The Vagrant way was dropped completly? because https://github.com/cachethq/Vagrant seems to be empty

**Comment by jbrooksuk** [comment]
Yeah, Vagrant was only for Homestead I think anyway, @GrahamCampbell?
