### ISSUE TITLE
Route [dashboard] not defined following login

### ISSUE THREAD

**Issue by explody** [cachethq/Cachet#1098]
Using v2.0.0-RC1 running on Cloud Foundry. Minor mods to the configs to support the CF env but otherwise straight from the v2.0.0-RC1 tag.  Cache is set to file, Session and Queue are database.

Install and setup worked ok but upon login, we get the above exception.  This *only* happens on the redirect from /auth/login to /dashboard.   From the exception page, if one manually adds the URI path (/dashboard), it loads fine.  So, it seems that auth/login works fine and just the redirection does not. All other functions appear to work as expected as well.

<img width="1796" alt="screen shot 2015-11-01 at 2 20 32 pm" src="https://cloud.githubusercontent.com/assets/80896/10871758/bb462554-80a4-11e5-9598-39fc611e0795.png">

**Comment by explody** [comment]
Seems to be fixed with this

```php
diff --git a/app/Http/Middleware/RedirectIfAuthenticated.php b/app/Http/Middleware/RedirectIfAuthenticated.php
index 30cafdb..ca69dcc 100644
--- a/app/Http/Middleware/RedirectIfAuthenticated.php
+++ b/app/Http/Middleware/RedirectIfAuthenticated.php
@@ -47,7 +47,7 @@ class RedirectIfAuthenticated
     public function handle($request, Closure $next)
     {
         if ($this->auth->check()) {
-            return new RedirectResponse(route('dashboard'));
+            return new RedirectResponse(route('dashboard.index'));
         }

         return $next($request);
```

**Comment by GrahamCampbell** [comment]
Thanks guys. :)
