### ISSUE TITLE
Add Incident Field does not match up to Binput::get() in processing form.

### ISSUE THREAD

**Issue by tnvw** [cachethq/Cachet#1102]
Stuck on the Dashboard's Add Incident page due to missing 'name' and 'message' despite those fields being filled.

https://github.com/cachethq/Cachet/blob/master/resources/views/dashboard/incidents/add.blade.php#L33
The form fields appear to be in direct conflict with what the receiving script is expecting.
https://github.com/cachethq/Cachet/blob/master/app/Http/Controllers/Dashboard/IncidentController.php#L114

The received information would have name and message contained in the incident Array, making it impossible to pass through to this command.

**Comment by jbrooksuk** [comment]
Thanks for this! :)
