### ISSUE TITLE
Documentation: API for Component groups

### ISSUE THREAD

**Issue by andygrunwald** [cachethq/Cachet#1105]
From the source code i see that it is possible to create component groups by API: https://github.com/cachethq/Cachet/blob/master/app/Http/Controllers/Api/ComponentGroupController.php

I would love to see a documentation about this to be able to update the golang client and make this feature possible.

**Comment by jbrooksuk** [comment]
Done https://docs.cachethq.io/docs/get-componentgroups

**Comment by andygrunwald** [comment]
Thx. Will update the go client library asaps
