### ISSUE TITLE
Documentation: How to setup a development env?

### ISSUE THREAD

**Issue by andygrunwald** [cachethq/Cachet#1106]
I (maybe) want to modify Cachet and apply a PR.
And i was looking war an easy way how to setup a development env.
Sadly i can`t find a guide in the docs.

Can you provide one?

**Comment by jbrooksuk** [comment]
Yeah sure, I'll add this shortly.

**Comment by jbrooksuk** [comment]
I will get around to this @andygrunwald :)

**Comment by jbrooksuk** [comment]
Started this at https://docs.cachethq.io/docs/developing-cachet
