### ISSUE TITLE
Feature: New checkbox to show / hide status of components (like graphs)

### ISSUE THREAD

**Issue by andygrunwald** [cachethq/Cachet#1109]
In the http://URL/dashboard/settings/setup page you can choose if you want to show the graphs at the start page (checkbox `display_graphs`).

I would love to see such a checkbox for the status of the components as well, to be able to hide them.

In my use case i don't use Cachet as an incident system directly. More like a system to visualize events in a infrastructure. For this, i have components of course, but i don`t track the status (operational, etc.) for them.

I may would provide a PR for this (with the help of https://github.com/cachethq/Cachet/issues/1106), if you would accept this?

**Comment by jbrooksuk** [comment]
This is actually already done now :)

**Comment by andygrunwald** [comment]
@jbrooksuk Where?
Can you point me to a commit or to a line of code?

I can`t see something similar like this:
* https://github.com/cachethq/Cachet/blob/master/resources/views/index.blade.php#L14
* https://github.com/cachethq/Cachet/blob/master/resources/views/dashboard/settings/app-setup.blade.php#L69

**Comment by jbrooksuk** [comment]
https://github.com/cachethq/Cachet/commit/c89691cb2c97eb943437c7494d08f7abe5b1fae0

**Comment by andygrunwald** [comment]
Thx
