### ISSUE TITLE
Metric Updates Don't Appear on Homepage

### ISSUE THREAD

**Issue by TehTotalPwnage** [cachethq/Cachet#1113]
I've spent the past few hours writing up a PHP application to update one of the metrics on my website. I've finally gotten it working, and it's returned the data, metric ID, etc. Looking in the MySQL database, the entries are there as well. However, if I go to my homepage, the metric isn't updated, and I have no idea why. Any ideas?

**Comment by jbrooksuk** [comment]
Looks related to #1111

**Comment by jbrooksuk** [comment]
Are you able to send your metric data to me please?

**Comment by TehTotalPwnage** [comment]
Do you mean to the demo? (demo.cachethq.io)

**Comment by TehTotalPwnage** [comment]
Tried making a metric on the demo and then sending it metrics via the API page (https://docs.cachethq.io/docs/post-metric-points). Still didn't work.

**Comment by jbrooksuk** [comment]
What timezone are you specifying?

**Comment by TehTotalPwnage** [comment]
I don't think I ever set a timestamp for the POST requests.

**Comment by jbrooksuk** [comment]
Fixed now :)
