### ISSUE TITLE
API: Apply settings via API

### ISSUE THREAD

**Issue by andygrunwald** [cachethq/Cachet#1114]
Cachet is great. Thanks for this.
Most of the things are able to control by API like Components or Incidents. It would be great to be able to set all kinds of settings (Themes, Description, title, "display graphs", etc) by API as well.

With this a setup of cachet can be fully automated with scripts without using a predefined data set.
This would make updates more smooth and independent from the database structure.

**Comment by jbrooksuk** [comment]
I am unsure about exposing an API to this. Let me think about it.

**Comment by andygrunwald** [comment]
Of course, this should not be public, but with a standard auth (like POST / PUT requests) this should not be a problem. If you think about security reasons this can maybe activated on purpose or something.

**Comment by jbrooksuk** [comment]
After some thought this isn't something I'm comfortable adding. Thanks for the suggestion though!
