### ISSUE TITLE
Mail Function not working in setup 

### ISSUE THREAD

**Issue by userguy** [cachethq/Cachet#1117]
Even after editing .env file and adding the required config the mail function is not working 
I tried with sync also but neither of them is working 

QUEUE DRIVER = sync 
mail_driver=smtp
mail_host=smtp ip address
mail_address=noreply@domain.com
mail_encryption=tls 

When i use database it give me error that expected response is 200 but got 500 5.3.3 unrecognized command 

I can telnet to smtp ip address with port 25

**Comment by userguy** [comment]
Also When i use database and Run a cron job with artisian queue:listen 

I have to error Runtime exception too many arguments and for queue i have error Expected Response code 220 but got code 500 , with message 5.3.3. unrecognized command

**Comment by jbrooksuk** [comment]
You might need to set MAIL_PORT too.

**Comment by jbrooksuk** [comment]
@GrahamCampbell is @userguy missing anything?

**Comment by userguy** [comment]
I have used port 25

**Comment by jbrooksuk** [comment]
Did it work?

**Comment by userguy** [comment]
IT was configured from start ,I forgot to put it here ..

**Comment by jbrooksuk** [comment]
Ah right. I'll have a look.

**Comment by jbrooksuk** [comment]
Who is your email provider?

**Comment by userguy** [comment]
This is exchange mail server ..  The server ip is white listed on relay server and i am. Able. To telnet to smtp server from my cachet server..

**Comment by jbrooksuk** [comment]
I'm unsure. I'm pretty sure it's something Laravel is doing or SMTP isn't properly configured.

**Comment by jbrooksuk** [comment]
Cachet itself doesn't deal with the mail stuff.

**Comment by alexandre-lg** [comment]
Works for me with Exchange 2010:
```
QUEUE_DRIVER=database

MAIL_DRIVER=smtp
MAIL_HOST=mail.adami.local
MAIL_PORT=25
MAIL_USERNAME=null
MAIL_PASSWORD=null
MAIL_ADDRESS=incidents@adami.local
MAIL_NAME="Incidents"
MAIL_ENCRYPTION=null
```

**Comment by alexandre-lg** [comment]
Works for me with Exchange 2010:

```
QUEUE_DRIVER=database

MAIL_DRIVER=smtp
MAIL_HOST=mail.domain.com
MAIL_PORT=25
MAIL_USERNAME=null
MAIL_PASSWORD=null
MAIL_ADDRESS=cachet@domain.com
MAIL_NAME="Cachet"
MAIL_ENCRYPTION=null
```

Test your settings with:
`php artisan queue:listen`
