### ISSUE TITLE
Component gets disabled when updated via API

### ISSUE THREAD

**Issue by L1lle** [cachethq/Cachet#1119]
Hi,

Just updated Cachet to the newest version. Great work.

I update the status of a component via API depending on how many entries are in my queue. That works well so far. After the update, the component gets disabled very time I send a single status value via API.

**Comment by jbrooksuk** [comment]
This is odd since the default value of the `enabled` field is `true`: https://github.com/cachethq/Cachet/blob/master/app/Http/Controllers/Api/ComponentController.php#L76

If you're not specifying the enabled value, then is it already disabled?

**Comment by L1lle** [comment]
The true is missing in the put command.

https://github.com/cachethq/Cachet/blob/master/app/Http/Controllers/Api/ComponentController.php#L117

**Comment by jbrooksuk** [comment]
Good catch, I missed this and will update now. Thanks :beers:

**Comment by L1lle** [comment]
No problem, thanks for the reply.

**Comment by L1lle** [comment]
Just testet your quick fix. This now `enables` components which have been `disabled` before. The default value on `UPDATE` in your controller should be something like `null`. And only change the current component value if it is not null. Something like:

```$value = (!is_null($newValue)) ? $newValue : $oldValue```

I didn't dive too deep into your UpdateCommands, but titles and descriptions are not updated to default values if they are not present in any api call. This would be the expected behaviour to boolean as well.

**Comment by L1lle** [comment]
Same behavior with `Decimal Places` with metrics when updating the metric title only via API. It get's always changed back to `2`.

**Comment by jbrooksuk** [comment]
This should be fixed by #1110 too, right @GrahamCampbell?

**Comment by GrahamCampbell** [comment]
Fixed. :)
