### ISSUE TITLE
Can not update Metric decimal places to zero

### ISSUE THREAD

**Issue by L1lle** [cachethq/Cachet#1122]
I can not change the decimal places to `0` when updating a metric in the dashboard.

If zero is not allowed the input field should start at `min=1`. But it seems to work just fine when setting it to 0 directly in the database.

**Comment by GrahamCampbell** [comment]
Should be fixed by https://github.com/cachethq/Cachet/pull/1110 when we can actually get that stuff to work.

**Comment by GrahamCampbell** [comment]
Fixed. :)
