### ISSUE TITLE
if  QUEUE DRIVER = sync , then after every entry via web page it give not reachable error 

### ISSUE THREAD

**Issue by userguy** [cachethq/Cachet#1126]
Hello Team , 

as per documentation if we change QUEUE DRIVER = sync , then the notification will be processed as it is created . so when i do that and then try to subscribe or create any incident the web page says it is not reachable but if i refresh and check the incident is created and users are getting created .. But this is causing issue .. 
Am i doing something wrong here

**Comment by jbrooksuk** [comment]
The sync driver should never be used, it's more for development. It'll run before every request is made, which is poor.

I advise changing to a different driver.

**Comment by userguy** [comment]
Thanks , so i changed sync just to check if my mail is going ( my issue  #1117 ) . As per documentation ,, But even after changing the queue driver it is not going .. So i will focus on #1117
