### ISSUE TITLE
[Runtime Excecption ] Too many Arguments when crontab runs for mail (SMTP )

### ISSUE THREAD

**Issue by userguy** [cachethq/Cachet#1134]
Hello Please find my SMTP config .. 

MAIL_DRIVER=smtp
MAIL_HOST=SMTPHOSTIPaddress
MAIL_PORT=25
MAIL_USERNAME=null
MAIL_PASSWORD=null
MAIL_ADDRESS=noreply@domain.com
MAIL_NAME=APPNAME
MAIL_ENCRYPTION=tls

crontab -l
* * * * * /usr/bin/php /var/www/Cachet/artisan schedule:run 1 >> /tmp/test.txt  2>&1

This is output from /tmp/test.txt 

  [RuntimeException]
  Too many arguments.

#php artisan queue:listen

  [Swift_TransportException]
  Expected response code 220 but got code "500", with message "500 5.3.3 Unrecognized command

I can see some job in mysql - select * from jobs;

| 27728 | default | {"job":"mailer@handleQueuedMessage","data":{"view":{"html":"emails.subscribers.verify-html","text":"emails.subscribers.verify-text"},"data":{"email":"subscriberemail_id","subject":"Confirm your subscription.","link":"http:\/\/10.130.33.77\/subscribe\/verify\/oD2pog8qMBySphkGWNq28I3Xd7Qsw55pt3hIiu8d7e","app_url":"http:\/\/localhost"},"callback":"C:32:\"SuperClosure\\SerializableClosure\":544:{a:5:{s:4:\"code\";s:121:\"function (\\Illuminate\\Mail\\Message $message) use($mail) {\n    $message->to($mail['email'])->subject($mail['subject']);\n};\";s:7:\"context\";a:1:{s:4:\"mail\";a:4:{s:5:\"email\";s:20:\"subscriberemail_id\";s:7:\"subject\";s:26:\"Confirm your subscription.\";s:4:\"link\";s:79:\"http:\/\/hostipaddress\/subscribe\/verify\/oD2pog8qMBySphkGWNq28I3Xd7Qsw55pt3hIiu8d7e\";s:7:\"app_url\";s:16:\"http:\/\/localhost\";}}s:7:\"binding\";N;s:5:\"scope\";s:81:\"CachetHQ\\Cachet\\Handlers\\Events\\Subscriber\\SendSubscriberVerificationEmailHandler\";s:8:\"isStatic\";b:0;}}"}} |      255 |        0 |        NULL |   1447403740 | 1447403740 |

This is what i get in storage/logs/
#0 /var/www/Cachet/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Transport/AbstractSmtpTransport.php(281): Swift_Transport_
AbstractSmtpTransport->_assertResponseCode('500 5.3.3 Unrec...', Array)
#1 /var/www/Cachet/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Transport/EsmtpTransport.php(243): Swift_Transport_Abstrac
tSmtpTransport->executeCommand('STARTTLS\r\n', Array, Array)
#2 /var/www/Cachet/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Transport/EsmtpTransport.php(286): Swift_Transport_EsmtpTr
ansport->executeCommand('STARTTLS\r\n', Array)
#3 /var/www/Cachet/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Transport/AbstractSmtpTransport.php(118): Swift_Transport_
EsmtpTransport->_doHeloCommand()
#4 /var/www/Cachet/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Mailer.php(79): Swift_Transport_AbstractSmtpTransport->sta
rt()
#5 /var/www/Cachet/vendor/laravel/framework/src/Illuminate/Mail/Mailer.php(395): Swift_Mailer->send(Object(Swift_Message), Arr
ay)
#6 /var/www/Cachet/vendor/laravel/framework/src/Illuminate/Mail/Mailer.php(181): Illuminate\Mail\Mailer->sendSwiftMessage(Obje
ct(Swift_Message))
#7 /var/www/Cachet/vendor/laravel/framework/src/Illuminate/Mail/Mailer.php(286): Illuminate\Mail\Mailer->send(Array, Array, Object(Closure))
#8 /var/www/Cachet/vendor/laravel/framework/src/Illuminate/Queue/Jobs/Job.php(129): Illuminate\Mail\Mailer->handleQueuedMessage(Object(Illuminate\Queue\Jobs\DatabaseJob), Array)
#9 /var/www/Cachet/vendor/laravel/framework/src/Illuminate/Queue/Jobs/DatabaseJob.php(50): Illuminate\Queue\Jobs\Job->resolveAndFire(Array)
#10 /var/www/Cachet/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(208): Illuminate\Queue\Jobs\DatabaseJob->fire()
#11 /var/www/Cachet/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(159): Illuminate\Queue\Worker->process('database', Object(Illuminate\Queue\Jobs\DatabaseJob), 0, 0)
#12 /var/www/Cachet/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(111): Illuminate\Queue\Worker->pop(NULL, NULL, 0, 3, 0)
#13 /var/www/Cachet/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(87): Illuminate\Queue\Worker->runNextJobForDaemon(NULL, NULL, 0, 3, 0)
#14 /var/www/Cachet/vendor/laravel/framework/src/Illuminate/Queue/Console/WorkCommand.php(103): Illuminate\Queue\Worker->daemon(NULL, NULL, 0, 128, 3, 0)
#15 /var/www/Cachet/vendor/laravel/framework/src/Illuminate/Queue/Console/WorkCommand.php(71): Illuminate\Queue\Console\WorkCommand->runWorker(NULL, NULL, 0, 128, true)
#16 [internal function]: Illuminate\Queue\Console\WorkCommand->fire()
#17 /var/www/Cachet/bootstrap/cache/compiled.php(1181): call_user_func_array(Array, Array)

#18 /var/www/Cachet/vendor/laravel/framework/src/Illuminate/Console/Command.php(150): Illuminate\Container\Container->call(Array)
#19 /var/www/Cachet/vendor/symfony/console/Command/Command.php(256): Illuminate\Console\Command->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#20 /var/www/Cachet/vendor/laravel/framework/src/Illuminate/Console/Command.php(136): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#21 /var/www/Cachet/vendor/symfony/console/Application.php(838): Illuminate\Console\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#22 /var/www/Cachet/vendor/symfony/console/Application.php(189): Symfony\Component\Console\Application->doRunCommand(Object(Illuminate\Queue\Console\WorkCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#23 /var/www/Cachet/vendor/symfony/console/Application.php(120): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#24 /var/www/Cachet/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(107): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#25 /var/www/Cachet/artisan(36): Illuminate\Foundation\Console\Kernel->handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#26 {main} {"identification":{"id":"c6a26bb2-1719-4028-aea8-9d750b997d13"}}
[2015-11-13 08:33:44] production.ERROR: exception 'Swift_TransportException' with message 'Expected response code 220 but got :

Does it give some hint .. what is the issue here 

When i telnet to SMTP server from CAChet server i am able to do that .. so

**Comment by jbrooksuk** [comment]
Change the cron job to:

```
* * * * /usr/bin/php /var/www/Cachet/artisan schedule:run >> /tmp/test.txt 2>&1
```
