### ISSUE TITLE
profile-dropdown not responding

### ISSUE THREAD

**Issue by phecho** [cachethq/Cachet#1148]
When I click the username at the top of sidebar in dashboard pages, the profile-dropdown is not responding.

**Comment by jbrooksuk** [comment]
It's working fine on the demo?

**Comment by phecho** [comment]
@jbrooksuk It's not working fine on the demo of https://demo.cachethq.io/dashboard.

I fixed this issue.

**Comment by jbrooksuk** [comment]
Ok I must've had a cache.
