### ISSUE TITLE
Troubleshooting Cachet install

### ISSUE THREAD

**Issue by KeiroD** [cachethq/Cachet#1150]
Hi,

So, I finally managed to get Cachet working consistently on a brand new VPS rather than an existing one... however, I ran into an issue whilst attempting to edit or delete an incident.

Stats:

No idea what Cachet version this is, but I did a git pull from what I assume to be the latest stable release as per Cachet install doc.
OS: Ubuntu 14.4
MySQL: 

```
Welcome to the MariaDB monitor.  Commands end with ; or \g.
Your MariaDB connection id is 193
Server version: 10.1.8-MariaDB-1~trusty-log mariadb.org binary distribution
```
PHP: 
```
root@status:/var/www/Cachet# php5 -v
PHP 5.5.9-1ubuntu4.14 (cli) (built: Oct 28 2015 01:34:46)
Copyright (c) 1997-2014 The PHP Group
Zend Engine v2.5.0, Copyright (c) 1998-2014 Zend Technologies
    with Zend OPcache v7.0.3, Copyright (c) 1999-2014, by Zend Technologies
```
Apache2:

```
root@status:/var/www/Cachet# apache2 -v
Server version: Apache/2.4.7 (Ubuntu)
Server built:   Oct 14 2015 14:20:21
```

See: http://status.eidolonhost.com for test incidents.

Laravel logs snippet:

```
#52 [internal function]: Fideloper\Proxy\TrustProxies->handle(Object(Illuminate\Http\Request), Object(Closure))
#53 /var/www/Cachet/bootstrap/cache/compiled.php(9556): call_user_func_array(Array, Array)
#54 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#55 /var/www/Cachet/bootstrap/cache/compiled.php(9546): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#56 /var/www/Cachet/bootstrap/cache/compiled.php(2251): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#57 /var/www/Cachet/bootstrap/cache/compiled.php(2234): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter(Object(Illuminate\Http\Request))
#58 /var/www/Cachet/public/index.php(54): Illuminate\Foundation\Http\Kernel->handle(Object(Illuminate\Http\Request))
#59 {main} {"identification":{"id":"5edd775c-9907-49a0-a853-c48088c535e3"}}
```

Full log: http://pastebin.com/Ezjc1PF2 because it'd exceed the limit here.

What I've tried:

`php artistan config:cache` -- Works but no dice when trying to edit or delete test incidents.

Attempts to delete a test incident results in a `http://status.eidolonhost.com/dashboard/undefined`

```
What does this mean?

Something went wrong on our servers while we were processing your request. The requested resource could not be found but may be available again in the future. This occurrence has been logged, and a highly trained team of monkeys has been dispatched to deal with your problem. We're really sorry about this, and will work hard to get this resolved as soon as possible.

This error can be identified by 5edd775c-9907-49a0-a853-c48088c535e3. You might want to take a note of this code.

Perhaps you would like to go to our home page?
```

**Comment by GrahamCampbell** [comment]
> Laravel logs snippet:

**Comment by GrahamCampbell** [comment]
> Laravel logs snippet:

Please paste the entire trace. The last few liens isn't any use to use.

**Comment by GrahamCampbell** [comment]
The snippet you pasted is common to every exception. ;)

**Comment by KeiroD** [comment]
@GrahamCampbell 

Apologies for the grouchiness at this early morn, but:

**Full log: http://pastebin.com/Ezjc1PF2 because it'd exceed the limit here.**

Again, apologies, but... I *did* post the full trace. I simply chose to stick it in a Pastebin rather than posting multiple comments full of the log.

**Comment by GrahamCampbell** [comment]
Ah, I see. That's not a bug. You just need set a github key in https://github.com/cachethq/Cachet/blob/master/config/emoji.php, or, just upgrade to the latest version of cachet, where this is "fixed".

**Comment by KeiroD** [comment]
@GrahamCampbell 

Hmm... that's odd, because I set a github token as per the emoji doc.

Which version is fixed?

Also, enabling app debug, I see that it correctly picks up the github token. But if upgrading fixes this issue, I'll go ahead and do that, provided I know which version to upgrade to.

**Comment by KeiroD** [comment]
@GrahamCampbell just wanted to let you know I updated most recent comment with details.
