### ISSUE TITLE
Component Description tab wont re-size

### ISSUE THREAD

**Issue by alexmaccabi** [cachethq/Cachet#1155]
We gave cachet a run, and we use it as a deploy status page.
breaking it by group and components, we use tag for our deploy.
Example tag: "orchnode12_kandy_0.0.209_prp"
![cachet-description](https://cloud.githubusercontent.com/assets/3840250/11277118/c57bd58a-8eed-11e5-9933-99294204dbf0.JPG)

the description pop up wont re-size itself.

**Comment by jbrooksuk** [comment]
Interesting.

**Comment by jbrooksuk** [comment]
Fixed :)
