### ISSUE TITLE
Next button unresponsive on Setup (2.0.0 RC3)

### ISSUE THREAD

**Issue by JonathanBennett** [cachethq/Cachet#1156]
Hey, feeling rather stupid right now...

Currently trying to test 2.0.0 RC3 and unable to click "Next" button on first setup screen to progress to next step... (Screenshot attached albeit not very useful...) No errors in logs, nothing in console (also in screenshot).
![screen shot 2015-11-19 at 23 23 11](https://cloud.githubusercontent.com/assets/61564/11284950/77e8439e-8f15-11e5-8d14-e3ae557b280d.png)

Actions taken to try and resolve: 
Try all browsers (Chrome, Safari, FF)
Install from fresh (same deal)

Details
Ubuntu 14.04 - PHP 5.5.9

**Comment by jbrooksuk** [comment]
@joecohens one for you?

**Comment by phecho** [comment]
@JonathanBennett 

see here : #1143

I have fixed it.

**Comment by joecohens** [comment]
I can confirm this is fixed in master next release will be tagged soon /cc @jbrooksuk
