### ISSUE TITLE
After the success of adding operations, the redirect-routing of the page is confusing

### ISSUE THREAD

**Issue by phecho** [cachethq/Cachet#1158]
For example, when I added to a component successfully, should be redirected to the list of components page, and should not still enter a New component adding pages.

How do you think about this issue?

**Comment by jbrooksuk** [comment]
:+1:

**Comment by wfjsw** [comment]
@phecho Please, upload all your translations to https://translate.cachethq.io , thanks.

**Comment by phecho** [comment]
@wfjsw 
done
