### ISSUE TITLE
error 500 

### ISSUE THREAD

**Issue by philshil** [cachethq/Cachet#1161]
Hello
followed instructions,
running 2.0.0-RC3
error 500
[Fri Nov 20 15:24:10.179541 2015] [php5:error] [pid 20906] [client 10.97.76.151:55905] PHP Fatal error:  Call to undefined function Illuminate\\Cache\\apc_fetch() in /srv/www/Cachet/vendor/laravel/framework/src/Illuminate/Cache/ApcWrapper.php on line 32, referer:
[Fri Nov 20 15:24:10.966173 2015] [php5:error] [pid 20907] [client 10.97.76.151:55927] PHP Fatal error:  Call to undefined function Illuminate\\Cache\\apc_fetch() in /srv/www/Cachet/vendor/laravel/framework/src/Illuminate/Cache/ApcWrapper.php on line 32, referer:
[Fri Nov 20 15:24:11.149439 2015] [php5:error] [pid 20908] [client 10.97.76.151:55928] PHP Fatal error:  Call to undefined function Illuminate\\Cache\\apc_fetch() in /srv/www/Cachet/vendor/laravel/framework/src/Illuminate/Cache/ApcWrapper.php on line 32, referer:

**Comment by GrahamCampbell** [comment]
In order to use the apc cache driver, you MUST install the apc extension on your server.

**Comment by philshil** [comment]
HI @GrahamCampbell 
sorry wasn't until after i posted i noticed that it wasn't installed i thought i had. 
was running on opensuse leap and i can't for some reason install zend for the apc cache

**Comment by GrahamCampbell** [comment]
NB, you need the apc userland cache rather than the opcode cacher.

**Comment by GrahamCampbell** [comment]
Alternatively, just use redis or something.

**Comment by philshil** [comment]
Would I still keep apc in the .env file
