### ISSUE TITLE
Validation/Incident editing failure

### ISSUE THREAD

**Issue by KeiroD** [cachethq/Cachet#1164]
Hi, as per @GrahamCampbell request, I am creating a new issue.

An issue seems to be persisting after installation of Cachet where creating and deleting issues work but editing does not.

Steps to reproduce:

Edit existing incident. Give it a name, a status, in this case, Fixed, visibility to public. The Investigating section label is set to Operational. I give it a time and message to display. As soon as I press Update, it results in a 500 and similar errors to the other closed issues I've created.

The version applicable to this particular issue is

```
git log -n1
commit 72233ff4ac5374fb1fd2ed972b959f1d61ff8b7a
Merge: 1db5dcb 638f5d0
Author: James Brooks <james@alt-three.com>
Date:   Thu Nov 19 17:59:40 2015 +0000

    Merge pull request #1154 from phecho/improve-dashboard

    Add links for both of incidents & subscribers in dashboard default page
```

**Comment by GrahamCampbell** [comment]
Thanks. We'll look into this soon. ;)

**Comment by GrahamCampbell** [comment]
Thanks everyone. ;)
