### ISSUE TITLE
I suggest that we change the title of Cachet in github

### ISSUE THREAD

**Issue by phecho** [cachethq/Cachet#1167]
# Changes

From: An open source status page system, for everyone.

To: An open source status page system **based on the PHP Laravel Framework**, for everyone.

# Why

Users search the both keywords of PHP and Laravel can directly find our project.

**Comment by jbrooksuk** [comment]
It used to be this, but it doesn't matter as much anymore. Cachet is so easily found by people looking for  status page system or a solid Laravel project.

**Comment by GrahamCampbell** [comment]
> To: An open source status page system based on the PHP Laravel Framework, for everyone.

It's not even based on laravel though? It's built with laravel.

**Comment by GrahamCampbell** [comment]
And that fact isn't really massively important tbh.
