### ISSUE TITLE
Mailgun integration

### ISSUE THREAD

**Issue by KeiroD** [cachethq/Cachet#1174]
Hi,

Is it possible to integrate [Mailgun](http://mailgun.org) into Cachet? As far as that goes, I think that all that would be needed is to add the user's API key in place of either the user or password.

It looks like you don't necessarily have to use the API user key... I'll be testing this setup shortly. But it'd be nice to have support for Mailgun, just the same.

**Comment by jbrooksuk** [comment]
You need to set some values in the `.env` file:

```
MAIL_DRIVER=mailgun
MAILGUN_DOMAIN=domain
MAILGUN_SECRET=secret
```

That should be all, but untested.

**Comment by KeiroD** [comment]
Awesome, will test and report back any issues when I get back here to do testing.

**Comment by KeiroD** [comment]
Hmm, okay, I seem to be unable to get the system to send e-mail. I'll enable app debug here shortly to see what's going on. Here's my `.env` as it is currently:

```
MAIL_DRIVER=mailgun
MAILGUN_DOMAIN=status.eidolonhost.com
MAILGUN_SECRET=xxxx
MAIL_HOST=smtp.mailgun.org
MAIL_PORT=587
MAIL_USERNAME=noreply@status.eidolonhost.com
MAIL_PASSWORD=xxxx
MAIL_ADDRESS=null
MAIL_NAME=EidolonHost Status Service
MAIL_ENCRYPTION=tls
```

**Comment by KeiroD** [comment]
Well, it works! Looks like that's the appropriate `.env` setup to run with.

Can we add this to documentation?

**Comment by jbrooksuk** [comment]
Please suggest edits to the docs :)

**Comment by KeiroD** [comment]
@jbrooksuk All done with that. Hopefully it looks good. :P
