### ISSUE TITLE
Team dashboard returns 500 v2.0.0-RC5

### ISSUE THREAD

**Issue by alexmaccabi** [cachethq/Cachet#1175]
Hi, Version v2.0.0-RC5
accessing dashboard ==> team returns 500 error.
Stack trace:
         
    production.ERROR: exception 'InvalidArgumentException' with message 'Route                
    [dashboard.team.invite] not defined.' in /var/www/Cachet/bootstrap/cache/compiled.php:9119
    #0 /var/www/Cachet/vendor/laravel/framework/src/Illuminate/Foundation/helpers.php(593):
    Illuminate\Routing\UrlGenerator->route('dashboard.team....', Array, true, NULL)

**Comment by jbrooksuk** [comment]
Not here. Try running `php artisan cache:clear`.

**Comment by GrahamCampbell** [comment]
Or, indeed the route cache clear command.

**Comment by GrahamCampbell** [comment]
Make sure you ALWAYS run `composer install` after updating. Doing that runs that command for you, and also updates the dependencies to the ones we've locked in for the release.

**Comment by alexmaccabi** [comment]
Hi, I tried to run ;

    composer install --no-dev -o

and I`m getting this error:

    PHP Fatal error:  Class 'Barryvdh\Cors\CorsServiceProvider' not found in /var/www/Cachet/bootstrap/cache/compiled.php on line 6898

I've run 

    composer.phar self-update 

and rerun composer install again with same results, I've checked composer.json and composer.lock file and it seems like Barryvdh is there and the only change is it's version 0.7.2 instead of 0.5.0 
any advice ?

**Comment by GrahamCampbell** [comment]
Looks like you need to manually delete the services.json file.
