### ISSUE TITLE
GET-request with accept type set to "text/*" results in 406

### ISSUE THREAD

**Issue by SydoxX** [cachethq/Cachet#1182]
For example if you request https://demo.cachethq.io/api/v1/ping with `"accept: application/*"` it works fine while with `"accept: text/*"` it returns a 406 although you could still pass the json string as text.
Would be quite useful as the requests made by the online game "Second Life" have the fixed accept-type "text/*".

**Comment by GrahamCampbell** [comment]
This is the expected behaviour. The endpoint does not know how to respond in plain text. We could add a plain text responder though I guess.

**Comment by GrahamCampbell** [comment]
Actually, looking a the code, we could not easily do that.
