### ISSUE TITLE
Show "open" Incidents

### ISSUE THREAD

**Issue by tmankartz** [cachethq/Cachet#1183]
Would be great if we can show only open incidents regardless of the time line.
This will gibe customers a better overview about ongoing service incidents.

**Comment by jbrooksuk** [comment]
> Would be great if we can show only open incidents regardless of the time line.

So only show a certain status?

> This will gibe customers a better overview about ongoing service incidents.

I disagree. As a customer I'd be more interested in what's happened, including resolution.

**Comment by jbrooksuk** [comment]
This will be redundant when we come to do #1176 anyway :)
