### ISSUE TITLE
Merge Docker-Setup into Cachethq again for automated builds

### ISSUE THREAD

**Issue by andygrunwald** [cachethq/Cachet#1186]
Dockerhub supports automated builds.
With this you get on commit and tag push automated builds for every version of Cachet for free and without overhead.

But for this the Docker setup at https://github.com/cachethq/Docker needs to be merged back into this repository.

**Comment by jbrooksuk** [comment]
Ping @djdefi?

**Comment by djdefi** [comment]
Thus is already setup for the cachethq/docker project.

Why would we duplicate that?

**Comment by andygrunwald** [comment]
@djdefi because then the docker containers would be automatically up to date with the latest cachethq version. This is currently not the case. See

* https://hub.docker.com/r/cachethq/docker/tags/
* https://hub.docker.com/r/cachethq/cachet/tags/

With the current version every new cachethq version needs to be pushed manually.
If we modify the Dockerfile to use the current source code version instead of downloading the archive from github (a static version) and include the Dockerfile into this project again, a new docker container tagged with the CachetHQ version will be created automatically by Dockerhub.

**Comment by djdefi** [comment]
@andygrunwald I will need to leave that up to the @cachethq/owners to decide if they want to put a Dockerfile back in the repo.

For now I have updated the `cachethq/docker:latest` to utilize the upstream cachethq/cachet master branch. https://github.com/cachethq/Docker/pull/21

**Comment by GrahamCampbell** [comment]
We don't need to put docker back in here.

**Comment by andygrunwald** [comment]
Hm. Okay.
But take in mind: With this you have to maintain the Docker-builds on your own for every tag.
Or you build your automated solution on your own.
IMHO: Both are bad ideas.

**Comment by GrahamCampbell** [comment]
> With this you have to maintain the Docker-builds on your own for every tag.

I know. That's ok though.
