### ISSUE TITLE
Metrics not shown on the front page

### ISSUE THREAD

**Issue by matteogit** [cachethq/Cachet#1187]
Hi, i'm trying to display metrics, i've created the metric and i'm setting the points using PostMan, if i GET them the result looks nice
```javascript
{
  "data": [
    {
      "id": 1,
      "metric_id": 1,
      "value": 4,
      "created_at": "2015-11-27 21:17:01",
      "updated_at": "2015-11-27 21:17:01"
    },
    {
      "id": 2,
      "metric_id": 1,
      "value": 4,
      "created_at": "2015-11-27 21:17:21",
      "updated_at": "2015-11-27 21:17:21"
    },
    {
      "id": 3,
      "metric_id": 1,
      "value": 4,
      "created_at": "2015-11-27 21:17:24",
      "updated_at": "2015-11-27 21:17:24"
    },
    {
      "id": 4,
      "metric_id": 1,
      "value": 4,
      "created_at": "2015-11-27 21:17:25",
      "updated_at": "2015-11-27 21:17:25"
    },
    {
      "id": 5,
      "metric_id": 1,
      "value": 4,
      "created_at": "2015-11-27 21:17:28",
      "updated_at": "2015-11-27 21:17:28"
    },
    {
      "id": 6,
      "metric_id": 1,
      "value": 4,
      "created_at": "2015-11-27 21:17:31",
      "updated_at": "2015-11-27 21:17:31"
    }
  ]
}
```

but when i go to the front page, i don't see the graphic,even looking in the HTML there is nothing more printed about metrics.
I'm using the lastest version ( 2.0.2 ) inside a custom docker image, and with Postegre as DB.
I already tryied to run the gulp script which instead is a node-elixir one, but didn't help.
Do you need other infos ? thanks !

**Comment by jbrooksuk** [comment]
Have you enabled metrics to display on the homepage?

![image](https://cloud.githubusercontent.com/assets/246103/11448140/4a21bc20-954a-11e5-97ef-c9414048fd87.png)

**Comment by lnxslck** [comment]
I have Display Graphs on status page active, and still i see no metrics graph on the status page. I can create metrics and add metric points, but no graph is displayed.

I'm on v2.3.10

**Comment by jbrooksuk** [comment]
@lnxslck are you allowing metrics to display in the settings above?

**Comment by lnxslck** [comment]
@jbrooksuk  Thanks for your reply.  When i created the metric in the dashboard, i clicked the "Display chart on status page?" option. Is that it?

**Comment by lnxslck** [comment]
@jbrooksuk  I just saw what you meant. We also need to activate option "Display graphs on status page" but when i click it and hit Save, it reverts back to un-ticked.

**Comment by lnxslck** [comment]
I just fixed that by doing 
chmod -R 777 /var/www/Cachet/bootstrap
