### ISSUE TITLE
"Show dashboard button in the footer?" cannot be turned off

### ISSUE THREAD

**Issue by sparanoid** [cachethq/Cachet#1190]
![image](https://cloud.githubusercontent.com/assets/96356/11455851/c108e5ee-96ac-11e5-9e65-3e7ce6698dfc.png)

When unchecked the checkbox and hit Save, the checkbox remained checked.

**Comment by jbrooksuk** [comment]
What version of Cachet are you using?

**Comment by sparanoid** [comment]
@jbrooksuk v2.0.2, this bug also existed when it was v1.2.x on my server.

**Comment by jbrooksuk** [comment]
Fixed in https://github.com/cachethq/Cachet/commit/a35430a4fd2f558e5e9e3b3be85e1d790d1c6e6b
