### ISSUE TITLE
Duplicate subscriber email raises QueryException

### ISSUE THREAD

**Issue by GlennV** [cachethq/Cachet#1201]
From the logs:

`Next exception 'Illuminate\Database\QueryException' with message 'SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry 'email@host.com' for key 'subscribers_email_unique' (SQL: insert into `subscribers` (`email`, `verify_code`, `updated_at`, `created_at`) values (email@host.com, zN7eoLkERS9D4cS8w61lSCJG5az2PQNZXDn94kPLzC, 2015-12-06 17:26:37, 2015-12-06 17:26:37))' in /opt/cachet/Cachet/vendor/laravel/framework/src/Illuminate/Database/Connection.php:651`

**Comment by GrahamCampbell** [comment]
Hmmm. What version of Cachet is this?

**Comment by GrahamCampbell** [comment]
Is this from using our API?

**Comment by GlennV** [comment]
2.0.3, not using API

**Comment by GlennV** [comment]
Demo: status.peepl.be

**Comment by GrahamCampbell** [comment]
Thanks. :)

**Comment by GrahamCampbell** [comment]
Does https://github.com/cachethq/Cachet/pull/1203 resolve your issue?
