### ISSUE TITLE
Stylesheet isn't saved 

### ISSUE THREAD

**Issue by GlennV** [cachethq/Cachet#1202]
When adding a stylesheet and saving, the data isn't saved properly.

Can be reproduced on the cachet demo (https://demo.cachethq.io/dashboard/settings/stylesheet).

**Comment by GrahamCampbell** [comment]
Thanks for reporting.

**Comment by GlennV** [comment]
The data does show up in the `settings` database table, though not in the template and not in the form after submitting.

**Comment by jbrooksuk** [comment]
Closed by https://github.com/cachethq/Cachet/commit/cf19fec
