### ISSUE TITLE
Upgrading from v1.x to v2.x causes error during composer install

### ISSUE THREAD

**Issue by thorerik** [cachethq/Cachet#1213]
I'm attempting to upgrade our Cachet version from v1.2.1 (currently) to v2.0.0/3, during composer install I get the following error:
```
Generating autoload files
> php artisan optimize --force
PHP Fatal error:  Class 'Barryvdh\Cors\CorsServiceProvider' not found in /var/www/Cachet/bootstrap/cache/compiled.php on line 6683



  [Symfony\Component\Debug\Exception\FatalErrorException]
  Class 'Barryvdh\Cors\CorsServiceProvider' not found



Script php artisan optimize --force handling the post-install-cmd event returned with an error



  [RuntimeException]
  Error Output: PHP Fatal error:  Class 'Barryvdh\Cors\CorsServiceProvider' not found in /var/www/Cachet/bootstrap/cache/compiled.php on line 6683
```
I've attempted to do composer update to see if that could get past the error, but unfortunatly that turned out to be a no go.

I've cleared out bootstrap/cache/* to try that, also a no go.

I've reverted it back to v1.2.1 to have a working status page, I have an offline copy that I can test on.

PHP Version: 5.6.16 (FPM)
OS: Fedora 22
Webserver: Nginx 1.8.0

**Comment by GrahamCampbell** [comment]
> I've cleared out bootstrap/cache/* to try that, also a no go.

Well, it seems you didn't.

> Error Output: PHP Fatal error:  Class 'Barryvdh\Cors\CorsServiceProvider' not found in /var/www/Cachet/bootstrap/cache/compiled.php on line 6683

**Comment by thorerik** [comment]
pebcak, I hit n instead of y when rm -rf bootstrap/cache/*
