### ISSUE TITLE
post/incidents requires field component_id ?

### ISSUE THREAD

**Issue by dpina000** [CachetHQ/Cachet#1217]
Using one of the common extensions for cachet v2 to create an incident and update the status of a component it fails unless we specify the component_id, which in the documentation (https://docs.cachethq.io/docs/incidents) is showing as optional.

Example
1) Trying to update my component 1, I run a get/component first and print the results:

    [0] => stdClass Object
                        (
                            [id] => 1
                            [name] => my.main website
                            [description] =>
                            [link] => http://www.my.main
                            [status] => 3
                            [order] => 0
                            [group_id] => 0
                            [enabled] => 1
                            [created_at] => 2015-11-24 14:41:04
                            [updated_at] => 2015-12-10 09:09:31
                            [deleted_at] =>
                            [status_name] => Partial Outage
                        )

All good so far, now I'm going to create an incident with these data:

    $query = array(
                'name' => $incident_prefix . ' ' . $service_name,
                'message' => $service_output,
                'status' => 1,
                'visible' => 1,
                'notify' => $cachet_notify_subscribers,
        );

Notice that this is following documentation (https://docs.cachethq.io/docs/incidents) and uses the required fields [name, message, status, visible]. It fails, and this is the result:

    Array
    (
    [code] => 400
    [body] => stdClass Object
        (
            [errors] => Array
                (
                    [0] => stdClass Object
                        (
                            [id] => 722e9464-ab5f-407b-bdaf-a5f79cbc1935
                            [status] => 400
                            [title] => Bad Request
                            [detail] => The request cannot be fulfilled due to bad syntax.
                            [meta] => stdClass Object
                                (
                                    [details] => Array
                                        (
                                            [0] => The status field is required.
                                        )

                                )

                        )

                )

        )

    )

The error message is also a bit misleading as it says "status field is required" but really what it needs is the component_id. Trying again the post/incidents this time with component_id:

    $query = array(
                'name' => $incident_prefix . ' ' . $service_name,
                'message' => $service_output,
                'status' => 1,
                'visible' => 1,
                'component_status' => 3,
                'notify' => $cachet_notify_subscribers,
        );

Result 200:

    Array
    (
    [code] => 200
    [body] => stdClass Object
        (
            [data] => stdClass Object
                (
                    [name] => my.main website
                    [status] => 1
                    [message] => The service is Critical
                    [visible] => 1
                    [component_id] => 1
                    [updated_at] => 2015-12-10 09:56:34
                    [created_at] => 2015-12-10 09:56:34
                    [id] => 44
                    [human_status] => Investigating
                    [scheduled_at] => 2015-12-10 09:56:34
                )

        )

    )

So should this be the case or is the documentation out of date?

**Comment by AntoineAugusti** [comment]
According to the validation rules, `component_id` is only required if you set `component_status` in your request https://github.com/cachethq/Cachet/blob/master/app/Commands/Incident/ReportIncidentCommand.php#L91-L101

**Comment by GrahamCampbell** [comment]
Ping @jbrooksuk.

**Comment by jbrooksuk** [comment]
Interesting... I'll take a look.

**Comment by jbrooksuk** [comment]
I don't understand... The error states that:

> The **status** field is required.

If it was `component_status` then it would say so.

**Comment by jbrooksuk** [comment]
Further, the tests are passing without ever specifying the `component_status`...

**Comment by GrahamCampbell** [comment]
https://i.starbs.net/zrzL

**Comment by GrahamCampbell** [comment]
What about "status" though?

**Comment by dpina000** [comment]
Does that mean that the error is raised by using the 'component_id' without 'component_status' then? That's what it shows from @GrahamCampbell screenshot.

Will re run this test as my issue explanation doesn't show component_id but that may be a typo.

In that case, the error message really should say "The **component_status** field is required."

**Comment by jbrooksuk** [comment]
@GrahamCampbell the error is here is wrong, but it's caused by Validator? What?

**Comment by jbrooksuk** [comment]
Ah! I know what this is... It's not a bug either.

The issue is that the `Component` has a field called `status` too. Which you're missing from your request. You need to be specifying `component_status`.

https://github.com/CachetHQ/Cachet/pull/1403
