### ISSUE TITLE
Error 500 with metrics

### ISSUE THREAD

**Issue by vogelor** [cachethq/Cachet#1218]
Every time i added a metric i got a 500 error. After searching several hours i got the "problem".
in metrics.blade.php line 96 there is:
tooltipTemplate: $el.data('metric-name') + ": <%= value %> " + $el.data('metric-suffix'),

and <% is handeled by the template engine. so i got a 
production.ERROR: exception 'ErrorException' with message 'Use of undefined constant value - assumed 'value''

after changing the line to:
tooltipTemplate: $el.data('metric-name') + ": <{{ '%' }}= value %> " + $el.data('metric-suffix'),

everything works fine for me, because the templae engine can't find "<%" (because the "%" is echoed by php).

if you need more infos please ask...

**Comment by jbrooksuk** [comment]
We'd accept a pull request for this :+1:

**Comment by vogelor** [comment]
Sorry, i can't do that, because i don't know HOW to do this and i don't have the environment to do this. just change this ONE Line in metrics.blade.php. There is no more to do.

Maybe you can also change the line to
tooltipTemplate: $el.data('metric-name') + ": <" + "%= value %> " + $el.data('metric-suffix'),
but i didn't test this. (The code at the top of the issue is testet and works fine for me)

**Comment by jbrooksuk** [comment]
Fixed.
