### ISSUE TITLE
Cant access public page

### ISSUE THREAD

**Issue by jvwjgames** [cachethq/Cachet#1222]
When ever I access http://tfdatabase.net/Cachet and click on public or server.php it flips out. Need help please.

Let me know what you need.

**Comment by jbrooksuk** [comment]
Please follow the [installation instructions](https://docs.cachethq.io/docs/installing-cachet).

**Comment by jvwjgames** [comment]
I did follow them 10 times but it errors out like that

**Comment by jbrooksuk** [comment]
You shouldn't be accessing Cachet within a sub-directory like that.

**Comment by jvwjgames** [comment]
Can you tell me how to fix it cause when I pull it from git hub it creates that folder and when I access the folder it gets the directory listing

**Comment by jvwjgames** [comment]
OK I think I know I believe my MOD_rewrite is not working cause now my other sites on the same server arn't rewriting.
