### ISSUE TITLE
Still getting errors here is more debug info

### ISSUE THREAD

**Issue by jvwjgames** [cachethq/Cachet#1224]
Here is the error logs and access logs and .htaccess cause I am still having issues installing it oh also here is the configuration vhost: http://hastebin.com/epohomocit.apache

http://hastebin.com/jopudisolu.avrasm

http://hastebin.com/qukedutesa.sm

http://hastebin.com/uxinekaqed.apache

**Comment by GrahamCampbell** [comment]
You need to set the url entry in app.php to get cachet to work in a subfolder.

**Comment by jvwjgames** [comment]
Witch app.php do I change and what line.
