### ISSUE TITLE
Witch app.php do i change

### ISSUE THREAD

**Issue by jvwjgames** [cachethq/Cachet#1225]
Witch app.php do I change and what do I change?

Cause I have to have cachet living in a sub folder there is no way around it.

**Comment by GrahamCampbell** [comment]
https://github.com/cachethq/Cachet/blob/master/config/app.php#L38

**Comment by GrahamCampbell** [comment]
Actually, just set it in your .env though. ;)

**Comment by jvwjgames** [comment]
I changed it but it still is retiring what am I doing wrong

**Comment by GrahamCampbell** [comment]
Did you re-run `php artisan config:cache`?

**Comment by jvwjgames** [comment]
Yes but still errors out

**Comment by jvwjgames** [comment]
Is there anyway I can pm you my ssh creds and you can check

**Comment by GrahamCampbell** [comment]
I'm sorry, but I don't do that sort of thing free of charge. I'm happy to give free advice on software development, but not actually install software on people's machines for them.

**Comment by jvwjgames** [comment]
Email sent
