### ISSUE TITLE
More realtime metric graphs

### ISSUE THREAD

**Issue by stather** [cachethq/Cachet#1227]
How easy would it be to have a last hour metric graph? This would be great for real time monitoring.

**Comment by jbrooksuk** [comment]
Yeah, I don't see why not.

**Comment by stather** [comment]
Brilliant. That was fast work.

Sent from Outlook Mobile




On Thu, Dec 24, 2015 at 7:10 AM -0800, "Graham Campbell" <notifications@github.com> wrote:












Closed #1227 via #1278.
