### ISSUE TITLE
Multiple metrics on the same graph

### ISSUE THREAD

**Issue by stather** [CachetHQ/Cachet#1228]
It would be great to have multiple metrics plotted on the same graph. This would be ideal for comparing say successful transactions to error transactions.

**Comment by jbrooksuk** [comment]
This is a rather bespoke request. Having an option to do this would be cool, but add a lot of complexity. You'd need to explicitly state which graphs to merge into one and then change the chart code itself to accommodate this.

We'll probably look at this for another version.

**Comment by jbrooksuk** [comment]
Sorry @GrahamCampbell we looked at this issue at the same time :laughing:

**Comment by GrahamCampbell** [comment]
This would definitely be cool to have.

**Comment by GrahamCampbell** [comment]
> Sorry @GrahamCampbell we looked at this issue at the same time :laughing:

Ha, no worries. ;)

**Comment by ConnorVG** [comment]
Is this really that difficult? It'd just be a case of having metrics and then having graphs. These two can be separate. You add a graph, tell it what metrics to display then Bob's your uncle. This opens up the gate for alternate / cool graphs like incident graphs etc.

idk

**Comment by jbrooksuk** [comment]
@ConnorVG that seems reasonable.

**Comment by jbrooksuk** [comment]
Thank you for your input on Cachet 2.x. We are shifting our attention and resources to Cachet 3.x and will no longer be supporting the 2.x version. If your feedback or issue is relevant to the 3.x series, we encourage you to engage with the new branch.

For more information on the Cachet rebuild and our plans for 3.x, you can read the announcement [here](https://github.com/CachetHQ/Cachet/discussions/4342).

We appreciate your understanding and look forward to your contributions to the new version.
