### ISSUE TITLE
I want paid install service

### ISSUE THREAD

**Issue by jvwjgames** [cachethq/Cachet#1232]
I sent an email last night and was wondering about paid install service

**Comment by GrahamCampbell** [comment]
Hi, yeh. James replied to you a few hours ago. Did you not get his email?

**Comment by jvwjgames** [comment]
No

**Comment by jvwjgames** [comment]
I looked in my junk mail and inbox witch email did it come from and was it sent to the same email.

**Comment by jbrooksuk** [comment]
`support@alt-three.com` and it was just a reply to your original email.

**Comment by jvwjgames** [comment]
I got the one about James will be assigned was it that one?

**Comment by jbrooksuk** [comment]
It's after that :)

**Comment by jvwjgames** [comment]
Intresting. I checked but there is no mail from you there is from Graham.

**Comment by GrahamCampbell** [comment]
![image](https://cloud.githubusercontent.com/assets/2829600/11842964/cd00031e-a3fe-11e5-9385-de5b177d9f4e.png)

**Comment by jvwjgames** [comment]
OK let's do it where do I send info too

**Comment by GrahamCampbell** [comment]
Just reply to me email. It should go through to James. ;)

**Comment by jvwjgames** [comment]
Replied

**Comment by jvwjgames** [comment]
Replied to your email.

**Comment by jvwjgames** [comment]
I replied to the second email

**Comment by GrahamCampbell** [comment]
No need to keep writing here.
