### ISSUE TITLE
Custom stylesheet is not visible on status page

### ISSUE THREAD

**Issue by msc1978** [cachethq/Cachet#1234]
When we add css through settings/stylesheet/custom Stylesheet it is saved correctly, but it isn't visible on the front status page. We see:
<style type="text/css"></style>
I don't know if that is related.

Regards,
Maarten
(version 2.0.3 with fix #1202 applied)

**Comment by GrahamCampbell** [comment]
Is it working on the current `2.0` branch?

**Comment by msc1978** [comment]
I would need to test that and setup and new env for it..
for test we added a simple
 body {  background-color: yellow !important; }

Anyway for me to test it an the 2.0 brach without creating a new env?

**Comment by jbrooksuk** [comment]
Fixed in the 2.0 branch @GrahamCampbell

**Comment by GrahamCampbell** [comment]
I've not seen you on slack in a while @jbrooksuk?

**Comment by jbrooksuk** [comment]
Weekend away, relaxing, work party and work end of year meeting has kept me rather busy I'm afraid.

I was about to reply to your text when I saw a Slack notification about not texting you :trollface:

**Comment by GrahamCampbell** [comment]
Are you free tonight. There's some very important, and some less-important stuff that needs doing.

**Comment by GrahamCampbell** [comment]
Can't really talk about the very important one on GitHub for reasons that will be immediately apparent, lol.

**Comment by jbrooksuk** [comment]
I'm actually working till half 9 tonight, I'm free tomorrow, or you could email?

**Comment by msc1978** [comment]
Confirming this fixed the issue. Thanks!
