### ISSUE TITLE
Email question

### ISSUE THREAD

**Issue by jvwjgames** [cachethq/Cachet#1235]
I think the support emails are getting delayed cause I just got the email about thanks for getting in touch so if you sent any email after I sent the server info I have not gotten it.

**Comment by GrahamCampbell** [comment]
Hi, they're not delayed. We're just very busy at the moment. Aim to have a response time of under 1 hour, but our maximum acceptable response time is 24 hours, so please only ping us if we don't respond within 24 hours of you emailing us.
