### ISSUE TITLE
Users that subscribe, but have not yet validated already receive notications

### ISSUE THREAD

**Issue by msc1978** [cachethq/Cachet#1237]
Problem situation:
- A user subscribes for mail notification
- He successfully receives the validation email with the link to validate, but he doesn't use it (so he doesn't validate.
- A new incident is reported and notity users checkbox is selected
- The user that has not validated already received the notification. 

In my opinion the notification should only be send to users that have validated. But maybe this is by design?
using tag 2.0.3

**Comment by GrahamCampbell** [comment]
Ping @jbrooksuk
