### ISSUE TITLE
Status changes after next day

### ISSUE THREAD

**Issue by jvwjgames** [cachethq/Cachet#1239]
Thanks again James for helping me. I am noticing a strange problem I put in some statuses and haven't changed then from some of them being down. So they are still down and just today all of the statuses switched back to Operational. Is this a bug?

**Comment by GrahamCampbell** [comment]
Ping @jbrooksuk.

**Comment by jvwjgames** [comment]
Did you want me to send an email to James or no also if you want to see what is happening http://status.tfdatabase.net

**Comment by jbrooksuk** [comment]
The last incident logged has a status of "Watching" - you need to add one marked as Fixed.
