### ISSUE TITLE
Missing directories error for Cachet

### ISSUE THREAD

**Issue by KeiroD** [cachethq/Cachet#1240]
Hi,

I tried to follow the documentation that was provided for upgrading from Laravel 4 in the Cachet docs. That didn't work, so I decided to simply do the update for Cachet via following the Install Cachet docs.

However, that's resulted in the following errors:

```
root@status:/var/www/Cachet# git checkout v2.0.4
Note: checking out 'v2.0.4'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by performing another checkout.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -b with the checkout command again. Example:

  git checkout -b new_branch_name

HEAD is now at 666da01... Released 2.0.4
root@status:/var/www/Cachet# cd ..
root@status:/var/www# cp .env Cachet/
root@status:/var/www# cd Cachet/
root@status:/var/www/Cachet# php artisan migrate
PHP Warning:  require(/var/www/Cachet/bootstrap/../vendor/autoload.php): failed to open stream: No such file or directory in /var/www/Cachet/bootstrap/autoload.php on line 28
PHP Fatal error:  require(): Failed opening required '/var/www/Cachet/bootstrap/../vendor/autoload.php' (include_path='.:/usr/share/php:/usr/share/pear') in /var/www/Cachet/bootstrap/autoload.php on line 28
```

Obviously, the files exist where they should. Except, apparently for that. Looks like you guys forgot to include the `vendor` directory within `bootstrap`?

**Comment by GrahamCampbell** [comment]
Instead of checkout, try `git reset --hard v2.0.4`

**Comment by GrahamCampbell** [comment]
Looks like you forgot to run `composer install --no-dev -o` too.

**Comment by GrahamCampbell** [comment]
> PHP Warning:  require(/var/www/Cachet/bootstrap/../vendor/autoload.php): failed to open stream: No such file or directory in /var/www/Cachet/bootstrap/autoload.php on line 28

That's what that is telling you.

**Comment by KeiroD** [comment]
Ooh, so I did.

That's resulted in the following, which has been tail -f'd:

```
Stack trace:
#0 /var/www/Cachet/vendor/symfony/console/Application.php(186): Symfony\Component\Console\Application->find('config:Cache')
#1 /var/www/Cachet/vendor/symfony/console/Application.php(120): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#2 /var/www/Cachet/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(107): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#3 /var/www/Cachet/artisan(36): Illuminate\Foundation\Console\Kernel->handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#4 {main} {"identification":{"id":"67e7635a-8c67-4f28-9bf1-4c9ebec36401"}}
```

Full logs, are as always, at: https://pastebin.com/FKpypgwy well, apparently I didn't need to pastebin because it was a very short log...

The `config:Cache` was because I fat-fingered shift. So ignore that.

**Comment by GrahamCampbell** [comment]
That entire log is related to your typo, and nothing else.

**Comment by KeiroD** [comment]
... Well, tits on a pig, it seems setting `chmod 777 * /var/www/Cachet/storage` fixes the error 500.

I really should document that for my own idiot self.

I checked `/var/logs/apache2/error.log` which was complaining about not being able to open `laravel` logs and as soon as I do the initial command, it fixes the error 500.

WHY does it keep doing that? :/
