### ISSUE TITLE
Upgrade to Laravel 5.2

### ISSUE THREAD

**Issue by phecho** [cachethq/Cachet#1249]
Who is ready to do this task?

**Comment by joecohens** [comment]
We are not ready because the bus has been removed from Laravel 5.2, we have to discuss how to upgrade. //cc @cachethq/owners

**Comment by jbrooksuk** [comment]
There is always [LaravelCollective/Bus](https://github.com/LaravelCollective/bus).

**Comment by GrahamCampbell** [comment]
I'm going to write my own bus package. That one is shit, and doesn't work properly.

**Comment by GrahamCampbell** [comment]
It relies on the self handling interface, which I deleted in L5.3...

**Comment by jbrooksuk** [comment]
> which I deleted in L5.3...

:laughing:

**Comment by GrahamCampbell** [comment]
I'm going to make an alt three bus package soon. ;)

**Comment by GrahamCampbell** [comment]
That and that fact I don't trust laravel collective not to mess it up, lol.

**Comment by GrahamCampbell** [comment]
https://github.com/laravel/framework/issues/11452

**Comment by GrahamCampbell** [comment]
That issue there might be a blocker for us atm btw.

**Comment by GrahamCampbell** [comment]
I'll get Cachet upgraded to L5.2 btw, at some point soonish. Leave it with me.

**Comment by GrahamCampbell** [comment]
> Who is ready to do this task?

That's a big assumption that we actually do want to upgrade.

**Comment by GrahamCampbell** [comment]
The changes are non-trivial.
