### ISSUE TITLE
One click install on Laravel Forge

### ISSUE THREAD

**Issue by joecohens** [cachethq/Cachet#125]
When ready, talk to Taylor for one click install on Laravel Forge.

**Comment by andretanguy** [comment]
Also checkout http://viaduct.io (by aTechMedia down in Bournemouth)

**Comment by GrahamCampbell** [comment]
@jbrooksuk Have you spoken to him yet? I can have a chat if you like?

**Comment by jbrooksuk** [comment]
I tweeted him but no reply. If you can get in touch that would be great :)

**Comment by GrahamCampbell** [comment]
Good news. He said yeh, it should be doable.

**Comment by GrahamCampbell** [comment]
@jbrooksuk How do we proceed from here? Is cachet ready for this one click deploy on forge just yet, or should we leave it until we've got things stable. I don't think he's going to want to change the onclick install process multiple times.

**Comment by jbrooksuk** [comment]
Let's wait for now, get V1 down. How do we implement with Forge, or is it something we can help him with?

**Comment by GrahamCampbell** [comment]
Don't know.

**Comment by jbrooksuk** [comment]
If we can get some more info for what he needs that'd us.

**Comment by GrahamCampbell** [comment]
He did ask if it was configurable through a gui, and it is, so I think we're pretty much sorted.

**Comment by jbrooksuk** [comment]
Perfect :)

**Comment by joecohens** [comment]
Excellent news! :)

**Comment by foxted** [comment]
:+1:

**Comment by jbrooksuk** [comment]
I've spoken to @taylorotwell and all we need is a **bash script** which automates the deployment. He'll make sure that Node.js installed too, so then we'll be able to get Gulp/Bower on there.

**Comment by kfrankperson** [comment]
:+1: Great news

**Comment by joecohens** [comment]
Excellent!!! It would be nice to sort out the updating system before.

**Comment by jbrooksuk** [comment]
Yeah, #109 needs implementing first.

**Comment by tomschlick** [comment]
FYI, taylor mentioned this in the LaravelDFW livestream as coming soon! https://www.youtube.com/watch?v=XrBoZE_jnSo#t=3670

**Comment by jbrooksuk** [comment]
@Duffleman did a great job of writing up [Installing Cachet with Forge](https://blog.cachethq.io/installing-cachet-with-forge/), I'd suggest reading through this rather than the app for now.
