### ISSUE TITLE
Don't generate code coverage on pull request builds

### ISSUE THREAD

**Issue by GrahamCampbell** [cachethq/Cachet#1261]
It just takes ages, then gets discarded at the end...

**Comment by jbrooksuk** [comment]
This is for Scrutinizer, no?

**Comment by GrahamCampbell** [comment]
Yeh. Our tests are taking like 30 mins to run. This is really slowing down contributions.

**Comment by jbrooksuk** [comment]
You know I hate Scrutinizer so, yeah, do it.

**Comment by GrahamCampbell** [comment]
Scrutinizer doesn't even use it anyway. We have it setup to only analyse the master branch.

**Comment by jbrooksuk** [comment]
Sack it off then :trollface:

**Comment by jbrooksuk** [comment]
(Please tell me you got my Christmas pun)?

**Comment by GrahamCampbell** [comment]
:cake:

**Comment by GrahamCampbell** [comment]
Travis being bull shit.

**Comment by GrahamCampbell** [comment]
Got a solution.

**Comment by jbrooksuk** [comment]
:banana:
