### ISSUE TITLE
Add field on incidents to modify components status

### ISSUE THREAD

**Issue by SamuelMoraesF** [cachethq/Cachet#127]
I reccomend to create an field on incidents to change components status(by component or by tag) and another field to the status to be changed(Performance Issues, Major Outage...) and when the incident are changed as fixed, return the components to the original status

The tag feature are in #126

**Comment by jbrooksuk** [comment]
@SamuelMoraesF I'm going to be doing this, but slightly differently. When you create an incident you'll be able to assign it to a component, when you pick one, you'll get an inline component view where you can then change the status of the component too.

**Comment by jbrooksuk** [comment]
See #301.
