### ISSUE TITLE
Key Generation

### ISSUE THREAD

**Issue by GrahamCampbell** [cachethq/Cachet#1270]
Why are we generating a 42 byte key?

![image](https://cloud.githubusercontent.com/assets/2829600/11978379/1d29814c-a983-11e5-92a0-1b08c212be38.png)

**Comment by jbrooksuk** [comment]
Hmm... I'm unsure. Only needs to be 32?

**Comment by GrahamCampbell** [comment]
Yeh.

**Comment by jbrooksuk** [comment]
I'll fix this.

**Comment by jbrooksuk** [comment]
2.0 branch?

**Comment by GrahamCampbell** [comment]
master

**Comment by GrahamCampbell** [comment]
2.0 is essentially closed. I want to ship 2.1 as soon as we can. Maybe about a week.

**Comment by GrahamCampbell** [comment]
It would be good if we could aim for a minor release every 6 weeks or something.

**Comment by jbrooksuk** [comment]
Ok, no problem.

**Comment by GrahamCampbell** [comment]
I cba with 2.0 because it means more composer shit and merges, lol.

**Comment by jbrooksuk** [comment]
:trollface:

**Comment by GrahamCampbell** [comment]
![image](https://cloud.githubusercontent.com/assets/2829600/11979552/221651e0-a98c-11e5-94e7-e033ce544de3.png)

**Comment by jbrooksuk** [comment]
I've been waiting for this bad boy.
