### ISSUE TITLE
Footer Icons Broken

### ISSUE THREAD

**Issue by TheoBearman** [cachethq/Cachet#1286]
I can't isolate which commit is the culprit but I can confirm it is not a result of the upgrade to Laravel 5.2 in fa23585.

**Comment by GrahamCampbell** [comment]
https://github.com/cachethq/Cachet/commit/36f0f9f2cb4b2302a637ec0ed5e4d1131b7f86db

**Comment by GrahamCampbell** [comment]
Thanks, but these were intentionally removed in 2.0.

**Comment by TheoBearman** [comment]
But it's not supposed to look like this no?

![fdfq](https://cloud.githubusercontent.com/assets/6546590/11996707/d5224008-aa60-11e5-8a83-1815ad6f0e4e.JPG)

**Comment by TheoBearman** [comment]
I literally only just noticed this change and am wondering why we did this.

At least it's not a bug.

**Comment by jbrooksuk** [comment]
Ping @joecohens for reasons :wink:

**Comment by joecohens** [comment]
Sorry for the late response. I just think it looks cleaner, especially when you have the subscribe button.

<img width="951" alt="screen shot 2016-01-07 at 12 15 48 am" src="https://cloud.githubusercontent.com/assets/1803556/12163515/dbe4b344-b4d3-11e5-92f5-bb017fb7d0f5.png">
