### ISSUE TITLE
Missing or incomplete author information from most classes

### ISSUE THREAD

**Issue by GrahamCampbell** [cachethq/Cachet#1287]

**Comment by jbrooksuk** [comment]
Is this the class docblocks?

**Comment by GrahamCampbell** [comment]
Yeh.

**Comment by jbrooksuk** [comment]
Do you want to list all three of us on each class?

**Comment by GrahamCampbell** [comment]
No.

**Comment by GrahamCampbell** [comment]
That's the issue. We need to work out who's actually authored what.

**Comment by jbrooksuk** [comment]
I'm on it.

**Comment by GrahamCampbell** [comment]
A simple git blame won't cut it because files have been moved about. :/

**Comment by jbrooksuk** [comment]
Then we'll have to do it going forward?

**Comment by GrahamCampbell** [comment]
D'no. Maybe we should just delete any existing ones we have?

**Comment by jbrooksuk** [comment]
Just stay without?

**Comment by jbrooksuk** [comment]
We're going to start adding them going forward.
