### ISSUE TITLE
Display a Badge for each Component

### ISSUE THREAD

**Issue by stjohnjohnson** [CachetHQ/Cachet#1313]
Support an endpoint for each component such that you can do things like:

 - ![Operational](https://img.shields.io/badge/Blog-Operational-brightgreen.svg)
 - ![Performance Issues](https://img.shields.io/badge/Website-Performance_Issues-yellow.svg)
 - ![Partial Outage](https://img.shields.io/badge/Documentation-Partial_Outage-orange.svg)
 - ![Major Outage](https://img.shields.io/badge/API-Major_Outage-red.svg)

I'm using http://shields.io/ as the example (which we could use as the implementation). 

I expect we could do something like:
 1. Go to https://demo.cachethq.io/api/components/1/badge
 2. Redirects with 302 Found (or 307 Temporary Redirect, your choice) to shields.io

We could also replace the text on the UI with these badges:
![screen shot 2015-12-28 at 9 44 48 am](https://cloud.githubusercontent.com/assets/622065/12022750/b08df3ec-ad47-11e5-9a3d-0905b04beb46.png)

__Note:__ I would love to contribute this change.  Do you have recommendations for where this should go?  What should the messages be (status/name/etc.)?

**Comment by GrahamCampbell** [comment]
:-1: for adding badges. shields.io should just support us through our api

**Comment by jbrooksuk** [comment]
:-1: from me too. I agree with @GrahamCampbell, they should support us :)

**Comment by stjohnjohnson** [comment]
That's great and all, but you don't have a centralized instance.  So you'll need shields.io to support each locally running instance.  How do you propose to do that?

**Comment by jbrooksuk** [comment]
Pass through a parameter?

**Comment by stjohnjohnson** [comment]
Okay, that would be the first time they have done that.  I'll take a look at their code.

Are all your Cachet instances publicly hosted as well?  For those of us that have internal instances, this won't work. :(

**Comment by jbrooksuk** [comment]
Now I've sat and mulled it over, I'm not 100% opposed to this.

There are some things to think about though...

1. Would it live on the API? I don't know if it should.
2. If it's not on the API, we'd need some component endpoint that could filter down issues to anything linked to that component.
3. Would we provide flat versions too?
4. We could implement it like we have done at StyleCI, which is very lightweight.

Leave it with me.

**Comment by jbrooksuk** [comment]
Btw, StyleCI redirected to Shields IIRC, but it was so slow, so now we just host an SVG and dynamically generate it.

**Comment by GrahamCampbell** [comment]
> so now we just host an SVG and dynamically generate it.

Ish, lol.

**Comment by GrahamCampbell** [comment]
https://github.com/StyleCI/StyleCI/tree/master/resources/assets/svg/shields

**Comment by jbrooksuk** [comment]
Looking at StyleCI again, we'd have to account for translations...

**Comment by GrahamCampbell** [comment]
Nah, we only want English badges.

**Comment by GrahamCampbell** [comment]
Does anyone else actually translate images?

**Comment by GrahamCampbell** [comment]
What do travis do?

**Comment by jbrooksuk** [comment]
I think they're just English?

**Comment by stjohnjohnson** [comment]
They should just be SVGs.  Which is just text.

**Comment by jbrooksuk** [comment]
That's fine, but some words are shorter/longer in other languages.

**Comment by jbrooksuk** [comment]
This is harder than I first thought... Shields.io dynamically sizes the badges based on the service and the status text length. We're not able to easily do that without essentially recreating Shields.io

So I have another idea... We could cache the badge from Shields.io for each component and potential status? Ping @GrahamCampbell?

**Comment by jbrooksuk** [comment]
Moving this to 2.2.0
