### ISSUE TITLE
Switch away from Laravel-Throttle in favour of native laravel implementation

### ISSUE THREAD

**Issue by GrahamCampbell** [CachetHQ/Cachet#1315]
https://github.com/illuminate/cache/blob/5.2/RateLimiter.php

**Comment by GrahamCampbell** [comment]
I'm not planning to deprecate my throttle package any time soon, but who knows in a few year's time.

**Comment by jbrooksuk** [comment]
> but who knows in a few year's time.

Be honest, it'll be deprecated soon :trollface:

**Comment by GrahamCampbell** [comment]
It's the 3rd most popular package in the `graham-campbell` package namespace. I can't really get away with that, lol.
