### ISSUE TITLE
Feature request - Show OK/WARN/FAIL status on component group when not expanded

### ISSUE THREAD

**Issue by wingZero21** [CachetHQ/Cachet#1317]
Hi,

It would be good if on the component group itself once closed it could show whether or not anything in the group is affected.

If one of the members of the component groups is down and all of the groups are not expanded, you would need to expand all of them to find out which service is affected, unless there was a post saying X service was affected.

**Comment by GrahamCampbell** [comment]
So, show the worst status for something inside the group, at the top level?
