### ISSUE TITLE
Consider AWS AMI

### ISSUE THREAD

**Issue by empireruler** [CachetHQ/Cachet#1324]
This technically doesn't belong in the issues section, but it would he amazing if CachetHQ built a AMI on the AWS marketplace, I wouldn't mind paying the $99 for a quick install.

**Comment by GrahamCampbell** [comment]
Ping @jbrooksuk.

**Comment by jbrooksuk** [comment]
This is a great idea! I'll take a look at this probably tonight :+1:

**Comment by jbrooksuk** [comment]
I've no idea how to go about this at the moment, so I could do with spending some more time on it. It'd definitely be a good thing to ship 3.0.0 with this.

:shipit:

**Comment by sawanoboly** [comment]
Hi @jbrooksuk , I'm going to share Cachet 2.1.0 and later on AWS MarketPlace. This is good product!

If you don't mind, could you preview my public AMI ? I've already registered my AMI to AWS.

- Name: Cachet 2.1.0 1455253081 (you can find by query like `Cachet 2.1.0` at ap-northeast-1)
A- MI-ID: ami-4d0a3f27

(※This AMI will be removed after we have released on AWS MarketPlace.)

And, I have a question about setup 2.1.0.
At creating `Administrator account` step, I always saw warning with no message after pushed `complete setup` below.

![setup](https://cloud.githubusercontent.com/assets/272388/13000008/b424e766-d198-11e5-8484-866ff22276b2.jpg)


- Is this a bug?

F.Y.I.

- We are going to line up Cachet at http://amiage.com/apps/.
- My AMI is builded with packer, source is available on public repository by us.
    - https://github.com/Launch-with-1-Click/lw1-cachet

**Comment by jbrooksuk** [comment]
I can do so after the weekend :)

Can you report the `[object Object]` issue separately please?

**Comment by sawanoboly** [comment]
Ah, I've noticed. I have something to worry about the Cachet's license.
It looks like doesn't allow someone provides Cachet such as by AMI at AWS MarketPlace?

**Comment by sawanoboly** [comment]
Yeah, thanks for fix installer. By the way, can we consider about license for release AMI ?

**Comment by jbrooksuk** [comment]
@sawanoboly could you email me at james@alt-three.com please? :)

**Comment by sawanoboly** [comment]
@jbrooksuk I've sent mail in last week. Any updates?

**Comment by jbrooksuk** [comment]
Ah sorry I missed this. I'll get back to you today.

**Comment by jbrooksuk** [comment]
https://www.orionian.com/ launched the other day which is offering free Cachet hosting :)

**Comment by UdoKifferbrehl** [comment]
+1 

By the way, is https://www.orionian.com/ still offering Cachet hosting @jbrooksuk?

**Comment by pmit07** [comment]
Yeah, I noticed that my status page went down a few weeks ago and orionian.com is down. Haven't been able to figure out why.

**Comment by jbrooksuk** [comment]
@UdoKifferbrehl @pmit07 we hadn't heard anything about them shutting down. We're completely unaffiliated from them, but I'll try emailing them.

**Comment by jbrooksuk** [comment]
We provide a [Docker](https://github.com/CachetHQ/Docker) repo. AWS AMI is something we have no experience with or time to allocate to it.

If someone makes one, please do get in touch; james@alt-three.com

**Comment by esam-iw** [comment]
Regarding Orionian’s discontinuation of the short experimental open source app installations, we actually sent a notice prior the shutdown accompanied with the full backup of the installation database. I apologize if the message/file didn’t make it to you pmit07.
