### ISSUE TITLE
About this page - Save issue

### ISSUE THREAD

**Issue by mipapo** [CachetHQ/Cachet#1326]
When I put something in "About this page" like: 

    Test

It's converted to

    <p>Test</p>

That is okay. But if I add something like:

    <p>Test</p>
     a

Everything will be deleted if I save the changes

Maybe related with #1325

**Comment by jbrooksuk** [comment]
Pretty sure that this is because we use Markdown.

**Comment by mipapo** [comment]
But if you use Markdown than it should stay in Markdown there. 
If I add something like and save it 
    ![Images description](Image Url)
it shows up like:
    <img src="" .....>

But in the editor it should stay in Markdown and not in converted html

**Comment by jbrooksuk** [comment]
Ah, I know why this is. I'll get it fixed.
