### ISSUE TITLE
Status summary bar at top doesn't show red for major outage

### ISSUE THREAD

**Issue by GrahamCampbell** [CachetHQ/Cachet#1342]

**Comment by GrahamCampbell** [comment]
Just shows blue.

**Comment by jbrooksuk** [comment]
This is by design. We never show a complete failure message.

**Comment by GrahamCampbell** [comment]
Joe and I both thought it was a bug.

**Comment by GrahamCampbell** [comment]
> This is by design. We never show a complete failure message.

Consider this as a proposal to change that design then. :trollface:

**Comment by jbrooksuk** [comment]
Feature time.

**Comment by GrahamCampbell** [comment]
Maybe show red if 50% or more is marked as major outage?

**Comment by jbrooksuk** [comment]
Or just one, since it'd probably critical?

**Comment by GrahamCampbell** [comment]
Depends if it's a large system, and say there's a major outage in the email system, it's probably not worth marking the entire system as broken.

**Comment by GrahamCampbell** [comment]
Say, if it's a system as large as all of amazon aws for example. :D

**Comment by jbrooksuk** [comment]
This is hard to work out then...

**Comment by GrahamCampbell** [comment]
Not really? Just count the number of major outages and divide by the number of components.

**Comment by GrahamCampbell** [comment]
If greater than 0.5 then show red.
