### ISSUE TITLE
Add some search parameters when performing a GET on /incidents or /components

### ISSUE THREAD

**Issue by alkivi-sas** [CachetHQ/Cachet#1348]
It would be great to be able to get incidents or components using for example, name or url parameters.
Currently, I need to parse all result (i.e. process all paginated results) and then search on it. 
What a waste of CPU ;)

**Comment by blaskovicz** [comment]
I would second this request. Specifically adding the ability for `start_date` and `end_date` parameters for the incidents api (so it's easier to query for issues on a certain date rangee).
