### ISSUE TITLE
Metric order changed?

### ISSUE THREAD

**Issue by GrahamCampbell** [CachetHQ/Cachet#1355]
The metric with id 2 is shown above the one with id 1. This was not the case in 2.0, but is in 2.1

![image](https://cloud.githubusercontent.com/assets/2829600/12187820/0f238c0c-b5a7-11e5-8ed9-b703a13979d8.png)
.

**Comment by jbrooksuk** [comment]
Oh. Hah!

**Comment by jbrooksuk** [comment]
https://github.com/CachetHQ/Cachet/blob/b928c849e958a6fe9808cd5f97e55457e2e54cff/app/Composers/MetricsComposer.php#L50

I don't see how this is happening.

**Comment by GrahamCampbell** [comment]
I think it's just that there's no orderBy.
