### ISSUE TITLE
Most recent metric point broken

### ISSUE THREAD

**Issue by GrahamCampbell** [CachetHQ/Cachet#1356]
The far right point always shows 0 even when it's not...

![image](https://cloud.githubusercontent.com/assets/2829600/12187831/41224130-b5a7-11e5-80ba-b9cedd39af8d.png)

**Comment by jbrooksuk** [comment]
I think that this is because it rounds to the hour, rather than up.

**Comment by jbrooksuk** [comment]
It's not happening here?

![image](https://cloud.githubusercontent.com/assets/246103/12458737/3845958e-bfa3-11e5-8428-2b8d29499d49.png)

**Comment by jbrooksuk** [comment]
Ping @GrahamCampbell on this?

**Comment by jbrooksuk** [comment]
This is for average calculations.

**Comment by GrahamCampbell** [comment]
I think we should remove the "sum"/"average" stuff and keep everything as a sum.

**Comment by jbrooksuk** [comment]
> I think we should remove the "sum"/"average" stuff and keep everything as a sum.

Averages need to stay for metrics such as Response Time.

**Comment by GrahamCampbell** [comment]
We need average "over each metric" rather than "over a time period" then.

**Comment by jbrooksuk** [comment]
How does StatusPage and alike do it then?

**Comment by GrahamCampbell** [comment]
> We need average "over each metric"

Irrespective of what anyone else does.

**Comment by vogelor** [comment]
Just as information: i have a metric "# of pages crawled" and submit the # every 10 minutes. You can't use the sum there ;-)

**Comment by GrahamCampbell** [comment]
Fixed in the most recent changes.
