### ISSUE TITLE
Timezone issues

### ISSUE THREAD

**Issue by Dids** [CachetHQ/Cachet#1357]
I've setup Cachet v2.0.4 to use "Helsinki" as the default timezone (GMT +0200), and my monitoring scripts are also including the "Time-Zone" header with "Europe/Helsinki" as the value, but the charts are still looking like they're missing data to me, when in fact it's just the chart's timezone that's incorrect.

I took this screenshot at 16:58 GMT +2:
![nayttokuva 2016-01-08 kello 16 58 36](https://cloud.githubusercontent.com/assets/3455449/12200724/29862a96-b629-11e5-95bf-e69b31de132b.png)

Am I doing something wrong, or did #1011 not solve the timezone issues?

**Comment by GrahamCampbell** [comment]
Not a timezone issue I think.

**Comment by GrahamCampbell** [comment]
See https://github.com/CachetHQ/Cachet/issues/1356.

**Comment by Dids** [comment]
Hmm. Well, I'm not sure if this helps or not, but if I set the timezone in Cachet to "Select Timezone" and hit Save, which I believe shouldn't be allowed anyway, I get this (doesn't have the issue you linked):
![nayttokuva 2016-01-08 kello 17 59 23](https://cloud.githubusercontent.com/assets/3455449/12202276/b6f199da-b631-11e5-9e8c-243a317ed0e3.png)

**Comment by GrahamCampbell** [comment]
Hmmm, very odd. Ping @jbrooksuk.

**Comment by jbrooksuk** [comment]
Ping @joecohens on this one... `MetricRepository` does make use of the timezone code that we're using elsewhere, so I'm unsure.

**Comment by juliancesar** [comment]
+1

**Comment by juliancesar** [comment]
The date saved in database is correct, but the information in graph appears incorrect! Maybe the query is wrong.

**Comment by jbrooksuk** [comment]
Ok, so the database `created_at` timestamps are spot on? It may be that we're double timezoning stuff then.

**Comment by Dids** [comment]
I should also add that whether I add the "Time-Zone" header to requests or not, it doesn't affect the end result in any way.

**Comment by jbrooksuk** [comment]
Also, what database driver are you guys using?

**Comment by Moncleared** [comment]
Same issue here, I confirmed my timestamps are being put into the DB properly but the graph will not update accordingly with site being set to New York timezone. I set the site settings back to London (such as the demo.cachet) and it appears to work fine.

I'm assuming that as the date is pulled OUT of the db there is no conversion of UTC to Site Settings time zone?

**Comment by jbrooksuk** [comment]
https://github.com/CachetHQ/Cachet/blob/2c26bd739678e1875656ff1270b3d5b3c5816de1/app/Repositories/Metric/MySqlRepository.php#L50

We're definitely fetching metrics with the right timezone info.

**Comment by Moncleared** [comment]
https://github.com/CachetHQ/Cachet/blob/2c26bd739678e1875656ff1270b3d5b3c5816de1/app/Repositories/Metric/MySqlRepository.php#L50

Is this basically taking my timezone (EST) and creating an interval and pulling data out of the DB based on that? If so, all of the data in the DB for me is stored as UTC so I feel like that's why it may be missing the results I'm putting in. 

Is it the expectation that I send a timestamp with EST? (I'd previously been sending no timestamp, so was letting cachet generate it for me which I expected would be current time)

**Comment by imlonghao** [comment]
Hi, I think I have the same issue.

I've setup Cachet v2.0.4 to Asia/Shanghai timezone (GMT +8), I keep sending the metrics point for a long time. But the graph looks wrong.

![2016-02-02 14-20-33](https://cloud.githubusercontent.com/assets/4951333/12741528/24036e88-c9b8-11e5-99c8-cb76db99490f.png)

Now is 14:26 in Asia/Shanghai timezone (GMT +8) and 6:26 in UTC

As the screenshot shown above, the graph shows the data from 02:00 to 06:30 (GMT +8).
But in fact, the data is ranging from 10:00 to 14:30 (GMT +8) / 02:00 to 06:30 (UTC)
Which means that the metrics points didn't transform to my timezone, only the x-axis of graph transformed.

Here are some environment information.

System timezone
```
root@imlonghao:~# cat /etc/timezone 
Asia/Shanghai
```

Notice: I sent metric points without timestamp.
```
MariaDB [status]> select * from metric_points order by -id limit 1;
+-------+-----------+---------+---------------------+---------------------+
| id    | metric_id | value   | created_at          | updated_at          |
+-------+-----------+---------+---------------------+---------------------+
| 34592 |         4 | 243.000 | 2016-02-02 06:31:23 | 2016-02-02 06:31:23 |
+-------+-----------+---------+---------------------+---------------------+
1 row in set (0.03 sec)
  
MariaDB [status]> select now();
+---------------------+
| now()               |
+---------------------+
| 2016-02-02 14:31:27 |
+---------------------+
1 row in set (0.00 sec)
```

```
mysql  Ver 15.1 Distrib 10.0.23-MariaDB, for debian-linux-gnu (x86_64) using readline 5.2
```

Sorry for my poor English...
