### ISSUE TITLE
Issue Sending Mail

### ISSUE THREAD

**Issue by jacoblw** [CachetHQ/Cachet#1362]
Hi,

I'm trying to configure Cachet to use Mailgun- I have the following in `.env`

```
MAIL_DRIVER=mailgun
MAILGUN_DOMAIN=<hidden>
MAILGUN_SECRET=<hidden: API key from Mailgun dashboard>
MAIL_HOST=smtp.mailgun.org
MAIL_PORT=587
MAIL_USERNAME=<hidden>
MAIL_PASSWORD=<hidden>
MAIL_ADDRESS=<hidden>
MAIL_NAME=<hidden>
MAIL_ENCRYPTION=tls
```
I added a subscriber in the dashboard, no mail sent.
I subscribed publicly, no mail sent.

I've tried grepping for the email address used in the directory but no results.

I just tried changing the driver to `'driver' => env('MAIL_DRIVER', 'mailgun'),` in `mail.php`

Any ideas on where to start?

**Comment by GrahamCampbell** [comment]
Did you run `php artisan config:cache` after saving the changes. That is absolutely required otherwise we'll ignore the changes you made.

**Comment by jacoblw** [comment]
Yes, after every change

**Comment by GrahamCampbell** [comment]
What errors are in your logs. What queue diver are you using?

**Comment by jacoblw** [comment]
There seems to be no log files generated for today in `storage/logs/`

```
CACHE_DRIVER=apc
SESSION_DRIVER=apc
QUEUE_DRIVER=database
```

**Comment by GrahamCampbell** [comment]
You can only use the database driver if you setup a queue worker.

**Comment by GrahamCampbell** [comment]
Otherwise, you must use the sync driver.

**Comment by jacoblw** [comment]
OK, so just amend to
```
CACHE_DRIVER=apc
SESSION_DRIVER=apc
QUEUE_DRIVER=sync
```
and then `php artisan config:cache`?

**Comment by GrahamCampbell** [comment]
Yes.

**Comment by GrahamCampbell** [comment]
Note that without a queue worker, any request that would have otherwise queued jobs executes them right there and the user must wait for that to complete before the request is then sent.

**Comment by jacoblw** [comment]
Great, well I've just tested mail and can confirm it's working.

Thanks Graham.
