### ISSUE TITLE
Broken metric y-axis scaling

### ISSUE THREAD

**Issue by GrahamCampbell** [CachetHQ/Cachet#1363]
The y-axis should start at 0, not the min value.

![image](https://cloud.githubusercontent.com/assets/2829600/12273218/8be5131a-b95c-11e5-8b07-5eb56b9d8dd2.png)

**Comment by jbrooksuk** [comment]
I'm unsure what's up here @GrahamCampbell. Is it because the first point in the second chart is not at 0?

**Comment by jbrooksuk** [comment]
Oddly it looks ok here:

![image](https://cloud.githubusercontent.com/assets/246103/12458686/f7847966-bfa2-11e5-8af2-bd841cc2a1ef.png)

**Comment by GrahamCampbell** [comment]
That's because there are zero values there.

**Comment by GrahamCampbell** [comment]
Add more points so everything is much greater than zero.
