### ISSUE TITLE
Error when subscribe using version 2.0.4 (Docker)

### ISSUE THREAD

**Issue by ephillipe** [CachetHQ/Cachet#1364]
Next exception 'Illuminate\Database\QueryException' with message 'SQLSTATE[22003]: Numeric value out of range: 7 ERROR:  smallint out of range (SQL: update "jobs" set "reserved" = 0, "reserved_at" = , "attempts" = attempts + 1 where "queue" = default and "reserved" = 1 and "reserved_at" <= 1452626162)' in /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Connection.php:651
Stack trace:
#0 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Connection.php(611): Illuminate\Database\Connection->runQueryCallback('update "jobs" s...', Array, Object(Closure))
#1 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Connection.php(416): Illuminate\Database\Connection->run('update "jobs" s...', Array, Object(Closure))
#2 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Connection.php(359): Illuminate\Database\Connection->affectingStatement('update "jobs" s...', Array)
#3 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(1816): Illuminate\Database\Connection->update('update "jobs" s...', Array)
#4 /var/www/html/vendor/laravel/framework/src/Illuminate/Queue/DatabaseQueue.php(198): Illuminate\Database\Query\Builder->update(Array)
#5 /var/www/html/vendor/laravel/framework/src/Illuminate/Queue/DatabaseQueue.php(164): Illuminate\Queue\DatabaseQueue->releaseJobsThatHaveBeenReservedTooLong('default')
#6 /var/www/html/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(177): Illuminate\Queue\DatabaseQueue->pop()
#7 /var/www/html/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(151): Illuminate\Queue\Worker->getNextJob(Object(Illuminate\Queue\DatabaseQueue), NULL)
#8 /var/www/html/vendor/laravel/framework/src/Illuminate/Queue/Console/WorkCommand.php(109): Illuminate\Queue\Worker->pop(NULL, NULL, 0, '3', '3')
#9 /var/www/html/vendor/laravel/framework/src/Illuminate/Queue/Console/WorkCommand.php(71): Illuminate\Queue\Console\WorkCommand->runWorker(NULL, NULL, 0, 128, false)
#10 [internal function]: Illuminate\Queue\Console\WorkCommand->fire()
#11 /var/www/html/bootstrap/cache/compiled.php(1187): call_user_func_array(Array, Array)
#12 /var/www/html/vendor/laravel/framework/src/Illuminate/Console/Command.php(150): Illuminate\Container\Container->call(Array)
#13 /var/www/html/vendor/symfony/console/Command/Command.php(256): Illuminate\Console\Command->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#14 /var/www/html/vendor/laravel/framework/src/Illuminate/Console/Command.php(136): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#15 /var/www/html/vendor/symfony/console/Application.php(838): Illuminate\Console\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#16 /var/www/html/vendor/symfony/console/Application.php(189): Symfony\Component\Console\Application->doRunCommand(Object(Illuminate\Queue\Console\WorkCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#17 /var/www/html/vendor/symfony/console/Application.php(120): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#18 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(107): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#19 /var/www/html/artisan(36): Illuminate\Foundation\Console\Kernel->handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#20 {main} {"identification":{"id":"49d9ea85-362e-406c-b2e3-f6354fd34d1b"}}

**Comment by jbrooksuk** [comment]
Can you report this on the [Docker](http://github.com/CachetHQ/Docker) repo please.
