### ISSUE TITLE
Install Error/Bug

### ISSUE THREAD

**Issue by Conciliare** [CachetHQ/Cachet#1365]
I keep getting this error any help?

PHP Parse error:  syntax error, unexpected '[' in /var/www/Cachet-2.0.4/vendor/guzzlehttp/psr7/src/functions.php on line 77

**Comment by SamuelMoraesF** [comment]
what version of PHP your server is running?

**Comment by Conciliare** [comment]
PHP 5.6.17 (cli) (built: Jan  6 2016 18:56:36)
Copyright (c) 1997-2015 The PHP Group
Zend Engine v2.6.0, Copyright (c) 1998-2015 Zend Technologies

**Comment by jbrooksuk** [comment]
That's a vendor package, specifically Guzzle. Can you try running:

```bash
composer self-update
composer clear-cache
rm -rf vendor/
composer install
```

**Comment by Conciliare** [comment]
Thanks for the help, that seemed to fix everything! But I am getting a blank white page when visiting the site with no console, network, or php errors being reported?

**Comment by jbrooksuk** [comment]
Now try running `rm -rf bootstrap/cache/*`.
