### ISSUE TITLE
Passwort-Reset issue

### ISSUE THREAD

**Issue by f0o** [CachetHQ/Cachet#1370]
Hi,

I recently updated from 1.x to 2.0.4. It's been a while and I guess that I forgot the password for the install.
I use SQLite as storage backend and nginx+fpm in the front.

I used `https://docs.cachethq.io/docs/frequently-asked-questions#how-do-i-reset-a-forgotten-password` verbatim but still login doesnt work.

I can see the SQLite being updated but no luck on logging in.

Any pointers on how to retrieve access?

**Comment by jbrooksuk** [comment]
Sorry about this, the docs for this page are out of date.

**Comment by jbrooksuk** [comment]
I'm updating them now.

**Comment by Phoenix09** [comment]
FAQ needs updating again, that doesn't work on 2.4
