### ISSUE TITLE
Metrics Points not showing up

### ISSUE THREAD

**Issue by roycepope** [CachetHQ/Cachet#1371]
I'm having a problem with metrics. I am building my python library that sends metrics to my Cachet page but am unable to see the metrics populating on the front end. I am able to GET /api/v1/metrics/3/points and can see all my points that have been sent through the api. The webpage however is not reflecting them correctly. Any help would be appreciated. I'm using v2.0.4

I am using Postman to debug and am making sure my requests are 200OK
![no_points](https://cloud.githubusercontent.com/assets/3598120/12381300/28bd5dea-bd3c-11e5-87ee-b23808ef31f1.png)
![points](https://cloud.githubusercontent.com/assets/3598120/12381301/28bf2e90-bd3c-11e5-9e09-9e6b405f7505.png)

**Comment by jbrooksuk** [comment]
Are you able to send me your metrics data as an SQL file?

**Comment by roycepope** [comment]
Bear with me, I'm still learning about all this and trying to figure out how REST works.

When you say SQL is that the same as json?

Does this Metrics SQL file live on the Cachet host?

**Comment by jbrooksuk** [comment]
They'll be in the DB :)

**Comment by GrahamCampbell** [comment]
This is a duplicate.

**Comment by GrahamCampbell** [comment]
https://github.com/CachetHQ/Cachet/issues/1354
