### ISSUE TITLE
mail does not get triggered for incident update .

### ISSUE THREAD

**Issue by userguy** [CachetHQ/Cachet#1372]

**Comment by jbrooksuk** [comment]
Have you setup mail correctly?

**Comment by userguy** [comment]
Yes mail work fine , But for query i am asking , Suppose We change incident or mark the incident close it does not trigger the mail again .. Mail is only received when i create the incident for fist time ..

**Comment by GrahamCampbell** [comment]
That is because you're not supposed to edit an incident. You're supposed to create a new one to update the status.

**Comment by GrahamCampbell** [comment]
Editing is only there for if you make a typo and have to fix it.

**Comment by userguy** [comment]
So you are saying i create a incident and the if i have mark it fixed ( closed ) do i need to create a new incident and what about the incident i created earlier.. For that how will its incidents status  change .. 

For Example - i create a incident mark its status as  Performance Issue and now that is displayed on dashboard ( since i have marked viewable by public)  - I assign it to component group and also mark as component group status as outage - and after giving explanation and date i create a incident as soon as i create it all subscribers get a mail alert of the problem and also the central screen where this is displayed that also gets changed .Now the if i have to mark incident as closed or change the status to other status or change the component group to other status the Mail is not triggered. If you say for every change in status i have to create a new incident then the incident status will not change and we should have incident occurred date and incident fixed date time .So it complies in one go

**Comment by jbrooksuk** [comment]
Yeah, unfortunately so at the moment.

We have plans to fix this; https://github.com/CachetHQ/Cachet/issues/1176
