### ISSUE TITLE
Dashboard should be powered by the API

### ISSUE THREAD

**Issue by jbrooksuk** [CachetHQ/Cachet#1375]
For the most part at least. Settings can't be because we don't allow settings to be changed via the API.

**Comment by jbrooksuk** [comment]
@CachetHQ/owners what do we think of making a Vue.js powered dashboard?

**Comment by GrahamCampbell** [comment]
Sounds good.

**Comment by jbrooksuk** [comment]
Almost everything that can be done in the dashboard can be done via the API. There are some odd things like:

- Regenerating the API token
- Managing of users
- Updating settings

But I feel these should stay locked into the Dashboard itself, not exposed via the API.

**Comment by GrahamCampbell** [comment]
That's fine.
