### ISSUE TITLE
Move away from RoumenDamianoff/laravel-feed

### ISSUE THREAD

**Issue by GrahamCampbell** [CachetHQ/Cachet#1376]
I'm not going to say what I actually think of that codebase here, but I assume you can guess. :trollface:

**Comment by jbrooksuk** [comment]
I've been meaning to do this for a while with another project anyway :)

**Comment by GrahamCampbell** [comment]
Maybe we need to make our own alt three package?

**Comment by jbrooksuk** [comment]
Same intention as I had :laughing:

**Comment by jbrooksuk** [comment]
Once we've moved, let's add feed tests.

**Comment by jbrooksuk** [comment]
https://github.com/AltThree/Feeder is the package we're making for this.
