### ISSUE TITLE
Providing stream of updates about a particular incident from one URL

### ISSUE THREAD

**Issue by brianjking** [CachetHQ/Cachet#1379]
![screenshot1-19-1609 59](https://cloud.githubusercontent.com/assets/6786817/12423908/504c6eb6-be93-11e5-82b4-e556b25bb943.png)

* http://domain.com/incident/10
    * Update to incident # 9 
* http://domain.com/incident/9
    * Initial incident posted to Cachet

![screenshot1-19-1610 00](https://cloud.githubusercontent.com/assets/6786817/12423959/8db0093e-be93-11e5-947d-dae9902ef9a2.png)
* Via: [http://demo.staytus.co/issue/59088129-d30d-473b-aab1-70905abd314e](http://demo.staytus.co/issue/59088129-d30d-473b-aab1-70905abd314e)

**Comment by brianjking** [comment]
Is there a way with Cachet to post several updates to a particular incident so that from a single incident URL someone can see the status updates and how it's progressing?

This is the one plus side I have found to Staytus thus far over Cachet. The screenshot above shows the demo of Staytus showing a particular incident and the updates made to it: http://demo.staytus.co/issue/59088129-d30d-473b-aab1-70905abd314e

However, with Cachet I find that I have to make several incidents and subsequently if I link someone to incident # 9 they may not see that it's resolved or being monitored unless they go back to my main Cachet page.

**Comment by GrahamCampbell** [comment]
That would be really useful. :+1:

**Comment by GrahamCampbell** [comment]
> Is there a way with Cachet to post several updates to a particular incident so that from a single incident URL someone can see the status updates and how it's progressing?

No. Updating an incident is only for if you make a typo in it. To post "updates" about it, you create a new incident.

**Comment by brianjking** [comment]
@GrahamCampbell @jbrooksuk Perhaps we'll see this feature added? :+1: :smile: Thanks, keep up the great work!

**Comment by jbrooksuk** [comment]
I'm sure that we had an issue for this previously?

**Comment by jbrooksuk** [comment]
I can't find it, but this is **definitely** in the pipeline for V3.

**Comment by TheoBearman** [comment]
Wasn't this my issue? #715 ?

**Comment by jbrooksuk** [comment]
Ah yes, which I then merged into https://github.com/CachetHQ/Cachet/issues/1176 :)

Closing as a duplicate.
