### ISSUE TITLE
Cachet CORS access headers returning lowercase

### ISSUE THREAD

**Issue by Azerothian** [CachetHQ/Cachet#1391]
Hi,
on latest docker image (2.0.4) - Allow Control headers coming back lower case, is not recognized by IE or Chrome causing AJAX requests not to work;

XMLHttpRequest cannot load https://status.vostronet.com/api/v1/incidents. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://support.vostronet.com:7080' is therefore not allowed access.

CURL Example 
access-control-allow-origin: http://10.20.30.40:7080
access-control-allow-methods: GET, POST, PUT, DELETE
access-control-allow-headers: ORIGIN, ACCEPT, CONTENT-TYPE

**Comment by jbrooksuk** [comment]
This seems to be a bug with the `laravel-cors` package I'm afraid.
