### ISSUE TITLE
Incidents spanning multiple components

### ISSUE THREAD

**Issue by jaxxstorm** [CachetHQ/Cachet#1399]
It would be nice if we could have an incident affect multiple components. For example, we have a component group for datacenters, and list each of our datacenters as a component there.

If we have a network issue which spans multiple datacenters, we'd have to update each DC manually. We've got around this by adding our WAN as a component, but it would be nice to be able to add an incident effecting multiple components.

**Comment by jbrooksuk** [comment]
This is something we're planning for the future :)

**Comment by GrahamCampbell** [comment]
We don't actually "link" a component to an incident though, right? We just change its status separately?

**Comment by jbrooksuk** [comment]
We do store the `component_id` on an incident if it's affected.

Anyway, duplicate of https://github.com/CachetHQ/Cachet/issues/1176
