### ISSUE TITLE
Support for Component Groups within Component Groups

### ISSUE THREAD

**Issue by Moncleared** [CachetHQ/Cachet#1427]
For larger systems, it would be nice to have groups within groups such that you can drill down to a finer detail. [Nested Groups]

**Comment by jbrooksuk** [comment]
The implementation of this wouldn't be too difficult. We'd definitely accept a PR for this :)

**Comment by jbrooksuk** [comment]
For the majority of cases, Component Groups are enough by themselves. This isn't something that we will be implementing, but we'd accept from a third-party.
