### ISSUE TITLE
Cachet RSS Feeds in Slack

### ISSUE THREAD

**Issue by brianjking** [CachetHQ/Cachet#1428]
When attempting to use the Slack RSS Feed module for the Cachet RSS Feed I'm receiving the error

`Sorry, 'http://monitor.dockdogs.com/rss' doesn't look like a feed url. Try again?`

Any tips?

Thanks!

**Comment by jbrooksuk** [comment]
Odd... Can you give the demo URL a go? https://demo.cachethq.io/rss

**Comment by jbrooksuk** [comment]
I was able to add the demo to our Slack integrations:

![image](https://cloud.githubusercontent.com/assets/246103/12720776/3d3d78ae-c8f4-11e5-8912-f1001bc4dd01.png)

**Comment by brianjking** [comment]
I can add the demo as well. I'm using Cachet 2.0.4, which I believe is the newest release.

**Comment by GrahamCampbell** [comment]
The demo is running 2.1.0-RC1.

**Comment by jbrooksuk** [comment]
Must be something we've changed since 2.0? https://github.com/CachetHQ/Cachet/compare/2.0...v2.1.0-RC1

**Comment by brianjking** [comment]
I did notice this issue: http://feedvalidator.org/check.cgi?url=http%3A%2F%2Fmonitor.dockdogs.com%2Frss

**Comment by jbrooksuk** [comment]
Ah I do remember fixing the RSS & Atom feeds a little.

**Comment by brianjking** [comment]
Upgrading to `2.1.0-RC1` seems to fix it. Thanks!
