### ISSUE TITLE
Updating Incident status via API doesn't work.

### ISSUE THREAD

**Issue by jsandova** [CachetHQ/Cachet#1435]
curl -X PUT -H "Content-Type: application/json" -H "X-Cachet-Token: ********" http://status.corp.aofl.com/api/v1/incidents/28 -d '{"id":"28" "name":"JIRA","message":"Fixed","status":"4","visible":"1","notify": "true"}'

{"data":{"id":"28","component_id":"3","name":"JIRA","status":"1","visible":1,"message":"Broken","scheduled_at":"2016-02-01 16:52:14","created_at":"2016-02-01 16:52:14","updated_at":"2016-02-01 16:52:14","deleted_at":null,"human_status":"Investigating"}}

I am able to create the incidents via the API but not update the status.

**Comment by GrahamCampbell** [comment]
Is it not component_status?

**Comment by GrahamCampbell** [comment]
Maybe not, lol.

**Comment by GrahamCampbell** [comment]
Ping @jbrooksuk.

**Comment by jbrooksuk** [comment]
This worked fine for me:

```
curl -X PUT -H "Content-Type: application/json" -H "X-Cachet-Token: 9yMHsdioQosnyVK4iCVR" http://cachet.dev/api/v1/incidents/1 -d '{"id": 1, "name":"JIRA","message":"Fixed","status":"3","visible":"1","notify": "true"}'
{"data":{"id":1,"component_id":0,"name":"JIRA","status":"3","visible":1,"message":"Fixed","scheduled_at":"2016-02-02 09:07:31","created_at":"2016-01-29 15:48:28","updated_at":"2016-02-02 09:07:31","deleted_at":null,"human_status":"Watching"}}
```

**Comment by GrahamCampbell** [comment]
@jsandova What cachet version please?

**Comment by jsandova** [comment]
@GrahamCampbell I installed it about a week ago so whatever version was running on github.com/castawaylabs/cachet-monitor. How can I tell the version I am running?

**Comment by GrahamCampbell** [comment]
The version of cachet (totally unrelated to that project) can be found in the settings on the dashboard.

**Comment by jsandova** [comment]
Whoops, I pasted the wrong url earlier. I don't see anything under the settings tab that shows a version of cachet. However I was able to look at my command history and I installed version 2.0.4.

13  git clone https://github.com/cachethq/Cachet.git
   14  cd Cachet
   15  git tag -l
   16  git checkout v2.0.4

**Comment by jsandova** [comment]
I maybe going crazy, or working past my bed time is getting to me. It seems to work now when I run this command.
curl -X PUT -H "Content-Type: application/json" -H "X-Cachet-Token: ****" http://status.corp.aofl.com/api/v1/incidents/30 -d '{"id": 30, "name":"JIRA","message":"Fixed","status":"4","visible":"1","notify": "true"}'

**Comment by jbrooksuk** [comment]
:+1:

**Comment by jbrooksuk** [comment]
Glad it's sorted!
