### ISSUE TITLE
PDOException SQLSTATE[HY000] [2002] No such file or directory

### ISSUE THREAD

**Issue by MayhemLV** [CachetHQ/Cachet#1439]
Whenever I tried to install Cachet and run the migrations with "php artisan migrate" it would generate this error:

production.ERROR: exception 'PDOException' with message 'SQLSTATE[HY000] [2002] No such file or directory' in vendor/laravel/framework/src/Illuminate/Database/Connectors/Connector.php:55

Turns out the problem was because I'm using a socket to connect to MySQL. The example .env file uses "localhost" which will cause the MySQL client to try a socket in the standard directory. Because I'm not using the standard directories it wasn't able to connect. By changing the .env to use "127.0.0.1" instead of "localhost" the client now uses TCP to connect to the socket and I was able to run the migrations and finish the install.

I couldn't find anything relating to this in the install guide and I wasn't sure where else to put this so it's here. Thank you for a great product.

**Comment by jbrooksuk** [comment]
Hey, thanks for debugging this and letting us know! We'd love for you to suggest some edits to the documentation?
