### ISSUE TITLE
Stop using facades in bad places

### ISSUE THREAD

**Issue by GrahamCampbell** [CachetHQ/Cachet#1440]
It's particularly naughty to be using facades outside of controllers and views, in places where DI is happening, and then randomly a facade just appears, lol

**Comment by jbrooksuk** [comment]
So... `CurrentUserComposer` for example?

**Comment by GrahamCampbell** [comment]
Oh, nah, they're ok too, I was thinking like metrics and repositories.

**Comment by GrahamCampbell** [comment]
Also, hacks like this need to stop:

![image](https://cloud.githubusercontent.com/assets/2829600/12763127/b3be70ae-c9ea-11e5-8f0e-55d76779abd8.png)

Infact, I'd go as far to say we should never be interfacing with even the dates libraries like that. I'm going to move stuff over to our date factory.

**Comment by jbrooksuk** [comment]
I think that this is more or less done, we'll just remove them as we go.
