### ISSUE TITLE
Broken twig bridge config

### ISSUE THREAD

**Issue by GrahamCampbell** [CachetHQ/Cachet#1445]
![image](https://cloud.githubusercontent.com/assets/2829600/12763834/83ec8c68-c9ee-11e5-811f-503ce992809f.png)

That debug config clearly won't work. You can't read the config before it's been filled.

**Comment by jbrooksuk** [comment]
Needs to be `env`.

**Comment by GrahamCampbell** [comment]
Or just `false`. Why do we even need to use that stuff?

**Comment by jbrooksuk** [comment]
True.

**Comment by joecohens** [comment]
:+1:
