### ISSUE TITLE
Sub-urls for groups

### ISSUE THREAD

**Issue by bashou** [CachetHQ/Cachet#1451]
Hi guys,

I'm experiencing some troubles when you have a lot of components and groups.
When you have these visual issues, you have two options : 
- setup multiple cachethq instances.
- open an issue to ask for an url improvement.

I think it will be a good idea to request /groups/blabla or /groups/123 (to be restful).
It displays only the selected group with his incidents/maintenances/status.

No ?

**Comment by johnmac77** [comment]
would like this too, can we pay for this extra feature.

**Comment by jbrooksuk** [comment]
Hey @johnmac77 yes, you can donate towards this feature if you'd like.

**Comment by johnmac77** [comment]
H James, as per emails, I will if we have an eta / demo on this (as per my emails).

**Comment by GrahamCampbell** [comment]
Ping @jbrooksuk.

**Comment by jbrooksuk** [comment]
I'm moving this to the v2.5.0 release, although it may get pushed back again. I'll be refactoring large portions to add the ability to setup multiple pages, so it makes sense to build this in.

**Comment by fbatschi** [comment]
is it still planned to merge this feature into 2.4?

**Comment by jbrooksuk** [comment]
Thank you for your input on Cachet 2.x. We are shifting our attention and resources to Cachet 3.x and will no longer be supporting the 2.x version. If your feedback or issue is relevant to the 3.x series, we encourage you to engage with the new branch.

For more information on the Cachet rebuild and our plans for 3.x, you can read the announcement [here](https://github.com/CachetHQ/Cachet/discussions/4342).

We appreciate your understanding and look forward to your contributions to the new version.
