### ISSUE TITLE
Missing argument 1 for Illuminate\Support\Manager::createDriver()

### ISSUE THREAD

**Issue by jneureuther** [CachetHQ/Cachet#1452]
I get the following error when adding a new incident:

```
production.ERROR: exception 'ErrorException' with message 'Missing argument 1 for Illuminate\Support\Manager::createDriver(), called in /var/www/virtual/rnet/cachet/bootstrap/cache/compiled.php on li
ne 12040 and defined' in /var/www/virtual/rnet/cachet/bootstrap/cache/compiled.php:12034
```

Relevant lines in /var/www/virtual/rnet/cachet/bootstrap/cache/compiled.php:

```php
protected function createDriver($driver)
{
    $method = 'create' . ucfirst($driver) . 'Driver';
    if (isset($this->customCreators[$driver])) {
        return $this->callCustomCreator($driver);
    } elseif (method_exists($this, $method)) {
        return $this->{$method}();
    }
    throw new InvalidArgumentException("Driver [{$driver}] not supported.");
}
```
The error results in an error 500 page, but the incident gets created and is editable/removable as normal.

**Comment by jbrooksuk** [comment]
Try running `rm -rf bootstrap/cache/*`

What version of Cachet are you on? Have you ran `composer install` too?

**Comment by GrahamCampbell** [comment]
@jbrooksuk Looks like cachet 1.x to me because of the concat with spaces there. Laravel 5.1+ doesn't concat with spaces.

**Comment by jbrooksuk** [comment]
Good call @GrahamCampbell.

**Comment by jneureuther** [comment]
@GrahamCampbell I'm on the latest release (2.0.4).
@jbrooksuk I strictly followed the install documentation (https://docs.cachethq.io/docs/installing-cachet) and didn't change anything after the installation.
Running `rm -rf bootstrap/cache/*` doesn't solve the issue in my case.

**Comment by GrahamCampbell** [comment]
Looks like you haven't run composer install since before you updated to 2.0.4.

**Comment by jneureuther** [comment]
I did not update, this error appears on a fresh install from git.
I executed `composer install --no-dev -o` as described in install docs.

**Comment by GrahamCampbell** [comment]
Do you have a `.env` file. NB **not** `.env.example`.

**Comment by GrahamCampbell** [comment]
Is `v2.1.0-RC2` working? We plan to ship the final 2.1.0 this weekend.

**Comment by jneureuther** [comment]
After clearing the bootstrap cache i can now localize the error exactly in source.
Relevant code is in vendor/laravel/framework/src/Illuminate/Support/Manager.php:
```php
    /**
     * Create a new driver instance.
     *
     * @param  string  $driver
     * @return mixed
     *
     * @throws \InvalidArgumentException
     */
    protected function createDriver($driver)
    {
        $method = 'create'.ucfirst($driver).'Driver';

        // We'll check to see if a creator method exists for the given driver. If not we
        // will check for a custom driver creator, which allows developers to create
        // drivers using their own customized driver creator Closure to create it.
        if (isset($this->customCreators[$driver])) {
            return $this->callCustomCreator($driver);
        } elseif (method_exists($this, $method)) {
            return $this->$method();
        }

        throw new InvalidArgumentException("Driver [$driver] not supported.");
    }
```
From the stack trace it looks like `NULL` is passed as argument to createDriver:
```
#2 /var/www/virtual/rnet/cachet/vendor/laravel/framework/src/Illuminate/Support/Manager.php(63): Illuminate\Support\Manager->createDriver(NULL)
```
This is obviously because of my config:
```
MAIL_DRIVER=null
MAIL_HOST=null
MAIL_PORT=null
MAIL_USERNAME=null
MAIL_PASSWORD=null
MAIL_ADDRESS=null
MAIL_NAME=null
MAIL_ENCRYPTION=tls
```
I defined `MAIL_DRIVER` as null because i did not find documentation about what to configure if i don't want to use the mail functionality.

**Comment by jneureuther** [comment]
Defining `MAIL_DRIVER` as e.g. `smtp` fixes this error.

This error appeared because i couldn't find documentation about the actual configuration of cachet.
In my opinion is not clear what has to be configured and what are valid values for configuration.
(Other example: what is the correct size of `APP_KEY`?)

Is there any documentation about that i have missed?

**Comment by jbrooksuk** [comment]
`APP_KEY` is generated by running `php artisan app:install`.

**Comment by jneureuther** [comment]
Ok, this is surprising to me.
After reading the install documentation it looked like everything in `.env` has to be configured manually.
(`APP_KEY=SomeRandomString` looks like I have to set this random string)

I would suggest to state that clearly in the documentation.

**Comment by jneureuther** [comment]
Can you then please explain your warning about the APP_KEY in docs:
```
Never change the APP_KEY after installation on production environment. All your encrypted / hashed data will be lost, becoming unusable!
```
When i shouldn't specify an APP_KEY in .env and instead it is generated with `php artisan app:install`, how can i be sure it is not changed in future (e.g. though running `php artisan app:install` again)?
Furthermore why is there even an option APP_KEY in .env if i shouldn't specify it myself?
Sorry, but i think the documentation should contain more details about configuration..

**Comment by GrahamCampbell** [comment]
> (e.g. though running php artisan app:install again)?

Only every run install once. Run `php artisan app:update` later.

**Comment by jneureuther** [comment]
Ok, but what is the intention with the `APP_KEY` config option?

**Comment by GrahamCampbell** [comment]
It must be a 32 character random string that is used for all encryption by cachet.

**Comment by jneureuther** [comment]
Is this information available anywhere in documentation?
I think it would be good to know during setup.

**Comment by jneureuther** [comment]
Thank you for updating the documentation regarding installation. :+1: 
But it would be very helpful if you specify the `APP_KEY` config option more detailed.
