### ISSUE TITLE
Upgrade to Laravel 5.3 and drop PHP 5.5

### ISSUE THREAD

**Issue by GrahamCampbell** [CachetHQ/Cachet#1453]
Laravel 5.3 is dropping php 5.5 (has dropped it), so when it ships later this year, we can upgrade to it, and do the same.

**Comment by jbrooksuk** [comment]
What would the recommended version become? 5.6?

**Comment by GrahamCampbell** [comment]
5.6.4.

**Comment by GrahamCampbell** [comment]
https://github.com/laravel/framework/blob/master/composer.json#L18

**Comment by jbrooksuk** [comment]
Closed by https://github.com/CachetHQ/Cachet/pull/2195
