### ISSUE TITLE
Component Groups

### ISSUE THREAD

**Issue by jbrooksuk** [cachethq/Cachet#146]
I've noticed on Travis-CI's status page, they have component groups:

![screenshot 2014-12-30 22 11 00](https://cloud.githubusercontent.com/assets/246103/5583426/d1df0648-9070-11e4-9d65-4eb61a19f119.png)

**Comment by kfrankperson** [comment]
@jbrooksuk Looking good !!!

**Comment by jbrooksuk** [comment]
Actually we don't need the component_groups table because we can add an id to the component itself for group_id. Components won't be under more than one group so this is fine.

**Comment by joecohens** [comment]
:+1:

**Comment by willdurand** [comment]
Looks like it is not possible to remove component groups yet. Am I wrong?

**Comment by jbrooksuk** [comment]
Correct, that was an oversight on my part. If you create an issue, I'll do it tonight.
