### ISSUE TITLE
"No supported encrypter found. The cipher and / or key length are invalid" error on first run

### ISSUE THREAD

**Issue by ihatehandles** [CachetHQ/Cachet#1460]
Had followed the installation instructions but I kept getting the error message in the title. And I had generated the key before running the installation command. I also reinstalled the app twice but the error didn't go away. Solution that finally worked was from [this forum post](http://laravel.io/forum/06-09-2015-no-supported-encrypter-found-the-cipher-and-or-key-length-are-invalid?page=1#reply-26279), the solution being to run ```php artisan config:clear```.

Just putting this out there in case you feel someone may run into the same so that we have it added to the docs. Or did I do something wrong somewhere that caused this only error only for me?

**Comment by GrahamCampbell** [comment]
You forgot to run our install command. `php artisan app:install`.

**Comment by ihatehandles** [comment]
Hi @GrahamCampbell, think you missed the part where I said:

> And I had generated the key before running the installation command

And the two reinstalls. No worries though if you think this likely won't happen often. Had just thought if it happened on a plain install procedure with nothing custom it may hit someone else in the future (or not). Cheers

**Comment by GrahamCampbell** [comment]
In general, please don't run any of laravel's built in commands. Cachet is not designed to use them. For example, don't run laravel's migration commands or key generation commands. Just run our `app:` commands.

**Comment by ihatehandles** [comment]
I see, thanks. RE the key you might want to remove [this part](https://docs.cachethq.io/docs/installing-cachet#security-key) of the docs then. I've been on Cachet for over a year but I'm not confident enough in my knowledge of it to make contributions to the docs, but I hope to soon. I think a few more paragraphs in the installation docs explaining Cachet's methodologies would help as Cachet's usage grows, I don't think everyone will have time to figure things out themselves - Components, Component Groups, Metrics (and how you pass the data use for those), Incident templates etc. I'll take a shot at helping out with the docs sometime and see if I can add value there.
