### ISSUE TITLE
Notification emails only sent to one recipient at a time.

### ISSUE THREAD

**Issue by andrekeller** [CachetHQ/Cachet#1461]
Hi,

it seems cachet only sends one notification mail, each time artisan schedule:run is called.

Cronjob:
```
* * * * * /usr/bin/php5 /opt/cachet/artisan schedule:run 1>> /dev/null
```

So if I have 50 subscribers, it takes 50 minutes until the last notification mail is sent out. Is this intentional? Is this behavior configurable?

**Comment by GrahamCampbell** [comment]
Setup a proper queue rather than the scheduler. That way you can get all your jobs processed more quickly. The scheduler is only here so people can get a minimal setup quickly.

**Comment by GrahamCampbell** [comment]
Checkout http://fideloper.com/ubuntu-beanstalkd-and-laravel4. It's a bit old, but the core concepts, and supervisor config are the same.
