### ISSUE TITLE
documentation doesn't mention the need for job scheduling cron

### ISSUE THREAD

**Issue by mbravorus** [CachetHQ/Cachet#1464]
After wondering for a bit why the invitation mails do not go out, I discovered the need to run artisan cron job. This should be mentioned in documentation for people who are not experienced Laravel users.

**Comment by GrahamCampbell** [comment]
It's not needed. You are recommended to either setup a queue, or for the must basic setup, use sync queuing.

**Comment by jbrooksuk** [comment]
FWIW, sync is going to increase page load times.

**Comment by mbravorus** [comment]
This discussion is missing the point. It doesn't matter *what* needs to be done for mail to function, as long as it is not documented. Presumption that a Cachet user is experienced in Laravel maintenance is fundamentally flawed. Say, I have a modest understanding but without going into Laravel documentation I have no idea what queue/sync queueing you are talking about - fwiw, the default setup queues mail-out jobs in the database and they stay there unless artisan schedule:run is executed.

**Comment by jneureuther** [comment]
@mbravorus i think you overlooked [this](https://docs.cachethq.io/docs/setup-subscribers) documentation  :wink:

**Comment by mbravorus** [comment]
@jneureuther true, I did, my bad :) however I missed it because I wasn't looking to set up subscribers, only to use presumably built-in mechanism to invite team members. Perhaps it would be beneficial to move the mail setup part into a generic section, named, hmm, "Mail setup" maybe? ;)

**Comment by jneureuther** [comment]
:+1: for renaming to e.g. "Mail setup"

**Comment by jbrooksuk** [comment]
Could you open a new issue for this separately please?

**Comment by mbravorus** [comment]
sure, no problem
