### ISSUE TITLE
Upgrading to 2.1

### ISSUE THREAD

**Issue by philshil** [CachetHQ/Cachet#1465]
Hello,
followed the upgrade instructions in the documentation, all seemed to go well and got the application back up live. i then refreshed the webpage and then went into dashboard and its still saying version 2.0.0

**Comment by jbrooksuk** [comment]
You mustn't have checked out the `2.1.0` tag?

**Comment by philshil** [comment]
Hi James,
thanks i don't think i was in the right tag. however moved to tag v2.1.0 and run composer install and i have been hit with this error;

Could not fetch https://api.github.com/repos/twigphp/Twig/zipball/3e5aa30ebfbafd5951fb1b01e338e1800ce7e0e8, please create a GitHub OAuth token to go over the API rate limit
Head to https://github.com/settings/tokens/new?scopes=repo&description=Composer+on+it+2016-02-08+1106
to retrieve a token. It will be stored in "/root/.composer/auth.json" for future use by Composer.
Token (hidden): 
Invalid token provided.
You can also add it manually later by using "composer config github-oauth.github.com <token>"
    Failed to download twig/twig from dist: Could not authenticate against github.com

**Comment by jbrooksuk** [comment]
https://docs.cachethq.io/docs/github-oauth-token

**Comment by philshil** [comment]
Loading composer repositories with package information
Installing dependencies (including require-dev) from lock file
Nothing to install or update
Generating autoload files
> php artisan clear-compiled
PHP Fatal error:  Class 'CachetHQ\Cachet\Providers\AppServiceProvider' not found in /srv/www/Cachet/bootstrap/cache/compiled.php on line 6909

                                                                  
  [Symfony\Component\Debug\Exception\FatalErrorException]         
  Class 'CachetHQ\Cachet\Providers\AppServiceProvider' not found  
                                                                  

Script php artisan clear-compiled handling the post-install-cmd event returned with an error

when i run php artisan config:cache i get this error;

it:/srv/www/Cachet # php artisan config:cache
PHP Fatal error:  Class 'CachetHQ\Cachet\Providers\AppServiceProvider' not found in /srv/www/Cachet/bootstrap/cache/compiled.php on line 6909

                                                                  
  [Symfony\Component\Debug\Exception\FatalErrorException]         
  Class 'CachetHQ\Cachet\Providers\AppServiceProvider' not found

**Comment by jbrooksuk** [comment]
Run the following: `rm -rf bootstrap/cache/*`

**Comment by philshil** [comment]
Okay thanks @jbrooksuk sorry for my stupidity. All sorted now :)

**Comment by jbrooksuk** [comment]
I've updated the upgrading docs slightly to try and remedy a lot of these issues; https://docs.cachethq.io/docs/updating-cachet

**Comment by philshil** [comment]
@jbrooksuk Okay thanks James, I'm getting a error 500 now :/ have tried chmod -R 777 storage/ and chmod -R 755 storage/ was working okay and then suddenly crashed.

**Comment by jbrooksuk** [comment]
What's in your log file?

**Comment by philshil** [comment]
i know i have looked before, but I'm sorry i can't remember where the log file is? sorry @jbrooksuk

**Comment by jbrooksuk** [comment]
`./storage/logs/laravel-...` pick the latest log file :)

**Comment by philshil** [comment]
[2016-02-08 12:05:59] production.ERROR: exception 'ErrorException' with message 'include(/srv/www/Cachet/vendor/twig/twig/lib/Twig/Extension.php): failed to open stream: No such file or directory' in /srv/www/Cachet/vendor/composer/ClassLoader.php:412
Stack trace:
#0 /srv/www/Cachet/vendor/composer/ClassLoader.php(412): Illuminate\Foundation\Bootstrap\HandleExceptions->handleError(2, 'include(/srv/ww...', '/srv/www/Cachet...', 412, Array)
#1 /srv/www/Cachet/vendor/composer/ClassLoader.php(412): Composer\Autoload\includeFile()
#2 /srv/www/Cachet/vendor/composer/ClassLoader.php(301): Composer\Autoload\includeFile('/srv/www/Cachet...')
#3 [internal function]: Composer\Autoload\ClassLoader->loadClass('Twig_Extension')
#4 /srv/www/Cachet/vendor/rcrowe/twigbridge/src/Extension/Laravel/Str.php(23): spl_autoload_call('Twig_Extension')
#5 /srv/www/Cachet/vendor/composer/ClassLoader.php(412): include('/srv/www/Cachet...')
#6 /srv/www/Cachet/vendor/composer/ClassLoader.php(301): Composer\Autoload\includeFile('/srv/www/Cachet...')
#7 [internal function]: Composer\Autoload\ClassLoader->loadClass('TwigBridge\\Exte...')
#8 [internal function]: spl_autoload_call('TwigBridge\\Exte...')
#9 /srv/www/Cachet/vendor/rcrowe/twigbridge/src/ServiceProvider.php(283): class_alias('TwigBridge\\Exte...', 'TwigBridge\\Exte...')
#10 /srv/www/Cachet/vendor/rcrowe/twigbridge/src/ServiceProvider.php(41): TwigBridge\ServiceProvider->registerAliases()
#11 /srv/www/Cachet/bootstrap/cache/compiled.php(1775): TwigBridge\ServiceProvider->register()
#12 /srv/www/Cachet/bootstrap/cache/compiled.php(7394): Illuminate\Foundation\Application->register(Object(TwigBridge\ServiceProvider))
#13 /srv/www/Cachet/bootstrap/cache/compiled.php(1765): Illuminate\Foundation\ProviderRepository->load(Array)
#14 /srv/www/Cachet/bootstrap/cache/compiled.php(2182): Illuminate\Foundation\Application->registerConfiguredProviders()
#15 /srv/www/Cachet/bootstrap/cache/compiled.php(1641): Illuminate\Foundation\Bootstrap\RegisterProviders->bootstrap(Object(Illuminate\Foundation\Application))
#16 /srv/www/Cachet/bootstrap/cache/compiled.php(2374): Illuminate\Foundation\Application->bootstrapWith(Array)
#17 /srv/www/Cachet/bootstrap/cache/compiled.php(2327): Illuminate\Foundation\Http\Kernel->bootstrap()
#18 /srv/www/Cachet/bootstrap/cache/compiled.php(2312): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter(Object(Illuminate\Http\Request))
#19 /srv/www/Cachet/public/index.php(54): Illuminate\Foundation\Http\Kernel->handle(Object(Illuminate\Http\Request))
#20 {main} {"identification":{"id":"e5eba118-e65f-4bab-81c3-26d5df28c400"}}

**Comment by jbrooksuk** [comment]
Ping @GrahamCampbell.

**Comment by philshil** [comment]
@jbrooksuk I'm guessing some unusual error.

**Comment by GrahamCampbell** [comment]
Looks like you forgot to run composer install, or only partially ran it?

**Comment by philshil** [comment]
Thats odd. i had run it and then run php artisan up and it was working then it ran into that error. its working now though thanks @GrahamCampbell
