### ISSUE TITLE
Upgrade question: (like #1465) upgrading from 2.0.4 to 2.1.0

### ISSUE THREAD

**Issue by msc1978** [CachetHQ/Cachet#1475]
Hello 

According to documentation folow these steps:
Put your status page into maintenance mode php artisan down
Fetch the latest code with git pull
Install the latest dependencies with composer install -o --no-dev
Run the update command; php artisan app:update
Bring your status page back up php artisan up

But then like in #1465 I stay on 2.0.4.
I #1465 is asked: You mustn't have checked out the 2.1.0 tag?

So does this mean I need to first do a git checkout v2.1.0? so the actions would be:

Put your status page into maintenance mode php artisan down
git checkout v2.1.0
Fetch the latest code with git pull
Install the latest dependencies with composer install -o --no-dev
Run the update command; php artisan app:update
Bring your status page back up php artisan up

Sorry i have no experience with git (still a subversion user:))

Thanks in advance,
regards,
Maarten

**Comment by msc1978** [comment]
Just wanted to update this ticket, that i got it working by doing a checkout first. After that (and after fining the spacing issue in my .env file) it worked. Thanks, love the product. 

We use dutch language, will try to contribute to translation of that language

**Comment by jbrooksuk** [comment]
Awesome, thanks!
