### ISSUE TITLE
Add component_status parameter to update an incident request

### ISSUE THREAD

**Issue by qk4l** [CachetHQ/Cachet#1480]
Hi,

It's possible to change _component_status_ by creating incidents but there isn't way to change it after by PUT request.

Please add _component_status_ parameter to  PUT /incidents/:id  method.

**Comment by jbrooksuk** [comment]
I've had a quick look at the code and it is indeed already there. You have to supply the `component_id` at the same time though.

**Comment by qk4l** [comment]
@jbrooksuk , oh sorry it works. I miss _component_id_ in one of my requests.

But missing parameter in [docs](https://docs.cachethq.io/docs/update-an-incident) push me to create this issue.
It's better to update it.

**Comment by jbrooksuk** [comment]
I'll update the documentation.

**Comment by jbrooksuk** [comment]
Done :)
