### ISSUE TITLE
500 internal server error

### ISSUE THREAD

**Issue by jakesullyneytiri** [CachetHQ/Cachet#1481]
Hi, i just installed the script but problem is script first nagged about sv-SE.php could not be found/read due to file was actually alled sv.php so i renamed it to proper file to what it needed but still index page remains as 500 internal server error what so ever :/ i cannot figure out what is the problem that is causing it to error out only admincp works fine but index keeps showing same error, does anyone here know how to find out a way to solve this??

Also error code it's giving me is 0e4e2a15-f195-491e-9ee9-82e8b215d1b2

site is http://status.xenionode.com/

Update: after adding a components to site thats when index page responded with success result no more 500 internal server error but once i remove the components the 500 internal server error comes back so is this normal for script to keep erroring out without any components?

/thanks

**Comment by GrahamCampbell** [comment]
> Also error code it's giving me is 0e4e2a15-f195-491e-9ee9-82e8b215d1b2

That code is meaningless. It's randomly generated. You're meant to use it to lookup the log entry.

**Comment by jakesullyneytiri** [comment]
okay well should script be giving 500 internal server error when i havent added any components?

**Comment by GrahamCampbell** [comment]
I think I know what's happening. Upgrade to the latest master branch. It fixes a division by zero error on new installs.

**Comment by GrahamCampbell** [comment]
We ship the stable release with that patch this weekend.
