### ISSUE TITLE
Last hour still broken

### ISSUE THREAD

**Issue by spencerhance** [CachetHQ/Cachet#1482]
I'm not seeing anything showing up under `Last Hour` for any of my metrics.  I've also noticed the same issue on the demo website.

**Comment by jbrooksuk** [comment]
Are you using Postgres?

**Comment by spencerhance** [comment]
Currently i'm using Sqlite on v2.1.0, but i've also tried it with Postgres on Master

**Comment by GrahamCampbell** [comment]
@jbrooksuk Who was it that requested last hour view?

**Comment by GrahamCampbell** [comment]
Why is the code there different to the others?

**Comment by jbrooksuk** [comment]
It's just the query that calculates it is not working I think.

**Comment by jbrooksuk** [comment]
https://github.com/CachetHQ/Cachet/issues/1227

**Comment by jbrooksuk** [comment]
Is this still an issue @GrahamCampbell?

**Comment by henry-spanka** [comment]
I have the issue that it always shows the tooltip for 3 data points(for last hour only)
See Picture
![screenshot_2](https://cloud.githubusercontent.com/assets/10375269/13186914/9956778c-d748-11e5-8680-23fd55ef89f7.png)

**Comment by GrahamCampbell** [comment]
> Is this still an issue @GrahamCampbell?

Yes, very much so.

**Comment by jbrooksuk** [comment]
I don't know what's going on here at all.

**Comment by jbrooksuk** [comment]
It's just Postgres and SQLite.
