### ISSUE TITLE
Log Error Message this page status

### ISSUE THREAD

**Issue by zhiephie** [CachetHQ/Cachet#1484]
exception 'ErrorException' with message 'Division by zero' in E:\xampp\htdocs\laravel-status\app\Composers\StatusPageComposer.php:32

**Comment by jbrooksuk** [comment]
There will be a bug fix release this weekend.

**Comment by zhiephie** [comment]
Oke @jbrooksuk

**Comment by jbrooksuk** [comment]
This is the bug fix that'll be released; https://github.com/CachetHQ/Cachet/commit/c11daf289820faec04b541dd64e6a1ab24d04996
