### ISSUE TITLE
laravel-cors upgrade

### ISSUE THREAD

**Issue by GrahamCampbell** [CachetHQ/Cachet#1485]
```
        "asm89/stack-cors": "dev-master as 0.2.2",
        "barryvdh/laravel-cors": "^0.7.3",
```

needs replacing with:

```
        "barryvdh/laravel-cors": "^0.8",
```

**Comment by GrahamCampbell** [comment]
Hmm, this is non-trivial. The config file we have won't actually work in 0.8, and the stuff we were using was deprecated in 0.7 anyway (and maybe even in earlier versions too).

`paths` config is gone.

**Comment by jbrooksuk** [comment]
They broke backwards compatibility in a point release?

**Comment by GrahamCampbell** [comment]
> They broke backwards compatibility in a point release?

Yes, that is allowed by semver in 0.x.

**Comment by jbrooksuk** [comment]
Ok :)

**Comment by GrahamCampbell** [comment]
Point 4 from the spec:

> Major version zero (0.y.z) is for initial development. Anything may change at any time. The public API should not be considered stable.
