### ISSUE TITLE
v2.1.0 installer says [object Object] just before complete setup once.

### ISSUE THREAD

**Issue by sawanoboly** [CachetHQ/Cachet#1486]
duplicate from https://github.com/CachetHQ/Cachet/issues/1324#issuecomment-183189686

![setup](https://cloud.githubusercontent.com/assets/272388/13000008/b424e766-d198-11e5-8484-866ff22276b2.jpg)

Reproduce.

- install v2.1.0 below steps
    - composer install --no-dev -o
    - php artisan key:generate
    - php artisan app:install
- I through the setup wizard.

When I click `complete setup` again after occur it. It completes without problem.

**Comment by GrahamCampbell** [comment]
@joecohens This doesn't fix the frontend bug though?

**Comment by joecohens** [comment]
We were getting the object object since the request didn't have any kind of response or a 500 I don't remember. We could code to catch if the error message thrown by the server it's not "readable" and show a generic error maybe?

**Comment by GrahamCampbell** [comment]
Are you sure just didn't forget to update the setup page js for the new error format from the exception package?

**Comment by sawanoboly** [comment]
I entered a weak password to see this message.

**Comment by joecohens** [comment]
I'll double check :)

**Comment by ihatehandles** [comment]
I can also confirm running into [object object] in more than one installation, but I failed to consistently reproduce the error message consistently when [I reported](https://github.com/CachetHQ/Cachet/issues/1460) some other setup troubles.
