### ISSUE TITLE
move description of mail setup to a separate documentation section

### ISSUE THREAD

**Issue by mbravorus** [CachetHQ/Cachet#1487]
To make it easier for people not very familiar with Laravel to set up mail as necessary for both team member invites and subscribers, move mail setup documentation as currently listed under Subscriber setup to a separate  section, titled "Setting up mail" or similar. As discussed in #1464

**Comment by jbrooksuk** [comment]
I forgot that this was done; https://docs.cachethq.io/docs/configuring-mail
