### ISSUE TITLE
[API] Sort behavior in pagination result

### ISSUE THREAD

**Issue by rogeriolino** [CachetHQ/Cachet#1489]
The sort/order is applied into the limited collection, and the correct is to apply in the all records then limit the result.

https://github.com/CachetHQ/Cachet/blob/master/app/Http/Controllers/Api/AbstractApiController.php#L167

Example:

- I've 22 incidents (id 1 to 22)
- Cachet version 2.0.4

`/api/v1/incidents?sort=id&order=desc`

Shows the first 20 records sort by id desc (id 20 to 1).

`/api/v1/incidents?sort=id&order=desc&page=2`

The second page shows incidents 22 and 21, respectively.

Regards

**Comment by GrahamCampbell** [comment]
Thanks for reporting. Not sure how this went unnoticed.

**Comment by jbrooksuk** [comment]
We've kinda screwed this one up then. We're passing through the truncated results even before we've sorted them. This kind of needs a refactor.

**Comment by jbrooksuk** [comment]
This needs to be covered in tests.

**Comment by djtecha** [comment]
Out of curiosity, is there a way to return more then 20 results? This is breaking the nagios plugin currently. And it would be nice to just modify the endpoint.

**Comment by joecohens** [comment]
Yeah we could add a limit. Taking this task now, thanks!

**Comment by joecohens** [comment]
@djtecha You can modify it now with `&per_page=50`

**Comment by djtecha** [comment]
sweet, thanks!

**Comment by mhruscak** [comment]
Param "order=" does not work.
There is no difference in output when using
http://demo.cachethq.io/api/v1/components?sort=id&order=desc&per_page=10
or
http://demo.cachethq.io/api/v1/components?sort=id&order=asc&per_page=10

Params "sort=" and "per_page=" are working correctly though.

see https://github.com/CachetHQ/Cachet/blob/35279cebe4e6294d420bd8c086c04e67ca9c3169/app/Http/Controllers/Api/ComponentController.php#L46
