### ISSUE TITLE
Site language bug ? Weird translation problems

### ISSUE THREAD

**Issue by bbcorp** [CachetHQ/Cachet#1490]
Hey there,
I'm trying version 2.1.1-dev, I upgraded from old version.
Language in dashboard is set to French and next to services there is `Funktionsfähig`.
I also tried to set language to english and same problem.

See in this screenshot for more informations.
![cachet-translation](https://cloud.githubusercontent.com/assets/11371274/13017766/79d920f8-d1c6-11e5-8c07-c3cbccab2d7d.png)

**Comment by TheoBearman** [comment]
I can confirm @pierr3 has experienced this issue on my install too.

**Comment by GrahamCampbell** [comment]
Ping @jbrooksuk.

**Comment by bbcorp** [comment]
I just discover another bug I think in v2.1.0.
If you set language to French in dasboard and then set in your .env file `APP_LOCALE=fr`.
In dashboard, status of services is in german.
In front-end it's all ok.
If you don't think that's a bug just ignore what I just said
![bug-cachet-locale](https://cloud.githubusercontent.com/assets/11371274/13028686/995cac14-d276-11e5-83db-1991dc5e6a1c.png)

**Comment by jbrooksuk** [comment]
Errr... The French language file is German. https://github.com/CachetHQ/Cachet/blob/master/resources/lang/fr/cachet.php

This must be a CrowdIn export issue. Will re-export it.

**Comment by bbcorp** [comment]
> This must be a CrowdIn export issue. Will re-export it.
Okay thanks, I did translate all french language files by myself. Are you interessed in a pull with translated files ?
It mights need a review before.

**Comment by jbrooksuk** [comment]
> Okay thanks, I did translate all french language files by myself. Are you interessed in a pull with translated files ?

Only for the English translation file I'm afraid. This makes managing translations _much_ easier.

**Comment by bbcorp** [comment]
It's okay, I started helping translation on CrowdIn. I'll make a upload to it today and review all the translation. Do you guys know when you'll export from CrowdIn ?

**Comment by jbrooksuk** [comment]
I'm just about to re-sync them now.
