### ISSUE TITLE
Time bug

### ISSUE THREAD

**Issue by jakesullyneytiri** [CachetHQ/Cachet#1493]
Hey,

when ever adding planned maintenace and i set it to 20:00 i hit save/apply so when i check it then i see 21:00 not 20:00 it keeps jumping 1 hour forward to what i save please fix this.

**Comment by GrahamCampbell** [comment]
What version please, what timezone?

**Comment by jakesullyneytiri** [comment]
i dont see it asking me any timezone but i'm on 2.1.1 RC2 or something like that if i remember correctely. Issue comes when i put a maintenance to be done thats when i etc tell it to put 20:00 once i save thats when it jumps 1 hour forward 21:00 so yeah.

**Comment by GrahamCampbell** [comment]
> 2.1.1 RC2

No such version exists. ;)

**Comment by jakesullyneytiri** [comment]
well in log it says 2.1.1 RC2??? when i fetch version thing.

**Comment by GrahamCampbell** [comment]
Can I see please?

**Comment by jakesullyneytiri** [comment]
i will get back to you soon i will need to login and fetch the proof :)

**Comment by jakesullyneytiri** [comment]
okay i had 1 no wrong it's 2.1.0-RC2

**Comment by GrahamCampbell** [comment]
I assume it'll probably actually be `2.1.0-RC2`, since that does exist.

**Comment by GrahamCampbell** [comment]
2.1.0 is the latest, but i'm shipping 2.1.1 today.

**Comment by jakesullyneytiri** [comment]
okay how do i apply a update without loosing any data?

**Comment by GrahamCampbell** [comment]
Assuming you only modifed the .env file, you can just delete everything and replace it with the new version, run composer install, and then php artisan app:update. This should be documented on our website.

**Comment by GrahamCampbell** [comment]
I'm going to assign this issue to @joecohens.

If you still need help with upgrading, you can contact our support email support@alt-three.com to avoid cluttering this thread with unrelated info.

**Comment by jakesullyneytiri** [comment]
okay well i will give a try myself so i learn :) if i do get a problem i will send a mail.

**Comment by GrahamCampbell** [comment]
@jbrooksuk Normally deals with Cachet support requests on that address, and emails to that address regarding Cachet aren't likely to get a response in under 48 hours atm.

**Comment by GrahamCampbell** [comment]
Basically, just a heads up so you don't wait for a while expecting a reply. :)

**Comment by jakesullyneytiri** [comment]
okay thank you for that info :)

**Comment by marcalle** [comment]
Is this the same problem that I'm having, where the time is about 5 hours off. EX, I choose 10PM and it moves it to 5PM upon saving?

**Comment by GrahamCampbell** [comment]
Are your server's timezones set to GMT?

**Comment by marcalle** [comment]
I've verified my server has the correct time and is set to edt

**Comment by GrahamCampbell** [comment]
What timezone though. it doesn't matter what the server time is.

**Comment by jakesullyneytiri** [comment]
my dedi is using Paris / France but it jumps forward by 1 hour after applying the changes

**Comment by GrahamCampbell** [comment]
What timezone settings do you have on Cachet?

**Comment by GrahamCampbell** [comment]
https://github.com/CachetHQ/Cachet/blob/master/config/app.php#L64

In there, that value must be UTC, and should never be changed.

**Comment by marcalle** [comment]
The timezone in there is set to UTC, the server itself is EST time as noted above.

[root@status config]# date
Sun Feb 14 09:17:25 EST 2016

Any other thoughts?

**Comment by GrahamCampbell** [comment]
Ping @joecohens.

**Comment by GrahamCampbell** [comment]
I assume Cachet is assuming you're entering the time in UTC, then it's converting it to display it to you?

> when ever adding planned maintenace and i set it to 20:00 i hit save/apply so when i check it then i see 21:00 not 20:00 it keeps jumping 1 hour forward to what i save please fix this.

Is this through the API, or what?

**Comment by jakesullyneytiri** [comment]
no api it's through dashboard under maintenance area where you add new maintenance thats where you select date & time but that keeps jumping 1 hour forward after save.

**Comment by GrahamCampbell** [comment]
> but that keeps jumping 1 hour forward after save.

Right, but it's not "jumping forward" if the time you enter there is the time in UTC?

**Comment by jakesullyneytiri** [comment]
it only jumps 1 hour forward when saving like i wrote before if i put 20:00 hit save button it tells me 21:00 is set instead of 20:00 and i havent touched the file you linked about UTC so it should be UTC by default.

**Comment by GrahamCampbell** [comment]
What I'm saying is that it's not jumped forward. Entering 20:00 GMT on there is then displayed to you as 21:00 in +1 time?

**Comment by GrahamCampbell** [comment]
I guess this is probably a bug that the input isn't read as +1 time.

**Comment by marcalle** [comment]
My time is also set to UTC in that file

**Comment by peterlaws** [comment]
Maybe it's reading UTC then +1 (Paris) in your php.ini (if set)? I remember I had/have the same issue.

**Comment by jakesullyneytiri** [comment]
no i want to save it as 20:00 but it changes on it's own to 21:00 but i dont want it to save as 21:00 i want it to save at 20:00 or w.e time i set it to.

**Comment by peterlaws** [comment]
is it 21:00 in the actual database? can you check if you haven't already

**Comment by jakesullyneytiri** [comment]
well since it tells me maintenance is planned at 21:00 i would guess db has it writen to 21:00 :/ but i will check some how and get back to you soon.

**Comment by jakesullyneytiri** [comment]
Okay i got a bit dificult for me atm i'm runing cachet of a 4 core with 7 GB RAM vps at azure from microsoft and it wont let me use straight root login :/ so yeah i gota do advanced stuff to get phpmyadmin up so i can check and right now i'm not able todo that :/ @peterlaws

**Comment by GrahamCampbell** [comment]
> well since it tells me maintenance is planned at 21:00 i would guess db has it writen to 21:00 :/ but i will check some how and get back to you soon.

20:00 should be in the db, and 21:00 shyould be displayed on the screen.

**Comment by jakesullyneytiri** [comment]
well i dont want it to say 21:00 i want it to show up as 20:00 to what i saved :/

**Comment by GrahamCampbell** [comment]
It shows according to the timezone header sent by people's browser.

**Comment by jakesullyneytiri** [comment]
well server is on same timzone as where i live i'm in sweden and france + sweden has same timezone so then dont know why it should add an hour so it says 21:00 instead :/

**Comment by l365** [comment]
I can confirm this issue exists on 2.1.1.  I add an incident and the time is shifted back 5 hours.  For example:
Incident created via dashboard at 15:45  
Status board immediately shows 10:45
Viewing incident in dashboard shows 10:45.
Changing incident in dashboard to 15:45 and clicking update immediately refreshes the page and sets it back at 10:45.

I have tried setting my server time to both  EST (-5) and UTC.  Dashboard is configured for EST, as is my workstation.

**Comment by l365** [comment]
Appears to be a "display issue" as the time is correct in the db:

`+----+--------------+--------+--------+---------+---------+--------------+---------------------+---------------------+------------+
| id | component_id | name   | status | visible | message | scheduled_at | created_at          | updated_at          | deleted_at |
+----+--------------+--------+--------+---------+---------+--------------+---------------------+---------------------+------------+
| 16 |            0 | TEST 3 |      1 |       1 | test    | NULL         | 2016-02-17 15:45:00 | 2016-02-17 15:45:00 | NULL       |
+----+--------------+--------+--------+---------+---------+--------------+---------------------+---------------------+------------+`

**Comment by l365** [comment]
But interestingly enough, every time I click Update, another 5 hours roll off the time and that new time is written to the DB:
`+----+--------------+--------+--------+---------+---------+--------------+---------------------+---------------------+------------+
| id | component_id | name   | status | visible | message | scheduled_at | created_at          | updated_at          | deleted_at |
+----+--------------+--------+--------+---------+---------+--------------+---------------------+---------------------+------------+
| 16 |            0 | TEST 3 |      2 |       0 | test    | NULL         | 2016-02-17 05:45:00 | 2016-02-17 05:45:00 | NULL       |
+----+--------------+--------+--------+---------+---------+--------------+---------------------+---------------------+------------+`

**Comment by peterlaws** [comment]
Something must be going on, thing is, not everyone is seeing this issue

**Comment by jbrooksuk** [comment]
Ping @joecohens any update?

**Comment by jneureuther** [comment]
I can also confirm this bug in v2.1.0.

**Comment by joecohens** [comment]
Working on this now. Thanks everybody!

**Comment by l365** [comment]
Thanks Joe! Let me know if you need anything from an impacted system. I can
provide access if needed.

On Feb 17, 2016, at 5:17 PM, Joe Cohen <notifications@github.com> wrote:

Working on this now. Thanks everybody!

—
Reply to this email directly or view it on GitHub
<https://github.com/CachetHQ/Cachet/issues/1493#issuecomment-185432218>.
