### ISSUE TITLE
Upgrade issue

### ISSUE THREAD

**Issue by jakesullyneytiri** [CachetHQ/Cachet#1498]
Okay i tried to upgrade my cachet with by cloning new files and then runing composer install and then php artisan app:update but the 2nd cmd just tells me this

Copied Directory [/vendor/roumen/feed/src/views] To [/resources/views/vendor/feed]
Publishing complete for tag []!
Nothing to migrate.
Clearing cache...
Application cache cleared!
Cache cleared!
and then script gives me 500 internal server error page :/ any clue how to fully upgrade it without loosing any data??

**Comment by GrahamCampbell** [comment]
Does your web server has write access to the storage folder?

**Comment by GrahamCampbell** [comment]
It's normal to clone cachet and run the command using the same user as your web server is running as to avoid having to chmod 755 things.

**Comment by jakesullyneytiri** [comment]
yes i did same method when i first installed cachet it worked fine straight away but upgrade method failed :/

**Comment by jakesullyneytiri** [comment]
any solution to solve this upgrade problem??? since i would like to upgrade it asap without having to re-do data from scratch.

**Comment by jakesullyneytiri** [comment]
@GrahamCampbell i tried to follow this https://docs.cachethq.io/docs/updating-cachet but guide is confusing like when i do git pull it tells me i'm not currently in a branch so i gota do git pull <remote> <branch> but idk what to type in rest of cmd :/ could you tell me exactly what i need to type to get latest version? so i can continue upgrade steps??

**Comment by GrahamCampbell** [comment]
> Nvm i solved it but for odd reason it now upgraded to 2.1.2-Dev O_o instead of 2.1.1 ??? idk how that happened since i followed the steps for the upgrade hmmm.

2.1.2-dev is **identical** to 2.1.1 atm.

**Comment by jakesullyneytiri** [comment]
ah i see well at least i found working update method :)

**Comment by jbrooksuk** [comment]
Try run `rm -rf bootstrap/cache/*`.

Not a Cachet issue though as far as I'm aware.
