### ISSUE TITLE
The List Becomes Too Long 

### ISSUE THREAD

**Issue by userguy** [CachetHQ/Cachet#1500]
Hello , 

As of now we have only one option of having components under components group in vertical way .. But if i have around 50 components in each component group it becomes too big so can we also have an option or change it to horizontal tab . Just a suggestion .. Want to know why you have kept it in vertical way ..

**Comment by jbrooksuk** [comment]
Could you mockup what you think it'd look like? I'm unsure about showing them horizontally, we could collapse a big list though?

**Comment by jbrooksuk** [comment]
Actually, no, this isn't something we're going to do. You can put components into a group and have it collapsed by default.

Your use case is pretty obscure compared to 99% of the others, so it's not something we'd be able to accommodate.

**Comment by userguy** [comment]
I was talking about this .. 
As of now with in cachet we have component group and components assigned like this 
![image](https://cloud.githubusercontent.com/assets/11783537/13277019/3c20ba36-daeb-11e5-8878-145253f8578a.png)

Whereas Suppose if we have something like 100 components in one compoennt group as we expand the list becomes too big and if we try to put this dashboard in monitoring (LCD ) we cannot accommodate all in one screen .. 

Can we also have something like this .. 

![image](https://cloud.githubusercontent.com/assets/11783537/13277075/d434e69e-daeb-11e5-9d01-ae38bca1a3d2.png)

I hope i am clear ..  Collapsing is what is already there ,  if we want dashboard to be presented and put up in monitoring room we would like components and components to bee seen at once .. just a suggestion :)

**Comment by jbrooksuk** [comment]
Ping @joecohens, just something to think about in the event of a design refresh.

@userguy it's kinda hard to account for this, hundreds of components is unusual and would require odd conditions to account for it.

**Comment by GrahamCampbell** [comment]
I'd suggest you just set the default state to collapsed if it's getting a bit long?

**Comment by userguy** [comment]
@joecohens whats your input .. I understand your idea that you can collapse it , But in case we are using this a dashboard to see for users and to know which server are up down or what is status of it .. We cannot ask someone to scroll or every-time collapse it and expand it .. This is case in Many IT environment where you will definitely have more components in component group .. i would like to hear others opinion  ..Actually both the snapshot which are attached are of Cachet .. One is default the other one has its code changed a bit .. But some issue still ..

**Comment by joecohens** [comment]
I see two ways of doing this, in case of having 20 >= components we could switch to a two column layout to display all the components and still can see the incidents timeline without having to scroll all the way down. The other it's to make components like @userguy suggested, kind of like tags with background status color.

**Comment by jbrooksuk** [comment]
:+1:

**Comment by jbrooksuk** [comment]
Re-opened due to the PR above only being half-baked. We'll look into this some more.

**Comment by GrahamCampbell** [comment]
Moving this to the 2.3.0 milestone.

**Comment by GrahamCampbell** [comment]
This is also less of an issue after we added the auto-expand only on issue option.

**Comment by peelman** [comment]
@joecohens wrote: 
> I see two ways of doing this, in case of having 20 >= components we could switch to a two column layout to display all the components and still can see the incidents timeline without having to scroll all the way down. The other it's to make components like @userguy suggested, kind of like tags with background status color.

If this is still a thing to be done, please make it a configurable number and not hard coded to 20; even if its a `.env` parameter.

**Comment by jbrooksuk** [comment]
@joecohens this is why we need flex box in the new design 😉
