### ISSUE TITLE
Cachet API client written in PHP

### ISSUE THREAD

**Issue by rogeriolino** [CachetHQ/Cachet#1503]
Hi,

I've coded a client for Cachet and published it in Packagist:

https://github.com/mangati/cachet

This library is using Guzzle for HTTP requests and JMS Serializer for JSON parser.

Regards.

**Comment by jbrooksuk** [comment]
Cool, thanks! I'll add it to the docs.

**Comment by jbrooksuk** [comment]
Done here, https://docs.cachethq.io/docs/client-libraries

**Comment by rogeriolino** [comment]
Thanks @jbrooksuk 

ps: Mangati is my org, the author is me, "Rogerio Lino".

**Comment by jbrooksuk** [comment]
I'll update :)

**Comment by rogeriolino** [comment]
:+1:
