### ISSUE TITLE
Feature: Integration/Plugin Interface

### ISSUE THREAD

**Issue by TheFynx** [CachetHQ/Cachet#1507]
I know some of this has already been mention in https://github.com/CachetHQ/Cachet/issues/36 and https://github.com/CachetHQ/Cachet/issues/579

But I propose something a little more geared towards allowing the community to contribute easily. 

1) Enable a dashboard section for integrations (i.e. New Relic, Pagerduty, Pingdom, etc...) 

2) Build a plugin/integration interface into CachetHQ and document to allow the community to build these items without having to modify the codebase itself.

I understand 90% of this will be handle via API, but there needs to be some sort of option inside the app itself to allow configuration (e.g.; Enabling/Disabling Plugins, Configure Plugin options, intervals if pulling data, etc...) But having something of a plug-able interface should allow a more modular approach to expanding Cachet and it's capabilities (especially those not as overly laravel or php savvy as myself).

**Comment by jbrooksuk** [comment]
This is definitely going to require a pretty big architecture change. We'll discuss this :)

**Comment by ConnorVG** [comment]
@jbrooksuk any progress on this idea? I love Cachet and this is literally the only thing holding me back from using it :disappointed:

**Comment by jbrooksuk** [comment]
@ConnorVG in terms of a plugin interface, we're not currently any closer to implementing it. We (@CachetHQ/owners) have discussed implementing it, but we've not solidified any implementations yet. It's something we have to get right first time.

This is something that we **absolutely will** be implementing, but we just don't know when yet.

@CachetHQ/owners we should discuss this further.

**Comment by ConnorVG** [comment]
Please do :heart:

**Comment by ConnorVG** [comment]
I've started something, I'll initiate the PR tomorrow.

![plugins](https://cloud.githubusercontent.com/assets/3260091/17596345/e0a5786c-5fe8-11e6-86fa-65ef7b539a9e.png)

**Comment by jbrooksuk** [comment]
:D

**Comment by ConnorVG** [comment]
@GrahamCampbell / @jbrooksuk any ideas how we can make this any faster? The main slow down seems to be cache generation and composer optimisation...

![image](https://dn122w.bn1301.livefilestore.com/y3p4W6aa5aa89lJRUZ5xCH14zm6klx9jckkQ4LpwpaK7MFAW_-0nSGmwFWUx_Wi3sFbIGx1V-a91tkkeI2mJ_quYeCxbEPdtVp0gW7Mpt7tx0fpJgX9nfdJ5BqHOfEBRFFXZd_N-4Tc_g8DcWs-PF05DqvjdJEpHunLypP6eY2VrWA/2016-08-13_17-26-25.gif)

**Comment by ConnorVG** [comment]
Migrations are in, I think it's time @jbrooksuk and/or @GrahamCampbell see about possibly helping with creating tests. If this eco system is the correct direction, that is.

![here](https://goo.gl/zO2IgN)

**Comment by anonrig** [comment]
+1

**Comment by Skolzack** [comment]
Any news on integration with NewRelic?

**Comment by jbrooksuk** [comment]
This is on hold at the moment, @ConnorVG has been busy :)

**Comment by jbrooksuk** [comment]
For now, I think we're going to focus on providing a rock solid API and let third-parties integrate into Cachet that way.

Plugins themselves can come at a later date :)
