### ISSUE TITLE
Limitation in DB in metric_points

### ISSUE THREAD

**Issue by vogelor** [CachetHQ/Cachet#1508]
i am using Cachet for a status page showing some metrics. Yesterday i saw, that a normally growing metric is still standing at the same level (10.000.000 to be exact).
i am wondering why. First i search for the problem in my code. But then i found out, that the problem is your Database.

metric_points -> value is decimal(10,3) and so 9.999.999,99 is the highest value Cachet can handle. Can you please change this to a higher value (for example decimal(15,3) - or better, why not using float (double)?

**Comment by GrahamCampbell** [comment]
Are you using MySQL. This sounds a lot like a standard MySQL issue of just silently truncating data. That's why we recommend PostGres.

**Comment by GrahamCampbell** [comment]
Ping @jbrooksuk.

**Comment by vogelor** [comment]
Yes i am using MySQL. After changing to Double(15,3) it works fine for me. But at the next update of the system ( and the DB ) the error still occours - if you don' t change it ...


Am 16.02.2016 um 21:46 schrieb Graham Campbell <notifications@github.com<mailto:notifications@github.com>>:


Are you using MySQL. This sounds a lot like a standard MySQL issue of just silently truncating data. That's why we recommend PostGres.

**Comment by jbrooksuk** [comment]
Could you make a PR fixing this? :)

**Comment by vogelor** [comment]
Sorry - i can't. i don't have a development environment working with git. 

You only have to change the field value in the table metric_points from
decimal(10,3)
to
decimal(15,3).

THE DB IS THE ONLY LIMITATION
"your" code for the API call and for creating the graph inside the page is working fine!

after i canged the field, the limitation is gone away and the system is working fine for me...

**Comment by jbrooksuk** [comment]
Just waiting on some testing @vogelor and then this will be fixed :+1:

**Comment by vogelor** [comment]
Feedback is comming tomorrow...

**Comment by jbrooksuk** [comment]
Awesome, thanks!

**Comment by vogelor** [comment]
O.K. My System is working fine for about 3 days. The only thing i changed is value to decimal(15,3). there is no need to change anything other thing. the api (i am using the api to add points) is working fine without any issues. The maximum value i added was about 12.654.923 and i can see this value correct.

so only change the size of the db-field and thats it...

have a nice day...

**Comment by jbrooksuk** [comment]
https://github.com/CachetHQ/Cachet/pull/1525

Are you able to test this under Postgres and your MySQL?

**Comment by vogelor** [comment]
No, i only have MySql. 
But i can't belive that the TYPE of the DB is a problem. your (API) Code is working fine and only the limitation of the filed-size causes the problem...

**Comment by jbrooksuk** [comment]
Huh?

**Comment by vogelor** [comment]
sorry. there is a typo - to make it clear:

only the limitation of the size of the db field (number 10,3) is the problem, because mysql truncates 12.000.000 to 9.999.999,99 and stores this value inside the table. after changing to number(15,3) the value isn't truncated by mysql and the "right" value is stored inside the table (12.000.000)

**Comment by GrahamCampbell** [comment]
@vogelor Does #1525fix it for you on your setup please?

**Comment by jbrooksuk** [comment]
Ah this is the same issue as #1508, so I'm assuming we're closed :)

**Comment by vogelor** [comment]
;-)
