### ISSUE TITLE
Any examples of Cachet installs using UptimeRobot with the API?

### ISSUE THREAD

**Issue by brianjking** [CachetHQ/Cachet#1510]
Hello,

Are there any installs or documentation I may be overlooking for using UptimeRobot to do any of the following in conjunction with Cachet?

- Update the status of components automatically
- Add incidents automatically
- Use metrics graphics for displaying response time 

Thanks! Any assistance you can provide would be much appreciated.

**Comment by jbrooksuk** [comment]
I don't know if Uptime Robot integrate with Cachet? They should be sending you metrics.

I do know that they were looking at it, but if not [Pingometer](https://pingometer.com) have integrated into Cachet :)

This isn't a Cachet issue, so I'm closing it, but I'm happy to continue the conversation.

**Comment by camilonova** [comment]
I'll leave this here https://github.com/Axiacore/cachet-uptime-robot

**Comment by brianjking** [comment]
@camilonova -- Thanks, now I just need to figure out how to set this up. Have you succeeded yet? Thanks!

**Comment by camilonova** [comment]
@brianjking yes we do. If you have any other issues please add them there. Best.
