### ISSUE TITLE
Using UDP as transfer protocol

### ISSUE THREAD

**Issue by zhil** [CachetHQ/Cachet#1513]
Right now our application sends around 300k "status update" events daily. It will be great perfomance improvement, if reactPhp + UDP will be used (https://github.com/reactphp/datagram).
Clients will not get locked while sending stats.
Server will work faster (thanks to reactPhp)

what do you think?

**Comment by jbrooksuk** [comment]
I understand the benefits for this but it's a pretty big (and unnecessary) overhead for the majority of users.

If we were to implement a separate package that could be installed, that'd be a good way of getting around it.

Thoughts @CachetHQ/owners?

**Comment by joecohens** [comment]
This sounds very cool. I think I like the idea of a package to enable this feature on more complex systems.

**Comment by zhil** [comment]
Ok, i will discuss with my client possibility of releasing part of code as open source

**Comment by zhil** [comment]
@joecohens @jbrooksuk I have got agreement from client. I will release this addon as separate abstract library and separate symfony2 wrapper bundle. Not sure when I will do it - probably within next month or so. Just let you know.

**Comment by jbrooksuk** [comment]
Awesome, thanks @zhil! We look forward to seeing it!
