### ISSUE TITLE
500 when adding subscribers 

### ISSUE THREAD

**Issue by compscinoob** [CachetHQ/Cachet#1522]
When trying to add subscribers through the dashboard or through the status page I am getting a 500 error. However, when checking the subscribers tab in the dashboard the email is show to have been added. I recently upgraded to v2.1.1. Is it a bug?

**Comment by GrahamCampbell** [comment]
Can you provide us with the log file please?

**Comment by compscinoob** [comment]
The error is caused by my misconfiguration of the mail .env
[2016-02-17 22:14:38] production.ERROR: exception 'Swift_TransportException' with message 'Failed to authenticate on SMTP server with username
I apologize. It tries to send out the verification email and is unable to so because I didn't finish configuring the .env file; that's why I get the 500.

**Comment by InfoSecured** [comment]
I get this problem too on 2.4 however I'm able to successfully send a test message.  When I add a subscriber through the dashboard or a subscriber using the subscribe link, I get an error 500.

**Comment by jbrooksuk** [comment]
@InfoSecured can you open a new issue and provide the latest log file please. You can find the logs in `./storage/logs`.

**Comment by tmburger** [comment]
I know this issue was closed but I couldn't bring myself to open a new ticket for this issue.  I am getting the same 500 error and it is clearly because I have not supplied a username and password.  Does cachet not support sending mail through an allowed relay without auth?

**Comment by Atriusftw** [comment]
As far as i know, authentication is required for mailing.
