### ISSUE TITLE
Edit an incident broken

### ISSUE THREAD

**Issue by peterlaws** [CachetHQ/Cachet#1528]
Does this version state the actual version under Settings? 

I tried to update with 'git pull', it listed all versions, then stated "Already up-to-date.".

But I see no version under settings? Am I going mad?

I'm trying to update because when I edit an incident, I get

> production.ERROR: exception 'AltThree\Validator\ValidationException' with message 'Validation has failed.' in /var/www/Cachet/vendor/alt-three/validator/src/ValidatingObserver.php:89
Validation errors:
The status field is required.

**Comment by jbrooksuk** [comment]
Have you ran `php artisan app:update`?

**Comment by peterlaws** [comment]
php artisan app:update
>Publishing complete for tag []!
Nothing to migrate.
Clearing cache...
Application cache cleared!
Cache cleared!

tag shouldn't be empty?

**Comment by GrahamCampbell** [comment]
> tag shouldn't be empty?

No, that's totally fine for that to be empty.

**Comment by peterlaws** [comment]
Ok, so, what could be the issue for me to update to 2.1?

**Comment by jbrooksuk** [comment]
Are you doing this from the dashboard or API?

**Comment by peterlaws** [comment]
Still trying to upgrade, I'm at a loss, unless i delete everything in the Cachet folder apart from the .env file then try a pull?..... I'm sure I'm not using 2.1... Been a while since I upgraded

If you mean the error, editing an opened incident via dashboard - not sure which version I'm currently using!

**Comment by jbrooksuk** [comment]
Incident updated here on the 2.1 branch 

![image](https://cloud.githubusercontent.com/assets/246103/13196737/0718e06c-d7cf-11e5-8df7-9cd36b8109bb.png)

**Comment by peterlaws** [comment]
As you can see, the status is selected, but still states it's not...... Also, how do I get the version number or hash, I forgotten

![cachet](https://cloud.githubusercontent.com/assets/9319293/13196760/9274fd30-d7cf-11e5-804f-e5d97dce8b6d.png)

**Comment by peterlaws** [comment]
Ok so, I took my own advice and tried to start fresh with my .env, but during 'composer install --no-dev -o' I get:

> PHP Fatal error:  Uncaught exception 'ReflectionException' with message 'Class config does not exist' in /var /www/Cachet/vendor/laravel/framework/src/Illuminate/Container/Container.php:738

**Comment by peterlaws** [comment]
Ok, scrub that..... I copied back my .env too soon, but now I get the same error when doing 'php artisan key:generate', and when visiting the url, I get:

>  production.ERROR: exception 'InvalidArgumentException' with message 'Database (/var/www/Cachet/storage/database.sqlite) does not exist.' in /var/www/Cachet/vendor/laravel/framework/src/Illuminate/Database/Connectors/SQLiteConnector.php:34

I'm beginning to think if this will happen every time I upgrade (or try to), then Cachet isn't for me

**Comment by GrahamCampbell** [comment]
> production.ERROR: exception 'InvalidArgumentException' with message 'Database (/var/www/Cachet/storage/database.sqlite) does not exist.' in /var/www/Cachet/vendor/laravel/framework/src/Illuminate/Database/Connectors/SQLiteConnector.php:34

You need to either create that file, or use a different database driver. This is a not a bug in Cachet.

**Comment by peterlaws** [comment]
But I was using mysql from the start, so I'm not sure what gives

>DB_DRIVER=mysql
...
CACHE_DRIVER=file
SESSION_DRIVER=file
QUEUE_DRIVER=database

**Comment by GrahamCampbell** [comment]
Is the file called .env.example? If so, it needs to be called .env.

**Comment by peterlaws** [comment]
I copied my own .env back into the directory after I used composer, even tried artisan config:clear too.

**Comment by GrahamCampbell** [comment]
Maybe try restarting php-fpm. It's probably cached the compiled config file in memory.

**Comment by jbrooksuk** [comment]
@CachetHQ/owners can you guys confirm this?

**Comment by jbrooksuk** [comment]
I cannot replicate this at all. Let me know if this is still ongoing.
