### ISSUE TITLE
Class config does not exist

### ISSUE THREAD

**Issue by okaufmann** [CachetHQ/Cachet#1530]
Hi,

As i checkout the newest tag via git and had installed the composer packages, i got the following error:

```
Fatal error: Uncaught exception 'ReflectionException' with message 
'Class config does not exist' in vendor/laravel/framework/src/Illuminate/Container/Container.php:738
```
Now I'm back on v2.0.4 where it works fine. Are there any upgrade steps I missed ?

**Comment by jbrooksuk** [comment]
In your `.env` file do you have any spaces in any of the values? You need to double quote them please.

For example:

```
...
MAIL_FROM=Cachet Demo
...
```

Should now become:

```
...
MAIL_FROM="Cachet Demo"
...
```
