### ISSUE TITLE
The requested URL /setup was not found on this server.

### ISSUE THREAD

**Issue by sixteeN11** [CachetHQ/Cachet#1531]
Hi,

after the installation of Cachet it shows on my statuspage:
The requested URL /setup was not found on this server.

/var/www/cachet/public# ls l
total 40
132320 4 drwxr-xr-x  6 www-data www-data 4096 Feb 19 23:21 .
131961 4 drwxr-xr-x 12 www-data www-data 4096 Feb 19 23:31 ..
132322 4 drwxr-xr-x  3 www-data www-data 4096 Feb 19 23:21 build
132329 4 drwxr-xr-x  2 www-data www-data 4096 Feb 19 23:21 dist
132331 4 -rw-r--r--  1 www-data www-data 1034 Feb 19 23:21 favicon.ico
132332 4 drwxr-xr-x  2 www-data www-data 4096 Feb 19 23:21 fonts
132321 4 -rw-r--r--  1 www-data www-data  412 Feb 19 23:21 .htaccess
132337 4 drwxr-xr-x  2 www-data www-data 4096 Feb 19 23:21 img
132356 4 -rw-r--r--  1 www-data www-data 1859 Feb 19 23:21 index.php
132357 4 -rw-r--r--  1 www-data www-data   24 Feb 19 23:21 robots.txt

there is no "setup" directory.

Could you help me, please?

**Comment by jbrooksuk** [comment]
You're not using mod_rewrite properly.

https://docs.cachethq.io/docs/installing-cachet

**Comment by sixteeN11** [comment]
# a2enmod rewrite
Module rewrite already enabled

**Comment by jbrooksuk** [comment]
You need to setup your Virtual Hosts, see the documentation please.

**Comment by sixteeN11** [comment]
000-default.conf
DocumentRoot /var/www/cachet/public


i do..

**Comment by sixteeN11** [comment]
i have reinstalled all.

IT WORKS!
