### ISSUE TITLE
Incidents API throws error

### ISSUE THREAD

**Issue by jaxxstorm** [cachethq/cachet#154]
I'm working my way through the API endpoints listed here: https://github.com/cachethq/Cachet/blob/22d54cf05f78ffdad761dfdea382e75ca5133f4a/app/routes/api.php

And most work. However, when trying to list incidents, I get the following error:

```
curl -XGET http://localhost/api/incidents

Symfony \ Component \ Debug \ Exception \ FatalErrorException (E_ERROR) 
Call to a member function getTransformer() on a non-object
Open: /var/www/html/status/app/CachetHQ/Cachet/Transformers/IncidentTransformer.php
use League\Fractal\TransformerAbstract;

class IncidentTransformer extends TransformerAbstract
{
    public function transform(Incident $incident)
    {
        $component = $incident->component;
        $transformer = $component->getTransformer();

        return [
```

Valid issue, or have I done something else wrong? :)

**Comment by tomer-h** [comment]
Hi, not sure if this is another incident creation issue or something stupid that I'm doing, whenever I POST to create an incident via the API, I get a redirect.

Example curl:
curl -X POST -H "Content-Type: application/json" -H "X-Cachet-Token: SECRET" http://myurl.com/incidents -d '{"name":"Test","message":"Test message","status":"1"}'

The response I get is:
<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8" />
        <meta http-equiv="refresh" content="1;url=http://myurl.com" />

        <title>Redirecting to http://myurl.com</title>
    </head>
    <body>
        Redirecting to <a href="http://myurl.com">http://myurl.com</a>.
    </body>
</html>

Issue occurs with all the possible payload options, and also only with the necessary once. Would appreciate your input.

**Comment by jbrooksuk** [comment]
@tomer-h the API endpoint is `http://myurl.com/api/incidents`.

**Comment by tomer-h** [comment]
SO glad I did not open a new issue. Thank you very much.

**Comment by jbrooksuk** [comment]
My pleasure :smile:
