### ISSUE TITLE
Setup seems to be broken?

### ISSUE THREAD

**Issue by KeiroD** [CachetHQ/Cachet#1540]
Before submitting your issue, please make sure that you've checked all of the checkboxes below.

- [x] You're running the [latest release](https://github.com/CachetHQ/Cachet/releases/latest) version of Cachet.
- [x] Ensure that you're running at least PHP 5.5.9, you can check this by running `php -v`
- [x] You've ran `rm -rf bootstrap/cache/*` from the root of your Cachet installation.

```
eidolon@eidolonhost:~/web/status.seola.tech/public_html/Cachet$ git status
HEAD detached at v2.1.2
root@eidolonhost:/home/eidolon/web/status.seola.tech/public_html/Cachet/storage/logs# php -v
PHP 5.5.32-1+deb.sury.org~trusty+1 (cli) (built: Feb  5 2016 10:07:16) 
Copyright (c) 1997-2015 The PHP Group
Zend Engine v2.5.0, Copyright (c) 1998-2015 Zend Technologies
    with the ionCube PHP Loader + Intrusion Protection from ioncube24.com (disabled) v5.0.7, Copyright (c) 2002-2015, by ionCube Ltd.
    with Zend OPcache v7.0.6-dev, Copyright (c) 1999-2015, by Zend Technologies
```
Not exactly cutting edge, but I figure this should be OK... **for now**. It appears Cachet is working for the most part... and I don't think the php version is at issue here.

To help us better understand your issue, please answer the following — cheers!

### Expected behaviour

*Please describe what you're expecting to see happen.*

I'm expecting to see a working Setup screen.

### Actual behaviour

Setup screen seems to be partially there but mostly is broken.

### Steps to reproduce

Visit http://status.seola.tech/Cachet/public/setup

**Comment by GrahamCampbell** [comment]
You've incorrectly setup your server. You can't include the /public part in the url, or /cachet.

**Comment by KeiroD** [comment]
So you need to have it be something else? For example, /system would work, I hope?

**Comment by KeiroD** [comment]
Got it.

**Comment by jbrooksuk** [comment]
:+1: 

For reference, https://docs.cachethq.io/docs/installing-cachet#running-cachet-on-apache
