### ISSUE TITLE
Creating resolved incident doesn't cause Cachet to mark page as clear.

### ISSUE THREAD

**Issue by KeiroD** [CachetHQ/Cachet#1541]
Before submitting your issue, please make sure that you've checked all of the checkboxes below.

- [x] You're running the [latest release](https://github.com/CachetHQ/Cachet/releases/latest) version of Cachet.
- [x] Ensure that you're running at least PHP 5.5.9, you can check this by running `php -v`
- [x] You've ran `rm -rf bootstrap/cache/*` from the root of your Cachet installation.

*Running v2.1.2
*Note that running rm -rf bootstrap/cache/* broke my install for some reason. Running `php artisan config:cache` cleared up the issue.

To help us better understand your issue, please answer the following — cheers!

### Expected behaviour

Correctly resolve "Some systems are experiencing issues", as seen on http://status.seola.tech

### Actual behaviour

System is still showing "Some systems are experiencing issues" despite following #790, specifically, [this comment](https://github.com/CachetHQ/Cachet/issues/790#issuecomment-119369844).

### Steps to reproduce

Create new incident. Set to performance issues, specify test message, test subject.

See: 
![screenshot from 2016-02-21 17 43 58](https://cloud.githubusercontent.com/assets/3938118/13206398/b5d8740c-d8c2-11e5-9174-5661ca5e630c.png)

Then mark as resolved in second incident:

![screenshot from 2016-02-21 17 44 39](https://cloud.githubusercontent.com/assets/3938118/13206401/cd465e56-d8c2-11e5-8377-a5507b1a8853.png)

I'm aware that this is still a WIP as per #715 but... is there anything else that I'm maybe missing?

**Comment by GrahamCampbell** [comment]
> *Note that running rm -rf bootstrap/cache/ broke my install for some reason. Running php artisan config:cache cleared up the issue.

Always run `php artisan app:update` rather than any of laravel's native commands. For example, never run the artisan migration commands.

**Comment by KeiroD** [comment]
Ah, gotcha. I'll do that, next time.

I'm not sure if that'd contribute to the incidents not working as you guys intended, but I suspect probably not.

**Comment by jbrooksuk** [comment]
This is because your components are listed with a status that isn't "Operational". This is something we'll be changing for V3. Since this is already covered in #1176, I'm going to close the issue.

**Comment by KeiroD** [comment]
@jbrooksuk but if you look at the screenshot, specifically the second one in the OP, it's listed as "Operational"?

If marking it as Operational's supposed to fix it, why is it not marked as fixed? Exactly how is one supposed to resolve this? Because I had seen the comment in the other issues that were opened and I had noted that I had done this and screenshotted me doing this with the obvious behavior not working as expected.

Also, components screen:

![screenshot from 2016-02-22 03 27 09](https://cloud.githubusercontent.com/assets/3938118/13214273/3ea1230a-d914-11e5-845f-ed46f2153761.png)
