### ISSUE TITLE
component timestamp

### ISSUE THREAD

**Issue by gfernandez83** [CachetHQ/Cachet#1544]
### Expected behaviour

created_at and updated_at should have different timestamp? 

### Actual behaviour

I created some components and tried to update it and I notice that created_at and updated_at are always the same. Is that the normal behavior?

**Comment by jbrooksuk** [comment]
Are you using the API? When updating a component from the dashboard, I can see that `updated_at` is different from `created_at`.

**Comment by gfernandez83** [comment]
yes, but if look at the db, they are the same timestamp. as well as when you query incidents, components and metrics using api. 

update using API:
{"data":{"id":9728,"name":"prod.ab5560.com","description":"returned with status code 0","link":"http:\/\/prod.ab5560.com","status":1,"order":0,"group_id":1,"enabled":true,"created_at":"2016-02-23 09:38:06","updated_at":"2016-02-24 02:39:50","deleted_at":null,"status_name"

query using API:
{"data":{"id":9728,"name":"prod.ab5560.com","description":"returned with status code 0","link":"http:\/\/prod.ab5560.com","status":"1","order":0,"group_id":1,"enabled":true,"created_at":"2016-02-24 02:39:50","updated_at":"2016-02-24 02:39:50","deleted_at":null,"status_name":"Operational"}}

from DB:
mysql> select * from components where id=9728;

mysql> select * from components where id=9728\G
*************************** 1. row ***************************
         id: 9728
       name: prod.ab5560.com
description: returned with status code 0
       link: http://prod.ab5560.com
     status: 1
      order: 0
   group_id: 1
    enabled: 1
 created_at: 2016-02-24 02:39:50
 updated_at: 2016-02-24 02:39:50
 deleted_at: NULL
1 row in set (0.00 sec)

**Comment by jbrooksuk** [comment]
Ping @GrahamCampbell, is this the expected behaviour of Laravel?
