### ISSUE TITLE
Ability to associate metric with component

### ISSUE THREAD

**Issue by robkooper** [CachetHQ/Cachet#1546]
It would be nice to be able to associate a metric with a component. This would allow me to query the API to see a component and see the metrics associated with that component. This would potentially help with #1451 which would allow the GUI to show a group of components as well as all metrics/graphs associated with that component group.

**Comment by jbrooksuk** [comment]
Thank you for your input on Cachet 2.x. We are shifting our attention and resources to Cachet 3.x and will no longer be supporting the 2.x version. If your feedback or issue is relevant to the 3.x series, we encourage you to engage with the new branch.

For more information on the Cachet rebuild and our plans for 3.x, you can read the announcement [here](https://github.com/CachetHQ/Cachet/discussions/4342).

We appreciate your understanding and look forward to your contributions to the new version.
