### ISSUE TITLE
Ability to subscribe to component group

### ISSUE THREAD

**Issue by robkooper** [CachetHQ/Cachet#1547]
It would be nice to subscribe to a component group and get emails. Right now I can either get everything or a specific component.

**Comment by jbrooksuk** [comment]
@joecohens I completely forgot about this! We should've made this part of the Subscriber refactor. Doh!

**Comment by peelman** [comment]
You kinda sorta get this behavior in #1983.  Using the select / deselect all links you can pick and choose groups a little easier.

**Comment by jbrooksuk** [comment]
@peelman yeah, but now the issue is that if a component gets added to a group, you won't be automatically subscribed to it.

Good work around for now though.

**Comment by jbrooksuk** [comment]
Thank you for your input on Cachet 2.x. We are shifting our attention and resources to Cachet 3.x and will no longer be supporting the 2.x version. If your feedback or issue is relevant to the 3.x series, we encourage you to engage with the new branch.

For more information on the Cachet rebuild and our plans for 3.x, you can read the announcement [here](https://github.com/CachetHQ/Cachet/discussions/4342).

We appreciate your understanding and look forward to your contributions to the new version.
