### ISSUE TITLE
Tool Bar on Left side of Cachet Status Page Missing

### ISSUE THREAD

**Issue by cla777** [CachetHQ/Cachet#1556]
I've worked through the install of Cachet on a Linux box and successfully got it working (accessing the Cachet Status and setup page) (I'm running Cachet 2.1.1).

Problem:
On initial access to the status page, I went through the setup (username, password, etc) but did not create any components or incidents.

Next day I opened my status page, but I cannot do anything.  the tool bar on the left side of the screen is missing.  I've tried opening the status page in IE and Chrome with the same results.

Also, is it possible to add switches or routers to the status page and if so, is there a link to how to do it?

thanks

**Comment by jbrooksuk** [comment]
Can you show us a screenshot of this please?

Your switches/routers are simply components.

**Comment by jbrooksuk** [comment]
Hang on... Cachet doesn't have a toolbar on the side. Closing this till we get more info.

**Comment by cla777** [comment]
My error.  I was looking at the status page.  Once I figured out how to access the dashboard, I was able to access the options on the left of the screen.  Sorry.

**Comment by jbrooksuk** [comment]
:+1:
