### ISSUE TITLE
How to invite new member on Cachet 2.2.0-dev

### ISSUE THREAD

**Issue by MiteshShah** [CachetHQ/Cachet#1557]
Before submitting your issue, please make sure that you've checked all of the checkboxes below.

- [x] You're running the [latest release](https://github.com/CachetHQ/Cachet/releases/latest) version of Cachet.
- [x] Ensure that you're running at least PHP 5.6.18, you can check this by running `php -v`
- [x] You've ran `rm -rf bootstrap/cache/*` from the root of your Cachet installation.

To help us better understand your issue, please answer the following — cheers!

### Expected behaviour

1. When we open https://demo.cachethq.io/dashboard/team theer is Invite New Member button on top right side.

### Actual behaviour

1. No invite New Member button on top right side.

### Steps to reproduce

*If your issue requires any specific steps to reproduce, please outline them here.*

**Comment by MiteshShah** [comment]
Mark as fixed 
Issue as login as non-admin user :(

**Comment by jbrooksuk** [comment]
> Issue as login as non-admin user :(

Yeah, security :)
