### ISSUE TITLE
Sort Incidents per pages

### ISSUE THREAD

**Issue by qk4l** [CachetHQ/Cachet#1563]
Hello, I'm writing Zabbix-Cachet integration and want to change component status by creating and updating incidents. Just because I don't want to use any additional storage for this I assume that last incident with particular component_id is the last registered state that have delivered from Zabbix to Cachet.

And here is the problem:
Cachet returns incidents in non sorted order. And because there is no way to filter incidents by component_id (via API) I must read _all pages_ with incidents, sorted them and only then find the last one.

### Expected behavior

Returning incident in sorted order per pages.
For example:
   page1: id 1-20
   page2: id 20-40

### Actual behavior

Incidents returning in by non knowing algorithm
For example:
   page1: id: 202, 207, 174
   page2: id: 179, 199, 200
   page3: id: 206, 195

**Comment by jbrooksuk** [comment]
This is fixed in v2.2.0

Should be arriving this weekend.
