### ISSUE TITLE
Add Client Library to Doc List: Ruby

### ISSUE THREAD

**Issue by TheFynx** [CachetHQ/Cachet#1564]
It's not a 100% yet, it will be in beta tomorrow (I'll push the gem out to rubygems). But I have started a pretty full featured API wrapper for the Cachet API in ruby.

https://github.com/TheFynx/cachet_api 

For the most part, everything works as expected. Having other library issues (json) when deleting items. 

By the end of the week I'll have some fully fledged examples and eventually a program that utilizes it for sharing (doing integration work with pagerduty and newrelic).

**Comment by jzielke** [comment]
I ended up creating for .Net - Not sure if anyone would interested in it.

**Comment by TheFynx** [comment]
gem url: https://rubygems.org/gems/cachet_api pre-release is available.

**Comment by jbrooksuk** [comment]
Done :) https://docs.cachethq.io/docs/client-libraries
