### ISSUE TITLE
Improve Y axis scaling

### ISSUE THREAD

**Issue by spencerhance** [CachetHQ/Cachet#1569]
It would be nice if the Y axis could adjust its scale so that a metric with consistent values didn't just fill up the graph (e.g. whitespace above the points).  In this example, some of the points are also being cut off because they are so close to the top. 

![image](https://cloud.githubusercontent.com/assets/9636457/13357634/4785373c-dc79-11e5-8b5d-57bee9bac443.png)

**Comment by GrahamCampbell** [comment]
This looks like a bug with the graph library. Please take it up with them.

**Comment by jbrooksuk** [comment]
For reference that's https://github.com/nnnick/Chart.js/
