### ISSUE TITLE
Improve readability and scaling of metrics

### ISSUE THREAD

**Issue by SydoxX** [CachetHQ/Cachet#1571]
### The Problem
When selecting a data point of a metric, the selection range is too big so that multiple dialogues open which makes the additional information unreadable. Also, on the phone the hourly data points are too close together.
##### Desktop
![spacing](https://cloud.githubusercontent.com/assets/6787349/13364421/00aa233a-dccf-11e5-9bd3-6f0d41dc70d8.png)

##### Android Phone

![screenshot_20160226-103955](https://cloud.githubusercontent.com/assets/6787349/13364568/d3f3cf70-dccf-11e5-9699-a413cc3e1075.png)

**Comment by jbrooksuk** [comment]
This is more of an issue with Chart.js
