### ISSUE TITLE
Configuring Components with Metrics

### ISSUE THREAD

**Issue by cla777** [CachetHQ/Cachet#1572]
I'm in the process of reviewing cachet for possible integration into our environment and needs some assistance.

I've been searching for documentation to help with setting up components and metrics.  I've not been able to locate anything beyond the basic instructions.

I setup a Splunk component to monitor the status of our Splunk server and a component to monitor one of our wiki pages.  I created two metrics with the following settings:
up-status
  suffix: status
  metrics: sum
  default view: last 12 hours
  default value: 0
  decimal places: 1
  display chart: yes
visitors
  suffix: visitors
  metrics: sum
  default view: last 12 hours
  default value: 0
  decimal places: 1
  display chart: yes

The status page displays fine with the specified charts, but absolutely no data (flat lined chart).  I suspect I'm missing a piece that ties the specified metrics to the components.  But I can't locate any information on it.  

The results I'm looking for are:
*If we get 'x' visitors to our wiki page, the cachet component would reflect that
*if the Splunk server is restarted or rebooted, cachet would reflect that (ie reflect the current status of the Splunk server).

I need some help bringing the pieces together.  thanks

**Comment by jbrooksuk** [comment]
You need to manually send the metrics data. Cachet doesn't monitor anything.

**Comment by cla777** [comment]
Is there any examples / documentation / procedures for the metrics data piece?

**Comment by jbrooksuk** [comment]
See https://docs.cachethq.io/docs/addons

**Comment by anshk-vcloudx** [comment]
You need to add   PUSH METRICS under action like
action:
      - PUSH_METRICS
    and put   latency_unit: ms
in config.yml
