### ISSUE TITLE
Documentation: Missing Requirement or Code Issue?

### ISSUE THREAD

**Issue by TheFynx** [CachetHQ/Cachet#1574]
Before submitting your issue, please make sure that you've checked all of the checkboxes below.

- [X] You're running the [latest release](https://github.com/CachetHQ/Cachet/releases/latest) version of Cachet. (Utilizing Demo)
- [ ] Ensure that you're running at least PHP 5.5.9, you can check this by running `php -v`
- [ ] You've ran `rm -rf bootstrap/cache/*` from the root of your Cachet installation.

To help us better understand your issue, please answer the following — cheers!

### Expected behaviour

To create a metric with the 4 listed required options.

Note: Not sure if the documentation just needs to be updated or the code needs a default value added?

```
name:
required

suffix:
required

description:
required

default_value:
required

display_chart:

```

### Actual behaviour
Get this when trying to not pass `display_chart`, tested via https://docs.cachethq.io/docs/metrics to be sure it was not my code.

![image](https://cloud.githubusercontent.com/assets/5805780/13408648/9316954c-def4-11e5-81a0-982a7a0840df.png)

and with `display_chart`

![image](https://cloud.githubusercontent.com/assets/5805780/13408710/d2b51a52-def4-11e5-9468-911fe40bfcbe.png)

### Steps to reproduce

Go to https://docs.cachethq.io/docs/metrics and try to create metric without `display_chart`

**Comment by jbrooksuk** [comment]
`display_chart` is a boolean, so pass it true or false. I'll set the default to `true`.

**Comment by TheFynx** [comment]
is it? in the documentation and my testing it responds as 0/1 (off/on), actually there are a few that respond that way. I think collapsed is the other one?

**Comment by jbrooksuk** [comment]
Yeah 0 = false, 1 = true. It's boolean logic.

**Comment by TheFynx** [comment]
Good deal, I just know some have true/false to pass and other 0/1 so wanted to be sure :-)

**Comment by jbrooksuk** [comment]
It's all the same :) the documentation should be consistent though.
