### ISSUE TITLE
API Error: Component Group Create

### ISSUE THREAD

**Issue by TheFynx** [CachetHQ/Cachet#1575]
Before submitting your issue, please make sure that you've checked all of the checkboxes below.

**Using Demo** 

To help us better understand your issue, please answer the following — cheers!

### Expected behaviour

Create Component Group where collapsed is false

### Actual behaviour

Can only create group where component group is collapse.

Set `collapsed` to false
![image](https://cloud.githubusercontent.com/assets/5805780/13410608/5d0e2938-defe-11e5-9545-835d4cae9d8a.png)

set `collapsed` to true
![image](https://cloud.githubusercontent.com/assets/5805780/13410638/7f6f1122-defe-11e5-939b-7a9976a28179.png)

### Steps to reproduce

Try to create a group via api with collapsed set to false

**Comment by jbrooksuk** [comment]
It's all worked using Paw:

![image](https://cloud.githubusercontent.com/assets/246103/13411291/30590030-df34-11e5-92fe-9cc8783665f7.png)

**Comment by TheFynx** [comment]
Ahh, then documentation probably needs to be updated. I see in PAW your doing 0/1 essentially. I just switched my tests to that and it works. But passing an actually true/false throws it off.

collapsed:	Boolean  false
Whether to collapse the group by default
