### ISSUE TITLE
[API] cannot schedule a maintenance through the API

### ISSUE THREAD

**Issue by ScottMGerstl** [CachetHQ/Cachet#1576]
Before submitting your issue, please make sure that you've checked all of the checkboxes below.

- [ ] You're running the [latest release](https://github.com/CachetHQ/Cachet/releases/latest) version of Cachet.
- [ ] Ensure that you're running at least PHP 5.5.9, you can check this by running `php -v`
- [ ] You've ran `rm -rf bootstrap/cache/*` from the root of your Cachet installation.

- [x] Running online version

To help us better understand your issue, please answer the following — cheers!

### Expected behaviour

create a scheduled maintenance at the time specified

### Actual behaviour

creates an incident now

### Steps to reproduce

**send**
{
    "name": "test maintenance",
    "status": "0",
    "message": "test message",
    "scheduled_at": "2016-03-03 20:00:00"
}

**receive**
{
  "data": {
    "name": "test maintenance",
    "status": "0",
    "message": "test message",
    "visible": 1,
    "updated_at": "2016-02-29 21:05:58",
    "created_at": "2016-02-29 21:05:58",
    "id": 21,
    "notify": true,
    "human_status": "Scheduled",
    "component": null,
    "scheduled_at": "2016-02-29 21:05:58"
  }
}

**Comment by jbrooksuk** [comment]
We don't actually have an API for scheduling maintenance.

**Comment by jbrooksuk** [comment]
This is going to be fixed in https://github.com/CachetHQ/Cachet/pull/1652
