### ISSUE TITLE
PHP Fatal Error During Install

### ISSUE THREAD

**Issue by TheoBearman** [CachetHQ/Cachet#1577]
Before submitting your issue, please make sure that you've checked all of the checkboxes below.

- [ ] You're running the [latest release](https://github.com/CachetHQ/Cachet/releases/latest) version of Cachet.
- [x] Ensure that you're running at least PHP 5.5.9, you can check this by running `php -v`
- [x] You've ran `rm -rf bootstrap/cache/*` from the root of your Cachet installation.

To help us better understand your issue, please answer the following — cheers!

### Expected behaviour

A normal install with the `composer install -o` command.

### Actual behaviour

![cdcs](https://cloud.githubusercontent.com/assets/6546590/13420719/773f19ac-df80-11e5-90e1-f322e818970d.JPG)

### Steps to reproduce

None other than normal.

**Comment by jbrooksuk** [comment]
Run `rm -rf boostrap/cache/*`

**Comment by TheoBearman** [comment]
Did that and re-ran `composer install -o`. The same error is appearing.

**Comment by jbrooksuk** [comment]
Run the following:

1. `composer self-update`
2. `composer clear-cache`
3. `rm -rf vendor`
4. `composer install`

**Comment by TheoBearman** [comment]
Done all of it. Still have the same error.

**Comment by jbrooksuk** [comment]
Ping @GrahamCampbell?

**Comment by TheoBearman** [comment]
Anything?

**Comment by GrahamCampbell** [comment]
> Run rm -rf boostrap/cache/*

**Comment by GrahamCampbell** [comment]
Specifically, there will be a services file in there that needs removing.

**Comment by GrahamCampbell** [comment]
Is app/config in sync with our version?

**Comment by GrahamCampbell** [comment]
Specifically, the app.php file.

**Comment by TheoBearman** [comment]
My install is up to date with the `master` branch. I have run `rm -rf boostrap/cache/*` with no success.

**Comment by GrahamCampbell** [comment]
Did you try restarting php-fpm?

**Comment by GrahamCampbell** [comment]
> Is this something to do with native throttling?

Not really.

**Comment by TheoBearman** [comment]
Apparently, I don't have php-fpm (or php5-fpm) installed.

**Comment by GrahamCampbell** [comment]
Meh, just reboot the server. :P

**Comment by GrahamCampbell** [comment]
I think php is caching the files in memory in their "compiled" state, so not loading the new files.

**Comment by TheoBearman** [comment]
I have rebooted my server and I am still getting the same error when I run `composer install -o`.

Happy to let you take a look through TeamViewer if you can. Alternatively, would a fresh install correct the error?

**Comment by GrahamCampbell** [comment]
> Alternatively, would a fresh install correct the error?

I assume so. It's odd since our demo isn't affected by this, and all we do there is pull in the new code and run composer install each time.

**Comment by TheoBearman** [comment]
It worked.
