### ISSUE TITLE
Dashbaord Links Not Reflecting Site URL setting

### ISSUE THREAD

**Issue by mjseid** [CachetHQ/Cachet#1581]
Before submitting your issue, please make sure that you've checked all of the checkboxes below.

- [ ] You're running the [latest release](https://github.com/CachetHQ/Cachet/releases/latest) version of Cachet.
- [x] Ensure that you're running at least PHP 5.5.9, you can check this by running `php -v`
- [x] You've ran `rm -rf bootstrap/cache/*` from the root of your Cachet installation.

To help us better understand your issue, please answer the following — cheers!

### Expected behaviour

Im deploying the latest tagged release in the docker repository (v2.0.4) via docker-compose following the instructions here: https://docs.cachethq.io/docs/get-started-with-docker

I need to install Cachet behind a reverse proxy and I expected that setting the Site URL to \<myproxyalias> would cause the links on the dashboard (ex Incidents, Components, Settings) to redirect to \<myproxyalias>/dashboard/settings instead of \<ipofmyserver>/dashboard/settings

### Actual behaviour

The Links on the dashboard redirect to the IP/dns of the server rather than my proxy url.

### Steps to reproduce

Set the Site URL to http://example.com.  Go to the dashboard and verify the page links for settings points to \<ipofserver>/dashboard/settings

**Comment by mjseid** [comment]
I've also tried manually updating the APP_URL In .env and then running ` php artisan config:cache` but the generated links still point to the local ip.

**Comment by djdefi** [comment]
Hey there! 

We have updated the docker images to [2.1.2](https://github.com/CachetHQ/Docker/tree/v2.1.2) - Nginx has broken out into a seperate container to better support custom configurations as of https://github.com/CachetHQ/Docker/pull/46 - Can you give this version a try and let us know if the issue still occurs?
