### ISSUE TITLE
Incident List too long

### ISSUE THREAD

**Issue by djtecha** [CachetHQ/Cachet#1585]
Is there a way to limit the number of incidents other then by # of days? Currently, we toggle a new incident about every 10 minutes (bouncing test machines) and the dashboard starts to take a day and a half to load. So it would be handy if I could just say load X number of most recent.

**Comment by GrahamCampbell** [comment]
What are the specs on your machine. Putting a "limit" on the results might not make a large difference.

**Comment by djtecha** [comment]
It's a pretty lightweight machine (an ec2 m1.small). But I have noticed when I set the # of days to 1 no incidents show up and the page loads instantly.

**Comment by GrahamCampbell** [comment]
This is probably a limitation due to the machine specs more than anything else. The load is probably coming from the database.

**Comment by GrahamCampbell** [comment]
Feel free to try adding a load of stuff to our demo to see how it performs. https://demo.cachethq.io/.

**Comment by djtecha** [comment]
I agree the machine isn't spec'd to be that beefy, mainly just cheap here. But I guess this is more of a feature request to let the user limit that list. If there is a better method for filing these requests I would be happy to move this there.

**Comment by GrahamCampbell** [comment]
> If there is a better method for filing these requests I would be happy to move this there.

GitHub is just fine. ;)

**Comment by GrahamCampbell** [comment]
Ping @jbrooksuk.

**Comment by jbrooksuk** [comment]
This isn't something we'll be doing for V2, likely V3 when we refactor the incidents :)

**Comment by jbrooksuk** [comment]
@joecohens this is something to take into consideration with #1595 - closing this though.

**Comment by joecohens** [comment]
@jbrooksuk :+1:
