### ISSUE TITLE
Can't have per compnent-group RSS

### ISSUE THREAD

**Issue by ldidry** [CachetHQ/Cachet#1586]
Before submitting your issue, please make sure that you've checked all of the checkboxes below.

- [X] You're running the [latest release](https://github.com/CachetHQ/Cachet/releases/latest) version of Cachet.
- [X] Ensure that you're running at least PHP 5.5.9, you can check this by running `php -v`
- [X] You've ran `rm -rf bootstrap/cache/*` from the root of your Cachet installation.

To help us better understand your issue, please answer the following — cheers!

### Expected behaviour

It should display a RSS feed with items from the component-group

### Actual behaviour

Error 500

### Steps to reproduce

Ask for `rss/1` (or any valid component group id).

### Log

I got this in my logs:

```
production.ERROR: exception 'ErrorException' with message 'Undefined variable: isRss' in /var/www/cachet/app/Http/Controllers/FeedController.php:83
```

Plus some traces: https://framabin.org/?137775462c86c041#tEGYvUZBd6kLhbFpBITHIBs87fNY1etvgOzplO/dzvI=

**Comment by jbrooksuk** [comment]
Fixed, thanks!
