### ISSUE TITLE
Unable to update or install Cachet

### ISSUE THREAD

**Issue by tomperys** [CachetHQ/Cachet#1587]
Hi,

we are unable to update our Cachet or even install a new one. It always ends with eroor: Script php artisan clear-compiled handling the post-install-cmd event returned with an error

  [RuntimeException]
  Error Output: PHP Fatal error:  Uncaught exception 'ReflectionException' with message 'Class config does not exist' in /va
  r/www/status/www/Cachet/vendor/laravel/framework/src/Illuminate/Container/Container.php:738
  Stack trace:
  #0 /var/www/status/www/Cachet/vendor/laravel/framework/src/Illuminate/Container/Container.php(738): ReflectionCla
  ss->__construct('config')
  #1 /var/www/status/www/Cachet/vendor/laravel/framework/src/Illuminate/Container/Container.php(633): Illuminate\Co
  ntainer\Container->build('config', Array)
  #2 /var/www/status/www/Cachet/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(674): Illuminate
  \Container\Container->make('config', Array)
  #3 /var/www/status/www/Cachet/vendor/laravel/framework/src/Illuminate/Container/Container.php(1178): Illuminate\F
  oundation\Application->make('config')
  #4 /var/www/status/www/Cachet/vendor/laravel/framework/src/Illuminate/Container/Container.php(1223): Illuminate\C
  ontainer\Container->offsetGet('config')
  #5 /var/www/status in /var/www/status/www/Cachet/vendor/laravel/framework/src/Illuminate/Container/Container.ph
  p on line 738

**Comment by GrahamCampbell** [comment]
Looks like you are missing double quotes round an entry in the dotenv file where there are spaces.
