### ISSUE TITLE
No index.php, no setup wizard appears

### ISSUE THREAD

**Issue by mashedkeyboard** [CachetHQ/Cachet#1588]
Before submitting your issue, please make sure that you've checked all of the checkboxes below.

- [x] You're running the [latest release](https://github.com/CachetHQ/Cachet/releases/latest) version of Cachet.
- [x] Ensure that you're running at least PHP 5.5.9, you can check this by running `php -v`
- [x] You've ran `rm -rf bootstrap/cache/*` from the root of your Cachet installation.

To help us better understand your issue, please answer the following — cheers!

### Expected behaviour

Viewing some sort of setup wizard or informational page of some description upon visiting status.test.com

### Actual behaviour

Seeing simply a directory index in the root directory, and the following message when browsing to /public: 

> `make('Illuminate\Contracts\Http\Kernel'); $request = Illuminate\Http\Request::capture(); $response = $kernel->handle($request); $response->send(); $kernel->terminate($request, $response);`

### Steps to reproduce

Just follow the exact steps at https://docs.cachethq.io/docs/installing-cachet on Ubuntu 14.04.3 LTS (GNU/Linux 3.13.0-74-generic x86_64)

**Comment by GrahamCampbell** [comment]
Looks like you don't have PHP installed on your server.

**Comment by GrahamCampbell** [comment]
> and the following message when browsing to /public:

You MUST set public as the root folder.

**Comment by mashedkeyboard** [comment]
`$ php -v
PHP 5.5.9-1ubuntu4.14 (cli) (built: Oct 28 2015 01:34:46)
Copyright (c) 1997-2014 The PHP Group
Zend Engine v2.5.0, Copyright (c) 1998-2014 Zend Technologies
    with Zend OPcache v7.0.3, Copyright (c) 1999-2014, by Zend Technologies`

**Comment by GrahamCampbell** [comment]
PHP is not installed on your "server" though. That's why the php file is getting presented to you as plain text.

**Comment by mashedkeyboard** [comment]
Sorry, I'm not sure I follow - PHP is installed on the server, clearly? Sorry if I'm being stupid.

**Comment by mashedkeyboard** [comment]
Fixed the PHP issues, but now I simply get a blank page with no output whatsoever :/

**Comment by jbrooksuk** [comment]
Follow the installation instructions; https://docs.cachethq.io/docs/installing-cachet
