### ISSUE TITLE
Autoextend when issue occurs

### ISSUE THREAD

**Issue by SydoxX** [CachetHQ/Cachet#1589]
Currently you only have the option to have a component group either extended or collapsed.
It would be nice to have the feature that component groups are only expanded when there is an issue with one of the components in the group and the rest of the time they are kept collapsed. This would increase the overview when everything is alright but still tells the user exactly what is wrong when something isn't right.

![tm2](https://cloud.githubusercontent.com/assets/6787349/13551721/c4f54bbe-e343-11e5-8cd5-b4f3760a70f0.png)
↓
*Problem occurs*
↓
![tm3](https://cloud.githubusercontent.com/assets/6787349/13551723/d8161534-e343-11e5-8ab6-40b2af5ea7f1.png)

**Comment by jbrooksuk** [comment]
V2.2 separates the groups now. See our demo :)
