### ISSUE TITLE
Incident & Component status/mapping

### ISSUE THREAD

**Issue by jaxxstorm** [cachethq/Cachet#159]
After a discussion in gitter, I'd like to propose a change to the incidents status field in order to better map to the component status.

At the moment, components have an "operational status" which determine whether the component is working as expected or is experiencing issues. The thing I've noticed is when you update the "operational status" of an incident, it doesn't update the banner on the dashboard saying "everything is okay"

Incidents also have a "status", but the status is the same field name (in the API at least) but it denotes a different TYPE of status, mainly the progress of the fix.

I would like to propose:

- Changing the current incident status field to something like "progress_status", whereby the progress of resolving the incident is detailed
- Changing the "status" of the incident to be the same as the component status.

That way, when an incident happens, you should be able to select a component that the status affects (as well as leaving it blank, if required) and when the incident is created, it also updates the status of the component, all the way through to resolution.

**Comment by jaxxstorm** [comment]
If you link a component via the API, does it also update the components status?

**Comment by jbrooksuk** [comment]
@jaxxstorm nope, not yet, but we could supply a `component_status` value in the API to update it.

I'm actually going to close this issue; [see why here](https://github.com/cachethq/Cachet/pull/301#issuecomment-68881901). In the incident panel, you'll be able to pick the component then change its status inline (on POST).
