### ISSUE TITLE
PDOException because `cachet.incidents` isn't a thing.

### ISSUE THREAD

**Issue by KiloSierraCharlie** [CachetHQ/Cachet#1592]
### Expected behaviour

Should show the setup page asking how different things should be managed.

### Actual behaviour

500 Internal Server Error

And this in the log (production.ERROR: exception 'PDOException' with message 'SQLSTATE[42S02]: Base table or view not found: 1146 Table 'cachet.incidents' doesn't exist')

This is a brand new install running on MySQL on Windows Server 2012R2 using Apache & PHP7.

**Comment by jbrooksuk** [comment]
- What version are you running?
- Have you ran `php artisan app:install`?

**Comment by KiloSierraCharlie** [comment]
I'm running the current version - "2.2.0-dev"

Yes, I have run the install command, but still no population of tables.

**Comment by TheoBearman** [comment]
Have you verified that your `.env` file database settings are correct?

**Comment by jbrooksuk** [comment]
What if you manually run `php artisan migrate`?

**Comment by KiloSierraCharlie** [comment]
> Have you verified that your .env file database settings are correct?
Yep, I can login to the SQL server and use the DB.

> What if you manually run php artisan migrate?

No change at all - still gives the same error.

**Comment by jbrooksuk** [comment]
Ping @GrahamCampbell
