### ISSUE TITLE
Better Looking Scrollbars

### ISSUE THREAD

**Issue by TheoBearman** [CachetHQ/Cachet#1598]
Could we have some slightly better looking scrollbars for the component groups on the status page? Maybe a mac style scrollbar with the Cachet green?

**Comment by jbrooksuk** [comment]
https://github.com/Charuru/lionbars!

**Comment by TheoBearman** [comment]
Yes. Would be nice.

**Comment by jbrooksuk** [comment]
This was on my todo anyway by the way :)

**Comment by TheoBearman** [comment]
#InSync

**Comment by jbrooksuk** [comment]
![Crunk Crunk](http://i.giphy.com/t4LDxDEtRUnKg.gif)

**Comment by jbrooksuk** [comment]
Closing this, we've removed component scrolling for now and it'll be handled better next time.
