### ISSUE TITLE
Improve components view: columns?

### ISSUE THREAD

**Issue by abioneperhobby** [CachetHQ/Cachet#1599]
sometime a single column view can be too small to permits to view every component status in a single screen.

i think a configuration of cachet that permits to use n colums (max 3?) will be useful.

**Comment by jbrooksuk** [comment]
@joecohens I believe is looking into this. Something I've thought about is making use of flexbox, because we could have it auto flow into a different direction. I'm unsure though.

**Comment by jbrooksuk** [comment]
This isn't actually needed anymore as the component list now scrolls.
