### ISSUE TITLE
feature suggestion : data auto refresh

### ISSUE THREAD

**Issue by abioneperhobby** [CachetHQ/Cachet#1601]
if i want to keep cachet dashboard opened i need to use a browser plugin in order tu automatically refresh page and obtain fresh status.

i think auto refresh will be a useful feature.

**Comment by jbrooksuk** [comment]
Whilst yes, this would be nice, it's not really applicable to people who have a lot of incidents and components (Nestlé for example). If you had 100 incidents and 100 visitors, you're putting a lot of load on the server.

Instead, what you can do in v2.2 (releasing soon) is set a custom header, so you could add a piece of JS to auto reload.

**Comment by abioneperhobby** [comment]
@jbrooksuk great! thanks.

**Comment by anandchida** [comment]
Could adding a cache like redis help? This could also help in updating data via ajax than a page reload.

**Comment by abioneperhobby** [comment]
@jbrooksuk now i can add custom header, but i cannot add script tags because they will be removed. it is normal? 
![image](https://cloud.githubusercontent.com/assets/2149815/14171863/77210a8a-f735-11e5-87aa-d047da534809.png)

**Comment by jbrooksuk** [comment]
Can you open another issue for this please, this is a separate bug.

**Comment by abioneperhobby** [comment]
@jbrooksuk yeah, thanks .

**Comment by lnxslck** [comment]
@jbrooksuk Can you instruct me on how to set up that custom header that auto refreshes the page for every visitor?

**Comment by jbrooksuk** [comment]
```
<meta http-equiv="refresh" content="60">
```

This will refresh the page every 60 seconds.

**Comment by ConnorVG** [comment]
Though I think this is a bit of a silly practice - I imagine someone will (when the plugin system is released) - release some sort of auto-refresh plugin that doesn't reload the entire page. This is a feature that I'd like myself but it doesn't seem like something that should be in core.

**Comment by jbrooksuk** [comment]
That said, we _could_ add it as an option. I'm not opposed to options.

**Comment by lnxslck** [comment]
Thanks @jbrooksuk  

Based on previous posts, I think it would be beneficial if we could have an option on the dashboard, that we could turn ON or OFF auto-refresh of status page or components status.
