### ISSUE TITLE
Expand only Component Groups with open issues

### ISSUE THREAD

**Issue by bjshively** [cachethq/cachet#1605]
### Feature Request

For component groups, provide an option to collapse all groups by default except when some component is in a negative state. For example, a page would load and display like this:

![screen shot 2016-03-10 at 3 54 01 pm](https://cloud.githubusercontent.com/assets/2646312/13684147/6576736e-e6d8-11e5-9611-232c2366ebca.png)
### Current behaviour

Currently there are only two options: expand or collapse by default. These do not consider the current state of the component group.
### Steps to reproduce

N/A

**Comment by jbrooksuk** [comment]
:smile
