### ISSUE TITLE
Usage of absolute links make Cachet unusable on example.com/status

### ISSUE THREAD

**Issue by TheLastProject** [CachetHQ/Cachet#1606]
Before submitting your issue, please make sure that you've checked all of the checkboxes below.

- [X] You're running the [latest release](https://github.com/CachetHQ/Cachet/releases/latest) version of Cachet.
- [X] Ensure that you're running at least PHP 5.5.9, you can check this by running `php -v`
- [X] You've ran `rm -rf bootstrap/cache/*` from the root of your Cachet installation.

To help us better understand your issue, please answer the following — cheers!

### Expected behaviour

Links are relative, so that Cachet also correctly works when put on domains such as example.com/status.

### Actual behaviour

Some of the links are absolute, causing Cachet to lack some of its CSS styling, fail to load JavaScript and have a non-functioning login form when installed to a subdirectory.

https://github.com/CachetHQ/Cachet/blob/master/resources/views/layout/master.blade.php#L50 and https://github.com/CachetHQ/Cachet/blob/master/resources/views/layout/master.blade.php#L50 are two examples, which become respectively `/build/dist/css/all-5f5b94f75a.css` and `/build/dist/js/all-9c19e78dd3.js` for me.

### Steps to reproduce

Make sure you can access Cachet from a subdirectory. For example, you can add an NGINX proxy_pass for example.com/status to point to your Cachet installation.

### Notes

While I understand this implementation for simplicity, at least some documented way to set your Cachet root directory would be a great way to be able to use Cachet on any URL.

Update: Playing around more, I see Cachet has more hardcoded absolute links, such as on the login form, so it is not a Elixir thing.

**Comment by GrahamCampbell** [comment]
You forgot to set the app url in the config.
