### ISSUE TITLE
Dashboard crashes with Symfony exception (incidents page)

### ISSUE THREAD

**Issue by berlic** [CachetHQ/Cachet#1610]
The error is here: https://github.com/CachetHQ/Cachet/blob/master/resources/lang/ru/dashboard.php#L20

Symfony expects array of three standard pluralization rules for Russian and throws InvalidArgumentException in case of error.

One-to-one translation from English gives error on some values (e.g.
5), because there are only two standard rule supplied.

I've submitted my suggestions to https://crowdin.com/translate/cachet/9/en-ru.

If you need a quick-fix, I can create a pull request with this commit.
https://github.com/berlic/Cachet/commit/17c10fb8e357f4acc936c03d058b0c5378ea348d

**Comment by jbrooksuk** [comment]
I'll sync the languages around 12 :)

**Comment by jbrooksuk** [comment]
I've made you a proofreader, so you should be able to accept translations now. If you don't mind updating the Russian files that'd be amazing :heart_eyes:

**Comment by berlic** [comment]
Ok, I'll try to look into it during the week.
I've scrolled through the items and tried to fix all strings with the same issue, so everything else should not be very urgent.

**Comment by jbrooksuk** [comment]
Awesome, thank you @berlic.

**Comment by berlic** [comment]
@jbrooksuk i've done with Russian translation review and marked all strings as approved. Took me a little longer than a week :)

**Comment by jbrooksuk** [comment]
Awesome, thank you. I'll re-build our translations.
