### ISSUE TITLE
Suggestion: Introduce some kind of changelog/release notes

### ISSUE THREAD

**Issue by ManneW** [CachetHQ/Cachet#1611]
I think Cachet is really good, in many different aspects. One of those is that it's actively maintained and extended, but this might lead to other challenges.

I've looked through the repository, but haven't been able to find some kind of changelog or release notes for each release. I know I've seen something along those lines on the ([Alt Three blog](https://blog.alt-three.com/), but it would be great to have this in the repo as well. If not as a dedicated changelog file, at least as notes to each release.

**Maybe I've simply missed it – and if so I'm sorry for taking up your time and polluting the issue tracker ;-)**

Thanks for a great project!

**Comment by GrahamCampbell** [comment]
We put content here: https://github.com/CachetHQ/Cachet/releases.

**Comment by GrahamCampbell** [comment]
Sorry stuff is a bit missing in the latest releases.

**Comment by GrahamCampbell** [comment]
https://github.com/CachetHQ/Cachet/milestones?state=closed might be useful to you too.

**Comment by ManneW** [comment]
Thanks for the swift response, @GrahamCampbell :-)

I added parts of this information to the README.md and created a PR (PR #1612)

**Comment by luiseduardobrito** [comment]
Hey guys, thanks for the great software, really useful for us at our software company in Brazil. In my opinion, the current Release Notes are not enough for deciding when to upgrade our version. 

The main issue for me is knowing how important a new release is to my workflow and whether I should just upgrade asap (security updates, for instance) or if I can plan it in my schedule for some weeks ahead (UI or minor fixes). 

Is there any way of getting this kind of information without looking into the commits log?

**Comment by jbrooksuk** [comment]
@luiseduardobrito thanks for your lovely feedback. In [recent](https://blog.alt-three.com/cachet-v2-2-2/) [blog](https://blog.alt-three.com/cachet-v2-2-1/) [posts](https://blog.alt-three.com/cachet-v2-2-0/) announcing new releases I've included a run down of the changes included in the release.

Does this help in deciding when to upgrade, or do you still require more information?

**Comment by luiseduardobrito** [comment]
@jbrooksuk Thats's exactly what I was looking for! I think it would be great to have this written in the Release Notes as well, it's really useful. Thanks for the response!
