### ISSUE TITLE
Metrics chart shows 3-4 tooltips on hovering data points in last hour

### ISSUE THREAD

**Issue by skddc** [CachetHQ/Cachet#1614]
### Expected behaviour

Show one tooltip of the data point that is hovered.

### Actual behaviour

When hovering a data point in the last-hour resolution, 3-4 tooltips are shown:

![screenshot from 2016-03-15 08-45-25](https://cloud.githubusercontent.com/assets/842/13779728/80162af6-ea8a-11e5-9c86-18d5c69ee662.png)

This is the same in both latest Firefox and Chrome stable releases.

### Steps to reproduce

Record data for every minute, show graph, switch to "last hour" resolution, hover a data point.

**Comment by jbrooksuk** [comment]
I appreciate that this is annoying, but this is the behaviour of [Chart.js](https://github.com/nnnick/Chart.js) can you open this up on their issue tracker please?

**Comment by skddc** [comment]
As long as it's not fixed, even if it's a dependency, it's an issue for this project. It's not just annoying, it basically breaks the chart UI completely for all users looking at the last hour (which is a reasonable default resolution for live performance metrics).

**Comment by skddc** [comment]
By the way, we're using Chart.js in a JS app of ours and it didn't break that way so far.

**Comment by jbrooksuk** [comment]
> By the way, we're using Chart.js in a JS app of ours and it didn't break that way so far.

What configuration are you using? Maybe we're missing something.

**Comment by skddc** [comment]
We're using https://dima117.github.io/Chart.Scatter/ for time scales, as it also provides much nicer, auto-adjusting legends for the x-axis.

**Comment by skddc** [comment]
Also, it won't have non-existing 0-values for minutes that are missing.

**Comment by jbrooksuk** [comment]
I'll happily accept a PR which switches to Chart.Scatter if there is benefit?

**Comment by skddc** [comment]
I don't know enough about how Cachet calculates all those values and I haven't even looked into the code itself. Unfortunately, I don't have time to dig in anytime soon, as I'm involved in too many other OSS projects.

I still think this issue should stay open until the bug is fixed, because those charts are unusable in current master, and it's not clear what the best solution is apparently. So just closing the issue means ignoring it.

**Comment by skddc** [comment]
Just because you yourself can't fix it right now doesn't mean you have to close the issue so it's invisible to other potential contributors. The issue does not lie solely with Chart.js for sure, and even if it does, it's still an issue for this project until it's fixed over there, so closing it also means not being able to keep track of progress over there.

**Comment by jbrooksuk** [comment]
Sure.

I'd still like to see someone contribute a fix to this :+1:
