### ISSUE TITLE
Incident template not filling form when adding scheduled maintenance

### ISSUE THREAD

**Issue by andrekeller** [CachetHQ/Cachet#1620]
### Expected behavior

When I schedule a maintenance, I can select a incident template from the template drop-down and it fills the form with the information from the incident template

### Actual behavior

The incident template can be selected, but the form stays empty.

### Steps to reproduce

- Add an incident template
- Add a scheduled maintenance and try to use the incident template.

**Comment by jbrooksuk** [comment]
Thanks a lot for filing this issue! We'll triage and take a look at it as soon as possible!

I'll likely get this fixed later today.

**Comment by labolanimichele** [comment]
Hey @jbrooksuk , I installed the current 2.4, and this is still not working for me.
Could you please reopen it?
