### ISSUE TITLE
Tooltips within component groups are hidden

### ISSUE THREAD

**Issue by jbrooksuk** [CachetHQ/Cachet#1626]
![image](https://cloud.githubusercontent.com/assets/246103/13842095/4c27a922-ec24-11e5-8c39-81a171ff9f0b.png)

**Comment by jbrooksuk** [comment]
@joecohens this bug also affects #1598 because scrollbars are hidden.

**Comment by jbrooksuk** [comment]
This might be a Chrome issue actually because GitHub is doing the same for me.

**Comment by jbrooksuk** [comment]
Scratch the above.

It's caused by the `overflow-y` setting on `.group-items`.

**Comment by GrahamCampbell** [comment]
I can't see this on the latest chrome and firefox betas.

**Comment by spirou1997** [comment]
Problem still on Chrome (Mac OS X version) and Safari

**Comment by jbrooksuk** [comment]
@GrahamCampbell did you try it in the **Alt Three** group? I'm on latest Chrome beta and it happens for me.

**Comment by GrahamCampbell** [comment]
Must be a Mac bug.

**Comment by GrahamCampbell** [comment]
Upto the browsers to fix this on Mac.

**Comment by jbrooksuk** [comment]
Nope. https://github.com/CachetHQ/Cachet/issues/1626#issuecomment-198956680

**Comment by GrahamCampbell** [comment]
How come it works for me then?

**Comment by GrahamCampbell** [comment]
Either way, we have browser bugs here. It may in fact be a bug that is does display correctly for me.

**Comment by jbrooksuk** [comment]
I'm using Chrome Version 50.0.2661.26 beta (64-bit). Removing that does fix it and it makes sense that it's broken due to the CSS used there.

**Comment by GrahamCampbell** [comment]
Yeh, I see that. It's just very odd that broken stuff is, well. broken at being broken. :P

**Comment by peterlaws** [comment]
I'm seeing this too FYI.... Chrome Version 49.0.2623.87 m

**Comment by meonkeys** [comment]
Yay, thanks!
