### ISSUE TITLE
Suggestion : flag to activate "Last Modified" in Component title

### ISSUE THREAD

**Issue by abioneperhobby** [CachetHQ/Cachet#1627]
if activated,

component will show "last modified" date in title.

Useful to know WHEN a component was updated

**Comment by jbrooksuk** [comment]
We could show a timestamp tooltip on the status text?

**Comment by abioneperhobby** [comment]
thanks @jbrooksuk  . 

Personally i think cachet dashboard as a "monitor" , so it will be better to permits to recognize every useful information without touch anything with the mouse. Anyway also timestamp tool will be appreciated, thanks.

**Comment by jbrooksuk** [comment]
Syncing language files.
