### ISSUE TITLE
Incidents timeline should not show "scheduled at" once it fixed.

### ISSUE THREAD

**Issue by prasad83** [CachetHQ/Cachet#1629]
When a schedule Incident is fixed - on its timeline avoiding "scheduled at" is good.

File: resources/views/partials/incident.blade.php
Workaround check ($incident->humanStatus != 'Fixed') got me the fix.

```php
<strong>{{ $incident->name }}</strong>{{ $incident->isScheduled && $incident->humanStatus != 'Fixed' ? trans("cachet.incidents.scheduled_at", ["timestamp" => $incident->scheduled_at_diff]) : null }}
```

It would be best if it can be shown as "completed on" instead.

**Comment by jbrooksuk** [comment]
This doesn't work unfortunately. Just because the scheduled time has passed, doesn't mean it's fixed. I'm working on a new refactor of the scheduled maintenance. This will fix it.

**Comment by jbrooksuk** [comment]
Closing this as we already have the branch in progress :)
