### ISSUE TITLE
Are emails supposed to be sent when an incident is Fixed?

### ISSUE THREAD

**Issue by meonkeys** [CachetHQ/Cachet#1631]
I marked an incident as "Fixed", but I noticed no emails were sent. Are emails supposed to be sent when an incident is marked as "Fixed"?

If not, is there another way you'd recommend to notify subscribers when an incident is resolved?

If I had to guess, I'd say just report another "incident" to say everything is fixed, and check the box to notify subscribers. Is that correct?

**Comment by GrahamCampbell** [comment]
You need to create a new incident to "update" people of changes. Otherwise, editing the incident should be used to fix mistakes in it only.

**Comment by meonkeys** [comment]
Got it, thanks!

**Comment by jbrooksuk** [comment]
We know that this sucks for everyone, we're working on improving this :)
