### ISSUE TITLE
Random package concerns

### ISSUE THREAD

**Issue by GrahamCampbell** [CachetHQ/Cachet#1633]
We need to wait on the shit storm caused by the random_compat 1.3 release.

**Comment by GrahamCampbell** [comment]
Still a blocker.

**Comment by jbrooksuk** [comment]
It's now 1.4.1, I figured it'd be fixed?

**Comment by GrahamCampbell** [comment]
Nah, we've got a massive problem in that we can't install 2.x because everyone's forcing 1.x everywhere.

**Comment by GrahamCampbell** [comment]
Still waiting on a response from the symfony core team RE this.

**Comment by GrahamCampbell** [comment]
Removing since this is not a blocker after 1.4 was released, but it is still something to watch.

**Comment by jbrooksuk** [comment]
:+1:

**Comment by GrahamCampbell** [comment]
Moving this to a new milestone.
