### ISSUE TITLE
POST to /metrics/:id/points request returns 406 without header Accept: */*

### ISSUE THREAD

**Issue by meonkeys** [CachetHQ/Cachet#1636]
My POST requests to `/metrics/:id/points` appear to require this `Accept` header:

    Accept: */*

This one also works:

    Accept: application/json, */*

If I omit this header or change it to `Accept: application/json`, I get this HTTP 406 response:

````javascript
{
  "errors": [
    {
      "id": "blah-blah-blah-GUID-blah",
      "status": 406,
      "title": "Not Acceptable",
      "detail": "The requested resource is only capable of generating content not acceptable."
    }
  ]
}
````

Is this expected?

**Comment by jbrooksuk** [comment]
@GrahamCampbell isn't this by design?

**Comment by jbrooksuk** [comment]
Thanks for the bug report! Fixed :)
