### ISSUE TITLE
Option to disable component list scrolling

### ISSUE THREAD

**Issue by GrahamCampbell** [CachetHQ/Cachet#1640]
I think it looks silly, and I much prefer what CloudFlare have. I think it's unneeded to "save space" like that. We already have a scroll bar. Why add yet another one inside a page that already scrolls?

**Comment by GrahamCampbell** [comment]
https://www.cloudflarestatus.com/

**Comment by GrahamCampbell** [comment]
Note, their component lists autoexpand on issue.

**Comment by jbrooksuk** [comment]
To be honest, it is creating a few issues. But I wouldn't mind if we fixed it. You wouldn't see the scrollbars once #1598 is implemented anyway.

Ping @joecohens

**Comment by GrahamCampbell** [comment]
Can we revert the scroll bars for now. They look really ugly on firefox/windows.

**Comment by GrahamCampbell** [comment]
https://i.starbs.net/nw0X
