### ISSUE TITLE
500 Internal server error

### ISSUE THREAD

**Issue by karthik-22feb** [CachetHQ/Cachet#1646]
Hi Team,

I am trying to install CACHET on my linux machine. Please find the link below,

http://118.102.216.139/cachet/public/setup

I followed exactly the same steps except configuring the virtualhost, something like http://cachethost.com.

I have installed CACHET on my ‘/var/www/html/cachet’ directory and I get ‘500 Internal server error’.

Please let me know if an missing anything here.

Thanks,
Karthik

**Comment by milanvanschaik** [comment]
I'm also getting a 500. This is the error I got from the logs:
`production.ERROR: exception 'Illuminate\Contracts\Container\BindingResolutionException' with message 'Unresolvable dependency resolving [Parameter #0 [ <required> $path ]] in class GrahamCampbell\Exceptions\ExceptionInfo' in /var/www/../Cachet/vendor/laravel/framework/src/Illuminate/Container/Container.php:824`
I did exactly what was in the installation guide.

@karthik-22feb Is this the same error you got?

**Comment by jbrooksuk** [comment]
@karthik-22feb if setup correctly, you should not be visiting the `./cachet/public/setup` directory. Visit the index page and you'll be directed through to the setup.

@milanvanschaik this may be a different issue for you. Try running `rm -rf bootstrap/cache/*`

**Comment by GrahamCampbell** [comment]
Closing as per the email conversation.
