### ISSUE TITLE
Allow setting non-public postgres schema via .env

### ISSUE THREAD

**Issue by codefx9** [CachetHQ/Cachet#1649]
Hi,
We would like to set non-public schema when using postgres db. It seems that all needs to change is the 
`'schema'    => 'public',`
to 
`'schema'    => env('DB_SCHEMA', 'public'),`
in https://github.com/CachetHQ/Cachet/blob/master/config/database.php#L87 

Is something like this can be added to Cachet? 

-Thanks.

**Comment by jbrooksuk** [comment]
Thanks a lot for filing this issue! Would you like to write a patch for this? We'd be more than happy to walk you through the steps involved.
