### ISSUE TITLE
Propagate activity into a chat service.

### ISSUE THREAD

**Issue by Jamie-Owen** [CachetHQ/Cachet#1651]
Is there any plan to add functionality to allow users to integrate Cachet with a chat service like Slack?

It would be nice if a component changing state or an incident being created triggered a message to a chat channel.

I believe statuspage.io provide this functionality too, see [here](http://help.statuspage.io/knowledge_base/topics/pipe-activity-log-into-slack?from_search=true).

**Comment by jbrooksuk** [comment]
Ah, this is a duplicate of https://github.com/CachetHQ/Cachet/issues/1023
