### ISSUE TITLE
Feature request: per-hour/12hrs/month/week metrics, like "99.95% uptime for the last month"

### ISSUE THREAD

**Issue by meonkeys** [CachetHQ/Cachet#1656]
[SLA](https://en.wikipedia.org/wiki/Service-level_agreement)s generally require visibility into average metrics per some time period. For example: "uptime percentage per month". It would be helpful if Cachet would support reporting metrics in this fashion. Example with "uptime percentage per month" numbers: https://status.heroku.com/uptime .

![status.heroku.com screenshot](https://cloud.githubusercontent.com/assets/50639/14962701/0bc5cbf2-1055-11e6-8bca-be6924b9a175.png)

**Comment by abilto** [comment]
In order to track this would we need to store the operational status with each incident? If we wanted to track the existing incident status (investigating, watching, etc) we could do a SQL query something like this:

```sql
SELECT 
	incidents.created_at AS start_datetime, 
	nextIncident.created_at AS end_datetime, 
	incidents.`status` AS `component_status`, 
	incidents.`component_id` 
FROM 
	incidents 
	INNER JOIN incidents nextIncident 
		ON nextIncident.id > incidents.`id`	
		AND incidents.component_id = nextIncident.component_id 
		AND incidents.status != nextIncident.status 
GROUP BY component_id, start_datetime
```

If the component status was stored there we could track that over time as well.

**Comment by jbrooksuk** [comment]
I don't think that this can be efficientl done until https://github.com/CachetHQ/Cachet/pull/1595 is merged in?

**Comment by mjrussell** [comment]
This would be a great feature. I saw that #1595 is merged, is there any movement on this now?

**Comment by jbrooksuk** [comment]
> This would be a great feature. I saw that #1595 is merged, is there any movement on this now?

It's merged but only into the v3 branch, we're still working on v2.4 first :)

**Comment by alexcurtin** [comment]
any update on this capability?

**Comment by slava-basko** [comment]
up

**Comment by jbrooksuk** [comment]
Thank you for your input on Cachet 2.x. We are shifting our attention and resources to Cachet 3.x and will no longer be supporting the 2.x version. If your feedback or issue is relevant to the 3.x series, we encourage you to engage with the new branch.

For more information on the Cachet rebuild and our plans for 3.x, you can read the announcement [here](https://github.com/CachetHQ/Cachet/discussions/4342).

We appreciate your understanding and look forward to your contributions to the new version.
