### ISSUE TITLE
Editing component groups causes the display order to revert to default behavior in 2.2.0-RC1

### ISSUE THREAD

**Issue by brianjking** [CachetHQ/Cachet#1659]
Before submitting your issue, please make sure that you've checked all of the checkboxes below.

- [x] You're running the [latest release](https://github.com/CachetHQ/Cachet/releases/latest) version of Cachet.
- [x] Ensure that you're running at least PHP 5.5.9, you can check this by running `php -v`
- [x] You've ran `rm -rf bootstrap/cache/*` from the root of your Cachet installation.

To help us better understand your issue, please answer the following — cheers!

### Expected behaviour

* I should be able to edit a component groups details without having the order displayed on the front-end dashboard change.

### Actual behaviour

* When I edit a component group on 2.2.0-RC1 to change the default collapsed to be "default to expanded" option and save the record the component groups revert to default sorting (alphabetical I do believe).
* The sorting can be seen in the backend or on the front-end user display. Upon re-shuffling them manually they can be fixed, however, they become jumbled again once editing a component group once more.

### Steps to reproduce

* Login to Cachet admin panel.
* Click Components
* Click Component Groups
* Edit a component group (in my case I changed the collapse options)
* Save the record
* Notice that the sorting of the component groups has changed in the admin panel, confirm it's also changed to the end-user. Reshuffle manually to fix.

* _NOTE: I'm not sure if this is an issue on other versions, however, I can see it in 2.2.0-RC1._

Thank you!

**Comment by GrahamCampbell** [comment]
Is this happening on our demo?

**Comment by GrahamCampbell** [comment]
If not, please make sure you've run the `php artisan app:update` command on your system.

**Comment by GrahamCampbell** [comment]
Ping @jbrooksuk.

**Comment by GrahamCampbell** [comment]
@brianjking Please can you confirm that the current master branch works, and then we'll be shipping v2.2.0 shortly.
