### ISSUE TITLE
Social media account links

### ISSUE THREAD

**Issue by Jamesking56** [cachethq/Cachet#166]
Adding the twitter feed to the status page would be nice :smile:

**Comment by GrahamCampbell** [comment]
I don't really like this idea. :(

**Comment by joecohens** [comment]
Me neither, I think we can add social links configurable from settings but not the feed itself.

**Comment by jbrooksuk** [comment]
Yeah, social links is the way I'd prefer to take this. As I mentioned in my first comment, the feed would slow down the page.

All in favour of social links?

**Comment by joecohens** [comment]
:+1:

**Comment by kfrankperson** [comment]
:+1:  Social links in the footer or something :-1: To adding twiiter feed

**Comment by jbrooksuk** [comment]
This feature won't be something that the Cachet team will be developing. If you want to add social links, you could add them to the **About us** section of the website, or modify the source.

If you'd like to contribute the feature, that'd be cool and we could look at merging it into `master`. Thanks for the suggestion though :)
