### ISSUE TITLE
French translation

### ISSUE THREAD

**Issue by spirou1997** [CachetHQ/Cachet#1661]
Hi,

Just little thing:
Line 15 for french translation file (cachet.PHP): "Last updated" can be translated by "Dernière mise à jour"
Thank you :grinning: 

(I don't know if I can edit the file myself)

**Comment by jbrooksuk** [comment]
Can you submit this to https://translate.cachethq.io please? :)

**Comment by spirou1997** [comment]
Yes no problem, done.
I will translate now ;-)
Thank you and sorry

**Comment by jbrooksuk** [comment]
Don't worry about it 😀

Thanks for your contributions.
