### ISSUE TITLE
Problem with install of Cachet

### ISSUE THREAD

**Issue by DefaltNF** [CachetHQ/Cachet#1663]
- [Y] You're running the [latest release] version of Cachet.
- [Y] Ensure that you're running at least PHP 5.5.9, you can check this by running (I'm running on PHP 5.6.17-0+deb8u1) 
- [Y] You've ran `rm -rf bootstrap/cache/*` from the root of your Cachet installation.

### Expected behaviour

The setup/Homepage

### Actual behaviour

I see http://prntscr.com/akc7or

### Steps to reproduce

Install Cachet 

Thank's for your help.

**Comment by GrahamCampbell** [comment]
Looks like you've not setup the file permissions correctly.

**Comment by DefaltNF** [comment]
And how I should setup permissions?

**Comment by jbrooksuk** [comment]
`sudo chmod -R 777 storage`.

**Comment by DefaltNF** [comment]
Not work "sudo chmod -R 777 storage"

**Comment by jbrooksuk** [comment]
You'll also want to run `rm -rf bootstrap/cache/*`

**Comment by DefaltNF** [comment]
Yes i have run this 2 days ago

**Comment by jbrooksuk** [comment]
Have you ran this since changing permissions?
