### ISSUE TITLE
View [signup] not found.

### ISSUE THREAD

**Issue by Drusy** [CachetHQ/Cachet#1668]
### Expected behaviour

Show the signup page when someone follow the e-mailed link on invite.

### Actual behaviour

Error 500 : `[2016-03-29 16:11:16] production.ERROR: exception 'InvalidArgumentException' with message 'View [signup] not found.' in /home/monitoring/www/cachet/bootstrap/cache/compiled.php:14225

### Steps to reproduce

Invite someone to join your team, click on the link.
I have seen any other issue of this kind, and it's the only problem I have using cachet.
Of course I tried cleaning the cache.

Regards.

**Comment by Drusy** [comment]
I am running Cachet in 2.2.
I just tried using 2.1 and the signup page just shown, possible regression of 2.2 ?

**Comment by GrahamCampbell** [comment]
Thanks for the report. I'll look into it.

**Comment by jbrooksuk** [comment]
Did you get anywhere with this?

**Comment by GrahamCampbell** [comment]
Forgot, sorry. :P

**Comment by jbrooksuk** [comment]
This will be fixed too.

**Comment by anlutro** [comment]
> This will be fixed too.

When? The milestone says 2.2.1 but I'm running 2.2.1 and it's still happening. I sincerely hope you aren't closing issues before they're actually solved?

**Comment by jbrooksuk** [comment]
> When? The milestone says 2.2.1 but I'm running 2.2.1 and it's still happening. I sincerely hope you aren't closing issues before they're actually solved?

Ah looks like I closed this instead of another issue, my mistake.
