### ISSUE TITLE
Editing maintenance scheduled time - incorrect time saved

### ISSUE THREAD

**Issue by bjshively** [CachetHQ/Cachet#1669]
Before submitting your issue, please make sure that you've checked all of the checkboxes below.

- [x] You're running the [latest release](https://github.com/CachetHQ/Cachet/releases/latest) version of Cachet.
- [x] Ensure that you're running at least PHP 5.5.9, you can check this by running `php -v`
- [x] You've ran `rm -rf bootstrap/cache/*` from the root of your Cachet installation.

To help us better understand your issue, please answer the following — cheers!

### Expected behaviour

Select date/time for a maintenance window. Save. Page (both on signed-in view and user-facing view) shows the selected date/time.

### Actual behaviour

When creating a new maintenance window, it seems that the app is not correctly saving the time for scheduled maintenance. For example when trying to create a new event scheduled for 21:00 I clicked save and the page refreshed showing 17:00. Then, if I click save again, it changes to 13:00. If I click save again, it changes to 9:00, etc.

In order to get the time I wanted for the event, I had to select a time of n+4 (so it was "changed" to the correct time..)

### Steps to reproduce

Create and save a new maintenance event. Go to edit view of the maintenance item. Click save. Watch the scheduled time change. Click it again. Watch it change again. etc.

**Comment by jbrooksuk** [comment]
Ping @joecohens and @GrahamCampbell. Are we not using `DateFactory` again?

**Comment by GrahamCampbell** [comment]
We should be. Is this code new?

**Comment by GrahamCampbell** [comment]
Looks at `public function editScheduleAction(Incident $schedule)`, it looks like that code never got turned into a command...

**Comment by GrahamCampbell** [comment]
I see the issue though.

**Comment by GrahamCampbell** [comment]
See https://github.com/CachetHQ/Cachet/pull/1678.
