### ISSUE TITLE
Finish notifications support

### ISSUE THREAD

**Issue by Jamesking56** [cachethq/Cachet#167]
Another thought I've had, slightly related to #36 .

It would be nice to integrate with Mailchimp so that users could signup to a Mailchimp list on the Cachet main page. This could solve the issue of email notifications as then we could automatically notify customers when one of the components status has changed or when there is a status update.

- [x] Create `notifications` table.
- [ ] Add a way for signing up to notifications.
- [ ] Implement a system for setting the mail server info.
- [ ] Integrate with a queue system to send, said emails (rather than blocking the UI).

**Comment by jbrooksuk** [comment]
@joecohens we need a modal creating please ;)

**Comment by tomschlick** [comment]
A nicer option would be for cachet to have a "type" radio box where you could select mandrill/mailgun/smtp. Changing types would change the form to accept an api key instead of full smtp info. The mandrill driver in laravel uses HTTP so it would be faster than trying to SMTP it directly.

**Comment by jbrooksuk** [comment]
@tomschlick can you suggest this in #317 please. I'm closing this in favour of the original interface issue #36.
