### ISSUE TITLE
 cachet.components.status.

### ISSUE THREAD

**Issue by TheGarner** [CachetHQ/Cachet#1670]
### Expected behaviour

On the components status it should say whether each one is operational, having an outage etc when it gets results from pingometer. 

### Actual behaviour

Each one of the components say "cachet.components.status.0" 

### Steps to reproduce

The only thing that has changed recently with the site is it was put through SSL and most of it seems to have been working but since one of the components had a outage and was going to get updated to say that on the site automatically. It now just says "cachet.components.status.0" 

Is there a way to resolve this or is it best not to run the status page through SSL?

**Comment by jbrooksuk** [comment]
What language file are you using?

**Comment by TheGarner** [comment]
It would be the English/en language file.

**Comment by jbrooksuk** [comment]
Running over SSL shouldn't affect what happens on the page, not in Cachet anyway. Does the [demo](https://demo.cachethq.io) do this for you?

**Comment by jbrooksuk** [comment]
Also, status `0` for a component doesn't exist.

**Comment by TheGarner** [comment]
Okay I have resolved the problem - If anyone comes across this, make sure you update your link in pingometer to include https:// rather than http:// as that seems to be what was causing it to not update correctly.

**Comment by jbrooksuk** [comment]
:+1:
