### ISSUE TITLE
User subscription

### ISSUE THREAD

**Issue by itwy** [CachetHQ/Cachet#1672]
### Expected behaviour

A form on the main page that allows users to subscribe.

### Actual behaviour

Only see it in admin control panel.

### Steps to reproduce

N/A

**Comment by GrahamCampbell** [comment]
I'm pretty sure we do already have this feature?

**Comment by GrahamCampbell** [comment]
Ping @jbrooksuk.

**Comment by jbrooksuk** [comment]
We do :)

If you've got subscriptions enabled, you can click on the mail icon next to a component on the status page:

![image](https://cloud.githubusercontent.com/assets/246103/14168002/e8b252fe-f716-11e5-9a35-d4c8f4a94372.png)

Or there is a button in the footer labelled "Subscribe".
