### ISSUE TITLE
Form not repopulated on invalid server submission

### ISSUE THREAD

**Issue by itwy** [CachetHQ/Cachet#1673]
### Expected behaviour

Fields repopulated on server side   ##validation.

### Steps to reproduce

- Go to: /dashboard/incidents/add
- Only fill the title and description fields then hit enter.
- Error message "The status format is invalid." and title/description fields lost; have to fill them again!

**Comment by GrahamCampbell** [comment]
I noticed this issue the other day too. It was super annoying for me to have to rewrite all the text I'd just put in.

**Comment by jbrooksuk** [comment]
:+1:
