### ISSUE TITLE
History of how an incident was handled

### ISSUE THREAD

**Issue by itwy** [CachetHQ/Cachet#1674]
Hey guys,

It seems like Cachet is missing a core functionality available in every status page management system and that is the history of the incident.

Take a look here for example:
https://developers.facebook.com/status/issues/542450382592920/
Or here:
http://status.linode.com/incidents/ckdds0nwn1kr
As you can see, the admin can post comments on how the issue is treated. On Cachet, there's no such thing. Just a description field for every incident. Why is that?

**Comment by GrahamCampbell** [comment]
Right, yeh. We've got some improvements regarding this coming up soon.

**Comment by GrahamCampbell** [comment]
https://github.com/CachetHQ/Cachet/issues/1176

**Comment by itwy** [comment]
@GrahamCampbell Cool. Thanks for the prompt answers.

**Comment by GrahamCampbell** [comment]
Currently, updating the status of an incident requires creating a new incident.

**Comment by GrahamCampbell** [comment]
Incident editing, on our current version, is for fixing typos.

**Comment by itwy** [comment]
> Currently, updating the status of an incident requires creating a new incident.

Is this changing in the near future? I am are we going to see the ability to update the incident itself while keeping the history?

The problem is I see with the current method is, there could be multiple issues at the same time and things will be mixed up.

**Comment by GrahamCampbell** [comment]
It's likely something that will be happening for Cachet 3.x, which might be shipping as early as June 2016, but we really have no idea yet. My best guess is that we get 3.0.0 shipped in early September 2016. We've not really discussed this internally yet.

**Comment by jbrooksuk** [comment]
This is actively being worked on :)

https://github.com/CachetHQ/Cachet/pull/1595

**Comment by itwy** [comment]
That's fantastic! Thanks for this amazing app. I appreciate the quality of the PHP code, too 👍
