### ISSUE TITLE
Creating user accounts fails

### ISSUE THREAD

**Issue by jbrooksuk** [CachetHQ/Cachet#1675]
> I also noticed in 2.2.1 dev that I get a server 500 when creating accounts, whether it is a user/admin account.

From a support email.

**Comment by jbrooksuk** [comment]
Interestingly I'm unable to recreate this issue:

![image](https://cloud.githubusercontent.com/assets/246103/14184458/2bbeb5be-f76d-11e5-9a18-92d1171deb30.png)

**Comment by jbrooksuk** [comment]
Tested on Postgres and it worked too. Testing SQLite.

**Comment by jbrooksuk** [comment]
Nope worked for SQLite too. Closing this as un-reproducible.

**Comment by GrahamCampbell** [comment]
Possible they didn't run artisan app:update.

**Comment by jbrooksuk** [comment]
True.
