### ISSUE TITLE
Bug: SQL Constraint Violations when Running Migrations

### ISSUE THREAD

**Issue by bandgeekndb** [CachetHQ/Cachet#1679]
I apologize in advance if MS SQL Server is not a supported database, I'm working under the assumption that since Laravel supports it, it's supported in Laravel applications.  If this isn't the case for Cachet, you can disregard this bug report, although I would hope a note about not supporting MS SQL Server would be added to the requirements page going forward.

### Expected behaviour

Attempting to install Cachet, database should migrate properly during the command php artisan app:install

### Actual behaviour

There are issues running certain migrations containing DROP COLUMN statements, by manually removing the conflicts in the database, the migration process can continue.

```
D:\wwwroot\cachet>php artisan app:install
Copied Directory [\vendor\roumen\feed\src\views] To [\resources\views\vendor\feed]
Publishing complete for tag []!
Migration table created successfully.

  [Illuminate\Database\QueryException]
  SQLSTATE[42000]: [Microsoft][ODBC Driver 11 for SQL Server][SQL Server] The index 'components_user_id_index' is dependent on column 'user_id'. (SQL: alter table "components" drop column "user_id")

  [PDOException]
  SQLSTATE[42000]: [Microsoft][ODBC Driver 11 for SQL Server][SQL Server] The index 'components_user_id_index' is dependent on column 'user_id'.
```

**Deleting the components_user_id_index on the components table resolved this conflict.**

```
D:\wwwroot\cachet>php artisan app:install
Copied Directory [\vendor\roumen\feed\src\views] To [\resources\views\vendor\feed]
Publishing complete for tag []!

  [Illuminate\Database\QueryException]
  SQLSTATE[42000]: [Microsoft][ODBC Driver 11 for SQL Server][SQL Server] The index 'incidents_user_id_index' is dependent on column 'user_id'. (SQL: alter table "incidents" drop column "user_id")

  [PDOException]
  SQLSTATE[42000]: [Microsoft][ODBC Driver 11 for SQL Server][SQL Server] The index 'incidents_user_id_index' is dependent on column 'user_id'.
```

**Deleting the incidents_user_id_index on the incidents table resolved this conflict.**

```
D:\wwwroot\cachet>php artisan app:install
Copied Directory [\vendor\roumen\feed\src\views] To [\resources\views\vendor\feed]
Publishing complete for tag []!

  [Illuminate\Database\QueryException]
  SQLSTATE[42000]: [Microsoft][ODBC Driver 11 for SQL Server][SQL Server] The object 'DF__component__colla__5441852A' is dependent on column 'collapsed'. (SQL: alter table "component_groups" drop column "collapsed")

  [PDOException]
  SQLSTATE[42000]: [Microsoft][ODBC Driver 11 for SQL Server][SQL Server]The
  object 'DF__component__colla__5441852A' is dependent on column 'collapsed'.
```

**Deleting the constraint on the collapsed column on the component_groups table resolved this conflict.**

After resolving these 3 errors, the migrations completed successfully and from the minimal testing I've done so far, the installation appears to be working properly, I was able to run Cachet setup and am now working on testing my instance.

### Steps to reproduce

Platform: Windows Server 2012, Apache 2.4.18, PHP 5.6.17, MS SQL Server 2014

Setup the .env file to point to a MS SQL 2014 database server and attempt to run the app:install command.

Please let me know if you need anymore information, I am happy to provide any data that will help troubleshoot and resolve this bug.  Thank you!

**Comment by jbrooksuk** [comment]
I'm really sorry to hear that you're experiencing a bug with your database.

Unfortunately none of us have the means to test SQL Server support, so we've always classed it as unofficial. Laravel itself supports connecting to it, but we're unable to test our migrations.

Due to this we're unable to properly diagnose the issue for you. That said, I think I have a sneaking suspicion as to the issue.

My guess is that when we drop the column, we also need to drop the index too — perhaps even drop the index first.

Are you able to modify the migrations to do this and try again?

**Comment by bandgeekndb** [comment]
I think I have the first 2 errors completed, I just have to cross check with mysql and verify I'm not breaking things there when I add the fix for MS SQL.

The last one though, SQL Server dynamically generates the constraint name (with a unique value of some sort - ex: DF__component__colla__5441852A), so I can't write that into the migration, and it doesn't follow the syntax Laravel likes for naming constraints.  Not familiar enough with the inner workings of the framework to know if there is code for sql server I could utilize to find a constraint on a column.

**Comment by jbrooksuk** [comment]
1. Awesome! I look forward to seeing the change.
2. What about switching from a `Schema` migration to an `Alter`? That way you can `DROP WITH CONSTRAINTS` or whatever the syntax is?

**Comment by jbrooksuk** [comment]
Did you get any further with this @bandgeekndb?

**Comment by jbrooksuk** [comment]
I've asked on Twitter if I can use an MSSQL server (if anybody has one) for Cachet testing.

I'd like to make MSSQL server supported, but I can only do that with access to a test server. If I can get this, then I'll fix any issues that arise. Since this isn't currently supported *and* @bandgeekndb has gone silent, I'm closing this issue.

Like I said, if I can get a server to test support, I'll fix it and make it 100% supported by Cachet. Until then we have to say it's unofficial :(
