### ISSUE TITLE
archive old incidents

### ISSUE THREAD

**Issue by gfernandez83** [CachetHQ/Cachet#1681]
is there any way we can archive old incidents?

**Comment by jbrooksuk** [comment]
There isn't a way to archive incidents.

Out of interest; what is your use case here? What would this achieve?

**Comment by gfernandez83** [comment]
I'm polling all incidents and create percent availability for the day. maybe I'l just revise my code.  thanks.

**Comment by jbrooksuk** [comment]
For the next release we're working on adding incident updates, so you won't need to keep posting new incidents. Would this help?

**Comment by gfernandez83** [comment]
yeah, it will. but adding percent availability and average response time beside the metrics will be great though a too much to ask.

**Comment by jbrooksuk** [comment]
> percent availability and average response time beside the metrics will be great though too much to ask.

Not #1656?

**Comment by gfernandez83** [comment]
yeah, just like that but also similar to this: http://projects.spencerl.com/statuspage/

**Comment by jbrooksuk** [comment]
Ah I see, we could probably calculate that.
