### ISSUE TITLE
Manage subscriptions page ?

### ISSUE THREAD

**Issue by msc1978** [CachetHQ/Cachet#1682]
Before submitting your issue, please make sure that you've checked all of the checkboxes below.

- [ ] Running 2.2.0 (upgraded form 2.1.x)
- [ ] PHP 5.5.9

Manage subscriptions by end user. From 2.2.0 the emails contain a link to manage subscription eg http://domain.com/subscribe/manage/Jro3E0zAYNTWwcoJsizOXJsFm2XUaxjglbdOgoVt9e

### Expected behaviour

When a user clicks that link I would expect him to manage subscriptions, eg subscribe or unsubscribe for receiving notifcations per component.

### Actual behaviour

A page saying: You're currently subscribed to all updates, the users mail adres and a home button, but no further functionality. So what's the purpose of this page?

### Steps to reproduce

Subscribe for notifications from footer, validate mail from link, report an incident, user receives mail and clicks link to manage subscribtions.

**Comment by GrahamCampbell** [comment]
What's the status here @jbrooksuk?

**Comment by jbrooksuk** [comment]
@joecohens is working on this, it'll be done this week I believe.

**Comment by GrahamCampbell** [comment]
is 2.2.1 the correct milestone?

**Comment by GrahamCampbell** [comment]
We might need to just backport the actual bug fix part of it?

**Comment by jbrooksuk** [comment]
It's a complete rewrite I believe.

**Comment by GrahamCampbell** [comment]
We need to fix this separately on 2.2.x then. ;)

**Comment by GrahamCampbell** [comment]
Just the minimal possible fix will do.

**Comment by GrahamCampbell** [comment]
2.2.x is closing for changes now. No need to backport. 2.3.0 will be the next release after 2.2.2 goes out today.
