### ISSUE TITLE
Feature request: Add parameter to subscribers API to specify component

### ISSUE THREAD

**Issue by Smashmint** [CachetHQ/Cachet#1685]
For those like me who are adding subscribers via de API it would be great to have the option to subscribe someone to a specific component (e.a. a clients server). Otherwise they will be subscribed to all updates.

https://docs.cachethq.io/docs/subscribers

**Comment by jbrooksuk** [comment]
Ping @joecohens maybe something to include in your PR?

**Comment by joecohens** [comment]
👍

**Comment by GrahamCampbell** [comment]
Moving to 3.x since 2.2.x is for bug fixes.

**Comment by jbrooksuk** [comment]
Moved to v2.3.0

**Comment by Smashmint** [comment]
I see V2.3.0 is released. Could you update the documentation with the new parameter(s) added to the API?

**Comment by jbrooksuk** [comment]
Yes. Docs are still behind unfortunately.

**Comment by Smashmint** [comment]
I think the new api parameter is not working as aspected, the subscriber isn't being subscribed to the supplied component.

Taken from the docs API demo:
`{
    "email": "support@alt-three.com",
    "verify": true,
    "components": [
        3,
        4
    ]
}`

Response: 

`{
    "data": {
        "email": "support@alt-three.com",
        "verify_code": "Jk0edycFWLUmu7Xlhbgk0l5JBOsA81Tg3jGnxSNFFV",
        "updated_at": "2016-07-08 17:28:23",
        "created_at": "2016-07-08 17:28:23",
        "id": 1,
        "verified_at": "Friday 8th July 2016 17:28:23"
    }
}`

**Comment by AndronikiEnartia** [comment]
Any answer on this? 
I have exactly the same problem with Smashmint.

**Comment by jbrooksuk** [comment]
This is done by the way! You specify the `components` array with ID's of components. https://docs.cachethq.io/docs/subscribers
