### ISSUE TITLE
Subscribe button not visible

### ISSUE THREAD

**Issue by brianjking** [CachetHQ/Cachet#1686]
Before submitting your issue, please make sure that you've checked all of the checkboxes below.

- [x] You're running the [latest release](https://github.com/CachetHQ/Cachet/releases/latest) version of Cachet.
- [x] Ensure that you're running at least PHP 5.5.9, you can check this by running `php -v`
- [x] You've ran `rm -rf bootstrap/cache/*` from the root of your Cachet installation.

To help us better understand your issue, please answer the following — cheers!

### Expected behaviour

* I expect to see a subscribe option on components and overall for the page via the frontend view. 

### Actual behaviour

* No subscribe button shows.
* If subscribing people from Admin dashboard no emails are ever sent.

### Steps to reproduce

Configure Mailgun as per the Cachet Readme pages at the URLs below.

* https://cachet.readme.io/docs/configuring-mail
* https://cachet.readme.io/docs/setup-subscribers

env file

````
CACHE_DRIVER=apc
SESSION_DRIVER=apc
QUEUE_DRIVER=sync

MAIL_DRIVER=mailgun
MAILGUN_DOMAIN=sandboxef22bf7ac96c48aba5ead38f765d2aa1.mailgun.org
MAILGUN_SECRET= hidden
MAIL_HOST=smtp.mailgun.org
MAIL_PORT=587
MAIL_USERNAME=postmaster@sandboxef22bf7ac96c48aba5ead38f765d2aa1.mailgun.org
MAIL_PASSWORD=hidden
MAIL_ADDRESS=postmaster@sandboxef22bf7ac96c48aba5ead38f765d2aa1.mailgun.org
MAIL_NAME="DockDogs"
MAIL_ENCRYPTION=tls
````

**Comment by brianjking** [comment]
Just as an additional note I've ran `php artisan config:cache` after making the edits to the `env` file.

**Comment by jbrooksuk** [comment]
Have you enabled the setting on the dashboard?

**Comment by brianjking** [comment]
@jbrooksuk yes, I have.

**Comment by brianjking** [comment]
I can turn debugging on if you'd like and check that?

**Comment by jbrooksuk** [comment]
The subscribe button is in the footer by the way?

**Comment by brianjking** [comment]
@jbrooksuk I don't see it anywhere. I checked source too...

http://monitor.dockdogs.com.

**Comment by jbrooksuk** [comment]
If you go to the Dashboard, Settings, you should see this tick box:

![image](https://cloud.githubusercontent.com/assets/246103/14285461/892f9450-fb43-11e5-8d2a-7d7f11afe7aa.png)

Is this ticked?

**Comment by brianjking** [comment]
@jbrooksuk Yes.

**Comment by brianjking** [comment]
I've configured Mailgun with a production level domain now and verified it as well to see if that was an issue and still no go.

````
MAIL_DRIVER=mailgun
MAILGUN_DOMAIN=dockdogs.org
MAILGUN_SECRET=key-secret
MAIL_HOST=smtp.mailgun.org
MAIL_PORT=587
MAIL_USERNAME=postmaster@dockdogs.org
MAIL_PASSWORD=redacted
MAIL_ADDRESS=postmaster@dockdogs.org
MAIL_NAME="DockDogs"
MAIL_ENCRYPTION=tls
````

**Comment by GrahamCampbell** [comment]
Did you remember to run `php artisan config:cache` after making the changes?

**Comment by brianjking** [comment]
Yes. Is there anything I can share in the logs that may help you?

**Comment by jbrooksuk** [comment]
What DB are you using?

**Comment by brianjking** [comment]
MySQL

**Comment by GrahamCampbell** [comment]
And the full filename is definitely `.env` and not `.env.example`?

**Comment by brianjking** [comment]
@GrahamCampbell @jbrooksuk The filename is actually `env` not `.env`.

I'm using @ALinuxNinja's Openshift config as seen https://github.com/ALinuxNinja/openshift-cachet

**Comment by jbrooksuk** [comment]
Okay, for a start it should be `.env`. It may be something regarding Openshift Cachet that is buggy?

**Comment by brianjking** [comment]
I changed it to `.env` and re-ran `php artisan config:cache` and no-go.

**Comment by jbrooksuk** [comment]
The code is definitely working :smile: I've just tried it in my dev environment:

![image](https://cloud.githubusercontent.com/assets/246103/14325411/3158bb10-fc21-11e5-9f3b-aba55e3df877.png)

@ALinuxNinja could you look?

**Comment by jbrooksuk** [comment]
@brianjking are you comfortable making a minor change to something?

**Comment by brianjking** [comment]
@jbrooksuk Yeah, should be fine. I'm also not scared to break things :stuck_out_tongue_winking_eye: What's up?

**Comment by jbrooksuk** [comment]
Can you open up `./app/Http/helpers.php` and modify lines 55-70 to be this:

```php
if (!function_exists('subscribers_enabled')) {
    /**
     * Is the subscriber functionality enabled and configured.
     *
     * @return bool
     */
    function subscribers_enabled()
    {
        $isEnabled = Config::get('setting.enable_subscribers', false);
        $mailAddress = Config::get('mail.from.address', false);
        $mailFrom = Config::get('mail.from.name', false);

        dd($isEnabled, $mailAddress, $mailFrom);

        return $isEnabled && $mailAddress && $mailFrom;
    }
}
```

Refresh your status page and copy the output for me please.

**Comment by brianjking** [comment]
All systems are operational
 DockDogs Website
DockDogs Website
"1"
null
null

**Comment by jbrooksuk** [comment]
Okay so the configuration for mail isn't being passed through to Cachet. I'm going to suggest that Openshift-Cachet is at fault here. Let's see if we can figure it out.

**Comment by jbrooksuk** [comment]
The deploy hook doesn't do anything with the `MAIL_*` variables. https://github.com/ALinuxNinja/openshift-cachet/blob/master/.openshift/action_hooks/deploy

Probably this.

I'm going to close this issue as it's non-Cachet, but we can continue the conversation.

**Comment by brianjking** [comment]
Thanks @jbrooksuk I've referenced my issue over at https://github.com/ALinuxNinja/openshift-cachet/issues/5 with your most recent comment about the file you're discussing so hopefully with your help & @ALinuxNinja's help we can get this working.

Thanks to everyone for all that you do, really.

**Comment by ALinuxNinja** [comment]
@brianjking You edited the wrong file, the env is in $OPENSHIFT_REPO_DIR/Cachet/.env

Correct output is below:

![2016-04-06_18-08-05](https://cloud.githubusercontent.com/assets/9060865/14334466/9a439504-fc22-11e5-8397-0e0a0568a528.png)

I do however have a idea of what might be going wrong, I will take a look at that later today.

**Comment by kareemzok** [comment]
Hello, I m having the same issue. we dd clear cache and the env file is correct but still subscribe button not appearing
