### ISSUE TITLE
Component Subscriptions are linked to Incidents

### ISSUE THREAD

**Issue by txsteven** [CachetHQ/Cachet#1687]
### Expected behaviour

I have 3 Components: 
Component A
Component B
Component C

I have a user (User 1) who is subscribed to Component B (Only Component B not the page)

When I create an Incident for Component A User 1 is not notified. 
When I create an Incident for Component B User 1 is notified. 
When I create an Incident for Component C User 1 is not notified. 

### Actual behaviour

I have 3 Components: 
Component A
Component B
Component C

I have a user (User 1) who is subscribed to Component B (Only Component B not the page)

When I create an Incident for Component A User 1 is notified. 
When I create an Incident for Component B User 1 is notified. 
When I create an Incident for Component C User 1 is notified. 

Possibly Related:

https://github.com/CachetHQ/Cachet/pull/1360#issuecomment-183038816

**Comment by jbrooksuk** [comment]
We're aware of this issue and it'll be fixed in an overhaul of the subscriber system that we're currently working on.
