### ISSUE TITLE
Some sections are shown in diferente lenguage that is configured

### ISSUE THREAD

**Issue by ruiztulio** [CachetHQ/Cachet#1688]
- [x] You're running the [latest release](https://github.com/CachetHQ/Cachet/releases/latest) version of Cachet.
 Checked, jut build a new image before creating the issue.

- [x] Ensure that you're running at least PHP 5.5.9, you can check this by running `php -v`
![php_version](http://screenshots.vauxoo.com/tulio/19422909516-qafdVdW3Fm.jpg)

- [x] You've ran `rm -rf bootstrap/cache/*` from the root of your Cachet installation.
    Several times just to test

### Expected behaviour
All the app in the same language no matter the browser

### Actual behaviour

Some parts are in spanish, others in english and german even when the selected lenguage is english:

Dashboard:
![dashboard](http://screenshots.vauxoo.com/tulio/19405209516-ZTIn0aGgXq.jpg)

Localization configuration:
![localization](http://screenshots.vauxoo.com/tulio/19513309516-KuoGdkTkrY.jpg)
This is happening in Chrome 50.0.2661.57 beta in firefox 47.0a2 works fine (both in Ubuntu 15.10 host).

**Comment by jbrooksuk** [comment]
This is likely because the translations are incomplete.

Please contribute over at https://translate.cachethq.io/translate/cachet/9/en-es :smile:

**Comment by jbrooksuk** [comment]
Also, we've had some instances where translations got muddled up. If you speak Spanish or German, please help correct them :)

**Comment by ruiztulio** [comment]
Yeah, I get it, but we're trying to use the English translation, isn't that complete? Well I'll be happy to help with the Spanish one but they are mixing in the dashboard.

**Comment by jbrooksuk** [comment]
Oh... The English translation is showing German too? That's especially odd.

The status page itself *will* automatically localize based on your locale regardless of your dashboard, but the dashboard should remain in English.

**Comment by ruiztulio** [comment]
Hi,

I'm still having issue with the translations (actually they where never fixed) this is from a fresh installation I just did today:
![dashboard](http://screenshots.vauxoo.com/tulio/10250414616-aoxve9qpeo.jpg)

And spanish translation is almost done:

![translations](http://screenshots.vauxoo.com/tulio/10274714616-e49A2i43iT.jpg)

(I'll finish the missing ones in a minute) But it seems to mess up with all languages, can I force to show them all in English only? Because is better for us to show only in English than German/Spanish.

Regards

**Comment by jbrooksuk** [comment]
Thanks! We'll re-sync languages before the release of v2.3.0

**Comment by ruiztulio** [comment]
Yeah, but is there a way to force it to one language only (in our case would be english)? and ignore the user configure language.

**Comment by jbrooksuk** [comment]
Do you mean the automatic localization? This will be off by default in v2.3.0 :)
