### ISSUE TITLE
Templates and vars for the issues

### ISSUE THREAD

**Issue by ruiztulio** [CachetHQ/Cachet#1689]
I don't know if this is an issue or feature request, but couldn't find anything about.

I'm trying to show the modification time in the issue because we want it to show like this:

![issue](http://screenshots.vauxoo.com/tulio/13452309616-oFMGY1nBdf.jpg)

I know that it is possible to use twig templates, but I was not able to find anything about the vars that can be used (if any) and it actually shows the template:
![template_issue](http://screenshots.vauxoo.com/tulio/13490009616-HQpb6DlexK.jpg)

I must say that the statuses are being updated via a python script so that's why we want the timestamp is automatically added by the template in the specified placeholder like:
![placeholder](http://screenshots.vauxoo.com/tulio/13524409616-hV6P8odgAi.jpg)

Is this possible in the actual application state? 

Regards.

**Comment by jbrooksuk** [comment]
You can use any variables that you'd like! :smiley: 

When you `POST` to the Incident API, you can pass an array of key/value pairs in a `vars` key. Hopefully this code from our tests will make more sense; https://github.com/CachetHQ/Cachet/blob/master/tests/Api/IncidentTest.php#L90-L99
