### ISSUE TITLE
Language problem

### ISSUE THREAD

**Issue by davidlebr1** [CachetHQ/Cachet#1690]
### Your setup

- *What version of Cachet?* 2.1.0
- *What database driver? MySQL? Postgres? SQLite?* MySQL
- *What version of PHP?* PHP 5.5.9-1ubuntu4.14 (cli) 

### Expected behaviour

Expected so see Operational in the status page. The language it supposed to be in french.

### Actual behaviour

I see Funktionsfähig.

![capture du 2016-04-06 14-36-36](https://cloud.githubusercontent.com/assets/838845/14328571/46a510ca-fc05-11e5-9c7d-029863c2358b.png)

### Steps to reproduce

A normal install of Cachet. Then, I add a component and go to the status page.

**Comment by GrahamCampbell** [comment]
This was fixed in a later version of Cachet. Please upgrade.

**Comment by davidlebr1** [comment]
Alright. I thought I had the newest version. 

Thank you
