### ISSUE TITLE
Cachet - Incident message Customisation

### ISSUE THREAD

**Issue by karthik-22feb** [CachetHQ/Cachet#1691]
Hi Team,

I have installed CACHET on my linux machine and trying to do some customization with the existing system. Please let me know if you have a patch or solution to my requirement

Is it possible to display the all the new incidents (except FIXED incidents) at the top of the page. Once the incident is changed to fixed, then all the incident messages with that particular component should appear in the PAST INCIDENT section
![statuspage_io_1](https://cloud.githubusercontent.com/assets/17992464/14328741/0c6ce7b0-fc06-11e5-85f8-aae3d536e384.jpg)

SIMILAR to https://www.statuspage.io/

Please let me know if this is doable by customizing the code.

Thanks,
Karthik

**Comment by jbrooksuk** [comment]
Currently, no. This isn't something that Cachet supports natively.

And, due to the time required to do this as a one-off (which, wouldn't be compatible with future updates), it's not something we can offer for free I'm afraid.

It's definitely doable though.
