### ISSUE TITLE
Google Analytics Issue

### ISSUE THREAD

**Issue by scheesman** [CachetHQ/Cachet#1692]
Before submitting your issue, please make sure that you've checked all of the checkboxes below.

- [x] You're running the [latest release](https://github.com/CachetHQ/Cachet/releases/latest) version of Cachet.
- [x] Ensure that you're running at least PHP 5.5.9, you can check this by running `php -v`
- [x] You've ran `rm -rf bootstrap/cache/*` from the root of your Cachet installation.

To help us better understand your issue, please answer the following — cheers!

### Your setup

- *What version of Cachet?* - v2.2.0
- *What database driver? MySQL? Postgres? SQLite?* - MySQL
- *What version of PHP?* - 5.5.9

### Expected behaviour

*Please describe what you're expecting to see happen.*

Entered Google Analytics Tracking ID on Settings - Analytics page.  Expected to see usage in GA.

### Actual behaviour

Did not see usage.  Did not see GA code fire in Chrome Inspector.

### Steps to reproduce

Noticed that resources/views/partials/analytics.blade.php didn't have a server method in front of //www.google-analytics.com/analytics.js.  When I set this to https manually on my copy, GA started working as expected.

**Comment by GrahamCampbell** [comment]
@scheesman Please confirm https://github.com/CachetHQ/Cachet/pull/1693 fixes this.

**Comment by scheesman** [comment]
Can't confirm the other analytics versions, but this fixes GA.  Thanks for
the quick response!
ᐧ

On Thu, Apr 7, 2016 at 10:16 AM, Graham Campbell <notifications@github.com>
wrote:

> @scheesman <https://github.com/scheesman> Please confirm #1693
> <https://github.com/CachetHQ/Cachet/pull/1693> fixes this.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/CachetHQ/Cachet/issues/1692#issuecomment-206926431>
>



-- 

Sean Cheesman | CTO
Level365 – Voice. Data. Cloud Apps.
Cloud Technology. Simplifying Business

**Comment by jbrooksuk** [comment]
The prefixed `//` should make this work on HTTPS by default, no?

**Comment by scheesman** [comment]
At least in my environment, the URL wasn't being called without it.  And
the GA script they provide has it prefixed with https. I am just not sure
about mixed content (will it work on a non-SSL Cachet install?).
ᐧ

On Thu, Apr 7, 2016 at 11:06 AM, James Brooks <notifications@github.com>
wrote:

> The prefixed // should make this work on HTTPS by default, no?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/CachetHQ/Cachet/issues/1692#issuecomment-206944594>
>



-- 

Sean Cheesman | CTO
Level365 – Voice. Data. Cloud Apps.
Cloud Technology. Simplifying Business

**Comment by GrahamCampbell** [comment]
I assume the issue here is your cachet website was http rather than https, and google only allow https now.
