### ISSUE TITLE
PHP-APC is not included to docker container

### ISSUE THREAD

**Issue by qk4l** [CachetHQ/Cachet#1694]
Hi I noticed that Cachet container does not has `php-apcu` package so if user choose APCu as cache module he would get 500 error.

Debian Sid has `php-apcu` [deb package](https://packages.debian.org/sid/php5-apcu) in official repository so we can just add this package name  in Docker file.

### Your setup

- I use Docker compose for version 2.2
- Cachet 2.2
- Database Postgres
- PHP 7

### Actual behaviour

Cachet not wors and generate 500 error after docker container restart.
```
[2016-04-07 21:29:18] production.CRITICAL: Symfony\Component\Debug\Exception\FatalThrowableError: Fatal error: Call to undefined function Illuminate\Cache\apc_fetch() in /var/www/html/vendor/laravel/framework/src/Illuminate/Cache/ApcWrapper.php:32

```

### Steps to reproduce

Follow docker-compose installation guide and chose APCu as cache module. Then restart docker container.

**Comment by jbrooksuk** [comment]
Hey sorry about this. This issue needs to be opened on our [Docker](https://github.com/CachetHQ/Docker) repository. I've copied this issue there for you; https://github.com/CachetHQ/Docker/issues/57
