### ISSUE TITLE
Control panel option to enable/disable subscription

### ISSUE THREAD

**Issue by itwy** [CachetHQ/Cachet#1695]
It doesn't seem there's an option to juggle the subscription from within the control panel. It looks if `enable_subscribers` is not selected during setup, there's no way to enable it but to edit the settings table manually.

Any idea? Thanks.

**Comment by GrahamCampbell** [comment]
You can toggle it on the settings page.

**Comment by GrahamCampbell** [comment]
Go to /dashboard and click on settings.
