### ISSUE TITLE
Round graph metrics

### ISSUE THREAD

**Issue by henry-spanka** [CachetHQ/Cachet#1704]
We should round graph metrics or let the user configure this via the admin dashboard.

See image below:
![screenshot_1](https://cloud.githubusercontent.com/assets/10375269/14589754/05438560-04ea-11e6-90d6-2ee747cecfe3.png)

**Comment by jbrooksuk** [comment]
I'm afraid that I'm unsure what you mean. Can you provide me with some more information to help me understand this issue please.

**Comment by GrahamCampbell** [comment]
@jbrooksuk Look at the scale on the y-axis. :P

**Comment by jbrooksuk** [comment]
Oh, I see. The `metrics` table has a column called `places`, which we could use to round that value off, if that would fix the issue?

**Comment by GrahamCampbell** [comment]
:+1:

**Comment by jbrooksuk** [comment]
Hang on... The `metric_points.value` column doesn't even allow for storing a value like this?

**Comment by jbrooksuk** [comment]
Done!
