### ISSUE TITLE
Blank Page

### ISSUE THREAD

**Issue by RedSpid3r** [CachetHQ/Cachet#1714]
Before submitting your issue, please make sure that you've checked all of the checkboxes below.

- [X] You're running the [latest release](https://github.com/CachetHQ/Cachet/releases/latest) version of Cachet.
- [X] Ensure that you're running at least PHP 5.5.9, you can check this by running `php -v`
- [X] You've ran `rm -rf bootstrap/cache/*` from the root of your Cachet installation.

To help us better understand your issue, please answer the following — cheers!

### Your setup

- *What version of Cachet?* 2.1
- *What database driver? MySQL? Postgres? SQLite?* MySQL
- *What version of PHP?* PHP 5.6.20 (cli) (built: Apr  4 2016 20:54:57)
- LiteSpeed Web Server + cPanel

### Expected behaviour

Be presented with the install/config page

### Actual behaviour

Blank page

### Steps to reproduce

Followed the install docs, but getting a blank page when access the URL. Database tables seems to have been created but are all empty.

Storage folder is 777 -R and owned by the correct user.

**Comment by GrahamCampbell** [comment]
We'll need to see the logs.

**Comment by jbrooksuk** [comment]
Is your site setup to point to the `public` directory?

**Comment by RedSpid3r** [comment]
Will grab the logs now. Subdomain is set to use /public as the document root

**Comment by RedSpid3r** [comment]
Re-created the sub-domain via cPanel and it seems to be working now, something must have b0rked on the original one. Thank you anyway.
