### ISSUE TITLE
500 Internal server error

### ISSUE THREAD

**Issue by enigmamachine69** [CachetHQ/Cachet#1719]
Before submitting your issue, please make sure that you've checked all of the checkboxes below.

- [X] You're running the [latest release](https://github.com/CachetHQ/Cachet/releases/latest) version of Cachet.
- [X] Ensure that you're running at least PHP 5.5.9, you can check this by running `php -v`
- [X] You've ran `rm -rf bootstrap/cache/*` from the root of your Cachet installation.

To help us better understand your issue, please answer the following — cheers!

### Your setup

- *What version of Cachet 2.2.1
- *What database driver? MySQL
- *What version of PHP? 5.6.19

### Expected behaviour

setup load

### Actual behaviour

blank page, if I clear cache I get a actual 500ISE error

[Sat Apr 23 16:42:05.681369 2016] [:error] [pid 9232] [client x.x.x.x:53940] PHP Fatal error:  Uncaught exception 'Illuminate\\Contracts\\Container\\BindingResolutionException' with message 'Unresolvable dependency resolving [Parameter #0 [ <required> $path ]] in class GrahamCampbell\\Exceptions\\ExceptionInfo' in /var/vhosts/www.XXXXstatus.com/Cachet/vendor/laravel/framework/src/Illuminate/Container/Container.php:839\nStack trace:\n#0 /var/vhosts/www.XXXXstatus.com/Cachet/vendor/laravel/framework/src/Illuminate/Container/Container.php(806): Illuminate\\Container\\Container->resolveNonClass(Object(ReflectionParameter))\n#1 /var/vhosts/www.XXXXstatus.com/Cachet/vendor/laravel/framework/src/Illuminate/Container/Container.php(779): Illuminate\\Container\\Container->getDependencies(Array, Array)\n#2 /var/vhosts/www.XXXXstatus.com/Cachet/vendor/laravel/framework/src/Illuminate/Container/Container.php(633): Illuminate\\Container\\Container->build('GrahamCampbell\\\\...', Array)\n#3 /var/vhosts/www.XXXXstatus.com/Cachet/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(697): Illuminate\\Container in /var/vhosts/www.XXXXstatus.com/Cachet/vendor/laravel/framework/src/Illuminate/Container/Container.php on line 839, referer: https://www.XXXXstatus.com/setup

**Comment by enigmamachine69** [comment]
You guys need to update your install documentation, this was occurring because apache couldn't write to the cache directory, couldn't write to the storage directory & it wanted to write to .env during the setup tool

**Comment by jbrooksuk** [comment]
Our docs already contain this information, however it _could_ be easily overlooked:

https://docs.cachethq.io/docs/installing-cachet#using-the-install-command

>  Getting a 500 - Internal Server Error?
> 
> If you get a 500 error when visiting your status page, you may need to run chmod -R 777 storage for it to work or rm -rf bootstrap/cache/*

**Comment by enigmamachine69** [comment]
Yeah, I saw that part.  But I had to chmod 777 the storage/logs directory and .env as well for the setup tool to not kick back a 500 ISE.

**Comment by jbrooksuk** [comment]
That's what the `-R` flag is for, it'll recursively run the chmod on any folders within it. So running `chmod-R 777 storage` will also change `storage/logs` :)

I've never seen anyone need to chmd `.env` though.

**Comment by justinsacbibit** [comment]
For anyone else running into this problem, chmod'ing `.env` (after also chmod'ing storage) made it work for me.

**Comment by jbrooksuk** [comment]
I'm currently on holiday, but once I'm back I plan to update the Install documentation anyway :)

**Comment by GrahamCampbell** [comment]
> For anyone else running into this problem, chmod'ing .env (after also chmod'ing storage) made it work for me.

That should not be needed, and actually should not be done.

**Comment by jbrooksuk** [comment]
@GrahamCampbell potentially it will, because the `SetupController` writes to the `.env` file.

**Comment by GrahamCampbell** [comment]
@jbrooksuk No, it shouldn't be needed. You shouldn't even need to chmod the storage folder if you set the file ownership correctly. This is the case on our demo for example.
