### ISSUE TITLE
Incident creation should be a little smarter

### ISSUE THREAD

**Issue by Jamesking56** [cachethq/Cachet#172]
When the user makes a new Incident, the next thing the user will want to do is change some of the component's current status so that they reflect the new incident.

Wouldn't it be a bit nicer if on the Incident creation screen, you could change the statuses of the components on the same screen?

**Comment by jbrooksuk** [comment]
Perhaps we could move the create incident screen to the dashboard index, above the inline component editor?

**Comment by Jamesking56** [comment]
Yeah that would be good as they are the most commonly accessed parts of the application.

**Comment by joecohens** [comment]
I was thinking on a modal window with the form triggered by the button on the sidebar a add incident. That way you can add incidents no matter where you are. Maybe also launch it with a keyboard shortcut.

**Comment by jbrooksuk** [comment]
@joecohens that's a nice idea, but then it wouldn't be immediately visible to the user how to add an incident?

**Comment by jbrooksuk** [comment]
This will be a thing in #301.
