### ISSUE TITLE
Can't run tests, stalling on SymfonyQuestionHelper

### ISSUE THREAD

**Issue by anlutro** [CachetHQ/Cachet#1721]
Debian 8 with PHP 5.6.19. I git clone, composer install, run ./vendor/bin/phpunit, I get the phpunit version output but no tests get ran.

strace makes it look like SymfonyQuestionHelper is waiting for input, as the process tries to read from STDIN:

```
open("/home/andreas/dev/cachet/vendor/symfony/console/Helper/SymfonyQuestionHelper.php", O_RDONLY) = 4
fstat(4, {st_mode=S_IFREG|0644, st_size=3119, ...}) = 0
fstat(4, {st_mode=S_IFREG|0644, st_size=3119, ...}) = 0
fstat(4, {st_mode=S_IFREG|0644, st_size=3119, ...}) = 0
fstat(4, {st_mode=S_IFREG|0644, st_size=3119, ...}) = 0
mmap(NULL, 3119, PROT_READ, MAP_SHARED, 4, 0) = 0x7f46b386b000
munmap(0x7f46b386b000, 3119)            = 0
close(4)                                = 0
read(0, 0x29569a0, 8192)                = ? ERESTARTSYS (To be restarted if SA_RESTART is set)
--- SIGWINCH {si_signo=SIGWINCH, si_code=SI_KERNEL} ---
read(0, 
```

I can't find any information in any markdown files on how to setup and run tests, so I'll just assume this is a bug.

**Comment by jbrooksuk** [comment]
What version of PHPUnit are you using? Tests are running fine locally and on our TravisCI tests.

**Comment by anlutro** [comment]
```
% ./vendor/bin/phpunit 
PHPUnit 4.8.21 by Sebastian Bergmann and contributors.
```

**Comment by anlutro** [comment]
Found the line of code that causes the hang, throwing an exception yields this stacktrace:

```
/home/andreas/dev/cachet/vendor/symfony/console/Helper/QuestionHelper.php:395
/home/andreas/dev/cachet/vendor/symfony/console/Helper/QuestionHelper.php:63
/home/andreas/dev/cachet/vendor/symfony/console/Helper/SymfonyQuestionHelper.php:48
/home/andreas/dev/cachet/vendor/symfony/console/Style/SymfonyStyle.php:330
/home/andreas/dev/cachet/vendor/symfony/console/Style/SymfonyStyle.php:256
/home/andreas/dev/cachet/vendor/laravel/framework/src/Illuminate/Console/Command.php:243
/home/andreas/dev/cachet/vendor/laravel/framework/src/Illuminate/Console/ConfirmableTrait.php:32
/home/andreas/dev/cachet/vendor/laravel/framework/src/Illuminate/Database/Console/Migrations/MigrateCommand.php:54
/home/andreas/dev/cachet/bootstrap/cache/compiled.php:1240
/home/andreas/dev/cachet/vendor/laravel/framework/src/Illuminate/Console/Command.php:169
/home/andreas/dev/cachet/vendor/symfony/console/Command/Command.php:256
/home/andreas/dev/cachet/vendor/laravel/framework/src/Illuminate/Console/Command.php:155
/home/andreas/dev/cachet/vendor/symfony/console/Application.php:791
/home/andreas/dev/cachet/vendor/symfony/console/Application.php:186
/home/andreas/dev/cachet/vendor/symfony/console/Application.php:117
/home/andreas/dev/cachet/vendor/laravel/framework/src/Illuminate/Console/Application.php:64
/home/andreas/dev/cachet/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php:170
/home/andreas/dev/cachet/vendor/laravel/framework/src/Illuminate/Foundation/Testing/Concerns/InteractsWithConsole.php:25
/home/andreas/dev/cachet/vendor/laravel/framework/src/Illuminate/Foundation/Testing/DatabaseMigrations.php:14
/home/andreas/dev/cachet/vendor/laravel/framework/src/Illuminate/Foundation/Testing/TestCase.php:102
/home/andreas/dev/cachet/vendor/laravel/framework/src/Illuminate/Foundation/Testing/TestCase.php:67
```

**Comment by jbrooksuk** [comment]
Have you ran `composer install`?

**Comment by anlutro** [comment]
You can clearly see the vendor directory in my code dumps.

**Comment by jbrooksuk** [comment]
Sorry I mean just `composer install` and not `composer install -o --no-dev` which is what we usually say to install. I'm just checking everything is fresh.

**Comment by anlutro** [comment]
Yes, just a regular `composer install` with no arguments.

**Comment by jbrooksuk** [comment]
What version of PHP are you using? This is my output:

```shell
➜ ~/Code/cachethq/cachet (master) ./vendor/bin/phpunit
PHPUnit 4.8.21 by Sebastian Bergmann and contributors.

Runtime:	PHP 7.0.5
Configuration:	/Users/james.brooks/Code/CachetHQ/Cachet/phpunit.xml.dist

...............................................................  63 / 284 ( 22%)
............................................................... 126 / 284 ( 44%)
............................................................... 189 / 284 ( 66%)
............................................................... 252 / 284 ( 88%)
................................

Time: 10.83 seconds, Memory: 118.00Mb

OK (284 tests, 651 assertions)
```

**Comment by anlutro** [comment]
PHP version 5.6.19.

If I `rm bootstrap/cache/*` I get an error that actually sense: PDO driver missing.

Should said cache not be written when you `composer install`? Why would writing the cache cause an input prompt?

**Comment by jbrooksuk** [comment]
Oh, well that's likely the issue then. Do you have `php-pdo` installed?

**Comment by anlutro** [comment]
I don't see why a missing php extension should cause phpunit to prompt for input. Why does `ConfirmableTrait` get invoked? Does the application think it's in the production env when the phpunit tests try to run migrations?

**Comment by GrahamCampbell** [comment]
You'll need to install the sqlite extension as well as php-pdo, since the pdo extension uses the others as drivers.

**Comment by anlutro** [comment]
That still doesn't explain why I was prompted for input. If I just got the exception telling me a PDO driver was missing I wouldn't have reported an issue because I would immediately know what the problem is. Is something going wrong during the cache generation?

**Comment by GrahamCampbell** [comment]
> That still doesn't explain why I was prompted for input. 

Looks like you have cached config. Delete that before running the tests.

**Comment by GrahamCampbell** [comment]
Otherwise, the tests will just run rampage on your production data...

**Comment by anlutro** [comment]
Even with the PDO driver installed, if I `composer install`, phpunit hangs. If I `rm boostrap/cache/*` it works again.

If I'd gotten an exception telling me the PDO driver was missing instead of the hanging prompt, I wouldn't have reported this issue as I'd have known what the problem was and how to fix it.

**Comment by anlutro** [comment]
Github was serving me an outdated page, so I confused myself a bit in that previous comment.

Shouldn't whatever phpunit test case you're using set the environment to "testing"?

**Comment by anlutro** [comment]
Right, so apparently Laravel considers the config caching to be enabled if the cache file exists and there's no way to disable that at run time. Unless you're willing to manually remove that cache config file, or maybe use a different cache path for testing purposes, I guess there's not much to do about that.

Still seems very inconvenient not to be able to just `git clone` and `phpunit` though.

Anyway, feel free to close the issue if you don't see any actionable tasks from here on.

**Comment by GrahamCampbell** [comment]
Yeh, this is a limitation in Laravel that Taylor and I introduced when optimizing boot up performance in Laravel 5.2. It requires you to clear the cache to use a different "environment", such as the one provided by our phpunit config.

**Comment by jbrooksuk** [comment]
It's really annoying, I'm always having demo data splurged around my dev environment.

**Comment by GrahamCampbell** [comment]
Sorry, lol. Our changes made the default app like 25% faster out of the box.

**Comment by jbrooksuk** [comment]
It's only annoying because, like @anlutro said, you can't just run tests.

**Comment by GrahamCampbell** [comment]
I've got an idea on how to fix this.

**Comment by GrahamCampbell** [comment]
"fix" :trollface:

**Comment by GrahamCampbell** [comment]
My fix won't work.

**Comment by jbrooksuk** [comment]
Oh.
