### ISSUE TITLE
Subscribers not receiving verification email 

### ISSUE THREAD

**Issue by codefetcher** [CachetHQ/Cachet#1724]
Hey, I have configured my email settings using stmp  driver and host as gmail. Whenever i get a new subscriber a job is created in the job table but the subscriber doesn't receive the mail with verification link.
I have added the job in crontab -e.
I have also changed the queue_driver to sync.
my .env file contents are :- 
MAIL_DRIVER=smtp
MAIL_HOST=smtp.gmail.com
MAIL_PORT=587
MAIL_USERNAME=my gmail id
MAIL_PASSWORD=my password
MAIL_ADDRESS=my gmail id
MAIL_NAME=bla bla 
MAIL_ENCRYPTION=tls   
how to figure it out?

**Comment by GrahamCampbell** [comment]
Did you run `php artisan app:update` after making changes to the `.env` file?

**Comment by GrahamCampbell** [comment]
Also, make sure you restart the php-fpm service too.

**Comment by codefetcher** [comment]
I did it now it gives a new error : 
Copied Directory [/vendor/roumen/feed/src/views] To [/resources/views/vendor/feed]
Publishing complete for tag []!
Nothing to migrate.
Clearing cache...

                                                                                                                     
  [Illuminate\Database\QueryException]                                                                               
  SQLSTATE[42S02]: Base table or view not found: 1146 Table 'cachet.cache' doesn't exist (SQL: delete from `cache`)  
                                                                                                                     

                                                                                          
  [PDOException]                                                                          
  SQLSTATE[42S02]: Base table or view not found: 1146 Table 'cachet.cache' doesn't exist

**Comment by GrahamCampbell** [comment]
You've setup the cache incorrectly. Change it from `database` to something else.

**Comment by GrahamCampbell** [comment]
The default is `file`, and that's good for most people.

**Comment by GrahamCampbell** [comment]
If you have the apc cache extension installed, you could use the `apc` driver.

**Comment by codefetcher** [comment]
oh okay is it possible to change the settings to file now or I'll have to do a fresh install?

**Comment by GrahamCampbell** [comment]
Yes, that's fine. Just update the .env file, and run the update command again.

**Comment by codefetcher** [comment]
Thanks the artisan app:update worked but email service still not working!!

**Comment by jbrooksuk** [comment]
What is `QUEUE_DRIVER` set to? You need to be running the queue worker. https://docs.cachethq.io/docs/setup-subscribers#database-queue-and-cron

**Comment by codefetcher** [comment]
I have set the queue driver to sync

**Comment by jbrooksuk** [comment]
What are your logs saying?

**Comment by codefetcher** [comment]
mayank@MG:/var/www/cachet_live$ ./storage/logs/laravel-2016-04-27.log 
./storage/logs/laravel-2016-04-27.log: line 1: [2016-04-27: command not found
./storage/logs/laravel-2016-04-27.log: line 2: Stack: command not found
./storage/logs/laravel-2016-04-27.log: line 40: [2016-04-27: command not found
./storage/logs/laravel-2016-04-27.log: line 41: Stack: command not found
./storage/logs/laravel-2016-04-27.log: line 55: [2016-04-27: command not found
./storage/logs/laravel-2016-04-27.log: line 56: Stack: command not found
./storage/logs/laravel-2016-04-27.log: line 151: [2016-04-27: command not found
./storage/logs/laravel-2016-04-27.log: line 152: Stack: command not found
./storage/logs/laravel-2016-04-27.log: line 179: [2016-04-27: command not found
./storage/logs/laravel-2016-04-27.log: line 180: Stack: command not found
./storage/logs/laravel-2016-04-27.log: line 207: [2016-04-27: command not found
./storage/logs/laravel-2016-04-27.log: line 208: Stack: command not found
./storage/logs/laravel-2016-04-27.log: line 235: [2016-04-27: command not found
./storage/logs/laravel-2016-04-27.log: line 236: Stack: command not found
./storage/logs/laravel-2016-04-27.log: line 292: ca...)
#1 /var/www/cachet_live/vendor/laravel/framework/src/Illuminate/Database/Connection.php(662): Illuminate\Database\Connection->Illuminate\Database\{closure}(Object(Illuminate\Database\MySqlConnection), delete: No such file or directory
./storage/logs/laravel-2016-04-27.log: line 292: ca..., Array, Object(Closure))
#3 /var/www/cachet_live/vendor/laravel/framework/src/Illuminate/Database/Connection.php(434): Illuminate\Database\Connection->run(delete: No such file or directory
./storage/logs/laravel-2016-04-27.log: line 292: ca..., Array)
#5 /var/www/cachet_live/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(1974): Illuminate\Database\Connection->delete(delete: No such file or directory
./storage/logs/laravel-2016-04-27.log: line 291: [2016-04-27: command not found
./storage/logs/laravel-2016-04-27.log: line 329: Stack: command not found
./storage/logs/laravel-2016-04-27.log: line 362: [2016-04-27: command not found
./storage/logs/laravel-2016-04-27.log: line 363: Stack: command not found
./storage/logs/laravel-2016-04-27.log: line 418: [2016-04-27: command not found
./storage/logs/laravel-2016-04-27.log: line 421: Stack: command not found
./storage/logs/laravel-2016-04-27.log: line 523: [2016-04-27: command not found
./storage/logs/laravel-2016-04-27.log: line 524: Stack: command not found
./storage/logs/laravel-2016-04-27.log: line 626: [2016-04-27: command not found
./storage/logs/laravel-2016-04-27.log: line 628: Stack: command not found
./storage/logs/laravel-2016-04-27.log: line 734: [2016-04-27: command not found
./storage/logs/laravel-2016-04-27.log: line 737: Stack: command not found
./storage/logs/laravel-2016-04-27.log: line 839: [2016-04-27: command not found
./storage/logs/laravel-2016-04-27.log: line 840: Stack: command not found
./storage/logs/laravel-2016-04-27.log: line 948: [2016-04-27: command not found
./storage/logs/laravel-2016-04-27.log: line 951: Stack: command not found
./storage/logs/laravel-2016-04-27.log: line 1053: [2016-04-27: command not found
./storage/logs/laravel-2016-04-27.log: line 1054: Stack: command not found
./storage/logs/laravel-2016-04-27.log: line 1162: [2016-04-27: command not found
./storage/logs/laravel-2016-04-27.log: line 1163: Stack: command not found
./storage/logs/laravel-2016-04-27.log: line 1638: unexpected EOF while looking for matching `''
./storage/logs/laravel-2016-04-27.log: line 1640: syntax error: unexpected end of file


This are my logs in storage directory
whenever i try to add a new subscriber i get an internal sever error 500 page

**Comment by codefetcher** [comment]
All the other functions are working fine.

**Comment by jbrooksuk** [comment]
What database driver are you using?

**Comment by codefetcher** [comment]
Mysql

**Comment by codefetcher** [comment]
my .env file :- 


APP_ENV=production
APP_DEBUG=false
APP_URL=http://localhost
APP_KEY=vLlQHrMjhgpaEapG7jf5QaGhr5etASOv

DB_DRIVER=mysql
DB_HOST=localhost
DB_DATABASE=cachet
DB_USERNAME=root
DB_PASSWORD=null
DB_PORT=null
DB_PREFIX=null

CACHE_DRIVER=file
SESSION_DRIVER=file
QUEUE_DRIVER=sync
CACHET_EMOJI=false

MAIL_DRIVER=smtp
MAIL_HOST=smtp.gmail.com
MAIL_PORT=587
MAIL_USERNAME=myemail@gmail.com
MAIL_PASSWORD=mypassword
MAIL_ADDRESS=myemail@gmail.com
MAIL_NAME=helloworld
MAIL_ENCRYPTION=tls

REDIS_HOST=null
REDIS_DATABASE=null
REDIS_PORT=null

GITHUB_TOKEN=null


my crontab job :- 
* * * * * php /var/www/cachet_live/artisan schedule:run >> /dev/null 2>&1

**Comment by jbrooksuk** [comment]
Are you adding subscribers from the dashboard? Also, what version of Cachet are you using?

**Comment by codefetcher** [comment]
I have added from both dashboard as well as through subscribe button on home age.
Cachet version is 2.2.0

**Comment by codefetcher** [comment]
**home page

**Comment by jbrooksuk** [comment]
Can you upgrade to v2.2.1 please?

**Comment by codefetcher** [comment]
Yes, Okay  I'll update the cachet, But is the issue resolved in it?
Will the mail service work with this configuration?

**Comment by jbrooksuk** [comment]
I'm unsure to be honest, but it's always best to be up to date when we try to figure out issues.

**Comment by codefetcher** [comment]
Okay I'll get back to you after i upgrade

**Comment by codefetcher** [comment]
Thank you for your support it worked after the upgrade

**Comment by jbrooksuk** [comment]
:)
