### ISSUE TITLE
Dates not being localized

### ISSUE THREAD

**Issue by anlutro** [CachetHQ/Cachet#1727]
I've set the locale to norwegian in `.env` as well as under settings in the dashboard, however, dates are still being formatted in English.

If I `php artisan tinker` everything seems to work as you'd expect, dates are translated:

```
>>> Jenssegers\Date\Date::getLocale();
=> "no"
>>> $df = app('CachetHQ\Cachet\Dates\DateFactory');
=> CachetHQ\Cachet\Dates\DateFactory {#888}
>>> $df->make('2016-04-27 12:00:00')->format('l j. F Y');
=> "onsdag 27. april 2016"
```

However, if I `var_dump($dt->getLocale())` inside `IncindentPresenter::create_at_formatted`, it shows the locale is "en".

**Comment by jbrooksuk** [comment]
Our `DateFactory` doesn't take into consideration the locale. I don't really know if this is by design because in the presenters we format it into the given format you're using.

I don't think this is right though...

Ping @GrahamCampbell.

**Comment by anlutro** [comment]
> Our DateFactory doesn't take into consideration the locale.

No, but Jensseger's Date library does. I assume that its service provider gets the app locale and sets it on the Date class. Maybe that service provider is running too early in the application lifecycle, i.e. the app locale hasn't been properly set yet? But that doesn't explain why it gets translated in the interactive shell but not in the presenter class.

**Comment by jbrooksuk** [comment]
Yeah, looks like we're not setting any locales for the Date library. https://github.com/CachetHQ/Cachet/blob/2.2/app/Foundation/Providers/ConfigServiceProvider.php#L38-L41

**Comment by jbrooksuk** [comment]
Out of interest, for what reason are you expecting to see the locale within the Date library?

**Comment by anlutro** [comment]
I assume it should get set here: https://github.com/jenssegers/date/blob/master/src/DateServiceProvider.php#L21-L23

**Comment by GrahamCampbell** [comment]
@anlutro We then override it again here with what the browser sends: https://i.starbs.net/Vqjl.

**Comment by anlutro** [comment]
Okay... I personally wouldn't want my status page to change language depending on who visits it, unless you can also add support for multi-lingual incident reports, and the ability to set up different date formats for different locales. The date format is currently static, as it is defined in the admin panel along with the locale, but the date format I use in Norwegian is different from the one I'd use in English.

**Comment by TheLastProject** [comment]
I agree with @anlutro here. I use it for some Dutch service with a fully Dutch target audience and thus, incident reports are also in Dutch. Yet, some visitors get it in English anyway depending on their device, making the whole site a weird mix between Dutch and English for them. I'd really like to be able to force Cachet to one specific language, especially for the time being with single-lingual incident reports.

**Comment by jbrooksuk** [comment]
I'm sure we add a setting to configure this.

**Comment by GrahamCampbell** [comment]
Relabling this to a feature request.

**Comment by jbrooksuk** [comment]
@anlutro in v2.3.0 we no longer translate automatically, you need to turn it on from the Localization settings page.

**Comment by anlutro** [comment]
So I just upgraded to 2.3.1 and dates still aren't being localized despite the rest of the webpage being translated properly.

**Comment by GrahamCampbell** [comment]
It's possible that those translations are missing?

**Comment by anlutro** [comment]
https://github.com/jenssegers/date/blob/master/src/Lang/no.php

**Comment by GrahamCampbell** [comment]
Ping @jbrooksuk.

**Comment by jbrooksuk** [comment]
Ping @joecohens on this, I can't see the cause?
