### ISSUE TITLE
Error 500

### ISSUE THREAD

**Issue by maitrey0da** [CachetHQ/Cachet#1728]
Hello,

I use the latest version of Cachet or docker-cachet. With sandalone or docker installation, I have definitely errors 500.
I tried `rm -rf bootstrap/cache/*` and `chmod -R 777 storage`

Before my last checkout, docker-cachet was working.

**Comment by jbrooksuk** [comment]
Can you report this on the [Docker](https://github.com/CachetHQ/Docker) repo please.
