### ISSUE TITLE
Bug: Forms let you submit multiple times

### ISSUE THREAD

**Issue by Jamesking56** [cachethq/Cachet#173]
When adding a new incident, I noticed a weird bug.

If you fill in the form as normal, then click the submit button twice really quickly, it'll create __TWO__ identical new incidents!

This could be a bit annoying, a simple fix is using a bit of JS that on submit, disables the submit button so that once clicked, it cannot be clicked again.

**Comment by kfrankperson** [comment]
I wouldn't use JavaScript to solve this problem, It should be solved in Laravel. JavaScript can be turned off so it's more of a hack than anything else.

**Comment by Jamesking56** [comment]
How do you suppose it could be fixed in Laravel?

**Comment by GrahamCampbell** [comment]
Provide a unique code as a hidden field that invalides once submitted.

**Comment by Jamesking56** [comment]
Doesn't Laravel have that already?

http://laravel.com/docs/4.2/security#protecting-routes

Doesn't Laravel's CSRF Protection offer this?

**Comment by GrahamCampbell** [comment]
No, it doesn't. That's something different. It doesn't prevent multiple submissions of a form.

**Comment by Jamesking56** [comment]
Thanks for clarifying that :+1:

**Comment by joecohens** [comment]
This could be fixed by now with js on all the submit buttons to disable them.

**Comment by GrahamCampbell** [comment]
This isn't even a bug.

**Comment by GrahamCampbell** [comment]
If you press submit twice, expect it to submit twice.

**Comment by joecohens** [comment]
:+1: anyway I'll add the js to prevent it.

**Comment by GrahamCampbell** [comment]
K

**Comment by jbrooksuk** [comment]
Alternative solution is to disable the form on submit.
