### ISSUE TITLE
Backup databases before updating

### ISSUE THREAD

**Issue by jbrooksuk** [CachetHQ/Cachet#1730]
We should hook into the `app:update` command so that a backup of the database is taken before we do anything.

At the very least this will cover ourselves and make some irreversible future migrations safer.

We could make use of https://github.com/ShawnMcCool/database-backup

**Comment by GrahamCampbell** [comment]
Seems legit. :+1:

**Comment by jbrooksuk** [comment]
I lied, we need to use https://github.com/backup-manager/laravel.
