### ISSUE TITLE
How to configure Cachet to log to syslog?

### ISSUE THREAD

**Issue by codefx9** [CachetHQ/Cachet#1744]
Hi,
I am using 2.2.2 version of Cachet with PHP 5.6. From Laravel website, I gather that it will be possible to log to syslog via their monolog library. But I can't find any examples on how to do that. Can you please tell me how to log to syslog from Cachet?

Thanks.

**Comment by GrahamCampbell** [comment]
Just look for tutorials on how to do it on Laravel 5.1+. Same same. ;)

**Comment by codefx9** [comment]
I tries setting the `APP_LOG=syslog` in .env file. That causes Cachet to stop logging to file but it does not log anything to syslog. How do I specify syslog server ip:port or socket address?
