### ISSUE TITLE
Validation error creating incident but incident gets created anyway

### ISSUE THREAD

**Issue by anlutro** [CachetHQ/Cachet#1745]
I was creating an incident and forgot to enter the component status (operational/performance issues etc). This send me back to the "create new incident" form with most fields filled out, but upon fixing the mistake and submitting the form again I discovered I had created duplicate incidents.

The operations should probably be wrapped in a database transaction if validation beforehand is not enough.

**Comment by jbrooksuk** [comment]
@GrahamCampbell @joecohens maybe we wrap our commands in the transaction middleware we used in StyleCI once?
