### ISSUE TITLE
Usability: No hint or link for dashboard on status page or in docs

### ISSUE THREAD

**Issue by hubertgrzeskowiak** [CachetHQ/Cachet#1746]
### My setup

- Cachet 2.1.0
- MySQL
- PHP 5.6.20

### Expected behaviour

I was expecting some small link or information about a dashboard or some other sort of an "admin area". I actually only stumbled upon it by accident. I'd at least expect some hint about it in the documentation.

### Actual behaviour

No indication on the status page nor in the documentation.

### Steps to reproduce

You get the idea.

**Comment by GrahamCampbell** [comment]
You can enable the link to the dashboard in the footer, on our settings page.

**Comment by GrahamCampbell** [comment]
At `/dashboard/settings/theme` there is a checkbox towards the bottom of the form.

**Comment by hubertgrzeskowiak** [comment]
Aaaah thanks! This should be enabled by default IMHO. Also a note about the dashboard would improve the docs a lot.
Thanks anyways! Saves me a new bookmark.

**Comment by jbrooksuk** [comment]
We did used to have the button showing by default, but we felt it crowded the footer a bit too much and if you setup the status page, you'd know where to go.
