### ISSUE TITLE
Disabling automatic localization

### ISSUE THREAD

**Issue by ManneW** [CachetHQ/Cachet#1747]
### My setup

- *What version of Cachet?* **2.2.2**
- *What database driver? MySQL? Postgres? SQLite?* **SQLite**
- *What version of PHP?* **5.5.9**

### Expected behaviour

The public facing interface (the status page itself) is not automatically translated based on the users' locale, unless I've explicitly enabled that feature.

### Actual behaviour

The public facing interface is always translated into the users' locale, even though I've specified another language as "site language" within the localization settings.

### Motivation

Don't get me wrong; I thing automatic localization is a great feature, in some cases. What I'm looking for is some way to disable it on a per-site basis. Like in our case, where we have all our communication in English, it looks quite strange for some of our Swedish customers when parts of the website is in Swedish while the actual information is in English.

Perhaps there is a feature to do this, but I simply haven't found it? :-) Or is it a bug that the language set in the settings isn't respected?

**Anyhow; many thanks for the great work put into Cachet!**

**Comment by GrahamCampbell** [comment]
> The public facing interface is always translated into the users' locale, even though I've specified another language as "site language" within the localization settings.

That language only sets the language for the dashboard, not the public facing site.

**Comment by GrahamCampbell** [comment]
I know there is another issue for adding this feature, but I can't find it.

**Comment by GrahamCampbell** [comment]
Ping @jbrooksuk. Where's that issue, or was it closed, in which case, I'm delegating this one to be the replacement.

**Comment by jbrooksuk** [comment]
@GrahamCampbell yeah there was, but I can't find it either. I'll get this feature done now.
