### ISSUE TITLE
Remove site name from "Powered by" line

### ISSUE THREAD

**Issue by mhayes14** [CachetHQ/Cachet#1758]
Hey,

Firstly, Cachet is a fantastic project which I'm sure has an even brighter future ahead. Hopefully I'll be able to make some PR's in future.

I want our installation to show support for Cachet. However, I have the site name set to "[Business Name] - Network Status". This makes the powered by line look a bit ugly, in fact it forces it to wrap because it's too long. Even if we changed the site name on the installation to "[Business Name]", I don't think we'd want to display "[Business Name] is powered by Cachet".

My proposal is to remove the site name from this line. A simple "Powered by Cachet." is nicer in my personal opinion, then I'd be happy to enable this option. I'll be sharing the project with others anyway but it would be nice to have the footer link in place.

Give this issue a 👍  or 👎 !

**Comment by jbrooksuk** [comment]
You know what? I like this idea :)

**Comment by GrahamCampbell** [comment]
:+1:
