### ISSUE TITLE
Embedding Custom Metrics?

### ISSUE THREAD

**Issue by JustinFarris** [CachetHQ/Cachet#1764]
Is there currently a sanctioned method of customizing the Status View to replace the metrics section with a graph embedded from an outside source? Just one example: We already have a lot of metrics captured elsewhere in graphite, new relic, etc. Rather than emit those metrics to the Cachet API and store them in yet another database/platform, we would like to embed an existing graph on the Cachet Status page where Cachet would normally add its metrics.

**Comment by jbrooksuk** [comment]
You could change the header HTML (through settings) to embed this data.

**Comment by JustinFarris** [comment]
Thanks, but that doesn't really answer my question, at least not directly.

Are the custom header and footer the only options for customizing the layout of the Status view, aside from just manually modifying the site? We've tried doing this in the header, but we just can't make it look like it fits well and we would prefer to have it in the middle section where the other metrics are.

**Comment by jbrooksuk** [comment]
Sorry @JustinFarris, I was replying from my phone.

We don't currently have a way to modify or extend the default views, at least not without making changes to the source files. Something that we'd like to introduce (perhaps in v3.0.0) is a "theme selector" or a way to upload a `.zip` file with your views in and have them completely custom.

**Comment by JustinFarris** [comment]
Great, thanks for the follow-up.
