### ISSUE TITLE
Banner Image

### ISSUE THREAD

**Issue by 298atc** [CachetHQ/Cachet#1766]
Cachet 2.2.2 Uploading new banner image, Error 500
This error can be identified by c4474cfa-95b7-4fa0-84a0-4137d21e36ef.

**Comment by GrahamCampbell** [comment]
Thanks for reporting. This error will be fixed in the 2.3.0 release. ALso, do note that your error code there is totally useless to us. It is literally just a random string. You use it to find the entry in your logs.

**Comment by GrahamCampbell** [comment]
This was the fix btw: https://github.com/CachetHQ/Cachet/pull/1750.
