### ISSUE TITLE
Site language not respected in Firefox

### ISSUE THREAD

**Issue by hubertgrzeskowiak** [CachetHQ/Cachet#1778]
### Your setup

- Cachet v2.2.2
- MySQL with MyISAM (was a hell to set up)
- PHP 5.6

### Expected behaviour

Setting site language in admin area to english and never see anything internationalized (non-english) again.

### Actual behaviour

Dashboard shows all texts in the browser's requested language instead of english. The problem seems to only occur in Firefox. Couldn't reproduce in Chrome or MSIE.

### Steps to reproduce

Fresh install 2.2.2. Set site language to english or anything. Browse dashboard using Firefox on a non-english system. Tested in Firefox on Linux and Windows 8.1.

**Comment by GrahamCampbell** [comment]
That setting just changes the language of the admin panel, not the website.

**Comment by GrahamCampbell** [comment]
We have added a new setting that will allow you to change the language of the user facing part that will ship in our 2.3.0 release soon.
