### ISSUE TITLE
PHP SDK

### ISSUE THREAD

**Issue by damianopetrungaro** [CachetHQ/Cachet#1784]
Hi!
I wrote a PHP SDK  for Cachet.
Here a link: https://github.com/damianopetrungaro/CachetSDK
Any feedback is welcome!
It would be great if you include this in the Client Libraries https://docs.cachethq.io/docs/client-libraries.
Thanks!

@jbrooksuk

**Comment by GrahamCampbell** [comment]
Thanks for letting us know. Feel free to use the suggest an edit feature on our docs to add it, and we'll approve the chanage.
