### ISSUE TITLE
Write documentation for incident updates

### ISSUE THREAD

**Issue by joecohens** [CachetHQ/Cachet#1786]
https://github.com/CachetHQ/Cachet/pull/1595

**Comment by JustinFarris** [comment]
I know this still needs to be documented, so I'm asking a specific question: Can incident updates only be added via API, or is there some way to add them via the Dashboard/UI as well?

**Comment by jbrooksuk** [comment]
It'll be both, but the feature is currently in development :)

**Comment by travelton** [comment]
Is there anything the community can do to help with this request... From pull #1595 it looks like this might be done in v3.0.0? Same for the feature request #1844. I'd love to contribute, if I can.

**Comment by jbrooksuk** [comment]
Hey @travelton, we're in a weird situation with the docs. We can write the docs, but not publish them as we don't currently list API endpoints as "Beta", we probably should do.

**Comment by jbrooksuk** [comment]
This is a job I'll get done this week :)

**Comment by jbrooksuk** [comment]
Mostly done!
