### ISSUE TITLE
Descriptions in .env.example

### ISSUE THREAD

**Issue by lhorace** [CachetHQ/Cachet#1788]
Before submitting your issue, please make sure that you've checked all of the checkboxes below.

- [x] You're running the [latest release](https://github.com/CachetHQ/Cachet/releases/latest) version of Cachet.
- [x] Ensure that you're running at least PHP 5.5.9, you can check this by running `php -v`
- [ ] You've ran `rm -rf bootstrap/cache/*` from the root of your Cachet installation.

To help us better understand your issue, please answer the following — cheers!

### Your setup

- *What version of Cachet?* 1.2.2
- *What database driver? MySQL? Postgres? SQLite?* MySQL
- *What version of PHP?* 5.5.9

Hello,

It would have been convenient for first-time users that .env.example included descriptive text as to what values are acceptable values for each variable. Take CACHE_DRIVER for example, what are the acceptable values? No examples on http://docs.cachethq.io/ explain this. Additionally, what undocumented variables could be placed in .env?

Thank you and regards.

**Comment by jbrooksuk** [comment]
Thanks for submitting your issue!

I plan on rewriting the installation documents over the next week or so, I'm just collating some recurring issues that people have had so I can make it clearer.

> Additionally, what undocumented variables could be placed in .env?

As far as I can remember, there are none that we create. Laravel itself may have some though.

**Comment by lhorace** [comment]
Great, actually, I wasn't aware of the setup phase in the browser that may address this particular issue.

Super!

Regards
