### ISSUE TITLE
Site not available on KDE neon 5.6 (based on Ubuntu 16.04 LTS)

### ISSUE THREAD

**Issue by zane901267** [CachetHQ/Cachet#1790]
Before submitting your issue, please make sure that you've checked all of the checkboxes below.

- [x] You're running the [latest release](https://github.com/CachetHQ/Cachet/releases/latest) version of Cachet.
- [x] Ensure that you're running at least PHP 5.5.9, you can check this by running `php -v`
- [x] You've ran `rm -rf bootstrap/cache/*` from the root of your Cachet installation.

To help us better understand your issue, please answer the following — cheers!

### Your setup

- *Cachet v2.2.2*
- *MySQL v5.6.28 Community Edition (Installed on Windows Server 2012)*
- *PHP 7.0 (PHP 7.0.4-7ubuntu2)*

### Expected behaviour

I'm expecting to see the Dashboard from Cachet after a new installation with the possibility to setup everything and create new services or at least anything from my older installation if I restore the database backup before the upgrade.

### Actual behaviour

Actually, when I try to access my Cachet Dashboard under http://status.clan-agoshan.com I see the following error message, with no clue to solve this problem:
make('Illuminate\Contracts\Http\Kernel'); $request = Illuminate\Http\Request::capture(); $response = $kernel->handle($request); $response->send(); $kernel->terminate($request, $response); 

### Steps to reproduce

I've tried to install Cachet v2.2.2 on a new installation of KDE neon 5.6 (which is based on Ubuntu 16.04 LTS, also using the same repositories as Ubuntu 16.04 LTS). Also upgrading from Ubuntu 14.04 LTS to 16.04 LTS has ended with the error above. My MySQL databases are stored on my Windows Server 2012 R2 root server, the Linux server  with Cachet runs as a Hyper-V VM on this  Windows server. This configuration was successfully working with 14.04 LTS.

Thank you and have a nice day!

**Comment by GrahamCampbell** [comment]
Looks like you don't have php installed.

**Comment by GrahamCampbell** [comment]
That "error message" is the index.php file being printed to the screen, without going through php.
