### ISSUE TITLE
Mail delivery doesn't work

### ISSUE THREAD

**Issue by zane901267** [CachetHQ/Cachet#1791]
Before submitting your issue, please make sure that you've checked all of the checkboxes below.

- [x] You're running the [latest release](https://github.com/CachetHQ/Cachet/releases/latest) version of Cachet.
- [x] Ensure that you're running at least PHP 5.5.9, you can check this by running `php -v`
- [x] You've ran `rm -rf bootstrap/cache/*` from the root of your Cachet installation.

To help us better understand your issue, please answer the following — cheers!

### Your setup

- *Cachet v2.2.2*
- *MySQL (Community Edition, v5.6.28 - Windows) *
- *PHP 7.0 (7.0.4-7ubuntu2)*
- *Mail Server on Root server, based on MailEnable 9.00 Standard - Comes with Parallels Plesk*
 
### Expected behaviour

*When I try to invite someone / subscribe to my Cachet Status Updates, an email will sended to the specified mailbox. The mail will delivered over the MailEnable SMTP on my Windows Server.*

### Actual behaviour

*The Server isn't sending any mails to the specified mailbox. The configuration is set to an SMTP server on port 25 with no encryption (because MailEnable Standard Edition doesn't provide any encryption methodes). I can't find any logs for the first steps, solving this Problem.

Configuration:

MAIL_DRIVER=smtp
MAIL_HOST=clan-agoshan.com
MAIL_PORT=25
MAIL_USERNAME=<protected>@clan-agoshan.com
MAIL_PASSWORD=<protected>
MAIL_ADDRESS=<protected>@clan-agoshan.com
MAIL_NAME="Agoshan Online Communities Heartbeat Service"
MAIL_ENCRYPTION=false

<protected> means I've removed sensitive informations. Did I configure something wrong? Is it possible, forcing Cachet (or better the Laravet Framework) to send the mails unencrypted?*

### Steps to reproduce

*Use any SMTP server without Mail Encryption capability*

**Comment by jbrooksuk** [comment]
What happens if you set `MAIL_ENCRYPTION` to `ssl`?

**Comment by jbrooksuk** [comment]
Alternatively `MAIL_ENCRYPTION=""`.

Mail delivery is working fine though, just a setting issue.

**Comment by zane901267** [comment]
All right, i've tried your two suggestions. Unfortunately it isn't working with both of them. Could it possible that depencies are missing on my system? Which packages needs the mail delivery for working?

**Comment by jbrooksuk** [comment]
Ping @GrahamCampbell what's Laravel's convention for turning mail encryption off?

**Comment by GrahamCampbell** [comment]
Set it to `null`.

**Comment by zane901267** [comment]
Thanks for responding! I've tried your suggestion but it's still not working. Also I've reinstalled everyting...but still nothing. Any ideas?

**Comment by GrahamCampbell** [comment]
What queue driver are you using?

**Comment by zane901267** [comment]
I'm using the database driver.

**Comment by jbrooksuk** [comment]
You have the queue running then? https://docs.cachethq.io/docs/setup-subscribers#database-queue-and-cron

**Comment by zane901267** [comment]
All right, this finally solved my problem! Thank you all so much! Have a nice weekend!
