### ISSUE TITLE
Component status not always visible when reporting an incident

### ISSUE THREAD

**Issue by jhamilton09** [CachetHQ/Cachet#1792]
Before submitting your issue, please make sure that you've checked all of the checkboxes below.

- [ X ] You're running the [latest release](https://github.com/CachetHQ/Cachet/releases/latest) version of Cachet.
- [ X ] Ensure that you're running at least PHP 5.5.9, you can check this by running `php -v`
- [ X ] You've ran `rm -rf bootstrap/cache/*` from the root of your Cachet installation.

To help us better understand your issue, please answer the following — cheers!

### Your setup

- *What version of Cachet?* 2.2.2
- *What database driver? MySQL? Postgres? SQLite?* MySQL
- *What version of PHP?* 7.0.3

### Expected behavior

Component status options should always be visible when a component is selected while reporting a new incident.

### Actual behavior

Component status options may disappear if you choose a component and then choose a different component.
Component status options may remain if you choose the blank component.

The div seems to be given class="form-group hidden" almost every other time.

### Steps to reproduce

Creating a new incident:
Fill out the form and choose a Component. Component status options appear.
I need to change Component. Select drop-down and choose a different component. For some components, the status options do not appear.
Choose the " " component at top and status options sometimes remain.

You can refresh the page and choose the correct component and the status options appear properly. You can also select enough different components to get back to the original component with the status options appearing.

![image](https://cloud.githubusercontent.com/assets/11819245/15400902/f357a318-1db2-11e6-9ff7-3495f4cc0269.png)

**Comment by jbrooksuk** [comment]
This only happens occasionally?

**Comment by jhamilton09** [comment]
Sorry, not explained well enough. The problem happens consistently, it's just not noticed unless you choose one component and then choose another one, which doesn't happen unless you make a mistake with the first selection.

Create a new incident.
Choose component A. Component status shown.
Choose component B. Component status hidden.
Choose component C. Component status shown.
Choose component D. Component status hidden.
Choose component B. Component status shown.

So, it does look like it's consistently every other time.

**Comment by jbrooksuk** [comment]
I think I know what is causing this! Thanks :)
