### ISSUE TITLE
Component order and component group order when reporting an incident

### ISSUE THREAD

**Issue by jhamilton09** [CachetHQ/Cachet#1793]
Before submitting your issue, please make sure that you've checked all of the checkboxes below.

- [X] You're running the [latest release](https://github.com/CachetHQ/Cachet/releases/latest) version of Cachet.
- [X] Ensure that you're running at least PHP 5.5.9, you can check this by running `php -v`
- [X] You've ran `rm -rf bootstrap/cache/*` from the root of your Cachet installation.

To help us better understand your issue, please answer the following — cheers!

### Your setup

- *What version of Cachet?* 2.2.2
- *What database driver? MySQL? Postgres? SQLite?* MySQL
- *What version of PHP?* 7.0.3

### Expected behavior

Component order in the drop-down when reporting an incident should match the order sorted by the component/component group list.

The component list should also update the order when the component group is rearranged.

### Actual behavior

Component list in incident report is grouped by Component groups but none of it matches the manually-configured Component order or even alphabetical order. It looks like it goes by ID and when the items were created.

### Steps to reproduce

Creating a new incident:
Fill out the form and choose a Component. Component order is its own.

Component list can show things in the proper order but inconveniently have components of different groups throughout the list.

**Comment by jbrooksuk** [comment]
Thanks for the bug report! I'll get this looked at.
