### ISSUE TITLE
Bootstrap autoload.php unable to find ../vendor/autoload.php

### ISSUE THREAD

**Issue by ecnepsnai** [cachethq/Cachet#180]
**Problem description:**

When I run `$ php artisan migrate` I get these critical failures:

    $ php artisan migrate
    PHP Warning:  require(<path where cachet is installed>/bootstrap/../vendor/autoload.php): failed to open stream: No such file or directory in <path where cachet is installed>/bootstrap/autoload.php on line 17

    Warning: require(<path where cachet is installed>/bootstrap/../vendor/autoload.php): failed to open stream: No such file or directory in <path where cachet is installed>/bootstrap/autoload.php on line 17
    PHP Fatal error:  require(): Failed opening required '<path where cachet is installed>/bootstrap/../vendor/autoload.php' (include_path='.:/usr/local/lib/php') in <path where cachet is installed>/bootstrap/autoload.php on line 17

    Fatal error: require(): Failed opening required '<path where cachet is installed>/bootstrap/../vendor/autoload.php' (include_path='.:/usr/local/lib/php') in <path where cachet is installed>/bootstrap/autoload.php on line 17

**Steps took to produce problem:**

1. Downloaded Cachet and extracted into desired directory
2. Created MySQL user and database, granted full permissions for that database.
3. `cd`'d into the root of cachet
4. `$ php artisan migrate`

**Desired outcome:**

The creation of the tables in the MySQL Database

**Actual outcome:**

(see above error)

**Environment Information:**

CentOS 6.1, PHP 5.6.3

    --enable-fpm --with-xmlrpc --with-curl --enable-zip --enable-ftp --enable-calendar --enable-bcmath --enable-exif --with-mcrypt --with-mhash --with-zlib --with-bz2 --with-mysql --with-mysqli --with-pdo-mysql --enable-mbstring --with-fpm-user=ian --with-fpm-group=ian --with-openssl

**Comment by joecohens** [comment]
Please run `composer install`

**Comment by jbrooksuk** [comment]
@ecnepsnai thanks for formatting this issue nicely - that's great, I may add it to the `CONTRIBUTING.md` document. As @joecohens said, just run `composer install`.

**Comment by MohammedAlzard** [comment]
composer install
