### ISSUE TITLE
Error 400 CSRF token validation failed during login for the first time

### ISSUE THREAD

**Issue by hostmikro** [CachetHQ/Cachet#1802]
i've just installed cachet,
when i tried to login for the first time, this error appears

> Error 400
Bad Request
CSRF token validation failed.

> What does this mean?
Something went wrong on our servers while we were processing your request. CSRF token validation failed. This occurrence has been logged, and a highly trained team of monkeys has been dispatched to deal with your problem. We're really sorry about this, and will work hard to get this resolved as soon as possible.

> This error can be identified by 44c25a78-add2-4f74-bf4f-6a024bffb0d3. You might want to take a note of this code.

> Perhaps you would like to go to our home page?

i'm running latest version of cachet (v2.2.2) with php56 and sqlite database
Before submitting your issue, please make sure that you've checked all of the checkboxes below.

i tried ```rm -rf bootstrap/cache/*``` and ```php artisan config:cache``` but nothing work

**Comment by jbrooksuk** [comment]
Did you run `php artisan app:install`?

**Comment by jbrooksuk** [comment]
Without more information, I can only say that this is down to an install issue. What session driver are you using?
