### ISSUE TITLE
Failed Running App Update

### ISSUE THREAD

**Issue by chaseconey** [CachetHQ/Cachet#1804]
### Your setup

- *What version of Cachet?* `v2.2.2`
- *What database driver? MySQL? Postgres? SQLite?* `MySQL`
- *What version of PHP?* `PHP 5.5.9-1ubuntu4.16`

### Expected behaviour

When I run `php artisan app:update` that the application would update.

### Actual behaviour

Receive MySQL socket error. Full output:

```
Copied Directory [/vendor/roumen/feed/src/views] To [/resources/views/vendor/feed]
Publishing complete for tag []!


[PDOException]
SQLSTATE[HY000] [2002] Can't connect to local MySQL server through socket '/var/run/mysqld/mysqld.sock' (2)
```

### Steps to reproduce

* Install v2.2.2 with normal installation process
* Follow updating instructions [here](https://docs.cachethq.io/docs/updating-cachet)

**Comment by GrahamCampbell** [comment]
Looks like your database is not set up to accept socket connections.

**Comment by chaseconey** [comment]
I am using an external database - so that would make sense.

**Comment by GrahamCampbell** [comment]
We don't do backups on the 2.2.x version?

**Comment by chaseconey** [comment]
![application_setup_-_dashboard](https://cloud.githubusercontent.com/assets/1449463/15480079/2d9c038c-20e9-11e6-8a99-f04f626a36f9.png)

**Comment by GrahamCampbell** [comment]
Why are you showing me that?

**Comment by chaseconey** [comment]
Sorry, just giving more data points. I am using version 2.2.2 as far as I know. I installed using that tag and all steps were performed as stated in the installation instructions.

Is there something obvious that I am missing?

**Comment by jbrooksuk** [comment]
Try running `rm -rf bootstrap/cache/*` and then `php artisan config:cache`?

**Comment by chaseconey** [comment]
Ran those commands and followed up with another `php artisan app:update` and the same error occurred.

**Comment by GrahamCampbell** [comment]
I don't think this is a Cachet bug. Please ensure you've entered your database information correctly.

**Comment by GrahamCampbell** [comment]
If you're not able to get this working, we do offer an installation service for $99.

**Comment by chaseconey** [comment]
I don't doubt there is some sort of caching issue - but the application is running just fine. Just that command seems to fail. I have had repeated issues with cache getting **stuck** somehow. Even after clearing all cache via artisan and completely killing the bootstrap caching, it still seems to persist.

**Comment by GrahamCampbell** [comment]
Opening until we know more.

**Comment by jbrooksuk** [comment]
@chaseconey can you try this on v2.3.0-RC2 please?

**Comment by jbrooksuk** [comment]
Out of interest what is your DB_ settings like? You using Homestead or something?

Closing as we can't replicate and it's unlikely to be Cachet issue. Let me know if you need more support.

**Comment by chaseconey** [comment]
Just as an FYI for the environment.

It is an AWS setup, just a basic single instance + RDS setup. No worries on the issue, I am sure once 2.3 rolls around it will fix itself.
