### ISSUE TITLE
Subscriber timestamp shows current time

### ISSUE THREAD

**Issue by jhamilton09** [CachetHQ/Cachet#1805]
Before submitting your issue, please make sure that you've checked all of the checkboxes below.

[ X ] You're running the latest release version of Cachet.
[ X ] Ensure that you're running at least PHP 5.5.9, you can check this by running php -v
[ X ] You've ran rm -rf bootstrap/cache/* from the root of your Cachet installation.
To help us better understand your issue, please answer the following — cheers!

Your setup

What version of Cachet? 2.2.2
What database driver? MySQL? Postgres? SQLite? MySQL
What version of PHP? 7.0.3

**Expected behavior**

Viewing the subscribers list would show when a person subscribed to notifications.

**Actual behavior**

Subscriber list shows the current timestamp.

**Steps to reproduce**

View Subscriber list at .../dashboard/subscribers and note the timestamp of a subscriber.
Refresh the page. Timestamp is updated to reflect the current time.

![image](https://cloud.githubusercontent.com/assets/11819245/15481799/ec763f86-20f1-11e6-967f-b2a2b11cadf3.png)

Refresh a minute later...

![image](https://cloud.githubusercontent.com/assets/11819245/15481803/f822796c-20f1-11e6-8176-abe5b332ae28.png)

**Comment by jbrooksuk** [comment]
I'm going to re-do this view as part of v2.3 :)

**Comment by jbrooksuk** [comment]
FWIW I don't see why this bug would be occurring as we're using a static `subscriber.subscribed_at` date :)
