### ISSUE TITLE
Show a text title if there is no image for site 

### ISSUE THREAD

**Issue by jhamilton09** [CachetHQ/Cachet#1807]
Before submitting your issue, please make sure that you've checked all of the checkboxes below.

[ X ] You're running the latest release version of Cachet.
[ X ] Ensure that you're running at least PHP 5.5.9, you can check this by running php -v
[ X ] You've ran rm -rf bootstrap/cache/\* from the root of your Cachet installation.
To help us better understand your issue, please answer the following — cheers!

**Your setup:**

What version of Cachet? 2.2.2
What database driver? MySQL? Postgres? SQLite? MySQL
What version of PHP? 7.0.3

**Expected behavior**

The site looks pretty plain without a logo and if I don't have a good image for those dimensions.

Title could also be used in the subscription notification emails.

**Actual behavior**

Use the 'Site title' for a 'banner' if no image is uploaded for the Banner Image.

**Workaround**
I put this in the Custom Header HTML field and it works great for me. More accessible too.

```
<div class="app-banner">
    <div class="container">
        <div class="row app-banner-padding  ">
            <div class="col-md-12 text-center">
                                <span class="title">Demo Status Page</span>
                            </div>
        </div>
    </div>
</div>
```

**Comment by GrahamCampbell** [comment]
Isn't this already possible using the about this site feature?

**Comment by GrahamCampbell** [comment]
See https://demo.cachethq.io/ for example.

**Comment by jhamilton09** [comment]
You can customize the paragraph of text under 'About this site' but you cannot put an h1 title or even change the words 'About this site'. They are the most prominent while the 'site title' field only really goes to the _title_ tag and puts the site name on the tab.

I love the look with a logo but I would prefer to use text instead of an image of text. Your header customizations would then apply to the text title as well, rather than if you tried to use the 'About this site' paragraph.

**Comment by jbrooksuk** [comment]
You can add custom HTML to the header (which actually replaces it).

**Comment by jhamilton09** [comment]
Right. That's my workaround. Just seems like a more user-friendly feature to fallback to the site title if no image is provided.

**Comment by jbrooksuk** [comment]
v3.0.0 is having a nice big design overhaul on the status page. This would be a better place to implement this change, although I'm not sure that the new design accounts for something like this. Ping @joecohens on this.

**Comment by jbrooksuk** [comment]
Thank you for your input on Cachet 2.x. We are shifting our attention and resources to Cachet 3.x and will no longer be supporting the 2.x version. If your feedback or issue is relevant to the 3.x series, we encourage you to engage with the new branch.

For more information on the Cachet rebuild and our plans for 3.x, you can read the announcement [here](https://github.com/CachetHQ/Cachet/discussions/4342).

We appreciate your understanding and look forward to your contributions to the new version.
