### ISSUE TITLE
User management from API

### ISSUE THREAD

**Issue by tobias-urdin** [CachetHQ/Cachet#1822]
Hello,

Since the LDAP auth approach was scrubbed is there any possibility that we as an additional feature
could add the ability to manage users from the API?
Having a large organization and being able to integrate it with other systems is crucial or most enterprises.

Best regards

**Comment by jbrooksuk** [comment]
LDAP is something I'd be happy to accept as a PR. Unfortunately, I don't have the means of testing an integration, hence why it's not on the list.

We probably should add an API for managing users though, for admins only of course.

**Comment by jbrooksuk** [comment]
Closed by https://github.com/CachetHQ/Cachet/pull/1962, this will be in the v3.0.0 release.
