### ISSUE TITLE
Settings not saving properly

### ISSUE THREAD

**Issue by splitice** [CachetHQ/Cachet#1833]
Before submitting your issue, please make sure that you've checked all of the checkboxes below.

- [X] You're running the [latest release](https://github.com/CachetHQ/Cachet/releases/latest) version of Cachet.
- [X] Ensure that you're running at least PHP 5.5.9, you can check this by running `php -v`
- [X] You've ran `rm -rf bootstrap/cache/*` from the root of your Cachet installation.

To help us better understand your issue, please answer the following — cheers!

### Your setup

- *What version of Cachet?* 2.3.0-RC1
- *What database driver? MySQL? Postgres? SQLite?* MySQL
- *What version of PHP?* 5.6.14

### Expected behaviour

When updating Application setup, no changes are applied. 

### Actual behaviour

Change checkboxes for example, click save, checkboxes go back to original state.

### Steps to reproduce

Change the settings in application setup

**Comment by jbrooksuk** [comment]
Ping @GrahamCampbell, looks like our fixes for this didn't work. Check the demo out... https://cloudup.com/cylG-opxSGv

You'll see that the refresh has to be quite quick. It looks that the time it takes to write the cache file can be slow sometimes.

**Comment by GrahamCampbell** [comment]
I'll take a look soon.

**Comment by GrahamCampbell** [comment]
I don't see what the bug is?

**Comment by GrahamCampbell** [comment]
That massive slow down is what would have been there anyway if it wasn't for the caching. The slowdown is waiting on the db, not writing the file?

**Comment by GrahamCampbell** [comment]
@splitice Are your file permissions to bootstrap/cachet allowing the webserver to read and write there?

**Comment by GrahamCampbell** [comment]
Do you see the same issue on https://demo.cachethq.io/ please?

**Comment by GrahamCampbell** [comment]
I can't replicate this on the demo?

**Comment by splitice** [comment]
Unfortunately no i can not replicate on the demo.

If there is some permissions error its not logged to syslog. Ill put the cache into the DB and see if the issue still exists.

**Comment by JackWent** [comment]
@GrahamCampbell under the settings page on the demo site if you try and enable graphs and save it doesnt save?

**Comment by splitice** [comment]
@JackWent There might be too many people trying that test right now...

**Comment by GrahamCampbell** [comment]
I can't replicate?

![image](https://cloud.githubusercontent.com/assets/2829600/15570174/a697fd46-232c-11e6-9ae8-f4218c1168e2.png)

> If there is some permissions error its not logged to syslog.

If there was a permissions error, there would be no "error". It would just iterate zero files went it went to clear the cache.

**Comment by splitice** [comment]
@GrahamCampbell 

I tested with two different cache drivers (APC and Database). Did a artisan update, then config:cache. Then restarted php5-fpm in the unlikely case zend optimizer had not expired anything.

Neither fixed it. That should eliminate the filesystem since neither depends on it. Unless there is still some on-disk cache?

**Comment by GrahamCampbell** [comment]
> Neither fixed it. That should eliminate the filesystem since neither depends on it. Unless there is still some on-disk cache?

We use the disk because it's much faster because we can use php's opcache to cache it, so in order to load that cache, we don't even touch the disk, infact, the data is already natively in php's memory before we start. That's the same way laravel's config caching already works.

**Comment by splitice** [comment]
Also somewhere while I was doing all these changes the status of the checkboxes I was toggling did change.

My gut is telling me the cache isnt resetting, although I would have expected having set it to APC it would have to be with a FPM restart.

**Comment by GrahamCampbell** [comment]
> Did a artisan update, then config:cache. 

`php artisan app:update` does everything. No need to run any other command again. ;)

**Comment by splitice** [comment]
Well... That would be a problem. I set CACHE_DRIVER for a reason to eliminate the disk.

Really should add an error of disk write fails, since if you try and write to any file in cachet's directory it will fail with EPERM.

The disk from which the code exists isnt writeable from any of the web servers for security reasons (R/O NFS share).

**Comment by GrahamCampbell** [comment]
> I set CACHE_DRIVER

The cache driver doesn't have anything to do with this. We have to be able to write to the disk in order to display all our views and get the config system to work. This is true of all laravel applications.

**Comment by GrahamCampbell** [comment]
> The disk from which the code exists isnt writeable from any of the web servers for security reasons (R/O NFS share).

That can't be true, because we're writing to the disk and then requiring the files we wrote in order to display the views...

**Comment by JackWent** [comment]
php artisan app:update - Fixed my issues :)

**Comment by splitice** [comment]
@GrahamCampbell Well, it is.

I had to give permissions to one node to write when installing since the software insisted on writing a new environment file for me. Perhaps they have been stored since then?

Again - nothing of any severity logged. So I have no idea what its doing, or failing to do.

**Comment by GrahamCampbell** [comment]
Please make sure you give the webserver full permissions to write and read to bootstrap/cachet.
