### ISSUE TITLE
Broken Subscription Verification

### ISSUE THREAD

**Issue by splitice** [CachetHQ/Cachet#1838]
1. Add subscription in dashboard
2. Receive Mail
3. Click verification link in email ```http://status.**/subscribe/verify/***```
4. Shows non-verifed

**Comment by GrahamCampbell** [comment]
I can confirm this is a bug.

**Comment by jbrooksuk** [comment]
Not broken. You need to have subscribers enabled for the verify link to work. This is now on by default from RC2 (upcoming and the final release).
