### ISSUE TITLE
Cleanup controllers and view files

### ISSUE THREAD

**Issue by jbrooksuk** [cachethq/Cachet#184]
I think we need to re-organise the view files and controllers, especially the dashboard. I'm not sure whether we should actually have one dashboard controller, or one per-page?

**Comment by jbrooksuk** [comment]
Views are cleaned (for the dashboard at least).

**Comment by GrahamCampbell** [comment]
> or one per-page?

Nah, we don't need that. The controller will end up thinner after we've done the service layer stuff.

**Comment by jbrooksuk** [comment]
Yeah, it will now because of your epic refactor :) will close now.
