### ISSUE TITLE
Feature Request: API Filtering

### ISSUE THREAD

**Issue by splitice** [CachetHQ/Cachet#1840]
Currently the API seems to (according to the documentation) only support the listing of all objects of each model, or specific models by ID.

It would make the API alot more useful if the API could be filtered by field. i.e get all incidents for a component, or even more complex queries such as all active incidents.

**Comment by GrahamCampbell** [comment]
Thanks for the suggestions @splitice. I think we already discussed this @jbrooksuk. Do we have an existing issue for it?

**Comment by jbrooksuk** [comment]
This is exactly what we need for the metrics issue #1774.

**Comment by splitice** [comment]
FYI the use case for this is an integration into a monitoring platform for the initial "Under Investigation" state creation, and issue follow up.

At a minimum lookup by component is necessary. It would be optimal to have an open incident lookup to allow a sync in case any updates are missed etc.

I'll be open sourcing the Zabbix integration and forking or working work the cachet.php developer to make this happen. I'd rather not work on the API server side myself though being not that familiar with laravel.

**Comment by jbrooksuk** [comment]
We've actually sort of done this already. https://docs.cachethq.io/docs/advanced-api-usage
