### ISSUE TITLE
POST /metrics request/response field mismatch

### ISSUE THREAD

**Issue by dhorbach** [CachetHQ/Cachet#1842]
Before submitting your issue, please make sure that you've checked all of the checkboxes below.

- [x] You're running the [latest release](https://github.com/CachetHQ/Cachet/releases/latest) version of Cachet.
- [x] Ensure that you're running at least PHP 5.5.9, you can check this by running `php -v`
- [x] You've ran `rm -rf bootstrap/cache/*` from the root of your Cachet installation.

To help us better understand your issue, please answer the following — cheers!

### Your setup

- *What version of Cachet?*
2.2.2
- *What database driver? MySQL? Postgres? SQLite?*
MySQL
- *What version of PHP?*
5.5.9

### Expected behaviour

Input fields for /metrics API matches output fields

### Actual behaviour

POST /metrics has "view" parameter
Result has "default_view" parameter.

Can we make them the same? Is there some specific convention?
No documentation on this field too.

### Steps to reproduce

POST /metrics
```
{
    "name":"Visitors7",
    "description":"How many visitors",
    "suffix":"Visitors per hour",
    "default_value":"0",
    "display_chart":"1",
    "view": 2
}
```
Response:
```
{
  "data": {
    "name": "Visitors7",
    "display_chart": true,
    "default_value": 0,
    "calc_type": 0,
    "places": 2,
    "default_view": 2,
    "suffix": "Visitors per hour",
    "description": "How many visitors",
    "updated_at": "2016-05-27 05:09:32",
    "created_at": "2016-05-27 05:09:32",
    "id": 16
  }
}
```

**Comment by GrahamCampbell** [comment]
Is this still the case in v2.3.0-RC2 please?

**Comment by GrahamCampbell** [comment]
Is this still the case in v2.3.0-RC3 please?

**Comment by GrahamCampbell** [comment]
@dhorbach Is this still the case in v2.3.0-RC3 please?

**Comment by jbrooksuk** [comment]
I'm going to have to support BC here by allowing either `view` or `default_view` to be POST'd.

**Comment by jbrooksuk** [comment]
Done.
