### ISSUE TITLE
Report Incident for more than one Component

### ISSUE THREAD

**Issue by splitice** [CachetHQ/Cachet#1844]
Many status pages are for people providing VPS, Dedicated or Shared hosting services. These people host many servers often in the same locations.

It would be adventurous to be able to define an for multiple components.

**Comment by jbrooksuk** [comment]
This is something I plan on doing for v3.0.0 as I've already added Incident Updates ⚡

**Comment by jbrooksuk** [comment]
Thank you for your input on Cachet 2.x. We are shifting our attention and resources to Cachet 3.x and will no longer be supporting the 2.x version. If your feedback or issue is relevant to the 3.x series, we encourage you to engage with the new branch.

For more information on the Cachet rebuild and our plans for 3.x, you can read the announcement [here](https://github.com/CachetHQ/Cachet/discussions/4342).

We appreciate your understanding and look forward to your contributions to the new version.
