### ISSUE TITLE
Incident days does not save (2.3)

### ISSUE THREAD

**Issue by ruiztulio** [CachetHQ/Cachet#1845]
Before submitting your issue, please make sure that you've checked all of the checkboxes below.

- [x ] You're running the [latest release](https://github.com/CachetHQ/Cachet/releases/latest) version of Cachet.
- [ x] Ensure that you're running at least PHP 5.5.9, you can check this by running `php -v`
- [x ] You've ran `rm -rf bootstrap/cache/*` from the root of your Cachet installation.

To help us better understand your issue, please answer the following — cheers!

### Your setup

- *What version of Cachet?*
2.3 5c5634d
- *What database driver? MySQL? Postgres? SQLite?*
Postgres 9.5

- *What version of PHP?*
5.6.21

### Expected behaviour
Save the number of days without the need of deleting the cache

### Actual behaviour
Whenever I try to change the incidents days to show it simply shows the previous value.
Does not save I have to manually delete the cache in order it can save them. And no error is shown in the log

### Steps to reproduce
- Log in into the instance
- Settings -> Application setup 
- In "How many days of incidents to show?" change the value to anything other than the default and click save

**Comment by jbrooksuk** [comment]
If you refresh again, the change should be made. Can you confirm?

**Comment by ruiztulio** [comment]
The changes are not saved:

I change to this:
![before](http://screenshots.vauxoo.com/tulio/10553814816-WpI9E4V7UT.jpg)

Click save:
![save](http://screenshots.vauxoo.com/tulio/10561814816-cRdrEZmwwG.jpg)

Refresh:
![refresh](http://screenshots.vauxoo.com/tulio/10564814816-0fncJs5TZ4.jpg)

And it is not even applied into the public board:
![board](http://screenshots.vauxoo.com/tulio/10572214816-CL19vQ9rsF.jpg)

**Comment by jbrooksuk** [comment]
Is your `./bootstrap/` directory writeable?

**Comment by ruiztulio** [comment]
yes:
![bootstrap](http://screenshots.vauxoo.com/tulio/11251514816-AaRNDoIz4h.jpg)

Most of it is writeable:
![files](http://screenshots.vauxoo.com/tulio/11264114816-lkwbE9W2qo.jpg)

But that _production.php_ file needs to be writeable by www-data user?

**Comment by jbrooksuk** [comment]
Yeah. We need to write to it so that we can cache the settings, rather than hitting the DB for each request :)

**Comment by ruiztulio** [comment]
So, is it better to execute the _php artisan *_ commands as www-data instead of root so all files are created with that user?

**Comment by GrahamCampbell** [comment]
> But that production.php file needs to be writeable by www-data user?

The whole folder needs to be totally writable and readable.

**Comment by GrahamCampbell** [comment]
> So, is it better to execute the php artisan * commands as www-data instead of root so all files are created with that user?

Yes.

**Comment by ruiztulio** [comment]
Thanks, after changing the permissions everything worked as spected:
![good](http://screenshots.vauxoo.com/tulio/12184114816-klQOwqV4i6.jpg)

Regards

**Comment by jbrooksuk** [comment]
Note to self: update docs.

**Comment by jbrooksuk** [comment]
Ping @djdefi can we make sure that the Docker image is working properly please?

**Comment by djdefi** [comment]
Should be able to just add a `chown` in the Dockerfile.

**Comment by GrahamCampbell** [comment]
:+1:

**Comment by djdefi** [comment]
I'm actually doing some work currently to run services in the container as `www-data` rather than root. It is a Docker best practice but one that is easy to overlook early on in development.

**Comment by GrahamCampbell** [comment]
On our demo, we just made an entire new user and ran php-fpm as that.

**Comment by ruiztulio** [comment]
@djdefi We follow that practice too, we create an user for the service that we want to deploy inside a container.

But in this case we plan to deploy Cachet and Zabbix front end in the same _bare metal_ and I'm writing some ansible files to deploy them automatically (I could write a separate role for Cachet).
