### ISSUE TITLE
php fatal error updating cachet to v2.3.0-RC5

### ISSUE THREAD

**Issue by abioneperhobby** [CachetHQ/Cachet#1868]
updating cachet to last version i got a php fatal error

this is the log.

what should i do?

thanks.

```
qa-asus Cachet # php artisan down
Application is now in maintenance mode.
qa-asus Cachet # git fetch origin
remote: Counting objects: 2344, done.
remote: Compressing objects: 100% (391/391), done.
remote: Total 2344 (delta 1066), reused 820 (delta 820), pack-reused 1128
Receiving objects: 100% (2344/2344), 1.85 MiB | 726.00 KiB/s, done.
Resolving deltas: 100% (1581/1581), completed with 266 local objects.
From https://github.com/cachethq/Cachet
   b0a4820..b0c75a2  master     -> origin/master
 * [new branch]      2.2        -> origin/2.2
 * [new branch]      2.3        -> origin/2.3
 * [new branch]      drop-langauges -> origin/drop-langauges
 * [new branch]      scheduled-maintenance-backup -> origin/scheduled-maintenance-backup
 + d354c46...ca45aa2 scheduled-maintenance-refactoring -> origin/scheduled-maintenance-refactoring  (forced update)
 * [new branch]      tags-api   -> origin/tags-api
 * [new branch]      update-login-page -> origin/update-login-page
 * [new branch]      upgrade-paths -> origin/upgrade-paths
 * [new tag]         v2.2.1     -> v2.2.1
 * [new tag]         v2.2.2     -> v2.2.2
 * [new tag]         v2.3.0-RC1 -> v2.3.0-RC1
 * [new tag]         v2.3.0-RC2 -> v2.3.0-RC2
 * [new tag]         v2.3.0-RC3 -> v2.3.0-RC3
 * [new tag]         v2.3.0-RC4 -> v2.3.0-RC4
 * [new tag]         v2.3.0-RC5 -> v2.3.0-RC5
qa-asus Cachet # git tag -l
v0.1.0-alpha
v1.0.0
v1.1.0
v1.1.1
v1.2.0
v1.2.1
v2.0.0
v2.0.0-RC1
v2.0.0-RC2
v2.0.0-RC3
v2.0.0-RC4
v2.0.0-RC5
v2.0.0-beta1
v2.0.0-beta2
v2.0.1
v2.0.2
v2.0.3
v2.0.4
v2.1.0
v2.1.0-RC1
v2.1.0-RC2
v2.1.1
v2.1.2
v2.2.0
v2.2.0-RC1
v2.2.1
v2.2.2
v2.3.0-RC1
v2.3.0-RC2
v2.3.0-RC3
v2.3.0-RC4
v2.3.0-RC5
qa-asus Cachet # git checkout LATEST_TAG
error: pathspec 'LATEST_TAG' did not match any file(s) known to git.
qa-asus Cachet # git checkout v2.3.0-RC5
Note: checking out 'v2.3.0-RC5'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by performing another checkout.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -b with the checkout command again. Example:

  git checkout -b new_branch_name

HEAD is now at 42aa437... Released 2.3.0 RC5
qa-asus Cachet # composer install --no-dev -o
Warning: This development build of composer is over 60 days old. It is recommended to update it by running "/usr/local/bin/composer self-update" to get the latest version.
Loading composer repositories with package information
Installing dependencies from lock file
  - Removing vlucas/phpdotenv (v2.2.0)
  - Installing vlucas/phpdotenv (v2.2.1)
    Downloading: 100%

  - Removing symfony/polyfill-mbstring (v1.1.1)
  - Installing symfony/polyfill-mbstring (v1.2.0)
    Downloading: 100%

  - Removing symfony/var-dumper (v3.0.3)
  - Installing symfony/var-dumper (v3.0.6)
    Downloading: 100%

  - Removing symfony/translation (v3.0.3)
  - Installing symfony/translation (v3.0.6)
    Downloading: 100%

  - Removing symfony/routing (v3.0.3)
  - Installing symfony/routing (v3.0.6)
    Downloading: 100%

  - Removing symfony/process (v3.0.3)
  - Installing symfony/process (v3.0.6)
    Downloading: 100%

  - Removing symfony/polyfill-util (v1.1.1)
  - Installing symfony/polyfill-util (v1.2.0)
    Downloading: 100%

  - Removing symfony/polyfill-php56 (v1.1.1)
  - Installing symfony/polyfill-php56 (v1.2.0)
    Downloading: 100%

  - Removing symfony/http-foundation (v3.0.3)
  - Installing symfony/http-foundation (v3.0.6)
    Downloading: 100%

  - Removing symfony/event-dispatcher (v3.0.3)
  - Installing symfony/event-dispatcher (v3.0.6)
    Downloading: 100%

  - Removing symfony/debug (v3.0.3)
  - Installing symfony/debug (v3.0.6)
    Downloading: 100%

  - Removing symfony/http-kernel (v3.0.3)
  - Installing symfony/http-kernel (v3.0.6)
    Downloading: 100%

  - Removing symfony/finder (v3.0.3)
  - Installing symfony/finder (v3.0.6)
    Downloading: 100%

  - Removing symfony/console (v3.0.3)
  - Installing symfony/console (v3.0.6)
    Downloading: 100%

  - Removing swiftmailer/swiftmailer (v5.4.1)
  - Installing swiftmailer/swiftmailer (v5.4.2)
    Downloading: 100%

  - Removing nikic/php-parser (v2.0.1)
  - Installing nikic/php-parser (v2.1.0)
    Downloading: 100%

  - Removing monolog/monolog (1.18.1)
  - Installing monolog/monolog (1.19.0)
    Downloading: 100%

  - Removing league/flysystem (1.0.20)
  - Installing league/flysystem (1.0.22)
    Downloading: 100%

  - Removing laravel/framework (v5.2.26)
  - Installing laravel/framework (v5.2.34)
    Downloading: 100%

  - Removing alt-three/badger (v3.0.0)
  - Installing alt-three/badger (v3.1.0)
    Downloading: 100%

  - Removing alt-three/bus (v1.0.2)
  - Installing alt-three/bus (v1.1.0)
    Downloading: 100%

  - Removing league/commonmark (0.13.1)
  - Installing league/commonmark (0.13.3)
    Downloading: 100%

  - Removing guzzlehttp/psr7 (1.2.3)
  - Installing guzzlehttp/psr7 (1.3.0)
    Downloading: 100%

  - Removing guzzlehttp/promises (1.1.0)
  - Installing guzzlehttp/promises (1.2.0)
    Downloading: 100%

  - Removing alt-three/emoji (v3.0.1)
  - Installing alt-three/emoji (v3.1.0)
    Downloading: 100%

  - Removing alt-three/validator (v1.4.1)
  - Installing alt-three/validator (v1.5.0)
    Downloading: 100%

  - Removing christian-riesen/base32 (1.2.2)
  - Installing christian-riesen/base32 (1.3.1)
    Downloading: 100%

  - Removing graham-campbell/security (v3.5.1)
  - Installing graham-campbell/security (v3.6.0)
    Downloading: 100%

  - Removing graham-campbell/binput (v3.3.1)
  - Installing graham-campbell/binput (v3.4.0)
    Downloading: 100%

  - Removing graham-campbell/core (v4.2.1)
  - Installing graham-campbell/core (v5.1.0)
    Downloading: 100%

  - Removing graham-campbell/exceptions (v8.3.2)
  - Installing graham-campbell/exceptions (v8.5.0)
    Downloading: 100%

  - Removing graham-campbell/markdown (v6.0.1)
  - Installing graham-campbell/markdown (v6.1.0)
    Downloading: 100%

  - Removing jenssegers/date (v3.2.0)
  - Installing jenssegers/date (v3.2.1)
    Downloading: 100%

  - Removing mccool/laravel-auto-presenter (4.2.1)
  - Installing mccool/laravel-auto-presenter (4.3.0)
    Downloading: 100%

  - Removing roumen/feed (v2.10.1)
  - Installing roumen/feed (v2.10.2)
    Downloading: 100%

  - Installing alt-three/throttle (v1.0.4)
    Downloading: 100%

  - Installing backup-manager/backup-manager (1.1.1)
    Downloading: 100%

  - Installing backup-manager/laravel (1.1.1)
    Downloading: 100%

  - Installing symfony/css-selector (v3.0.6)
    Downloading: 100%

  - Installing tijsverkoyen/css-to-inline-styles (1.5.5)
    Downloading: 100%

  - Installing fedeisas/laravel-mail-css-inliner (1.5)
    Downloading: 100%

Generating optimized autoload files
> Illuminate\Foundation\ComposerScripts::postInstall
> php artisan optimize --force
PHP Fatal error:  Class 'CachetHQ\Cachet\Foundation\Providers\GitHubServiceProvider' not found in /var/www/Cachet/vendor/laravel/framework/src/Illuminate/Foundation/ProviderRepository.php on line 146


  [Symfony\Component\Debug\Exception\FatalErrorException]
  Class 'CachetHQ\Cachet\Foundation\Providers\GitHubServiceProvider' not found


Script php artisan optimize --force handling the post-install-cmd event returned with an error


  [RuntimeException]
  Error Output: PHP Fatal error:  Class 'CachetHQ\Cachet\Foundation\Providers
  \GitHubServiceProvider' not found in /var/www/Cachet/vendor/laravel/framewo
  rk/src/Illuminate/Foundation/ProviderRepository.php on line 146


install [--prefer-source] [--prefer-dist] [--dry-run] [--dev] [--no-dev] [--no-plugins] [--no-custom-installers] [--no-autoloader] [--no-scripts] [--no-progress] [-v|vv|vvv|--verbose] [-o|--optimize-autoloader] [-a|--classmap-authoritative] [--ignore-platform-reqs] [--] [<packages>]...
```

**Comment by jbrooksuk** [comment]
It looks like you've may have made modifications to `app.php`?

You need to reset to the `2.3` branch and then update. Also, you'll want to run `composer self-update` too.

**Comment by abioneperhobby** [comment]
@jbrooksuk thanks, so i updated composer, i make hard reset hard to 2.3, and cachet goes up and running,
then i tried update,
and the same error occur. Can you help me please?

thanks.

qa-asus Cachet # git reset --hard 2.3
HEAD is now at f79fada Released 2.2.2
qa-asus Cachet # composer install --no-dev -o
Do not run Composer as root/super user! See https://getcomposer.org/root for details
Loading composer repositories with package information
Installing dependencies from lock file
  - Removing fedeisas/laravel-mail-css-inliner (1.5)
  - Removing tijsverkoyen/css-to-inline-styles (1.5.5)
  - Removing symfony/css-selector (v3.0.6)
  - Removing backup-manager/laravel (1.1.1)
  - Removing backup-manager/backup-manager (1.1.1)
  - Removing alt-three/throttle (v1.0.4)
  - Removing christian-riesen/base32 (1.3.1)
  - Installing christian-riesen/base32 (1.3.0)
    Loading from cache

  - Removing symfony/polyfill-mbstring (v1.2.0)
  - Installing symfony/polyfill-mbstring (v1.1.1)
    Loading from cache

  - Removing symfony/var-dumper (v3.0.6)
  - Installing symfony/var-dumper (v3.0.4)
    Loading from cache

  - Removing symfony/translation (v3.0.6)
  - Installing symfony/translation (v3.0.4)
    Loading from cache

  - Removing symfony/routing (v3.0.6)
  - Installing symfony/routing (v3.0.4)
    Loading from cache

  - Removing symfony/process (v3.0.6)
  - Installing symfony/process (v3.0.4)
    Loading from cache

  - Removing symfony/polyfill-util (v1.2.0)
  - Installing symfony/polyfill-util (v1.1.1)
    Loading from cache

  - Removing symfony/polyfill-php56 (v1.2.0)
  - Installing symfony/polyfill-php56 (v1.1.1)
    Loading from cache

  - Removing symfony/http-foundation (v3.0.6)
  - Installing symfony/http-foundation (v3.0.4)
    Loading from cache

  - Removing symfony/event-dispatcher (v3.0.6)
  - Installing symfony/event-dispatcher (v3.0.4)
    Loading from cache

  - Removing symfony/debug (v3.0.6)
  - Installing symfony/debug (v3.0.4)
    Loading from cache

  - Removing symfony/http-kernel (v3.0.6)
  - Installing symfony/http-kernel (v3.0.4)
    Loading from cache

  - Removing symfony/finder (v3.0.6)
  - Installing symfony/finder (v3.0.4)
    Loading from cache

  - Removing symfony/console (v3.0.6)
  - Installing symfony/console (v3.0.4)
    Loading from cache

  - Removing swiftmailer/swiftmailer (v5.4.2)
  - Installing swiftmailer/swiftmailer (v5.4.1)
    Loading from cache

  - Removing laravel/framework (v5.2.34)
  - Installing laravel/framework (v5.2.31)
    Loading from cache

  - Removing graham-campbell/core (v5.1.0)
  - Installing graham-campbell/core (v4.3.0)
    Loading from cache

  - Removing graham-campbell/exceptions (v8.5.0)
  - Installing graham-campbell/exceptions (v8.4.0)
    Loading from cache

  - Removing guzzlehttp/promises (1.2.0)
  - Installing guzzlehttp/promises (1.1.0)
    Loading from cache

  - Removing league/commonmark (0.13.3)
  - Installing league/commonmark (0.13.2)
    Loading from cache

  - Removing mccool/laravel-auto-presenter (4.3.0)
  - Installing mccool/laravel-auto-presenter (4.2.1)
    Loading from cache

  - Removing roumen/feed (v2.10.2)
  - Installing roumen/feed (v2.10.1)
    Loading from cache

Generating optimized autoload files
> Illuminate\Foundation\ComposerScripts::postInstall
> php artisan optimize --force
Generating optimized class loader
Compiling common classes
> php artisan config:cache
Configuration cache cleared!
Configuration cached successfully!
> php artisan route:cache
Route cache cleared!
Routes cached successfully!
qa-asus Cachet # php artisan app:update
Copied Directory [/vendor/roumen/feed/src/views] To [/resources/views/vendor/feed]
Publishing complete for tag []!
Nothing to migrate.
Clearing cache...
Application cache cleared!
Cache cleared!
qa-asus Cachet # php artisan up
Application is now live.
qa-asus Cachet # php artisan down
Application is now in maintenance mode.
qa-asus Cachet # git fetch origin
qa-asus Cachet # git tag -l
v0.1.0-alpha
v1.0.0
v1.1.0
v1.1.1
v1.2.0
v1.2.1
v2.0.0
v2.0.0-RC1
v2.0.0-RC2
v2.0.0-RC3
v2.0.0-RC4
v2.0.0-RC5
v2.0.0-beta1
v2.0.0-beta2
v2.0.1
v2.0.2
v2.0.3
v2.0.4
v2.1.0
v2.1.0-RC1
v2.1.0-RC2
v2.1.1
v2.1.2
v2.2.0
v2.2.0-RC1
v2.2.1
v2.2.2
v2.3.0-RC1
v2.3.0-RC2
v2.3.0-RC3
v2.3.0-RC4
v2.3.0-RC5
qa-asus Cachet # git checkout v2.3.0-RC5
Previous HEAD position was f79fada... Released 2.2.2
HEAD is now at 42aa437... Released 2.3.0 RC5
qa-asus Cachet # composer install --no-dev -o
Do not run Composer as root/super user! See https://getcomposer.org/root for details
Loading composer repositories with package information
Installing dependencies from lock file
  - Removing christian-riesen/base32 (1.3.0)
  - Installing christian-riesen/base32 (1.3.1)
    Loading from cache

  - Removing symfony/polyfill-mbstring (v1.1.1)
  - Installing symfony/polyfill-mbstring (v1.2.0)
    Loading from cache

  - Removing symfony/var-dumper (v3.0.4)
  - Installing symfony/var-dumper (v3.0.6)
    Loading from cache

  - Removing symfony/translation (v3.0.4)
  - Installing symfony/translation (v3.0.6)
    Loading from cache

  - Removing symfony/routing (v3.0.4)
  - Installing symfony/routing (v3.0.6)
    Loading from cache

  - Removing symfony/process (v3.0.4)
  - Installing symfony/process (v3.0.6)
    Loading from cache

  - Removing symfony/polyfill-util (v1.1.1)
  - Installing symfony/polyfill-util (v1.2.0)
    Loading from cache

  - Removing symfony/polyfill-php56 (v1.1.1)
  - Installing symfony/polyfill-php56 (v1.2.0)
    Loading from cache

  - Removing symfony/http-foundation (v3.0.4)
  - Installing symfony/http-foundation (v3.0.6)
    Loading from cache

  - Removing symfony/event-dispatcher (v3.0.4)
  - Installing symfony/event-dispatcher (v3.0.6)
    Loading from cache

  - Removing symfony/debug (v3.0.4)
  - Installing symfony/debug (v3.0.6)
    Loading from cache

  - Removing symfony/http-kernel (v3.0.4)
  - Installing symfony/http-kernel (v3.0.6)
    Loading from cache

  - Removing symfony/finder (v3.0.4)
  - Installing symfony/finder (v3.0.6)
    Loading from cache

  - Removing symfony/console (v3.0.4)
  - Installing symfony/console (v3.0.6)
    Loading from cache

  - Removing swiftmailer/swiftmailer (v5.4.1)
  - Installing swiftmailer/swiftmailer (v5.4.2)
    Loading from cache

  - Removing laravel/framework (v5.2.31)
  - Installing laravel/framework (v5.2.34)
    Loading from cache

  - Removing graham-campbell/core (v4.3.0)
  - Installing graham-campbell/core (v5.1.0)
    Loading from cache

  - Removing graham-campbell/exceptions (v8.4.0)
  - Installing graham-campbell/exceptions (v8.5.0)
    Loading from cache

  - Removing guzzlehttp/promises (1.1.0)
  - Installing guzzlehttp/promises (1.2.0)
    Loading from cache

  - Removing league/commonmark (0.13.2)
  - Installing league/commonmark (0.13.3)
    Loading from cache

  - Removing mccool/laravel-auto-presenter (4.2.1)
  - Installing mccool/laravel-auto-presenter (4.3.0)
    Loading from cache

  - Removing roumen/feed (v2.10.1)
  - Installing roumen/feed (v2.10.2)
    Loading from cache

  - Installing alt-three/throttle (v1.0.4)
    Loading from cache

  - Installing backup-manager/backup-manager (1.1.1)
    Loading from cache

  - Installing backup-manager/laravel (1.1.1)
    Loading from cache

  - Installing symfony/css-selector (v3.0.6)
    Loading from cache

  - Installing tijsverkoyen/css-to-inline-styles (1.5.5)
    Loading from cache

  - Installing fedeisas/laravel-mail-css-inliner (1.5)
    Loading from cache

Generating optimized autoload files
> Illuminate\Foundation\ComposerScripts::postInstall
> php artisan optimize --force
PHP Fatal error:  Class 'CachetHQ\Cachet\Foundation\Providers\GitHubServiceProvider' not found in /var/www/Cachet/vendor/laravel/framework/src/Illuminate/Foundation/ProviderRepository.php on line 146

                                                                                
  [Symfony\Component\Debug\Exception\FatalErrorException]                       
  Class 'CachetHQ\Cachet\Foundation\Providers\GitHubServiceProvider' not found  
                                                                                

Script php artisan optimize --force handling the post-install-cmd event returned with error code 255
qa-asus Cachet #

**Comment by jbrooksuk** [comment]
Ping @GrahamCampbell.

**Comment by GrahamCampbell** [comment]
Try running with `--no-scripts`, then run `php artisan app:update` yourself afterwards.

**Comment by GrahamCampbell** [comment]
Can you go into `bootstrap/cache`, and delete everything other than the `.gitignore` file, and then try to run that app update command again?

**Comment by abioneperhobby** [comment]
@GrahamCampbell , sure, i deleted config.php and routers.php, the only file contained inside the folder other than .gitignore.

now it work!

qa-asus cache # ls -a
.  ..  config.php  .gitignore  routes.php
qa-asus cache # dir
config.php  routes.php
qa-asus cache # rm config.php 
qa-asus cache # rm routes.php 
qa-asus cache # dir
qa-asus cache # cd ..
qa-asus bootstrap # cd ..
qa-asus Cachet # php artisan app:update
Clearing settings cache...
Settings cache cleared!
Backing up database...
Dumping database and uploading...

Successfully dumped mysql, compressed with gzip and store it to local at /var/www/Cachet/database/backups/2016-06-01 13.40.26
Backup completed!
Configuration cache cleared!
Configuration cached successfully!
Route cache cleared!
Routes cached successfully!
Copied Directory [/vendor/roumen/feed/src/views] To [/resources/views/vendor/feed]
Publishing complete for tag []!
Migrated: 2016_03_01_174858_AlterTableMetricPointsAddCounterColumn
Migrated: 2016_04_29_061916_AlterTableSubscribersAddGlobalColumn
Clearing cache...
Application cache cleared!
Cache cleared!
qa-asus Cachet # 

now application is up and running :-)

**Comment by jbrooksuk** [comment]
🎉
