### ISSUE TITLE
Feature Request: specify a sort order for list of incidents

### ISSUE THREAD

**Issue by Bekbolatov** [CachetHQ/Cachet#1872]
Sometimes one wants to get only the last incidents:  
GET .../incidents?...&order=desc

**Comment by jbrooksuk** [comment]
You can order Incidents by:

- `id`
- `name`
- `status`
- `visible`
- `message`

And you can filter incidents by:

- `id`
- `component_id`
- `name`
- `status`
- `visible`

This is part of the documentation updates I need to do this weekend :)

https://github.com/CachetHQ/Cachet/blob/2.3/app/Models/Incident.php#L72-L91

**Comment by Bekbolatov** [comment]
Thanks!
What about asc/desc?

**Comment by jbrooksuk** [comment]
You can use the `order` parameter and `asc` or `desc` such as `https://demo.cachethq.io/api/v1/incidents?order=desc`.
