### ISSUE TITLE
Feature Request: limit to a component, when getting a list of incidents

### ISSUE THREAD

**Issue by Bekbolatov** [CachetHQ/Cachet#1873]
Sometimes one wants to get only the incidents associated with some component:  
GET .../incidents?...&cid=69

**Comment by dhorbach** [comment]
+1. I'm fetching all incidents and doing manual filtering now which is not effective

**Comment by jbrooksuk** [comment]
This will be available in v2.3.0 - you'll simply request https://demo.cachethq.io/api/v1/incidents/?component_id=1

**Comment by doul59** [comment]
Hi,
Can you update documentation ?

Thanks and good job guys

**Comment by jbrooksuk** [comment]
I'll do this now, sorry for the delay in docs.

**Comment by jbrooksuk** [comment]
https://docs.cachethq.io/docs/advanced-api-usage
