### ISSUE TITLE
Undefined index: argv in ArgvInput.php

### ISSUE THREAD

**Issue by RedSpid3r** [CachetHQ/Cachet#1875]
Before submitting your issue, please make sure that you've checked all of the checkboxes below.

- [ ] You're running the [latest release](https://github.com/CachetHQ/Cachet/releases/latest) version of Cachet.
- [x] Ensure that you're running at least PHP 5.5.9, you can check this by running `php -v`
- [x] You've ran `rm -rf bootstrap/cache/*` from the root of your Cachet installation.

To help us better understand your issue, please answer the following — cheers!

### Your setup

- *What version of Cachet?* 2.3.0-dev
- *What database driver? MySQL? Postgres? SQLite?* MySQL
- *What version of PHP?* 5.6 

[01-Jun-2016 08:16:01 UTC] PHP Notice:  Undefined index: argv in /home/*******/vendor/symfony/console/Input/ArgvInput.php on line 55

[01-Jun-2016 08:16:01 UTC] PHP Warning:  array_shift() expects parameter 1 to be array, null given in /home/*******/vendor/symfony/console/Input/ArgvInput.php on line 59

**Comment by GrahamCampbell** [comment]
How did you get that error please?

**Comment by RedSpid3r** [comment]
It was in my error_log

**Comment by GrahamCampbell** [comment]
I meant, what did you do to get that error? Is cachet crashing?

**Comment by RedSpid3r** [comment]
Cachet seems to be working fine (as far as i can tell!), i was just doing a routine check in the error log and noticed it

**Comment by GrahamCampbell** [comment]
Hmm, ok.
