### ISSUE TITLE
Can`t access dashboard. Error 500.

### ISSUE THREAD

**Issue by LostinAllThatCode** [CachetHQ/Cachet#1877]
Before submitting your issue, please make sure that you've checked all of the checkboxes below.

- [x] You're running the [latest release](https://github.com/CachetHQ/Cachet/releases/latest) version of Cachet.
- [x] Ensure that you're running at least PHP 5.5.9, you can check this by running `php -v`
- [x] You've ran `rm -rf bootstrap/cache/*` from the root of your Cachet installation.

To help us better understand your issue, please answer the following — cheers!

### Your setup

Cachet 2.3
MySQL
PHP 5.6.21

### Expected behaviour

Access to dashboard. :D

### Actual behaviour

Can't get to the dashboard page. The actual cachet status website is working,

### Laravel Log
http://pastebin.com/34YKWtQj

**Comment by jbrooksuk** [comment]
Replaced with #1878, this will affect more than just your server configuration :)
