### ISSUE TITLE
Use Of Facades :(

### ISSUE THREAD

**Issue by GrahamCampbell** [cachethq/Cachet#188]
Can we only uses facades in controllers and views please, and use dependency injection everywhere else?

**Comment by jbrooksuk** [comment]
For ease of example, can you change one to follow this rule, then I'll update the rest.

**Comment by GrahamCampbell** [comment]
Also, I'd recommend always importing fully qualified class names for the faces, and deleting all the class aliases apart from the html facade, because you might want to use that in your views. That will force you to write better code. NB, this works better if you have integration tests because you spot the issues immediately if you delete the aliases.

**Comment by GrahamCampbell** [comment]
Infact, this is one refactor I'd be happy to help with.

**Comment by jbrooksuk** [comment]
That'd be awesome Graham!

**Comment by GrahamCampbell** [comment]
One thing we need to watch out for is poorly written packages that assume a load of facade aliases.

**Comment by GrahamCampbell** [comment]
Packages should never use facades as far as I'm concerned. Using them is assuming far to much about the environment they're being used in.

**Comment by jbrooksuk** [comment]
How do you not use them then?

**Comment by GrahamCampbell** [comment]
Very easily. All of my packages don't use them (appart from the credentials package, because that's not relly a package in the same sense).

**Comment by GrahamCampbell** [comment]
Check out the source for this package for example: https://github.com/GrahamCampbell/Laravel-Throttle.

**Comment by GrahamCampbell** [comment]
All the framework specific code is in the service provider, and my other classes accept dependencies by constructor injection. Very flexible.

**Comment by GrahamCampbell** [comment]
NB, my packages do provide facades for those people who really want them.

**Comment by GrahamCampbell** [comment]
They just don't consume any.

**Comment by jbrooksuk** [comment]
Gotcha. I really need to spend some time learning decent design patterns such as service layers, dependency injection etc - your packages will be perfect examples :)

**Comment by GrahamCampbell** [comment]
I think I'm going to do this in small bits, so if I break anything, we can detect it quickly.

**Comment by jbrooksuk** [comment]
Sure :)

**Comment by GrahamCampbell** [comment]
Also, dingo is an example of a well written package. cachet uses it, and dingo doesn't go near facades.

**Comment by joecohens** [comment]
:+1:

**Comment by GrahamCampbell** [comment]
This has been improved some what in my refactoring pulls, but it's not quite done yet.

**Comment by GrahamCampbell** [comment]
I'm going to work on cleaning up the repositories, then i'm going to to cleanup the views code, ie, remove http/model stuff, then i'm going to cleanup and namespace the models.

**Comment by jbrooksuk** [comment]
:+1:

**Comment by joecohens** [comment]
:+1:
