### ISSUE TITLE
Internal Server Error CentOS 6

### ISSUE THREAD

**Issue by haynes11** [CachetHQ/Cachet#1884]
Before submitting your issue, please make sure that you've checked all of the checkboxes below.

- [X ] You're running the [latest release](https://github.com/CachetHQ/Cachet/releases/latest) version of Cachet.
- [X ] Ensure that you're running at least PHP 5.5.9, you can check this by running `php -v`
- [ X] You've ran `rm -rf bootstrap/cache/*` from the root of your Cachet installation.

To help us better understand your issue, please answer the following — cheers!

### Your setup

- *What version of Cachet?* Latest - 2.3?
- *What database driver? MySQL? Postgres? SQLite?* - Mysql
- *What version of PHP?*  5.6.22

### Expected behaviour

*Please describe what you're expecting to see happen.*

Setup Screen to appear
### Actual behaviour
Internal Server Error
![screenshot_1](https://cloud.githubusercontent.com/assets/19718532/15762085/bfe2aa2a-2913-11e6-9570-a140e8215d67.jpg)
![screenshot_2](https://cloud.githubusercontent.com/assets/19718532/15762087/bfe5bd50-2913-11e6-93ff-d858e4f995ff.jpg)
![screenshot_11](https://cloud.githubusercontent.com/assets/19718532/15762086/bfe5045a-2913-11e6-8198-3d72849bdabd.jpg)

*Please describe what you're actually seeing happen.*
Finishing setup using official documentation on Cent OS 6. Go to the my fqdn/ip and I get: "Internal Server Error" I've tried running ALL permissions changes/rm -rf commands on the official documentation. I have no idea where logging from Cachet goes otherwise I would produce a log file. I've followed the instructions to the letter several times on the documentation.

Kind Regards,
Jerome Haynes

**Comment by cuddylier** [comment]
I'm also getting 'Internal Server Error' on Nginx after following the documentation very carefully and everything seemingly succeeding.

http://i.imgur.com/bw8B5nC.png

**Comment by GrahamCampbell** [comment]
If you're still having trouble, we offer a professional install service at $99.

Just get in touch at support@alt-three.com.

**Comment by cuddylier** [comment]
You're not even willing to let us know things to check? :(

**Comment by GrahamCampbell** [comment]
Common issues include incorrect file permissions and forgetting quotes around entries that contain spaces in them in the .env ifle.

**Comment by GrahamCampbell** [comment]
Getting a more standard error page like that indicates you've not setup php right, rather than cachet.

**Comment by haynes11** [comment]
I've setup php with all that is required on the documentation, unsure of what else to check or what log to look in for this specific issue. Any ideas?

Kind Regards,
Jerome Haynes

**Comment by haynes11** [comment]
<VirtualHost *:80>
    ServerAdmin thejeromeohaynes@gmail.com
    ServerName monitorthe.online
    ServerAlias www.monitorthe.online
    DocumentRoot "/var/www/html/monitorthe.online/public_html/public"
    <Directory "/var/www/html/monitorthe.online/public_html/public">
        Require all granted 
        # Used by Apache 2.4
        Options Indexes FollowSymLinks
        AllowOverride All
        Order allow,deny
        Allow from all
    </Directory>
</VirtualHost>

Is what's in my virtual host file. After looking in the log about an auth issue, I googled it and it said to remove "Require all granted "

Assumed that this would just be ignored, but removing it fixes the issue. For Cent OS 6 your file should look like:

<VirtualHost *:80>
    ServerAdmin thejeromeohaynes@gmail.com
    ServerName monitorthe.online
    ServerAlias www.monitorthe.online
    DocumentRoot "/var/www/html/monitorthe.online/public_html/public"
    <Directory "/var/www/html/monitorthe.online/public_html/public">
        Require all granted 
        # Used by Apache 2.4
        Options Indexes FollowSymLinks
        AllowOverride All
        Order allow,deny
        Allow from all
    </Directory>
</VirtualHost>

**Comment by jbrooksuk** [comment]
Are you using Apache 2.4?

**Comment by cuddylier** [comment]
I switched to Apache and managed to get the install done however it now goes to an Internal server error (Error 500) after logging into the admin dashboard, loading the main status page works fine.

**Comment by GrahamCampbell** [comment]
Please upload your log files to pastebin and link here.

**Comment by cuddylier** [comment]
@GrahamCampbell There is nothing in the /var/log/apache2/error.log since I fixed some permissions issues I was having. Any other logs you wish me to check? I put in a 45 character password on the account setup page that had special characters in it, that isn't related no?

**Comment by GrahamCampbell** [comment]
> There is nothing in the /var/log/apache2/error.log since

Please look at the logs inside Cachet. `/storage/logs`.

**Comment by cuddylier** [comment]
@GrahamCampbell 

I think this is it: Next exception 'Illuminate\Database\QueryException' with message 'SQLSTATE[42S02]: Base table or view not found: 1146 Table 'status.cache' doesn't exist (SQL: select * from `$
Stack trace:

I selected database for both of the options on the install page 1.

**Comment by GrahamCampbell** [comment]
@jbrooksuk We should publish the database cachet migrations.

**Comment by cuddylier** [comment]
@GrahamCampbell Anyway to create the table in the meantime?

**Comment by jbrooksuk** [comment]
I thought we did?

**Comment by GrahamCampbell** [comment]
No, only the sessions. I think we should not allow database caching though.

**Comment by GrahamCampbell** [comment]
Can we delete it from thee GUI? It's slow as shit. People are better of using apc, or file.

**Comment by cuddylier** [comment]
If I just change the .env to file for the caching, will that work straight away or did it need to re-run the installer somehow?

**Comment by peterborghard** [comment]
@cuddylier I had a similar issue(centos 6/apache 2.2) and removed 'Require all granted' from the virtualhost config and things started working.  Try commenting that out in the config and restarting apache.

**Comment by cuddylier** [comment]
@peterborghard Yeah, I did that and it seems to have resolved everything. Once everything was setup and working on Apache, I switched back to Nginx and it seems to work fine too. The 'RSS' and 'Atom' links at the bottom of the status page both show an error page with 'This XML file does not appear to have any style information associated with it. The document tree is shown below.' however I cannot find them mentioned in the documentation so I guess they maybe don't do anything yet.

**Comment by jbrooksuk** [comment]
The XML feed is fine; http://validator.w3.org/check?uri=https%3A%2F%2Fdemo.cachethq.io%2Frss&charset=%28detect+automatically%29&doctype=Inline&group=0 it's your browser (I guess) telling you it can't render it like HTML (I think),

**Comment by jbrooksuk** [comment]
Feeds work perfectly :)

**Comment by jbrooksuk** [comment]
Can you email our support@alt-three.com address for installation support please 😄
