### ISSUE TITLE
Add the ability to enable/hide a component group

### ISSUE THREAD

**Issue by barchard** [CachetHQ/Cachet#1892]
I have a component group that I don't want to be displayed. I would, however, like to record data on it. As a feature request, it'd be nice to be able to hide an entire component group from being displayed.

**Comment by jbrooksuk** [comment]
Since v2.3.0 is delayed anyway, I'll aim to get this done.

**Comment by dbarentine** [comment]
We also have certain component groups that we don't want visible to reduce end user confusion but we want our internal team members (who would have user accounts) to be able to see it on the status page. So it would be nice if it was one of three options, Viewable by public, Only visible to logged in users, and Hidden. Basically something similar to how Incident Visibility works.

It would also be nice if this could be done with metrics as well.

**Comment by jbrooksuk** [comment]
Sure, could you open a new issue for this **and** the metrics please? :)

**Comment by dbarentine** [comment]
Sure do you want them separated into two issues?

**Comment by jbrooksuk** [comment]
Pretty please! :)

**Comment by yoyosan** [comment]
Hello.

Is it ok with you if I work on this?

**Comment by yoyosan** [comment]
@barchard do you want the hidden component groups(see the comments in #1897) to not be displayed on both the status and dashboard pages?

**Comment by barchard** [comment]
@yoyosan whatever is public should be hidden. For example, I have a group called "name servers" users don't care about this, but as an admin, I want to track it for myself.
