### ISSUE TITLE
error 500: this app is not Heroku friendly

### ISSUE THREAD

**Issue by hadifarnoud** [CachetHQ/Cachet#1893]
Cachet version 2.2.2
Database Postgres
PHP version 7.0.7

I'm running into all kinds of issues with Cachet. I managed to solve most issues myself but have no idea how to solve this one.

it seems like Cachet relies on dotenv package to load environment variables even in production. This is creating issue with Heroku. 

in order to get over dotenv issue I committed an empty .env, but still can't manage to fix this 500 error

`[2016-06-04 13:39:47] production.ERROR: InvalidArgumentException: View [setup] not found. in /app/bootstrap/cache/compiled.php:14326`

**Comment by jbrooksuk** [comment]
You need to run `rm -rf bootstrap/cache/*` to fix the view not found issue.

**Comment by hadifarnoud** [comment]
I have done that @jbrooksuk with `heroku run rm -rf bootstrap/cache/*`  I checked afterwards and the directory was empty.

**Comment by hadifarnoud** [comment]
the real issue is this:
`[04-Jun-2016 13:58:08 UTC] [2016-06-04 13:58:08] production.ERROR: Dotenv\Exception\InvalidPathException: Unable to read the environment file at /app/.env. in /app/vendor/vlucas/phpdotenv/src/Loader.php:75`

for some reason, it looks for `.env` in production, which is not how Heroku works. I have to commit an empty .env file to fix this and that led to the issue I mentioned above.

**Comment by hadifarnoud** [comment]
it seems like ENV variables are not read from Heroku

**Comment by jbrooksuk** [comment]
That's how Laravel works. Laravel reads the `.env` file.

Unfortunately, we don't support Heroku out of the box :)

**Comment by hadifarnoud** [comment]
there seems to be [a solution](https://github.com/vlucas/phpdotenv/issues/63#issuecomment-89419664) to this. not exactly sure how should this apply it to Cachet

**Comment by hadifarnoud** [comment]
this is not how you should use Dotenv. I don't know why you're loading it [here](https://github.com/CachetHQ/Cachet/blob/2.2/app/Http/Controllers/SetupController.php#L252) for example.

I'm going to fork this and fix it.

**Comment by jbrooksuk** [comment]
Like I said, this is how Laravel works.

During the setup we have to write to the file, so we do have to load Dotenv.

If you have a PR that can fix this on Heroku **and** remain working for everybody else, I'm happy to take a look :)

**Comment by anonrig** [comment]
It would be really good if Heroku was supported.

**Comment by yoyosan** [comment]
I can take a swing at this.

**Comment by jbrooksuk** [comment]
> I can take a swing at this.

Sure, thanks.

**Comment by cjthomp** [comment]
Sure wish I'd seen this before I wasted two hours setting it up.

**Comment by jbrooksuk** [comment]
@cjthomp did you manage to get setup? We dropped Heroku support over a year ago now.
