### ISSUE TITLE
Subscribers not showing

### ISSUE THREAD

**Issue by cuddylier** [CachetHQ/Cachet#1894]
- [x] You're running the [latest release](https://github.com/CachetHQ/Cachet/releases/latest) version of Cachet.
- [x] Ensure that you're running at least PHP 5.5.9, you can check this by running `php -v`
- [x] You've ran `rm -rf bootstrap/cache/*` from the root of your Cachet installation.

I'm running 2.3.0-RC5 however there is no option on the status page for anyone to subscribe eventhough the 'Allow people to signup to email notifications?' option is enabled in the dashboard and there is no option on the 'Subscribers' tab to add a new subscriber manually (if that's a feature).

**Comment by jbrooksuk** [comment]
Have you configured the `.env` file to setup mail? https://docs.cachethq.io/docs/setup-subscribers

**Comment by cuddylier** [comment]
@jbrooksuk Yes and the mail setup works fine as I tried the 'invite team member' option in the dashboard and the email was received okay.

**Comment by jbrooksuk** [comment]
The button should be in the footer, is this not the case?

**Comment by cuddylier** [comment]
Correct, not the case: http://status.spartanhost.net

**Comment by jbrooksuk** [comment]
Can you try upgrading to RC6?

**Comment by jbrooksuk** [comment]
If this doesn't work, could you contact support@alt-three.com for Installation support please 😄
