### ISSUE TITLE
Test email configuration

### ISSUE THREAD

**Issue by barchard** [CachetHQ/Cachet#1896]
I've set up a 'Subscribe' option for my users but I have no way to test the email configuration. It might be useful to have a 'test email configuration' button to verify that the credentials and settings are working properly.

**Comment by jbrooksuk** [comment]
We'll include this in v3.0.0 I think.

**Comment by serrexlabs** [comment]
May I know where this feature goes and little bit information about it ?

**Comment by barchard** [comment]
I am having issues setting up and configuring email in Cachet. It'd be nice to be able to send a test email to myself and see if there was any errors or issues with the mail transport (e.g., invalid SMTP or Mailgun credentials)

**Comment by serrexlabs** [comment]
Alright got it. Will work on that.

**Comment by jbrooksuk** [comment]
That'd be awesome!

**Comment by jbrooksuk** [comment]
@serrexlabs I'm really looking forward to this!

**Comment by serrexlabs** [comment]
@jbrooksuk I already did UI part , now I'm working on email configuration testing part. If needed I can create WIP pull request.

**Comment by jbrooksuk** [comment]
Yes please. We can give you feedback then :)

**Comment by serrexlabs** [comment]
@jbrooksuk  I've created a pull request.

**Comment by serrexlabs** [comment]
@jbrooksuk Shall I move to writeEnv method in `SetupController` to helper.php, have to reuse this methoid `SetupMailCommand` or is there any better place to put.

**Comment by jbrooksuk** [comment]
You do as you feel best for now and then we'll review :)

**Comment by jbrooksuk** [comment]
This is now done 😄 

![Screenshot](https://cldup.com/erUF_fiHRH.png)

**Comment by Cigizmoond-Vyhuholev** [comment]
When will be release of 2.4.0 version on docker-hub?
