### ISSUE TITLE
Add the ability to control component group visibility by user authentication

### ISSUE THREAD

**Issue by dbarentine** [CachetHQ/Cachet#1897]
We also have certain component groups that we don't want visible to reduce end user confusion but we want our internal team members (who would have user accounts) to be able to see it on the status page. So it would be nice if we could control visibility based on three options, Viewable by public, Only visible to logged in users, and Hidden. Basically something similar to how Incident Visibility works.

Similar to issue 1892 but with finer grain level of visibility.

**Comment by jbrooksuk** [comment]
This could be part of https://github.com/CachetHQ/Cachet/issues/236, so I'll move this into the v2.5.0 milestone.

**Comment by yoyosan** [comment]
Hi.

I'd like to work on this since it's part of #1892 .

For the components group, I am thinking of:
- adding a `visible` int column to the `component_groups` table with the three possible values mentioned above `0 - Viewable by public, 1 - Only visible to logged in users, 2 - Hidden`.
- rephrase the existing `Choose visibility of the group` label to `Expand/Collapse` options.

What do you think?

**Comment by jbrooksuk** [comment]
I like it! Looking forward to seeing your contribution @yoyosan!

@joecohens @GrahamCampbell and I are at Laracon US this week, so it might be that reviewing of your PR is delayed until we're back, but don't worry!

**Comment by yoyosan** [comment]
@dbarentine I'm not sure why you need the Hidden option.

Did you maybe thought it should be visible only to the creator?

**Comment by yoyosan** [comment]
I can't figure out why running the tests is stuck. Here's the output:
```
➜  Cachet git:(add-visibility-to-component-groups) ✗ phpunit -v tests
PHPUnit 4.8.21 by Sebastian Bergmann and contributors.

Runtime:        PHP 7.0.9
Configuration:  /home/yoyosan/Work/PHP/Cachet/phpunit.xml.dist

...............................................................  63 / 808 (  7%)
............................................................... 126 / 808 ( 15%)
............................................................... 189 / 808 ( 23%)
.............F...............................................F. 252 / 808 ( 31%)
............................................................... 315 / 808 ( 38%)
.............................................
```

**Comment by yoyosan** [comment]
The next step is to add functional tests for the code I've added :)

**Comment by dbarentine** [comment]
@yoyosan For our use we don't actually need the hidden option but I think I was trying to include it for completeness.

Specifically, I was trying to include the request from 1892 which wanted to hide the component group but still collect data on it via the API.

It could also be useful as you are creating new component group but don't want to expose it to anyone yet. So in that case exposing it only to the creator would be fine.

**Comment by yoyosan** [comment]
@dbarentine will add this too then.

**Comment by yoyosan** [comment]
Regarding phpunit, found the fix in 1721.

**Comment by yoyosan** [comment]
Things left to do:

- [ ] Fix existing tests
- [ ] Add dashboard functional tests for the displayed component groups as a guest vs logged in
- [ ] Add API tests for guest vs with TOKEN requests
- [ ] Using TDD, add hidden functionality for component groups(waiting for answer on #1892)

**Comment by yoyosan** [comment]
Weird behaviour I've noticed:
- [ ] For the dashboard, you need the component group to have at least one component in order to be displayed. For the API, the component group doesn't need to have any.

**Comment by jbrooksuk** [comment]
@yoyosan where exactly do you mean in the dashboard? On the index?

**Comment by yoyosan** [comment]
Yes, on the index page(`StatusPageController::showIndex`).

**Comment by jbrooksuk** [comment]
Oh, not the dashboard, sorry I misunderstood.

**Comment by jbrooksuk** [comment]
This is the expected behaviour, though. The UI shouldn't show an empty group, but the consumers of the API want to know about all groups.

**Comment by yoyosan** [comment]
Bad phrasing, sorry.

**Comment by jbrooksuk** [comment]
> Bad phrasing, sorry.

Nah, I'm just a numpty.

**Comment by yoyosan** [comment]
> Nah, I'm just a numpty.

`! true` :)

**Comment by jbrooksuk** [comment]
Thank you for your input on Cachet 2.x. We are shifting our attention and resources to Cachet 3.x and will no longer be supporting the 2.x version. If your feedback or issue is relevant to the 3.x series, we encourage you to engage with the new branch.

For more information on the Cachet rebuild and our plans for 3.x, you can read the announcement [here](https://github.com/CachetHQ/Cachet/discussions/4342).

We appreciate your understanding and look forward to your contributions to the new version.
