### ISSUE TITLE
Add the ability to control metric visibility by user authentication

### ISSUE THREAD

**Issue by dbarentine** [CachetHQ/Cachet#1898]
We also have certain metrics that we don't want visible to reduce end user confusion but we want our internal team members (who would have user accounts) to be able to see it on the status page. So it would be nice if we could control visibility based on three options, Viewable by public, Only visible to logged in users, and Hidden. Basically something similar to how Incident Visibility works.

**Comment by tejasshah93** [comment]
@jbrooksuk hi! this one up for grabs?
I've done some modifications to have metric options as "viewable by public" and "only visible to logged in users" (similar to how incident visibility works). Will add the "hidden" option soon.

Let me know👍

**Comment by jbrooksuk** [comment]
@tejasshah93 yes it is! If you make a PR for this, could you do so on the 2.4 branch please? :)

**Comment by tejasshah93** [comment]
@jbrooksuk Sure thing! Will update here as and when done 👍 

P.S. I just noticed that you'll be off for Laracon US this week. Nice :)

**Comment by jbrooksuk** [comment]
I will indeed! Are you there?

Hopefully I'll get some time to review your PR over the week, if not, it's on my list for once I'm back!

**Comment by tejasshah93** [comment]
Unfortunately, no. Though glad to know you'll be making it to Laracon!

I'll also be hitting the road this week and would create a PR mostly by next week itself. So, no worries as such :) Thanks!

**Comment by jbrooksuk** [comment]
Thanks man! :)

**Comment by jbrooksuk** [comment]
I've just checked and this is a thing in v2.4 :)
