### ISSUE TITLE
Client libraries docs broken

### ISSUE THREAD

**Issue by eladnava** [CachetHQ/Cachet#1899]
Hey guys,
The [client libraries docs](https://docs.cachethq.io/docs/client-libraries) are broken for some reason.

Getting a blank page:

![screen shot 2016-06-06 at 11 53 00 pm](https://cloud.githubusercontent.com/assets/4394189/15837412/d6b06afe-2c41-11e6-9174-85dc3fc75e07.png)

**Comment by jbrooksuk** [comment]
Thanks for the bug report, I've fixed it. https://docs.cachethq.io/docs/client-libraries

**Comment by eladnava** [comment]
@jbrooksuk Cool, thanks! I'm thinking about building a Node.js package for interfacing with the Cachet API =)

**Comment by jbrooksuk** [comment]
I look forward to seeing it :)

**Comment by eladnava** [comment]
@jbrooksuk Here it is! =)
https://www.npmjs.com/package/cachet-api

**Comment by jbrooksuk** [comment]
Docs updated to include a link to the NPM package, thanks!

**Comment by eladnava** [comment]
Cool, thanks! 👍
