### ISSUE TITLE
No link to subscribe (version 2.2.1)

### ISSUE THREAD

**Issue by Bekbolatov** [CachetHQ/Cachet#1902]
There appears to be no link to subscribe on the main page, even though in administration - this is checked "Allow people to signup to email notifications?".

Also, is it possible to signup to receive notification limited only to selected components?

**Comment by GrahamCampbell** [comment]
Yes, in 2.3.x.

**Comment by Bekbolatov** [comment]
Awesome - so the second part is also a yes?
> ... is it possible to signup to receive notification limited only to selected components?

We will upgrade the newer version.  Is "pre-release" v2.3.0-RC5 stable enough to use in production, when compared to 2.2.1?

**Comment by GrahamCampbell** [comment]
Our stable releases have the same stability guarantees as our RC releases (none at all).

**Comment by GrahamCampbell** [comment]
> THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

**Comment by GrahamCampbell** [comment]
Please let me know if you have any issues with the latest 2.3 branch. It is currently deployed to https://status.styleci.io and is working well.

**Comment by Bekbolatov** [comment]
Thanks!

**Comment by Bekbolatov** [comment]
Just checked the provided URL - there doesn't appear to be any link to sign up for notifications.

**Comment by jbrooksuk** [comment]
We don't have sign ups on StyleCI.

**Comment by GrahamCampbell** [comment]
Yeh, we've turned that feature off on that status page. I mainly linked it to demonstrate that the whole status page is working fine in a real production environment.

**Comment by Bekbolatov** [comment]
Perfect - thanks!
I guess we will go ahead and try out 2.3.0-RC5.

**Comment by GrahamCampbell** [comment]
I'd recommend using the latest 2.3-dev. RC5 has known issues.

**Comment by Bekbolatov** [comment]
Upgraded to 2.3.0-RC6, set "Allow people to signup to email notifications?" to true, but still no link to sign up for notifications.

**Comment by jbrooksuk** [comment]
@Bekbolatov have you configured the [Mail Settings](https://docs.cachethq.io/docs/configuring-mail)?

**Comment by Bekbolatov** [comment]
Our DevOps team configured and restarted services and the link showed up. Thanks!
