### ISSUE TITLE
Issue when creating new metric

### ISSUE THREAD

**Issue by fdhex** [CachetHQ/Cachet#1903]
This might be an issue of understanding what the question means but I saw no docs on this so I tried what seemed logical to me.

Before submitting your issue, please make sure that you've checked all of the checkboxes below.

- [ X] You're running the [latest release](https://github.com/CachetHQ/Cachet/releases/latest) version of Cachet.
- [ X] Ensure that you're running at least PHP 5.5.9, you can check this by running `php -v`
- [ X] You've ran `rm -rf bootstrap/cache/*` from the root of your Cachet installation.

To help us better understand your issue, please answer the following — cheers!

### Your setup

- *What version of Cachet?* 2.3.0
- *What database driver? MySQL? Postgres? SQLite?* Postgres
- *What version of PHP?* 5.6.20-0+deb8u1

### Expected behaviour

Metric creation

### Actual behaviour

When creating a new metric, I would like a per hour view over 12 hours, so I select a 12 hours default view, then for the question: "How many minutes of threshold between metric points?" I put 60. The metric does not get created and the following message appears on top:

"
Whoops. Something went wrong with the metric, please try again.

The threshold must be a date before :date.
"
!

### Steps to reproduce

![metric](https://cloud.githubusercontent.com/assets/902517/15894533/a0f119f4-2d86-11e6-8a6b-34b5f4252b7d.png)

**Comment by jbrooksuk** [comment]
Whoops! Thanks for the bug report, this will be fixed shortly.

**Comment by jbrooksuk** [comment]
This is fixed in the latest RC :)
