### ISSUE TITLE
Endless setup loop.

### ISSUE THREAD

**Issue by xxxkilldogxxx** [CachetHQ/Cachet#1907]
### Your setup

- What version of Cachet? 2.3 RC6
- *What database driver? Postgres
- *What version of PHP?* 5.6

### Expected behaviour

After completing the setup I am directed to the dashbord correctly however when going back to view the status page I am redirected once again back to the setup process even though I have completed it once already.

### Actual behaviour

I should see the status page rather than the setup process.

### Steps to reproduce

*If your issue requires any specific steps to reproduce, please outline them here.*

**Comment by GrahamCampbell** [comment]
What cache driver please? Is your bootstrap/cachet folder writable by the webserver?

**Comment by xxxkilldogxxx** [comment]
It was all because cachet was not writable... thank 
you!

**Comment by tejasshah93** [comment]
Suggestion by @GrahamCampbell works! Happened with me too.. `bootstrap/cachet` was not writable. Thanks! 👍
