### ISSUE TITLE
Package installs fails when publishing translations.

### ISSUE THREAD

**Issue by mrbase** [CachetHQ/Cachet#1908]
- *What version of Cachet?* 2.2.4
- *What database driver? MySQL? Postgres? SQLite?* MySQL
- *What version of PHP?* 7.0.7

I'm refactoring a package I created for Slack integration with Cachet. But when I follow the Laravel directions for adding languages, Cachet fails do to [this piece of code](https://github.com/CachetHQ/Cachet/blob/v2.2.4/app/Composers/TimezoneLocaleComposer.php#L32-L36).

Language files are published to `resource_path('lang/vendor/courier')` - which for Cachet is `app/lang`- but adding the `vendor` folder here breaks the code above, because `vendor` is not a language, and not registered in `$enabledLangs`

I added the following - not the best solution, but it works for my local need right now:

```php
if (empty($enabledLangs[$locale])) {
    return [];
}
```

When creating packages for Cachet, is there some other directions we need to follow, or ... ?

**Comment by GrahamCampbell** [comment]
Same as for laravel. ;)

**Comment by jbrooksuk** [comment]
Languages are located in `resources/lang`, not `app/lang` :)

**Comment by mrbase** [comment]
Ermh, ok there was an error in my post... The files are published to `resources/lang/vendor`.

I don't think I understood the answer tho.

I use this to publish the language file in my package:
```php
$this->publishes([__DIR__.'/resources/lang' => resource_path('lang/vendor/slack'));
```
The code is more or less copy/pasted from the [Laravel docs](https://laravel.com/docs/5.2/packages#translations) on package development - So what should I change the `lang/vendor/slack` path to ? `lang/[lang code]/slack` ?
