### ISSUE TITLE
Manage Subscriptions

### ISSUE THREAD

**Issue by karthik-22feb** [CachetHQ/Cachet#1909]
Hi Team,

I am using the latest version of CACHE ( 2.3.0-RC4). The Manage subscription page shows the list of all the component in one list.

Is it possible to show the components on Manage Subscription page by COMPONENT GROUP with expand/Collapse feature.

Let me know about your thoughts.

![manage_subscriptions](https://cloud.githubusercontent.com/assets/17992464/16015879/c9201528-3165-11e6-9d52-2354d0e4e0c6.jpg)

Thanks,
Karthik

**Comment by jbrooksuk** [comment]
Yes, this makes a bit of sense.

**Comment by GrahamCampbell** [comment]
> I am using the latest version of CACHE ( 2.3.0-RC4).

That is not the latest vesion.

**Comment by jbrooksuk** [comment]
> That is not the latest version.

Still doesn't change though :)

**Comment by karthik-22feb** [comment]
Hi Team,

Is there an patch update for this change that i could use ?

Thanks,
Karthik

**Comment by jbrooksuk** [comment]
Not yet, no, it'll probably be available in v2.3.0

**Comment by jbrooksuk** [comment]
Pushing this to v3.0.0 which includes a new design anyway.

**Comment by peelman** [comment]
@jbrooksuk is this something you are actively developing?  Planning on making some changes / pull requests early next week, a pass at this could be among them.

**Comment by peelman** [comment]
I had some free time this evening, so I worked this up...

![screen shot 2016-07-15 at 23 25 41](https://cloud.githubusercontent.com/assets/52936/16892528/7e8fe28a-4ae3-11e6-848c-e4cfa7c5c190.PNG)

If there's interest and/or feedback, I will roll it into a pull request on Monday.

**Comment by jbrooksuk** [comment]
@peelman this looks nice! If you can remove the blue outer panel, then that'd be perfect! We'd love to see a PR for this change.

Could you do it on the `master` branch please.

**Comment by peelman** [comment]
Wilco. I'll make sure to apply this against the current master on Monday and ship it over. I'll go back to a panel-default along the way. I'm rather partial to the blue outer box, so I'll probably be reapplying that change for our instance though. ;)

**Comment by barchard** [comment]
hi, is this released or still being pushed to 3? i am currently fighting service overload too! thanks :)

![status](https://cloud.githubusercontent.com/assets/17622/17350367/1f50ebb0-58f4-11e6-9d03-3736be48a9d9.jpg)

**Comment by jbrooksuk** [comment]
v3.0.0 is not out yet, and won't be for a while yet. It should've found its way into the latest v2.3.* versions though?

**Comment by barchard** [comment]
@jbrooksuk not from what i'm seeing.. currently running v2.3.7:

```
# git status
# HEAD detached at v2.3.7
```

**Comment by peelman** [comment]
My PR went into 2.4. But isn't in 2.3.7.

**Comment by barchard** [comment]
@peelman oooh. I guess I have to wait until 2.4 then. thanks
