### ISSUE TITLE
LastPass & the 'login' Field

### ISSUE THREAD

**Issue by peterlaws** [CachetHQ/Cachet#1910]
Does anyone else use LastPass? I do not log in much, but LastPass will not fill in the "login" field..... If I manually change the field to ``name="email"`` from ``name="login"``, it'll fill it.

I understand it's a LastPass issue, but it used to work.... You didn't change the field name at all?

**Comment by jbrooksuk** [comment]
We can't really call the field `email` as it also accepts the username.

I don't have use LastPass, but I will take a look and see what we can do.

**Comment by jbrooksuk** [comment]
Seems easy enough, I'll make the field called username as in this case, the email acts like your username too.
