### ISSUE TITLE
Unable make Email notification working. New subscribers added never receive the EMail

### ISSUE THREAD

**Issue by benlec** [CachetHQ/Cachet#1915]
Before submitting your issue, please make sure that you've checked all of the checkboxes below.

- [X] You're running the [latest release](https://github.com/CachetHQ/Cachet/releases/latest) version of Cachet.
- [W] Ensure that you're running at least PHP 5.5.9, you can check this by running `php -v`
- [ ] You've ran `rm -rf bootstrap/cache/*` from the root of your Cachet installation.
-> I put full control I'm on Windows

To help us better understand your issue, please answer the following — cheers!

### Your setup

- *What version of Cachet?* 2.2.4
- *What database driver? MySQL? Postgres? SQLite?* MySQL 5.6.3
- *What version of PHP?* 5.6.22.0
- Windows 2012 Server

### Expected behaviour

I add a new subscriber via the Dashboard and I would expect to receive an EMail

### Actual behaviour

I add new subscriber and never receive the emails.

### Steps to reproduce

Add New Subscriber
Enter an EMail Adress
OK Addition is succesfull in the Dashboard
-> Email is never received.

----------------------------------------------------------------------------------------------------------
NOTE: I'm Under Windows, so please do not send me Linux command, I don't know what is the equivalent Under Windows and specifically for the Cron Job commands, etc...
---------------------------------------------------------------------------------------------------------
.env file

MAIL_DRIVER=smtp
MAIL_HOST=myserverhere
MAIL_PORT=25
MAIL_USERNAME=null
MAIL_PASSWORD=null
MAIL_ADDRESS=null
MAIL_NAME=null
MAIL_ENCRYPTION=null (tried default TLS but it doesn't matter)
..
CACHE_DRIVER=file
SESSION_DRIVER=file
QUEUE_DRIVER=database
CACHET_EMOJI=false
------------------------------------------------------------------------------------------------------------

>When I change the .env file for my tests i run
php artisan config: cache -> OK Command successfull
>When i add a subscriber, i order to trigger the EMail notification i suppose i need to run this
php artisan Schedule: run -> OK command succesfull

I suppose there is an error in the Schedule command i send but I'm not sure. I don't understand the example given in the docs with the 1&2 thing...

Please help me to troubleshoot this. The app looks to be working file but I'm not able to add subscribers and receiving emails.

**Comment by benlec** [comment]
Fixed after adding MAIL_USERNAME and MAIL_PASSWORD info as I need to be authenticated to my server..... saw this in the storage\log

**Comment by jbrooksuk** [comment]
I'm glad you managed to sort this issue. Sorry for the lack of response.
