### ISSUE TITLE
Internal server error at setup page

### ISSUE THREAD

**Issue by xedro00** [CachetHQ/Cachet#1916]
I just followed the installation guide and installed it but when I visit my site it takes me to

www.mysite.com/setup and shows an Internal server error this is my log below.

http://pastebin.com/stTTKA0L

hope I can find a solution to this!

**Comment by jbrooksuk** [comment]
Did you run `php artisan app:install`?

**Comment by xedro00** [comment]
Yep! but no luck still the same.
http://puu.sh/pzDhh/96b96ae335.png

**Comment by GrahamCampbell** [comment]
Can you show us the output of `php artisan app:install` please? Are you running the latest 2.3 RC release?

**Comment by jbrooksuk** [comment]
The permissions are correct on `./bootstrap` and `./storage`?

**Comment by xedro00** [comment]
php artisan app:install
Clearing settings cache...
Settings cache cleared!
Backing up database...
Dumping database and uploading...

Successfully dumped mysql, compressed with gzip and store it to local at /home/bitsnap/backend/database/backups/2016-06-21 02.22.11
Backup completed!
Application key [base64:RRIWRZNE/KkajUMu3HBU70ZMBRfIYm3k+VBOuCPoXPg=] set successfully.
Configuration cache cleared!
Configuration cached successfully!
Route cache cleared!
Routes cached successfully!
Copied Directory [/vendor/roumen/feed/src/views] To [/resources/views/vendor/feed]
Publishing complete for tag []!
Nothing to migrate.
Clearing cache...
Application cache cleared!
Cache cleared!


Permission is correct for those folders.

**Comment by jbrooksuk** [comment]
Can you send us the full output of the most recent log file please?

**Comment by xedro00** [comment]
Here you go!

https://www.cyph0.com/paste/paste2321.log

**Comment by GrahamCampbell** [comment]
Looks like some of our files are missing from the public folder. Did you install them correctly?

**Comment by xedro00** [comment]
yes  I have uploaded every files!

**Comment by xedro00** [comment]
do I need to set permission for any folder in public?

**Comment by jbrooksuk** [comment]
Have you run `gulp`? (Don't do so, if you haven't).

**Comment by xedro00** [comment]
Nope! i have not run that!

**Comment by xedro00** [comment]
any update on this?

**Comment by jbrooksuk** [comment]
Try installing again as you seem to be missing the `./public/build` files, which **definitely** ship with Cachet, so it looks like your installation has gone crazy.

**Comment by xedro00** [comment]
well I am sure I have that folder in fact every folders and files.
http://puu.sh/pD0C9/e252dd34f9.png

**Comment by jbrooksuk** [comment]
What's within the `./public/build` directory? Can you give me the output of `tree` please.

**Comment by xedro00** [comment]
here you go.

http://puu.sh/pD1Q8/fab4fb0a59.png

**Comment by jbrooksuk** [comment]
And what files are within `./public/build/dist/js` and `./public/build/dist/css`?

**Comment by xedro00** [comment]
http://puu.sh/pD9hm/9db97378b6.png

http://puu.sh/pD9j4/41976d7bbd.png

**Comment by juniorb2ss** [comment]
This error also occurred to me. In the tag 2.2.4 dependencies of gulp are incorrect, all pointing to folder "vendor" and not "node_modules" in SCSS files. Upgrade to a current tag or do the merge manually

**Comment by jbrooksuk** [comment]
@xedro00 what version of Cachet are you using, sorry?

@juniorb2ss 2.2.4 worked here, I'm sure it did.

**Comment by xedro00** [comment]
2.3.0-dev

**Comment by xedro00** [comment]
please give an update!

**Comment by GrahamCampbell** [comment]
It's hard for us to guess what you've done wrong I'm afraid. We offer  a professional installation service for $99 if you are interested.

**Comment by jbrooksuk** [comment]
@joecohens I've noticed that the installation can break the `.env` file by writing one value across all keys. I've not had chance to re-produce this though.

**Comment by joecohens** [comment]
I think I know what's the problem, let me try to reproduce it

**Comment by xedro00** [comment]
do let me know if u get the solution :+1:
