### ISSUE TITLE
Component List - auto refresh

### ISSUE THREAD

**Issue by karthik-22feb** [CachetHQ/Cachet#1917]
Hi Team,

I am using the latest version of CACHE ( 2.3.0-RC4). Is it possible to auto refresh the component list on the frontpage every 5 seconds?

Do you have an custom code to implement this feature? Please let me know about your thoughts.
![components_demo_cachethq_io](https://cloud.githubusercontent.com/assets/17992464/16242762/09827978-37c2-11e6-9ff5-4e02d7ba7b38.jpg)

Thanks,
Karthik

**Comment by jbrooksuk** [comment]
This isn't something that we'll be implementing as a feature, but you can achieve this yourself by adding custom HTML into the header, which can be controlled from the Dashboard.
