### ISSUE TITLE
some graphs are not correct after upgrade to 2.3.0-RC6 (from 2.1)

### ISSUE THREAD

**Issue by Bekbolatov** [CachetHQ/Cachet#1918]
We are sending some metrics every minute and we used to get smooth graphs.
After upgrade, we are seeing that there is another metric parameter that apparently specifies how often this metric will accumulate incoming metric values. It is ideal for something like counting the "cup of coffee", but if we want to see a "level" value we can't have that anymore.

We specified it as a "Average" when aggregating and we lowered the number of minutes to the minimum of 1 min.

In graphs, it appears that it is using "calculated_value" field rather than the actual data point.

What is a workaround?

**Comment by jbrooksuk** [comment]
Sorry for the delay @Bekbolatov. On your metric, you should set the `threshold` setting to be `1`.

The idea behind this Threshold feature is that when you're submitting a lot of metrics, we want to save space in the database, where the value is the same.

I'm going to close this issue, but feel free to keep the channel open if you have any further questions.

**Comment by Bekbolatov** [comment]
Thanks for the reply. Before I posted here, I actually tried the value of 1 for that parameter, as you explained, but it is not doing two things correctly:

1) when the data points and cut-off times don't exactly align - it lumps two data points in one period and none in the next - this pattern repeats. 

2) instead of averaging, it adds. For instance, if it is metrics about latency - in milliseconds - then the sum doesn't make any sense. (FYI, I did set the "avg vs sum" parameter to "avg" - in case, you want to suggest that next)

**Comment by Bekbolatov** [comment]
Alright, no worries guys, you don't have to fix that bug - we decided to move to a different tool for metrics and their graphs/displays. We will still use your product for components (status/notifications/history).
Thanks!

**Comment by jbrooksuk** [comment]
Sorry for the delay in getting back to you @Bekbolatov, it's been the weekend and I've been making a hole in the roof (loft hatch installation).

> Alright, no worries guys, you don't have to fix that bug

Since this is a bug, it will need fixing regardless :)

**Comment by lnxslck** [comment]
@Bekbolatov That new metric tool you are working with, do you have it integrated into Cachet?
