### ISSUE TITLE
Show exact incident time on status page (on hover/click)

### ISSUE THREAD

**Issue by Ehesp** [cachethq/Cachet#192]
If a service goes down and effects a 3rd party, they might need to do a report if things effected their services with specific outage times.

**Comment by jbrooksuk** [comment]
We could also add [timeago](http://timeago.yarp.com/) so that the readable times are updated in realtime.

**Comment by GrahamCampbell** [comment]
Yeh, I use that library on bootstrap cms. I also have an html macro setup that I use with it.

**Comment by jbrooksuk** [comment]
That'd be good to add!

**Comment by GrahamCampbell** [comment]
```php
        HTML::macro('ago', function (Carbon $carbon, $id = null) {
            if ($id) {
                return '<abbr id="'.$id.'" class="timeago" title="'
                    .$carbon->toISO8601String().'">'.$carbon->toDateTimeString().'</abbr>';
            } else {
                return '<abbr class="timeago" title="'
                    .$carbon->toISO8601String().'">'.$carbon->toDateTimeString().'</abbr>';
            }
        });
    }
```

**Comment by jbrooksuk** [comment]
I'll create a `macros.php` and whack it in there.

**Comment by GrahamCampbell** [comment]
NB, I actually did this in a service provider, and didn't use the facade.

**Comment by GrahamCampbell** [comment]
Real code: https://github.com/GrahamCampbell/Laravel-Core/blob/master/src/CoreServiceProvider.php#L63.

**Comment by jbrooksuk** [comment]
@GrahamCampbell we should implement that into Cachet - it'd be a nice little "polish" feature IMHO.
