### ISSUE TITLE
Multiple pages on 1 server and access control

### ISSUE THREAD

**Issue by ohh-sure** [CachetHQ/Cachet#1921]
Hi Guys,

I currently have an AWS EC2 instance (t2.micro) on their free-their running Ubuntu 14.04. The site works very well. (Free-tier is only free for the first year for an instance.)

I used this guide to setup my server with the most current v2.3 of Cachet, which by the way was an awesome article - https://chrisreinking.com/installing-cachet-on-ubuntu-14-04/

Looking for some insight into how I could setup multiple sites with different Cachet pages for different clients. Would like to have basicauth enabled thru htaccess as well. Is any type of access control like this available thru the app for multiple pages with login/account features?

See, here's the situation... We have a shared environment by multiple clients, and also have dedicated environments for different clients. I would not want customer names publically available on the web on a page OR in the URL, which is why I'd like to restrict the pages with at least basicauth and name the URL discretely - For example:
http://status.companyname.com/shared
http://status.companyname.com/dedicated1
http://status.companyname.com/dedicated2
http://status.companyname.com/dedicated3

I'd like to keep the Cachet web server limited to one Linux server to avoid extra costs for more AWS instances. Otherwise I could have a separate AWS instance for each page, but that gets very expensive overtime.

We have dozens of clients, and was wondering if there was any documentation that could help or third-party plugins that might be available. I did find this "issue" (https://github.com/CachetHQ/Cachet/issues/236) created in GitHub, therefore I wanted to see if anything was available in v2.3.

Thanks for your help and for such an awesome tool!

**Comment by jbrooksuk** [comment]
This isn't supported by Cachet natively yet, I'm afraid.

One way that you could handle this is to write a custom wrapper using the [Cachet API](https://docs.cachethq.io) and have the sub-directories pull in the components you're interested in. The way I'd do this is to group the shared components into a **Shared Components** group, and always pull them in for every client.
