### ISSUE TITLE
Metric points grouping

### ISSUE THREAD

**Issue by jbrooksuk** [CachetHQ/Cachet#1922]
Split from #1918 

1) when the data points and cut-off times don't exactly align - it lumps two data points in one period and none in the next - this pattern repeats.

2) instead of averaging, it adds. For instance, if it is metrics about latency - in milliseconds - then the sum doesn't make any sense. (FYI, I did set the "avg vs sum" parameter to "avg" - in case, you want to suggest that next.

**Comment by czerwonkabartosz** [comment]
When it will be solved? ;)

**Comment by jbrooksuk** [comment]
@GrahamCampbell any idea how we can fix these issues?

**Comment by GrahamCampbell** [comment]
I'll think about this. :D

**Comment by ConnorVG** [comment]
You could attach aggregates to metrics? Just an idea.
