### ISSUE TITLE
Unable to disable Dashboard link in footer

### ISSUE THREAD

**Issue by jamesduffy** [CachetHQ/Cachet#1925]
Before submitting your issue, please make sure that you've checked all of the checkboxes below.

- [x] You're running the [latest release](https://github.com/CachetHQ/Cachet/releases/latest) version of Cachet.
- [x] Ensure that you're running at least PHP 5.5.9, you can check this by running `php -v`
- [x] You've ran `rm -rf bootstrap/cache/*` from the root of your Cachet installation.

To help us better understand your issue, please answer the following — cheers!

### Your setup

- *What version of Cachet?*
2.3.1
- *What database driver? MySQL? Postgres? SQLite?*
MySQL
- *What version of PHP?*
```
PHP 7.0.6-12+donate.sury.org~trusty+4 (cli) ( NTS )
Copyright (c) 1997-2016 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2016 Zend Technologies
    with Zend OPcache v7.0.8-2+deb.sury.org~trusty+1, Copyright (c) 1999-2016, by Zend Technologies
```

### Expected behaviour

When unchecking "Show dashboard button in the footer?" in theme settings it should appear unchecked and hide the link in the footer.

### Actual behaviour

When looking in the DB the `dashboard_login_link` value is `0`, but in the form it stays checked. Also on the status page the Dashboard link is still there.

### Steps to reproduce

Login and go to settings/theme. Uncheck "Show dashboard button in footer?". Click save. You get a message saying that changes were saved. Check box should be unchecked if false in settings and Dashboard link in footer should not appear.

**Comment by GrahamCampbell** [comment]
James, this is is the reason why I wasn't deleting old settings on purpose before.

**Comment by jbrooksuk** [comment]
What's the solution to this then? 😕

**Comment by GrahamCampbell** [comment]
I'll try to look at this today.

**Comment by GrahamCampbell** [comment]
@jbrooksuk This was the commit that broke shit: https://github.com/CachetHQ/Cachet/commit/de232ab2b51caa22bf3f81c16a50993d8a9ae2ba.

**Comment by GrahamCampbell** [comment]
Errr, wait, or was it...

**Comment by GrahamCampbell** [comment]
Err, WTF... James... Go to the demo and UNTICK "Display graphs on status page?". Then refresh 3 times and watch it go back and forward.
