### ISSUE TITLE
subscribers receive subscription confirmation email but no followup email when component status changes

### ISSUE THREAD

**Issue by fdhex** [CachetHQ/Cachet#1927]
### Your setup

- *What version of Cachet?* 2.3
- *What database driver? MySQL? Postgres? SQLite?* MySQL
- *What version of PHP?* 7

### Expected behaviour

In sync mode, I receive an email when I subscribe to notifications on the dashboard to complete my verification. I see a 'Verified' when clicking on the link, so I assume emailing is working as expected.

Later, I try to update the status of a component (from operational to major outage), I expect an email telling me that something is wrong.

### Actual behaviour

I receive no email.

Emails need to be sent from a specific sender so that my smtp server accepts them, this works well for the verification system, but maybe not from the notification system? Could this be checked?

I am not sure if there are any logs of failed emails or anything where I should look. Could you please help me understand what can be happening there?

**Comment by fdhex** [comment]
Ah, it seems to work for Incidents, so I guess my problem is that there seems to be no possibility to send emails on component status updates rather than only on specified incidents. Is there an option to activate that maybe?

**Comment by GrahamCampbell** [comment]
Please provide the full version information. Say, Cachet 2.3.1, PHP 7.0.8?

**Comment by fdhex** [comment]
It's currently 2.3.0 and PHP 7.0.3, but please see my second message, I guess it's expected behaviour as it is now in fact?

**Comment by GrahamCampbell** [comment]
Is this working on Cachet 2.3.1 with PHP 7.0.8 please?

**Comment by fdhex** [comment]
I'll do a merge and retry. Is the behaviour I described above intended or not? If yes, then there's no bug to correct.

**Comment by fdhex** [comment]
Same result in 2.3.1.

**Comment by Srthk** [comment]
+1

What is the behaviour for mailing subscribers? Do they get notified on both component status/incident corresponding to the components they are subscribed to or only for incidents?

And the subscribers only get notified when an incident is created, but not when it is fixed. Is there a way to notify subscribers in both cases?

**Comment by jbrooksuk** [comment]
Ping @joecohens

**Comment by jbrooksuk** [comment]
@joecohens shouldn't we be emailing on **any** change to a Component? I can't see anything that prevents a change just to the status from emailing subscribers?

**Comment by jbrooksuk** [comment]
Wait! Are you changing the Components status from the dashboard index:

![image](https://cloud.githubusercontent.com/assets/246103/16694429/204c71ae-4532-11e6-89a0-3c4b7d66a168.png)

If so, this is the issue.

**Comment by jbrooksuk** [comment]
(Which is a bug).

**Comment by jbrooksuk** [comment]
This bug will be fixed in the v2.3.3 release, which should land over the weekend (if not beforehand).
