### ISSUE TITLE
Scheduled Maintenance - Notify subscribers

### ISSUE THREAD

**Issue by karthik-22feb** [CachetHQ/Cachet#1928]
Hi Team,

I am using the  2.3.0-RC4 version of CACHE. The dashboard has an option to 'Notify subscribers' when adding an Scheduled Maintenance

Is it possible to have the 'Notify subscribers' feature when editing an Scheduled Maintenance

Let me know if you have an custom code to enable this feature?

Thanks,
Karthik

**Comment by jbrooksuk** [comment]
This is something that we'll do in v3.0.0 :)
