### ISSUE TITLE
Upgrade to v2.3.0

### ISSUE THREAD

**Issue by philshil** [CachetHQ/Cachet#1931]
Hello,
i have followed the upgrade guide and checked out tag V2.3.0 and run the composer command but was met by an error.
it:/srv/www/Cachet # composer install --no-dev -o
Loading composer repositories with package information
Installing dependencies from lock file
Nothing to install or update
Generating optimized autoload files
> Illuminate\Foundation\ComposerScripts::postInstall
> php artisan optimize --force
PHP Fatal error:  Class 'CachetHQ\Cachet\Foundation\Providers\GitHubServiceProvider' not found in /srv/www/Cachet/vendor/laravel/framework/src/Illuminate/Foundation/ProviderRepository.php on line 146

                                                                                
  [Symfony\Component\Debug\Exception\FatalErrorException]                       
  Class 'CachetHQ\Cachet\Foundation\Providers\GitHubServiceProvider' not found  
                                                                                

Script php artisan optimize --force handling the post-install-cmd event returned with error code 255

**Comment by GrahamCampbell** [comment]
Delete all files in https://github.com/CachetHQ/Cachet/tree/2.3/bootstrap/cache other than the ignore file, and then run `php artisan optimize --force` and `php artisan app:update`.

**Comment by philshil** [comment]
My bootstrap/cache folder for some reason doesn't exist 
i had run the rm -rf /bootstrap/cachet/* before when i first hit the error now i am hit with this below.

it:/srv/www/Cachet # composer install --no-dev -o
Loading composer repositories with package information
Installing dependencies from lock file
Nothing to install or update
Generating optimized autoload files
> Illuminate\Foundation\ComposerScripts::postInstall
> php artisan optimize --force

                                                                                                                     
  [ErrorException]                                                                                                   
  file_put_contents(/srv/www/Cachet/bootstrap/cache/services.php): failed to open stream: No such file or directory  
                                                                                                                     

Script php artisan optimize --force handling the post-install-cmd event returned with error code 1

**Comment by GrahamCampbell** [comment]
You must not delete the cache folder. That will break everything. ONLY delete the files inside it.

**Comment by philshil** [comment]
Hi @GrahamCampbell 
Im guessing the only way to fix this is a fresh install?

**Comment by GrahamCampbell** [comment]
Just make the cache folder again.

**Comment by philshil** [comment]
Okay. I have done that, Cleared out the cache folder and run the php artisan optimize --force and still gettting the github error

it:/srv/www/Cachet # php artisan optimize --force
PHP Fatal error:  Class 'CachetHQ\Cachet\Foundation\Providers\GitHubServiceProvider' not found in /srv/www/Cachet/vendor/laravel/framework/src/Illuminate/Foundation/ProviderRepository.php on line 146

                                                                                
  [Symfony\Component\Debug\Exception\FatalErrorException]                       
  Class 'CachetHQ\Cachet\Foundation\Providers\GitHubServiceProvider' not found

**Comment by TheLastProject** [comment]
Did you run it as root? You need to run the artisan commands as the correct user. If you already messed up (sounds like you did), a recursive chown should work.

On 29 June 2016 17:10:54 CEST, philshil <notifications@github.com> wrote:
>Okay. I have done that, Cleared out the cache folder and run the php
>artisan optimize --force and still gettting the github error
>
>it:/srv/www/Cachet # php artisan optimize --force
>PHP Fatal error:  Class
>'CachetHQ\Cachet\Foundation\Providers\GitHubServiceProvider' not found
>in
>/srv/www/Cachet/vendor/laravel/framework/src/Illuminate/Foundation/ProviderRepository.php
>on line 146
>
>                                                                       
>[Symfony\Component\Debug\Exception\FatalErrorException]                
>      
>Class 'CachetHQ\Cachet\Foundation\Providers\GitHubServiceProvider' not
>found  
>                                                                       
>
>---
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/CachetHQ/Cachet/issues/1931#issuecomment-229387270

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by philshil** [comment]
Hello,
I've always run as root. run chown and chmod, still no luck.

**Comment by TheLastProject** [comment]
I did say a RECURSIVE chown, obviously to whatever user it should be. It's not clear from the error, but this exact one is caused by wrong permissions because you ran commands as root that shouldn't have been ran as root.

Also, running things as root is a horrible idea in almost every single case, I'd urge you to look up why (the Internet is filled with explanations) before this comes back to bite you much, much worse. Running as root should only be done if you know exactly why and there is no other way.

On 29 June 2016 17:31:06 CEST, philshil <notifications@github.com> wrote:
>Hello,
>I've always run as root. run chown and chmod, still no luck.
>
>---
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/CachetHQ/Cachet/issues/1931#issuecomment-229393846

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by philshil** [comment]
I did do recursive. we only use it internally anyway so im happy to rebuild it!

**Comment by GrahamCampbell** [comment]
If you're still having trouble later, you can get in touch with us at support@alt-three.com. We offer a paid install service.

**Comment by philshil** [comment]
@GrahamCampbell thanks, i have managed to fix it now!
