### ISSUE TITLE
Can't change site language

### ISSUE THREAD

**Issue by anlutro** [CachetHQ/Cachet#1932]
Logging into the dashboard and going into settings → localization, if I try to change the language from English to something else and hit "Save", when the page reloads the site language is still English.

Using v2.3.1

**Comment by GrahamCampbell** [comment]
The dashboard language ignores that setting.

**Comment by GrahamCampbell** [comment]
It will use the language your browser sends. This setting on affects non-dashboard pages.

**Comment by anlutro** [comment]
Maybe I wasn't clear enough. When I hit the "Save" button, the dropdown on the settings page for the site language reverts to English regardless of what I try to change it to.

**Comment by GrahamCampbell** [comment]
Does your web server have full write access to /bootstrap/cachet`?

**Comment by anlutro** [comment]
I see - no, it did not. Why not store these settings in the database? Also, getting an actual error message for missing write capabilities would be nice.

**Comment by GrahamCampbell** [comment]
We do stores these in the database. We cache them in that folder though.

**Comment by jbrooksuk** [comment]
Does this solve your issue @anlutro?

**Comment by anlutro** [comment]
Yeah.
