### ISSUE TITLE
Incident Timeline and Current Incidents

### ISSUE THREAD

**Issue by fdhex** [CachetHQ/Cachet#1933]
Before submitting your issue, please make sure that you've checked all of the checkboxes below.

- [x ] You're running the [latest release](https://github.com/CachetHQ/Cachet/releases/latest) version of Cachet.
- [x ] Ensure that you're running at least PHP 5.5.9, you can check this by running `php -v`
- [x ] You've ran `rm -rf bootstrap/cache/*` from the root of your Cachet installation.

To help us better understand your issue, please answer the following — cheers!

### Your setup

- *What version of Cachet?*
2.3.1
- *What database driver? MySQL? Postgres? SQLite?*
MySQL
- *What version of PHP?*
7.0.8

### Expected behaviour

New, non-resolved incident should be at the top of the page, or at the very least appear in a "Current Incident" part of the timeline. 

### Actual behaviour

New incident, not in a Fixed state, appears in the timeline under 'Past Incidents'

### Steps to reproduce

Create a normal incident with the present date.

I think it would be a good idea to at least offer the option to have the behaviour I describe in the expected behaviour, currently users have to scroll down below all the components and graphs before they can actually check incidents. Incidents are often important admin messages and should be highlighted, as long as they are not resolved. Please provide some feedback on your vision here or what you think of that proposal?

**Comment by jbrooksuk** [comment]
This functionality is changing in v3.0.0, where you'll add updates to a given incident. But thank you for your suggestion!

**Comment by fdhex** [comment]
@jbrooksuk Great, thanks! I'll be looking forward to this new version.

I know it's an open source project, but just to see if it's worth trying to implement this feature myself given the time it will take me, do you have a (even very rough) ETA for v3.0.0?

**Comment by jbrooksuk** [comment]
It'll be later in the year as it's a HUGE release. https://github.com/CachetHQ/Cachet/issues?q=is%3Aopen+is%3Aissue+milestone%3AV3.0.0
