### ISSUE TITLE
API endpoint to get System Status

### ISSUE THREAD

**Issue by odannyc** [CachetHQ/Cachet#1936]
Can we get an endpoint that just gets the entire system status message.
For example, if all systems are operational the message the endpoint should return

```json
{
  "message": "All systems are operational"
}
```

**Comment by jbrooksuk** [comment]
Yeah, I don't see why not :+1:

**Comment by adammbalogh** [comment]
Nice idea!

Could I create a PR for this feature?

**Comment by jbrooksuk** [comment]
I'd love for you to! Could you base it on the 2.3 branch please? That'll see it gets into the v2.4.0 release.

**Comment by adammbalogh** [comment]
#1943

**Comment by jbrooksuk** [comment]
Closed by https://github.com/CachetHQ/Cachet/pull/1968

**Comment by Daniel15** [comment]
Is there an ETA for getting this into a released version of Cachet?
