### ISSUE TITLE
Incident and Scheduled Maintenance Component Selection

### ISSUE THREAD

**Issue by cirkut** [CachetHQ/Cachet#1937]
When you're reporting an Incident, you're able to select a single component that may be affected. Sometimes incidents affect multiple services, so I would imagine having the ability to select multiple services that are affected would be a welcomed feature.

Likewise when you're scheduling maintenance, there's no component selection at all. Generally for scheduled maintenance, you know what components/services are going to be affected. I think it would be good to be able to select component(s) that will be undergoing scheduled maintenance.

**Comment by jbrooksuk** [comment]
Thanks for your report :)

This is something that our `v3.0.0` release will be taking care of, we already have an issue for this https://github.com/CachetHQ/Cachet/issues/1176
