### ISSUE TITLE
Table 'cachet.metrics' doesn't exist

### ISSUE THREAD

**Issue by SijmenHuizenga** [CachetHQ/Cachet#1938]
Hello Cachet People! I just started using Cachet, and i am loving it! There is just a little problem...

### Setup
I am running the following configuration:
-  Cachet version 2.3.1 (823fe6e9e22cc58acff1e6c4075cc2f48044b4d6)
-  PHP version 5.6.22
-  MySQL (database name = `cachet`)
- in my '.env' file there is a database prefix specified (`DB_PREFIX=example_`)

### Issue
I am trying to add a Metric and showing in on the homepage. But when loading the homepage, i get the following error message in my chrome console:
`http://status.example.com/metrics/1?filter=last_hour Failed to load resource: the server responded with a status of 500 (Internal Server Error)`

When inspecting the laravel log file, there is the flowing errors:
`production.ERROR: exception 'PDOException' with message 'SQLSTATE[42S02]: Base table or view not found: 1146 Table 'cachet.metrics' doesn't exist' in /var/www/status.example.com/vendor/laravel/framework/src/Illuminat$`
`Next exception 'Illuminate\Database\QueryException' with message 'SQLSTATE[42S02]: Base table or view not found: 1146 Table 'cachet.metrics' doesn't exist (SQL: SELECT AVG(mp.`value` * mp.`counter`) AS `value` FROM metrics m INNER JOIN $`

The full stack-trace can be found on [pastebin](http://pastebin.com/raw/Ee2K81DP)

I am suspecting this issue has something to do with my database table prefix. The stacktrace sais Cachet cannot find table `cachet.metrics`. This is correct because the database table name is `example_metrics`. So i think Cachet somehow forgot to apply the table prefix.
Or maybe it is something completely different. ;)

Thanks in advance!

**Comment by GrahamCampbell** [comment]
Try without using a table prefix. It shouldn't be needed?

**Comment by SijmenHuizenga** [comment]
The plan was to run multiple cachet installations on 1 database using prefixes. But i can create multiple databases if necessary... I was just hoping to use prefixes.

**Comment by jbrooksuk** [comment]
Hey! This usage is actually unsupported by Cachet, a bug if you will. I'll fix this up in a point release.

**Comment by SijmenHuizenga** [comment]
Oke. Thanks for your fast responses!
