### ISSUE TITLE
Markdown Issues

### ISSUE THREAD

**Issue by jzielke** [CachetHQ/Cachet#1951]
Before submitting your issue, please make sure that you've checked all of the checkboxes below.

- [X] You're running the [latest release](https://github.com/CachetHQ/Cachet/releases/latest) version of Cachet.
- [X] Ensure that you're running at least PHP 5.5.9, you can check this by running `php -v`
- [X] You've ran `rm -rf bootstrap/cache/*` from the root of your Cachet installation.

To help us better understand your issue, please answer the following — cheers!

### Your setup

- *What version of Cachet?* v2.3.3
- *What database driver? MySQL? Postgres? SQLite?* MySQL
- *What version of PHP?* 5.5.9

### Expected behaviour

*Please describe what you're expecting to see happen.*
Markdown to display correctly for scheduled maintenance in regards to line breaks (double space) empty lines and other tags.  New lines work if there is text before the double space.  Strikethrough should work also. I have not checked all the markdown tags.

Not sure if this is a limitation of the markdown that is implemented in the system.

### Actual behaviour

*Please describe what you're actually seeing happen.*
Markdown does not display correctly for scheduled maintenance description with blank lines or some of the tags.  Does work partially once the scheduled maintenance becomes an incident. 

### Steps to reproduce

*If your issue requires any specific steps to reproduce, please outline them here.*
Create a Scheduled Maintenance

Example
```
**This is Bold**  
Line 1  
Line 2    
  
Line 4  
Line 5  
~~Scratch This~~
```

![scheduled](https://cloud.githubusercontent.com/assets/3512553/16714456/01614dda-4692-11e6-9918-884d2ff328ee.png)
![incident](https://cloud.githubusercontent.com/assets/3512553/16714458/06679136-4692-11e6-8923-314252704d2c.png)

**Comment by jbrooksuk** [comment]
Ping @GrahamCampbell

**Comment by GrahamCampbell** [comment]
Strikethrough is not included in the commonmark spec.

**Comment by jbrooksuk** [comment]
What about the double line break?

**Comment by GrahamCampbell** [comment]
http://spec.commonmark.org/0.25/

**Comment by GrahamCampbell** [comment]
I don't see any bug? Just looks like the screenshot render was for different input.

**Comment by jzielke** [comment]
Schedule Maintenance displays the markdown differently than the Incident displays with the same markdown. 

Since commonmark does not support the strikethrough that is fine, but it should display a blank line for a line that has two spaces like the incident display does.

Paste this is as a scheduled task and also as an incident. There is a difference in the new lines for a blank line which has 2 spaces only.

```
Line 1  
Line 2    
  
Line 4  
Line 5
  
Tincidunt cras risus natoque augue? Lacus. Parturient in urna auctor! Tincidunt vut odio porta ultrices duis pellentesque pellentesque penatibus amet placerat montes turpis amet, placerat elementum et turpis?  
  
Mus ut, pellentesque. Urna arcu turpis, cursus a scelerisque. Rhoncus elit? Nec, cum parturient! Ut, in adipiscing vel ut. Lundium in tempor aliquam, vel magna urna. Augue risus, porta, elementum magna sagittis, nunc dignissim ultrices non pulvinar vel ac. Habitasse porttitor, arcu platea integer porttitor tempor ac, aliquam?
```
![incident](https://cloud.githubusercontent.com/assets/3512553/16714914/44a1371a-469f-11e6-823c-31b515bd71a8.png)

**Comment by GrahamCampbell** [comment]
Cachet doesn't control the behaviour here.

**Comment by DigiDaz** [comment]
Should links work, I'm trying to provide a clickable link to an external page but this does not seem to work?

**Comment by jbrooksuk** [comment]
Links work, what are you using?

**Comment by DigiDaz** [comment]
Thanks for the very quick reply, exactly this:

Due to this being a BT Core Routing problem we will not post any further updates. Please see the BT status page for any updates:   
[https://btbusiness.custhelp.com/app/service_status] (https://btbusiness.custhelp.com/app/service_status)

See https://status.directvoip.co.uk/

**Comment by DigiDaz** [comment]
Ah, it used the markdown...

```
[https://btbusiness.custhelp.com/app/service_status] (https://btbusiness.custhelp.com/app/service_status)
```

**Comment by jbrooksuk** [comment]
Your using Markdown links incorrectly there. You can't have a space after the closing `]`.

```
[https://btbusiness.custhelp.com/app/service_status](https://btbusiness.custhelp.com/app/service_status)
```

**Comment by jbrooksuk** [comment]
And actually, if the anchor text is the link itself, you can just type the link out and it should auto make itself into a link :)

**Comment by DigiDaz** [comment]
You're the man, thanks! The [link] definitely does not work but removing the space does! :)

https://status.directvoip.co.uk

**Comment by jbrooksuk** [comment]
By placing just the link, I mean you can literally just type the link with no formatting:

```
https://cachethq.io
```

Will be converted into 

> https://cachethq.io

**Comment by jimmybrancaccio** [comment]
@GrahamCampbell & @jbrooksuk I understand Cachet doesn't control the Markdown rendering here. I assume some 3rd party Markdown rendering library is being used? What needs to be done to correct this as this is not correct. Should the rendering library be updated or replaced? Newlines should be properly rendered/displayed.

> When you do want to insert a `<br />` break tag using Markdown, you end a line with two or more spaces, then type return.

[Source](https://daringfireball.net/projects/markdown/syntax#p).
