### ISSUE TITLE
Cachet RSS and Atom not working Ubuntu 16.04

### ISSUE THREAD

**Issue by olkitu** [CachetHQ/Cachet#1973]
I have Ubuntu 16.04, PHP7.0 and Cachet installed to Apache2 webserver. All working well but RSS and Atom not working.

When try open Atom or RSS it shows that error:

`This page contains the following errors:

error on line 39 at column 58: Entity 'auml' not defined
Below is a rendering of the page up to the first error.
`

**Comment by GrahamCampbell** [comment]
What version of cachet please? I'm pretty sure this is fixed in the latest release.

**Comment by olkitu** [comment]
I have latest Cache, 2.3.4-dev.

**Comment by GrahamCampbell** [comment]
Did you run `composer install --no-dev -o` after upgrading?

**Comment by olkitu** [comment]
Yes, i run that command.

**Comment by GrahamCampbell** [comment]
Ping @jbrooksuk.

**Comment by jbrooksuk** [comment]
@olkitu are you able to share the URL to your status page? If it's private, would you mind emailing us at support@alt-three.com please?

**Comment by olkitu** [comment]
@jbrooksuk sended URL to email.

**Comment by jbrooksuk** [comment]
Thanks @olkitu! It looks like the feed package we use doesn't put `title` tag content into `CDATA` blocks.
