### ISSUE TITLE
Error 500 (Components and Dashboard)

### ISSUE THREAD

**Issue by dtpest** [CachetHQ/Cachet#1974]
Before submitting your issue, please make sure that you've checked the checkboxes below.

- [ Docker Container -> latest ] I am running the [latest release](https://github.com/CachetHQ/Cachet/releases/latest) version of Cachet.
- [ 5.6.20-0+deb8u1 ] I am running at least PHP 5.5.9. *You can check this by running `php -v`.*
- [ yes ] I have ran `rm -rf bootstrap/cache/*`.

### Expected behaviour

domain.com/dashboard responses an HTTP-Error 500.
After login in "domain.com/auth/login" the Dashboard is reachable.

Also adding a new "Component" responses an 500 Error, but it adds the Component anyways.

Docker Container:
docker run --name cachet -p 9000:9000 --volume=/var/www -e DB_DRIVER=pgsql -e DB_HOST=xxxx -e DB_DATABASE=xxxx -e DB_USERNAME=xxxx -e DB_PASSWORD=xxxx -d cachethq/docker:latest

docker run -d --name nginx --volume=/etc/nginx/docker_conf.d/:/etc/nginx/conf.d/ -p 80:80 --volumes-from=cachet --link cachet nginx:stable-alpine

**Comment by jbrooksuk** [comment]
Could you post this issue in the [Docker](https://github.com/CachetHQ/Docker) issues please?

**Comment by dtpest** [comment]
done
