### ISSUE TITLE
HTTP 500 after configurating e-mail

### ISSUE THREAD

**Issue by TLingC** [CachetHQ/Cachet#1980]
Before submitting your issue, please make sure that you've checked the checkboxes below.

- [ ] I am running the [2.3.3](https://github.com/CachetHQ/Cachet/releases/latest) version of Cachet.
- [x] I am running at least PHP 5.5.9. *You can check this by running `php -v`.*
- [x] I have ran `rm -rf bootstrap/cache/*`.

### Expected behaviour

-

### Actual behaviour

It return with HTTP ERROR 500
With an error:
> [Sat Jul 16 19:30:13.136689 2016] [:error] [pid 8664:tid 1600] [client 183.60.175.133:54338] PHP Fatal error:  Allowed memory size of 268435456 bytes exhausted (tried to allocate 24 bytes) in E:\\xampp\\vhosts\\mywebsite\\vendor\\laravel\\framework\\src\\Illuminate\\Database\\Grammar.php on line 153
[Sat Jul 16 19:31:40.296315 2016] [:error] [pid 9656:tid 1640] [client 183.60.175.133:50641] PHP Fatal error:  Allowed memory size of 268435456 bytes exhausted (tried to allocate 32 bytes) in E:\\xampp\\vhosts\\mywebsite\\vendor\\laravel\\framework\\src\\Illuminate\\Database\\Grammar.php on line 70
[Sat Jul 16 19:31:40.311821 2016] [:error] [pid 9656:tid 1648] [client 183.60.175.133:25650] PHP Fatal error:  Allowed memory size of 268435456 bytes exhausted (tried to allocate 24 bytes) in E:\\xampp\\vhosts\\mywebsite\\vendor\\laravel\\framework\\src\\Illuminate\\Database\\Grammar.php on line 153

(I set memory_limit to 256M and then 512M later but still have this error)

Permissions has already checked and it's no problem.
### Steps to reproduce

Following the document of Cachet
1. Configurate the .env file about e-mail
2. Run `php artisan config:cache`
3. Delete all files in "bootstrap/cache" folder

**Comment by jbrooksuk** [comment]
Have you added subscribers already?
