### ISSUE TITLE
Functionality of Cachet

### ISSUE THREAD

**Issue by thebbqiscancelled** [CachetHQ/Cachet#1984]
Hi there,

I have a few questions about the functionality of Cachet..

1. Is there a way to approve subscribers? (i.e. third party plug-in, etc.)

2. Un-checking the "Allow people to signup to email notifications?" checkbox disables ALL email alerts. Can this be changed so that email alerts are still sent out for EXISTING subscribers but NEW email subscribers cannot sign-up?

3. Is there a way to force basic authentication of the Cachet page so before the page is displayed, the end-user must enter credentials? (i.e. .htaccess, basicAuth, etc.)

Thank you in advance for your help,

-Bryan

**Comment by jbrooksuk** [comment]
Hi there,

Thanks for getting in touch! I'll answer your questions:

1. Not exactly, but you can go into the Dashboard and remove subscribers. The idea is that Cachet is used for transparency so *anybody* can subscribe.
2. This is correct and actually the wrong behaviour. We should split this into two options: alert subscribers of updates, enable subscriber signups.
3. You can do this through your web server, Nginx and Apache both support this.

Cheers!
