### ISSUE TITLE
Translated days are wrong in Dutch

### ISSUE THREAD

**Issue by TheLastProject** [CachetHQ/Cachet#1985]
Before submitting your issue, please make sure that you've checked the checkboxes below.

- [X] I am running the [latest release](https://github.com/CachetHQ/Cachet/releases/latest) version of Cachet.
- [X] I am running at least PHP 5.5.9. *You can check this by running `php -v`.*
- [ ] I have ran `rm -rf bootstrap/cache/*`.

### Expected behaviour

When using the Dutch translations, days are described as, for example, `maandag 18 juli 2016`.

### Actual behaviour

Days are described as `maandag 18th juli 2016`, thus containing an unnecessary and gramatically incorrect `th` suffix after the day number.

### Steps to reproduce

1. Switch Cachet to Dutch
2. Look at the public-facing page

EDIT: Screenshot for clarity
![incidentlist](https://cloud.githubusercontent.com/assets/1885159/16923661/a0c3e2f4-4d1b-11e6-922c-0668fb2d8267.png)

**Comment by jbrooksuk** [comment]
Would you be willing to submit fixes to https://translate.cachethq.io?

**Comment by TheLastProject** [comment]
I would be willing too, but I am pretty sure it isn't an issue that can be fixed with translation files. After all, there isn't even a translation in there for `maandag` (Dutch for `monday`). My personal bet is that it is related to the DateFactory as it is called on https://github.com/CachetHQ/Cachet/blob/2.3/app/Http/Controllers/StatusPageController.php#L92-L99.

**Comment by jbrooksuk** [comment]
Ah, in which case the issue is https://github.com/jenssegers/date.

Could you report the issue there please :)

**Comment by TheLastProject** [comment]
Actually, it is a minor Cachet configuration issue it seems.

By default, on dashboard/settings/localization, the date format is set to `l jS F Y` and the time format is set to `l jS F Y H:i:s`. However, in many languages, including Dutch, this is simply not correct. I (apparently incorrectly) expected Cachet to use the correct date and time format for Dutch (respectively `I j F Y` and `I j F Y H:i:s`) when switching language.

**Comment by jbrooksuk** [comment]
Ah-ha! The default is English, so it needs to be changed by the admin :)

**Comment by TheLastProject** [comment]
Indeed. I still consider it a minor issue that the way dates are written isn't implicit in the language. One of the features Cachet provides is a multi-lingual status page, which is simply impossible to truly support when the date and time format isn't set automatically based on language, because some languages will display the date incorrectly then. Seeing as I am not planning on running Cachet in a multi-lingual state that doesn't really matter, but it is important to consider the implications of the date and time format being independent from the site language.

**Comment by jbrooksuk** [comment]
Whilst true, without supporters from all over the world, it'd likely be impossible to get all of the settings right for multi-lingual installs.

Ping @CachetHQ/owners any ideas if we could make this easier? Maybe include the date formats in a translation string for people to set as part of the language?

**Comment by joecohens** [comment]
Yeah that sounds like a good idea. On the lang/cachet.php we can add a `"date" => "format"`

**Comment by jbrooksuk** [comment]
`date` and `time` would be good.
