### ISSUE TITLE
Disable "Latest News"

### ISSUE THREAD

**Issue by dtpest** [CachetHQ/Cachet#1988]
Before submitting your issue, please make sure that you've checked the checkboxes below.

- [ 3.0.0-dev ] I am running the [latest release](https://github.com/CachetHQ/Cachet/releases/latest) version of Cachet.
- [ 5.6 ] I am running at least PHP 5.5.9. *You can check this by running `php -v`.*
- [ yes ] I have ran `rm -rf bootstrap/cache/*`.

It should be possible to disable the "Latest News" Section on the Dashboard.
It takes about 600 ms from 800 ms to load this Section.

Best,
Peter

**Comment by jbrooksuk** [comment]
@dtpest the data is currently cached for 12 hours, so the time it takes to load the dashboard shouldn't take long, only when it needs to re-fetch the data.

Also, you probably don't want to be running v3.0.0-dev as this is currently **very** unstable and likely broken. I'd suggest downgrading to [v2.3.6](https://github.com/CachetHQ/Cachet/releases/tag/v2.3.6) for stability or v2.4.0-dev if you fancy living life on the edge :)

**Comment by GrahamCampbell** [comment]
It's not very likely to be broken, it most definitely is completely broken. :trollface:
