### ISSUE TITLE
Skip subscriber verification

### ISSUE THREAD

**Issue by karthik-22feb** [CachetHQ/Cachet#1990]
Hi Team,

I am using the CACHE ( 2.3.0-RC4) version. & am trying to skip the CONFIRM SUBSCRIPTION when an user subscribes to the system 

I would really appreciate if you can provide a solution to my issue?

Let me know about your thoughts.

Thanks,
Karthik

**Comment by jbrooksuk** [comment]
We don't have an option for confirming subscriptions, but that would be something we could easily add.

Ping @joecohens.

Also, you're running an outdated version of Cachet, the latest version is v2.3.6 :)

**Comment by karthik-22feb** [comment]
Hi jbrooksuk,

The Confirm Subscription feature is already available in the system. I receive an Confirm Subscription email when i subscribe to the updates .

I wish to turn off this feature. I want people to sign up the the updates without confirming their email address.

I tried to set  Binput::get('verify', false), in the below code located in app/Http/Controllers/Api/SubscriberController.php but it did not work

public function postSubscribers()
    {
        try {
            $subscriber = dispatch(new SubscribeSubscriberCommand(
                Binput::get('email'),
                Binput::get('verify', false),
                Binput::get('components', null)
            ));
        } catch (QueryException $e) {
            throw new BadRequestHttpException();
        }

        return $this->item($subscriber);
    }

**Comment by jbrooksuk** [comment]
Sorry, I re-worded my reply. It's very hot here today and I'm not with it :)

**Comment by jbrooksuk** [comment]
This is now done in v2.4.0.
