### ISSUE TITLE
Idea: Multi-branding

### ISSUE THREAD

**Issue by mhayes14** [CachetHQ/Cachet#1991]
I'm not sure how popular this would be for the masses. However it would be nice (in my opinion) if we could change the title and toggle the display of components depending on the hostname used to access the installation. This would be handy for multiple brands being managed by the same people, even running on the same servers, rather than using separate installations.

**Comment by TheoBearman** [comment]
Or just run multiple Cachet instances with Apache vhosts and save the developers a lot of time?

**Comment by mhayes14** [comment]
The people who would like to see such a feature (such as myself) can always open a PR in terms of development time but it's worth seeing if the maintainers would even consider accepting this.

The benefit over running multiple instances is being able to open incidents from one central place, although admittedly this could probably be handled using some API magic with a separate interface.

**Comment by jbrooksuk** [comment]
Like this? https://github.com/CachetHQ/Cachet/issues/236

**Comment by mhayes14** [comment]
@jbrooksuk Thanks, looks good (I was searching "branding" etc so didn't come across this issue). There's definitely some relevant comments in there too. In my case I would probably add something to default to the relevant "application" (`/app/some-app-name` view) depending on the hostname or using environment vars. No doubt that issue covers most cases and could certainly be the basis to any further suggestions - I'll close this one.

**Comment by jbrooksuk** [comment]
If you have anything to add, just add them to the other issue :)

I'm actually going to be working on this next month, anyway!
