### ISSUE TITLE
Shows setup screen after upgrade

### ISSUE THREAD

**Issue by meyskens** [CachetHQ/Cachet#1996]
Before submitting your issue, please make sure that you've checked the checkboxes below.

- [x] I am running the [latest release](https://github.com/CachetHQ/Cachet/releases/latest) version of Cachet.
- [x] I am running at least PHP 5.5.9. *You can check this by running `php -v`.*
- [x] I have ran `rm -rf bootstrap/cache/*`.

### Expected behaviour

Show the status page after upgrade

### Actual behaviour

It shows the setup while everything is in the .env file. 

### Steps to reproduce

Upgrading from 2.1.x to 2.3.x

**Comment by jbrooksuk** [comment]
Ping @GrahamCampbell, this is because of caching, right?

**Comment by GrahamCampbell** [comment]
No idea. I'll need to properly investigate this.

**Comment by meyskens** [comment]
If you need any more info give me a ping ;)

**Comment by GrahamCampbell** [comment]
Sure, thanks. :)

**Comment by scheesman** [comment]
Same issue here.  First happened from v2.3.2 to v2.3.5.  Upgrading to v2.3.6 didn't address.  Tried clearing caching and didn't help.  Both the main page and /dashboard redirect to /setup.  I would be willing to help in whatever way possible as well.

**Comment by ivanbreet** [comment]
Got the same issue upgrading from __v2.3.5__ to __v2.3.6__.

**Comment by GrahamCampbell** [comment]
Thanks for the feedback everyone. I'm elevating the priority on the issue to maximum.

**Comment by GrahamCampbell** [comment]
> Got the same issue upgrading from v2.3.5 to v2.3.6.

Must have already been broken at that point, since we didn't actually change anything between those two versions.

**Comment by GrahamCampbell** [comment]
I've reverted the change that I think is responsible for this. We'll be doing a release soon.

**Comment by meyskens** [comment]
I have upgraded to the dev branch and it worked :)

**Comment by jbrooksuk** [comment]
👍 

We've shipped a new version too.

**Comment by scheesman** [comment]
Can confirm release v2.3.7 fixed problem on our system!

**Comment by jbrooksuk** [comment]
🎉

**Comment by GrahamCampbell** [comment]
Great"

**Comment by viswamitra** [comment]
I have the same problem with v2.3.15. (Latest at this point). 
I have done the following: 

- [x] Enabled mod_rewrite in httpd.conf
- [x] Running PHP with v7.2.8
- [x] Followed the instructions given in the setup page [https://docs.cachethq.io/v1.0/docs/installing-cachet](url), using apache. 

I see that whenever I point to /, it redirects to /setup, and that gives a 500.
Access-log: 
```
[Wed Aug  8 16:40:51 2018] ::1:55366 [302]: /
[Wed Aug  8 16:40:51 2018] ::1:55367 [500]: /setup
```

**Comment by Atriusftw** [comment]
As far as i know, Cachet 2.3 doesn't properly support PHP 7. Correct me if this has changed though.
