### ISSUE TITLE
Link from the Github README.md to Vagrant doc is broken (404)

### ISSUE THREAD

**Issue by chaica** [CachetHQ/Cachet#1998]
### Expected behaviour

https://github.com/CachetHQ/Cachet should allow the access to the webpage about Vagrant https://docs.cachethq.io/docs/get-started-with-vagrant

### Actual behaviour

Link to the Vagrant documentation is broken https://docs.cachethq.io/docs/get-started-with-vagrant
from the web page:
https://github.com/CachetHQ/Cachet

### Steps to reproduce
1/ go to the following page https://github.com/CachetHQ/Cachet
2/ try to click on the link https://docs.cachethq.io/docs/get-started-with-vagrant

**Comment by jbrooksuk** [comment]
Fixed, thanks!
