### ISSUE TITLE
Feature Request: MEAnalystics

### ISSUE THREAD

**Issue by KacyLuzz** [CachetHQ/Cachet#2000]
Hello!
MEAnalystics is a analystics service, actually in dev and only in french, API is simple
_GET_ https://analystics.might-espace.com/rest/newvisit.php?accid={ID}&accsecret={SECRET}

Website : https://analystics.might-espace.com/

**git commit -m "New issue" & git push**

**Comment by GrahamCampbell** [comment]
Thanks, but I don't think this is something suitable for the core. // cc @jbrooksuk

**Comment by jbrooksuk** [comment]
Hi @KacyLuzz thanks for your suggestion!

I agree with @GrahamCampbell that this isn't suitable for the core of Cachet. We won't be adding MEAnalytics whilst it's in dev, French only and is an API as opposed to a JS tracker.

Thanks again though!
