### ISSUE TITLE
cachet front page super slow, stalling

### ISSUE THREAD

**Issue by mbravorus** [CachetHQ/Cachet#2001]
Before submitting your issue, please make sure that you've checked the checkboxes below.

- [x] I am running the [latest release](https://github.com/CachetHQ/Cachet/releases/latest) version of Cachet.
- [x] I am running at least PHP 5.5.9. *You can check this by running `php -v`.*
- [x] I have ran `rm -rf bootstrap/cache/*`.

### Expected behaviour

Normal loading times

### Actual behaviour

Front page loads excessively slow, multiple tens of seconds, leading sometimes to 504 gateway timeouts from nginx

At the same time, the dashboard loads super quick and functions also very snappy.

The server is not [over]loaded, load averages are all <1

PHP version is PHP 5.6.19-1+deb.sury.org~trusty+1

php-fpm, nginx, mysql restarts make no difference

You can view the front page in action (if it loads) here - https://status.freefeed.net/

**Comment by jbrooksuk** [comment]
Hey, it loads just fine, is that why you closed the issue?

**Comment by mbravorus** [comment]
I have discovered I have misrepresented one of checkboxes :) I thought I was running the latest code, however I was deploying via a forked repo, with tags not pulled through properly. Pushed the tags through, upgraded, and now it loads fine.

**Comment by jbrooksuk** [comment]
Awesome! :)
