### ISSUE TITLE
Redirects to setup every time

### ISSUE THREAD

**Issue by kureci** [CachetHQ/Cachet#2005]
Before submitting your issue, please make sure that you've checked the checkboxes below.

- [x] I am running the [latest release](https://github.com/CachetHQ/Cachet/releases/latest) version of Cachet.
- [x] I am running at least PHP 5.5.9. *You can check this by running `php -v`.*
- [x] I have ran `rm -rf bootstrap/cache/*`.

### Expected behaviour

* Cachet should go to Dashboard after it's setup once 

### Actual behaviour

* Cachet shows setup page every time regardless of previous setup

Is anyone actually using the latest release of this project (v2.3.6) because it just doesn't work! After going through the setup, it goes back to setup again every time. When having a quick look, `SetupAlreadyCompleted` middleware checks for `setting.app_name` config but that's never set as part of the setup process. When manually inserting `app_name` in `config/setting.php`, it works.
I also noticed that none of the settings are saved when you update, e.g. site name, URL.. etc. Is it a permissions issue? I even tried changing permissions on `config/*` to 775 but didnt do good.

**Comment by keithslater** [comment]
Same problem here.

**Comment by ccosentino** [comment]
I have 2.3.6 working with MySQL (I can't get it to work with Sqlite).

Make sure you chmod 777 storage before you run through the setup. I think that fixed it for me, but it is hard to say what got it working because I tried about 15 times to get it installed, trying different things each time.  

My suggestion is to start fresh. Here are the commands that seemed to work for me one or the last few times I installed. I saved my .env file in my home directory so I could quickly copy it over to the cloned repo.

```
cd /var/www
git clone https://github.com/cachethq/Cachet.git
cd Cachet
git checkout v2.3.6
chmod -R 777 storage
chmod -R 777 bootstrap
cp ~/env.txt ./.env
chmod 777 .env
composer install --no-dev -o
php artisan key:generate
php artisan app:install 
rm -rf bootstrap/cache/*
```
Then open your browser and go to the site (assuming you set up the virtual host config already)

**Comment by kureci** [comment]
I've followed steps from @ccosentino and install works fine now (albeit I also had to change permissions for `storage/logs`). 
For anyone anyone coming across this issue and not being able to add subscribers, please note you also need to have a value for `MAIL_NAME` in you `.env.` file - otherwise subscription is disabled.

**Comment by shaun-ba** [comment]
Why is the documentation so outdated? Its taken me a good number of hours and i'm still not up and running, also experiencing this redirect.

**Comment by jbrooksuk** [comment]
@shaun-ba what version are you using?

**Comment by nikhilgupta23** [comment]
It was a permission issue for me too. Refer to the comment by @ccosentino to solve it.

**Comment by ageric** [comment]
For those who aren't having permission issues, try running

php artisan up

to disable the setup redirect. Worked for me, but YMMV.

**Comment by sheldonj22** [comment]
I had this issue as well. For anyone else I went to the root of the application and ran:
```
chown -R apache:apache *
chmod -R 775 *
```
Then went through the setup again. Better than 777. 

Would be nice to include in install documentation.

**Comment by gmyhre** [comment]
I had this issue as well.  For an sqlite setup I had to change the 
CACHE_DRIVER=database
SESSION_DRIVER=database
in addition to the permissions on .env
but as noted above YMMV
