### ISSUE TITLE
Style not updating

### ISSUE THREAD

**Issue by meyskens** [CachetHQ/Cachet#2009]
Before submitting your issue, please make sure that you've checked the checkboxes below.

- [x] I am running the [latest release](https://github.com/CachetHQ/Cachet/releases/latest) version of Cachet.
- [x] I am running at least PHP 5.5.9. *You can check this by running `php -v`.*
- [x] I have ran `rm -rf bootstrap/cache/*`.

### Expected behaviour

Text color to update after changing in settings.

### Actual behaviour

It saves it correct in the database but doesn't serve it back to the settings and the status page css. 

### Steps to reproduce

Update any color in the styles.

**Comment by GrahamCampbell** [comment]
Does your web server have write permission to the bootstrap/cachet folder?

**Comment by jbrooksuk** [comment]
Can you try again on the latest version please?

**Comment by meyskens** [comment]
It works now :) Thanks
