### ISSUE TITLE
Setup Code Climate

### ISSUE THREAD

**Issue by jbrooksuk** [cachethq/Cachet#201]
I've setup Code Climate for [Cachet](https://codeclimate.com/github/cachethq/Cachet). We'll just need to setup the test coverage with it.

**Comment by GrahamCampbell** [comment]
Scrutinizer ci is better as far as I'm concerned.

**Comment by GrahamCampbell** [comment]
I use it a lot.

**Comment by GrahamCampbell** [comment]
It does coverage and quality analysis, and was build for php unlike codeclimate that just supports php.

**Comment by jbrooksuk** [comment]
I've no idea how to setup Scruitinizer properly. I hated the interface. Does someone want to do that, if @GrahamCampbell says it's better, it is.

**Comment by GrahamCampbell** [comment]
I can set it up for you if you want.

**Comment by GrahamCampbell** [comment]
I've got existing config files from my other repos that work. :)

**Comment by joecohens** [comment]
Awesome!

**Comment by jbrooksuk** [comment]
Sure :)

**Comment by GrahamCampbell** [comment]
Only someone with admin access is allowed to sign this repo up on scrutinizer.

**Comment by jbrooksuk** [comment]
I'll make you and @joecohens admins.

**Comment by jbrooksuk** [comment]
Done.

**Comment by joecohens** [comment]
:)

**Comment by kfrankperson** [comment]
:+1:

**Comment by GrahamCampbell** [comment]
I'll add badges soon.

**Comment by jbrooksuk** [comment]
Awesome!

**Comment by GrahamCampbell** [comment]
NB, scrutinize takes ~10 to actually get going. I'll let you know when it's ready.

**Comment by jbrooksuk** [comment]
Do we need Travis now?

**Comment by GrahamCampbell** [comment]
Yeh, we still run the tests on travis.
