### ISSUE TITLE
Missing English Language Lines

### ISSUE THREAD

**Issue by johnwheal** [CachetHQ/Cachet#2010]
I'm using v2.3.6

A chunk of the English `forms` language file appears to missing.

For example, I have identified that the following lines are missing:
* forms.setup.mail_driver
* forms.setup.mail_host
* forms.setup.mail_address
* forms.setup.mail_username
* forms.setup.mail_password

The above are used on the Setup page.

**Comment by jbrooksuk** [comment]
I've updated the CrowdIn translations.
