### ISSUE TITLE
Y-axis scale precision not consistent with decimal value of metrics

### ISSUE THREAD

**Issue by tejasshah93** [CachetHQ/Cachet#2012]
### Expected behaviour
In case of multiple metrics too, Y-axis scale precision must be set to metric's decimal value respectively.

### Actual behaviour
Y scale precision doesn't get reflected unless the **last** metric's decimal value is set > 0

### Steps to reproduce

Reproducible on [Cachet Demo](https://demo.cachethq.io/)

1. Create a new metric with decimal value > 0  ( . . say '2')
2. After step 1, create another metric with decimal value = 0
3. Visit the status page. Both the Y-axes will show non-decimal scale (Not expected)
4. Now, update decimal value of the last metric created to '2'.
5. Visit the status page. Now both the Y-axes will show decimal scale (Expected)

Tried this with different permutations as well.

**Comment by tejasshah93** [comment]
Observation: For all the metrics with decimal value > 0, the Y-axis scale precision is synchronised to last metric's decimal value.

So, if decimal value is set to 2 for any metric (other than the last), and the last one is assigned decimal value of 1, then both the metrics will reflect precision with 1 decimal only.

**Comment by jbrooksuk** [comment]
@tejasshah93 thanks for the bug report! Are you able to make a PR to fix this issue? :)

**Comment by jbrooksuk** [comment]
Does #2015 fix this for you?
