### ISSUE TITLE
A python client library for Cachet: python-cachetclient

### ISSUE THREAD

**Issue by dmsimard** [CachetHQ/Cachet#2013]
Hi,

As per the instructions in the [documentation](https://docs.cachethq.io/docs/client-libraries), I'm letting you know that I'm working on a python client library for Cachet: [python-cachetclient](https://github.com/dmsimard/python-cachetclient).
The module already works and can be installed from source or from PyPi.

python-cachetclient will be the foundation of an eventual [Ansible](https://www.ansible.com/) module in order to be able to manage Cachet programmatically (i.e, create incidents/resolve incidents, manage components/component groups, etc.) in Ansible playbooks.

Let me know if you have any questions !

**Comment by jbrooksuk** [comment]
Awesome, thanks! We'll get this updated on our docs ASAP.

**Comment by jbrooksuk** [comment]
I've updated the docs! Thank you :)
