### ISSUE TITLE
Changing order of one component break status of all components

### ISSUE THREAD

**Issue by sapk** [CachetHQ/Cachet#2014]
Before submitting your issue, please make sure that you've checked the checkboxes below.

- [X] I am running the [latest release](https://github.com/CachetHQ/Cachet/releases/latest) version of Cachet.
- [X] I am running at least PHP 5.5.9. *You can check this by running `php -v`.*
- [X] I have ran `rm -rf bootstrap/cache/*`.

### Expected behaviour

Changing the order of one component should change order a components and keep components state intact.

### Actual behaviour

Changing the order of one component change the order of the components and set all components state to "cachet.components.status.0". No error is reported to the admin changing the order.

### Steps to reproduce

1. Have a working cachet status page with components in any state you like
2. Change the order of one component in /dashboard/components vue

### Note
Bug is in lastest release. (2.3.7)
Also reproductible in [demo](https://demo.cachethq.io/) (2.3.8-dev)

Web browser : Firefox

**Comment by jbrooksuk** [comment]
Woah, this wasn't caught during testing, sorry man. I'll see if I can fix immediately.

**Comment by sapk** [comment]
Thanks
