### ISSUE TITLE
Incident update should also update the incident status as the old status

### ISSUE THREAD

**Issue by stipx** [CachetHQ/Cachet#2022]
Hi,

in the development version the incident update is not updating the incident status, so it is still shown with the old status in the dashboard and also the status is wrong when using the REST api.

I do not know if this is expected behavior, but I think the incident status should be updated as well.
I know the development version is (as the name indicates) still in development, but I think this should be a low hanging fruit and just to not forget about this point.

Thanks

**Comment by jbrooksuk** [comment]
Are you using the `develop` branch currently? I wouldn't even look at it 😄 it's nowhere near ready for production and is nowhere near even half complete yet.

**Comment by stipx** [comment]
Yes, thought so. Just wanted to mention so that it does not get lost ;)

**Comment by jbrooksuk** [comment]
I think that my original plan was to:

1. Use the `incidents.status` field if there were no updates yet.
2. If an update exists, then virtually override the `status` field in the API with that of the last updates status.

That way the original incident status still exists. But perhaps it'd be better to _actually_ update the incident status?

**Comment by stipx** [comment]
I think it does not have any benefit keeping the old incident status and just virtually override it.
But one other thing: I find this update feature really cool. In 2.x we have to change the incident message e.g. when we want to post that some person is working on it and that guy is the one to contact first on issues.

**Comment by jbrooksuk** [comment]
> I find this update feature really cool.

Thanks mate! I can't wait for us to ship it!

**Comment by jbrooksuk** [comment]
Fixed https://github.com/CachetHQ/Cachet/commit/d5d92f5a3d4584a3645ae89d0e21d219bf6a2674
