### ISSUE TITLE
Add the possibility to stick a incident to the top

### ISSUE THREAD

**Issue by sapk** [CachetHQ/Cachet#2023]
I think it should be possible to add the possibility to stick a (or multiple) incident to the top (on top of the historic). In order to display long running incident that are "far away" in the timeline. The incident should also be display in the timeline.

**Comment by jbrooksuk** [comment]
> In order to display long running incident that are "far away" in the timeline.

As in, in the past?

**Comment by sapk** [comment]
For example you have detect a incident that slow your process 5 days ago. Your are still on it but performance are still impacted but the incident is not visible at first sight. It should be great if we could indicat to "stick" the incident to show it also on top of the timeline.

**Comment by jbrooksuk** [comment]
@sapk I see, thanks for clarifying.

We'll have a think :)

**Comment by jbrooksuk** [comment]
Ping @joecohens on your thoughts? :)

**Comment by joecohens** [comment]
I think it's a cool idea, you can pin or unpin featured incidents. If you have a featured incident that you want to keep for a few weeks just to let people that it happened or that it has already been resolved but you need to make it notice, you won't need to paginate.

**Comment by sapk** [comment]
Maybe, I could propose a PR for implementing this. I have no experience with Laravel but a little with PHP and this feature may only need little modification.

**Comment by jbrooksuk** [comment]
Sure! We look forward to it :)

**Comment by jbrooksuk** [comment]
Closed by https://github.com/CachetHQ/Cachet/pull/2065
