### ISSUE TITLE
Reference id / remote id in api generated incidents

### ISSUE THREAD

**Issue by mrbase** [CachetHQ/Cachet#2024]
We would like to use Cachet with out surveillance setup, but needs to be able to set the id of the incident, not have it auto-generated.

Opening up for id setters is probably not a good idea, but how about a `remote_reference` field ? 
Then on lookups/updates - you should also be able to look up incidents by that id.

That way a 3-party system could post and update incidents without having to know about Cachet id's - which is optimal when using tools that do not process return data.

Thoughts on this ?

**Comment by jbrooksuk** [comment]
@GrahamCampbell and I actually briefly discussed this on Saturday, but for a different reason.

I do agree that it'd be useful to have a way of storing an "internal reference" or whatever it may be, for incidents and components.

**Comment by jbrooksuk** [comment]
I'm not going to place this into a Milestone until we're further forward with some other bits.

**Comment by jbrooksuk** [comment]
Done in https://github.com/CachetHQ/Cachet/pull/2570
