### ISSUE TITLE
Button to remove Banner Image disable the Save Settings

### ISSUE THREAD

**Issue by SamuelMoraesF** [cachethq/Cachet#203]
On ```Settings > Application Setup```, when I click on the ```Remove``` button of the ```Banner Image``` the ```Save Settings``` button are disabled

**Comment by jbrooksuk** [comment]
```js
$('#remove-banner').click(function(){
    $('#banner-view').remove();
    $('input[name=remove_banner]').val('1');
    $('#settings-form').submit();
});
```

What's happening is that on click, the form gets submitted, but it doesn't seem to fully submit. We could just remove the `submit` line and wait for the user to click Submit form manually.

**Comment by joecohens** [comment]
@jbrooksuk I think that is a better solution.
