### ISSUE TITLE
fix thresholds and metrics

### ISSUE THREAD

**Issue by GrahamCampbell** [CachetHQ/Cachet#2035]

**Comment by jbrooksuk** [comment]
What did we say about this?

**Comment by GrahamCampbell** [comment]
The threshold must be a factor of 60, and if it's more than 10, then we should disable hourly view. We also need to update the scale on hourly view to match the threshold width.

**Comment by jbrooksuk** [comment]
We don't need the threshold factor check as we're storing minutes only.

Assigning to you @GrahamCampbell for the weekend.
