### ISSUE TITLE
Sort subscription components by component groups

### ISSUE THREAD

**Issue by jhamilton09** [CachetHQ/Cachet#2048]
Before submitting your issue, please make sure that you've checked the checkboxes below.

[ X ] I am running the latest release version of Cachet.
[ X ] I am running at least PHP 5.5.9. You can check this by running php -v.
[ X ] I have ran rm -rf bootstrap/cache/*.
What version of Cachet? 2.3.9
What database driver? MySQL? Postgres? SQLite? MySQL
What version of PHP? 7.0.3

### Expected behaviour

*Please describe what you're expecting to see happen.*
The 'Manage notifications' page should order components by component groups.

### Actual behaviour

*Please describe what you're actually seeing happen.*
Components on the notification page are listed by ID rather than component group.

### Steps to reproduce

*If your issue requires any specific steps to reproduce, please outline them here.*

View page at example.com/subscribe/manage/[string].

**Comment by jbrooksuk** [comment]
We pull out the components in a group by their `order` value, so this shouldn't be the case.

**Comment by GrahamCampbell** [comment]
Try running `php artisan app:update` please.

**Comment by jbrooksuk** [comment]
Closed as I can't replicate.
