### ISSUE TITLE
Add new component status for ongoing maintenance (e.g. UNDER MAINTENANCE)

### ISSUE THREAD

**Issue by stipx** [CachetHQ/Cachet#2051]
During discussions in #2044 we came across the idea to add another status for components to be able to mark the component as "under maintenance". This would ease our maintenance workflow:
- Schedule a maintenance
- When maintenance is started set the status to "UNDER MAINTENANCE"
- When maintenance is done reset the status

We're also creating incidents via a checking service and so we are able to skip incident creation when the component is under maintenance.

**Comment by jbrooksuk** [comment]
I think the way I'm going to handle this is to add a new status **and** at the same time make the status names configurable 💥

**Comment by stipx** [comment]
Hi,
any news on this? We eagerly await this feature to get our workflow clean.

**Comment by jbrooksuk** [comment]
@stipx I've rewritten the scheduled maintenance system today, but need to finish it off so that components can be modified too. Then we'll be there!

**Comment by jbrooksuk** [comment]
Okay, so there won't be a new status specifically for this, instead the component status will be changed to say "Under maintenance" or whatever we decide on 👍

**Comment by jbrooksuk** [comment]
All we need is a way of selecting affected components in the dashboard now.

**Comment by Hunterm267** [comment]
Really looking forward to custom status names, hope that feature can be included in a v2.4 release potentially as well as originally mentioned!

**Comment by ImFlushy** [comment]
You can rename your status-names in /resources/lang/YOUR-LANGUAGE/cachet.php in line 17-20.

**Comment by stipx** [comment]
But I do not want to rename the status. I would like to have another one. The current states with "Operational", "Performance Issues", "Partial Outage" and "Major Outage" are all in use.

**Comment by jbrooksuk** [comment]
Adding a new status is a little harder because we have validation in place.

**Comment by mhayes14** [comment]
Another vote for additional statuses. In our case we would like an "At Risk" status between "Operational" and "Performance Issues".

For example, when grid power has failed and switched to generators or any other part of the service is running on a failover system, the component would be considered "At Risk" of failure. Some may consider this a "partial outage" but as far as our customers are concerned, there is no outage, there is just a greater risk of an outage occurring than usual.

**Comment by jbrooksuk** [comment]
@mhayes14 I see what you're saying... 🤔

**Comment by MarkL4YG** [comment]
Another vote for configurable statuses! Having them configurable gives you the freedom to have as many and name statuses as you want.

**Comment by iamjulians** [comment]
+1 for more statuses and configurable names + colors!

**Comment by jbrooksuk** [comment]
Thoughts...

We'd setup default component and incident statuses within a configuring table:

```
id | name | slug | type | status_id
1 | Unknown | unknown | components | 0
2 | Operational | operational | components | 1
3 | Performance Issues | performance-issues | components | 2
4 | Partial Outage | partial-outage | components | 3
5 | Major Outage | major-outage | components | 4
6 | Investigating | investigating | incidents | 1
7 | Identified | identified | incidents | 2
7 | Watching | watching | incidents | 3
7 | Fixed | fixed | incidents | 4
```

This means incidents and components can have different statuses. We'd do this as part of the migration I guess, but it would default English versions.

**Comment by MarkL4YG** [comment]
That's very interesting! Maybe also add a column for component coloring.  
I'd love to test ;)

**Comment by phutchins** [comment]
Just started using Cachet and really need this feature added so that I can have a deprecated status. If we're moving a service out and it will no longer be available, we want to communicate that without having it look like its down by error.

**Comment by jbrooksuk** [comment]
👍 

It's being worked on @phutchins :)

**Comment by felipelalli** [comment]
+1

**Comment by phutchins** [comment]
Awesome! Thanks for the update @felipelalli

**Comment by dschwabeS11** [comment]
Just wanted to open a feature request for this. 
It would be awesome to have this feature released with 2.4. It is also required to be able select components that will be affected by the maintenance work.

Thanks guys!

**Comment by jbrooksuk** [comment]
I've been thinking about this a bit more.

Would it make sense that as soon as a scheduled maintenance becomes active, the component needs to simply change the status to "Under Maintenance"?

**Comment by jbrooksuk** [comment]
The important thing here is that if a schedule attaches to a component, then it will *always* be under maintenance, it wouldn't be a choice.

**Comment by jlcd** [comment]
Is there any way, today, to add a single custom status without tweaking the code too much? Anyone done that?

**Comment by MarkL4YG** [comment]
@jlcd Not that I am aware of. But you could just rename one of the predefined ones?  
Otherwise, you could try to figure out how the statuses are implemented. Surely this will reveal how to add custom statuses atm.

**Comment by jlcd** [comment]
@MarkL4YG thanks for the quick response. Will try your first suggestion.

**Comment by Blizzard098** [comment]
Any progress on this? @jbrooksuk

**Comment by jbrooksuk** [comment]
Thank you for your input on Cachet 2.x. We are shifting our attention and resources to Cachet 3.x and will no longer be supporting the 2.x version. If your feedback or issue is relevant to the 3.x series, we encourage you to engage with the new branch.

For more information on the Cachet rebuild and our plans for 3.x, you can read the announcement [here](https://github.com/CachetHQ/Cachet/discussions/4342).

We appreciate your understanding and look forward to your contributions to the new version.
