### ISSUE TITLE
PHPUnit Doesn't Clear Caches

### ISSUE THREAD

**Issue by ConnorVG** [CachetHQ/Cachet#2053]
Before submitting your issue, please make sure that you've checked the checkboxes below.

- [x] I am running the [latest release](https://github.com/CachetHQ/Cachet/releases/latest) version of Cachet.
- [x] I am running at least PHP 5.5.9. *You can check this by running `php -v`.*
- [x] I have ran `rm -rf bootstrap/cache/*`.

### Expected behaviour

After running `phpunit`, I expect my environment to not be mutated.

### Actual behaviour

PHPUnit bootstraps it's environment and never clears it's cache once completed (application stays in testing).

### Steps to reproduce

1. Have a default installation (pre-setup and seeded)
2. Run `vendor/bin/phpunit`
3. Go to your site, notice you're now on `/setup`
4. Run `artisan env` and notice you're now in `testing`

**Comment by GrahamCampbell** [comment]
Yeh, this is a known issue, but I've never really cared enough to fix it. :trollface:

Feel free to have a go I guess. ;)

**Comment by ConnorVG** [comment]
It's annoying af...

**Comment by yoyosan** [comment]
`artisan config:clear` fixes it. But it should be automatic.

**Comment by GrahamCampbell** [comment]
I imagine we're also messing with our settings cache (not the same as config).

**Comment by ConnorVG** [comment]
Hmm, we could always add a listener... Like:

```php
<?php

/*
 * This file is part of Cachet.
 *
 * (c) Alt Three Services Limited
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace CachetHQ\Tests\Cachet;

use ErrorException;
use Illuminate\Container\Container;
use PHPUnit_Framework_BaseTestListener;
use PHPUnit_Framework_TestSuite;

/**
 * This is the test listener class.
 *
 * @author Connor S. Parks <connor@connorvg.tv>
 */
class TestListener extends PHPUnit_Framework_BaseTestListener
{
    /**
     * A test suite ended.
     *
     * @since Method available since Release 2.2.0
     *
     * @param \PHPUnit_Framework_TestSuite $suite
     *
     * @return void
     */
    public function endTestSuite(PHPUnit_Framework_TestSuite $suite)
    {
        if ($suite->getName() !== 'Cachet Test Suite') {
            return;
        }

        foreach (glob(__DIR__.'/../bootstrap/cache/*.php') as $file) {
            unlink($file);
        }
    }
}
```

```xml
<listeners>
    <listener class="CachetHQ\Tests\Cachet\TestListener" file="./tests/TestListener.php" />
</listeners>
```

**Comment by ConnorVG** [comment]
Lul :trollface:

**Comment by ConnorVG** [comment]
As @GrahamCampbell noted, it actually needs all cache files cleared. Not just X or Y.
