### ISSUE TITLE
500 Internal server error on fresh install

### ISSUE THREAD

**Issue by fcpwiz** [CachetHQ/Cachet#2057]
Before submitting your issue, please make sure that you've checked the checkboxes below.

- [x] I am running the [latest release](https://github.com/CachetHQ/Cachet/releases/latest) version of Cachet.
- [x] I am running at least PHP 5.5.9. *You can check this by running `php -v`.*
- [x] I have ran `rm -rf bootstrap/cache/*`.

### Expected behaviour

The setup page to show up.

### Actual behaviour

Gives a 500 Internal Server Error

### Steps to reproduce

1. Refresh the page.

**Comment by yoyosan** [comment]
Hi!

I don't think you configured correctly your Apache virtual host for 
Maybe this helps: http://laravel-recipes.com/recipes/25/creating-an-apache-virtualhost

Also, please be mindful of sharing so many details. If you go here, https://status.fluxxmc.com/Cachet/.env, you'll see that your credentials(like DB username and password) are now exposed to the world. Please change them ASAP.

**Comment by fcpwiz** [comment]
@yoyosan The httpd-vhosts.conf file contains this:

```
VirtualHost *:80>
    ServerName cachet.dev
    # Or whatever you want to use
    ServerAlias cachet.dev
    # Make this the same as ServerName
    DocumentRoot "/public_html/Cachet/public"
    <Directory "/public_html/Cachet/public">
        Require all granted
        # Used by Apache 2.4
        Options Indexes FollowSymLinks
        AllowOverride All
        Order allow,deny
        Allow from all
    </Directory>
</VirtualHost>
```

**Comment by fcpwiz** [comment]
@yoyosan that file is located at /etc/httpd/conf/ on a CentOS 6 VPS

**Comment by yoyosan** [comment]
Did you check `/var/log/httpd/error_log`?

**Comment by fcpwiz** [comment]
@yoyosan it shows as empty.

**Comment by GrahamCampbell** [comment]
And your php-fpm logs?

**Comment by fcpwiz** [comment]
@GrahamCampbell /var/log/php-fpm/error_log ?

**Comment by fcpwiz** [comment]
If that's the correct file path, then the error log is also empty.

**Comment by GrahamCampbell** [comment]
I'm not really sure what to recommend then. We do offer a professional install service starting at $149 if you're interested.

**Comment by fcpwiz** [comment]
Cachet is installed on ~/public_http. Should it be installed in /public_http instead? @GrahamCampbell @yoyosan

**Comment by GrahamCampbell** [comment]
You can install it wherever you want.

**Comment by yoyosan** [comment]
@fcpwiz try to use the absolute path to your Cachet installation folder in the `httpd-vhosts.conf` file:

```
DocumentRoot "<absolute_path_to_Cachet>"
<Directory "<absolute_path_to_Cachet>">
```

Hope it works.

**Comment by fcpwiz** [comment]
@yoyosan Ok I modified that file. What commands do I have to run to get it working? What do I have to restart?

**Comment by yoyosan** [comment]
Search Google on how to restart your apache server on CentOS.

**Comment by fcpwiz** [comment]
@yoyosan doesn't seem to be working from my side: https://status.fluxxmc.com

**Comment by GrahamCampbell** [comment]
Looks like you;ve not setup the vhost correctly.

**Comment by TheLastProject** [comment]
If that is your actual config, it's a good idea to actually use a search engine to see how ServerName works in Apache because I'm preeeetty sure you're not serving it from cachet.dev.

**Comment by fcpwiz** [comment]
Ok I fixed that config. Will restarting the VPS also reset Apache?

**Comment by fcpwiz** [comment]
@TheLastProject @GrahamCampbell @yoyosan Ok here's the current httpd-vhosts.conf:

```
<VirtualHost *:80>
ServerName status.fluxxmc.com
# Or whatever you want to use
ServerAlias status.fluxxmc.com
# Make this the same as ServerName
DocumentRoot "<absolute_path_to_Cachet>"
<Directory "<absolute_path_to_Cachet>">
Require all granted
# Used by Apache 2.4
Options Indexes FollowSymLinks
AllowOverride All
Order allow,deny
Allow from all
</Directory>
</VirtualHost>
```

**Comment by GrahamCampbell** [comment]
is it pointing to the public folder?

**Comment by GrahamCampbell** [comment]
Short answer is no looking at status.fluxxmc.com.

**Comment by TheLastProject** [comment]
Your issue, unfortunately, is clearly that you're just copy-pasting whatever people tell you without properly reading their posts. Re-read https://github.com/CachetHQ/Cachet/issues/2057#issuecomment-239664506 and try to actually understand what @yoyosan said, instead of copy-pasting it without thinking.

**Comment by fcpwiz** [comment]
Well, the folder "public_html" is the public folder but you said to use the absolute path thing.

**Comment by yoyosan** [comment]
`<absolute_path_to_Cachet>` is just a placeholder. You need to replace with your actual installation directory for Cachet.

Find it out by going into the Cachet installation directory on your VPS and issuing a `pwd` command. The output of the command will tell you the absolute path.

**Comment by fcpwiz** [comment]
@yoyosan Should if end in "/public"?

**Comment by fcpwiz** [comment]
Because that's what's on the docs.

**Comment by yoyosan** [comment]
> @yoyosan Should it end in "/public"?

Yes.

**Comment by fcpwiz** [comment]
@yoyosan This looks correct?

```
<VirtualHost *:80>
ServerName status.fluxxmc.com
# Or whatever you want to use
ServerAlias status.fluxxmc.com
# Make this the same as ServerName
DocumentRoot "/home/fluxxmc/public_html/Cachet/publi$<Directory "/home/fluxxmc/public_html/Cachet/public">Require all granted
# Used by Apache 2.4
Options Indexes FollowSymLinks
AllowOverride All
Order allow,deny
Allow from all
</Directory>
</VirtualHost>
```

**Comment by fcpwiz** [comment]
```
<VirtualHost *:80>
ServerName status.fluxxmc.com
# Or whatever you want to use
ServerAlias status.fluxxmc.com
# Make this the same as ServerName
DocumentRoot "/home/fluxxmc/public_html/Cachet/public"
<Directory "/home/fluxxmc/public_html/Cachet/public">
Require all granted
# Used by Apache 2.4
Options Indexes FollowSymLinks
AllowOverride All
Order allow,deny
Allow from all
</Directory>
</VirtualHost>
```

@yoyosan This look correct?

**Comment by yoyosan** [comment]
Yes. But pay attention to the formatting from https://github.com/CachetHQ/Cachet/issues/2057#issuecomment-239658175.

**Comment by fcpwiz** [comment]
@yoyosan Hmm can you check if https://status.fluxxmc.com is working for you?

**Comment by yoyosan** [comment]
It's not.

There's something wrong with your Apache configuration but I don't know what.

**Comment by fcpwiz** [comment]
@yoyosan so here's the full conf: http://i.imgur.com/1RTu8R0.jpg

**Comment by fcpwiz** [comment]
The Cachet install is /home/fluxxmc/public_html/Cachet/public

And the config is /etc/httpd/conf/httpd-vhosts.conf

**Comment by fcpwiz** [comment]
Could this be caused by the .env file not being properly set up? I have "(redacted)" in place for my DB info.

**Comment by fcpwiz** [comment]
@yoyosan If the vhosts file isnt working for whatever reason, is there a way to set up a .htaccess file to route to /Cachet/public?

**Comment by fcpwiz** [comment]
@yoyosan 

1. Take a look at the properly formatted conf file. Does it look correct?
![](https://cloud.githubusercontent.com/assets/2921172/17649873/2415d152-623f-11e6-8023-236c8782a028.png)

2. Just to let you know The Cachet install is `/home/fluxxmc/public_html/Cachet/public` & the config is `/etc/httpd/conf/httpd-vhosts.conf`.

3. Could this be caused by the fact that the .env file not being properly set up? I have "(redacted)" in place for my DB info?

4. _If_ we can't get the vhost working, can't we just use a .htaccess file to route to `/Cachet/public`?

**Comment by jbrooksuk** [comment]
What version of Cachet are you trying to install?

**Comment by yoyosan** [comment]
@jbrooksuk https://status.fluxxmc.com/Cachet/VERSION, `2.3.9`

**Comment by jbrooksuk** [comment]
Do you have `mod_indexes` enabled?

**Comment by jbrooksuk** [comment]
I'm closing this as it's not a Cachet issue, but please feel free to continue the discussion.

Also worth noting is that we do a provide an installation service, which starts at $149, you can email us at support@alt-three.com

**Comment by fcpwiz** [comment]
@yoyosan is there a way to convert a server from Apache to Nginx easily?

**Comment by jbrooksuk** [comment]
> @yoyosan Would you recommend switching to NGINX from Apache?

Not @yoyosan but yes.

**Comment by fcpwiz** [comment]
> Do you have mod_indexes enabled?

@jbrooksuk Like in a .htaccess file?

**Comment by fcpwiz** [comment]
@yoyosan Ok so I turned off directory listing. Also, I found the Apache error_log and it's extremely long. What's the best way to get it to you?

**Comment by fcpwiz** [comment]
@yoyosan @jbrooksuk Notice anything weird with the log?

**Comment by jbrooksuk** [comment]
> @jbrooksuk Like in a .htaccess file?

Do you have `mod_rewrite` enabled?

**Comment by fcpwiz** [comment]
@jbrooksuk where would I check to see if I have that enabled? In the vhost config? In a .htaccess file?

**Comment by jbrooksuk** [comment]
Run `apache2ctl -M` and give me the output.

**Comment by fcpwiz** [comment]
`-bash: apache2ctl: command not found`

**Comment by jbrooksuk** [comment]
I'm sorry but this out of our remit of free support. If somebody else can help, please do, otherwise we're only able to offer our professional support service.

**Comment by fcpwiz** [comment]
@jbrooksuk Ah sorry, I had to do `apachectl -M`. Here's what showed up:

```
Loaded Modules:
 core_module (static)
 authn_file_module (static)
 authn_default_module (static)
 authz_host_module (static)
 authz_groupfile_module (static)
 authz_user_module (static)
 authz_default_module (static)
 auth_basic_module (static)
 include_module (static)
 filter_module (static)
 deflate_module (static)
 log_config_module (static)
 logio_module (static)
 env_module (static)
 expires_module (static)
 headers_module (static)
 unique_id_module (static)
 setenvif_module (static)
 version_module (static)
 proxy_module (static)
 proxy_connect_module (static)
 proxy_ftp_module (static)
 proxy_http_module (static)
 proxy_scgi_module (static)
 proxy_ajp_module (static)
 proxy_balancer_module (static)
 ssl_module (static)
 mpm_prefork_module (static)
 http_module (static)
 mime_module (static)
 status_module (static)
 autoindex_module (static)
 asis_module (static)
 suexec_module (static)
 cgi_module (static)
 negotiation_module (static)
 dir_module (static)
 actions_module (static)
 userdir_module (static)
 alias_module (static)
 rewrite_module (static)
 so_module (static)
 bwlimited_module (shared)
 suphp_module (shared)
 security2_module (shared)
Syntax OK
```

**Comment by fcpwiz** [comment]
@jbrooksuk To answer your question, it doesn't look like `mod_rewrite` is there. Is that correct?

**Comment by jbrooksuk** [comment]
It is, it's listed as `rewrite_module`.

I'm sorry to keep repeating this, but we're unable to help you without access to the server.

**Comment by fcpwiz** [comment]
Do you offer student discounts? @jbrooksuk

**Comment by jbrooksuk** [comment]
> Do you offer student discounts? @jbrooksuk

Please contact support@alt-three.com and we'll discuss something.

**Comment by fcpwiz** [comment]
@jbrooksuk Alright, sent out an email :)

**Comment by jbrooksuk** [comment]
Thank you. I'll reply tonight.

**Comment by fcpwiz** [comment]
👍
