### ISSUE TITLE
eonasdan-bootstrap-datetimepicker is 💩

### ISSUE THREAD

**Issue by jbrooksuk** [CachetHQ/Cachet#2062]
There are a couple of issues at play here...

1. The latest version is even more, 💩! We tried upgrading once and then the stupid thing kept not appearing in the right position.
2. The current version is bugged when there are time selectors.
3. It doesn't seem to be maintained any longer.

**Comment by GrahamCampbell** [comment]
Brutal. :trollface:

**Comment by jbrooksuk** [comment]
Looking for alternate suggestions!

**Comment by ConnorVG** [comment]
Easiest option: rewrite the entire system to be an api driven vue spa...


:trollface:

**Comment by jbrooksuk** [comment]
You joke, but once we're on Laravel 5.3 and the new design is released, we'll be rewriting the dashboard with Vue anyway. It's mainly so that we can stop duplicating code and use the same API.

**Comment by ConnorVG** [comment]
Vue would be much easier to have mutated views via plugins, that's for sure.

**Comment by jbrooksuk** [comment]
> Vue would be much easier to have mutated views via plugins, that's for sure.

;)
