### ISSUE TITLE
Dashboard 404 pages

### ISSUE THREAD

**Issue by jbrooksuk** [CachetHQ/Cachet#2063]
We need a dashboard error 404 page.

**Comment by serrexlabs** [comment]
Is there specific templates for 404 ?

**Comment by jbrooksuk** [comment]
Nope, we probably just want the usual dashboard page and some text to say we couldn't find anything.

**Comment by serrexlabs** [comment]
You want to show 404 page when dashboard empty or just a balde template for that ?

**Comment by girishpatil** [comment]
at present what is implemented when a 404 error occurs?

**Comment by jbrooksuk** [comment]
We should show a dashboard page that just says "We couldn't find that page".

Currently, this happens https://demo.cachethq.io/dashboard/foo

**Comment by ankitjain28may** [comment]
Anyone is working on this issue??

**Comment by jbrooksuk** [comment]
Nope :) feel free!

**Comment by ankitjain28may** [comment]
What u need in ur 404 error apart from the current page.. So I wil modify it accordingly

**Comment by jbrooksuk** [comment]
Well, we want to still show the dashboard layout, but with some information text to say that the page wasn't found as this will allow the user to continue navigation.

**Comment by ankitjain28may** [comment]
ok..
