### ISSUE TITLE
Update the Romanian translations

### ISSUE THREAD

**Issue by yoyosan** [CachetHQ/Cachet#2067]
Before submitting your issue, please make sure that you've checked the checkboxes below.

- [x] I am running the [latest release](https://github.com/CachetHQ/Cachet/releases/latest) version of Cachet.
- [x] I am running at least PHP 5.5.9. *You can check this by running `php -v`.*
- [x] I have ran `rm -rf bootstrap/cache/*`.

### Expected behaviour

*All phrases should be translated in Romanian when choosing the Romanian language.*

### Actual behaviour

*Romanian translations are missing for a lot of phrases.*

### Steps to reproduce

*Just switch the website's language to Romanian.*

**Comment by yoyosan** [comment]
I'm going to take care of this for milestone 2.4.

**Comment by jbrooksuk** [comment]
Remember to do this on https://translate.cachethq.io :)

I can add you as an official contributor to the project if you'd like.

**Comment by yoyosan** [comment]
> I can add you as an official contributor to the project if you'd like.

I don't see how it can hurt :smile:

**Comment by jbrooksuk** [comment]
You should be able to accept translations now.
