### ISSUE TITLE
Cachet Not Sending Email When Issue is Fixed

### ISSUE THREAD

**Issue by apssupport** [CachetHQ/Cachet#2071]
Good evening,

Not sure if it is just my setup or the way cachet currently behaves, but an email is only sent out automatically to subscribers when an incident is created, but no email is sent when an issue is fixed. Is this currently possible? If not, is it something in the pipeline?

Thanks,

Evangelos

**Comment by ConnorVG** [comment]
You're right, there is no email that is sent on resolution. This is something that should be added.

**Comment by apssupport** [comment]
Thank you Connor! Is this something easy to implement?

**Comment by ConnorVG** [comment]
It's pretty simple to add, yeah. The only difficult part is the view (for people like me anyway :laughing:).

I can write you something up and show you if you like? I'm not at my computer right now but I'm happy to when I am.

On 20 Aug 2016 14:08, apssupport <notifications@github.com> wrote:

Thank you Connor! Is this something easy to implement?

**Comment by apssupport** [comment]
Thank you so much! I would definitely be interested to look at what you come up with. Anything would be better than no email at all 😄 . Appreciate your help as well as the entire team and all involved with this great tool.

**Comment by ConnorVG** [comment]
Sorry, was at the shop. You'll want to do something similar to this: https://github.com/connorvg/Cachet/tree/incident-close-email

See here: https://github.com/ConnorVG/Cachet/commit/d5d0260101d44f6b364b9bc9fafb18b1ed61beb6

**Comment by apssupport** [comment]
Thank you and no apologies needed, I did not expect anything so quickly, especially on a weekend! 😄  What would be the best way to implement your code? Just create and or edit the existing files with your changes? Thank you again for making this happen so quickly!!

**Comment by ConnorVG** [comment]
It all depends honestly. I believe this sort of thing needs to be a core feature but that is up to the Cachet team (pinging @jbrooksuk, @GrahamCampbell and @joecohens).

What I can suggest is possibly putting them in yourself for now but, all-in-all, it's entirely up to you.

**Comment by apssupport** [comment]
I completely agree with you, I believe it should be a core feature as well as it is just as important to get notified when an incident is resolved. Hopefully the team can add it in as a feature if they like.

In the meantime, I will add this in myself and test it out. Thank you so much again and hope you have a good weekend! Will let you know how this works out.

**Comment by jbrooksuk** [comment]
This is something that will be coming in v3.0.0 where we're introducing Incident Updates. An incident technically doesn't get resolved currently.

**Comment by apssupport** [comment]
@jbrooksuk Thank you!

**Comment by gadago** [comment]
@jbrooksuk I think this should also be a feature for when maintenances are completed/fixed.

**Comment by jbrooksuk** [comment]
@gadago could you open a new issue for that please? :)

**Comment by karanp24** [comment]
Hi guys, waiting for this incident update email fix for long time. When 3.0.0 will be released?
Thanks

**Comment by jbrooksuk** [comment]
This is already in v2.4 which will become v3.0
