### ISSUE TITLE
Tidy up setup

### ISSUE THREAD

**Issue by jbrooksuk** [CachetHQ/Cachet#2080]
The setup needs a bit of TLC.
- [ ] Start using commands.
- [x] Fix mail validation.
- [x] Potentially improve error handling.

**Comment by jbrooksuk** [comment]
@joecohens do you have any ideas on how to redesign the setup to make it an easier flow.

**Comment by gamkiller77** [comment]
yah the setup is always asking for a username and password for outbound mail.  This dose not work with my setup as it open.  There should be a check box to have the username and password be greyed out when not needed.

**Comment by jbrooksuk** [comment]
I'd love to start using Vue in Cachet, so now would be a prime time to introduce it.

**Comment by jbrooksuk** [comment]
If someone fancies giving this a go, we'd love to help.

**Comment by jbrooksuk** [comment]
@gamkiller77 this shouldn't be an issue anymore :)
