### ISSUE TITLE
Metrics set up

### ISSUE THREAD

**Issue by fcpwiz** [CachetHQ/Cachet#2083]
Before submitting your issue, please make sure that you've checked the checkboxes below.

- [x] I am running the [latest release](https://github.com/CachetHQ/Cachet/releases/latest) version of Cachet.
- [x] I am running at least PHP 5.5.9. *You can check this by running `php -v`.*
- [x] I have ran `rm -rf bootstrap/cache/*`.

Hi,

I'm trying to set up a ping response time for metrics. I'm using Pingometer's guide: https://pingometer.groovehq.com/knowledge_base/topics/cachet. I managed to set it up for a component, but how can I connect it to the metric system for ping?

**Comment by jbrooksuk** [comment]
Pingometer doesn't deal with metrics (as far as I'm aware). You'll have to do this by integrating the API into your application/service yourself.
