### ISSUE TITLE
E-mail notifications don't properly populate URL to Cachet

### ISSUE THREAD

**Issue by djgalloway** [CachetHQ/Cachet#2085]
Before submitting your issue, please make sure that you've checked the checkboxes below.

- [X] I am running the [latest release](https://github.com/CachetHQ/Cachet/releases/latest) version of Cachet.
- [X] I am running at least PHP 5.5.9. *You can check this by running `php -v`.*
- [X] I have ran `rm -rf bootstrap/cache/*`.

### Expected behaviour

E-mail notifications contain links that accurately point back to Cachet instance.

### Actual behaviour

Buttons/links, such as "Manage your subscription" point to http://localhost/subscribe/manage/etc

**/etc/hosts**
```
127.0.1.1 status.my.fqdn.com status
127.0.0.1 localhost
```

Cachet is the only application running on the VM so if the `127.0.0.1` line can safely be changed, I'm guessing that'd solve the problem but I'm hesitant to change it in case anything else relies on being able to resolve localhost.

This seems like it could be an easy fix by using `APP_URL` in `.env` instead of trying to resolve localhost when building the e-mail.

**Comment by jbrooksuk** [comment]
Cachet should be using the `APP_URL` value in `.env`. Have you set yours?

**Comment by djgalloway** [comment]
Yep.  I actually just got another notification of a Component change and it used the public IP of the VM instead of 'localhost'

**Comment by jbrooksuk** [comment]
After changing the `.env` values you'll need to run:

```
php artisan cache:clear
php artisan config:cache
```

**Comment by djgalloway** [comment]
Ok. I took the app down, ran the commands you listed, brought the app back up, enabled a subscription so I'd get a notification and the IP address is still what came in the "Manage your subscription" button's URL.

**Comment by djgalloway** [comment]
Got 5 in a row with the IP address -- which works -- but you mentioned it _should be_ the FQDN?  Let me know what other info you need to debug.

**Comment by ConnorVG** [comment]
@djgalloway out of interest, could you check your corresponding environment's cached config file and see what the domain is set to?

EG: if you're in `staging` then the file should be `bootstrap/cachet/staging.php`.

**Comment by djgalloway** [comment]
@ConnorVG `app_domain` is actually set to the FQDN (including http://)

**Comment by ConnorVG** [comment]
OK, last important questions... What queue driver are you using and are you processing your queue in the same environment as you are hosting the website? If you're not using the `sync` queue driver, what are the arguments you're passing to the queue worker artisan command?

IE: if you're running the website in a VM, do you also run the queue worker within the VM?

**Comment by djgalloway** [comment]
`QUEUE_DRIVER=sync`

The site and application are all running on the same VM.  A small subset of components are updated by a remote host.  Does that answer your question?

**Comment by jbrooksuk** [comment]
I've been unable to find any reason this would be an issue.

Ping @CachetHQ/owners, have you guys experienced this at all, in any project?

**Comment by joecohens** [comment]
@djgalloway Can you try to set the trusted proxies to `*` https://github.com/CachetHQ/Cachet/blob/2.4/config/trustedproxy.php#L30 ?

**Comment by jbrooksuk** [comment]
@djgalloway what do the links look like on the main status page? We use the same `route` function in the emails as we do on the status page, so I'd imagine that all of your links are looking at `localhost`, which would suggest it's a setup issue, as the demo my dev instance and our StyleCI status page don't do this.

Could you share more about your setup to support@alt-three.com please.

I'm going to close this issue (as not to _clutter_ issue list), but we'll still continue to help resolve this issue with you.
