### ISSUE TITLE
Nothing Personal ! Just a doubt

### ISSUE THREAD

**Issue by leovarmak** [CachetHQ/Cachet#2087]
I really respect you people and there is no doubting that thing. Without you open sourcing this thing none of us would have enjoyed this as we are enjoying now. But is there a way I am remove The whole footer ? This includes
- Powered by Cachet
- RSS
- Atom 

If yes, how can I do it ?

**Comment by jbrooksuk** [comment]
You have two options:

1. Set some custom HTML code in the footer. This can be done in the dashboard. Go into settings. 
2. Turn off the "Show support for Cachet" checkbox in the dashboard. Obviously, we'd rather you keep that as it'd mean a lot to us 😀

You can't turn off the RSS and ATOM buttons though. You'll need to set some custom HTML for that.
