### ISSUE TITLE
Display only Blackout Dates

### ISSUE THREAD

**Issue by leovarmak** [CachetHQ/Cachet#2088]
Before submitting your issue, please make sure that you've checked the checkboxes below.

- [x] I am running the [latest release](https://github.com/CachetHQ/Cachet/releases/latest) version of Cachet.
- [x] I am running at least PHP 5.5.9. *You can check this by running `php -v`.*
- [x] I have ran `rm -rf bootstrap/cache/*`.

Hey !
I would like to only display the dates where incidents happened. How can I do this ?

**Comment by jbrooksuk** [comment]
Putting this into the v3.0.0 branch where we'll be refactoring a lot of incident stuff 😄

**Comment by leovarmak** [comment]
Cool :+1:
