### ISSUE TITLE
Don't Missuse The Return Annotation

### ISSUE THREAD

**Issue by GrahamCampbell** [cachethq/Cachet#209]
I've been cleaning up the repository classes, and noticed you've said things like `@returns Exception`. You should have used the `@throws \Exception` annotation there.

**Comment by GrahamCampbell** [comment]
All, please don't use `is_null` `=== null` is better performing. Micro-optimization. :)

**Comment by GrahamCampbell** [comment]
Also, is there an error in your code here?

```php
    public function count($key = null, $value = null)
    {
        if (is_null($key) || is_null($value)) {
            return $this->model->where($key, $value)->count();
        }

        return $this->model->count();
    }
```

Did you not mean to have the two statements the other way round?

```php
    public function count($key = null, $value = null)
    {
        if (is_null($key) || is_null($value)) {
            return $this->model->count();
        }

        return $this->model->where($key, $value)->count();
    }
```

**Comment by jbrooksuk** [comment]
1. Got it. That makes a lot more sense.
2. Okey dokey.
3. I'm not sure, I believe @Ehesp did that?

**Comment by GrahamCampbell** [comment]
Also, I don't think we should even use repositories there if we don't use them everywhere.

**Comment by jbrooksuk** [comment]
I think it was the plan to move everything to it, but it's just for the API for now - no particular reason why.

**Comment by GrahamCampbell** [comment]
There doesn't seem much point in them atm. Repositories are the most overused patern within the laravel community. Often they're simply not required.

**Comment by GrahamCampbell** [comment]
If only we had unit tests, we would know what the desired behaviour was...

**Comment by jbrooksuk** [comment]
Ok, we can pull them out then if it's better for us. I wonder if it was to do with Dingo? @Ehesp?

**Comment by GrahamCampbell** [comment]
Nah, it's nothing to do with dingo. I'll leave them in for now.

**Comment by GrahamCampbell** [comment]
I want to refactor without removing them. We can remove them afterwards if we still don't want them.

**Comment by GrahamCampbell** [comment]
Also, some of the phpdoc is incorrect. I'll try and work out what was really intended. Pull request coming soon(ish)...
