### ISSUE TITLE
Settings not being applied

### ISSUE THREAD

**Issue by mhayes14** [CachetHQ/Cachet#2094]
Before submitting your issue, please make sure that you've checked the checkboxes below.

- [x] I am running the [latest release](https://github.com/CachetHQ/Cachet/releases/latest) version of Cachet.
- [x] I am running at least PHP 5.5.9. *You can check this by running `php -v`.*
- [x] I have ran `rm -rf bootstrap/cache/*`.

### Expected behaviour

Changing the settings under 'Application Setup' is not reflecting in the application. I save the settings and the page reloads with the "Settings saved." message. I would expect the settings page to reflect the settings chosen and for these to be applied on the status page.

### Actual behaviour

The settings are not applied and the settings page does not reflect the changes, even after a further reload. Strangely, the 'settings' database table appears to be updated just fine. I have tried clearing the application cache too.

### Steps to reproduce

1. Settings -> Application Setup
2. Change settings

**Comment by GrahamCampbell** [comment]
Does your web server have write access to bootstrap/cachet?

**Comment by mhayes14** [comment]
No it did not have write access, now it does everything is working again. That was a ridiculously quick response, thank you very much. It must have been lost after I performed an upgrade a couple of days ago, I will keep this in mind in future. Thanks again.

**Comment by GrahamCampbell** [comment]
np :)
