### ISSUE TITLE
MailGun docs incorrect

### ISSUE THREAD

**Issue by mhayes14** [CachetHQ/Cachet#2095]
Hi

The [Cachet mail docs](https://docs.cachethq.io/docs/configuring-mail) specify environment variables `MAILGUN_DOMAIN` and  `MAILGUN_SECRET` for using MailGun.

However looking at https://github.com/CachetHQ/Cachet/blob/v2.3.10/config/services.php (and after being confused for a while!) it seems `MAIL_USERNAME` is used for the domain and `MAIL_PASSWORD` is used for the secret.

I haven't made a PR as I'm not sure if it's the config or the docs which is considered incorrect! (Though I guess it probably doesn't _really_ matter if one or the other is corrected)

Thanks,
Mike

**Comment by joecohens** [comment]
Hey! Thanks for reporting this issue, I've updated this part of the docs to Cachet 2.4 🍻 

/cc @jbrooksuk

**Comment by jbrooksuk** [comment]
Thanks @joecohens!

**Comment by KeiroD** [comment]
I was the one that originally wrote the doc for integrating Mailgun, so it's not too surprising that it's been slowly going out of date with all the changes of late.

Good to see it's updated now, however!
