### ISSUE TITLE
Subscriptions can be managed/removed by anyone

### ISSUE THREAD

**Issue by mhayes14** [CachetHQ/Cachet#2096]
Before submitting your issue, please make sure that you've checked the checkboxes below.

- [x] I am running the [latest release](https://github.com/CachetHQ/Cachet/releases/latest) version of Cachet.
- [x] I am running at least PHP 5.5.9. *You can check this by running `php -v`.*
- [x] I have ran `rm -rf bootstrap/cache/*`.

### Expected behaviour

If you try to subscribe with an email address which is already subscribed, there should either be an error message ("This email address has already been subscribed") or even better, an email sent out with a link for managing subscriptions.

### Actual behaviour

Anyone can type the email address for an existing subscription into the subscribe form and be sent onto a page which allows them to subscribe/unsubscribe from components for that email address, without first being verified.

The following success message is given after subscribing with an existing email address: "Awesome. Cannot subscribe <email> because they're already subscribed."

### Steps to reproduce

1. Visit `/subscribe`
2. Enter the email address of an existing subscriber
3. You're forwarded straight onto `/subscribe/manage/<key>`
4. Any subscription can be deselected and saved

On another note, it would be good if the initial subscription verification email contained a link to manage subscriptions, or you were forwarded to view/manage subscriptions after verifying your email address.

**Comment by jbrooksuk** [comment]
This is fixed in https://github.com/CachetHQ/Cachet/commit/838beac285deb5b1969f87ea18f6eaac2778080a and will be in v2.4.0 when it's released.
