### ISSUE TITLE
Log person that reported incident

### ISSUE THREAD

**Issue by jhamilton09** [CachetHQ/Cachet#2097]
### Expected behaviour

From the dashboard, I should be able to see which team member logged an incident so I can follow-up with them for more information.

### Actual behaviour

An incident exists, can be created\edited by anybody, I cannot find out whom created it.
_I agree that the user name should not be shown (or should be an option) on the public page but I think it would be beneficial to show it on the Dashboard with an incident's history._

### Steps to reproduce

_If your issue requires any specific steps to reproduce, please outline them here._
1. Log an incident.
2. Have your team members guess who created the incident. This gets more difficult with more team members.

**Comment by ConnorVG** [comment]
I agree, general auditing would is quite a fundamental feature that should be supported.

**Comment by jbrooksuk** [comment]
What about when we have an API and an incident was not created by a user? This is the reason we removed the `incidents.user_id` tracking in the past.

**Comment by ConnorVG** [comment]
Generic auditing with input sources. A user could be an input source, a consumer could be an input source, etc?

**Comment by jbrooksuk** [comment]
@ConnorVG did you ever plan to implement this one?

**Comment by jbrooksuk** [comment]
This is done.
