### ISSUE TITLE
http://cachethost.example.com/dashboard/components - ERR_EMPTY_RESPONSE for >200 Components

### ISSUE THREAD

**Issue by snowball2** [CachetHQ/Cachet#2099]
We have ~370 components in 7 component groups. When trying to view the components page dashboard/components the request eventually times out with empty response. I'm unsure of the threshold but the components view page works with 190 components.

Does Cachet have a maximum component level?

**Comment by jbrooksuk** [comment]
There is no upper-bound limit in Cachet. The issue here will be that your server is running out of memory.

Try increasing `memory_limit` in your `php.ini` file.

**Comment by ConnorVG** [comment]
I'm not sure >190 components should really be using so much memory. Is this something we need to look in to? That's not much in the grand scheme of things...

**Comment by jbrooksuk** [comment]
@ConnorVG I don't think we're doing anything amazing here, we're just listing them all. I'll assign to you :)

**Comment by jbrooksuk** [comment]
@snowball2 what DB are you using actually? I've got a feeling my first comment was misinformed. I imagine SQLite?

**Comment by snowball2** [comment]
Hi James,  using MySQL. First comment actually resolved the issue though; upping PHP memory_limit from 256M to 512M fixed the issue.

**Comment by ConnorVG** [comment]
@snowball2 have you got many incidents?

**Comment by snowball2** [comment]
Hi Connor, no - 6 incidents at the moment.

**Comment by jbrooksuk** [comment]
We'll investigate memory usage before the v2.4 release. 256M is quite low though, but I wouldn't have imagined it being like this. 

It could be related to your MySQL setup?
