### ISSUE TITLE
Sorting by status in component groups

### ISSUE THREAD

**Issue by snowball2** [CachetHQ/Cachet#2100]
Is it possible for one of the following 2 options to be added to the component group editor in addition to default collapsed options. Either of these options would improve presentation of groups with large numbers of components to prevent the user having to scroll through a large number of operational components to find the component with issues. Option 1 would be the preferable solution.
1. \- Stay Collapsed but show components with issues.      - keep component group collapsed but show components that are experiencing issues.
2. \- When expanded - sort by components with issues.     - allow components with issues to be shown at the top of the list

**Comment by ConnorVG** [comment]
It's a bit odd, I imagine a layout that is constantly changing would just be annoying to continually interpret?

**Comment by jbrooksuk** [comment]
> Stay Collapsed but show components with issues. - keep component group collapsed but show components that are experiencing issues.

This is physically impossible. A group can't be collapsed and uncollapsed. It's Schrödinger's group 😆 

> When expanded - sort by components with issues. - allow components with issues to be shown at the top of the list

Although this is possible, it defies the order in which the components may have been put into.

This needs more thought before we do anything :)

**Comment by snowball2** [comment]
Attached screenshot of what I mean (option 1)- The Servers component group contains 120 components with 1 component experiencing issues. To avoid the user having to scroll through the list of servers looking for the one with issues, I would have the problem server displayed while keeping the group collapsed.

![image](https://cloud.githubusercontent.com/assets/4521029/18431954/5ef6e6d6-78d7-11e6-8921-0b8d9feb6db2.png)

Option 2 would retain the component order but problem components would bubble to the top.

**Comment by billmn** [comment]
@jbrooksuk If a group contains a component that have an outage ... the group status icon must be green or red?

![schermata 2016-10-03 alle 18 37 20](https://cloud.githubusercontent.com/assets/779534/19045371/c08f2e04-8998-11e6-9bc4-7011fe5f6d1d.png)

**Comment by billmn** [comment]
If a group contains a component in outage status ... the group status icon must be red or green?

![schermata 2016-10-03 alle 18 37 20](https://cloud.githubusercontent.com/assets/779534/19045719/98a14420-899a-11e6-99fe-1aa6f2cbb7ce.png)

**Comment by jbrooksuk** [comment]
It might also be blue or yellow, right? We should show the most severe colour.

**Comment by billmn** [comment]
@jbrooksuk Totally agree ... I think could be useful order groups by "severe score" -> "manual order", thoughts?

**Comment by jbrooksuk** [comment]
`order` then `status`?

**Comment by billmn** [comment]
Status then Order.
I can give you some example in 5 minutes 😉

**Comment by jbrooksuk** [comment]
Please :)

**Comment by jbrooksuk** [comment]
Unless @billmn still fancies taking this one, I feel I'm going to close it. It's a bit confusing for people.
