### ISSUE TITLE
[Question] ETA on v3.0 ?

### ISSUE THREAD

**Issue by leovarmak** [CachetHQ/Cachet#2101]

**Comment by GrahamCampbell** [comment]
Ages, sorry. We still might rename 2.4 to 3.0 anyway, and the current 3.0 will become 4.0.

**Comment by GrahamCampbell** [comment]
I'd say at least 6 months.

**Comment by leovarmak** [comment]
Shit. Thats a lot of time. Anyways goodluck ! Rock it
