### ISSUE TITLE
v2.3.10 - Constantly redirected to /setup

### ISSUE THREAD

**Issue by cjsoftuk** [CachetHQ/Cachet#2102]
I've just installed cachet - and it'd be great..... if I could get past being redirected to /setup every time I try and view the page.

I've got as far as working out that the Config name "setting.app_name" isn't set on Line 33 of "app/Http/Middleware/ReadyForUse.php" - but I don't understand why.  It's there in the database..... but it's notably missing from bootstrap/cache/config.php though.....

Any pointers are thoroughly appreciated as I'm stumped now.

Thanks in advance.

**Comment by ConnorVG** [comment]
Try deleting all the `.php` files in the `bootstrap/cache` and `bootstrap/cachet` folders and report what happens, please :smile:

**Comment by cjsoftuk** [comment]
@ConnorVG - Thanks. All sorted.

You've now made me curious though, is there any reason why those folder both need to be writable by the user running the website.  It seems there are a lot of folders that cachet needs write access to, including some where people could dump executable PHP....

**Comment by ConnorVG** [comment]
No one can dump executable PHP in the `bootstrap/cache` nor the `bootstrap/cachet` folder - they're purely performance based files. Generated for optimising certain aspects of the application.

When it comes to anything else, such as `storage`, this is entirely dependant on the developer. The *only* possible way a user would be able to dump anything in that to have it ran is if the developer makes this a specific feature (for whatever reason). The general rule of that folder in Laravel is to have it's permissions set to `666`. This is `read + write` - not execute.

**Comment by cjsoftuk** [comment]
@ConnorVG - OK.  I'm just a paranoid sysadmin who likes to understand why something should be chmodded or chowned to the user that's running the code before doing as the instructions say.  My general rule is that no matter where the PHP files are on the system, if they've got write access from anyone other than the application maintainer and root without a valid explanation they don't get that permission.  Too many times have I had to clean up after somebody else's liberal chmod/chowning.....

**Comment by cjsoftuk** [comment]
Thanks for the help though - all up and running now.
