### ISSUE TITLE
Installation like Wordpress

### ISSUE THREAD

**Issue by svrooij** [CachetHQ/Cachet#2103]
Would it be possible to provide us with a zip file that we can unzip on a web server, input the database connection and just have a working version of cachet?
We like the way cachet looks and works!!! Only the installation is a bit of a hassle.

We would like to setup this status page on an external hoster where we don't have ssh access to.

(And to be completely honest, I don't get the entire command line php, why would you want to use that??)

**Comment by GrahamCampbell** [comment]
Cachet cannot be installed on such servers, sorry.

**Comment by GrahamCampbell** [comment]
Installation of cachet is already pretty easy. Just put it on the server, run 2 commands, and follow the web interface.
