### ISSUE TITLE
Mentioning Cachet on Backstroke's home page

### ISSUE THREAD

**Issue by 1egoman** [CachetHQ/Cachet#2105]
Hello!

I noticed that one of my projects, Backstroke (http://backstroke.us), is being used a lot with this repo. I'm not sure if many people are using Backstroke on their own forks or whether you've set up a hook on this repo, but from what I can tell it seems to be the latter. 

Anyway, if you are indeed using Backstroke, would you mind if I mention Cachet on Backstroke's website? Here's what it would look like:
<img width="760" alt="screen shot 2016-09-20 at 8 00 24 am" src="https://cloud.githubusercontent.com/assets/1704236/18669356/9f78c9e0-7f08-11e6-8402-a03b9f9749cf.png">

Thanks a lot,
Ryan

(Tagging @GrahamCampbell since I think he's a maintainer)

**Comment by yoyosan** [comment]
Hi! @jbrooksuk is also a maintainer.

**Comment by GrahamCampbell** [comment]
We all get notified anyway. Please contact us at support@alt-three.com regarding things that arn't code specific issues.

**Comment by 1egoman** [comment]
Ok, will do.

**Comment by GrahamCampbell** [comment]
Thanks :)
