### ISSUE TITLE
Installing Under a Directory?

### ISSUE THREAD

**Issue by Tokkemon** [CachetHQ/Cachet#2106]
I've installed Cachet on an internal development server, but I wish to have the application's requests all under a directory url like so:

Default setup: http://localhost/
Wanted setup: http://localhost/cachet

Is this possible with some clever apache workaround? Using CentOS 7 and MySQL if that matters.

**Comment by jbrooksuk** [comment]
Cachet shouldn't be installed under a sub-directory. You need to install at a sub-domain or root domain level.

**Comment by GrahamCampbell** [comment]
Yeh, that's possible. Closing this since it's not a big report. Feel free to discuss on forums or research this. We also offer an install service. Contact support@alt-three.com.

**Comment by Tokkemon** [comment]
Where's the link to the forums? I can't find it.

> Cachet shouldn't be installed under a sub-directory. You need to install at a sub-domain or root domain level.

I don't understand *why* other than it simply hasn't been implemented yet. If so, you should note that in the documentation. It's kind of a fundamental issue, though. I was very surprised it hasn't been taken care of.
