### ISSUE TITLE
Support for notifications

### ISSUE THREAD

**Issue by mm-manageit** [CachetHQ/Cachet#2107]
We currently use StatusPages.io and our users overwhelmingly utilize the SMS notifications over the email (i.e..  5392 SMS, 297 email). This also comes into major play if services you are reporting on include email servers(i.e.. Exchange, Office365 etc...), as if they are down subscribers will not get notifications. 

I recommend Twilio for this as it is dirt cheap, and extremely easy to integrate with, just about anything.

**Comment by ConnorVG** [comment]
Thanks for the input, SMS notifications would be pretty swish. If we were to add SMS support, we wouldn't limit it to one service (like Twilio) though. This would be pretty easy to add with Laravel 5.3's notification system :wink:

**Comment by mm-manageit** [comment]
The most common options are Twilio, Nexmo, and Plivo. I am not familiar with the programming interfaces of Nexmo and Plivo, so not sure of their level of difficulty for integration.

**Comment by mm-manageit** [comment]
Looking at the Doc's at the Larevel Notifications - SMS, It appears out of the box it supports Nexmo after getting the Nexmo library with composer.

**Comment by jbrooksuk** [comment]
This is something we'll do once we've upgraded to Laravel 5.3 :)

**Comment by ericvhileman** [comment]
SMS is killing feature!  Our customers all want SMS notifications more than email :)  We're a web hosting provider.  Most of the time when we have a problem and need to notify a customer email won't work because the service affected has killed email.  But even if email isn't killed, SMS is real-time and the best way to notify someone of an important problem.  In today's world, even 5 minutes of downtime of an online service is a critical problem that requires SMS notification.  You'll also likely see adoption from the status.io users too. I really hope this is released soon cause it's a killer!

**Comment by giubueno** [comment]
Is someone implementing it? I've created a handler and I will use a similar structure used to send e-mails to send the SMS. I am completelly new to Laravel. Some suggestions and advices would be great.

**Comment by CosmicPuppy** [comment]
Just wanted to chirp in that perhaps integration with a **_REST-API based notification service_** might be a suitable SMS alternative in some situations; or, at worst, an _additional_ feature request.

**Examples:**
- Pushover: https://pushover.net/
- Pushbullet
- Prometheus Alert Manager: https://prometheus.io/docs/alerting/alertmanager/

**Comment by jbrooksuk** [comment]
I'm working on this :+1:

**Comment by jbrooksuk** [comment]
Since we're using Laravel 5.3, we're now making use of the new Notification system which makes these really simple to start integrating :)

**Comment by mm-manageit** [comment]
If I can be of assistance, let me know.

**Comment by mm-manageit** [comment]
One thing I would recommend, especially if we can integrate SMS reply handling, as one of the first SMS messages to a new SMS subscriber. Send a message like the following: "Reply with your email to be able to manage Email and SMS subscritions together", then you can add the phone number to the profile for the email if it already exists.
