### ISSUE TITLE
LDAP Authentication

### ISSUE THREAD

**Issue by hExPY** [CachetHQ/Cachet#2108]
Hey guys,

i've been wondering if you would ever implement a LDAP Authentication.

Kind regards,

**Comment by ConnorVG** [comment]
It's something that would certainly be of great use to Cachet. Although... it's a pretty big job.

**Comment by jabarihunt** [comment]
I'll take this on this week.  Any specifics before I start?  I'll add support for multiple LDAP servers (can either be an array of servers, or a set amount...4 maybe?)

**Comment by jbrooksuk** [comment]
We have nothing in mind, so please make a start and we'll advise through your PR.

**Comment by dstuecken** [comment]
I would support you implementing this, did you start already?

**Comment by jbrooksuk** [comment]
We'd accept a PR for this, but we don't have the time to allocate to it I'm afraid.

**Comment by amolsh** [comment]
Is this feature available now? In which release?

**Comment by jbrooksuk** [comment]
We don't support LDAP I'm afraid @amolsh.

**Comment by stephenyeargin** [comment]
So, I think this or #213 should remain open and tagged as a `future` road-map item instead of closing the :octocat: Issue. That will communicate to others that they could potentially pick it up. Closing the issue signals to most folks that it was either invalid or completed -- this falls somewhere in the middle (could be worked on, but not a small task). :heart:

**Comment by jbrooksuk** [comment]
Tagged as `up-for-grabs` :)

**Comment by stephenyeargin** [comment]
Excellent! I figure @jabarihunt probably got wrapped up in other things. Here is a [CodeIgniter based app](https://github.com/bbalet/jorani) that leverages some LDAP components for authentication that could likely serve as a starting point. I'd propose:

- [ ] Add a basic LDAP component to the Docker install with some default users ([this one](https://github.com/osixia/docker-openldap) looks scriptable)
- [ ] Select a composer package work with LDAP ([Symfony](https://packagist.org/packages/symfony/ldap) has one)
- [ ] Research intercepting the process check against LDAP if configured before falling back to the database

Some things to consider:

- Users should likely be configured _first_ in Cachet before allowing access.
- Alternatively, the BaseDN would need to be configured to only permit certain users to access (user record would be created on new sign in via LDAP).
- If the second scenario is used, promotion to admin would need to be limited to a configured database user.
- An LDAP user should not be permitted to set a password, perhaps not able to update their first name or last name.

**Comment by jbrooksuk** [comment]
LDAP adds a lot of complexity so this needs to be handled correctly the first time it's implemented. We can absolutely work together on a PR for this.

**Comment by EmilioD** [comment]
just a thought... would setting up HTTP auth be easier/simpler? That way apache/nginx could be configured to handle auth using whatever mechanism is prefered and Cachet would only need to be able to accept remote_user. If ldap was needed, then the web server could be configured for that.. or saml2 or <insert webserver auth mechanism here>

**Comment by ConnorVG** [comment]
That sounds like a not-so-pretty work around @EmilioD; I feel like this, as a feature, is something that should be implemented as neatly as possible – full integration. Not just a bypass of sorts.

**Comment by EmilioD** [comment]
I was more thinking that way its more flexible than just ldap. At least in my environment we dont care where/which authentication source we use so long as its once of the options we have centralized. This would allow the devs to focus on the app and allow for admins to focus on auth / config.

**Comment by ConnorVG** [comment]
Maybe it would be more suited as an option, rather than a replacement.

**Comment by nixmomo** [comment]
i would recommend that no LDAP Support would be enabled... use a radius support instead.
You can use radius with all backends and it's a much easier solution

**Comment by jbrooksuk** [comment]
Radius?

**Comment by nixmomo** [comment]
http://freeradius.org/
Yes... it's good with Server where you can configure multiple backends... so cachet need one code implementation to radius only and all can configure his radius instance for his needs.... 
best Auth solution

**Comment by segfly** [comment]
No Radius please! :slightly_smiling_face: 
LDAP is very common need and I don't think anyone wants to setup a radius server just to use Cachet with auth.

My suggestion: accept preauth headers. Then you can have a reverse proxy handle the auth, whether that's LDAP, Radius, or some single-sign-on solution. The proxy would just pass in the username as an HTTP header and Cachet would trust the request was preauthenticated.

**Comment by camous** [comment]
fully supporting @segfly suggestion. it would allows easy integration with Azure: https://docs.microsoft.com/en-us/azure/app-service/app-service-authentication-overview

**Comment by ConnorVG** [comment]
@segfly I'm unsure about just 'trusting' the request – that sounds horrible.

That said, I also agree with not using Radius. Seems like an extra step for no real reason.

**Comment by EmilioD** [comment]
I think @segfly is recommending the right path forward. Let the web server (what I was recommending) or a reverse proxy take care of the authentication. This way if someone wants radius then they can setup apache/nginx to use radius, if they want ldap/shibboleth/oauth/etc then they can set that up with the web server, independently of the cachet web app.

**Comment by segfly** [comment]
@ConnorVG
> I'm unsure about just 'trusting' the request – that sounds horrible.

This approach is not unheard of, in fact I wish more applications did this and embraced separation of concerns. The security aspect is taken care of if you just ensure no other client can reach Cachet other than the reverse proxy - trivial in a container deployment. The reverse proxy needs to sanitize input and ensure no one is trying to inject the trusted auth header e.g. `CACHET_PREAUTH_USER`.

I'll see if I can get a PR created for this in the next 1-2 weeks if the idea itself is something that will be approved. @jbrooksuk?

**Comment by EmilioD** [comment]
@segfly  I am not very familiar with the authentication stack in laravel (I am a lot more old school php), but if someone can point me to where the current user authentication library/module is coming from, I should be able to get remote_user auth working fairly easily. 

@jbrooksuk  any concerns with us making remote_user authentication an option? That way its up to an admin to configure whatever external authentication mechanism they would like, or use the built in.

**Comment by segfly** [comment]
@EmilioD To be honest, I don't know either. I have someone on my team who is experienced in PHP, but not necessarily laravel. So we'd be starting from the same place.

**Comment by EmilioD** [comment]
@segfly I have a few folks here as well who have done work using Laravel, Ill ping them. 
In the meantime it appears as though Laravel already has the capabilities: https://laravel.com/docs/5.4/authentication#authenticating-users

**Comment by jbrooksuk** [comment]
I think this needs proper thought before we implement any changes to the user system.

**Comment by utscnetworking** [comment]
There multiple levels of LDAP integration. I would suggest to implement with a Step by Step approach. The basic is LDAP authentication, e.g. the username is in the Cachet database and the password authentication routed to the backend LDAP server(s). This should be a straight-forward enhancement. Then it will be the full integration, such as LDAP group integration, user account auto provisions and attribute mappings, the whole nine yards.

**Comment by wesleyhuang** [comment]
There are multiple levels of integrations for LDAP integration. I would suggest to implement it with a Step by Step approach. The basic is LDAP authentication, e.g. the username is in the Cachet database and the password authentication routed to the backend LDAP server(s). This should address issues for many users and should be a straight-forward enhancement. Then it will be the full integration, such as LDAP group integration, user account auto provisions and attribute mappings, the whole nine yards.

**Comment by jbrooksuk** [comment]
I'd like to see a PR with this :)

**Comment by hscheffers** [comment]
My 2c: Groupbased authentication against LDAP/AD would be very nice. Ideally, users don't need to be known to cachet, and user maintenance would be lot easier for the admins.

**Comment by joaquin386** [comment]
Following this one as it would be an amazing new feature.

**Comment by jbrooksuk** [comment]
I wonder if we should create a new issue which is just one SSO issue? That'd make this and https://github.com/CachetHQ/Cachet/issues/2930 one issue.

**Comment by jbrooksuk** [comment]
Also, would we be better with LDAP vs AD vs oAuth?

**Comment by MarPiRK** [comment]
LDAP is so much different in terms of architecture and configuration complexity than SAML or OIDC that I don't think that merging issues is good idea.
AD is implementation of LDAP, so it's managed in the same way with exception for configuration. OAuth2, OpenID Connect in particular is based on much different authentication philosophy.

**Comment by jbrooksuk** [comment]
Ah okay, that clears it up. I've not got much experience past oAuth and a bit of AD (through Azure).

**Comment by benyanke** [comment]
Once we get to a point where we plan to add this to our backend services, I can write an LDAP patch.

A few comments from a dev who has implemented LDAP on many systems and custom apps (and also maintains an ldap server ([glauth/glauth](https://github.com/glauth/glauth)):

1) SAML and LDAP are very different on the backend despite a similar frontend. They should be separate.
2) Everyone uses LDAP differently - build as flexible as possible. Use sane defaults, but allow any attribute to be specified by an arbitrary LDAP query so that an admin can select any set of users for any role/field/permission/attribute.
3) If implemented properly, AD support is a given if you implement LDAP. Try to avoid anything AD specific, instead implement basic LDAP and leverage AD via that.
4) Please, no radius.

**Comment by willwh** [comment]
How about an approach like [this?](https://github.com/jotaelesalinas/laravel-simple-ldap-auth), which uses https://github.com/Adldap2/Adldap2-Laravel

**Comment by benyanke** [comment]
I use Adldap2/Adldap2-Laravel on another project - it's quite good.

**Comment by redzioch** [comment]
Any update on this...? It's been years...

**Comment by fruetalo** [comment]
Any news? This issue started in 2016.

**Comment by jbrooksuk** [comment]
Thank you for your input on Cachet 2.x. We are shifting our attention and resources to Cachet 3.x and will no longer be supporting the 2.x version. If your feedback or issue is relevant to the 3.x series, we encourage you to engage with the new branch.

For more information on the Cachet rebuild and our plans for 3.x, you can read the announcement [here](https://github.com/CachetHQ/Cachet/discussions/4342).

We appreciate your understanding and look forward to your contributions to the new version.
