### ISSUE TITLE
Support for Subscriptions to Individual Groups/Components

### ISSUE THREAD

**Issue by mm-manageit** [CachetHQ/Cachet#2109]
Supporting the ability to subscribe to individual Groups/Components would allow subscribers to choose which items they want to be notified about in cases where the status page contains several groups that may not affect the user. 

In theory would only require changing the Subscribe form to include: (Using the Demo Groups)
Subscribe To:
All []
Websites []
Alt Three []
Other Components []

Then changing the Send Notifications functions to include a WHERE Subscribed to Group = 1

**Comment by jbrooksuk** [comment]
This is done in v2.3. At least, you can subscribe to individual components.

**Comment by mm-manageit** [comment]
Oh ok, hadn't seen that yet, thanks.

**Comment by jbrooksuk** [comment]
No problem :)

One thing we don't yet have is the ability to subscribe to a group and any new components added. That'll come eventually :)
