### ISSUE TITLE
Component Status update

### ISSUE THREAD

**Issue by karaktaka** [CachetHQ/Cachet#2113]
I'm not sure if this is a bug or some kind of feature, but is it intended that I receive an email every time the status of a component gets updated even if the status don't get changed?
This also occurs if the component get's changed by itself, eg I change the description of a component.

As an example, I'm using a script to check the status of a service which updates it every 5 minutes.
I could change it, but why should I be notified if there is no actual incident?

**Comment by fdhex** [comment]
This is fixed in 2.4, but introduced another bug which can be quickfixed by implementing this PR https://github.com/CachetHQ/Cachet/pull/2084 on your own branch.

**Comment by jbrooksuk** [comment]
This is now fixed on 2.4.
