### ISSUE TITLE
Setup 404 not found

### ISSUE THREAD

**Issue by pork94** [CachetHQ/Cachet#2114]
I installed Cachet v2.3.9 on Ubuntu 16.04 with PHP 7 and Apache installed. After successful installation, I ended up with the web browser pointing to /setup with 404 not found.

**Comment by GrahamCampbell** [comment]
Sounds like your apache config is not correct. Closing since our issues are for bugs in the software rather than support. You can contact us at support@alt-three.com for paid support if you want.
