### ISSUE TITLE
403 error after upgrade

### ISSUE THREAD

**Issue by Bananenbaas** [CachetHQ/Cachet#2116]
Hi, 

I've upgraded cachet using git. Now I get an 403 error page. 
This what my log tells me:

`[Wed Sep 28 17:23:01.740003 2016] [fcgid:warn] [pid 27777] [client ....:59203] mod_fcgid: stderr: PHP Warning:  require(/var/www/vhosts/.../Cachet/app/Http/helpers.php): failed to open stream: No such file or directory in /var/www/vhosts/.../Cachet/vendor/composer/autoload_real.php on line 55
[Wed Sep 28 17:23:01.975420 2016] [fcgid:warn] [pid 27777] [client ....:59203] mod_fcgid: stderr: PHP Fatal error:  require(): Failed opening required '/var/www/vhosts/.../Cachet/app/Http/helpers.php' (include_path='.:/opt/plesk/php/7.0/share/pear') in /var/www/vhosts/.../Cachet/vendor/composer/autoload_real.php on line 55`

**Comment by GrahamCampbell** [comment]
Did you run composer install again?

**Comment by Bananenbaas** [comment]
Do you mean? $ composer install --no-dev -o --no-scripts

Yes I did, after that I ran: $ php artisan app:update

**Comment by jbrooksuk** [comment]
Can you run `rm -rf bootstrap/cache/*` and then try again please?

**Comment by Bananenbaas** [comment]
@jbrooksuk I've done that but still the same result

**Comment by jbrooksuk** [comment]
What version are you running?

**Comment by Bananenbaas** [comment]
I did an upgrade from 2.0.1RC1 to the latest, v2.3.9 I believe?

**Comment by Bananenbaas** [comment]
Of course I was to busy doing other things that I failed to notice it was an 503 error... 

But using $ php artisan up 
fixed it :)

**Comment by jbrooksuk** [comment]
Ah-ha!

**Comment by ConnorVG** [comment]
iamateapot
