### ISSUE TITLE
Duplicate username account creation generates 500 Internal Server Error

### ISSUE THREAD

**Issue by MichaelJohnson90** [CachetHQ/Cachet#2118]
If the username "admin" exists as a user, and you attempt to add another "admin" user. Instead of saying the user account already exists, Postgres will spit out an error; 

postgres_1  | ERROR:  duplicate key value violates unique constraint "users_username_unique"
postgres_1  | DETAIL:  Key (username)=(admin) already exists.
postgres_1  | STATEMENT:  insert into "users" ("username", "password", "email", "level", "api_key", "updated_at", "created_at") values ($1, $2, $3, $4, $5, $6, $7) returning "id"
postgres_1  | ERROR:  current transaction is aborted, commands ignored until end of transaction block
postgres_1  | STATEMENT:  DEALLOCATE pdo_stmt_00000004

And you receive an Internal 500 error in the webpage.

**Comment by ConnorVG** [comment]
https://github.com/CachetHQ/Cachet/blob/2.4/app/Bus/Commands/User/SignupUserCommand.php#L50

Why does this not check for `unique`? @jbrooksuk :joy:

**Comment by Luciam91** [comment]
@ConnorVG the Command shouldn't care whether it's unique, the data model here: https://github.com/CachetHQ/Cachet/blob/2.4/app/Models/User.php should manage that :)

**Comment by ConnorVG** [comment]
@Luciam91 you know what I mean :facepunch:

**Comment by GrahamCampbell** [comment]
The command should catch the model exception and throw it's own "domain exception".

**Comment by Luciam91** [comment]
Done correctly the data passed into the command should be validated before it becomes a Command object, no Command should be emitted unless it's in an acceptable state :)
