### ISSUE TITLE
Bad Request - Error 400 After the first login

### ISSUE THREAD

**Issue by brunohcunha** [CachetHQ/Cachet#2121]
Hello.

After making all installation and several tests for use of CachetHQ I came across the following problem.
When I finished the setup and I was redirected to the dashboard, I get the following error message:

`{"errors":[{"id":"4c1c1870-78f8-446f-9682-9529480ff166","status":400,"title":"Bad Request","detail":"The request cannot be fulfilled due to bad syntax.","meta":{"details":["The username has already been taken.","The email has already been taken."]}}]}`

The initial page and the page login into dashboard is working fine.

![sem titulo](https://cloud.githubusercontent.com/assets/14180022/19009036/5cc33ebe-8746-11e6-950e-af17d01e5cca.png)

Logs: http://pastebin.com/gXtZq7Z1

**Comment by jbrooksuk** [comment]
I've reverted the change that I made and will write a better fix for this.

**Comment by brunohcunha** [comment]
I'm waiting for the solution but it seems that will not be answered soon.
Do you have any prediction?

**Comment by jbrooksuk** [comment]
@brunohcunha sorry for the delay in the fix here. It might be better to reset Cachet and see what happens then?

**Comment by brunohcunha** [comment]
So I've tried to reinstall 2 times and always results in the same error.

**Comment by jbrooksuk** [comment]
All of `./bootstrap/` is writable, right?

**Comment by ConnorVG** [comment]
@brunohcunha are you using a fresh database? If not, could you please try installing into a fresh database and report the results?
