### ISSUE TITLE
Add history feature

### ISSUE THREAD

**Issue by lnxslck** [CachetHQ/Cachet#2126]
Is it possible to have a history feature? Something like being able to se 2 entries for the same incident, one for when the incident was created and another for when the incident was solved.

Apache is UP. Incident solved at (sometime + x )

Apache is Down. Incident created at (sometime)

This would allow us to see exactly when incidents happened, and were fixed, how long it took the incident to be fixed (important for customers), etc.

**Comment by jbrooksuk** [comment]
This will be done along with https://github.com/CachetHQ/Cachet/issues/1176 :)

**Comment by jbrooksuk** [comment]
This is now done in v2.4

**Comment by lnxslck** [comment]
Awesome!


Às 13:23 de 07-10-2016, James Brooks escreveu:
