### ISSUE TITLE
LDAP Auth

### ISSUE THREAD

**Issue by jbrooksuk** [cachethq/Cachet#213]
A very cool feature to have would be to support LDAP authorisation and AD passwords.

**Comment by sammcj** [comment]
+1 for this, I'd certainly like to see this.

**Comment by tomferreira** [comment]
+1

**Comment by jbrooksuk** [comment]
Once #196 is in, we can look at extending it with LDAP.

**Comment by lelutin** [comment]
+1
with an LDAP library it should be really easy to implement.

**Comment by jbrooksuk** [comment]
This isn't something we'll likely be supporting.

**Comment by helhindi** [comment]
@jbrooksuk - Thanks for a cracking tool :)
I did wonder if 'LDAP auth' was ever revisited or considered (for a future release)?
Cheers James/Team

**Comment by anandchida** [comment]
@jbrooksuk  +1 if LDAP support can be added.  This may be important for adoption among enterprises.
