### ISSUE TITLE
Positioning of Prompt When Trying to Delete an Incident from Dashboard

### ISSUE THREAD

**Issue by TheoBearman** [CachetHQ/Cachet#2145]
The confirmation prompt for deleting an incident from the dashboard (as a logged-in admin) seems to be appearing off the left hand side of the dashboard screen when the `Delete` button is clicked.

Please confirm and fix if required.

**Comment by jbrooksuk** [comment]
Can you screenshot?

**Comment by TheoBearman** [comment]
Having clicked delete:

<img width="944" alt="3" src="https://cloud.githubusercontent.com/assets/6546590/19191817/f2eee140-8c9b-11e6-8263-586cbbdeda42.PNG">
<img width="943" alt="2" src="https://cloud.githubusercontent.com/assets/6546590/19191818/f2f6ccca-8c9b-11e6-984e-9f8048c16d96.PNG">

**Comment by TheoBearman** [comment]
Cheers @billmn!
