### ISSUE TITLE
Index of / issue

### ISSUE THREAD

**Issue by jorcco** [CachetHQ/Cachet#2148]
Hi,
I followed the installation instructions for Cachet, but on the browser I get the following screen:
![image](https://cloud.githubusercontent.com/assets/11443496/19193566/8a0ffd6c-8c78-11e6-944b-ad41fe2ef74f.png)

Cachet V2.3.9
Php 5.6
Apache 2.4 
OS: RHEL 6.7
Mysqldb
Any idea what I might be missing?

**Comment by GrahamCampbell** [comment]
Looks like the htaccess config is not being read correctly.
