### ISSUE TITLE
Scheduled maintenance names a random component in notification email

### ISSUE THREAD

**Issue by jhamilton09** [CachetHQ/Cachet#2153]
Before submitting your issue, please make sure that you've checked the checkboxes below.

[ X ] I am running the latest release version of Cachet.
[ X ] I am running at least PHP 5.5.9. You can check this by running php -v.
[ X ] I have ran rm -rf bootstrap/cache/*.
[ X ] I have searched to see if this issue was previously logged.

What version of Cachet? 2.3.9
What database driver? MySQL? Postgres? SQLite? MySQL
What version of PHP? 7.0.3

**Expected behaviour**

Scheduled maintenance email notification would not indicate an unrelated component.

**Actual behaviour**

Scheduled maintenance does not choose a component. However, the notification email includes a seemingly random component in the body.

**Steps to reproduce**

If your issue requires any specific steps to reproduce, please outline them here.

Create a few components.
Subscribe for notifications.
Create a scheduled maintenance event.
Receive email and see top of the body (first row of the table under the h1 title):
"Scheduled (*random component*)"
[message]
[scheduled time]

I have also seen this apply to notifications of other incidents where you can select a component but the email specifies a different component. I have not tested enough to find a pattern.

**Comment by jbrooksuk** [comment]
I'm tempted to rebase https://github.com/CachetHQ/Cachet/commit/bab4f25045ded07b6a45bee0361519925074ef21 on to `2.4` so that we can get better usage from scheduled maintenance.

Regardless, I'll take a look at this now.

**Comment by jbrooksuk** [comment]
Wait, how are you sending components in the maintenance email? Although the email does allow for it (I don't remember why), we don't actually have the functionality to assign components to scheduled maintenance, unless you're running from another development version (perhaps the commit above?)

![https://cldup.com/hawfzAjG7n.png]()

This is what the scheduled email looks like. Before we implement the commit I linked, I'm going to remove any code from the current maintenance email that refers to components.

**Comment by jhamilton09** [comment]
I do not get to pick the component for the maintenance but the notification was still including one. It would be exactly as your email shows but after Scheduled ([Component Name]). Thanks for looking into it!
