### ISSUE TITLE
Avoid manual setup flow

### ISSUE THREAD

**Issue by trickleup** [CachetHQ/Cachet#2156]
Hi, 

What is the best practice to avoiding the manual setup flow, when first using the app? I'm provisioning cachet to a machine with scripts, and would like it to be accessible immediately.

I've tried to insert user + settings in the database, but I still get redirected to `/setup` when I first hit the cachet url. 

Ideas?

**Comment by jbrooksuk** [comment]
That's because you're missing settings. You need to set the `app_name` value in the `settings` table.

I do want to introduce a command that can do this, but the issue has always been the user data.

**Comment by trickleup** [comment]
Thanks,

However, I'm running these scripts in the sqlite database (which includes app_name), and I still get redirected to the setup page after a fresh install:

```
INSERT OR REPLACE INTO "settings" VALUES(1,"app_name","Some name","2016-10-07 20:41:23","2016-10-07 20:41:23");
INSERT OR REPLACE INTO "settings" VALUES(2,"app_domain","some_url","2016-10-07 20:41:23","2016-10-07 20:41:23");
INSERT OR REPLACE INTO "settings" VALUES(3,"app_timezone","America/Los_Angeles","2016-10-07 20:41:23","2016-10-07 20:41:23");
INSERT OR REPLACE INTO "settings" VALUES(4,"app_locale","en","2016-10-07 20:41:23","2016-10-07 20:41:23");
INSERT OR REPLACE INTO "settings" VALUES(5,"show_support","1","2016-10-07 20:41:23","2016-10-07 20:41:23");
INSERT OR REPLACE INTO "settings" VALUES(6,"app_incident_days","7","2016-10-07 20:41:23","2016-10-07 20:41:23");
```

I also add a user, with a pre-defined token that I use to hit the api. Is there something that is not right here?

**Comment by trickleup** [comment]
I should mention that I use `v2.3.10` version.

**Comment by jbrooksuk** [comment]
You may then want to clear the config cache.

**Comment by trickleup** [comment]
Thank you for your help. It turns out the issue was the app key - it was being regenerated by the install script every time, which caused the landing page to redirect to /setup every time.

**Comment by jbrooksuk** [comment]
Ah!
