### ISSUE TITLE
Remove All "Auth" Calls From The Views

### ISSUE THREAD

**Issue by GrahamCampbell** [cachethq/Cachet#216]
All this stuff needs to be moved to the controller.

**Comment by joecohens** [comment]
How would you like to do this, I use a helper but I saw you don't like too much. This is what I use for Laravel 5 https://gist.github.com/joecohens/6209b438695bcfac58c4

**Comment by GrahamCampbell** [comment]
I recommend not using a helper in the views either. The views should not know about any authentication logic. They should only be displaying data.

**Comment by GrahamCampbell** [comment]
You know how we have transformers and repositories, and then really "skinny" api controllers. That's the same deal we should have with the html presentation too.

**Comment by joecohens** [comment]
I would love to see it :)

**Comment by kfrankperson** [comment]
@joecohens Same here !!!

**Comment by jbrooksuk** [comment]
@GrahamCampbell do you have examples of this? I'd love to know how you would do this.
