### ISSUE TITLE
Root Cause Analyses

### ISSUE THREAD

**Issue by jbrooksuk** [CachetHQ/Cachet#2162]
Sometimes an incident may cause severe outages which need more explanation that a simple update. A post mortem would be pinned to the status page (where the stickied incidents are).

Post mortems would also be given their own canonical URLs and can be linked to an incident. The single post mortem page would, if linked to an incident, show the timeline.

**Comment by brianjking** [comment]
Awesome, thanks @jbrooksuk. This will be a great addition. Can't wait to see it in Cachet.

**Comment by ConnorVG** [comment]
Grim name, though.

**Comment by adammatthews** [comment]
RCA (Root Cause Analysis) is a more common term for this.

**Comment by jbrooksuk** [comment]
Updated.

**Comment by jbrooksuk** [comment]
Still looking forward to getting this in once we have the new design in place, so that we have the right place to put it.
