### ISSUE TITLE
Ability to search (find) incidents

### ISSUE THREAD

**Issue by mefiblogger** [CachetHQ/Cachet#2165]
Hello,

First of all: we have started using Cachet a few months ago and we really like it, thanks for the great effort building this software. :)

There is one feature that I couldn't really find in our latest instance and as I looked in feature request: the ability to search in incidents. A simple keyword search would do the trick, maybe an option to filter results between dates.

Is this a feature which I couldn't find and if it is not, is it possible in the near future?

Thanks for reading this,
Mefi

**Comment by ConnorVG** [comment]
Hey @mefiblogger, do you mean searching the API, dashboard or front of the site? :smile:

**Comment by nixmomo** [comment]
Search in Dashboard and Frontpage would be great. API is easy to fetch all and grap your Keywords...

**Comment by mefiblogger** [comment]
Hi @ConnorVG, thx for the response! Frontend and/or dashboard search would be really cool. :)

**Comment by jbrooksuk** [comment]
Thank you for your input on Cachet 2.x. We are shifting our attention and resources to Cachet 3.x and will no longer be supporting the 2.x version. If your feedback or issue is relevant to the 3.x series, we encourage you to engage with the new branch.

For more information on the Cachet rebuild and our plans for 3.x, you can read the announcement [here](https://github.com/CachetHQ/Cachet/discussions/4342).

We appreciate your understanding and look forward to your contributions to the new version.
