### ISSUE TITLE
Problem with API - Add Subscriber - Version 2.3.10

### ISSUE THREAD

**Issue by tmatthaeus** [CachetHQ/Cachet#2168]
I have a problem with the API. I am trying to subscribe an email via POST over the API. But the component value is ignored…

~ » http POST http://URL/api/v1/subscribers X-Cachet-Token:mZPZSs53qYNhWTLJyb0H email=duh23fosd@fdso24uhsfd.foo verify=true components:='[1]' tmatthaeus@tobias
HTTP/1.1 200 OK
Cache-Control: no-cache
Connection: Keep-Alive
Content-Length: 235
Content-Type: application/json
Date: Tue, 11 Oct 2016 10:30:22 GMT
Keep-Alive: timeout=5, max=100
Server: Apache/2.4.10 (Debian)

{
"data": {
"created_at": "2016-10-11 12:30:22",
"email": "duh23fosd@fdso24uhsfd.foo",
"id": 24,
"updated_at": "2016-10-11 12:30:22",
"verified_at": "Dienstag 11th Oktober 2016 12:30:22",
"verify_code": "JPQA6TNeDKSYeNEEKYunN1qdzc7ESchIX50fETaPdv"
}
}

mysql> select * from components where id = 1;
+----+--------+-------------+------+--------+-------+----------+---------+---------------------+---------------------+------------+
| id | name | description | link | status | order | group_id | enabled | created_at | updated_at | deleted_at |
+----+--------+-------------+------+--------+-------+----------+---------+---------------------+---------------------+------------+
| 1 | Bremen | | | 1 | 0 | 1 | 1 | 2016-10-10 13:14:50 | 2016-10-10 13:16:09 | NULL |
+----+--------+-------------+------+--------+-------+----------+---------+---------------------+---------------------+------------+

Do you have any hint for me? I am using version 2.3.10

**Comment by ConnorVG** [comment]
Hey @tmatthaeus, we've received your support request and will deal with it there. Thank you! :smile:
