### ISSUE TITLE
Maintenance informations - Line breaks ignored

### ISSUE THREAD

**Issue by tmatthaeus** [CachetHQ/Cachet#2169]
Affected version: 2.3.10
If you use more then one line break in the maintenance message, it will be ignored on the front site.

Example:

Used Maintenance Message:

"We will do some work

on our backend servers
Hope this is okay for you."

On the front site it looks like this:
"We will do some work
on our backend servers
Hope this is okay for you."

**Comment by billmn** [comment]
What about this?

## Manteinance message
![schermata 2016-10-18 alle 18 43 25](https://cloud.githubusercontent.com/assets/779534/19487364/cd752bd4-9562-11e6-866f-0da22bf6e32a.png)

## Result

![schermata 2016-10-18 alle 18 43 18](https://cloud.githubusercontent.com/assets/779534/19487371/d2c8da5e-9562-11e6-8b5a-c313e90fdc75.png)

## Code
```php
public function formattedMessage()
{
    $result = Markdown::convertToHtml($this->wrappedObject->message);
    $result = str_replace("\n", "<br />", trim($result, "\n"));

    return $result;
}
```

**Comment by jbrooksuk** [comment]
Sorry, I had meant to reply to this. The issue isn't on the PHP side, it's the CSS. It'll be fixed :)
