### ISSUE TITLE
Use ModelNotFoundException instead

### ISSUE THREAD

**Issue by abhimanyu003** [CachetHQ/Cachet#2170]
Why we are not using `ModelNotFoundException` instead of `BadRequestHttpException`

https://github.com/CachetHQ/Cachet/blob/2.4/app/Http/Controllers/SignupController.php#L41-L45

I guess we can refactor this to and can use `firstOrFail`

```
Invite::where('code', '=', $code)->whereNotNull('claimed_at')->firstOrFail();
```

Or Even better

```
Invite::whereCode($code)->whereNotNull('claimed_at')->firstOrFail();
```

I can see this code pattern is used over many places if you like I can create a pull request to update them this way.

Thanks

**Comment by GrahamCampbell** [comment]
An error 400 is fine I think.
