### ISSUE TITLE
Enable analytics piwik on http

### ISSUE THREAD

**Issue by sebglon** [CachetHQ/Cachet#2172]
If cachet site is on  http; is it possible to use piwik call on http?

For exemple you can change your code by:
```
<script type="text/javascript">
  var _paq = _paq || [];
  _paq.push(['trackPageView']);
  _paq.push(['enableLinkTracking']);
  (function() {
    var u= window.location.protocol+"://default.piwik.t-statuspage.vs.cloud.socrate.vsct.fr";
    _paq.push(['setTrackerUrl', u+'/piwik.php']);
    _paq.push(['setSiteId', 1]);
    var d=document, g=d.createElement('script'), s=d.getElementsByTagName('script')[0];
    g.type='text/javascript'; g.async=true; g.defer=true; g.src=u+'/piwik.js'; s.parentNode.insertBefore(g,s);
  })();
</script>
```

**Comment by GrahamCampbell** [comment]
No reason to use http to them when we can use https.

**Comment by sebglon** [comment]
My piwik is not on https.

**Comment by ConnorVG** [comment]
@GrahamCampbell but it can be self hosted - there is definitely a reason to support http.

**Comment by sebglon** [comment]
```
use piwik syntax     var u= "//default.piwik.t-statuspage.vs.cloud.socrate.vsct.fr";
```
without schema; dona by piwik script generaor

**Comment by jbrooksuk** [comment]
I'll update this don't worry :+1:

**Comment by jbrooksuk** [comment]
You'll have to supply the _full_ URL to your Piwik instance.

**Comment by iaidan** [comment]
Is this being worked on?

**Comment by jbrooksuk** [comment]
@iaidan we've not started it as of yet, if you'd like to open a PR, please do.

**Comment by iaidan** [comment]
I updated the view to rely on the HTTP/HTTPS being part of the URL provided in settings. May be a good idea to add a little note mentioning that on the analytics settings page.

Could also add a migration to update the old values to include https:// at the front so existing installations using Piwik will still work without updating the setting.

**Comment by jbrooksuk** [comment]
Closed by https://github.com/CachetHQ/Cachet/pull/2197
