### ISSUE TITLE
incidents templates

### ISSUE THREAD

**Issue by nixmomo** [CachetHQ/Cachet#2175]
Hi,
i'm new in cachet and i try to work deep into this lol...

Is there any documentation about incident templates? I can't find anything about it.
If not, in which files can i read the variables that i can use in the templates?

**Comment by jbrooksuk** [comment]
Hey @nixmomo, thanks for checking out Cachet!

Documentation for Incident Templates is lacking, it's something I want (read: need) to go back through before the 2.4 release.

There is a little about it here: https://docs.cachethq.io/docs/incidents

Incident Templates are defined by you, and then when you report an incident you can use a template. Essentially, they're "placeholders" for text. So you might know that every time you report an incident, you'll be able to provide an `error_id` value, your template would look for that and you can pass the value through in the `vars` parameter.

**Comment by nixmomo** [comment]
Hi @jbrooksuk ,

thanks for the fast reply :-) 
I know that i can define the templates but not really how it works... i can define a text and so on...
Which Placeholder does it give? Or can i define them too?
And if yes, how :-)

**Comment by jbrooksuk** [comment]
You define them in your incident templates, for example:

```twig
<h1>Incident ID {{ company_id_ref }}</h1>

<p>Some text here, reported at <strong>{{ created_at }}</strong></p>
```

Now when you create your incident through the API, you would specify a `params` key with a key/value pair:

```json
{
    params: {
    }
}
```

**Comment by h3m5k** [comment]
I'm using v2.3.9 and none of the documented or suggested ways of posting template variables via API are working.

The [API reference](https://docs.cachethq.io/reference#incidents) lists **vars** as the param to use for template variables, and that it should contain a **list of strings**.

Trying this, using curl and the following request body:
```
'{"vars":["thefirstvar","thesecondvar"],"name":"An incident.","message":"This will be replaced by message template.","status":"3","visible":"1","notify":"true","template":"testvars","component_id":"3","component_status":"4"}'
```
...generates this error:
```
{"errors":[{"id":"06215b4a-9cf3-47e4-b6af-4edbdaf32973","status":400,"title":"Bad Request","detail":"The request cannot be fulfilled due to bad syntax.","meta":{"details":["The message format is invalid."]}}]}
```

Trying the method you are describing above, using **params** (which is completely undocumented?):
```
'{"params":{"some_var":"thefirstvar","another_var":"thesecondvar"},"name":"An incident","message":"This will be replaced by message template.","status":"3","visible":"1","notify":"true","template":"testvars","component_id":"3","component_status":"4"}'
```
...generates the same error:
```
{"errors":[{"id":"dd3d6b7a-f50d-477a-94cb-0c8c24f7f193","status":400,"title":"Bad Request","detail":"The request cannot be fulfilled due to bad syntax.","meta":{"details":["The message format is invalid."]}}]}
```

_However_, using **vars** containing a **dictionary** _is_ working. (Suprisingly, since this is not described anywhere.)
Request body:
```
'{"vars":{"some_var":"thefirstvar","another_var":"thesecondvar"},"name":"An incident","message":"This will be replaced by message template.","status":"3","visible":"1","notify":"true","template":"testvars","component_id":"3","component_status":"4"}'
```

Successful response:
```
{"data":{"name":"An incident","status":"3","visible":1,"message":"\n\nthefirstvar\nthesecondvar","component_id":"3","updated_at":"2019-03-13 14:28:17","created_at":"2019-03-13 14:28:17","id":14,"notify":true,"component":{"id":3,"name":"MyService","description":"Some service","link":"http:\/\/example.com","status":"4","order":0,"group_id":0,"created_at":"2019-03-13 11:29:07","updated_at":"2019-03-13 14:28:17","deleted_at":null,"enabled":true,"status_name":"Major Outage","tags":{"":""}},"human_status":"Watching","scheduled_at":"2019-03-13 14:28:18"}}
```

I'm guessing this is a documentation bug rather than a functional difference between versions?

**Comment by jbrooksuk** [comment]
v2.3.9 is out of date. Please can you update to the latest v2.3 and try again.

**Comment by h3m5k** [comment]
The issues are valid for v2.3.15 as well.
