### ISSUE TITLE
Upgrade in Docu is missing one step

### ISSUE THREAD

**Issue by nixmomo** [CachetHQ/Cachet#2180]
Hi,
your Docu is missing one Step after the upgrade...
[Upgrading Cachet Documentation](https://docs.cachethq.io/docs/updating-cachet) 

After 

```
$ php artisan down
$ git fetch origin
$ git tag -l
$ git checkout LATEST_TAG
$ composer install --no-dev -o --no-scripts
$ php artisan app:update
```

you have tu run
`$ php artisan up`

If you don't run the last step you get a 500 error on the Webpage ;-)

**Comment by jbrooksuk** [comment]
Could you suggest edits to the page please?

**Comment by nixmomo** [comment]
@jbrooksuk Suggestion submitted 👍 

Sorry, i didn't know this function :-)

**Comment by nixmomo** [comment]
just a reminder, docs are'nt updated :)

**Comment by jbrooksuk** [comment]
Merged, thanks!
