### ISSUE TITLE
Feed don't sorting posts the same as frontend timeline

### ISSUE THREAD

**Issue by nixmomo** [CachetHQ/Cachet#2181]
i noticed that the RSS and Atom Feeds have another sorting mechanic as the timeline in frontend.

i have in timeline following inccidents:
1. sheduled maintenance planed for 14.10. 2am published at 13.10. 2:22pm
2. inccident fixed post published at 13.10. 6:07pm
3. inccident update post published at 13.10. 5:30pm
4. inccident report post published at 13.10. 4:13pm

in my feeds is it sorted like this
1.  inccident fixed post published at 13.10. 6:07pm
2. inccident update post published at 13.10. 5:30pm
3. sheduled maintenance planed for 14.10. 2am published at 13.10. 2:22pm
4. inccident report post published at 13.10. 4:13pm

Looks like the feeds aren't synchron with the timeline in frontend. 

It's good that the sheduled Maintenance is posted in feed earlier but i haven't the update in the Feed and that was my last report.

I'm thinking wrong or is it too late for me only :-D

**Comment by jbrooksuk** [comment]
Although Scheduled Maintenance doesn't appear in either the Atom or RSS feed in v2.4, it will be back soon and this won't be an issue 👍
