### ISSUE TITLE
Filter for displaying component group data

### ISSUE THREAD

**Issue by nicolasfagotti** [CachetHQ/Cachet#2184]
When many components are added, is difficult to focus on specific data. It would be nice to have a way to filter the component group information without disrupting whole site functionality.

**Comment by jbrooksuk** [comment]
Thank you for your input on Cachet 2.x. We are shifting our attention and resources to Cachet 3.x and will no longer be supporting the 2.x version. If your feedback or issue is relevant to the 3.x series, we encourage you to engage with the new branch.

For more information on the Cachet rebuild and our plans for 3.x, you can read the announcement [here](https://github.com/CachetHQ/Cachet/discussions/4342).

We appreciate your understanding and look forward to your contributions to the new version.
