### ISSUE TITLE
Cachet won't send Mails out

### ISSUE THREAD

**Issue by nixmomo** [CachetHQ/Cachet#2187]
#2183
after this fix i can open subscribers in dashboard and i can subscribe with a new mail but cachet isn't sending Mails.
(It worked 2 days ago with 2.3.9)
Credentials in .env are correct, i send with the same credentials and the same Mail Drivers with another App E-Mails out.

I checked Cachet Logs but found nothing.

I checked Logs from my Mailserver too but he never got any Mails from Cachet again.

**Comment by jbrooksuk** [comment]
Are you running the cron?

**Comment by nixmomo** [comment]
i use supervisor ;-) 
And yes it's running.... it isn't a "Internet Problem" too, i just used the same domain as mail adress so if my mailserver get the mail its in the inbox too :)

**Comment by nixmomo** [comment]
Okay i found the error.
It was Supervisor, i trusted the docu and that is wrong again.

Supervisor crashs if the --delay option is set to 1 with the Error "Fatal,  Exited too quickly

A change to 
`command=php artisan queue:work --daemon --delay=2 --sleep=1 --tries=3`
resolve this issue.

I want suggest the changes but i can't, every try to submit ends with a red icon without error message.
You can close the issue please.
Thx!

**Comment by jbrooksuk** [comment]
I'll update the docs. Thanks.

**Comment by nixmomo** [comment]
just a reminder, docs aren't updated now :-)

**Comment by jbrooksuk** [comment]
They are now 👍

**Comment by nixmomo** [comment]
i don't see the update with --delay=2 :-(

![image](https://cloud.githubusercontent.com/assets/8502506/19932873/dded0904-a111-11e6-9f76-fd6fa0c583f8.png)

**Comment by jbrooksuk** [comment]
I didn't save it, whoops!

**Comment by nixmomo** [comment]
Shit happens :D 

For 2.4 works this too ;-)

Regards
