### ISSUE TITLE
Show groups in subscription page, and no default component selected

### ISSUE THREAD

**Issue by daniel-lalaina-movile** [CachetHQ/Cachet#2188]
Hello Guys, Cachet is awesome! You are all F.. incredible.  I have 2 suggestions about subscription page:

1 - No component selected by default.
This will force subscribers to select just what they want.
A "(un)select all" box would be nice, but by default, it's better to open the page without any component selected.

2 - Show group in selection page. (just to display it, not to enable selection)
It's usual to have same or very similar component names in different groups, and today the subscriber can't differentiate them.

Regards,
Daniel La Laina

**Comment by nixmomo** [comment]
Hi Daniela,

in Branch 2.4 you have the option to deselect / select all.

As Default are all activated in 2.4 too.
If nobody have a sec I can look when I'm home what changes are needed do set no activated components as default. 

Von meinem iPhone gesendet

**Comment by nixmomo** [comment]
Sry i watched shortly but haven't found it.... I'm sure it is only one code line but very hard to find it in this big code

**Comment by jbrooksuk** [comment]
I've thought about this for a bit now.

1. When somebody signs up for notifications, they're initially created as a global subscriber (subscribed to everything), this is better than signing up to nothing as people are less likely to click more buttons afterwards.
2. Unselect is a thing now.
3. Groups are done :)
