### ISSUE TITLE
Demo error

### ISSUE THREAD

**Issue by ziraak** [CachetHQ/Cachet#2193]
you should probably know that there is something wrong with your demo.
![asf](https://cloud.githubusercontent.com/assets/9131432/19469025/d7413f3e-9519-11e6-85f2-f64879264aa7.PNG)

**Comment by jbrooksuk** [comment]
Interesting... A status of `0` shouldn't be allowed (currently).

**Comment by jbrooksuk** [comment]
This will be fixed with #2194
