### ISSUE TITLE
Footer is not visible on ipad

### ISSUE THREAD

**Issue by Harsh061** [CachetHQ/Cachet#2196]
Hey, Cachet is awesome! I am new to open source contributions. I found 2 issues :bug:  on Google Chrome : 
1. On inspecting the website i found this error : 
    Failed to load resource: https://cachethq.io/img/social/favicon.png 
2. The site is completely responsive. The only screen where i find issue was ipad. The footer section i.e.
    Quick Links is not visible.       

Regards,
Harshit

**Comment by jbrooksuk** [comment]
Thanks for this report!

As part of v2.4 we're implementing a new status page design which will eradicate this issue 👍
