### ISSUE TITLE
Subscribers which are subscribed via API with Components getting all mails

### ISSUE THREAD

**Issue by tmatthaeus** [CachetHQ/Cachet#2201]
I am subscribing a user via the API for just some components. Dashboard is showing, that this worked. But the user receive an email for every new issue.

I found in the MySQL Database in the table "subscribers" the value "global = 1". Every user who came from the API is "global = 1".

But it looks like, that there is no option to define a "global = 0" through the API.

**Comment by jbrooksuk** [comment]
It looks like we're not exposing the `global` flag at all, or even ensuring that if `subscriptions` isn't empty, then we're not global...

One for you @joecohens, unless you have no time and want me to look into it?

**Comment by jbrooksuk** [comment]
Also, I've tagged this under Hacktoberfest, it's not a massive change (but will require tests).

**Comment by jbrooksuk** [comment]
Ping @joecohens

**Comment by jbrooksuk** [comment]
@tmatthaeus sorry for the delay in this one. Looking at the code, if you supply `null` components, then the subscriber will be subscribed globally 👍
