### ISSUE TITLE
Cachet showing 500 error.

### ISSUE THREAD

**Issue by nikolaaa4** [CachetHQ/Cachet#2203]
Installed Cachet via the docs, https://docs.cachethq.io/docs/installing-cachet however, the admin panel works fine but the site shows a 500 error. https://status.rileybot.top/
Any help?

**Comment by nikolaaa4** [comment]
Forgot to mention that i'm installing on Ubuntu 14.04

**Comment by GrahamCampbell** [comment]
Please paste your log file.

**Comment by nikolaaa4** [comment]
Log file can be found here http://pastebin.com/FwM9DhcZ

**Comment by GrahamCampbell** [comment]
Copy .env.example to .env.

**Comment by nikolaaa4** [comment]
The file is already renamed to .env unless you're thinking about some other file? http://prntscr.com/cxie36
