### ISSUE TITLE
Install without Artisan

### ISSUE THREAD

**Issue by m1guelpiedrafita** [CachetHQ/Cachet#2204]
Hi!
I am trying to setup Cachet in an enviroment where I can't access sudo, and when I try to execute php artisan I get:
`
[ErrorException]                                                                                                                                                               
  is_file(): open_basedir restriction in effect. File(/opt/php-5.6/bin/php) is not within the allowed path(s): (/home/[username]:/tmp:/var/tmp:/opt/php-5.6/pear:/usr/local/bin:/etc/pki/tls/certs)
`
Can I install Cachet?

**Comment by GrahamCampbell** [comment]
Not possible, sorry.
