### ISSUE TITLE
Deb Package + Apt Mirror

### ISSUE THREAD

**Issue by sammcj** [cachethq/Cachet#221]
It would be great to have Cachet packaged into a Deb and available from an apt mirror.

This would:  

* Make upgrades easier
* Make it obvious when a new release is available
* Allow for easy automated patching using tools such as puppet
* Properly define dependencies
* Properly log application installations and upgrades
* Avoid the need for composer which has a very dangerous installer

I've used https://packagecloud.io for a few projects and found to to be really great and it's free for up to 25 packages which should be more than you will ever need (latest + maybe 2 previous versions available?)

I would be happy to test any packages you make against both Debian 7 (stable) and Debian 8 (testing) and provide feedback.

**Comment by jbrooksuk** [comment]
I suggest that we get V1 out before we look at packaging Cachet up like this, but I'm all for it once we're ready.

**Comment by jbrooksuk** [comment]
We'd also want the update system to be working.

**Comment by GrahamCampbell** [comment]
I think that's probably a bad idea. "composer create-project" works fine doesn't it?

**Comment by jbrooksuk** [comment]
Having a Debian package would let us setup all the dependencies essentially.

**Comment by sammcj** [comment]
Hi Graham,

There are many advantages to creating standard packages rather than
relying on people to use third party tools specific to the language
you've written an application in.

It makes automation, updating, reporting and dependancy management a lot
easier.

Many people (myself and colleges being certainly included) end up having
a lot of time wasted by managing all the third party, language specific
package managers and many people will attempt to create their own third
party packages not only for the reasons listed above, but often also it
is company policy for application deployments and update management.

Also worth mentioning is the often suspect reliability of upstream
package management repositories - for example NPM for nodejs packages is
often unavailable as their site often goes offline without warning and
can take hours to return.

By packaging your application in a standard way, free of upstream
dependencies you're making it easy for people to mirror the installer,
thus providing your applications install process with more reliability
and allowing for companies to easily mirror the requirements offline as
required, especially for secure environments without direct Internet
access.

For the organisation I work for (@infoxchange) if Debian packages were
not available, I would be trying to package it myself or at least create
a docker file and image to allow for reliable updates and deployment -
if it was too wasteful of time and there wasn't packages - we probably
wouldn't use Cachet.

**Comment by matthewjamesr** [comment]
Just jumping in on the conversation here, all of this could be negated by
building a docker image upon each release and push that to docker hub or
upload it's .tar in GitHub.

Thoughts?

**Comment by sammcj** [comment]
I would agree that having a dockerfike and pushing the image to the docker hub would probably be sufficient for most places as the build requirements are quite modern anyway.

**Comment by jbrooksuk** [comment]
Providing a Dockerfile would be better than a debian package. Agreed?

**Comment by sammcj** [comment]
@jbrooksuk I'm sure it won't please everyone (that's a hard thing to do!) but I think it makes sense especially since Docker is now widely accepted and easy to use.

**Comment by jbrooksuk** [comment]
Ok, cool. I'm going to close this and open a new issue for supplying a Dockerfile.
