### ISSUE TITLE
About this page

### ISSUE THREAD

**Issue by Aybee2k** [CachetHQ/Cachet#2216]
At the point "About this page" we have something entered, but it is not displayed on the front page

**Comment by jbrooksuk** [comment]
Can you see if the setting is in the database? Is your `./bootstrap/` folder writeable by your web server process?

**Comment by Aybee2k** [comment]
Yes the Folder have 755

In which table should the entry be placed?

**Comment by jbrooksuk** [comment]
`settings`.

**Comment by fdhex** [comment]
@jbrooksuk Was this solved? Somehow I have a similar issue, and I see my data in settings.app_about on the database.
