### ISSUE TITLE
issue with component status management

### ISSUE THREAD

**Issue by ludovicraymond** [CachetHQ/Cachet#2217]
If I create an issue with a critical status on a component and a new issue is created with a limited impact status the component change to the limited impact status even if two issues are not fixed.

I think that the component status management should take into account the status of current opened issues.

Secondly I think that an historical should be necessary in issue to kept the creation date with status and provide the issue debug historic in views.

**Comment by jbrooksuk** [comment]
This is going to be taken into consideration with the 2.4 release, now that we have Incident Updates.
