### ISSUE TITLE
Configuring email documentation

### ISSUE THREAD

**Issue by axilleas** [CachetHQ/Cachet#2218]
According to the docs, you need to configure `.env` with the SMTP credentials in order to get SMTP to work. However, even when those are set up, you are still asked to enter their values in the Environment Setup page.

Should the docs be updated or is there something I'm missing? If the docs need an update I'm happy to provide one.

Also what are the different mail drivers options used for? I mean, even if you choose to use Mailgun, it's still SMTP, right?

**Comment by ConnorVG** [comment]
I assume the fields should really pre-fill with the entered details from `.env`, for security reasons if not.

You can learn about the mail drivers here: https://laravel.com/docs/5.2/mail
They use different delivery systems, generally speaking via a HTTP API.

**Comment by jbrooksuk** [comment]
>  However, even when those are set up, you are still asked to enter their values in the Environment Setup page.

This is something that is fixed in v2.4 setup 👍

**Comment by axilleas** [comment]
Okay, thanks guys :)
