### ISSUE TITLE
Allow for custom data fields in components

### ISSUE THREAD

**Issue by cascer1** [CachetHQ/Cachet#2226]
Hi!

I'm working on a tool that automatically checks certain things for components I added to Cachet (Right now, I'm only pinging and getting response codes). 

I currently have a file that simply stores the settings for each component in an array. In this I store the url, check type, expected response code, timeout, and some other details needed for tests. I tried moving this to tags, but that didn't work because you can't have a custom tag slug (as far as I know). 

I would like to be able to add custom data to a component. I imagine this being similar to tags, but instead of the tag slug being automatically generated, it is manually entered by me. That way I can store some data used by my automatic checking tool.

In the API response for GET /components/:id, I could imagine a response like

        {
            "id": 1,
            "name": "API",
            "description": "This is the Cachet API.",
            "link": "",
            "status": 1,
            "order": 0,
            "group_id": 0,
            "created_at": "2015-07-24 14:42:10",
            "updated_at": "2015-07-24 14:42:10",
            "deleted_at": null,
            "status_name": "Operational",
            "tags": [
                "slug-of-tag": "Tag Name"
            ],
            "meta": [
                "check-type": "http",
                "timeout": "15",
                "port": "80"
            ]
        }

**Comment by ConnorVG** [comment]
This is quite an interesting idea.

**Comment by jbrooksuk** [comment]
I like this.

Somebody feel free to hack on it 😄

**Comment by ekandreas** [comment]
Great! I'm using the "description" field with json-data right now. It would be great with meta fields instead :-)

**Comment by jbrooksuk** [comment]
If we (or somebody) does this, I'd also like to see the same thing applied to Incidents. I reckon that'd be very useful!
