### ISSUE TITLE
Updating an incident

### ISSUE THREAD

**Issue by JExactly** [CachetHQ/Cachet#2230]
So, when you create a new incident, it appears that the only email that is sent is the initial incident notice. 
When you update an incident, no follow-up e-mail is sent. It seems to me that the way an incident is reported works great. But updating an incident, I would like the ability to notify my subscribed users of the change/update. 

Would it be logical to maybe create a incident history of sorts that when an update is made to an existing incident, it changes the component status etc, gives the ability to send an update notice and moves the previous history of the incident to a historical list nested within the incident until it is back to operational and closed?

**Comment by jbrooksuk** [comment]
This is something that will be fixed in v2.4
