### ISSUE TITLE
Customize Front Page

### ISSUE THREAD

**Issue by daza111** [CachetHQ/Cachet#2233]
Hi there,

Just a quick question. Because of how we have our CSS colors set, I am running into an issue where I need text white except when its on the subscribe popup since that has a white background. The subscribe page is using an h2 tag for text, but so is one of the headers on the front page.

What template/view can I change "About This Site" on the front page to use h1 as the tag rather than h2? The Past incidents on the same page is already using h1 so it should match?

**Comment by jbrooksuk** [comment]
This isn't something that is supported I'm afraid. You'd have to change the Blade template.
