### ISSUE TITLE
Several bugs, plus some feature suggestions

### ISSUE THREAD

**Issue by Robbbbbbbbb** [CachetHQ/Cachet#2236]
~~v2.1.0, installed today~~ updated to 2.3.9 and resolved most problems I had when creating this..

Hey all - thanks for a great product! And thanks to Barracuda for having an outage today, otherwise I would have never found this 😄

Edit: I'm a big dummy and didn't install the latest tag earlier while reading through the documentation. I've updated this Issue accordingly. Please see below.

_____

Status page issues

- One particular component has "Major Outage" selected, however the Component Group still shows as "Operational"
-  If I link to something in the 'message' textarea using an href, no link is actually created on the Status page. Not sure if there is a way to use Twig to do this, or what.
_____

Dashboard page issues

Settings > Application Setup
- Nothing changes here when a field is modified. When I save, all checkboxes and fields reset to their previous value and no changes are made on the Status page.

_____

Here are some functionality suggestions I had while using it:

- Have the ability to set the label on Scheduled Maintenance to a Component name, like if you were creating an incident.
- If there is an outage, have 'Major Outage' or whatever status link to the Incident details.

**Comment by jbrooksuk** [comment]
Hi @Robbbbbbbbb thanks for submitting this issue :)

1. I'll take a look at this, it doesn't sound right at all!
2. The message of an incident, or somewhere else? Could you please clarify.
3. You need to ensure that the entire `./bootstrap`directory and the directories/files below it are writeable from your server process.
4. Scheduled Maintenance is being refactored for v2.4 :+1:
5. This is something we _might_ implement with the new design.

**Comment by jbrooksuk** [comment]
@Robbbbbbbbb I'm taking a look at the component group stuff and I'm unable to find what would be causing this, it's working fine here.

![](https://cldup.com/IpFtmhUew5.png)

Could you possibly email me a dump of your database to james@alt-three.com please? Don't worry, all sensitive information such as passwords is encrypted.

**Comment by jbrooksuk** [comment]
You can now supply a `<a>` tag in an Incident message.
