### ISSUE TITLE
Invalid Metric timer saved on database

### ISSUE THREAD

**Issue by biovn** [CachetHQ/Cachet#2237]
i just tried the 2.4 version and found a bug that mysql did save the wrong timer on this table "metric_points" ( -7 hours comparing to current server time)  when i used the cachet monitor tool to test.
This does not happen when i tried with version 2.3.9 before

**Comment by jbrooksuk** [comment]
Hi @biovn, this is weird as I don't believe we've touched metrics in v2.4.

What field is it that's wrong exactly?

**Comment by biovn** [comment]
it's the fields : created_at, updated_at 
the way i found the problem that i don't see mertric graph at the current hour but it appear at the other hour when i try check the graph with 12 hours. checking your database and i found this issue.

**Comment by jbrooksuk** [comment]
Ping @joecohens, do you reckon this is related to timestamps?

**Comment by jbrooksuk** [comment]
Or... This could be due to the performance refactor I did on metrics? @biovn what DB driver are you using?

**Comment by biovn** [comment]
db driver is mysql

**Comment by jbrooksuk** [comment]
Are you using the [Timezone](https://docs.cachethq.io/docs/time-zone-header) header when you're sending the data?

**Comment by biovn** [comment]
sending data using this tool https://github.com/castawaylabs/cachet-monitor . So i don't know how they send data inside. this tool work ok with cachet 2.3.10 but not with 2.4

**Comment by jbrooksuk** [comment]
Are you able to send me a copy of your `metric_points` table at all please?

**Comment by jbrooksuk** [comment]
cachet-monitor must be setting the `created_at` value. I'm pretty sure there is no issue with Cachet here, but I could be wrong.
