### ISSUE TITLE
Subscribe to issues not showing

### ISSUE THREAD

**Issue by m1guelpiedrafita** [CachetHQ/Cachet#2238]
I have cachet installed at status.miguelpiedrafita.com with the subscribe option enabled, but it doesn't show up in the page.

**Comment by jbrooksuk** [comment]
Have you configured the [mail settings](https://docs.cachethq.io/docs/configuring-mail)?

**Comment by jbrooksuk** [comment]
Also, what version of Cachet are you using?

**Comment by m1guelpiedrafita** [comment]
The lastest. Also, can't you get that from the API?
