### ISSUE TITLE
Upgrade in most recent version not working

### ISSUE THREAD

**Issue by karaktaka** [CachetHQ/Cachet#2240]
If you update to the current master branch and trying to upgrade the installation you get an error:

`[Illuminate\Database\QueryException]                                                                                                             
  SQLSTATE[42S02]: Base table or view not found: 1146 Table 'cachet.incidents' doesn't exist (SQL: UPDATE incidents SET occurred_at = created_at) 
             
  [Doctrine\DBAL\Driver\PDOException]                                                         
  SQLSTATE[42S02]: Base table or view not found: 1146 Table 'cachet.incidents' doesn't exist  
 
 [PDOException]                                                                              
  SQLSTATE[42S02]: Base table or view not found: 1146 Table 'cachet.incidents' doesn't exist `

My installation uses Table prefixes beginning with "ca_".

**Comment by jbrooksuk** [comment]
Oh, ignore the comment I just added on the commit, thanks!

**Comment by jbrooksuk** [comment]
I'm going to work on a better way of globally dealing with table prefixes.

**Comment by jbrooksuk** [comment]
Fixed :)
