### ISSUE TITLE
Adding Scheduled Maintenance - Error 500 Internal Server Error

### ISSUE THREAD

**Issue by lewtaylor4** [CachetHQ/Cachet#2242]
Hi, 

I have recently installed Cachet 2.4.0 on Centos 7

Installation went smooth, no other issues apart from when I schedule maintenance. I get a internal server 500 error. This happens as soon as I submit the page and it has never worked. 

Looking at the logs I see:

[2016-11-11 13:27:28] local.ERROR: exception 'InvalidArgumentException' with message 'Unexpected data found.
Unexpected data found.
Data missing' in /var/www/Cachet/vendor/nesbot/carbon/src/Carbon/Carbon.php:425
Stack trace:
#0 /var/www/Cachet/vendor/jenssegers/date/src/Date.php(96): Carbon\Carbon::createFromFormat('Y-m-d H:i', '25/11/2016', 'UTC')
#1 /var/www/Cachet/app/Dates/DateFactory.php(65): Jenssegers\Date\Date::createFromFormat('Y-m-d H:i', '25/11/2016', 'UTC')
#2 /var/www/Cachet/app/Bus/Handlers/Commands/Schedule/CreateScheduleCommandHandler.php(70): CachetHQ\Cachet\Dates\DateFactory->create('Y-m-d H:i', '25/11/2016')
#3 /var/www/Cachet/app/Bus/Handlers/Commands/Schedule/CreateScheduleCommandHandler.php(54): CachetHQ\Cachet\Bus\Handlers\Commands\Schedule\CreateScheduleCommandHandler->filter(Object(CachetHQ\Cachet\Bus\Commands\Schedule\CreateScheduleCommand))
#4 /var/www/Cachet/bootstrap/cache/compiled.php(9761): CachetHQ\Cachet\Bus\Handlers\Commands\Schedule\CreateScheduleCommandHandler->handle(Object(CachetHQ\Cachet\Bus\Commands\Schedule\CreateScheduleCommand))
#5 /var/www/Cachet/bootstrap/cache/compiled.php(9880): Illuminate\Bus\Dispatcher->Illuminate\Bus\{closure}(Object(CachetHQ\Cachet\Bus\Commands\Schedule\CreateScheduleCommand))

It does not seem to like the date format? I believe I have set all the relevant permissions! Any ideas?

Apologies if this is the wrong platform to post my issue.

Cheers! :+1:

**Comment by jbrooksuk** [comment]
Please know that Cachet v2.4 is **not** the most stable version and as such, there will be bugs like this one.

What date format are you submitting dates in?

**Comment by jbrooksuk** [comment]
We expect the date format to be `Y-m-d H:i` so `2016-11-14 18:16` for now.

**Comment by jbrooksuk** [comment]
Also, there is a calendar component that should be showing?

**Comment by jbrooksuk** [comment]
I've tested here and the form works when the date format is correct 👍
