### ISSUE TITLE
any way to separate graph metric into a page with password protection 

### ISSUE THREAD

**Issue by biovn** [CachetHQ/Cachet#2244]
on the homepage of cachethq have graphic metric showing, however as we don't want normal user see that graphic but system admin only. So i would like to know if we able separate graph metric into a page with password protection, or move that graph into the portal after login

**Comment by jbrooksuk** [comment]
@biovn there isn't currently a way of hiding metrics from users who are not logged in.

This would make a good feature for v2.4 if you'd like to contribute it?

**Comment by biovn** [comment]
i hope too. as am not familar with php, hope other can help

**Comment by jbrooksuk** [comment]
I'll do this by adding an option for visibility as we do other bits. 

Still need a better ACL...

**Comment by m1guelpf** [comment]
If you point me to a page that already has this function, I will try.

**Comment by jbrooksuk** [comment]
Component Groups can be hidden, so follow this code :)

**Comment by jbrooksuk** [comment]
I've done this :)
