### ISSUE TITLE
Limit access to components to users (access control)

### ISSUE THREAD

**Issue by thomaschaaf** [CachetHQ/Cachet#2247]
Our company has components which only some of our customers are interested in or allowed to see. Thus we need a way to limit the visibility of these components to a limited number of users.

StatusPage.IO has a feature called access control (http://blog.statuspage.io/cutting-support-costs-with-access-control).

**Comment by jbrooksuk** [comment]
This is something that I'd like to see implemented at some point, but it's not there yet. 

In its current state, our entire control system is very basic and incomplete. 

I'll take a look at the StatusPage.io post and see how we can better it :)

**Comment by iknev31** [comment]
Hey jbrooksuk, Do we have this feature available ? Limiting user access to specific components/groups.

It's a great feature to have. Please let us know when it would be available.

**Comment by jbrooksuk** [comment]
Thank you for your input on Cachet 2.x. We are shifting our attention and resources to Cachet 3.x and will no longer be supporting the 2.x version. If your feedback or issue is relevant to the 3.x series, we encourage you to engage with the new branch.

For more information on the Cachet rebuild and our plans for 3.x, you can read the announcement [here](https://github.com/CachetHQ/Cachet/discussions/4342).

We appreciate your understanding and look forward to your contributions to the new version.
