### ISSUE TITLE
Remove Cloud flare cookies, automatically ping servers.

### ISSUE THREAD

**Issue by LiveChief** [CachetHQ/Cachet#2248]
why does Cachet require cloudflare?

add a feature where you can automatically ping servers, (custom ports)

**Comment by jbrooksuk** [comment]
> why does Cachet require cloudflare?

It doesn't? We just have a configuration file for handling proxying to it. Ping @GrahamCampbell.

> add a feature where you can automatically ping servers, (custom ports)

Cachet doesn't do monitoring yet, and likely won't for the foreseeable future.
