### ISSUE TITLE
Bottom menu sidebar is hidden for certain widths

### ISSUE THREAD

**Issue by axilleas** [CachetHQ/Cachet#2249]
Between the widths 767-991, Cachet is not showing the bottom menu sidebar. Tested on latest master.

**934x686**

![screen shot 2016-11-19 at 10 51 45](https://cloud.githubusercontent.com/assets/340023/20454621/646bfab2-ae46-11e6-80e0-d36cdd382b6f.png)

**Comment by jbrooksuk** [comment]
Thanks for reporting!

This isn't ideal as the logout button is lost.

Assigning to @joecohens.

**Comment by axilleas** [comment]
Yep, that's the primary reason I reported this :) Suddenly I didn't know how to logout!

**Comment by max-l-weaver** [comment]
This has been a bug for quite a while now, any update?

**Comment by jbrooksuk** [comment]
It'll be fixed in v2.4 :)

**Comment by jbrooksuk** [comment]
Unless someone would like to submit a fix to v2.3

**Comment by jbrooksuk** [comment]
Hacked in v2.4 🙈 

Hopefully we'll have a new dashboard anyway.
