### ISSUE TITLE
Why do you configure composer to think php is php 5.5.9?

### ISSUE THREAD

**Issue by LKDevelopment** [CachetHQ/Cachet#2253]
Hello,

i wanted to install an own package with requirements to php7 in cachet. But composer said that the system has php 5.5.9. So i started to think that this is a composer bug: https://github.com/composer/composer/issues/5905#issuecomment-263059536

What is your reason to configure composer to think on the server is php 5.5.9?

**Comment by jbrooksuk** [comment]
This is something we're dropping from v2.4 https://github.com/CachetHQ/Cachet/blob/2.4/composer.json
