### ISSUE TITLE
Can't write to .env

### ISSUE THREAD

**Issue by supawiz6991** [CachetHQ/Cachet#2255]
Trying to complete setup and I get an error "An error has occurred and this resource cannot be displayed". A review of the logs show: 

[2016-11-30 03:37:15] production.ERROR: ErrorException: file_put_contents(/var/www/public_html/.env): failed to open stream: Permission denied.

I verified file permissions are good. I even tried changing them to 777 as a test but still I get the above error.

**Comment by jbrooksuk** [comment]
Your web process must have write access to your Cachet directory too.

**Comment by supawiz6991** [comment]
The web process appears to have full read/write access to .env but still I get the error. Is there anything else that could cause this?

**Comment by jbrooksuk** [comment]
What web server are you using?

**Comment by supawiz6991** [comment]
Centos
Apache2

Turns out SELinux was the problem. Apparently the first time I altered its directives to allow writing to that directory it didnt take.

Re-ran the commands and all is good.

**Comment by jbrooksuk** [comment]
✨
