### ISSUE TITLE
Can't add subscribers on new install - internal server error

### ISSUE THREAD

**Issue by haynes11** [CachetHQ/Cachet#2260]
Hello,

I've recently put cachet on a new vps. Set everything up as usual and all working fine. Apart from getting the usual "Houston internal server error" page you get if you get an error with Cachet.

It happened when I tried to add new subscribers.

Upon looking at the log it moans about my mailserver being denied access, but the credentials are correct I'm sure! I've tested the credentials just to be sure and I was able to login. Please see screenshot for the line from the error log.
![screenshot_1](https://cloud.githubusercontent.com/assets/19718532/20863354/f019970c-b9bf-11e6-819c-1ce97876a55a.png)

Thanks for your help,
Jerome Haynes

**Comment by jbrooksuk** [comment]
Have you got encryption on your mail server?

I'm closing this issue as it's *very* likely not a Cachet bug, but I'm happy to help fix it :)

**Comment by haynes11** [comment]
Test

**Comment by haynes11** [comment]
How do I make it send just using the virtual machine it's installed on rather than having to specify my mailserver on another server? I e-mailed you about this but never received a reply and would very much like to get this working!
