### ISSUE TITLE
improvement - handle timeout request

### ISSUE THREAD

**Issue by abioneperhobby** [CachetHQ/Cachet#2264]
my cachet application store a metric point every 30 seconds every time every days.

after some months, the GET of data (http://host/metrics/1?filter=last_hour) goes in timeout ( 60s ) but user connected to interface cannot understand what is going on. the metrics still empty and white.

in my case, now i will try to drop some stored data. i don't need those anymore.

**Comment by jbrooksuk** [comment]
The way we calculate metrics in v2.4 has been rewritten, which should result in faster calculation times for you.

However, if you could email me a dump of your `metric_points` table, I'd like to test that this is indeed the case for larger data gatherers :)

**Comment by abioneperhobby** [comment]
@jbrooksuk i deleted the metric by dashboard, but the metric point stay stored in the metric_points table. (is this a bug?)
anyway, the deleted metric had 213287 points

**Comment by jbrooksuk** [comment]
Hmm, metric points should be removed when you remove a metric - I'll check that.

> anyway, the deleted metric had 213287 points

Wow, okay.
