### ISSUE TITLE
500 Error Everywhere

### ISSUE THREAD

**Issue by GhostCyborg** [CachetHQ/Cachet#2267]
Before submitting your issue, please make sure that you've checked the checkboxes below.
- [x]  I am running the latest release version of Cachet.
- [x]  I am running at least PHP 5.5.9. You can check this by running php -v.
- [x] I have ran #rm -rf bootstrap/cache/*.
## Expected Behavior
Normal Cachet dashboard and Status page
## Actual Behavior
I get a 500 error, happened after setup
## Log (/var/www/Cachet/storage/logs/laravel-2016-12-10.log):
http://pastebin.com/6cgeiEtU or http://pastebin.com/raw/6cgeiEtU

**Comment by jbrooksuk** [comment]
You've set one or more of your drivers to `apc` but it looks like you don't have the APC extension installed. You have two options:

1. Install APC.
2. Use a different cache/session driver

Good luck!

**Comment by GhostCyborg** [comment]
Could you give me a walkthrough or link me to a website which might help me? Cause I don't quite understand what I have to do..

**Comment by jbrooksuk** [comment]
🚀
