### ISSUE TITLE
Unable to install Cachet v2.3.10

### ISSUE THREAD

**Issue by heticor915** [CachetHQ/Cachet#2272]
Hi Everybody, 

I was trying to install this app; until version **v2.2.2** it was working like a charm, but due to some changes in our infrastructure we were updating old services like our status page we're using **_v2.3.10_** and the procedure used to install the app was the same founded [here](https://docs.cachethq.io/docs/installing-cachet), our **_.env_** file contains the following configuration:

> APP_ENV=production
> APP_DEBUG=false
> APP_URL=http://status.sample.co
> APP_KEY=ourkeyhere
> DB_DRIVER=sqlite
> CACHE_DRIVER=file
> SESSION_DRIVER=file
> QUEUE_DRIVER=sync
> CACHET_EMOJI=false
> MAIL_DRIVER=smtp
> MAIL_HOST=null
> MAIL_PORT=null
> MAIL_USERNAME=null
> MAIL_PASSWORD=null
> MAIL_ADDRESS=null
> MAIL_NAME=null
> MAIL_ENCRYPTION=tls
> REDIS_HOST=null
> REDIS_DATABASE=null
> REDIS_PORT=null
> GITHUB_TOKEN=null

after checking all the configuration in our box we couldn't find whats the problem, seems something like  a dependency reference error, 
![alt text](http://i.imgur.com/T5tTqDw.png "Error ")

Is there any solution to this ?

**Comment by phy25** [comment]
Seems like duplicate as #1997. For me using SQLite and PHP 7.0 Windows, under 2.3.10 / 2.4.0-dev, installing db fails.

>\>php artisan app:install
[Illuminate\Database\QueryException]
SQLSTATE[HY000]: General error: 17 database schema has changed (SQL: create
 table "cachet_component_groups" ("id" integer not null primary key autoinc
rement, "name" varchar not null, "created_at" datetime null, "updated_at" d
atetime null))
[Doctrine\DBAL\Driver\PDOException]
SQLSTATE[HY000]: General error: 17 database schema has changed
[PDOException]
SQLSTATE[HY000]: General error: 17 database schema has changed

>\>php artisan migrate
[Doctrine\DBAL\Schema\SchemaException]
There is no column with name 'user_id' on table 'components'.`

**Comment by heticor915** [comment]
I was checking #1997 @phy25  but if I just run  `php artisan migrate` I get  the same error. I was testing the same exact steps to install v2.2.2 and it works, but with this new version even if I try to update didn't work.

**Comment by GrahamCampbell** [comment]
SQLite is unfortunately a bit rubbish. Please try with a real database. :)

**Comment by heticor915** [comment]
We were thinking to move to postgres, can you @GrahamCampbell  confirm if this .env is correct  asuming that we're goint to use postgres : 

APP_ENV=production
APP_DEBUG=false
APP_URL=http://status.sample.com
APP_KEY=
DB_DRIVER=**postgres**
DB_HOST=localhost
DB_DATABASE=cachetdb
DB_USERNAME=cachet
DB_PASSWORD=secret
DB_PORT=null
DB_PREFIX=null
CACHE_DRIVER=file
SESSION_DRIVER=file
QUEUE_DRIVER=sync
CACHET_BEACON=true
CACHET_EMOJI=false
MAIL_DRIVER=log
MAIL_HOST=null
MAIL_PORT=null
MAIL_USERNAME=null
MAIL_PASSWORD=null
MAIL_ADDRESS=null
MAIL_NAME=null
MAIL_ENCRYPTION=tls
REDIS_HOST=null
REDIS_DATABASE=null
REDIS_PORT=null
GITHUB_TOKEN=null

**Comment by GrahamCampbell** [comment]
No, the driver name is pgsql. :)

**Comment by GrahamCampbell** [comment]
https://github.com/CachetHQ/Cachet/blob/2.4/config/database.php#L78

**Comment by heticor915** [comment]
Thank you @GrahamCampbell  After checking seems that the best option is move to another database.
I'm closing this.

**Comment by phy25** [comment]
Maybe we can print a warning message to console when installing with SQLite? I used that because the docs mentioned SQLite.

**Comment by jbrooksuk** [comment]
Cachet _should_ install with SQLite since that's what we use when running the tests. I don't know what had happened to @heticor915's database by the point he went to upgrade, did you do any manual modifications?

**Comment by heticor915** [comment]
@jbrooksuk No, the .env file is the same mentioned before, I was thinking to mention the part of the drivers and what's the best alternative in cachet in the official documentation

**Comment by jbrooksuk** [comment]
Postgres or MySQL 👍

**Comment by heticor915** [comment]
postgres, and change the version in the [documentation ](https://docs.cachethq.io/docs/installing-cachet) from v2.1.0 to the most stable version(v2.3.9). I would like to say Thank you because the site is up and running after a long fight :smile:
