### ISSUE TITLE
uploading images to incidents

### ISSUE THREAD

**Issue by jetie** [CachetHQ/Cachet#2274]
Would it be possible to upload images into incidents? 

Not seeing this functionality today. 

Thanks!

**Comment by GrahamCampbell** [comment]
It's not possible to upload images to Cachet, however it's certainly possible to use images if you host them yourself, or drop them into Cachet's "public" folder, for example, then include them using markdown syntax.

**Comment by jbrooksuk** [comment]
@GrahamCampbell @joecohens this would be pretty cool though! GitHub style uploads?

**Comment by GrahamCampbell** [comment]
Would be cool, but not something we support right now. I was just suggesting a workaround for now. :D

**Comment by MatthewSH** [comment]
This could easily be done with the storage with the incident id and a random name for the image name.
This could easily be displayed with a lightbox style system on the main pages or as a separate page for the incident.

Example URL: `https://cachet.example.com/storage/incidents/1/hTdf.png`


Thoughts about something like this?

**Comment by davidak** [comment]
@MatthewSH so when you use the same image in every post you have it multiple times on the server. i would put it in one directory and save it under it's current name. if the name is already existent, it should get checked if the files have the same checksum, in that case just use the existing image. else add an -# to the name like image-1.png.

**Comment by ConnorVG** [comment]
The best way to do it would not be that, in my opinion. It would make much more sense to have a media library and a media selector. Checksums on matching names seems a bit 'hacky'?

**Comment by davidak** [comment]
A media library sound good. So you could easily select one of your 5 preffered images.

Such system may have a function to deduplicate files. But people will also see that there already is that image they want to use and don't have to upload it.

**Comment by jbrooksuk** [comment]
The image URL would be in the message, so the filename doesn't matter so long as it's unique. I'd probably place them under date directories.

**Comment by ConnorVG** [comment]
There is a nice perk of media libraries not being too hard to implement too. Kunstmaan's aint too bad.

**Comment by jbrooksuk** [comment]
Kunstmaan seems overkill?

**Comment by ConnorVG** [comment]
@jbrooksuk I'm on about their media management system, not the entire thing haha.

I wouldn't pull theirs in, I am more on about how they handle it. The media library is completely separate but can be easily chosen from / added due during entity management.

**Comment by jbrooksuk** [comment]
Gotcha! 🙈

**Comment by MatthewSH** [comment]
What about this...
How about we just do a random 4-6 character string after the image name and we have some sort of media library? We can select from the media library to embed in the incident or we can upload?

Also, thoughts about using something like Glide to allow more customization?

**Comment by jbrooksuk** [comment]
@MatthewSH we could do this, yeah! Would you be happy taking this on? We could easily upload to the `public/storage` directory.

**Comment by jbrooksuk** [comment]
We should use storage from Laravel to store the imagery in https://laravel.com/docs/5.4/filesystem#the-public-disk

**Comment by Pimorez** [comment]
Now that storage is being used, is this a possibility to implement?

**Comment by jbrooksuk** [comment]
Thank you for your input on Cachet 2.x. We are shifting our attention and resources to Cachet 3.x and will no longer be supporting the 2.x version. If your feedback or issue is relevant to the 3.x series, we encourage you to engage with the new branch.

For more information on the Cachet rebuild and our plans for 3.x, you can read the announcement [here](https://github.com/CachetHQ/Cachet/discussions/4342).

We appreciate your understanding and look forward to your contributions to the new version.
