### ISSUE TITLE
You don't have permission to access / on this server.

### ISSUE THREAD

**Issue by mkok1019** [CachetHQ/Cachet#2280]
I installed cachet on my local, OSX.

I installed PHP5.5.29, MYSQL, and APACHE.

I am getting this error after db migration.
http://localhost/

Forbidden
You don't have permission to access / on this server.

@jbrooksuk, @GrahamCampbell, @joecohens Can you please let me know how to fix? Thanks.

**Comment by mkok1019** [comment]
By the way, I've tried this, but no help.

```
If you get a 500 error when visiting your status page, you may need to run chmod -R 777 storage for it to work or rm -rf bootstrap/cache/*
You can also try to give permissions to cache chmod -R 777 bootstrap/
```

**Comment by mkok1019** [comment]
I just added the virtualhost to apache httpd.conf file,  so the above issue disappeared but the page is not loading. Could you please check this screenshot?

![screen shot 2016-12-23 at 1 22 42 pm](https://cloud.githubusercontent.com/assets/12889588/21453792/1ebfdde8-c913-11e6-974a-f89f74f5e145.png)

**Comment by GrahamCampbell** [comment]
Sorry, but we don't provide setup support for Cachet. We do offer a professional install service though. You can contact us at support@alt-three.com for more information.
