### ISSUE TITLE
Metrics Re-ordering?

### ISSUE THREAD

**Issue by shaun-ba** [CachetHQ/Cachet#2282]
I would like to place my metric ID 5 above others, like there is sorting in components, can you add this ability to metrics too?

**Comment by ogghi** [comment]
Hi, I'd like to have a similar thing: I would like to have the possibility to put metrics **below** the status incidents.

**Comment by jbrooksuk** [comment]
> Hi, I'd like to have a similar thing: I would like to have the possibility to put metrics below the status incidents.

Well, @ConnorVG has written the module system in Cachet, so it should actually be possible to order these I believe?

**Comment by souni** [comment]
+1

**Comment by jbrooksuk** [comment]
Metrics are actually orderable, but not through the frontend. You need to update the `order` value in the `metrics` table.

**Comment by jbrooksuk** [comment]
Thank you for your input on Cachet 2.x. We are shifting our attention and resources to Cachet 3.x and will no longer be supporting the 2.x version. If your feedback or issue is relevant to the 3.x series, we encourage you to engage with the new branch.

For more information on the Cachet rebuild and our plans for 3.x, you can read the announcement [here](https://github.com/CachetHQ/Cachet/discussions/4342).

We appreciate your understanding and look forward to your contributions to the new version.
