### ISSUE TITLE
CSS and JS 404ing

### ISSUE THREAD

**Issue by fcpwiz** [CachetHQ/Cachet#2283]
About a week ago my [status page](https://status.fluxxmc.com) stopped displaying its CSS and JS files.

I checked and those files are in fact there in the Cachet install, but are 404ing for some reason.

<img width="1437" alt="screen shot 2016-12-27 at 11 35 41 am" src="https://cloud.githubusercontent.com/assets/2921172/21506890/9e889138-cc28-11e6-8b5c-27acc1adf545.png">

<img width="1433" alt="screen shot 2016-12-27 at 11 35 05 am" src="https://cloud.githubusercontent.com/assets/2921172/21506883/91cfbe58-cc28-11e6-80cc-b381ae4c0395.png">

**Comment by GrahamCampbell** [comment]
I can't replicate that here.

**Comment by fcpwiz** [comment]
Do you have any suggestions to what could possibly be doing this? @GrahamCampbell

**Comment by GrahamCampbell** [comment]
Since we installed Cachet for you, I've replied to your ticket on the private support system. :)
