### ISSUE TITLE
Error 500: Internal Server Error

### ISSUE THREAD

**Issue by ImFlushy** [CachetHQ/Cachet#2284]
> "What does this mean?
> Something went wrong on our servers while we were processing your request. An error has occurred and this resource cannot be displayed. This occurrence has been logged, and a highly trained team of monkeys has been dispatched to deal with your problem. We're really sorry about this, and will work hard to get this resolved as soon as possible.
> This error can be identified by bf7c08a3-c030-4ee5-a903-4875fcb23cc5. You might want to take a note of this code.
> Perhaps you would like to go to our home page?"

LIVE VERSION: http://status.ssolutiongaming.com/

Hello Developers,
I'm new to CachetHQ and i really like the design and the idea behind it!
Anyway, I'm running into problems stated above.
Sadly, I don't know how to check any logs. I have followed the documentations given in other threads.
I would be very happy if you could help me, thanks :) :+1:

**Comment by GrahamCampbell** [comment]
The logs are found in the storage/logs folder.

**Comment by ImFlushy** [comment]
Gosh... Log is 1800 lines long.

Here's the last part:
`[2016-12-28 23:39:18] production.ERROR: exception 'RuntimeException' with message 'No supported encrypter found. The cipher and / or key length are invalid.' in /var/www/Cachet/vendor/laravel/framework/src/Illuminate/Encryption/EncryptionServiceProvider.php:45
Stack trace:
#0 /var/www/Cachet/vendor/laravel/framework/src/Illuminate/Encryption/EncryptionServiceProvider.php(25): Illuminate\Encryption\EncryptionServiceProvider->getEncrypterForKeyAndCipher('srBYaXYbwClpnm6...', 'AES-256-CBC')
#1 /var/www/Cachet/vendor/laravel/framework/src/Illuminate/Container/Container.php(731): Illuminate\Encryption\EncryptionServiceProvider->Illuminate\Encryption\{closure}(Object(Illuminate\Foundation\Application), Array)
#2 /var/www/Cachet/vendor/laravel/framework/src/Illuminate/Container/Container.php(629): Illuminate\Container\Container->build(Object(Closure), Array)
#3 /var/www/Cachet/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(697): Illuminate\Container\Container->make('encrypter', Array)
#4 /var/www/Cachet/vendor/laravel/framework/src/Illuminate/Container/Container.php(849): Illuminate\Foundation\Application->make('Illuminate\\Cont...')
#5 /var/www/Cachet/vendor/laravel/framework/src/Illuminate/Container/Container.php(804): Illuminate\Container\Container->resolveClass(Object(ReflectionParameter))
#6 /var/www/Cachet/vendor/laravel/framework/src/Illuminate/Container/Container.php(775): Illuminate\Container\Container->getDependencies(Array, Array)
#7 /var/www/Cachet/vendor/laravel/framework/src/Illuminate/Container/Container.php(629): Illuminate\Container\Container->build('Illuminate\\Cook...', Array)
#8 /var/www/Cachet/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(697): Illuminate\Container\Container->make('Illuminate\\Cook...', Array)
#9 /var/www/Cachet/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(152): Illuminate\Foundation\Application->make('Illuminate\\Cook...')
#10 /var/www/Cachet/public/index.php(57): Illuminate\Foundation\Http\Kernel->terminate(Object(Illuminate\Http\Request), Object(Illuminate\Http\Response))
#11 {main} {"identification":{"id":"09cfee38-5a81-4188-8f9a-f37bd093ddd1"}} `

**Comment by GrahamCampbell** [comment]
Looks like you didn't run the install process correctly.

**Comment by GrahamCampbell** [comment]
Make sure there's an encryption key set in the `.env` file (not `.env.example`), and then run `php artisan app:update`.

**Comment by GrahamCampbell** [comment]
If you're not able to get it working, we do offer a paid installation service. You can reach us at support@alt-three.com. :)
