### ISSUE TITLE
Proposal to remove per-component subscriptions

### ISSUE THREAD

**Issue by jbrooksuk** [CachetHQ/Cachet#2286]
In reference to https://twitter.com/cachethq/status/814868830522667008 this is a proposal to remove the per-component subscriptions. Removing of per-component subscriptions will:

1. Tidy up the subscription implementations
2. Allow us to switch to a new notification system I've been working on https://twitter.com/cachethq/status/814546709065961472 - this system supports Mail, Nexmo (SMS) and Slack. The new system will allow us to further add channels such as Twitter, Facebook, Twilio etc.
3. Simplify what the customer is seeing. To manage their subscriptions they need to find the email from the last notification or confirmation as there is no secure way of managing without the verification code.

To me, 2 & 3 are the most important parts here and whilst I understand that bigger status pages will have a lot of components that their users generally aren't interested in, we need to be providing features that can be used by a wider audience.

In the future we may be able to re-implement per-component subscriptions, but first we need to nail the UX and channel integrations.

**Comment by mm-manageit** [comment]
I would vote against removing the per component subscriptions. The end users are the most important users of a status page, and they will opt-out and not use it, if they are forced to be sent notifications for components they don't care about.

**Comment by jbrooksuk** [comment]
Okay, so the Twitter poll concluded (closely) that we won't be removing it. This does mean that we'll need a better way of handling per-component subscriptions.
