### ISSUE TITLE
Add SAML authentication support

### ISSUE THREAD

**Issue by sidewinder12s** [cachethq/Cachet#229]
Support for SAML authentication and user management for integration with products like https://shibboleth.net/.

**Comment by jbrooksuk** [comment]
Once #196 is in, we can look at extending it with SAML.

**Comment by sidewinder12s** [comment]
Thanks, Seems like a lot of LDAP auth is switching to SAML type solutions going forward.

**Comment by jbrooksuk** [comment]
I've never used LDAP or SAML in an application, are they widely used?

**Comment by sidewinder12s** [comment]
I would fathom from what I've set up that LDAP is the most used common authentication system (Maybe other than Active directory/Kerberos, depending on how it's connected, since it could be actual AD or Kerberos auth or it can be LDAP on top of AD/Kerberos). SAML is the preferred auth mechanism going forward where I work because it is single sign on and federated. 

There are a lot of shibboleth integrations you might be able to easily integrate, one I found was simpleSAMLphp. But I haven't coded much or web applications so I'm not sure haha.

**Comment by sidewinder12s** [comment]
Another way you could do this is to allow a web server to send headers to Cachet with something like REMOTE_USER and REMOTE_USER_GROUPS and let apache deal with the auth.

**Comment by jbrooksuk** [comment]
@sidewinder12s the second suggestion would make creating users harder :)

**Comment by jbrooksuk** [comment]
This isn't something we'll likely be supporting.

**Comment by helhindi** [comment]
@jbrooksuk - Thanks to you and the team for your great work.
LDAP would allow the tool to be used in larger organisations where SSO, user/role based auth is the norm (most orgs with > 10 people).
Adding support for LDAP/SAML would certainly make Cachet a viable choice for those orgs. I imagine the majority of those with a requirement to keep users\clients updated via Cachet are likely to be larger in size/operation (as in our case).
Is there anything we can do to have this considered / on the road map at all?

**Comment by jbrooksuk** [comment]
> Thanks to you and the team for your great work.

It's our pleasure!

> LDAP/SAML would allow the tool to be used in larger organisations where SSO, user/role based auth is the norm (most orgs with > 10 people). Adding support for LDAP/SAML would certainly make Cachet a viable choice for those orgs. I imagine the majority of those with a requirement to keep users\clients updated via Cachet are likely to be larger in size/operation (as in our case).

True.

> Is there anything we can do to have this considered / on the road map at all?

None of us have access to an LDAP/SAML server to integrate this, plus 2.0 is a stepping stone to 3.0 which will essentially be an overhaul of every piece of the system. We'll likely revisit this then, at least one way or another.

**Comment by helhindi** [comment]
@jbrooksuk - Thanks ever so much for looking into this James.
We will certainly look forward to these great new additions to this useful application.
I may PM you to see if an LDAP server can be made available (for your testing if that helps).
All the best and many thanks
helhindi

**Comment by sachinaher** [comment]
@jbrooksuk, Cachet is good product for status dashboard and really helpful for my projects.
Is SAML authentication going to be implemented in upcoming versions?
It will definitely help companies with large number of users.
Thanks.

**Comment by jbrooksuk** [comment]
https://github.com/CachetHQ/Cachet/issues/2108

It'll probably come along with the LDAP support 👍

**Comment by RedPepper** [comment]
Hi,

there seems not much activitiy regarding this issue any chance to upvote this as our company requires this to use Cachet to its full potential
