### ISSUE TITLE
Dashboard

### ISSUE THREAD

**Issue by JustMaffie** [CachetHQ/Cachet#2292]
Hey, I just installed Cachet on my status page: https://status.justmaffie.nl
But when I go into the dashboard, I don't think all the features are there, why is this?

- JustMaffie

**Comment by JustMaffie** [comment]
When I go to https://status.justmaffie.nl/dashboard/settings it gives me error 405 method not allowed.

**Comment by GrahamCampbell** [comment]
Looks correct? The correct URL for the setting page is  https://status.justmaffie.nl/dashboard/settings/setup. (setup is the name of the first tab on the settings page).

**Comment by JustMaffie** [comment]
Ok, but its not in the side navigation bar.

**Comment by GrahamCampbell** [comment]
What version please. The current 2.3 branch works fine for me (or the very latest v2.3.10 tag)? That's the version I'd recommend installing for now. The master is still not ready for release.

**Comment by JustMaffie** [comment]
2.10

**Comment by JustMaffie** [comment]
Updating to the latest version as we speak.

**Comment by JustMaffie** [comment]
Got it fixed.

**Comment by jbrooksuk** [comment]
👍🏻
