### ISSUE TITLE
Subscription Management Proposal

### ISSUE THREAD

**Issue by MikeKMiller** [CachetHQ/Cachet#2293]
In response to the recent proposal to remove per component subscriptions, and subsequent vote against it.   The need still remains to simplify the subscription handling.

I am proposing the following:

1. Add a column to the 'subscriptions' table, named 'type', which will be future filled with the type (email, sms, slack, twitter, facebook, etc..)

2.  Add a table named 'subscription_notifications', which will hold notifications that need to go out for an event, and a log of what was sent, and when (columns= id, event_id, subscriber, type, added(datetime) status, status_changed(datetime)) 'status' could contain (pending, sent, undeliverable, etc...., or numeric codes for those)

3. Create a single page, that is linked from top or bottom of StatusPage, to enter email. Then email sent to verify, user clicks link, then can View/Change/Remove Subscriptions, and View History of Notifications sent.

4. System User, be added as a default subscriber to handle notifications to Slack, Twitter, etc..

Does this sound like it would work? I have not reviewed all code surrounding the subscriptions, but feel this layout would allow the notifications system to move forward without major rewrites.

**Comment by jbrooksuk** [comment]
In regards to step 3, how would people manage notifications from say SMS where lack of size means ideally we can't send two URLs to the incident and unsubscribe.

**Comment by jbrooksuk** [comment]
Maybe for SMS we send an initial text that says you can visit this link to unsubscribe? We can simplify the unsub link to `/notifications/{code}/unsubscribe`?

**Comment by mm-manageit** [comment]
Just use a (Reply Stop) to unsubscribe, or an initial link with the subscription

**Comment by jbrooksuk** [comment]
Replying isn't something we could simply integrate into a self-hosted version as you'd have to integrate with the SMS provider. In a SaaS version that would be 👌

**Comment by mm-manageit** [comment]
Hmmm, well if someone is integrating with Nexmo, Twilio, etc.. they will have to have an account with it, and for either, you would just have setup the callback URL for when a SMS is received, could be something that a simple tutorial could cover.

**Comment by mm-manageit** [comment]
Then in the code:
if(strtolower($sms_content) == 'stop'){
// Find DB row in 'subscribers' where number equals sender number for the ID
//  Find in 'subscriptions' all the subscriptions, if just one, remove them, otherwise send link to management page. 
(i.e.. "We noticed you are subscribed to multiple items, click the link to manage subscriptions : {link} )
}

On the Subscrition Management Page, may have three buttons at the top [Unsubscribe All SMS], Unsubscribe All Email]. [Unsubscribe All]. The SMS, and Email only showing if they have a subscription showing for that format, and the All button

**Comment by jbrooksuk** [comment]
Thank you for your input on Cachet 2.x. We are shifting our attention and resources to Cachet 3.x and will no longer be supporting the 2.x version. If your feedback or issue is relevant to the 3.x series, we encourage you to engage with the new branch.

For more information on the Cachet rebuild and our plans for 3.x, you can read the announcement [here](https://github.com/CachetHQ/Cachet/discussions/4342).

We appreciate your understanding and look forward to your contributions to the new version.
