### ISSUE TITLE
No Subscribe button

### ISSUE THREAD

**Issue by AleksejsC** [CachetHQ/Cachet#2294]
Hi,
I have deployed version 2.3.10 on Ubuntu 16.04. Set up mailgun account and checked that emails are working buy inviting team member in dashboard. "Allow people to signup to email notifications?" is set, but still no "Subscribe" button. 
Thank you!

**Comment by jbrooksuk** [comment]
Try running `rm -rf bootstrap/cache{,t}/*`.

**Comment by AleksejsC** [comment]
thank you for fast response. But it still does not work.

**Comment by jbrooksuk** [comment]
Can you share your `.env` `MAIL_*` settings please (remember to obscure the password).

**Comment by AleksejsC** [comment]
MAIL_DRIVER=mailgun
MAIL_HOST=smtp.mailgun.org
MAIL_PORT=587
MAIL_USERNAME=sandbox558e795cc6014a31a44ba72a77bda4a5.mailgun.org
MAIL_PASSWORD=key-6be*****************************
MAIL_ADDRESS=postmaster@sandbox558e795cc6014a31a44ba72a77bda4a5.mailgun.org
MAIL_NAME=null
MAIL_ENCRYPTION=tls

As I said it just works fine for team member invitation.

**Comment by jbrooksuk** [comment]
`MAIL_FROM` has to be set for subscribers to be enabled 👍

**Comment by AleksejsC** [comment]
Thank you! just set MAIL_NAME and it works!

**Comment by jbrooksuk** [comment]
In v2.4 I think we'll default this value to `notify@APP_URL`.
