### ISSUE TITLE
Resolve incident button

### ISSUE THREAD

**Issue by jbrooksuk** [CachetHQ/Cachet#2296]
We need a quick way to resolve incidents, perhaps a button on the incidents page that says "Resolve". Maybe the dashboard index shows a list of unresolved incidents?

**Comment by AleksejsC** [comment]
would be great if it also could send notifications to subscribers that incident is now resolved.

**Comment by jbrooksuk** [comment]
Yep! This will happen automatically :)

**Comment by MatthewSH** [comment]
Would also be nice to have an automatic edit to the issue to add a section like....
```
### Resolved
Resolution comment.
```

The button can easily be added to the incidents view.
