### ISSUE TITLE
Subscribers not recieving verification mail

### ISSUE THREAD

**Issue by eladbitton** [CachetHQ/Cachet#2298]
Hi.

I installed cachet on ubuntu 14.04 and my subscribers does not receive any verification mail(including me). 

My current mail config:
```
MAIL_DRIVER=mailgun
MAIL_HOST=smtp.mailgun.org
MAIL_PORT=587
MAIL_USERNAME=MY-DOMAIN.com
MAIL_PASSWORD=MY-PASSWORD
MAIL_ADDRESS=notifications@MY-DOMAIN.com
MAIL_NAME="MY-COMPANY-NAME"
MAIL_ENCRYPTION=tls
```

Tried many variations of this configuration and still no mail is sending out of the system.

On my laravel logs this may be related:
```
[2017-01-04 09:35:18] production.WARNING: exception 'Symfony\Component\HttpKernel\Exception\HttpException' in /v
ar/www/Cachet/app/Http/Middleware/Authenticate.php:51
```
Saw other issues of this problem and nothing worked for me.

What can i do?

**Comment by jacoblw** [comment]
@eladbitton for `MAIL_PASSWORD` are you using your Mailgun password or the API key (from https://mailgun.com/app/domains/${your_domain})?

**Comment by jbrooksuk** [comment]
What is `QUEUE_DRIVER` set to? https://docs.cachethq.io/docs/configuring-the-queue

**Comment by eladbitton** [comment]
QUEUE_DRIVER is set to database. also tried sync and it didn't work. MAIL_PASSWORD is set to the api key. Any other suggestions?

**Comment by eladbitton** [comment]
Also when i am trying to run:
`sudo php artisan app:update`
I get this error:
```
Successfully dumped mysql, compressed with gzip and store it to local at /var/www/Cachet/database/backups/2017-0
1-04 16.06.12
Backup completed!
Configuration cache cleared!
Configuration cached successfully!
Route cache cleared!
Routes cached successfully!
Copied Directory [/vendor/roumen/feed/src/views] To [/resources/views/vendor/feed]
Publishing complete for tag []!
                         
  [PDOException]         
  could not find driver  
                        
```

**Comment by GrahamCampbell** [comment]
The error is self explanatory is it not? You've not installed the pdo extension for mysql, so PDO is telling you it doesn't have that driver.

**Comment by eladbitton** [comment]
Ye i wrote that it is now fixed. Right now what i am seeing in my laravel log:
`[2017-01-04 16:55:02] production.ERROR: PDOException: could not find driver in /var/www/Cachet/vendor/laravel/fr
amework/src/Illuminate/Database/Connectors/Connector.php:55`

Any suggestions?

**Comment by GrahamCampbell** [comment]
That is the same error.

**Comment by GrahamCampbell** [comment]
> could not find driver

**Comment by GrahamCampbell** [comment]
> telling you it doesn't have that driver.

**Comment by GrahamCampbell** [comment]
> The error is self explanatory is it not? You've not installed the pdo extension for mysql, so PDO is telling you it doesn't have that driver.

**Comment by eladbitton** [comment]
PDO is installed and enabled.
When I am running `php -i | grep PDO`
This is why i am getting:
`PDO
PDO support => enabled
PDO drivers => mysql, sqlite
PDO Driver for MySQL => enabled
PDO Driver for SQLite 3.x => enabled`
