### ISSUE TITLE
Mails not translated

### ISSUE THREAD

**Issue by karaktaka** [CachetHQ/Cachet#2299]
Since the latest commit, Mails are not being translated and are always send in english.

It also does affect every languages as it doesn't matter which language I switch to.

**Comment by karaktaka** [comment]
I use the main branch 2.4.
It worked before, so I'm not sure if this is related to laravel or did you updated it aswell?

**Comment by karaktaka** [comment]
Maybe this happens, because you moved away from the custom mail templating and using laravals notifications instead?

**Comment by karaktaka** [comment]
Nevermind. I just found out, that the file ressources/lang/de/nofitifactions.php is missing or not yet created.
I'm creating one know and testing it in my installation.

**Comment by jbrooksuk** [comment]
It's a new file.

Please note that you are on the dev build. Translations come later.
