### ISSUE TITLE
Move all static text into the language file

### ISSUE THREAD

**Issue by jbrooksuk** [cachethq/Cachet#230]
There is still a lot of static text within the view and controller files. Whilst there has been a lot of work going into moving the text, there is still **a lot more** to move.

- Controllers
- Views

We may actually want to split the `cachet.php` language file into multiple files:

- [ ] `cachet.php` - general Cachet strings (status levels, titles etc)
- [ ] `setup.php`
- [ ] `dashboard.php`
- [ ] `forms.php`

This may cause some annoyances for the translators as I don't think CrowdIn will copy the translations that we already have, however it'll benefit us all after the initial pain.

**Comment by joecohens** [comment]
:+1:

**Comment by jbrooksuk** [comment]
We may be able to pull the string out into different files, then upload a revision to CrowdIn for each language - this will help?

**Comment by Crash--** [comment]
Do you already have a branch with some work concerning this issue? When I created the view for editing an incident I saw some plain text in views  without the use of {{trans... 

So how can we contribute on this one?

**Comment by jbrooksuk** [comment]
Nope, this can be done by anyone at the moment. Essentially anywhere that there is plaintext (perhaps, except for API errors), we should be using `trans`.

**Comment by jbrooksuk** [comment]
Closed by #267.
