### ISSUE TITLE
Rename some terms via. admin console

### ISSUE THREAD

**Issue by absolutejam** [CachetHQ/Cachet#2302]
Hey guys,

I love the project and I've been using it internally for our IT network status, and we're hoping to make a push to use it as our primary method of updating staff and students. 

As I've been using CachetHQ, it struck me that the system would be great for non-technical news too. I realise this is likelyway outside the scope and desires of the project, but I wondered if there was potentially a way to make some of the terms more generic, eg. the ability to rename 'incidents' to 'news'. I've been looking for a similar thing for non-technical means and had some requests from our customers to the same degree.

Feel free to tell me this is not inline with the project and to fork it and work it out myself, but I just wanted to pass on the praise and ask the question.

Regards,
James.

**Comment by ConnorVG** [comment]
To be fair, when it comes to just the 'names', as it where, you could always just provide a custom translation?

**Comment by absolutejam** [comment]
Oh, I hadn't even considered this. That sounds like a fine option for me - Is there some documentation on getting started with the translations?

**Comment by jbrooksuk** [comment]
I've never thought about it but I could see Cachet being used for non-technical updates however, it's not and likely won't be within the remit of this project.

That said, you could easily update the language files and rename Incident to News for example.

**Comment by jbrooksuk** [comment]
That was weird, GitHub didn't update to show @ConnorVG or @absolutejam's comments.
