### ISSUE TITLE
Feature request: End time for Maintenance

### ISSUE THREAD

**Issue by zobelhelas** [CachetHQ/Cachet#2304]
Currently one is asked to set **_When to schedule the maintenance for?_**, which I would consider a time window rather then a start time. It would be very handy for me if i would be able to either set a time window or an additional end time.

**Comment by jbrooksuk** [comment]
Does it help that we now have a completion time in v2.4?

![](https://cldup.com/nNl07NHKja.png)

**Comment by zobelhelas** [comment]
yes! :thumbsup:

Sorry, i am running on latest stable tag, which is 2.3.10 so i didn't see that feature....

**Comment by jbrooksuk** [comment]
That's okay. v2.4 is still in development, I wouldn't advise switching.

**Comment by calvinbui** [comment]
Has this been removed? I'm seeing it on the [latest commit](https://github.com/CachetHQ/Cachet/commit/47000c999bbe8e1ba22782c9bcee34b296828e73) on the 2.4 branch.
