### ISSUE TITLE
Laravel key length issues in Cachet 2.3.9

### ISSUE THREAD

**Issue by max-l-weaver** [CachetHQ/Cachet#2307]
Hi,

OS: Ubuntu 16.04
php version: 7.1.0

I am getting a persistent error with Laravel.

Here is the latest entry in `storage/logs/laravel-2017-01-10.log`

`[2017-01-10 12:42:41] production.ERROR: RuntimeException: The only supported ciphers are AES-128-CBC and AES-256-CBC with the correct key lengths. in /var/www/Cachet/bootstrap/cache/compiled.php:13496
Stack trace:
#0 /var/www/Cachet/bootstrap/cache/compiled.php(7910): Illuminate\Encryption\Encrypter->__construct('\x8A\x07\xDA\x84\xA8\xFE\xB6\x16\x9D\x9B\xD7\x19\xB2S\f...', 'AES-256-CBC')
#1 /var/www/Cachet/bootstrap/cache/compiled.php(1477): Illuminate\Encryption\EncryptionServiceProvider->Illuminate\Encryption\{closure}(Object(Illuminate\Foundation\Application), Array)
#2 /var/www/Cachet/bootstrap/cache/compiled.php(1433): Illuminate\Container\Container->build(Object(Closure), Array)
#3 /var/www/Cachet/bootstrap/cache/compiled.php(2011): Illuminate\Container\Container->make('encrypter', Array)
#4 /var/www/Cachet/bootstrap/cache/compiled.php(1534): Illuminate\Foundation\Application->make('encrypter')
#5 /var/www/Cachet/bootstrap/cache/compiled.php(1511): Illuminate\Container\Container->resolveClass(Object(ReflectionParameter))
#6 /var/www/Cachet/bootstrap/cache/compiled.php(1497): Illuminate\Container\Container->getDependencies(Array, Array)
#7 /var/www/Cachet/bootstrap/cache/compiled.php(1433): Illuminate\Container\Container->build('Illuminate\\Cook...', Array)
#8 /var/www/Cachet/bootstrap/cache/compiled.php(2011): Illuminate\Container\Container->make('Illuminate\\Cook...', Array)
#9 /var/www/Cachet/bootstrap/cache/compiled.php(2529): Illuminate\Foundation\Application->make('Illuminate\\Cook...')
#10 /var/www/Cachet/public/index.php(57): Illuminate\Foundation\Http\Kernel->terminate(Object(Illuminate\Http\Request), Object(Illuminate\Http\Response))
#11 {main} {"identification":{"id":"20e982db-dda0-41c8-bb92-93c0d9a7c456"}}`

I have re-generated key using `php artisan key:generate` numerous times
Looking in `.env` everything looks fine. There are no spaces in APP_KEY.

I have also `chmod -R 777 storage` and `chmod -R 777 bootstrap` and cleared the config cache.

Does Cachet support php 7.1?

**Comment by max-l-weaver** [comment]
update: Just tried re-installing with php7.0 and it worked fine, so guessing no compatibility with 7.1

**Comment by jbrooksuk** [comment]
Ping @GrahamCampbell

**Comment by dimacus** [comment]
Was this issue ever fixed? I'm having issues with latest code from https://github.com/CachetHQ/Docker and getting the same error
