### ISSUE TITLE
Live status by ping, etc.

### ISSUE THREAD

**Issue by Bluscream** [CachetHQ/Cachet#2308]
Why would you have to report outages manually?

**Comment by jbrooksuk** [comment]
Why wouldn't you? Not all outages can be monitored.

**Comment by GrahamCampbell** [comment]
You don't "have" to, if that was the question. :)

You can do it through the web interface if you want, but you can also programmatically report issues to cachet from your monitoring software using our API.

**Comment by Bluscream** [comment]
No I was talking about example scenario:

- I want to monitor google.com so I add it to the components
- it pings google.com every minute and when the response is "connection timed out" it automatically shows it as outage

**Comment by jbrooksuk** [comment]
Oh, in which case there are several integrations you can find here https://docs.cachethq.io/docs/addons

**Comment by Bluscream** [comment]
Now we're talking. Thanks :)
