### ISSUE TITLE
Installation/Setup not working

### ISSUE THREAD

**Issue by matematrix** [CachetHQ/Cachet#2309]
I followed the setup manual on your website, and I got no errors.
But when I want to open /cachet/setup in my web browser, I get an 404 error, and when I look for the directory via FTP, it is indeed missing.

I hope that you can help me, thanks in advance.

**Comment by jbrooksuk** [comment]
You shouldn't be installing Cachet under a sub-directory. Assuming you're using Apache, you need to be setting a VHOST.

We offer a professional support service that you can use by emailing support@alt-three.com

**Comment by GrahamCampbell** [comment]
> and when I look for the directory via FTP, it is indeed missing.

Yeh, that's not how routing works.
