### ISSUE TITLE
Automatically download and integrate translations from Crowdin

### ISSUE THREAD

**Issue by wfjsw** [CachetHQ/Cachet#2311]
The translation progress seems much too slow than release. Currently, the translation files are locked-down on release. However the translation progress may not completed so it is difficult for end user to get a fully localized one.
So I would like to request a feature that with Crowdin's API, translated files can be updated on install or upon user request. New translations with fixes therefore can be applied even after releases.

What do your guys think?
Thank you for your awesome project!

**Comment by jbrooksuk** [comment]
This would be _very_ nice, but before we can do that we'd likely need to move the translations into the database or have a system for linking them back up as after upgrading Cachet, you'll have lost those files.

**Comment by MatthewSH** [comment]
@jbrooksuk which files are you talking about specifically?

**Comment by jbrooksuk** [comment]
`./resources/lang` then anything which isn't `en-US`.

**Comment by jbrooksuk** [comment]
@GrahamCampbell this might be something else we want to proxy through Beacon too... We wouldn't want to expose a key for CrowdIn.

**Comment by wfjsw** [comment]
Also you may want to cache it, as there is some usage limit on Crowdin side.

**Comment by jbrooksuk** [comment]
CrowdIn automatically updates for us now.
