### ISSUE TITLE
Overview of How It Works

### ISSUE THREAD

**Issue by pjmayhew** [CachetHQ/Cachet#2312]
I like the documentation. It is concise and quite complete. But since I am new to the 'metrics' game, and open source I wonder if you could briefly tell me how it all fits together...

There are a lot of moving pieces: I assume, we use http calls to Get data from a service we have 
>>> then use http to update thru the Cachet API? I assume the database contains this data, but how does it get put there?

I couldn't find this type of overview anywhere...any ideas?

Thanks much

**Comment by jbrooksuk** [comment]
I'm not sure if you're confused about how Cachet works or how to connect to Cachet? If it's the latter then you'll want to look into connecting to a JSON API.
