### ISSUE TITLE
Error Running Composer Commands

### ISSUE THREAD

**Issue by TheoBearman** [CachetHQ/Cachet#2313]
When trying to run `composer install -o` command following the recent dependency update 02fe8d1, the following error is thrown in the console:

```
[ErrorException]
Undefined index: hash
```
![efes](https://cloud.githubusercontent.com/assets/6546590/21966132/bbb1fb54-db65-11e6-9b4f-c70b2e2d5176.JPG)

**Comment by GrahamCampbell** [comment]
Please run `composer self-update`.

**Comment by TheoBearman** [comment]
>Please run `composer self-update`.

```
[InvalidArgumentException]
Command "self-update" is not defined.
```

**Comment by GrahamCampbell** [comment]
Seems like there's something wrong with your composer. Try running the command in a directory where there is no composer.json file.

It should behave like this:

![image](https://cloud.githubusercontent.com/assets/2829600/21966934/0c39d84e-db75-11e6-986a-7c434f428623.png)

(or indeed, show the stable channel)
