### ISSUE TITLE
Subscribers retain their component subscription

### ISSUE THREAD

**Issue by friponneau** [CachetHQ/Cachet#2315]
If I subscribe an email, un-subscribe it, then subscribe it again, I'm registered twice every for components.

Here's an excerpt of the metrics that are sent back. Please note that the "subscriptions" array has several entries with the same "component_id".

{
"id": 2,
"email": "xxxx@hotmail.com",
"verify_code": "xxxx",
"verified_at": "Monday 16th January 2017 09:48:41",
"created_at": "2017-01-16 09:47:39",
"updated_at": "2017-01-16 09:48:41",
"global": true,
"subscriptions": [
{
"id": 21,
"subscriber_id": 2,
"component_id": 1,
"created_at": "2017-01-16 14:36:46",
"updated_at": "2017-01-16 14:36:46"
},
{
"id": 22,
"subscriber_id": 2,
"component_id": 2,
"created_at": "2017-01-16 14:36:46",
"updated_at": "2017-01-16 14:36:46"
},
{
"id": 23,
"subscriber_id": 2,
"component_id": 3,
"created_at": "2017-01-16 14:36:46",
"updated_at": "2017-01-16 14:36:46"
},
{
"id": 24,
"subscriber_id": 2,
"component_id": 4,
"created_at": "2017-01-16 14:36:46",
"updated_at": "2017-01-16 14:36:46"
},
{
"id": 25,
"subscriber_id": 2,
"component_id": 1,
"created_at": "2017-01-16 14:38:35",
"updated_at": "2017-01-16 14:38:35"
},
{
"id": 26,
"subscriber_id": 2,
"component_id": 2,
"created_at": "2017-01-16 14:38:35",
"updated_at": "2017-01-16 14:38:35"
},
{
"id": 27,
"subscriber_id": 2,
"component_id": 3,
"created_at": "2017-01-16 14:38:35",
"updated_at": "2017-01-16 14:38:35"
},
{
"id": 28,
"subscriber_id": 2,
"component_id": 4,
"created_at": "2017-01-16 14:38:35",
"updated_at": "2017-01-16 14:38:35"
},
{
"id": 29,
"subscriber_id": 2,
"component_id": 1,
"created_at": "2017-01-16 14:47:39",
"updated_at": "2017-01-16 14:47:39"
},
{
"id": 30,
"subscriber_id": 2,
"component_id": 2,
"created_at": "2017-01-16 14:47:39",
"updated_at": "2017-01-16 14:47:39"
},
{
"id": 31,
"subscriber_id": 2,
"component_id": 3,
"created_at": "2017-01-16 14:47:39",
"updated_at": "2017-01-16 14:47:39"
},
{
"id": 32,
"subscriber_id": 2,
"component_id": 4,
"created_at": "2017-01-16 14:47:39",
"updated_at": "2017-01-16 14:47:39"
}
]
}

Also, you can see the problem in the subscribers page (see attached file)

![image](https://cloud.githubusercontent.com/assets/3298261/21996162/dee95d4c-dbf6-11e6-9d39-fcc02d733889.png)

**Comment by jbrooksuk** [comment]
What version are you using? You're experiencing a lot of issues that we've not seen before.

**Comment by friponneau** [comment]
![image](https://cloud.githubusercontent.com/assets/3298261/21997886/af24ffa4-dbff-11e6-9666-a7d6a798164d.png)

**Comment by jbrooksuk** [comment]
Ping @joecohens

**Comment by jbrooksuk** [comment]
This is now fixed 😄
