### ISSUE TITLE
Subscribers receive too much emails

### ISSUE THREAD

**Issue by friponneau** [CachetHQ/Cachet#2316]
The context is:

A cachet page that monitors the state of a service.
The service availability is verified every 10 minutes, and the cachet component is updated with the value.
Subscribers want to be warned whenever the service changes state.
Currently, the user is warned whenever the component state is updated, regardless of the value.

Solution: send notification email only when new information is available (for example: the component state is updated with a different status than the current one).

Workaround: update the component only when the value has actually changed. The problem with this is that the person looking at the component has no way of knowing the state of the service was actually monitored.

**Comment by jbrooksuk** [comment]
This is really by design. The more configurability we add, the harder the implementation becomes to maintain and for the user to manage their preferences.

**Comment by friponneau** [comment]
I understand.  However, isn't the trade-off between "not updating the component" and "not knowing the component was confirmed" a bit hard to make?  In other words, to eliminate email spamming we have to let user wonder whether "the component status is accurate", or if "the watchdog that updates it stopped functioning"...  For users counting on the cachet page to accurately reflect the reality of SaaS nodes, being able to make the difference between "node is operational as of xyz" and "component status wasn't updated since xyz" is somewhat important.

**Comment by jbrooksuk** [comment]
How about, we add a `silent` parameter to the Component API, so that if it's `true` we don't send notifications.

**Comment by friponneau** [comment]
That would be perfect.
