### ISSUE TITLE
Subscribers email sent even when subscriber has been removed

### ISSUE THREAD

**Issue by friponneau** [CachetHQ/Cachet#2317]
I removed a subscriber from the subs list on friday, and he kept receiving notification emails during the week-end.

**Comment by jbrooksuk** [comment]
You removed him from the `subscribers` table and he was still receiving them?

**Comment by friponneau** [comment]
Yes.  But the darnedest thing is, I had two subscribers: me (added first), and another guy.  The problem manifested itself with the other guy, but not with me.  I hesitated before submitting this one up because of the weirdness of it, but it occurred to me that someone with intimate knowledge of the source code might make something out of it.

**Comment by jbrooksuk** [comment]
What's really weird about this is that we're not caching the subscribers list, so there's no obvious way as to how we're sending emails to them too.

**Comment by jbrooksuk** [comment]
Ping @joecohens any ideas?

**Comment by jbrooksuk** [comment]
I've not been able to replicate this issue, sorry! If you can give me steps to reproduce, I'll look into this again.

If you're using the queue driver I can only suggest restarting the workers.
