### ISSUE TITLE
Sessions table gets full quickly

### ISSUE THREAD

**Issue by jbrooksuk** [cachethq/Cachet#232]
@SamuelMoraesF has reported that the sessions table gets full very quickly, at least on Heroku. He's had an ema to say that the free PgSql database is almost full. 

This is a high priority but IMHO. 

What's the solution? Don't use a table for sessions?

**Comment by GrahamCampbell** [comment]
We can use apc for sessions. :)

**Comment by jbrooksuk** [comment]
Let's do that then!
