### ISSUE TITLE
IDEA: Insert Twitter Integration

### ISSUE THREAD

**Issue by ImFlushy** [CachetHQ/Cachet#2320]
Just a quick idea (tried to use the search tool to find if someone posted it, but not really sure if someone had the idea before):

Wouldn't it be cool to automaticaly post predefined messages when the status of a server is changed by using the Twitter API?

**Comment by jbrooksuk** [comment]
Yeah! This is on its way to being implemented with the new Notifications system that is coming in v2.4

Feel free to add a PR!
