### ISSUE TITLE
Component Update email templates

### ISSUE THREAD

**Issue by amann717** [CachetHQ/Cachet#2321]
Can these email templates be modified in anyway in the code? I can't seem to find them anywhere . It looks like some type of NexmoMessage is being used.

**Comment by jbrooksuk** [comment]
You need to change the language file `./lang/:code/notifications.php`.

**Comment by amann717** [comment]
I actually want to add a banner to the incident email and make some text changes. Does not look like I am able to that in the lang files.

**Comment by jbrooksuk** [comment]
You're looking for `./resources/views/vendor/notifications/*` :)

**Comment by amann717** [comment]
I dont see the vendor folder in the code: https://github.com/CachetHQ/Cachet/tree/2.4/resources/views

**Comment by jbrooksuk** [comment]
Hmm, looks like I've not committed. This will arrive tonight.

**Comment by amann717** [comment]
Awesome!

**Comment by jbrooksuk** [comment]
Added in https://github.com/CachetHQ/Cachet/commit/268d54d2173e0c18049133a8eecf5f6c592608de
