### ISSUE TITLE
Issue: "Some systems are experiencing issues" when incidents solved via API

### ISSUE THREAD

**Issue by pbmzero** [CachetHQ/Cachet#2322]
System is getting stuck on "Some systems are experiencing issues" if i use the API to solve an incident, but it does not seem to be the case through the web interface.

Pre-Conditions
1. I have all my components available state
2. Deleted all incidents so there are none.
3. "All systems operational" on dashboard.

Create An incident through API
1. Update one component as "Major Outage"
2. Create an Incident associated with same component as Identified

Close the Incident Via API
1. Update the component to be Online
2. Update Incident to be Fixed

Result:
1. All Components Available
2. The one ticket i had is Fixed
3. On the dashboard "Some systems are experiencing issues" despite all the systems being operational and the one ticket fixed.

Alternate Case:
If I perform the same steps through the website, but not the API, Result step 3 is "All Systems Operational"

I'm either doing something wrong through the API or there might be an API related issue.

**Comment by jbrooksuk** [comment]
Are you using v2.4?

**Comment by pbmzero** [comment]
I'm using v2.4.0-dev from Monday.

**Comment by jbrooksuk** [comment]
Did you upgrade from v2.3?

**Comment by pbmzero** [comment]
@jbrooksuk  no sir, fresh install.  I just started using this software.  As a work around, i'm no only problematically opening the incidents and then manually closing them. 


I tried updating incidents only directly in the component itself, however this is also problematic as the email templates for component changes the email contains the header with literally the name of the variable "Notification.component.status_update.mail.title" instead of the value of in the email header, so it wasn't too user friendly.  Seems i have to stick with Incidents until i can figure that out.

**Comment by jbrooksuk** [comment]
Thanks @pbmzero!

I'll take a look into this issue.

You know that you're using v2.4 which is a development build, right? I've fixed the component status subject 👍

**Comment by pbmzero** [comment]
I realize i installed -dev after the fact,  i will switch to something in the -main shortly. Thanks for addressing the component status thing.

**Comment by jbrooksuk** [comment]
I've just fixed an issue that _might_ fix the component status :)

**Comment by jbrooksuk** [comment]
Thanks for reporting this.

**Comment by Thomvaill** [comment]
Hello,
I have the same issue with Cachet's Docker image v2.3.15 (`cachethq/docker:2.3.15`).
For what version has this bug been fixed?
By the way, the Docker images don't seem to be up to date, is it normal?

**Comment by chreck** [comment]
You can swipe up the non fixed incidents to remove the message. Described here https://github.com/CachetHQ/Cachet/issues/2241#issuecomment-713402690
