### ISSUE TITLE
Is Cachet really open source? LICENSE file does not state so ...

### ISSUE THREAD

**Issue by bozicm** [CachetHQ/Cachet#2323]
Hi CachetHQ. I'm a bit confused about Cachet being promoted as _"The open source status page system"_ on your webpage whereas in the code I cannot find under which type of license it is licensed.

LICENSE file states that it is under "All rights reserved" along with a couple of clauses/conditions, but this isn't actually for example [OSI approved](https://opensource.org/faq#approved-licenses-only) licence. This seems to be the commit that changed the license terms: 5043a86b80080. I understand that it might be easier for the Cachet team to relicense it as a closed source app for their commercial purpose, but for the rest of us this code isn't open source anymore.

**Comment by bozicm** [comment]
Well, after some googling I found that this is indeed [BSD-3 clause license](https://opensource.org/licenses/BSD-3-Clause) which is OSI approved. Maybe the type of licence should be explicitly stated in the LICENSE and README files?

**Comment by GrahamCampbell** [comment]
License already stated in https://github.com/CachetHQ/Cachet/blob/2.4/LICENSE and https://github.com/CachetHQ/Cachet/blob/2.4/composer.json#L12
