### ISSUE TITLE
Make URLs clickable

### ISSUE THREAD

**Issue by davidak** [CachetHQ/Cachet#2327]
When you add URLs to Cachet posts, they are just plain text. They should get converted to clickable links like Github does.

Screenshot from Cachet 2.3.10:

![bildschirmfoto von 2017-01-26 14 39 36](https://cloud.githubusercontent.com/assets/91113/22333267/823c89a2-e3d5-11e6-8752-8115101d135f.png)

**Comment by ConnorVG** [comment]
Hey, @davidak.

If you would like to have a link then feel free to use Markdown :smile: 

`[Link Description](Url of link)` ie: `[Google](https://google.com)`

**Comment by jbrooksuk** [comment]
You're right though, the URL should be automatically clickable.

**Comment by ConnorVG** [comment]
@jbrooksuk would this then be delegated to the parser?

**Comment by davidak** [comment]
@ConnorVG i know Markdown :)

@jbrooksuk thanks!

**Comment by jbrooksuk** [comment]
@GrahamCampbell as you're familiar with CommonMark, does it not support it?

**Comment by ConnorVG** [comment]
@jbrooksuk as far as I am aware, CommonMark doesn't do anything special with raw URLs. It just wraps them in ` p` tag.

**Comment by GrahamCampbell** [comment]
We could write a package that did transform them tho. :P

**Comment by ConnorVG** [comment]
[Yeah...](http://spec.commonmark.org/0.27/#example-580)

Custom would be the way :grimacing:

**Comment by jbrooksuk** [comment]
Anybody up for writing the extension? It'd be good to have this in v2.4 where things are a bit further along.

**Comment by jbrooksuk** [comment]
Technically, Cachet supports CommonMark, so we're not going to add this to the core unless someone writes a custom extension.
