### ISSUE TITLE
(optionally) notify on updates of incidents

### ISSUE THREAD

**Issue by davidak** [CachetHQ/Cachet#2329]
When you create a new incident, there is a checkbox to notify subscribers. Please provide this checkbox also when you edit incidents!

There should also be a setting to enable or disable it by default. It can be disabled by default so the behaviour don't change.

Currently we have to create a new Inident every time when we fixed one so subscribers get notified. This is very bad usabillity!

**Comment by jbrooksuk** [comment]
Anybody may feel free to pick this up!

**Comment by Moolgeson** [comment]
Would love this, same goes with scheduled maintenance updates.

**Comment by jbrooksuk** [comment]
Moved into v2.4.

**Comment by jbrooksuk** [comment]
This is done!
