### ISSUE TITLE
Subscribe button not showing for me on the latest version

### ISSUE THREAD

**Issue by ChristopherP1221** [CachetHQ/Cachet#2330]
Hello,

This is probably way more user error than it is a bug but I'm noticing some strange behavior that I'm not able to figure out.  In the settings section of the UI, I try to click the button to enable users to subscribe to email notifications and when I click save, the tick box reverts back to its original setting i.e. if it was clear, it goes back to clear, if checked back to checked.  I have not yet been able to furnish the subscribe button.  I have set up my email server properly and verified that I'm able to receive email by adding a new team member.  I have tried all of the config:clear, config:cache, app:update and app:install commands and still no luck.  Please let me know what information you'd like for me to send over and I'll attach it to this post.

Thanks ahead of time for the assistance!

Thanks,
Chris

**Comment by jbrooksuk** [comment]
Make sure that `./bootstrap/cache{,t}/*` is writable.

**Comment by ChristopherP1221** [comment]
Hi jbrooksuk,

The directory is indeed writeable.  I'm now able to toggle the button without any issues but still no subscribe button.  I am able to toggle other things at the bottom of that page such as "Show support for Cachet" without any issues.  Does Redis need to have a special configuration in order for this to work?  I feel like I'm missing something very obvious but it's driving me nuts.  Thanks again for your help.

Thanks,
Chris

**Comment by ChristopherP1221** [comment]
So, I'm now receiving an error message when issuing 'php artisan app:install' and it's related to subscribers.  Any ideas? 


root@statuspage100:/var/www/Cachet> php artisan app:install
Clearing settings cache...
Settings cache cleared!
Backing up database...
Dumping database and uploading...

Successfully dumped mysql, compressed with gzip and store it to local at /var/www/Cachet/database/backups/2017-01-31 23.34.56
Backup completed!
Application key [] set successfully.
Configuration cache cleared!
Configuration cached successfully!
Route cache cleared!
Routes cached successfully!
Copied Directory [/vendor/roumen/feed/src/views] To [/resources/views/vendor/feed]
Publishing complete for tag []!
Nothing to migrate.
Clearing cache...
Application cache cleared!
Cache cleared!


  [ReflectionException]
  Class GrahamCampbell\Core\Subscribers\CommandSubscriberonLinkStorage does not exist

**Comment by jbrooksuk** [comment]
That's not subscribers as in people who are subscribed, that's a command listener for a package we use. Ping @GrahamCampbell?

**Comment by GrahamCampbell** [comment]
Looks like ur PR had a typo in James.

**Comment by GrahamCampbell** [comment]
Pushed a fix to the core package.

**Comment by GrahamCampbell** [comment]
https://github.com/GrahamCampbell/Laravel-Core/releases/tag/v5.3.1

**Comment by jbrooksuk** [comment]
Fixed :)
