### ISSUE TITLE
Purpose of checkRules

### ISSUE THREAD

**Issue by mehrdaad** [CachetHQ/Cachet#2332]
I see this app uses ``alt-three\test-bench`` since I couldn't find any docs related to that package I'm gonna ask here.  
In almost all of models unit test you use ``$this->checkRules(new ModelName())``.  
What This method does? can explain a bit?  
As far as I could tell it verifies the model over the rules property. But would appreciate if you can explain more.

**Comment by MatthewSH** [comment]
@mehrdaad this is definitely *not* the place to ask this. Ask your question [here](https://github.com/AltThree/TestBench/issues).

**Comment by mehrdaad** [comment]
Oops sorry!
