### ISSUE TITLE
CachetHQ Setupscreen Bug

### ISSUE THREAD

**Issue by MrSascha** [CachetHQ/Cachet#2333]
I want to Install Cachet on a FreeBSD Server. I folow all Steps from the Documentation. Pleas Help Me.

![screenshot_1](https://cloud.githubusercontent.com/assets/17358343/22398886/137e8674-e591-11e6-8f28-68ed8f45aa66.png)

![screenshot_2](https://cloud.githubusercontent.com/assets/17358343/22398889/1bdd40c6-e591-11e6-8141-91a28dde4d9c.png)

**Comment by MatthewSH** [comment]
Can you provide a URL?

**Comment by MrSascha** [comment]
How do you mean?

**Comment by MatthewSH** [comment]
@MrSascha to your install, if it's public.

**Comment by jbrooksuk** [comment]
Are you using Apache/Nginx?

**Comment by MrSascha** [comment]
It was a linking error, which I could change with the hosting interface.
