### ISSUE TITLE
schedules view generates an error

### ISSUE THREAD

**Issue by AleksejsC** [CachetHQ/Cachet#2335]
Version 2.4-dev. Created schedules, when if I go to
/schedules/1
there is error 500
Log file attached
[laravel-2017-01-30.txt](https://github.com/CachetHQ/Cachet/files/739145/laravel-2017-01-30.txt)

**Comment by jbrooksuk** [comment]
I've fixed this now.

**Comment by jbrooksuk** [comment]
https://github.com/CachetHQ/Cachet/commit/e015424f7d1de295d49911ddbbdff0c069a7217a
