### ISSUE TITLE
Incident Description in Email Rather Than Just a Link

### ISSUE THREAD

**Issue by max-l-weaver** [CachetHQ/Cachet#2338]
Currently, in v2.4.0-Dev, when a subscriber is sent a notification the email just contains a link to the incident description:
<img width="400" alt="screen shot 2017-01-31 at 11 11 01" src="https://cloud.githubusercontent.com/assets/22293003/22463512/d013bdda-e7a9-11e6-9338-a14afc32b770.png">

This is quite problematic as many of our subscribers will not click the view button. We need an option to display the event description directly within the email.

Is this possible, or perhaps it is something that needs to be set up via the incident template function? Unfortunately due to the lack of documentation regarding the incident template I am unable to see whether this is where the solution lies.

**Comment by ConnorVG** [comment]
I'm afraid, to add the description, you'd have to alter [this bit of code](https://github.com/CachetHQ/Cachet/blob/2.4/app/Notifications/IncidentUpdate/IncidentUpdatedNotification.php#L77).

**Comment by jbrooksuk** [comment]
I can add this, not a problem.

**Comment by max-l-weaver** [comment]
Is there any ETA for this enhancement please? I'm just trying to figure out whether it's worth waiting or if it's going to take a while I might as well try and hack it myself.

**Comment by jbrooksuk** [comment]
Should be done now.

**Comment by jbrooksuk** [comment]
e156be6ce14ec5e88b8df95d141e5c2134b78df4
