### ISSUE TITLE
Demo of V2.4

### ISSUE THREAD

**Issue by hjone72** [CachetHQ/Cachet#2343]
Didn't want to derail the staytus github page. @jbrooksuk, offered to setup a demo of version 2.4. Thought I'd create this to track the staytus ;) of that.

Thanks,

**Comment by jbrooksuk** [comment]
@hjone72 I've setup the new demo - https://dev.cachethq.io

Also, love the pun ❤️

**Comment by roycepope** [comment]
Is this open to the public? Can I log into the Dashboard to check it out?

**Comment by jbrooksuk** [comment]
Yes, https://dev.cachethq.io/dashboard using the same login details, test@test.com test123

**Comment by duysmil** [comment]
Hi jbrooksuk, in this demo, don't show MAINTENANCE in home page?

**Comment by jbrooksuk** [comment]
Are you creating any?

**Comment by duysmil** [comment]
> Are you creating any?

No, I'm installing into production myself.

I meant that I tested it in its demo version and the schedule did not work.
I created one now for testing and it did not show up.

In the 2.4-dev version I installed, it also does not work.
