### ISSUE TITLE
Weekdays only in english

### ISSUE THREAD

**Issue by dwydler** [CachetHQ/Cachet#2347]
Hi Guys,
i upgraded from v2.3.9 to v2.4.0-dev. My default language for Cachet is german. After i review the new version i noticed that the weekdays not translated to the specified language in the settings.

Regards,
Daniel

**Comment by jbrooksuk** [comment]
@joecohens reckon this is us switching to `Carbon` instead of `Date`?

**Comment by joecohens** [comment]
Mmm it sounds like it. I'll test this soon.

**Comment by fgth** [comment]
Hi all,
same problem here : default language to French and the dates on dashboard stay in english (not only the weekday, all the date). Waiting for your opinion. Tanks.

**Comment by jbrooksuk** [comment]
@joecohens I've looked into it... Carbon doesn't support locales exactly like the Date package... http://carbon.nesbot.com/docs/#api-localization

Reckon we revert? 😞

**Comment by jbrooksuk** [comment]
I've reverted.

**Comment by dwydler** [comment]
It works, thanks!

**Comment by fgth** [comment]
Confirmed ! Thank for reactivity !
