### ISSUE TITLE
Double entries Site language

### ISSUE THREAD

**Issue by dwydler** [CachetHQ/Cachet#2348]
After i installed a demo system with v2.4.0-dev i changed the language to german. If i open den drop down menu i see for every language two entries.

Here a scrrenshot for it:
http://picpaste.de/7d37b28ccbe0a3e9587f8a55a98e7617.png

**Comment by jbrooksuk** [comment]
`de-DE`?

I think I know what's causing this.

**Comment by jbrooksuk** [comment]
Fixed :) This might be the case for a few languages to be honest.
