### ISSUE TITLE
Stick Incident overwrites on edit

### ISSUE THREAD

**Issue by dwydler** [CachetHQ/Cachet#2349]
I create a new Incident with some demo text. The Parameter "Stick Incident" is set to "not Stickied" and saved it. After that i edit the same incident again the option ist automatically set to "Stickied".

Version: 2.4.0-dev
PHP: PHP 5.6
Web: Apache 2.4.20

**Comment by jbrooksuk** [comment]
Thanks for reporting this! I'll look into it,

**Comment by jbrooksuk** [comment]
Fixed! 👍
