### ISSUE TITLE
Setup not completing

### ISSUE THREAD

**Issue by matematrix** [CachetHQ/Cachet#2352]
Hello,

I have installed Cachet exactly the same way as you describe it in your setup guide.
I can now access the setup page, I fill everything in, and when I press the button "Complete Setup",
I just get the error popup: "An error has occured and this resource cannot be displayed".

Thanks in advance :)

**Comment by jbrooksuk** [comment]
Can you share your log files please? You can find them in `./storage/logs/`.

**Comment by jbrooksuk** [comment]
Also, what version of Cachet are you using?

**Comment by matematrix** [comment]
I am using version 2.3.9,
and here is the pastebin of the laravel log: http://pastebin.com/zEHeXb4h

Thanks :)

**Comment by jbrooksuk** [comment]
It looks like the user has already been created:

```
Next Illuminate\Database\QueryException: SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry 'Mats' for key 'users_username_unique' (SQL: insert into `users` (`username`, `email`, `password`, `level`, `api_key`, `updated_at`, `created_at`) values (Mats, mats@zierhut-it.de, y$rynu9xbG1WrloVoqGKOFjuRHc03aHfLw3phSPwfXewelFX7WuLT6O, 1, 0Uz5skitS09hjjqsInlN, 2017-02-04 14:56:56, 2017-02-04 14:56:56))
```

Reset your migrations and try again 👍

**Comment by matematrix** [comment]
Sorry to ask, but how can I do that?

**Comment by jbrooksuk** [comment]
`php artisan app:reset`

**Comment by matematrix** [comment]
Thank you very much!

**Comment by matematrix** [comment]
Sorry , but now the webinterface itself works, but I can't login with my credentials.
Do I need anything else to get it to work?

**Comment by heimuya** [comment]
maybe because project dir is not set the owner to www or any other web users. My problem is fixed by running 'sudo chown -R www:www cachet'.

**Comment by jbrooksuk** [comment]
👍
