### ISSUE TITLE
installation for docker exec instructions should use cachetdocker_cachet_1

### ISSUE THREAD

**Issue by jbayer** [CachetHQ/Cachet#2354]
after `docker-compose up` the next two commands currently have the wrong container reference

should be:
```
docker exec -i cachetdocker_cachet_1  php artisan key:generate
docker exec -i cachetdocker_cachet_1  php artisan app:install
```

**Comment by jbrooksuk** [comment]
Can you add this issue to the [Docker issues](https://github.com/CachetHQ/Docker/issues) please.

**Comment by jbayer** [comment]
sure, thanks for the pointer

**Comment by jbrooksuk** [comment]
Thanks :)
