### ISSUE TITLE
Mail settings not saved

### ISSUE THREAD

**Issue by dwydler** [CachetHQ/Cachet#2357]
Hi Guys,
today i want to setup the mail settings on my cachet installation. I configured the parameters ans saved it. After reload the site default settings are restored. So i configured the options again and the result was the same as before. In the logfile (storage/log/la...) i found no entry for this.

Environment
Version: 2.4.0-dev
PHP: 5.6

**Comment by jbrooksuk** [comment]
You need to have the `./bootstrap/cachet/*` and `./bootstrap/cache` directories as writeable.

**Comment by klamontagne** [comment]
Hello, I'm trying out a new setup here. Changing the `'mail'` values in `./bootstrap/cache/config.php` (with the web server user) made the notifications go through, but it seems submitting the form at `http://.../dashboard/settings/mail` is not updating those values.

**Comment by jbrooksuk** [comment]
Ping @GrahamCampbell @ConnorVG permissions right?

**Comment by dwydler** [comment]
@jbrooksuk 
Booth directories have accress rights 777.

**Comment by jbrooksuk** [comment]
Does the web user have access to those directories? Are you running Apache or Nginx?

**Comment by dwydler** [comment]
We use Apache 2.4.20.

Here the output of the directories.
[http://up.picr.de/28252321nu.png](url)

**Comment by dwydler** [comment]
i do some tests...
1) change the mail driver and save it
2) Reload the page shows the default "(Log) Testing"
3) Logout and login again nothing changed on the mail settings ite
4) Delete the cache via rm -rf bootstrap/cache/* & php artisan config:cache and browse to the mail settings it displays the correct selection of point 1)

If i do the same steps again with the parameter Mail Username & Mails Password it does not work. :-(

**Comment by jbrooksuk** [comment]
You shouldn't need to run `php artisan config:cache`. Try not running that.

**Comment by jbrooksuk** [comment]
It may also be a bug in Cachet v2.4, I'll double check.

**Comment by dwydler** [comment]
@jbrooksuk 
Why did you close the issue?

**Comment by jbrooksuk** [comment]
I'm confident that it's not a Cachet issue. I've tested this on our https://dev.cachethq.io instance and it worked. We can still continue to provide help though.

**Comment by dwydler** [comment]
Here the output of the directory rights:
(14:20:01) [Cachet] ls -lsa | grep "bootstrap"
  4 drwxrwxrwx  4 re946346 nobody   4096 Mar  9 22:57 bootstrap

(14:24:41) [Cachet] ls -lsa bootstrap/ | grep "cache"
4 drwxrwxrwx  2 re946346 nobody 4096 Mar  9 23:01 cache

So the webserver user re946346 can access the dirs.

What should I check next?

**Comment by jbrooksuk** [comment]
Is all of `./bootstrap` and it's sub-directories writeable?

**Comment by dwydler** [comment]
Yes, see here:
(11:18:10) [Cachet] ls -laR bootstrap/
bootstrap/:
total 24
drwxrwxrwx  4 re946346 nobody 4096 Mar  9 22:57 .
drwxr-x--- 12 re946346 nobody 4096 Mar 10 14:20 ..
-rw-r-----  1 re946346 nobody 1418 Mar  9 22:57 app.php
-rw-r-----  1 re946346 nobody 1345 Mar  9 22:57 autoload.php
drwxrwxrwx  2 re946346 nobody 4096 Mar  9 23:01 cache
drwxrwxrwx  2 re946346 nobody 4096 Mar 10 14:20 cachet

bootstrap/cache:
total 280
drwxrwxrwx 2 re946346 nobody   4096 Mar  9 23:01 .
drwxrwxrwx 4 re946346 nobody   4096 Mar  9 22:57 ..
-rw-r----- 1 re946346 nobody  37542 Mar  9 23:01 config.php
-rw-r----- 1 re946346 nobody     14 Mar  9 22:57 .gitignore
-rw-r----- 1 re946346 nobody 218523 Mar  9 23:01 routes.php
-rw-r----- 1 re946346 nobody  12090 Mar  9 23:01 services.php

bootstrap/cachet:
total 28
drwxrwxrwx 2 re946346 nobody  4096 Mar 10 14:20 .
drwxrwxrwx 4 re946346 nobody  4096 Mar  9 22:57 ..
-rw-r----- 1 re946346 nobody    14 Mar  9 22:57 .gitignore
-rw-r----- 1 re946346 nobody 14894 Mar 10 14:20 production.php
(11:18:24) [Cachet]

**Comment by amit-partelo** [comment]
Not sure why this is closed. Experiencing same issue here.

**Comment by nefarius** [comment]
Hey hey,

same issue here on a fresh install of `2.4.0-dev`, checked suggested permissions multiple times, no errors logged.

**Comment by ssg-luke** [comment]
Also experiencing the same issue after a fresh install. Permissions are fine. It's able to write the correct values to `./bootstrap/cachet/production.php` but then these are not loaded up correctly or something on a page refresh

**Comment by jbrooksuk** [comment]
Are you using Docker?

**Comment by ssg-luke** [comment]
Yep its hosted using Dokku (powered by Docker)

**Comment by zetas** [comment]
Did anyone solve this? I'm having this same issue today but none of these workarounds are working for me. Restarting the containers does nothing.

**Comment by azielke** [comment]
Had the same problem and google pointed me to this issue.

For me the problem was that the configuration was already in my .env, which seems to override the settings. Using Docker like in the Documentation "Installing Cachet with Docker" will generate an .env with default values for some MAIL_*-Settings.

Adding the corresponding MAIL_*-Settings to .env solved the problem for me.
