### ISSUE TITLE
Multi tenancy support

### ISSUE THREAD

**Issue by jaiswalsanjeev** [CachetHQ/Cachet#2360]
Is there support for multi- tenant customers? Having a separate status page for each of the customers in a cloud environment?

**Comment by jbrooksuk** [comment]
There isn't and we don't intend to support this. 

Cachet is very lightweight and can be installed quickly and this use case is not a big one for the majority of people :)

**Comment by dwydler** [comment]
Try follow idea:
1) Install Cachet as a template in a folder, exclude .env
2) Create a new subdomain which is link to the template via _ln_ command.
3) Create in every subdomain the settings file .env with custom data for the key, database connection and so on.
4) Test it. :-)

**Comment by mm-manageit** [comment]
@dwydler could you elaborate on what you mean by the "IN" command?

**Comment by dwydler** [comment]
@mm-manageit I mean the command [ln](https://wiki.ubuntuusers.de/ln/) for synmbol links at the file system.
