### ISSUE TITLE
Error on Composer Install 

### ISSUE THREAD

**Issue by Bananenbaas** [CachetHQ/Cachet#2362]
Hi guys, 

I get this error on the installation of composer... 
Don't really get it. Maybe you can help me? 

`> Illuminate\Foundation\ComposerScripts::postInstall
> php artisan optimize --force
PHP Fatal error:  Uncaught ReflectionException: Class config does not exist in /home/status/web/public_html/Cachet/vendor/laravel/framework/src/Illuminate/Container/Container.php:734
Stack trace:
#0 /home/status/web/public_html/Cachet/vendor/laravel/framework/src/Illuminate/Container/Container.php(734): ReflectionClass->__construct('config')
#1 /home/status/web/public_html/Cachet/vendor/laravel/framework/src/Illuminate/Container/Container.php(629): Illuminate\Container\Container->build('config', Array)
#2 /home/status/web/public_html/Cachet/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(697): Illuminate\Container\Container->make('config', Array)
#3 /home/status/web/public_html/Cachet/vendor/laravel/framework/src/Illuminate/Container/Container.php(1178): Illuminate\Foundation\Application->make('config')
#4 /home/status/web/public_html/Cachet/vendor/laravel/framework/src/Illuminate/Container/Container.p in /home/status/web/public_html/Cachet/vendor/laravel/framework/src/Illuminate/Container/Container.php on line 734
Script php artisan optimize --force handling the post-install-cmd event returned with error code 255`

**Comment by jbrooksuk** [comment]
Try running `rm -rf bootstrap/cache{,t}/*`.

**Comment by Bananenbaas** [comment]
Well, unfortunately that did not fix it...

**Comment by ConnorVG** [comment]
It may be worth running an `rm -rf vendor && rm -rf bootstrap/cache{,t}/*` then running `composer install`

**Comment by Bananenbaas** [comment]
I still get the same error :(

**Comment by ConnorVG** [comment]
Is this a fresh install of Cachet?

**Comment by Bananenbaas** [comment]
Yes a new fresh EC2 instance and an install of Vesta CP on it...

**Comment by jbrooksuk** [comment]
Did you run `composer install --no-dev`?

What version of PHP are you using?

**Comment by Bananenbaas** [comment]
Sorry for the late reply, but yeah I did run `composer install --no-dev` and it gives me this error: `Script php artisan optimize --force handling the post-install-cmd event returned with error code 255` 

I'm using PHP 7.0.15-0ubuntu0.16.04.2 (cli) ( NTS )

**Comment by x10Corey** [comment]
I ran into this exact error also, using PHP70 from the REMI repository.

It turns out I was missing both php70-php-bcmath and php70-php-pdo, once I installed these packages the issue was resolved though no error or logs prior pointed to this being the issue.  Found it on the Laravel forums.
