### ISSUE TITLE
Can't log into dashboard

### ISSUE THREAD

**Issue by matematrix** [CachetHQ/Cachet#2363]
In reference to #2352 , I followed these steps, but can't log in now, and I am 100% sure I am using the correct credentials.
Any help appreciated, thanks in advance 👍

**Comment by jbrooksuk** [comment]
Are you able to see if you have a user setup? You could try following the steps at https://docs.cachethq.io/docs/frequently-asked-questions#section-how-do-i-reset-a-forgotten-password

**Comment by matematrix** [comment]
I followed the steps there and it is just showing me `NULL`.
So, I assume that means that I have no user setup.
But as in the reference to #2352 , if I reinstall Cachet I get an error at the end of the setup,
and if I follow the steps you told me there, I end up with no user.

**Comment by jbrooksuk** [comment]
Delete all tables and try again. Something is going wrong and when you try again it's mixing up errors.

**Comment by matematrix** [comment]
Sorry for the late answer, but still I can't get it to work.
