### ISSUE TITLE
Subscribe button not showing up on UI in v2.3.10

### ISSUE THREAD

**Issue by ChristopherP1221** [CachetHQ/Cachet#2364]
Hello, 

I'm starting a new thread because I accidentally revealed a bug in the previous thread #2330 and didn't want to muddy the waters with this.  I performed a clean install of v2.3.10 using my current Apache and MySQL settings.  My mail server is configured properly because I'm able to create accounts and invite team members through the dashboard functionality.

 I'm using PHP7.0.14, mysql 5.1.73 for RHEL, and Apache web server.  I added the predis/predis package to my composer.json and verified the subscriber tables exist in the database.  I have tried clearing caches and configs through artisan and also wiped the boostrap/cachet/* several times while troubleshooting, all with no luck.  Below is my .env file as well.

I don't have Supervisor setup.  Instead, I chose to use the MySQL database queueing option with a crontab entry.
```bash
root@statuspage100:/var/www/Cachet-clean/Cachet> crontab -l | grep schedule
* * * * * /usr/bin/php /var/www/Cachet/artisan schedule:run >> /dev/null 2>&1
```

Here is a peek at my database tables and subscriber setting...
```sql
mysql> select * from settings where name like '%subscribe%';
+----+--------------------+-------+---------------------+---------------------+
| id | name               | value | created_at          | updated_at          |
+----+--------------------+-------+---------------------+---------------------+
|  8 | enable_subscribers | 1     | 2017-01-15 00:18:23 | 2017-01-31 23:34:48 |
+----+--------------------+-------+---------------------+---------------------+
1 row in set (0.00 sec)

mysql> use cachet;
Database changed
mysql> show tables;
+--------------------+
| Tables_in_cachet   |
+--------------------+
| cache              |
| component_groups   |
| component_tag      |
| components         |
| failed_jobs        |
| incident_templates |
| incidents          |
| invites            |
| jobs               |
| metric_points      |
| metrics            |
| migrations         |
| sessions           |
| settings           |
| subscribers        |
| subscriptions      |
| tags               |
| users              |
+--------------------+
18 rows in set (0.00 sec)

mysql> select * from settings where name like '%subscribe%';
+----+--------------------+-------+---------------------+---------------------+
| id | name               | value | created_at          | updated_at          |
+----+--------------------+-------+---------------------+---------------------+
|  8 | enable_subscribers | 1     | 2017-01-15 00:18:23 | 2017-01-31 23:34:48 |
+----+--------------------+-------+---------------------+---------------------+
1 row in set (0.00 sec)
```

Here is my .env...
```ini
APP_ENV=production
APP_DEBUG=true
APP_URL=http://localhost
APP_KEY=<left blank on purpose>

DB_DRIVER=mysql
DB_HOST=localhost
DB_DATABASE=cachet
DB_USERNAME=cachet
DB_PASSWORD=password
DB_PORT=3306
DB_PREFIX=null

CACHE_DRIVER=redis
SESSION_DRIVER=file
QUEUE_DRIVER=database
CACHET_EMOJI=true

MAIL_DRIVER=smtp
MAIL_HOST=<left blank on purpose>
MAIL_PORT=25
MAIL_USERNAME=null
MAIL_PASSWORD=null
MAIL_ADDRESS=statuspage@statuspage.com
MAIL_NAME=null
MAIL_ENCRYPTION=null

REDIS_HOST=127.0.0.1
REDIS_DATABASE=cachet
REDIS_PORT=6379

GITHUB_TOKEN=null
```

**Comment by GrahamCampbell** [comment]
> <left blank on purpose>

Unless this is set, cachet will not allow subscribers to show up.

**Comment by GrahamCampbell** [comment]
The same goes for a username and password.

**Comment by ChristopherP1221** [comment]
Sorry, I should have been more clear.  I left those blank when I pasted so I wasn't providing my app key and mail server name.  Are you saying the mail server username and pass need to be set in order to properly allow subscribers?  I"m able to successfully generate emails to teammates when asking them to join through the dashboard without having username and pass set.

**Comment by GrahamCampbell** [comment]
Yeh, I seem to remember we had some sort of unneeded restriction there, but I can't remember if we ever got around to fixing it on 2.4.x. Ping @jbrooksuk.

**Comment by ChristopherP1221** [comment]
Interestingly enough after double checking on the send team mail
functionalit, I noticed my postfix server was broken.  I fixed it and still
no subscribe button.  What should I be using for mail_username and pass?
We map postix to the user account that is logged into the server at the
time they send mail.  There is no static password.  The documentation
around this is light so please excuse the seemingly simple questions.

Thanks,
Chris

**Comment by ChristopherP1221** [comment]
I think we're all set here but I'm really confused on what was needed to actually solve the problem.  I ended up creating a MailGun account just to make sure there wasn't something strange happening with my mail setting.  After configuring the .env settings using the documentation as a template, the Subscribe button showed up (great!).  But, what's weird is when I reverted back to my original mail settings, the Subscribe button doesn't actually go back away.  It may be something to look into because it drove me crazy for a little while so others may be experiencing the same!  

Great job on creating this app and thanks for all of the help!  I'm looking forward to to seeing what else you all do and hopefully I can contribute at some point.

**Comment by jbrooksuk** [comment]
Very odd! I'll continue to look into this though. Thanks for the update.

**Comment by segfly** [comment]
In case anyone comes here searching how to fix this, I just ran into a very similar issue, and it was not making any sense at all. In my case, it turned out I had a typo in my docker-compose environment variables. Instead of `MAIL_NAME` I had `MAIN_NAME` which was causing `MAIL_NAME` to default to `null`

The real mind-racking thing was that I was searching the code for the footer flag `enable_subscribers` and I can't find any connection to `MAIL_NAME`. Further more, the docs don't say this is required, in fact it seems to suggests to set it to null in the very first paragraph:
https://docs.cachethq.io/docs/configuring-mail

**Comment by jbrooksuk** [comment]
I think I'm going to default the `MAIL_NAME` value to be `Cachet` or even the application name.

**Comment by prbond** [comment]
MAIL_NAME is needed !!
