### ISSUE TITLE
Unable to update component status nor component order

### ISSUE THREAD

**Issue by snowball2** [CachetHQ/Cachet#2365]
Upgraded to latest build 2.4 and now when trying to update component status or change the order of components I receive errors "something went wrong updating the component" and "ordering not updated". Hoping you can assist as I've tried everything I can think of to fix. I can create new components successfully but again, unable to edit their status nor order. I'm also unable to edit components, receive HTTP 500 when trying to save.

![image](https://cloud.githubusercontent.com/assets/4521029/22787396/19653686-eed4-11e6-9690-8fd8547e0656.png)

![image](https://cloud.githubusercontent.com/assets/4521029/22787411/27f05db6-eed4-11e6-9bf0-6a67d0187231.png)

Kind regards

**Comment by jbrooksuk** [comment]
v2.4 is still experimental. Can you send me your log file please.

**Comment by snowball2** [comment]
Laravel log attached

**Comment by snowball2** [comment]
Laravel logs attached

(attempt to update status)
[laravel-2017-02-09.log.txt](https://github.com/CachetHQ/Cachet/files/763973/laravel-2017-02-09.log.txt)

(attempt to update order)
[laravel-2017-02-09_order.log.txt](https://github.com/CachetHQ/Cachet/files/763979/laravel-2017-02-09_order.log.txt)

**Comment by jbrooksuk** [comment]
That should do it for you.

**Comment by snowball2** [comment]
Hi James,

Extra comma at the end of the try block in the commit. That's fixed the issue now though, thank you!

```
    public function postUpdateComponent(Component $component)
    {
        try {
            dispatch(new UpdateComponentCommand(
                $component,
                $component->name,
                $component->description,
                Binput::get('status'),
                $component->link,
                $component->order,
                $component->group_id,
                $component->enabled,
                $component->meta,
                false,
            ));
```

**Comment by jbrooksuk** [comment]
Fixed now too.
