### ISSUE TITLE
Component-Group Save on initial creation

### ISSUE THREAD

**Issue by TWG-Matt** [CachetHQ/Cachet#2366]
I'm running 2.4.0-dev and I noticed when I create a new component group and set it to expanded and anyone can see it, it doesn't save that.  When I go back in to edit it, it's collapsed and set to logged in user's only.

Below you can see the initial creation and then the edit values.
![cachet_component_create_initial](https://cloud.githubusercontent.com/assets/25368064/22836011/687d5e2c-ef80-11e6-874c-1e0a06f3d4c5.png)
![cachet_component_create_edit](https://cloud.githubusercontent.com/assets/25368064/22836012/688732c6-ef80-11e6-9d0e-2ac9a81835ba.png)

**Comment by jbrooksuk** [comment]
Fixed 👍

**Comment by TWG-Matt** [comment]
Awesome.  That was quick @jbrooksuk .
