### ISSUE TITLE
Core Infrastructure Initiative (CII) Best Practices

### ISSUE THREAD

**Issue by ypid** [CachetHQ/Cachet#2367]
I would like to point you to the [CII Best Practices Badge Program](https://bestpractices.coreinfrastructure.org). Could you go thought the [criteria](https://bestpractices.coreinfrastructure.org/criteria), [add the project](https://bestpractices.coreinfrastructure.org/projects/new) and keep it up-to-date there?

Refs:
- https://bestpractices.coreinfrastructure.org
- https://twit.tv/shows/floss-weekly/episodes/389

**Comment by jbrooksuk** [comment]
I'll take a look at this in detail at some point.

**Comment by jbrooksuk** [comment]
I'm going to close this for now, I don't think Cachet has been active enough to deserve entry to something like this for now. Maybe we'll revisit it in the future.
