### ISSUE TITLE
Cachet Error on Update Component from Dashboard

### ISSUE THREAD

**Issue by OzWookiee** [CachetHQ/Cachet#2368]
Got an error when trying to update a component from the Dashboard: http://pastebin.com/F1LDJizq

1. From the Dashboard go to Components
2. Select a Component to Edit
3. Update Description
4. Get 500 Failure

Have tried updating other fields and same result.

**Comment by jbrooksuk** [comment]
What version of Cachet are you running?

**Comment by OzWookiee** [comment]
Sorry should have included that. Not at work atm, but only installed 2 days ago using instructions from readme.

**Comment by OzWookiee** [comment]
{
  "meta": {
    "on_latest": true,
    "latest": {
      "tag_name": "v2.3.10",
      "prelease": false,
      "draft": false
    }
  },
  "data": "2.4.0-dev"
}

**Comment by jbrooksuk** [comment]
Fixed 👍

**Comment by OzWookiee** [comment]
Followed the steps here: https://docs.cachethq.io/docs/updating-cachet

Now getting 500 errors when accessing Cachet
`Next exception 'Illuminate\Database\QueryException' with message 'SQLSTATE[42S22]: Column not found: 1054 Unknown column 'scheduled_at' in 'where clause' (SQL: select * from `incidents` where (`status` > 0 or (`status` = 0 and (`scheduled_at` is null or `scheduled_at` <= 2017-02-17 04:21:22))) and `visible` >= 1 and `created_at` between 2017-02-11 00:00:00 and 2017-02-17 23:59:59 and `incidents`.`deleted_at` is null order by `scheduled_at` desc, `created_at` desc)' in /var/www/Cachet/vendor/laravel/framework/src/Illuminate/Database/Connection.php:713
`
http://pastebin.com/g6utZ63a

Guessing there are new columns added in 2.4 that have snuck into this release?

**Comment by OzWookiee** [comment]
Either that or **php artisan app:update** doesn't know it has to update a table?

**Comment by OzWookiee** [comment]
```
mysql> desc incidents;
+--------------+------------------+------+-----+---------+----------------+
| Field        | Type             | Null | Key | Default | Extra          |
+--------------+------------------+------+-----+---------+----------------+
| id           | int(10) unsigned | NO   | PRI | NULL    | auto_increment |
| component_id | int(11)          | NO   | MUL | 0       |                |
| name         | varchar(255)     | NO   |     | NULL    |                |
| status       | int(11)          | NO   | MUL | NULL    |                |
| visible      | tinyint(1)       | NO   | MUL | 1       |                |
| stickied     | tinyint(1)       | NO   | MUL | 0       |                |
| message      | longtext         | NO   |     | NULL    |                |
| occurred_at  | timestamp        | YES  |     | NULL    |                |
| created_at   | timestamp        | YES  |     | NULL    |                |
| updated_at   | timestamp        | YES  |     | NULL    |                |
| deleted_at   | timestamp        | YES  |     | NULL    |                |
+--------------+------------------+------+-----+---------+----------------+
11 rows in set (0.00 sec)


```

**Comment by OzWookiee** [comment]
Has occurred_at been relabeled to scheduled_at??

**Comment by ShonM** [comment]
Upgrading to 2.4 and downgrading to 2.3 introduced this issue for me.

**Comment by temenoskrpavithra** [comment]
We have hit the same issue. We were in 2.4.0-dev earlier and chose to install 2.3.13 as we found some bugs in the dev version. 

Is there a solution for the above reported issue or should we roll back to 2.4.0-dev ?

**Comment by jbrooksuk** [comment]
This should be fixed now.
