### ISSUE TITLE
Stop HTML input into incidents

### ISSUE THREAD

**Issue by Ehesp** [cachethq/Cachet#237]
Seems that you can enter HTML into the incident box, which is currently breaking the layout. I'd imagine a quick fix for this would to be use the triple blade tags (`{{{ }}}`).

**Comment by jbrooksuk** [comment]
You should be able to enter Markdown though.

**Comment by GrahamCampbell** [comment]
Maybe you want to use by binput package.

**Comment by GrahamCampbell** [comment]
It prevents xss, then you can run that through the markdown renderer.

**Comment by jbrooksuk** [comment]
That's what we need, but on all user input.

**Comment by jbrooksuk** [comment]
So what we could do is when any data is saved, run it through binput.

**Comment by GrahamCampbell** [comment]
Yeh, basically, instead of using `Input::get` we can use `Binput::get`, and all the other methods like all, except, only, work too.

**Comment by GrahamCampbell** [comment]
Do you want me to send a pull?

**Comment by jbrooksuk** [comment]
Yeah go ahead, I'm at work today, so I've only got a few minutes here and there.

**Comment by GrahamCampbell** [comment]
Sure.

**Comment by GrahamCampbell** [comment]
Just running composer now...
