### ISSUE TITLE
Problem installing

### ISSUE THREAD

**Issue by AppleCarmine** [CachetHQ/Cachet#2371]
Hello everyone
When I try to install Cachet, finding a problem, that is, after installation, when I go on the site where I put Cachet tells me that the file does not exist. Why?

**Comment by OzWookiee** [comment]
Have you checked the logs in storage/logs?

**Comment by AppleCarmine** [comment]
And inside there is only one file called .gitignore with written inside *
! .gitignore

**Comment by OzWookiee** [comment]
> when I go on the site where I put Cachet tells me that the file does not exist. Why?
Are you using Apache or nginx?
Did you create the virtual site config and restart the webserver?

**Comment by AppleCarmine** [comment]
I installed Cachet in / var / www / html and I am using apache2

**Comment by OzWookiee** [comment]
What's in your Apache Error/access log??

What's you apache conf?

https://docs.cachethq.io/docs/installing-cachet#section-running-cachet-on-apache

**Comment by jbrooksuk** [comment]
I'm going to close this, but please do continue the conversation :)

We provide a professional installation service, you can email us at support@alt-three.com :)
