### ISSUE TITLE
Metrics graphed as UTC not localtime

### ISSUE THREAD

**Issue by OzWookiee** [CachetHQ/Cachet#2373]
```
{
  "meta": {
    "on_latest": true,
    "latest": {
      "tag_name": "v2.3.10",
      "prelease": false,
      "draft": false
    }
  },
  "data": "2.4.0-dev"
}
```
Metrics shown as graphs render as UTC not local time from settings.

http://imgur.com/3vl8Uck
Raw data from MySQL, stored in UTC

http://imgur.com/fMYCuvT
Returned data from API, returned as localtime

http://imgur.com/B77sQ0Z
Metrics graphed on status page in UTC

**Comment by OzWookiee** [comment]
FYI http://my-cachet/dashboard/settings/localization is set to Melbourne, Australian (UTC +11)

**Comment by OzWookiee** [comment]
RESOLVED

The issue comes from MySQL not having any timezone information loaded by default.  Follow the steps listed here: https://dev.mysql.com/doc/refman/5.7/en/time-zone-support.html

Perhaps this can be listed in the documentation? Or is that too basic?

**Comment by jbrooksuk** [comment]
Ping @GrahamCampbell @joecohens

**Comment by jbrooksuk** [comment]
Whoops. Should we be using the `timestampTz` columns, in an ideal world?

**Comment by jbrooksuk** [comment]
Oh, it's resolved 🤷‍♂️
