### ISSUE TITLE
Metrics: "Last Hour" displaying all data

### ISSUE THREAD

**Issue by Technoblazed** [CachetHQ/Cachet#2374]
When a metric is changed to "Last Hour", it is displaying ALL data from the start of the duration, instead of the last hour.

![Image](https://i.tech-no.me/180217142926.png)

Cachet Version: 2.4-dev

**Comment by jbrooksuk** [comment]
Thanks for this report! I'll look into it.

**Comment by jbrooksuk** [comment]
What database are you using?

**Comment by Technoblazed** [comment]
MySQL, seemed to be when the 'ORDER BY' was removed from the last hour query that it sorted out again.

**Comment by fgth** [comment]
Hi,
with last 2.0.4-dev installed from git I have another strange béhavior : the last hour is now correctly selected, but display only the default value, on all points, not the real values. Values exist in the metric (checked in mysql). Thanks for suggestions.

**Comment by jbrooksuk** [comment]
I think we might need to look into metrics again. I know @GrahamCampbell has said a few times that the current implementation isn't good enough. See https://github.com/CachetHQ/Cachet/issues/2092

**Comment by jbrooksuk** [comment]
Thank you for your input on Cachet 2.x. We are shifting our attention and resources to Cachet 3.x and will no longer be supporting the 2.x version. If your feedback or issue is relevant to the 3.x series, we encourage you to engage with the new branch.

For more information on the Cachet rebuild and our plans for 3.x, you can read the announcement [here](https://github.com/CachetHQ/Cachet/discussions/4342).

We appreciate your understanding and look forward to your contributions to the new version.
