### ISSUE TITLE
Wrong label text in "prev/next week" when settings are not default

### ISSUE THREAD

**Issue by sirkkalap** [CachetHQ/Cachet#2377]
Hi,

Just a minor inconsistency.

Setting: `How many days of incidents to show` = 14, but Status page has buttons "[prev/next week](#)"

Expected: [next 14 days](#), [previous 14 days](#)

Workaround: Use the default (7)

**Comment by jbrooksuk** [comment]
We're moving away from this layout in v2.4, so although it's a bug in v2.3 it'll no longer happen once https://github.com/CachetHQ/Cachet/pull/2325 is merged 😄
