### ISSUE TITLE
Different size for hr in incident markdown

### ISSUE THREAD

**Issue by sirkkalap** [CachetHQ/Cachet#2379]
Cosmetic issue on old version 2.5.0-dev Status page.

I will test on newer version when we manage to roll out an update. Feel free to close or ignore, if you can not reproduce this.

It seems that a `hr` within an incident written with markdown (using "----") is thicker than a similar `hr` in Scheduled Maintenance issue. 

I like the thinner better (the one in Scheduled maintenance).

<img width="1002" alt="screenshot 2017-02-20 16 40 30" src="https://cloud.githubusercontent.com/assets/703699/23129533/b7fc3596-f78b-11e6-8bce-ed7083453352.png">

**Comment by jbrooksuk** [comment]
Woah `2.5.0-dev`? We're only actively working on v2.4-dev can you confirm that you're indeed on v2.5?

**Comment by sirkkalap** [comment]
That is what the Docker image says in Settings.

**Comment by sirkkalap** [comment]
<img width="526" alt="screenshot 2017-02-21 14 03 28" src="https://cloud.githubusercontent.com/assets/703699/23164187/97555a12-f83e-11e6-854b-fb2bcafd4a5e.png">

**Comment by sirkkalap** [comment]
Hi,

I went to the build environment and checked the version this was happening.
The actual tag that the container was built from was v2.3.10. 

For some reason the UI is not reflecting that.

**Comment by jbrooksuk** [comment]
Are you able to see files within the container? If so, can you share the contents of the `VERSION` file please?

Ping @djdefi.

**Comment by sirkkalap** [comment]
Sure, here goes
````bash
[ec2-user@ip-xxx-xx-xx-xxx ~]$ docker exec -i -t dtstatus_cachet_1 bash
www-data@c7819cddf5e8:~/html$ ls
CONTRIBUTING.md  VERSION  bootstrap      composer.phar  gulpfile.js       public      storage
LICENSE          app      composer.json  config         package.json      resources   vendor
README.md        artisan  composer.lock  database       phpunit.xml.dist  server.php
www-data@c7819cddf5e8:~/html$ cat VERSION
2.5.0-dev
````

**Comment by sirkkalap** [comment]
The actual version tag that I used to build the container is:
````bash
[ec2-user@ip-xxx-xx-xx-xxx dt_status]$ git remote -v
origin  https://github.com/cachethq/Docker.git (fetch)
origin  https://github.com/cachethq/Docker.git (push)
[ec2-user@ip-xxx-xx-xx-xxx dt_status]$ git status
HEAD detached at v2.3.9
nothing to commit, working directory clean
````

**Comment by jbrooksuk** [comment]
We use [Github Markdown CSS](https://github.com/sindresorhus/github-markdown-css) for styling our Markdown content in incidents, so we only need to override it.

**Comment by jbrooksuk** [comment]
This isn't an issue in v2.4 :)
