### ISSUE TITLE
Ignore missing metric points in average metric

### ISSUE THREAD

**Issue by sirkkalap** [CachetHQ/Cachet#2383]
Hi,

Would it be possible to ignore missing metric points when calculating average graph?

Any average metric now decays towards the default value, when measurements are not present for every minute.

We would like to record service response times to a metric and we do not wish to run response time tests every minute.

Thus the average currently contains missing metric points every other minute and the average gets lower than the actual measured points average.

----

Alternately we could pad the metric between each recorded metric using the same value for every minute. This is difficult because we have not found any way to get the last metric point without loading all points from Cachet.

Also this alternate way would bloat the database with irrelevant data.

**Comment by sirkkalap** [comment]
To make this more tanglible, here is a picture of three component response times, that we are currently able to record with our monitoring:

<img width="985" alt="screenshot 2017-02-24 09 22 15" src="https://cloud.githubusercontent.com/assets/703699/23294208/f7cbc6a2-fa72-11e6-8200-320e75bce7fd.png">

There are missing data points where the response time is 0. The average for hourly, weekly and so on is affected by them, since they are counted in as value 0.

Maybe this is not what the metrics are to be used for, but response time is something we would really like to offer for our users.

**Comment by jbrooksuk** [comment]
Response Time should be a metric that Cachet supports, it's a common metric to display.

Would you be happy to submit a pact for this?

**Comment by sirkkalap** [comment]
I would very much like to be able to develop Cachet, but unfortunately my php is way old and outdated.

I will take a look and report back.

**Comment by sirkkalap** [comment]
Sorry, there was nothing I could do to this. The graph plotting seems to be fixed to contain continous points and it is not straight forward to support missing data points.

**Comment by sirkkalap** [comment]
After using Cachet for a while I think this was a misunderstanding. I am not sure, but the average seems ok even with multiple 0 default values between actual measurements.

I am closing this, the current implementation is adequate.

**Comment by jbrooksuk** [comment]
👍 awesome :)
