### ISSUE TITLE
Change location of language options

### ISSUE THREAD

**Issue by Vultur** [CachetHQ/Cachet#2388]
Just like WordPress or Windows，the language options should be on the first page。

**Comment by jbrooksuk** [comment]
First page being what?

**Comment by Vultur** [comment]
@jbrooksuk the Language preferences,Just like the WordPress installation process

**Comment by jbrooksuk** [comment]
I've not used Wordpress in a few years now. What do they do with their language preferences which is different?

**Comment by Vultur** [comment]
![cd27cd134954092391655f869558d109b2de494b](https://cloud.githubusercontent.com/assets/15240953/23395066/9b8ba986-fdc7-11e6-803a-cdd9e7cb9cde.png)

Installation the first step is to select language preference, the next configured server, user accounts...

Just a matter of sequence of steps, but it will be more friendly for users

**Comment by jbrooksuk** [comment]
We do need a new setup page, so this could be done then. This is up for grabs!
