### ISSUE TITLE
Customizing CachetHQ Component status

### ISSUE THREAD

**Issue by sukhada369** [CachetHQ/Cachet#2390]
Is there any way to modify the Component status in CachetHQ?

**Comment by jbrooksuk** [comment]
Not yet there isn't. It's something I'd like to implement, but it's not high on the list yet.

There is quite a lot of work needed to do this:

1. Move translations for Component and Incident statuses into the database.
2. Add a way of retrieving the database translations.
3. Swap _all_ existing code where the status names are used for the new system.

**Comment by sukhada369** [comment]
can we expect these enhancement in next release?

**Comment by jbrooksuk** [comment]
Likely not, maybe the version after, it all depends as v2.4 is taking a lot longer than we originally anticipated (as there is a lot to do 😄)

**Comment by moertel** [comment]
Because I didn't want to fiddle with the code in the Docker container, I put a script in the footer section (`https://{yourcachetserver}/dashboard/settings/customization`) and renamed the status. We're only browsing in English anyway, so don't mind the missing/broken translations:
```html
<script type="text/javascript">
jQuery(document).ready(function() {
    var operational = document.getElementsByClassName('text-component-1 greens');
    var partialOutage = document.getElementsByClassName('text-component-3 yellows');
    var majorOutage = document.getElementsByClassName('text-component-4 reds');

    function renameComponentStatus(components, old_text, new_text) {
        for(i=0; i<components.length; i++) {
            components[i].innerHTML = components[i].innerHTML.replace(old_text, new_text);
        }
    }

    renameComponentStatus(operational, 'Operational', '✓ On schedule');
    renameComponentStatus(partialOutage, 'Partial Outage', '◔ Update delayed');
    renameComponentStatus(majorOutage, 'Major Outage', '⚡ Not updated');
});
</script>
```
Code goes here:

<img width="836" alt="screen shot 2017-09-22 at 12 24 28" src="https://user-images.githubusercontent.com/1823966/30740403-1e09669e-9f91-11e7-9b61-d50033f1ad16.png">

**Comment by jbrooksuk** [comment]
Neat hack! ;)

**Comment by Ali-zi** [comment]
@moertel hey great hack, I tried using it but when I do i lose the footer including the dashboard and logout buttons

**Comment by moertel** [comment]
@Ali-zi: Yeah, I'm afraid that was the only place that allowed to enter a custom script. Maybe @jbrooksuk can give some advice here how to both add custom code and keep the default footer. Otherwise, you could copy the original HTML from the footer, then add it manually.

**Comment by jbrooksuk** [comment]
Unfortunately, there isn't a way currently. The footer is replaced automatically.

**Comment by jbrooksuk** [comment]
Thank you for your input on Cachet 2.x. We are shifting our attention and resources to Cachet 3.x and will no longer be supporting the 2.x version. If your feedback or issue is relevant to the 3.x series, we encourage you to engage with the new branch.

For more information on the Cachet rebuild and our plans for 3.x, you can read the announcement [here](https://github.com/CachetHQ/Cachet/discussions/4342).

We appreciate your understanding and look forward to your contributions to the new version.
