### ISSUE TITLE
Performance Settings/Documentation

### ISSUE THREAD

**Issue by TLMcNulty** [CachetHQ/Cachet#2392]
Is there any insight into performance at various scales? We're playing with deploying Cachet into enterprise and are trying to find a baseline for system performance; hits per seconds, memory, storage, etc.

**Comment by jbrooksuk** [comment]
We're yet to benchmark Cachet at any particular scales. That said, I know Cachet is used in large enterprise scenarios and we're yet to be told it's performing slowly.

I know @ConnorVG has a few ideas on how we can further improve performance, so he can jump in and let you know.

**Comment by TLMcNulty** [comment]
Cool, as we spin this up we'll do some testing and documentation and see if we can contribute some information.
