### ISSUE TITLE
New Feature Enhancement: Maximum option for calculation of metrics display

### ISSUE THREAD

**Issue by RickB17** [CachetHQ/Cachet#2396]
It would be great if the "calculation of metrics" had an option for "max value". This would be helpful when attempting to report on the maximum or high water mark of a metric over a period of time.

![image](https://cloud.githubusercontent.com/assets/704271/23509277/40e11a36-ff23-11e6-8e84-dda624edaa52.png)

**Comment by jbrooksuk** [comment]
Okay, so if the submitted metric point value is higher than the max, what happens? Do we silently ignore, or report that it's too high?

**Comment by RickB17** [comment]
I'm assuming one datapoint per minute. And the graph would show the highest data point per sample period when plotting.

**Comment by jbrooksuk** [comment]
Would you be able to make a PR?
