### ISSUE TITLE
Feature Request: Option to Allow zooming or truncation of data in metrics

### ISSUE THREAD

**Issue by TobiTenno** [CachetHQ/Cachet#2397]
As a site admin, I need to be able to give accurate metrics on the fly to my consumers. Presently, the metrics, if all close in value and the value isn't relatively low, are ambiguous. 

For example. Having a metric of average uptime where you are always very close to 100 doesn't allow  consumers to see the .01% variation from time to time of uptime.

**Comment by jbrooksuk** [comment]
I reckon this might be a Chart.js function...

**Comment by jbrooksuk** [comment]
Thank you for your input on Cachet 2.x. We are shifting our attention and resources to Cachet 3.x and will no longer be supporting the 2.x version. If your feedback or issue is relevant to the 3.x series, we encourage you to engage with the new branch.

For more information on the Cachet rebuild and our plans for 3.x, you can read the announcement [here](https://github.com/CachetHQ/Cachet/discussions/4342).

We appreciate your understanding and look forward to your contributions to the new version.
