### ISSUE TITLE
add component API fails intermittently

### ISSUE THREAD

**Issue by eyalzf** [CachetHQ/Cachet#2398]
I'm using node.js as a service for creating and updating components. From time to time adding a component fails with ECONNRESET.

On a possibly related note I see **Failed connect to api.github.com:443** error in Cachet log. The Emoji feature is turned off and I didn't set github token.

Cachet version: 2.4.0-dev
DB: MySQL

**Comment by jbrooksuk** [comment]
You'll also need to add `CACHET_EMOJI=false` to your `.env` file. It's off by default in the `.env.example` file too.
