### ISSUE TITLE
Incident Process Flow

### ISSUE THREAD

**Issue by jzielke** [CachetHQ/Cachet#2399]
First, thanks for a wonderful status program.

I have questions on how to use the incident process.  I have searched the docs looking for a description on how the incident flow works.  I see the Demo Site creates a new incident with a different status.  

I understand you can create an incident and it emails the Subscribers a New Incident Email.

How do update the incident?  If I edit it, it does not email the subscribers.  

Am I supposed to create a new incident with a new status update, and leave the original one alone? How does the new incident link to the original one?  Or it doesn't?  The original one is just part of history?  Creating a new incident for an update does not seem right as it would be an update to an incident and not a new one.  

Seems New Incident email are the only emails sent and if I update it, no email is sent letting them know of an update to the previous reported incident.   Although I have seen a Status Change email but not every time I changed the status in the incident.  I only see it is if I change the status from the dashboard. 

Is there a example Open to Close incident process flow anywhere on how it works?

**Comment by jbrooksuk** [comment]
> How do update the incident? If I edit it, it does not email the subscribers.

This is something we're sorting out in v2.4 😄 

Pre-v2.4 the workflow is to create a new incident - obviously, this isn't very nice hence the update.

You can see this change at https://dev.cachethq.io
