### ISSUE TITLE
Laravel 5.1 And "Commands"

### ISSUE THREAD

**Issue by GrahamCampbell** [cachethq/Cachet#240]
The plan here is to upgrade to laravel 5, and implement some architectural improvements.

1. Upgrade to Laravel 5 (requires L5 to be stable and all packages we use to support L5)
2. Replace repositories with "commands" for writing, that might hit other services behind the scenes.
3. If by removing the repositories we lost any abstraction over reading, "presenters" might be a good move. I co-maintain "Laravel Auto Presenter".

---
NB, I plan to do this in ~~early February 2015~~ late June 2015.

**Comment by jbrooksuk** [comment]
Taylor Otwell has a [video on Laracasts](https://laracasts.com/lessons/laravel-5-commands) explaining the new L5 commands - it's a good watch!

**Comment by GrahamCampbell** [comment]
Yeh, I've seen it already actually. :)

**Comment by GrahamCampbell** [comment]
Oh, yeh, forgot to mention, I plan to move all validation to the commands. That is definitely the best place for it as far as I can see.

**Comment by jbrooksuk** [comment]
That makes sense!

**Comment by GrahamCampbell** [comment]
This architecture is so cool. I can't wait. :)

**Comment by joecohens** [comment]
:+1: Laravel 5 it's going to be so cool.

**Comment by GrahamCampbell** [comment]
Also, it might be cool to use https://github.com/Respect/Validation for validation in our commands.

My idea is to have command objects that are instantiated with the user input and then validation happens right there in the constructor. If validation fails, we get a really nice exception to deal with back in the controller. If validation passes, then the command object is successfully instantiated, and can then be "handled".

**Comment by joshhornby** [comment]
@GrahamCampbell Validation in commands seems a pretty interesting idea. Do you know any good sources/code examples where I can see more about this?

**Comment by GrahamCampbell** [comment]
Sorry, never seen it before. I just figured it would be a good idea. :)

**Comment by foxted** [comment]
Out of curiosity: Why not using the Form Request feature?

**Comment by GrahamCampbell** [comment]
> Why not using the Form Request feature?

I don't see the point in it. I don't think validation belongs in it. Otherwise, we have to implement validation twice - once for command line interface, and again for http interface.

**Comment by foxted** [comment]
Make sense :+1:

**Comment by GrahamCampbell** [comment]
This is going to be done later into the 2.0 cycle, that is, if I'm still doing it.

**Comment by joecohens** [comment]
@GrahamCampbell Do you mean if you still doing the Commands and Handlers thing?

**Comment by GrahamCampbell** [comment]
Yeh. I guess I might be able to squeeze in the L5 upgrade earlier.

**Comment by jbrooksuk** [comment]
Moved into First Release again as we're now working on L5 branch.

**Comment by jbrooksuk** [comment]
@GrahamCampbell what's the low down on this? We're technically using commands now with the subscriber stuff.

**Comment by jbrooksuk** [comment]
Actually, re-reading the issue itself, we've done the above.
