### ISSUE TITLE
Unable to send emails via Postmark SMTP 

### ISSUE THREAD

**Issue by awalls** [CachetHQ/Cachet#2400]
Hi,

I am trying to send email via Postmark SMTP servers but I keep getting the following error message below:

```
[2017-03-02 10:07:31] production.ERROR: Swift_TransportException: Connection could not be 
established with host smtp.postmarkapp.com [Connection timed out #110] in /home/my_acc/sub-
accounts/status.example.com/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Transport/StreamBuf
fer.php:269
```

My .env file includes:

```
CACHE_DRIVER=file
SESSION_DRIVER=file
QUEUE_DRIVER=database
CACHET_EMOJI=false

MAIL_DRIVER=smtp
MAIL_HOST=smtp.postmarkapp.com
MAIL_PORT=25
MAIL_USERNAME=<POSTMARK-API-KEY>
MAIL_PASSWORD=<POSTMARK-API-KEY>
MAIL_ADDRESS=info@example.com
MAIL_NAME=MyCompany
MAIL_ENCRYPTION=tls
```

When for example I send an invite to a colleague to the UI tells me it has been sent but a minute later when the job queue is processed I can see the error above in logs. I am using the same Postmark server on another account on my server running a CodeIgniter based app using the same host, port and username/password without any issue.

Appricaite any help or pointers to get to the bottom of this.

**Comment by jbrooksuk** [comment]
I've not used Postmark before but I'll try and take a look tonight to see what settings you need.

Looking at the [Developer Documentation](http://developer.postmarkapp.com/developer-send-smtp.html), it suggests trying `25, 2525, or 587` as port numbers. Could you try all three variations, please?

**Comment by awalls** [comment]
Thanks @jbrooksuk. Have tried all three ports and same issue.I am also double checking with server provider the ports are open but we are using Postmark via SMTP on a different account on this server and it is working ok there.

**Comment by jbrooksuk** [comment]
Okay, no problem. I will try tonight too.

**Comment by awalls** [comment]
Just a quick update. I checked with our hosting provider and the IP address range for Postmark were not whitelisted on our server firewall even through the ports were open ok.

http://support.postmarkapp.com/article/800-ips-for-firewalls

Everything is working as it should at the minute. Thanks for looking into this. Will close the issue.
