### ISSUE TITLE
Connect to database using Unix sockets

### ISSUE THREAD

**Issue by axilleas** [CachetHQ/Cachet#2402]
Is it possible? I don't see an option https://github.com/CachetHQ/Cachet/blob/2.4/config/database.php.

Would it be fixed if we added a `unix_socket` option to `database.php`? The only thing I found in Laravel docs was https://laravel.com/docs/5.4/cache#driver-prerequisites, where in memcache they say:

> You may also set the `host` option to a UNIX socket path. If you do this, the `port` option should be set to 0.

I wonder if it works the same with mysql/postgres.

**Comment by axilleas** [comment]
I was able to make it work with:

```
DB_DRIVER=pgsql
DB_HOST=/var/run/postgresql
DB_DATABASE=cachet
DB_USERNAME=cachet
DB_PREFIX=null
```

I had to remove `DB_PASSWORD` and `DB_HOST` from `.env` to make it work. It would be nice to document that :)

**Comment by jbrooksuk** [comment]
Feel free to submit edits to our documentation at https://docs.cachethq.io 😄

**Comment by axilleas** [comment]
I will :)

**Comment by jbrooksuk** [comment]
Awesome! Thanks :)
