### ISSUE TITLE
Two-factor auth flow should ignore spaces in token

### ISSUE THREAD

**Issue by wolfgang42** [CachetHQ/Cachet#2405]
I enabled two-factor auth and then panicked because I couldn't log in any more. This turned out to be because the Google Authenticator app displays the code in two halves, like `123 456`, but the authentication code is expecting the digits all together, like `123456`. The auth flow should probably strip the spaces from this field before checking it, so that both ways work as expected.

**Comment by jbrooksuk** [comment]
Nice observation!

**Comment by jbrooksuk** [comment]
Fixed in https://github.com/CachetHQ/Cachet/commit/2742797897a8ecbda549b8fe62e527bc30c162c0
