### ISSUE TITLE
Incident Ordering on Home Page

### ISSUE THREAD

**Issue by jimmybrancaccio** [CachetHQ/Cachet#2406]
I've attempted to search for an answer to this question but have come up empty handed. Is there anyway to sort how incidents are ordered on the home page. For example, I had two incidents yesterday, the first one displayed first (happened at 9am) and the second one displayed second (8pm), sounds normal? Ha. But I want it displayed so that the one that happened more recently is displayed on top. From the screenshot, I want the one relating to MyVideoGameList to be on top. Possible?

<img width="978" alt="screen shot 2017-03-05 at 2 45 58 pm" src="https://cloud.githubusercontent.com/assets/405585/23591204/880a3c94-01b2-11e7-970f-eee58ce369a4.png">

**Comment by jbrooksuk** [comment]
You'll be pleased to know that we've already fixed this in the next release; https://github.com/CachetHQ/Cachet/commit/a0f2d6642ef7112122a39392559e9511a0edbcab

**Comment by jimmybrancaccio** [comment]
That's awesome. I tried looking through PRs too but I guess the wording is a bit different then I was looking for. Thanks @jbrooksuk! 👍 Looking forward to 2.4!

**Comment by jbrooksuk** [comment]
No problem!
