### ISSUE TITLE
CachetHQ metrics usecase

### ISSUE THREAD

**Issue by sukhada369** [CachetHQ/Cachet#2407]
Hi,

Can you please elaborate on the use cases for which metrics can be useful?

**Comment by brianjking** [comment]
Showing uptime percentages, ping response time, etc.

<img width="910" alt="screenshot3-6-1722 23" src="https://cloud.githubusercontent.com/assets/6786817/23641699/81be95b0-02bb-11e7-884e-bedb8eb802f0.png">
