### ISSUE TITLE
2FA Recovery Codes

### ISSUE THREAD

**Issue by ShadowFM** [CachetHQ/Cachet#2408]
If I add the 2FA on my account I don't need to verify it.
So if I add the option and log out the account is over.

**Comment by jbrooksuk** [comment]
I suppose one way would be recovery codes. We should implement these at some point too!

**Comment by jbrooksuk** [comment]
Thank you for your input on Cachet 2.x. We are shifting our attention and resources to Cachet 3.x and will no longer be supporting the 2.x version. If your feedback or issue is relevant to the 3.x series, we encourage you to engage with the new branch.

For more information on the Cachet rebuild and our plans for 3.x, you can read the announcement [here](https://github.com/CachetHQ/Cachet/discussions/4342).

We appreciate your understanding and look forward to your contributions to the new version.
