### ISSUE TITLE
Email Notification not using correct app.name

### ISSUE THREAD

**Issue by OzWookiee** [CachetHQ/Cachet#2410]
I am getting notification emails that are showing "Cachet" as the app.name instead of our correct setting

```
{
  "meta": {
    "on_latest": true,
    "latest": {
      "tag_name": "v2.3.10",
      "prelease": false,
      "draft": false
    }
  },
  "data": "2.4.0-dev"
}
```
resources/views/vendor/notifications/email.blade.php line 72:
```
                        <td style="{{ $style['email-masthead'] }}">
                            <a style="{{ $fontFamily }} {{ $style['email-masthead_name'] }}" href="{{ url('/') }}" target="_blank">
                                {{ config('app.name') }}
                            </a>
                        </td>
                    </tr>
```
Mysql Settings: http://imgur.com/1xrQcps

Email Notificaiton: http://imgur.com/KFaNsGN

**Comment by OzWookiee** [comment]
I have done a config and cache clear and still getting the same issue.

**Comment by jbrooksuk** [comment]
Whoops! This should be the status page name, not Cachet anyway.

**Comment by OzWookiee** [comment]
Here is the log from today after repeating the above.
```
[2017-03-19 22:00:34] production.WARNING: exception 'Symfony\Component\HttpKernel\Exception\HttpException' in /var/www/Cachet/app/Http/Middleware/Authenticate.php:51
```

Log file: [laravel-2017-03-19.log.txt](https://github.com/CachetHQ/Cachet/files/853609/laravel-2017-03-19.log.txt)
