### ISSUE TITLE
Write documentation for Incident Updates

### ISSUE THREAD

**Issue by OzWookiee** [CachetHQ/Cachet#2412]
When will Updates get POST/PUT in the API  :) ??

https://docs.cachethq.io/reference#incidentsidupdates only lists GET's

**Comment by jbrooksuk** [comment]
We already have a full API for Incident Updates, we just haven't documented it yet 🙈 

https://github.com/CachetHQ/Cachet/blob/2742797897a8ecbda549b8fe62e527bc30c162c0/app/Http/Routes/ApiRoutes.php#L73

**Comment by jbrooksuk** [comment]
I will do this, I promise!

**Comment by OzWookiee** [comment]
Ahh awesome. Will go through that when I get back to work!

**Comment by jbrooksuk** [comment]
I just linked to one of the endpoints by the way. I've also updated the title of the issue :)

**Comment by OzWookiee** [comment]
using this end point for an incident I'd just created (id:8) /api/v1/incidents/8/updates and the following body:
```
{"name":"An Update","message":"This is an update","status":4,"visible":1,"component_id":1,"component_status":1,"notify":"true"}
```
I get this response
```
{
  "errors": [
    {
      "id": "03bf7cda-17c4-4116-9665-9f06cbd18749",
      "status": 404,
      "title": "Not Found",
      "detail": "The requested resource could not be found but may be available again in the future."
    }
  ]
}
```


This is the version information:
```
{
  "meta": {
    "on_latest": true,
    "latest": {
      "tag_name": "v2.3.10",
      "prelease": false,
      "draft": false
    }
  },
  "data": "2.4.0-dev"
}
```

**Comment by jbrooksuk** [comment]
Can you provide the `laravel.log` file too please?

**Comment by OzWookiee** [comment]
Here is the log from today after repeating the above.
```
[2017-03-19 22:00:34] production.WARNING: exception 'Symfony\Component\HttpKernel\Exception\HttpException' in /var/www/Cachet/app/Http/Middleware/Authenticate.php:51
```

Log file: [laravel-2017-03-19.log.txt](https://github.com/CachetHQ/Cachet/files/853609/laravel-2017-03-19.log.txt)

**Comment by jbrooksuk** [comment]
I've added basic docs. They'll all be fleshed out at some point :)

**Comment by chronicals** [comment]
Have the exact same problem as OzWookiee. The problem is I don't get any error message.

Sending request to `/api/v1/incidents/19/updates` :
```
curl -H "Content-Type: application/json;" -H "X-Cachet-Token: FouC1WO5LB50nQIywW9A" -d '{"status":3,"message":"Seems fixed, looking into it #demotext."}' https://serverstatus.com/api/v1/incidents/19
```
Answer: 
```
{"errors":[{"id":"1880d956-5531-432c-8b9b-cfefce4b3c6d","status":404,"title":"Not Found","detail":"The requested resource could not be found but may be available again in the future."}]}
```

**Comment by jbrooksuk** [comment]
:+1:
