### ISSUE TITLE
Formatting of Scheduled Maintainance

### ISSUE THREAD

**Issue by sukhada369** [CachetHQ/Cachet#2413]
When I add an link in [title] (link) format, the way it is displayed on the screen is weird.

![image](https://cloud.githubusercontent.com/assets/12746279/23643959/e62df454-032a-11e7-8919-4f67833de979.png)

What I added to the description box is as follows:
This is a demo scheduled maintenance:
- this is line 1 [link](https://www.google.com/)
- this is line 2 [link](https://www.google.com/)
- this is line 3 [link](https://www.google.com/)

**Comment by jbrooksuk** [comment]
What version of Cachet are you using?

Is it possible we could get a full screenshot of that window?

**Comment by jbrooksuk** [comment]
This was caused by using a link in the `list-group`.
