### ISSUE TITLE
Metric only display points from page 1

### ISSUE THREAD

**Issue by fgth** [CachetHQ/Cachet#2414]
Hi again,
I start using metrics yesterday, by downgrading the script by Axiacore (automatic updates from Uptime Robot) for Python 2.7. All was fine but this morning I see that the graph stops at 23 pm yesterday. Checking in Mysql I can see that the points exist from yesterday to now.
After some requests, I found that the datas displayed was only these on page 1 :
curl -X GET -H "Content-Type: application/json" -H "X-Cachet-Token: my_token" https://status.mydomain.com/api/v1/metrics/2/points
is equivalent to :
curl -X GET -H "Content-Type: application/json" -H "X-Cachet-Token: my_token" https://status.mydomain.com/api/v1/metrics/2/points?page=1

but the last points are on pages > 1.
Is there a problem in the API (is the graph using the API ?) or something that I do wrong ?
Thanks for job ! And for suggestions.

**Comment by fgth** [comment]
Oooops. Strange, so strange... At 12pm, the graph suddenly display the right points, from midnight to now... I'm sure that wasn't a problem with cache (tested in a private firefox window). I don't understand what happens. If you agree, I leave this issue opened for some times and will close it if the problem doesn't reappear.

**Comment by jbrooksuk** [comment]
What version of Cachet were you using?

**Comment by fgth** [comment]
It's (last) 2.4-dev

**Comment by jbrooksuk** [comment]
Hmmm... We really do need to finalise metrics.

**Comment by fgth** [comment]
Well.. I'm not sure today about what I've seen :/
The graph, like yesterday, finished by "23:00", but I discover that the preceding hours was correct.
for ex : in "last 12 hours" mode, at 10am this morning, we had on axis from 22:00 to 9:00, and the last value was... "23:00". Can't remember if it was the same thing yesterday.
At 12pm like yesterday, the graph now display all the correct hours.

I hope I'm enough clear in this explanations. I'll continue to check this.

**Comment by fgth** [comment]
I can confirm that until 12:00, the last or the two last hours on graph stay at 22 or 23:00. This screenshot was taken at 11:07. Than at 12:00, all return to normal. 
![capture d ecran_2017-03-31_11-07-41](https://cloud.githubusercontent.com/assets/1536832/24544116/5d36f1ba-1602-11e7-85cd-c5fd54b910cd.png)

**Comment by jbrooksuk** [comment]
@fgth sorry for the delay! I'm starting to look at metrics now. Are you able to provide me with any example dumps?

**Comment by jbrooksuk** [comment]
I believe this is now fixed :)

**Comment by jbrooksuk** [comment]
See 986f6c56
