### ISSUE TITLE
Previous/Next "week" must be "range"

### ISSUE THREAD

**Issue by fgth** [CachetHQ/Cachet#2415]
Hi again again again :)
Just a remark about the legend of buttons "previous week", "next week" : if I understand correctly, it select the previous/next range (sets in application settings/number of days to show) not only a week, so perhaps they should be renamed ?

**Comment by jbrooksuk** [comment]
This has been brought up a few times now, I should really fix it 🙈

**Comment by fgth** [comment]
It's OK, with only "Previous" / "Next".
Thanks !
