### ISSUE TITLE
Does database need periodical cleanup?

### ISSUE THREAD

**Issue by genzj** [CachetHQ/Cachet#2416]
After being integrated into Icinga monitor system as event handler, several unstable services generate many incidents everyday. Does the database need cleanup periodically to save room? If so, how should I do that?

Thanks a lot!

**Comment by jbrooksuk** [comment]
How many incidents are we talking? You could implement an archiving tool.

**Comment by genzj** [comment]
about 100 incidents in last 12 hours. could you please give me a clue which table(s) I should pay attention to?
thanks a lot.

**Comment by jbrooksuk** [comment]
Ping @ConnorVG something to investigate for performance!

**Comment by jbrooksuk** [comment]
2.4 is better with indexing.

**Comment by TobiTenno** [comment]
was hoping to find something to truncate to the last 30 days or so. I run a pretty minimal monitoring board and was hoping to trim down how much I store. I've been able to run for a few years on the same database/instance, but i'm hoping to reduce my current disk usage
