### ISSUE TITLE
Toggling of Weeks in Home Page

### ISSUE THREAD

**Issue by TheoBearman** [CachetHQ/Cachet#2420]
I cannot seem to be able to toggle to the previous week in the _Past Incidents_ section of my home page. Could this be something do to with 9a56625f0980e14cab3fb5e6711cdaa2878995a1?

**Comment by jbrooksuk** [comment]
Sorry @TheoBearman I'm confused? All we've done is change the pagination links to Next and Previous instead of Next Week and Previous Week.

**Comment by TheoBearman** [comment]
See my install here: https://status.theobearman.com/

I am not presented with these options.

**Comment by TheoBearman** [comment]
Bump.

**Comment by jbrooksuk** [comment]
@TheoBearman looking at your API you don't have any incidents? https://status.theobearman.com/api/v1/incidents we only show those buttons if there is anything to go back to.

I don't think this is a bug, unless you're losing data.

**Comment by jbrooksuk** [comment]
Let me know if you have more info 😄

**Comment by TheoBearman** [comment]
Correct. Thanks for the clarification James. Wasn't aware that the presence of incidents was a condition!

**Comment by jbrooksuk** [comment]
😊
