### ISSUE TITLE
How to translate?

### ISSUE THREAD

**Issue by omtr** [CachetHQ/Cachet#2421]
Not an issue, just a question: what is the best approach to makes changes in the language files?
edit the file in /resources/lang/<mylanguage>? obviously the changes do not take effect, i guess i have to commit them or maybe just clear the cache...?
Can you give me a hint how to do it the right way?
Thanks!

**Comment by jbrooksuk** [comment]
You can submit translations to https://translate.cachethq.io and we'll merge them in.

**Comment by omtr** [comment]
i know that i can submit them and i already did, but sometimes i want some translations that are useless for public use, such as brand names or special use cases.

**Comment by jbrooksuk** [comment]
You can create your own language directory if you wanted? Set the `fallback_locale` to whatever language you want, and `locale` to the language you create.
