### ISSUE TITLE
Component continues at major outage even after all the incidents are marked as fixed

### ISSUE THREAD

**Issue by checkium** [CachetHQ/Cachet#2423]
![image](https://cloud.githubusercontent.com/assets/9268058/23798929/932c4924-059e-11e7-83d5-880217c74f14.png)

**Comment by jbrooksuk** [comment]
The status is also based on the overall status of your components. Your Website component needs updating too.

**Comment by checkium** [comment]
@jbrooksuk If I update it manually it will trigger a second email saying it was manually changed beyound the "issue as been fixed" one

**Comment by jbrooksuk** [comment]
What version of Cachet are you using?

**Comment by checkium** [comment]
@jbrooksuk 2.3.9
