### ISSUE TITLE
Metric set to average acting strange

### ISSUE THREAD

**Issue by checkium** [CachetHQ/Cachet#2429]
Hi, I'm running cachet 2.3.10 and I have a metric set to average:
![image](https://cloud.githubusercontent.com/assets/9268058/23828167/496ce590-06c1-11e7-87cf-4879a92ad018.png)
The problem is that, for example, right now the value is 19718, and if I send another point some minutes later with a value of 500, it will then display 19968.
I can't find from where that number comes, it seems to almost act like sum and add the two values, but not completly.
Edit: I think I found it, if I add two points at the same 5 minutes (threshold) it will sum that two values, is that intended?

**Comment by jbrooksuk** [comment]
Correct, that can be configured via the threshold.
