### ISSUE TITLE
Component status isn´t calculated properly in 2.4.0-dev

### ISSUE THREAD

**Issue by gregorkistler** [CachetHQ/Cachet#2430]
Hi,

really great project btw :)

Yesterday I´ve installed a fresh instance from scratch using:

Ubuntu 16.04.2 LTS 4.4.0-66-generic
PHP 7.0.15-0ubuntu0.16.04.4
psql (PostgreSQL) 9.6.2
Redis server v=3.0.6 build=687a2a319020fa42
nginx/1.11.10
Kemp Loadmaster 7.2.37.1 (HTTPS redirect and SSL termination)

as well as the current Cachet Github repo: 2.4

php artisan cachet:version reports: Cachet 2.4.0-dev is installed

My problem so far looks like this:

![screen shot 2017-03-12 at 14 24 17](https://cloud.githubusercontent.com/assets/12155030/23833175/497a2f4e-0742-11e7-926b-2e7bc67ddcd7.png)

and this:

![screen shot 2017-03-12 at 15 34 46](https://cloud.githubusercontent.com/assets/12155030/23833174/49799674-0742-11e7-9ce9-4e64e6776253.png)

If I mark any of the components via dashboard (haven´t tried the API yet .. also no incidents were involved at this stage) with a status other than 'Major Outage' the status won´t change and still show the green banner 'All systems are operational' or in case only one exists then 'System operational'.
Only if at least one component has a 'Major Outage' the banner gets red.

Yesterday I also instantiated some Docker containers with version 2.3.10 and it went flawless. Each status brought me up a different color.

If I create an incident on the other hand, don´t fix it but put all components in 'Operational' status it will still show a non-green banner. Guess the latter is more or less 'as designed'  because a possible incident status isn´t related to a component status.
For the first one I have no other guess than it´s really a bug.

Any clues?

Thanks

Here´s my .env - already tried different queue, session and cache driver like apc but the result was the same:

```
APP_ENV=production
APP_DEBUG=false
APP_URL=<removed>
APP_KEY=<removed>

DB_DRIVER=pgsql
DB_HOST=localhost
DB_DATABASE=<removed>
DB_USERNAME=<removed>
DB_PASSWORD=<removed>
DB_PORT=5432

CACHE_DRIVER=redis
SESSION_DRIVER=redis
QUEUE_DRIVER=redis

CACHET_BEACON=false
CACHET_EMOJI=false
CACHET_AUTO_TWITTER=false

MAIL_DRIVER=smtp
MAIL_HOST=smtp.gmail.com
MAIL_PORT=587
MAIL_USERNAME=<removed>
MAIL_PASSWORD=<removed>
MAIL_ADDRESS=<removed>
MAIL_NAME=<removed>
MAIL_ENCRYPTION=tls

REDIS_HOST=127.0.0.1
REDIS_DATABASE=0
REDIS_PORT=6379

GITHUB_TOKEN=null

NEXMO_KEY=null
NEXMO_SECRET=null
NEXMO_SMS_FROM=null
```

**Comment by jbrooksuk** [comment]
Interesting...

**Comment by jbrooksuk** [comment]
Wait, wait, did you have any non-fixed incidents open at the same time? The status bar is calculated with both components and incidents.

**Comment by gregorkistler** [comment]
Nope, when I made the first screenshot my setup contained only one (happen also with more than one) component, no incidents at all.

Incidents were involved in the second one.

**Comment by jbrooksuk** [comment]
💥 found the issue! All fixed.

**Comment by gregorkistler** [comment]
Sweet!

Thank you
