### ISSUE TITLE
Issues with installation on shared hosting

### ISSUE THREAD

**Issue by emillod** [CachetHQ/Cachet#2432]
Hello, i want to install cachet on shared hosting, but my hosting doesn't support node.js.. Can i install cachet on hosting without node.js?

**Comment by jbrooksuk** [comment]
Cachet does not require Node.js, that's only for development. That said, Cachet doesn't support shared hosts.

**Comment by emillod** [comment]
But i remember that Cachet supported shared hosting, am i wrong?

**Comment by jbrooksuk** [comment]
Not out of the box, but with a bit of effort it might 🙂

**Comment by emillod** [comment]
Do you have any Official tutorial to install Cachet on CentOS 7? I want to install Cachet in lan network.. 
Thanks for reply 😄

**Comment by emillod** [comment]
I try to install Cachet with this tutorial: https://sysadmincollective.blogspot.com/2016/05/installing-cachet-on-centos-7.html

But i have issues with php-xml, because Cachet require PHP 5.6 version. Do you have any idea how to fix this ?
/open

**Comment by jbrooksuk** [comment]
You need to add the missing extensions 👍

**Comment by emillod** [comment]
I know that, but i can't find php-xml for PHP 5.6 ... haha :D

**Comment by jbrooksuk** [comment]
Can't you do `yum --enablerepo remi install php-xml`?

**Comment by dwydler** [comment]
Try `yum install php-xml`

**Comment by emillod** [comment]
> Can't you do yum --enablerepo remi install php-xml?
I tried this, but "Can't find package php5.6-xml"

> Try yum install php-xml
error: Package php-xml-5.4.45-13.el7.remi.x86_84
          Require: php-common(x86-64) = 5.4.45-13.el7.remi
          Already installed:  php-common-5.6.30-1.el7.remi.x86_64 (@remi-php56)

**Comment by dwydler** [comment]
Read follow comment:
https://github.com/puphpet/puphpet/issues/2221#issuecomment-195035556

**Comment by emillod** [comment]
OK, but:
1. I have php-common 5.6* (Cachet require php 5.6 ^)
And when i try to install php-xml my system have problem because php-xml have version 5.4 and require php-common with version **5.4**
> php-common(x86-64) = 5.4.16-42.el7 for package: php-xml-5.4.16-42.el7.x86_64

here you have error in polish:
> --> Przetwarzanie zależności: php-common(x86-64) = 5.4.16-42.el7 dla pakietu: php-xml-5.4.16-42.el7.x86_64
--> Ukończono rozwiązywanie zależności
Błąd: Pakiet: php-xml-5.4.16-42.el7.x86_64 (base)
          Wymaga: php-common(x86-64) = 5.4.16-42.el7
          Zainstalowano: php-common-5.6.30-1.el7.remi.x86_64 (@remi-php56)
              php-common(x86-64) = 5.6.30-1.el7.remi
          Dostępne: php-common-5.4.16-42.el7.x86_64 (base)
              php-common(x86-64) = 5.4.16-42.el7
 Można spróbować użyć --skip-broken, aby obejść problem
 Można spróbować wykonać polecenie: rpm -Va --nofiles --nodigest
