### ISSUE TITLE
Component status not rolling up to component group status

### ISSUE THREAD

**Issue by willallen** [CachetHQ/Cachet#2434]
Hi guys -

I am a really big fan of the tool and I am getting ready to it out to our production environment. I have worked through a few issues but I am stumped on one of them. 

When I update a component status the status changes on the dashboard but in some cases (not all) the component group status does not update. We have seen this issue before and in order to resolve we deleted all components and re-added. I have about 60 components in there now so I would like to avoid having to do that again if possible.

Any thoughts? 

**Some info...**
- Php 7.1.2
- RHEL 7.3
- Apache 2.4.6
- Mariadb 5.5.52

![image](https://cloud.githubusercontent.com/assets/6948057/23949717/c6857f7a-095e-11e7-9934-2f31d2423cb1.png)

**Comment by jbrooksuk** [comment]
The system status bar is also counting Incidents. The reason I implemented this is because Incidents can be unrelated to the Components as a whole.

Thoughts?

**Comment by willallen** [comment]
@jbrooksuk that makes total sense. Any ideas on why the component (business intelligent) and component (sap) aren't matching up? It is a mixed bag, some components update the component group and some don't.

**Comment by jbrooksuk** [comment]
What version of Cachet? I think I fixed this in either 2.4 or the new design branch :)

**Comment by willallen** [comment]
We are on 2.3.9!

**Comment by jbrooksuk** [comment]
In which case were fixed in the next version :)

**Comment by tcrall** [comment]
I'm seeing this behavior, and I'm running 2.5.0-dev

**Comment by willallen** [comment]
@tcrall do you mean 2.4.0-dev?

**Comment by tcrall** [comment]
Am I misunderstanding this?

![Uploading Screen Shot 2017-03-24 at 9.05.47 PM.png…]()

**Comment by jbrooksuk** [comment]
I'm confused?

**Comment by willallen** [comment]
@tcrall I am seeing this on 2.3.9. I can't see the upload but I don't think there is a 2.5 out there.

**Comment by willallen** [comment]
@tcrall just a heads up I just updated dependencies and that seemed to resolve all the issues. Not sure why but hope that works for you.

`composer install --no-dev -o --no-scripts`

**Comment by tcrall** [comment]
I can't seem to load screenshots for some reason, but my cachet dashboard sidebar underneath 'Credits' says '2.5.0-dev' - is that not the version?

**Comment by tcrall** [comment]
http://imgur.com/a/te7sS

**Comment by jbrooksuk** [comment]
Assuming you're using Docker?

**Comment by tcrall** [comment]
yes
