### ISSUE TITLE
Today's issues are not in the Past

### ISSUE THREAD

**Issue by OzWookiee** [CachetHQ/Cachet#2435]
It's a little strange that if an incident is reported **now()** then it appears under the heading **Past Incidents**.

http://imgur.com/1pQQSKJ

I just created the above issue so it is not in the past. Past Issues also implies that the issue was previously resolved. Now there is **kind of** a work around in that I can make the issue sticky **but** the issue also appears in the Past Issues list as well.

```
{
  "meta": {
    "on_latest": true,
    "latest": {
      "tag_name": "v2.3.10",
      "prelease": false,
      "draft": false
    }
  },
  "data": "2.4.0-dev"
}
```

**Comment by jbrooksuk** [comment]
Yes and no. The heading is perhaps a bit misleading. In the new design this won't be an issue.
