### ISSUE TITLE
500 Thrown on Load

### ISSUE THREAD

**Issue by TheoBearman** [CachetHQ/Cachet#2441]
Install at: [https://status.theobearman.com](https://status.theobearman.com)

Error:

`[2017-03-18 18:37:43] local.CRITICAL: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'syntax error, unexpected '->' (T_OBJECT_OPERATOR)' in /var/www/html/Cachet/app/Integrations/Core/System.php:53
Stack trace:
#0 {main} {"identification":{"id":"e65315e4-c39d-401c-b480-48a4debbc05e"}} 
`

I believe this is linked to 15297205c453893a2a7df0b605756c11533b21c8

**Comment by GrahamCampbell** [comment]
Yeh. I think Cachet will be dropping support for PHP 5 soon though.

**Comment by GrahamCampbell** [comment]
This should probably fix it: https://github.com/CachetHQ/Cachet/pull/2442.

**Comment by TheoBearman** [comment]
Fixed. Cheers 😄
