### ISSUE TITLE
HTTP 500 Error on Fresh Install - CentOS 7

### ISSUE THREAD

**Issue by johnbboyd** [CachetHQ/Cachet#2445]
I'm getting HTTP 500 Error on fresh Install

Environment - 

CentOS 7, PHP 5.6, Httpd, git checkout v2.3.9

Tutorial I followed - 

https://docs.cachethq.io/v1.0/docs/installing-cachet

httpd]$ more error_log
[Mon Mar 20 07:01:08.551988 2017] [core:notice] [pid 19824] SELinux policy enabled; httpd running as context system_u:system_r:httpd_t:s0
[Mon Mar 20 07:01:08.553323 2017] [suexec:notice] [pid 19824] AH01232: suEXEC mechanism enabled (wrapper: /usr/sbin/suexec)
[Mon Mar 20 07:01:08.577419 2017] [auth_digest:notice] [pid 19824] AH01757: generating secret for digest authentication ...
[Mon Mar 20 07:01:08.578178 2017] [lbmethod_heartbeat:notice] [pid 19824] AH02282: No slotmem from mod_heartmonitor
[Mon Mar 20 07:01:08.618942 2017] [mpm_prefork:notice] [pid 19824] AH00163: Apache/2.4.6 (CentOS) PHP/5.6.30 configured -- resuming normal operations
[Mon Mar 20 07:01:08.618987 2017] [core:notice] [pid 19824] AH00094: Command line: '/usr/sbin/httpd -D FOREGROUND'
[Mon Mar 20 07:01:30.374817 2017] [:error] [pid 19830] [client 106.210.153.231:8427] PHP Fatal error:  Uncaught exception 'UnexpectedValueException' with message 'The s
tream or file "/var/www/Cachet/storage/logs/laravel-2017-03-20.log" could not be opened: failed to open stream: Permission denied' in /var/www/Cachet/vendor/monolog/mon
olog/src/Monolog/Handler/StreamHandler.php:107\nStack trace:\n#0 /var/www/Cachet/vendor/monolog/monolog/src/Monolog/Handler/RotatingFileHandler.php(107): Monolog\\Handl
er\\StreamHandler->write(Array)\n#1 /var/www/Cachet/vendor/monolog/monolog/src/Monolog/Handler/AbstractProcessingHandler.php(37): Monolog\\Handler\\RotatingFileHandler-
>write(Array)\n#2 /var/www/Cachet/vendor/monolog/monolog/src/Monolog/Logger.php(336): Monolog\\Handler\\AbstractProcessingHandler->handle(Array)\n#3 /var/www/Cachet/ven
dor/monolog/monolog/src/Monolog/Logger.php(615): Monolog\\Logger->addRecord(400, Object(UnexpectedValueException), Array)\n#4 /var/www/Cachet/vendor/laravel/framework/s
rc/Illuminate/Log/Writer.php(202): Monolog\\Logger->error(Object(UnexpectedValueException), Array)\n#5 /var/www/Cachet/vendor/laravel/ in /var/www/Cachet/vendor/monolog
/monolog/src/Monolog/Handler/StreamHandler.php on line 107
[Mon Mar 20 07:01:30.375735 2017] [:error] [pid 19830] [client 106.210.153.231:8427] PHP Fatal error:  Uncaught exception 'UnexpectedValueException' with message 'The s
tream or file "/var/www/Cachet/storage/logs/laravel-2017-03-20.log" could not be opened: failed to open stream: Permission denied' in /var/www/Cachet/vendor/monolog/mon
olog/src/Monolog/Handler/StreamHandler.php:107\nStack trace:\n#0 /var/www/Cachet/vendor/monolog/monolog/src/Monolog/Handler/RotatingFileHandler.php(107): Monolog\\Handl
er\\StreamHandler->write(Array)\n#1 /var/www/Cachet/vendor/monolog/monolog/src/Monolog/Handler/AbstractProcessingHandler.php(37): Monolog\\Handler\\RotatingFileHandler-
>write(Array)\n#2 /var/www/Cachet/vendor/monolog/monolog/src/Monolog/Logger.php(336): Monolog\\Handler\\AbstractProcessingHandler->handle(Array)\n#3 /var/www/Cachet/ven
dor/monolog/monolog/src/Monolog/Logger.php(643): Monolog\\Logger->addRecord(500, Object(Symfony\\Component\\Debug\\Exception\\FatalErrorException), Array)\n#4 /var/www/
Cachet/vendor/laravel/framework/src/Illuminate/Log/Writer.php(202): Monolog\\Logger->critical(Object(Symfony\\Component\\Debug\\Exception\\Fa in /var/www/Cachet/vendor/
monolog/monolog/src/Monolog/Handler/StreamHandler.php on line 107

If you need me to paste anything else, please let me know

**Comment by jbrooksuk** [comment]
You need to make the `storage` and `bootstrap/*` directories writeable 👍

**Comment by johnbboyd** [comment]
I did already

chmod -R 777 storage
chmod -R 777 bootstrap/

They have 'drwxrwxrwx.' permission
