### ISSUE TITLE
Multiple emails sent out when reordering, editing components

### ISSUE THREAD

**Issue by oznorts** [CachetHQ/Cachet#2450]
When I reorder components or edit them (but don't edit the status of them) my subscribers get a ton of emails saying the status was updated, when it really wasn't.

**Comment by jbrooksuk** [comment]
Is this in v2.4 or v2.3?

**Comment by oznorts** [comment]
v2.3 — haven't used v2.4 yet.

**Comment by jbrooksuk** [comment]
Ah, this is fixed in v2.4 as we now silence notifications when those type of updates are made :)
