### ISSUE TITLE
Say Group Name on Notification Updating and Honor Ordering

### ISSUE THREAD

**Issue by oznorts** [CachetHQ/Cachet#2451]
It's confusing on the notification management page for subscribers to see a ton of options but not be able to see what component group they're in.  A label before the name of the component saying the group name would be perfect.

Additionally, the order there is all out of whack, not following the order I set on the Component page in the dashboard.

**Comment by jbrooksuk** [comment]
The dashboard does display the group name, at least in v2.4

![](https://cldup.com/w2mMi7rlzR.png)

You're right that the orders are incorrect though!

**Comment by oznorts** [comment]
Actually, I just updated to 2.4.0 and it looks just like I wanted in it!
