### ISSUE TITLE
 Installing multiple cachet instances with docker on the same server

### ISSUE THREAD

**Issue by lilbil94** [CachetHQ/Cachet#2452]
I want to install several images of cachet with docker on the same server, and binder them with different port (http://status1.ca:80, http://status2.ca:81), I have an ubuntu server 16.04 with  Docker version 17.03.0-ce, and docker-compose version 1.8.1 , could you please share any ideas on how to achieve this?
thanks.

**Comment by jbrooksuk** [comment]
Can you open this on the [Docker](/CachetHQ/Docker) repo please?
