### ISSUE TITLE
Google Analytics failed to work

### ISSUE THREAD

**Issue by sirkkalap** [CachetHQ/Cachet#2454]
For some reason I had to edit `./resources/views/partials/analytics.blade.php` to get Google Analytics to work.

On line **7** I had to write:
`ga('create', '{{ $app_analytics }}', 'auto');`

The site I was working on is [status.digitraffic.fi](status.digitraffic.fi) .

Google Tag Assistant plugin for Chrome reported errors without this change and statistics were not received in Google Analytics.

**Comment by jbrooksuk** [comment]
What version of Cachet is this? 😄

**Comment by jbrooksuk** [comment]
I've fixed this in v2.4 :)
