### ISSUE TITLE
Subscriber Verification

### ISSUE THREAD

**Issue by TWG-Matt** [CachetHQ/Cachet#2456]
I've been trying to verify a test subscriber but each time it returns a 400 error on the url link I'm emailed.

I'm running the 2.4.0-dev build.

**Comment by jbrooksuk** [comment]
Ping @joecohens

**Comment by joecohens** [comment]
Could you share the url you are testing? I tested the functionality and it's working for me. Thanks!

**Comment by jbrooksuk** [comment]
No response in several months.
