### ISSUE TITLE
How to update dev build

### ISSUE THREAD

**Issue by TWG-Matt** [CachetHQ/Cachet#2457]
I was following the instructions you had on your site for the update but I didn't notice the 2.4.0-dev build in there for updating.  Am I missing something?

**Comment by PietsHost** [comment]
because v2.4.0-dev isn't tagged right now..

just run `git clone https://github.com/CachetHQ/Cachet.git`, `cd Cachet` and then `composer install --no-dev -o --no-scripts`

**Comment by TWG-Matt** [comment]
I see there is a --no-dev flag won't that **not** install the dev?

**Comment by PietsHost** [comment]
Just try it..

**Comment by jbrooksuk** [comment]
You need to check out the `2.4` branch. There are no tags for the dev builds yet 😄 

So the process is:

1. `cd $CACHET` (your Cachet installation directory)
2. `git fetch origin`
3. `git checkout 2.4`
4. `composer install --no-dev -o`
5. `php artisan app:update`
