### ISSUE TITLE
Running Cachet with Plesk?

### ISSUE THREAD

**Issue by AutoJukebox** [CachetHQ/Cachet#2461]
Is it possible to run Cachet along side plesk?

**Comment by nixmomo** [comment]
Yes no problem with plesk....give your plesk account the ssh chroot for composer and all is fine

**Comment by AutoJukebox** [comment]
Would i be able to run it off a subdomain? i.e status.mydomain.com

**Comment by nixmomo** [comment]
Sure, take a look at https://status.dl-host.info 
It's a backup plesk server where the site is up and running in a sub domain

Regards

**Comment by jbrooksuk** [comment]
:)
