### ISSUE TITLE
Change Manage Subscription Button in Subscriber Notification Email

### ISSUE THREAD

**Issue by Moogleson86** [CachetHQ/Cachet#2462]
We would like to see the Manage subscription button in a subscriber notification email to actually link to the current Incident that is triggering the email.

**Comment by jbrooksuk** [comment]
Which button in the email, sorry? Why wouldn't the "manage subscription" button take you to a page to manage the subscription?

**Comment by Moogleson86** [comment]
The green button that is currently labeled as Manage Subscription. Can we move the function of that button to the link below that says unsubscribe and turn it into Manage subscription.

Ultimately, the idea is to provide a link to the current incident that is sending out the notification.
________________________________

**Comment by Moogleson86** [comment]
Any further thoughts or ideas around my last update. 

Our thoughts are that there is redundancy in the manage subscription and unsubscribe link. We would like to be able to provide a link to the incident that is being emailed about. Condensing the subscription functions into one link.

Thanks

**Comment by jbrooksuk** [comment]
Sorry @Moogleson86 I haven't had much time to look at Cachet recently. I'll take a look this weekend.

**Comment by jbrooksuk** [comment]
This is now done.
