### ISSUE TITLE
Scheduled Maintenance screen data verification issue

### ISSUE THREAD

**Issue by wcom939** [CachetHQ/Cachet#2463]
Hi,

The scheduled maintenance screen entry field does not force non-null timestamps for the "When did this maintenance complete?" field which causes a 500 error if submitted with a null timestamp.

Additionally when a scheduled maintenance is added where can I find this on the main status page?

Thanks,
Dan

**Comment by jbrooksuk** [comment]
Are you using Safari? I'm sure that the field is `required`, but I could be wrong.

> Additionally when a scheduled maintenance is added where can I find this on the main status page?

Scheduled Maintenance appears below the metrics (if you have any).

**Comment by wcom939** [comment]
Using Firefox 52.0.1

All fields are required (including the start datetime field but not the scheduled to datetime field; at least as far as the browser is concerned).

Thanks!
Dan
