### ISSUE TITLE
Failed to open Stream /../vendor/autoload.php 

### ISSUE THREAD

**Issue by EH-Nathan** [CachetHQ/Cachet#2465]
Hello, When i generate the PHP key i get the following error:

php artisan key:generate

PHP Warning:  require(/var/www/vhosts/mysite/mysubdomain/bootstrap/../vendor/autoload.php): failed to open stream: No such file or directory in /var/www/vhosts/mysite/mysubdomain/bootstrap/autoload.php on line 28

I'm currently on the latest version of PHP and Composer

**Comment by jbrooksuk** [comment]
Have you ran `composer install`?

**Comment by EH-Nathan** [comment]
Yes, I am on the latest version on Composer

**Comment by jbrooksuk** [comment]
Did you run `composer install --no-dev -o` from within your Cachet directory though?

**Comment by EH-Nathan** [comment]
So i did that now i get this strange install page 

![ss 2017-03-23 at 06 54 12](https://cloud.githubusercontent.com/assets/26636030/24273724/51431608-0ffa-11e7-87ec-37e1aad28129.png)

**Comment by jbrooksuk** [comment]
Looks like you haven't configured the Apache site properly. https://docs.cachethq.io/docs/installing-cachet#section-running-cachet-on-apache

**Comment by EH-Nathan** [comment]
Hmm, Everything looks good on my part, Any specific thing from the installation that could cause that?

**Comment by jbrooksuk** [comment]
Likely an incorrect VHOST?

**Comment by EH-Nathan** [comment]
I'm using Plesk with Cachet running under a subdomain, Is that an issue?

**Comment by nixmomo** [comment]
No, Cachet works fine with Plesk... Can you Post the Webservers Logs? Looks that there is an chmod issue or the server can't find css files

**Comment by EH-Nathan** [comment]
[Mon Mar 27 19:16:12.899073 2017] [autoindex:error] [pid 22145:tid 139774283187968] [client 71.69.192.58:45370] AH01276: Cannot serve directory /var/www/vhosts/mydomain/status.mydomain/: No matching DirectoryIndex (at_domains_index.html,index.html,index.cgi,index.pl,index.php,index.xhtml,index.htm,index.shtml,index.cfm) found, and server-generated directory index forbidden by Options directive
[Mon Mar 27 19:16:53.385819 2017] [autoindex:error] [pid 22145:tid 139774241224448] [client 71.69.192.58:45382] AH01276: Cannot serve directory /var/www/vhosts/mydomain/status.mydomain/: No matching DirectoryIndex (at_domains_index.html,index.html,index.cgi,index.pl,index.php,index.xhtml,index.htm,index.shtml,index.cfm) found, and server-generated directory index forbidden by Options directive

That's my error_log

**Comment by nixmomo** [comment]
`<Directory "/var/www/vhosts/dl-host.info/status.dl-host.info/Cachet/public">
	Require all granted
	# Used by Apache 2.4
	Options Indexes FollowSymLinks
	AllowOverride All
	Order allow,deny
	Allow from all
</Directory>`
Add this to your Webserver Settings in your hosting account...
Is mod_rewrite active? Do you have the htaccess file with this content
`<IfModule mod_rewrite.c>
    <IfModule mod_negotiation.c>
        Options -MultiViews
    </IfModule>

    RewriteEngine On
RewriteCond %{SERVER_PORT} !^443$   #optional for SSL website
RewriteRule (.*) https://%{HTTP_HOST}/$1  [R=301,L]  #optional for SSL website
    # Redirect Trailing Slashes If Not A Folder...
    RewriteCond %{REQUEST_FILENAME} !-d
    RewriteRule ^(.*)/$ /$1 [L,R=301]

    # Handle Front Controller...
    RewriteCond %{REQUEST_FILENAME} !-d
    RewriteCond %{REQUEST_FILENAME} !-f
    RewriteRule ^ index.php [L]

    # Handle Authorization Header
    RewriteCond %{HTTP:Authorization} .
    RewriteRule .* - [E=HTTP_AUTHORIZATION:%{HTTP:Authorization}]
</IfModule>`

jbrooksuk pointed you to the right direction... look into the docu dude
https://docs.cachethq.io/docs/installing-cachet#section-running-cachet-on-apache

**Comment by EH-Nathan** [comment]
https://puu.sh/v0otp/7e766ffd76.png

Verified the Vhost, I do have to .htaccess and i have looked extensively into the installation doc with no luck.

**Comment by nixmomo** [comment]
Pls check my post again.. githubs markdown makes my post crazy... is your domain really ***.info? or did you blind copy & paste my code? you have to edit the Folder path and please check the root directory. It must be the public folder from cachet.. something like /var/www/vhosts/your-domain/sub.your-domain/Cachet/public/

**Comment by EH-Nathan** [comment]
I hid my domain in the screenshot. Some website require you to. So i usually just do it anyway

**Comment by nixmomo** [comment]
ok, do you have checked the document root in Plesk Hosting Settings for your subdomain?

**Comment by EH-Nathan** [comment]
Document root is /var/www/vhosts/mywebspace/mysubdomain

**Comment by nixmomo** [comment]
Change it to 
    /var/www/vhosts/mywebspace/mysubdomain/Cachet/public/

**Comment by EH-Nathan** [comment]
Document Root is /var/www/vhosts/mywebspace/mysubdomain/Cachet/public/ and i updated it in the VHost Config. 

Still this install page.

![ss 2017-03-27 at 03 49 50](https://cloud.githubusercontent.com/assets/26636030/24375086/155e2dd6-1305-11e7-99de-5105f76b0cd8.png)

**Comment by nixmomo** [comment]
do you use chrome or firefox? open the dev tools and take a look into the console from dev tools... what is he missing? css files?
Do you checked the chmods?

**Comment by EH-Nathan** [comment]
I have storage chmod to 777

This is the Devlog on chrome 

dashboard-654ce9264c.css Failed to load resource: the server responded with a status of 404 (Not Found)
all-74bb70763d.js Failed to load resource: the server responded with a status of 404 (Not Found)
setup:1 This page includes a password or credit card input in a non-secure context. A warning has been added to the URL bar. For more information, see https://goo.gl/zmWq3m.
dashboard-654ce9264c.css Failed to load resource: the server responded with a status of 404 (Not Found)

**Comment by nixmomo** [comment]
Plesk never run with chmod 777 ... use 755 for folders and 644 for files and disable mod_pagespeed... I'm not sure if that isn't your problem

**Comment by EH-Nathan** [comment]
I tried 755 and disabling mod_pagespeed. Same issue. Not sure what to do at this point.

**Comment by nixmomo** [comment]
Fileowner is your Plesk Webuser and Group psacln? Files have chmod 644? htaccess has really that content i posted earlier?

**Comment by EH-Nathan** [comment]
ls -l output 

![ss 2017-03-27 at 04 24 02](https://cloud.githubusercontent.com/assets/26636030/24376426/d4d840c6-1309-11e7-81d5-1380b9c865dd.png)

**Comment by nixmomo** [comment]
can you post a ls -l from /Cachet/public/build/dist/css and js folder?

**Comment by EH-Nathan** [comment]
![ss 2017-03-27 at 04 31 23](https://cloud.githubusercontent.com/assets/26636030/24376717/e7479850-130a-11e7-9a04-a234ae0fd574.png)
![ss 2017-03-27 at 04 31 42](https://cloud.githubusercontent.com/assets/26636030/24376722/eda98848-130a-11e7-8072-8375b7ef28b5.png)

**Comment by nixmomo** [comment]
ok, can you now post the content from /Cachet/public/.htaccess ?

**Comment by EH-Nathan** [comment]
<IfModule mod_rewrite.c>
    <IfModule mod_negotiation.c>
        Options -MultiViews
    </IfModule>

    RewriteEngine On

    # Redirect Trailing Slashes If Not A Folder...
    RewriteCond %{REQUEST_FILENAME} !-d
    RewriteRule ^(.*)/$ /$1 [L,R=301]

    # Handle Front Controller...
    RewriteCond %{REQUEST_FILENAME} !-d
    RewriteCond %{REQUEST_FILENAME} !-f
    RewriteRule ^ index.php [L]

    # Handle Authorization Header
    RewriteCond %{HTTP:Authorization} .
    RewriteRule .* - [E=HTTP_AUTHORIZATION:%{HTTP:Authorization}]

</IfModule>

**Comment by EH-Nathan** [comment]
![ss 2017-03-27 at 04 34 30](https://cloud.githubusercontent.com/assets/26636030/24376822/4522fed8-130b-11e7-82f2-2cb897f84182.png)

**Comment by EH-Nathan** [comment]
Found then issue, When i inspect element and change the style sheet from /build/dist/css/dashboard-654ce9264c.css to /public/build/dist/css/dashboard-654ce9264c.css to works. How would i permanently change that?

**Comment by nixmomo** [comment]
hmm crazy... are you sure that your root directory is /var/www/vhosts/yourdomain/yoursbdomain/Cachet/public/ ?
Cause in that folder is the build directory but in /Cachet/public isn't a second public directory so it looks that your doc root isn't set correctly.

Check it again and restart your webserver to make sure the changes are active

**Comment by EH-Nathan** [comment]
You are a legend it works now. I had the root pointing to just /Cachet. My bad. Thanks for your help!

**Comment by nixmomo** [comment]
Great, Thanks a lot and you're always welcome.
So have fun with Cachet on Plesk :-)
Please don't forget to mark the issue as solved.
