### ISSUE TITLE
Accent in author field makes RSS feed invalid

### ISSUE THREAD

**Issue by oxlay** [CachetHQ/Cachet#2466]
Could you please update the roumen/feed library to include the fix? It was merged two days ago : https://github.com/RoumenDamianoff/laravel-feed/pull/64

Thanks !

**Comment by jbrooksuk** [comment]
Sure can!

**Comment by jbrooksuk** [comment]
@RoumenDamianoff can you tag a new release, please?

**Comment by RoumenDamianoff** [comment]
@jbrooksuk [v2.10.5](https://github.com/RoumenDamianoff/laravel-feed/releases/tag/v2.10.5) is released today.

**Comment by jbrooksuk** [comment]
Thanks!

**Comment by oxlay** [comment]
Great, thank you!
