### ISSUE TITLE
Allow custom http headers

### ISSUE THREAD

**Issue by DanielRuf** [CachetHQ/Cachet#2469]
In some cases it is helpful to add security headers (see https://securityheaders.io) to the requets in the frontend using some setting in the backend.

**Comment by GrahamCampbell** [comment]
This is something you should configure your webserver to add.

**Comment by DanielRuf** [comment]
@GrahamCampbell I can not in this case as I am on a managed webhosting package and use PHP7 FPM and can not use the .htaccess file ;-)

**Comment by GrahamCampbell** [comment]
Please contact your webhost, or feel free to implement your own middleware and use that.

**Comment by DanielRuf** [comment]
@GrahamCampbell So I should add / change files in Cachet to solve this?

Unfortunately I am still stuck to this setup for a few more weeks until I move to a new server with the same hosting provider where I have PHP 7 as module by default (and can use .htaccess again to set the headers myself).
