### ISSUE TITLE
CORS not working

### ISSUE THREAD

**Issue by markus2000** [CachetHQ/Cachet#2470]
Running 2.3.10. I have set the "Allowed domains" on the Security settings page to "http://test-cors.org,http://www.test-cors.org" which results in them being present in bootstrap/cache/config.php.

But when I test the CORS functionality (for example using the mentioned website to send a preflight CORS request), the `Access-Control-Allow-Origin` header is always missing.

**Comment by markus2000** [comment]
More details:
The issue is that the response to a preflight request is _always_ missing the `Access-Control-Allow-Origin` and `Access-Control-Request-Headers` headers.

There are quite some issues around that topic in the [laravel-cors project](https://github.com/barryvdh/laravel-cors) — some of which point to modifying the `app/Http/Kernel.php` by adding `'Barryvdh\Cors\HandleCors::class'` to $middleware.

When I do that, suddenly the `Access-Control-Allow-Origin`header is set correctly, but the `Access-Control-Allow-Headers` is still missing.

**Comment by jbrooksuk** [comment]
Hmm, this looks like one for @GrahamCampbell. Is this something that we might want to set in the server config, instead of Cachet?
