### ISSUE TITLE
Unable to load Cachet through browser

### ISSUE THREAD

**Issue by savaikar** [CachetHQ/Cachet#2471]
I am setting up the Cachet for the first time and unable to load it through the browser. I can, however, load it through elinks via the command prompt.

Attached is the zip file of the logs. I managed to resolve most of them except this. I can assure that httpd is working fine.

Can somebody help?

**Comment by savaikar** [comment]
@ranjantomtom

**Comment by savaikar** [comment]
[laravel-2017-03-28.zip](https://github.com/CachetHQ/Cachet/files/874569/laravel-2017-03-28.zip)

**Comment by savaikar** [comment]
Attached the zip file of the entire logs.

**Comment by savaikar** [comment]
Hello @jbrooksuk ,

I have managed to get the Cachet started via the web browser and the subscription is enabled. However, most of the times, there is an error while adding any subscriber to the list.

If the logs are required, I will add them on Monday.

Thanks & Regards,
Rahul

**Comment by jbrooksuk** [comment]
Okay. Please open a new issue :)
