### ISSUE TITLE
Averaging metric data points

### ISSUE THREAD

**Issue by tcrall** [CachetHQ/Cachet#2472]
The average calculated for metric data points seems to only include actual points recorded via the api endpoint, and not 'default' values.  So the graph shows my uptime as 100% all day except for 1 minute, but because I'm only sending metric values when the state changes from good to bad or from bad to good, the hourly and daily averages show exactly 0.5.  

I'd like to avoid having to hit the api every minute, or ten minutes, or whatever when nothing has changed, if possible.  Is there a way to:

1) include 'default' data points in the averages 
 
and

2) have the default set to whatever the last recorded data point was, instead of a constant value, so then when it's 0 it stays 0 until it goes up again, and then stays at 100 until it crashes?

also, 

3) is there a way to get monthly and yearly averages?

Thanks!

![screen shot 2017-03-30 at 10 00 39 am](https://cloud.githubusercontent.com/assets/11201787/24537480/fb43c4d8-15a7-11e7-8105-393159bd0e4d.png)

![screen shot 2017-03-30 at 10 00 56 am](https://cloud.githubusercontent.com/assets/11201787/24537462/e16fa536-15a7-11e7-98ee-c299f214a649.png)

**Comment by sirkkalap** [comment]
Hi @tcrall ,

Just a note about uptime.

I have seen uptime represented as number of days since last restart. For example here is how uptime is reported in FreeNAS server:

<img width="556" alt="screenshot 2017-04-21 20 02 20" src="https://cloud.githubusercontent.com/assets/703699/25288267/741f47e8-26cd-11e7-8bd0-b13c3b605824.png">

**Comment by jbrooksuk** [comment]
We really need to look at metrics again at some point.

**Comment by ch-tm** [comment]
+1 for this bug

**Comment by jbrooksuk** [comment]
This should be fixed.
