### ISSUE TITLE
Error 500 Internal Server Error

### ISSUE THREAD

**Issue by time4e** [CachetHQ/Cachet#2474]
here are the logs:

Error 500
Houston, We Have A Problem.
Internal Server Error
What does this mean?

Something went wrong on our servers while we were processing your request. An error has occurred and this resource cannot be displayed. This occurrence has been logged, and a highly trained team of monkeys has been dispatched to deal with your problem. We're really sorry about this, and will work hard to get this resolved as soon as possible.

This error can be identified by 488b329c-8611-456d-9661-6623f4c83e8a. You might want to take a note of this code. 

There is nothing in the error logs when this occurs. Please assist.

**Comment by time4e** [comment]
I this per docs but no dice 
If you get a 500 error when visiting your status page, you may need to run chmod -R 777 storage for it to work or rm -rf bootstrap/cache/*

You can also try to give permissions to cache chmod -R 777 bootstrap/
 did nto work

**Comment by jbrooksuk** [comment]
Can you supply us with the actual log file from `./storage/logs` please?

**Comment by ranjantomtom** [comment]
I have same problem with my instance. Working cachet stopped working when I am trying to setup mail configuration.
I followed and perform below steps 
 rm -rf  bootstrap/cache/*
Run php artisan config:cache

But now luck. please find attached the latest laravel-2017-04-18.log
[500 error.txt](https://github.com/CachetHQ/Cachet/files/927867/500.error.txt)

**Comment by GrahamCampbell** [comment]
You chose the apc driver, but don't have the apc extension installed.

**Comment by ranjantomtom** [comment]
How do we install apc on cantos and restart php?

**Comment by GrahamCampbell** [comment]
D'no. Ask Google I guess. :P

**Comment by ranjantomtom** [comment]
But it is working earlier, just after mail configuration its broken.

**Comment by jbrooksuk** [comment]
@ranjantomtom must've configured something incorrectly then. Check that APCU is installed.

If you're still struggling, we offer an installation service.
