### ISSUE TITLE
Posting incident with curl end in #500

### ISSUE THREAD

**Issue by SpecialZwerg** [CachetHQ/Cachet#2477]
Hi,

i used the following command to post an incident:
curl -H "Content-Type: application/json;" -H "X-Cachet-Token: some_token" -d '{"name":"test","message":"test","status":1,"visible":1}' localhost/api/v1/incidents
results in:
{"errors":[{"id":"1b43a3ea-ae6d-4e3e-acd4-9cd3a86a4ef4","status":500,"title":"Internal Server Error","detail":"An error has occurred and this resource cannot be displayed."}]}

I have tried it the same way with anything else you can post (metrics, components, ...) and it worked with that same syntax. I honestly have no clue why incidents won't do it for me. Any idea?

Kind regards
Andrew

(Some lines from the log:
production.ERROR: exception 'InvalidArgumentException' with message 'The separation symbol could not be found
Unexpected data found.
Unexpected data found.
Unexpected data found.
Trailing data' in /var/www/Cachet/vendor/nesbot/carbon/src/Carbon/Carbon.php:425)

**Comment by jbrooksuk** [comment]
You haven't sent any dates through. Dates are a required field.

**Comment by jbrooksuk** [comment]
Ignore my last response, I think I'm wrong.

**Comment by jbrooksuk** [comment]
I assume you're not using v2.4 here?

https://cloudup.com/cwONcf4k5Qm

I'm able to send the same data through and get an incident created.
