### ISSUE TITLE
(Idea/Feedback) Changing the way 'Previous days' work (History)

### ISSUE THREAD

**Issue by Naspyy** [CachetHQ/Cachet#2482]
When clicking 'Previous days' you should get a list of previous outages and not just day by day (so if you search for an - for example - outage a month ago, depending on your settings it could be that you have to click the 'Previous days'-Button 30 times) like the [history of status.io](https://www.cloudflarestatus.com/history).

**Comment by jbrooksuk** [comment]
This is something we're changing in [v2.4](https://github.com/CachetHQ/Cachet/pull/2325). You'll see a complete history with a breakdown for the month/year.
