### ISSUE TITLE
New 2.3.x release?

### ISSUE THREAD

**Issue by GuidoHendriks** [CachetHQ/Cachet#2483]
I'm experiencing some issues with API on 2.3.x. I noticed this is already fixed in the latest commits:
https://github.com/CachetHQ/Cachet/commits/2.3

Will there be any more 2.3.x releases or will there be a 2.4 release soon?

**Comment by jbrooksuk** [comment]
@GuidoHendriks I'll get a new release made tonight :)

**Comment by jbrooksuk** [comment]
v2.3.11 is released https://github.com/CachetHQ/Cachet/releases/tag/v2.3.11
