### ISSUE TITLE
Delete button throws mixed content warning

### ISSUE THREAD

**Issue by felixoi** [CachetHQ/Cachet#2484]
Hello,

I set up Cachet with a reserved NGINX Proxy which uses ssl. If I am logged in I get a mixed content warning. I think it's a bug with cachet because the configured Site URL starts with `https` and nginx passes `X-Forwarded-Proto`. The "delete" Button causes this warning.

This is the chrome warning:
```
Mixed Content: The page at 'https://status.secret.net/' was loaded over a secure connection, but contains a form which targets an insecure endpoint 'http://status.secret.net/dashboard/incidents/1/delete'. This endpoint should be made available over a secure connection.
```
Correct me if I made a mistake.

Thanks,
felixoi

**Comment by jbrooksuk** [comment]
Might need further investigation in the JS here.

**Comment by jbrooksuk** [comment]
Oh, I think you need to add your Nginx server IP to `./config/trustedproxy.php`.
