### ISSUE TITLE
Component visibility

### ISSUE THREAD

**Issue by ju5t** [CachetHQ/Cachet#2488]
Would it be possible to disable the visibility of a component and only display the high level status of the component group? 

For example: we have a dozen webservers where each webserver is in a component group. If 1 or more webservers are offline that would be classed as a partial outage on a component group level. We're still able to deliver but we know there might be a loss in performance somewhere. We don't want to drill down in much detail to the end user though. Often they don't care either.

**Comment by jbrooksuk** [comment]
@ju5t this gets into a very bespoke setup, but it's something we should offer... What does everyone think?

**Comment by jbrooksuk** [comment]
Thank you for your input on Cachet 2.x. We are shifting our attention and resources to Cachet 3.x and will no longer be supporting the 2.x version. If your feedback or issue is relevant to the 3.x series, we encourage you to engage with the new branch.

For more information on the Cachet rebuild and our plans for 3.x, you can read the announcement [here](https://github.com/CachetHQ/Cachet/discussions/4342).

We appreciate your understanding and look forward to your contributions to the new version.
