### ISSUE TITLE
Updating component status through API results unknown component status

### ISSUE THREAD

**Issue by cleberwarmling** [CachetHQ/Cachet#2489]
Updating component status through API results unknown component status. 

 Cachet Version.: 2.3.11 running with Docker.

How to reproduce/example below.:

```
curl -H "Content-Type: application/json" -H "X-Cachet-Token: xxxxxxxxxxxxxxxxxxxx" http://xx.xxx.xxx.xx/api/v1/components/1 -X PUT -d'{“status":1}'
{"data":{"id":1,"name":"NFSE","description":"","link":"","status":0,"order":0,"group_id":2,"created_at":"2017-04-13 16:24:40","updated_at":"2017-04-13 17:45:25","deleted_at":null,"enabled":true,"status_name":"cachet.components.status.0","tags":{"":""}}}%
```

Someone has any idea of what is happening?

**Comment by jbrooksuk** [comment]
@cleberwarmling did you manage to find the issue?

**Comment by cleberwarmling** [comment]
@jbrooksuk yeah, I think it was just indentation or something like that. I only made the curl call in separated lines and it worked great.

**Comment by jbrooksuk** [comment]
:)

**Comment by kungpaolam** [comment]
I'm seeing a similar issue while trying to use the API to change a component status on my cachet instance, and i see the same behavior on the cachet demo (https://demo.cachethq.io). I tried the syntax generated by https://docs.cachethq.io/reference#update-a-component:
$ curl --request PUT \
  --url https://demo.cachethq.io/api/v1/components/3 \
  --data '{"name":"Website","status":3,"link":"https://cachethq.io","group_id":1,"enabled":"true"}' -H "X-Cachet-Token: xxxxxxxxxxxxxxxxxxxx"

and i've tried something simpler:
$ curl --request PUT --url https://demo.cachethq.io/api/v1/components/3 --data '{"status":3}' -H "X-Cachet-Token: xxxxxxxxxxxxxxxxxxxx"

in both cases, the status of the component is always set to "0", and the status_name changed to "cachet.components.status.0" no matter which value i set the status to (1-4).

the output from the command is:
{"data":{"id":3,"name":"Website","description":"","link":"https:\/\/cachethq.io","status":0,"order":0,"group_id":1,"created_at":"2017-09-17 23:30:02","updated_at":"2017-09-18 00:02:20","deleted_at":null,"enabled":true,"status_name":"cachet.components.status.0","tags":{"webasd":"webasd"}}}

**Comment by kungpaolam** [comment]
just for fun, i tried the same thing using python and got the same results

`#!/usr/bin/python
import requests

url = "https://demo.cachethq.io/api/v1/components/3"

payload = "{\"name\":\"Website\",\"status\":3,\"link\":\"https://cachethq.io\",\"group_id\":1,\"enabled\":\"true\"}"
headers = {'X-Cachet-Token': 'xxxxxxxxxxxxxxxxxxxxx'}

response = requests.request("PUT", url, headers=headers, data=payload)

print(response.text)
`
the output was the same:
{"data":{"id":3,"name":"Website","description":"","link":"https:\/\/cachethq.io","status":0,"order":0,"group_id":1,"created_at":"2017-09-17 23:30:02","updated_at":"2017-09-18 00:26:51","deleted_at":null,"enabled":true,"status_name":"cachet.components.status.0","tags":{"webasd":"webasd"}}}
