### ISSUE TITLE
Sending mail from localhost

### ISSUE THREAD

**Issue by 2Belette** [CachetHQ/Cachet#2490]
Hi, 

Anyone using the same host where Cachet is installed to send email without using external SMTP server?
What would be the best configuration for that and what would be the corresponding .env?
I made some tries but I haven't been able to make it work for now :(
Many thanks :)

**Comment by johnny-bit** [comment]
Try `driver=sendmail`

**Comment by 2Belette** [comment]
Thanks! I tried but nothing..
I have confirmed that sendmail works correctly on my server and I have sent a test mail no issue here..

is there any issue to leave null on some parameters ?
here are my parameters:

```
MAIL_DRIVER=sendmail
MAIL_HOST=localhost
MAIL_PORT=25
MAIL_USERNAME=null
MAIL_PASSWORD=null
MAIL_ADDRESS=my@address.fr
MAIL_NAME="mail cachet"
MAIL_ENCRYPTION=null
```

any log fil I can't take a look on Cachet to get more information?
many thanks

**Comment by jbrooksuk** [comment]
That should be all you need... Try running `rm -rf bootstrap/cache{,t}/*`

**Comment by 2Belette** [comment]
thanks I did that but where the log should go to ? (syslog/journalctl/file?)

**Comment by jbrooksuk** [comment]
`./storage/logs/`.

**Comment by 2Belette** [comment]
Thanks I can see the logs but nothing inside the logs to help me debug 
the mail notification..

**Comment by hiteshmahajan** [comment]
it works :+1: 

```
MAIL_DRIVER=sendmail
MAIL_HOST=localhost
MAIL_PORT=25
MAIL_USERNAME=null
MAIL_PASSWORD=null
MAIL_ADDRESS=my@address.fr
MAIL_NAME="mail cachet"
MAIL_ENCRYPTION=null
```
