### ISSUE TITLE
How to install Cachethq on synology

### ISSUE THREAD

**Issue by emillod** [CachetHQ/Cachet#2491]
Hello i have NAS from Synology. I can install packages like node, perl and etc. I want to install cachethq on vhost.

**Comment by Smashmint** [comment]
The easiest way to do this is to install the Docker package on your synology and follow the documentation for installing Cachet with Docker https://docs.cachethq.io/docs/get-started-with-docker

**Comment by emillod** [comment]
Hah, i know 😄 
But my synology doesn't support Docker 😢 
I can install PHP, Apache, NodeJS and etc, maybe with this i can do something? Because I really need this :)

**Comment by jbrooksuk** [comment]
I don't know about Synology, but can you not install this [package](https://www.synology.com/en-us/dsm/app_packages/Docker) to get Docker?

**Comment by emillod** [comment]
And below description of this package, you can check supported models. My Synology is DS215j .

**Comment by jbrooksuk** [comment]
I take it you're not supported then?

**Comment by emillod** [comment]
Yes, that's why I'm asking here for alternative solution ;)

**Comment by jbrooksuk** [comment]
I don't know then, sorry! If your NAS doesn't support it, I don't know what else to suggest I'm afraid.
