### ISSUE TITLE
Error 500 After Fresh Install

### ISSUE THREAD

**Issue by Sade66** [CachetHQ/Cachet#2492]
Hello,
I have done a fresh install (with a new Ubuntu workspace) twice, resulting in the same error. I go through the setup and attempt to go to the dashboard, homepage, etc. and I get this error...

![image](https://cloud.githubusercontent.com/assets/19366945/25075474/86ed0510-22e3-11e7-9473-eebbbe65a1ec.png)

[Here is my Laravel log also.](https://gist.github.com/Sade66/4612ea1402e645ca78551a63e9e3341d)

Any help is appreciated!

**Comment by GrahamCampbell** [comment]
ext-apc needs installing, since you chose it

**Comment by Sade66** [comment]
@GrahamCampbell Is [this](https://www.digitalocean.com/community/tutorials/how-to-install-alternative-php-cache-apc-on-a-cloud-server-running-ubuntu-12-04) what you are talking about?

**Comment by GrahamCampbell** [comment]
No. `apt-get install php-apc`.

**Comment by Sade66** [comment]
It works! Thank you for your help! :)
