### ISSUE TITLE
Install on shared hosting environment

### ISSUE THREAD

**Issue by amjad** [CachetHQ/Cachet#2493]
I'm trying to install cachet on a shared hosting server. Is this possible? Any tutorial out there? Thanks.

**Comment by jbrooksuk** [comment]
Cachet does not support shared-hosting. We advise that you setup a [Digitalocean](https://www.digitalocean.com/?refcode=8c9b5cbcff1a) server for $5 :)

**Comment by amjad** [comment]
Thanks. Is there documentation for this?

**Comment by Smashmint** [comment]
@amjad You can find installation docs here: https://docs.cachethq.io/docs/installing-cachet
