### ISSUE TITLE
Y-axis labels broke after a month in production

### ISSUE THREAD

**Issue by sirkkalap** [CachetHQ/Cachet#2494]
Hi,

For some reason all the y-axis labels changed to be even whole numbers in https://status.digitraffic.fi .

Here is a sample what we see:

<img width="974" alt="screenshot 2017-04-20 11 24 26" src="https://cloud.githubusercontent.com/assets/703699/25221046/68e693fc-25bc-11e7-823b-5f45f95935d9.png">

We are running Cachet 2.3.9 with Docker under AWS AMI Linux.

Have you seen any issues with graph labeling?

Copying the database to another instance did not reproduce the issue.

Rebuilding Docker containers with docker-compose did fix the issue.

**Comment by jbrooksuk** [comment]
Thanks for reporting this. @GrahamCampbell has a few ideas on how to fix metrics.

**Comment by sirkkalap** [comment]
Hi @GrahamCampbell ,

Do you think I could do some diagnostics to enlighten this issue?
