### ISSUE TITLE
Create the incident before sending mails to the subscribers ?

### ISSUE THREAD

**Issue by BlackYoup** [CachetHQ/Cachet#2495]
Hi,

Apologies if the incident is created before the mails are sent, that means my problem lies elsewhere.

I'm using cachet and noticed that the incident takes a long time to create. I think that the mails are first sent and then the incident is created.
We use Mailgun as our mail provider and the mails are slow to be sent, which delays the incident creation.
Also, it already happened that mailgun returned an error at some points in the mails processing and the incident wasn't created (that was a problem from our mailgun configuration).

Is there any way to delay the mails after the incident has been created ? Or to push them to a queue that will consume messages instead of sending them asynchronously ?

Again, sorry if my assumptions are wrong :-)

**Comment by jbrooksuk** [comment]
> I'm using cachet and noticed that the incident takes a long time to create. I think that the mails are first sent and then the incident is created.

What database driver are you using? MySQL, Postgres or SQLite?

We create incidents under a transaction so that if something fails, we won't leave data half lying around.

But we do send emails _after_ the incident is created. We have to, otherwise there is nothing to send technically.

**Comment by jbrooksuk** [comment]
Also, what version of Cachet are you using?

**Comment by BlackYoup** [comment]
Okay, that makes sense.

I'm using the postgresql driver and Cachet v2.3.10

**Comment by jbrooksuk** [comment]
Hmm, this seems to be fine in 2.4 though. Can you maybe run a demo instance and try it?

**Comment by BlackYoup** [comment]
I'll try but not sure I'll have the time to do it. I think we'll see that when 2.4 gets released :D

**Comment by BlackYoup** [comment]
Hi,

I had the time to test this out. I have 2 users subscribed on the mailing list and I'm using cachet at commit 25581cd7

Creating the incident with notifying subscribers: 6.2s
Creating the incdient without notifying subscribers: 200ms

I'm using SMTP with mailgun. So this is a 3s delay per user. During this time, the incident isn't displayed on the status page.

On our "production" cachet, we have far more users, and sometimes, incidents are resolved on our end before it has been created and users notified. One time, it even took 12 minutes to create the incident.

So I'm not sure what would be the solution here. Maybe have a queue of mails to send and send them separately ? Notifying users is great, but not being able to display the incident while sending mails can be misleading.

I would be glad to help you on that matter, if you need :-)

**Comment by ConnorVG** [comment]
What queue driver are you using @BlackYoup?

**Comment by BlackYoup** [comment]
@ConnorVG I wasn't aware that there was a queue system until your message. So I checked up and I guess I'm using the sync queue, since I didn't configured it.

So, would using supervisor help here ?

**Comment by ConnorVG** [comment]
Take a look at [the documentation](https://laravel.com/docs/5.3/queues).

**Comment by BlackYoup** [comment]
Hi,

I think I managed to not use the sync driver but I'm still not really sure if it works yet.

Could you add in the cachet documentation what values you have to set to either use the `database` or `supervisor` queues ? I had to look through the code and laravel documentation to find that. Once again, I can do a PR if you want :-)
