### ISSUE TITLE
Can't find Database on "php artisan app:install"

### ISSUE THREAD

**Issue by COOLGAMETUBE** [CachetHQ/Cachet#2497]
I've been following the Documentation (v. 2.4) and im not able to run "php artisan app:install" without following error:

`mysqldump: Got error: 1049: Unknown database 'cachet' when selecting the database`
...
...
...
` [Illuminate\Database\QueryException]
  SQLSTATE[42000] [1049] Unknown database 'cachet' (SQL: select * from inform
  ation_schema.tables where table_schema = cachet and table_name = migrations
  )
`
`[Doctrine\DBAL\Driver\PDOException]
  SQLSTATE[42000] [1049] Unknown database 'cachet'
`
`[PDOException]
  SQLSTATE[42000] [1049] Unknown database 'cachet'
` 

Im running Debian 8 Minimal.

**Comment by COOLGAMETUBE** [comment]
Ah. Documentation does miss, that i have to create one first.

**Comment by jbrooksuk** [comment]
> Ah. Documentation does miss, that i have to create one first.

You can provide suggested edits on the docs too :)
