### ISSUE TITLE
Team Member Permission Issue

### ISSUE THREAD

**Issue by gonzoinc** [CachetHQ/Cachet#2499]
When team members are added, those with the user role shouldn't really have write permissions to a lot of the dashboard settings, that should be reserved for admin roles only. 

Should also have the ability to assign a user to a component or group, Only those with component or group access have write, everyone else has read.

Admin should be the only ones to have access to settings & subscribers, both read/write.

Currently there are two roles "User/Admin" but I'm not seeing a difference in what each role does.

**Comment by jbrooksuk** [comment]
This is something we definitely need to improve in Cachet. Permissions don't really make sense at the moment.

**Comment by dschwabeS11** [comment]
Just checking. Is this going somewhere in 2.4/3.0?

**Comment by jbrooksuk** [comment]
Definitely will be, yes. We need to revamp a lot of things in what will become 3.0

**Comment by miquelbarbero** [comment]
Good morning,

we are in the same situation as @gonzoinc 

Would you have any date estimation about when we could enjoy those new features?

Thanks and kind regards

**Comment by cwross** [comment]
Thank you for this great software. I just wanted to add a request to this - if possible, please allow users to be "read only" as an option. My use case is for a private network and all users need to be logged into view anything on Cachet. However, the only way to do that right now is to give everyone edit/write permissions. Thank you!

**Comment by DuhBatista** [comment]
Dear colleagues

good morning,


I was analyzing this topic, referring to user permission without being an administrator. Would you have any possibility to edit the permission or remove the permission so that the average user cannot access the DashBoard?
Thanks for listening

**Comment by jbrooksuk** [comment]
Thank you for your input on Cachet 2.x. We are shifting our attention and resources to Cachet 3.x and will no longer be supporting the 2.x version. If your feedback or issue is relevant to the 3.x series, we encourage you to engage with the new branch.

For more information on the Cachet rebuild and our plans for 3.x, you can read the announcement [here](https://github.com/CachetHQ/Cachet/discussions/4342).

We appreciate your understanding and look forward to your contributions to the new version.
