### ISSUE TITLE
API New Component Error

### ISSUE THREAD

**Issue by gonzoinc** [CachetHQ/Cachet#2500]
Hey All,

> curl  -H "X-Cachet-Token:9yMHsdioQosnyVK4iCVR" --request POST \
>   --url https://demo.cachethq.io/api/v1/components \
>   --data '{"name":"test","description":"This is a test","status":1,"order":-4,"group_id":1,"enabled":"true"}'
> 
> {"errors":[{"id":"6f8a8cda-3220-41a8-9842-9c330a598dfd","status":400,"title":"Bad Request","detail":"The request cannot be fulfilled due to bad syntax.","meta":{"details":["The name format is invalid."]}}]}

The above is generated right from your documentation site -> https://docs.cachethq.io/v1.0/reference#components

Originally tried this on my install and it was failing so tried it on the demo to confirm the problem.  not sure if this is a docuemtnation issue or a bug.

Thx,

**Comment by gonzoinc** [comment]
Looks like the issue is your documentation is missing the content type for the header:

> curl  -H "Content-Type: application/json;" -H "X-Cachet-Token:9yMHsdioQosnyVK4iCVR" --request POST \
>   --url https://demo.cachethq.io/api/v1/components \
>   --data '{"name":"test","description":"This is a test","status":1,"order":-4,"group_id":1,"enabled":"true"}'

**Comment by jbrooksuk** [comment]
This is more of a documentation issue I believe.
