### ISSUE TITLE
Error 500 on metrics

### ISSUE THREAD

**Issue by Odko** [CachetHQ/Cachet#2501]
I created database tables with chq_ prefix. But when i try to get metrics server return _Internal Server Error 500_.
As i seen in pgsql log and laravel log the app trying to access metric_points(without chq_ prefix).

**SQL log:** 

> ERROR:  relation "metric_points" does not exist at character 90      
> STATEMENT:  select sum(metric_points.value * metric_points.counter) as value FROM chq_metrics m  JOIN metric_points ON metric_points.metric_id = m.id WHERE metric_points.metric_id = $1 AND to_char(metric_points.created_at, 'YYYYMMDDHH24') = $2 GROUP BY to_char(metric_points.created_at, 'H')

**Laravel log:**

> [2017-04-26 11:04:09] development.ERROR: exception 'PDOException' with message 'SQLSTATE[42P01]: Undefined table: 7 ERROR:  relation "metric_points" does not exist
> LINE 1: ..._points.counter) as value FROM chq_metrics m JOIN metric_poi...
>                                                              ^' in /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Connection.php:335
> Stack trace:
> #0 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Connection.php(335): PDOStatement->execute(Array)

**Cachet version: 2.5.0-dev**
**Installed with docker-compose**

**Comment by GrahamCampbell** [comment]
> Cachet version: 2.5.0-dev

Please install the latest 2.3.x version. That one will work.
