### ISSUE TITLE
php 7 support?

### ISSUE THREAD

**Issue by athonyhendrix** [CachetHQ/Cachet#2503]
Hi,
I am new to php and github in general so this could be the wrong place to post this question, if so please let me know how/where I should post it.  I'm curious if Cachet is supported by php7 if so do you have guidance for how I would deploy in a php7 environment.  From what I could tell the compose file is fairly tied to php5*

Our organisation is considering a status page solution and so far we like what we see however the runtime is older than the ubuntu images I have access to within our organisation.

Thanks.

**Comment by GrahamCampbell** [comment]
yes
