### ISSUE TITLE
Manage Subscription is either all or nothing

### ISSUE THREAD

**Issue by gerardgoubert** [CachetHQ/Cachet#2504]
(running v2.3, waiting for 2.4! -- our configs have been submitted under issue #2485, as well as other issues) 
We have many components, and when you first subscribe you get subscribed to all components. ok good.
You then goto manage your subscription and uncheck several components. ok good.
Now go look at that user in the subscribers list and they are still subscribed to ALL components even the ones they just unchecked (!!!) Not good.
So ideally people (subscribers) would like to select which components that they actually get alerts for, but that does not work -- either you get everything or nothing.
Bug: 1)actually update the component subscriptions when the user edits their subscriptions preferences, and show the changes in the subscriber list.
Feature enhancement: Also there is no way for an admin to add/change/remove a subscriber from a component, or even a way to require admin approval to subscribe to a "restricted" component for example.

**Comment by gerardgoubert** [comment]
I would also add, I think there is a basic flaw in the subscription model, anyone knowing someone else's email address could modify someone else's subscriptions without their knowledge. I would think perhaps there should be a verification step of sending an email to the user who's subscriptions have changed, ... a confirmation email, where you have to click on a link (containing a special code or whatever) that would then make the change, this way only people who are able to access the email account can make changes to that subscription. Thoughts?

**Comment by jbrooksuk** [comment]
Thanks for reporting this! We'll look into it :)

**Comment by jbrooksuk** [comment]
Replacing this issue with https://github.com/CachetHQ/Cachet/issues/3102
