### ISSUE TITLE
Enabled Metrics Do Not Show Up

### ISSUE THREAD

**Issue by nprail** [CachetHQ/Cachet#2505]
I created a metric and selected the option to have the metric show up on the status page but it doesn't show up. I'm unable to figure out why. 

Also, it would be great if the metrics feature was documented better. I don't fully understand it. Which is honestly probably why it isn't showing up. Because I probably miss configured it.

**Comment by jbrooksuk** [comment]
@nprail have you checked the "Display graphs on status page?" option in the main settings screen?

> Also, it would be great if the metrics feature was documented better. I don't fully understand it. Which is honestly probably why it isn't showing up. Because I probably miss configured it.

True, we should!

**Comment by nprail** [comment]
Oh, I hadn't seen that setting! The metrics now show up! Thanks! More reason to document it better :)

**Comment by jbrooksuk** [comment]
I can't see why that couldn't be a default setting tbh :)

**Comment by nprail** [comment]
I have a new problem. I'm not sure if I should create a new issue for this or not since it's very related. 

The metrics now show up, but it isn't working quite right. It's just blank. If I look at the JavaScript console, it says that the metric resource returned a 500 error. You can see my status page [here](https://status.filiosoft.com).

**Comment by jbrooksuk** [comment]
Can you open a new issue and supply the latest log file, they can be found in `./storage/logs/`.
