### ISSUE TITLE
Plesk install guide

### ISSUE THREAD

**Issue by agreements** [CachetHQ/Cachet#2506]
Would love a plesk install guide for this.

**Comment by GrahamCampbell** [comment]
As far as I can see, installing on plesk is the same as for any other server?

**Comment by agreements** [comment]
I keep getting error 500 no matter what i do.

**Comment by agreements** [comment]
Fatal error: Call to a member function bind_param() on boolean in /extensions/Auth_phpbb.php on line 507

**Comment by nixmomo** [comment]
It's thje same one a plesk server... Logs?

**Comment by agreements** [comment]
What logs do you want?

**Comment by GrahamCampbell** [comment]
https://github.com/CachetHQ/Cachet/tree/2.4/storage/logs

**Comment by GrahamCampbell** [comment]
That error code is provided so the users of your website can give you it, so you can look it up in the log file.

**Comment by nixmomo** [comment]
Hmm...  cachet error logs, apache / nginx error logs?

**Comment by f0o** [comment]
all logs you find under storage/logs path of your cachet installation. likely a file called laravel.log

**Comment by jbrooksuk** [comment]
The logs can be found where @GrahamCampbell posted above :)
