### ISSUE TITLE
Cachet Showing Issues but Everything is Operational

### ISSUE THREAD

**Issue by apssupport** [CachetHQ/Cachet#2507]
Hi everyone,

Is there a way to reset the message on top that shows "Some systems are experiencing issues" even though all components are set to operational? Please see attached image.
![screen shot 2017-04-30 at 1 45 51 pm](https://cloud.githubusercontent.com/assets/19654323/25566673/ad242b50-2dab-11e7-8f79-42f82952ecf2.png)

**Comment by nixmomo** [comment]
Check your last incidents ... update it to closed ... there is one that isn't resolved

**Comment by apssupport** [comment]
Thank you, went through all the old incidents and set everything to fixed. Issue resolved, thank you!

**Comment by jbrooksuk** [comment]
I'm tempted to remove the condition that checks for any open incidents and only base it on the component status. Thoughts?

**Comment by yuvarajan1989k** [comment]
@jbrooksuk I m looking for a similar solution. how to do ?
