### ISSUE TITLE
No components section appearing in Safari

### ISSUE THREAD

**Issue by AlessioMartorelli** [CachetHQ/Cachet#2510]
Hi! It seems that in Safari the components aren't showing in the page. See attached image
<img width="1029" alt="screen shot 2017-05-01 at 19 41 50" src="https://cloud.githubusercontent.com/assets/9568357/25589940/66c16a32-2ea6-11e7-8709-6211dad21f65.png">

It works ok on Chrome (and I guess other browsers too).
I'm currently running version 2.4 of Cachet.

Thanks

**Comment by jbrooksuk** [comment]
Are your components hidden from non-authenticated users?

**Comment by AlessioMartorelli** [comment]
That was it! Sorry about this, we didn't have to set it as public with the previous version.
Also wasn't expecting the setting to be in the component group, but all good now.

Many thanks @jbrooksuk
