### ISSUE TITLE
Tagging of releases and version number format

### ISSUE THREAD

**Issue by marcomusso** [CachetHQ/Cachet#2511]
First of all I don't know if there is a "defacto standard" in naming releases with tags or release branches but I noticed that the version number (ie `2.3.11`, included in the `VERSION` file) is not supposed to include anything else if we want to leverage some functions that parse version numbers (example: [puppet's versioncmp](https://docs.puppet.com/puppet/latest/function.html#versioncmp)).

So I am suggesting (and I'd like to hear you point of view) to drop the `v` from the tagging of release numbers... that clashes somewhat with the branching too (thinking about the `2.4` branch right now vs the future `v2.4` tag).

Of course this is more of a workflow problem that a code one...

**Comment by marcomusso** [comment]
Adding some other opinions:

http://stackoverflow.com/questions/21639437/git-flow-release-branches-and-tags-with-or-without-v-prefix

And of course http://semver.org/ noting that a version number and its format has (in theory) nothing to do with tagging of branch naming "per se".

I have to admit that I am a little biased to `v`-less tags because I'm used to git-flow and I found the `v` to be a (potentially) blocking factor when automating stuff and having to compare two different strings.

**Comment by jbrooksuk** [comment]
@GrahamCampbell @joecohens @ConnorVG what do you guys think? We're obviously following Semver here currently.

**Comment by GrahamCampbell** [comment]
What we have is already fine.

**Comment by marcomusso** [comment]
Ok I'll do my best to support your decision and I hope to find a way to handle upgrades in the puppet module.

**Comment by ConnorVG** [comment]
Not only do I think what we have is fine but if we change at this point then it's just going to cause confusion, apologies @marcomusso.
