### ISSUE TITLE
Database password change

### ISSUE THREAD

**Issue by athonyhendrix** [CachetHQ/Cachet#2513]
What is the correct process for changing/updating the mysql cachet user password ensuring cachet still works.  I did this as part of our password cycling, then updated my .env file and then restarted the apache2 service however I would then get error 500s after restart.  The only way I resolved it was to go a manually also change the password in the bootstrap/cache/config.php files which felt like a hack but it worked.  If there is a more correct method let me know.
Thanks.

**Comment by ConnorVG** [comment]
This is due to how config caching works. If you change `.env`, consider running `php artisan config:cache` to re-cache your config.
