### ISSUE TITLE
Managing announcements

### ISSUE THREAD

**Issue by labatt** [CachetHQ/Cachet#2518]
Just a thought for a future version... If you look at https://status.suredone.com you'll see I added some Announcements towards the top of the page. I had to modify the header via the ui to do this. It would be nice if this was another section where we could add and remove announcements like we do incidents, perhaps with a start and end date and the ability to order them. We find the announcements very useful for longer term outages or general info.. and have found that people don't scroll down the page to incidents to get info. Adding this section has greatly reduced our support calls.

**Comment by jbrooksuk** [comment]
Perhaps you're looking for Scheduled Maintenance? Cachet will show these above the incidents section.

**Comment by labatt** [comment]
Scheduled maintenance is a bit different. These might not be things like scheduled maintenance, but something larger. For example, we're in the process of migrating from dedicated hosting to AWS. There will be many scheduled maintenance times, but we want to have an overarching message at the very top of the status page under the logo that says... here's what we're doing so make sure to keep an eye on scheduled maintenance. I guess what we're looking for is an "above the fold" place to include general info relevant to our status - we don't want users to have to scroll past components, scroll past multiple metric charts, and THEN see really important status info that might be bigger than the rest of the stuff. Once again - see how we added this at https://status.suredone.com.

**Comment by baxter19** [comment]
+1 I think this type of functionality would be useful for general communication. Perhaps even rebranding the scheduled maitenance block to a more generic announcements (which could contain upcoming maitenance or other notifications)

**Comment by jbrooksuk** [comment]
Putting this into v2.4 as this would make a really good feature but should be done **after** the new design.

**Comment by AchoArnold** [comment]
@jbrooksuk Is this ready to be picked up? Has the new design been completed?

**Comment by jbrooksuk** [comment]
Thank you for your input on Cachet 2.x. We are shifting our attention and resources to Cachet 3.x and will no longer be supporting the 2.x version. If your feedback or issue is relevant to the 3.x series, we encourage you to engage with the new branch.

For more information on the Cachet rebuild and our plans for 3.x, you can read the announcement [here](https://github.com/CachetHQ/Cachet/discussions/4342).

We appreciate your understanding and look forward to your contributions to the new version.
