### ISSUE TITLE
Subscription possible for internal components

### ISSUE THREAD

**Issue by spiritix** [CachetHQ/Cachet#2520]
If I click subscribe as a not logged in user, I will see all components, independently of whether they are set to "only visible to logged in users" or not. This is a privacy issue, I don't want our subscribers to see our internal components.

**Comment by jbrooksuk** [comment]
This is definitely a bug!

What version are you using? I reckon this will need back porting to v2.3 too.

**Comment by spiritix** [comment]
Looks like Composer somehow pulled 2.4.0-dev. Maybe it's working in the last stable version?

**Comment by jbrooksuk** [comment]
Fixed!
