### ISSUE TITLE
Thirdparty integration for automatically managing uptime, response time and component status

### ISSUE THREAD

**Issue by spiritix** [CachetHQ/Cachet#2521]
Cachet is a great software, but for being able to compete against services like status.io, it's absolutely required that all components and metrics are automatically monitored and updated. I've had a look at the existing thirdparty integrations and even tried some of them. Unfortunately, it seems like none of them offers all of the following, major, features:

- Monitor component status
- Automatically create incidents
- Automatically update response time metrics
- Automatically update uptime metrics

Does anyone have a suggestion? If so, it would be great if you could add it to the docs.

**Comment by codeagencybe** [comment]
Agree, I also just checked many of the integrations and also missing these points. 
Any update so far for this?

**Comment by jbrooksuk** [comment]
Currently this it out of scope for Cachet. Adding a monitoring layer is definitely something I’d like to add, but I’m already behind on many other issues. I’m leaving this open for now though.

**Comment by jbrooksuk** [comment]
I'm going to close this as I don't believe this should sit in the Cachet core at this time.

However, please do feel free to add this and open a PR if you make it happen :)

**Comment by jbrooksuk** [comment]
Cachet does provide an API that this can be easily integrated into :)

**Comment by codeagencybe** [comment]
Yes I'm trying to get info about that, but the documentation is not much as of this moment. 
For monitoring, I'm already checking apps like prometheus, and zabbix. But now I also need to check how those can push back updates to cachethq to create auto updates, incidents, etc.. via API. 

Opsgenie looks like a very nice component inbetween but they don't have any support yet for cachethq. Neither does Zapier which would also be feasible to use the webhooks feature perhaps.

**Comment by jbrooksuk** [comment]
True, the documentation isn't great - we're looking into that in [CachetHQ/Docs](/CachetHQ/Docs).

**Comment by jbrooksuk** [comment]
If you're looking for an Opsgenie/Zapier integration, then I'd suggest reaching out to them and showing your support for it 😃

**Comment by spiritix** [comment]
@jbrooksuk 
> I'm going to close this as I don't believe this should sit in the Cachet core at this time.

I understand that this might currently be out of scope of Cachet core. However, I think it's the responsibility of the Cachet authors to provide or at least initialize a well tested, comprehensive **integration** with a service that provides the mentioned features. As long as this is not available, Cachet can't be considered a true alternative to commercial solutions like statuspage.io & co.

**Comment by jbrooksuk** [comment]
> However, I think it's the responsibility of the Cachet authors to provide or at least initialize a well tested, comprehensive integration with a service that provides the mentioned features.

@spiritix can you please explain this further? Cachet does not claim to solve the issue you're looking to solve, so why should we provide a solution to a different issue because it suits you? Last time I check out StatusPage.io, it had monitoring of a few services but you couldn't add your own. Why is it different for Cachet?

If you're looking for addons that may be able to do this then see https://docs.cachethq.io/docs/addons

**Comment by codeagencybe** [comment]
I also find that strange feedback. 
I would also love to see monitoring inside CachetHQ, but I can understand this is an entire different story and scope for a statuspage tool. 

I think the API should be sufficient to build an integration with any other monitoring system available in the market (either opensource or commercial). 
I'm currently looking at prometheus.io which seems to be a very popular one. 
The only problem I find difficult is that docs are very short, there is barely any information available about the API, how to use, some PHP examples etc... 
That would be very helpful to anybody trying to integrate CatchetHQ with any possible 3rd party app.

**Comment by anthonybocci** [comment]
I understand @jbrooksuk, Cachet is a project about a status page. It is up to us to provide a documented API to allow easy integration, but it's not up to us to provide all existing integration. It's only my mind. I agree we aren't perfect about the API documentation, but we're working on it.

@codeagencybe It was a temporary solution, but I began to write some Swagger annotation on the API. You can read these annotation that describe the API [on a dedicated branch]. Swagger takes lot of lines and the controllers are not so readable then, so we are working on the documentation in the `/docs` directory.

@jbrooksuk Why should we move the documentation in CachetHQ/Docs? I think we could keep the documentation at one place, so if someone clones the repository it has the documentation inside.

**Comment by jbrooksuk** [comment]
> @jbrooksuk Why should we move the documentation in CachetHQ/Docs? I think we could keep the documentation at one place, so if someone clones the repository it has the documentation inside.

Potentially we could have it in both places.

**Comment by spiritix** [comment]
> Cachet does not claim to solve the issue you're looking to solve, so why should we provide a solution to a different issue because it suits you? Last time I check out StatusPage.io, it had monitoring of a few services but you couldn't add your own. Why is it different for Cachet?

@jbrooksuk The issue I am looking to solve is automating the status page, which I hardly think I am the only person trying to do that. Otherwise, should one update his response time metrics manually once a minute? I can think of three possible solutions for that:

1. Extending Cachet with a simple tool for measuring system metrics
2. Providing an API for being able to push the relevant metrics and statuses to Cachet
3. Providing integrations with popular third-party solutions like New Relic, Pingdom, etc.

I understand and agree that 1. is out of scope.  Then 2. certainly does make sense but doesn't really solve the problem, since it only works for people operating with a custom monitoring system. So finally 3. is what I would appreciate being implemented. And that is also what the major commercial solutions like StatusPage.io or Status.io base their services on.

I don't know if anything was implemented in this area since I opened this issue one year ago, but the last time I checked I was not able to fully automate the status page. After trying back and forth for a long time, I managed to get an integration working which does update the uptime more or less properly and another one which updates the component status, but then the response time metrics were not provided at all. 

So what I am missing in the documentation is a simple tutorial on how to set up Cachet, possibly by using third-party services, so that at least the following tasks are automated:

- Component status
- Response time metrics
- Uptime metrics

**Comment by jbrooksuk** [comment]
@spiritix point two of your list is already done. There is a powerful JSON API that you can use.

Point 3 is as much up to us as it is New Relic, Pingdom etc. Maybe you should speak with them to ask them to do the integration. Again, Cachet has an API, so they can easily connect to it.

**Comment by spiritix** [comment]
@jbrooksuk From my point of view it's clearly up to Cachet to provide such integrations since it would put Cachet into the position of being a real competitor to Status.io & co. I am sure the large majority of the Cachet community would highly appreciate that. But ok, you are the author, if you see it differently I am not going to question that.

**Comment by jbrooksuk** [comment]
@spiritix have you tried reaching out to the other companies and seeing if they’ll integrate?

**Comment by spiritix** [comment]
@jbrooksuk New Relic is a listed $350 million enterprise, I am quite convinced that they'll argue it's up to third-party tools to integrate with their API, and not the other way round :) Especially since Status.io and StatusPage.io already have integrated with New Relic, Pingdom, Librato, etc. by themselves.

**Comment by jbrooksuk** [comment]
That’s the wrong attitude in my opinion. Money doesn’t make them better than anybody. 

Also, there are tools such as https://github.com/99Taxis/cachet-newrelic-proxy

**Comment by spiritix** [comment]
Mate, I am not New Relic, if you convince them to integrate with Cachet I'll owe you a crate of beer, but in reality, it just doesn't work like this. Let's end this discussion here, if you guys think integrations are not important and every user should hack his own integration, then it should be like that. Meanwhile, I'll be happy to pay a few bucks for a fully automated, integrated and working solution.

**Comment by spiritix** [comment]
@codeagencybe 
> there are integrations available, check the docs!

Already spent a couple of days with that, see my initial post. 

> Secondly, I don't think any platform has any obligation to build integrations for any other possible piece of software in the world.
> Is it good for commercial reasons: yes absolute, I agree with you about that. But that still does not mean they have to do it.

Absolutely, yes. Nobody has to do anything. The question is what do you want Cachet to be? If you want it to be an automated status page, then someone needs to build this, if you want it to be a manually operated one, then certainly not. The thing is just, then it's probably not interesting for large parts of the users which would be very sad considering the great amount of work already put into it.

> You can not compare a commercial business like statuspage.io, new relic, etc... with an opensource product that is FREE available for anybody.
> Those commercial tools can build all those integrations because simply said, they have the money for it! Everybody is paying for the tool, they have turnover, and gives them leverage to invest faster and more in e.g. integrations.

Agree, that's why open source projects have a community which contributes for free.

> Using opensource means that users also should try to contribute back to the product by e.g. providing integrations, translations, etc...
> There is no money in the project to keep up with commercial tools like statuspage (at least not as much as them), so development goes slower and there is no room to build anything and everything because somebody needs something.
> That's the whole point and model to keep the tool free, otherwise it will just be become a dead product sooner or later.

Here I can't quite agree with you. If open source projects can't manage to keep up with their commercial competitors, at least considering the major features, they are going to die earlier or later. People (or let's say companies) are just not going to mess around with anything if they can have a much better commercial solution for a few bucks. For example, have a look at osTicket, it was huge 10 years ago and nowadays it's about to disappear. Why? Because there are alternatives like ZenDesk which are 10x better and available for small money!

> If you don't mind paying a few "bucks", then why not simply hire a developer and pay him to develop the integration for you between CachetHQ and any monitoring tool you want?
> That way, you also have the integration you need and at the same time you don't have to pay for any recurring subscription business like statuspage. And if you truly support opensource, you could give publish the integration back to CachetHQ so other users can also use and keep improving the complete tool. That's a win-win-win case and the only way how opensource should be like.

Because that would cost me much more than paying for a commercial solution, exactly the thing I wrote above. The initiative for those integrations needs to come from you guys. Instead of closing all issues related to this topic you could have kept them open, labeled them with 'Help wanted' and maybe provide some guidelines on how they should be structured, etc. Then I am sure a lot of people from your community, including me, would have been happy to contribute.

**Comment by anthonybocci** [comment]
Because it's a community discussion, I'll try to give my opinion too.

**Is it up to the core developers to create integrations?** I would say **no** to this question. As said by @jbrooksuk, a powerful API is there and it's easily possible to monitor anything and post the informations into the API. You want your website response time? No problem, with a little script you can _ping_ it and send the data into Cachet, and if the response time is greater than 2 seconds create an incident using the API. It would be automated.  
You are write, the API documentation is pretty poor, it was out of date. That's why we are working on documentation, about the status page and about the API. But I think it's not useful to give a PHP example of the API request, because:
1. If it's written `GET /incidents/42` there is not need of more, any developer that knows how to use HTTP with its favorite language understands what to do.
2. PHP is not the only language, specially when we speak about CLI programs or monitoring daemon. For example, cachet-monitor is written in Go, some other tools are written in Python or Ruby. 

**Should we forget all integrations?** I would say **no** to this question. It would be absolutely great if we had many integrations with many other platforms. But I think:
1. It shouldn't be built in Cachet. Cachet is a __Status Page_, I think it's important to remember this.
2. Everybody in the community may help for this, and many have already helped by creating addons, like Cachet Monitor and many others. 
I agree when you say that we could set a label like 'Help wanted' or other and leave the issue open. Doing so, a community member could do it. But the core developers of Cachet are busy with Cachet core, and with their own lives. Because as it was said, we are not a company, we are people around the world working together on our free time.
