### ISSUE TITLE
Cachet not abiding by set APP_URL

### ISSUE THREAD

**Issue by gonzoinc** [CachetHQ/Cachet#2522]
I moved our instance behind SSL Termination and even though APP_URL is set to reflect the new hostname and HTTPS:// when you navigate to the main page and click on Dashboard at the bottom of the page the link is being populated without the HTTPS:// so it leads to a 404 error. I

I have gone through and double checked the env variables being set, cleared the cache and config, Removed the cache files, etc and nothing seems to be changing the links to use HTTPS. What am I missing here?

**Comment by jbrooksuk** [comment]
Assuming you'r using a proxy server, you need to add the IP to `./config/trustedproxy.php`.

**Comment by gonzoinc** [comment]
Yes it is behind a proxy.

We do not store anything via IP address as our environment is constantly changing with VM's being shifted around. So it is bad setting anything via an IP address. 

Looks like I was able to dump the IP addresses in the trustedproxy file and just wildcard it to correct the problem.

Thanks!

**Comment by gonzoinc** [comment]
After further testing wildcarding the proxy config did nothing. Requests were still redirecting to http. We found this after spinning up another staging instance. Last instance still had browser cache to force https still set which is why we missed it thinking the proxy wildcard had fixed it.

Adding rewrite condition statements into the Apache Config file forcing it to always use HTTPS seems to be the only way to resolve the issue. We also set a strict transport security header so that the browser knows to always connect via https.

**Comment by gonzoinc** [comment]
Problem we are seeing now is the invite emails going out are using HTTP in the email links. So unless the user goes to the site to have the security header set they will get a 404 when clicking links in emails. 

There needs to be a way to force HTTPS for all links in the system.

**Comment by gonzoinc** [comment]
So this has been a pain in the ass to figure out but I finally have a working solution. I want to note that I have no clue what the values set in the Db:Settings table for App_domain are used for, I see it being written into the production.php file for cache and I am assuming it is being pulled from the .env file on initial install and set elsewhere, but it looks like it does not get used when building out the pages/link or being used in the notification emails being sent. I located the issue back to the cachet_route function and from there found the below fix.

The fix to the problem  I have confirmed is working which will force Cachet/Laravel to be https including building out all links to be https. regardless being behind a proxy, etc. Our Proxy is configured to reroute to https along with the before mentioned apache config changes, but when emails go out the links are all http. Unless the end user has been to the site previously they were getting a 404 error when they clicked the links in the email. So I decided that all these bandages were not an actual fix and the core application needed to be writing the links to https.

within app/Foundation/Providers/AppServiceProvider.php

In the boot function add in the following:

`          \URL::forceSchema('https');
`

Examples I found online had it wrapped in an if statement as below. I believe it was for a previous version of Laravel as I'm not sure is App::environment('local') still used. I had it included in mine originally and the https was still forced 

`if (!\App::environment('local')) {
          \URL::forceSchema('https');
        }
`

My recommendation would be to add this in and create a .env setting for it to allow it to be changed as needed depending on the install.

**Comment by nixmomo** [comment]
Sounds that your Webserver isn't well configured.... do. you know about rewrite from http to https? 
It isn't the job from cachet to do that...

**Comment by gonzoinc** [comment]
Originally had rewrite rules in place to convert all http to https but that is considered a hack and insecure which worked fine in staging, but for production it needed to be secured the correct way. Forcing it to be secure to begin with is the correct method which is what the above settings resolves.

**Comment by Thomvaill** [comment]
If you are still interested, I posted a Dockerfile example that fixes (in an ugly way) this issue: https://github.com/CachetHQ/Cachet/issues/3952
