### ISSUE TITLE
Open issue at top

### ISSUE THREAD

**Issue by mattmartincouk** [CachetHQ/Cachet#2524]
Can't spot any existing "issues" about this but apologies if there is already.

As the posts are in date order, sometimes if an issue has been updated (current post text), it is lost should that remain open for a few days.

Either being able to pin postings until resolved or keep them "at top" automatically could be useful.

Had a few times where the component states an issue but as the days have progressed, it isn't clear what the issue is.

**Comment by jbrooksuk** [comment]
This is something that'll be changing in v2.4

Instead of showing the last x days, we'll be showing a list of unresolved incidents and then allow you go back through history.
