### ISSUE TITLE
Design not appear in setup page

### ISSUE THREAD

**Issue by Amisoz** [CachetHQ/Cachet#2526]
Hi, i have try to install Cachet.
But, the setup page haven't got design. I can make without but i think after the install this don't change.
Screen : http://prntscr.com/f6me31

(Sorry for my bad english :o)

**Comment by Amisoz** [comment]
And i see in tutorial i just have to go in my website. But for have this page, i have to go in server.php, because when i go in my website i have a index of

**Comment by jacoblw** [comment]
Looking at your Site Domain, you're using a subfolder?
 see https://github.com/CachetHQ/Cachet/issues/1696

**Comment by jbrooksuk** [comment]
Installation support isn't provided by ourselves on the issue tracker. Can you email support@alt-three.com please.
