### ISSUE TITLE
Option to limit number of incidents returned by API

### ISSUE THREAD

**Issue by jaxxstorm** [cachethq/Cachet#253]
Currently, when you list all the incidents from the incidents API, you get every incident that has occurred.

It may be in the future that there are a lot of incidents for some installations. It would be nice if we could pass a parameter, such as "limit" and then only get say, the last 10 incidents

**Comment by jbrooksuk** [comment]
Good idea. We'd also perhaps want to paginate the results, and like you said, limit by default but that could be overwritten.

**Comment by GrahamCampbell** [comment]
Yeh, a limit and an offset.

**Comment by joecohens** [comment]
I think it could be api/incidents?per_page=20&page=1.

@GrahamCampbell How do you like to manage paging with Laravel, with the built in methods or manual?

**Comment by jbrooksuk** [comment]
I think that's how GitHub's API works?

**Comment by GrahamCampbell** [comment]
Yeh, that would probably work.

**Comment by GrahamCampbell** [comment]
NB, pagination is also much improved in L5.

**Comment by joecohens** [comment]
@GrahamCampbell Should we wait to L5 to implement it?

**Comment by GrahamCampbell** [comment]
Nah, just implement it. Your code might just appear "hacky".

**Comment by jbrooksuk** [comment]
FWI Dingo [will be upgraded](https://github.com/dingo/api/issues/213) to support L5, but only once the dust settles.

**Comment by foxted** [comment]
It could be interesting to try to implement the API ourselves using Fractal, don't you think? It shouldn't be that hard, and like @GrahamCampbell said, L5 pagination will be much better.

**Comment by jbrooksuk** [comment]
@foxted sure, but it's a lot of extra work, what with writing auth adapters etc. Heck, it may be worthwhile and if so, we should do it.

**Comment by GrahamCampbell** [comment]
I don't think fractal even supports the new paginator yet. So that's another thing to wait for since dingo depends on it...

**Comment by jbrooksuk** [comment]
Dingo does support [pagination](https://github.com/dingo/api/wiki/Responses#responding-with-paginated-items) but if we're switching to Laravel 5 soon, then it's probably not worth implementing yet...
