### ISSUE TITLE
Change Wording in Schedule Maintenance

### ISSUE THREAD

**Issue by apssupport** [CachetHQ/Cachet#2530]
Good Morning,

I noticed the wording on the scheduled maintenance email that gets sent out for any future even says **"was scheduled"** instead of **"is scheduled"**. Is that something that we can change on our own? Example below.

A new scheduled maintenance was created.

CrunchTime! Scheduled Maintenance was scheduled for Sunday 21st May 2017 03:30:00

**Comment by jbrooksuk** [comment]
Hey! Thanks for reporting this. This requires a little bit of work to achieve as it's not a simple translation.

**Comment by jbrooksuk** [comment]
Thank you for your input on Cachet 2.x. We are shifting our attention and resources to Cachet 3.x and will no longer be supporting the 2.x version. If your feedback or issue is relevant to the 3.x series, we encourage you to engage with the new branch.

For more information on the Cachet rebuild and our plans for 3.x, you can read the announcement [here](https://github.com/CachetHQ/Cachet/discussions/4342).

We appreciate your understanding and look forward to your contributions to the new version.
