### ISSUE TITLE
RSS/Atom feeds don't include Incident Updates

### ISSUE THREAD

**Issue by cboltz** [CachetHQ/Cachet#2531]
The RSS and ATOM feeds only include the initial Incident, but don't include anything added as update later. The result is that people who just watch the RSS or ATOM feed never get notified about updates (like "fixed now").

Please change the feeds so that updates get included - either as separate articles (with title "Update for $original_title") or by adding the update to the original Incident text.

**Comment by jbrooksuk** [comment]
Ah yes, good point. Feel free to make a PR for this!

**Comment by jbrooksuk** [comment]
Based on @GrahamCampbell's [tweet](https://twitter.com/GrahamJCampbell/status/1057654707810910208) regarding RSS feeds, I think we can look at removing them.

**Comment by jbrooksuk** [comment]
We removed the feeds.
