### ISSUE TITLE
Translate Error Pages

### ISSUE THREAD

**Issue by fabm3n** [CachetHQ/Cachet#2534]
The Error Pages arent translatet. Can you add them to crowdin so the community can translate them for the next update?

**Comment by jbrooksuk** [comment]
This is because we use a package by @GrahamCampbell and never translated it.

**Comment by jbrooksuk** [comment]
Thank you for your input on Cachet 2.x. We are shifting our attention and resources to Cachet 3.x and will no longer be supporting the 2.x version. If your feedback or issue is relevant to the 3.x series, we encourage you to engage with the new branch.

For more information on the Cachet rebuild and our plans for 3.x, you can read the announcement [here](https://github.com/CachetHQ/Cachet/discussions/4342).

We appreciate your understanding and look forward to your contributions to the new version.
