### ISSUE TITLE
Adding Update Check

### ISSUE THREAD

**Issue by fabm3n** [CachetHQ/Cachet#2535]
It would be nice if you can add an Update Checker in the Settings when you click on the version (or something else). Also with a link to the upgrade description in the docs.

**Comment by jbrooksuk** [comment]
We already do this :)

**Comment by fabm3n** [comment]
Thanks! 

_Sent from my OnePlus ONEPLUS A3003 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by fabm3n** [comment]
Thanks! 

_Sent from my OnePlus ONEPLUS A3003 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_
