### ISSUE TITLE
minutes of threshold between metric points has no effect

### ISSUE THREAD

**Issue by gn-ley** [CachetHQ/Cachet#2538]
Metric Points are not summed up according to configuration of "minutes of threshold between metric points".

Default points as well as actual reported points. I need this to avoid tailing 0-values.

Made these screenshots with default points in https://dev.cachethq.io/ (but same issue in demo.cachethq.io and 2.3).

![bildschirmfoto 2017-05-22 um 11 47 18](https://cloud.githubusercontent.com/assets/14089663/26302438/8d0a2ca8-3ee4-11e7-9dc0-6b769e65dfec.png)

![bildschirmfoto 2017-05-22 um 11 46 52](https://cloud.githubusercontent.com/assets/14089663/26302450/96846776-3ee4-11e7-996a-c2d07ee37edd.png)

**Comment by jbrooksuk** [comment]
What happens on https://dev.cachethq.io?

**Comment by gn-ley** [comment]
Screenshots are made on https://dev.cachethq.io. So every version has this behaviour.

**Comment by getvivekv** [comment]
Subscribing. I also see this bug with my installation. v2.4
In addition to this, I get this error message "The threshold must be between 0 and 10" when I select the threshold value 15. I understand the error message, but I shouldn't be presented with the values other than 0-10 if this is not allowed. Currently, I see values till 60 minutes.

**Comment by freaghill** [comment]
+1

**Comment by jbrooksuk** [comment]
Sorry about this. I really, really need to look at metrics.

**Comment by jbrooksuk** [comment]
Supporting SQLite, MySQL and Postgres makes this harder though.

**Comment by mmihalev** [comment]
Same issue here....

**Comment by 009800** [comment]
Any news? :) Same here.

**Comment by RedSpid3r** [comment]
any update?

**Comment by jbrooksuk** [comment]
Not as of yet, sorry. 

I could really do with someone taking a look at the metrics system and removing all the issues.

The current system is a bit of an embarrassment.

**Comment by jbrooksuk** [comment]
This should be fixed in v2.4
