### ISSUE TITLE
Do not create a tailing default point if still in threshold

### ISSUE THREAD

**Issue by gn-ley** [CachetHQ/Cachet#2539]
Metric-Graph drops to zero (= my default value) when url-monitor has not yet reported a new point.

This is a show-stopper for metric-graphs, because our clients might get confused and think our service just died. See screenshot below.

The graph should not create a default point if there was a point reporting during threshold-time (which also might be 1min).

![bildschirmfoto 2017-05-22 um 11 57 03](https://cloud.githubusercontent.com/assets/14089663/26303015/5c7174b4-3ee6-11e7-8abf-17d4e2fa0e37.png)

**Comment by jbrooksuk** [comment]
This has always annoyed myself and @GrahamCampbell!
