### ISSUE TITLE
Improved look for metrics

### ISSUE THREAD

**Issue by gn-ley** [CachetHQ/Cachet#2540]
The metrics have an unusual look in comparison to other metrics. The metric display should be improved.

Here are some problems I see with the current display:

1. Every other setting then "last hour" makes to much averaging (so points are pretty sense-less) and drop downs are not visible. Only really long lasting failures would be remarkable.

2. Line has a "strange" curve, point should be connected directly.

3. Make the value more remarkable. e.g. show the last value with suffix.

4. Dont show to much labels (every point makes a label).

Here are some examples of other pages:

![bildschirmfoto 2017-05-22 um 12 13 42](https://cloud.githubusercontent.com/assets/14089663/26303800/2905aed0-3ee9-11e7-926f-fe145439ff6b.png)
![bildschirmfoto 2017-05-22 um 12 12 27](https://cloud.githubusercontent.com/assets/14089663/26303801/2906ab28-3ee9-11e7-97be-200aa8ab3d92.png)

**Comment by jbrooksuk** [comment]
I'd love for someone to implement a new metrics system! The example from StatusPage.io is far nicer and way easier to understand.

**Comment by AdaptiveThinking** [comment]
One addition: The new StatusPage-Showcase is very nice. (see [Atlassian](https://www.atlassian.com/blog/statuspage/introducing-statuspage-uptime-showcase) [Reddit-Statuspage](http://www.redditstatus.com/) [CircleCI-StatusPage](https://status.circleci.com/)

It would probably be a good Idea to also include Maintanance-Windows in there.

![grafik](https://user-images.githubusercontent.com/6608070/29005523-399cc4ce-7add-11e7-8ca7-b32ff32d2be5.png)

**Comment by gn-ley** [comment]
Similar issue is #1656. Which apparently has an PR already.

**Comment by jbrooksuk** [comment]
If someone wants to overhaul the metric system, **please** do so :) It's currently nowhere near fit for purpose.

**Comment by jbrooksuk** [comment]
Closed in favour of https://github.com/CachetHQ/Cachet/issues/2641
