### ISSUE TITLE
Manage Subscriptions Form select/deselect all

### ISSUE THREAD

**Issue by gonzoinc** [CachetHQ/Cachet#2541]
It seems the select all and deselect all buttons do nothing on the manage subscription form. There looks to be zero JS functionality coded into the buttons. Not sure if these are placeholders for future or someone missed something.

This is in 2.4

**Comment by jbrooksuk** [comment]
Yeah, I think this may be the case as part of the redesign.

**Comment by AchoArnold** [comment]
Hey @jbrooksuk  It seems this issue has been resolved? I don't see any "Select All/ Deselect All" button under the subscriptions section.

![screenshot 2018-10-16 11 17 03](https://user-images.githubusercontent.com/4196457/47009710-1b856900-d135-11e8-8566-9597341bd0e1.png)

**Comment by jbrooksuk** [comment]
@AchoArnold this issue is relating to the customer-facing subscription page.

**Comment by jbrooksuk** [comment]
Thank you for your input on Cachet 2.x. We are shifting our attention and resources to Cachet 3.x and will no longer be supporting the 2.x version. If your feedback or issue is relevant to the 3.x series, we encourage you to engage with the new branch.

For more information on the Cachet rebuild and our plans for 3.x, you can read the announcement [here](https://github.com/CachetHQ/Cachet/discussions/4342).

We appreciate your understanding and look forward to your contributions to the new version.
