### ISSUE TITLE
Subscribed to all updates

### ISSUE THREAD

**Issue by gonzoinc** [CachetHQ/Cachet#2542]
When a user subscribes and selects no components to be notified on, the Admin Dashboard UI is showing "Subscribed to all updates". Seems this only gets set when the user unchecks all components when they subscribe. So it should show something like "No Subscribed Components".

![screen shot 2017-05-23 at 11 17 00 am](https://cloud.githubusercontent.com/assets/27728728/26361656/9d26674e-3fa9-11e7-9759-ec5686a1873c.png)

**Comment by jbrooksuk** [comment]
Definitely a bug, thanks for reporting!

**Comment by jbrooksuk** [comment]
Fixed!
