### ISSUE TITLE
Subscriptions are not removed once unsubscribed

### ISSUE THREAD

**Issue by robdn** [CachetHQ/Cachet#2543]
Hi Cachet!
We're running 2.3.9.

I've noticed today that when a subscriber unsubscribes he or she is correctly removed from table 'subscribers', however, the subscriptions connected with the subscriber are not removed from table 'subscriptions'.

Now I don't see a point in keeping them, since the joining record is removed from 'subscribers' so there's no value. Such records are only wasting DB space. 

I believe it would be beneficial to change this behaviour and remove connected subscriptions as well.

Hope this report helps!

D

**Comment by jbrooksuk** [comment]
Yeah, this should be the case for performance alone really.

**Comment by jbrooksuk** [comment]
Hmm... We do this already https://github.com/CachetHQ/Cachet/blob/5a78eeb6a980aac52c294fe2f52dca27fad4b552/app/Bus/Handlers/Commands/Subscriber/UnsubscribeSubscriberCommandHandler.php#L38

**Comment by jbrooksuk** [comment]
Ah back at this https://github.com/CachetHQ/Cachet/commit/f9bf20aa53514547977d74bd8416c8502a98ac85
