### ISSUE TITLE
Need to change the email notification subject

### ISSUE THREAD

**Issue by Djas2017** [CachetHQ/Cachet#2544]
Hi,

As the emails do not seem to be customizable from the dashboard area, what is the easiest way to change the **email notification email subject** for new incidents and component status changes.

Current email notification subject when a new incident is created: "New Incident Reported"

Is it possible to add the value of the variable we configure in the settings/Dashboard area (Called Site Name) to have something like: "[$Site_Name] New Incident Reported" 

If this is not possible, where do we have to change it to something static/hardcoded like "[MyCompany] New Incident Reported" 

Same thing will apply for notifications related to component status change.
Current email subject is: "Component Status Updated"
New: "[$Site_Name] Component Status Updated"     or  "[MyCompany] Component Status Updated"

Thanks

**Comment by jbrooksuk** [comment]
You can edit the language file :) look in resources/Lang/en or whichever language code you need to edit.

**Comment by Djas2017** [comment]
Thank you, this is exactly what I was looking for!

**Comment by jbrooksuk** [comment]
My pleasure :)

**Comment by wendelmineiro89** [comment]
@Djas2017 please, could you share an example that you configured? I have some doubts about some `vars` that I can user on `notifications.php`.
