### ISSUE TITLE
Email input placeholder in subscription form

### ISSUE THREAD

**Issue by Bvz2001** [CachetHQ/Cachet#2547]
Hi,
we are running 2.3.9 and we think subscribers should see an email placeholder on a subscription page.
For example, adding just `placeholder="email@example.com"` will be a good addition to your redesign efforts.
![download](https://cloud.githubusercontent.com/assets/1611259/26577977/dd070e1c-4536-11e7-9fd6-7ae2b66bb8ac.png)

Thanks.

**Comment by jbrooksuk** [comment]
Feel free to make a PR on the 2.4 branch :)

**Comment by Bvz2001** [comment]
done https://github.com/CachetHQ/Cachet/pull/2560
