### ISSUE TITLE
Automating Installation

### ISSUE THREAD

**Issue by Jamesking56** [CachetHQ/Cachet#2549]
Hello,

Is there any way to install Cachet using Docker but unattended (no gui installation). For example, say I already knew what the settings need to be, can I script the install for Docker to apply the same configuration?

Another example, if I wanted to install 100 Cachet Docker containers and have them all configured and setup automatically, how would I go about doing that?

**Comment by jbrooksuk** [comment]
Hey, can you open this on the [Docker](https://github.com/CachetHQ/Docker) repo please.
