### ISSUE TITLE
Installing Cachet on OpenShift 3

### ISSUE THREAD

**Issue by juliustip** [CachetHQ/Cachet#2551]
Step by Step guide to this would be appreciated.

**Comment by jbrooksuk** [comment]
I've not got any experience with OpenShift, but I seem to remember someone has done an OpenShift install before.

**Comment by Smashmint** [comment]
@juliustip Have you looked at our guide for running Cachet in Docker? You should be able to run Cachet almost everywhere via this way.

**Comment by juliustip** [comment]
@jbrooksuk Saw that at [](https://github.com/ALinuxNinja/openshift-cachet) but its for OpenShift 2 which is now obsolete for new users due to OpenShift 3 release.

**Comment by juliustip** [comment]
@Smashmint I have successfully installed cachet locally via the Docker guide. Am new to that, just needed something flexible and easy to update. Perhaps a guide will do. Or any other host that makes cachet installation a breeze.

**Comment by jbrooksuk** [comment]
Docker should be plenty :)
