### ISSUE TITLE
Error 500 on demo site

### ISSUE THREAD

**Issue by alex-bender** [CachetHQ/Cachet#2552]
Hi  
I'm trying to add new metric via `https://demo.cachethq.io/dashboard/metrics/add`.
Then I'm getting error 500 with message: `This error can be identified by 350699c0-ea7c-4521-939f-41da3a3ba38d.`
Form filled with these data:
```
Name: Test
Suffix: s
Descr: <empty>
Calculation of metrics: Sum
Default view: last 12 h
Default value: <empty>
Decimal Places: 0  # Seems that this one causing the problem
How many minutes of threshold between metric points?: 2
Display chart on status page?: Yes
```
Hope this will help.

**Comment by jbrooksuk** [comment]
@GrahamCampbell any luck on the Beacon server so we can centrally track these errors?

**Comment by GrahamCampbell** [comment]
I will be working on it soon.

**Comment by jbrooksuk** [comment]
The default value is required 👍 in 2.4 the dashboard will now return to you with this error message.

**Comment by vitorbaptista** [comment]
I'm seeing this on `2.5.0-dev`, just built the Docker container from your `cachethq/docker` repository, so I'd imagine it's running the latest version.

Adding the default value fixes the issue.
