### ISSUE TITLE
Getting some random Error 500

### ISSUE THREAD

**Issue by Naspyy** [CachetHQ/Cachet#2553]
`[2017-06-02 08:12:37] production.ERROR: exception 'ErrorException' with message 'proc_open(): fork failed - Cannot allocate memory' in /var/www/status/foxgaming/vendor/symfony/console/Application.php:901
Stack trace:
#0 [internal function]: Illuminate\Foundation\Bootstrap\HandleExceptions->handleError(2, 'proc_open(): fo...', '/var/www/status...', 901, Array)
#1 /var/www/status/foxgaming/vendor/symfony/console/Application.php(901): proc_open('stty -a | grep ...', Array, NULL, NULL, NULL, Array)
#2 /var/www/status/foxgaming/vendor/symfony/console/Application.php(704): Symfony\Component\Console\Application->getSttyColumns()
#3 /var/www/status/foxgaming/vendor/symfony/console/Application.php(665): Symfony\Component\Console\Application->getTerminalDimensions()
#4 /var/www/status/foxgaming/vendor/symfony/console/Application.php(598): Symfony\Component\Console\Application->getTerminalWidth()
#5 /var/www/status/foxgaming/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(142): Symfony\Component\Console\Application->renderException(Object(ErrorException), Object(Symfony\Component\Console\Output\ConsoleOutput))
#6 /var/www/status/foxgaming/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(273): Illuminate\Foundation\Exceptions\Handler->renderForConsole(Object(Symfony\Component\Console\Output\ConsoleOutput), Object(ErrorException))
#7 /var/www/status/foxgaming/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(111): Illuminate\Foundation\Console\Kernel->renderException(Object(Symfony\Component\Console\Output\ConsoleOutput), Object(ErrorException))
#8 /var/www/status/foxgaming/artisan(36): Illuminate\Foundation\Console\Kernel->handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#9 {main} {"identification":{"id":"f04d45ad-3568-414f-a16d-10dfd55e6b70"}} 
[2017-06-02 08:12:37] production.CRITICAL: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'Uncaught exception 'ErrorException' with message 'proc_open(): fork failed - Cannot allocate memory' in /var/www/status/foxgaming/vendor/symfony/console/Application.php:901
Stack trace:
#0 [internal function]: Illuminate\Foundation\Bootstrap\HandleExceptions->handleError(2, 'proc_open(): fo...', '/var/www/status...', 901, Array)
#1 /var/www/status/foxgaming/vendor/symfony/console/Application.php(901): proc_open('stty -a | grep ...', Array, NULL, NULL, NULL, Array)
#2 /var/www/status/foxgaming/vendor/symfony/console/Application.php(704): Symfony\Component\Console\Application->getSttyColumns()
#3 /var/www/status/foxgaming/vendor/symfony/console/Application.php(665): Symfony\Component\Console\Application->getTerminalDimensions()
#4 /var/www/status/foxgaming/vendor/symfony/console/Application.php(598): Symfony\Component\Console\Application->getTerminalWidth()
#5 /var/www/status/foxgaming/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(142): Symfony\Component\Console\Application->renderEx' in /var/www/status/foxgaming/vendor/symfony/console/Application.php:901
Stack trace:
#0 {main} {"identification":{"id":"fcd792d7-5688-4c33-a9e4-1531ee35c03f"}}`

Pretty random as I got three Cachet installations, one working and two have the exact same error...

**Comment by Naspyy** [comment]
Fixed this by `chown -R www-data:www-data /var/www/*` and restarting apache2 with `apachectl restart`.

**Comment by jbrooksuk** [comment]
Nice :)
