### ISSUE TITLE
Why are Incident pages indexed?

### ISSUE THREAD

**Issue by Naspyy** [CachetHQ/Cachet#2554]
Just a quick question: Why do you index (`<meta name="robots" content="index, follow">`) [incident pages](https://status.naspyy.eu/incident/27)? I think this is completely useless...

**Comment by jbrooksuk** [comment]
Can you explain why you think it's useless?

**Comment by ConnorVG** [comment]
I feel like it would be logical to index incident pages; it's self-exposing via search engines

**Comment by Naspyy** [comment]
**I am not talking of the status page in general - more about the incident pages.**

@jbrooksuk:
It would make sense to index incident pages if Google would crawl and apply (index) them while issues are live. In most of the cases, Google takes its time to crawl (about once a day), finds the new page and indexes it. This most of the time takes up to three days.

So in the case, XYZ's server is down and he would google "XYZ's status" he will not be able to find the ongoing incident. When Google does index it, the incident is already resolved in most of the time so I see completely no reason for Cachet to index incident pages.

___

I am sorry, but I do not get your point, @ConnorVG

**Comment by ConnorVG** [comment]
@Naspyy are your timings accurate? What is your source?

**Comment by Naspyy** [comment]
I don't know what you're trying to say? :( @ConnorVG

**Comment by jbrooksuk** [comment]
Google can index very quickly depending on how popular your website is. I've seen articles published within the last few minutes before.

So long as the timestamp of the incident is shown, I see no reason why incident pages should not be indexed.

Is there another reason?

**Comment by Naspyy** [comment]
> I've seen articles published within the last few minutes before.
Do you mean news articles? Yeah, thats usual.

> Is there another reason?
Than at least, make the pagetitle equal to the incident name...

I still think it's useless to index the incident pages as noone profits from it.

**Comment by jbrooksuk** [comment]
> Than at least, make the pagetitle equal to the incident name...

Yeah, we should definitely do this.

**Comment by jbrooksuk** [comment]
In regards to not indexing the incident pages, I see no benefit to doing this so at least for now, we'll leave this as is. Page title needs updating though!
