### ISSUE TITLE
Installing Cachet error

### ISSUE THREAD

**Issue by arriej** [CachetHQ/Cachet#2555]
Hello,

I tried to install Cachet (done it before without error). Now on a new machine, and with plesk php settings. 
I get the following error during the command "composer install --no-dev -o" 

```
 Generating optimized autoload file
> Illuminate\Foundation\ComposerScripts::postInstall
PHP Parse error:  syntax error, unexpected '$value' (T_VARIABLE) in /var/www/vhosts/blockmadness.com/status/vendor/aws/aws-sdk-php/src/functions.php on line 36
```
I rechecked all needed php extentions they are all activated. I dont know what to do next. I used version v2.3.11 and php version 7.0.19

Thanks in advance

**Comment by cfarthingale** [comment]
I would like to second this issue rather than create a new one but am experiencing a similar/same issue. Just as arriej experienced I ran " " and received this error as output:

`  - Installing rcrowe/twigbridge (v0.9.1): Downloading (100%)         
  - Installing roumen/feed (v2.9.9): Downloading (100%)         
Generating optimized autoload files
> php artisan clear-compiled
PHP Parse error:  syntax error, unexpected 'class' (T_CLASS), expecting identifier (T_STRING) or variable (T_VARIABLE) or '{' or '$' in /var/www/html/Cachet/vendor/laravel/framework/src/Illuminate/Foundation/helpers.php on line 104
Script php artisan clear-compiled handling the post-install-cmd event returned with error code 255
`
I then followed the next suggested step: "If you're stuck at the Composer stage, you can run composer install --no-dev -o --no-scripts" which seemed to work?:

`[root@user Cachet]# composer install --no-dev -o --no-scripts
Do not run Composer as root/super user! See https://getcomposer.org/root for details
Loading composer repositories with package information
Installing dependencies from lock file
Nothing to install or update
Generating optimized autoload files
`

I then progressed to the next step "php artisan key:generate" and received the following error:

`[root@status Cachet]# php artisan key:generate
PHP Parse error:  syntax error, unexpected 'class' (T_CLASS), expecting identifier (T_STRING) or variable (T_VARIABLE) or '{' or '$' in /var/www/html/Cachet/vendor/laravel/framework/src/Illuminate/Foundation/helpers.php on line 104`

Any assistance in this matter is greatly appreciated.

**Comment by jbrooksuk** [comment]
Can you run:

1. `composer clear-cache`
2. `rm -rf vendor/`
3. `composer install --no-scripts -o`

Thanks!

**Comment by arriej** [comment]
Ran the commands, tried to install again. Same error (from my phone) 

**/prophecy (v1.7.0): Downloading (100%)
  - Installing phpunit/phpunit (4.8.21): Downloading (100%)
  - Installing symfony/dom-crawler (v3.2.6): Downloading (100%)
symfony/var-dumper suggests installing ext-symfony_debug ()
symfony/translation suggests installing symfony/config ()
symfony/routing suggests installing symfony/config (For using the all-in-one router or any loader)
symfony/routing suggests installing symfony/dependency-injection (For loading routes from a service)
symfony/routing suggests installing symfony/expression-language (For using expression matching)
symfony/event-dispatcher suggests installing symfony/dependency-injection ()
symfony/http-kernel suggests installing symfony/browser-kit ()
symfony/http-kernel suggests installing symfony/class-loader ()
symfony/http-kernel suggests installing symfony/config ()
symfony/http-kernel suggests installing symfony/dependency-injection ()
psy/psysh suggests installing ext-pdo-sqlite (The doc command requires SQLite to work.)
psy/psysh suggests installing ext-posix (If you have PCNTL, you'll want the POSIX extension as well.)
paragonie/random_compat suggests installing ext-libsodium (Provides a modern crypto API that can be used to generate random bytes.)
monolog/monolog suggests installing doctrine/couchdb (Allow sending log messages to a CouchDB server)
monolog/monolog suggests installing ext-amqp (Allow sending log messages to an AMQP server (1.0+ required))
monolog/monolog suggests installing ext-mongo (Allow sending log messages to a MongoDB server)
monolog/monolog suggests installing graylog2/gelf-php (Allow sending log messages to a GrayLog2 server)
monolog/monolog suggests installing mongodb/mongodb (Allow sending log messages to a MongoDB server via PHP Driver)
monolog/monolog suggests installing php-amqplib/php-amqplib (Allow sending log messages to an AMQP server using php-amqplib)
monolog/monolog suggests installing php-console/php-console (Allow sending log messages to Google Chrome)
monolog/monolog suggests installing rollbar/rollbar (Allow sending log messages to Rollbar)
monolog/monolog suggests installing ruflin/elastica (Allow sending log messages to an Elastic Search server)
monolog/monolog suggests installing sentry/sentry (Allow sending log messages to a Sentry server)
league/flysystem suggests installing league/flysystem-aws-s3-v2 (Allows you to use S3 storage with AWS SDK v2)
league/flysystem suggests installing league/flysystem-aws-s3-v3 (Allows you to use S3 storage with AWS SDK v3)
league/flysystem suggests installing league/flysystem-azure (Allows you to use Windows Azure Blob storage)
league/flysystem suggests installing league/flysystem-cached-adapter (Flysystem adapter decorator for metadata caching)
league/flysystem suggests installing league/flysystem-copy (Allows you to use Copy.com storage)
league/flysystem suggests installing league/flysystem-dropbox (Allows you to use Dropbox storage)
league/flysystem suggests installing league/flysystem-eventable-filesystem (Allows you to use EventableFilesystem)
league/flysystem suggests installing league/flysystem-rackspace (Allows you to use Rackspace Cloud Files)
league/flysystem suggests installing league/flysystem-sftp (Allows you to use SFTP server storage via phpseclib)
league/flysystem suggests installing league/flysystem-webdav (Allows you to use WebDAV storage)
league/flysystem suggests installing league/flysystem-ziparchive (Allows you to use ZipArchive adapter)
laravel/framework suggests installing league/flysystem-aws-s3-v3 (Required to use the Flysystem S3 driver (~1.0).)
laravel/framework suggests installing league/flysystem-rackspace (Required to use the Flysystem Rackspace driver (~1.0).)
laravel/framework suggests installing pda/pheanstalk (Required to use the beanstalk queue driver (~3.0).)
laravel/framework suggests installing predis/predis (Required to use the redis cache and queue drivers (~1.0).)
laravel/framework suggests installing pusher/pusher-php-server (Required to use the Pusher broadcast driver (~2.0).)
laravel/framework suggests installing symfony/psr-http-message-bridge (Required to psr7 bridging features (0.2.*).)
league/commonmark suggests installing league/commonmark-extras (Library of useful extensions including smart punctuation)
aws/aws-sdk-php suggests installing aws/aws-php-sns-message-validator (To validate incoming SNS notifications)
backup-manager/backup-manager suggests installing league/flysystem-aws-s3-v3 (AwsS3 and GoogleCS adapter support.)
backup-manager/backup-manager suggests installing league/flysystem-dropbox (Dropbox adapter support.)
backup-manager/backup-manager suggests installing league/flysystem-rackspace (Rackspace adapter support.)
backup-manager/backup-manager suggests installing league/flysystem-sftp (Sftp adapter support.)
rcrowe/twigbridge suggests installing laravelcollective/html (For bringing back html/form in Laravel 5.x)
rcrowe/twigbridge suggests installing twig/extensions (~1.0)
filp/whoops suggests installing whoops/soap (Formats errors as SOAP responses)
sebastian/global-state suggests installing ext-uopz (*)
phpunit/phpunit-mock-objects suggests installing ext-soap (*)
phpunit/php-code-coverage suggests installing ext-xdebug (>=2.2.1)
phpunit/phpunit suggests installing phpunit/php-invoker (~1.1)
Generating optimized autoload files
[arriej@bmwebcontrol status]# php artisan key:generate
PHP Parse error:  syntax error, unexpected '$value' (T_VARIABLE) in /var/www/vhosts/blockmadness.com/status/vendor/aws/aws-sdk-php/src/functions.php on line 36**

**Comment by jbrooksuk** [comment]
What version of PHP are you using?

**Comment by arriej** [comment]
7.0.19 https://status.blockmadness.com/test/php/test.html

**Comment by jbrooksuk** [comment]
@GrahamCampbell any idea?
