### ISSUE TITLE
Problem on setup

### ISSUE THREAD

**Issue by igramnet** [CachetHQ/Cachet#2557]
Hello. I installed the cachet on my Windows.
Now, I have this on page
![e69eca3ec7ede4a7d44b4430e3bdd4a0](https://cloud.githubusercontent.com/assets/15707768/26821914/d578ca76-4ab0-11e7-8baa-d24f9851821d.png)

Why did the images and styles not boot? There are no build folders on the server. What am I doing wrong? Version - 2.3.9

log
```
p_zhukovskiy@BY1-WL-107 c:\webserver\OpenServer\domains\site2.ru
> php artisan app:install
Clearing settings cache...
Settings cache cleared!
Backing up database...
Dumping database and uploading...

Successfully dumped mysql, compressed with gzip and store it to local at C:\webserver\OpenServer\domains\site2.ru\database\backups\2017-06-06 09.37.27
Backup completed!
Application key [base64:F10bcCsX72GOdPoXKqYZ0szinQiQtnR2Ge5cRvjr5uQ=] set successfully. Configuration cache cleared!
Configuration cached successfully!
Route cache cleared!
Routes cached successfully!
Copied Directory [\vendor\roumen\feed\src\views] To [\resources\views\vendor\feed]
Publishing complete for tag []!
Nothing to migrate.
Clearing cache...
Application cache cleared!
Cache cleared!
```

**Comment by igramnet** [comment]
Solved a problem. It turns out you need to start from the public folder. And the domain itself is tied to it.

**Comment by ConnorVG** [comment]
@igramnet this is covered in the installation guide – you need to proxy through `public/index.php` and have `public` as the docroot.

**Comment by yuhao-nyc** [comment]
Hi I have exactly same issue. Not sure whats wrong. What do yo you mean by " need to start from the public folder " @igramnet
