### ISSUE TITLE
y axis showing weird line text

### ISSUE THREAD

**Issue by si458** [CachetHQ/Cachet#2558]
![untitled](https://user-images.githubusercontent.com/765314/26845201-a0b33672-4aed-11e7-893c-bb7af40a5bbb.jpg)
Hi all,

im getting these weird graph after inserting a few metric points after 5 mins (1 every minute, so only 5 metrics in total)

any body have any ideas?

the values are only whole numbers, e.g: 567, 600, 400, 300

its ment to show load time in ms

**Comment by si458** [comment]
its ok, self fixed! I had decimal places set as 3 and not 0!

**Comment by jbrooksuk** [comment]
Whoops!
