### ISSUE TITLE
Getting a Status that doesn't look right

### ISSUE THREAD

**Issue by TheFonix** [CachetHQ/Cachet#2563]
Ive been messing around with the API and am trying to create a simple API `PUT` that will changed the status of a component using this:
```
curl -H "Content-Type: application/json;" -H "X-Cachet-Token:XXXXXXXXX" --request PUT --url https://status.XXXXXX.net/api/v1/components/1 --data '{"data":{"name":"","description":"","status":2,"order":-4,"group_id":1,"enabled":"true"}}'
```
But when i run this it changes the status of a component to `cachet.components.status.0` Ive seen some other people have this issue but i don't see any resolution

Thanks!

**Comment by jbrooksuk** [comment]
Your request isn't right, so the value is coming through as `null` which is resulting in `0`. We should fix this too.

Here is the request which does work:

```
curl -H "Content-Type: application/json;" -H "X-Cachet-Token:9yMHsdioQosnyVK4iCVR" --request PUT --url http://cachet.app/api/v1/components/1 --data '{"status":2}'
```

Notice how the `--data` flag isn't passing through an object with `data` (that's only from the response).

Are you aware that you're also updating the name of the component to an empty string?
