### ISSUE TITLE
External Incident ID: Store ID + allow API update with external id

### ISSUE THREAD

**Issue by dakoller** [CachetHQ/Cachet#2564]
Hi,

I have a scenario, where the incident information comes from a different system, which is the leading system for incidents. In this system every incidents has a unique ID.

To bring this together with the really nice Cachet UI, I'd like to ask for the following:
- allow to store an external ID in the Cachet incident data &
- provide an additional API method, which allows to update an incident, which is identified by this external ID.

(The other systems would not easily be able to find out about cachet incident ids)

Kind regards,

Daniel

**Comment by mm-manageit** [comment]
I agree, this could be very useful.

**Comment by jbrooksuk** [comment]
Yeah? Let's do it! 💪
