### ISSUE TITLE
Unable to update subscription for newly created components

### ISSUE THREAD

**Issue by gonzoinc** [CachetHQ/Cachet#2565]
Once you have subscribers set up and subscribed to a set of components, if you go and add new components to the system there seems to be no way to allow you to update anyones subscription status to subscribe them to the newly added components. Even the emails sent out have no sort of Manage preference links in them so it looks like there is no option to add subscribers to any newly created components which is a pretty major problem when your company is constantly creating new services that need to be monitored....

**Comment by jbrooksuk** [comment]
Good spot! @joecohens built the original subscribers system, what are your thoughts on this?

**Comment by adishorvs** [comment]
This still hasn't been fixed? I'm using version 2.4 and I cannot update the subscription.

**Comment by jbrooksuk** [comment]
This will be handled better within the new design :)

**Comment by jbrooksuk** [comment]
Replacing with https://github.com/CachetHQ/Cachet/issues/3102
