### ISSUE TITLE
Please optimize front end

### ISSUE THREAD

**Issue by btd** [CachetHQ/Cachet#2566]
Hello.

I am new user of cachet (we just deployed it - version 2.3.11 iirc). I noticed that cachet loads around 1MB of gzipped js and 100kb of css. I do not want to blame anyone but it looks strange to me. At slow 3g connection it takes 40s to load status page with 0 incidents.

Can i suggest few starting optimizations:
![default](https://user-images.githubusercontent.com/334851/26979343-1e29146e-4d37-11e7-9028-6c072a638add.png)
1. You do not need zxcvbn.js at status page - only for dashboard.
2. ionicons.ttf - you use only few icons from whole font - it makes sence to cut custom font (you can do e.g. there https://icomoon.io/app/)
3. in all.js it seems you are loading moment.js + some charting library. If charting disabled in dashboard do not need to load lib for this. Also do you really need whole moment js?
4. all.css the same comment about ionicons and it looks you are not using all this at status page, but most is for dashboard right?

**Comment by jbrooksuk** [comment]
Thanks for the in-depth analysis! I have some questions

1. What is `zxcvbn.js`?
2. We could absolutely roll our own font. I'd actually like to make our own font too, this would really be nice for branding etc.
3. Yeah, Chart.js could be loaded separately if enabled.
4. Ionicons are used on the status page, just not very much.

I'd love to see some external support in rectifying this :)

**Comment by btd** [comment]
> What is zxcvbn.js?

Interesting question =). I think this is https://github.com/dropbox/zxcvbn (by idea you should know what cachet uses)

> We could absolutely roll our own font. I'd actually like to make our own font too, this would really be nice for branding etc.

I do not mean whole font - but just cut from ionicons custom icon fonts. But even better (at least if you do not support IE <10) to use svg icons. It loads instantly and allow a lot better styling.

I would suggest you tool called [webpack](https://webpack.github.io/). It allows to split bundle to peaces, which loads automatically (with import or script+jsonp - this all hidden from eyes) when they needs.

**Comment by jbrooksuk** [comment]
> (by idea you should know what cachet uses)

Ah yeah, this was added by someone else a long time back. Easier said than done 😂 I can't remember everything for the OSS projects I use plus my job...

**Comment by iamjulians** [comment]
100kb of CSS is tiny. Even on the ionicons loading, removing some won't change anything noticeable and make it harder to use some icons in future.

**Comment by jbrooksuk** [comment]
Yeah, I agree with @iamjulians. We can definitely do _some_ optimisation, but Cachet is already pretty small - minus the few overheads you've pointed out.

**Comment by iamjulians** [comment]
Yep. Only thing I'd change is the charting loading, make it load if enabled 👍

**Comment by btd** [comment]
@jbrooksuk yep i agree with this points. My suggestion would be doing quickest of possible ways - just split js/css for 3 parts - status page, status page + chart, dashboard.
This is very easy to implement and does not require any complex changes.

**Comment by jbrooksuk** [comment]
Please feel free to pick this up :) I currently have a lot of things going on, so this may take me a while to get implemented otherwise.

**Comment by jbrooksuk** [comment]
I'm going to look at running the generated CSS through `purgecss` to remove the non-used code.

**Comment by jbrooksuk** [comment]
Done :)

As part of rewriting the frontend to use Vue and the Cachet API, this will become better.

**Comment by jbrooksuk** [comment]
Thank you for your input on Cachet 2.x. We are shifting our attention and resources to Cachet 3.x and will no longer be supporting the 2.x version. If your feedback or issue is relevant to the 3.x series, we encourage you to engage with the new branch.

For more information on the Cachet rebuild and our plans for 3.x, you can read the announcement [here](https://github.com/CachetHQ/Cachet/discussions/4342).

We appreciate your understanding and look forward to your contributions to the new version.
