### ISSUE TITLE
Incidents dashboard - Incidents are not clickable

### ISSUE THREAD

**Issue by gonzoinc** [CachetHQ/Cachet#2567]
When in the Admin dashboard -> Incidents, the listing of incidents there are not clickable to show the full incident history. So it is impossible to see the actual history timeline of the incident.

I made the following change locally to correct the issue. Unable to submit pull requests due to policies :(

Line 27 /resources/views/dashboards/incidents/index.blade.php

`<i class="{{ $incident->icon }}"></i> <a href="{{ cachet_route('incident', [$incident->id]) }}" target="_blank"><strong>{{ $incident->name }}</strong></a> <span class="badge badge-info">{{ trans_choice('dashboard.incidents.updates', $incident->updates->count()) }}</span>`

This allows you to access the full history view of the incident itself in a new tab.

**Comment by jbrooksuk** [comment]
Pushing a change for this 👍 

The only difference is that I'm not opening it into a new window.
