### ISSUE TITLE
Open vs Resolved incidents display

### ISSUE THREAD

**Issue by gonzoinc** [CachetHQ/Cachet#2569]
On the main dashboard page I was confused that  the overall status bar was showing "Some systems are experiencing issues" but all components where showing operational. Looking through the recent incidents they all seemed to have been resolved, until I pages back to the prior weeks and found one still opened. It's a bit confusing, especially for an end user to see bar showing problems but not really seeing any open issues right off the bat. 

I updated the dashboard to break out current incidents to past resolved incidents. This should correct any confusion on what is open and what is closed.

Again sorry for not being able to properly submit this.  Working on contributor policies right now with work.... :(

Update the original code to exclude open incidents and Add in code for the new current incidents.
Line 70  /app/Http/Controllers/StatusPageController.php

```
       $allIncidents = Incident::where('visible', '>=', (int) !Auth::check())->whereBetween('occurred_at', [
                                    $startDate->copy()->subDays($daysToShow)->format('Y-m-d').' 00:00:00',
                                    $startDate->format('Y-m-d').' 23:59:59',
                                ])
                                ->where('status','=',4)
                                ->orderBy('occurred_at', 'desc')
                                ->get()
                                ->groupBy(function (Incident $incident) {
                                    return app(DateFactory::class)->make($incident->occurred_at)->toDateString();
                                });
        
        $allActiveIncidents = Incident::where('status','!=',4)
                                ->orderBy('occurred_at', 'desc')
                                ->get()
                                ->groupBy(function (Incident $incident) {
                                            return app(DateFactory::class)
                                ->make($incident->occurred_at)->toDateString();
                                });;

```

line 109 add the following
```
->withAllActiveIncidents($allActiveIncidents)
```
Update the view 
//resources/views/partials/modules/timeline.blade.php just shift it down and add in the new code at the top.

```
<div class="section-timeline">
    <h1>{{ trans('cachet.incidents.current') }}</h1>
    @foreach($all_active_incidents as $date => $incidents)
    @include('partials.incidents', [compact($date), compact($incidents)])
    @endforeach
</div>

<hr size='80%' style='display:block;border-width:5px;border-color:grey'>
```
***Added the hr to break up the transition from current to past incidents.

Update your Lang file to include the new cachet.incidents.current. In my case it was the /resources/lang/en/cachet.php file  add in after line 30

```        
'current'      => 'Current Incidents',
```

**Comment by jbrooksuk** [comment]
When you say dashboard, do you mean the status page view?

**Comment by gonzoinc** [comment]
Yes the main status page view. Sorry we call it the dashboard...

The above code basically breaks out open and resolved status into two different sections as shown in the below screenshot. Makes it easier to find outstanding/unresolved issues.

![screen shot 2017-06-15 at 1 34 37 pm](https://user-images.githubusercontent.com/27728728/27194175-9ba7cb78-51cf-11e7-9fcc-7a6e0ab26312.png)

**Comment by jbrooksuk** [comment]
@gonzoinc any movement on contributing?

**Comment by jbrooksuk** [comment]
In the design that @thomasHolman did for us, the main status page view does this. I'm going to close this as it'll be implemented then.
