### ISSUE TITLE
Online static resource issue

### ISSUE THREAD

**Issue by Diaoji** [CachetHQ/Cachet#2574]
Cachet page stuck in local area network (block outside internet but dns is connect outside-network) ,  Chrome will show waitting 'cdnjs.cloudflare.com' or 'fonts.googleapis.com'

`cdnjs.cloudflare.com` show on `public/build/dist/js/all-b2c62d4294.js`
`fonts.googleapis.com` show on every page header

**Comment by jbrooksuk** [comment]
In v2.4 it's possible to turn off third-party dependencies. Main settings screen 👍 

> Enable Third Party Dependencies (Google Fonts, Trackers, etc...)
