### ISSUE TITLE
Scheduled maintenances not honoring date

### ISSUE THREAD

**Issue by oznorts** [CachetHQ/Cachet#2578]
When I add/update a scheduled maintenance for, for example, 2017-06-17 15:59, the date gets changed to 2017-06-16 17:00 when I save it. This happens for the end date as well, but that gets changed to 2017-06-17 17:00.

This is in the latest version of 2.4

**Comment by jbrooksuk** [comment]
I feel like I only just recently fixed a bug related to this 🤔
