### ISSUE TITLE
Scheduled Maintenance Updates

### ISSUE THREAD

**Issue by ozzy-simpson** [CachetHQ/Cachet#2580]
Scheduled maintenances should stay in the "Past Incidents" log after they've completed for posterity. They should also be able to be updated as regular incidents can.

Their should also be an option to automatically change the status of a scheduled maintenance automatically (i.e. if the start date has passed, it's in progress, but if the completed date has passed, it's completed).

**Comment by koendc** [comment]
Scheduled maintenances disappear from the status page from the moment the scheduled_at time is passed. They should remain visibible as 'planned/ongoing' as long as they have status "Upcoming" or "In Progress".

**Comment by jimmybrancaccio** [comment]
Ah yes, I knew this was a reason I had stopped using them. I scheduled one today, it had been so long that I couldn't remember why I stopped using them, but this is why. Thanks for bringing this up. 👍

**Comment by jbrooksuk** [comment]
This should change as part of the new design :)

**Comment by jimmybrancaccio** [comment]
Woop woop, thanks @jbrooksuk!

**Comment by jbrooksuk** [comment]
When we get there... :)

**Comment by WilliamDEdwards** [comment]
Is there any status update regarding this issue?

**Comment by jayze** [comment]
Any update on this topic?

**Comment by Pimorez** [comment]
Is this still on the roadmap? The maintenance feature would be greatly improved if they remain visible (or at least have the option to remain visible) after the end date.

**Comment by astrakid** [comment]
Would like to see this feature as well, maybe configurable.

**Comment by jbrooksuk** [comment]
Thank you for your input on Cachet 2.x. We are shifting our attention and resources to Cachet 3.x and will no longer be supporting the 2.x version. If your feedback or issue is relevant to the 3.x series, we encourage you to engage with the new branch.

For more information on the Cachet rebuild and our plans for 3.x, you can read the announcement [here](https://github.com/CachetHQ/Cachet/discussions/4342).

We appreciate your understanding and look forward to your contributions to the new version.
