### ISSUE TITLE
Unable to install - Settings not saving?

### ISSUE THREAD

**Issue by Daniel15** [CachetHQ/Cachet#2584]
Hi!

I'm trying to configure Cachet and am encountering difficulties. One thing missing from the docs at https://docs.cachethq.io/docs/installing-cachet is that the `.env` file needs to be writable by the web user. Once I `chown`ed it to the correct user, I could go through the entire setup process and got to the dashboard with no issues. However, hitting the root directory redirects to the setup flow again (even though I've already completed it), and going to the settings section of the dashboard shows required fields like site URL and name as being empty. Even if I enter something into those fields and click save, the changes do not persist.

I'm using PHP 7 on Debian, and MySQL.

**Comment by jbrooksuk** [comment]
Is your `./bootstrap` directory writable?

**Comment by Daniel15** [comment]
@jbrooksuk - I think that was the issue. I ended up deleting the directory and starting from scratch. This time I `chown`ed everything to `www-data` and it worked fine, so I suspect it was a file ownership issue.

The strange thing is that Cachet was not throwing any errors, nor did the log file (`storage/logs/laravel-2017-06-20.log`) contain any useful information. It simply failed to work properly.

**Comment by jbrooksuk** [comment]
That's a bit weird. Usually Laravel is really good at catching all errors and logging them. If it was permission based, then perhaps it couldn't write the log either? Who knows!?

Glad you're sorted!
