### ISSUE TITLE
Get good/bad status via API?

### ISSUE THREAD

**Issue by Daniel15** [CachetHQ/Cachet#2585]
Is there a simple API to get the good ("All systems are operational") / bad ("Some systems are experiencing issues") / severe ("Some systems are experiencing major issues") status? `/api/v1/incidents` returns all incidents even if they're closed.

**Comment by Daniel15** [comment]
Looks like this was added in #1936 which has not been released yet :(

**Comment by jbrooksuk** [comment]
Yeah :) https://dev.cachethq.io/api/v1/status

**Comment by Daniel15** [comment]
@jbrooksuk - Is there an ETA for getting this into a released version of Cachet? Could it be backported to 2.3?

**Comment by jbrooksuk** [comment]
2.4 is a long way off I imagine.

I could look at back porting it, yeah.

**Comment by Daniel15** [comment]
Is the current dev version of 2.4 stable enough to run in production? Or are there known issues with it?

**Comment by Daniel15** [comment]
fdfebc18fb580b9009a58fbdf3fd1c5f48f58c8e and 883fdb56dcc87023f926b058652dce9d129a6d14 apply cleanly on top of 2.3.9 so I just cherry picked them into my fork. 👍

**Comment by jbrooksuk** [comment]
Would you mind a PR to 2.3 with these? :)

**Comment by Daniel15** [comment]
Good idea! Done: #2601
