### ISSUE TITLE
Incident Times Broken

### ISSUE THREAD

**Issue by iamjulians** [CachetHQ/Cachet#2589]
Running 2.4 branches code is mostly working, however I have noticed a strange bug when selecting date/time for Incident start (on incident edit/create screen). 

This happens both when not entering a date (which means it uses the current date) and when entering any custom date - the year (2017) and month (2017-07) work, but when entering the *time* and submitting, the hour of the time (e.g. 21) becomes the *date* (so in this case 2017-07-21), and the minute of the time is disregarded, the time becoming 08:00. 

^ Thats a little confusing, but in that example, the date, even if I enter `2017-07-20 21:00` would become `2017-07-21 08:00`.

I can provide screenshots etc. if needed, or more explanations, just tell me!

**Comment by AdenFraser** [comment]
Running into the same issue on initial setup of 2.4 tag.

Will investigate tonight, fork and hopefully push up a PR — as this is currently preventing us from putting Cachet into prod.
