### ISSUE TITLE
Forms contain http links instead of https

### ISSUE THREAD

**Issue by mapete94** [CachetHQ/Cachet#2590]
I had setup cachet on one of our servers and forced ssl via nginx as well as setting the https url in the env file. However links within forms and a handful of assets are still retrieved over http. This causes the application to 405 whenever I try and use a form. Any thoughts on how to fix this? The application is not being proxied.

It specifically seems tied to anything returned by the cachet_route() function. I'm looking into it further to try and determine what the behavior is.

**Comment by jbrooksuk** [comment]
I believe this is the same issue as https://github.com/CachetHQ/Cachet/issues/2522 please re-open if you don't feel that it is.

**Comment by mapete94** [comment]
Forcing the URL scheme results in the site working as expected. Curious why the environment file seems to be ignored in getting the url for those links though.

**Comment by jbrooksuk** [comment]
This is due to the trusted proxies package.
