### ISSUE TITLE
Subscribe to components group

### ISSUE THREAD

**Issue by igramnet** [CachetHQ/Cachet#2591]
Hello. Now user can subscribe to each components.
How do I get users to subscribe to group component notifications?

**Comment by jbrooksuk** [comment]
You can't currently, we only allow notifications per-component. @joecohens we should probably add this though.

**Comment by jbrooksuk** [comment]
Thank you for your input on Cachet 2.x. We are shifting our attention and resources to Cachet 3.x and will no longer be supporting the 2.x version. If your feedback or issue is relevant to the 3.x series, we encourage you to engage with the new branch.

For more information on the Cachet rebuild and our plans for 3.x, you can read the announcement [here](https://github.com/CachetHQ/Cachet/discussions/4342).

We appreciate your understanding and look forward to your contributions to the new version.
