### ISSUE TITLE
API returns could not be relevant

### ISSUE THREAD

**Issue by qk4l** [CachetHQ/Cachet#2598]
Hi,

I noticed that some API methods could return non relevant information because of delay.

Example case:
1. Create a component via API (POST components)
2. Get info about new created component (GET components)

If you do GET just after POST you do not found info about the component.
In my environment it takes about 30 seconds before GET returns become relevant.

Same for deleting components via dashboard.
I guess that it could be with methods.

Cachet version - 2.3.11

**Comment by jbrooksuk** [comment]
I cannot confirm this bug, sorry. I tried a freshly seeded version of Cachet (with `php artisan cachet:seed`).

```
## Cachet — Create Component
curl -X "POST" "http://cachet.app/api/v1/components" \
     -H "X-Cachet-Token: 9yMHsdioQosnyVK4iCVR" \
     -H "Content-Type: application/json; charset=utf-8" \
     -d $'{
  "status": 1,
  "enabled": true,
  "name": "Test",
  "description": "Lorem ipsum dolor"
}'
```

Where the newly created component has an ID of 7:

```
## Cachet — Get Component
curl "http://cachet.app/api/v1/components/7" \
     -H "X-Cachet-Token: 9yMHsdioQosnyVK4iCVR"
```

Both worked.

We don't queue the creation of components, so it doesn't make sense for it to be delayed. Perhaps you have a slow database connection? If the POST API returns, then that component has been created.

**Comment by qk4l** [comment]
@jbrooksuk , thanks for fast response.

I investigated it more closely and found that a problem definitely exist at least in my installation.
I always have ~30 second delay via API but see changes via WEB interfaces _immediately_.
And yes I've not reproduced it on Cachet demo site.

May be it's fastcgi_cache...

I don't think that it's my personal problem because I use _cachet-docker_ and other users can get same problems.

Here is a small  python [test script ](https://gist.github.com/qk4l/fe7024874d322d785beb5c6020a39193) with my results in comments.

Could anybody try to run it on Cachet which run via [this](https://github.com/CachetHQ/Docker/blob/master/docker-compose.yml) docker-compose file.

**Comment by jbrooksuk** [comment]
Very weird! It _must_ be a setup issue, but it's an odd one! Sorry I can't be of more use 😞
