### ISSUE TITLE
[Support] Installation on ServerPilot

### ISSUE THREAD

**Issue by D14RAP** [CachetHQ/Cachet#2599]
So far I have followed the installation instructions to the letter however when getting to the apache/nginx section in unsure what todo because I'm running server pilot which uses non normal server paths. Also which going to the /public directly currently there is no styling and also the pages JS doesn't function, is this normal and does the site require the VirtualHost things to work correctly. Anyone who can assist would be much appreciated!

**Comment by jbrooksuk** [comment]
I wonder if the very nice @jstnsml could chip in here?

**Comment by senseiner** [comment]
Hey! @D14RAP 
I had the same problem. The way I've made it work on Serverpilot is with .htaccess to redirect the domain to the subdirectory /Cachet/public/ 

I followed the installation instructions (logged as a serverpilot user to avoid issues with permissions). Once the installation is done, just create the .htaccess file in the app public folder "serverpilot/apps/cachet/public"

```RewriteEngine on
RewriteCond %{HTTP_HOST} ^foo.domain.com$ [NC,OR]
RewriteCond %{HTTP_HOST} ^www.foo.domain.com$
RewriteCond %{REQUEST_URI} !Cachet/public/
RewriteRule (.*) /Cachet/public/$1 [L]
```

Go to the domain and you should see the Setup Wizard.

Hope this helps.

Cheers!
