### ISSUE TITLE
Can't remove completed at on scheduled maintenances

### ISSUE THREAD

**Issue by oznorts** [CachetHQ/Cachet#2600]
If I try to remove the value of the `completed_at` field when updating a scheduled maintenance, when I save it it goes back to the old value. I can change the value to something new, as long as it's not empty.

**Comment by gonzoinc** [comment]
Known bug - https://github.com/CachetHQ/Cachet/issues/2509

**Comment by jbrooksuk** [comment]
Closing as dupe.
