### ISSUE TITLE
Integrate seedfile-mechanism for auto-deploy in pipelines

### ISSUE THREAD

**Issue by LarsKumbier** [CachetHQ/Cachet#2602]
In order to have a fully integrated CI/CD-pipeline, we would like to be able to present a seed-file or -command for the customizations like adding components, groups, etc. on the first run.

With the current state, it is not possible to automatically deploy everything from scratch without manual intervention or some really hacky deployment code filling the database directly (and not being future proof) or by simulating API queries.

(was https://github.com/CachetHQ/Docker/issues/212)

**Comment by jbrooksuk** [comment]
Technically... we do have a [seed file](https://github.com/CachetHQ/Cachet/blob/2.4/app/Console/Commands/DemoSeederCommand.php).

I'd like to know how you'd want to implement this though. What are your thoughts?

**Comment by LarsKumbier** [comment]
Maybe I'm unclear on the possibilities of the seedfile, but from what I saw, it is used *after* the setup of database connection, etc. I am unaware, if this file can be used to also provide the initial setup.

Wording: 
* a *setup* is what needs to be done to get cachet running at all (the first four pages where you setup database connectivity, smtp server, etc), 
* a *customization* is all configuration happening after that (adding components, component groups, etc. - everything in the "admin"-link)

Goal: As a devops guy, I'd like to be able to automatically deploy and customize a cachet docker container and redeploy the state cachet had at any time after the initial deploy. This includes a changed environment / cluster, e.g. with a different database connection.

Implementation:
I would like to have a seed-file in yaml or json to be mounted into the docker container. The seed-file has two parts: *config* and *customization*:

```
{
  "config": {
    "db_host": "xxx://yyy:12345/zzz",
    "title": "My Cachet installation",
    // ...
  },
  "customization": {
    "components": [
      {
        "name": "git",
        "description": "https+git connectivity to our SCM server",
        "group": "environment"
      },
      {
        "name": "jabber",
        "description": "external connectivity of our jabber server",
        "group": "environment"
      },
      {
        "name": "customer-api",
        "description": "REST-API for our customers",
        "group": "frontend"
      },
      {
        "name": "customer-ui",
        "description": "The webapp for our customers",
        "group": "frontend"
      }
    ]
  },
  // ...
}
```

I am unsure about how the config-part is currently handled, but it would work the same as with the seeder-implementation: Give it the config-file and add all the configured points in the file.

Is it clearer now?

**Comment by jbrooksuk** [comment]
Is this specifically related to Docker?

**Comment by LarsKumbier** [comment]
@jbrooksuk yes and no - more specifically, it is important for *any* automated setup, no matter what technology is used to achieve this.

**Comment by LarsKumbier** [comment]
Just because something doesn't have any activity doesn't mean that it should be closed.
Good features, which do not have a priority at the moment can still be revisited later on.
