### ISSUE TITLE
Cachet not sending emails

### ISSUE THREAD

**Issue by c0ri** [CachetHQ/Cachet#2603]
I'm having some issues getting Cachet to send emails.

After digging through the logs I saw this:
```
[2017-06-26 21:24:49] production.ERROR: exception 'Swift_TransportException' with message 'Connection could not be established with host my_server.com [Unable to find the socket transport "none" - did you forget to enable it when you configured PHP? #8]' in /var/www/Cachet/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Transport/StreamBuffer.php:269

#0 /var/www/Cachet/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Transport/StreamBuffer.php(62): Swift_Transport_StreamBuffer->_establishSocketConnection()
#1 /var/www/Cachet/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Transport/AbstractSmtpTransport.php(113): Swift_Transport_StreamBuffer->initialize(Array)
#2 /var/www/Cachet/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Mailer.php(79): Swift_Transport_AbstractSmtpTransport->start()
```
Checking the Swiftmail docs seems to indicate you need PHP 7.0+ in order to run that and I'm on 5.6.27, but I digress..

```
Here's my config:
MAIL_DRIVER=smtp
MAIL_HOST=my_server.com
MAIL_PORT=25
MAIL_USERNAME=null
MAIL_PASSWORD=null
MAIL_ADDRESS=me@my_server.com
MAIL_NAME="Cachet Admin"
MAIL_ENCRYPTION=none
```

I'm running supervisord. BTW: Supervisored doesn't work with the suggested config. You need to use this:
```
[program:cachet-queue]
command=/usr/bin/php /var/www/Cachet/artisan queue:work --delay=2 --sleep=2 --tries=3
directory=/var/www/Cachet/
redirect_stderr=true
autostart=true
autorestart=true
user=cachet
```
I'm running the latest release tag V2.3.9.

Isn't there some way to set this thing to use mailx or sendmail or something?

Thanks!

**Comment by gonzoinc** [comment]
I have mine set up with sendmail in the .env file just using:

`MAIL_DRIVER=sendmail`

along with MAIL_ADDRESS and MAIL_NAME

as for supervisord, we're using the following settings and it's working well in our Env:

`[program:cachet-queue]
command=/usr/bin/php56 artisan queue:work --daemon --delay=2 --sleep=1 --tries=3
numprocs=1
directory=./
redirect_stderr=true
autostart=true
autorestart=true
user=cachet
stdout_logfile=./log/cachet_worker.log
stdout_logfile_maxbytes=50MB
stderr_logfile=./log/cachet_worker_error.log
stderr_logfile_maxbytes=50MB
stopsignal=INT`

**Comment by c0ri** [comment]
@gonzoinc Thanks Greg, that fixed er :)  👍

**Comment by jbrooksuk** [comment]
Thanks @gonzoinc!
