### ISSUE TITLE
Disable notification on create or update components

### ISSUE THREAD

**Issue by igramnet** [CachetHQ/Cachet#2605]
Hello.
[https://github.com/CachetHQ/Cachet/issues/2592](Close issue)

I do not agree with the closure of the ticket. I just want to disable notifications when adding and updating components. Now I had to find the file \ resources \ app \ Foundation \ Providers \ EventServiceProvider.php and delete the line

`        'CachetHQ\Cachet\Bus\Events\Component\ComponentWasUpdatedEvent' => [
            'CachetHQ\Cachet\Bus\Handlers\Events\Component\SendComponentUpdateEmailNotificationHandler',
        ],
`

This solution is not correct.

**Comment by jbrooksuk** [comment]
No problem! I'd like to see a PR which prevents notifications. Needs a checkbox of some kind. Would you like to contribute it?

**Comment by igramnet** [comment]
Yes, I need a checkbox. Those. Globally configure multiple options
1. Send notification when updating component (subscribers)
2. Sending notifications when adding a component (subscribers)

Here's what I found.
The subscriber unsubscribed from the component. Then the administrator started the mailing (incident), specifying this component. The newsletter still came to this subscriber. It's somehow illogical, is not it?

**Comment by jbrooksuk** [comment]
If the subscriber unsubscribed from the component but were still mailed, were the subscribed globally?

**Comment by d-core** [comment]
Hi,

I would like to join the discussion. If I’m correct, this requests fits our needs. We also want to disable the mail notification if we change the component status on the dashboard. The notification, if we create incident or scheduled maintenance, should remain. So un-subscription is not the solution.

Regards

**Comment by igramnet** [comment]
Yes, I meant it.

**Comment by jbrooksuk** [comment]
@d-core 2.4 will no longer notify when making simple changes from the dashboard homepage.

**Comment by jbrooksuk** [comment]
Grouping this issue into https://github.com/CachetHQ/Cachet/issues/2508
