### ISSUE TITLE
Error "File css/all.css not defined in asset manifest" on Heroku

### ISSUE THREAD

**Issue by SamuelMoraesF** [cachethq/Cachet#261]
When I deploy to heroku, [some errors are retorned](http://pastebin.mozillabrasil.org.br/vocogotawe.coffee), and the home page return:

```File css/all.css not defined in asset manifest. (View: /app/app/views/layout/master.blade.php) (View: /app/app/views/layout/master.blade.php)```

**Comment by GrahamCampbell** [comment]
Yeh, you need to now run gulp on heroku after the latest changes.

**Comment by GrahamCampbell** [comment]
```
bower install
npm install
gulp
```

**Comment by SamuelMoraesF** [comment]
I runned these commands, none error has returned, but when access the
page the same error is returned:

http://status.mozillabrasil.org.br/

**Comment by GrahamCampbell** [comment]
One sec.

**Comment by GrahamCampbell** [comment]
Try now with my latest changes. Just run it how you used to do it.

**Comment by SamuelMoraesF** [comment]
The push is rejected because bower is not installed:

```Error Output: sh: 1: bower: not found```

**Comment by GrahamCampbell** [comment]
I'll revert all the changes for now...

**Comment by GrahamCampbell** [comment]
Reverted.
