### ISSUE TITLE
Following Docs can break installation

### ISSUE THREAD

**Issue by tmfksoft** [CachetHQ/Cachet#2611]
When following the documentation at https://docs.cachethq.io/docs/github-oauth-token
You may end up with a broken installation.

I installed Cachet and enabled redis in the configuration, the setup ran absolutely fine.
I edited .env to add the GitHub Token and ran the suggested command `php artisan config:cache`

The install of Cachet decided to die, after tracking down the logs it appeared to be a complete lack of the predis package.

I had to Google the issue and stumbled across this issue:
https://github.com/CachetHQ/Cachet/issues/785

I had to resolve the issue by adding predis to the composer config and running `composer install`

Would be really helpful if either:
- predis was included from the get go
- Config/Setup phase didnt mention predis or had a notice about having to add it manually.
- Installation documentation mentioned installing predis.

It'd also be +1 to use defaults for Redis, redis rarely changes from system to system on a simple setup. Just like MySQL its details are pretty predictable in terms of the host and port.

**Comment by jbrooksuk** [comment]
What version of Cachet were you installing? Predis is required on the 2.4 branch https://github.com/CachetHQ/Cachet/blob/3ad23828ba3a47f621f1d2e9f431887ff8735e5b/composer.json#L52, so I assume it'll be 2.3

@GrahamCampbell how come we didn't do this?

**Comment by tmfksoft** [comment]
Ah, I installed 2.3.9, I were unaware of 2.4 being a thing. Would really be worth it making it into the documentation, at least as a warning

**Comment by jbrooksuk** [comment]
I think it should be in 2.3 to be honest. Incoming!
