### ISSUE TITLE
Cachet shows problems although all components are ok

### ISSUE THREAD

**Issue by MDXDave** [CachetHQ/Cachet#2612]
No entry in log file referring to this issue.
Any idea how to fix this?

link to cachet instance: https://status.nevoxo.com/

**Comment by jbrooksuk** [comment]
This is because you have an unresolved incident. https://status.nevoxo.com/incident/387

We've been discussing whether this is a good idea or not in https://github.com/CachetHQ/Cachet/pull/2515

**Comment by MDXDave** [comment]
Thanks for your help.
