### ISSUE TITLE
Add an option to notify subscribers when scheduled maintenance date changes

### ISSUE THREAD

**Issue by ferjaninasraoui** [CachetHQ/Cachet#2613]
is there an option to notify subscribers when scheduled maintenance date changes. if not can this be added.

Cachet v2.3.11

**Comment by jbrooksuk** [comment]
There isn't, but we could notify of updates when something has changed.

**Comment by jbrooksuk** [comment]
Basically, any maintenance, incident or component edit should have a "Notify subscribers?" option which can be disabled.

**Comment by ferjaninasraoui** [comment]
hi @jbrooksuk ,

thanks or considering adding this , but i don't see the "Notify subscribers?" when i try to edit the scheduled maintenance

**Comment by jbrooksuk** [comment]
I see.

**Comment by jbrooksuk** [comment]
This won't make it into 2.3 but should be part of 2.4

We have an event for `ScheduleWasUpdatedEvent` but we don't have a handler to notify with anything.

**Comment by AchoArnold** [comment]
@jbrooksuk  Is this ready to be picked up?

**Comment by grant-veepshosting** [comment]
We are currently using branch v2.4-dev and cannot yet see emails to subscribers for Scheduled Maintenance. Any updates on this request, or if it exists - link to documentation or advice on how to implement?

**Comment by jbrooksuk** [comment]
Thank you for your input on Cachet 2.x. We are shifting our attention and resources to Cachet 3.x and will no longer be supporting the 2.x version. If your feedback or issue is relevant to the 3.x series, we encourage you to engage with the new branch.

For more information on the Cachet rebuild and our plans for 3.x, you can read the announcement [here](https://github.com/CachetHQ/Cachet/discussions/4342).

We appreciate your understanding and look forward to your contributions to the new version.
