### ISSUE TITLE
API request results in HTTP 406 - Not Acceptable

### ISSUE THREAD

**Issue by ronindesign** [CachetHQ/Cachet#2614]
In the documentation, there is a curl example for adding a component that results in a HTTP 406 error.
Documentation: https://docs.cachethq.io/docs/api-authentication

The curl command:
`$ curl -H "Content-Type: application/json;" -H "X-Cachet-Token: YOUR_KEY_HERE" -d '{"name":"API","description":"An example description","status":1}' http://status.cachethq.io/api/v1/components`

Results in the following error when using terminal:
> Error 406 - Not Acceptable
> 
> Generally a 406 error is caused because a request has been blocked by Mod Security. If you believe that your request has been blocked by mistake please contact the web site owner.

The solution for me was to simply add a user agent to the curl request, as so:
`$ curl -H "Content-Type: application/json;" -H "X-Cachet-Token: YOUR_KEY_HERE" -d '{"name":"API","description":"An example description","status":1}' http://status.cachethq.io/api/v1/components -A "Mozilla"`

This may not necessarily be a bug, but rather simply a difference of configuration, etc.
However, it did cause a hiccup when walking through the documentation.
I've submitted a documentation change already to include additional info regarding this exception, so hopefully it will help others in the future.

If the documentation addition is an acceptable fix for this issue, please feel free to close this. I just wanted to throw notice of this.

This issue (and solution) was reproduced in the following environments:
Mac - Terminal - curl 7.43.0 (x86_64-apple-darwin15.0) libcurl/7.43.0
Linux - Terminal - curl 7.51.0 (x86_64-redhat-linux-gnu) libcurl/7.51.0
Linux - Terminal - curl 7.19.7 (x86_64-redhat-linux-gnu) libcurl/7.19.7

**Comment by jbrooksuk** [comment]
This isn't a Cachet thing, it's your Apache setup. Specifically, Mod Security (as it says in the error). You need to look into your configuration for that 😃

**Comment by ronindesign** [comment]
I'm not using Mod Security.

**Comment by ronindesign** [comment]
Verbatim:

In terminal I enter exactly (anonymized):
```
curl -H "Content-Type: application/json;" -H "Accept: application/json" -H "X-Cachet-Token: MY_TOKEN_KEY" -d '{"name":"API","description":"An example description","status":1}' http://status.my.server/api/v1/components
```

The exact response I get is:
```html
<html><head><title>Error 406 - Not Acceptable</title><head><body><h1>Error 406 - Not Acceptable</h1><p>Generally a 406 error is caused because a request has been blocked by Mod Security. If you believe that your request has been blocked by mistake please contact the web site owner.</p></body></html>
```

Conversely, when I enter:
```
curl -H "Content-Type: application/json;" -H "Accept: application/json" -H "X-Cachet-Token: MY_TOKEN_KEY" -d '{"name":"API","description":"An example description","status":1}' http://status.my.server/api/v1/components -A "Mozilla"
```

I get:
```json
{"data":{"order":0,"group_id":0,"description":"An example description","link":"","enabled":true,"name":"API","status":1,"updated_at":"2017-07-01 03:53:12","created_at":"2017-07-01 03:53:12","id":5,"status_name":"Operational","tags":[]}}
```

**Comment by GrahamCampbell** [comment]
Yeh, this is definitely not coming from cachet. Our errors never look like that response body.

**Comment by ronindesign** [comment]
Ok, thanks for the follow-up.
I am running Apache, and it makes sense that it is server related, being an HTTP error.

My point in opening this issue is not that it is a bug in cachet, but rather more of an issue with documentation.
My use case (seems) to be a typical Apache install, as supported according to the doc's requirements page, yet I'm unable to run the example commands without additional parameters, config, etc.

It very well could be due to additional configuration, so I will look into that, but it should just be a normal, default install of Apache. I didn't manually install / setup Mod Security.

I guess if I'm an outlier than there is no need to add note to docs, but I assumed others would face this issue as my environment is pretty much vanilla. Sorry if I wasted time / energy on this, if I'm mistaken!

Thanks again!

**Comment by ronindesign** [comment]
Yeah, I've confirmed, it's definitely something to do with the Apache configuration.
