### ISSUE TITLE
Internal Server Error 500

### ISSUE THREAD

**Issue by palnati81** [CachetHQ/Cachet#2615]
Internal Server Error

What does this mean?

Something went wrong on our servers while we were processing your request. An error has occurred and this resource cannot be displayed. This occurrence has been logged, and a highly trained team of monkeys has been dispatched to deal with your problem. We're really sorry about this, and will work hard to get this resolved as soon as possible.

This error can be identified by cc5f3b28-2e49-4ef9-ac83-586b5ca5b019. You might want to take a note of this code.

Perhaps you would like to go to our home page?

**Comment by palnati81** [comment]
[laravel-2017-07-01.zip](https://github.com/CachetHQ/Cachet/files/1117165/laravel-2017-07-01.zip)

**Comment by GrahamCampbell** [comment]
You have not run the install command. Please follow the installation instructions.

**Comment by palnati81** [comment]
Can you please guide me further?

**Comment by palnati81** [comment]
$ php artisan app:install
Copied Directory [\vendor\roumen\feed\src\views] To [\resources\views\vendor\fee
d]
Publishing complete for tag []!
Nothing to migrate.
Clearing cache...
Application cache cleared!
Cache cleared!

**Comment by GrahamCampbell** [comment]
Did you create a `.env` file as listed in the documentation?

**Comment by palnati81** [comment]
APP_ENV=production
APP_DEBUG=false
APP_URL=http://localhost
APP_KEY=base64:mvtuY8QH/+UTQBaOBt0fAKYMdAkDHSC6uJcB/TV/o+Q=

DB_CONNECTION=sqlite
DB_DATABASE=C:\cp\Cachet\database\database.sqlite

CACHE_DRIVER=file
SESSION_DRIVER=file
QUEUE_DRIVER=sync
CACHET_EMOJI=false

MAIL_DRIVER=smtp
MAIL_HOST=mailtrap.io
MAIL_PORT=2525
MAIL_USERNAME=null
MAIL_PASSWORD=null
MAIL_ADDRESS=null
MAIL_NAME=null
MAIL_ENCRYPTION=tls

REDIS_HOST=null
REDIS_DATABASE=null
REDIS_PORT=null

GITHUB_TOKEN=null

**Comment by GrahamCampbell** [comment]
Is that `.env` or `.env.example`? Please restart the server, and provide us with fresh logs from the most recent crash.

**Comment by palnati81** [comment]
It is .env file.
[laravel-2017-07-01.zip](https://github.com/CachetHQ/Cachet/files/1117186/laravel-2017-07-01.zip)

**Comment by GrahamCampbell** [comment]
The error remains the same:

> No supported encrypter found. The cipher and / or key length are invalid.

This is not a Cachet bug, but a server configuration bug. Did the composer install succeed? What exact command did you run?

**Comment by palnati81** [comment]
Yes, The composer installed Successfully. 

composer install --no-dev -o --no-scripts   -->cmd used

**Comment by GrahamCampbell** [comment]
Running with no-scripts will be the problem.

**Comment by palnati81** [comment]
Do you want me to re-install?

**Comment by jemestica** [comment]
I had cachet up and running fine, but without the subscription button -yes the check to allow subs was checked- but I read somewhere here that running command artisan config:clear will fix the button problem but didn't and now I can't go to th dashboard!!

#14 /var/www/Cachet/vendor/graham-campbell/core/src/Console/Commands/AppUpdate.php(67): Illuminate\Events\Dispatcher$
#15 [internal function]: GrahamCampbell\Core\Console\Commands\AppUpdate->handle()
#16 /var/www/Cachet/vendor/laravel/framework/src/Illuminate/Container/Container.php(507): call_user_func_array(Array$
#17 /var/www/Cachet/vendor/laravel/framework/src/Illuminate/Console/Command.php(169): Illuminate\Container\Container$
#18 /var/www/Cachet/vendor/symfony/console/Command/Command.php(256): Illuminate\Console\Command->execute(Object(Symf$
#19 /var/www/Cachet/vendor/laravel/framework/src/Illuminate/Console/Command.php(155): Symfony\Component\Console\Comm$
#20 /var/www/Cachet/vendor/symfony/console/Application.php(794): Illuminate\Console\Command->run(Object(Symfony\Comp$
#21 /var/www/Cachet/vendor/symfony/console/Application.php(186): Symfony\Component\Console\Application->doRunCommand$
#22 /var/www/Cachet/vendor/symfony/console/Application.php(117): Symfony\Component\Console\Application->doRun(Object$
#23 /var/www/Cachet/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(107): Symfony\Component\Co$
#24 /var/www/Cachet/artisan(35): Illuminate\Foundation\Console\Kernel->handle(Object(Symfony\Component\Console\Input$
#25 {main} {"identification":{"id":"0ead8343-579c-4e21-9fee-177dd37a498e"}}

**Comment by GrahamCampbell** [comment]
Please post the whole stack trace. The last 12 lines are no use I'm afraid.

**Comment by jemestica** [comment]
@GrahamCampbell  sorry.
I installed again and now working fine. But still no Subscribe button. I configured the mail and supervisor but still no subscribe button. Thanks

**Comment by jemestica** [comment]
@GrahamCampbell the version is 2.3.12 but same happens with 2.3.9, NO subscribe button

**Comment by GrahamCampbell** [comment]
Subscribe will not show if mail is incorrectly configured, or if subscriptions are not enabled in the settings.

**Comment by jemestica** [comment]
I know but I have configured smtp (for google gsuite) and tried server using mail from command and it works, but not for cachet.

MAIL_DRIVER=smtp
MAIL_HOST=smtp.gmail.com
MAIL_PORT=465
MAIL_USERNAME=julio@   <-here my email
MAIL_PASSWORD= ****** <-here my pasword
MAIL_ADDRESS= <-here email address
MAIL_NAME=estado
MAIL_ENCRYPTION=ssl

also tested send email from server and worked fine. 
mail -s "Test Subject" julio@myemail.com < /dev/null

**Comment by GrahamCampbell** [comment]
Have you run `php artisan app:update', and enabled subscriptions in the in-browser cachet settings?

**Comment by jemestica** [comment]
Great!! php artisan app:update worked for me! Thank you!!!!

**Comment by palnati81** [comment]
php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
php -r "if (hash_file('SHA384', 'composer-setup.php') === '669656bab3166a7aff8a7506b8cb2d1c292f042046c5a994c43155c0be6190fa0355160742ab2e1c88d40d5be660b410') { echo 'Installer verified'; } else { echo 'Installer corrupt'; unlink('composer-setup.php'); } echo PHP_EOL;"
php composer-setup.php
php -r "unlink('composer-setup.php');"

resolved the issue
