### ISSUE TITLE
Internal Server Error 500 #2615

### ISSUE THREAD

**Issue by palnati81** [CachetHQ/Cachet#2616]
AP+vemulapalli.gv@wh-fw-srv-446 MINGW64 /c/cp/cachet ((v2.2.4))
$ php artisan app:install
Copied Directory [\vendor\roumen\feed\src\views] To [\resources\views\vendor\fee
d]
Publishing complete for tag []!
Nothing to migrate.
Clearing cache...
Application cache cleared!
Cache cleared!

**Comment by GrahamCampbell** [comment]
Duplicate.
