### ISSUE TITLE
Metric loading takes long time

### ISSUE THREAD

**Issue by irfanops** [CachetHQ/Cachet#2617]
Hi,

I have a ping metric displaying on my dashboard. Initially when I setup Cachet, the metric loads fine. As days pass, there is a delay in loading the graph and it keeps increasing. Sometimes it could take upto a minute. I am using cachet-service to ping the site and update the metric. Attached a gif video for reference.

Please advice!

![graph](https://user-images.githubusercontent.com/22214163/27808466-a24ac8e6-6065-11e7-8a80-f7a9482c04bb.gif)

**Comment by irfanops** [comment]
Regarding my setup: I am using Apache, MySQL and only one metric(ping response time). I also tried sqlite, MariaDB but they all give the same result.

Jake's [comment](https://github.com/CachetHQ/Cachet/issues/1488#issuecomment-183506822) explains it well too. Wonder if I can create any cron jobs to clean old metric points as per  @GrahamCampbell comment on [#1488](https://github.com/CachetHQ/Cachet/issues/1488)

**Comment by irfanops** [comment]
Any temporary workarounds? Like setting up cronjobs etc....

**Comment by jbrooksuk** [comment]
@irfanops how many points are you storing?

**Comment by jbrooksuk** [comment]
Also, are you using 2.4?

**Comment by irfanops** [comment]
Well, the cachet-monitor polls 24x7. Have plans to use multiple metrics but limited by this issue. I am using the stable version - v2.3.11.

**Comment by jbrooksuk** [comment]
Would there be any chance you could send me a dump your `metrics` and `metric_points` tables?

**Comment by jbrooksuk** [comment]
I'd like to check the situation in v2.4

**Comment by irfanops** [comment]
Will give it a shot... It will take a month though because things start normally but get slow when days pass by...

**Comment by jbrooksuk** [comment]
That's no problem! Let's see what we can do to improve it.

**Comment by irfanops** [comment]
I have attached the dumps of **metrics** and **metric_points** tables
[mysqldump.sql.zip](https://github.com/CachetHQ/Cachet/files/1154001/mysqldump.sql.zip)

**Comment by jbrooksuk** [comment]
Looks to load quite well in 2.4 to be honest!

**Comment by jbrooksuk** [comment]
This has been improved in 2.4 :)
