### ISSUE TITLE
FR: Ability to edit incident updates

### ISSUE THREAD

**Issue by myH2Oservers** [CachetHQ/Cachet#2618]
In 2.4.0-dev you can add updates to an incident, however there is no option to edit an update after adding it. This would be handy for example if you make a typing error.

**Comment by jbrooksuk** [comment]
Yeah, this does need implementing!

**Comment by nstapelbroek** [comment]
This can be closed I think :)

**Comment by jbrooksuk** [comment]
Thanks @nstapelbroek!
