### ISSUE TITLE
Change sort of incident updates to "last update at the bottom"

### ISSUE THREAD

**Issue by myH2Oservers** [CachetHQ/Cachet#2619]
In version 2.4.0-dev incident updates (at least with the same status) are ordered by "last update directly below incident". We would like this option to be configurable since most humans read incident updates from top to bottom, and expect the last update to be at the bottom.

**Comment by jbrooksuk** [comment]
Why would you not want the latest update with (hopefully) the fixed status at the top? To me, that reads like: there was an incident, now it's fixed, if you're interested here are the updates...

Thanks for the suggestion, but it's not something I'm going to write myself. If someone wants to implement this as a setting that's fine by me though! :)

**Comment by myH2Oservers** [comment]
> Why would you not want the latest update with (hopefully) the fixed status at the top?

If you have multiple updates with the same status (fix in progress for example) it is confusing as people are used to read "forum style", from top to bottom. Just the way you look at it. I will see if somebody shares my opinion. Tried to change it my selves but I am not familiar enough with the coding style of CachetHQ.

**Comment by jbrooksuk** [comment]
Hm?

**Comment by myH2Oservers** [comment]
Did my comment raise a question? ;-) Just like Github.. oldest post in the top, new updates in the bottom :-)

**Comment by jbrooksuk** [comment]
I'm going to change them round, we'll have a look.
