### ISSUE TITLE
setup page broken after install 

### ISSUE THREAD

**Issue by yuhao-nyc** [CachetHQ/Cachet#2620]
similar issues like other guys had in here. 
followed this link step by step: https://docs.cachethq.io/docs/installing-cachet-on-windows 

![image](https://user-images.githubusercontent.com/4121735/27886889-f9846b16-61ab-11e7-886a-a20643139e02.png)

I tried lot of solutions didnt work. 

here's my laravel log
[laravel-2017-07-05.txt](https://github.com/CachetHQ/Cachet/files/1126156/laravel-2017-07-05.txt)

**Comment by MrPAttema** [comment]
Same problem here, but if I change <link rel="stylesheet" href="/build/dist/css/all-81fdbf996d.css">in the developer console of chrome to <link rel="stylesheet" href="build/dist/css/all-81fdbf996d.css"> without the first slash. The CSS works, but buttons and the logo ar still unclickable. I've been looking all day fo a solution.

**Comment by GrahamCampbell** [comment]
Cachet doesn;t work well installed in a subfolder.
