### ISSUE TITLE
Cachet 2.4.0 problem with DB not on the same machine

### ISSUE THREAD

**Issue by nan008** [CachetHQ/Cachet#2622]
Hello,

OS: Centos 7
Cachet: 2.4.0-dev
I have a problem with Catchet is that my DB is on another machine. I am running the command

```
php artisan app:install
```

and get this errors:

```
[Illuminate\Database\QueryException]
  SQLSTATE[42000]: Syntax error or access violation: 1071 Specified key was too long; max key length is 767 bytes (SQL: alter table `subscribers` add unique `subsc
  ribers_email_unique`(`email`))
```

```
[Doctrine\DBAL\Driver\PDOException]
  SQLSTATE[42000]: Syntax error or access violation: 1071 Specified key was too long; max key length is 767 bytes
```

```
[PDOException]
  SQLSTATE[42000]: Syntax error or access violation: 1071 Specified key was too long; max key length is 767 bytes
```

I amended 
CachetHQ/vendor/backup-manager/backup-manager/config/database.php
CachetHQ/config/database.php
and .env to reflect the DB
Is there any other file that I supposed to change to be able to run Cachet?

**Comment by jbrooksuk** [comment]
What version of MySQL were you using?

**Comment by jbrooksuk** [comment]
@joecohens this has happened again 🤔
