### ISSUE TITLE
Bad output when creating a component incident without component status

### ISSUE THREAD

**Issue by leonardoarroyo** [CachetHQ/Cachet#2623]
Take a look at the following request:
```
curl --request POST \
  -H "X-Cachet-Token: {{token}}" \
  -H "Content-Type: application/json" \
  --url http://{{cachet_url}}/api/v1/incidents \
  --data '{"name":"dasdsa","message":"dsadsad","status":4,"component_id":1}'

{"errors":[{"id":"5d3aca90-d6e5-40c9-a7a0-f31de7a115da","status":400,"title":"Bad Request","detail":"The request cannot be fulfilled due to bad syntax.","meta":{"details":["The status format is invalid."]}}]}
```

It took me some time to find out it was related to `component_status` and not `status`. I believe a better response would be something like: `The component_status is required.`

**Comment by jbrooksuk** [comment]
I think we'd need to pre-validate the data before we hit the model. The model validation is looking for `status` as it's on the component.

**Comment by nan008** [comment]
I have similar on 2.4, 

I am feeding the status from zabbix-cachet plugin

```bash
ERROR: (Trigger Watcher) ClientHttpError[https://status.example.com/api/v1/incidents, 400: {"errors":[{"id":"261aa814-c094-4550-acb9-107f4969d82c","status":400,"title":"Bad Request","detail":"The request cannot be fulfilled due to bad syntax.","meta":{"details":["The notify field must be true or false."]}}]}]
```
when the components are created it is ok - when the status of the service in zabbix is changed, the trigger is fire off and zabbix-cachet plugin is trying to update the status in Cachet and getting the above error.

The owner of the plugin asked me to downgrade to 2.3.14

> It's look like a bug in Cachet. Because this field is optional. Try to use stable version for example 2.3.14.

**Comment by jbrooksuk** [comment]
Thank you for your input on Cachet 2.x. We are shifting our attention and resources to Cachet 3.x and will no longer be supporting the 2.x version. If your feedback or issue is relevant to the 3.x series, we encourage you to engage with the new branch.

For more information on the Cachet rebuild and our plans for 3.x, you can read the announcement [here](https://github.com/CachetHQ/Cachet/discussions/4342).

We appreciate your understanding and look forward to your contributions to the new version.
