### ISSUE TITLE
Composer Install Error

### ISSUE THREAD

**Issue by TheoBearman** [CachetHQ/Cachet#2624]
44de01b

`[2017-07-08 14:14:32] local.CRITICAL: Symfony\Component\Debug\Exception\FatalThrowableError: Parse error: syntax error, unexpected '$dispatcher' (T_VARIABLE) in /var/www/html/Cachet/app/Foundation/Providers/AppServiceProvider.php:40
Stack trace:
#0 /var/www/html/Cachet/vendor/composer/ClassLoader.php(322): Composer\Autoload\includeFile('/var/www/html/C...')
#1 [internal function]: Composer\Autoload\ClassLoader->loadClass('CachetHQ\\Cachet...')
#2 /var/www/html/Cachet/vendor/laravel/framework/src/Illuminate/Foundation/ProviderRepository.php(208): spl_autoload_call('CachetHQ\\Cachet...')
#3 /var/www/html/Cachet/vendor/laravel/framework/src/Illuminate/Foundation/ProviderRepository.php(144): Illuminate\Foundation\ProviderRepository->createProvider('CachetHQ\\Cachet...')
#4 /var/www/html/Cachet/vendor/laravel/framework/src/Illuminate/Foundation/ProviderRepository.php(61): Illuminate\Foundation\ProviderRepository->compileManifest(Array)
#5 /var/www/html/Cachet/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(549): Illuminate\Foundation\ProviderRepository->load(Array)
#6 /var/www/html/Cachet/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/RegisterProviders.php(17): Illuminate\Foundation\Application->registerConfiguredProviders()
#7 /var/www/html/Cachet/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(208): Illuminate\Foundation\Bootstrap\RegisterProviders->bootstrap(Object(Illuminate\Foundation\Application))
#8 /var/www/html/Cachet/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(267): Illuminate\Foundation\Application->bootstrapWith(Array)
#9 /var/www/html/Cachet/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(114): Illuminate\Foundation\Console\Kernel->bootstrap()
#10 /var/www/html/Cachet/artisan(35): Illuminate\Foundation\Console\Kernel->handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#11 {main} {"identification":{"id":"1bcbe2aa-d890-4377-b7a0-6423b6345e70"}} 
`

**Comment by GrahamCampbell** [comment]
Thanks. Fixed.

**Comment by jbrooksuk** [comment]
Whoops!

**Comment by TheoBearman** [comment]
:smile:
