### ISSUE TITLE
subscribed to components but system doesn't send any mail.

### ISSUE THREAD

**Issue by jkotev** [CachetHQ/Cachet#2625]
ver 2.3.11

1. after suscribing to compoenents and getting the " Awesome. You've been subscribed to email notifications, please check your email to confirm your subscription. " 

no mail is being sent to the suscriber.

2. also if i didn't confirm the subscrption like i should on mail the changes are being made to the user. i can see the same on the admin console. 

please advise.

**Comment by jbrooksuk** [comment]
What is the `QUEUE_DRIVER` value set to in your `.env` file?

**Comment by jbrooksuk** [comment]
You probably just need to get the queue running. https://docs.cachethq.io/docs/configuring-the-queue

**Comment by jkotev** [comment]
QUEUE_DRIVER=sync

**Comment by jkotev** [comment]
thanks, Jason

it is sending emails for new subscriptions.

for not for a change in subscriptions. 

is that the way it should work?

**Comment by jkotev** [comment]
if an already listed subscriber makes a change in his subscriptions.
he will get the next message: 

"Awesome. You've been subscribed to email notifications, please check your email to confirm your subscription."

but no email is being sent.

**Comment by jbrooksuk** [comment]
Have you set the mail settings? Do they work?

**Comment by jkotev** [comment]
the emails are being sent.

just in the case i described above: (user changes his subscriptions) they are not being sent.
