### ISSUE TITLE
Installation of version 2.4 fails

### ISSUE THREAD

**Issue by Mebus** [CachetHQ/Cachet#2626]
Hallo,

when I try to use php artisan app:install I keep getting the attached error message. Why?

![image](https://user-images.githubusercontent.com/271557/28036388-6475ffba-65b8-11e7-8337-432493cc5266.png)

Mebus

**Comment by GrahamCampbell** [comment]
2.4 is still in development, and may not work. Using postgres or mysql will likely work better.

**Comment by jbrooksuk** [comment]
Are you using Maria DB?

**Comment by GrahamCampbell** [comment]
SQLite, from the screenshot.

**Comment by GrahamCampbell** [comment]
Please see duplicate issues. SQLite is not working properly on 2.4-dev atm.

**Comment by Mebus** [comment]
I think it didn't work with 2.3.9, too. I wonder why one needs so much stuff to create a status page...
