### ISSUE TITLE
Add backups folder to gitignore

### ISSUE THREAD

**Issue by gemal** [CachetHQ/Cachet#2627]
the backups folder should be added to the gitignore file is doesn't show up as modified after the installation put a database backup file into it
Got a file like this `XXXX-07-03 12.27.31.gz` in it

**Comment by jbrooksuk** [comment]
How do you mean sorry? https://github.com/CachetHQ/Cachet/blob/2.4/database/backups/.gitignore

**Comment by GrahamCampbell** [comment]
Maybe you accidently cleared our that ignore file when deleting all backups?
