### ISSUE TITLE
Emails for Scheduled Maintenance

### ISSUE THREAD

**Issue by adishorvs** [CachetHQ/Cachet#2629]
Hi,

I have an issue with Cachet 2.4.
It doesn't send emails for for Scheduled Maintenance, it used to when I finished the installation, but not anymore, I didn't change anything.
There's no logs in laravel and nothing in maillog. 

It does send emails for component updates and incidents, but not for Scheduled Maintenance.

Regards,

**Comment by adishorvs** [comment]
Managed to reproduce it.
Installed fresh.
Subscribed.
Scheduled maintenance - email worked.
Added component
Scheduled maintenance - email worked.
Removed myself from subscribers.
Subscribed again - unchecked the component.
Scheduled maintenance - not emailing
subscribed another email - not receiving emails.
removed component 
re-subbed
scheduled maintenance - works.

**Comment by adishorvs** [comment]
Mmmkay, so it seems that I need to be subscribed to all components in order for it to work. But I don't want people to receive emails on all components change, only on scheduled maintenance.

**Comment by adishorvs** [comment]
can you tell me how to remove the automatic email sent when updating a component? :)

**Comment by adishorvs** [comment]
Found the answer myself : 

In ../Cachet/app/Notifications/Component/ComponentStatusChangedNotification.php

    public function via($notifiable)
    {
        #return ['mail', 'nexmo', 'slack'];
        return ['nexmo', 'slack'];

    }

**Comment by jbrooksuk** [comment]
👍

**Comment by gcommit** [comment]
I have the same Problem with 2.4 but i don't get it to work! Have you changed something so it worked? 

I re-subbed several times, subscribed to all components but i did not receive any mails. 

What i found in the code: 

Notifications/Component/ComponentStatusChangedNotification.php

![Bildschirmfoto 2019-12-02 um 12 20 21](https://user-images.githubusercontent.com/18714033/69955549-2b5d3980-14fe-11ea-9e1e-0aca7d1e3366.png)


Is this correct?
