### ISSUE TITLE
Change back to default language

### ISSUE THREAD

**Issue by LazosPlaying** [CachetHQ/Cachet#2631]
Hello. i just finished setting up Cachet. I stated playing around so i can see what i can do, when i changed the language to "crowdin" and now i am blocked from doing anything.

Any way to fix that by editing a file?

Thank you in advance.

**Comment by LazosPlaying** [comment]
Fixed by authorising into Crowdin with GitHub and changing the language.

**Comment by jbrooksuk** [comment]
Cachet isn't linked to CrowdIn in that way though... You can change the language by editing the DB setting for `app_locale` I believe.
