### ISSUE TITLE
Error 404: setup/step1 not found 

### ISSUE THREAD

**Issue by emt1803** [CachetHQ/Cachet#2634]
Hello everybody!

I just installed Cachet on Debian 8 with PHP 5.6.

Now I am on the first site of the setup guide but when I click next I get these errors in the Browser Console:

```
all-b2c62d4294.js:3 POST http://status.******.download/setup/step1 404 (Not Found)
send @ all-b2c62d4294.js:3
ajax @ all-b2c62d4294.js:3
ae.(anonymous function) @ all-b2c62d4294.js:3
(anonymous) @ all-b2c62d4294.js:21
dispatch @ all-b2c62d4294.js:2
g.handle @ all-b2c62d4294.js:2
all-b2c62d4294.js:21 Uncaught TypeError: Cannot read property 'errors' of undefined
    at Object.<anonymous> (all-b2c62d4294.js:21)
    at u (all-b2c62d4294.js:2)
    at Object.fireWith [as rejectWith] (all-b2c62d4294.js:2)
    at i (all-b2c62d4294.js:3)
    at XMLHttpRequest.<anonymous> (all-b2c62d4294.js:3)
(anonymous) @ all-b2c62d4294.js:21
u @ all-b2c62d4294.js:2
fireWith @ all-b2c62d4294.js:2
i @ all-b2c62d4294.js:3
(anonymous) @ all-b2c62d4294.js:3
```

I hope you can help me with this issue.

Additional Information:
newest Cachet Release

**Comment by jbrooksuk** [comment]
Which version of Cachet are you installing?

**Comment by syui** [comment]
I am getting the same error.
I hope you can help me with this issue.

```js
all.js:11 POST http://cachet-syui.1d35.starter-us-east-1.openshiftapps.com/setup/step1 400 (Bad Request)
```

cachet version 2.4 : https://github.com/syui/Cachet

I am using openshift online (free) and mysql (oc new-app mysql).

http://cachet-syui.1d35.starter-us-east-1.openshiftapps.com/setup

I have followed most of the steps below.

https://github.com/CachetHQ/Docker/issues/175#issuecomment-287696223

**Comment by auth1299** [comment]
I'm getting the same issue. I am running cachet 2.4

**Comment by auth1299** [comment]
![capture](https://user-images.githubusercontent.com/7773605/52086896-0adaf080-2576-11e9-87bb-442d2f4a2abf.PNG)

**Comment by auth1299** [comment]
When in the setup,  I click next it fails. I'm running this on a windows 2016 server using IIS. 

![capture](https://user-images.githubusercontent.com/7773605/52087008-4f668c00-2576-11e9-9625-53d2f13c9d88.PNG)
