### ISSUE TITLE
Component limit on API page?

### ISSUE THREAD

**Issue by thetechgy** [CachetHQ/Cachet#2635]
I've deleted and re-created many components over the course of setting up our Cachet instance, to the point that we're at over 70 components due to the fact that when components are deleted those numbers are never re-used.

When I go to https://status.ritzmanrx.com/api/v1/components, I don't find some of the higher-numbered components listed there, like a test component I created just named 'Google', yet if I go to https://status.ritzmanrx.com/api/v1/components/70, it clearly exists, and it shows up on the dashboard.

Is there an undocumented component limit for that API page?

**Comment by thetechgy** [comment]
Found that there are additional pages, just didn't see that documented, but maybe I'm missing it

https://status.ritzmanrx.com/api/v1/components?page=2

**Comment by jbrooksuk** [comment]
https://docs.cachethq.io/docs/meta
