### ISSUE TITLE
Replace Chart.js with something else

### ISSUE THREAD

**Issue by jbrooksuk** [CachetHQ/Cachet#2641]
The charts produced by Chart.js seem to be lacking in a few areas. We need to up our chart game.

@joecohens any thoughts? We've shared a few options previously.

**Comment by joecohens** [comment]
Should we replace Chart.js or just make it work better? If replace is the option what library are you thinking about?

**Comment by jbrooksuk** [comment]
Make it work better if we can I guess.

**Comment by colby-ham** [comment]
Is there an update to the charting choice or ideology?

**Comment by jbrooksuk** [comment]
We're going to use Frappe Charts :)

**Comment by jbrooksuk** [comment]
Thank you for your input on Cachet 2.x. We are shifting our attention and resources to Cachet 3.x and will no longer be supporting the 2.x version. If your feedback or issue is relevant to the 3.x series, we encourage you to engage with the new branch.

For more information on the Cachet rebuild and our plans for 3.x, you can read the announcement [here](https://github.com/CachetHQ/Cachet/discussions/4342).

We appreciate your understanding and look forward to your contributions to the new version.
