### ISSUE TITLE
Webhook Support

### ISSUE THREAD

**Issue by ekristen** [CachetHQ/Cachet#2650]
It would nice to allow registering of webhooks that Cachet then updates with different changes. Changes would include incidents, scheduled maintenance, changes to component statuses, etc.

**Comment by jbrooksuk** [comment]
This would be amazing! Are you able to contribute a PR? It's something we've previously discussed too.

**Comment by danielemontesi** [comment]
+1

**Comment by jbrooksuk** [comment]
I'm going to push this back to v4.0 (as v2.4 will become v3.0 on launch). We're focusing on bug fixes and several key improvements.

**Comment by katsil** [comment]
hello! any news about webhook?

**Comment by jbrooksuk** [comment]
Not as of yet, but I'd be grateful for someone to pick this up! It'd be very easy to do actually.

1. Make sure all kinds of actions fire events (subscriber updated/created/deleted, incident updated/created/deleted etc)
2. Setup an interface on all events as `Webhookable` or similar.
3. Add event listener for the `Webhookable` interface and handle the webhook event from here.

The hardest bit will simply be the UX for it.

**Comment by katsil** [comment]
ugh, sorry. i world like to try, but i’m not unto php 
python mostly..

**Comment by atymic** [comment]
I'll have a go of this when I have some spare time, I think this would be an awesome feature.

**Comment by jbrooksuk** [comment]
@atymic it may be a good opportunity to check out https://github.com/spatie/laravel-webhook-server

**Comment by atymic** [comment]
> @atymic it may be a good opportunity to check out [spatie/laravel-webhook-server](https://github.com/spatie/laravel-webhook-server)

I did see that package, I am definitely a fan of Spatie :)
I take it you are happy with using a 3rd party package?

**Comment by jbrooksuk** [comment]
> I take it you are happy with using a 3rd party package?

Yeah 🙂 

You need to weigh up what we gain from using a 3rd party instead of writing it ourselves, but I think in this case it makes sense.

**Comment by atymic** [comment]
Just another thought, if we were to use this package (or build it ourselves), we'd also probably need to update the documentation to add information on running queues (ie, setting up supervisor, etc).

**Comment by jbrooksuk** [comment]
Heh, a lot of documentation needs rewriting into the `docs` folder anyway, so that's a good opportunity.

**Comment by RustyIngles** [comment]
hi everyone, any news about webhook please?

**Comment by hartfordfive** [comment]
Any news on this?  Would be interested in this also!

**Comment by luto** [comment]
Anyone interested in _implementing_ this, send me an email to the address in my profile page. I'd love to get this as a sponsored feature. Also, tell me, if you or your company has spare cash to co-finance this. @jbrooksuk

**Comment by adambirds** [comment]
Any news on when this will be available?

**Comment by olivierlambert** [comment]
Same question: if we got webhook support to update it, that will be really great!

**Comment by jbrooksuk** [comment]
Thank you for your input on Cachet 2.x. We are shifting our attention and resources to Cachet 3.x and will no longer be supporting the 2.x version. If your feedback or issue is relevant to the 3.x series, we encourage you to engage with the new branch.

For more information on the Cachet rebuild and our plans for 3.x, you can read the announcement [here](https://github.com/CachetHQ/Cachet/discussions/4342).

We appreciate your understanding and look forward to your contributions to the new version.
