### ISSUE TITLE
Error 500

### ISSUE THREAD

**Issue by ilkiny** [CachetHQ/Cachet#2651]
Hello friends,

I am getting the following error, what is the problem?

![34123123](https://user-images.githubusercontent.com/24559998/28484947-566a2b02-6e7e-11e7-9ab4-01b0b83aa811.png)

Stay with love.

**Comment by jbrooksuk** [comment]
@ilkiny sorry for the delay! You can see from the error in the top left that is says:

> Access denied for user `cachethq`@`localhost`.

You need to check your database connection settings.

**Comment by ilkiny** [comment]
Hi @jbrooksuk 
Thank you for reply, I got that problem wrong password entered :( But the button does not work on the install page now

**Comment by jbrooksuk** [comment]
This is now fixed in 861f0351c5836a03cd6e52e11aa8bf4fd461711d

**Comment by ilkiny** [comment]
I've made changes, but it's not working again. :( @jbrooksuk

**Comment by jbrooksuk** [comment]
You pulled down the latest 2.4?
