### ISSUE TITLE
Your requirements could not be resolved to an installable set of packages.

### ISSUE THREAD

**Issue by barreeeiroo** [CachetHQ/Cachet#2652]
I'm getting this error executing _composer install --no-dev -o_

> ubuntu@ip-172-31-7-102:~/Cachet$ composer install --no-dev -o
> Loading composer repositories with package information
> Installing dependencies from lock file
> Your requirements could not be resolved to an installable set of packages.
> 
>   Problem 1
>     - The requested PHP extension ext-xml * is missing from your system. Install or enable PHP's xml extension.
>   Problem 2
>     - Installation request for laravel/framework v5.2.39 -> satisfiable by laravel/framework[v5.2.39].
>     - laravel/framework v5.2.39 requires ext-mbstring * -> the requested PHP extension mbstring is missing from your system.
>   Problem 3
>     - Installation request for league/commonmark 0.13.4 -> satisfiable by league/commonmark[0.13.4].
>     - league/commonmark 0.13.4 requires ext-mbstring * -> the requested PHP extension mbstring is missing from your system.
>   Problem 4
>     - Installation request for simplesoftwareio/simple-qrcode 1.3.3 -> satisfiable by simplesoftwareio/simple-qrcode[1.3.3].
>     - simplesoftwareio/simple-qrcode 1.3.3 requires ext-gd * -> the requested PHP extension gd is missing from your system.
>   Problem 5
>     - laravel/framework v5.2.39 requires ext-mbstring * -> the requested PHP extension mbstring is missing from your system.
>     - roumen/feed v2.10.4 requires illuminate/support ^5.0 -> satisfiable by laravel/framework[v5.2.39].
>     - Installation request for roumen/feed v2.10.4 -> satisfiable by roumen/feed[v2.10.4].
> 
>   To enable extensions, verify that they are enabled in your .ini files:
>     - /etc/php/7.0/cli/php.ini
>     - /etc/php/7.0/cli/conf.d/10-opcache.ini
>     - /etc/php/7.0/cli/conf.d/10-pdo.ini
>     - /etc/php/7.0/cli/conf.d/20-calendar.ini
>     - /etc/php/7.0/cli/conf.d/20-ctype.ini
>     - /etc/php/7.0/cli/conf.d/20-exif.ini
>     - /etc/php/7.0/cli/conf.d/20-fileinfo.ini
>     - /etc/php/7.0/cli/conf.d/20-ftp.ini
>     - /etc/php/7.0/cli/conf.d/20-gettext.ini
>     - /etc/php/7.0/cli/conf.d/20-iconv.ini
>     - /etc/php/7.0/cli/conf.d/20-json.ini
>     - /etc/php/7.0/cli/conf.d/20-phar.ini
>     - /etc/php/7.0/cli/conf.d/20-posix.ini
>     - /etc/php/7.0/cli/conf.d/20-readline.ini
>     - /etc/php/7.0/cli/conf.d/20-shmop.ini
>     - /etc/php/7.0/cli/conf.d/20-sockets.ini
>     - /etc/php/7.0/cli/conf.d/20-sysvmsg.ini
>     - /etc/php/7.0/cli/conf.d/20-sysvsem.ini
>     - /etc/php/7.0/cli/conf.d/20-sysvshm.ini
>     - /etc/php/7.0/cli/conf.d/20-tokenizer.ini
>   You can also run `php --ini` inside terminal to see which files are used by PHP in CLI mode.
> ubuntu@ip-172-31-7-102:~/Cachet$

How can I fix it?

**Comment by barreeeiroo** [comment]
Hosting on AmazonEC2 t2.micro with Ubuntu16.04

**Comment by GrahamCampbell** [comment]
Composer lists the problems for you. You need to install the extensions listed.

**Comment by barreeeiroo** [comment]
Thanks

Fixed executing:
`apt get install php-gd php-xml php7.0-mbstring`

**Comment by jbrooksuk** [comment]
:)

**Comment by heversonr** [comment]
Thanks!

**Comment by Ajax30** [comment]
Should "apt get install php-gd php-xml php7.0-mbstring" be executed globally or in the project's root directory?

**Comment by jbrooksuk** [comment]
It won't matter as `apt get` is a global installation.

**Comment by AnDi1402** [comment]
para windows como es el comando?

**Comment by AnDi1402** [comment]
help please

**Comment by fettymkima** [comment]
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - The requested PHP extension ext-gd * is missing from your system. Install or enable PHP's gd extension.
  Problem 2
    - dompdf/dompdf v0.8.2 requires ext-gd * -> the requested PHP extension gd is missing from your system.
    - dompdf/dompdf v0.8.1 requires ext-gd * -> the requested PHP extension gd is missing from your system.
    - dompdf/dompdf v0.8.0 requires ext-gd * -> the requested PHP extension gd is missing from your system.
    - barryvdh/laravel-dompdf v0.8.1 requires dompdf/dompdf ^0.8 -> satisfiable by dompdf/dompdf[v0.8.0, v0.8.1, v0.8.2].
    - Installation request for barryvdh/laravel-dompdf ^0.8.1 -> satisfiable by barryvdh/laravel-dompdf[v0.8.1].

  To enable extensions, verify that they are enabled in your .ini files:
    - /etc/php/5.6/cli/php.ini
    - /etc/php/5.6/cli/conf.d/10-mysqlnd.ini
    - /etc/php/5.6/cli/conf.d/10-opcache.ini
    - /etc/php/5.6/cli/conf.d/10-pdo.ini
    - /etc/php/5.6/cli/conf.d/15-xml.ini
    - /etc/php/5.6/cli/conf.d/20-calendar.ini
    - /etc/php/5.6/cli/conf.d/20-ctype.ini
    - /etc/php/5.6/cli/conf.d/20-curl.ini
    - /etc/php/5.6/cli/conf.d/20-dom.ini
    - /etc/php/5.6/cli/conf.d/20-exif.ini
    - /etc/php/5.6/cli/conf.d/20-fileinfo.ini
    - /etc/php/5.6/cli/conf.d/20-ftp.ini
    - /etc/php/5.6/cli/conf.d/20-gettext.ini
    - /etc/php/5.6/cli/conf.d/20-iconv.ini
    - /etc/php/5.6/cli/conf.d/20-intl.ini
    - /etc/php/5.6/cli/conf.d/20-json.ini
    - /etc/php/5.6/cli/conf.d/20-ldap.ini
    - /etc/php/5.6/cli/conf.d/20-mbstring.ini
    - /etc/php/5.6/cli/conf.d/20-mcrypt.ini
    - /etc/php/5.6/cli/conf.d/20-mysql.ini
    - /etc/php/5.6/cli/conf.d/20-mysqli.ini
    - /etc/php/5.6/cli/conf.d/20-pdo_mysql.ini
    - /etc/php/5.6/cli/conf.d/20-phar.ini
    - /etc/php/5.6/cli/conf.d/20-posix.ini
    - /etc/php/5.6/cli/conf.d/20-readline.ini
    - /etc/php/5.6/cli/conf.d/20-shmop.ini
    - /etc/php/5.6/cli/conf.d/20-simplexml.ini
    - /etc/php/5.6/cli/conf.d/20-sockets.ini
    - /etc/php/5.6/cli/conf.d/20-sysvmsg.ini
    - /etc/php/5.6/cli/conf.d/20-sysvsem.ini
    - /etc/php/5.6/cli/conf.d/20-sysvshm.ini
    - /etc/php/5.6/cli/conf.d/20-tokenizer.ini
    - /etc/php/5.6/cli/conf.d/20-wddx.ini
    - /etc/php/5.6/cli/conf.d/20-xmlreader.ini
    - /etc/php/5.6/cli/conf.d/20-xmlwriter.ini
    - /etc/php/5.6/cli/conf.d/20-xsl.ini
  You can also run `php --ini` inside terminal to see which files are used by PHP in CLI mode.
am getting this error help please

**Comment by GrahamCampbell** [comment]
> Your requirements could not be resolved to an installable set of packages.

The error message tells you what you need to install:

> The requested PHP extension ext-gd

**Comment by rami1989** [comment]
and how can i install all this file
