### ISSUE TITLE
Prevent metrics in same minute from adding together

### ISSUE THREAD

**Issue by elderlabs** [CachetHQ/Cachet#2653]
I'd like to show the average for each datapoint that gets added per minute, however an extra data point gets added from time to time, which adds to the first, doubling the data, instead of averaging together. Is there a fix for this? [And yes, my setting reflect averaging data points, not adding them together.]

**Comment by jbrooksuk** [comment]
What version of Cachet are you using?

**Comment by elderlabs** [comment]
v2.3.9

**Comment by jbrooksuk** [comment]
Are you able to test this under v2.4?

**Comment by elderlabs** [comment]
Tested under 2.4. Same result.

**Comment by jbrooksuk** [comment]
Are you setting the threshold to 0?

**Comment by elderlabs** [comment]
YesOn Sep 30, 2017 6:54 AM, James Brooks <notifications@github.com> wrote:Are you setting the threshold to 0?

**Comment by 1digbick1x** [comment]
What

**Comment by elderlabs** [comment]
Sorry, updated my answer. Seems github's email reply system is broken.

**Comment by jbrooksuk** [comment]
Can you see if the newest 2.4 fixes this for you?

**Comment by si458** [comment]
sorry to tag onto old issue but im having the same issue, 
if i post a metric thats the same as the minute before, it just updates the counter rather than inserting the new metric even tho i am setting a different timetstamp?

**Comment by jbrooksuk** [comment]
Thank you for your input on Cachet 2.x. We are shifting our attention and resources to Cachet 3.x and will no longer be supporting the 2.x version. If your feedback or issue is relevant to the 3.x series, we encourage you to engage with the new branch.

For more information on the Cachet rebuild and our plans for 3.x, you can read the announcement [here](https://github.com/CachetHQ/Cachet/discussions/4342).

We appreciate your understanding and look forward to your contributions to the new version.
