### ISSUE TITLE
Remove GrahamCampbell/Laravel-Core

### ISSUE THREAD

**Issue by jbrooksuk** [CachetHQ/Cachet#2669]
The package is now abandoned.

We should move things into the `cachet` signature.

**Comment by GrahamCampbell** [comment]
👍

**Comment by GrahamCampbell** [comment]
All the events stuff is overkill BS that was in the core package originally. We can just have 3 console commands that do shit. :P

**Comment by jbrooksuk** [comment]
I need to get on with this so we can move to Laravel 5.5 at some point.

**Comment by jbrooksuk** [comment]
Closed by https://github.com/CachetHQ/Cachet/pull/3092
