### ISSUE TITLE
Metrics not pulling latest?

### ISSUE THREAD

**Issue by ShonM** [CachetHQ/Cachet#2670]
Despite metrics streaming in via API and MySQL confirming it, the dashboard has looked like this for days now https://cl.ly/3w0k3e343v1M

```
mysql> select * from metric_points order by created_at desc limit 10;
+---------+-----------+---------+---------+---------------------+---------------------+
| id      | metric_id | value   | counter | created_at          | updated_at          |
+---------+-----------+---------+---------+---------------------+---------------------+
| 1175307 |         8 | 624.000 |       1 | 2017-07-28 21:20:18 | 2017-07-28 21:20:18 |
| 1175306 |         7 | 119.000 |       1 | 2017-07-28 21:20:17 | 2017-07-28 21:20:17 |
| 1175305 |         8 | 537.000 |       1 | 2017-07-28 21:19:18 | 2017-07-28 21:19:18 |
| 1175304 |         7 | 106.000 |       1 | 2017-07-28 21:19:17 | 2017-07-28 21:19:17 |
| 1175303 |         8 | 647.000 |       1 | 2017-07-28 21:18:47 | 2017-07-28 21:18:47 |
| 1175302 |         7 | 119.000 |       1 | 2017-07-28 21:18:17 | 2017-07-28 21:18:17 |
| 1175301 |         8 | 516.000 |       1 | 2017-07-28 21:17:18 | 2017-07-28 21:17:18 |
| 1175300 |         7 | 118.000 |       1 | 2017-07-28 21:17:17 | 2017-07-28 21:17:17 |
| 1175299 |         7 | 119.000 |       1 | 2017-07-28 21:16:17 | 2017-07-28 21:16:17 |
| 1175298 |         8 | 532.000 |       2 | 2017-07-28 21:15:21 | 2017-07-28 21:16:18 |
+---------+-----------+---------+---------+---------------------+---------------------+
10 rows in set (0.33 sec)

mysql> select count(*) from metric_points where created_at > '2017-07-28 00:00:00';
+----------+
| count(*) |
+----------+
|     2291 |
+----------+
1 row in set (0.29 sec)

mysql> select CONCAT(HOUR(created_at), ':00-', HOUR(created_at)+1, ':00') AS Hours, count(*) from metric_points where created_at > '2017-07-28 00:00:00' group by HOUR(created_at);
+-------------+----------+
| Hours       | count(*) |
+-------------+----------+
| 0:00-1:00   |      115 |
| 1:00-2:00   |      117 |
| 2:00-3:00   |      116 |
| 3:00-4:00   |      117 |
| 4:00-5:00   |       98 |
| 5:00-6:00   |       98 |
| 6:00-7:00   |      102 |
| 7:00-8:00   |       99 |
| 8:00-9:00   |       98 |
| 9:00-10:00  |      100 |
| 10:00-11:00 |      100 |
| 11:00-12:00 |      100 |
| 12:00-13:00 |      105 |
| 13:00-14:00 |      106 |
| 14:00-15:00 |      105 |
| 15:00-16:00 |      103 |
| 16:00-17:00 |      109 |
| 17:00-18:00 |      109 |
| 18:00-19:00 |      108 |
| 19:00-20:00 |      106 |
| 20:00-21:00 |      114 |
| 21:00-22:00 |       70 |
+-------------+----------+
22 rows in set (0.30 sec)
```

Last 10 today, total today, and total by-hour today. All of this indicates there are metrics to pull. The API response (`/metrics/8?filter=last_hour`) matches the graph. If I had to guess, I would say this is a query issue, but I'm not sure how to expose the query.

I'm hoping for a quick "aha!" response. Otherwise come Monday I'll dig into this more and post my findings.

Still loving Cachet. Very much looking forward to some of the changes I see cooking... 😄

**Comment by ShonM** [comment]
I believe this was a CDN caching issue. CloudFlare defaults to caching everything for 4h and not just respecting existing headers. Which makes sense for lots of domains! Just not this one.

Sorry for the noise!

**Comment by ShonM** [comment]
I felt this out for a while. It is absolutely a Cachet 2.4 issue. I'm not sure how or where. I set up a brand new project from scratch and can reproduce.

**Comment by jbrooksuk** [comment]
What timezone is Cachet configured to?

**Comment by ShonM** [comment]
To be clear, this was the case after _days_. It wasn't just a missing hour, or a missing day, it was consistently pulling the _same_ set of metrics. 

It's configured to be eastern standard.

**Comment by jbrooksuk** [comment]
How weird... we don't currently cache metric data yet, so it can't be something there.

What database driver do you use?

**Comment by ShonM** [comment]
MySQL

**Comment by ilsire** [comment]
Hi to all, I've got the same problem or quiet similar.
Graph works well only for Last 12h, Week and Month but the Last Hour is exaclty as @ShonM described here https://cl.ly/3w0k3e343v1M
Time zone is setted to Rome in MySQL

**Comment by samwiseg00** [comment]
One issue that I am seeing is the metric points are being written to the database with the wrong timestamp. I have checked my php.ini and mysql for the correct time and timezone settings.

As a workaround I am setting the timestamp in the metric 5 hours back

```
{"data":{"value":4,"counter":1,"metric_id":1,"created_at":"2018-02-16 10:25:28","updated_at":"2018-02-16 10:25:30","id":4,"calculated_value":4}}
```

mysql
```
MariaDB [cachet_datadev]> select * from metric_points;
+----+-----------+-------+---------+---------------------+---------------------+
| id | metric_id | value | counter | created_at          | updated_at          |
+----+-----------+-------+---------+---------------------+---------------------+
|  1 |         1 | 4.000 |       1 | 2018-02-16 15:26:26 | 2018-02-16 15:26:28 |
+----+-----------+-------+---------+---------------------+---------------------+
1 row in set (0.00 sec)
```
```
MariaDB [cachet_datadev]> SELECT NOW();
+---------------------+
| NOW()               |
+---------------------+
| 2018-02-16 10:26:57 |
+---------------------+
1 row in set (0.00 sec)
```

**Comment by jbrooksuk** [comment]
Have you set the timezone in Cachet correctly?

**Comment by samwiseg00** [comment]
@jbrooksuk Yes all timezones were set correctly.

**Comment by jbrooksuk** [comment]
Thank you for your input on Cachet 2.x. We are shifting our attention and resources to Cachet 3.x and will no longer be supporting the 2.x version. If your feedback or issue is relevant to the 3.x series, we encourage you to engage with the new branch.

For more information on the Cachet rebuild and our plans for 3.x, you can read the announcement [here](https://github.com/CachetHQ/Cachet/discussions/4342).

We appreciate your understanding and look forward to your contributions to the new version.
