### ISSUE TITLE
MAIL_NAME with space

### ISSUE THREAD

**Issue by igramnet** [CachetHQ/Cachet#2672]
Tell me, I want to have the name "G-Core Labs" as the sender. But if I write MAIL_NAME = "G-Core Labs" or MAIL_NAME = G-Core Labs, then the script does not work. How to be?

**Comment by jbrooksuk** [comment]
You need to do:

```
MAIL_NAME="G-Core Labs"
```

Notice there isn't a space between the key and value.

**Comment by fitz123** [comment]
getting this

>>>
Initializing Cachet container ...
sed: -e expression #1, char 22: unterminated `s' command
Initializing Cachet container ...
sed: -e expression #1, char 22: unterminated `s' command
Initializing Cachet container ...
sed: -e expression #1, char 22: unterminated `s' command
Initializing Cachet container ...
sed: -e expression #1, char 22: unterminated `s' command
Initializing Cachet container ...
sed: -e expression #1, char 22: unterminated `s' command

**Comment by fitz123** [comment]
and that's demo:

```
[sa@fr2-v-lugovoi-1 cachet-status]$ MAIL_NAME="foo"; echo "{{MAIL_NAME}}" | sed 's,{{MAIL_NAME}},'${MAIL_NAME}','
foo
[sa@fr2-v-lugovoi-1 cachet-status]$ MAIL_NAME="foo bar"; echo "{{MAIL_NAME}}" | sed 's,{{MAIL_NAME}},'${MAIL_NAME}','
sed: -e expression #1, char 19: unterminated `s' command
```
