### ISSUE TITLE
Adding Metric point notes?

### ISSUE THREAD

**Issue by tmfksoft** [CachetHQ/Cachet#2673]
A feature I dont think I've seen anywhere.
Would be nice to add a note to a metric point with any relevant information.

In my case I'm monitoring an IRC network, would be useful to add a note to a metric point to show what server the monitoring bot connected to (It performs a check every 15minutes and adds a metric point for the ping)

I'm sure it could be useful for others. Though arguably it'd make more sense to add a metric per server.

**Comment by jbrooksuk** [comment]
2.4 has introduced a meta system, which this can make use of. https://github.com/CachetHQ/Cachet/pull/2570
