### ISSUE TITLE
Add blog/information link to field?

### ISSUE THREAD

**Issue by tmfksoft** [CachetHQ/Cachet#2674]
Would be useful to have an optional link in incidents that could be used to link to a postmortem or just general information about the incident.

It would fit well underneath the incident description as an information link.
similar to status page's postmortem/information support.

Such an example could be found here:
https://status.discordapp.com/incidents/ywdwttd6b0hg

A custom link would probably be more suitable as it'd be easier to add in and allow linking to external blogs.

**Comment by jbrooksuk** [comment]
I'm not sure I understand? Cachet uses Markdown, so you can link to somewhere if you wanted to.

**Comment by tmfksoft** [comment]
Good point, I were thinking along the lines of just throwing a URL in a box to show a nice obvious button rather than messing with markdown.

**Comment by jbrooksuk** [comment]
I'd add it to Markdown :) one thing 2.4 will introduce is a meta system for incidents, components etc, however, this won't be displayed anywhere, only within the API.
