### ISSUE TITLE
Show status date and time of incident

### ISSUE THREAD

**Issue by TecSecret** [CachetHQ/Cachet#2676]
Good Morning,

I wonder if someone can tell you how to cachet to show the date and time that they had change the insider on each change of status as in the picture.

![image](https://user-images.githubusercontent.com/6561517/28824861-5f1a9786-769a-11e7-82a6-19686ccd0486.png)

A big hug

**Comment by jbrooksuk** [comment]
Hover over the timestamp.

![image](https://user-images.githubusercontent.com/246103/31045176-baea990c-a5d5-11e7-8714-151e15579880.png)
