### ISSUE TITLE
Error 500 on dashboard.

### ISSUE THREAD

**Issue by jeanblu** [CachetHQ/Cachet#2681]
I installed v2.3.9 on Ubuntu Server. 
After the setup, when I try to access the cachet (dashboard) I'm getting 2 errors 500 (Houston, We Have A Problem).

Anyone can help-me to find the how to solve the problem?

**Comment by instacode-AU** [comment]
Have you enabled mod-rewrite?

`sudo a2enmod rewrite`

**Comment by jeanblu** [comment]
Module rewrite already enabled.

I've configure the setup just fine, just when I open the dashboard the error happens.

**Comment by tambnguyen** [comment]
I'm getting this error too, on both 2.3.12 and 2.3.13.

**Comment by jbrooksuk** [comment]
Can you please share the log file?

**Comment by Apollo2000** [comment]
I am getting also 500 on version 2.4
Using PHP 5.6.3 + Nginix 
Clean install

**Comment by agentcobra** [comment]
same issue for me,
I'm under version 2.4
with apache : 
> Server version: Apache/2.4.25 (Debian)
> Server built:   2018-03-31T08:47:16

with PHP : 
> PHP 7.2.5-1+0~20180505045740.21+stretch~1.gbpca2fa6 (cli) (built: May  5 2018 04:57:44) ( NTS )
> Copyright (c) 1997-2018 The PHP Group
> Zend Engine v3.2.0, Copyright (c) 1998-2018 Zend Technologies
>     with Zend OPcache v7.2.5-1+0~20180505045740.21+stretch~1.gbpca2fa6, Copyright (c) 1999-2018, by Zend Technologies


I'v got this error : 
![image](https://user-images.githubusercontent.com/1831853/39971449-620ad950-56fb-11e8-86a6-7ec0aa3c8f4f.png)
I have already done : 
`php artisan down`
`git fetch origin`
`git checkout 2.4`
it's actually 1eb045fba1b8a57e5495443651580c41b8e25583
`chown -R www-data:www-data /var/www && find /var/www -type d -exec chmod 775 {} \; && find /var/www -type f -exec chmod 664 {} \;` for permissions
`composer install --no-dev -o --no-scripts`
`php artisan app:update`
`php artisan up`
`rm -rf bootstrap/cache/*`
in vhost file, I have this  : 
```
<VirtualHost *:80>
        ServerName status.agentcobra.net
        ServerAdmin webmaster@agentcobra.net
        DocumentRoot "/var/www/status.agentcobra.net/public"

        <Directory />
            Require all granted 
            # Used by Apache 2.4
            Options Indexes FollowSymLinks
            AllowOverride All
            Order allow,deny
            Allow from all
        </Directory>

        LogLevel alert rewrite:trace8
        LogFormat "%t, process : %P,  from : %{X-Forwarded-For}i  %r  pwd : %U" spec
        CustomLog ${APACHE_LOG_DIR}/net.agentcobra.status/access.log spec
        ErrorLog ${APACHE_LOG_DIR}/net.agentcobra.status/error.log

</VirtualHost>
```
rewrite mod is enable

**Comment by jbrooksuk** [comment]
This does look like a setup issue. Cachet would respond with a different error page.
