### ISSUE TITLE
Subscribe CSRF token validation failed.

### ISSUE THREAD

**Issue by kappert** [CachetHQ/Cachet#2682]
Hello,
I have some trouble with the subscribe part. The whole application is running fine but when i want to subscribe it get: Error 400 CSRF token validation failed. Bad Request

i have try'd mutliple settings cleard cache, created cache updated and try'd even a whole new installation.

I am using Redis as session and cache driver. 

This is the error log:

[2017-08-07 14:55:03] production.NOTICE: Illuminate\Session\TokenMismatchException in /var/www/vhosts/somewwwsite.com/status.somewwwsite.com/cachet/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/VerifyCsrfToken.php:67
Stack trace:
#0 [internal function]: Illuminate\Foundation\Http\Middleware\VerifyCsrfToken->handle(Object(Illuminate\Http\Request), Object(Closure))
#1 /var/www/vhosts/somewwwsite.com/status.somewwwsite.com/cachet/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(136): call_user_func_array(Array, Array)
#2 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#3 /var/www/vhosts/somewwwsite.com/status.somewwwsite.com/cachet/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(32): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#4 /var/www/vhosts/somewwwsite.com/status.somewwwsite.com/cachet/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php(49): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#5 [internal function]: Illuminate\View\Middleware\ShareErrorsFromSession->handle(Object(Illuminate\Http\Request), Object(Closure))
#6 /var/www/vhosts/somewwwsite.com/status.somewwwsite.com/cachet/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(136): call_user_func_array(Array, Array)
#7 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#8 /var/www/vhosts/somewwwsite.com/status.somewwwsite.com/cachet/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(32): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#9 /var/www/vhosts/somewwwsite.com/status.somewwwsite.com/cachet/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(62): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#10 [internal function]: Illuminate\Session\Middleware\StartSession->handle(Object(Illuminate\Http\Request), Object(Closure))
#11 /var/www/vhosts/somewwwsite.com/status.somewwwsite.com/cachet/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(136): call_user_func_array(Array, Array)
#12 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#13 /var/www/vhosts/somewwwsite.com/status.somewwwsite.com/cachet/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(32): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#14 /var/www/vhosts/somewwwsite.com/status.somewwwsite.com/cachet/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php(37): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#15 [internal function]: Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse->handle(Object(Illuminate\Http\Request), Object(Closure))
#16 /var/www/vhosts/somewwwsite.com/status.somewwwsite.com/cachet/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(136): call_user_func_array(Array, Array)
#17 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#18 /var/www/vhosts/somewwwsite.com/status.somewwwsite.com/cachet/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(32): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#19 /var/www/vhosts/somewwwsite.com/status.somewwwsite.com/cachet/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php(59): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#20 [internal function]: Illuminate\Cookie\Middleware\EncryptCookies->handle(Object(Illuminate\Http\Request), Object(Closure))
#21 /var/www/vhosts/somewwwsite.com/status.somewwwsite.com/cachet/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(136): call_user_func_array(Array, Array)
#22 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#23 /var/www/vhosts/somewwwsite.com/status.somewwwsite.com/cachet/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(32): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#24 [internal function]: Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#25 /var/www/vhosts/somewwwsite.com/status.somewwwsite.com/cachet/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(102): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#26 /var/www/vhosts/somewwwsite.com/status.somewwwsite.com/cachet/vendor/laravel/framework/src/Illuminate/Routing/Router.php(726): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#27 /var/www/vhosts/somewwwsite.com/status.somewwwsite.com/cachet/vendor/laravel/framework/src/Illuminate/Routing/Router.php(699): Illuminate\Routing\Router->runRouteWithinStack(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request))
#28 /var/www/vhosts/somewwwsite.com/status.somewwwsite.com/cachet/vendor/laravel/framework/src/Illuminate/Routing/Router.php(675): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
#29 /var/www/vhosts/somewwwsite.com/status.somewwwsite.com/cachet/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(246): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#30 [internal function]: Illuminate\Foundation\Http\Kernel->Illuminate\Foundation\Http\{closure}(Object(Illuminate\Http\Request))
#31 /var/www/vhosts/somewwwsite.com/status.somewwwsite.com/cachet/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(52): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#32 /var/www/vhosts/somewwwsite.com/status.somewwwsite.com/cachet/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/CheckForMaintenanceMode.php(44): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#33 [internal function]: Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode->handle(Object(Illuminate\Http\Request), Object(Closure))
#34 /var/www/vhosts/somewwwsite.com/status.somewwwsite.com/cachet/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(136): call_user_func_array(Array, Array)
#35 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#36 /var/www/vhosts/somewwwsite.com/status.somewwwsite.com/cachet/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(32): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#37 /var/www/vhosts/somewwwsite.com/status.somewwwsite.com/cachet/vendor/fideloper/proxy/src/TrustProxies.php(56): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#38 [internal function]: Fideloper\Proxy\TrustProxies->handle(Object(Illuminate\Http\Request), Object(Closure))
#39 /var/www/vhosts/somewwwsite.com/status.somewwwsite.com/cachet/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(136): call_user_func_array(Array, Array)
#40 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#41 /var/www/vhosts/somewwwsite.com/status.somewwwsite.com/cachet/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(32): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#42 [internal function]: Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#43 /var/www/vhosts/somewwwsite.com/status.somewwwsite.com/cachet/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(102): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#44 /var/www/vhosts/somewwwsite.com/status.somewwwsite.com/cachet/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(132): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#45 /var/www/vhosts/somewwwsite.com/status.somewwwsite.com/cachet/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(99): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter(Object(Illuminate\Http\Request))
#46 /var/www/vhosts/somewwwsite.com/status.somewwwsite.com/cachet/public/index.php(54): Illuminate\Foundation\Http\Kernel->handle(Object(Illuminate\Http\Request))
#47 {main} {"identification":{"id":"b40e5b9a-1540-4c22-8818-8f4febf5fe36"}}

**Comment by BerkanYildiz** [comment]
Hi, i fixed mine by cleaning my disk a bit. Check if your disk isn't full by running :
`df -h`

**Comment by kappert** [comment]
Disk is not full, thats not the problem.

**Comment by elkoralish** [comment]
I just opened a nearly identical issue #2690 , disk is also not full.  could it be permissions related? I don't see how, but I suppose it might be possible.  the webserver has the permission to write to the Cachet/storage and Cachet/bootstrap subtrees in my install.

**Comment by jbrooksuk** [comment]
This should be fixed now :)

**Comment by syui** [comment]
I am getting the same error.
I hope you can help me with this issue.

```js
all.js:11 POST http://cachet-syui.1d35.starter-us-east-1.openshiftapps.com/setup/step1 400 (Bad Request)
```

cachet version 2.4 : https://github.com/syui/Cachet

I am using openshift online (free) and mysql (oc new-app mysql).

http://cachet-syui.1d35.starter-us-east-1.openshiftapps.com/setup

I have followed most of the steps below.

https://github.com/CachetHQ/Docker/issues/175#issuecomment-287696223

```
CACHE_DRIVER=file
SESSION_DRIVER=file
QUEUE_DRIVER=sync
```

Setting `CACHE_DRIVER=apc` will result in 500 error.

**Comment by skebo** [comment]
@jbrooksuk I details on how to fix Error 400
CSRF token validation failed.  I am getting this error consistently with the docker build of 2.4-dev when I attempt to authenticate after I complete the setup.

**Comment by jbrooksuk** [comment]
I shall take a look now.

**Comment by jbrooksuk** [comment]
I've just done a test installation on the latest `2.4` branch and there were no errors. How long did you take to do the installation out of interest?

**Comment by skebo** [comment]
I've done it three or four times without any installation errors and gone through the setup after each installation.  I haven't really timed it though.
After each time I have removed the docker containers and re-run the installation after a fresh git clone and docker built with --no-cache, to insure everything is up to date.

**Comment by jbrooksuk** [comment]
I'd suggest opening in CachetHQ/Docker because Cachet itself has worked for me during a few installs.

**Comment by hensur** [comment]
I just had this issue myself. After a few hours of debugging (I couldn't figure out how to get more verbose logs, setting APP_DEBUG to true didn't change anything).

Anyway, the issue was in the `envsetup.sh` script of the Docker image. This script writes the `.env` file from the supplied environment variables.

However, instead of just ignoring a unset environment variable (like `SESSION_DRIVER`), it writes the variable with it's own defaults to the `.env` file.
In this case the cachet default is `"file"`, which is set in `config/app.php`. `envsetup.sh` sets the variable to `"apc"` [here](https://github.com/CachetHQ/Docker/blob/master/entrypoint.sh#L106).

This affects `SESSION_DOMAIN` and `SESSION_SECURE_COOKIE` as well. 
I could fix my issue (always getting a csrf verificaition fail) by unsetting these variables in the `.env` file.
This would activate the `"file"` driver and sessions would get saved. I don't know why it didn't work with the `apc` driver.

I will create an issue in the Cachet Docker repo, I guess it would be better to ignore unset environment variables and just write the set ones to `.env`, which leaves the rest set to cachet defaults.

**Comment by BirkhoffLee** [comment]
I'm also having the same issue, also running in official Docker setup. (v2.3.14)

**Comment by jbrooksuk** [comment]
@djdefi any suggestions? :)

**Comment by djdefi** [comment]
Sounds like this is sort of working as intended really. All of the settings need to be set at runtime if not using the defaults.
