### ISSUE TITLE
Unable to update items from dashboard.

### ISSUE THREAD

**Issue by Phelzier** [CachetHQ/Cachet#2685]
Hi there,

I can't update the status from the dashboard, I get something went wrong updating the component and then it takes me to the front page.

![image](https://user-images.githubusercontent.com/22050004/29269528-e4fcae80-80e9-11e7-9f00-e124a94b5ce1.png)

I can't arrange the order of components or components group, I get the same error.

Nothing in the error log and I can update the components by creating and editing an Incident.

I am running 2.4.0 and have pulled the latest git.

Check previous report of similar issue and comma is at the end of the lines in ApiController
![image](https://user-images.githubusercontent.com/22050004/29271003-44cf086a-80f1-11e7-85ea-9efcaf2a0cfe.png)

laravel log not changed since install
php-fpm log empty
nginx error log empty

Any pointers where else I could check would be great.

Any ideas?

Thanks,
Ben

**Comment by jbrooksuk** [comment]
Thanks for reporting this @Phelzier, I'll take a look now.

**Comment by paulnus** [comment]
Also running v2.4.0 and I am getting same error. 

I am sleuthing another issue that I may report a a new issue regarding unable to create an issue in the incident/create area. It sends an email, but never makes it to the database and gives a swift error like it is unable to connect to SMTP. Obviously, this will require a new ticket but I find it strange I am unable to open an incident in either fashion.

**Comment by Diogo-Ferreira** [comment]
Same issue here with 2.4. I looked a bit and the problem is that the Ajax request isn't authorized (401), although the cookies and CRSF are sent, it gives a 401. Maybe there's an issue in the auth middleware with Ajax requests.

**Comment by PhiGi87** [comment]
I had the same mistake. I have set the driver of session, cache and queue to database. Now the error is fixed.

**Comment by PhiGi87** [comment]
same problem on sort components (Drag and Drop). :-(

**Comment by pfender** [comment]
Same issue with 2.4 on my 2.4

**Comment by labolanimichele** [comment]
Same issue for me on 2.4.

**Comment by Phelzier** [comment]
Sorry for delayed response, but I confirm that this is now working as intended.  Thanks for you support.
