### ISSUE TITLE
remove dependency on Google fonts

### ISSUE THREAD

**Issue by baszoetekouw** [CachetHQ/Cachet#2686]
Would you be open to a patch removing the dependency on external (Google) webfonts?  I'd rather not signal Google everytime a user visits my site, so I'd like to avoid getting resources from Google where possible.

The fonts that are currently used in Cachet (Open Sans) are available under the Apache License, so it should be fine to distribute them with the Cachet source.

**Comment by vmitchell85** [comment]
There is an option in the settings to disabled it:

![image](https://user-images.githubusercontent.com/1248035/29523383-dde2717c-865a-11e7-8b96-c0c35906cb4a.png)

**Comment by jbrooksuk** [comment]
Correct! Setting exists.

**Comment by Perflyst** [comment]
When will this be available in a release? It is not available in v2.3.15 and in the screenshot I see v2.4.0-dev. I really need this, so is it save to use master for production?

**Comment by jbrooksuk** [comment]
The 2.4 branch is typically stable, though under more active development. No guarantees, of course, but we do try to avoid merging untested and broken code.
