### ISSUE TITLE
Cachet needs unsafe-inline Content-Security-Policy for styles and scripts

### ISSUE THREAD

**Issue by baszoetekouw** [CachetHQ/Cachet#2688]
I was trying to implement a CSP (https://en.wikipedia.org/wiki/Content_Security_Policy) for my Cachet instance.  Apart from references to the Cloudflare CDN and Google Fonts, unfortunately also the unsafe-inline directives are needed for scripts and styles.  This is bad, because it defeats the purpose of the CSP, which is to try to prevent injection attacks and such.

To reproduce, make your webserver output the following CSP header:
```
Content-Security-Policy: default-src * data:; script-src 'self' https://cdnjs.cloudflare.com; style-src 'self' https://fonts.googleapis.com;
```
and observe the errors in your browsers console.  For example, in Chrome:

![console](https://user-images.githubusercontent.com/1461740/29315191-20299f8a-81c2-11e7-9d9a-224e3b002de6.png)

The first error there is caused by this fragment of the main html file:
```html
    <script type="text/javascript">
        var Global = {};
        Global.locale = 'en';
    </script>
```
it should be easy to serve that from an external script file.

The other error are cause by the `all.js`-file setting inline styles.  It's a bit hard to see what the source of those error is, but it seems to be coming from one of Cachet's js-lib dependencies (sparkline, perhaps?).

**Comment by GrahamCampbell** [comment]
Looks like a bug caused by your server settings headers perhaps? https://demo.cachethq.io/ works correctly.

**Comment by GrahamCampbell** [comment]
> I was trying to implement a CSP

Oh yes, it was :P

**Comment by GrahamCampbell** [comment]
> unfortunately also the unsafe-inline directives are needed for scripts and styles

This issue will never go away I'm afraid, since we plan to use vuejs too.

**Comment by jvoisin** [comment]
It's ok, Vuejs is [CSP compliant]( https://vuejs.org/v2/guide/installation.html#CSP-environments ).
