### ISSUE TITLE
[ ? ] APP_URL setting not fully applied.

### ISSUE THREAD

**Issue by MarkL4YG** [CachetHQ/Cachet#2689]
When the URL Cachet is reachable on does not happen to be a domain root (e.g. "example.com/cachet/public" and one properly sets the APP_URL setting to be that 
( ``APP_URL=https://example.com/cachet/public``) Cachet fails to correctly display because some paths do not use the APP_URL setting.
 
This for example is what the stylesheet tries to load from:
```html
<link rel="stylesheet" href="/build/dist/css/all-2812406e36.css">
```
While it should be:
```html
<link rel="stylesheet" href="/cachet/public/build/dist/css/all-2812406e36.css">
```
Is this wanted behavior?

Additional information
---
I am currently trying to set up Cachet for a Gaming Community and sadly the provider does only offer handy-capped VirtualHost support.
That means I can have the directory "\~/status" respond to "status.example.com" but not "\~/status/public" which seems to be the intended web root for Cachet.
Therefore the try is to just use the full path and no sub domain.

Cachet-Build: ``Tag: v2.3.13``

FYI
---
I can't verify if the installation instructions changed in the last months since the documentation page now only redirects to the API docs when trying to access the normal docs.
Due to that I installed Cachet by doing the following:
* Clone the repo and checkout the latest tag
* Editing the ``.env`` file
* ``composer install -o --no-dev``
* ``php artisan app:install``
* ``chmod -R 777 bootstrap``
* ``chmod -R 777 storage``

I am willing to provide further information if needed and thank you for your help in advance.

**Comment by GrahamCampbell** [comment]
Looks like you have not setup routing correctly. NEVER expose your Cachet folder over the internet, only the public folder,.

**Comment by MarkL4YG** [comment]
Routing? The App URL is correctly set up and denying access to the cachet main folder is easy using htaccess.
And as I said, it is not possible to use the public folder as web root. That's what my question is all about....

I know that normally you'd set up a sub domain pointing to the public folder for this - but this isn't an option in this case.

**Comment by GrahamCampbell** [comment]
> And as I said, it is not possible to use the public folder as web root. 

You should not use Cachet then. It is not secure unless you do that.

**Comment by MarkL4YG** [comment]
I guess this leads to nothing - thanks for trying though.

**Comment by jbrooksuk** [comment]
Cachet isn't setup to work how you're trying to use it. Is there a technical reason as to why you can't point to the `public` directory?

**Comment by MarkL4YG** [comment]
@jbrooksuk Yes, the webspace host does not support dynamic virtual hosts. If ``/´` is the root of the webspace I can have "status.example.com" point to ``/status`` but not ``/status/public``.
Also: Since this is a webspace I'd have to block access to the Cachet directory using htaccess anyways so it won't be reachable from the main domain.

**Comment by MarkL4YG** [comment]
There's however a linux server available where I could theoretically install Cachet on. Just that Cachet is also used to display the status of that server - so it would be somewhat pointless to do so.

**Comment by jbrooksuk** [comment]
There's not a lot we can do other than suggesting to use a new web host, I'm sorry 🙈

**Comment by MarkL4YG** [comment]
@jbrooksuk No problem, thank you for your answer. I guess that's what will happen.
