### ISSUE TITLE
validation code?

### ISSUE THREAD

**Issue by elkoralish** [CachetHQ/Cachet#2690]
Hi, I've just installed cachet 2.3.9 (very nice by the way) and I'm having an issue with email subscriptions. This is a test scenario and is repeatable
I have a non-logged in user in safari trying to initially subscribe, everything appears good.
The confirmation mail I recieve also looks ok, clicking on the link generates a 400 error. ( just like Issue #1802 ).
looking in the database, I can see the email and verify_code in the subscribers table.  Checking this vs the link in the email I see the verify code is different. If I manipulate the link, providing the verify code from the database it correctly validates the subscription.
Any idea as to why this may be? I'll include the .env below in anticipation of that question but I'm not sure where to go from here, appears to be a bug?

Appreciate any help you may have, It's quite possibly my fault, but as the email is getting sent with a code that differs from the database I'm at a loss as to how. Thanks in advance

-Chris

**.env**

```
APP_ENV=production
APP_DEBUG=true
APP_URL=http://status.us.local
APP_KEY=base64:1JK5KcPobjr7iEeeXia46SrBW8m2xcleTORZgkDgQpA=

DB_DRIVER=mysql
DB_HOST=localhost
DB_DATABASE=cachet
DB_USERNAME=cachet
DB_PASSWORD=password
DB_PORT=null
DB_PREFIX=null

CACHE_DRIVER=apc
SESSION_DRIVER=apc
QUEUE_DRIVER=database
CACHET_EMOJI=false

MAIL_DRIVER=sendmail
MAIL_HOST=localhost
MAIL_PORT=25
MAIL_USERNAME=null
MAIL_PASSWORD=null
MAIL_ADDRESS=cachet@localhost
MAIL_NAME="Status Update"
MAIL_ENCRYPTION=null

REDIS_HOST=null
REDIS_DATABASE=null
REDIS_PORT=null
```

**Comment by elkoralish** [comment]
Updated to 2.3.13 (damn you numeric sort), problem still persists.

**Comment by elkoralish** [comment]
Any kind of acknowledgement / statement / comment on this? 
I realize it may not be critical, but it can't be that hard to track down and if it's something I'm somehow doing wrong that should also be obvious? It sends out a completely different code from the one in the DB.

**Comment by jbrooksuk** [comment]
Sorry for the delay here @elkoralish I've had some things going on that have meant that open source has had to take a back seat.

I'm not able to verify this issue, I'm afraid. I subscribed an email address and was sent this email:

```
Please confirm your email subscription to Cachet Demo status updates.
http://cachet.app/subscribe/verify/A0u4o88H5cSdkbxM9iR5u5KyPnwkD7WZF6uy2eyOaF

Powered by <a href="https://cachethq.io" class="links">Cachet</a>.
```

In my database, I have:

![image](https://user-images.githubusercontent.com/246103/31045159-24a9042e-a5d5-11e7-9191-af0c4d912795.png)

The `verify_code` matches perfectly. 

Ping @joecohens any idea on this? Seems strange...

**Comment by jbrooksuk** [comment]
I can't recreate this (tried again). Please pull down the latest version and lemme know if this continues to happen.
