### ISSUE TITLE
500 error when adding a metric with no default value

### ISSUE THREAD

**Issue by pendraggon87** [CachetHQ/Cachet#2692]
A 500 error is returned when adding a metric with a blank default value.  Validation should be done to prevent

**Comment by jbrooksuk** [comment]
Are you doing this via the API?

**Comment by vitorbaptista** [comment]
I saw this error as well. To reproduce, simply try creating a new Metric through the admin page leaving the "Default value" empty. I'm running the code from master of a few days ago (I can get the actual commit if you're unable to reproduce).

**Comment by jbrooksuk** [comment]
![image](https://user-images.githubusercontent.com/246103/31045098-18b3e5ea-a5d4-11e7-8ba1-18ac5af2b07a.png)

This is what I see on the 2.4 branch.
