### ISSUE TITLE
Feeding plugin crashes on 2.4 while the incident on component is created 

### ISSUE THREAD

**Issue by nan008** [CachetHQ/Cachet#2693]
I have a problem on 2.4

I am feeding the status from zabbix-cachet plugin

```bash
ERROR: (Trigger Watcher) ClientHttpError[https://status.example.com/api/v1/incidents, 400: {"errors":[{"id":"261aa814-c094-4550-acb9-107f4969d82c","status":400,"title":"Bad Request","detail":"The request cannot be fulfilled due to bad syntax.","meta":{"details":["The notify field must be true or false."]}}]}]
```
when the components are created it is ok - when the status of the service in zabbix is changed, the trigger is fired off and zabbix-cachet plugin is trying to update the status in Cachet and getting the above error.

The owner of the plugin asked me to downgrade to 2.3.14

> It's look like a bug in Cachet. Because this field is optional. Try to use stable version for example 2.3.14.

EDIT:

I downgraded my testing environment to 2.13.14 and can confirm that the trigger is passed correctly in this version to Cachet by the plugin.

![screen shot 2017-08-09 at 10 35 54](https://user-images.githubusercontent.com/18073067/29115290-0d63ee8c-7cef-11e7-8240-d8142ec5f961.png)

I originally commented on this issue on the ticket opened  by leonardoarroyo on 7 Jul - Bad output when creating a component incident without component status #2623 which was marked as a bug

Any update on this problem?

**Comment by jbrooksuk** [comment]
Which field is now optional, sorry?

**Comment by nan008** [comment]
"meta":{"details":["The notify field must be true or false."]}}]}]
Notify field in Post request to api/v1/incidents

**Comment by jbrooksuk** [comment]
Ah right. You need to send `notify=0` or `notify=1`.

**Comment by jbrooksuk** [comment]
This should be defaulted to `0` IMHO.

**Comment by jbrooksuk** [comment]
Odd. We have a default of `true` for notifications. Make sure that the package is sending a `1` or `0` is all I can say for now.
