### ISSUE TITLE
Too many labels on charts Y axis makes it unreadable

### ISSUE THREAD

**Issue by pmajkutewicz** [CachetHQ/Cachet#2696]
Looks like there is too many labels on Y axis :)
![cachet](https://user-images.githubusercontent.com/12598208/29785878-6e88d256-8c29-11e7-9af0-b95636b4fe8f.png)

**Comment by jbrooksuk** [comment]
Yeah, the metric system is crap 😆 it's a known issue.

**Comment by MDXDave** [comment]
You can fix this by adding `maxTicksLimit: 20` in metrics.blade.php
