### ISSUE TITLE
Sort metric points by "created_at" instead of "id"

### ISSUE THREAD

**Issue by vitorbaptista** [CachetHQ/Cachet#2697]
When querying the metric points via the `/api/v1/metrics/METRIC_ID/points` endpoint, they are returned sorted by their `id`. This creates a couple issues:

* Later metric points appear in the last pages of the response
* To find the latest (or first) metric point, one needs to go through each page checking their `created_at` dates

As the metric points are a time series, it makes more sense to sort them by `created_at` instead, ideally in reverse order so the latest points appear in the first pages.

If you agree, I'm happy to send a PR to change this behaviour.

**Comment by jbrooksuk** [comment]
This makes sense to me! A PR would be great!

**Comment by vitorbaptista** [comment]
@jbrooksuk So, I tried writing this change, but was unable to figure out how to assert that the order was right in the tests. From what I could understand, we could simply change this line:

https://github.com/CachetHQ/Cachet/blob/bd34264d3c4a4177ee0b49113c317f4356d4f18f/app/Models/Metric.php#L185

adding `->sortBy('created_at', 'desc')`, so the metric points would be sorted by default everywhere. I was adding the test to `tests/Api/MetricPointTest.php` (although you could argue it should be added to the model's test instead). This is what I got:

```php
    public function testGetMetricPointsSortedByCreatedAt()
    {
        $metric = factory('CachetHQ\Cachet\Models\Metric')->create();
        // Very ugly way of explicitly setting the "created_at" of the metric points
        $metricPoint = [
            factory('CachetHQ\Cachet\Models\MetricPoint')->create([
                'metric_id' => $metric->id,
                'created_at' => mktime(0, 0, 0, 1, 1, 2017),
            ]),
            factory('CachetHQ\Cachet\Models\MetricPoint')->create([
                'metric_id' => $metric->id,
                'created_at' => mktime(0, 0, 0, 1, 1, 2015),
            ]),
            factory('CachetHQ\Cachet\Models\MetricPoint')->create([
                'metric_id' => $metric->id,
                'created_at' => mktime(0, 0, 0, 1, 1, 2016),
            ]),
        ]

        $this->get("/api/v1/metrics/{$metric->id}/points");

        // Assert that the metric points are returned in the order we want them.
        // I tried with seeJsonContains, but couldn't work it out.

        $this->assertResponseOk();
    }
```

I won't have much more time to work on this, but I'm hoping that these pointers would help someone else to finish the patch.

**Comment by jbrooksuk** [comment]
@vitorbaptista do you want to submit a PR for this?

**Comment by jbrooksuk** [comment]
@vitorbaptista any update? :)

**Comment by jbrooksuk** [comment]
@vitorbaptista I'm going to PR this change now.

**Comment by jbrooksuk** [comment]
Closed by f98ae4d3

**Comment by jbrooksuk** [comment]
I don't really know how to test this very well either. @joecohens do you have any thoughts? One thing I'm thinking would be a Snapshot test?

**Comment by joecohens** [comment]
The example by @vitorbaptista looks ok to me for testing this. Just we just need to create different metric points and set the date to them. In the test, just check if the order is right. I'll send a PR for tests soon

**Comment by joecohens** [comment]
Done here https://github.com/CachetHQ/Cachet/pull/3153

**Comment by jbrooksuk** [comment]
Thanks!

**Comment by jbrooksuk** [comment]
@joecohens it looks like tests are failing? I was on my phone so didn’t see this.

**Comment by joecohens** [comment]
@jbrooksuk It was another error since we round the created_at seconds, I've fixed it on https://github.com/CachetHQ/Cachet/pull/3156
