### ISSUE TITLE
500 Error

### ISSUE THREAD

**Issue by tb582** [CachetHQ/Cachet#2700]
[✓ ] I am running the latest release version of Cachet.
    [✓ ] I am running at least PHP 5.5.9. You can check this by running php -v.
    [✓ ] I have ran rm -rf bootstrap/cache/*.

Expected behaviour

*Should be able to access dashboard.
Actual behaviour

*Getting HTTP Error 500. 

```
[Fri Sep 01 15:56:43.517910 2017] [mpm_prefork:notice] [pid 30211] AH00170: caught SIGWINCH, shutting down gracefully
[Fri Sep 01 15:56:44.774592 2017] [core:notice] [pid 30482] SELinux policy enabled; httpd running as context system_u:system_r:httpd_t:s0
[Fri Sep 01 15:56:44.776577 2017] [suexec:notice] [pid 30482] AH01232: suEXEC mechanism enabled (wrapper: /usr/sbin/suexec)
[Fri Sep 01 15:56:44.858499 2017] [auth_digest:notice] [pid 30482] AH01757: generating secret for digest authentication ...
[Fri Sep 01 15:56:44.859716 2017] [lbmethod_heartbeat:notice] [pid 30482] AH02282: No slotmem from mod_heartmonitor
[Fri Sep 01 15:56:44.909455 2017] [mpm_prefork:notice] [pid 30482] AH00163: Apache/2.4.6 (CentOS) PHP/7.1.9 configured -- resuming normal operations
[Fri Sep 01 15:56:44.909501 2017] [core:notice] [pid 30482] AH00094: Command line: '/usr/sbin/httpd -D FOREGROUND'
[Fri Sep 01 15:56:48.107309 2017] [php7:error] [pid 30483] [client 10.23.5.126:64698] PHP Fatal error:  Uncaught UnexpectedValueException: The stream or file "/var/www/Cachet/storage/logs/laravel-2017-09-01.log" could not be opened: failed to open stream: Permission denied in /var/www/Cachet/vendor/monolog/monolog/src/Monolog/Handler/StreamHandler.php:107\nStack trace:\n#0 /var/www/Cachet/vendor/monolog/monolog/src/Monolog/Handler/RotatingFileHandler.php(107): Monolog\\Handler\\StreamHandler->write(Array)\n#1 /var/www/Cachet/vendor/monolog/monolog/src/Monolog/Handler/AbstractProcessingHandler.php(37): Monolog\\Handler\\RotatingFileHandler->write(Array)\n#2 /var/www/Cachet/vendor/monolog/monolog/src/Monolog/Logger.php(337): Monolog\\Handler\\AbstractProcessingHandler->handle(Array)\n#3 /var/www/Cachet/vendor/monolog/monolog/src/Monolog/Logger.php(616): Monolog\\Logger->addRecord(400, Object(UnexpectedValueException), Array)\n#4 /var/www/Cachet/vendor/laravel/framework/src/Illuminate/Log/Writer.php(203): Monolog\\Logger->error(Object(UnexpectedValueException), Array)\n#5 /var/www/Cachet/vendor/laravel/framework/src/Illuminate/L in /var/www/Cachet/vendor/monolog/monolog/src/Monolog/Handler/StreamHandler.php on line 107
[Fri Sep 01 15:56:48.108633 2017] [php7:error] [pid 30483] [client 10.23.5.126:64698] PHP Fatal error:  Uncaught UnexpectedValueException: The stream or file "/var/www/Cachet/storage/logs/laravel-2017-09-01.log" could not be opened: failed to open stream: Permission denied in /var/www/Cachet/vendor/monolog/monolog/src/Monolog/Handler/StreamHandler.php:107\nStack trace:\n#0 /var/www/Cachet/vendor/monolog/monolog/src/Monolog/Handler/RotatingFileHandler.php(107): Monolog\\Handler\\StreamHandler->write(Array)\n#1 /var/www/Cachet/vendor/monolog/monolog/src/Monolog/Handler/AbstractProcessingHandler.php(37): Monolog\\Handler\\RotatingFileHandler->write(Array)\n#2 /var/www/Cachet/vendor/monolog/monolog/src/Monolog/Logger.php(337): Monolog\\Handler\\AbstractProcessingHandler->handle(Array)\n#3 /var/www/Cachet/vendor/monolog/monolog/src/Monolog/Logger.php(616): Monolog\\Logger->addRecord(400, Object(UnexpectedValueException), Array)\n#4 /var/www/Cachet/vendor/laravel/framework/src/Illuminate/Log/Writer.php(203): Monolog\\Logger->error(Object(UnexpectedValueException), Array)\n#5 /var/www/Cachet/vendor/laravel/framework/src/Illuminate/L in /var/www/Cachet/vendor/monolog/monolog/src/Monolog/Handler/StreamHandler.php on line 107
```
Checked permissions and all seems well

`drwxrwxrwx. 15 apache apache    242 Aug 31 19:52 app
-rwxrwxrwx.  1 apache apache   1650 Aug 31 19:52 artisan
drwxrwxrwx.  4 apache apache     68 Aug 31 19:52 bootstrap
-rwxrwxrwx.  1 apache apache   3216 Aug 31 19:52 CODE_OF_CONDUCT.md
-rwxrwxrwx.  1 apache apache   3384 Sep  1 14:45 composer.json
-rwxrwxrwx.  1 apache apache 223023 Aug 31 19:52 composer.lock
drwxrwxrwx.  2 apache apache   4096 Aug 31 19:52 config
-rwxrwxrwx.  1 apache apache   2806 Aug 31 19:52 CONTRIBUTING.md
-rwxrwxrwx.  1 apache apache    240 Aug 31 19:52 crowdin.yaml
drwxrwxrwx.  6 apache apache     87 Aug 31 19:52 database
-rwxrwxrwx.  1 apache apache  14848 Jun 24 15:08 epel-release-latest-7.noarch.rpm
-rwxrwxrwx.  1 apache apache   1504 Aug 31 19:52 LICENSE
-rwxrwxrwx.  1 apache apache   1728 Aug 31 19:52 package.json
-rwxrwxrwx.  1 apache apache 329440 Aug 31 19:52 package-lock.json
-rwxrwxrwx.  1 apache apache   1584 Aug 31 19:52 phpunit.xml.dist
drwxrwxrwx.  5 apache apache    188 Sep  1 15:10 public
-rwxrwxrwx.  1 apache apache   2760 Aug 31 19:52 README.md
drwxrwxrwx.  5 apache apache     45 Aug 31 19:52 resources
-rwxrwxrwx.  1 apache apache    405 Aug 31 19:52 server.php
drwxrwxrwx.  5 apache apache     64 Aug 31 19:52 storage
drwxrwxrwx.  8 apache apache    170 Aug 31 19:52 tests
drwxr-xr-x. 38 apache apache   4096 Sep  1 14:51 vendor
-rwxrwxrwx.  1 apache apache     10 Aug 31 19:52 VERSION
-rwxrwxrwx.  1 apache apache   2224 Aug 31 19:52 webpack.mix.js`

Confirmed httpd is running as apache
`[root@app Cachet]# ps -ef | grep -e apache -e httpd
root     30482     1  0 15:56 ?        00:00:00 /usr/sbin/httpd -DFOREGROUND
apache   30483 30482  0 15:56 ?        00:00:00 /usr/sbin/httpd -DFOREGROUND
apache   30484 30482  0 15:56 ?        00:00:00 /usr/sbin/httpd -DFOREGROUND
apache   30485 30482  0 15:56 ?        00:00:00 /usr/sbin/httpd -DFOREGROUND
apache   30486 30482  0 15:56 ?        00:00:00 /usr/sbin/httpd -DFOREGROUND
apache   30487 30482  0 15:56 ?        00:00:00 /usr/sbin/httpd -DFOREGROUND
root     30512 26183  0 16:02 pts/0    00:00:00 grep --color=auto -e apache -e httpd`

**Comment by Si-Richards** [comment]
Check SELinux is disabled (temporarily stop Firewalld too)
check your settings file .ENV
Confirm you've run php artisan cache:clear and php artisan app:update

**Comment by jbrooksuk** [comment]
Not a Cachet bug :)
