### ISSUE TITLE
Release archives don't contain appropriate files

### ISSUE THREAD

**Issue by JimboJoe** [CachetHQ/Cachet#2703]
Hi, when downloading the [latest release (2.3.12)](https://github.com/CachetHQ/Cachet/releases) on github, some files don't seem to be up-to-date (for instance, `config/setting.php` doesn't match the git master file, and doesn't show the latest settings)... Is that normal?

Thanks! 

P.S. : For your information, I'm building a [YunoHost package](https://github.com/YunoHost-Apps/cachet_ynh) for Cachet, hence my question about your release files, because we're automating installation ;-)

**Comment by jbrooksuk** [comment]
Hmm, it might be that we've since changed files in the `2.3` branch but not yet tagged it?
