### ISSUE TITLE
Redirect error while setting up cachet

### ISSUE THREAD

**Issue by Jason667** [CachetHQ/Cachet#2704]
Tried to install cachet on OpenSUSE 42.2 with PHP 7.0.8 using this installation guide:

https://docs.cachethq.io/v1.0/docs/installing-cachet

Completed all steps with no errors. When I try o access my instance apache throws following lines.

Access Log:

> 145.228.79.136 - - [07/Sep/2017:14:29:31 +0200] "GET /monitor/ HTTP/1.1" 302 424 "-" "Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/61.0.3163.79 Safari/537.36"
145.228.79.136 - - [07/Sep/2017:14:29:31 +0200] "GET /monitor/ HTTP/1.1" 302 424 "-" "Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/61.0.3163.79 Safari/537.36"
145.228.79.136 - - [07/Sep/2017:14:29:31 +0200] "GET /monitor/setup HTTP/1.1" 302 299 "-" "Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/61.0.3163.79 Safari/537.36"
145.228.79.136 - - [07/Sep/2017:14:29:31 +0200] "GET /monitor/setup HTTP/1.1" 302 299 "-" "Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/61.0.3163.79 Safari/537.36"

Error Log:

> [Thu Sep 07 14:39:25.347091 2017] [core:error] [pid 9048] [client 145.228.79.136:49511] AH00124: Request exceeded the limit of 10 internal redirects due to probable configuration error. Use 'LimitInternalRecursion' to increase the limit if necessary. Use 'LogLevel debug' to get a backtrace.

My .env lokes like this:

> APP_ENV=production`
APP_DEBUG=false
APP_URL=http://localhost
APP_KEY=base65:Z74zjC2yIDUoJiib73YgyDdJiT3KlUILnQULzZTfh0o=
DB_DRIVER=mysql
DB_HOST=localhost
DB_UNIX_SOCKET=null
DB_DATABASE=cachet
DB_USERNAME=cachet
DB_PASSWORD=********
DB_PORT=3306
DB_PREFIX=null
CACHE_DRIVER=file
SESSION_DRIVER=file
QUEUE_DRIVER=sync
CACHET_BEACON=true
CACHET_EMOJI=false
CACHET_AUTO_TWITTER=true
MAIL_DRIVER=log
MAIL_HOST=null
MAIL_PORT=null
MAIL_USERNAME=null
MAIL_PASSWORD=null
MAIL_ADDRESS=null
MAIL_NAME=null
MAIL_ENCRYPTION=tls
REDIS_HOST=null
REDIS_DATABASE=null
REDIS_PORT=null
GITHUB_TOKEN=null
NEXMO_KEY=null
NEXMO_SECRET=null
NEXMO_SMS_FROM=Cachet

**Comment by jbrooksuk** [comment]
`/monitor` isn't anything to do with Cachet...
