### ISSUE TITLE
Log failed login attempts for fail2ban

### ISSUE THREAD

**Issue by JimboJoe** [CachetHQ/Cachet#2705]
Hello,
Would it be possible to define a log file/log pattern to allow administrators to define a [fail2ban](http://www.fail2ban.org/wiki/index.php/Main_Page) jail for Cachet?
Thanks!

**Comment by jbrooksuk** [comment]
I've no idea I'm afraid! Do you have any examples?

**Comment by JimboJoe** [comment]
For example, here is a [PR](https://github.com/wallabag/wallabag/pull/3195) implemented in Wallabag on the very same request :wink:

**Comment by jbrooksuk** [comment]
I see!

So you'd setup fail2ban to look at the log file, specifically for certain messages and action based on that?

**Comment by JimboJoe** [comment]
Yes, based on log files output by Cachet, we could setup a fail2ban jail to enhance the security of the server 👍

**Comment by jbrooksuk** [comment]
Not a bad idea. I'll have a think.

**Comment by jbrooksuk** [comment]
Thank you for your input on Cachet 2.x. We are shifting our attention and resources to Cachet 3.x and will no longer be supporting the 2.x version. If your feedback or issue is relevant to the 3.x series, we encourage you to engage with the new branch.

For more information on the Cachet rebuild and our plans for 3.x, you can read the announcement [here](https://github.com/CachetHQ/Cachet/discussions/4342).

We appreciate your understanding and look forward to your contributions to the new version.
