### ISSUE TITLE
HTTPD Error 500

### ISSUE THREAD

**Issue by barreeeiroo** [CachetHQ/Cachet#2706]
OS: CentOS7
Machine: GoogleComputeEngine f1-micro

I get this when trying to access my status page:
![image](https://user-images.githubusercontent.com/19251112/30240822-e910a06a-9577-11e7-87b4-503c16bcea59.png)
And this is what I found in HTTPD error_log: `[Sat Sep 09 13:57:58.424463 2017] [php7:error] [pid 6249] [client 213.143.50.23:64960] PHP Fatal error:  Uncaught UnexpectedValueException: The stream or file "/var/www/Cachet/storage/logs/laravel-2017-09-09.log" could not be opened: failed to open stream: Permission denied in /var/www/Cachet/vendor/monolog/monolog/src/Monolog/Handler/StreamHandler.php:107\nStack trace:\n#0 /var/www/Cachet/vendor/monolog/monolog/src/Monolog/Handler/RotatingFileHandler.php(107): Monolog\\Handler\\StreamHandler->write(Array)\n#1 /var/www/Cachet/vendor/monolog/monolog/src/Monolog/Handler/AbstractProcessingHandler.php(37): Monolog\\Handler\\RotatingFileHandler->write(Array)\n#2 /var/www/Cachet/vendor/monolog/monolog/src/Monolog/Logger.php(336): Monolog\\Handler\\AbstractProcessingHandler->handle(Array)\n#3 /var/www/Cachet/vendor/monolog/monolog/src/Monolog/Logger.php(643): Monolog\\Logger->addRecord(500, Object(Symfony\\Component\\Debug\\Exception\\FatalErrorException), Array)\n#4 /var/www/Cachet/vendor/laravel/framework/src/Illuminate/Log/Writer.php(202): Monolog\\Logger->critical(Object(Symfony\\Component\\Debug\\Exception\\FatalErrorException), Array) in /var/www/Cachet/vendor/monolog/monolog/src/Monolog/Handler/StreamHandler.php on line 107`

**Comment by barreeeiroo** [comment]
And yes, I've already checked permissions

**Comment by judge2020** [comment]
Try running 
```
egrep -i '^user|^group' /etc/httpd/conf/httpd.conf
```
Get the username and group then run
```
chown -R <USER>:<GROUP> /var/www/storage
```

**Comment by barreeeiroo** [comment]
I've already done that

**Comment by judge2020** [comment]
What is the output of `ls -l /var/www/Cachet/storage`?

**Comment by barreeeiroo** [comment]
I've changed the OS to Debian and now it works
IDk why it show that error

**Comment by jbrooksuk** [comment]
Google Compute Engine isn't officially supported, just a heads up.

**Comment by barreeeiroo** [comment]
It runs perfectly on GCE with Debian
