### ISSUE TITLE
Weird behaviour with UpTimeRobot

### ISSUE THREAD

**Issue by barreeeiroo** [CachetHQ/Cachet#2707]
My status site has a graph integrated with UpTimeRobot
The status site is: https://status.makeroid.io
But in the values for an hour, it only shows values like 100 or 200 ms, but when I login to UpTimeRobot I see more accurate values
Any idea if what's happening?

**Comment by barreeeiroo** [comment]
I made this simple script to solve it:
https://gist.github.com/barreeeiroo/01188e58ad769d0a401a2867814bcc82
It runs with PHP, and must be executed with crontab

**Comment by jbrooksuk** [comment]
Yeah, the metric system in Cachet isn't very powerful. We're aware it needs an overhaul :) @GrahamCampbell has many plans!
