### ISSUE TITLE
PDOException:  Invalid text representation: 7 ERROR:  invalid input syntax for integer

### ISSUE THREAD

**Issue by MarcinOrlowski** [CachetHQ/Cachet#2709]
While playing with demo app's logs I noticed this (https://dev.cachethq.io/dashboard/settings/log):

> [2017-09-11 09:57:05] production.ERROR: PDOException: SQLSTATE[22P02]: Invalid text representation: 7 ERROR:  invalid input syntax for integer: "" in /home/boris/cachet-dev/releases/20170725105310/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:91

Which may indication of input data validation issue.

The whole stacktrace below:

> [2017-09-11 09:57:05] production.ERROR: PDOException: SQLSTATE[22P02]: Invalid text representation: 7 ERROR:  invalid input syntax for integer: "" in /home/boris/cachet-dev/releases/20170725105310/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:91
> Stack trace:
> #0 /home/boris/cachet-dev/releases/20170725105310/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php(91): PDOStatement->execute(NULL)
> #1 /home/boris/cachet-dev/releases/20170725105310/vendor/laravel/framework/src/Illuminate/Database/Connection.php(323): Doctrine\DBAL\Driver\PDOStatement->execute()
> #2 /home/boris/cachet-dev/releases/20170725105310/vendor/laravel/framework/src/Illuminate/Database/Connection.php(640): Illuminate\Database\Connection->Illuminate\Database\{closure}('select * from "...', Array)
> #3 /home/boris/cachet-dev/releases/20170725105310/vendor/laravel/framework/src/Illuminate/Database/Connection.php(607): Illuminate\Database\Connection->runQueryCallback('select * from "...', Array, Object(Closure))
> #4 /home/boris/cachet-dev/releases/20170725105310/vendor/laravel/framework/src/Illuminate/Database/Connection.php(326): Illuminate\Database\Connection->run('select * from "...', Array, Object(Closure))
> #5 /home/boris/cachet-dev/releases/20170725105310/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(1710): Illuminate\Database\Connection->select('select * from "...', Array, true)
> #6 /home/boris/cachet-dev/releases/20170725105310/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(1695): Illuminate\Database\Query\Builder->runSelect()
> #7 /home/boris/cachet-dev/releases/20170725105310/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php(462): Illuminate\Database\Query\Builder->get(Array)
> #8 /home/boris/cachet-dev/releases/20170725105310/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php(446): Illuminate\Database\Eloquent\Builder->getModels(Array)
> #9 /home/boris/cachet-dev/releases/20170725105310/vendor/laravel/framework/src/Illuminate/Database/Concerns/BuildsQueries.php(75): Illuminate\Database\Eloquent\Builder->get(Array)
> #10 /home/boris/cachet-dev/releases/20170725105310/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php(272): Illuminate\Database\Eloquent\Builder->first(Array)
> #11 /home/boris/cachet-dev/releases/20170725105310/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(1357): Illuminate\Database\Eloquent\Builder->find('')
> #12 /home/boris/cachet-dev/releases/20170725105310/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(1369): Illuminate\Database\Eloquent\Model->__call('find', Array)
> #13 /home/boris/cachet-dev/releases/20170725105310/app/Bus/Handlers/Commands/Incident/CreateIncidentCommandHandler.php(117): Illuminate\Database\Eloquent\Model::__callStatic('find', Array)
> #14 /home/boris/cachet-dev/releases/20170725105310/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php(90): CachetHQ\Cachet\Bus\Handlers\Commands\Incident\CreateIncidentCommandHandler->handle(Object(CachetHQ\Cachet\Bus\Commands\Incident\CreateIncidentCommand))
> #15 /home/boris/cachet-dev/releases/20170725105310/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(114): Illuminate\Bus\Dispatcher->Illuminate\Bus\{closure}(Object(CachetHQ\Cachet\Bus\Commands\Incident\CreateIncidentCommand))
> #16 /home/boris/cachet-dev/releases/20170725105310/vendor/alt-three/validator/src/ValidatingMiddleware.php(61): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(CachetHQ\Cachet\Bus\Commands\Incident\CreateIncidentCommand))
> #17 /home/boris/cachet-dev/releases/20170725105310/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(148): AltThree\Validator\ValidatingMiddleware->handle(Object(CachetHQ\Cachet\Bus\Commands\Incident\CreateIncidentCommand), Object(Closure))
> #18 /home/boris/cachet-dev/releases/20170725105310/app/Bus/Middleware/UseDatabaseTransactions.php(35): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(CachetHQ\Cachet\Bus\Commands\Incident\CreateIncidentCommand))
> #19 /home/boris/cachet-dev/releases/20170725105310/vendor/laravel/framework/src/Illuminate/Database/Concerns/ManagesTransactions.php(29): CachetHQ\Cachet\Bus\Middleware\UseDatabaseTransactions->CachetHQ\Cachet\Bus\Middleware\{closure}(Object(Illuminate\Database\PostgresConnection))
> #20 /home/boris/cachet-dev/releases/20170725105310/vendor/laravel/framework/src/Illuminate/Database/DatabaseManager.php(324): Illuminate\Database\Connection->transaction(Object(Closure))
> #21 /home/boris/cachet-dev/releases/20170725105310/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(221): Illuminate\Database\DatabaseManager->__call('transaction', Array)
> #22 /home/boris/cachet-dev/releases/20170725105310/app/Bus/Middleware/UseDatabaseTransactions.php(36): Illuminate\Support\Facades\Facade::__callStatic('transaction', Array)
> #23 /home/boris/cachet-dev/releases/20170725105310/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(148): CachetHQ\Cachet\Bus\Middleware\UseDatabaseTransactions->handle(Object(CachetHQ\Cachet\Bus\Commands\Incident\CreateIncidentCommand), Object(Closure))
> #24 /home/boris/cachet-dev/releases/20170725105310/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(102): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(CachetHQ\Cachet\Bus\Commands\Incident\CreateIncidentCommand))
> #25 /home/boris/cachet-dev/releases/20170725105310/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php(98): Illuminate\Pipeline\Pipeline->then(Object(Closure))
> #26 /home/boris/cachet-dev/releases/20170725105310/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php(75): Illuminate\Bus\Dispatcher->dispatchNow(Object(CachetHQ\Cachet\Bus\Commands\Incident\CreateIncidentCommand))
> #27 /home/boris/cachet-dev/releases/20170725105310/vendor/laravel/framework/src/Illuminate/Foundation/helpers.php(378): Illuminate\Bus\Dispatcher->dispatch(Object(CachetHQ\Cachet\Bus\Commands\Incident\CreateIncidentCommand))
> #28 /home/boris/cachet-dev/releases/20170725105310/app/Http/Controllers/Dashboard/IncidentController.php(122): dispatch(Object(CachetHQ\Cachet\Bus\Commands\Incident\CreateIncidentCommand))
> #29 [internal function]: CachetHQ\Cachet\Http\Controllers\Dashboard\IncidentController->createIncidentAction()
> #30 /home/boris/cachet-dev/releases/20170725105310/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(55): call_user_func_array(Array, Array)
> #31 /home/boris/cachet-dev/releases/20170725105310/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(44): Illuminate\Routing\Controller->callAction('createIncidentA...', Array)
> #32 /home/boris/cachet-dev/releases/20170725105310/vendor/laravel/framework/src/Illuminate/Routing/Route.php(203): Illuminate\Routing\ControllerDispatcher->dispatch(Object(Illuminate\Routing\Route), Object(CachetHQ\Cachet\Http\Controllers\Dashboard\IncidentController), 'createIncidentA...')
> #33 /home/boris/cachet-dev/releases/20170725105310/vendor/laravel/framework/src/Illuminate/Routing/Route.php(160): Illuminate\Routing\Route->runController()
> #34 /home/boris/cachet-dev/releases/20170725105310/vendor/laravel/framework/src/Illuminate/Routing/Router.php(574): Illuminate\Routing\Route->run()
> #35 /home/boris/cachet-dev/releases/20170725105310/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(30): Illuminate\Routing\Router->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
> #36 /home/boris/cachet-dev/releases/20170725105310/app/Http/Middleware/Authenticate.php(61): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
> #37 /home/boris/cachet-dev/releases/20170725105310/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(148): CachetHQ\Cachet\Http\Middleware\Authenticate->handle(Object(Illuminate\Http\Request), Object(Closure))
> #38 /home/boris/cachet-dev/releases/20170725105310/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
> #39 /home/boris/cachet-dev/releases/20170725105310/vendor/laravel/framework/src/Illuminate/Routing/Middleware/SubstituteBindings.php(41): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
> #40 /home/boris/cachet-dev/releases/20170725105310/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(148): Illuminate\Routing\Middleware\SubstituteBindings->handle(Object(Illuminate\Http\Request), Object(Closure))
> #41 /home/boris/cachet-dev/releases/20170725105310/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
> #42 /home/boris/cachet-dev/releases/20170725105310/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/VerifyCsrfToken.php(65): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
> #43 /home/boris/cachet-dev/releases/20170725105310/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(148): Illuminate\Foundation\Http\Middleware\VerifyCsrfToken->handle(Object(Illuminate\Http\Request), Object(Closure))
> #44 /home/boris/cachet-dev/releases/20170725105310/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
> #45 /home/boris/cachet-dev/releases/20170725105310/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php(49): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
> #46 /home/boris/cachet-dev/releases/20170725105310/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(148): Illuminate\View\Middleware\ShareErrorsFromSession->handle(Object(Illuminate\Http\Request), Object(Closure))
> #47 /home/boris/cachet-dev/releases/20170725105310/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
> #48 /home/boris/cachet-dev/releases/20170725105310/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(64): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
> #49 /home/boris/cachet-dev/releases/20170725105310/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(148): Illuminate\Session\Middleware\StartSession->handle(Object(Illuminate\Http\Request), Object(Closure))
> #50 /home/boris/cachet-dev/releases/20170725105310/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
> #51 /home/boris/cachet-dev/releases/20170725105310/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php(37): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
> #52 /home/boris/cachet-dev/releases/20170725105310/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(148): Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse->handle(Object(Illuminate\Http\Request), Object(Closure))
> #53 /home/boris/cachet-dev/releases/20170725105310/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
> #54 /home/boris/cachet-dev/releases/20170725105310/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php(59): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
> #55 /home/boris/cachet-dev/releases/20170725105310/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(148): Illuminate\Cookie\Middleware\EncryptCookies->handle(Object(Illuminate\Http\Request), Object(Closure))
> #56 /home/boris/cachet-dev/releases/20170725105310/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
> #57 /home/boris/cachet-dev/releases/20170725105310/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(102): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
> #58 /home/boris/cachet-dev/releases/20170725105310/vendor/laravel/framework/src/Illuminate/Routing/Router.php(576): Illuminate\Pipeline\Pipeline->then(Object(Closure))
> #59 /home/boris/cachet-dev/releases/20170725105310/vendor/laravel/framework/src/Illuminate/Routing/Router.php(535): Illuminate\Routing\Router->runRouteWithinStack(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request))
> #60 /home/boris/cachet-dev/releases/20170725105310/vendor/laravel/framework/src/Illuminate/Routing/Router.php(513): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
> #61 /home/boris/cachet-dev/releases/20170725105310/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(176): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
> #62 /home/boris/cachet-dev/releases/20170725105310/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(30): Illuminate\Foundation\Http\Kernel->Illuminate\Foundation\Http\{closure}(Object(Illuminate\Http\Request))
> #63 /home/boris/cachet-dev/releases/20170725105310/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/CheckForMaintenanceMode.php(46): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
> #64 /home/boris/cachet-dev/releases/20170725105310/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(148): Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode->handle(Object(Illuminate\Http\Request), Object(Closure))
> #65 /home/boris/cachet-dev/releases/20170725105310/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
> #66 /home/boris/cachet-dev/releases/20170725105310/vendor/fideloper/proxy/src/TrustProxies.php(56): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
> #67 /home/boris/cachet-dev/releases/20170725105310/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(148): Fideloper\Proxy\TrustProxies->handle(Object(Illuminate\Http\Request), Object(Closure))
> #68 /home/boris/cachet-dev/releases/20170725105310/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
> #69 /home/boris/cachet-dev/releases/20170725105310/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(102): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
> #70 /home/boris/cachet-dev/releases/20170725105310/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(151): Illuminate\Pipeline\Pipeline->then(Object(Closure))
> #71 /home/boris/cachet-dev/releases/20170725105310/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(116): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter(Object(Illuminate\Http\Request))
> #72 /home/boris/cachet-dev/releases/20170725105310/public/index.php(54): Illuminate\Foundation\Http\Kernel->handle(Object(Illuminate\Http\Request))
> #73 {main}

**Comment by jbrooksuk** [comment]
I need more info, please :)

**Comment by MarcinOrlowski** [comment]
Its your demo instance so you can easily get what you need yourself ;)

**Comment by jbrooksuk** [comment]
Oh, you didn't do anything and then notice this, it was already in there?

**Comment by MarcinOrlowski** [comment]
Well, frankly I do not know I was the one who triggered it or not. I just spotted this log entries and as the timestamp was fresh, I thought you may want to be notified about this to inspect.

**Comment by jbrooksuk** [comment]
That's fine @MarcinOrlowski. I just wanted to know if you happened to know if you caused it or not so that we could debug further.

I'll keep an eye on it.
