### ISSUE TITLE
php artisan app:update PHP Fatal error: Uncaught Error: Class name must be a valid object or a string in 

### ISSUE THREAD

**Issue by nixmomo** [CachetHQ/Cachet#2710]
Hi,

after git checkout to the new 2.4 Branch i get this composer error

PHP Version 7.1
Waiting for a fix or to know what i should do to fix it

`Loading composer repositories with package information
Updating dependencies (including require-dev)
Package operations: 47 installs, 51 updates, 9 removals
  - Removing dnoegel/php-xdg-base-dir (0.1)
  - Removing jakub-onderka/php-console-highlighter (v0.3.2)
  - Removing jakub-onderka/php-console-color (0.1)
  - Removing symfony/polyfill-php56 (v1.2.0)
  - Removing symfony/polyfill-util (v1.2.0)
  - Removing psy/psysh (v0.7.2)
  - Removing jeremeamia/superclosure (2.2.0)
  - Removing classpreloader/classpreloader (3.0.0)
  - Removing fedeisas/laravel-mail-css-inliner (1.5)
  - Updating league/commonmark (0.13.4 => 0.15.6): Downloading (100%)
  - Updating symfony/polyfill-mbstring (v1.2.0 => v1.5.0): Downloading (100%)     - Updating symfony/http-foundation (v3.0.9 => v3.3.9): Downloading (100%)       - Updating symfony/event-dispatcher (v3.1.5 => v3.3.9): Downloading (100%)      - Updating symfony/debug (v3.0.9 => v3.3.9): Downloading (100%)
  - Updating swiftmailer/swiftmailer (v5.4.3 => v5.4.8): Downloading (100%)       - Updating symfony/var-dumper (v3.0.9 => v3.3.9): Downloading (100%)
  - Updating symfony/console (v3.0.9 => v3.3.9): Downloading (100%)
  - Updating symfony/translation (v3.0.9 => v3.3.9): Downloading (100%)
  - Updating nesbot/carbon (1.21.0 => 1.22.1): Downloading (100%)
  - Updating mtdowling/cron-expression (v1.1.0 => v1.2.0): Downloading (100%)     - Updating monolog/monolog (1.21.0 => 1.23.0): Downloading (100%)
  - Updating league/flysystem (1.0.28 => 1.0.41): Downloading (100%)
  - Updating nikic/php-parser (v2.1.1 => v3.1.1): Downloading (100%)
  - Updating doctrine/inflector (v1.1.0 => v1.2.0): Downloading (100%)
  - Updating symfony/css-selector (v3.1.5 => v3.3.9): Downloading (100%)          - Updating tijsverkoyen/css-to-inline-styles (1.5.5 => 2.2.0): Downloading (100%)
  - Updating symfony/routing (v3.0.9 => v3.3.9): Downloading (100%)
  - Updating symfony/process (v3.0.9 => v3.3.9): Downloading (100%)
  - Updating symfony/http-kernel (v3.0.9 => v3.3.9): Downloading (100%)
  - Updating symfony/finder (v3.0.9 => v3.3.9): Downloading (100%)
  - Updating paragonie/random_compat (v1.4.1 => v2.0.10): Downloading (100%)      - Installing ramsey/uuid (3.7.0): Downloading (100%)
  - Installing erusev/parsedown (1.6.3): Downloading (100%)
  - Updating laravel/framework (v5.2.45 => v5.4.36): Downloading (100%)
  - Updating guzzlehttp/psr7 (1.3.1 => 1.4.2): Downloading (100%)
  - Updating guzzlehttp/promises (1.2.0 => v1.3.1): Downloading (100%)
  - Updating guzzlehttp/guzzle (6.2.2 => 6.3.0): Downloading (100%)
  - Updating alt-three/emoji (v3.1.0 => v4.1.0): Downloading (100%)
  - Updating alt-three/validator (v1.5.0 => v2.0.0): Downloading (100%)
  - Updating backup-manager/backup-manager (1.1.1 => 1.1.3): Downloading (100%)   - Removing backup-manager/laravel (1.1.1)
  - Installing backup-manager/laravel (dev-master df53f9c): Downloading (100%)    - Updating doctrine/collections (v1.3.0 => v1.5.0): Downloading (100%)          - Updating doctrine/cache (v1.6.0 => v1.7.1): Downloading (100%)
  - Updating doctrine/annotations (v1.2.7 => v1.5.0): Downloading (100%)          - Updating doctrine/common (v2.6.1 => v2.7.3): Downloading (100%)
  - Updating doctrine/dbal (v2.5.5 => v2.5.13): Downloading (100%)
  - Updating graham-campbell/markdown (v6.1.0 => v7.1.0): Downloading (100%)      - Updating mccool/laravel-auto-presenter (4.3.0 => 5.0.0): Downloading (100%)   - Updating alt-three/badger (v3.1.0 => v3.2.0): Downloading (100%)
  - Updating alt-three/bus (v1.1.0 => v2.1.0): Downloading (100%)
  - Updating alt-three/throttle (v1.1.0 => v1.2.0): Downloading (100%)
  - Updating mtdowling/jmespath.php (2.3.0 => 2.4.0): Downloading (100%)          - Updating aws/aws-sdk-php (3.19.14 => 3.36.5): Downloading (100%)
  - Updating barryvdh/laravel-cors (v0.8.2 => v0.8.6): Downloading (100%)         - Updating fideloper/proxy (3.1.0 => 3.3.4): Downloading (100%)
  - Updating graham-campbell/security (v3.6.0 => v3.7.0): Downloading (100%)      - Updating graham-campbell/binput (v3.4.0 => v3.6.0): Downloading (100%)        - Updating graham-campbell/core (v5.1.0 => v5.3.2): Downloading (100%)          - Updating graham-campbell/exceptions (v8.8.0 => v9.4.0): Downloading (100%)    - Updating jenssegers/date (v3.2.6 => v3.2.12): Downloading (100%)
  - Updating roumen/feed (v2.10.4 => v2.10.5): Downloading (100%)
  - Updating twig/twig (dev-master => v1.34.4): Downloading (100%)
  - Installing alt-three/logger (v1.3.0): Downloading (100%)
  - Installing symfony/yaml (v3.3.9): Downloading (100%)
  - Installing sebastian/version (2.0.1): Downloading (100%)
  - Installing sebastian/resource-operations (1.0.0): Downloading (100%)          - Installing sebastian/recursion-context (2.0.0): Downloading (100%)
  - Installing sebastian/object-enumerator (2.0.1): Downloading (100%)
  - Installing sebastian/global-state (1.1.1): Downloading (100%)
  - Installing sebastian/exporter (2.0.0): Downloading (100%)
  - Installing sebastian/environment (2.0.0): Downloading (100%)
  - Installing sebastian/diff (1.4.3): Downloading (100%)
  - Installing sebastian/comparator (1.2.4): Downloading (100%)
  - Installing doctrine/instantiator (1.1.0): Downloading (100%)
  - Installing phpunit/php-text-template (1.2.1): Downloading (100%)
  - Installing phpunit/phpunit-mock-objects (3.4.4): Downloading (100%)
  - Installing phpunit/php-timer (1.0.9): Downloading (100%)
  - Installing phpunit/php-file-iterator (1.4.2): Downloading (100%)
  - Installing sebastian/code-unit-reverse-lookup (1.0.1): Downloading (100%)     - Installing phpunit/php-token-stream (2.0.1): Downloading (100%)
  - Installing phpunit/php-code-coverage (4.0.8): Downloading (100%)
  - Installing webmozart/assert (1.2.0): Downloading (100%)
  - Installing phpdocumentor/reflection-common (1.0.1): Downloading (100%)        - Installing phpdocumentor/type-resolver (0.4.0): Downloading (100%)
  - Installing phpdocumentor/reflection-docblock (4.1.1): Downloading (100%)      - Installing phpspec/prophecy (v1.7.2): Downloading (100%)
  - Installing myclabs/deep-copy (1.6.1): Downloading (100%)
  - Installing phpunit/phpunit (5.7.20): Downloading (100%)
  - Installing composer/semver (1.4.2): Downloading (100%)
  - Installing brianium/habitat (v1.0.0): Downloading (100%)
  - Installing brianium/paratest (0.15.0): Downloading (100%)
  - Installing hamcrest/hamcrest-php (v1.2.2): Downloading (100%)
  - Installing mockery/mockery (0.9.9): Downloading (100%)
  - Installing symfony/dom-crawler (v3.3.9): Downloading (100%)
  - Installing laravel/browser-kit-testing (v2.0.0): Downloading (100%)
  - Installing alt-three/twitter (v1.0.1): Downloading (100%)
  - Installing lcobucci/jwt (3.2.2): Downloading (100%)
  - Installing php-http/promise (v1.0.0): Downloading (100%)
  - Installing php-http/httplug (v1.1.0): Downloading (100%)
  - Installing php-http/guzzle6-adapter (v1.1.1): Downloading (100%)
  - Installing zendframework/zend-diactoros (1.5.0): Downloading (100%)
  - Installing nexmo/client (1.0.0): Downloading (100%)
  - Installing graham-campbell/testbench-core (v1.1.2): Downloading (100%)        - Installing alt-three/testbench (v1.11.3): Downloading (100%)
  - Installing filp/whoops (2.1.10): Downloading (100%)
  - Installing fzaninotto/faker (v1.7.1): Downloading (100%)
  - Installing tightenco/mailthief (v0.3.9): Downloading (100%)
ramsey/uuid suggests installing ircmaxell/random-lib (Provides RandomLib for use with the RandomLibAdapter)
ramsey/uuid suggests installing ext-libsodium (Provides the PECL libsodium extension for use with the SodiumRandomGenerator)
ramsey/uuid suggests installing ext-uuid (Provides the PECL UUID extension for use with the PeclUuidTimeGenerator and PeclUuidRandomGenerator)
ramsey/uuid suggests installing moontoast/math (Provides support for converting UUID to 128-bit integer (in string form).)
ramsey/uuid suggests installing ramsey/uuid-doctrine (Allows the use of Ramsey\Uuid\Uuid as Doctrine field type.)
ramsey/uuid suggests installing ramsey/uuid-console (A console application for generating UUIDs with ramsey/uuid)
sebastian/global-state suggests installing ext-uopz (*)
phpunit/php-code-coverage suggests installing ext-xdebug (^2.5.1)
phpunit/phpunit suggests installing phpunit/php-invoker (~1.1)
phpunit/phpunit suggests installing ext-xdebug (*)
lcobucci/jwt suggests installing mdanter/ecc (Required to use Elliptic Curves based algorithms.)
filp/whoops suggests installing whoops/soap (Formats errors as SOAP responses)
Package graham-campbell/core is abandoned, you should avoid using it. No replacement was suggested.
Writing lock file
Generating optimized autoload files
> Illuminate\Foundation\ComposerScripts::postUpdate
> php artisan optimize
PHP Fatal error:  Uncaught Error: Class name must be a valid object or a string in /var/www/vhosts/censored/Cachet/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php:96
Stack trace:
#0 [internal function]: Illuminate\Foundation\Exceptions\Handler->Illuminate\Foundation\Exceptions\{closure}(0, 'Illuminate\\Http...')
#1 /var/www/vhosts/censored/Cachet/bootstrap/cache/compiled.php(6449): call_user_func(Object(Closure), 0, 'Illuminate\\Http...')
#2 /var/www/vhosts/censored/Cachet/bootstrap/cache/compiled.php(12660): Illuminate\Support\Arr::first(Array, Object(Closure), NULL)
#3 /var/www/vhosts/censored/Cachet/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(97): Illuminate\Support\Collection->first(Object(Closure))
#4 /var/www/vhosts/censored/Cachet/vendor/graham-campbell/exceptions/src/ExceptionHandlerTrait.php(40): Illuminate\Foundation\Exceptions\Handler->shouldn in /var/www/vhosts/censored/Cachet/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php on line 96
PHP Fatal error:  Uncaught Error: Class name must be a valid object or a string in /var/www/vhosts/censored/Cachet/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php:96
Stack trace:
#0 [internal function]: Illuminate\Foundation\Exceptions\Handler->Illuminate\Foundation\Exceptions\{closure}(0, 'Illuminate\\Http...')
#1 /var/www/vhosts/censored/Cachet/bootstrap/cache/compiled.php(6449): call_user_func(Object(Closure), 0, 'Illuminate\\Http...')
#2 /var/www/vhosts/censored/Cachet/bootstrap/cache/compiled.php(12660): Illuminate\Support\Arr::first(Array, Object(Closure), NULL)
#3 /var/www/vhosts/censored/Cachet/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(97): Illuminate\Support\Collection->first(Object(Closure))
#4 /var/www/vhosts/censored/Cachet/vendor/graham-campbell/exceptions/src/ExceptionHandlerTrait.php(40): Illuminate\Foundation\Exceptions\Handler->shouldn in /var/www/vhosts/censored/Cachet/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php on line 96
`

**Comment by nixmomo** [comment]
ok after composer cache-clear and running composer install --no-scripts -o without error, i get this message on php artisan app:update

` # php artisan app:update
PHP Fatal error:  Uncaught Error: Class name must be a valid object or a string in /var/www/vhosts/censored/Cachet/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php:96
Stack trace:
#0 [internal function]: Illuminate\Foundation\Exceptions\Handler->Illuminate\Foundation\Exceptions\{closure}(0, 'Illuminate\\Http...')
#1 /var/www/vhosts/censored/Cachet/bootstrap/cache/compiled.php(6449): call_user_func(Object(Closure), 0, 'Illuminate\\Http...')
#2 /var/www/vhosts/censored/Cachet/bootstrap/cache/compiled.php(12660): Illuminate\Support\Arr::first(Array, Object(Closure), NULL)
#3 /var/www/vhosts/censored/Cachet/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(97): Illuminate\Support\Collection->first(Object(Closure))
#4 /var/www/vhosts/censored/Cachet/vendor/graham-campbell/exceptions/src/ExceptionHandlerTrait.php(40): Illuminate\Foundation\Exceptions\Handler->shouldn in /var/www/vhosts/censored/Cachet/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php on line 96
PHP Fatal error:  Uncaught Error: Class name must be a valid object or a string in /var/www/vhosts/censored/Cachet/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php:96
Stack trace:
#0 [internal function]: Illuminate\Foundation\Exceptions\Handler->Illuminate\Foundation\Exceptions\{closure}(0, 'Illuminate\\Http...')
#1 /var/www/vhosts/censored/Cachet/bootstrap/cache/compiled.php(6449): call_user_func(Object(Closure), 0, 'Illuminate\\Http...')
#2 /var/www/vhosts/censored/Cachet/bootstrap/cache/compiled.php(12660): Illuminate\Support\Arr::first(Array, Object(Closure), NULL)
#3 /var/www/vhosts/censored/Cachet/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(97): Illuminate\Support\Collection->first(Object(Closure))
#4 /var/www/vhosts/censored/Cachet/vendor/graham-campbell/exceptions/src/ExceptionHandlerTrait.php(40): Illuminate\Foundation\Exceptions\Handler->shouldn in /var/www/vhosts/censored/Cachet/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php on line 96
root@server2 /var/www/vhosts/censored/Cachet # php -v
PHP 7.1.9 (cli) (built: Sep  1 2017 16:53:35) ( NTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.1.0, Copyright (c) 1998-2017 Zend Technologies
    with Zend OPcache v7.1.9, Copyright (c) 1999-2017, by Zend Technologies
`

**Comment by nixmomo** [comment]
Now i fixed it... clearing caches and update the .env file and chmod issues

**Comment by jbrooksuk** [comment]
👍 Glad to hear you got it sorted.

**Comment by rarguelloF** [comment]
@nixmomo I'm having this exact issue, could you be more specific on how you fixed it? Thanks in advance!

**Comment by nixmomo** [comment]
puhh... 
composer cache-clear 
after that i checked my .env file for the cache driver
then
composer install --no-scripts -o
and thats it
