### ISSUE TITLE
No Subscribe Button

### ISSUE THREAD

**Issue by Si-Richards** [CachetHQ/Cachet#2715]
Running the latest v2.3.13 / Apache 2.4 / PHP7 / MYSQL / Centos7 (all latest) after following this https://hostpresto.com/community/tutorials/how-to-install-cachet-status-page-system-on-centos-7/

I can't see the subscribe button and I've tried various .env mail settings and ensured the option is enabled in the GUI

Are there any instructions on how to fix this.....

![image](https://user-images.githubusercontent.com/20224397/30334294-0e394cd2-97d7-11e7-9030-f05a4d4d4d89.png)

**Comment by Si-Richards** [comment]
+----+-------------------------------+----------------------+---------------------+---------------------+
| id | name                          | value                | created_at          | updated_at          |
+----+-------------------------------+----------------------+---------------------+---------------------+
|  1 | app_name                      | Network Status       | 2017-09-12 13:02:02 | 2017-09-12 13:02:02 |
|  2 | app_domain                    | http://192.168.1.149 | 2017-09-12 13:02:02 | 2017-09-12 13:02:02 |
|  3 | app_timezone                  | Europe/London        | 2017-09-12 13:02:02 | 2017-09-12 13:02:02 |
|  4 | app_locale                    | en                   | 2017-09-12 13:02:02 | 2017-09-12 13:02:02 |
|  5 | app_incident_days             | 1                    | 2017-09-12 13:02:02 | 2017-09-12 13:15:27 |
|  6 | app_about                     |                      | 2017-09-12 13:03:13 | 2017-09-12 13:03:13 |
**|  7 | enable_subscribers            | 1                    | 2017-09-12 13:03:13 | 2017-09-12 13:37:28 |**
|  8 | display_graphs                | 1                    | 2017-09-12 13:03:13 | 2017-09-12 13:56:39 |
|  9 | show_support                  | 0                    | 2017-09-12 13:03:13 | 2017-09-12 14:24:28 |
| 10 | date_format                   | l jS F Y             | 2017-09-12 13:03:31 | 2017-09-12 13:03:31 |
| 11 | incident_date_format          | l jS F Y H:i:s       | 2017-09-12 13:03:31 | 2017-09-12 13:03:31 |
| 12 | automatic_localization        | 1                    | 2017-09-12 13:03:31 | 2017-09-12 13:03:31 |
| 13 | style_background_color        | #f0f3f4              | 2017-09-12 13:08:35 | 2017-09-12 13:08:35 |
| 14 | style_text_color              | #333333              | 2017-09-12 13:08:35 | 2017-09-12 13:08:35 |
| 15 | style_banner_background_color |                      | 2017-09-12 13:08:35 | 2017-09-12 13:08:35 |
| 16 | style_banner_padding          | 40px 0               | 2017-09-12 13:08:35 | 2017-09-12 13:08:35 |
| 17 | style_fullwidth_header        | 0                    | 2017-09-12 13:08:35 | 2017-09-12 13:08:35 |
| 18 | style_reds                    | #ff6f6f              | 2017-09-12 13:08:35 | 2017-09-12 13:08:35 |
| 19 | style_blues                   | #3498db              | 2017-09-12 13:08:35 | 2017-09-12 13:08:35 |
| 20 | style_greens                  | #7ed321              | 2017-09-12 13:08:35 | 2017-09-12 13:08:35 |
| 21 | style_yellows                 | #f7ca18              | 2017-09-12 13:08:35 | 2017-09-12 13:08:35 |
| 22 | style_oranges                 | #ff6600              | 2017-09-12 13:08:35 | 2017-09-12 13:08:35 |
| 23 | style_metrics                 | #7ed321              | 2017-09-12 13:08:35 | 2017-09-12 15:23:56 |
| 24 | style_links                   | #ff6600              | 2017-09-12 13:08:35 | 2017-09-12 13:08:35 |
| 25 | style_background_fills        | #333333              | 2017-09-12 13:08:35 | 2017-09-12 14:27:49 |
| 26 | dashboard_login_link          | 0                    | 2017-09-12 13:08:35 | 2017-09-12 13:08:35 |
+----+-------------------------------+----------------------+---------------------+---------------------+
26 rows in set (0.00 sec)

**Comment by Si-Richards** [comment]
APP_ENV=production
APP_DEBUG=false
APP_URL=http://localhost
APP_KEY=base64:Ju+y0YznA2EmOQ42eu6GF0Vepql7q385mJdcz4vCMYc=

DB_DRIVER=mysql
DB_HOST=localhost
DB_DATABASE=db
DB_USERNAME=user
DB_PASSWORD=password
DB_PORT=3306
DB_PREFIX=null

CACHE_DRIVER=memcached
SESSION_DRIVER=memcached
QUEUE_DRIVER=sync
CACHET_EMOJI=false

MAIL_DRIVER=smtp
MAIL_HOST=relay.domain.com
MAIL_PORT=25
MAIL_USERNAME=null
MAIL_PASSWORD=null
MAIL_ADDRESS=support@domain.com
MAIL_NAME=Network Status
MAIL_ENCRYPTION=tls

REDIS_HOST=null
REDIS_DATABASE=null
REDIS_PORT=null

GITHUB_TOKEN=null

**Comment by nixmomo** [comment]
the subscribe button isn't in dashboard and always visible at the end of the front page... do you cleared the caches ?

**Comment by Si-Richards** [comment]
Hi, yes i have run this many times.....

```
[root@localhost ~]# cd /var/www/cachet
[root@localhost cachet]# php artisan cache:clear
Application cache cleared!
[root@localhost cachet]# 
```

**Comment by Si-Richards** [comment]
Looks like the variable $enable_subscribers is not ever being set in PHP but is in the database

**Comment by nixmomo** [comment]
do you use chrome? Did you cleared cache and cookies in your browser too?

**Comment by Si-Richards** [comment]
Yes i use chrome but I have emptied cache and tried on IE / Edge and Firefox.

For sure the variable `$enable_subscribers` is not being set

**Comment by nixmomo** [comment]
can you check your /var/www/Cachet/bootstrap/cache/config.php ?
look at this line
`'enable_subscribers' => true,`
is this set?

**Comment by Si-Richards** [comment]
Okay looking at 2615 i ran the following command and i can now see the button !!!!! :-)

                         `php artisan app:update`

I still get an error 500 on submitting an email so will play with the .env mail settings

**Comment by nixmomo** [comment]
Great!
A tipp for your Mail settings... most servers needs a authentication... in your config postet earlier is the username and password empty.
i think it can be a reason for that error
