### ISSUE TITLE
Subscription choices

### ISSUE THREAD

**Issue by 0xbaadf00d** [CachetHQ/Cachet#2716]
Hello,

It could be nice if user can choose for which group he want subscribe. By example: The demo site have 3 groups "websites", "Alt three" and "Others". By clicking on the button "subscribe", user can be asked for which groups he want to subscribe to receive notification.

An user could be only interrested to receive notifications about "Alt Three" group, not for others

**Comment by nixmomo** [comment]
Which Version do you use? If i subscribe i get in step 2 the page where i can choose what i want to subscribe
