### ISSUE TITLE
Can Cachet accept incoming requests from NAGIOS?

### ISSUE THREAD

**Issue by savaikar** [CachetHQ/Cachet#2719]
Hello,

I have a working instance of Cachet and wish to know whether I can use events from NAGIOS to create and send automatic notifications via Cachet.

Please feel free to provide your suggestions.

Regards,
Rahul

**Comment by nixmomo** [comment]
10 seconds Google :)
https://github.com/mpellegrin/nagios-eventhandler-cachet

see also
https://docs.cachethq.io/v1.0/docs/addons

**Comment by savaikar** [comment]
@nixmomo - Thank you very much.

I will try this and provide an update.
