### ISSUE TITLE
Setup Error

### ISSUE THREAD

**Issue by CuReSoft** [cachethq/Cachet#272]
Im getting this error when i try to run the setup for the first time.

file_get_contents(/var/www/Cachet/public/build/rev-manifest.json): failed to open stream: No such file or directory (View: /var/www/Cachet/app/views/partials/dashboard/head.blade.php) (View: /var/www/Cachet/app/views/partials/dashboard/head.blade.php) (View: /var/www/Cachet/app/views/partials/dashboard/head.blade.php) 
ErrorException thrown with message "file_get_contents(/var/www/Cachet/public/build/rev-manifest.json): failed to open stream: No such file or directory (View: /var/www/Cachet/app/views/partials/dashboard/head.blade.php) (View: /var/www/Cachet/app/views/partials/dashboard/head.blade.php) (View: /var/www/Cachet/app/views/partials/dashboard/head.blade.php)"

Stacktrace:
#41 ErrorException in /var/www/Cachet/src/helpers.php:18
#40 Illuminate\View\Engines\CompilerEngine:handleViewException in /var/www/Cachet/vendor/laravel/framework/src/Illuminate/View/Engines/PhpEngine.php:41
#39 ErrorException in /var/www/Cachet/src/helpers.php:18
#38 Illuminate\View\Engines\CompilerEngine:handleViewException in /var/www/Cachet/vendor/laravel/framework/src/Illuminate/View/Engines/PhpEngine.php:41
#37 ErrorException in /var/www/Cachet/src/helpers.php:18
#36 Illuminate\View\Engines\CompilerEngine:handleViewException in /var/www/Cachet/vendor/laravel/framework/src/Illuminate/View/Engines/PhpEngine.php:41
#35 ErrorException in /var/www/Cachet/src/helpers.php:18
#34 Illuminate\Exception\Handler:handleError in <#unknown>:0
#33 file_get_contents in /var/www/Cachet/src/helpers.php:18
#32 elixir in /var/www/Cachet/app/storage/views/c3f029a686d4b606d9242193b960d124:24
#31 include in /var/www/Cachet/vendor/laravel/framework/src/Illuminate/View/Engines/PhpEngine.php:37
#30 Illuminate\View\Engines\PhpEngine:evaluatePath in /var/www/Cachet/vendor/laravel/framework/src/Illuminate/View/Engines/CompilerEngine.php:56
#29 Illuminate\View\Engines\CompilerEngine:get in /var/www/Cachet/vendor/laravel/framework/src/Illuminate/View/View.php:134
#28 Illuminate\View\View:getContents in /var/www/Cachet/vendor/laravel/framework/src/Illuminate/View/View.php:102
#27 Illuminate\View\View:renderContents in /var/www/Cachet/vendor/laravel/framework/src/Illuminate/View/View.php:76
#26 Illuminate\View\View:render in /var/www/Cachet/app/storage/views/66c3a462a4d62f625cdb5bc65ba25c71:3
#25 include in /var/www/Cachet/vendor/laravel/framework/src/Illuminate/View/Engines/PhpEngine.php:37
#24 Illuminate\View\Engines\PhpEngine:evaluatePath in /var/www/Cachet/vendor/laravel/framework/src/Illuminate/View/Engines/CompilerEngine.php:56
#23 Illuminate\View\Engines\CompilerEngine:get in /var/www/Cachet/vendor/laravel/framework/src/Illuminate/View/View.php:134
#22 Illuminate\View\View:getContents in /var/www/Cachet/vendor/laravel/framework/src/Illuminate/View/View.php:102
#21 Illuminate\View\View:renderContents in /var/www/Cachet/vendor/laravel/framework/src/Illuminate/View/View.php:76
#20 Illuminate\View\View:render in /var/www/Cachet/app/storage/views/b09342b1350f32b0f043fb16fb43c171:80
#19 include in /var/www/Cachet/vendor/laravel/framework/src/Illuminate/View/Engines/PhpEngine.php:37
#18 Illuminate\View\Engines\PhpEngine:evaluatePath in /var/www/Cachet/vendor/laravel/framework/src/Illuminate/View/Engines/CompilerEngine.php:56
#17 Illuminate\View\Engines\CompilerEngine:get in /var/www/Cachet/vendor/laravel/framework/src/Illuminate/View/View.php:134
#16 Illuminate\View\View:getContents in /var/www/Cachet/vendor/laravel/framework/src/Illuminate/View/View.php:102
#15 Illuminate\View\View:renderContents in /var/www/Cachet/vendor/laravel/framework/src/Illuminate/View/View.php:76
#14 Illuminate\View\View:render in /var/www/Cachet/vendor/laravel/framework/src/Illuminate/Http/Response.php:43
#13 Illuminate\Http\Response:setContent in /var/www/Cachet/vendor/symfony/http-foundation/Symfony/Component/HttpFoundation/Response.php:202
#12 Symfony\Component\HttpFoundation\Response:__construct in /var/www/Cachet/vendor/laravel/framework/src/Illuminate/Routing/Router.php:1496
#11 Illuminate\Routing\Router:prepareResponse in /var/www/Cachet/vendor/dingo/api/src/Routing/Router.php:381
#10 Dingo\Api\Routing\Router:prepareResponse in /var/www/Cachet/vendor/laravel/framework/src/Illuminate/Routing/Router.php:1031
#9 Illuminate\Routing\Router:dispatchToRoute in /var/www/Cachet/vendor/laravel/framework/src/Illuminate/Routing/Router.php:996
#8 Illuminate\Routing\Router:dispatch in /var/www/Cachet/vendor/dingo/api/src/Routing/Router.php:220
#7 Dingo\Api\Routing\Router:dispatch in /var/www/Cachet/vendor/laravel/framework/src/Illuminate/Foundation/Application.php:775
#6 Illuminate\Foundation\Application:dispatch in /var/www/Cachet/vendor/laravel/framework/src/Illuminate/Foundation/Application.php:745
#5 Illuminate\Foundation\Application:handle in /var/www/Cachet/vendor/laravel/framework/src/Illuminate/Session/Middleware.php:72
#4 Illuminate\Session\Middleware:handle in /var/www/Cachet/vendor/laravel/framework/src/Illuminate/Cookie/Queue.php:47
#3 Illuminate\Cookie\Queue:handle in /var/www/Cachet/vendor/laravel/framework/src/Illuminate/Cookie/Guard.php:51
#2 Illuminate\Cookie\Guard:handle in /var/www/Cachet/vendor/stack/builder/src/Stack/StackedHttpKernel.php:23
#1 Stack\StackedHttpKernel:handle in /var/www/Cachet/vendor/laravel/framework/src/Illuminate/Foundation/Application.php:641
#0 Illuminate\Foundation\Application:run in /var/www/Cachet/public/index.php:48

**Comment by GrahamCampbell** [comment]
You need to run npm and gulp.

**Comment by GrahamCampbell** [comment]
https://github.com/cachethq/Cachet/commit/c025946aa8ade7dcddaf304751d02de056db8399

**Comment by jbrooksuk** [comment]
We need to add this into the install document I think.

**Comment by jbrooksuk** [comment]
@GrahamCampbell can you see why I was committing the compiled source too?

**Comment by wingZero21** [comment]
Hi,

I am seeing a similar problem with this currently. Do you know what the fix is for this. As far as I can see I have done the NPM install for gulp and it appears in the node_modules folder.

Looking at the error it suggests this might be a problem with node-sass? Is there any way to get around this error occuring.

**Comment by jbrooksuk** [comment]
@wingZero21 what system are you running on? There are reports of CentOS 6 and Debian Wheezy not working #275.

**Comment by wingZero21** [comment]
Hey,

Yeah I am running on CentOS 6 currently.

**Comment by jbrooksuk** [comment]
@wingZero21 if you could follow the last few comments in the issue above, perhaps it may work? Let me know in that issue though :)

**Comment by wingZero21** [comment]
Hey, Yeah I have tried running that install node-sass beta as requested on that forum but it still seems to fail with that error.

Details:
``` 
/tmp/Cachet]# /tmp/node-v0.10.35-linux-x64/bin/npm install node-sass@2.0.0-beta
npm WARN package.json @ No repository field.
\
> node-sass@2.0.0-beta install /tmp/Cachet/node_modules/node-sass
> node scripts/install.js

Binary downloaded and installed at /tmp/Cachet/node_modules/node-sass/vendor/linux-x64/binding.node

> node-sass@2.0.0-beta postinstall /tmp/Cachet/node_modules/node-sass
> node scripts/build.js

node-sass@2.0.0-beta node_modules/node-sass
├── get-stdin@3.0.2
├── object-assign@2.0.0
├── replace-ext@0.0.1
├── cross-spawn@0.2.3 (lru-cache@2.5.0)
├── chalk@0.5.1 (escape-string-regexp@1.0.2, ansi-styles@1.1.0, supports-color@0.2.0, strip-ansi@0.3.0, has-ansi@0.1.0)
├── mkdirp@0.5.0 (minimist@0.0.8)
├── shelljs@0.3.0
├── nan@1.4.1
├── meow@2.1.0 (minimist@1.1.0, indent-string@1.2.0, camelcase-keys@1.0.0)
├── gaze@0.5.1 (globule@0.1.0)
├── request@2.51.0 (caseless@0.8.0, json-stringify-safe@5.0.0, forever-agent@0.5.2, aws-sign2@0.5.0, stringstream@0.0.4, oauth-sign@0.5.0, tunnel-agent@0.4.0, node-uuid@1.4.2, qs@2.3.3, mime-types@1.0.2, combined-stream@0.0.7, http-signature@0.10.1, form-data@0.2.0, bl@0.9.3, tough-cookie@0.12.1, hawk@1.1.1)
└── mocha@2.1.0 (escape-string-regexp@1.0.2, diff@1.0.8, growl@1.8.1, commander@2.3.0, debug@2.0.0, glob@3.2.3, jade@0.26.3)
```

**Comment by jbrooksuk** [comment]
Can you copy that output to #275 please, we can keep all information together then :)

**Comment by wingZero21** [comment]
Hi,

What is the recommendation for the system to be running on if it currently does not work with CentOS 6?

**Comment by jbrooksuk** [comment]
Ubuntu works ok.

**Comment by wingZero21** [comment]
Yeah we dont really use Ubuntu in our environment so will have to see if I can persevere and get this working! 

Would be good to try and get this working on CentOS

**Comment by jbrooksuk** [comment]
Unfortunately though it's out of my hands as it's a dependency we rely on. `node-sass` v2 should be working though.

**Comment by wingZero21** [comment]
Hey, I have managed to get past that now I think!

Getting this error currently.

Details:
```
Symfony \ Component \ Debug \ Exception \ FatalErrorException (E_ERROR) 
Call to undefined function CachetHQ\Cachet\Composers\locale_get_display_name()
```

**Comment by wingZero21** [comment]
The above error was fixed by installing the below 
```
php-intl
```

**Comment by wingZero21** [comment]
Its now gone back to the previous error :(

**Comment by GrahamCampbell** [comment]
We're going to need to add that extension to our composer.json @jbrooksuk.

**Comment by jbrooksuk** [comment]
Ok :)

**Comment by jbrooksuk** [comment]
Actually, we may not need it now. @joecohens was just going to make the languages an array.

**Comment by wingZero21** [comment]
Hi,

Managed to sort this, it looks like it was an issue with NPM install.

However when trying to run the setup, when getting to the last page on creating the user account and pressing complete setup it just seems to do nothing. Any ideas what might be causing that.

**Comment by jbrooksuk** [comment]
@joecohens any idea on this? It could be a weird `Setup` model issue.

I just reset all migrations and was able to setup Cachet, so it could be something with the DB driver? @wingZero21 what are you using?

**Comment by wingZero21** [comment]
Hey,

I am using postgres DB for the db driver. How do you reset all the migrations?

**Comment by wingZero21** [comment]
I tried doing a php artisan migrate:reset and then a php artisan migrate and it still seems to do the same thing.

**Comment by wingZero21** [comment]
Seems to get a 500 on apache when trying to complete looking at the below.

Details:
"POST /setup/step2 HTTP/1.1" 500 246 "http://localhost/setup" "Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/39.0.2171.95 Safari/537.36"

**Comment by jbrooksuk** [comment]
What details are you sending in the second step?

**Comment by wingZero21** [comment]
Sending the Admin username, email address and password

**Comment by jbrooksuk** [comment]
What's the username you're sending?

**Comment by wingZero21** [comment]
Just admin

**Comment by wingZero21** [comment]
Hey,

Ok I have fixed this initially, it looks like it was a perms issue. I amended the folder to include the apache group on the folder its not allowing the setup part to complete.

However its then redirecting back to /setup when going to /dashboard.

Any ideas on what might be causing that to occur.

**Comment by wingZero21** [comment]
Hi,

Just to confirm.

The fix for that last problem was to install php54w-mbstring. I can now get to the /dashboard page.

Hopefully this is helpful for anyone else that has the same problems :D!.

Might be worth adding these deps into the install documentation.

**Comment by GrahamCampbell** [comment]
I thought we added mb-string as a dependency to our composer.json?

**Comment by GrahamCampbell** [comment]
Ping @jbrooksuk. That dependency seems to have been removed?

**Comment by jbrooksuk** [comment]
I think we were supposed to add it, but it never got there.

**Comment by jbrooksuk** [comment]
Done in 1c20463d5fdd0f76d4600ad3c1757c783819ab33
