### ISSUE TITLE
Scheduled Maintenance Window should not email incidents

### ISSUE THREAD

**Issue by DP19** [CachetHQ/Cachet#2720]
Not sure if I'm missing something but when we schedule maintenance windows and some of our components go un-operational, cachet shouldn't send mail out for these incidents during the window.

Currently we are syncing everything from zabbix to cachet and I do like the fact it still creates incidents and updates status's during the window so people can still see that things went down but the emails shouldn't send out as it alarms people. 

Either this or cachet should be put in a "maintenance" mode that displays "we are in a maintenance window" and doesn't send out incident mail.

**Comment by jbrooksuk** [comment]
Can you try https://github.com/CachetHQ/Cachet/pull/2726 for me?

**Comment by DP19** [comment]
Thanks for getting this implemented so fast! I did try it, but it seems to not be working correctly. 

Scheduled maintance for 12:04 and then created an incidnet. the maintainence didn't show up on the front page and it still sent mail during the window.

![screen shot 2017-09-15 at 12 04 31 pm](https://user-images.githubusercontent.com/20734057/30492414-5bbc3c9c-9a0e-11e7-8b7c-f048df48194d.png)
![screen shot 2017-09-15 at 12 04 36 pm](https://user-images.githubusercontent.com/20734057/30492417-5e0524aa-9a0e-11e7-9998-d1ecbc8f802b.png)
![screen shot 2017-09-15 at 12 04 46 pm](https://user-images.githubusercontent.com/20734057/30492420-60d35f8a-9a0e-11e7-9d0d-7d9918477de0.png)
![screen shot 2017-09-15 at 12 05 19 pm](https://user-images.githubusercontent.com/20734057/30492423-651c3f4e-9a0e-11e7-958d-b7d48a6c63cf.png)
![screen shot 2017-09-15 at 12 05 25 pm](https://user-images.githubusercontent.com/20734057/30492425-6715117c-9a0e-11e7-831b-c72ca316188e.png)

**Comment by sgutermann** [comment]
Other point as I am using Zabbix as well. Why does anything get sent to Cachet from yourr Zabbix anyway if it is unter maintenance?

Zabbix hast functions to stop alerting (even on Dashboard) if Komponent is in maintenance.
