### ISSUE TITLE
Docker not sending mail

### ISSUE THREAD

**Issue by nalipaz** [CachetHQ/Cachet#2727]
Is there any reason that the following docker-compose instructions would not work to setup subscriptions? I can't seem to figure out what is wrong, I get the following message whenever adding a subscriber:

```
cachet_1    | [2017-09-16 07:00:43] Failed: mailer@handleQueuedMessage
```
And here is my docker-compose
```
version: "3"

services:
  postgres:
    image: postgres:9.5
    volumes:
      - /var/lib/postgresql/data
    environment:
      - POSTGRES_USER=redacted
      - POSTGRES_PASSWORD=redacted
    restart: always
  cachet:
    build:
      context: .
      args:
        - cachet_ver=master
    ports:
      - 8000:8000
    links:
      - postgres:postgres
    environment:
      - DB_DRIVER=pgsql
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_DATABASE=postgres
      - DB_USERNAME=postgres
      - DB_PASSWORD=postgres
      - APP_KEY=base64:redacted
      - DEBUG=true
      - MAIL_DRIVER=sendmail
      - MAIL_NAME=redacted
      - MAIL_ADDRESS=redacted
      - QUEUE_DRIVER=database
    depends_on:
      - postgres
    restart: always
```

**Comment by moertel** [comment]
No idea whether this might be your issue, but for me the whole mail functionality would fail if my `MAIL_NAME` had spaces in it. `SomeMailName` would be fine while `Some Mail Name`, even if put in quotes, would not.

**Comment by nalipaz** [comment]
I do have spaces in my name, will check that out, Thanks.

**Comment by nalipaz** [comment]
Well, I tried without the spaces and I am getting the same error. Perhaps outgoing smtp is blocked at my router, but hard to tell.

**Comment by nalipaz** [comment]
So I opened port 25 to udp and it didn't make any difference... Not sure what else to try, any suggestions then I am glad to try them out.

**Comment by nalipaz** [comment]
I have tried changing to us mailgun with the same error message. Doesn't seem like mail configuration issue but something to do with the queue runner maybe.

**Comment by jbrooksuk** [comment]
Can you open this on the [Docker](https://github.com/CachetHQ/Docker) repository, please. @djdefi will be able to help out there :)
