### ISSUE TITLE
No setup folder exists on new install

### ISSUE THREAD

**Issue by calonmerc** [CachetHQ/Cachet#2728]
**Your setup**

What version of Cachet? 2.3.9
What database driver?  MySQL
What version of PHP? PHP 7.0.22-0ubuntu0.16.04.1 (cli) ( NTS )
**Expected behaviour**

Be presented with the install/config page

**Actual behaviour**

404, requested url /setup not found

**Steps to reproduce**

Followed the install docs, https://docs.cachethq.io/docs/installing-cachet.
Going to my cachet install via the URL redirects to /setup which I have confirmed does not exist.

I've done all of the steps, up to and including the `php artisan app:install` and then edited my virtualhost for the main subdomain to reference /var/www/public.

Checking the database, I show all of the tables exist.

**Comment by jbrooksuk** [comment]
This isn't a bug. The setup route isn't a folder.

Are you using Apache? If so, you need to enable the `mod_rewrite` module.

**Comment by calonmerc** [comment]
As I said, I followed the set up entirely, including enabling mod_rewrite. 
`a2enmod rewrite
Module rewrite already enabled`

**Comment by jbrooksuk** [comment]
Have you restarted Apache process?
