### ISSUE TITLE
Updating component status through API results invalid component status

### ISSUE THREAD

**Issue by kungpaolam** [CachetHQ/Cachet#2729]
I'm seeing a similar issue while trying to use the API to change a component status on my cachet instance, and i see the same behavior on the cachet demo (https://demo.cachethq.io). I tried the syntax generated by https://docs.cachethq.io/reference#update-a-component:
```
$ curl --request PUT 
--url https://demo.cachethq.io/api/v1/components/3 
--data '{"name":"Website","status":3,"link":"https://cachethq.io","group_id":1,"enabled":"true"}' -H "X-Cachet-Token: xxxxxxxxxxxxxxxxxxxx"
```

and i've tried something simpler:
`$ curl --request PUT --url https://demo.cachethq.io/api/v1/components/3 --data '{"status":3}' -H "X-Cachet-Token: xxxxxxxxxxxxxxxxxxxx"`

in both cases, the status of the component is always set to "0", and the status_name changed to "cachet.components.status.0" no matter which value i set the status to (1-4).  according to the documentation, valid states are 1-4.

the output from the command is:
{"data":{"id":3,"name":"Website","description":"","link":"https://cachethq.io","status":0,"order":0,"group_id":1,"created_at":"2017-09-17 23:30:02","updated_at":"2017-09-18 00:02:20","deleted_at":null,"enabled":true,"status_name":"cachet.components.status.0","tags":{"webasd":"webasd"}}}

just for fun, i tried the same thing using python and got the same results

```
#!/usr/bin/python
import requests

url = "https://demo.cachethq.io/api/v1/components/3"

payload = "{"name":"Website","status":3,"link":"https://cachethq.io\",\"group_id\":1,\"enabled\":\"true\"}"
headers = {'X-Cachet-Token': 'xxxxxxxxxxxxxxxxxxxxx'}

response = requests.request("PUT", url, headers=headers, data=payload)

print(response.text)
```

the output was the same:
{"data":{"id":3,"name":"Website","description":"","link":"https://cachethq.io","status":0,"order":0,"group_id":1,"created_at":"2017-09-17 23:30:02","updated_at":"2017-09-18 00:26:51","deleted_at":null,"enabled":true,"status_name":"cachet.components.status.0","tags":{"webasd":"webasd"}}}

demo.cachethq.io is running version 2.3.14-dev
the version that i'm using is 2.5.0-dev

can you tell me if i'm using the API incorrectly?  thanks for your help.

**Comment by moertel** [comment]
Adding `-H "Content-Type:application/json"` fixes this for me:
```
curl -H "Content-Type:application/json" \
  -H "X-Cachet-Token: xxx" \
  -X PUT https://demo.cachethq.io/api/v1/components/3 \
  -d '{"status":2}'
```
Gives:
```
{
    "data": {
        "created_at": "2017-09-18 18:30:01",
        "deleted_at": null,
        "description": "",
        "enabled": true,
        "group_id": 1,
        "id": 3,
        "link": "https://cachethq.io",
        "name": "Website",
        "order": 0,
        "status": 2,
        "status_name": "Performance Issues",
        "tags": {
            "webasd": "webasd"
        },
        "updated_at": "2017-09-18 19:11:12"
    }
}
```

**Comment by jbrooksuk** [comment]
Yeah, you need to request with JSON Content-Type header.
