### ISSUE TITLE
Health check and web hooking options

### ISSUE THREAD

**Issue by leegeng** [cachethq/Cachet#273]
Do you have a plan to provide an automated health check or a web hooking interface to change status value automatically?

**Comment by jaxxstorm** [comment]
There's an API already where you can change status of incidents and components: https://github.com/cachethq/Cachet/tree/master/docs/api

I think a health check would be more suited to a monitoring system..

**Comment by jbrooksuk** [comment]
By "health check" do you mean integration with other services?

**Comment by SamuelMoraesF** [comment]
Health check is the automatic verification of status of
site/server/service(like pingdom and statushub).

The system verify for errors(404, 500, DNS Resolution, Ping...) and if
found, register an special issue(pingdom have 2 sections, reported
issues and issues found by the system).

**Comment by jbrooksuk** [comment]
Oh right, then the answer is no for that, we won't be performing checks, but we could gather data from Pingdom or Uptime Robot etc.

**Comment by hadifarnoud** [comment]
is there any open source alternative for health check like Pingdom? I thought Cachet does that tbh

**Comment by jbrooksuk** [comment]
https://github.com/spatie/server-monitor-app
