### ISSUE TITLE
Error 500 on Advanced API GET

### ISSUE THREAD

**Issue by ilsire** [CachetHQ/Cachet#2730]
As in the past versions (<2.4.0-dev) I'm using advanced api search. 
Now in 2.4.0-dev the same call goes in error 500 

The call (component and status exist) GET with advanced API http://myhost/api/v1/incidents?component_id=1&status=1 

`curl --Request GET --url http://myhost/api/v1/incidents?component_id=1&status=1`

it returns Error 500

`
    {
        "errors":
        [
            {
                "id": "c8f53316-832d-447c-a0e8-cba4248207f2",
                "status": 500,
                "title": "Internal Server Error",
                "detail": "An error has occurred and this resource cannot be displayed."
            }
        ]
    }
`

The same call without suffix _?component_id=1&status=1_ goes ok

`
{
    "meta":
    {
        "pagination":
        {
            "total": 1,
            "count": 1,
            "per_page": 20,
            "current_page": 1,
            "total_pages": 1,
            "links":
            {
                "next_page": null,
                "previous_page": null
            }
        }
    },
    "data":
    [
        {
            "id": 1,
            "component_id": 1,
            "name": "Problem",
            "status": 1,
...
`

Could you please help me?

**Comment by jbrooksuk** [comment]
Can you send me the output of the latest log file, which can be found in `./storage/logs/laravel.log` (the file may have a date on it).

**Comment by jbrooksuk** [comment]
Oh, don't worry! This is now fixed :)

**Comment by VeekeeFr** [comment]
is it the same issue as the https://github.com/CachetHQ/Cachet/pull/2736 PR i submitted ?

**Comment by VeekeeFr** [comment]
it is...

**Comment by jbrooksuk** [comment]
👍

**Comment by ilsire** [comment]
Ok, and sorry for the delay

**Comment by jbrooksuk** [comment]
Ah, this is now fixed.
