### ISSUE TITLE
group shown as operationnal even if one component have issues

### ISSUE THREAD

**Issue by paulo-dc** [CachetHQ/Cachet#2731]
A group is shown as operationnal even if one component have problems. That happen as soon as components in the group are ordered.

![image](https://user-images.githubusercontent.com/31652387/30583495-8539ecd8-9d27-11e7-885e-1bbd30004945.png)

**Comment by jbrooksuk** [comment]
What version of Cachet are you using?

**Comment by paulo-decarvalho** [comment]
Hello, I have installed the release v2.3.13

**Comment by jbrooksuk** [comment]
Try clearing your cache?

This is on 2.3 and it's working fine.

![image](https://user-images.githubusercontent.com/246103/31045042-61688fb2-a5d3-11e7-9001-c229743f0280.png)

**Comment by paulo-decarvalho** [comment]
On an ordred group, like I said, when there is an issue on the first element of the group, the group is marked as having an issue. That is good.
 But, if it is an another element of the "ORDERED" group that is having an issue, like the second one, and the first is ok, then the group is not marked as having an issue.

**Comment by jbrooksuk** [comment]
Re-opening until I can test ordered group.

**Comment by RIPv1** [comment]
Can confirm this issue as well on version 2.3.9

<img width="990" alt="screen shot 2017-11-30 at 1 18 12 pm" src="https://user-images.githubusercontent.com/31700628/33447329-f27811ee-d5d0-11e7-84d6-82f4d21852d0.png">

**Comment by jbrooksuk** [comment]
Can I get a dump of your database please?

**Comment by ericfrederich** [comment]
I have this issue as well.  Clearing cache doesn't seem to help.  I open a new private window even... still has group as green even though there are major outages in sub-components.

**Comment by jbrooksuk** [comment]
Can I get a dump of the components/groups/incidents please @ericfrederich?

**Comment by ericfrederich** [comment]
@jbrooksuk unfortunately I don't think I can provide this.  Even our components have sensitive information on them.  When components are failing we publish the error to the description of the component.

**Comment by celebrion** [comment]
I have the exact same issue. If the top component in a component group is set to have some sort of issue, the "ball" on the component group changes to match the issue, but if a component further down the list (under the same component group) has problems, the group says "everything is fine"-ish.

**Comment by fotto1** [comment]
Any updates on this issue?

**Comment by celebrion** [comment]
Still nothing?

**Comment by jbrooksuk** [comment]
Can someone please test https://github.com/CachetHQ/Cachet/pull/3069

**Comment by celebrion** [comment]
Yes, seems to work better! Too bad that the item with issues are not put on top in its group - but there perhaps is a way to solve this as well?

**Comment by jbrooksuk** [comment]
Thanks @celebrion! I'll get this merged and tagged in the next day or so - I'm hoping to spend most of Saturday sorting out some long standing issues in Cachet.

**Comment by jbrooksuk** [comment]
Closed by https://github.com/CachetHQ/Cachet/pull/3069

**Comment by ericfrederich** [comment]
How does that coffee change fix anything?  I'm curious.  Those functions would still return the same components just ordered differently.  Where is the code that sets status on the group?
