### ISSUE TITLE
Component Status selection not visible anymore when creating an incident

### ISSUE THREAD

**Issue by labolanimichele** [CachetHQ/Cachet#2732]
Just pulled the latest changes to 2.4.

When creating an incident, one can select what component it affects. If doing so, he then have to select the status for the component.
Within the last week, there was a change that made the selection of the status not visible anymore.
This means that if you select a component and you create the incident, the creation is going to fail, stating that the component status is a mandatory field. However, it is not visible (nor selectable) anymore.

It used to be located where highlighted in the image:

![capture](https://user-images.githubusercontent.com/22618797/30597737-2dd6a112-9d58-11e7-8dcd-442205d37bc7.PNG)

**Comment by Atriusftw** [comment]
If you select another component again, it should be visible.

There seems to be a bug here, where it doesn't register the first selection of component.

**Comment by Phelzier** [comment]
Thanks @Atriusftw , I too had the issue but I can raise incidents with your workaround.

**Comment by jbrooksuk** [comment]
This seems to be working again now.

![image](https://user-images.githubusercontent.com/246103/31044998-512c5936-a5d2-11e7-802d-0624cc32926b.png)
