### ISSUE TITLE
Facing issue while sending SMS using API

### ISSUE THREAD

**Issue by ypathak7** [CachetHQ/Cachet#2734]
Hi,

Thanks for including option to send sms using api,  i have done the changes according to your suggestion but not able to receive sms. 
We are able to send sms using the below command 
/usr/bin/curl -d 'feedid=xxxxxx' -d 'username=xxxxxxxx' -d 'password=xxxxxxx' -d 'senderid=xxxxxxx' -d 'To=xxxxx' -d 'Text=Your password reset token is: xxxxxx' -k https://apiurl

there is no any problem with api, message is received using the above command

We have added the command in shell script and remove the To and Message field as it should be pick by $mobile and $ message variable in /usr/share/self-service-password/lib/smsapi.inc.php 

The message has been sent as per logs generated by ssp, please find the logs below but we have not received any message.

Send SMS code 812453 by api to xxxxxxx

Send SMS code 323804 by api to xxxxxxx

Send SMS code 992495 by api to xxxxxxx

Send SMS code 837339 by api to xxxxxxxx

Send SMS code 952239 by api to xxxxxxxx

Send SMS code 836148 by api to xxxxxxxx

We have also tried a php code but same issue is happening, please find the code below

<?php
#==============================================================================
# LTB Self Service Password
#
# Copyright (C) 2009-2017 Clement OUDOT
# Copyright (C) 2009-2017 LTB-project.org
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# GPL License: http://www.gnu.org/licenses/gpl.txt
#
#==============================================================================

/* @function boolean send_sms_by_api(string $mobile, string $message)
 * Send SMS trough an API
 * @param mobile mobile number
 * @param message text to send
 * @return 1 if message sent, 0 if not
 */
function send_sms_by_api($mobile, $message) {

    # PHP code
    //PHP SMS API integration code 
//Your application url 
$ApiUrl ="xxxxx";

//Your User Id
$user ="xxxxx";

//Your password
$pass ="xxxxx";

//Multiple mobiles numbers separated by comma
$feedid = "xxxxxxxx";

//Sender ID,While using route4 sender id should be 6 characters long.
$sid = "xxxxxx";

// Message Type (1,2,3,4) 1- English,2-Unicode,3- Special Character,4-Arabic
$type = "1";

//Prepare parameter string
$url = "$ApiUrl?user=$user&pass=$pass&feedid=$feedid&sid=$sid&mobile=$mobile&message=$message&type=$type";

//prepare connection
$ch = curl_init($url);
curl_setopt($ch,CURLOPT_RETURNTRANSFER,TRUE);
curl_setopt($ch,CURLOPT_SSL_VERIFYPEER,false);

//reading response
$body = curl_exec($ch);

//finally close connection
curl_close($ch);

//print response 
echo $body;    

# Or call to external script
    $command = escapeshellcmd("/usr/share/self-service-password/lib/sms.sh").' '.escapeshellarg($mobile).' '.escapeshellarg($message);
    exec($command);

    return 1;
}

The same logs are displaying using the code as well but not able to receive message

please find the content of sms.sh script below:- 

#!/bin/bash
/usr/bin/curl -d 'feedid=xxxx' -d 'username=xxxx' -d 'password=xxxxx' -d 'senderid=xxxxx' -k https://apiurl
exit;

Kindly suggest if i am making any mistake in both method and confirm if we can enable debugging of sms being sent using api. if enable then share the log location where logs are generated

**Comment by ypathak7** [comment]
<?php
#==============================================================================
# LTB Self Service Password
#
# Copyright (C) 2009-2017 Clement OUDOT
# Copyright (C) 2009-2017 LTB-project.org
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# GPL License: http://www.gnu.org/licenses/gpl.txt
#
#==============================================================================

/* @function boolean send_sms_by_api(string $mobile, string $message)
 * Send SMS trough an API
 * @param mobile mobile number
 * @param message text to send
 * @return 1 if message sent, 0 if not
 */
function send_sms_by_api($mobile, $message) {

    # PHP code
    //PHP SMS API integration code 
//Your application url 
$ApiUrl ="xxxxx";

//Your User Id
$user ="xxxxx";

//Your password
$pass ="xxxxx";

//Multiple mobiles numbers separated by comma
$feedid = "xxxxxxxx";

//Sender ID,While using route4 sender id should be 6 characters long.
$sid = "xxxxxx";

// Message Type (1,2,3,4) 1- English,2-Unicode,3- Special Character,4-Arabic
$type = "1";

//Prepare parameter string
$url = "$ApiUrl?user=$user&pass=$pass&feedid=$feedid&sid=$sid&mobile=$mobile&message=$message&type=$type";

//prepare connection
$ch = curl_init($url);
curl_setopt($ch,CURLOPT_RETURNTRANSFER,TRUE);
curl_setopt($ch,CURLOPT_SSL_VERIFYPEER,false);

//reading response
$body = curl_exec($ch);

//finally close connection
curl_close($ch);

//print response 
echo $body;    

# Or call to external script
    $command = escapeshellcmd("/usr/share/self-service-password/lib/sms.sh").' '.escapeshellarg($mobile).' '.escapeshellarg($message);
    exec($command);

    return 1;
}

The same logs are displaying using the code as well but not able to receive message

please find the content of sms.sh script below:- 

#!/bin/bash
/usr/bin/curl -d 'feedid=xxxx' -d 'username=xxxx' -d 'password=xxxxx' -d 'senderid=xxxxx' -k https://apiurl
exit;


Kindly suggest if i am making any mistake in both method and confirm if we can enable debugging of sms being sent using api. if enable then share the log location where logs are generated

**Comment by jbrooksuk** [comment]
You're using the Nexmo API, correct?
