### ISSUE TITLE
[2.4-dev] Metric graph not working

### ISSUE THREAD

**Issue by Atriusftw** [CachetHQ/Cachet#2737]
![image](https://user-images.githubusercontent.com/1478937/30705566-14f64d6a-9ef6-11e7-975c-64f7ebdc5f18.png)

This is a fresh installation of the current 2.4 branch (b5f6c23)
Even though this is a minor issue, i'm putting it here as i haven't seen another issue for it.

**Comment by Raz0rwire** [comment]
I'm having the same issue

**Comment by jbrooksuk** [comment]
This is now fixed :)
