### ISSUE TITLE
2.3.9 Metrics not showing on status page

### ISSUE THREAD

**Issue by judge2020** [CachetHQ/Cachet#2739]
Status page in question: https://status.projectalt.is

Php v7.1

I currently have one metric (ID 1) that is being constantly updated with the api and an amazon lambda task. 

metric details: https://status.projectalt.is/api/v1/metrics/1

The metric is not showing up on the status page.

* It is being updated: https://status.projectalt.is/api/v1/metrics/1/points

* The metric is public on the metric page: 

![image1](https://judge2020.me/ILsk83.png)

* The "display graphs" on the settings page **is not** checked (even after checking it, saving, and a refresh):

![image2](https://judge2020.me/YzLKl.png)

* However, it *is* set in the settings table:

![image3](https://judge2020.me/h3Uh8r.png)

* Database schema: https://ghostbin.com/paste/jvwx4

**Comment by Atriusftw** [comment]
What software are you running for your web server? Have you tried flushing cache etc?

**Comment by judge2020** [comment]
Clearing cache fixed it. Thanks!
