### ISSUE TITLE
Upgrade bug

### ISSUE THREAD

**Issue by jaxxstorm** [cachethq/Cachet#274]
Another bug when upgrading:

```
ErrorException (E_UNKNOWN) 
file_get_contents(/var/www/html/status/public/build/rev-manifest.json): failed to open stream: No such file or directory (View: /var/www/html/status/app/views/layout/master.blade.php) (View: /var/www/html/status/app/views/layout/master.blade.php)
Open: /var/www/html/status/src/helpers.php
     * @return string
     */
    function elixir($file)
    {
        static $manifest = null;
 
        if ($manifest === null) {
            $manifest = json_decode(file_get_contents(public_path().'/build/rev-manifest.json'), true);
        }
 ```

I've run composer update and artisan migrate. I don't see the particular file in the git repo either.

**Comment by jbrooksuk** [comment]
Ah. The problem here is that you won't have `gulp` and `bower` installed to generate the assets.

**Comment by jaxxstorm** [comment]
I suspect this is a new requirement? Any tips to get them?

**Comment by GrahamCampbell** [comment]
It's been on our readme for ages. We just didn't make it a hard requirement until recently.

**Comment by jbrooksuk** [comment]
This can be fixed for older installations though @jaxxstorm.

1. Open your Heroku dashboard.
2. Change the `BUILDPACK_ENV` variable to `https://github.com/cachethq/cachet-buildpack`
3. Re-deploy.

You'll get everything built in.
