### ISSUE TITLE
Cachet database accidentally deleted

### ISSUE THREAD

**Issue by GhostCyborg** [CachetHQ/Cachet#2744]
Hello, the Cachet database was accidentally deleted, is there any way to re-enable the setup process, or have Cachet re-configure the MySQL database, without me having to reinstall Cachet?

**Comment by jbrooksuk** [comment]
Most of the data is stored within the Cachet database, so unfortunately the only way is to reinstall. If you have a backup, I'd recommend restoring that and Cachet would continue to work.

Sorry!

**Comment by GhostCyborg** [comment]
I see, thanks!!
