### ISSUE TITLE
Slack Slash Commands

### ISSUE THREAD

**Issue by mritzmann** [CachetHQ/Cachet#2747]
Would it be possible to integrate Slack Commands so that new incident can create within Slack?

https://api.slack.com/slash-commands

Example (or so):

```
/cachet incident new down due hardware failure
```

**Comment by jbrooksuk** [comment]
Yeah, we could add an endpoint that Slack connects to which handles Slash commands.

We're already _way_ behind a 2.4 release, so this won't be something we - the core maintainers - add yet, but I'd be happy to see a PR with this in.

**Comment by jbrooksuk** [comment]
I'm going to close this as "out of scope" from Cachet for now. That doesn't mean that we wouldn't like to see this make it into Cachet though.

If someone wants to pick this up, please do :)
