### ISSUE TITLE
Settings not saving

### ISSUE THREAD

**Issue by paradoxni** [CachetHQ/Cachet#2748]
Version: 0.3.9

When I attempt to make changes within "Settings" I am told the settings have saved, however, they are not changed.
 
e.g. 

Cannot change Theme/Stylesheet
Cannot enable features in "Application Setup" or change Site Name.

Note that adding Components and Incidents is working OK.

**Comment by jbrooksuk** [comment]
You need to make sure that `./bootstrap/cachet` is writeable.
