### ISSUE TITLE
Incident template creation not working

### ISSUE THREAD

**Issue by labolanimichele** [CachetHQ/Cachet#2749]
Just pulled the latest 2.4

I am now unable to create an incident template: when trying to create one, I can enter text for the "Name" section, but the "Template" section is a non-editable field (the Twig pre-viewer).
Happens also when trying to edit an existing template.

![capture](https://user-images.githubusercontent.com/22618797/31346108-51d2e8bc-ad18-11e7-8d4a-4da857a5e1ae.PNG)

**Comment by jbrooksuk** [comment]
Noted. I'll get a fix for this shortly.

**Comment by cringer** [comment]
:+1:

**Comment by chesterduane** [comment]
Is this already fixed? I am also having same issue. 

![image](https://user-images.githubusercontent.com/20613780/34572832-5ac1b1ae-f1ad-11e7-82c2-1ea3bd737698.png)

**Comment by uxen-ab** [comment]
@chesterduane, @labolanimichele The problem is because the text editor (CodeMirror) is initialized before the DOM is fully loaded. I've just submitted a pull request #2866 that fixed this problem.

**Comment by labolanimichele** [comment]
Hello - this specific issue is now fixed upon template creation.
However, the editing of existing templates is still showing the same problem.

Thanks,
Michele
