### ISSUE TITLE
Bower & Gulp requirements  break Debian Wheezy & CentOS 6 installs

### ISSUE THREAD

**Issue by jaxxstorm** [cachethq/Cachet#275]
A bunch of the node requirements require node-sass ~ 1.0, which is broken on CentOS 6 and Debian Wheezy re: https://github.com/sass/node-sass/issues/517

The error message received is:

```
> node-sass@1.2.3 install /var/www/html/status/node_modules/laravel-elixir/node_modules/gulp-sass/node_modules/node-sass
> node scripts/install.js

Binary downloaded and installed at /var/www/html/status/node_modules/laravel-elixir/node_modules/gulp-sass/node_modules/node-sass/vendor/linux-x64/binding.node

> node-sass@1.2.3 postinstall /var/www/html/status/node_modules/laravel-elixir/node_modules/gulp-sass/node_modules/node-sass
> node scripts/build.js

`linux-x64` exists; testing

module.js:356
  Module._extensions[extension](this, filename);
                               ^
Error: /usr/lib64/libstdc++.so.6: version `CXXABI_1.3.5' not found (required by /var/www/html/status/node_modules/laravel-elixir/node_modules/gulp-sass/node_modules/node-sass/vendor/linux-x64/binding.node)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/var/www/html/status/node_modules/laravel-elixir/node_modules/gulp-sass/node_modules/node-sass/lib/index.js:181:15)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
npm ERR! weird error 8
npm ERR! not ok code 0
```

The fix currently is to use node-sass 2.0.0 beta:

https://github.com/sass/node-sass/issues/517#issuecomment-68086206

Unfortunately, the deps require explicitly that node-sass versions around 1.0 are used, so simply updating the dependencies won't be enough.

CentOS 6 and Debian Wheezy will account for a vast, vast number of production instances, so this could severely reduce the market for Cachet - it certainly rules me out of running it internally.

**Comment by jbrooksuk** [comment]
@jaxxstorm can you try running `npm shrinkwrap` and then installing.

**Comment by jaxxstorm** [comment]
I'll have a crack at redeploying from scratch tonight and seeing if that resolved

**Comment by jbrooksuk** [comment]
The issue you linked to says that the problem has been fixed, they rebuilt the dependencies? Worth trying again, like you said :)

**Comment by jbrooksuk** [comment]
@jaxxstorm can you try again please? We've added another dependency `array-union`. I've no idea if it will help, but it can't hurt.

**Comment by jbrooksuk** [comment]
@Ehesp I believe you were having an issue on Debian? Can you try?

**Comment by jaxxstorm** [comment]
Haven't had time to try this recently, I'll try find some time next week

**Comment by jbrooksuk** [comment]
This isn't a bug with Cachet, but is obviously causing issues for people. We should add some information somewhere explaining that it's not working on CentOS and Debian.

In the mean time, we can't do anything as it's the dependencies themselves which are broken.

**Comment by kfrankperson** [comment]
Could we not have another branch with all the assets compiled in there ?

**Comment by jbrooksuk** [comment]
Technically the answer is yes.

But because it means that we need to maintain two branches it's not logistically elegant. I'm going to look into the actual issue itself and see if I can contibute a fix.

**Comment by jbrooksuk** [comment]
Actually, it looks like there is an issue and a PR open for it: https://github.com/dlmanning/gulp-sass/issues/162 but the `gulp-sass` guy hasn't merged.

**Comment by jbrooksuk** [comment]
I may have a temporary fix on the go.

**Comment by kfrankperson** [comment]
@jbrooksuk :+1: 

I ran into this problem today on my Centos 6 &7 boxes, going to reimage it for ubuntu and try again.

**Comment by wingZero21** [comment]
Yeah I am having this issue as well, tried using node-sass beta but still it fails with the error.

```
/tmp/Cachet]# /tmp/node-v0.10.35-linux-x64/bin/npm install node-sass@2.0.0-beta
npm WARN package.json @ No repository field.
\
> node-sass@2.0.0-beta install /tmp/Cachet/node_modules/node-sass
> node scripts/install.js

Binary downloaded and installed at /tmp/Cachet/node_modules/node-sass/vendor/linux-x64/binding.node

> node-sass@2.0.0-beta postinstall /tmp/Cachet/node_modules/node-sass
> node scripts/build.js

node-sass@2.0.0-beta node_modules/node-sass
├── get-stdin@3.0.2
├── object-assign@2.0.0
├── replace-ext@0.0.1
├── cross-spawn@0.2.3 (lru-cache@2.5.0)
├── chalk@0.5.1 (escape-string-regexp@1.0.2, ansi-styles@1.1.0, supports-color@0.2.0, strip-ansi@0.3.0, has-ansi@0.1.0)
├── mkdirp@0.5.0 (minimist@0.0.8)
├── shelljs@0.3.0
├── nan@1.4.1
├── meow@2.1.0 (minimist@1.1.0, indent-string@1.2.0, camelcase-keys@1.0.0)
├── gaze@0.5.1 (globule@0.1.0)
├── request@2.51.0 (caseless@0.8.0, json-stringify-safe@5.0.0, forever-agent@0.5.2, aws-sign2@0.5.0, stringstream@0.0.4, oauth-sign@0.5.0, tunnel-agent@0.4.0, node-uuid@1.4.2, qs@2.3.3, mime-types@1.0.2, combined-stream@0.0.7, http-signature@0.10.1, form-data@0.2.0, bl@0.9.3, tough-cookie@0.12.1, hawk@1.1.1)
```

**Comment by jbrooksuk** [comment]
Well [this](https://github.com/dlmanning/gulp-sass/pull/159) got merged. Try now?

**Comment by jbrooksuk** [comment]
I ran `npm update` and it's installed `node-sass@2.0.0-beta`. That should be fixed now?

**Comment by pedrommone** [comment]
Its running well on Centos 6.5.

**Comment by rambo-panda** [comment]
You can try the 0.9.3 version of node-sass
