### ISSUE TITLE
Unable to email subscribers when reporting an issue.

### ISSUE THREAD

**Issue by azmcnutt** [CachetHQ/Cachet#2750]
Version 2.3.9 - on Linux / Apache / MySQL server
PHP Ver 7.1

I have about 25 subscribers.

When I report a new incident and I delete most of my subscribers (delete all but 10 or so) or I do not select Email subscribers then everything works fine.

If select Email subscribers (all 25) I get an Internal Server Error.

When the Internal Server Error is generated subscribers receive an email stating a new incident was reported, but the incident never appears in the list of incidents.

The Error in the laravel log states:
`[2017-10-10 22:11:01] production.ERROR: PDOException: SQLSTATE[HY000]: General error: 2006 MySQL server has gone away in /home/crsk12/Cachet/vendor/laravel/framework/src/Illuminate/Database/Connection.php:333`

A copy of the log has been attached.
[laravel-2017-10-10.log](https://github.com/CachetHQ/Cachet/files/1373610/laravel-2017-10-10.log)

I have verified the MySQL settings and everything works otherwise.

Verification emails are sent and people are able to use the system normally.  So the root cause does not seem to be a MySQL error, but the log points to something going wrong.

When I manually run the query shown on line 106 of the log:
`select 'subscribers'.* from 'subscribers' inner join 'subscriptions' on 'subscribers'.'id' = 'subscriptions'.'subscriber_id' where 'verified_at' is not null and 'subscriptions'.'component_id' = 9`

The query runs fine from PHPMyAdmin and returns the users subscribed to the system.

I've tried increasing the script timeout to see if perhaps it was running out of time.  However, even with the PHP script timeout set at 600, I am still getting the error.

If any other information I can provide would be helpful, please just ask for it....

Thanks.

**Comment by azmcnutt** [comment]
Hi.  After a bit of research I discovered that I had the Queue driver set to sync.  I've changed it to database and configure a crontab to take care of sending emails.  This seems to have resolved the issue.

**Comment by jbrooksuk** [comment]
Awesome, thanks for the update and I'm glad you got this resolved.
