### ISSUE TITLE
Can not add a new incident

### ISSUE THREAD

**Issue by cmllr** [CachetHQ/Cachet#2751]
Hello everyone,

I'm trying to add a new incident, but I receive following error message:

> Whoops. There was an error adding the incident, please try again.
> The component status field is required when component id is present.

I'm not sure if I'm just to stupid to use the backend, I'm trying to add an incident with an arbitrary  status connected to a component. The problems also occurs on your demo instance.

Thanks!

**Comment by jbrooksuk** [comment]
What browser are you using and what version of Cachet are you using? (We have two demo instances).

**Comment by cmllr** [comment]
I'm working with cromium, I tested the demo version of 2.4, the local installed version is 2.4 also. Do you recommend to use a lower version/ a previous branch?

**Comment by marcomusso** [comment]
I get the same error, just updated yesterday to last commit e426eff98c18e60be9f659bb935df1a12193156e
And, btw: displaying that error cleans up all fields so you lose all typing...

**Comment by Atriusftw** [comment]
Duplicate. See https://github.com/CachetHQ/Cachet/issues/2732#issuecomment-331200376 for workaround.

Tagging @jbrooksuk for followup.

**Comment by cmllr** [comment]
I tried the workaround suggestion on dev.cachethq.io, but I did not manage to view the missing form elements.

(Do you want further comments regarding this issue here or on #2732?)

**Comment by marcomusso** [comment]
Workaround works for me. Thanks.

**Comment by cmllr** [comment]
Also an update for me: Managed to use the workaround.

**Comment by jbrooksuk** [comment]
This is now fixed then! :)
