### ISSUE TITLE
Adding component name to Incident template

### ISSUE THREAD

**Issue by f7medina** [CachetHQ/Cachet#2754]
Is there a way to include a component name in an incident template dinamically? 
When I report a new new incident I select my template and my component.
e.g. my component name is FUSION and this is my template:

# `Component Name` is experiencing slowness due to high demand.
## We will be `Monitoring Performance.`

I need fusion to replace `Component Name` when updating Dashboard.
Is there a way to do this?
Thanks

**Comment by jbrooksuk** [comment]
You can use `{{ incident.component.name }}` https://github.com/CachetHQ/Cachet/blob/528e9b99dadb0c64401e96b755d5c47872c5faab/app/Bus/Handlers/Commands/Incident/CreateIncidentCommandHandler.php#L159

**Comment by f7medina** [comment]
Thank you so much for the reply. That file that you are showing me is not in the repository anymore.
Now, you guys have Cachet/app/Handlers/Commands/Incident/UpdateIncidentCommand.php 
so when I used the line you wrote down: {{ incident.component.name }} it just prints: {{ incident.component.name }} what is the new syntax? Thanks in advance again.

**Comment by jbrooksuk** [comment]
Are you using v2.3 of Cachet?

**Comment by f7medina** [comment]
@jbrooksuk We are using v2.4. Should I use v2.3? Thanks for the reply.

**Comment by jbrooksuk** [comment]
Ah, now, are you using templates from the API? I think that may be the limitation here.

**Comment by f7medina** [comment]
I am not using templates from the API @jbrooksuk. Thanks so much for the reply.
