### ISSUE TITLE
Cachet behind a proxy

### ISSUE THREAD

**Issue by paulo-decarvalho** [CachetHQ/Cachet#2755]
Hello,

If cachet is installed on a server without direct access to internet, how indicates to it to use a proxy to make calls outside, like for "credits" ?

**Comment by jbrooksuk** [comment]
Cachet will use your systems settings, I believe?

**Comment by paulo-decarvalho** [comment]
I have set env variables, and I'm able to install cachet and all stuff. 

But unfortunately for Cachet itself, that does not work. Nginx/PHP-FPM does not use env variables, and does not use the proxy. 

So actually after installation, when we clic on "credits" for example, we got an error 500.

**Comment by nixmomo** [comment]
can you post more infos about your VM where cachet is installed? 
Need your proxy a authentification?
Can you ping public hosts in internet from the cachet vm?

sounds more like a wrong nginx or proxy config as a cachet error.
My Cachet works fine behind a proxy... my cachet vm has a private only IP and i dont get this errors

**Comment by jbrooksuk** [comment]
Closing this as it's a support issue, but please do continue the conversation. I don't believe this will be related to Cachet itself.

**Comment by paulo-decarvalho** [comment]
Hi,
My VMi is in private network without direct access to internet.
Tu reach internet I can set a proxy without authentification.
I set env parameter kike this :
export http_proxy=http://my_proxy_host:my_proxy_port/
export https_proxy=http://my_proxy_host:my_proxy_port/

With that i can do curl request on public hosts like :
curl https://github.com
or
wget https://github.com

But unfortunatelly, cachet (the nginx/php-fpm) don t use the proxy like curl. Perhaps some rule is missing on my nginx conf.

My nginx conf is the same as the one shown on link https://docs.cachethq.io/v1.0/docs/installing-cachet

**Comment by nixmomo** [comment]
ok, look at the logs which urls nginx cant reach...
you have to use proxy_pass to rewrite them to your http proxy
example:
`rewrite ^(.*)$ "://$http_host$uri$is_args$args" break; 
rewrite ^(.*)$ "http$uri$is_args$args" break; 
proxy_pass http://proxy.abc.lan:3128;`

**Comment by paulo-decarvalho** [comment]
Finally i solve my issue inserting this lines in the index.php file :
```
<?php
putenv("HTTP_PROXY=myproxyhost:myproxyport");
putenv("HTTPS_PROXY=myproxyhost:myproxyport");
/*
 * This file is part of Cachet.
 *
...
```
I'm not sure to understand what your nginx modification does. (Usually proxy_pass directive is used for reverse proxy. )

**Comment by nixmomo** [comment]
Good to know. Sounds easier as the reqrites.

proxy_pass isnt a reverse only... it told nginx to which server he should send the request. In your case the public internet.

@jbrooksuk his solution is worth to write into cachet doku. I'm sure more users looking around for this
