### ISSUE TITLE
Mail notification contains HTML even in text/plain section

### ISSUE THREAD

**Issue by cboltz** [CachetHQ/Cachet#2757]
The notification mails contain HTML even in the text/plain section:

```
--_=_swift_v4_1508082021_11e5b08ee8cdba1b2b5dfd4566156dcb_=_
Content-Type: text/plain; charset=utf-8
Content-Transfer-Encoding: quoted-printable

<!DOCTYPE html>
<html>
```

I noticed this after updating to the 2.4 branch c9a5363c171c37692c5f9bfa0c3b67061306367b 

Before, I used 2.4 branch 95d638f3f6f1fc5a752c80316e88aae30936fea3 where the notifications were really plaintext. Even if this means 7 months of changes, I still hope this helps to find out when this regression was introduced.

(CC @ccboltz)

**Comment by jbrooksuk** [comment]
Thanks for the bug report! Does this affect all email notifications or only some?

**Comment by cboltz** [comment]
It seems to affect all mails - I've seen it with the following mails:
- Verify Your Subscription
- New Incident Reported
- Incident Updated
- Component Status Updated

**Comment by raoasifraza11** [comment]
@jbrooksuk is anyone working on this issue, If not can I contribute on this issue?

**Comment by cboltz** [comment]
Since nobody spoke up since months, I'd assume nobody works on this, and your help is welcome ;-)

**Comment by raoasifraza11** [comment]
Can I work on it? @cboltz

**Comment by jbrooksuk** [comment]
@raoasifraza11 sorry about that! Yeah, feel free to work on it :)

**Comment by raoasifraza11** [comment]
Okay 👍

**Comment by jbrooksuk** [comment]
This should be fixed now.
