### ISSUE TITLE
Advanced API Usage not working

### ISSUE THREAD

**Issue by paulo-decarvalho** [CachetHQ/Cachet#2758]
Hello,

I've installed cachet on 2 machines. On the first one, advanced api usage works well.

But on the second one, when I make calls like http://mymachine/api/v1/components/groups?id=1 for example, the response of the call is all the groups like if I have done a simple http://mymachine/api/v1/components/groups .

No errors. It is just like advance usage is simply ignored.

How solve this issue ?

machine 1 : debian 7.9, cachet 2.3.13, mysql 5.6.37, php 5.6.31, nginx 1.10.3, acces to internet

machine 2 : debian 8.6, cachet 2.3.13, mariadb 10.0.32, php 5.6.30, nginx 1.6.2, behind proxy

**Comment by paulo-decarvalho** [comment]
Ok, my bad. 

On machine 2, my nginx conf was altered :(
try_files $uri /index.phps;
instead of
try_files $uri /index.php$is_args$args;

Shame on me :(

**Comment by jbrooksuk** [comment]
:)
