### ISSUE TITLE
Setting 'how many days of incident to show' to 1 will remove the whole history

### ISSUE THREAD

**Issue by shibumi** [CachetHQ/Cachet#2759]
Hello,
I tried to set the history on just one day. This doesn't seem to be possible. You can test that in your demo version. If you set the counter to 1 the whole history will disappear. Setting it to 2 fixes the issue.

Is there any way to set the history on just 1 day to only show all 'current' Incidents?

**Comment by jbrooksuk** [comment]
That's a bug! PR incoming.
