### ISSUE TITLE
Support for open mail relays

### ISSUE THREAD

**Issue by shibumi** [CachetHQ/Cachet#2760]
Hello,
We have an open mail relay in our company behind a firewall. It's open because that way apps don't need to login via login/password to send mails. I tried that with cachet too, but cachet seems to need that login/password parameters. While doing so I moved my whole cachet instance into a status where I just get  error 500. I even tried to reset the app via `php artisan app:reset`.

**Comment by mritzmann** [comment]
Have you testet with `null` as Username and Passwort?

```
MAIL_DRIVER=smtp
MAIL_HOST=example.com
MAIL_PORT=25
MAIL_USERNAME=null
MAIL_PASSWORD=null
MAIL_ADDRESS=no-reply@example.com
MAIL_NAME="John Doe"
MAIL_ENCRYPTION=null
```

**Comment by shibumi** [comment]
Yep I tested with `MAIL_USERNAME=null` and `MAIL_PASSWORD=null`. The result was an error 500. But I haven't set `MAIL_ENCRYPTION=null`. Let me test that.

**Comment by shibumi** [comment]
Ok, I tried to modify the `env` file like you said.. then I did a `php artisan config:cache` and then I got an error 500 again. I need to deploy the whole app again. No idea what went wrong there.

**Comment by jbrooksuk** [comment]
Can you share the latest `./storage/logs/laravel.log` file please.

Also, can you share your `.env` file please. Some things need to be wrapped with double quotes.
