### ISSUE TITLE
Support link to current incident of component

### ISSUE THREAD

**Issue by shibumi** [CachetHQ/Cachet#2761]
Hello,
it would be nice if I could link a component to the current incident of that component. So when I click on a component I would move to the incident or a little frame would pop up and shows information about the current incident.

**Comment by jbrooksuk** [comment]
That's a good suggestion! :)

I'd love to see a PR with this implemented.

**Comment by jbrooksuk** [comment]
Due to lack of activity or interest in this suggestion, I'm closing the issue. If someone would like to pick this up, please feel free to do so 😄
