### ISSUE TITLE
[feature-request] Use websockets

### ISSUE THREAD

**Issue by shibumi** [CachetHQ/Cachet#2762]
Hello,
It would be nice if you could use websockets. That way the website could be refreshed without pressing F5 all the time. I know it's possible to refresh via custom HTML headers but that way the server would get for every refresh a new request. Thats pretty much load for a status page.

**Comment by jbrooksuk** [comment]
That's quite a large overhead for something as simple as a status page.

**Comment by jbrooksuk** [comment]
Feel free to continue the discussion though.

**Comment by MikeKMiller** [comment]
A simple workaround is the Super Auto Refresh extension for Chrome (and others for Chrome, and other Browsers)
https://www.google.com/url?sa=t&source=web&rct=j&url=https://chrome.google.com/webstore/detail/super-auto-refresh/kkhjakkgopekjlempoplnjclgedabddk%3Fhl%3Den&ved=0ahUKEwj25v6ShYDXAhXB31QKHa-GD8cQFggpMAA&usg=AOvVaw1MWp4bIFXYLSUEMOKB2TKZ

We use the extension on our SOC and NOC status boards for systems that do not utilize built-in javascript refreshes

**Comment by shibumi** [comment]
@MikeKMiller It's much more simple to add this into your header or footer in cachet configuration:
```
 <meta http-equiv="refresh" content="5" />
```

That refreshs the website all 5 seconds without chromium addon. But it's for all visitors. And I would love to see a refresh via websockets or ajax. Hard refreshs need a lot of traffic :S
