### ISSUE TITLE
[feature-request] History for updated Incidents

### ISSUE THREAD

**Issue by shibumi** [CachetHQ/Cachet#2763]
Hello,
At the moment I create for every incident change a new incident because that way I will have a clean transparent history what has happened. I don't think that was the way it was supposed to be used, right?
Therefore it would be nice to have a history for incident updates. That way the user has a transparent view of incident updates.

What do you think about this?

**Comment by jbrooksuk** [comment]
Thanks for the suggestion! 

v2.4 has Incident Updates. See https://dev.cachethq.io for a demo.

**Comment by shibumi** [comment]
Yes it has Incident updates. But when I update an incident it will change the incident in-place instead of being transparent. The user will not see that something has changed.

**Comment by jbrooksuk** [comment]
So you want to actually store the edits?

**Comment by shibumi** [comment]
Exactly. The edits are important to keep a history. At the moment it's possible to simulate this with creating new incidents. So I am unsure if there is really a need for it.
