### ISSUE TITLE
Schedule window

### ISSUE THREAD

**Issue by shibumi** [CachetHQ/Cachet#2764]
Hello,
It would be nice to have a schedule window instead of a fixed date and time.
At the moment it's kind of confusing. What do I schedule there?

- The date/time has to be in the future
- When I set a specific time I see on the public page the following sentence:"Maintenance in an hour"
- After one hour the Maintenance-Window is away...

No Maintenance lasts for one second. Shouldn't be there a window? So it should be possible to schedule a maintenance:"maintenance in one hour for 30min"

so that way I would get a maintenance information window that lasts for 1 hour and a Maintenance Window that lasts for 30min during the maintenance.

What do you think?

**Comment by jbrooksuk** [comment]
Thank you for your input on Cachet 2.x. We are shifting our attention and resources to Cachet 3.x and will no longer be supporting the 2.x version. If your feedback or issue is relevant to the 3.x series, we encourage you to engage with the new branch.

For more information on the Cachet rebuild and our plans for 3.x, you can read the announcement [here](https://github.com/CachetHQ/Cachet/discussions/4342).

We appreciate your understanding and look forward to your contributions to the new version.
