### ISSUE TITLE
Metric Points counting wrong

### ISSUE THREAD

**Issue by ShadowFM** [CachetHQ/Cachet#2769]
I've seen today that the metrics counting wrong, some minutes it stack a metric point like you can see here:
https://i.imgur.com/ObDn8vI.png

Here a picture from the database:
https://i.imgur.com/RdJWQOj.png

Here a picture from the process at the database:
https://i.imgur.com/R4KIYWu.png

The cronjob run every minute, don't know what the problem is.

**Comment by jbrooksuk** [comment]
Could you dump the DB please?
