### ISSUE TITLE
[docs] Missing params in the documentation API

### ISSUE THREAD

**Issue by shibumi** [CachetHQ/Cachet#2770]
Hello,
There are missing params in the documentation. For example:

Incidents (Post)
https://docs.cachethq.io/reference#incidents

In the section: `Body Params` there is no description for `scheduled_at` param or `Human_status` param.

**Comment by jbrooksuk** [comment]
Hey @shibumi, neither `scheduled_at` or `human_status` is an actual parameter that you send to the endpoint.
