### ISSUE TITLE
[API] Maintenance 

### ISSUE THREAD

**Issue by shibumi** [CachetHQ/Cachet#2771]
Hello,
Is it possible to schedule a maintenance via API? I can't find the API functions for it.
I tried it via Incidents API + `status=0` but this only spawns a scheduled incident not a Maintenance Message.

**Comment by jbrooksuk** [comment]
There is no API in place for maintenance yet, but there will be :)

**Comment by SteveCaswellTST** [comment]
Any chance we could get some documentation on the schedules API, maybe in this issue, even if it isn't formal or published? I really need to automate the creation of Cachet objects and schedules is one of those important ones.

**Comment by jbrooksuk** [comment]
@SteveCaswellTST yeah, as part of some work I'm hoping to find time to do, I'll make sure documentation is updated.
