### ISSUE TITLE
Disable Certificate-Check for MAIL

### ISSUE THREAD

**Issue by auoa** [CachetHQ/Cachet#2772]
Is there a possibility to turn off the certificate validation for the mail-system?
For some reason I can not run a mail server with valid certificate, thus I'm not able to send mail TLS-protected mails to this machine.
 
```
.enc
[...]
MAIL_DRIVER=smtp
MAIL_HOST=mail.WWW.com
MAIL_PORT=25
MAIL_USERNAME=null
MAIL_PASSWORD=null
MAIL_ADDRESS=administrator@WWW.com
MAIL_NAME="Administrator WWW"
MAIL_ENCRYPTION=tls
[...]
```

**Comment by jbrooksuk** [comment]
This is the only thing I could find sorry https://gist.github.com/ssatz/7a8531c4ba7a7c4f851a5c7ed5640f23
