### ISSUE TITLE
Subscription page shows Disabled Components

### ISSUE THREAD

**Issue by mattparkes** [CachetHQ/Cachet#2774]
**Version:** ` 2.3.12`

When I click Subscribe, I get a list of all the components I wish to subscribe to, however this list includes ones which I've unticked _"Component enabled?"_ for in the Dashboard UI. 
They show as yellow and correctly don't appear on the main status page, but appear in this list by mistake.

**Comment by mattparkes** [comment]
In addition to the above, these Disabled Components show up in the _Component_ dropdown box when creating an _Incident_.

**Comment by mattparkes** [comment]
They also show in the Report an Incident dropdown, so I'm not sure if this is intended, but it doesn't seem expected from a user's point of view.

**Comment by jbrooksuk** [comment]
This shouldn't be a huge bug.

**Comment by jbrooksuk** [comment]
I've just verified that in v2.4 this is no longer the case.
