### ISSUE TITLE
incident update problems?

### ISSUE THREAD

**Issue by ilsire** [CachetHQ/Cachet#2775]
Hi,
I'm facing with API update and I find a couple of behaviours to check on 2.4.-dev:

## 1 <h2>
I'm trying to obtain all the updates form a incident but the result is not correct

**request**

http://myhost/api/v1/incidents/107/updates

**response**
{
    "meta":
    {
        "pagination":
        {
            "total": 5,
            "count": 5,
            "per_page": 20,
            "current_page": 1,
            "total_pages": 1,
            "links":
            {
                "next_page": null,
                "previous_page": null
            }
        }
    },
    "data":
    [
        {
            "id": 5,
            "incident_id": **104**,
            "status": 4,
            "message": "ghjgh hgj ghj ghj gj ghj gj ghj ghj ghj ghj  jjj  ggg  eeee  gggg",
            "user_id": 1,
            "created_at": "2017-10-19 14:10:53",
            "updated_at": "2017-10-19 14:10:53",
            "human_status": "Fixed",
            "permalink": "http://myhost/incidents/104#update-5"
        },
        {
            "id": 4,
            "incident_id": 104,
            "status": 3,
            "message": "asd ads asd ads",
            "user_id": 1,
            "created_at": "2017-10-19 14:10:26",
            "updated_at": "2017-10-19 14:10:26",
            "human_status": "Watching",
            "permalink": "http://myhost/incidents/104#update-4"
        }......

it calls 104 not 107 and the same with other incident id

## 2 <h2>
Every update did through dashboard give me this result:

![cattura1](https://user-images.githubusercontent.com/31535427/31879926-35003f74-b7df-11e7-8e2b-ce18cd25abb1.JPG)

but I can see on incident tab only "One update" instead of 5
![cattura2](https://user-images.githubusercontent.com/31535427/31880073-bca240d0-b7df-11e7-9533-ae0a41b4ec1c.JPG)

## 3 <h2>
The same operation before with Ruby Client API give me a different result:
**Step 1** - I create a new incident on a component. A component without no opened incidents

pl= {"name"=> "Auto error", "message"=> "Problem 1", "status"=>1,"visible"=>1,"component_id"=>1,"component_status"=>4} 
response = RestClient.post(url,pl,:content_type => h1v, :'X-Cachet-Token' => h2v)
puts JSON.parse(response.body)

and it works **109** inc appears
![cattura3](https://user-images.githubusercontent.com/31535427/31881531-1b32e916-b7e4-11e7-855a-ff938250bc64.JPG)

**Step 2** - I update this incident with Ruby Client API
url2 = url+"/incidents/109"
pl= {"name"=> "Updated Inc 109", "message"=> "**Fixed** Problem 1", "status"=>4,"visible"=>1,"component_id"=> 1,"component_status"=>1} 
response = RestClient.put(url2,pl,:content_type => h1v, :'X-Cachet-Token' => h2v)
puts JSON.parse(response.body)

and it works but this update not create history (as dashboard) but modified the same row
![cattura4](https://user-images.githubusercontent.com/31535427/31881564-3db61788-b7e4-11e7-8b18-fdb4ade25953.JPG)
Is that correct?

**Comment by jbrooksuk** [comment]
Thanks for reporting. Should be a simple enough fix if someone wants to tackle it.

**Comment by uxen-ab** [comment]
It seems `app/Http/Controllers/Api/IncidentUpdateController.php` in its `index` method returns all the incident updates, of all incidents and paginates by 20.

**Comment by uxen-ab** [comment]
I've committed to fix your problem 1, but the 2 is already fixed on my local, perhaps fixed by an other commit/pull request?
Also, your problem 3 is that the method works like the "Edit" functionnality in your browser, it doesn't add an update. Maybe you need `https://docs.cachethq.io/reference#incidentsincidentupdates`?

**Comment by AchoArnold** [comment]
@ilsire Any updates on this?

**Comment by jbrooksuk** [comment]
Thank you for your input on Cachet 2.x. We are shifting our attention and resources to Cachet 3.x and will no longer be supporting the 2.x version. If your feedback or issue is relevant to the 3.x series, we encourage you to engage with the new branch.

For more information on the Cachet rebuild and our plans for 3.x, you can read the announcement [here](https://github.com/CachetHQ/Cachet/discussions/4342).

We appreciate your understanding and look forward to your contributions to the new version.
