### ISSUE TITLE
Manage subsrcription (2.4.0-dev)

### ISSUE THREAD

**Issue by Andyycloud** [CachetHQ/Cachet#2776]
Hi all,

we're using 2.4.0-dev and there doesn't seem to be a way for users to manage subscriptions. 

The mail templates have an unsubscribe link so I'm assuming there would also have been a manage link. 

Any ideas how we can get around this?

Cheers 

Andy

**Comment by lyandr** [comment]
Hello,

i have the same issue: when you subscribe to notifications, after closing the window i didn't find any way to go to this page again through the interface.

But, in the email verify subscription or in the template of notification you have a link with a key. You can use this key to go to /subscribe/manage/key to go to manage your subscriptions

regards

**Comment by Andyycloud** [comment]
thanks @lyandr.

Found that one thanks. Any idea how to get it into the mail template e.g. so you could have an unsubscribe and also an update my preferences?

**Comment by jbrooksuk** [comment]
You can actually enter your email address to signup and you can manage that way too.

**Comment by sgutermann** [comment]
If this is still handled the way it is on 2.3, then anyone can enter anyones email and manage their subscriptions this way as well. Do not think that is a good idea.

**Comment by jbrooksuk** [comment]
This will be properly fixed in v2.4, don't worry.

**Comment by lyandr** [comment]
@sgutermann in 2.4 if you have subscribed to mail notifications you can't enter again the same adress. And that is my issue, after you subscribe to notifications, you d'ont have any link in the email subscriptions to manage your subscription again. The only way is to unsubscribe an re subscribe or to manually enter the good url with the token given in the subscribe mail verification.

**Comment by jbrooksuk** [comment]
If an email update is sent, there is a link in the email to manage your subscription, but I appreciate that's not useful.

**Comment by Andyycloud** [comment]
In 2.4 when an email is sent it only has the unsubscribe link in. Whilst it's ok, it would be more useful to have a manage link in as well
