### ISSUE TITLE
Unable to login

### ISSUE THREAD

**Issue by chrisx84** [CachetHQ/Cachet#2777]
I went through the whole setup, created my account, next day i cant log in using my username and password and i dont see anywhere on the login or in the routes file to reset my password.

**Comment by ilsire** [comment]
So do I, but with a couple of refreshes (F5) it works. 
It's a little bit slow

**Comment by chrisx84** [comment]
well i looked in the routes files since i use laravel for my sites too and i dont see any routes for forgotpassword. in a default laravel install its /auth/lostpassword but didnt even find the default or could i find it in the controllers.

**Comment by jbrooksuk** [comment]
Do you have any errors in the log files?

**Comment by chrisx84** [comment]
no, had nothing in the log but on the login page it kept coming up as invalid username or password even though i put the correct username and password in.

**Comment by jbrooksuk** [comment]
How weird... What version?

**Comment by chrisx84** [comment]
latest, sorry dont have the files now and i dont often check github.

**Comment by chrisx84** [comment]
just installed the latest again, 2.3.13, did the setup which was a pain with lots of errors then once i got into the dashboard i logged out and back in with the same info as i did for the setup and it came up as invalid.

**Comment by chrisx84** [comment]
just found the issue, tried another clean install and set the session and cache saving to file instead of APU at the setup stage and that seems to let me login with no issues.

**Comment by jbrooksuk** [comment]
👍
