### ISSUE TITLE
Front-end does not display components unless a user is logged in

### ISSUE THREAD

**Issue by jlambert-adv** [CachetHQ/Cachet#2779]
I noticed that is seems a user must be logged into the dashboard for the components to show up on the front end.  I was able to verify this behavior by first clearing my cache, and opening the status page in a new window.  The only information that displays is the 'all systems operational' and a maintenance message that we have set.

If i open another tab in the same browser, and then login to the dashboard, and return the the previous browser window and refresh, the components then show up.

To confirm this behavior further, I opened another browser (this time safari instead) - while still logged in - and it does not show the components.

Returning to chrome, and logging out of the dashboard, and then reloading the frontend returns to the original behavior of only showing 'all systems operational' and the maintenance message.

2.4.0-dev

![screen shot 2017-10-24 at 9 37 11 am](https://user-images.githubusercontent.com/33061927/31946686-79b973ee-b8a0-11e7-8fdd-2a17e1bb5729.png)
![screen shot 2017-10-24 at 9 36 29 am](https://user-images.githubusercontent.com/33061927/31946687-79c770c0-b8a0-11e7-9eff-800ffecd8dd8.png)

**Comment by jlambert-adv** [comment]
It's also worth noting that the messages are different.  If you view the page when logged in to an account it says 'All systems are operational' - when no one is logged in - it says 'System operational'

I'm not familiar with this code but I am attempting to locate the procedural differences as to why this is occurring.

**Comment by jlambert-adv** [comment]
Wow.  Well - im going to close this.  I'm sorry everyone - there is a lovely setting called 'visible to logged in users' in the components group section.  Opps.  My appologies

**Comment by jbrooksuk** [comment]
🙈
