### ISSUE TITLE
API - Post an incident update failed 404

### ISSUE THREAD

**Issue by kpma1985** [CachetHQ/Cachet#2780]
Hi!

i want to post an update with the API. 
Im using v2.3.9.

Here is my bash script
==================================================
CACHET_KEY="XXXXX"
CACHET_URL="http://XXXXX/api/v1/incidents/$CACHET_ID/updates"

generate_post_data()
{
  cat <<EOF
{
  "status":"4",
  "message":"Deployment erfolgreich"
}
EOF
}

curl --silent \
  -H "Content-Type: application/json;" POST \
  -H "X-Cachet-Token: ${CACHET_KEY}" \
  --url ${CACHET_URL} \
  --data "$(generate_post_data)"

But i got this error
==================================================
{"errors":[{"id":"7d8670e7-930f-488e-b1c8-580d5b1cb26c","status":404,"title":"Not Found","detail":"The requested resource could not be found but may be available again in the future."}]}`

can anyone give me a hint?

**Comment by jbrooksuk** [comment]
Cachet v2.4 is the only version that supports updates. You're using v2.3.9.

**Comment by alaverty** [comment]
Hi @jbrooksuk when will the Cachet v2.4 docker image be pushed into the docker hub cachethq/docker repo?

**Comment by jbrooksuk** [comment]
That's with @djdefi however, v2.4 isn't ready for production use yet. During the weekend just gone, I made a lot of changes. I'd say that v2.4 is only available for testing.
