### ISSUE TITLE
Access violation: 1142 CREATE command denied to user

### ISSUE THREAD

**Issue by moolshankar** [CachetHQ/Cachet#2785]
Hello Team,
 I am getting the issue while installing Cachet 
_Syntax error or access violation: 1142 CREATE command denied to user_ , 
which is obvious. So my question is 

**Can we skip table creation while installing Cachet?** 

As in our organization DB is on different server where we don't have access for table creation or alter, we can just raise a request to create database along with schema (for Cachet we can get that by installing Cachet on our local machine). So we already have Database with all the tables created and now just want to skip table creation part. But how do we do? Is there some code I need to comment out which is firing Create Table or You have something else to suggest please let me know.

Thanks in Advance!

**Comment by jbrooksuk** [comment]
Table creation can be skipped, yeah.
