### ISSUE TITLE
500 when grabbing data for charts

### ISSUE THREAD

**Issue by jgimenez** [CachetHQ/Cachet#2786]
In order to grab the data for charts, the dashboard makes a call to `GET /metrics/2?filter=today`, this call always responds with 500.

I'm using the Docker image in the 2.3 branch. The app shows version `2.5.0-dev` but I suspect I'm actually using 2.3. I don't know if I can grab any more logs, it looks like the Docker image is not configured to print them.

**Comment by jbrooksuk** [comment]
Can I get a copy of your DB?

**Comment by jgimenez** [comment]
Here you go!
[postgres.sql.gz](https://github.com/CachetHQ/Cachet/files/1526622/postgres.sql.gz)

**Comment by jbrooksuk** [comment]
Thanks @jgimenez!

**Comment by jgimenez** [comment]
I found what it is, it was this: #2104

I created a view so that the data can be fetched, like this:
`create view metric_points (id, metric_id,  value, created_at, updated_at, counter) AS SELECT * from chq_metric_points;`
