### ISSUE TITLE
Tags : Underscore become a - in the json key

### ISSUE THREAD

**Issue by Katyucha** [CachetHQ/Cachet#2787]
Hi,

My service is tagged : stuff_blue

When I use the API to get Tags, I obtain  'stuff-blue': 'stuff_blue' ! 
Is it normal ? 

Kat

**Comment by jbrooksuk** [comment]
This is the correct, although probably unexpected behaviour. We slug the keys. Happy to accept a PR which doesn’t do this.

**Comment by Katyucha** [comment]
Sorry for my poor English but I don't understand what you say by : "slug the keys"

**Comment by jbrooksuk** [comment]
For example “The colour blue” when converted to a slug becomes “the-colour-blue”
