### ISSUE TITLE
Polish translations messed up

### ISSUE THREAD

**Issue by celber** [CachetHQ/Cachet#2788]
Hello! You have had proper polish translations but commit 21fac303503c16fb88d8cf08a9b905740d872401 replaced most of them with german translations

**Comment by jbrooksuk** [comment]
Odd! I’ll re-export them from CrowdIn soon.

**Comment by jbrooksuk** [comment]
I've re-exported all language files, could you let me know if this has solved the issue please.

**Comment by celber** [comment]
I am sorry but I do not see any new commits on develop or v.2.4. Can you link me your change?

**Comment by jbrooksuk** [comment]
https://github.com/CachetHQ/Cachet/commit/874641246779455223773c2c8ded40021c97c214

**Comment by celber** [comment]
No, it is even worse. All it did was change single to double quote on for */forms.php and notifications.php and pagination.php is now English for every language :D German looks good tho

**Comment by jbrooksuk** [comment]
Would you have time to look at https://translate.cachethq.io and fix anything you see, please?

**Comment by celber** [comment]
Oh, i see now what is the problem. You somehow approved wrong translations. johnny-bit (https://crowdin.com/profile/johnny-bit) mentioned it to you. See here: https://translate.cachethq.io/translate/cachet/11/en-pl

**Comment by celber** [comment]
Sorry for second link above. It is one-page app. You need to navigate to any approved entry

**Comment by jbrooksuk** [comment]
No problem @celber. Not being multi-lingual makes it really hard to know what's right or not, so I have to go on what I've been told.

I'm always looking for maintainers of languages.

**Comment by celber** [comment]
I could help but Polish seems to be finished, it just has wrong translations. If you are unsure of anything feel free to ask me. But it seems comments there are enough

**Comment by jbrooksuk** [comment]
Thanks. I've just gone through some of the translations and accepted the updates.
