### ISSUE TITLE
Support showing multiple metrics on the same graph

### ISSUE THREAD

**Issue by hach-que** [CachetHQ/Cachet#2789]
We report both "success" and "failure" metrics for an action - I'd like to be able to display both successes and failures on the same metric graph on the dashboard to save vertical space.

It'd also be nice to have a separate page for metrics that gets linked to if "display graphs on dashboard" is turned off.

**Comment by jbrooksuk** [comment]
Duplicate of https://github.com/CachetHQ/Cachet/issues/1228
