### ISSUE TITLE
Feature Request: Number of days since "not green"

### ISSUE THREAD

**Issue by RickB17** [CachetHQ/Cachet#2790]
How difficult would it be to add a feature on the component group that indicates the number of days since "not green" or that the component status was "greater than red"?

**Comment by jbrooksuk** [comment]
Not hard, but not something we'll take on as part of the core team. Would like to see a PR though!

**Comment by jbrooksuk** [comment]
Due to lack of activity or interest in this suggestion, I'm closing the issue. If someone would like to pick this up, please feel free to do so 😄
