### ISSUE TITLE
Not sending incident update/resolved mails

### ISSUE THREAD

**Issue by sgutermann** [CachetHQ/Cachet#2791]
I am not sure if this is a bug, a feature, my bug or just an oversight of mine.

I have cachet version 2.3.12 running. Have been testing around and am now deciding on using it.

One small hair in the soup though. When I add an incident a mail goes out to all subscribers as intendet. When the incident is updated oder updated and resolved, there are no further mails going out.

I am not seeing anything wrong in my mail.log or in the laravel.log. 

When adding the incident I have a checkbox to send the mail. This is later on gone.

I can not find anything in the settings to controll this event any further.

Any help on this?

**Comment by jbrooksuk** [comment]
I believe this is actually the behaviour of 2.3. 

2.4 does change this but is still being worked on.
