### ISSUE TITLE
Incident - Follow up feature

### ISSUE THREAD

**Issue by getvivekv** [CachetHQ/Cachet#2792]
Great application! Just installed and testing. One feature that I'd like to see is the ability to post follow up comments on an incident along with timestamp.

For example, I have an incident,
-> Website is down!!

Then the agent should be able to add comments so that the subscribers get email notification and also they see the efforts of resolving the issue. Something like this

-> Website is down!!
->> 11/2/2017 8:00AM - Support is investigating
->> 11/2/2017 8:10AM - Support escalated to Security
->> 11/2/2017 8:30AM - Security resolved the issue
->> 11/2/2017 8:40AM - Incident is marked as Resolved 

This would give the user an idea how long the downtime/issue lasted and what was the steps taken to resolve the issue.

**Comment by getvivekv** [comment]
Just found that the feature is already in 2.4.

**Comment by jbrooksuk** [comment]
👍🏻
