### ISSUE TITLE
Feature Request - Display Timestamp instead of "x hours ago"

### ISSUE THREAD

**Issue by getvivekv** [CachetHQ/Cachet#2793]
It would be great if we can see the timestamp instead of "x hours ago".

**Comment by jbrooksuk** [comment]
You can hover the human friendly time to see the real time stamp.

**Comment by getvivekv** [comment]
I see. 

It works only on the main page. However, not on the /incident page.

**Comment by jbrooksuk** [comment]
Closed by #2795
