### ISSUE TITLE
Feature Request - Edit the follow up comments 

### ISSUE THREAD

**Issue by getvivekv** [CachetHQ/Cachet#2794]
In the 2.4 version, there is a new feature to add follow up comments to an incident, which is a great feature. But I am not finding any option to Edit/Modify those comments. If we have a typo or grammar error posted, is there any way to modify it?

**Comment by jbrooksuk** [comment]
Yeah, this does need adding. 2.4 isn’t complete yet, that’s the reason why it’s currently missing.

**Comment by jbrooksuk** [comment]
Incident updates can now be edited.
