### ISSUE TITLE
Graphs showing odd data points

### ISSUE THREAD

**Issue by JustinCarmony** [CachetHQ/Cachet#2796]
![image](https://user-images.githubusercontent.com/602176/32393884-db509954-c0a0-11e7-87d5-66475c2c8f88.png)
So I have a fresh install of Cachet on the 2.4 branch. My graphs are showing the right data on the right side of the graph, but the empty left side is erroneous data, especially if you look at the time labels on the x-axis. 

I'm totally willing to help troubleshoot more, I can get any info you need, or give me a place to start looking to debug in.

Thanks

**Comment by jbrooksuk** [comment]
Unfortunately, the metric system in Cachet isn't great. It needs some work :)

**Comment by samwiseg00** [comment]
One issue that I am seeing is the metric points are being written to the database with the wrong timestamp. I have check my php.ini and mysql for the correct time. 

As a work around I am setting the timestamp in the metric 5 hours back

```
{"data":{"value":4,"counter":1,"metric_id":1,"created_at":"2018-02-16 10:25:28","updated_at":"2018-02-16 10:25:30","id":4,"calculated_value":4}}
```

mysql
```
MariaDB [cachet_datadev]> select * from metric_points;
+----+-----------+-------+---------+---------------------+---------------------+
| id | metric_id | value | counter | created_at          | updated_at          |
+----+-----------+-------+---------+---------------------+---------------------+
|  1 |         1 | 4.000 |       1 | 2018-02-16 15:26:26 | 2018-02-16 15:26:28 |
+----+-----------+-------+---------+---------------------+---------------------+
1 row in set (0.00 sec)
```
MariaDB [cachet_datadev]> SELECT NOW();
+---------------------+
| NOW()               |
+---------------------+
| 2018-02-16 10:26:57 |
+---------------------+
1 row in set (0.00 sec)
```

**Comment by jbrooksuk** [comment]
@samwiseg00 does this mean we're not respecting the timezone set by Cachet when writing metrics?

**Comment by jbrooksuk** [comment]
@JustinCarmony can you confirm which database driver you're using, please?

**Comment by samwiseg00** [comment]
> @samwiseg00 does this mean we're not respecting the timezone set by Cachet when writing metrics?

@jbrooksuk as far as I can tell. No. It is not being honored when it get written to the DB.
