### ISSUE TITLE
Metric graph color issue

### ISSUE THREAD

**Issue by getvivekv** [CachetHQ/Cachet#2797]
Hi Team,

I am running 2.4 ( upgraded from 2.3). However, I am noticing that the Metrics color is changed in 2.4 and the new color isn't good as it is dark/gray. 

When I compared it with https://dev.cachethq.io/ I do see a different color on the dashboard page. 
[
![color](https://user-images.githubusercontent.com/914305/32407032-b9fb395e-c158-11e7-95dd-bd36c9025b32.PNG)
](url)

I've also compared Settings -> Theme page on both the installations and those are same values. Is there anything missing on my end that I am seeing this color instead of the color displaying on https://dev.cachethq.io/ ? 

Here is the screenshot of the Theme page 

![color2](https://user-images.githubusercontent.com/914305/32407046-242a9f90-c159-11e7-99ef-524c70c69fd6.PNG)

Ps: I also noticed that on https://dev.cachethq.io/  the color preview isn't working, but the color preview is working on my installation.

**Comment by jbrooksuk** [comment]
Thanks for reporting! :)

**Comment by thefeeltrain** [comment]
I have the same issue. I tried manually searching through all.js and vendor.js for where the color is getting set but none of them seem to affect it.
