### ISSUE TITLE
The component status field is required when component id is present

### ISSUE THREAD

**Issue by getvivekv** [CachetHQ/Cachet#2798]
This appears like an issue that I found in my installation of 2.4. I can replicate the same on https://dev.cachethq.io as well.

Using Google Chrome latest. 

Steps to replicate the problem.

- Login to the dashboard
- Goto Report an Incident
- Fill out the field. Select "Component" and you will see that the component is selected, but there is no  radio boxes showing after the component field to select the status of the componet. 
- Click ADD after filling all the boxes

You'll see this error message

"Whoops. There was an error adding the incident, please try again.
The component status field is required when component id is present."

Result 

![wrong](https://user-images.githubusercontent.com/914305/32420320-0b51a538-c256-11e7-9b61-a8357c926b82.PNG)

Expected result 

![correct](https://user-images.githubusercontent.com/914305/32420318-08fe82f6-c256-11e7-8001-3354b85418c6.PNG)

**Comment by incnway5** [comment]
Also having this issue using Google Chrome.

**Comment by guikolt** [comment]
Same here.

**Comment by jbrooksuk** [comment]
Closed by https://github.com/CachetHQ/Cachet/pull/2832
