### ISSUE TITLE
 Error 500 for first time access. 

### ISSUE THREAD

**Issue by kzdd** [CachetHQ/Cachet#2799]
Hello. 
I  installed Cachet on local following the provided installation instruction. When I access Cachet in first time. I got error 500 
![screen shot 2017-11-06 at 4 43 18 pm](https://user-images.githubusercontent.com/22047306/32471391-e7f33ac2-c311-11e7-8232-4dfd28668884.png)

I checked log files and read this error log on laravel log: 
[2017-11-07 00:35:13] production.CRITICAL: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'Call to undefined function Illuminate\Cache\apc_fetch()' in /usr/local/var/www/Cachet/vendor/laravel/framework/src/Illuminate/Cache/ApcWrapper.php:32
this log message repeated shows when i load the Cachet.

on error_log,  i got the following log message repeatly:
[:error] [pid 17443] [client 127.0.0.1:57111] PHP Fatal error:  Call to undefined function Illuminate\\Cache\\apc_fetch() in /usr/local/var/www/Cachet/vendor/laravel/framework/src/Illuminate/Cache/ApcWrapper.php on line 32
on access_log, i got follow log message repeatly
127.0.0.1 - - [06/Nov/2017:16:53:21 -0800] "GET / HTTP/1.1" 500 3155. 

I had tried the methods such as installing php56-apcu, and php artisan app:install, and php artisan config:cache. restarted php and apache, etc. The same issue remains and Error 500 page keep showing. 

My local environment is macOS 10.12 + php 5.6 + apache 2.4. Please give some suggestion and help. Thank you very much!

**Comment by vik0803** [comment]
You need to execute the steps provided in the documentation link

**Comment by kzdd** [comment]
@vik0803, what documentation link is it? 

tried to execute the link on logs. not working.

**Comment by GrahamCampbell** [comment]
You need to install the apc extension, or not use the apc driver.

**Comment by kzdd** [comment]
I installed apc extension (by using PEAR), and i changed cache driver in .env to different. The same problem is remain.

**Comment by foexle** [comment]
Same here, 
it seems to be some users have the same issue. I've also tried to install the php extension but nothing works. 
The module is loaded properly:
`php -r 'phpinfo();' |grep apc
/etc/php/7.0/cli/conf.d/20-apcu.ini,
apcu
apc.coredump_unmap => Off => Off
apc.enable_cli => Off => Off
apc.enabled => On => On
apc.entries_hint => 4096 => 4096
apc.gc_ttl => 3600 => 3600
apc.mmap_file_mask => no value => no value
apc.preload_path => no value => no value
apc.serializer => php => php
apc.shm_segments => 1 => 1
apc.shm_size => 32M => 32M
apc.slam_defense => On => On
apc.smart => 0 => 0
apc.ttl => 0 => 0
apc.use_request_time => On => On
apc.writable => /tmp => /tmp
`
Also cache operations are working:
`php artisan config:cache
Configuration cache cleared!
Configuration cached successfully!
`

So it would be nice if you have a module in your official installation documentation to describe the package dependencies.

Is there any way how i can solve that ?
