### ISSUE TITLE
No space between the groups

### ISSUE THREAD

**Issue by matroidde** [CachetHQ/Cachet#2800]
![c6k20h5r2](https://user-images.githubusercontent.com/31346301/32513320-264a1bc2-c3fa-11e7-9681-65c94ce469a7.png)

There are no spaces between the groups. How can i fix?

**Comment by jimmybrancaccio** [comment]
What version? Do you have any custom CSS?

Just checked my 2.4.0 install and didn't have this issue.

**Comment by matroidde** [comment]
How can i see wich Version I use? 
No custom CSS..

**Comment by jbrooksuk** [comment]
Do you have any browser specific CSS?

**Comment by matroidde** [comment]
@jbrooksuk No, i don't have any browser specific CSS... The problem is on all devices, I tried with...

**Comment by jbrooksuk** [comment]
This will be fixed in the new design #3111.
