### ISSUE TITLE
Component updated_at field not updating

### ISSUE THREAD

**Issue by zohaib85** [CachetHQ/Cachet#2802]
Hi,
I'm trying update status using http put request but it's not refreshing updated_at time stamp if status stays the same?
updated_at field will only get updated when status changes.
In api documentation this field is not the part of the body.
Can you please advise how to keep refreshing updated_at fields?
If that's the way system designed than how customers will know status of services last update time?
{
        "id": 1,
        "name": "mysite",
        "description": "",
        "link": "http://google.com",
        "status": 1,
        "order": 0,
        "group_id": 0,
        "created_at": "2017-11-08 21:26:32",
        "updated_at": "2017-11-08 21:31:36",
        "deleted_at": null,
        "enabled": true,
        "status_name": "Operational",
        "tags": {
            "": ""
        }

**Comment by jbrooksuk** [comment]
What version of Cachet are you using?

**Comment by zohaib85** [comment]
it's 2.5 dev

**Comment by mikhail-tokarev** [comment]
hi The same with 2.3.13
