### ISSUE TITLE
Why are Releases != Latest_Tag

### ISSUE THREAD

**Issue by niclasreich** [CachetHQ/Cachet#2803]
Hi,
just a quick question. When following the [Upgrading-Documentation](https://docs.cachethq.io/v1.0/docs/updating-cachet), I noticed when entering `git tag -l` that the lists ends with v2.3.9, but [Releases](https://github.com/CachetHQ/Cachet/releases) is at v2.3.13. Why?

**Comment by GrahamCampbell** [comment]
Probably because it's not ordering by latest version, but is ordering using strcmp?

**Comment by niclasreich** [comment]
Oh yeah, now I see it.
