### ISSUE TITLE
Error after Upgrading to Debian 9 with MariaDB

### ISSUE THREAD

**Issue by niclasreich** [CachetHQ/Cachet#2804]
Hi,

I was now upgrading to v2.3.13 following the [Upgrading-Documentation](https://docs.cachethq.io/v1.0/docs/updating-cachet). Recently, I also updated my Debian 8 to Debian 9. After checking out with the latest Cachet-Release I wanted to update Cachet using `php artisan app:update`, which led to a `mysqldump: Couldn't execute 'SHOW FUNCTION STATUS WHERE Db = 'status_niclasrei'': Cannot load from mysql.proc. The table is probably corrupted (1728)` error, which may because of the MySQL- to MariaDB-migration. Is there any way to fix this as I am currently receiving only a 503 Error-Message on my Cachet-Installation?

Thanks.

**Comment by jbrooksuk** [comment]
I take it this was fixed @niclasreich?

**Comment by niclasreich** [comment]
Yes, I think I fixed it by starting Cachet anyway, haha

**Comment by jbrooksuk** [comment]
:)
