### ISSUE TITLE
Docker install with remote DB

### ISSUE THREAD

**Issue by skyfox675** [CachetHQ/Cachet#2806]
A question regarding running a Docker install of Cachet on Windows connecting to a remote MySQL DB, is there available documentation on this configuration?

Thanks!
-Skyfox675

**Comment by nixmomo** [comment]
DB_DRIVER=mysql
DB_HOST=10.0.0.55
DB_UNIX_SOCKET=null
DB_DATABASE=cachet
DB_USERNAME=homestead
DB_PASSWORD=secret
DB_PORT=3306
DB_PREFIX=null

Via env File should work... i'm sure there is no difference between Docker or normal Installation...

**Comment by jbrooksuk** [comment]
Docker questions should also be opened on the [Docker](https://github.com/CachetHQ/Docker) repo.
