### ISSUE TITLE
Feature Request - See who created the incident

### ISSUE THREAD

**Issue by zerowebcorp** [CachetHQ/Cachet#2807]
A user story for consideration.

Role 
- As a subscriber and staff user

Functionality 
- I want to see the reporter's name on the incident page

Goal 
- So that I know who opened the incident

Acceptance Criteria
- Dashboard > Incident shows the user who created the incident
- Home Page -> shows who created the incident after the "x hours ago" 
- Incident update page shows who created the incident and who posted the updates

**Comment by jbrooksuk** [comment]
We're half way there, Incident Updates are attributed to a user already :)

**Comment by jbrooksuk** [comment]
Thank you for your input on Cachet 2.x. We are shifting our attention and resources to Cachet 3.x and will no longer be supporting the 2.x version. If your feedback or issue is relevant to the 3.x series, we encourage you to engage with the new branch.

For more information on the Cachet rebuild and our plans for 3.x, you can read the announcement [here](https://github.com/CachetHQ/Cachet/discussions/4342).

We appreciate your understanding and look forward to your contributions to the new version.
