### ISSUE TITLE
Error 500

### ISSUE THREAD

**Issue by jsargent7089** [CachetHQ/Cachet#2808]
This page isn’t working

10.20.0.10 is currently unable to handle this request.
HTTP ERROR 500

**Comment by jsargent7089** [comment]
status.doze-cloud.tech | 302 | text/html | Other | 1.1 KB | 207 ms
setup | 500 | document |   | 271 B | 129 ms

**Comment by GrahamCampbell** [comment]
Sorry, we can't do anything without more information than that.
