### ISSUE TITLE
Add locale, timezone & url settings to config/app.php after application setup

### ISSUE THREAD

**Issue by foxted** [cachethq/Cachet#281]
I think it would be nice to modify the `config/app.php` file at setup to save the **locale**, **timezone** and **url (domain)** settings.

I think it will just make it faster to install with the desired language & timezone.

**Comment by jbrooksuk** [comment]
This is definitely something we need to address. We actually ask for the `app_domain` at setup, but never use it in `app.php`.

**Comment by foxted** [comment]
How would you implement this?

**Comment by jbrooksuk** [comment]
We'd have to have default settings with it, so that before it's installed, migrations etc will continue to work.

**Comment by foxted** [comment]
I have been playing around with a package I found: [Phil-F/Setting](https://github.com/Phil-F/Setting). It seems pretty cool, you can set/get/forget settings in a json file wherever you want, and it has a fallback on the Laravel default if you use the same path (e.g. `app.locale`, `app.timezone`, etc...). 

Just need to be careful as his facade is called `Setting` and we already have a model with this name (which is setting the App name, we could store that info in json as well instead of using the database?!) 

What do you think?

**Comment by jbrooksuk** [comment]
@foxted the problem with that package is that if you were to redeploy the app on Heroku, you'd lose your settings.

**Comment by foxted** [comment]
Except if you change the path on the config file to something inside you versionning.

**Comment by jbrooksuk** [comment]
Potentially you'd lose them if you followed the current upgrade guide.

**Comment by GrahamCampbell** [comment]
@foxted Our current settings system is fine. You edit them online, and they're stored in the db. We should not start pulling in more packages to cachet (ex ones we know will be laravel 5 ready) otherwise I'm going to have to rewrite every package we use that's not L5 compatible when we upgrade...

**Comment by jbrooksuk** [comment]
@GrahamCampbell is there any reason we can't replace these values in `app.php` with `Setting::get()` so long as the model can take a default value? Also, as a side question, `Setting` should be a repository right?

**Comment by GrahamCampbell** [comment]
No. Repositories are totally overused in laravel. They make no sense because we're only using eloquent. The whole point of repositories is to allow you to interact with multiple totally different totally different database systems. I think we should remove our repositories. All the code in them belongs in our models.

**Comment by jbrooksuk** [comment]
Ok, so the models are fine as they are? I know you can use repositories for changing to NoSQL and mocking, I was just wondering if it's also the kind of thing we should use for default with default values. If not, that's cool.

**Comment by foxted** [comment]
Using the database is fine as well of course, as long as we can set the correct timezone and locale.

**Comment by jbrooksuk** [comment]
Yeah, it can go into the setup stage.

**Comment by foxted** [comment]
How do we get the settings back from the database at runtime? Never did this kind of work, not sure how to implement this :/

**Comment by GrahamCampbell** [comment]
The way laravel does this is it literally does a find and replace in the php file.

**Comment by GrahamCampbell** [comment]
That's how we set the encryption key.

**Comment by joecohens** [comment]
Or maybe we can do a filter called load config to override the values if set on runtime https://gist.github.com/joecohens/48b4d2965e890116d0b0. And use this package to set datetime https://github.com/jenssegers/laravel-date

**Comment by jbrooksuk** [comment]
@GrahamCampbell do you have any issue with @joecohens's suggestion?

**Comment by joecohens** [comment]
I have a PR already with this implementation. Let me know!

**Comment by jbrooksuk** [comment]
@joecohens does your suggestion include the ability to set the values from the setup wizard and in the dashboard?

**Comment by joecohens** [comment]
@jbrooksuk Yep so you can change it anytime.

**Comment by jbrooksuk** [comment]
Sweet. Make a PR, see what @GrahamCampbell has to say.

**Comment by joecohens** [comment]
:)
