### ISSUE TITLE
Question on notifications

### ISSUE THREAD

**Issue by lyandr** [CachetHQ/Cachet#2814]
Hello,

i use 2.4 and cachet for the first time and i have two questions about notifications:

- when you subscribe to notifications, after entering your email adress you are redirected to the page to manage notifications. But when you close this page (/subscribe/manage/longkey, how is it possible to access again to this page in the interface?

- i have a script that update the status of components every minutes for example and that create or close an incident regarding the component status, using rest api of cachet. With this method, if i subscribe to a component's notfications i will receive an email every minutes to tell me that the status didn't change. Am i using wrong the rest api or is there a way to be notified only when the status of a component change?

Thanks for your help
Regards

**Comment by jbrooksuk** [comment]
1. When you're sent an email, you should be able to manage your subscriptions :)
2. You should be able to pass a parameter that stops notifications, although I'm not sure if the API exposes this.

**Comment by lyandr** [comment]
@jbrooksuk thank you four your answers:

1. the mail to verify the subscription only have the link to verify the subscription. And mails received from subscription only have a link to cancel subscriptions. But you don't have any link to go to the page that allow to manage each component subscription. I don't know if i'am clear enought :)

2. It is not is the API documentation but indeed, in the componentController, in the update function there is a silent parameter and it works, thank you. Maybe you can update the documentation ;)

**Comment by mritzmann** [comment]
> It is not is the API documentation but indeed, in the componentController, in the update function there is a silent parameter and it works

I set component status with:

```
curl -silent --output /dev/null -H 'Content-Type: application/json;' -H "X-Cachet-Token: <TOKEN>" --request PUT --url https://example.com/api/v1/components/$1 --data '{"status":2}'
```

Do you have an example of how I can set the status without sending an email?

**Comment by jbrooksuk** [comment]
`silent=1`.

**Comment by mritzmann** [comment]
@jbrooksuk And how i can use `silent=1` in my curl example?
