### ISSUE TITLE
500 error

### ISSUE THREAD

**Issue by eddiejibson** [CachetHQ/Cachet#2815]
Hi,

Getting an 500 error with the message

"`This error can be identified by 47bbf026-a3be-46a6-96a9-502626c380cf. You might want to take a note of this code.`"

I have cleared the cache, re-installed, updated and granted the correct permissions for directories. However, this didn't solve the issue.

Any ideas?

Thanks.

**Comment by eddiejibson** [comment]
In Laravel log:

`[2017-11-20 18:04:28] production.ERROR: RuntimeException: No supported encrypter found. The cipher and / or key length are invalid. `

Full log can be found here: https://hastebin.com/uyodatiwav.sql

I tried re-installing and re-setting the key, but that didn't work either.

**Comment by eddiejibson** [comment]
Nevermind, problem solved, it was due to the URL I was setting in the .env file. 

Cheers.

**Comment by jbrooksuk** [comment]
:)
