### ISSUE TITLE
Setup SMTP server doesnt allow authless configuration

### ISSUE THREAD

**Issue by purplexss** [CachetHQ/Cachet#2816]
When setuping SMTP server, we cant config it without username and password
Maybe you can add it next version :)
Keep up the good work team!
Regards
![selection_026](https://user-images.githubusercontent.com/15010919/33075405-0009b336-ced2-11e7-99f9-461378b4529e.png)

**Comment by jbrooksuk** [comment]
Is this on v2.4?
