### ISSUE TITLE
API sorting for component groups

### ISSUE THREAD

**Issue by razuro** [CachetHQ/Cachet#2817]
I've searched existing issues, and couldn't find an answer.
Is it possible to do API sorting on status for component first, then component groups?

Condition:
Assume you have one component in a group that is currently having major outage. All other components in other groups is OK. When I query the API, I wanted the one that is having problem is shown first.

Code used:
 `http://localhost:8000/api/v1/components/groups?sort=status&order=desc` 

Please let me know whether this can't be done.

Thanks!

**Comment by jbrooksuk** [comment]
There isn't yet a way to do this, feel free to add it.

**Comment by jbrooksuk** [comment]
So... we added this at some point, I don't remember when but this does work:

```
http://cachet.test/api/v1/components/groups?sort=name&order=asc
```
