### ISSUE TITLE
Email Subscription of other Members editable

### ISSUE THREAD

**Issue by sgutermann** [CachetHQ/Cachet#2819]
I am using Version 2.3.12.

We have just gone through testing and on accident we noticed that if someone wants to "Subscribe" who has never been there before, enters the mail address of an already existing member:

1. he does get told that the mail address is already in use
2. get shown that persons subscription
3. can edit those subscriptions

He then gets told that they have been changed and he will get a mail.

Funny enough they are changed and the mail does not get sent.

**Comment by jbrooksuk** [comment]
The subscription management system is something I've not had a great deal of time to think about, but  I feel needs it.

Signing up has to be easy, but it also needs to be secure. If someone signs up and wants to change their preferences, how do they do it when we haven't yet sent an email?

**Comment by sgutermann** [comment]
In my eyes there could be two ways to go at it.

1. You make that person not just sign up, but you make him choose and enter a password. Seeing that you do not want to make signing up "yet another account to think of" this option is not my favorite.

2. Second option would be that if one entered his email to change his preferences, you could send him an email with a token, allowing soley him (with the token) to change his preferences. You are already using tokens for other things.

In the case that he signed up and hasn't yet answered on his "opt in" E-Mail, well honestly, tough luck. In some countries this can go as far as you may get a letter from his attorney if you are sending official newsletter to him and he did not opt in.

--------

So I would vote for something like no 2 above. If he really wants to sign up, he does have to opt in. If he wants to change his preference securely without creating an account then email link with a token to his email address is the best way in my eyes.

**Comment by aojari** [comment]
2.4 does not have the same behaviour, but does require some work on subscriptions.  If you enter in an existing email, it returns you to the home page with a banner across the top that informs you that the email address is already subscribed.  I can't see an obvious way for a subscriber to manage their preferences but presume that this is something on the to do list?

**Comment by jbrooksuk** [comment]
@sgutermann I was emailing someone about this over the weekend. I suggested your option 2, so that's wha we'll go with.

**Comment by jbrooksuk** [comment]
Replacing this issue with https://github.com/CachetHQ/Cachet/issues/3102
