### ISSUE TITLE
Connect Redis with Cachet

### ISSUE THREAD

**Issue by Oaktr33** [CachetHQ/Cachet#2824]
Hey guys, hoping you can guide me in the right direction here...
Was asked to implement Cachet at my company but I'm not a developer and am having a hard time setting up the cache-side of it.

Didn't have any issues with setting up Cachet with Docker in my localhost but would like as well to see it running with Redis cache.

From what I've been reading, the best way to make Redis work along with Cachet in Docker is by running a different container and link them both together...

My question is: what exactly do I need to change in .env and .yml files so that I make it happen? Or...is there an easier solution to this?

Really just trying to get some guidance here! Any input is greatly appreciated guys!

BTW, Cachet is awesome, was really easy to make a business case to show my superiors 😄

**Comment by jbrooksuk** [comment]
Thanks @Oaktr33 :)

To be honest, that's a question for @djdefi, I'll leave it with Ryan to answer.

**Comment by jbrooksuk** [comment]
Could you open this on [CachetHQ/Docker](https://github.com/CachetHQ/Docker).
