### ISSUE TITLE
Error 500 while adding a incident on dev demo

### ISSUE THREAD

**Issue by guikolt** [CachetHQ/Cachet#2826]
I am trying to evaluate the 2.4.0-dev version, however I am unable to create an incident.

I go to Incidents -> Report an incident -> 
Name: testing incident
Status: Investigating
Viewable by public
Not Stickied
No component
Message: Testing
Did not notify subscribers

Error 500.

If I try to report an incident with a component, it throws a different error.

**Comment by uxen-ab** [comment]
Usually the page that shows the error 500 also says that a log has been written into the log file and give a log identifier.
Please see the file `storage/logs/laravel-YYYY-mm-dd.log` and post here the error log.

**Comment by jbrooksuk** [comment]
Thanks for reporting! I'm just testing a few things and then I'll deploy the current 2.4 branch.

**Comment by jbrooksuk** [comment]
This should now be fixed. Thanks again :)
