### ISSUE TITLE
Clarification for POST /incidents in docs

### ISSUE THREAD

**Issue by jmccann** [CachetHQ/Cachet#2828]
Some issues I ran into came about due to bad reference documentation @ https://docs.cachethq.io/reference

Specifically, I had issues with `POST /incidents` @ https://docs.cachethq.io/reference#incidents

It should be included that:
* `Content-Type ` header should be set to `application/json `
   * e.g. `curl -H "Content-Type: application/json"`
* `component_status` is required when specifying `component_id `

**Comment by jbrooksuk** [comment]
Thanks. You can submit changes to the docs too.

**Comment by jmccann** [comment]
I don't mind submitting changes to the docs but I don't really want to have to register an account with readme.io to do so.  If there is a way to do so without the need to do that let me know.  Thanks!

**Comment by jbrooksuk** [comment]
No problem. I'll get this updated.
