### ISSUE TITLE
Unable to report an incident on 2.4

### ISSUE THREAD

**Issue by guikolt** [CachetHQ/Cachet#2829]
Hello,

I just did a fresh install of 2.4 from git and I am unable to report an incident.

I get this message:
"The component status field is required when component id is present."

What I have done:
1) Added a new component with the status Operational;
2) Went to the incident page
3) I have filled everything correctly, but still, the error appears.

CentOS 7.4
PHP 5.6.25
MySQL 5.7.19-17
git branch: 2.4

**Comment by guikolt** [comment]
If I select no component, the incident report works.

**Comment by jordonbrill** [comment]
We are seeing this as well

![pasted image at 2017_11_28 10_33 am](https://user-images.githubusercontent.com/271489/33491277-532db15c-d67f-11e7-8095-7aea2d66a9c2.png)

**Comment by ianconway** [comment]
We also are seeing this issue

**Comment by jbrooksuk** [comment]
I can't recreate this at all locally. Can you confirm the exact steps, please.
