### ISSUE TITLE
Languages

### ISSUE THREAD

**Issue by GrahamCampbell** [cachethq/Cachet#283]
We MUST NOT allow new code into cachet unless it has all static text in languages files, and all languages have been updated otherwise the backlog on languages becomes so large they end up totally broken and need to be removed.

**Comment by jbrooksuk** [comment]
I was going to make this a rule earlier in the project, but I figured we should wait until we have the ability to translate (we do now with CrowdIn) and move existing static text out.

This should go into `CONTRIBUTING.md`.

**Comment by foxted** [comment]
:+1:

**Comment by joecohens** [comment]
:+1:
