### ISSUE TITLE
Pluralization meta numbers displayed in some translations

### ISSUE THREAD

**Issue by rarguelloF** [CachetHQ/Cachet#2840]
Hi! I'm currently seeing the following message (with the `2,Inf` string) using spanish translations:

![image](https://user-images.githubusercontent.com/7250722/33547608-e4a551a0-d8e4-11e7-88a5-b2fe74a2c8fd.png)

I've checked the translation files and this problem seems to be present in more language files.

Maybe this could be fixed with some pre-processing in the translation part instead of having to change all the translation files?

**Comment by nstapelbroek** [comment]
It's a bit far-fetched. But maybe https://github.com/CachetHQ/Cachet/pull/2868 could be a fix for this?

**Comment by jbrooksuk** [comment]
Fixing this in CrowdIn now.

**Comment by jbrooksuk** [comment]
Should be fixed now. Let me know if you have any issues.
