### ISSUE TITLE
Variable displayed in text

### ISSUE THREAD

**Issue by uxen-ab** [CachetHQ/Cachet#2842]
Hello,
It seems some variables are displayed when I've got an error during the addition of a problem.
Example: I add a problem because my webserver is down. I forget the error message. I submit the form, and an error is displayed above the form.

Also, I lost all the informations that I'd previously typed, it would be great if the informations were pre-filled.

I join an image to show you the problem of variable.
![cachet-add-incident](https://user-images.githubusercontent.com/25496727/33609997-6cbaf938-d9ca-11e7-8a2b-43686fd72913.png)

Cachet version: 2.4
Web browser: Firefox 58.0b6

**Comment by jbrooksuk** [comment]
I've just tested this locally and it was okay.
