### ISSUE TITLE
&nbsp; in french translation

### ISSUE THREAD

**Issue by uxen-ab** [CachetHQ/Cachet#2843]
Hello,

It seems there is a little error in a french translation, a nbsp; is appended.
It's on the login page in the password field.

There is a picture to show : 
<img width="389" alt="cachet-login" src="https://user-images.githubusercontent.com/25496727/33610980-356f1d3a-d9cd-11e7-8f63-d3b415d72302.png">

Cachet version: 2.4
Web browser: 58.0b7

**Comment by jbrooksuk** [comment]
Would you mind checking all of the French translations at https://translate.cachethq.io?

**Comment by uxen-ab** [comment]
I just checked the French translations, and it seems there was a trailing space in the translation of "Password", so it gave "Mot de passe ".
I've submitted an update of the translation.
Thank you for for help.

**Comment by jbrooksuk** [comment]
Should all be updated now.
