### ISSUE TITLE
Component status not updated

### ISSUE THREAD

**Issue by uxen-ab** [CachetHQ/Cachet#2844]
Hello,
It seems the component status is not updated in the status page when I fixe an incident.
Example: I create an incident because my webserver is down, or a "test" incident. Once the incident is fixed I click on "Update", the blue button to add an update to an incident. I set the incident as "fixed" and I save. Then I go back on the status page and the component is still having problem.

It seems that's because the "update" button only update the status, but if the problem is "fixed", shouldn't we be able to set the component as operational?

Cachet version: 2.4
Web browser: Firefox 58.0b8

**Comment by jbrooksuk** [comment]
In the latest 2.4 branch you can modify the Component Status when creating an Incident Update.

<img width="906" alt="image" src="https://user-images.githubusercontent.com/246103/38207525-189d71ee-36a6-11e8-9a90-3441abde1840.png">
