### ISSUE TITLE
Setting Site URL doesn't change most site links from localhost:<port>

### ISSUE THREAD

**Issue by stlasalle** [CachetHQ/Cachet#2847]
This is a cross-post from https://github.com/CachetHQ/Docker/issues/262 as this repo seems to have a lot more activity...

cachet_ver: v2.3.13
docker version: 17.09.0-ce
docker-compose version: 1.17.1

I have just set up the docker image on a cloud server, and have set it up behind an nginx reverse proxy with SSL as mentioned at the bottom of [this page](https://docs.cachethq.io/docs/get-started-with-docker). After having completed the initial setup, almost all the links still start with localhost:6789.

![image](https://user-images.githubusercontent.com/26209178/33755868-ede4bde0-dc46-11e7-9e74-c40d61d05a7b.png)

This shows the Site URL set by me, but when I hover over 'components' on the left panel I am still directed to localhost:6789/dashboard/components

From reading other github issues this seems related to [Cachet issue #1545](https://github.com/CachetHQ/Cachet/issues/1545)

Does anyone have any suggestions?

**Comment by jbrooksuk** [comment]
Are you running behind a proxy?

**Comment by Pacerino** [comment]
I have the same issue but not with the container. Im using Nginx with php7.0.
I have 2 Servers in the intranet. One for the Reverse Proxy with Nginx and the Cachet server itself.
I got it running and can see everything from the Internet but the links generated are pointing to the intranet IP address which lead me into a "Server not found" error from my browser.
Tried to setting the URL via APP_URL and in the database.

**Comment by stlasalle** [comment]
@jrbooksuk yes, it's behind an nginx reverse proxy.

**Comment by jbrooksuk** [comment]
You need to add your proxy IP to `./config/trustedproxy.php`

**Comment by stlasalle** [comment]
Hi @jbrooksuk, this is for cachet-docker so I don't want to edit the PHP files directly as I'd have to re-edit them whenever the docker image is restarted. Is there a fix for docker?

**Comment by NeilHanlon** [comment]
The support for docker of this project is lackluster at best. 

Really turning me off from this in general.

But yes, the application should force all urls to just use the site URL. It's up to the user to configure it correctly--especially for emails. I just got an email with a link using an IP address, not my configured hostname.

**Comment by farhank3389** [comment]
Has this been fixed for docker? @NeilHanlon  @stlasalle were you able to find a solution to this?
