### ISSUE TITLE
Bugs in the average metrics graph

### ISSUE THREAD

**Issue by uxen-ab** [CachetHQ/Cachet#2848]
Hello,
I'm experiencing some things that seems to be bugs with the average metric graph, I'll try to explain them here and I'll join two screenshots in order to help you.

![cachet-metric](https://user-images.githubusercontent.com/25496727/33760505-1e2c59c2-dc06-11e7-9df7-9db7eea1fbc9.png)

At [10:39 a.m in France](https://www.timeanddate.com/worldclock/france) today I load the status page that shows the metric that is on the picture. This metric has the parameters that you can see in the second picture.

Mainly : 
- Default view: Last 12 hours
- Suffix: "%"

As you cas see, the suffix is not shown as it was in the 2.3.9 version. It seems `tooltip` metric's callback isn't called in Vue.

The graph has a weird timeline. The hours begins at 00:00, continues untill 10:00 and then switch to 22:00.

**Form that configures the metric**

![cachet-metric-form](https://user-images.githubusercontent.com/25496727/33760504-1dfff922-dc06-11e7-9710-b2cf5ebb6518.png)

Cachet version: 2.4
Commit number: 26a1d28a6fa32fec9a34e8de36f34d27c700fd09
Web browser: Firefox 58.0b8

**Comment by jbrooksuk** [comment]
Thanks for reporting!

**Comment by uxen-ab** [comment]
You're welcome! If you need more informations, a dump of the database or anything say it.

**Comment by uxen-ab** [comment]
A related problem is the date (timezone maybe?) when pushing a metric point.

**Example**: I use a French OS and Cachet uses the Paris timezone. I've created the same metric as above, and when pushing a data using the API the stored hour is wrong.
I pushed the data at 14:43 but in the database it's saved at 13:43. Is there a timezone converting or anything like that?

**Comment by jbrooksuk** [comment]
Looks like this is fixed!
