### ISSUE TITLE
Doc site unavailable due to expired SSL Key

### ISSUE THREAD

**Issue by doreplado** [CachetHQ/Cachet#2849]
Is there somewhere that https://docs.cachethq.io is mirrored? Or possibly could it be also published to the wiki or github-pages?

**Comment by jbrooksuk** [comment]
I have emailed Readme.io about this, so I'm just waiting for them to get back to me on it.

**Comment by rhuanbarreto** [comment]
You could have a status page for reporting this outage lol

**Comment by jbrooksuk** [comment]
The irony 😂

**Comment by StianOvrevage** [comment]
Also waiting for this one.

**Comment by davestephens** [comment]
You could temporarily update your Cloudflare config to ignore expired/invalid SSL certs. It means the Cloudflare -> docs site transports is still encrypted, just under an agreement that the SSL cert isn't actually valid - bit like if you were to run a self-signed cert on your own site. 

Not ideal, but at least it means the docs are still available until readme.io sort their end out.

**Comment by jbrooksuk** [comment]
It's back.
