### ISSUE TITLE
Incidents by defined users

### ISSUE THREAD

**Issue by dgiovannetti** [CachetHQ/Cachet#2850]
Hi all. First of all, let me say great product. I love it. Using 2.3.13

I started using it for my team, and I'm looking for a system to show on the incident dashboard who reported the incident.

I've seen in database incidents table that actually incidents are not related to any user id when are created.

Would be possible to add this feature, even manually? In this case, which file should be edited?

Thank you all guys for this amazing open source project!

keep up the great work!

Dan

**Comment by dgiovannetti** [comment]
ping @jbrooksuk ?

**Comment by jbrooksuk** [comment]
This is changing in 2.4, don't worry :)
