### ISSUE TITLE
[Request] Subscriptions without confirmation/removal

### ISSUE THREAD

**Issue by absolutejam** [CachetHQ/Cachet#2852]
Hey!

First of all - Awesome work on this project! We've begun using it for transparency and had great feedback, so I'd like to pass that straight back to you guys who did the hard work.

I know this could be a point of contention due to the risk of abuse, but I'd really like to be able to set up a subscription where a user cannot unsubscribe, and ideally, doesn't need confirmation (The latter I can kinda work around). This is because we're looking to automatically send updates to staff and students for any issues, and currently any person who is a member of these global mailing lists can remove the entire group!

Currently we're duplicating the effort by sending an issue with a manual link to any incidents, but we'd much rather it run from one place - Plus the CachetHQ emails are very pretty.

Now, I'm aware that this could be abused in some scenarios, so I'm not sure how this could be implemented in a way that satisfies both sides?

Cheers,
James.

**Comment by jbrooksuk** [comment]
Hi @absolutejam I'm so sorry for the delay here!

> First of all - Awesome work on this project! We've begun using it for transparency and had great feedback, so I'd like to pass that straight back to you guys who did the hard work.

Thank you very kindly, I love hearing feedback like this 😁 

As you've already mentioned, this would be a big security issue and with GDPR, it's not something I'm keen on implementing as we could never guarantee the use of such option.

Once https://github.com/CachetHQ/Cachet/issues/3101 is implemented, you'd actually be able to go into the email views and remove the subscription links. For internal use, this would sit within GDPR, so you'd be okay.

Hope this helps, sorry there's not much you could do short-term.
