### ISSUE TITLE
Enable Third Party Dependencies doesn't stop Cloudflare calls

### ISSUE THREAD

**Issue by mflpopescu** [CachetHQ/Cachet#2855]
Hi guys, I've disabled flag "Enable Third Party Dependencies (Google Fonts, Trackers, etc...)" but Cloudflare cookies are still set. I'm using Cachet 2.5.0-dev.

Un-setting the flag succesfully stopped external calls for Google fonts but CloudFlare calls are still being made. Is there any way to stop this ? 

![image](https://user-images.githubusercontent.com/22353083/34204719-071311b2-e580-11e7-9ab9-5f1f0abf65a0.png)

**Comment by GrahamCampbell** [comment]
If your website is behind Cloudflare, then that cookie will be set, and cannot be removed. This is out of Cachet's hands.

**Comment by GrahamCampbell** [comment]
> but CloudFlare calls are still being made.

What do mean?

**Comment by mflpopescu** [comment]
1) script `/build/dist/js/all-b2c62d4294.js` is called on page load
above script contains reference to `https://cdnjs.cloudflare.com/ajax/libs/zxcvbn/2.0.2/zxcvbn.min.js` . Just search for cloudflare in the js file

2) /dashboard has a link to `https://www.gravatar.com/avatar/..` to populate the user icon. This is with `Enable Third Party Dependencies (Google Fonts, Trackers, etc...` disabled

**Comment by jbrooksuk** [comment]
1. That can be a compiled dependency now. 
2. That’s changed in 2.4

**Comment by mflpopescu** [comment]
1 - any way to point to a local file ? What is generating the cloudflare cookies ?
2 - I'm using  2.5.0-dev and it still has the Gravatar reference

Cheers
