### ISSUE TITLE
Email does not send when the incident visibility limit to logged in user

### ISSUE THREAD

**Issue by joshuaavalon** [CachetHQ/Cachet#2857]
Version 2.3.12

As title. If a incident is created with "Only visible to logged in users", even "Notify subscribers?" is checked, email will not be sent. Public incident is fine.

**Comment by xreeckz** [comment]
Can confirm this.

**Comment by jbrooksuk** [comment]
Is this a bug though? If the incident isn't visible to the public, then sending notifications about it doesn't make sense.

What's the expected behaviour here?

**Comment by joshuaavalon** [comment]
@jbrooksuk How can a non-user subscribe? From my understand, a non-public issue just mean it is not visible without login. It should have nothing to do with subscribe.

**Comment by jbrooksuk** [comment]
Anyone can subscribe to a status page if it's public and you've enabled the setting.

**Comment by joshuaavalon** [comment]
@jbrooksuk My word still true though. Sending out email and visibility should be two different things.

**Comment by jbrooksuk** [comment]
@joshuaavalon can you break down what you're expecting to happen, both when you have public subscriptions and internal users, please?

**Comment by joshuaavalon** [comment]
@jbrooksuk Here is some pseudo code
if notify subscribers
    if public
        Notify everyone
    else
        Notify internal user
else
   No notify

**Comment by jbrooksuk** [comment]
Thank you for your input on Cachet 2.x. We are shifting our attention and resources to Cachet 3.x and will no longer be supporting the 2.x version. If your feedback or issue is relevant to the 3.x series, we encourage you to engage with the new branch.

For more information on the Cachet rebuild and our plans for 3.x, you can read the announcement [here](https://github.com/CachetHQ/Cachet/discussions/4342).

We appreciate your understanding and look forward to your contributions to the new version.
