### ISSUE TITLE
Settings Cache Issues

### ISSUE THREAD

**Issue by matthewsuan** [CachetHQ/Cachet#2858]
I am using the latest version 2.4.0dev.

When I save something, it gets persisted to the DB but the bootstrap cachet/production file still has the old settings values.

I don't see any error on the logs and I am pretty sure I don't have permissions issues on these folders.

Is there any way I can disable this settings cache?

**Comment by GrahamCampbell** [comment]
You can manually flush such caches by deleting the non-hidden files in `boostrap/cache` and `boostrap/cachet`.

**Comment by matthewsuan** [comment]
Yep I did that but it just create again same cache files with old credentials.

Besides, I dont want to do this everytime I update settings on the admin pages :)

However, I just implemented a quick and dirty workaround by returning `false` on the `load` method of the `App\Settings\Cache` class.

**Comment by jbrooksuk** [comment]
Are the `cachet` directories writeable? We regenerate the caches.
