### ISSUE TITLE
 Undefined variable: log

### ISSUE THREAD

**Issue by borgogelli** [CachetHQ/Cachet#2859]
Hello
I have cloned the version 2.4.0-dev from the master branh.
Running it I got following error in the cachet's log

` Undefined variable: log in cachet/app/Http/Controllers/Dashboard/SettingsController.php:279`

then I can't access the Log page from the Setting section on the web gui.

Regards

**Comment by nefarius** [comment]
Hey hey,

same here, fresh installation of `2.4.0-dev`.

**Comment by jbrooksuk** [comment]
This is now fixed :)

**Comment by nefarius** [comment]
Amazing, will test tomorrow, thanks! Now I just need mailing to get to work and we're set 😎
