### ISSUE TITLE
[Feature Request] Component group deletion

### ISSUE THREAD

**Issue by willdurand** [cachethq/Cachet#286]
It would be nice to be able to delete component groups.

I'd say, if and only if there is no component associated with a group. However, if a component can be group-less, we could delete any component group, and make its components group-less.

**Comment by jbrooksuk** [comment]
The idea is that the status page would group components, if they're not in a group, they'll appear above the groups list.

Removing a group wouldn't affect the components (except remove the `group_id` value).
