### ISSUE TITLE
Changes to Count() in PHP 7.2 Cause 500 internal Error.

### ISSUE THREAD

**Issue by VinMck** [CachetHQ/Cachet#2862]
Using:
Windows Server 2016
Cachet 2.3.9
PHP 7.2
Apache 2.4

After completing the install I get the 500 Internal Server Error. When I look in the error logs I see the following.
[Mon Jan 08 11:32:13.533024 2018] [php7:error] [pid 6812:tid 1052] [client 127.0.0.1:59375] PHP Fatal error:  Uncaught ErrorException: count(): Parameter must be an array or an object that implements Countable in E:\\Cachet Status Page\\cachet\\vendor\\graham-campbell\\exceptions\\src\\ExceptionIdentifier.php:51\nStack trace:\n#0 [internal function]: Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleError(2, 'count(): Parame...', 'E:\\\\Cachet Statu...', 51, Array)\n#1 E:\\Cachet Status Page\\cachet\\vendor\\graham-campbell\\exceptions\\src\\ExceptionIdentifier.php(51): count(NULL)\n#2 E:\\Cachet Status Page\\cachet\\vendor\\graham-campbell\\exceptions\\src\\ExceptionHandlerTrait.php(47): GrahamCampbell\\Exceptions\\ExceptionIdentifier->identify(Object(ErrorException))\n#3 E:\\Cachet Status Page\\cachet\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Bootstrap\\HandleExceptions.php(79): GrahamCampbell\\Exceptions\\ExceptionHandler->report(Object(ErrorException))\n#4 [internal function]: Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleException(Object(ErrorException))\n#5 {main}\n  thrown in E:\\Cachet Status Page\\cachet\\vendor\\graham-campbell\\exceptions\\src\\ExceptionIdentifier.php on line 51

[Mon Jan 08 11:32:13.533024 2018] [php7:error] [pid 6812:tid 1052] [client 127.0.0.1:59375] PHP Fatal error:  Uncaught ErrorException: count(): Parameter must be an array or an object that implements Countable in E:\\Cachet Status Page\\cachet\\vendor\\graham-campbell\\exceptions\\src\\ExceptionIdentifier.php:51\nStack trace:\n#0 [internal function]: Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleError(2, 'count(): Parame...', 'E:\\\\Cachet Statu...', 51, Array)\n#1 E:\\Cachet Status Page\\cachet\\vendor\\graham-campbell\\exceptions\\src\\ExceptionIdentifier.php(51): count(NULL)\n#2 E:\\Cachet Status Page\\cachet\\vendor\\graham-campbell\\exceptions\\src\\ExceptionHandlerTrait.php(47): GrahamCampbell\\Exceptions\\ExceptionIdentifier->identify(Object(Symfony\\Component\\Debug\\Exception\\FatalErrorException))\n#3 E:\\Cachet Status Page\\cachet\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Bootstrap\\HandleExceptions.php(79): GrahamCampbell\\Exceptions\\ExceptionHandler->report(Object(Symfony\\Component\\Debug\\Exception\\FatalErrorException))\n#4 E:\\Cachet Status Page\\cachet\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Bootstrap\\HandleExcept in E:\\Cachet Status Page\\cachet\\vendor\\graham-campbell\\exceptions\\src\\ExceptionIdentifier.php on line 51

After doing a bit of googling it seems there was a change to Count in PHP 7.2 that is the cause of this.

**Comment by GrahamCampbell** [comment]
Yes, cachet 2.3.9 won't work properly on php 7.2. You'll need 2.3-dev or 2.4-dev.

**Comment by Daniel15** [comment]
@GrahamCampbell Is there any ETA for a stable release with PHP 7.2 compatibility?

**Comment by agentcobra** [comment]
ok, same issue for me.
I'm trying 2.4 versions

**Comment by jbrooksuk** [comment]
3.0 (currently 2.4) will support PHP 7.2 once we've upgraded Laravel.

**Comment by dennusb** [comment]
I still have this problem, has it been resolved already?

**Comment by Daniel15** [comment]
I switched my installation to the 2.4 branch, which fixed the issue.
