### ISSUE TITLE
How to install 2.4

### ISSUE THREAD

**Issue by hostingwalk** [CachetHQ/Cachet#2865]
git tag -l only possible v2.3.9   or v2.3.13 if you try,  but is it hard to install 2.4 version ?

**Comment by uxen-ab** [comment]
The 2.4 is under development, so there is no v2.4 yet. You can use `git checkout 2.4` instead, at your own risk.
Some people use the 2.4 version, there are some instable features and lot of issues, but according to what you want to use, it _may_ be possible.
I think there is a migration from 2.3.9 to 2.4, isn't? You'd use the 2.3.9 for know and then migrate to 2.4 when it is stable.

**Comment by hatclub** [comment]
Just a small point of order, v2.3.13 is the current stable, btw, since October

**Comment by DerDanilo** [comment]
When will 2.4 be released? Having issues with the mail sending and want the GUI test button for that. :)

**Comment by MikeKMiller** [comment]
@jbrooksuk this new support thing is "far" from helpful. Why not just answer the question? Or at the very least have the "support" bot provide an answer that is somewhat supportive, such as how to reach the "support" channels

**Comment by uxen-ab** [comment]
@MikeKMiller Github is used for development, bug and feature request, but the project has a great Slack community where people will be glad to help you. With your email address we'd invite you to join us.

**Comment by jbrooksuk** [comment]
@MikeKMiller as @uxen-ab said. We can change the bot message to invite you to http://cachethq-slack.herokuapp.com/
