### ISSUE TITLE
Use an open-source emoji library

### ISSUE THREAD

**Issue by Foorack** [CachetHQ/Cachet#2869]
Examples are "Noto Color Emoji" or Twemoji.
[https://www.google.com/get/noto/help/emoji/](https://www.google.com/get/noto/help/emoji/)

This would remove the requirement for a Github API key to render emojis.

**Comment by jbrooksuk** [comment]
@Foorack do you know of any projects which implement these fonts in something similar to [AltThree/Emoji](https://github.com/AltThree/Emoji/)?

**Comment by Foorack** [comment]
I don't know anyone using that specifically. I have never used Larvel before,but you shouldn't have to enter an API key just to see emojis.

**Comment by Foorack** [comment]
This should be reopened @jbrooksuk
Github API key is an unnecessary technical barrier and requirement.

**Comment by jbrooksuk** [comment]
I see the feature as a "nice to have". The status page doesn't stop working if you don't have a key.

**Comment by JoshSalway** [comment]
@jbrooksuk FYI - the demo project on iPhone emojis not shoeing?

**Comment by jbrooksuk** [comment]
Thank you for your input on Cachet 2.x. We are shifting our attention and resources to Cachet 3.x and will no longer be supporting the 2.x version. If your feedback or issue is relevant to the 3.x series, we encourage you to engage with the new branch.

For more information on the Cachet rebuild and our plans for 3.x, you can read the announcement [here](https://github.com/CachetHQ/Cachet/discussions/4342).

We appreciate your understanding and look forward to your contributions to the new version.
