### ISSUE TITLE
Exception in graham-campbell/exceptions/src/ExceptionIdentifier.php with latest git master

### ISSUE THREAD

**Issue by cboltz** [CachetHQ/Cachet#2878]
I see this error with latest git master (a2a36cd0801d349d6164b1934d72740c44a4a9de)

`[Sun Jan 21 18:22:01.664300 2018] [php7:error] [pid 7825] [client 127.0.0.1:59350] PHP Fatal error:  Uncaught ErrorException: count(): Parameter must be an array or an object that implements Countable in /home/www/cachet.tux/httpdocs/cachet/vendor/graham-campbell/exceptions/src/ExceptionIdentifier.php:52\nStack trace:\n#0 [internal function]: Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleError(2, 'count(): Parame...', '/home/www/cache...', 52, Array)\n#1 /home/www/cachet.tux/httpdocs/cachet/vendor/graham-campbell/exceptions/src/ExceptionIdentifier.php(52): count(NULL)\n#2 /home/www/cachet.tux/httpdocs/cachet/vendor/graham-campbell/exceptions/src/ExceptionHandlerTrait.php(47): GrahamCampbell\\Exceptions\\ExceptionIdentifier->identify(Object(ErrorException))\n#3 /home/www/cachet.tux/httpdocs/cachet/bootstrap/cache/compiled.php(2163): GrahamCampbell\\Exceptions\\ExceptionHandler->report(Object(ErrorException))\n#4 [internal function]: Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleException(Object(ErrorException))\n#5 {main}\n  thrown in /home/www/cachet.tux/httpdocs/cachet/vendor/graham-campbell/exceptions/src/ExceptionIdentifier.php on line 52`

After adding a var_dump() call, it turns out that `$this->identification` is `NULL`, so at least it's not surprising that it can't be count()ed.

If I edit vendor/graham-campbell/exceptions/src/ExceptionIdentifier.php and change
```
    protected $identification;
```
to
```
    protected $identification = array();
```
it works and var_dump() prints an array with several uuids.

I'm not sure if this is a bug in cachet or in the exceptions module, therefore I'm reporting it here first. Feel free to upstream this bugreport (or tell me where to upstream it, if you don't want to do it yourself)

CC @ccboltz

**Comment by jbrooksuk** [comment]
What version of Cachet and PHP are you using?

**Comment by cboltz** [comment]
Cachet: git master (a2a36cd)

PHP 7.2.1

**Comment by uxen-ab** [comment]
My installation of Cachet on branch `2.4` uses `graham-campbell/exceptions` version `v9.4.0`, what is the version insalled in your Cachet? You can find this information in the `composer.lock` file.
In the version of `graham-campbell/exceptions` used in my Cachet, the error doesn't exist:

```
protected $identification = [];
```

I've ran `composer update` in order to get the latest version of this package, and the line is correct. Maybe you're not up to date?

**Comment by cboltz** [comment]
Looks like you pointed me to the right direction - I indeed had an old version. Also, it turned out that the `master` branch of Cachet was last updated in 2016 and the active development happens in the `2.4` branch.

I switched to the `2.4` branch, deleted the vendor directory and used `composer install --no-dev -o` to re-populate it - now with v9.4.0.

Unfortunately all I gained is a different error:

```
# rm -r vendor
# composer install --no-dev -o
Loading composer repositories with package information
Installing dependencies from lock file
Package operations: 78 installs, 0 updates, 0 removals
  - Installing [... lots of modules ...]
Package graham-campbell/core is abandoned, you should avoid using it. No replacement was suggested.
Generating optimized autoload files
> Illuminate\Foundation\ComposerScripts::postInstall
> php artisan optimize
PHP Fatal error:  Uncaught Error: Class name must be a valid object or a string in /home/www/cachet.tux/httpdocs/cachet/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php:96
Stack trace:
#0 [internal function]: Illuminate\Foundation\Exceptions\Handler->Illuminate\Foundation\Exceptions\{closure}(0, 'Illuminate\\Http...')
#1 /home/www/cachet.tux/httpdocs/cachet/bootstrap/cache/compiled.php(6451): call_user_func(Object(Closure), 0, 'Illuminate\\Http...')
#2 /home/www/cachet.tux/httpdocs/cachet/bootstrap/cache/compiled.php(12599): Illuminate\Support\Arr::first(Array, Object(Closure), NULL)
#3 /home/www/cachet.tux/httpdocs/cachet/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(97): Illuminate\Support\Collection->first(Object(Closure))
#4 /home/www/cachet.tux/httpdocs/cachet/vendor/graham-campbell/exceptions/src/ExceptionHandlerTrait.php(40): Illuminate\Foundation\Exceptions\Handler->shouldntReport(Object(Symfony\Component\Debug\Exception\FatalThrowableError))
#5 /home/www/cachet.tux/ in /home/www/cachet.tux/httpdocs/cachet/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php on line 96
PHP Fatal error:  Uncaught Error: Class name must be a valid object or a string in /home/www/cachet.tux/httpdocs/cachet/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php:96
Stack trace:
#0 [internal function]: Illuminate\Foundation\Exceptions\Handler->Illuminate\Foundation\Exceptions\{closure}(0, 'Illuminate\\Http...')
#1 /home/www/cachet.tux/httpdocs/cachet/bootstrap/cache/compiled.php(6451): call_user_func(Object(Closure), 0, 'Illuminate\\Http...')
#2 /home/www/cachet.tux/httpdocs/cachet/bootstrap/cache/compiled.php(12599): Illuminate\Support\Arr::first(Array, Object(Closure), NULL)
#3 /home/www/cachet.tux/httpdocs/cachet/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(97): Illuminate\Support\Collection->first(Object(Closure))
#4 /home/www/cachet.tux/httpdocs/cachet/vendor/graham-campbell/exceptions/src/ExceptionHandlerTrait.php(40): Illuminate\Foundation\Exceptions\Handler->shouldntReport(Object(Symfony\Component\Debug\Exception\FatalErrorException))
#5 /home/www/cachet.tux/ in /home/www/cachet.tux/httpdocs/cachet/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php on line 96
Script php artisan optimize handling the post-install-cmd event returned with error code 255
```
I also did `composer update --no-dev -o` which updated some modules, but ended with the same error message.

I added some debugging output to `vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php` `shouldntReport()`, and it turned out that `$type` is `int(0)`. This easily explains `Class name must be a valid object or a string in .../vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php:97` - but unfortunately I have no idea *why* it is an integer.

**Comment by uxen-ab** [comment]
Indeed the development is in the branch 2.4.

For your new error, it's weird because I haven't the error. But it seems that the problem may be reproduced by using `php artisan optimize`. Are you sure about your version of PHP? Sometimes the cli version is not the same as the one used by the web server.

There is one other thing, in your dump I see `78 installs`, I've just cloned the Cachet repository and l've launched `composer install --no-dev -o` and I've 79 installs. But it may be a detail.

**Comment by cboltz** [comment]
Yes, I'm sure about having PHP 7.2.1 everywhere ;-)

To check if there are 78 or 79 installs, I just did
```
# rm -r vendor
# rm rm bootstrap/cache/*.php
# composer install --no-dev -o
...
Package operations: 78 installs, 0 updates, 0 removals
```

Now the interesting part - I no longer see the error, and Cachet just works :-)

I have no idea what changed since yesterday, but anyway - problem solved :-)

**Comment by uxen-ab** [comment]
Did you have removed the content of `bootstrap/cache/*` on the first install? It wasn't on the result.
Anyway, It's solved :)
