### ISSUE TITLE
Need assistance for status page setup.

### ISSUE THREAD

**Issue by furqank786** [CachetHQ/Cachet#2886]
@jbrooksuk  @fabian @yoyosan @luismulinari @mwillbanks 

I am new to the Cachet, it very light and elegant. I have installed this on my server. Added the website as a component to check the status log (if any issue/problem occur/working normal) on daily basis. This status should be appear on the my status page.
I am using version 2.4    

To get this working what steps should I follow?

1. From where can I get the information to setup my status page, the link will be very helpful for this because I want to display website status on the status page automatically if through some API then can anyone please guide me in this process. 

2. Highly appericated if someone guide me through example.

Thanks in advance.

**Comment by jomurr** [comment]
https://www.digitalocean.com/community/tutorials/how-to-create-a-status-page-with-cachet-on-debian-8

Is the tutorial I followed, adapted for what I am currently using (a LEMP stack)

That should walk you through all you need to know.
