### ISSUE TITLE
Subscriber is not able to change his subscriptions

### ISSUE THREAD

**Issue by hscheffers** [CachetHQ/Cachet#2887]
Hi we have 2.4.0-dev installed and certain users can subscribe to different components.
If you subscribe yourself to email notifications, you get a screen where you can choose the components you want to receive notifications from. After the initial setup, a subscriber cannot change his subscriptions anymore, except for completely unsubscribing an resubscribing again.

It would be very nice-to-have if a subscriber could revise his subscriptions without resubscribing.

**Comment by uxen-ab** [comment]
I think in the mail the user receives on every event we should put the two links, the one for unsubscribe and the one for manage its subscriptions. I'll test that.

**Comment by jbrooksuk** [comment]
Partially done in https://github.com/CachetHQ/Cachet/pull/2890

**Comment by jbrooksuk** [comment]
Replacing this issue with https://github.com/CachetHQ/Cachet/issues/3102
