### ISSUE TITLE
Duplicate title tags and Meta Descriptions in status pages. 

### ISSUE THREAD

**Issue by suzanned88** [CachetHQ/Cachet#2895]
Hi all, 

We have a SEO issue with Cachet: 
I am having issues with meta data and title tags: all the status pages show the same meta description and title tag, so we get an error for duplicate title tags and duplicate meta descriptions. 

Is it possible to add a date or status number to the description and title manually? can it be implemented? Or is there another solution I have not thought about? 
Thanks all :)

**Comment by jbrooksuk** [comment]
Thanks for doing this so quickly @suzanned88.

@nstapelbroek fancy this one? 😉

**Comment by suzanned88** [comment]
Yw ;-)

**Comment by nstapelbroek** [comment]
It would be an honor to try this one :smile: 

I'm not sure if I can finish it before next week though. Will keep you posted

**Comment by jbrooksuk** [comment]
That's okay! :)

**Comment by nstapelbroek** [comment]
Hi @suzanned88 ,  It's finally here :tada: 

I'm not a native English speaker so if you have any suggestions on the translated messages you're more than welcome to leave them in the PR. In addition, If you had any other thoughts on how this issue should implemented (functionally or technically) I'm happy to hear that as wel.

**Comment by suzanned88** [comment]
Huray! Thank you @nstapelbroek ! 
I'm not very technical so no suggestions there ;-) is this for meta description and title tag as well? 

You have a dutch name so I would say you are dutch? Me too :)

**Comment by suzanned88** [comment]
Hi all/ @nstapelbroek , is there an update for this issue? Thanks!

**Comment by nstapelbroek** [comment]
Hi @suzanned88 I've submitted an PR that inserts generic title and descriptions on the overview, subscribe, incident details and schedule details pages. This PR is merged and should be available in the upcoming 2.4 release. (@jbrooksuk is there an option to merge it back as a fix to 2.3? Can I help with this?)

In addition, after submitting the PR I discovered you were actually asking for a manual way to insert the data :see_no_evil:, sorry about that. I'll get working on this tonight but can't promise a delivery date. @suzanned88 maybe you could help me out? Functionally speaking, what would be your preference? I could just slap two extra fields in the from when creating a incident or incident update but I'm not sure if that's what you are looking for.

**Comment by suzanned88** [comment]
As long as it fixes my duplicate title and description error, I'm also happy with the automatically filled in info, so no rush there! ;-) 

What I would suggest is that you fill in the meta title and description automatically, but also give users the option to manually change the Meta Description and title tag to something the user chooses. Something similair to the option in Wordpress I quess.

**Comment by jbrooksuk** [comment]
@suzanned88 what version of Cachet are you using? @nstapelbroek we could cherry pick into 2.3 if there was a need, yeah.

**Comment by suzanned88** [comment]
Hi @jbrooksuk I see you closed this issue. Is it fixed? can we update out Cachet-version?
