### ISSUE TITLE
Complete setup problem

### ISSUE THREAD

**Issue by GentillePlume** [CachetHQ/Cachet#2896]
Hi,

When I clic "Complete setup", I have this error : 
![opera_2018-01-30_10-40-20](https://user-images.githubusercontent.com/23276163/35559145-3d07451e-05aa-11e8-9b49-86ba4f6ba6c9.png)

Can you have a solution for this problem ?

Regards,

**Comment by jbrooksuk** [comment]
Can you supply us with your latest log file please?

**Comment by GentillePlume** [comment]
I arrived to install cachet. I do this : `php artisan app:install` and the bug was resolved. But when I want to do modification, if I want to apply the modification I must do `php artisan app:install` to apply the modification.
[laravel-2018-01-30.log](https://github.com/CachetHQ/Cachet/files/1677956/laravel-2018-01-30.log)

**Comment by jbrooksuk** [comment]
```
[2018-01-30 09:38:40] production.ERROR: ErrorException: file_put_contents(/home/www/status/.env): failed to open stream: Permission denied in /home/www/status/app/Http/Controllers/SetupController.php:257
```

You need to make sure the `.env` file is writeable by the web process.
