### ISSUE TITLE
MySQL queue runner only sends one email at once

### ISSUE THREAD

**Issue by hatclub** [CachetHQ/Cachet#2898]
Cachet 2.3.13

There's 440 items in the queue at the moment because of #2605 :disappointed: . Only one goes each minute when the cron runs. It's not even "one per minute per recipient", as an email address confirmation message to a different recipient is stuck behind all the "this component is now operational!" messages. This seems undesirable.

I'll switch to supervisor, but as is, the mysql queue runner is not useful and should not be used by anyone.

**Comment by jbrooksuk** [comment]
The queue runner is just Laravel, so it'd be a configuration thing.
