### ISSUE TITLE
Emails should contain a List-Unsubscribe header

### ISSUE THREAD

**Issue by hatclub** [CachetHQ/Cachet#2899]
Cachet v2.3.13

Emails to subscribers generated by the system do not have a List-Unsubscribe header (and really should).

**Comment by anthonybocci** [comment]
Absolutely right, thank about it!
I'll check about that in some days.

**Comment by jbrooksuk** [comment]
Honestly, I'd never heard of this header. This is simple to integrate though. Up for grabs!

**Comment by jbrooksuk** [comment]
I'm going to replace this with https://github.com/CachetHQ/Cachet/issues/3102 and keep all subscriber based stuff in one place :)
