### ISSUE TITLE
Don't allow admin account to be changed by team members

### ISSUE THREAD

**Issue by jbrooksuk** [cachethq/Cachet#290]
Currently any team member can change the admin account. This shouldn't be allowed.

**Comment by jbrooksuk** [comment]
Do we prevent the admin account from even being listed in the team members?

**Comment by foxted** [comment]
I think it would be a good idea. Also, there is still a view in a `user` folder, maybe we should move everything related to `teams` in a team folder?

**Comment by jbrooksuk** [comment]
This will also allow us to have an admin account on the demo and keep the `test@test.com` account separate.

**Comment by jbrooksuk** [comment]
Following on from this, when the administrator creates a new account, they could pick varying levels:

- Administrator
- Owner
- Member

Or whatever, then we can limit the features based on the `level` on the user.

**Comment by joecohens** [comment]
@jbrooksuk Basically a simple ACL?

**Comment by jbrooksuk** [comment]
@joecohens yeah, basically. Nothing complicated though.

**Comment by jbrooksuk** [comment]
For now, just the password can no longer be changed. ac28264d94b4daf39f1ef0f8a3b2d41ceac5f19f
