### ISSUE TITLE
[Request] UX - Move subscribe button to the header

### ISSUE THREAD

**Issue by xthiago** [CachetHQ/Cachet#2901]
The subscribe button is currently positioned on the footer and is very simple. In practice very few people click on this button.

In order to improve the use of that feature (UX), I would like to suggest moving this button to the header like some companies does, like:

<img width="971" alt="captura de tela 2018-02-01 as 18 36 21" src="https://user-images.githubusercontent.com/720151/35702489-6708e020-0780-11e8-9da6-428984ad50bd.png">

If the project maintainers agree I can write the necessary code and open a pull request.

What you think?

**Comment by jbrooksuk** [comment]
Yeah, this will be handled in the new redesign when we get to it :)
