### ISSUE TITLE
Error 500 when adding email subscribers from Dashboard and subscription button

### ISSUE THREAD

**Issue by jomurr** [CachetHQ/Cachet#2902]
Hello,

I am experiencing troubles with subscription and mail functionalities. I found the root of the issue in the logs; swiftmailer is trying to establish a connection at smtp.example.com (example replacing my site's hostname) when really it should be connecting to smtp.gmail.com. I specified the SMTP server both in .env before running setup and during the initial setup. 

Currently running V 2.3.13

**Comment by Slaine1987** [comment]
Hi jomurr, how did you fixed it?
