### ISSUE TITLE
Update documentation about Cachet API

### ISSUE THREAD

**Issue by hugomcfonseca** [CachetHQ/Cachet#2903]
Hello. 

I would like to know if it is possible to update Cachet documentation about its API (preferably, including already new routes added for Cachet v2.4). I am trying to improve existing Golang client to be compatible with your latest Cachet's version.

Thanks and congrats about your great job with this app.

**Comment by anthonybocci** [comment]
Hello,

I'll take a look if [laravel-apidoc-generator](https://github.com/mpociot/laravel-apidoc-generator) does the job. I would be really great if documentation was updated automatically.

**Comment by anthonybocci** [comment]
I'm only at the beginning step and I've documented three controllers, probably not fully, but if you want to test you can use my [automatic-api-doc](https://github.com/anthonybocci/Cachet/tree/automatic-api-doc) branch.
To generate the doc, execute `php artisan api:generate --routePrefix="api/v1/*"`and open the file `public/docs/index.html`.
I'll customize that later.

**Comment by anthonybocci** [comment]
This issues throws an other question: the API documentation could be updated or generated via command line, but what about the rest of the documentation? It could be really great to have a `resources/docs` directory that contains markdown files that explain all the install process and other. They could be updated easier.

**Comment by jbrooksuk** [comment]
We could use something like Swagger?

**Comment by hugomcfonseca** [comment]
Yes, it would be fine by me @jbrooksuk. And Swagger will help to keep documentation updated every time a new endpoint is added/changed/deleted, so it would be great.

**Comment by anthonybocci** [comment]
The package [DarkaOnLine/L5-Swagger](https://github.com/DarkaOnLine/L5-Swagger) seems to be the job.
I'll update my pull request to add the SwaggerPHP annotations in addition to the documentation block I've ever added.

**Comment by jbrooksuk** [comment]
I'm keen on this being generated to support Readme.io

**Comment by anthonybocci** [comment]
If we use ApiDoc (as discussed in #2929) there would be no need of Swagger and we could be synced with Readme.io.

**Comment by anthonybocci** [comment]
It could be great if a package would be able to use the Laravel's routes and the doc block to generate Swagger. [Swagger-php][1] needs all the information, but perhaps an other package or a wrapper would be able to do more?

[1]: https://github.com/zircote/swagger-php

**Comment by jbrooksuk** [comment]
I don't know much about Swagger, but yeah it would be very cool!

**Comment by anthonybocci** [comment]
I'm not sure if there is a such package. It would be annoying to type path and method for every route. It could be almost sufficient to generate the swagger.

**Comment by anthonybocci** [comment]
I suggest to accept the documentation update that I'd done in #2929 because generated documentation always uses PHP Doc, and keeping this issue open.
When we find a package that uses Laravel's routes to generate a Swagger file we'll add it.
What do you think about it?

**Comment by jbrooksuk** [comment]
I think we should get Swagger working because that's what we need to update Readme.io with.

**Comment by anthonybocci** [comment]
I agree to get Swagger working. The thing with swagger-php is we have to write all path (`/api/v1/components`) on every method, it's not synced with the Laravel's routes.
Any solution to that point?

**Comment by jbrooksuk** [comment]
Nah, but if that's what it takes, maybe we just get on with it?

**Comment by anthonybocci** [comment]
If we have no solution for that, we could use Swagger with an effort to keep the documentation up to date. If you're ok with that, I'll add Swagger to my PR.

**Comment by jbrooksuk** [comment]
Let's go with Swagger. We can import it into Readme.io then.

**Comment by jbrooksuk** [comment]
Alternatively, we could export documentation into this https://readme.readme.io/docs/importing-documentation

**Comment by jbrooksuk** [comment]
I'm actually going to do that as well because it's super useful.

**Comment by jbrooksuk** [comment]
(Not for API).

**Comment by jbrooksuk** [comment]
Exported to https://github.com/CachetHQ/Docs which does contain the API pages, but with no actual API info in them.
