### ISSUE TITLE
[Feature request] Incidents filter

### ISSUE THREAD

**Issue by sofasurfer** [CachetHQ/Cachet#2905]
I know this is not really an issue more a feature request, but would it be possible to add a filter to the incidents list on the dashboard /dashboard/incidents.

This would allow me to filter incidents by status?

Thanks great work!

**Comment by anthonybocci** [comment]
Hi,
You could perhaps update the issue title to be a bit more direct, like `[Feature request]Incidents filter in dashboard`.
The idea is interesting! Indeed for an administrator viewing many incidents may be difficult. I haven't checked that yet but I guess the incidents are ordered by the date of the last update, that would be logical. Incidents that occurred 2 years ago will not be edited nor searched I think, only the current incidents will be used, so I am not sure if the filter is a critical feature.
What would be the goal of filtering all the status by their status?

**Comment by sofasurfer** [comment]
Hi,

thanks for the reply. Sure this is not critical, it just would be nice if i could see only the incidents which are not fixed. Now it's difficult to find them, if there are allot of incidents.

The goal would be, to filter incidents by there status.

**Comment by anthonybocci** [comment]
In the lifecycle of an incident, the end occurred some time after its creation. Usually there are not many incidents that have been created between the creation and the end of the original incident.
But the idea of filtering the incident by some fields is interesting and may be useful. When I'll have a bit more time, I'll take a look to that.

**Comment by jonasdkhansen** [comment]
This feature is also smart, for companies using cachethq for incident documentation. So if you are experiencing issues, with one of your services, and want to see what was done last time, that specific incident happened, then it would be nice to search at the top of the page for issues that could relate.

It would also be smart to filter by date, so when a weekly incident meeting is up, then you could quickly filter out the past week incidents to talk about.

**Comment by anthonybocci** [comment]
I agree with @jonasdkhansen and @sofasurfer , indeed it could be useful to have a filter on the incidents. So I suggest to describe what kind of filters we could need.
- date (from/to, inclusive)
- status ([not]resolved, etc)
- name

I guess with at least these three filters we would be able to find our incidents without problems.
Is someone already working on it?

**Comment by jbrooksuk** [comment]
Not me @anthonybocci. 

Talking of being able to filter by date, this is in the new design (which I must share). There is a sidebar with a breakdown of each month/year.

**Comment by anthonybocci** [comment]
@jbrooksuk so we should wait for the new design before working on this issue.

**Comment by jbrooksuk** [comment]
Yeah, it’s the better way of doing it IMHO.

**Comment by anthosz** [comment]
Dear all,

Do we have a timeline for this feature?

Best regards,

**Comment by jbrooksuk** [comment]
Whilst I'm thinking about it, I'd like to provide a global search on the Cachet dashboard too.

@anthosz not yet, sorry. @ojdon is working on implementing our new design, so once that is done, we'll know more.

**Comment by jbrooksuk** [comment]
Thank you for your input on Cachet 2.x. We are shifting our attention and resources to Cachet 3.x and will no longer be supporting the 2.x version. If your feedback or issue is relevant to the 3.x series, we encourage you to engage with the new branch.

For more information on the Cachet rebuild and our plans for 3.x, you can read the announcement [here](https://github.com/CachetHQ/Cachet/discussions/4342).

We appreciate your understanding and look forward to your contributions to the new version.
