### ISSUE TITLE
500 Error but not the error page from cachet

### ISSUE THREAD

**Issue by dudeisbrendan03** [CachetHQ/Cachet#2910]
.env: https://gist.github.com/dudeisbrendan03/d4632c64994977d8c48482fa67458faf
Cachet Ver: 2.3.9
PHP Ver: 5.5.9
Apache: 2.4.7

PHP APC Installed
All requested dependencies installed

I have tried backing up permissions then settings 777.
The actual error page isn't displayed, just the chrome default one.
I have installed with `php artisan app:install`
I've tried clearing the cache with: `rm -rf bootstrap/cache/*`

**Comment by joedguarino** [comment]
Could be several things.  I'd recommend jumping on the Cachet Slack server for real-time assistance. https://cachethq.slack.com

**Comment by dudeisbrendan03** [comment]
I need a @alt-three.com email or an invite to join
