### ISSUE TITLE
Error while installing

### ISSUE THREAD

**Issue by OfficialCRUGG** [CachetHQ/Cachet#2913]
Heya!

I followed the [Installing Cachet Page](https://docs.cachethq.io/docs/installing-cachet) but I'm stuck at `php artisan key:generate`. It just prints _"PHP Fatal error:  Class 'Illuminate\Foundation\Application' not found in /var/www/Cachet/bootstrap/app.php on line 12"_. Does anyone know the problem?

**Comment by cjreysayago** [comment]
Hi. This error message is displayed because of a project missed dependency. Try this command on project root directory
`composer install --no-dev -o` and try again

**Comment by OfficialCRUGG** [comment]
Root Directory of Server or of Cachet?

**Comment by faustoFF** [comment]
@OfficialCRUGG Cachet directory (where file composer.json). In your case: /var/www/Cachet/
