### ISSUE TITLE
How to use Third party apps metrics.

### ISSUE THREAD

**Issue by ianjayloguinto** [CachetHQ/Cachet#2917]
Hi, Sorry for being a noob but I can't find a proper documentation that helps a newbie like me to integrate 3rd party apps in cachethq.
Can someone give me an instruction on how can I use a working sample metrics like the "Cups of Coffee" in demo page https://demo.cachethq.io/

**Comment by anthonybocci** [comment]
Hello and welcome in Cachet,

Cachet is a status page but there are [many plugins](https://docs.cachethq.io/docs/addons) that profile a web server or something else and that post the results to the API. 
I've used [Cachet Monitor](https://github.com/castawaylabs/cachet-monitor) once and it's great and easy to use. You configure it with your URL, your api key, the component to update, the metric to populate, some other parameters, and it does all the job!

**Comment by successtar** [comment]
> Hi, Sorry for being a noob but I can't find a proper documentation that helps a newbie like me to integrate 3rd party apps in cachethq.
> Can someone give me an instruction on how can I use a working sample metrics like the "Cups of Coffee" in demo page https://demo.cachethq.io/



> Hi, Sorry for being a noob but I can't find a proper documentation that helps a newbie like me to integrate 3rd party apps in cachethq.
> Can someone give me an instruction on how can I use a working sample metrics like the "Cups of Coffee" in demo page https://demo.cachethq.io/



> We use the issue tracker exclusively for bug reports and feature requests. However, this issue appears to be a support request. Please use our support channels to get help with the project.



> Hi, Sorry for being a noob but I can't find a proper documentation that helps a newbie like me to integrate 3rd party apps in cachethq.
> Can someone give me an instruction on how can I use a working sample metrics like the "Cups of Coffee" in demo page https://demo.cachethq.io/


You can give this a try https://github.com/successtar/cachet-manager
