### ISSUE TITLE
Remove 2FA (Login in problem)

### ISSUE THREAD

**Issue by 009800** [CachetHQ/Cachet#2918]
For some reason Cachet does not update the google_2fa_secret so I can't login. (Always invalid token) (I guess something is blocked in the internet connection)
Is there a way to reset the 2fa? Or to set it manually, like the passwords with tinker.

**Comment by 009800** [comment]
Solved by E-Mail Support: set google_2fa_secret to null with tinker

**Comment by kevin-og** [comment]
> Solved by E-Mail Support: set google_2fa_secret to null with tinker

hey @009800 sorry to bring this back up, but can you post commands after 'php artisan tinker' to null out google_2fa_secret ?

**Comment by kevin-og** [comment]
Nevermind, got it.  

>>> $user->update(['google_2fa_secret' => null]);
