### ISSUE TITLE
database migrating issue

### ISSUE THREAD

**Issue by kzdd** [CachetHQ/Cachet#2919]
Hello. I am installing Cachet follow the installation instruction. When I am doing the database migration and app install (php artisan app:install), there are some errors appear and shows as the image. 
![screen shot 2018-02-22 at 3 18 55 pm](https://user-images.githubusercontent.com/22047306/36569775-fd2683fa-17e3-11e8-94fb-db0be88fd60e.png)
I am using mariadb and macOS Sierra. php is 5.6, Before using mariadb.please advice,  Thanks!

**Comment by anthonybocci** [comment]
Hello,

You're using Mac OSX, is your `mysql.default_socket` statement well configured in php.ini?
I've got the error once using MAMP for Apache/PHP/MySQL. The MAMP's PHP was well configured to use the MAMP's MySQL, but the default PHP manually installed using Homebrew wasn't configured to use the right MySQL socket.

**Comment by kzeclincher** [comment]
@anthonybocci.  Thanks Anthony. The issue had beed solved by following your suggestion!

**Comment by kzdd** [comment]
@anthonybocci  Thanks Anthony. The issue had beed solved by following your suggestion!

**Comment by anthonybocci** [comment]
@kzdd You shouldn't run the `php artisan app:install`, it's only for installing Cachet. But you should run `php artisan app:update`. It will update your database if needed.

**Comment by kzdd** [comment]
@anthonybocci. Thank you!
