### ISSUE TITLE
Gateway Timeout on latest 2.4

### ISSUE THREAD

**Issue by labolanimichele** [CachetHQ/Cachet#2921]
Hello,

just pulled the latest 2.4.

I installed it on 2 different hosts in 2 different networks, and on both I now get a Gateway timeout quite often while navigating through the pages. It happens on different occasions and not always, does not seem to be related to the page itself.

Am I the only one experiencing this?

Thanks,
Michele

_Gateway Timeout_
_Server error - server 54.82.224.234 is unreachable at this moment._

_Please retry the request or contact your administrator._

**Comment by labolanimichele** [comment]
Hi Anthony,

Thanks for your feedback.

The reason why I opened an issue for this is that until the update this was never happening. As soon as the update was completed, the gateway timeout came up and is quite often visible in the Admin section navigating through pages.

**Comment by anthonybocci** [comment]
Can you create a Docker image or something that I could use to reproduce the problem? Because I have Cachet 2.4 on my local machine and I haven't any issue.
Also, can you remember commit number before and after the update?

**Comment by labolanimichele** [comment]
Hi,

I opened the issue right after deploying and testing on our staging server - so we can reconstruct the _after_ commit from the date of issue creation.
As for the _before_, I can't remember the commit but it was log ago (november/december)

**Comment by labolanimichele** [comment]
The issue mostly happens to me when creating a new component / incident / template. I just reproduced it while creating a new component, and got a timeout upon clicking on Create (after a fraction of a second from pressing on the button)

**Comment by anthonybocci** [comment]
I have Apache and MySQL both on localhost, I've creates 2 components, two incidents, one template and one maintenance, I couldn't reproduce your problem. It's either a network problem or a weird bug, but I can't help without being able to reproduce the problem.
A docker image that has the problem would be great.

**Comment by jbrooksuk** [comment]
I'm confident that this is a setup issue opposed to Cachet.
