### ISSUE TITLE
Automating the Cachet installation

### ISSUE THREAD

**Issue by anthonybocci** [CachetHQ/Cachet#2924]
Hi,

On Slack I discussed with someone that needed to automate the installation of Cachet, and because I'm interested by this feature I create this issue in order to contribute then.

The command `app:install` creates the tables in the database, but does not fill the `settings` nor the `users` table.
I would like to add an optional parameter (or create a subclass) to `app:install` in order to give as parameter the path to a file that contains the settings to write into the database. So, the installation would be fully automated.

For now even after executing `app:install` the database is empty, so it's mandatory to launch the setup page that asks for a user, mail drivers, app name and so on.
Also if I've already set the `.env` file with Cache driver, Mail driver and so on, is it required to ask for them on the setup page? Or at least pre-fill the select box could be a help.

I've looked in the `app/Console/Command` directory but all the commands inside are `cachet:*` and I don't know where the `app:install` command is located. Also, do you have guidelines about that? Like the usage of a json or any other file type to manage this configuration.

Regards,

Cachet 2.4
Commit number 2d8bf2fa791511a1ac0fe7ff6e4b4b4e0efd0ca8

**Comment by jbrooksuk** [comment]
@anthonybocci `app:install` is setup by https://github.com/GrahamDeprecated/Laravel-Core

I did start a fully automated solution in https://github.com/CachetHQ/Cachet/pull/2290 with @joecohens extending it to create the user in https://github.com/CachetHQ/Cachet/pull/2291

**Comment by anthonybocci** [comment]
Hi @jbrooksuk and thank you for your comment.

I've looked at the command `cachet:install` and if it does all the job it's absolutely great! But I have one question though, the line `!$this->confirm('Do you want to install Cachet?')` asks for the confirmation.
Is there a command line argument that we could supply line `-y` in order to fully automated installation?

**Comment by jbrooksuk** [comment]
Yeah, that could be added to the command. Do you want to handle that yourself? We just need a flag which skips any confirmations with a default of yes.

**Comment by jbrooksuk** [comment]
Alternatively, you could pipe into `yes`?

**Comment by anthonybocci** [comment]
Indeed it could be piped to `yes`, you're right. So this is absolutely not a priority, but I think it would be nice if a flag could be given.
I'll have a look to that when I'll have time.

**Comment by jbrooksuk** [comment]
👍

**Comment by jbrooksuk** [comment]
Updated the labels :)

**Comment by GrahamCampbell** [comment]
Replaced by https://github.com/CachetHQ/Cachet/issues/3379.
