### ISSUE TITLE
The requested URL /setup was not found on this server.

### ISSUE THREAD

**Issue by nxtVentix** [CachetHQ/Cachet#2925]
I have installed all: now i got this: 
`The requested URL /setup was not found on this server.`

My D.Root!
`DocumentRoot /var/www/status.ventix.eu/Cachet/public/

`
a2enmod rewrite`
`Module rewrite already enabled
`

**Comment by uxen-ab** [comment]
Hello,
Is the error shown with the Cachet layout or a plain old Apache page?

I had the same error the last week-end, but I hadn't enabled the rewrite module. I've enabled it, restarted Apache and it worked then.

**Comment by nxtVentix** [comment]
It is already started...

**Comment by uxen-ab** [comment]
I meant **restarted**, I'd launched `sudo service apache2 restart` in order to restart Apache after enabling the rewrite module. But perhaps you'd already done that.

**Comment by nxtVentix** [comment]
I have restarted it doesnt work... go to: `https://status.ventix.eu/`

**Comment by uxen-ab** [comment]
Indeed. We are indeed redirected to /setup.
Perhaps your virtual host is misconfigured? Does it allow the .htaccess using `AllowOverride All`?

**Comment by nxtVentix** [comment]
Okay i fixed it, now i got this error:

Look at: https://status.ventix.eu/setup

**Comment by uxen-ab** [comment]
Great.
Now, check the log file in `storage/logs/`, the error is inside. It may be about write rights on storage/ or something like that.

**Comment by nxtVentix** [comment]
```
#64 [internal function]: Fideloper\Proxy\TrustProxies->handle(Object(Illuminate\Http\Request), Object(Closure))
#65 /var/www/status.ventix.eu/Cachet/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(136): call_user_func_array(Array, Array)
#66 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#67 /var/www/status.ventix.eu/Cachet/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(32): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#68 [internal function]: Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#69 /var/www/status.ventix.eu/Cachet/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#70 /var/www/status.ventix.eu/Cachet/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(132): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#71 /var/www/status.ventix.eu/Cachet/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(99): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter(Object(Illuminate\Http\Request))
#72 /var/www/status.ventix.eu/Cachet/public/index.php(54): Illuminate\Foundation\Http\Kernel->handle(Object(Illuminate\Http\Request))
#73 {main} {"identification":{"id":"f050d6b6-9d92-4508-848b-5cf1ff0c40af"}} 
```

**Comment by uxen-ab** [comment]
That's the end of the stacktrace, can you paste the complete message?

**Comment by nxtVentix** [comment]
yeah! look here: https://hastebin.com/hevibiguxa.pas

**Comment by uxen-ab** [comment]
Thanks! So the error is following:
`[2018-02-26 13:26:34] production.ERROR: exception 'InvalidArgumentException' with message 'View [setup] not found.' in /var/www/status.ventix.eu/Cachet/vendor/laravel/framework/src/Illuminate/View/FileViewFinder.php:137
`
I've never hot that error. Does the file `resources/views/setup/index.blade.php` exist?
Are you on branch 2.4?

**Comment by nxtVentix** [comment]
What is branch 2.4?

And i cant find the file or the setup folder? 

https://i.imgur.com/9WOCWWy.png

**Comment by uxen-ab** [comment]
Do you have followed the [installation process](https://docs.cachethq.io/docs/installing-cachet)?
I think you are on a tag, 2.3.X, right?

**Comment by nxtVentix** [comment]
Iam on 2.3.9

**Comment by nxtVentix** [comment]
i followed all commands?

**Comment by nxtVentix** [comment]
https://github.com/cachethq/Cachet/issues/960

this helped me. thank you
