### ISSUE TITLE
Automatic change Issue to a 'Out of Date'-Status if no update is sent.

### ISSUE THREAD

**Issue by pree** [CachetHQ/Cachet#2928]
Hello,

I'm currently using Cachet to display some automated Checks. The Check always sets the Status to Operational, if it succeeded and create a Incident if it fails.

Is it possible for Cachet to automatically set a Component-Status to 'Out of Date' if there is no update given for XX-Hours/Days (e.g. if the automated check stopped working). Currently I wrote a little JS-Script to display how long ago the last update was, but this is not optimal:

![image](https://user-images.githubusercontent.com/9799276/36846990-196d9598-1d5d-11e8-97f5-a06ca7990f5d.png)

Best Regards,
Pascal

Edit: The Script I wrote, you need to update the Time-format and add this to the Custom Footer HTML field in Cachet to work: https://gist.github.com/pree/28da21ea4d1eb083157fddc4d0a6c771

**Comment by anthonybocci** [comment]
Hello,

According to me (but I may be wrong) Cachet is a status page and it aims to _show_ the status of your components to the world.
As you might know there are some [Cachet plugins](https://docs.cachethq.io/docs/addons) that aim to check your web server, database or whatever else and post the results to your Cachet instance.

So what I think is it is up to you to manage your scripts and perhaps think it differently. Your plugin could be a kind of daemon that runs automatically, or it could be a one-shot program that runs every X seconds with CRON so even if it doesn't do its work one time it will do the next time. There are solutions to (re)launch your program. So the program would be able to update the component status.

Regards,

**Comment by jbrooksuk** [comment]
Cachet doesn't monitor anything and monitoring the age of a components' last update is beyond the scope of this project.
