### ISSUE TITLE
API Allows status updates for undefined statuses

### ISSUE THREAD

**Issue by pablochacin** [CachetHQ/Cachet#2932]
In Cachet 2.3.9, when updating a component's status, if the value is invalid, the call success, no error message is returned, but the status is left in an status which not reflected in the dashboard" .  Looking at the component details, the status is reflected as "cachet.components.status.5".

For example, updating the status to "5"  return the following

```
> curl --request PUT -H "Content-Type: application/json" -H "X-Cachet-Token: HIum3MaYn5p9p4g5HQ91"  --url http://seam-status-dashboard-env.us-east-1.elasticbeanstalk.com/api/v1/components/2 -d '{"status": 5}'

{"data":{"id":2,"name":"seam-service-1","description":"","link":"","status":5,"order":0,"group_id":1,"enabled":true,"created_at":"2018-03-06 10:52:48","updated_at":"2018-03-07 12:31:26","deleted_at":null,"status_name":"cachet.components.status.5","tags":{"":""}}}
```

I think that the API should reject updates with invalid values.

**Comment by jbrooksuk** [comment]
Can you test this on Cachet 2.4 please?
