### ISSUE TITLE
Add the ability to section/hide graphs

### ISSUE THREAD

**Issue by csm10495** [CachetHQ/Cachet#2934]
(Feature Change / Request)
I would like the ability to hide metric graphs behind a tab.

I sort of picture it like a 'Graphs' tab that I can have open/closed by default then a user can click it to view various metric graphs. If I have all the graphs out the page is very long and a lot to look at, so by default, I would want to hide them and then make click to view them on the page.

**Comment by jbrooksuk** [comment]
I suppose if you have a lot of graphs, it could become overwhelming, but I'm keen to know how many people would need this.

**Comment by anthonybocci** [comment]
My opinion is that is not a critical feature at all, but it could be nice for users I agree.

**Comment by jbrooksuk** [comment]
Agree with @anthonybocci.

I really need to create a roadmap for the 2.4 (which will likely be v3) release so that we can focus what does need doing.

**Comment by anthonybocci** [comment]
I agree @jbrooksuk , a roadmap would be great. I think we should make 2.4 stable, fix the more critical bugs, and then handle issues like this one.

**Comment by jbrooksuk** [comment]
I'm going to close this as "out of scope" for now. That doesn't mean it's not a good idea, but it's not something we'll implement within Cachet itself.

That said, if you or someone else would like to pick this up, please feel free to do so.
