### ISSUE TITLE
Slack and Community

### ISSUE THREAD

**Issue by BoFFire** [CachetHQ/Cachet#2937]
Hello,
Any specific reason to have choosen Slack rather then XMPP and IRC for the project ?
Why the link is http and not httpS for Slack then ?
Some projects don't listen to Community voice.

Regards,

**Comment by BoFFire** [comment]
OK bot, human here

![](https://framapic.org/kIpQZvkIj44x/W0FHLnFpYud4)

**Comment by anthonybocci** [comment]
Hellon
You're right the link should be using httpS protocol, I guess that's an error. But there is an automatic redirection to https luckily.

**Comment by jbrooksuk** [comment]
I've now updated the links to use HTTPS.

We use Slack because most people already have a client for it and know how to use it. We previously used Gitter but that wasn't very stable or user friendly.
