### ISSUE TITLE
Sidebar and bottom menu have inconsistent width

### ISSUE THREAD

**Issue by kothman** [CachetHQ/Cachet#2938]
When you navigate to the Dashboard on a desktop, you should see that the menu in the bottom left doesn't line up with the sidebar. The menu (`.dashboard .sidebar .bottom-menu-sidebar`) has a width of 237px, and the sidebar (`.dashboard .sidebar`) has a width of 235px.

![image](https://user-images.githubusercontent.com/4342254/37496428-09d8ae12-2878-11e8-81c7-76d30c99cd5a.png)

**Comment by kothman** [comment]
Easy fix, just need to change `width: 237px;` to `width: 235px` on L135 in `resources/assets/sass/dashboard/partials/_sidebar.scss`, and then recompile assets with `npm run prod`.

**Comment by uxen-ab** [comment]
I can confirm that in Firefox Nightly (61) on OSX 10.13.
We'd check if the problem is present on an other resolution.

**Comment by jbrooksuk** [comment]
@joecohens could you pick this up? :)
