### ISSUE TITLE
Unknown Component status 

### ISSUE THREAD

**Issue by mohamedbarry** [CachetHQ/Cachet#2939]
Hi there,
Unknown Component Status is updating the Page to "Some systems are experiencing issues". Is this a bug in 2.4 ? Is there a way to change that to "All systems are operational" ?

**Comment by jbrooksuk** [comment]
How did you set an unknown status?

**Comment by jbrooksuk** [comment]
Ignore the above, it seems I had a moment...

If the status is unknown, then it's likely there are issues, so it's my belief this is the correct behaviour. Please let me know if you disagree and we'll discuss it further.

**Comment by Perflyst** [comment]
I think I got the same issue. I created a component with `Unknown status` and than updated it to `Operational`. Now I get `Some systems are experiencing issues` even if every component is `Operational`.
