### ISSUE TITLE
Settings option in dashboard sidebar is obstructed by the bottom-menu-sidebar

### ISSUE THREAD

**Issue by kothman** [CachetHQ/Cachet#2941]
The settings option in the dashboard sidebar is obstructed by the bottom-menu-sidebar.

![image](https://user-images.githubusercontent.com/4342254/37551285-96c2aaae-2962-11e8-9ce5-9be0af956c7b.png)

Windows 10 Home, Chrome Version 65.0.3325.162
Screen resolution: 1360x768

**Comment by uxen-ab** [comment]
Unable to reproduce the bug on OSX (Version 65.0.3325.162 (Official Build) (64-bit)). The sidebar is scrollable for me.

**Comment by uxen-ab** [comment]
The problem is confirmed on OSX, and is not only in Chrome.
