### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by jbrooksuk** [CachetHQ/Cachet#2943]
# v3.0 Roadmap

What is currently know as **Cachet v2.4** will eventually become **v3.0** as there are already backwards incompatible features and many changes under the hood. 

Here are the priorities for v3. 

1. Fix any significant bugs. Metrics is a big one, which will probably result in a rewrite. Any bugs that can reflected in the the API should have a test case applied with the fix. 
2. Speaking of tests, we need to ensure Cachet is better tested, more coverage etc. I’d also like to look again at Laravel Dusk so that we can do actual testing of the UI. This should wait till the re-design. 
3. Re-design. More before we work on any features that rely on UI changes, we **need** to get the new design introduced. This should also be applied to the dashboard. I’m very keen on Tailwind at the moment especially making components that can still be styled and not relying too heavily on the independent classes. 
4. GDPR and security vulnerabilities. 
4. Features. After the design we can move on to missing features.

**Comment by anthonybocci** [comment]
I am volunteer to help you with some items if needed. We should create a roadmap pretty precise, what we really want in 2.4, 2.x, 3.0 etc. Also, what kind if issues we'd allow.
Many people are asking for features, what should we accept? Some companies are asking for SSO/SAML support, is it something we could add in a given version?
I think these are questions we have to ask :)

**Comment by jbrooksuk** [comment]
@anthonybocci that's really great news! 2.4 will have to become 3.0 in the near future, so this is the prime opportunity to break things and really improve everything.

Maybe we should Skype sometime?

**Comment by anthonybocci** [comment]
@jbrooksuk In the 3.0 we could integrate the big changes that were requested before and that weren't integrated before. 3.0 should be great! We should add some stability too before releasing it.

Sure! We should Skype when you want, it could be useful. I'm _Anthony B_ on Slack, we could speak there about when to Skype.

**Comment by jbrooksuk** [comment]
I'd love to make 3.0 a proper, solid, feature-packed release of Cachet. I'll Slack you when I'm back from holiday 👍

**Comment by anthonybocci** [comment]
Enjoy your holidays! :+1: I'll be on Slack the days in the week.

**Comment by anthonybocci** [comment]
Note: In the 3.0 we should speak about ACL too. Some people ask for it on Slack. A user should be able to create an incident but not a component, etc.
Also, an improved maintenance mode could be great. As said in #2986 a message during the maintenance is needed. For now, we only have a message before the scheduled maintenance. Scheduled maintenance is a great feature, we could improve it a bit.

**Comment by anthonybocci** [comment]
@jbrooksuk Any news about the roadmap?

**Comment by jbrooksuk** [comment]
@anthonybocci sorry buddy, not yet. I wanted to clear a few issues out of the way and tidy up some code before we look at a solid roadmap because it'll get rid of the stragglers.

**Comment by anthonybocci** [comment]
@jbrooksuk I understand, it's good to have less important issues. But people are often asking about version 2.4, 3.0, release date and so on. It would be great to give them a bit of information.

**Comment by jbrooksuk** [comment]
I’ve updated the original post with some parts of the roadmap.

**Comment by pietzschke** [comment]
@jbrooksuk Any updates on 2.4 or 3.0? Thanks!

**Comment by yfried** [comment]
Hi, is there any update on the v3 release?
