### ISSUE TITLE
Incomplete documentation leads to #2898

### ISSUE THREAD

**Issue by hatclub** [CachetHQ/Cachet#2945]
The installation documentation supplied at https://docs.cachethq.io/v1.0/docs/installing-cachet / https://docs.cachethq.io/v1.0/docs/configuring-the-queue is apparently incomplete and will lead to users who select the MySQL queue driver installing/configuring in a manner that results in #2898

**Comment by jbrooksuk** [comment]
FWIW you can suggest edits to the documentation which I can review and merge in. I'd love it if someone sat down and updated the documentation, making it comprehensive and up to date, but I don't know of anyone who would do that.
