### ISSUE TITLE
Email sendout now gived 500 error

### ISSUE THREAD

**Issue by labolanimichele** [CachetHQ/Cachet#2949]
Hello,

I think something went wrong when closing #2935: now, when I try to "notify subscribers", I get a 500 error (which I was not getting before):
![errrornotifyusers](https://user-images.githubusercontent.com/22618797/37586325-4a64d97e-2b5c-11e8-89ce-763faef4f832.PNG)

Can the 2 things be related?

The error does not show if I create an incident without the "notify subscriber" checked. I'm talking of the latest 2.4 (pulled it right now).

Thanks,
Michele

**Comment by labolanimichele** [comment]
Note: I also get the same 500 error when trying to post an update for an incident (I suppose this is because the "notify users" feature is there defaulted to true?)

**Comment by raffus** [comment]
I'm facing same issue. I guess its related to the SMTP in use (maybe something related to TLS validation). I'm still going blind here.

**Comment by 3weakley** [comment]
I am running 2.3.13 and noticed this as well, I changed CALL_QUEUE from sync to database and the error went away

**Comment by jbrooksuk** [comment]
How many subscribers do you have? You probably need to change from the sync queue. https://docs.cachethq.io/docs/configuring-the-queue

**Comment by labolanimichele** [comment]
Currently I only have 2 (both are emails sent to myself, as I was testing it before making this available to users).
And I did have 2 also before updating, nothing changed there.
Will try and let you know then, thanks!

**Comment by jbrooksuk** [comment]
Still likely a timeout. What Mail server are you using?
