### ISSUE TITLE
RSS with incident status

### ISSUE THREAD

**Issue by sysmat** [CachetHQ/Cachet#2951]
I'm using version 2.4.0

Is it possible to have  incident status in RSS feed as part of item tag(maybe as category)?

Regards, Tomaž

**Comment by sysmat** [comment]
In source rss.blade.php I see that category is already taken by `$item['category']`.
Next question how to add category to incident?

By RSS 2 RFC it is possible to have  many category elements, so it would be possible to have one category  for incident status

**Comment by jbrooksuk** [comment]
Closed by https://github.com/CachetHQ/Cachet/pull/2965

**Comment by anthosz** [comment]
Dear @jbrooksuk ,

Do you know how to use RSS feeds?

I use 2.4 and I don't have any RSS feeds on incidents.

Best regards,
