### ISSUE TITLE
Cachet API: return an array of tags instead of object for Components tags

### ISSUE THREAD

**Issue by hugomcfonseca** [CachetHQ/Cachet#2952]
At the moment, Cachet API is returning a list of multiple key-values with key and value being duplicated. 

I would like to have it returning an array of strings (tags).

**Comment by uxen-ab** [comment]
Please could you provide a little example of what you receive and what you expect?

**Comment by hugomcfonseca** [comment]
Sure.

This is what `GET /api/v1/components/1` looks like:

```json
{"data":{"id":1,"name":"API","description":"Used by third-parties to connect to us","link":"","status":1,"order":0,"group_id":0,"created_at":"2018-03-23 10:30:02","updated_at":"2018-03-23 10:30:02","deleted_at":null,"enabled":true,"meta":null,"status_name":"Operational","tags":{"test":"test","as":"as","war":"war"}}}
```

I would like to have the following structure:

```json
{"data":{"id":1,"name":"API","description":"Used by third-parties to connect to us","link":"","status":1,"order":0,"group_id":0,"created_at":"2018-03-23 10:30:02","updated_at":"2018-03-23 10:30:02","deleted_at":null,"enabled":true,"meta":null,"status_name":"Operational","tags":["test","as","war"]}}
```

This is also replicated to `GET /api/v1/components`, at least. At the moment, I didn't find this problem in other API endpoints, but if they exists, it would be nice to extend this fix to all those endpoints.

**Comment by uxen-ab** [comment]
It's clearer now, thanks.
Indeed a tag has no need to have a key and a value. You may either block untill we use an array, or use a map that will have an integer key in the future but using only the value.

**Comment by jbrooksuk** [comment]
Tags are actually stored as `key/value` in the database for future changes, so this doesn't need to be done as they'll make sense in the future.

**Comment by hugomcfonseca** [comment]
@jbrooksuk just to make it clear, so I should expect something like `isLive: true`, right? In other words, I will be able to specify a __key-value__ tag on Cachet, right?

**Comment by jbrooksuk** [comment]
@hugomcfonseca correct, this is what will be happening by the time v3 is out :+1:
