### ISSUE TITLE
Team invitation failed

### ISSUE THREAD

**Issue by raffus** [CachetHQ/Cachet#2953]
Hi there,

I'm trying to invite a team member and when I type his email address and submit, I get an error message.

Doing a log research I found this:

> [2018-03-22 16:18:40] production.ERROR: exception 'ErrorException' with message 'stream_socket_enable_crypto(): SSL operation failed with code 1. OpenSSL Error messages:
error:14090086:SSL routines:ssl3_get_server_certificate:certificate verify failed' in /var/www/html/Cachet/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Transport/StreamBuffer.php:95
Stack trace:
#0 [internal function]: Illuminate\Foundation\Bootstrap\HandleExceptions->handleError(2, 'stream_socket_e...', '/var/www/html/C...', 95, Array)
#1 /var/www/html/Cachet/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Transport/StreamBuffer.php(95): stream_socket_enable_crypto(Resource id #9, true, 9)
#2 /var/www/html/Cachet/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Transport/EsmtpTransport.php(315): Swift_Transport_StreamBuffer->startTLS()
#3 /var/www/html/Cachet/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Transport/AbstractSmtpTransport.php(118): Swift_Transport_EsmtpTransport->_doHeloCommand()
#4 /var/www/html/Cachet/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Mailer.php(79): Swift_Transport_AbstractSmtpTransport->start()
#5 /var/www/html/Cachet/vendor/laravel/framework/src/Illuminate/Mail/Mailer.php(385): Swift_Mailer->send(Object(Swift_Message), Array)
#6 /var/www/html/Cachet/vendor/laravel/framework/src/Illuminate/Mail/Mailer.php(171): Illuminate\Mail\Mailer->sendSwiftMessage(Object(Swift_Message))
#7 /var/www/html/Cachet/vendor/laravel/framework/src/Illuminate/Mail/Mailer.php(276): Illuminate\Mail\Mailer->send(Array, Array, Object(Closure))
#8 /var/www/html/Cachet/vendor/laravel/framework/src/Illuminate/Queue/Jobs/Job.php(130): Illuminate\Mail\Mailer->handleQueuedMessage(Object(Illuminate\Queue\Jobs\SyncJob), Array)
#9 /var/www/html/Cachet/vendor/laravel/framework/src/Illuminate/Queue/Jobs/SyncJob.php(44): Illuminate\Queue\Jobs\Job->resolveAndFire(Array)
#10 /var/www/html/Cachet/vendor/laravel/framework/src/Illuminate/Queue/SyncQueue.php(30): Illuminate\Queue\Jobs\SyncJob->fire()
#11 /var/www/html/Cachet/vendor/laravel/framework/src/Illuminate/Mail/Mailer.php(187): Illuminate\Queue\SyncQueue->push('mailer@handleQu...', Array, NULL)
#12 /var/www/html/Cachet/app/Bus/Handlers/Events/User/SendInviteUserEmailHandler.php(59): Illuminate\Mail\Mailer->queue(Array, Array, Object(Closure))
#13 [internal function]: CachetHQ\Cachet\Bus\Handlers\Events\User\SendInviteUserEmailHandler->handle(Object(CachetHQ\Cachet\Bus\Events\User\UserWasInvitedEvent))
#14 /var/www/html/Cachet/bootstrap/cache/compiled.php(10179): call_user_func_array(Array, Array)
#15 [internal function]: Illuminate\Events\Dispatcher->Illuminate\Events\{closure}(Object(CachetHQ\Cachet\Bus\Events\User\UserWasInvitedEvent))
#16 /var/www/html/Cachet/bootstrap/cache/compiled.php(10124): call_user_func_array(Object(Closure), Array)
#17 /var/www/html/Cachet/vendor/laravel/framework/src/Illuminate/Foundation/helpers.php(419): Illuminate\Events\Dispatcher->fire(Object(CachetHQ\Cachet\Bus\Events\User\UserWasInvitedEvent), Array, false)
#18 /var/www/html/Cachet/app/Bus/Handlers/Commands/User/InviteTeamMemberCommandHandler.php(34): event(Object(CachetHQ\Cachet\Bus\Events\User\UserWasInvitedEvent))
#19 [internal function]: CachetHQ\Cachet\Bus\Handlers\Commands\User\InviteTeamMemberCommandHandler->handle(Object(CachetHQ\Cachet\Bus\Commands\User\InviteTeamMemberCommand))
#20 /var/www/html/Cachet/vendor/alt-three/bus/src/Dispatcher.php(225): call_user_func(Array, Object(CachetHQ\Cachet\Bus\Commands\User\InviteTeamMemberCommand))
#21 [internal function]: AltThree\Bus\Dispatcher->AltThree\Bus\{closure}(Object(CachetHQ\Cachet\Bus\Commands\User\InviteTeamMemberCommand))
#22 /var/www/html/Cachet/bootstrap/cache/compiled.php(9960): call_user_func(Object(Closure), Object(CachetHQ\Cachet\Bus\Commands\User\InviteTeamMemberCommand))
#23 /var/www/html/Cachet/app/Bus/Middleware/UseDatabaseTransactions.php(35): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(CachetHQ\Cachet\Bus\Commands\User\InviteTeamMemberCommand))
#24 /var/www/html/Cachet/vendor/laravel/framework/src/Illuminate/Database/Connection.php(527): CachetHQ\Cachet\Bus\Middleware\UseDatabaseTransactions->CachetHQ\Cachet\Bus\Middleware\{closure}(Object(Illuminate\Database\MySqlConnection))
#25 [internal function]: Illuminate\Database\Connection->transaction(Object(Closure))
#26 /var/www/html/Cachet/bootstrap/cache/compiled.php(11784): call_user_func_array(Array, Array)
#27 /var/www/html/Cachet/bootstrap/cache/compiled.php(6325): Illuminate\Database\DatabaseManager->__call('transaction', Array)
#28 /var/www/html/Cachet/bootstrap/cache/compiled.php(6325): Illuminate\Database\DatabaseManager->transaction(Object(Closure))
#29 /var/www/html/Cachet/app/Bus/Middleware/UseDatabaseTransactions.php(36): Illuminate\Support\Facades\Facade::__callStatic('transaction', Array)
#30 /var/www/html/Cachet/app/Bus/Middleware/UseDatabaseTransactions.php(36): Illuminate\Support\Facades\DB::transaction(Object(Closure))
#31 [internal function]: CachetHQ\Cachet\Bus\Middleware\UseDatabaseTransactions->handle(Object(CachetHQ\Cachet\Bus\Commands\User\InviteTeamMemberCommand), Object(Closure))
#32 /var/www/html/Cachet/bootstrap/cache/compiled.php(9953): call_user_func_array(Array, Array)
#33 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(CachetHQ\Cachet\Bus\Commands\User\InviteTeamMemberCommand))
#34 /var/www/html/Cachet/bootstrap/cache/compiled.php(9938): call_user_func(Object(Closure), Object(CachetHQ\Cachet\Bus\Commands\User\InviteTeamMemberCommand))
#35 /var/www/html/Cachet/vendor/alt-three/bus/src/Dispatcher.php(226): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#36 /var/www/html/Cachet/vendor/alt-three/bus/src/Dispatcher.php(201): AltThree\Bus\Dispatcher->dispatchNow(Object(CachetHQ\Cachet\Bus\Commands\User\InviteTeamMemberCommand), NULL)
#37 /var/www/html/Cachet/vendor/laravel/framework/src/Illuminate/Foundation/helpers.php(323): AltThree\Bus\Dispatcher->dispatch(Object(CachetHQ\Cachet\Bus\Commands\User\InviteTeamMemberCommand))
#38 /var/www/html/Cachet/app/Http/Controllers/Dashboard/TeamController.php(135): dispatch(Object(CachetHQ\Cachet\Bus\Commands\User\InviteTeamMemberCommand))
#39 [internal function]: CachetHQ\Cachet\Http\Controllers\Dashboard\TeamController->postInviteUser()
#40 /var/www/html/Cachet/bootstrap/cache/compiled.php(9419): call_user_func_array(Array, Array)
#41 /var/www/html/Cachet/bootstrap/cache/compiled.php(9481): Illuminate\Routing\Controller->callAction('postInviteUser', Array)
#42 /var/www/html/Cachet/bootstrap/cache/compiled.php(9461): Illuminate\Routing\ControllerDispatcher->call(Object(CachetHQ\Cachet\Http\Controllers\Dashboard\TeamController), Object(Illuminate\Routing\Route), 'postInviteUser')
#43 [internal function]: Illuminate\Routing\ControllerDispatcher->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#44 /var/www/html/Cachet/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(52): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#45 [internal function]: Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#46 /var/www/html/Cachet/bootstrap/cache/compiled.php(9938): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#47 /var/www/html/Cachet/bootstrap/cache/compiled.php(9462): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#48 /var/www/html/Cachet/bootstrap/cache/compiled.php(9449): Illuminate\Routing\ControllerDispatcher->callWithinStack(Object(CachetHQ\Cachet\Http\Controllers\Dashboard\TeamController), Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request), 'postInviteUser')
#49 /var/www/html/Cachet/bootstrap/cache/compiled.php(8517): Illuminate\Routing\ControllerDispatcher->dispatch(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request), 'CachetHQ\\Cachet...', 'postInviteUser')
#50 /var/www/html/Cachet/bootstrap/cache/compiled.php(8504): Illuminate\Routing\Route->runController(Object(Illuminate\Http\Request))
#51 /var/www/html/Cachet/bootstrap/cache/compiled.php(8218): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request))
#52 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#53 /var/www/html/Cachet/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(52): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#54 /var/www/html/Cachet/app/Http/Middleware/Admin.php(54): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#55 [internal function]: CachetHQ\Cachet\Http\Middleware\Admin->handle(Object(Illuminate\Http\Request), Object(Closure))
#56 /var/www/html/Cachet/bootstrap/cache/compiled.php(9953): call_user_func_array(Array, Array)
#57 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#58 /var/www/html/Cachet/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(32): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#59 /var/www/html/Cachet/app/Http/Middleware/Authenticate.php(54): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#60 [internal function]: CachetHQ\Cachet\Http\Middleware\Authenticate->handle(Object(Illuminate\Http\Request), Object(Closure))
#61 /var/www/html/Cachet/bootstrap/cache/compiled.php(9953): call_user_func_array(Array, Array)
#62 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#63 /var/www/html/Cachet/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(32): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#64 /var/www/html/Cachet/bootstrap/cache/compiled.php(3225): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#65 [internal function]: Illuminate\Foundation\Http\Middleware\VerifyCsrfToken->handle(Object(Illuminate\Http\Request), Object(Closure))
#66 /var/www/html/Cachet/bootstrap/cache/compiled.php(9953): call_user_func_array(Array, Array)
#67 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#68 /var/www/html/Cachet/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(32): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#69 /var/www/html/Cachet/bootstrap/cache/compiled.php(13400): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#70 [internal function]: Illuminate\View\Middleware\ShareErrorsFromSession->handle(Object(Illuminate\Http\Request), Object(Closure))
#71 /var/www/html/Cachet/bootstrap/cache/compiled.php(9953): call_user_func_array(Array, Array)
#72 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#73 /var/www/html/Cachet/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(32): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#74 /var/www/html/Cachet/bootstrap/cache/compiled.php(11943): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#75 [internal function]: Illuminate\Session\Middleware\StartSession->handle(Object(Illuminate\Http\Request), Object(Closure))
#76 /var/www/html/Cachet/bootstrap/cache/compiled.php(9953): call_user_func_array(Array, Array)
#77 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#78 /var/www/html/Cachet/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(32): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#79 /var/www/html/Cachet/bootstrap/cache/compiled.php(13139): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#80 [internal function]: Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse->handle(Object(Illuminate\Http\Request), Object(Closure))
#81 /var/www/html/Cachet/bootstrap/cache/compiled.php(9953): call_user_func_array(Array, Array)
#82 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#83 /var/www/html/Cachet/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(32): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#84 /var/www/html/Cachet/bootstrap/cache/compiled.php(13076): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#85 [internal function]: Illuminate\Cookie\Middleware\EncryptCookies->handle(Object(Illuminate\Http\Request), Object(Closure))
#86 /var/www/html/Cachet/bootstrap/cache/compiled.php(9953): call_user_func_array(Array, Array)
#87 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#88 /var/www/html/Cachet/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(32): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#89 [internal function]: Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#90 /var/www/html/Cachet/bootstrap/cache/compiled.php(9938): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#91 /var/www/html/Cachet/bootstrap/cache/compiled.php(8219): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#92 /var/www/html/Cachet/bootstrap/cache/compiled.php(8210): Illuminate\Routing\Router->runRouteWithinStack(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request))
#93 /var/www/html/Cachet/bootstrap/cache/compiled.php(8200): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
#94 /var/www/html/Cachet/bootstrap/cache/compiled.php(2419): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#95 [internal function]: Illuminate\Foundation\Http\Kernel->Illuminate\Foundation\Http\{closure}(Object(Illuminate\Http\Request))
#96 /var/www/html/Cachet/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(52): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#97 /var/www/html/Cachet/bootstrap/cache/compiled.php(3286): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#98 [internal function]: Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode->handle(Object(Illuminate\Http\Request), Object(Closure))
#99 /var/www/html/Cachet/bootstrap/cache/compiled.php(9953): call_user_func_array(Array, Array)
#100 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#101 /var/www/html/Cachet/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(32): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#102 /var/www/html/Cachet/vendor/fideloper/proxy/src/TrustProxies.php(46): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#103 [internal function]: Fideloper\Proxy\TrustProxies->handle(Object(Illuminate\Http\Request), Object(Closure))
#104 /var/www/html/Cachet/bootstrap/cache/compiled.php(9953): call_user_func_array(Array, Array)
#105 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#106 /var/www/html/Cachet/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(32): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#107 [internal function]: Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#108 /var/www/html/Cachet/bootstrap/cache/compiled.php(9938): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#109 /var/www/html/Cachet/bootstrap/cache/compiled.php(2366): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#110 /var/www/html/Cachet/bootstrap/cache/compiled.php(2350): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter(Object(Illuminate\Http\Request))
#111 /var/www/html/Cachet/public/index.php(54): Illuminate\Foundation\Http\Kernel->handle(Object(Illuminate\Http\Request))
#112 {main} {"identification":{"id":"60a7dd47-4277-474d-b4bb-f0b1cc5cb59b"}} 

Any ideas?

Thanks in advance.

R

**Comment by anthonybocci** [comment]
Hi,
After reading the beginning of your logs, it seems to be a SSL error. I guess your mail server uses a encrypted protocol, but OpenSSL on your server can't handle it.  Try to update OpenSSL.
But as said by the welcome but, for a such problem please come on Slack, we'll be glad to help you.

**Comment by raffus** [comment]
hi there!

I changed the SMTP server to sendmail and it worked. Weird thing is that I was not using SSL on the old SMTP configuration.

I found a way out to the solution, but the problem still exists.
