### ISSUE TITLE
ERROR:  relation "metric_points" does not exist at character 90

### ISSUE THREAD

**Issue by joaocfernandes** [CachetHQ/Cachet#2955]
Hi all,

Install of Cachet version 2.3.13 , running through docker-compose with Postgres.

On a pageload where a metric (2) is enabled the following Postgres error is logged:

```
Postgres_1  | ERROR:  relation "metric_points" does not exist at character 90
postgres_1  | STATEMENT:  select avg(metric_points.value * metric_points.counter) as value FROM chq_metrics m JOIN metric_points ON metric_points.metric_id = m.id WHERE metric_points.metric_id = $1 AND to_char(metric_points.created_at, 'YYYYMMDDHH24') = $2 GROUP BY to_char(metric_points.created_at, 'H')

```
In the cachet the following error is logged:

```
cachet_1    | [23-Mar-2018 16:17:34] WARNING: [pool www] child 72 said into stderr: "NOTICE: PHP message: [2018-03-23 16:17:34] development.ERROR: PDOException: SQLSTATE[42P01]: Undefined table: 7 ERROR:  relation "metric_points" does not exist"
cachet_1    | [23-Mar-2018 16:17:34] WARNING: [pool www] child 72 said into stderr: "LINE 1: ..._points.counter) as value FROM chq_metrics m JOIN metric_poi..."
cachet_1    | [23-Mar-2018 16:17:34] WARNING: [pool www] child 72 said into stderr: "                                                             ^ in /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Connection.php:335"
```

I have checked the tables that do exist in postgres:

```
postgres=# \dt
                 List of relations
 Schema |          Name          | Type  |  Owner   
--------+------------------------+-------+----------
 public | chq_cache              | table | postgres
 public | chq_component_groups   | table | postgres
 public | chq_component_tag      | table | postgres
 public | chq_components         | table | postgres
 public | chq_failed_jobs        | table | postgres
 public | chq_incident_templates | table | postgres
 public | chq_incidents          | table | postgres
 public | chq_invites            | table | postgres
 public | chq_jobs               | table | postgres
 public | chq_metric_points      | table | postgres
 public | chq_metrics            | table | postgres
 public | chq_migrations         | table | postgres
 public | chq_sessions           | table | postgres
 public | chq_settings           | table | postgres
 public | chq_subscribers        | table | postgres
 public | chq_subscriptions      | table | postgres
 public | chq_tags               | table | postgres
 public | chq_users              | table | postgres
(18 rows)

```
A metric was created , and some data was populated into metric/2 .

Observing the query provided to postgres , mentions table metric_points instead of the chq_metric_points. 

I have talked with @anthonybocci , which also evaluated this and is going to evaluate/implement the fix.

Thanks everyone,

**Comment by anthonybocci** [comment]
In the repositories (`app/Repositories/Metrics`) a method gives the 'metrics' table name, but there is no method giving the 'metric_points' table name using the prefix, the table name was hard-written.

I've [a branch][1] where I've fixed this problem by adding a method, could you try if everything is good for you before I submit a pull request?

[1]: https://github.com/anthonybocci/Cachet/tree/metric-points-prefix-table-2925

**Comment by joaocfernandes** [comment]
Hi,

I have tested the branch provided against my docker install. The issue is solved.

![2018-03-26_10h56_18](https://user-images.githubusercontent.com/2494410/37900047-fd508f32-30e4-11e8-8dba-ed9ab55f01b9.png)

Thanks @anthonybocci!! 

Best Regards,
João Fernandes

**Comment by jbrooksuk** [comment]
Closed by https://github.com/CachetHQ/Cachet/pull/2960
