### ISSUE TITLE
$redirectUrl is undefined with 3 uses in Dashboard/SettingsController

### ISSUE THREAD

**Issue by christianklemp-imt** [CachetHQ/Cachet#2956]
Hello,
I have Cachet deployed using Docker and am trying to upload a PNG image for my site banner. I have also tried a JPG, but get a 500 error due to `$redirectUrl` on line 332 being undefined. It also appears twice before this line, but am not hitting those.

https://github.com/CachetHQ/Cachet/blob/93d1f8784a75b5aa975f8cb89007e94ee63bb1e4/app/Http/Controllers/Dashboard/SettingsController.php#L324

**Comment by anthonybocci** [comment]
Hi,
You have the problem only because your file was invalid. If the file was valid, it would worked.
I've explained that in the commit that fix it.

**Comment by christianklemp-imt** [comment]
I find it odd that the image (tried as PNG and JPG formats) both fail. They are both images that I exported in those formats, so not sure what is making it fail.

**Comment by anthonybocci** [comment]
I've tried to add an image on my Cachet, it works well. Have you tried with an other image?
I think it's not a problem with Cachet, come on Slack, the community will be glad to help you.

**Comment by jbrooksuk** [comment]
I think it could be image dimensions?

**Comment by christianklemp-imt** [comment]
Thanks for the help guys! I'll do a little more debugging, but may jump onto Slack if I can't get it figured out since my image is 930px x 100px. I've even tried it with a 900px x 100px and a 250px x 100px image and am getting the same result.

**Comment by anthonybocci** [comment]
I suggest you to come on Slack indeed, it will be easier to discuss about your problem and fix it. If there is a real problem in Cachet we'll post it onto Github, but I don't think so. I'm "Anthony B" on Slack, don't hesitate to message me during the day!

**Comment by jbrooksuk** [comment]
Looking at `SettingsController`, it's not based on dimensions, sorry for misleading you there.

It could be that the servers max file size is too small? 

Do you not get any error messages at all?
