### ISSUE TITLE
Composer Install Error 

### ISSUE THREAD

**Issue by kfrankperson** [cachethq/Cachet#296]
When trying to install Cachet from the latest version, Composer spits back an error 

![screen shot 2015-01-05 at 21 17 44](https://cloud.githubusercontent.com/assets/9014669/5620113/73e2a41e-9520-11e4-91d7-c112f557b18c.png)

Fixed the prblem by removing the lines below out of the composer.json

````
"autoload-dev": {
        "classmap": [
            "tests/TestCase.php"
        ]
    },
````

**Comment by GrahamCampbell** [comment]
Yeh, this is clearly documented in our install guide.

**Comment by kfrankperson** [comment]
It's still a problem as there is no tests DIR. Having to run ````composer install --no-dev -o```` is just putting problems in front of people, when there is very little need to.

**Comment by GrahamCampbell** [comment]
No, there is a test dir.

**Comment by GrahamCampbell** [comment]
It just isn't included with a dist download.

**Comment by GrahamCampbell** [comment]
https://github.com/cachethq/Cachet/blob/master/tests/TestCase.php

**Comment by GrahamCampbell** [comment]
That tests folder very much exists.

**Comment by jbrooksuk** [comment]
@GrahamCampbell is there anything we can do here? We could technically include the tests with the dist download, but that seems pointless.

**Comment by GrahamCampbell** [comment]
Nah, it's fine how it is. People are just doing it wrong. If you were to clone the repo with git, you'd still get the tests folder, if you wanted it. Otherwise, we should give people the minimum stuff they want.

**Comment by kfrankperson** [comment]
It should be included with the download.

Even when doing thing right you still get an error @GrahamCampbell 

![screen shot 2015-01-05 at 21 33 04](https://cloud.githubusercontent.com/assets/9014669/5620315/a88fc2c6-9522-11e4-8eb0-3071a00a7412.png)


When following the install.md running ````composer install --no-dev -o```` still produces errors, the steps will need to be changed around.

**Comment by GrahamCampbell** [comment]
> It should be included with the download.

No it shouldn't. It's standard practice to exclude tests.

**Comment by jbrooksuk** [comment]
@kfrankperson you need an `.env.php` file with your DB configuration, see [install.md](https://github.com/cachethq/Cachet/blob/master/docs/setup/install.md).

**Comment by GrahamCampbell** [comment]
For all our dependencies, we don't want to download their tests too when we run composer install. They use the same method to exclude the tests folder as we do.

**Comment by kfrankperson** [comment]
Yeah up to the point of running ```composer install --no-dev -o```` there is no place which says please create the file below your run composer. The install.md should be moved around to say do XYZ then run composer.

**Comment by jbrooksuk** [comment]
@kfrankperson sure, we can update the install document to be clearer.

**Comment by jbrooksuk** [comment]
@kfrankperson [how's this](https://github.com/cachethq/Cachet/blob/master/docs/setup/install.md)?

**Comment by kfrankperson** [comment]
The only reason i raised this is I have a scripts at work to deploy code to multiple servers and with Cachet it now fails as we have to run ``` composer install --no-dev -o ```, yet all other systems we use it's  ```composer install```.

**Comment by kfrankperson** [comment]
@jbrooksuk Much much better !!!

**Comment by jbrooksuk** [comment]
I'm sorry if you felt misled whilst reading the installation document, hope it helps :)

**Comment by GrahamCampbell** [comment]
@kfrankperson No they don't. If you use composer install, you are also doing it wrong, because you are installing all the dev-dependencies.

**Comment by GrahamCampbell** [comment]
`-o` is not required anyway, it just gets composer to generate an optimized autoloader.

**Comment by kfrankperson** [comment]
@GrahamCampbell yeah but it best to have it there :P 

The other thing about the install document can the deploy to Heroku be it's own section at the bottom as it distracts from installing it in a non Heroku env ?

**Comment by jbrooksuk** [comment]
@kfrankperson would you mind making a PR with that change? I'm just in the middle of something :)
