### ISSUE TITLE
Transfer Cachet to another server

### ISSUE THREAD

**Issue by AppleCarmine** [CachetHQ/Cachet#2961]
At the moment I have Cachet on a VPS but I would like to transfer it to another VPS without losing the configuration. How can I do?

**Comment by uxen-ab** [comment]
I think this should be asked on Slack (https://cachethq-slack.herokuapp.com), we are a community that would be glad to help you.

For this question, you could:

1. Copy the database (if it has to be moved as well)
2. Copy all the Cachet tree on the new VPS
3. Update the DB configuration in .env if required and check if no other value needs to be updated (like paths)
4. Make your domain name point to the new VPS' IP

**Comment by Juster737** [comment]
After transfer cachet, copy dir and import DB to new server , i get error 400 CSRF token validation failed, when i go through authorization. dashboard is ok
Tell me what could be the problem?
