### ISSUE TITLE
Scheduled maintenance is not visible enough in the dashboard

### ISSUE THREAD

**Issue by lelutin** [CachetHQ/Cachet#2966]
When one wants to add or edit a scheduled maintenance, they need to first go to the "Incidents" page, then click on the "Scheduled maintenance" sub-section to finally find the list of current scheduled maintenance events and the button to add a scheduled maintenance.

This is too well hidden for most users. It'd be better if scheduled maintenance would have a link in the menu on the left for direct access instead of being a sub-section of Incidents.

**Comment by jbrooksuk** [comment]
In 2.4 maintenance is now within its own sidebar link.

**Comment by lelutin** [comment]
huh, you're the best :) I'll try to upgrade to 2.4 as soon as it's released

**Comment by jbrooksuk** [comment]
😄

**Comment by jbrooksuk** [comment]
The PR above was unrelated, I made a mistake.
