### ISSUE TITLE
Incident & Schedule Previewing

### ISSUE THREAD

**Issue by lelutin** [CachetHQ/Cachet#2967]
When writing an incident or a scheduled maintenance, it would be nice to have a "preview" button that would render the markdown to show you if you laid out the post correctly before actually publishing it. 

Currently the only way to make sure everything is OK is to actually save the incident/maintnenance, then look on the site what the published result looks like and fix by editing if it's not right.

**Comment by jbrooksuk** [comment]
I agree! We could split these into two tabs, similar to GitHub for example. This component would need to be clever though as we wouldn't want to be rendering a preview until the preview tab is active for performance reasons.

**Comment by jbrooksuk** [comment]
Thank you for your input on Cachet 2.x. We are shifting our attention and resources to Cachet 3.x and will no longer be supporting the 2.x version. If your feedback or issue is relevant to the 3.x series, we encourage you to engage with the new branch.

For more information on the Cachet rebuild and our plans for 3.x, you can read the announcement [here](https://github.com/CachetHQ/Cachet/discussions/4342).

We appreciate your understanding and look forward to your contributions to the new version.
