### ISSUE TITLE
Upgrading Heroku Instancing doesn't work

### ISSUE THREAD

**Issue by brianjking** [cachethq/Cachet#297]
When attempting to follow the upgrade instructions for the Heroku instances documented here https://github.com/cachethq/Cachet/blob/master/docs/heroku/upgrade.md I find myself in a series of errors. If I force a push to Heroku the build fails, any suggestions?

Thanks!

bk-mbp13:ddstatus brianjking$ git fetch origin
warning: no common commits
remote: Counting objects: 6780, done.
remote: Compressing objects: 100% (27/27), done.
remote: Total 6780 (delta 11), reused 12 (delta 4)
Receiving objects: 100% (6780/6780), 3.34 MiB | 1.61 MiB/s, done.
Resolving deltas: 100% (4229/4229), done.
From github.com:cachethq/cachet
 * [new branch]      delete-component-group -> origin/delete-component-group
 * [new branch]      master     -> origin/master
bk-mbp13:ddstatus brianjking$ git reset --hard origin/master
HEAD is now at 751ba68 Apply default attributes on Component. Closes #291
bk-mbp13:ddstatus brianjking$ git push heroku
To https://git.heroku.com/ddstatus.git
 ! [rejected]        master -> master (non-fast-forward)
error: failed to push some refs to 'https://git.heroku.com/ddstatus.git'
hint: Updates were rejected because the tip of your current branch is behind
hint: its remote counterpart. Integrate the remote changes (e.g.
hint: 'git pull ...') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.
bk-mbp13:ddstatus brianjking$ 

Here's the build log from Heroku:

-----> Fetching custom git buildpack... done
-----> PHP (composer.json) app detected
-----> Bundling NGINX 1.6.2
       Checksums match. Fetching from cache.
-----> Bundling PHP 5.6.4
-----> Bundling extensions
       apcu
       Checksums match. Fetching from cache.
       phpredis
       Checksums match. Fetching from cache.
       mongo
       Checksums match. Fetching from cache.
-----> NODE (package.json) app detected

       TIP: Specify a node version in package.json

-----> Defaulting to latest stable node: 0.10.35
-----> Downloading and installing node

       TIP: Use npm shrinkwrap to lock down dependency versions

-----> Installing dependencies
       npm WARN package.json @ No repository field.
       
       > v8flags@1.0.8 install /tmp/build_d47bbf4ecc5850e3fe3b80d371aa4ed7/node_modules/gulp/node_modules/v8flags
       > node fetch.js
       
       
       > node-sass@1.2.3 install /tmp/build_d47bbf4ecc5850e3fe3b80d371aa4ed7/node_modules/laravel-elixir/node_modules/gulp-sass/node_modules/node-sass
       > node scripts/install.js
       
       Binary downloaded and installed at /tmp/build_d47bbf4ecc5850e3fe3b80d371aa4ed7/node_modules/laravel-elixir/node_modules/gulp-sass/node_modules/node-sass/vendor/linux-x64/binding.node
       
       > node-sass@1.2.3 postinstall /tmp/build_d47bbf4ecc5850e3fe3b80d371aa4ed7/node_modules/laravel-elixir/node_modules/gulp-sass/node_modules/node-sass
       > node scripts/build.js
       
       `linux-x64` exists; testing
       Binary is fine; exiting
       del@1.1.1 node_modules/del
       ????????? is-path-cwd@1.0.0
       ????????? object-assign@2.0.0
       ????????? rimraf@2.2.8
       ????????? each-async@1.1.1 (onetime@1.0.0, set-immediate-shim@1.0.0)
       ????????? is-path-in-cwd@1.0.0 (is-path-inside@1.0.0)
       ????????? globby@1.1.0 (async@0.9.0, array-union@1.0.1, glob@4.3.2, minimatch@2.0.1)
       
       gulp@3.8.10 node_modules/gulp
       ????????? pretty-hrtime@0.2.2
       ????????? interpret@0.3.10
       ????????? deprecated@0.0.1
       ????????? archy@1.0.0
       ????????? minimist@1.1.0
       ????????? tildify@1.0.0 (user-home@1.1.0)
       ????????? semver@4.2.0
       ????????? v8flags@1.0.8
       ????????? chalk@0.5.1 (escape-string-regexp@1.0.2, ansi-styles@1.1.0, supports-color@0.2.0, strip-ansi@0.3.0, has-ansi@0.1.0)
       ????????? orchestrator@0.3.7 (stream-consume@0.1.0, sequencify@0.0.7, end-of-stream@0.1.5)
       ????????? vinyl-fs@0.3.13 (graceful-fs@3.0.5, strip-bom@1.0.0, defaults@1.0.0, vinyl@0.4.6, mkdirp@0.5.0, through2@0.6.3, glob-stream@3.1.18, glob-watcher@0.0.6)
       ????????? gulp-util@3.0.1 (lodash._reinterpolate@2.4.1, vinyl@0.4.6, lodash.template@2.4.1, dateformat@1.0.11, multipipe@0.1.2, lodash@2.4.1, through2@0.6.3)
       ????????? liftoff@0.13.6 (extend@1.3.0, flagged-respawn@0.3.1, resolve@1.0.0, findup-sync@0.1.3)
       
       laravel-elixir-jshint@0.1.6 node_modules/laravel-elixir-jshint
       ????????? jshint-stylish@1.0.0 (log-symbols@1.0.1, text-table@0.2.0, string-length@1.0.0, chalk@0.5.1)
       ????????? gulp-jshint@1.9.0 (rcloader@0.1.2, minimatch@1.0.0, gulp-util@3.0.1, through2@0.6.3, jshint@2.5.11, lodash@2.4.1)
       ????????? gulp-notify@2.1.0 (node.extend@1.1.3, lodash.template@2.4.1, through2@1.1.1, gulp-util@2.2.20, node-notifier@4.0.3)
       
       bower@1.3.12 node_modules/bower
       ????????? is-root@1.0.0
       ????????? junk@1.0.0
       ????????? stringify-object@1.0.0
       ????????? which@1.0.8
       ????????? abbrev@1.0.5
       ????????? chmodr@0.1.0
       ????????? osenv@0.1.0
       ????????? archy@0.0.2
       ????????? rimraf@2.2.8
       ????????? opn@1.0.1
       ????????? lru-cache@2.5.0
       ????????? graceful-fs@3.0.5
       ????????? bower-logger@0.2.2
       ????????? bower-endpoint-parser@0.2.2
       ????????? lockfile@1.0.0
       ????????? nopt@3.0.1
       ????????? retry@0.6.0
       ????????? tmp@0.0.23
       ????????? q@1.0.1
       ????????? request-progress@0.3.0 (throttleit@0.0.2)
       ????????? chalk@0.5.0 (escape-string-regexp@1.0.2, ansi-styles@1.1.0, supports-color@0.2.0, strip-ansi@0.3.0, has-ansi@0.1.0)
       ????????? shell-quote@1.4.2 (array-filter@0.0.1, array-map@0.0.0, array-reduce@0.0.0, jsonify@0.0.0)
       ????????? semver@2.3.2
       ????????? bower-json@0.4.0 (intersect@0.0.3, deep-extend@0.2.11, graceful-fs@2.0.3)
       ????????? mkdirp@0.5.0 (minimist@0.0.8)
       ????????? p-throttler@0.1.0 (q@0.9.7)
       ????????? promptly@0.2.0 (read@1.0.5)
       ????????? fstream@1.0.3 (inherits@2.0.1)
       ????????? bower-config@0.5.2 (osenv@0.0.3, graceful-fs@2.0.3, optimist@0.6.1)
       ????????? fstream-ignore@1.0.2 (inherits@2.0.1, minimatch@2.0.1)
       ????????? tar-fs@0.5.2 (pump@0.3.5, tar-stream@0.4.7)
       ????????? glob@4.0.6 (inherits@2.0.1, once@1.3.1, minimatch@1.0.0)
       ????????? decompress-zip@0.0.8 (nopt@2.2.1, mkpath@0.1.0, touch@0.0.2, binary@0.3.0, readable-stream@1.1.13)
       ????????? bower-registry-client@0.2.2 (graceful-fs@2.0.3, request-replay@0.2.0, lru-cache@2.3.1, async@0.2.10, mkdirp@0.3.5, request@2.27.0)
       ????????? cardinal@0.4.0 (redeyed@0.4.4)
       ????????? request@2.42.0 (caseless@0.6.0, json-stringify-safe@5.0.0, aws-sign2@0.5.0, forever-agent@0.5.2, stringstream@0.0.4, oauth-sign@0.4.0, tunnel-agent@0.4.0, qs@1.2.2, node-uuid@1.4.2, mime-types@1.0.2, form-data@0.1.4, tough-cookie@0.12.1, http-signature@0.10.0, hawk@1.1.1, bl@0.9.3)
       ????????? update-notifier@0.2.0 (semver-diff@0.1.0, string-length@0.1.2, latest-version@0.2.0, configstore@0.3.1)
       ????????? mout@0.9.1
       ????????? handlebars@2.0.0 (optimist@0.3.7, uglify-js@2.3.6)
       ????????? inquirer@0.7.1 (figures@1.3.5, mute-stream@0.0.4, through@2.3.6, readline2@0.1.0, cli-color@0.3.2, rx@2.3.22, lodash@2.4.1)
       ????????? insight@0.4.3 (object-assign@1.0.0, async@0.9.0, chalk@0.5.1, lodash.debounce@2.4.1, os-name@1.0.1, tough-cookie@0.12.1, configstore@0.3.1, inquirer@0.6.0)
       
       laravel-elixir@0.9.1 node_modules/laravel-elixir
       ????????? gulp-rename@1.2.0
       ????????? underscore@1.7.0
       ????????? install@0.1.8
       ????????? require-dir@0.1.0
       ????????? run-sequence@1.0.2 (chalk@0.5.1)
       ????????? gulp-rev@2.0.1 (object-assign@1.0.0, through2@0.6.3)
       ????????? parse-filepath@0.5.0 (path-ends-with@0.2.1)
       ????????? del@0.1.3 (is-path-cwd@1.0.0, rimraf@2.2.8, each-async@1.1.1, is-path-in-cwd@1.0.0, globby@0.1.1)
       ????????? main-bower-files@2.4.1 (strip-json-comments@1.0.2, colors@0.6.2, minimatch@1.0.0, glob@4.3.2)
       ????????? gulp-filter@1.0.2 (multimatch@0.3.0, through2@0.6.3)
       ????????? gulp-phpspec@0.3.1 (map-stream@0.0.4, gulp-util@2.2.20)
       ????????? gulp-if@1.2.5 (gulp-match@0.2.1, through2@0.6.3, ternary-stream@1.2.3)
       ????????? gulp-concat@2.4.3 (through@2.3.6, concat-with-sourcemaps@1.0.0)
       ????????? gulp-minify-css@0.3.11 (memory-cache@0.0.5, through2@0.6.3, clean-css@2.2.23, bufferstreams@0.0.2)
       ????????? gulp-load-plugins@0.7.1 (multimatch@1.0.0, findup-sync@0.1.3)
       ????????? gulp-phpunit@0.6.3 (map-stream@0.0.5, gulp-util@2.2.20)
       ????????? gulp-coffee@2.2.0 (merge@1.2.0, through2@0.6.3, coffee-script@1.8.0, vinyl-sourcemaps-apply@0.1.4)
       ????????? gulp-uglify@1.0.2 (deepmerge@0.2.7, uglify-js@2.4.15, through2@0.6.3, vinyl-sourcemaps-apply@0.1.4)
       ????????? gulp-shell@0.2.11 (async@0.9.0, through2@0.6.3, lodash@2.4.1)
       ????????? gulp-autoprefixer@1.0.1 (object-assign@1.0.0, vinyl-sourcemaps-apply@0.1.4, through2@0.6.3, autoprefixer-core@3.1.2)
       ????????? gulp-util@3.0.1 (lodash._reinterpolate@2.4.1, minimist@1.1.0, vinyl@0.4.6, chalk@0.5.1, dateformat@1.0.11, lodash.template@2.4.1, multipipe@0.1.2, through2@0.6.3, lodash@2.4.1)
       ????????? gulp-notify@1.8.0 (node.extend@1.1.3, lodash.template@2.4.1, through2@1.1.1, gulp-util@2.2.20, node-notifier@3.4.1)
       ????????? gulp-less@1.3.9 (convert-source-map@0.4.1, lodash.defaults@2.4.1, vinyl-sourcemaps-apply@0.1.4, through2@0.5.1, less@1.7.5)
       ????????? npm@2.1.17
       ????????? gulp-sass@1.2.4 (clone@0.1.19, map-stream@0.1.0, vinyl-sourcemaps-apply@0.1.4, node-sass@1.2.3)
-----> Pruning unused dependencies
       npm WARN package.json @ No repository field.
-----> Caching node_modules for future builds
-----> Cleaning up node-gyp and npm artifacts
-----> Building runtime environment
       Node  v0.10.35
-----> Vendoring Composer
-----> Bundling additional extensions mcrypt
openssl
       mcrypt
Checksums match. Fetching from cache.
       openssl
Checksums match. Fetching from cache.
Updating to version e172cd81a146666d844d2b7b37b5feccb89e2b61.
    Downloading: connection...    Downloading: 0%               Downloading: 5%    Downloading: 10%    Downloading: 15%    Downloading: 20%    Downloading: 25%    Downloading: 30%    Downloading: 35%    Downloading: 40%    Downloading: 45%    Downloading: 50%    Downloading: 55%    Downloading: 60%    Downloading: 65%    Downloading: 70%    Downloading: 75%    Downloading: 80%    Downloading: 85%    Downloading: 90%    Downloading: 95%    Downloading: 100%
Use composer self-update --rollback to return to version 28c65b5425f7f8722c260e3787b74c1ea6b37e3b
-----> Installing application dependencies with Composer
       Loading composer repositories with package information
       Installing dependencies from lock file
         - Installing symfony/finder (v2.5.8)
           Loading from cache
       
         - Installing symfony/filesystem (v2.6.1)
           Loading from cache
       
         - Installing symfony/console (v2.5.8)
           Loading from cache
       
         - Installing nikic/php-parser (v0.9.5)
           Loading from cache
       
         - Installing classpreloader/classpreloader (1.0.2)
           Loading from cache
       
         - Installing d11wtq/boris (v1.0.8)
           Loading from cache
       
         - Installing league/fractal (0.11.0)
           Loading from cache
       
         - Installing symfony/translation (v2.5.8)
           Loading from cache
       
         - Installing symfony/security-core (v2.5.8)
           Loading from cache
       
         - Installing symfony/routing (v2.5.8)
           Loading from cache
       
         - Installing symfony/process (v2.5.8)
           Loading from cache
       
         - Installing symfony/http-foundation (v2.5.8)
           Loading from cache
       
         - Installing symfony/event-dispatcher (v2.6.1)
           Loading from cache
       
         - Installing symfony/debug (v2.5.8)
           Loading from cache
       
         - Installing psr/log (1.0.0)
           Loading from cache
       
         - Installing symfony/http-kernel (v2.5.8)
           Loading from cache
       
         - Installing symfony/dom-crawler (v2.5.8)
           Loading from cache
       
         - Installing symfony/css-selector (v2.5.8)
           Loading from cache
       
         - Installing symfony/browser-kit (v2.5.8)
           Loading from cache
       
         - Installing swiftmailer/swiftmailer (v5.3.1)
           Loading from cache
       
         - Installing stack/builder (v1.0.3)
           Loading from cache
       
         - Installing predis/predis (v0.8.7)
           Loading from cache
       
         - Installing phpseclib/phpseclib (0.3.9)
           Loading from cache
       
         - Installing patchwork/utf8 (v1.1.26)
           Loading from cache
       
         - Installing nesbot/carbon (1.13.0)
           Loading from cache
       
         - Installing monolog/monolog (1.12.0)
           Loading from cache
       
         - Installing jeremeamia/superclosure (1.0.1)
           Loading from cache
       
         - Installing ircmaxell/password-compat (v1.0.4)
           Loading from cache
       
         - Installing filp/whoops (1.1.3)
           Loading from cache
       
         - Installing laravel/framework (v4.2.16)
           Loading from cache
       
         - Installing dingo/api (v0.8.2)
           Loading from cache
       
         - Installing doctrine/lexer (v1.0.1)
           Downloading: connection...    Downloading: 0%               Downloading: 100%
       
         - Installing doctrine/annotations (v1.2.3)
           Loading from cache
       
         - Installing doctrine/cache (v1.3.1)
           Loading from cache
       
         - Installing doctrine/collections (v1.2)
           Loading from cache
       
         - Installing doctrine/inflector (v1.0.1)
           Loading from cache
       
         - Installing doctrine/common (v2.4.2)
           Loading from cache
       
         - Installing doctrine/dbal (v2.5.0)
           Loading from cache
       
         - Installing graham-campbell/security (v2.1.3)
           Downloading: connection...    Downloading: 100%         
       
         - Installing graham-campbell/binput (v2.1.3)
           Downloading: connection...    Downloading: 100%         
       
         - Installing erusev/parsedown (1.1.4)
           Loading from cache
       
         - Installing erusev/parsedown-extra (0.2.6)
           Loading from cache
       
         - Installing graham-campbell/markdown (v2.0.6)
           Downloading: connection...    Downloading: 100%         
       
         - Installing graham-campbell/throttle (v2.0.2)
           Downloading: connection...    Downloading: 100%         
       
         - Installing react/promise (v2.2.0)
           Loading from cache
       
         - Installing guzzlehttp/streams (3.0.0)
           Loading from cache
       
         - Installing guzzlehttp/ringphp (1.0.5)
           Loading from cache
       
         - Installing guzzlehttp/guzzle (5.1.0)
           Loading from cache
       
         - Installing roumen/feed (v2.8.1)
           Downloading: connection...    Downloading: 100%         
       
         - Installing thujohn/rss (1.0.3)
           Loading from cache
       
         - Installing watson/validating (0.10.6)
           Loading from cache
       
       Generating optimized autoload files
       Generating optimized class loader
       Compiling common classes
       Compiling views
       Nothing to migrate.
-----> Detected Laravel app
-----> Setting up Laravel app
-----> Running compile commands
       Running 'bower install'
/tmp/buildpack_d47bbf4ecc5850e3fe3b80d371aa4ed7/bin/compile: line 293: bower: command not found

 !     Push rejected, failed to compile PHP (composer.json) app

**Comment by jbrooksuk** [comment]
Is this an existing installation? If so, you need to change the `BUILDPACK_URL` to `https://github.com/cachethq/cachet-buildpack`.

**Comment by brianjking** [comment]
:frowning: Even with the correct buildpack URL I'm unable to push this to Heroku and have it successfully build. The first error I get every time is this: 

master (non-fast-forward) error: failed to push some refs to 'https://git.heroku.com/ddstatus.git' hint: Updates were rejected because the tip of your current branch is behind hint: its remote counterpart. Integrate the remote changes (e.g. hint: 'git pull ...') before pushing again. hint: See the 'Note about fast-forwards' in 'git push --help' for details.

Am I doing something wrong? 

If I add --force to git push heroku the build fails.

Thanks!

If I just launch a new instance using the 1 button Heroku option do I have to manually re-configure or is there an easier option? Either way, great job and keep up the amazing work. Really appreciate it.

:grinning: By the way - I shared Cachet with Stackeo the other day to bring you a bit of extra spotlight. http://stackeo.me/posts/cachet

**Comment by jbrooksuk** [comment]
@brianjking did you follow the [Heroku upgrade guide](https://github.com/cachethq/Cachet/blob/master/docs/heroku/upgrade.md) fully?

Unfortunately there is no way to import existing data into a new deployment - but that's a good idea to have.

**Comment by jenolan** [comment]
Same as @brianjking followed the instructions on readme.io (the link you have above 404'd) here is my results...

abbey:Sites larrylewis$  heroku git:clone -a jenolan
Cloning from app 'jenolan'...
Cloning into 'jenolan'...
remote: Counting objects: 315, done.
remote: Compressing objects: 100% (290/290), done.
remote: Total 315 (delta 80), reused 0 (delta 0)
Receiving objects: 100% (315/315), 253.67 KiB | 55.00 KiB/s, done.
Resolving deltas: 100% (80/80), done.
Checking connectivity... done.
abbey:Sites larrylewis$ cd jenolan
abbey:jenolan larrylewis$ git remote add origin https://github.com/cachethq/Cachet.git
abbey:jenolan larrylewis$ git fetch origin
warning: no common commits
remote: Counting objects: 8669, done.
remote: Compressing objects: 100% (2872/2872), done.
remote: Total 8669 (delta 5585), reused 8495 (delta 5470)
Receiving objects: 100% (8669/8669), 3.69 MiB | 65.00 KiB/s, done.
Resolving deltas: 100% (5585/5585), done.
From https://github.com/cachethq/Cachet
 * [new branch]      crowdin-incontext -> origin/crowdin-incontext
 * [new branch]      master     -> origin/master
 * [new branch]      notifications -> origin/notifications
 * [new branch]      scheduled-statuses -> origin/scheduled-statuses
 * [new branch]      segment    -> origin/segment
abbey:jenolan larrylewis$ git reset --hard origin/master
HEAD is now at e41d4a9 Make component groups work
abbey:jenolan larrylewis$ heroku config:get BUILDPACK_URL
https://github.com/cachethq/cachet-buildpack
abbey:jenolan larrylewis$ git push heroku
warning: push.default is unset; its implicit value has changed in
Git 2.0 from 'matching' to 'simple'. To squelch this message
and maintain the traditional behavior, use:

  git config --global push.default matching

To squelch this message and adopt the new behavior now, use:

  git config --global push.default simple

When push.default is set to 'matching', git will push local branches
to the remote branches that already exist with the same name.

Since Git 2.0, Git defaults to the more conservative 'simple'
behavior, which only pushes the current branch to the corresponding
remote branch that 'git pull' uses to update the current branch.

See 'git help config' and search for 'push.default' for further information.
(the 'simple' mode was introduced in Git 1.7.11. Use the similar mode
'current' instead of 'simple' if you sometimes use older versions of Git)

To https://git.heroku.com/jenolan.git
 ! [rejected]        master -> master (non-fast-forward)
error: failed to push some refs to 'https://git.heroku.com/jenolan.git'
hint: Updates were rejected because the tip of your current branch is behind
hint: its remote counterpart. Integrate the remote changes (e.g.
hint: 'git pull ...') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.
abbey:jenolan larrylewis$

**Comment by jenolan** [comment]
I solved this for myself (I think) my manually merging, then pushing. But the recipe for doing this is not non-techie safe.

**Comment by jbrooksuk** [comment]
Dos you force push after resetting the head?

**Comment by jenolan** [comment]
I used my smartGIT tool (gui based git) just told it that I wanted the local sent and it took care of it. Just saying that the instructions as they are for non-techies don't seem to be right, if a list of commands are shown as the method it must work as-is, well that's just my view of course.

**Comment by jbrooksuk** [comment]
Did you follow [this](https://docs.cachethq.io/v1.0/docs/upgrading-on-heroku)? I guess you did.
