### ISSUE TITLE
[Version 2.4] "days of incidents to show" setting works incorrectly

### ISSUE THREAD

**Issue by shurikanet** [CachetHQ/Cachet#2976]
See example: 
Application Setup settings: http://prntscr.com/ixfrw2  (5 days )
How it is shown on the website: http://prntscr.com/ixfsdn  (today is March 28, but March 23-18  dates are shown )

Expected result:  March 28-23

If I change setting for 10 days, in the 'Past Incidents' section  I will see the following dates: 18th March 2018 - 8th March 2018

Version of PHP: 7.2.0

**Comment by jbrooksuk** [comment]
Thanks for reporting this! This should be fixed now :)
