### ISSUE TITLE
Unable to install Cachet when going to the URL

### ISSUE THREAD

**Issue by Jonah0037** [CachetHQ/Cachet#2977]
Hello, I am trying to install Cachet, and when I go to the main setup page in a browser, it shows as html. 
![screenshot_1](https://user-images.githubusercontent.com/24997844/38045601-750e924e-327a-11e8-9b6e-592f5a196f2a.png)
I have followed all instructions!

**Comment by prbond** [comment]
Same problem, i think it is about base url

**Comment by jbrooksuk** [comment]
Looks like a rewrite issue.

**Comment by anthosz** [comment]
Hi @Jonah0037 @prbond @jbrooksuk ,

Did you fix finally the issue? There are no history on slack...

I try to things (url is 127.0.0.1/cachet):
APP URL is the same in all case
If I add RewriteBase, only page seems to works but by example 127.0.0.1/cachet/setup/ cannot load ressources (like js/css...etc). Indeed, the browser try to get resources from 127.0.0.1/build/... instead 127.0.0.1/cachet/build/...

If I don't add RewriteBase, I have 404 for all pages but ressources links are ok..

**Comment by prbond** [comment]
No time, I gave up, sorry
