### ISSUE TITLE
Metrics Documentation Issues

### ISSUE THREAD

**Issue by DonRichards** [CachetHQ/Cachet#2988]
1. Where is the documentation on how to use this? 
2. How to configure it? 
3. What is a suffix for? 
4. What does default value even mean? 
5. What specifically is the decimal places being referred to? 
6. Where is the the data coming from?
7. How do you link it to a specific component?

**Comment by jbrooksuk** [comment]
@DonRichards hey, I'm confused as to what these questions are in relation to exactly?
