### ISSUE TITLE
[Version 2.4] No new line in an email incident

### ISSUE THREAD

**Issue by sontt710** [CachetHQ/Cachet#2996]
Hello,

Could you help me with this issue?

![image](https://user-images.githubusercontent.com/31494976/38283885-c25c1f2c-37e2-11e8-9105-2f938ab16f33.png)

**Comment by jbrooksuk** [comment]
Sorry for the delay @sontt710 can you share the raw Markdown that you used please? I feel like this has been fixed already.

**Comment by jbrooksuk** [comment]
@sontt710 can you please test out https://github.com/CachetHQ/Cachet/pull/3100 I think I've fixed this now.

**Comment by sontt710** [comment]
After updated, I can't create an incident, the page show blank and no logs be recorded
![image](https://user-images.githubusercontent.com/31494976/41516749-dd35c6ac-72e0-11e8-9523-d0adf4484de6.png)

**Comment by jbrooksuk** [comment]
Ah, this is because I need to re-compile assets. Bear with, I’ll get this done this morning, I’m on my phone currently.

**Comment by jbrooksuk** [comment]
So now that @nstapelbroek has validated that it works, I've pushed compiled assets and will merge in this branch 👌

**Comment by jbrooksuk** [comment]
Closed by https://github.com/CachetHQ/Cachet/pull/3100

**Comment by nstapelbroek** [comment]
ah, I thought this recompiling assets was just me :see_no_evil: . Good catch everyone!
