### ISSUE TITLE
Gaps in Graph

### ISSUE THREAD

**Issue by RedSpid3r** [CachetHQ/Cachet#2997]
I'm polling and entering metric data into cachet every 5 mins, but when I set the graph to hourly it always shows at 1 min intervals, leaving gaps in my graph.

can this be changed so that the x-axis only displays either every 5 mins or at the timestamp the data was entered into cachet?

Running v2.3.13
 
Example below:

![Graph](https://i.imgur.com/LOPrwTA.png)

**Comment by RedSpid3r** [comment]
nobody?! :/

**Comment by jbrooksuk** [comment]
Are you able to supply a data dump so we can test against?

**Comment by RedSpid3r** [comment]
@jbrooksuk do you have somewhere i can mail/send over an sql dump of the metrics tables?

**Comment by jbrooksuk** [comment]
@RedSpid3r sorry for the delay! I'm starting to look into metrics now. Could you email me at james@alt-three.com please.
