### ISSUE TITLE
Website footer cachet link  returns 404

### ISSUE THREAD

**Issue by dcoeurjo** [cachethq/Cachet#300]
The Cachet link (https://cachethq.github.io)  in the website footer once installed in heroku returns a 404.
The correct URL seems to be https://cachethq.io

**Comment by jbrooksuk** [comment]
That's now changed, have you pulled?

**Comment by jbrooksuk** [comment]
https://github.com/cachethq/Cachet/blob/master/app/lang/en/cachet.php#L41

**Comment by dcoeurjo** [comment]
I will.. thanks

**Comment by jbrooksuk** [comment]
:)
