### ISSUE TITLE
Can't login

### ISSUE THREAD

**Issue by jsargent7089** [CachetHQ/Cachet#3002]
Error 400
CSRF token validation failed.
Bad Request
What does this mean?
Something went wrong on our servers while we were processing your request. CSRF token validation failed. This occurrence has been logged, and a highly trained team of monkeys has been dispatched to deal with your problem. We're really sorry about this, and will work hard to get this resolved as soon as possible.

This error can be identified by 5ccf53e1-29d4-4535-bde1-bad4b872fa61. You might want to take a note of this code.

Perhaps you would like to go to our home page?

**Comment by uxen-ab** [comment]
Hi!

Could you provide some more informations?

- Log file
- Explanations about how to reproduce
- Link to your homepage is useful

Also, note that we're a community on Slack (https://cachethq-slack.herokuapp.com), please come and ask on Slack before asking on Gihub that is mainly for bugs. We'd be glad to help you!

**Comment by jsargent7089** [comment]
Try to login to my dashboard I enter my username and password then get that error message

https://status.dozecloud.com

**Comment by anthonybocci** [comment]
Please add the content of your log file (in `storage/logs`) in order to find what's the problem. Also what is the Cachet version?

**Comment by jsargent7089** [comment]
Here are the log files

[laravel-2018-04-09.log](https://github.com/CachetHQ/Cachet/files/1908337/laravel-2018-04-09.log)
[laravel-2018-04-10.log](https://github.com/CachetHQ/Cachet/files/1908338/laravel-2018-04-10.log)

**Comment by jsargent7089** [comment]
my cachet version is v2.3.14

**Comment by anthonybocci** [comment]
Hello @jsargent7089,

Could you provide the content of your `.env` file? (Don't forget to remove your passwords).
For now, I think that your `session driver` is invalid. Please update your session driver to `file`, execute `php artisan config:clear` and try to login again.

**Comment by jbrooksuk** [comment]
Yeah, this is likely a configuration error. Tagging as `support`.

**Comment by tienhm0202** [comment]
I think it's a config error. You should be sure your SESSION_DOMAIN matched with your cachet domain.
