### ISSUE TITLE
Trait 'AltThree\TestBench\ValidationTrait' not found  after upgrading 2.4 

### ISSUE THREAD

**Issue by krollebol** [CachetHQ/Cachet#3003]
I run Cachet 2.4 from git, it worked fine before. But last week I updated to latest git version following the upgrade procedure:
- php artisan down
- git pull
- composer install --no-dev -o --no-scripts
- php artisan app:update

At this stage I get an error:
```
PHP Fatal error:  Trait 'AltThree\TestBench\ValidationTrait' not found in /var/www/Cachet-dev/app/Models/Taggable.php on line 24

In Taggable.php line 24:
                                                        
  Trait 'AltThree\TestBench\ValidationTrait' not found  
```

After 'php artisan up' the site works, but the incidents are not showing when "Only show days containing incidents in the timeline? " is activate in settings. Notting is shown in "Past incidents". "Stickied incidents" shows the incidents that are stickied.

Could this be related to the error?

On your demo site it still works as expected.

Thanks!

**Comment by RyoshiKayo** [comment]
@krollebol I had the same issue; I was able to remedy this by running `composer require alt-three/testbench` 

Perhaps this is missing from [composer.json](https://github.com/CachetHQ/Cachet/blob/2.4/composer.json)?

**Comment by jbrooksuk** [comment]
Looks like this is now resolved, thanks @JordyvanDortmont.

**Comment by ilogus** [comment]
Hello I have the same problem but I did not understand how to correct it can you help me please?

**Comment by ilogus** [comment]
[laravel-2018-04-28.log](https://github.com/CachetHQ/Cachet/files/1957730/laravel-2018-04-28.log)

I want to send the log file on pastebin but I get time out.
