### ISSUE TITLE
Chart initial interval not working

### ISSUE THREAD

**Issue by hashitha** [CachetHQ/Cachet#3008]
When I have set the Default view to "Week". The page doesn't load the view. If I select the week then it loads it. I used the EC2 image from "CachetHQ Powered by Intuz"

See below screenshot

https://cl.ly/2802473w3k0s

**Comment by jbrooksuk** [comment]
What version of Cachet are you using?

**Comment by hashitha** [comment]
2.4.0-dev

![image](https://user-images.githubusercontent.com/10569142/39158481-e765e6d0-4792-11e8-940c-eda52e2b3fbd.png)

**Comment by jbrooksuk** [comment]
I believe this is fixed now.
