### ISSUE TITLE
Can someone tell me where to noidex the entire site.

### ISSUE THREAD

**Issue by danielmclements** [CachetHQ/Cachet#3011]
I want to put the following tag into the head of every page but can't find the best place to put it. Can someone please point me in the right direction?

`<meta name="robots" content="noindex">`

Thanks

Daniel

**Comment by jbrooksuk** [comment]
If you control the server, then I'd add a [`X-Robots-Tag` header](https://developers.google.com/search/reference/robots_meta_tag).
