### ISSUE TITLE
Lack of unsubscribe button in the Component Update Emails

### ISSUE THREAD

**Issue by JamesWilson19947** [CachetHQ/Cachet#3015]
Hi, we are using Version 2.3.9.

We notice that the component e-mails only have the option to manage emails and not unsubscribe where-as all over e-mails have the option to unsubscribe. With EU rules its necessary for the unsubscribe button to be in all e-mails.

I'm not sure if you have fixed this in 2.4 or above if so please disregard this.

It looks a pretty easy thing to adjust, so just wanted to see if you were aware of this and if you it's in the pipeline to be fixed?

Thanks!

**Comment by jbrooksuk** [comment]
Thanks for reporting. We need to do a couple of things in terms of emails, such as #2899.

**Comment by jbrooksuk** [comment]
Replacing with https://github.com/CachetHQ/Cachet/issues/3101
