### ISSUE TITLE
Adding component group: The name format is invalid

### ISSUE THREAD

**Issue by sandyws** [CachetHQ/Cachet#3019]
I am using dockerised version 2.3.9 cachet. I am trying to add incident with following details.

**site-url:** https://site-url/api/v1/components/groups
**Body:** 
{ "data": 
{ 
"name": "adminconsolee", 
"order": 0, 
"collapsed": 0, 
"updated_at": "2018-04-23 17:01:35", 
"created_at": "2018-04-23 17:01:35", "id": 1 
}
}
**Headers:**
Content-Type: application/json
X-Cachet-Token: ******

**I am following documentation given at :** https://docs.cachethq.io/reference#post-componentgroups
But still getting following error.
{"errors":[{"id":"70bbc601-0a20-4017-af82-fce370d05576","status":400,"title":"Bad Request","detail":"The request cannot be fulfilled due to bad syntax.","meta":{"details":["The name format is invalid."]}}]}

**Comment by sandyws** [comment]
Solved: Dont use "data": {} key. Pass all the details without data key.

**Comment by jbrooksuk** [comment]
This is correct.
