### ISSUE TITLE
Unable to log back into the dashboard

### ISSUE THREAD

**Issue by jbrooksuk** [cachethq/Cachet#302]
1. Deploy to Heroku
2. Setup
3. Logout
4. Log back in

You can't get back into the account and it'll just return you to the login screen without any error messages.

**Comment by willdurand** [comment]
@jbrooksuk I am not experiencing this issue (Heroku as well).

**Comment by jbrooksuk** [comment]
Interesting, it could be the demo site is having the password changed. I'll deploy a dev instance too.

**Comment by jbrooksuk** [comment]
Yep, no bug. I've re-deployed a test version and it's worked.
