### ISSUE TITLE
An error has occurred and this resource cannot be displayed : Incident creation API 

### ISSUE THREAD

**Issue by ghost** [CachetHQ/Cachet#3023]
I am providing following values while creating incident via api:
{
    "name": "new incident",
    "status": 2,
    "message": "VM stopped by infra team",
    "visible": 1,
    "created_at": "2018-04-22 11:25:16"
}

Incident creation is not working with **created_at** param. If we dont pass **created_at** param, incident will be created with current date. But I want to pass date of last week. So I tried to check the source code for params, i got following.
In below file I can see **created_at** param is there. Still I am getting error.
**/var/www/html/app/Http/Controllers/Api/IncidentController.php** 
    public function postIncidents()
    {
        try {
            $incident = dispatch(new ReportIncidentCommand(
                Binput::get('name'),
                Binput::get('status'),
                Binput::get('message'),
                Binput::get('visible', true),
                Binput::get('component_id'),
                Binput::get('component_status'),
                Binput::get('notify', true),
                **Binput::get('created_at'),**
                Binput::get('template'),
                Binput::get('vars')
            ));
        } catch (QueryException $e) {
            throw new BadRequestHttpException();
        }

**Comment by jbrooksuk** [comment]
What version of Cachet are you using?
