### ISSUE TITLE
"Subscribed to all updates" shown in subscriptions view when not subscribed to all updates

### ISSUE THREAD

**Issue by farhank3389** [CachetHQ/Cachet#3024]
I created a test subscription and used the manage subscription link in the email to only select one component. However I can still see the user as subscribed to all updates even though they are not.

I think its just a UI problem as I don't actually receive the updates for the components I am not subscribed to.

v2.3.14 with  php 7.0

**Comment by jbrooksuk** [comment]
Thank you for your input on Cachet 2.x. We are shifting our attention and resources to Cachet 3.x and will no longer be supporting the 2.x version. If your feedback or issue is relevant to the 3.x series, we encourage you to engage with the new branch.

For more information on the Cachet rebuild and our plans for 3.x, you can read the announcement [here](https://github.com/CachetHQ/Cachet/discussions/4342).

We appreciate your understanding and look forward to your contributions to the new version.
