### ISSUE TITLE
All incidents disappear when more than one incident is created

### ISSUE THREAD

**Issue by farhank3389** [CachetHQ/Cachet#3026]
This is a weird one...

I have an incident that was created 7 days ago with some updates. It displays fine when it is the only incident. I added a test incident and both of them fail to show! Same issue whether or not the test incident has updates or not.

They are both:
* Viewable by public
* Within the "days to show incidents" timeframe
* Not stickied

v2.3.14 php 7.0 mariadb 5.5

**Comment by farhank3389** [comment]
Creating an incident for the same component shows the same issue now too for some reason...

**Comment by farhank3389** [comment]
The settings page in the dashboard shows v2.4.0-dev for some reason. Even though I checked out v2.3.14 from git tag -l. Not sure why or how it has upgraded.

**Comment by farhank3389** [comment]
This only happens when "Only show days containing incidents in the timeline?" is ticked

**Comment by jbrooksuk** [comment]
I'm going to investigate this now.

**Comment by jbrooksuk** [comment]
This is no longer occuring on the latest 2.4 changes.

<img width="973" alt="image" src="https://user-images.githubusercontent.com/246103/39396464-872cee42-4ae6-11e8-9c59-4519b3d882be.png">
