### ISSUE TITLE
Can't update dashboard settings anymore

### ISSUE THREAD

**Issue by willdurand** [cachethq/Cachet#303]
Since last changes related to #287, I can't update dashboard settings anymore... The form gets redirected from `/dashboard/settings` to `/dashboard/settings/setup`, and thus the `POST` request is gone, meaning it does not submit the form.

**Comment by jbrooksuk** [comment]
@willdurand can you try #302 for me too please.

**Comment by jbrooksuk** [comment]
This works under MySQL, so I'm inclined to think that it's related to PgSQL again. I'll have a look.

**Comment by jbrooksuk** [comment]
@willdurand I've deployed a dev version and I'm able to update settings.

**Comment by jbrooksuk** [comment]
Heroku btw.

**Comment by jbrooksuk** [comment]
Oh, hangon... I've tried to change a theme setting and now get an error.

**Comment by willdurand** [comment]
mmh interesting..

**Comment by jbrooksuk** [comment]
The main `/dashboard/settings/setup` works for me.

**Comment by willdurand** [comment]
Well. It does not work **for me**. Second time you're telling me that it works for you. Honestly, I am really glad for you **BUT**, I really have an issue, and that one is described as much as possible here.

`POST`'ing a form to update _Application Setup_ gets redirected with a `302` and changes are **not** persisted. I don't get any feedback, and looking at the code, there are 5 possible redirections.

* Commit deployed: 3e74d28ff4d7b71fd0fec72f4c3ee7311ce55cfa
* Buildpack used is the recommended one
* No errors in logs

**Comment by jbrooksuk** [comment]
@willdurand sorry, but I don't appreciate your tone (yes, I saw your tweet too). I'm investigating the issue as I type this (pushing to Heroku, plus I've just pushed another change which could help). The reason for me mentioning that it works is for me to dump my thoughts. It works in MySQL, so now I know that it's again a PgSQL issue.

I'll continue to update this issue as I go through it.

**Comment by jbrooksuk** [comment]
I'm sorry that there is an issue for you, I'm not singling you out, it's an issue that will be affecting everybody. I'm doing my best to get that resolved for you and everyone.

**Comment by jbrooksuk** [comment]
@willdurand please try upgrading to 3cbb500de7520c1af7f41d4d962cfe821bc1e732 - I've pushed to Heroku (https://cachet-dev.herokuapp.com) and that has allowed me to update the settings.

![screen shot 2015-01-06 at 15 54 09](https://cloud.githubusercontent.com/assets/246103/5631170/4852bf72-95bc-11e4-92ea-c29fe7b4a7f7.png)

**Comment by willdurand** [comment]
I don't really appreciate your tone either, so let's go ahead ;-)

**Comment by willdurand** [comment]
Ok, upgrading..

**Comment by jbrooksuk** [comment]
@willdurand I've not been rude to you, I've done nothing but apologise and tried to fix the issues. I'm sorry if you think I'm being rude.

Let me know if it goes whacky.

**Comment by willdurand** [comment]
@jbrooksuk it works like a charm, thank you.

Updating all settings now works again \o/

**Comment by jbrooksuk** [comment]
:boom: 

Thanks for the bug report and helping me test this.
