### ISSUE TITLE
Setup: "An error has occurred and this resource cannot be displayed."

### ISSUE THREAD

**Issue by emresaracoglu** [CachetHQ/Cachet#3038]
Hi.

I am getting this error in the admin account section in setup:

> An error has occurred and this resource cannot be displayed.

![untitled](https://user-images.githubusercontent.com/297968/39563757-1ce432ac-4eba-11e8-9586-53bdb21281c2.png)

Internal Error 500

What would be the reason?
Thank you.

**Comment by chronicals** [comment]
Experienced the same, pressing next again redirected me to the Dashboard, so I ignored the error.

**Comment by jbrooksuk** [comment]
Can you share the log file please.
