### ISSUE TITLE
Constatly increasing of graph height on period change

### ISSUE THREAD

**Issue by aslepakurov** [CachetHQ/Cachet#3039]
![screenshot-2018-5-5 test cachet](https://user-images.githubusercontent.com/2423180/39667199-36c35e18-50b9-11e8-89e2-8f5a2eec8b23.png)

Every time time period is being selected for graph - height of said graph increases indefinitely.

Checked on OSX/Firefox 59.0.3

**Comment by jbrooksuk** [comment]
That’s annoying! Likely due to something in how we’ve configured Chart.js.

**Comment by jbrooksuk** [comment]
Thank you for your input on Cachet 2.x. We are shifting our attention and resources to Cachet 3.x and will no longer be supporting the 2.x version. If your feedback or issue is relevant to the 3.x series, we encourage you to engage with the new branch.

For more information on the Cachet rebuild and our plans for 3.x, you can read the announcement [here](https://github.com/CachetHQ/Cachet/discussions/4342).

We appreciate your understanding and look forward to your contributions to the new version.
