### ISSUE TITLE
Time shifting when editing scheduled event

### ISSUE THREAD

**Issue by aslepakurov** [CachetHQ/Cachet#3040]
![screenshot-2018-5-5 edit scheduled maintenance - dashboard](https://user-images.githubusercontent.com/2423180/39667321-e88ae3c6-50bb-11e8-99c8-16db8c6a1ee4.png)

When editing a scheduled event, on clicking the save button time shifts 1 hour ahead.

**Comment by jbrooksuk** [comment]
Definitely a bug! Metrics are a right pain.

**Comment by jbrooksuk** [comment]
Thank you for your input on Cachet 2.x. We are shifting our attention and resources to Cachet 3.x and will no longer be supporting the 2.x version. If your feedback or issue is relevant to the 3.x series, we encourage you to engage with the new branch.

For more information on the Cachet rebuild and our plans for 3.x, you can read the announcement [here](https://github.com/CachetHQ/Cachet/discussions/4342).

We appreciate your understanding and look forward to your contributions to the new version.
