### ISSUE TITLE
ERROR 404, /setup

### ISSUE THREAD

**Issue by NurLutix** [CachetHQ/Cachet#3044]
Hello
I just wanted to install the software, but I'm not going any further.
When I call the page, I'm redirected to /setup. There comes the following message:

Error 404
Not Found
What does this mean?
Something went wrong on our servers while we were processing your request. The requested resource could not be found but may be available again in the future. This occurrence has been logged, and a highly trained team of monkeys has been dispatched to deal with your problem. We're really sorry about this, and will work hard to get this resolved as soon as possible.

This error can be identified by 34fb6f67-8985-4165-a6ea-8af6dfdf27cc. You might want to take a note of this code.

Perhaps you would like to go to our home page?

What can I do?

**Comment by NurLutix** [comment]
Außerdem ist der Ordner setup noch nicht mal vorhanden.

https://NurLutix.de/screen18_133_20-29-53_52.png

**Comment by jbrooksuk** [comment]
There is no `setup` folder as Cachet uses rewrite rules. Please follow https://docs.cachethq.io/docs/installing-cachet
