### ISSUE TITLE
[Enhancement] Better user accountability

### ISSUE THREAD

**Issue by RyoshiKayo** [CachetHQ/Cachet#3046]
- Ability to add user who created/updated/modified incident to email notification
- Add `- Updated by {username} at {time}` to incidents.

**Comment by jbrooksuk** [comment]
👍 

Technically, we do know who updated an incident through the `actions` table, we just need to pull this information back.

**Comment by jbrooksuk** [comment]
Thank you for your input on Cachet 2.x. We are shifting our attention and resources to Cachet 3.x and will no longer be supporting the 2.x version. If your feedback or issue is relevant to the 3.x series, we encourage you to engage with the new branch.

For more information on the Cachet rebuild and our plans for 3.x, you can read the announcement [here](https://github.com/CachetHQ/Cachet/discussions/4342).

We appreciate your understanding and look forward to your contributions to the new version.
