### ISSUE TITLE
Poor translation in Hebrew language

### ISSUE THREAD

**Issue by schefs** [CachetHQ/Cachet#3047]
When translation to hebew is turned on, only half of the content is translated and the rest is in English. Running on 2.3.14 with docker.
Is there a way to fix this ?
What is the plans for a full language support ?
Is there a easy way to translate the rest of the content myself ?

**Comment by jbrooksuk** [comment]
If you have any issues with the translations, you can submit a change to https://translate.cachethq.io/project/cachet/he
