### ISSUE TITLE
broken dashboard page after login 

### ISSUE THREAD

**Issue by kzdd** [CachetHQ/Cachet#3049]
Hello, 
I had installed and setup Cachet following the install instruction. When i logged in the dashboard, the page looks like this:
![screen shot 2018-05-17 at 10 57 03 am](https://user-images.githubusercontent.com/22047306/40209163-9fc1f194-59f2-11e8-9c75-1ec3f5f6b243.png) and no content. 

And I checked log file. There is a error log: 
[:error] [pid 8166] [client 127.0.0.1:60849] PHP Fatal error:  Call to undefined function Intervention\\Image\\Gd\\imagettfbbox() in /Users/username/Documents/Cachet/vendor/intervention/image/src/Intervention/Image/Gd/Font.php on line 85, referer: http://127.0.0.1/auth/login 

500 error page appears if click on the image or running on php -S localhost and login to dashboard. Please advising if anything missing or did wrong. Thank you!

My php and modules are : php 5.6 and  
![screen shot 2018-05-17 at 2 52 39 pm](https://user-images.githubusercontent.com/22047306/40209349-7ba49356-59f3-11e8-9d39-32420a903000.png)

Database: mysqld 10.2.12-MariaDB
Apache:2.4
macOS 10.12
PS: Cachet 2.4

**Comment by kzdd** [comment]
Also, this is the logged error. from log file:
production.CRITICAL: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'Call to undefined function Intervention\Image\Gd\imagettfbbox()' in /Users/Kai/Documents/Cachet24/vendor/intervention/image/src/Intervention/Image/Gd/Font.php:85

**Comment by jbrooksuk** [comment]
Looks like you need to compile PHP with freetype support. http://php.net/manual/en/function.imagettfbbox.php
