### ISSUE TITLE
[Question] Would it be possible to separate `show_support` and `rss/atom` features?

### ISSUE THREAD

**Issue by willdurand** [cachethq/Cachet#305]
Hi!

It is probably intentional (well, I guess) but if one does not "show support" for Cachet, then RSS and Atom links are not displayed in the status page. Is this intentional first? And then, would it be possible to change that?

**Comment by jbrooksuk** [comment]
Do you mean the links in the footer?

**Comment by willdurand** [comment]
Yes :)

**Comment by willdurand** [comment]
Awesom!e

**Comment by jbrooksuk** [comment]
Done - that was accidental I'm afraid. Originally the view was only for showing support. It needs renaming to `footer` now.

**Comment by jbrooksuk** [comment]
Also done.

**Comment by willdurand** [comment]
ah I see. Cool :heart:
