### ISSUE TITLE
Feature Request: integrate Spellchecker

### ISSUE THREAD

**Issue by dschwabeS11** [CachetHQ/Cachet#3050]
Currently there is no Spellchecker integrated. It would be nice if admins could activate spell checking for posts. This would save time and raise the overwall quality of posts.

A button could appear on each "Description" box that would spellcheck the content on demand. This way only selected text would be send to external spellchecker services.

https://spellcheckplus.com/ 
https://www.grammarly.com/

Thanks!

**Comment by jbrooksuk** [comment]
Grammarly is a browser extension, so we couldn't implement that. We'd need to add a plugin to CodeMirror.
