### ISSUE TITLE
Translation update

### ISSUE THREAD

**Issue by shuichiro-makigaki** [CachetHQ/Cachet#3051]
I (and maybe others) added translations recently. Could you merge these updates from crowdin?

**Comment by jbrooksuk** [comment]
Sorry! I'll do this now.

**Comment by shuichiro-makigaki** [comment]
Could you update translations?

**Comment by jbrooksuk** [comment]
Please see https://github.com/CachetHQ/Cachet/issues/3088 where I'm calling for translation managers, so that I can pass this on to the people who know the languages :)

**Comment by jbrooksuk** [comment]
Closing this to replace with #3088.
