### ISSUE TITLE
docs.cachethq.io takes a lot of time to load

### ISSUE THREAD

**Issue by DoNotSpamPls** [CachetHQ/Cachet#3055]
Sometimes it even returns that the server is offline and shows the "Always Online" cloudflare cache instead.

**Comment by vstock28021** [comment]
I'll confirm this and I'm on GB Fiber in 2 locations and 10GB Fiber in the third.

**Comment by jbrooksuk** [comment]
It looks like Readme.io may have been down during this time. Sorry!

**Comment by vstock28021** [comment]
Still having long load time in the realm of 50 seconds per load. As you can see from the Firefox Screenshot below.
![docs cachethq io-loadingtime](https://user-images.githubusercontent.com/7843257/42416725-f0ee9962-8244-11e8-98c3-5c9e69b42613.png)
