### ISSUE TITLE
incident/maintenance message not using formatting

### ISSUE THREAD

**Issue by codeagencybe** [CachetHQ/Cachet#3056]
Hello,

When I create a new incident (or a scheduled maintenance), it puts all my text after each other, making it difficult to read. 
I type 4 lines, with a BR at the end but still it paste everything in a single line. 
I also tried adding HTML <br> and </br> but nothing is working. 

Anybody knows why and where to fix please?

**Comment by codeagencybe** [comment]
I'm on version 2.3.14-dev

**Comment by jbrooksuk** [comment]
This should be fixed in v2.4 😃
