### ISSUE TITLE
Markdown in Component Description

### ISSUE THREAD

**Issue by vstock28021** [CachetHQ/Cachet#3057]
Would it be possible to have the description field for components support markdown? I'd like to be able to list the individual pieces of the component via bullet points. Thanks!

**Comment by jbrooksuk** [comment]
I don’t see why not! 

This would be a good first PR for someone :)

**Comment by jbrooksuk** [comment]
Actually, this doesn't make sense in the current design because the layout puts the description into a tooltip.

If we change this in the new design so that descriptions are always visible, then we'll account for this.
