### ISSUE TITLE
SSL Problems

### ISSUE THREAD

**Issue by vstock28021** [CachetHQ/Cachet#3058]
I have OpenLiteSpeed acting as a reverse proxy for all of my docker web apps with LetsEncrypt. In order to make this script function without editing the php file for allowed hosts I used OpenLiteSpeed's mod rewrite functionality which is similar to Apache. I'm posting this here as I don't know git well enough to do a pull/merge or what ever it is. However I'm hoping that in the future this little bit of code will help people. While this isn't probably the preferred method for this, I noticed a few posts about it when I was going through the list of issues. I'm sure someone could take this and modify it to work out of the box with most web servers.

``rewriteCond %{HTTPS} !on``
``rewriteRule ^(.*)$ https://%{SERVER_NAME}%{REQUEST_URI} [R,L]
RewriteRule ^/(.*)$ http://Cachet-Proxy/$1 [P,E=Proxy-Host:status.carolinashost.com]``

**Comment by jbrooksuk** [comment]
Thanks for this! You can suggest changes to our Docs at [CachetHQ/Docs](/CachetHQ/Docs).
