### ISSUE TITLE
Issue with cachet 2.3 phpunit testing

### ISSUE THREAD

**Issue by tejaswivinod** [CachetHQ/Cachet#3061]
hello, 
I have been trying to setup Cachet 2.3 with homestead vagrant box. While running phpunit it get below issue.

There was 1 failure:

1) CachetHQ\Tests\Cachet\AnalysisTest::testReferences with data set "/home/vagrant/cachet/bootstrap/cache/compiled.php" (SplFileInfo Object ())
Expected Zend\Diactoros\Response to exist.
Failed asserting that false is true.

Screenshot:
/home/vagrant/cachet/vendor/alt-three/testbench/src/AnalysisTrait.php:38
<img width="591" alt="screen shot 2018-06-01 at 3 08 23 pm" src="https://user-images.githubusercontent.com/24422623/40858853-b3dd6aa2-65ad-11e8-9276-56b13729eeb3.png">

Steps followed:
1. composer install --no-interaction --no-scripts --prefer-source
2. vendor/bin/phpunit --stop-on-failure

I have also tried installing zend framework manually, but it leads to another dependency failure 
e.g Expected Illuminate\Contracts\Validation\ValidationException to exist

Please let me know, what are the correct local setup I should have to run tests successfully.
Thanks

**Comment by jbrooksuk** [comment]
What version of PHP are you using?

**Comment by jbrooksuk** [comment]
Oh, I can see you're using PHP 7.2 - this isn't supported in Cachet yet.
