### ISSUE TITLE
Impossible to change url path

### ISSUE THREAD

**Issue by qlaffont-smiirl** [CachetHQ/Cachet#3063]
Hi everyone,
Actually I had my Cachet installation on http://localhost and i want to change to http://localhost/status/. I make the modification on .env file and make an app update (+ artisan down & up) and the CSS is not load because is still pointing to http://localhost.
How i can solve this ? 
Thanks

**Comment by jbrooksuk** [comment]
Cachet doesn’t support sub directories natively, sorry.
