### ISSUE TITLE
cant connect to API

### ISSUE THREAD

**Issue by Marcel40625** [CachetHQ/Cachet#3064]
Hey there, im using a tool to update my Components if they are down, but i changed now my server setup. the Cachet is on a VM behind NAT and only Port 80 & 443 are going through to the VM, now when i try to connect to the API via the domain i get an connection refused ... is the API using another Port?

urllib.error.URLError: <urlopen error [Errno 111] Connection refused>

when i use http://127.0.0.1 is the tools everything works fine, but the mail to the subcribers has than http://127.0.0.1 as links ....

**Comment by jbrooksuk** [comment]
Sorry @Marcel40625 this sounds more like a setup issue than a Cachet one. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Marcel40625** [comment]
is Cachet using any other ports? as 80 & 443(SSL) ?

**Comment by jbrooksuk** [comment]
It’ll be whatever you’ve configured in your web server.
