### ISSUE TITLE
SQLite setup issue

### ISSUE THREAD

**Issue by imranh2** [CachetHQ/Cachet#3065]
When running a test cachet instance using sqlite as the DB, on the page for creation of the admin account in the inital setup I'm met with an error.

From the logs here's the problem:

`Next Illuminate\Database\QueryException: SQLSTATE[23000]: Integrity constraint violation: 19 UNIQUE constraint failed: users.username (SQL: insert into "users" ("username", "email", "password", "level", "api_key", "updated_at", "created_at") values (admin, admin@example.com, ypynoW0HM0b7gTbjsJTekuLrcX4sAhdGSh59Z.mP/Am.0aeo6eEJq, 1, jCxelms6uqvjCCVCr57V, 2018-06-08 15:50:20, 2018-06-08 15:50:20)) in /var/www/Cachet/vendor/laravel/framework/src/Illuminate/Database/Connection.php:713`

Also with the tag 2.3.14 I had to do `php artisan migrate` and then `php artisan app:install` to get it going.

**Comment by imranh2** [comment]
Right it was various permission problems all adding up.

Needed to make sure write privs were given to the db file (duh), also need to adjust write privs to the .env file.

I would click next, it'd insert the user into the db, fail to write to .env then when I clicked it again I got the above error that basically says, you already made a user.

**Comment by jbrooksuk** [comment]
I’m glad you’re sorted 👍🏻
