### ISSUE TITLE
I will appreciate a sample sql data

### ISSUE THREAD

**Issue by juliustip** [CachetHQ/Cachet#3067]
Any help with the latest cachet sql file?

**Comment by jbrooksuk** [comment]
Are you after the database structure? If so, make sure your `.env` file has the correct `DB_*` values and then run `php artisan migrate`.

**Comment by juliustip** [comment]
Keep getting 

> mysqldump: Got error: 2002: Can't connect to local MySQL server through socket '/tmp/mysql.sock' (2) when trying to connect 

Also getting:
 

> [PDOException]
>   SQLSTATE[HY000] [2002] No such file or directory

Could you just assist in uploading the latest one to upcloud?

**Comment by jbrooksuk** [comment]
That’s an issue with your configuration. We don’t supply the DB file.
