### ISSUE TITLE
Monitor Appliance

### ISSUE THREAD

**Issue by JujuBois** [CachetHQ/Cachet#3070]
Hello

I use "cachet" with "cachet-url-monitor" just perfect :)

I would like to know if it is possible to ping a server or appilance (switch, firewall ...)

Is there a free solution or module;)

Thank you

**Comment by jbrooksuk** [comment]
You'll need to open an issue with cachet-url-monitor as Cachet itself doesn't do that.

**Comment by JujuBois** [comment]
Ok thank you, but you do not know another module that can do it? nobody returns this type of information in "Cahet"

**Comment by jbrooksuk** [comment]
Not off the top of my head, but have a read of https://docs.cachethq.io/docs/addons
