### ISSUE TITLE
Allow people to signup to email notifications NOT showing

### ISSUE THREAD

**Issue by codeagencybe** [CachetHQ/Cachet#3073]
Hello

The feature "Allow people to signup to email notifications" is not working on my end. 
I have the option activated, but it does not show that button like in your demo. 
Using version 2.3.14

My settings
http://sharing.codeagency.be/2r001g0m0H40
![image 2018-06-14 at 10 52 58 am](https://user-images.githubusercontent.com/7568546/41401853-2d09b8d2-6fc1-11e8-84c3-377610f73d2c.png)

My result
** Yes I also tried not logging in, the button doesn't show no matter logged in or not. 
http://sharing.codeagency.be/1Y1s3i1D2b2N
![image 2018-06-14 at 10 55 47 am](https://user-images.githubusercontent.com/7568546/41402014-860e03a2-6fc1-11e8-808d-7b0b272c1f6a.png)

And it should look like this
this part is MISSING, even while the option is checked/activated
http://sharing.codeagency.be/2d2d0c1b1G2A
![image 2018-06-14 at 10 51 33 am](https://user-images.githubusercontent.com/7568546/41401770-fa68f19a-6fc0-11e8-8d02-6ceafef35ffc.png)

I don't have any errors showing anywhere, so I'm clueless why I don't have that subscribe button.

**Comment by jbrooksuk** [comment]
You also need to configure mail settings before this will show.
