### ISSUE TITLE
subscribers api not working

### ISSUE THREAD

**Issue by 01A4093** [CachetHQ/Cachet#3079]
When i add subscribers via api call the mapping between the service and subscriber is not working, it is display correctly in the backend. The probleme is that all subscibers resived a email, also when they did not subsribed the service.
When i add a subsciber via the webfrontend the mapping is working correctly.

**MAIL.LOG:**
Jun 15 12:40:52 SWEBKO15 postfix/qmgr[1664]: 4321660506: from=<status@test.com>, size=13250, nrcpt=1 (queue active)
Jun 15 12:41:03 SWEBKO15 postfix/smtp[5157]: 3A1FF5F882: to=<employees@test.com>, relay=10.0.0.80[10.0.0.80]:25, delay=11, delays=0.01/0.01/0.09/11, dsn=2.6.0, status=sent (250 2.6.0 <25fbe74baf1fa781a32c344626636077@swift.generated> [InternalId=53838808] Queued mail for delivery)
Jun 15 12:41:03 SWEBKO15 postfix/qmgr[1664]: 3A1FF5F882: removed
Jun 15 12:41:03 SWEBKO15 postfix/smtp[5161]: 4321660506: to=<admin1@test.com>, relay=10.0.0.80[10.0.0.80]:25, delay=11, delays=0.01/0.01/0.08/11, dsn=2.6.0, status=sent (250 2.6.0 <1189dbd356a8ba3d1c4d3f68cde382de@swift.generated> [InternalId=53838809] Queued mail for delivery)
Jun 15 12:41:03 SWEBKO15 postfix/qmgr[1664]: 4321660506: removed
Jun 15 12:41:04 SWEBKO15 postfix/smtp[5153]: 311475F819: to=<admin2@test.com>, relay=10.0.0.80[10.0.0.80]:25, delay=12, delays=0.02/0.01/0.1/12, dsn=2.6.0, status=sent (250 2.6.0 <698eb34f3315c87b3382add2e7e7c006@swift.generated> [InternalId=53838813] Queued mail for delivery)
Jun 15 12:41:04 SWEBKO15 postfix/qmgr[1664]: 311475F819: removed

![subscribers](https://user-images.githubusercontent.com/30403495/41464858-0bba03e0-709c-11e8-8767-eb5834e00956.png)

**Comment by jbrooksuk** [comment]
Thanks for reporting this @01A4093, can you just clarify who is receiving the emails and who isn't please?

**Comment by 01A4093** [comment]
hi @jbrooksuk, every subscriber is reciving emails not only the subscribe of the service.

**Comment by jbrooksuk** [comment]
@01A4093 I see! What version are you using?

**Comment by 01A4093** [comment]
@jbrooksuk i´m using version 2.3.11

**Comment by jbrooksuk** [comment]
Apologies @01A4093, this was fixed in 2.4
