### ISSUE TITLE
Route is Not Working

### ISSUE THREAD

**Issue by normalusr** [CachetHQ/Cachet#3081]
Hi, 
I followed all documentation, and there is no error. But, when i try to setup from browser, .css .js is not working (404 not found). Here is the [image](https://ibb.co/d7Evhy).

I suspicious laravel route (.htaccess) is not working. 

I am using VPS with cPanel installed. So, `mod_rewrite` is enabled by default, and `AllowOverride All`
is setup. 

How can i resolve this issue ? 

Thanks in advance

**Comment by normalusr** [comment]
[RESOLVED]

I only need to set root document to `/[doc_root]/[public_html]/public`

Everyting works properly :)

Thanks

**Comment by jbrooksuk** [comment]
🎉

**Comment by shokhruh** [comment]
How is the changes to the folder path done?


/[doc_root]/[public_html]/public
