### ISSUE TITLE
Very Annoying Behaviour

### ISSUE THREAD

**Issue by barreeeiroo** [CachetHQ/Cachet#3082]
When you re-order any component, a notification update of ALL components is sent to ALL subscribers
This is very annoying, as it bothers users a lot and it costs money due to SMTP email providers
And what's more, the component order is not updated until all emails are sent

Is there any way to fix this?

**Comment by jbrooksuk** [comment]
I agree, this really is annoying and completely unexpected. Re-ordering should not trigger this alert. I'll take a look.

**Comment by jbrooksuk** [comment]
Can you confirm which version of Cachet you're using.

**Comment by barreeeiroo** [comment]
@jbrooksuk Is safe to use the 2.4 branch?
Or it's better to wait for a release? And if so, please say one date 😅

**Comment by jbrooksuk** [comment]
2.4 is changing a lot at the moment so I’d hold off if you’re not prepared :)

**Comment by barreeeiroo** [comment]
@jbrooksuk **Any estimated release date?**
We are using Cachet at status.makeroid.io, and on Friday we relaunched our service, with peaks of +5k users connected at the same time, and we need a working status page

**Comment by jbrooksuk** [comment]
No release date yet.

2.4 will work for you currently, but it's changing often :)

**Comment by barreeeiroo** [comment]
Any guide to migrate to 2.4? 😅

On Jun 25, 2018 09:47, "James Brooks" <notifications@github.com> wrote:

No release date yet.

2.4 will work for you currently, but it's changing often :)

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/CachetHQ/Cachet/issues/3082#issuecomment-399862753>,
or mute
the thread

**Comment by barreeeiroo** [comment]
Hey @jbrooksuk 
Is this commit added on v2.3.15?
