### ISSUE TITLE
Call for translation managers!

### ISSUE THREAD

**Issue by jbrooksuk** [CachetHQ/Cachet#3088]
We all know that translations are behind and lacking accuracy so I'm looking for volunteers to maintain and manage translations at https://translate.cachethq.io

If you've submitted translations previously, please let me know your CrowdIn username and the language you'd like to manage, then we'll get you setup.

**Comment by jbrooksuk** [comment]
I believe I now have CrowdIn working automatically through a new bot account, so newly approved translations should be automatically sent into a PR.

**Comment by ruiztulio** [comment]
@jbrooksuk here?

if so, lang: spanish, user: ruiztulio

**Comment by jbrooksuk** [comment]
Thanks @ruiztulio! I’ve set you to be a proof reader for Spanish. Could you see what happens?

**Comment by shuichiro-makigaki** [comment]
Sounds good!

Lang: Japanese, User: shuichiro-makigaki

**Comment by jbrooksuk** [comment]
You're now a proof-reader for Japanese, @shuichiro-makigaki - thank you kindly!

**Comment by shuichiro-makigaki** [comment]
Thanks! Approve button appears now.

> I believe I now have CrowdIn working automatically through a new bot account, so newly approved translations should be automatically sent into a PR.

How does the bot work? Daily or weekly cron?

**Comment by jbrooksuk** [comment]
I’m not really sure, to be honest. I think it updates every hour or something.

**Comment by shuichiro-makigaki** [comment]
Works on #3108. Looks good!
I think CI should ignore `l10n_*` branches. TravisCI may encounter overload.

Or, it's nice if we can change the interval. But, indeed, I could not find any documents about that...

**Comment by jbrooksuk** [comment]
We're now ignoring the branch in bad4cac9f534ee8d0d0b49f66b2a8f7fcddec069

**Comment by kmartin26** [comment]
I can help if you want 😄 

Lang: french, user: kmartin26

**Comment by ruiztulio** [comment]
@jbrooksuk Now I can see the approve button.

@shuichiro-makigaki if in the commit message comes ["[ci skip]"](https://docs.travis-ci.com/user/customizing-the-build#Skipping-a-build) the ci will ignore it

**Comment by jbrooksuk** [comment]
@kmartin26 you're now a proof reader :)

**Comment by kmartin26** [comment]
@jbrooksuk thanks !

**Comment by anthonybocci** [comment]
My translations were done with my company account (uxen-ab) so with my personal account (anthonybocci) I've not submitted anything yet. Once it will be done, I could help.

Language: French.

**Comment by jbrooksuk** [comment]
@anthonybocci can you signup with http://translate.cachethq.io/project/cachet/invite please?

**Comment by anthonybocci** [comment]
@jbrooksuk I've clicked on your link, I already have an account with my username anthonybocci.

**Comment by jbrooksuk** [comment]
Do you need to join the project?

**Comment by anthonybocci** [comment]
@jbrooksuk Crowdin says I already joined the project, so I'm already in. But I haven't submitted any translation with this account yet, is it because of that?

**Comment by jbrooksuk** [comment]
Possibly!

**Comment by Atriusftw** [comment]
I'd be happy to help with translations.

Language: Norwegian
Username: Atrius

**Comment by jbrooksuk** [comment]
Great, thanks @Atriusftw!

**Comment by jbrooksuk** [comment]
@Atriusftw I've set you to a proofreader.

**Comment by Atriusftw** [comment]
Sounds good. I'll slowly begin going through all translated strings :-)

**Comment by jbrooksuk** [comment]
Great thanks mate!

**Comment by hensur** [comment]
I'd like to help, I just created a crowdin account using github.

Language: German
Username: hensur (like here)

**Comment by jbrooksuk** [comment]
That's awesome, thank you @hensur. I'll add you now.

**Comment by VictorAvelar** [comment]
I'd like to help, I just created a crowdin account using github.

Language: Spanish
Username: VictorAvelar

**Comment by jbrooksuk** [comment]
That’s great, thanks! I’ll add you shortly :)

**Comment by jbrooksuk** [comment]
You need to signup to the project at http://translate.cachethq.io/project/cachet/invite

**Comment by SevenCode** [comment]
I'd like to help, I just created a crowdin account using github.

Language: German
Username: sevencode

**Comment by AchdukeNavaron** [comment]
I'd like to help too.
If you are still looking for geman translators just add me.

Language: German
Username: ArchdukeNavaron

**Comment by ArchdukeNavaron** [comment]
I'd like to help too.
If you are still looking for geman translators just add me.

Language: German
Username: ArchdukeNavaron

**Comment by onovaes** [comment]
If you are still looking for portuguese translators just add me.

Language: Portuguese
Username: onovaes

**Comment by jbrooksuk** [comment]
Awesome! I'll add you now.

**Comment by jbrooksuk** [comment]
You'll need to signup to the project at http://translate.cachethq.io/project/cachet/invite

**Comment by jbrooksuk** [comment]
You can also signup to be a Proofreader at http://translate.cachethq.io/project/cachet/invite?d=m6j60535n427t683i3f3n4k4

**Comment by ArchdukeNavaron** [comment]
@jbrooksuk Maybe you can assign me as Manager again. You did that and in the same minute you demoted me again. 

Language: German
Username: ArchdukeNavaron

**Comment by jbrooksuk** [comment]
Apologies! I’ll sort this once I’m home.

**Comment by jbrooksuk** [comment]
@ArchdukeNavaron you should now be able to proof-read German translations.

**Comment by ArchdukeNavaron** [comment]
@jbrooksuk thanks, it is working now. Next question. Are we allowed to use letters like ä? Or do we have to translate them with replacements?

**Comment by TakeMeNL** [comment]
Language: Dutch (native), English
Username: TakeMeNL

**Comment by jbrooksuk** [comment]
> @jbrooksuk thanks, it is working now. Next question. Are we allowed to use letters like ä? Or do we have to translate them with replacements?

@ArchdukeNavaron please feel free to use characters from the language. The more native, the better.

**Comment by jbrooksuk** [comment]
@TakeMeNL you're now a proofreader for Dutch.

**Comment by jbrooksuk** [comment]
@JordyvanDortmont you're now also a proofreader for Dutch.

**Comment by craftbyte** [comment]
@jbrooksuk Could you create Slovenian and add me as manager
Username: jensterleanze

**Comment by sbaatar** [comment]
New language: Mongolian
Username: sbaatar

**Comment by jbrooksuk** [comment]
@craftbyte and @sbaatar you're now proofreaders for your requested languages.

**Comment by BaileyJM02** [comment]
I can proof read English.

**Comment by jbrooksuk** [comment]
@BaileyJM02 done! Thanks :)

**Comment by brunowdev** [comment]
Hi, I can help with Brazilian Portuguese (if you want), I've also suggested a few translations on version 2.4.

Username: brunowdev

**Comment by jbrooksuk** [comment]
@brunowdev done!

**Comment by gbaudoin** [comment]
Hello ! It looks like the French translations need some help.

Lang: French, User: gbaudoin

**Comment by MartinHynek** [comment]
Good idea.
Lang: Czech, User: martascz

**Comment by MartinHynek** [comment]
> Good idea.
> Lang: Czech, User: martascz

any updates @jbrooksuk ?

**Comment by jbrooksuk** [comment]
@gbaudoin and @martascz I've assigned you to your requested languages. Thanks!

**Comment by TheSlow** [comment]
Hello, I would like to help you for translating Cachet to Turkish. As I can see from Crowdin there are a lot of translation mistakes.

My username is Dopaa, also thank you!

**Comment by drummerschlumpf** [comment]
Hello, I Can Help with German

Username: Drummerschlumpf

**Comment by gautamkrishnar** [comment]
@jbrooksuk would like to contribute malayalam. Username: gautamkrishnar

**Comment by sgteoks** [comment]
@jbrooksuk , i can help with Chinese Traditional. Username: teoks

**Comment by holiiveira** [comment]
@jbrooksuk I can help with Portuguese, Brazilian translation, username: holiiveira
