### ISSUE TITLE
Refactor all emails to use Markdown views

### ISSUE THREAD

**Issue by jbrooksuk** [CachetHQ/Cachet#3101]
Replaces https://github.com/CachetHQ/Cachet/issues/3015

---

- Every email should be Markdown based as this makes it very easy to implement any dynamically generated Markdown content.
- Every email should contain **Unsubscribe** and **Manage subscription** links (this should be a partial).

This should be looked at as soon as https://github.com/CachetHQ/Cachet/pull/3100 is merged. It's even more important now that GDPR is live.

**Comment by nstapelbroek** [comment]
After merging #3100 , these notifications need markdown support:
- Notifications/Component/ComponentStatusChangedNotification.php
- Notifications/IncidentUpdate/IncidentUpdatedNotification.php
- Notifications/Schedule/NewScheduleNotification.php
- Notifications/Subscriber/VerifySubscriptionNotification.php
- Notifications/System/SystemTestNotification.php
- Notifications/User/InviteUserNotification.php

**Comment by JamesWilson19947** [comment]
@nstapelbroek any ideas of when this will be implemented or if I can even do this?

It's basically the primary reason we cannot use it as a company, because without the consistent unsubscribe button on the emails, it's not GDPR compliant! :)

**Comment by JamesWilson19947** [comment]
I'm seriously cool with helping out with this work if you need! 👍 
I just don't know exactly how you want the markdown example I made this for the update notifications:

In IncidentUpdatedNotification.php
```php
return (new MailMessage())
                    ->subject(trans('notifications.incident.update.mail.subject'))
                    ->markdown('notifications.incident.update', [
                        'incident'               => $this->update->incident,
                        'content'                => $content,
                        'actionText'             => trans('notifications.incident.new.mail.action'),
                        'actionUrl'              => cachet_route('incident', [$this->update->incident]),
                        'incidentName'           => $this->update->incident->name,
                        'newStatus'              => $this->update->human_status,
                        'unsubscribeText'        => trans('cachet.subscriber.unsubscribe'),
                        'unsubscribeUrl'         => cachet_route('subscribe.unsubscribe', $notifiable->verify_code),
                        'manageSubscriptionText' => trans('cachet.subscriber.manage_subscription'),
                        'manageSubscriptionUrl'  => cachet_route('subscribe.manage', $notifiable->verify_code),
                    ]);
```

update.blade.php

```blade
@component('mail::message')
# {{ trans('notifications.incident.update.mail.title', ['name' => $incidentName, 'new_status' => $newStatus])  }}

{{ $incident->message }}

Thanks,<br>
{{ Config::get('setting.app_name') }}

@include('notifications.partials.subscription')

@endcomponent
```

**Comment by jbrooksuk** [comment]
Fixed in https://github.com/CachetHQ/Cachet/pull/3270
