### ISSUE TITLE
Refactor Subscriber Flow

### ISSUE THREAD

**Issue by jbrooksuk** [CachetHQ/Cachet#3102]
The subscriber flow is currently completely wrong and actually a security vulnerability.

> **All emails should be sent with the `List-Unsubscribe` header**.

A decent flow looks like this for new users:

1. A user enters their email address to subscribe.
2. Fire a "Confirm your subscription" email.
3. Redirect the user back to the status page, notifying them that they'll receive an email shortly.
4. The user clicks the link and is taken to the "Manage your subscription" page, importantly with a verified URL.
5. Any subsequent emails to this user should include **Unsubscribe** and **Manage your subscription** links as per #3101 

The flow for people who are already subscribed:

1. A user enters their email address to subscribe.
2. Fire a "Manage your subscription" email.
3. Redirect the user back to the status page, notifying them that an email has been sent to their inbox to manage their subscription.
4. The user clicks the link and is taken to the "Manage your subscription" page, importantly with a verified URL.

If anyone has any thoughts/ideas on how we can improve these workflows, please let me know.

**Comment by dschwabeS11** [comment]
Let's do it!

It would also be nice if users can subscribe to component groups rather than selecting each component alone. If there are a lot of components it uncomfortable for users to do this and hence they might not do it at all (bad user experience). :)
