### ISSUE TITLE
New design

### ISSUE THREAD

**Issue by jbrooksuk** [CachetHQ/Cachet#3111]
Sketch file for the new design: https://nofile.io/f/CocpvKYzcZs/status-page.sketch

What is within these design files **does not** need to be taken as gospel however, the layout makes perfect sense.

[Cachet.pdf](https://github.com/CachetHQ/Cachet/files/2112715/Cachet.pdf)

Firstly, we need to discuss any potential changes that may need to be made or accounted for. After we've agreed on any changes, I'd really appreciate someone taking the time to implement the design as there are many other things that need implementing.

Obviously, a design change on this proportion will result in backwards incompatibilities so now may be the time we look at upgrading Bootstrap or using a different framework. As I've said in other issues, I'm loving Tailwind and we could use it to create a component framework that can still be configured or themed as Cachet currently allows.

**Comment by jbrooksuk** [comment]
![incident history](https://user-images.githubusercontent.com/246103/41558152-d0e51e28-7337-11e8-98d5-a83069e56415.png)
![single incident custom](https://user-images.githubusercontent.com/246103/41558153-d1031ca2-7337-11e8-9e6b-02f31062865a.png)
![single incident](https://user-images.githubusercontent.com/246103/41558154-d11f8450-7337-11e8-97d9-3c9f748c0c22.png)
![status custom branding](https://user-images.githubusercontent.com/246103/41558155-d136f0c2-7337-11e8-9394-ccbcdc0ee3d2.png)
![status](https://user-images.githubusercontent.com/246103/41558156-d156b5c4-7337-11e8-8d62-03801f4c3d94.png)

**Comment by jbrooksuk** [comment]
Note that some of these exports show what Cachet could look like with extra styling.

**Comment by MattBSG** [comment]
Any examples of metrics being used in the new design?

**Comment by jbrooksuk** [comment]
@MattBSG afraid not, this is all I have. I imagine it'd look relatively similar to how they do currently, but with a bit of polish behind them.

**Comment by shuichiro-makigaki** [comment]
Looks good design!

As for detailed implementation, we should employ HTML5 philosophy such as `<section>` and `<article>` tags for:

> that can still be configured or themed as Cachet currently allows.

Current v2.4 HTML is not structured well honestly.

**Comment by franzliedke** [comment]
As I've mentioned elsewhere, IMO Tailwind (and any other framework based on the "Atomic CSS" approach, for that matter) is not suited for creating themable *layouts* (which, I'd imagine, is a main point in any theme that people might create).

Using Tailwind for component styling is okay, I guess, but it will make life hard in for tweaking layout things (such as element positioning or order) in a theme (unless you want to allow themes to overwrite each component's HTML, which is yet another can of worms).

Nothing against Tailwind, if people like that, but it has its downsides when it comes to things like this.

**Comment by jbrooksuk** [comment]
@franzliedke are you thinking of using Tailwind with the individual classes? My thinking would be that we'd create individual components/structure without applying colours, instead do what we do currently and create dynamic classes for colours.

**Comment by franzliedke** [comment]
Basically, I am discouraging using it for layout, that's all. ;)

**Comment by anthonybocci** [comment]
I can help for the HTML 5 structure, but I'm not one of these CSS artist masters.

About themes, I think it's important that every person who installs Cachet can override the theme easily if needed.

**Comment by jbrooksuk** [comment]
I've been thinking about themes as well @anthonybocci!

I think once we're upgraded to Laravel 5.6 we get access to the automatic service provider support. What this means is that we could develop a theme system which looks for all of the registered themes and have them installed with `composer require cachethq/theme-dark` or whatever.

Technically, this means that themes could use whatever framework they wanted.

**Comment by anthonybocci** [comment]
It would be great @jbrooksuk! Doing so we could use the theme we want, either dark, light, or whatever else.
Does this mean all the views would move into the theme?

**Comment by jbrooksuk** [comment]
Yup! Every theme would auto-register and would contain the Blade templates as well, we’d just need to provide the variables to the view.

**Comment by anthonybocci** [comment]
That's interesting! Every company could have its own Cachet.

So, before doing the new design we need to update Laravel 5.6 right? A roadmap would be useful ;)

**Comment by jbrooksuk** [comment]
#3137 starts to solve this. I need to write some documentation on the basics of themes and then implement the new design with the required system changes, then if you don't like Tailwind, make a theme :)

**Comment by franzliedke** [comment]
And replicate all the markup / logic? Meh... :wink:

**Comment by jbrooksuk** [comment]
@franzliedke as I go about converting the new theme into a theme package, the core Cachet code should be improved to make it easier to get the data you need. In theory, you should be able to display it however you want.

**Comment by jbrooksuk** [comment]
@franzliedke yeah, so basically you'd be able to fork the official theme (which will live at https://github.com/CachetHQ/Official-Theme) and make the changes you'd like to make.

**Comment by InsaneSplash** [comment]
This will be great as I tried to run the site with a dark background, white text, but there a parts which change in areas they shouldn't and not in others... :)

**Comment by chrissie1234** [comment]
When someone has time to make a merge request for this, it would be nice. I will reward the creator that's making this theme into Cachet

**Comment by rayterrill** [comment]
It would be awesome if we could change around how components are laid out on the page as part of the design work/theming. I've currently modified /resources/views/index.blade.php to move the scheduled maintenance portion above the statuses - probably a big no-no in terms of staying consistent with builds, but it accomplished something we'd like to have.

**Comment by jbrooksuk** [comment]
@rayterrill I've been working on the ability to add custom themes to Cachet. I'm still in the very long process of implementing the design though. I could really do with some help from someone to make that happen **plus** the dashboard.

**Comment by rayterrill** [comment]
@jbrooksuk I took a look at the codebase, and it's been a long time since I did any real PHP so it's a little out of my league at the moment, but I'd love to help in any way I can. Happy to re-learn on the fly if you'll have me, mate!

**Comment by jbrooksuk** [comment]
No worries. To make this entire change work, we basically need to completely rip out the current design and start fresh. This will likely require a lot of changes to the backend to get data in the right format also.

**Comment by ojdon** [comment]
Is there anyone working on an active fork? If not, I'll [fork the current release](https://github.com/ojdon/Cachet) and start work on moving Cachet to Bootstrap 4, as it's currently based off bootstrap-sass (The Sass fork of Bootstrap 3). 

Once migrated, I'll work towards the new design.

**Comment by jbrooksuk** [comment]
@ojdon not that I'm aware of. If you're happy implementing the changes, that'd be great! I can definitely see the advantage of migrating to Bootstrap 4 first.

**Comment by jasoryeh** [comment]
Just verifying... are all the fonts Raleway?

**Comment by jbrooksuk** [comment]
Question for @ojdon :)

**Comment by ojdon** [comment]
@jasoryeh Yup. It's all Raleway. 

However, ["Material-Design-Iconic-Font"](https://zavoloklom.github.io/material-design-iconic-font/) is the icon font in use.

**Comment by jasoryeh** [comment]
Hey @ojdon I've been working on a kind of html outline that tried to clone the design on the proposed design, but it doesn't use bootstrap...
![image](https://user-images.githubusercontent.com/13290941/60224941-9745c280-9839-11e9-8af8-77188a3b520b.png)

**Comment by duysmil** [comment]
when this desing is released?

**Comment by ojdon** [comment]
@duysmil The first step is to update the frontend to Bootstrap 4 from Bootstrap 3. You can find my progress here: https://github.com/ojdon/Cachet/tree/updates/bootstrap 

When I PR and if it gets accepted, then I'll work towards the new design.

**Comment by Korthoutrody** [comment]
How will the re-design work? Is it one person creating the whole thing or is it split in component work?

**Comment by duysmil** [comment]
> @duysmil The first step is to update the frontend to Bootstrap 4 from Bootstrap 3. You can find my progress here: https://github.com/ojdon/Cachet/tree/updates/bootstrap
> 
> When I PR and if it gets accepted, then I'll work towards the new design.

Thanks.

**Comment by Sphiinx** [comment]
Would love a re-design

**Comment by GameMaster2030** [comment]
Is a re-design still in the works or has it been canceled? I would love to see it

**Comment by GameMaster2030** [comment]
@jbrooksuk Could you answer the above question?

**Comment by jbrooksuk** [comment]
It's still something we'll be doing. The problem I keep facing is that we need to rewrite **a lot** of code to make this work properly.

In doing so, I think we'll end up breaking the current 2.4 branch because there will be:

- Design changes
- Translation changes (I would want to make https://github.com/CachetHQ/Cachet/issues/3726 a part of this)
- The dashboard also needs updating in sync with the frontend (I don't want to be using Bootstrap and Tailwind for example). I also don't want to stick with Bootstrap at this point.

**Comment by GameMaster2030** [comment]
Ok, thanks for letting us know that it's still planned.

**Comment by ShadowPauler** [comment]
@jbrooksuk Would you like me to create an exact replica of this style however for the admin dashboard for better clarity on the idea? I love doing UI design ^~^

**Comment by jbrooksuk** [comment]
Absolutely! That'd be brilliant.

I'm very keen on using Tailwind for the re-design if someone does want to implement this.

**Comment by ShadowPauler** [comment]
So I can create the mockup, however I cannot implement the UI/UX. I would really like to help this project, but it might take me a bit to pickup CSS. If it comes down to I have to for this to not be a dead community project, I'll do it so that people can be satisfied with this open source software.

**Comment by ShadowPauler** [comment]
@jbrooksuk Tell exactly everything you need for the front-end. I won't be able to help with the back-end though.

**Comment by ShadowPauler** [comment]
You could use this to speed up production if you want. You are able apply your own JS, HTML, and CSS with an easy block editor called GrapeJS @jbrooksuk 

https://grapesjs.com/

**Comment by dudeisbrendan03** [comment]
Moved from statusfy to cachet because statusfy can't do metrics, but cachet is ugly 😔

**Comment by ChrisvanChip** [comment]
Time to copy their design.

**Comment by KaKi87** [comment]
@jbrooksuk Why did you close this while it hasn't yet been implemented ? Thanks

**Comment by jbrooksuk** [comment]
Thank you for your input on Cachet 2.x. We are shifting our attention and resources to Cachet 3.x and will no longer be supporting the 2.x version. If your feedback or issue is relevant to the 3.x series, we encourage you to engage with the new branch.

For more information on the Cachet rebuild and our plans for 3.x, you can read the announcement https://github.com/CachetHQ/Cachet/discussions/4342.

We appreciate your understanding and look forward to your contributions to the new version.

**Comment by KaKi87** [comment]
Well, I do want a dark theme for Cachet v3. Thanks

**Comment by jbrooksuk** [comment]
Consider it done as part of the new UI 😉
