### ISSUE TITLE
Status page - pagination doesn't work

### ISSUE THREAD

**Issue by uxen-ab** [CachetHQ/Cachet#3117]
When viewing the previous incidents on a status page, the date is not updated.
I means if I'm viewing https://status.mysite.com/?start_date=2017-12-12 the button "Previous" should lead to the previous incidents that occured in December 2017.

The date in the "previous" buttons should be based on the `$_GET['start_date']` if it exists, but it seems only the current date is used.

Cachet version 2.4
Commit number b20461fe89f71ebc207f72389c2ec8f84226c4c4

**Comment by jbrooksuk** [comment]
Does https://github.com/CachetHQ/Cachet/issues/3035 fix this?

**Comment by jbrooksuk** [comment]
Closed by 335c6f4d500f77c85459ae88b35775d02c218d6f
