### ISSUE TITLE
php artisan app:install fails, "could not find driver"

### ISSUE THREAD

**Issue by oz42** [CachetHQ/Cachet#3118]
It says "could not find driver" on CentOS 7.4 machine. Something is missing, I assume. The "installing cachet" documention is far too incomplete.

My PHP setup:

php72-php-common-7.2.7-1.el7.remi.x86_64
php72-php-7.2.7-1.el7.remi.x86_64
php72-php-json-7.2.7-1.el7.remi.x86_64
php72-php-cli-7.2.7-1.el7.remi.x86_64
php72-php-mysqlnd-7.2.7-1.el7.remi.x86_64
php72-php-opcache-7.2.7-1.el7.remi.x86_64
php72-runtime-1.0-1.el7.remi.x86_64
php72-1.0-1.el7.remi.x86_64
php72-php-pdo-7.2.7-1.el7.remi.x86_64
php72-php-pecl-mysql-1.0.0-0.17.20160812git230a828.el7.remi.x86_64

**Comment by jbrooksuk** [comment]
Can you share the `*_DRIVER` key/values from your `.env` file please.

**Comment by anthonybocci** [comment]
When submitting an issue, please provide us your `.env` (do not forget to remove the sensitive informations), your log file (located under `storage/logs`) and your Cachet version.
