### ISSUE TITLE
Many Actions Causing Error 500

### ISSUE THREAD

**Issue by DRST-github** [CachetHQ/Cachet#3119]
Hello,
I am using:
CentOS 7.5.1804
PostgreSQL 9.2.23
Apache 2.4.6
PHP 5.6
with SELinux disabled.

After installing Cachet successfully, I am seeing "Error 500" when:
-Modifying the "About this page" content.
-Submitting an incident.
-Adding a metric.

The error I get for all scenarios above, in the laravel log, is the following:

`[2018-06-18 18:37:09] production.CRITICAL: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'Call to undefined function League\CommonMark\mb_strcut()' in /var/www/Cachet/vend
or/league/commonmark/src/Cursor.php:349
Stack trace:
#0 {main} {"identification":{"id":"a8c3e5cf-e219-4547-bff2-69ebae019fc4"}}`

**Comment by jbrooksuk** [comment]
I believe your PHP installation was not installed with the `—mbstring` flag.

**Comment by DRST-github** [comment]
Thank you! That fixed the problem.
