### ISSUE TITLE
Option to remove case sensitive on login

### ISSUE THREAD

**Issue by RGiacometti** [CachetHQ/Cachet#3123]
Hello,

Can you please implement an option to remove case sensitive on login?

Thanks.

**Comment by jbrooksuk** [comment]
What’s case sensitive? The password?

**Comment by RGiacometti** [comment]
The login is case sensitive :

for user Admin :
- admin will not work
- aDmin will not work

for user REMI :
remi and Remi will not work

It can confuse some user when they try to login

Thanks

**Comment by jbrooksuk** [comment]
The only way to do this would be to create a mutator which lowercases the username on creation and then we lowercase the entered details before we attempt a login.

Personally, I think what we have is good security. What does everyone else thing?

**Comment by anthonybocci** [comment]
@jbrooksuk I think it's really better to keep the case sensitivity. It's more secure, "abc" is different from "aBc", we should keep the usernames as they are.

@RGiacometti What you could do is only type the username is lowercase, so you could be sure?

**Comment by jbrooksuk** [comment]
Agreed :) closing for now because I can’t see why we’d want to allow case insensitivity but I’d like to keep the conversation going in case I’m missing something.
