### ISSUE TITLE
Error Encountered on running php artisan app:install 

### ISSUE THREAD

**Issue by LordCheta** [CachetHQ/Cachet#3124]
Hi.

This is the output I get after running the `php artisan app:install` command

`Clearing settings cache...
Settings cache cleared!
Backing up database...
Dumping database and uploading...
sh: 1: mysqldump: not found

Backup skipped!
Backup completed!
Application key [base64:lrmYSNq/D/oufZrffK1YC/YAcxGls5d4N5N7ML8Gy0s=] set successfully.
Configuration cache cleared!
Configuration cached successfully!
Route cache cleared!
Routes cached successfully!
Copied Directory [/vendor/roumen/feed/src/views] To [/resources/views/vendor/feed]
Publishing complete for tag []!
PHP Fatal error:  Uncaught ErrorException: count(): Parameter must be an array or an object that implements Countable in /home/lordcheta/WebProject/youverify-status/vendor/graham-campbell/exceptions/src/ExceptionIdentifier.php:51
Stack trace:
#0 [internal function]: Illuminate\Foundation\Bootstrap\HandleExceptions->handleError(2, 'count(): Parame...', '/home/lordcheta...', 51, Array)
#1 /home/lordcheta/WebProject/youverify-status/vendor/graham-campbell/exceptions/src/ExceptionIdentifier.php(51): count(NULL)
#2 /home/lordcheta/WebProject/youverify-status/vendor/graham-campbell/exceptions/src/ExceptionHandlerTrait.php(47): GrahamCampbell\Exceptions\ExceptionIdentifier->identify(Object(ErrorException))
#3 /home/lordcheta/WebProject/youverify-status/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(79): GrahamCampbell\Exceptions\ExceptionHandler->report(Object(ErrorException))
#4 [internal function]: Illuminate\Foundation\Bootstrap\HandleExceptions->handleException(Object(ErrorException))
#5 {main}
 in /home/lordcheta/WebProject/youverify-status/vendor/graham-campbell/exceptions/src/ExceptionIdentifier.php on line 51
PHP Fatal error:  Uncaught ErrorException: count(): Parameter must be an array or an object that implements Countable in /home/lordcheta/WebProject/youverify-status/vendor/graham-campbell/exceptions/src/ExceptionIdentifier.php:51
Stack trace:
#0 [internal function]: Illuminate\Foundation\Bootstrap\HandleExceptions->handleError(2, 'count(): Parame...', '/home/lordcheta...', 51, Array)
#1 /home/lordcheta/WebProject/youverify-status/vendor/graham-campbell/exceptions/src/ExceptionIdentifier.php(51): count(NULL)
#2 /home/lordcheta/WebProject/youverify-status/vendor/graham-campbell/exceptions/src/ExceptionHandlerTrait.php(47): GrahamCampbell\Exceptions\ExceptionIdentifier->identify(Object(Symfony\Component\Debug\Exception\FatalErrorException))
#3 /home/lordcheta/WebProject/youverify-status/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(79): GrahamCampbell\Exceptions\ExceptionHandler->report(Object(Symfony\Component\Debug\Exception\FatalErrorException))
#4 /home/lordcheta/WebProject/youverify-status in /home/lordcheta/WebProject/youverify-status/vendor/graham-campbell/exceptions/src/ExceptionIdentifier.php on line 51`

I'll really love it if I could get help to fix this. I've looked at other issues resembling mine and haven't yet seen a solution that works for me. Many thanks

**Comment by jbrooksuk** [comment]
Cachet is not yet compatible with PHP 7.2
