### ISSUE TITLE
Managing timezone

### ISSUE THREAD

**Issue by nalysius** [CachetHQ/Cachet#3125]
Cachet stores many date/times, for incidents and incident updates for example.
For now, we don't store any timezone when inserting an incident of other.

It would be useful to store the timezone in database.

There are some things to think about:
- What timezone to use in database for previously inserted items? Perhaps a `APP_TIMEZONE` that would be a default timezone applied on the items that don't have timezone yet.
- How to show the date/times to users? Using the application timezone, or the user one?

**Comment by jbrooksuk** [comment]
Thank you for your input on Cachet 2.x. We are shifting our attention and resources to Cachet 3.x and will no longer be supporting the 2.x version. If your feedback or issue is relevant to the 3.x series, we encourage you to engage with the new branch.

For more information on the Cachet rebuild and our plans for 3.x, you can read the announcement [here](https://github.com/CachetHQ/Cachet/discussions/4342).

We appreciate your understanding and look forward to your contributions to the new version.
