### ISSUE TITLE
Subscription Captcha Feature Request

### ISSUE THREAD

**Issue by Si-Richards** [CachetHQ/Cachet#3129]
Keep having instancing of spam subscriptions. It would be great to maintain open subscription options whilst filtering out spambots.

Google NOCAPTCHA support is an obvious choice.

**Comment by anthonybocci** [comment]
I understand that spam subscriptions are very annoying, but I'm not sure if a captcha is the best solution.  
I mean, Captcha is really annoying for the user. The _Honey pot_ method is not so sure.  

A solution could be a validation email? When a person subscribes, we send a confirmation email.  
I think this feature already exists, isn't it?

**Comment by jbrooksuk** [comment]
Would #3102 not fix this?

**Comment by anthonybocci** [comment]
@jbrooksuk I think so.

> Fire a "Confirm your subscription" email.

If there is a real email account behind, I guess it's enough. But technically, it would be possible to make a bot that has an email account (or even Yopmail if not), and click on the confirmation link.  
But this would be a bot made specially for Cachet, the classic bots that we can found on the Internet only fill forms and submit them.

**Comment by jbrooksuk** [comment]
Yeah, but that’s very niche. We will also rate limit people from entering emails.

**Comment by jbrooksuk** [comment]
I'm going to close this and leave it to #3102 to prevent spam signups etc.
