### ISSUE TITLE
500 After Pulling Latest Commits

### ISSUE THREAD

**Issue by TheoBearman** [CachetHQ/Cachet#3138]
`[2018-06-26 23:33:16] local.CRITICAL: Symfony\Component\Debug\Exception\FatalThrowableError: Class 'Barryvdh\Debugbar\ServiceProvider' not found in /var/www/html/Cachet/vendor/laravel/framework/src/Illuminate/Foundation/ProviderRepository.php:208
Stack trace:
#0 /var/www/html/Cachet/vendor/laravel/framework/src/Illuminate/Foundation/ProviderRepository.php(144): Illuminate\Foundation\ProviderRepository->createProvider('Barryvdh\\Debugb...')
#1 /var/www/html/Cachet/vendor/laravel/framework/src/Illuminate/Foundation/ProviderRepository.php(61): Illuminate\Foundation\ProviderRepository->compileManifest(Array)
#2 /var/www/html/Cachet/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(548): Illuminate\Foundation\ProviderRepository->load(Array)
#3 /var/www/html/Cachet/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/RegisterProviders.php(17): Illuminate\Foundation\Application->registerConfiguredProviders()
#4 /var/www/html/Cachet/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(206): Illuminate\Foundation\Bootstrap\RegisterProviders->bootstrap(Object(Illuminate\Foundation\Application))
#5 /var/www/html/Cachet/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(297): Illuminate\Foundation\Application->bootstrapWith(Array)
#6 /var/www/html/Cachet/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(120): Illuminate\Foundation\Console\Kernel->bootstrap()
#7 /var/www/html/Cachet/artisan(35): Illuminate\Foundation\Console\Kernel->handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#8 {main} {"identification":{"id":"d63256e8-1b9a-47bc-85ef-a66ea99e2c85"}}`

and after running `php artisan app:update`:

<img width="1440" alt="screen shot 2018-06-27 at 00 33 43" src="https://user-images.githubusercontent.com/6546590/41944876-18a6e064-79a2-11e8-85e0-5d291756c66b.png">

**Comment by jbrooksuk** [comment]
Have you ran `composer install`?

**Comment by jbrooksuk** [comment]
Just walk me through the steps you did, sorry.

**Comment by jbrooksuk** [comment]
@TheoBearman I think you need to set `APP_DEBUG=false` in your `.env` file.

**Comment by TheoBearman** [comment]
I updated the `.env` file as instructed and then followed the following steps:

1. Pulled the latest commits
2. Ran `composer install -o` (also tried with `composer install --no-dev -o`
3. Ran `php artisan app:update`

The same errors appeared in the command line and the same 500 error was thrown as above.

**Comment by jbrooksuk** [comment]
Try running `rm -rf bootstrap/cache/*` and then running `composer du`.

**Comment by TheoBearman** [comment]
No change observed when running `php artisan app:update` after executing the suggested commands.

**Comment by jbrooksuk** [comment]
@TheoBearman could you try removing line 180 out of `./config/app.php` please, it's the line that reads:

```php
env('APP_DEBUG') ? Barryvdh\Debugbar\ServiceProvider::class : null,
```

I don't think that line is needed now that we use Laravel 5.6

**Comment by TheoBearman** [comment]
I have removed the line you have requested and no difference has been observed regarding the aforementioned errors.

**Comment by jbrooksuk** [comment]
How weird... I’m not sure what else to suggest. You could install with dev, so run `composer install -o` and see what happens there.

**Comment by TheoBearman** [comment]
I will do a clean install, with the suggestions you mentioned, and report back.

**Comment by TheoBearman** [comment]
Fixed. It was a config problem my end. I have multiple versions of PHP on my box and my Apache was using a version of PHP which is not compatible with Laravel 5.6. I have now configured it to use PHP 7.2 and we are back up and running.

Sorry for this!

**Comment by jbrooksuk** [comment]
😌
