### ISSUE TITLE
Markdown editor?

### ISSUE THREAD

**Issue by MaartenUreel** [CachetHQ/Cachet#3141]
Any plans to implement a simple markdown editor?

In our environment communication is done by less technical team, so some simple bold-italic-.. controls would be a big win.

e.g. something like [editor.md](https://pandao.github.io/editor.md/en.html) ?

**Comment by jbrooksuk** [comment]
This would be great, although editor.md seems a bit too heavy for what I'd be looking for. Do you know of anything simpler?

**Comment by mritzmann** [comment]
Maybe something like that: https://github.com/sparksuite/simplemde-markdown-editor ([Demo](https://simplemde.com/))

**Comment by jbrooksuk** [comment]
That'd be ideal @mritzmann!

**Comment by jbrooksuk** [comment]
Thank you for your input on Cachet 2.x. We are shifting our attention and resources to Cachet 3.x and will no longer be supporting the 2.x version. If your feedback or issue is relevant to the 3.x series, we encourage you to engage with the new branch.

For more information on the Cachet rebuild and our plans for 3.x, you can read the announcement [here](https://github.com/CachetHQ/Cachet/discussions/4342).

We appreciate your understanding and look forward to your contributions to the new version.
