### ISSUE TITLE
Problem with virtual hosts in Windows.

### ISSUE THREAD

**Issue by Hristiyanii** [CachetHQ/Cachet#3142]
Greetings!

I followed the tutorial (https://docs.cachethq.io/docs/installing-cachet-on-windows) for installing Cachet on Windows, and it worked really well! Now that I want to move my cachet installation to be accessable on directory "/status", I get an Internal Server Error
Image: https://gyazo.com/fd05d3355b56261c0ba1b5983d7db4fb

My vhosts file:
```
<VirtualHost *:80>
	DocumentRoot "C:/xampp/htdocs/"
        ServerAdmin titkatabg@gmail.com
	Alias /status "C:/xampp/htdocs/status/public"
	Alias /web "C:/xampp/htdocs/webstore"
</VirtualHost>
```

When I go to /status it works, like the actual status page works: https://gyazo.com/766a6cbc7cd2ed4f3c7bdd896285f5e8
But when I try to access dashboard or anything which is a subdirectory of /status, it does not work.

**Comment by jbrooksuk** [comment]
@TheoBearman is there any chance you can help? I don't think it's really supported.

**Comment by jbrooksuk** [comment]
Closing as `support`.
