### ISSUE TITLE
CSS missing for SweetAlert2

### ISSUE THREAD

**Issue by krollebol** [CachetHQ/Cachet#3151]
In the dashboard, when in incidents, Maintenance or Components, the 'Delete' button doesn't work correctly. The dialogbox for confirming is not correctly shown. 
I believe the SweetAlert2 related CSS is not available. With the Firefox developer tools, I don't see any of the swal2* css classed defined...
![image](https://user-images.githubusercontent.com/15714698/42165649-fc59159c-7e08-11e8-87ec-a96705117798.png)

Thanks for having a look at it.

**Comment by jbrooksuk** [comment]
I think that’s because of PurgeCSS removing code it thinks is unused. I’ll need to add an ignore statement to it.

**Comment by jbrooksuk** [comment]
This should be fixed in 1dfcd9aa

**Comment by krollebol** [comment]
Thanks James.
Confirmation dialogs and datepicker are now working.

**Comment by jbrooksuk** [comment]
Great 🎉
