### ISSUE TITLE
Feature Request: Subscribers Groups

### ISSUE THREAD

**Issue by monelgordillo** [CachetHQ/Cachet#3154]
I would like to customize status updates to specific groups.  I would like to see the ability to place subscribers in groups.

**Comment by jbrooksuk** [comment]
Thanks for your suggestion @mehaaksma!

What would be the use case of this?

**Comment by mehaaksma** [comment]
Howdy @jbrooksuk ,
We would like to be more selective on who gets a notification.
I was thinking of having subscribers tied to a department.  For example, if a dev server goes down, the accounting team doesn't really care.  However, if a payroll server goes down, the accounting team would want to know, and the development team would not.

**Comment by jbrooksuk** [comment]
Thank you for your input on Cachet 2.x. We are shifting our attention and resources to Cachet 3.x and will no longer be supporting the 2.x version. If your feedback or issue is relevant to the 3.x series, we encourage you to engage with the new branch.

For more information on the Cachet rebuild and our plans for 3.x, you can read the announcement [here](https://github.com/CachetHQ/Cachet/discussions/4342).

We appreciate your understanding and look forward to your contributions to the new version.
