### ISSUE TITLE
BUG: When reording the position of components. It fires off an email to subscribers for each state change, for each component. [bug]

### ISSUE THREAD

**Issue by bbarclay** [CachetHQ/Cachet#3157]
We only have 3 components but I imagine someone with more than this would be sending their subscribers a ton of emails. 

For instance, when I go into the drag and drop. When I change the location of one of the components. 

It fires off this email for each component 

The component SAP has seen a status change. The component is now at Operational.

Thank you, Status

This seems like a bug. Should the order changing in the drag and drop send out an email for each component? 

Thanks

Brandon

**Comment by jbrooksuk** [comment]
This is fixed in 2.4 from an issue at https://github.com/CachetHQ/Cachet/issues/3082

Looks like we need to backport it if we didn't already.

**Comment by jbrooksuk** [comment]
You need to be running PHP 7.1 or above first.

But it's the same as you do to upgrade normally, https://docs.cachethq.io/docs/updating-cachet only you need to check out the `2.4` branch.

**Comment by bbarclay** [comment]
I just upgraded to v.2.4 and it doesn't bug.
