### ISSUE TITLE
Subscription managment not workin behind SSL terminating reverse proxy

### ISSUE THREAD

**Issue by fnerdwq** [CachetHQ/Cachet#3161]
Hi,

we are running a dockerized Cachet v2.3.14 behind an apache reverse proxy, which terminates SSL.

In this setup a subscriber cannot mange his subscriptions due to a redirection from http - >https.
Effekt:

On submission of the subscription settings by hitting the button "Update Subscrition" a POST to the URL `http://status.some.org/subscribe/manage/...` with the correct `subscriptions[]` array is done, this receives a 302 redirecting to `https://status.some.org/subscribe/manage/...` which is then executed as GET, which clearly doesn't trigger the subscriptions update.

Our site is - as far as I can see - correctly deploy with `APP_URL=https://status.some.org/` and also the https-URLs in set the dashboards settings.

As a short test: injecting the correct `https` enabled URL manually as form action, makes the update work.
So how come the page is rendered with the `http` protocol for the form submission action instead of `https`?

Thanks
Frederik

**Comment by fnerdwq** [comment]
Seems to be related to https://github.com/CachetHQ/Docker/issues/271 and seems to be fixed by https://github.com/CachetHQ/Cachet/pull/3060.

Please make this `TRUSTED_PROXIES` environment available in a release (2.4 branch currently not working for me).

**Comment by voldemorte** [comment]
This still doesn't work for me with 2.4 branch

**Comment by squaricdot** [comment]
Experiencing same issue not being able to (properly) update subscription settings because the 

http://status.jemoer.com/subscribe/manage/...
body:

`<form action="http://status.jemoer.com/subscribe/manage/jfwaijwejfpowijefwiejiwj" method="post">`

keeps using http:// address whilst APP_URL=https://status.jemoer.com

Though according to the Cachet management page the subscribed components are being updated.

It's not visible to the subscriber itself using the interface for some reason...

**Comment by jbrooksuk** [comment]
Hi @fnerdwq what wasn't working in 2.4 for you?

**Comment by fnerdwq** [comment]
When I start the current 2.4 branch over my 2.3.15 setup the migration do not work, such that I just get a error message status page. I didn't try the setup from scracht. I was hoping for a 2.3.16 coming soon with `TRUSTED_PROXIES` included :-)

**Comment by titansmc** [comment]
Is this related with the Laravel behind LB or reverse proxy ? We fixed it following the instruction on the first answer.

[](https://laravel-tricks.com/tricks/fix-ssl-in-laravel-4-when-server-is-behind-a-load-balancer-or-a-reverse-proxy)

**Comment by wcgcoder** [comment]
`TRUSTED_PROXIES` only seems to make sense if your lbs have static IP addresses. This is an odd assumption made by laravel for scaled services.
The original issue referenced is preventing us from rolling out the subscription functionality to our users.

**Comment by jbrooksuk** [comment]
You can use wildcards in the trusted proxies configuration.
