### ISSUE TITLE
Localization for element "timeago"

### ISSUE THREAD

**Issue by Atriusftw** [CachetHQ/Cachet#3163]
The element "timeago" on the frontpage should also be localized, just like in the incident details.

![image](https://user-images.githubusercontent.com/1478937/42283821-fa00aba4-7faa-11e8-8769-74b9d271d6f3.png)

**Comment by jbrooksuk** [comment]
Thanks @Atriusftw although this is a duplicate of https://github.com/CachetHQ/Cachet/issues/974
