### ISSUE TITLE
Error in spanish translation

### ISSUE THREAD

**Issue by stepps** [CachetHQ/Cachet#3165]
I have found an issue in the Spanish translation:

`La página de estado de :app está proporcionada por Cachet`

:app iis not replaced as intended. 

Grepping the source, I have found other 3 instances of :app in the spanish translation

**Comment by jbrooksuk** [comment]
Can you submit a fix at https://translate.cachethq.io.

**Comment by stepps** [comment]
I can definetly help with Spanish and Italian proofreading/translation, but my PHP is very basic. I am not sure why :app is not replaced or what it should replace
