### ISSUE TITLE
Error 500 for RSS and Atom link

### ISSUE THREAD

**Issue by krollebol** [CachetHQ/Cachet#3166]
When going to the RSS or Atom link in the footer of Cachet, I get an error 500.

This is the reported error in laravel.log:
[2018-07-05 13:37:13] production.CRITICAL: Symfony\Component\Debug\Exception\FatalThrowableError: Argument 1 passed to CachetHQ\Cachet\Http\Controllers\FeedController::feedAc
tion() must be an instance of CachetHQ\Cachet\Models\ComponentGroup, null given, called in /var/www/Cachet-dev/app/Http/Controllers/FeedController.php on line 74 in /var/www/
Cachet-dev/app/Http/Controllers/FeedController.php:85

Somewhat unrelated, but I can't delete my customized footer from the settings. After saving, the custom code is still displayed in the settings.

**Comment by jbrooksuk** [comment]
Good spot! This is now fixed in 6b7263af
