### ISSUE TITLE
Display some text under the banner

### ISSUE THREAD

**Issue by krollebol** [CachetHQ/Cachet#3167]
I want to add a custom text just below the banner. Ideally it would be the text I've entered in the settings page for "About this page". That supports markdown, so it would great if I could use this!

Is that possible, without creating a custom header. A custom header also replace the banner image etc.

PS: is the "About this page" text used anywhere?

**Comment by jbrooksuk** [comment]
@krollebol not directly no. We're currently working towards a new design #3111, but as part of this, you'll be able to create your own themes and install them.
