### ISSUE TITLE
Error in PHP

### ISSUE THREAD

**Issue by jwashington104** [CachetHQ/Cachet#3168]
Hey guys, I keep getting this when I'm proxying my cachet instance. Any ideas?

#5 [internal function]: Illuminate\Foundation\Http\Middleware\VerifyCsrfToken->handle(Object(Illuminate\Http\Request), Object(Clos" while reading response header from upstream, client:

**Comment by jbrooksuk** [comment]
Please can you provide us with the latest laravel log file. You can find this in `./storage/logs`. Thanks!

**Comment by jwashington104** [comment]
Thanks for your reply. For some odd reason it looks like this line being added to the conf/nginx-site.conf file `fastcgi_param HTTPS on;` cured my problem.

**Comment by jbrooksuk** [comment]
👍🏻
