### ISSUE TITLE
(RFE) Scheduled Maintenance - Component Based Not System Wide. 

### ISSUE THREAD

**Issue by bbarclay** [CachetHQ/Cachet#3169]
- In a nut shell. Scheduled maintenance would be component or component group based and not system wide. 

So based on V.2.4 you can turn off email notifications during a system maintenance. The issue we have is that we have multiple systems. For instance, we account for our "phone systems", or "web application" and other various services in our office. This way our clients will know several aspects of our internal operations. 

- What if. Component Groups or even individual components were an option for scheduled maintenance. This way, if we are doing an update on a system and put in a scheduled maintenance. It doesn't stop our customers from getting notifications that our phone system is down. 

- What happens now. If we schedule maintenance for our web app, it would shut down all the email notifications for our other component groups.

**Comment by mgleadow** [comment]
I agree that this would be a very useful feature as I have a similar use case where a "component" is an application within a suite and they are deployed independently so I don't want a maintenance period for App A to suppress notifications for App B

**Comment by HA-TB303** [comment]
+1

**Comment by max1m1z0r** [comment]
+1 This is a very important feature in my opinion. People who are subscribing to schedules dont want to know about other services when subscribing to other services.

**Comment by jbrooksuk** [comment]
Thank you for your input on Cachet 2.x. We are shifting our attention and resources to Cachet 3.x and will no longer be supporting the 2.x version. If your feedback or issue is relevant to the 3.x series, we encourage you to engage with the new branch.

For more information on the Cachet rebuild and our plans for 3.x, you can read the announcement [here](https://github.com/CachetHQ/Cachet/discussions/4342).

We appreciate your understanding and look forward to your contributions to the new version.
