### ISSUE TITLE
lost https protocol

### ISSUE THREAD

**Issue by nilo72** [CachetHQ/Cachet#3170]
Hi there,

I have a problem with the configured site url. It is set to https://status.<mycdomain.com> and everything is fine as long as I take a look at the status-page. If I do the login to cachet the browser starts using http-Protokol. 

I'm working with a docker container which displays me the version 2.5.0-dev.

**Comment by jwashington104** [comment]
In your docker container, go to conf and edit the file nginx-site.conf, anywhere inside this option set: `location ~ \.php` add this line:  `fastcgi_param HTTPS on;` 

Save and then rebuild the container and that should cure your issue.

**Comment by nilo72** [comment]
THX for your hint! Cures my issue.
