### ISSUE TITLE
docs.cachethq.io still taking a long time to load

### ISSUE THREAD

**Issue by vstock28021** [CachetHQ/Cachet#3172]
Since I couldn't reopen the old post #3055 I figured I would open a new issue. I'm still seeing 50+ second load times on docs.cachethq.io as seen in this Firefox Screenshot below. You have this in both #3055 and here so you can delete this one and reopen that one if it's easier.

![docs cachethq io-loadingtime](https://user-images.githubusercontent.com/7843257/42416750-4d90b740-8245-11e8-9a7d-51526cbf19b8.png)

**Comment by jbrooksuk** [comment]
Readme.io have scaled up our dyno so this shouldn't be an issue now.
