### ISSUE TITLE
Add possibility to configure what kind of notifications subscribers will receive

### ISSUE THREAD

**Issue by cebe** [CachetHQ/Cachet#3173]
Currently according to the description in the admin dashboard "Subscribers will receive email updates when incidents are created or components are updated."

This is fine if components status changes are changed manually and incindent reports are created for every status change. I am however updating my components status automatically from my Icinga Monitoring, so users get notified every time a component changes its status. This is annoying for small changes like something is moving into "performance issues" and then back to normal after 5 minutes. There is no need for a notification in this case.

I would like to limit notifications to Incidents only so users are notified about important stuff but not spammed about small performance issues. A configuration option to control which events will trigger a notification could solve this.

**Comment by jbrooksuk** [comment]
Thank you for your input on Cachet 2.x. We are shifting our attention and resources to Cachet 3.x and will no longer be supporting the 2.x version. If your feedback or issue is relevant to the 3.x series, we encourage you to engage with the new branch.

For more information on the Cachet rebuild and our plans for 3.x, you can read the announcement [here](https://github.com/CachetHQ/Cachet/discussions/4342).

We appreciate your understanding and look forward to your contributions to the new version.
