### ISSUE TITLE
Turning off subscribe button forces removal of update subscribers

### ISSUE THREAD

**Issue by jwashington104** [CachetHQ/Cachet#3177]
Hey guys,

Weird use case for you. I want to be able to add subscribers manually, stop new people from subscribing to our status updates but also be able to notify our current subscribers of issues.

Currently when you turn off user based subscriptions, you can't notify your current subscribers via report an incident, the toggle just isn't there and as a result - no-one is notified.

Is this something you're looking at changing?

**Comment by jbrooksuk** [comment]
This is by design and really, you have a unique use-case there. We could look at adding an option though. So long as mail settings are configured...

**Comment by BBrey** [comment]
This is not a unique use case, sometimes you just do not want to let people sign up randomly.
Of course there are ways to disable the button with javascript 😆

**Comment by jwashington104** [comment]
I just removed the button on the front page via CSS and then emailed the subscribe link to those who needed it.

**Comment by spencerryan** [comment]
We are planning on using Cachet internally and similarly want something like this. We are going to subscribe specific mailing distribution lists ourselves but don't want end users to have the ability to do so.

**Comment by jbrooksuk** [comment]
Thank you for your input on Cachet 2.x. We are shifting our attention and resources to Cachet 3.x and will no longer be supporting the 2.x version. If your feedback or issue is relevant to the 3.x series, we encourage you to engage with the new branch.

For more information on the Cachet rebuild and our plans for 3.x, you can read the announcement [here](https://github.com/CachetHQ/Cachet/discussions/4342).

We appreciate your understanding and look forward to your contributions to the new version.
