### ISSUE TITLE
Session cookies being shared by different computers over the same network

### ISSUE THREAD

**Issue by jwashington104** [CachetHQ/Cachet#3178]
Why are laravel sessions being shared between different users? I don't think this is inteded to happen, and it's a massive security hole.

**Comment by jwashington104** [comment]
Using build 2.3.15 (reporting to be 2.3.14-dev)..

**Comment by jbrooksuk** [comment]
I don’t know how this is the case... are you using a different `SESSION_DRIVER`.

**Comment by jbrooksuk** [comment]
I believe this happened because of an nginx configuration?
