### ISSUE TITLE
Class 'AltThree\Logger\LoggerServiceProvider' not found

### ISSUE THREAD

**Issue by sneak-it** [CachetHQ/Cachet#3180]
Hello, I have reached this error while attempting to upgrade my 2.4 installation to the latest commit:

```
In ProviderRepository.php line 208:

  Class 'AltThree\Logger\LoggerServiceProvider' not found
```

I have already run
`composer install -o --no-dev`

Any thoughts?

**Comment by jbrooksuk** [comment]
Can you try:

```
rm -rf bootstrap/cache/*
```

**Comment by sneak-it** [comment]
Apologies, that did the trick!

**Comment by jbrooksuk** [comment]
That’s okay!
