### ISSUE TITLE
502 Bad Gateway - Ngnix

### ISSUE THREAD

**Issue by sixalyzza** [CachetHQ/Cachet#3185]
Hello, i have been having some issues with Cachet running on Ngnix it keeps requesting this

`2018/07/14 07:13:11 [crit] 27560#27560: *1 connect() to unix:/var/run/php5-fpm.sock failed (13: Permission denied) while connecting to upstream, client: 192.168.1.1, server: stats.sixserve.com, request: "GET / HTTP/1.1", upstream: "fastcgi://unix:/var/run/php5-fpm.sock:", host: "stats.sixserve.com"`

**Comment by Atriusftw** [comment]
Most likely related to php-fpm.

Edit your `www.conf` and uncomment the following lines and restart PHP fpm;

> listen.owner = www-data
> listen.group = www-data
> listen.mode = 0660

Change the user accordingly if different.

**Comment by jbrooksuk** [comment]
@Atriusftw seems to be right here. Closing this as it's unrelated to Cachet :)
