### ISSUE TITLE
500 Internal Server Error

### ISSUE THREAD

**Issue by Indominus121** [CachetHQ/Cachet#3186]
When trying to go to my site, I get a error page saying:

> Oops! An Error Occurred
> The server returned a "500 Internal Server Error".
> Something is broken. Please let us know what you were doing when this error occurred. We will fix it as soon as possible. Sorry for any inconvenience caused.

I've tried running both `php artisan config:cache` and `php artisan app:update`, however, the issue still persists. 

Below is a copy of my laravel log. Any help or suggestions would be greatly appreciated!
[laravel-2018-07-14.log](https://github.com/CachetHQ/Cachet/files/2195342/laravel-2018-07-14.log)

Copy of my `.env`

> APP_ENV=production
> APP_DEBUG=false
> APP_URL=http://status.sarpcommunity.com
> APP_KEY=base64:Yr2o1bl3l4zwPKipkYKRFJ2d8L2p41UkL/V+B85RDtY=
> 
> DB_DRIVER=sqlite
> 
> CACHE_DRIVER=file
> SESSION_DRIVER=file
> QUEUE_DRIVER=sync
> CACHET_EMOJI=false
> 
> MAIL_DRIVER=smtp
> MAIL_HOST=smtp.gmail.com
> MAIL_PORT=465
> MAIL_USERNAME=admin@*******
> MAIL_PASSWORD=********
> MAIL_ADDRESS=admin@*******
> MAIL_NAME=Status
> MAIL_ENCRYPTION=tls
> 
> REDIS_HOST=null
> REDIS_DATABASE=null
> REDIS_PORT=null
> 
> GITHUB_TOKEN=null

**Comment by jbrooksuk** [comment]
The error is:

> Next exception 'Illuminate\Database\QueryException' with message 'SQLSTATE[HY000]: General error: 17 database schema has changed (SQL: insert into "migrations" ("migration", "batch") values (2015_01_05_201324_CreateComponentGroupsTable, 1))' in /root/Cachet/vendor/laravel/framework/src/Illuminate/Database/Connection.php:713

@Indominus121 are you using SQLite?

**Comment by jbrooksuk** [comment]
Closing this due to lack of response.
