### ISSUE TITLE
Email customizaion 

### ISSUE THREAD

**Issue by Yuvky** [CachetHQ/Cachet#3187]
In the next version (2.4.0) is it possible to add the ability to customize the email?
The point is to be able to change the font /design (etc..) of the notification email of an incident / status change / scheduled maintenance

We have encountered a situation in which we want to tailor the design to meet our company's style, and the only (rather bad) option is to change the lang/cachet.php files under resources

**Comment by jbrooksuk** [comment]
Actually, yes! 2.4 will intrdouce a themeing system where you could replace them if you wanted to.
