### ISSUE TITLE
Error with the app key and the file docker-compose.yml

### ISSUE THREAD

**Issue by thesnipe789** [CachetHQ/Cachet#3190]
Hello !

I'm trying to install CachetHQ via docker on Plesk.

But when I install he tells me two mistakes:
- "The name of an environment variable can consist of uppercase letters, digits, and the underscore ('_'), and can not begin with a digit."

I put "cachet_ver" and "archive_url" in upper case and solve the problem.

But when I run the installation on the logs I have an error:
ERROR: Please set the 'APP_KEY = base64: EbLCuIvCFAkQ / KYZSL1mEipcpI07VdVTDAQDkNxkw + 8 =' environment variable at runtime or in docker-compose.yml and re-launch

Unfortunately, I do not find the docker-compose.yml file to add the line, nor do I know or create it. Can you help me?

Thank you in advance.

**Comment by jbrooksuk** [comment]
You need to open this in [CachetHQ/Docker](/CachetHQ/Docker), please.

**Comment by gcommit** [comment]
Simply just remove the "`exit 0`" in the `entrypoint.sh` - if you do so, a new key will be generated and written to file. 

```
  if [[ -z "${APP_KEY}" || "${APP_KEY}" = "null" ]]; then
    keygen="$(php artisan key:generate --show)"
    APP_KEY=$(echo "${keygen}")
    echo "ERROR: Please set the 'APP_KEY=${APP_KEY}' environment variable at runtime or in docker-compose.yml and re-launch"
    #exit 0
  fi
```
