### ISSUE TITLE
v2.3.15 tag wrong VERSION file

### ISSUE THREAD

**Issue by TakeMeNL** [CachetHQ/Cachet#3192]
The current release of v2.3.15 has a dev VERSION file.
https://github.com/CachetHQ/Cachet/blob/163f57397d60347a8a5fea57d1688a72f4f7e760/VERSION#L1
The file should be v2.3.15 but it is v2.3.14-dev.
The api /version returns this incorrectly then.

**Comment by jbrooksuk** [comment]
Whoops! I didn't update this. I'm going to fix this.

**Comment by jbrooksuk** [comment]
I need to release a new version of 2.3 which fixes Swiftmailer so hopefully the version will be fixed as well.

**Comment by jbrooksuk** [comment]
The tag for what will be 2.3.16 is ready now, sorry I ballsed up the version.
