### ISSUE TITLE
Documentation on Use? 

### ISSUE THREAD

**Issue by DonRichards** [CachetHQ/Cachet#3193]
I found the documentation for installing and places to go for 3rd party plugins, but where is the documentation on how to use this product? Trying to understand 

Example of questions I have and no idea where to get in the info
* What is a INCIDENT TEMPLATES? 
  * What should it look like? 
  * How should it behave?
  * What are the options/variables it has access to?
* How do I hide components description stuff (for non-admins)?
* How do I setup metrics? 
  * What metrics can be utilized?

**Comment by DonRichards** [comment]
From https://docs.cachethq.io/ the foot points to "Support" 
![Broken Links](https://user-images.githubusercontent.com/2738244/43023437-e1e082a2-8c38-11e8-99ff-e8ad1ce84953.png)
 All of those links are all 404 pages. 
![404](https://user-images.githubusercontent.com/2738244/43023438-e1ecdfb6-8c38-11e8-95a5-5005dac8d982.png)

**Comment by jbrooksuk** [comment]
Hi @DonRichards, thanks for your thoughts.

The documentation is currently being transferred to https://github.com/CachetHQ/Cachet/tree/2.4/docs - if you can help out, that'd be great!

Are you specifically looking for these questions to be answered right now, or within the documentation?

**Comment by DonRichards** [comment]
Ideally within the documentation.

**Comment by coosamatt** [comment]
I'd love to know how the * INCIDENT TEMPLATES work as well. I'v been trying for hours to make them work with no progress.

**Comment by Zauxst** [comment]
There seems to be 0 support for some feature right now... 
Did anyone managed to figure it out how it works?

**Comment by jbrooksuk** [comment]
Thank you for your input on Cachet 2.x. We are shifting our attention and resources to Cachet 3.x and will no longer be supporting the 2.x version. If your feedback or issue is relevant to the 3.x series, we encourage you to engage with the new branch.

For more information on the Cachet rebuild and our plans for 3.x, you can read the announcement [here](https://github.com/CachetHQ/Cachet/discussions/4342).

We appreciate your understanding and look forward to your contributions to the new version.
