### ISSUE TITLE
Question for page 

### ISSUE THREAD

**Issue by ToggleIP** [CachetHQ/Cachet#3194]
Hi,

Me and a friend were wondering if we could make a custom page for our status page.

Because we search in files but we couldn't find out what file and how to.

So is there a way to make a custom page for our status site?

Regards,

AverageKevin

**Comment by jbrooksuk** [comment]
@ToggleIP there isn't a way to add a custom page, but you could do this with relatively little work which should be easy if you have any experience with Laravel.

Maybe in the future we could add support for custom pages?
