### ISSUE TITLE
Add team invitation system

### ISSUE THREAD

**Issue by jbrooksuk** [cachethq/Cachet#320]
This would be a great way to get members of your team to join you. They'd simply be sent an email (using the notification email template) they click a link which lets them sign up then the invitation for that account is disabled so it's unable to be re-used.

- [x] Setup mail settings
    - [ ] Allow mail to be configured at setup
    - [ ] Change mail settings via dashboard
- [ ] Create invitation system
- [ ] Add email invitations to the setup stage of Cachet
- [ ] Add team member email invitations to the dashboard

**Comment by jbrooksuk** [comment]
We'll also want to get the queue enabled at some point, because if you invite someone to the team, the mail code will be blocking.

**Comment by joecohens** [comment]
:+1: on ajax for now, although I really love queues they are not available on all simple servers yet.

**Comment by jbrooksuk** [comment]
Pushing this back to V2 for the sake of getting V1 out.

**Comment by jbrooksuk** [comment]
Well we've at least started this with the subscriber stuff, so that's good.
