### ISSUE TITLE
Question about Installing Cachet

### ISSUE THREAD

**Issue by y-ohara8814** [CachetHQ/Cachet#3201]
(First of all, I'm japanese and so my English may not be good、sorry.)
Hi,
I'm trying to install CachetHQ ,following official documantation(https://docs.cachethq.io/docs/installing-cachet#section-running-cachet-on-apache).

But  some problems occuered and my job stopped.

1.can not find .env file in Cachet
Following official documentation, 
> Configuring a database
> By default Cachet comes with a .env.example file. You'll need to rename this file to just .env regardless of what environment you're working on.

But after I  downloaded source code with Git, there is no .env file in Cachet directory.
So I made .env file which includes some text written in official documentation as "Text".
Is it right way or Did I make any mistake when downloading source code??

2.way to set application key
Following official documentation,

> php artisan key:generate

But when I execute this command, the following message appears.

> Could not open input file: artisan

To create application key, what is lacking on my environment?

I hope someone whould give some advice to me...

regards,

**Comment by jsargent7089** [comment]
What linux distributions are you on?

**Comment by y-ohara8814** [comment]
Thanks for comments, but I could install CachetHQ myself.
(I executed install command on wrong directory and located source codes on wrong directory.
 And I'm on Amazon linux so I investigated how to install required programs.)

However some problems still exist. 
There is no instruction manual about CachetHQ in Japanese, so I can't run server monitoring operation.
Is there any instruction manual about CachetHQ in English?

**Comment by jsargent7089** [comment]
https://docs.cachethq.io/docs/installing-cachet

**Comment by jsargent7089** [comment]
https://docs.cachethq.io/docs/prerequisites

That is the requirements for cachet

**Comment by jsargent7089** [comment]
Here it is in Japanese




前提条件
Cachetの使用を開始するには、いくつかの前提条件が必要です。

簡単な編集
アプリケーションの前提条件
サーバーに少なくとも次のものがインストールされている必要があります。

PHP 5.5.9では、ext-gd、ext-simplexml、mcrypt、ext-xmlもインストールする必要があります。
作曲家とext-mbstring、ext-tokenizer
キャッシングのためのAPCまたはRedis。
MySQL、PostgreSQL、SQLiteなど、DB用のデータベースドライバ。
Git
SQLite
SQLiteはサポートしていますが、大量のトラフィックがあるステータスページには使用しないことをお勧めします。

MySQLのタイムゾーン情報
MySQLデータベースが正しいタイムゾーン情報で更新されていることを確認してください。これにより、メトリックが正しく表示されます。https://dev.mysql.com/doc/refman/5.7/en/time-zone-support.html

開発者の前提条件
もしあなたがCachetに貢献したいのであれば、いくつかの依存関係が必要かもしれません。あなたが探しているものに応じて。

私たちのCSSはSCSSからコンパイルされているので、コンパイルするには以下が必要です：

Node.js
NPM
バワー
ギャルプ
Zentei jōken Cachet no shiyō o kaishi suru ni wa, ikutsu ka no zentei jōken ga hitsuyōdesu. Kantan'na henshū apurikēshon no zentei jōken sābā ni sukunakutomo tsugi no mono ga insutōru sa rete iru hitsuyō ga arimasu. PHP 5. 5. 9De wa, ext - gd, ext - simplexml, mcrypt, ext - xml mo insutōru suru hitsuyō ga arimasu. Sakkyokka to ext - mbstring, ext - tokenizer kyasshingu no tame no APC matawa Redis. MySQL, PostgreSQL, SQLite nado, DB-yō no dētabēsudoraiba. Git SQLite SQLite wa sapōto shite imasuga, tairyō no torafikku ga aru sutētasupēji ni wa shiyō shinai koto o o susume shimasu. MySQL no taimuzōn jōhō MySQL dētabēsu ga tadashī taimuzōn jōhō de kōshin sa rete iru koto o kakuninshitekudasai. Kore ni yori, metorikku ga tadashiku hyōji sa remasu. Https: / / Dev. Mysql. Komu/ doc/ refman/ 5. 7/ En/ time - zone - support. Html kaihatsu-sha no zentei jōken moshi anata ga Cachet ni kōken shitai nodeareba, ikutsu ka no isonkankei ga hitsuyō kamo shiremasen. Anata ga sagashite iru mono ni ōjite. Watashitachi no CSS wa SCSS kara konpairu sa rete irunode, konpairu suru ni wa ika ga hitsuyōdesu: Nōdo. Js NPM bawā gyarupu

**Comment by y-ohara8814** [comment]
Thanks for comment, jsargent7089.
But I already saw that website and installed CachetHQ successfully.
What I mean is, I want to know how to run CachetHQ and monitor the status of some website.

Now I can access the Dashboard but I can't find a textbox or something to enter the address and make the website to the target of monitoring status.
Maybe is it required that write website's address in some file directly to make the website to the target of monitoring status?Is the Dashboard  only to monitor the statues?

**Comment by jbrooksuk** [comment]
> Now I can access the Dashboard but I can't find a textbox or something to enter the address and make the website to the target of monitoring status.

Cachet doesn't do this natively. You need to use a plugin (see https://docs.cachethq.io/docs/addons).

**Comment by y-ohara8814** [comment]
@jbrooksuk 
thank you for comment.
Now, I'm tring to install cachet-monitor, but an error occured.

would you give me some advice?
https://github.com/CastawayLabs/cachet-monitor/issues/96

Regards,
