### ISSUE TITLE
Docker install does not work

### ISSUE THREAD

**Issue by AndyBehr** [CachetHQ/Cachet#3202]
I run the docker image as described here: https://docs.cachethq.io/docs/get-started-with-docker

But i only get a 500 error. 
And in the logs I see this:
"NOTICE: PHP message: [2018-07-27 09:07:00] production.ERROR: RuntimeException: No supported encrypter found. The cipher and / or key length are invalid. in /var/www/html/vendor/laravel/framework/src/Illuminate/Encryption/EncryptionServiceProvider.php:45"

I don't know what to do. 
Any ideas?

**Comment by jedrzejsieracki** [comment]
1. In the environment section of your docker-compose.yml, remove the APP_KEY variable value
      `- APP_KEY=`
2. Restart the containers, receive a meaningful error message:
`cachet_1    | Initializing Cachet container ...
cachet_1    | ERROR: Please set the 'APP_KEY=base64:SOME GENERATED 32CHARS VALUE =' environment variable at runtime or in docker-compose.yml and re-launch`
3. Add the pregenerated variable APP_KEY value to the docker-compose.yml file.
4. Re-launch.

**Comment by jbrooksuk** [comment]
Yep, see above :)

**Comment by gcommit** [comment]
Simply just remove the "`exit 0`" in the `entrypoint.sh` - if you do so, a new key will be generated and written to file.
