### ISSUE TITLE
Install Cachet with other web pages

### ISSUE THREAD

**Issue by martheli** [CachetHQ/Cachet#3204]
I installed Cachet and got it set up on my server but now anyone I go to my IP address I get Cachet and if I try to navigate away to another webpage in my html folder I get server error. Is there anything I can do to set up Cachet at a location like www/Cachet but also have access to other web projects that I have at www/project1 as an example?

**Comment by Atriusftw** [comment]
Look into isolating the sites with `vhosts` on your webserver.

**Comment by jbrooksuk** [comment]
If you're using Nginx you need to not setup the Cachet site to use `default_server`.

This isn't different to other applications, so we're going to close this issue as it's unrelated to Cachet :)
