### ISSUE TITLE
DNSSEC broken on cachethq.io

### ISSUE THREAD

**Issue by stecklars** [CachetHQ/Cachet#3206]
DNSSEC is currently broken on cachethq.io. Users with a DNSSEC validating resolver therefore can't resolve cachethq.io.

```
$ dig cachethq.io

; <<>> DiG 9.13.0 <<>> cachethq.io
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: SERVFAIL, id: 18246
;; flags: qr rd ra; QUERY: 1, ANSWER: 0, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 512
;; QUESTION SECTION:
;cachethq.io.			IN	A

;; Query time: 38 msec
;; SERVER: 8.8.8.8#53(8.8.8.8)
;; WHEN: Mi Aug 01 19:12:08 CEST 2018
;; MSG SIZE  rcvd: 40
```

DNSSEC analysis for cachethq.io:

http://dnsviz.net/d/cachethq.io/W2Hpzw/dnssec/

https://dnssec-debugger.verisignlabs.com/cachethq.io

**Comment by jbrooksuk** [comment]
Thanks for letting us know! We'll resolve this shortly :)

**Comment by jbrooksuk** [comment]
We're waiting on GoDaddy to re-support configuring of the DS record (https://uk.godaddy.com/help/add-a-ds-record-23865).

Once they support it again we'll get this resolved, but unfortunately we're at the whim of GoDaddy.

**Comment by stecklars** [comment]
@jbrooksuk Looks fixed to me though:
http://dnsviz.net/d/cachethq.io/W2TeGA/dnssec/

I can resolve the domain again and it seems that DNSSEC is configured correctly currently.

**Comment by jbrooksuk** [comment]
Well... okay then 😂 no idea!
