### ISSUE TITLE
Displaying Average of Status Over 90 Days

### ISSUE THREAD

**Issue by MatthewC** [CachetHQ/Cachet#3208]
I'm not exactly sure on whether or not this has already been suggested, or if it is already a feature, but what I am trying to see is if it is possible to get something like what [Discord](https://status.discordapp.com) has, in which you see an overview of the past 90 days in a simple to understand format. I linked an image below to show exactly what I mean.
![groupedcomponenets](https://user-images.githubusercontent.com/16270955/43610730-42e9c48c-96a7-11e8-84f8-5354d9806424.PNG)

**Comment by Dancbeunny98** [comment]
good idea!

**Comment by jbrooksuk** [comment]
Thank you for your input on Cachet 2.x. We are shifting our attention and resources to Cachet 3.x and will no longer be supporting the 2.x version. If your feedback or issue is relevant to the 3.x series, we encourage you to engage with the new branch.

For more information on the Cachet rebuild and our plans for 3.x, you can read the announcement [here](https://github.com/CachetHQ/Cachet/discussions/4342).

We appreciate your understanding and look forward to your contributions to the new version.
