### ISSUE TITLE
Unnecessary requirement of external assets

### ISSUE THREAD

**Issue by telekem** [CachetHQ/Cachet#3210]
For offline development and for the sake of privacy (so that requests are only made to your own server), it should be possible to disable usage of external assets/cdns. Currently on a brand new install the home status page is making requests to cloudflare (for zxcvbn) and google fonts.

As an example where this issue has been resolved, gitea has an [offline mode](https://docs.gitea.io/en-us/config-cheat-sheet/) that disables usage of cdns for js libraries.

**Comment by jbrooksuk** [comment]
There is a setting in the dashboard which disables external dependencies :)

**Comment by telekem** [comment]
@jbrooksuk is this in a newer version? I'm on the v2.3.9 tag

**Comment by jbrooksuk** [comment]
Sorry, I can’t remember the exact version. You’re a bit behind in the 2.3 release cycle though, so it’s worth upgrading.
