### ISSUE TITLE
Incident Resolve Notificaition Failure

### ISSUE THREAD

**Issue by krishnaastica** [CachetHQ/Cachet#3215]
All,
Using Cachet 2.3.14-dev using docker.
Whenever a incident is resolved notification fails.
Any help will be highly appreciated.
Thanks,
Krishna

**Comment by krishnaastica** [comment]
Hi Guys,
Hope somebody is watching these threads???
Atleast can you guys share the V3 release date???

**Comment by jbrooksuk** [comment]
This should be fixed in v2.4, apologies for the issues.
