### ISSUE TITLE
getAllSubscribers method not working

### ISSUE THREAD

**Issue by rtroulak** [CachetHQ/Cachet#3216]
When i try to call getAllSubscribers method, i have this result :  

> PHP Fatal error:  Uncaught exception 'GuzzleHttp\Exception\ConnectException' with message 'cURL error 28: Operation timed out after 3002 milliseconds with 0 out of -1 bytes received (see http://curl.haxx.se/libcurl/c/libcurl-errors.html)' in /vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php:186

Any ideas? 

PS. another methods for example (getAllIncidents & getAllComponents) works fine

**Comment by rtroulak** [comment]
are there any limitation in subcriber's number?

**Comment by jbrooksuk** [comment]
@rtroulak what endpoint are you hitting here? How many subscribers do you have?

**Comment by jbrooksuk** [comment]
Also, can you please confirm which version of Cachet you're using?

**Comment by rtroulak** [comment]
i have almost 10,000 subscribers. I use 2.3 version

**Comment by jbrooksuk** [comment]
Thank you for your input on Cachet 2.x. We are shifting our attention and resources to Cachet 3.x and will no longer be supporting the 2.x version. If your feedback or issue is relevant to the 3.x series, we encourage you to engage with the new branch.

For more information on the Cachet rebuild and our plans for 3.x, you can read the announcement [here](https://github.com/CachetHQ/Cachet/discussions/4342).

We appreciate your understanding and look forward to your contributions to the new version.
