### ISSUE TITLE
Status 200 but nothing is rendered 

### ISSUE THREAD

**Issue by praneet12** [CachetHQ/Cachet#3217]
I have install CachetHQ as given in step and running it in nginx server. 

When I go to localhost:8080/Cachet/public/index.php  

I am getting status 200 but nothing is rendered.

**Comment by GrahamCampbell** [comment]
Thanks for getting in touch. I don't think that configuration is correct. You shouldn't need `Cachet/public/index.php` in the path. You should point the server directly at the public folder, like https://demo.cachethq.io/.
