### ISSUE TITLE
Multi-language display

### ISSUE THREAD

**Issue by rubbermaid123** [CachetHQ/Cachet#3222]
Hi, 

I will be nice to have multi-language interface that user can choose from the down corner. With that ability to user to choose in which language to display the status page, we will need in dashboard the ability to fill a textbox for each language supported by our page.

also, this feature need to be implement to subscriber (to be able to choose which language to receive email) and alerts.

Thanks.

**Comment by jbrooksuk** [comment]
This would be possible as well since we know all of the languages. The only difficulty is that Cachet ships with incomplete languages.

**Comment by jbrooksuk** [comment]
Also, you can enable a setting in Cachet in the Localization page **Automatically localise your status page to your visitor's language?**
