### ISSUE TITLE
Spurious notification when updating component

### ISSUE THREAD

**Issue by cdhowie** [CachetHQ/Cachet#3224]
Version: 2.3.14

It appears that any change to a component will result in a notification that the component is "now operational," even if e.g. only the description was updated.  **This includes reordering components, which will send out a notification for every component whose sort index is updated!**  This is confusing and has the potential to annoy subscribers, who are effectively being notified that nothing has changed.

I expected that notifications would only be sent when the component's operational status was changed.

**Comment by cdhowie** [comment]
I hacked a fix for this problem in 06d6edf12312c7cfb62ce47d0d2f92d0c5eaf5c1 to get our installation to stop sending out these useless notifications.  A proper fix would probably include the entire old component state in the `ComponentWasUpdatedEvent` object, as my hack adds too much specific knowledge to this class.

**Comment by jbrooksuk** [comment]
I believe this was fixed in 2.4
