### ISSUE TITLE
Email notifications should include a link to the status page

### ISSUE THREAD

**Issue by cdhowie** [CachetHQ/Cachet#3225]
Right now, notifications include a link to update subscription preferences, but do not link to the main status page anywhere.  A link would be useful so that subscribers can monitor the status of an impacted component.

**Comment by jbrooksuk** [comment]
Good spot, @cdhowie!

**Comment by Data-Kiss** [comment]
I can have a go at this one if nobody else is? I'm new to open source and have been having a bit of a nosey at the project and it seems interesting so am looking for something to contribute to!

**Comment by jbrooksuk** [comment]
Thank you for your input on Cachet 2.x. We are shifting our attention and resources to Cachet 3.x and will no longer be supporting the 2.x version. If your feedback or issue is relevant to the 3.x series, we encourage you to engage with the new branch.

For more information on the Cachet rebuild and our plans for 3.x, you can read the announcement [here](https://github.com/CachetHQ/Cachet/discussions/4342).

We appreciate your understanding and look forward to your contributions to the new version.
