### ISSUE TITLE
Component order changes when status is changed either from dashboard or edit component tab

### ISSUE THREAD

**Issue by tejaswivinod** [CachetHQ/Cachet#3228]
We are using Cachet 2.3. We have observed component order changes when status is changed from either from edit tab or dashboard. Order also changes on dashboard. 
This is also happening on cachet demo site(2.4 I believe). Below are the screenshots. 
QA1 a new component added and that's how it looks before change for status on demo site and dashboard:

![order of components before change on demo site](https://user-images.githubusercontent.com/24422623/44673781-75ea2f00-a9fa-11e8-81c6-f0f829420591.png)
![order of components before change on dashbaord](https://user-images.githubusercontent.com/24422623/44673782-75ea2f00-a9fa-11e8-8ca9-0d5efeb5aa06.png)

After QA1 status been changed to Major outage, it comes on the top.
![components after change on demo site](https://user-images.githubusercontent.com/24422623/44673779-75ea2f00-a9fa-11e8-8916-f69b182265bb.png)
![components after change on dasboard](https://user-images.githubusercontent.com/24422623/44673780-75ea2f00-a9fa-11e8-8740-6f7990df5e2e.png)

is this behaviour is expected? 
I have also noticed this happens after assigning groups to component. And set no order, it gets 0th order as default, but order changes when it's status changes and comes on top of group on dashboard. 

I am not sure why does the order changes on changing status?

**Comment by tejaswivinod** [comment]
Hello again, We have found out components can be arranged in specific order from `components` dashboard and newly created components gets 0th order.
I have assigned certain order to components by seeding data. But I found out that orders have been changed in the backend as I added more components from dashboard without rearranging from components page and not same as assigned. Can you explain on what basis this orders gets assigned. 
Also, whatever order a component gets, it should not change when I change status of it as explained in previous comment.

**Comment by jbrooksuk** [comment]
This should no longer be an issue in 2.4 - are you able to test this?

**Comment by jbrooksuk** [comment]
Thank you for your input on Cachet 2.x. We are shifting our attention and resources to Cachet 3.x and will no longer be supporting the 2.x version. If your feedback or issue is relevant to the 3.x series, we encourage you to engage with the new branch.

For more information on the Cachet rebuild and our plans for 3.x, you can read the announcement [here](https://github.com/CachetHQ/Cachet/discussions/4342).

We appreciate your understanding and look forward to your contributions to the new version.
