### ISSUE TITLE
Nested component groups

### ISSUE THREAD

**Issue by ghost** [CachetHQ/Cachet#3230]
Idea is to allow for component groups to contain subgroups in order to have a more easily navigable status page for services that contain many layers of subservices.

Motivation came from wanting to use Cachet as an internal service monitoring status page for test environments, and wanting to be able to view top level status, contain all subgroups of services, and drill down to the service level statuses. Example looks like: 
![screen shot 2018-08-30 at 9 34 53 am](https://user-images.githubusercontent.com/32464820/44865842-4aed1e80-ac38-11e8-932b-d2b39a890776.png)

@jbrooksuk Would love some feedback on the idea :)

**Comment by jithinsarath** [comment]
I would be interested in this very much. Similar use case for Internal IT with more applications that 3 full page loads can contain :)

**Comment by donalturrentine** [comment]
Is there a "feature" label in the house? :)

**Comment by schemetric** [comment]
This would be very helpful for us as well. We're using Cachet to publish the status of AV systems in classrooms. Being able to specify which particular component in a room is having the issue would be great. That would provide much more visibility for our faculty into the exact state of a room they will be teaching in.  Thanks.

**Comment by jbrooksuk** [comment]
This is something that we can implement relatively quickly. I can look at this after my holiday.

**Comment by cmardle** [comment]
Any update on this? :slightly_smiling_face:

**Comment by acrawly** [comment]
I'm willing to pay for this feature to be built if anyone is interested.

**Comment by thomschlereth** [comment]
Any update on this? My team would benefit from this a lot.

**Comment by acrawly** [comment]
I've begun working on this. We will have a pull request in the coming weeks. =) 

EDIT: we decided to build our own status page using Node/Serverless instead. Sorry. =(

**Comment by Chupathingy42** [comment]
Have there been any updates on adding this feature?

**Comment by fractos** [comment]
If you can get this done then I can interface it directly with my https://github.com/fractos/cupcake uptime monitor which has a 4 level hierarchy (environment group, environment, endpoint group, endpoint).

Any news on this?

**Comment by simonaciuciuc** [comment]
Hello,

Do you have any news regarding this feature? Thank you!

**Comment by jbrooksuk** [comment]
Thank you for your input on Cachet 2.x. We are shifting our attention and resources to Cachet 3.x and will no longer be supporting the 2.x version. If your feedback or issue is relevant to the 3.x series, we encourage you to engage with the new branch.

For more information on the Cachet rebuild and our plans for 3.x, you can read the announcement [here](https://github.com/CachetHQ/Cachet/discussions/4342).

We appreciate your understanding and look forward to your contributions to the new version.
