### ISSUE TITLE
Using cachet for scheduled maintenance, but also for "important" periods

### ISSUE THREAD

**Issue by arthurzenika** [CachetHQ/Cachet#3231]
For a given component it would be nice to be able to use cachet for managers of the site to communicate with the ops team. Right now ops can use schedule maintenance to warn users and manager of a possible downtime. We would love to be able to use cache so that users/managers could also warn the ops team of a period where maintenance should not be done, or a particular care should be taken as to keep the platform up, for a demo for example.

**Comment by jbrooksuk** [comment]
Thank you for your input on Cachet 2.x. We are shifting our attention and resources to Cachet 3.x and will no longer be supporting the 2.x version. If your feedback or issue is relevant to the 3.x series, we encourage you to engage with the new branch.

For more information on the Cachet rebuild and our plans for 3.x, you can read the announcement [here](https://github.com/CachetHQ/Cachet/discussions/4342).

We appreciate your understanding and look forward to your contributions to the new version.
