### ISSUE TITLE
scheduled maintenance component

### ISSUE THREAD

**Issue by ghost** [CachetHQ/Cachet#3237]
Hi,
this isn't a issue but I want to suggest a new feature.
It would be great if I would be able to select a component within the scheduled maintenance task.
Right now, if I schedule a task, everyone gets informed but if I am going to maintain only a specific server or whatever it would be great if not everyone gets informed that this Server will have a down time but only those who are affected.

**Comment by jbrooksuk** [comment]
Please try running `rm -rf bootstrap/cache{,t}/*`.
