### ISSUE TITLE
Error Running Composer Install Command

### ISSUE THREAD

**Issue by TheoBearman** [CachetHQ/Cachet#3241]
`php artisan cachet:install` produces this:

<img width="1191" alt="screen shot 2018-09-11 at 07 47 18" src="https://user-images.githubusercontent.com/6546590/45342830-05fdac00-b597-11e8-840b-fbba00c8eb5a.png">

**Comment by jbrooksuk** [comment]
Is this still an issue for you @TheoBearman? It seems like the database settings may have changed?

**Comment by TheoBearman** [comment]
Removed and readded database user and all systems now operational. No idea why it happened as I hadn't changed any of the database settings. Thanks!

**Comment by jbrooksuk** [comment]
Odd!

Thanks for the update.
