### ISSUE TITLE
Setup page requires a mail username

### ISSUE THREAD

**Issue by jcmcken** [CachetHQ/Cachet#3244]
The setup page seems to require a mail host login username (but doesn't require a password). I think the username and password should both be optional.

In my specific use case, I'm setting the mail host to ``127.0.0.1``, because my local host already has mail forwarding configured correctly. So I don't need any credentials to send mail

**Comment by jbrooksuk** [comment]
We can make the username optional. It's just validation.

For the time being, update the `.env` file `MAIL_*` settings.

**Comment by jbrooksuk** [comment]
Fixed in 6a53e21354ba004e0cebb133506e0c065eac639f
