### ISSUE TITLE
500 error

### ISSUE THREAD

**Issue by haer0248** [CachetHQ/Cachet#3245]
![image](https://user-images.githubusercontent.com/25150003/45587022-63488300-b932-11e8-94aa-20ced7017893.png)

**/var/www/Cachet/.env**
APP_ENV=production
APP_DEBUG=false
APP_URL=http://statust.<HIDDEN>
APP_KEY=base64:EkaN4p5JdueSQMnhgv/l2OHBvbmmLYzTUgtQ/nh96T0=

DB_DRIVER=mysql
DB_HOST=localhost
DB_DATABASE=cachet
DB_USERNAME=cachet
DB_PASSWORD=**HIDDEN**
DB_PORT=null
DB_PREFIX=null

CACHE_DRIVER=file
SESSION_DRIVER=file
QUEUE_DRIVER=sync
CACHET_EMOJI=false

MAIL_DRIVER=smtp
MAIL_HOST=smtp.gmail.com
MAIL_PORT=587
MAIL_USERNAME=**HIDDEN**
MAIL_PASSWORD=**HIDDEN**
MAIL_ADDRESS=**HIDDEN**
MAIL_NAME="Online Status"
MAIL_ENCRYPTION=tls

REDIS_HOST=null
REDIS_DATABASE=null
REDIS_PORT=null

GITHUB_TOKEN=null

**/var/log/apache2/error.log**
[Sat Sep 15 13:56:42.950638 2018] [mpm_prefork:notice] [pid 7177] AH00163: Apache/2.4.29 (Ubuntu) configured -- resuming normal operations
[Sat Sep 15 13:56:42.950741 2018] [core:notice] [pid 7177] AH00094: Command line: '/usr/sbin/apache2'

Please help me ;(

**Comment by VeekeeFr** [comment]
Hello

Could you set
APP_DEBUG=true
It will show the true error and be more helpful than a standard 500 error code.

Regards

**Comment by snandam** [comment]
I'm getting the same error while using docker-compose


`cachet_1    | #4 /var/www/html/vendor/larav" while reading response header from upstream, client: 172.18.0.1, server: localhost, request: "GET /setup HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "localhost"
cachet_1    | [22-Oct-2018 18:13:15] WARNING: [pool www] child 77 said into stderr: "NOTICE: PHP message: [2018-10-22 18:13:15] development.ERROR: RuntimeException: No supported encrypter found. The cipher and / or key length are invalid. in /var/www/html/vendor/laravel/framework/src/Illuminate/Encryption/EncryptionServiceProvider.php:45"
cachet_1    | [22-Oct-2018 18:13:15] WARNING: [pool www] child 77 said into stderr: "Stack trace:"
cachet_1    | [22-Oct-2018 18:13:15] WARNING: [pool www] child 77 said into stderr: "#0 /var/www/html/vendor/laravel/framework/src/Illuminate/Encryption/EncryptionServiceProvider.php(25): Illuminate\Encryption\EncryptionServiceProvider->getEncrypterForKeyAndCipher('Ay3wwcBVTTEWBss...', 'AES-256-CBC')"
cachet_1    | [22-Oct-2018 18:13:15] WARNING: [pool www] child 77 said into stderr: "#1 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Container.php(731): Illuminate\Encryption\EncryptionServiceProvider->Illuminate\Encryption\{closure}(Object(Illuminate\Foundation\Application), Array)"
cachet_1    | [22-Oct-2018 18:13:15] WARNING: [pool www] child 77 said into stderr: "#2 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Container.php(629): Illuminate\Container\Container->build(Object(Closure), Array)"
cachet_1    | [22-Oct-2018 18:13:15] WARNING: [pool www] child 77 said into stderr: "#3 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(697): Illuminate\Container\Container->make('encrypter', Array)"
cachet_1    | [22-Oct-2018 18:13:15] WARNING: [pool www] child 77 said into stderr: "#4 /var/www/html/vend..."
cachet_1    | 172.18.0.1 - - [22/Oct/2018:18:13:15 +0000] "GET /setup HTTP/1.1" 500 3165 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/69.0.3497.100 Safari/537.36" "-"
cachet_1    | 172.18.0.1 - - [22/Oct/2018:18:13:15 +0000] "GET /favicon.ico HTTP/1.1" 200 952 "http://localhost/setup" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/69.0.3497.100 Safari/537.36" "-"`

**Comment by GrahamCampbell** [comment]
It looks like the openssl extension is missing from your server. Please make sure you have it installed and available for fpm to use too, and that you have also followed the instructions at https://docs.cachethq.io/docs/installing-cachet

**Comment by snandam** [comment]
Not totally clean what you meant. The error I was seeing is when running the docker images. Also can you point me to docs where openssl requirement is documented please?
