### ISSUE TITLE
Add a link to a Twitter page

### ISSUE THREAD

**Issue by waqark3389** [CachetHQ/Cachet#3249]
I am trying to add a link to a Twitter page just below the banner. In the older versions it was possible to add a "About this page" section but this seems to have disappeared now. Whats the alternative now? 

I'm not sure what version I am on as the VERSION file in the root directory is showing version:  2.3.9 but on the dashboard it is showing 2.4.0-dev.

**Comment by anthonybocci** [comment]
This is not supposed to be in the issues, so thank you for having closed it and moved on Slack.

As you said there is an "About this page" field in the settings, and that's this information that is supposed to be shown on the status page (as you can see on the demo).
What you pointed out is there was a problem with that, this information was no longer shown.

I've fixed that point, I'll submit a pull request as soon as possible.

In de172e5defa4ac226044e3066413487fdee49de0 the VERSION file contains 2.4.0-dev, I guess you are not up to date.
