### ISSUE TITLE
How to hook a linux server to this status page?

### ISSUE THREAD

**Issue by a-w11** [CachetHQ/Cachet#3252]
Hello,

I have some linux servers and how I can hook this into this status page with automatically refresh?

Give me some docs please I wan’t to understandt this software.

**Comment by jbrooksuk** [comment]
Cachet doesn't monitor anything, so there isn't a built in way of doing this. Instead, I'd suggest checking out https://docs.cachethq.io/docs/addons and adding a monitoring system there.
