### ISSUE TITLE
No Subscribe Button Appearing

### ISSUE THREAD

**Issue by pacit-tech** [CachetHQ/Cachet#3253]
I have configured mailgun and selected the tick box to allow subscribers but there is no subscribe button showing.

    'enable_subscribers' => '1',

![image](https://user-images.githubusercontent.com/20848373/45922775-3addfd00-becd-11e8-9718-a3af36ef139a.png)

Strangely, when i change this tickbox to unchecked,  enable_subscribers is still 1.

**Comment by thnilsen** [comment]
Make sure MAIL_PASSWD is set in .env, as the Subscribe button will not show up before that is present. Just found this issue myself on a 2.3.15 install.

**Comment by Didr** [comment]
In version 2.3 the check to enable the subscribe-button looks like this:
```
    function subscribers_enabled()
    {
        $isEnabled = Config::get('setting.enable_subscribers', false);
        $mailAddress = Config::get('mail.from.address', false);
        $mailFrom = Config::get('mail.from.name', false);

        return $isEnabled && $mailAddress && $mailFrom;
    }
```

This means that the "Allow people to signup" needs to be set, a "From" address has to set and finally a "From" name. I'm unsure if null constitutes a false since my .env looks like this and works just fine after I set MAIL_NAME:

```
MAIL_DRIVER=sendmail
MAIL_HOST=null
MAIL_PORT=null
MAIL_USERNAME=null
MAIL_PASSWORD=null
MAIL_ADDRESS=no-reply@cachet.test
MAIL_NAME="Cachet"
MAIL_ENCRYPTION=null

```

**Comment by jbrooksuk** [comment]
The above is correct. We changed how this works in 2.4
