### ISSUE TITLE
Suggestion / request: use Dependabot to keep dependencies up-to-date

### ISSUE THREAD

**Issue by greysteil** [CachetHQ/Cachet#3255]
First of all, thanks for Cachet!

I've got a suggestion / request: would you be up for using [Dependabot](https://dependabot.com) to automatically create dependency update PRs for this Cachet? I ran it against my fork and it generated [these PRs](https://github.com/greysteil/Cachet/pulls). I'll port the `zendframework/zend-diactoros` PR over to this repo now.

I built Dependabot, but I'm honestly only suggesting it because I hope it can save you some time. I'd love any feedback, and obviously having a repo like Cachet using Dependabot would help boost its profile, but if it's not helpful to you then it's not really worth anything.

You can install it from [here](https://github.com/apps/dependabot) or [here](https://github.com/marketplace/dependabot) if you decide to give it a try. 🙏

**Comment by nstapelbroek** [comment]
I'd love to see this in Cachet. The interface allows configuring specific branches so it should work in the branching model of Cachet. 

![screenshot from 2018-10-16 21-41-35](https://user-images.githubusercontent.com/3368018/47042826-801fe280-d18c-11e8-948e-f1e8c257b8f9.png)

**Comment by jbrooksuk** [comment]
@greysteil thanks for the suggestion, you've built a great product there. Dependabot is now in use across Cachet (and my other projects!)
