### ISSUE TITLE
Multiple components or component group for an incident or scheduled maintenance.

### ISSUE THREAD

**Issue by aegiap** [CachetHQ/Cachet#3258]
When creating a new incident or scheduled maintenance, I can choose onlye one service or product in the component list. Sometimes a technical issue impacts multiple services and I would like to avoid creating an incident per component. 

I would like to be able to select multiple component for an incident or scheduled maintenance. At least, I would like to be able to select a component group in which I added all the impacted components.

Thank you

**Comment by JoshWeepie** [comment]
We strongly support this feature request. I tried for a few hours to get this implemented, but unsure of how best to proceed. Unfortunately it seems like this project is pretty dead :pensive:

**Comment by djmaze** [comment]
> Unfortunately it seems like this project is pretty dead :pensive: 

@JoshWeepie Where do you get the that impression from? The [numbers](https://github.com/CachetHQ/Cachet/pulse/monthly) tell a different story.

**Comment by JoshWeepie** [comment]
The easy interim fix on this would probably be making the component group selectable instead of just individual components. For users with more than two components in a group the real fix would probably be a multiselect dropdown of some sort.

**Comment by jbrooksuk** [comment]
Thank you for your input on Cachet 2.x. We are shifting our attention and resources to Cachet 3.x and will no longer be supporting the 2.x version. If your feedback or issue is relevant to the 3.x series, we encourage you to engage with the new branch.

For more information on the Cachet rebuild and our plans for 3.x, you can read the announcement [here](https://github.com/CachetHQ/Cachet/discussions/4342).

We appreciate your understanding and look forward to your contributions to the new version.
