### ISSUE TITLE
Missing database.sqlite

### ISSUE THREAD

**Issue by jesobreira** [CachetHQ/Cachet#3259]
The [installing docs](https://docs.cachethq.io/docs/installing-cachet) tells:

> If you're using SQLite then your .env file should not contain a DB_HOST key. You'll also need to touch ./database/database.sqlite and give it the required permissions.

However, `database/.gitignore` tells git to ignore any .sqlite file.

What is this file supposed to be? An empty newly-created SQLite3 database didn't work, whereas:

```
$ php artisan app:install
Clearing settings cache...
Settings cache cleared!
Backup skipped: SQLite is not supported.
Application key [...] set successfully.
Configuration cache cleared!
Configuration cached successfully!
Route cache cleared!
Routes cached successfully!
Copied Directory [/vendor/roumen/feed/src/views] To [/resources/views/vendor/feed]
Publishing complete for tag []!


  [InvalidArgumentException]
  Database (cachet) does not exist.
```

Is "SQLite is not supported" related to my server or to the backup routine? 'Cause my server does support SQLite...

**Comment by jbrooksuk** [comment]
You need to create this file. The `.gitignore` file ignores the SQLite database because we don't want this to be overwritten by changes from the core code.

**Comment by jesobreira** [comment]
Where can I find the database scheme/structure? Creating an empty database with sqlite command didn't work...

**Comment by jbrooksuk** [comment]
I’ve only ever had to run `touch database/database.sqlite` and it worked.
