### ISSUE TITLE
Multi-Factor Authentication

### ISSUE THREAD

**Issue by benwa** [cachethq/Cachet#326]
Support for MFA would be awesome.  According to [Authy](https://authy.com/developers), it's doable very quickly if you use their REST endpoint, though they also have [libraries](https://github.com/authy) if that would be more appropriate.

**Comment by jbrooksuk** [comment]
Yeah, this is something we could add quite easily. It'd be opt in of course.

**Comment by nodesocket** [comment]
Is you use a service such as Authy that would require each person who wants to run Cachet to signup for them. It would be better to use a fully native Google Authenticator library. Unfortunately I haven't been able to find any decent ones in php. I'm really tempted to use a node.js project (https://github.com/markbao/speakeasy) which seems solid and renders the QR codes.

**Comment by kfrankperson** [comment]
I would like to see 2FA for Cachet but I think it would need to be Google's 2FA as @nodesocket has said.

**Comment by nodesocket** [comment]
FYI, we [Commando.io](https://commando.io) currently use [GAuthify](https://www.gauthify.com) but we also looking for solid php native library without relying on a 3rd party service.

**Comment by jbrooksuk** [comment]
I was looking yesterday but everything returns Authy. Is there really no library that handles it?

**Comment by nodesocket** [comment]
Most libraries are old and seem abandoned and not maintained:

https://github.com/PHPGangsta/GoogleAuthenticator
https://github.com/chregu/GoogleAuthenticator.php

Of course there are solid ruby gems, but not finding anything good for php:

https://github.com/jaredonline/google-authenticator

**Comment by jbrooksuk** [comment]
I see another project coming on... /s

**Comment by joecohens** [comment]
:+1:

**Comment by nodesocket** [comment]
@jbrooksuk we'd be willing to sponsor some development of a **solid** and **secure** php implementation of Google Authenticator including generating QR codes with no 3rd party dependencies besides the call to google images for the QR. How long did you think it would take?

**Comment by jbrooksuk** [comment]
What about [this](https://github.com/scheb/two-factor-bundle) package?

**Comment by jbrooksuk** [comment]
Actually, [this](https://github.com/antonioribeiro/google2fa).

**Comment by nodesocket** [comment]
Winner, winner, chicken dinner.

https://github.com/antonioribeiro/google2fa

Looks solid! Thanks, will play around with it.

**Comment by jbrooksuk** [comment]
Saves re-inventing the wheel and you guys some dollar :) we could definitely implement it into Cachet too.

**Comment by jbrooksuk** [comment]
It's coming along!

**Comment by jbrooksuk** [comment]
Done in #342 but it first needs testing before I can merge it.

**Comment by jbrooksuk** [comment]
Merged!
