### ISSUE TITLE
Recurring or available time period

### ISSUE THREAD

**Issue by hcelik** [CachetHQ/Cachet#3260]
Hi,

First of all, thanks for the tool! It is very helpful.

I have added a component that available only from 8AM to 6PM every week day. 
I think it will be interesting if we can specify an available period for component or a recurring downtime.
For example, a customer support phone, available only from 8am to 6pm.

And the display outside business hours can only be orange with the message out of the available period.

Thanks!

**Comment by jbrooksuk** [comment]
@hcelik thanks for adding this issue.

I'm not sure how useful this is as a whole, for a generic solution such as Cachet.

Instead, if I were you, I'd create a cron job which automatically updates this component using the API outside of the hours you're open.
