### ISSUE TITLE
LDAP Support

### ISSUE THREAD

**Issue by asham0** [CachetHQ/Cachet#3261]
Hi,
 I have installed CachetHQ version 2.4.0-dev, I just want to know does it support integration with LDAP.

Please let me know ASAP

Thank You!

**Comment by asham0** [comment]
Hello Team,

Please let us know ASAP

Thank you!

**Comment by GrahamCampbell** [comment]
LDAP is not currently supported, but if you'd like to implemented, we'll happily review the PR.

**Comment by jbrooksuk** [comment]
Duplicate of https://github.com/CachetHQ/Cachet/issues/2108
