### ISSUE TITLE
2.4 scheduled maintance not displayed.

### ISSUE THREAD

**Issue by rovox** [CachetHQ/Cachet#3262]
Hi there,

Just updated to 2.4.0 and after i create a maintance its not shown on the frontpage. In the past it showed as comming in x hours. But now its not visible, Looks like a bug to me?

![image](https://user-images.githubusercontent.com/6184352/46106853-22762700-c1da-11e8-95e4-80c80073ea9f.png)
![image](https://user-images.githubusercontent.com/6184352/46106872-31f57000-c1da-11e8-8bba-51d0a5285d9c.png)

- Robert

**Comment by thomasxd24** [comment]
I made a PR revert a commit that made it dissappear #3266

**Comment by jbrooksuk** [comment]
Fixed in https://github.com/CachetHQ/Cachet/pull/3266
