### ISSUE TITLE
Adding Estonian support for Cachet on Crowdin

### ISSUE THREAD

**Issue by schweizerbolzonello** [CachetHQ/Cachet#3263]
Hello,

Please consider adding the support of Estonian language on Crowdin for Cachet (especially that you are already supporting Finnish) to be translated to

Also could be added : Latvian, Lithuanian

Thanks !
-Thomas

**Comment by jbrooksuk** [comment]
Estonian has been enabled on CrowdIn. I look forward to your contributions :)
