### ISSUE TITLE
Sessions is not persistent 

### ISSUE THREAD

**Issue by praneet12** [CachetHQ/Cachet#3264]
Everything is working fine on local. But in production it always takes the session of last logged user. Suppose I have login in the system and after sometimes someone else logged in the system. Then my session changed to his session and I am able to access his account.

**Comment by praneet12** [comment]
Is this is problem with particular version of Cachet ?

**Comment by jbrooksuk** [comment]
Can you show me the `CACHE_DRIVER` value in your `.env` file please?

**Comment by jbrooksuk** [comment]
This sounds like a misconfiguration.

**Comment by praneet12** [comment]
It is database. I have removed this line from nginx-site.config file then everything is working fine.
# fastcgi_cache  microcache;
       # fastcgi_cache_key $scheme$host$request_uri$request_method;
       # fastcgi_cache_valid 200 301 302 30s;
       # fastcgi_cache_use_stale updating error timeout invalid_header http_500;

      #  fastcgi_pass_header Set-Cookie;
      #  fastcgi_pass_header Cookie;
       # fastcgi_ignore_headers Cache-Control Expires Set-Cookie;

       # fastcgi_cache_bypass $no_cache;
       # fastcgi_no_cache $no_cache;

**Comment by jbrooksuk** [comment]
👌🏻

**Comment by praneet12** [comment]
Hey Can you tell me what is the issue ? What happen when I remove this line ?

**Comment by praneet12** [comment]
*Yes from our document*


*Praneet Drolia *
*8102075577,7992430856*

**Comment by praneet12** [comment]
Hey this problem is not there in docs. It is in docker file . So please
remove this line from nginx-site.config file in docker .

*Praneet Drolia *
*8102075577,7992430856*

**Comment by jbrooksuk** [comment]
@djdefi could you look into the above, please?
