### ISSUE TITLE
[2.4-dev] Mismatch in validation rules component?

### ISSUE THREAD

**Issue by TakeMeNL** [CachetHQ/Cachet#3269]
Hi there,

When creating a new component description is required. But when modifying not?

https://github.com/CachetHQ/Cachet/blob/a7789dc1a6723fa7d7f0097b53f433e274f06da0/app/Bus/Commands/Component/CreateComponentCommand.php#L84
https://github.com/CachetHQ/Cachet/blob/a7789dc1a6723fa7d7f0097b53f433e274f06da0/app/Bus/Commands/Component/UpdateComponentCommand.php#L95

Love too fix this but what is right?

**Comment by jbrooksuk** [comment]
Closed by https://github.com/CachetHQ/Cachet/pull/3362
