### ISSUE TITLE
Custom Favicon

### ISSUE THREAD

**Issue by benwa** [cachethq/Cachet#327]
Allow for a custom favicon to be set with a fallback to the default checkmark logo.

Possibly support to the "obsessive-level" in [audreyr/favicon-cheat-sheet](https://github.com/audreyr/favicon-cheat-sheet)

**Comment by jbrooksuk** [comment]
The problem with a custom icon is that we could only really easily support non-Heroku installations. Heroku doesn't have a permanent data store so when you upload then restart the app or upgrade, it'll be lost. 

We get round the banner by storing the base64 data in the DB. That's not really doable for a favicon.

**Comment by benwa** [comment]
What if it is enabled only for non-Heroku installs?

Favicons can actually be loaded from base64. Its how most dynamic favicon notification libraries set it. It of course would be browser dependent.

**Comment by jbrooksuk** [comment]
I did not know that a favicon could be base64 - that's awesome! What happens if a spider tries to get your favicon, does it still work?

If so, then we can easily add a favicon uploader to the App Setup panel.

**Comment by benwa** [comment]
I suppose that would depend on the intelligence of the spider.  If it's just looking for "favicon.ico" then it isn't really following standards as that's not really set in stone.
Of course since it isn't really a file like the common (but again, no set standard) practice, the spider would have to just know how to do it.

**Comment by jbrooksuk** [comment]
I wanted to get this done for V1, but with my recent illnesses and thus my time off, I'm pushing this back to V2.

If you want to change the favicon in the mean time you can easily replace the file in `./public/favicon.ico` etc.

**Comment by jbrooksuk** [comment]
Closing in favour of #686
