### ISSUE TITLE
Error ../Foundation/helpers.php on line 146

### ISSUE THREAD

**Issue by heshandh** [CachetHQ/Cachet#3282]
After fixing certain errors, again I found following error when execute "`php artisan key:generate`" command. Can someone help me to fix this please.
Please note that I'm using **sqlite** database

`PHP Parse error:  syntax error, unexpected 'class' (T_CLASS), expecting identifier (T_STRING) or variable (T_VARIABLE) or '{' or '$' in /var/www/Cachet/vendor/laravel/framework/src/Illuminate/Foundation/helpers.php on line 146
`

**Comment by jbrooksuk** [comment]
I’d try removing the `vendor` folder and then running `composer install -o` again

**Comment by GrahamCampbell** [comment]
It looks like perhaps your webserver is using a different version of PHP than cli. Please make sure both are using the same recent version. Latest 7.1 or 7.2 should work great.
