### ISSUE TITLE
Change demo details to example.com

### ISSUE THREAD

**Issue by sideffect0** [CachetHQ/Cachet#3284]
Instead of linking an already existing company domain, it is safe to change the test creds
test@test.com to test@example.com (which itself is for demo purpose)

**Comment by jbrooksuk** [comment]
There's no reason we couldn't change this and to be fair, it makes sense to do this. We'd need to co-ordinate the changes in documentation as well.

Would you like to propose a PR with this change in? 😄

**Comment by GrahamCampbell** [comment]
Thanks for getting in touch. Discussion can continue on the PR. :)

**Comment by jbrooksuk** [comment]
Closed by https://github.com/CachetHQ/Cachet/pull/3287
