### ISSUE TITLE
Components get disabled on updates

### ISSUE THREAD

**Issue by pree** [CachetHQ/Cachet#3288]
Hello !

I have a weird issue with components getting disabled when they are updated via API.
Everytime I update a component with the PUT Method directly on `https://cachet/component/:id` and do not specify `enabled` in the body, the component gets disabled.

BR,
Pascal

**Comment by GrahamCampbell** [comment]
Thanks for reporting this. Are you able to send a PR to fix this please? What versions of Cachet are affected by this bug?

**Comment by TakeMeNL** [comment]
https://github.com/CachetHQ/Cachet/blob/a7789dc1a6723fa7d7f0097b53f433e274f06da0/app/Http/Controllers/Api/ComponentController.php#L127
So this fails if enabled is not given via API, because ```(bool) Binput::get('enabled')``` will be false
