### ISSUE TITLE
Font issues.

### ISSUE THREAD

**Issue by lagseeing** [cachethq/Cachet#329]
The font is really hard to see on windows. 

I'm using windows 8.1 and the lastest google chrome

**Comment by joecohens** [comment]
Hi! Can you share a screenshot please?

**Comment by lagseeing** [comment]
![Blurry text](https://cloud.githubusercontent.com/assets/6233526/5658845/e63bd510-96da-11e4-8912-2dae2c0d628f.png)

**Comment by jbrooksuk** [comment]
Is the size or the weight of the font for you? I'm looking at the screenshot from mobile GitHub.

**Comment by benwa** [comment]
I think it is the font weight.  On Windows 7 at work and it is quite a bit more readable with it off.
![capture](https://cloud.githubusercontent.com/assets/1351571/5663464/431914fc-9715-11e4-9a5e-5a09a7416d2a.PNG)
Left is regular, right is off


At home on OS X, the question mark icons are not very recognizable unless `-webkit-font-smoothing: antialiased` is disabled.

**Comment by jbrooksuk** [comment]
With what turned off sorry, @benwa?

**Comment by benwa** [comment]
The set font weight.

**Comment by jbrooksuk** [comment]
Ok, I'll leave this with @joecohens to play with (or someone else, if they want to have a go).

**Comment by joecohens** [comment]
Sure! I'll set the font smoothing only for retina displays :). Thanks!

**Comment by joecohens** [comment]
I've change the font weight on the status page and set se -webkit-font-smoothing: antialiased; it had a bug. Let me know if everything it's ok now :)
