### ISSUE TITLE
Cachet websites hit CloudFlare by default

### ISSUE THREAD

**Issue by lelutin** [CachetHQ/Cachet#3296]
Hi there,

I just saw that cachet makes all visitors request a small javascript file from CloudFlare. I'm currently using 2.3.13, but from what I saw with a search in the code tagged 2.3.15 it's still the case.

I don't see the point of forcing everyone to hit up cloudflare by default, and actually for the internal policies here it's rather unwanted.

Since this seems to be done for librairies that would otherwise need to be vendored in your repository, maybe it would be nice to have the build process pull in the librairies from cloudflare, but then place them somewhere so they can be served locally?

**Comment by GrahamCampbell** [comment]
Thanks for getting in touch. Ping @jbrooksuk. What do you make of removing external deps, and packing everything in a local build process?

**Comment by pitchum** [comment]
Just for the record it seems that some work has been started in branch 2.4 with the new setting [`'enable_external_dependencies' => false`]( https://github.com/CachetHQ/Cachet/blob/50bcfb5/config/setting.php#L71:L81 ). But it started 2 years ago and it's still not released.
In the meantime I have followed that documentation (en French): [dégooglisation de Cachet](https://admin.chapril.org/doku.php?id=admin:machines_virtuelles:admin:cachet#degooglisation_de_cachet ).

**Comment by jbrooksuk** [comment]
@pitchum is correct, we do have a way of disabling these external dependencies, but ideally we wouldn't need to hit a third-party for _any_ assets, I'd even say that fonts should be system-first.

**Comment by jbrooksuk** [comment]
The password strength meter is what's pulled in from Cloudflare by the way. We can likely switch to using an NPM module for that.

**Comment by jbrooksuk** [comment]
Truth be told, we don't need it, so 30 mins to remove it is perfect.

**Comment by jbrooksuk** [comment]
We should split this task into removing the password strength and Google Fonts separately.

**Comment by GrahamCampbell** [comment]
Dependency on Cloudflare removed as of https://github.com/CachetHQ/Cachet/pull/3315.

**Comment by lelutin** [comment]
wow! nice, thanks all! you rock as always
