### ISSUE TITLE
No supported encrypter found

### ISSUE THREAD

**Issue by francisv-ets** [CachetHQ/Cachet#3299]
I'm getting this error message:

`cachet_1    | 2018/10/30 07:27:34 [error] 71#71: *7 FastCGI sent in stderr: "PHP message: [2018-10-30 07:27:34] development.ERROR: RuntimeException: No supported encrypter found. The cipher and / or key length are invalid. in /var/www/html/vendor/laravel/framework/src/Illuminate/Encryption/EncryptionServiceProvider.php:45`

### Environment
- docker-compose
- cachet_ver=master and cachet_ver=2.3.15

**Comment by GrahamCampbell** [comment]
Thanks for getting in touch. It looks like you are missing required extensions on your system (make sure the openssl extension is installed on your server and available through fpm as well as cli), or have not set an application key using `php artisan key:generate` as described in https://docs.cachethq.io/docs/installing-cachet.
