### ISSUE TITLE
Incident form error should prefil the originally submitted data

### ISSUE THREAD

**Issue by jbrooksuk** [cachethq/Cachet#330]
If you submit an incident but leave off the status, an error is shown and all form fields are emptied.

**Comment by stuartmacfarlane** [comment]
This appears to be happening again on "2.4.0-dev".

Steps to recreate:
1. Create a new incident.
2. Enter a title and Message.
3. Submit.

The page refreshes and gives the error:
---
Whoops. There was an error adding the incident, please try again.
The status field is required.
---

At which point all form fields are blank and you have to start over again.
