### ISSUE TITLE
Question on Production Version

### ISSUE THREAD

**Issue by boguest** [CachetHQ/Cachet#3312]
What version of Cachet is considered your "production version" versus your "development version"? Should I be using v2.4 or stick with v2.3.15 in my production environment?

**Comment by jbrooksuk** [comment]
2.3 is the **latest** "stable" version, though 2.4 has been used by **many** companies and organisations worldwide with few issues.

**Comment by boguest** [comment]
Ok, what are the major enhancements with v2.4?
