### ISSUE TITLE
Remove RSS Feeds

### ISSUE THREAD

**Issue by GrahamCampbell** [cachethq/cachet#3313]
https://twitter.com/GrahamJCampbell/status/1057654707810910208

**Comment by jbrooksuk** [comment]
@GrahamCampbell can you remember where this spawned from? I seem to recall a conversation we had about it.

Was it because Firefox dropped support of their RSS reader?

**Comment by sbarrier** [comment]
To bad that you decided to drop RSS support.It's still used by millions of users daily.

**Comment by jbrooksuk** [comment]
@sbarrier I'm actually contemplating bringing this back as in hindsight, I think a lot of people do still use RSS and that it serves a lot of uses.
