### ISSUE TITLE
Address Google Fonts Dependency

### ISSUE THREAD

**Issue by GrahamCampbell** [CachetHQ/Cachet#3317]
I think this may be an acceptable default, but we should allow people to opt-out.

---

Relates to #3296.

**Comment by jbrooksuk** [comment]
With the new theming system that I’ve been working on, this will be up to each theme. Howevto, the default theme will be without third-party services.

**Comment by szepeviktor** [comment]
Google Font is a strange service.
It **is** UA-depedent ([try](https://fonts.googleapis.com/css?family=Open+Sans:300,400,700&subset=latin) in modern Firefox and in IE 11 and see the result).

Although "user-agent" is missing from the `Vary:` HTTP header!

So it is [very hard to replicate](https://github.com/majodev/google-webfonts-helper) its service locally.

**Comment by GrahamCampbell** [comment]
Ping @jbrooksuk

**Comment by jbrooksuk** [comment]
I'm going to remove Google Fonts from the new theme.

**Comment by szepeviktor** [comment]
An option has been added: https://github.com/CachetHQ/Cachet/commit/57aef06927421d86d4845f0bf3594e860ef7c7f4#diff-1a116b5d4c79ba12a1bcad639c9c300eR49
