### ISSUE TITLE
Components lost?

### ISSUE THREAD

**Issue by Lichengchang** [CachetHQ/Cachet#3324]
Hi,

In mysql of  components table have TW12 - TW15, following :
![ca1](https://user-images.githubusercontent.com/25293877/48334905-1c0f1200-e697-11e8-8271-ad5ae55df814.png)

But not found TW12-TW15 in API and some components is lost following :
![ca2](https://user-images.githubusercontent.com/25293877/48335078-a3f51c00-e697-11e8-8eca-f9bb7518228e.png)

I hope someone can point me in a direction.
Thx.

**Comment by bonfire-dev** [comment]
Check here - https://docs.cachethq.io/docs/advanced-api-usage#section-pagination. You have a total of 52 items but by default, per_page is set to 20. So you are seeing the first 20 items in your result. Probably you may have to try http://<your_url>/api/v1/components?per_page=52

**Comment by jbrooksuk** [comment]
@bonfire-dev this looks to be the answer, thank you!
