### ISSUE TITLE
Incident Form Data Lost on Submission

### ISSUE THREAD

**Issue by stuartmacfarlane** [CachetHQ/Cachet#3325]
Same issue as this one:
https://github.com/CachetHQ/Cachet/issues/330

Running v2.4.0-dev

Steps to recreate:

1.Create a new incident.
2.Enter a title and Message.
3.Submit.

The page refreshes and gives the error:

**Whoops. There was an error adding the incident, please try again.
The status field is required.**

At which point all form fields are blank and you have to start over again.

**Comment by jbrooksuk** [comment]
Ah, this is because we're using a Vue component on the frontend. We need to pass through all of the old data back to the component.

**Comment by jbrooksuk** [comment]
Thank you for your input on Cachet 2.x. We are shifting our attention and resources to Cachet 3.x and will no longer be supporting the 2.x version. If your feedback or issue is relevant to the 3.x series, we encourage you to engage with the new branch.

For more information on the Cachet rebuild and our plans for 3.x, you can read the announcement [here](https://github.com/CachetHQ/Cachet/discussions/4342).

We appreciate your understanding and look forward to your contributions to the new version.
