### ISSUE TITLE
rename "past incidents"

### ISSUE THREAD

**Issue by SunnyTeater** [CachetHQ/Cachet#3327]
Hey guys,

i just asking if its possible to change the header "past incidents" to only "incidents" for my status page.
I think it sounds wrong when people only see current incidents.

Sorry, but im not familiar with coding, thats why im asking :)

**Comment by jbrooksuk** [comment]
Hi @SunnyTeater, good question. It's possible to edit the language files which are responsible for the text. You can find them in `./resources/lang/{code}/`.

**Comment by SunnyTeater** [comment]
@jbrooksuk  found it, changed it :) 
Thank you.
