### ISSUE TITLE
Export and import of data

### ISSUE THREAD

**Issue by jbrooksuk** [cachethq/Cachet#333]
Data is of course owned by the person running the instance of Cachet and as such we should offer a way to get your data out of Cachet into some kind of export file.

From that, you should be able to import existing data into a new instance of Cachet.

**Comment by jbrooksuk** [comment]
Looking back at this I'd say export your DB :)

**Comment by jetie** [comment]
I'm new here, but find it tough to follow the logic of this post, you ask for something, you restate it differently, you close it, you modify a milestone. Was this feature implemented then? Thanks for your patience.

**Comment by ConnorVG** [comment]
James wanted to add an export / import feature to the Cachet dashboard. He later decided there is no need to this as anyone who would have such access would also have access to the database so it'll be logical to instead use the database's export and import functionality.

**Comment by jetie** [comment]
Now I follow. Thanks Connor.
