### ISSUE TITLE
Error in vendor file on count() usage

### ISSUE THREAD

**Issue by nightkingdoms** [CachetHQ/Cachet#3331]
Having to deal with this particular error myself converting over to Laravel 5.7.  PHP is 7.2.10, Cachet is set to use tag v2.3.9.  Followed instructions to the letter on a brand new install. Getting this in the Apache logs, zero logs in the storage directory (777).  It throws a 500 error after going to the homepage and self-redirecting to /setup.

[Thu Nov 15 01:24:48.690237 2018] [php7:error] [pid 1064] [client XX.XXX.XXX.XXX:56866] PHP Fatal error:  Uncaught ErrorException: count(): Parameter must be an array or an object that implements Countable in /var/www/html/Cachet/vendor/graham-campbell/exceptions/src/ExceptionIdentifier.php:51\nStack trace:\n#0 [internal function]: Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleError(2, 'count(): Parame...', '/var/www/html/s...', 51, Array)\n#1 /var/www/html/Cachet/vendor/graham-campbell/exceptions/src/ExceptionIdentifier.php(51): count(NULL)\n#2 /var/www/html/Cachet/vendor/graham-campbell/exceptions/src/ExceptionHandlerTrait.php(47): GrahamCampbell\\Exceptions\\ExceptionIdentifier->identify(Object(ErrorException))\n#3 /var/www/html/Cachet/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(79): GrahamCampbell\\Exceptions\\ExceptionHandler->report(Object(ErrorException))\n#4 [internal function]: Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleException(Object(ErrorException))\n#5 {main}\n  thrown in /var/www/html/Cachet/vendor/graham-campbell/exceptions/src/ExceptionIdentifier.php on line 51

[Thu Nov 15 01:24:48.690686 2018] [php7:error] [pid 1064] [client XX.XXX.XXX.XXX:56866] PHP Fatal error:  Uncaught ErrorException: count(): Parameter must be an array or an object that implements Countable in /var/www/html/Cachet/vendor/graham-campbell/exceptions/src/ExceptionIdentifier.php:51\nStack trace:\n#0 [internal function]: Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleError(2, 'count(): Parame...', '/var/www/html/s...', 51, Array)\n#1 /var/www/html/Cachet/vendor/graham-campbell/exceptions/src/ExceptionIdentifier.php(51): count(NULL)\n#2 /var/www/html/Cachet/vendor/graham-campbell/exceptions/src/ExceptionHandlerTrait.php(47): GrahamCampbell\\Exceptions\\ExceptionIdentifier->identify(Object(Symfony\\Component\\Debug\\Exception\\FatalErrorException))\n#3 /var/www/html/Cachet/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(79): GrahamCampbell\\Exceptions\\ExceptionHandler->report(Object(Symfony\\Component\\Debug\\Exception\\FatalErrorException))\n#4 /var/www/html/Cachet/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.p in /var/www/html/Cachet/vendor/graham-campbell/exceptions/src/ExceptionIdentifier.php on line 51

**Comment by jbrooksuk** [comment]
Cachet 2.3 doesn’t support PHP 7. You’ll need to upgrade to 2.4.
