### ISSUE TITLE
Command "app:install" is not defined.

### ISSUE THREAD

**Issue by zhujitop** [CachetHQ/Cachet#3358]
php artisan app:install

Tips：
Command "app:install" is not defined.  
                                         
  Did you mean one of these?             
      app:name                           
      app:reset                          
      app:update                         
      cachet:install                     
      migrate:install   
![image](https://user-images.githubusercontent.com/35312148/49664938-4f727000-fa8e-11e8-87ca-19d18958eae3.png)

configuration setting
centos7
php7.2
Cachet2.4

**Comment by Didr** [comment]
Hi,
In Cachet 2.4 the php artisan command "app:install" was renamed to "cachet:install". Give that a try and see if it works.

**Comment by jbrooksuk** [comment]
@Didr is correct :)
