### ISSUE TITLE
Component's updated_at field not updating

### ISSUE THREAD

**Issue by cmardle** [cachethq/cachet#3361]
When I make an API call to a component the updated_at field only updates to the current time if the status actually changes - i.e. If I send a request to update a component from Operational to Operational the update_at timestamp does not change.

I have automated monitoring setup to update the components status regularly, and I want the timestamp to reflect the most recent time the component was checked.

The other option would be to send a PUT request to manually change the updated_at field with the current time, however when I do this it causes the status to be set to 'cachet.components.status.0' and doesn't even update the time field.

Example:
Call: `[2018-12-13 13:22.54] curl -X PUT http://status.domain.com/api/v1/components/4 -H "Content-type: application/json" -H "X-Cachet-Token: <token omitted>" -d "{\"updated_at\":date +%s}"`
Result:
`{"data":{"id":4,"name":"Component Four","description":"","link":"https:\/\/www.component-four.com","status":0,"order":0,"group_id":1,"created_at":"2018-12-12 15:13:15","updated_at":"2018-12-13 13:22:42","deleted_at":null,"enabled":true,"status_name":"cachet.components.status.0","tags":[]}} `

EDIT: Already reached out on slack and was told to raise an issue, also I see there was a similar issue raised on here but it was closed with no resolution

**Comment by jbrooksuk** [comment]
@joecohens or @GrahamCampbell have either of you had experience with this issue?
