### ISSUE TITLE
production.ERROR: ReflectionException: Class 

### ISSUE THREAD

**Issue by Dream-cake** [CachetHQ/Cachet#3364]
[2018-12-16 02:13:29] production.ERROR: ReflectionException: Class CachetHQ\Cachet\Integrations\Contracts\Feed does not exist in /var/www/html/Cachet/bootstrap/cache/compiled.php:1381

Lastest Build

Site: status.dreamingbot.net

happends goes to /dashboard or redirects

**Comment by jbrooksuk** [comment]
Can you run `rm -rf bootstrap/cache{,t}/*` please.

**Comment by jbrooksuk** [comment]
Ping @GrahamCampbell. This is a weird one?

**Comment by Dream-cake** [comment]
so what do i do?

@GrahamCampbell or @jbrooksuk

**Comment by Dream-cake** [comment]
any update?

**Comment by Dream-cake** [comment]
![image](https://user-images.githubusercontent.com/31389391/50370331-adb14f80-0572-11e9-891a-2045e34d84e3.png)
Here is the debug image

**Comment by Dream-cake** [comment]
tryed doing composer install --no-dev -o still nothing

**Comment by Dream-cake** [comment]
fixed by update
