### ISSUE TITLE
Unknown column 'notify' in 'where clause' 

### ISSUE THREAD

**Issue by jayze** [CachetHQ/Cachet#3366]
Hi,

When using the API to create an incident I'm getting an error 500 and the following error message in the log:

Next Illuminate\Database\QueryException: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'notify' in 'where clause' (SQL: select count(*) as aggregate from `incidents` where `visible` >= 1 and (`name` = test incident and `message` = This is a test incident created via API calls and `status` = 1 and `visible` = 1 and `notify` = 1) and `incidents`.`deleted_at` is null)

I'm running 2.4.0-dev
any suggestions?

Jay

**Comment by jbrooksuk** [comment]
You may need to run `php artisan migrate`?

**Comment by jayze** [comment]
Hi,

Yes I've followed the upgrade documentation.

But ran it again to be sure, this is the output.
**************************************
*     Application In Production!     *
**************************************

 Do you really wish to run this command? (yes/no) [no]:
 > yes

Nothing to migrate.

**Comment by jbrooksuk** [comment]
@jayze this is weird... can you show me the structure of your `incidents` table please.

Also, the column looks to be called `notifications` as opposed to `notify`. I'll take a look.

**Comment by jbrooksuk** [comment]
@jayze sorry, can you also confirm what the output of `git rev-parse HEAD` is if you run it within the Cachet directory (assuming you pulled down with Git?)

**Comment by jayze** [comment]
git rev-parse HEAD
a7789dc1a6723fa7d7f0097b53f433e274f06da0

Structure of the table:
```
MariaDB [cachet]> describe incidents;
+---------------+------------------+------+-----+---------+----------------+
| Field         | Type             | Null | Key | Default | Extra          |
+---------------+------------------+------+-----+---------+----------------+
| id            | int(10) unsigned | NO   | PRI | NULL    | auto_increment |
| user_id       | int(10) unsigned | YES  | MUL | NULL    |                |
| component_id  | int(11)          | NO   | MUL | 0       |                |
| name          | varchar(191)     | NO   |     | NULL    |                |
| status        | int(11)          | NO   | MUL | NULL    |                |
| visible       | tinyint(1)       | NO   | MUL | 1       |                |
| stickied      | tinyint(1)       | NO   | MUL | 0       |                |
| notifications | tinyint(1)       | NO   |     | 0       |                |
| message       | longtext         | NO   |     | NULL    |                |
| occurred_at   | timestamp        | YES  |     | NULL    |                |
| created_at    | timestamp        | YES  |     | NULL    |                |
| updated_at    | timestamp        | YES  |     | NULL    |                |
| deleted_at    | timestamp        | YES  |     | NULL    |                |
+---------------+------------------+------+-----+---------+----------------+
13 rows in set (0.00 sec)
```

**Comment by jbrooksuk** [comment]
I've no idea how this has happened.

All of the migrations from 2.3 to 2.4 work perfectly. Can you manually rename this column?

**Comment by jbrooksuk** [comment]
Closing this as unable to replicate, but we can continue the conversation.
