### ISSUE TITLE
Ensure Cachet Commands Respect `--no-interaction`

### ISSUE THREAD

**Issue by GrahamCampbell** [CachetHQ/Cachet#3379]
In particular, the cachet:install command needs to select good defaults automatically (if it can). Perhaps we should allow the command to create an sqlite database on disk?

**Comment by GrahamCampbell** [comment]
> but I think providing sensible defaults is the best option

Yeh, then with sensible defaults, --no-interaction will work properly.

**Comment by GrahamCampbell** [comment]
This bug extends to the framework core commands too.

**Comment by brunob** [comment]
@GrahamCampbell where are we about this feature ? Do you know if we can user cachet:install without any interaction in a salt recipe for example (with an admin account created) ?

**Comment by GrahamCampbell** [comment]
The idea would actually be that the command crashes and says you have to run it with interaction. Rather than just hanging forever waiting for input.

**Comment by brunob** [comment]
@GrahamCampbell thx for answer, so you mean that for now we can't fully install and configure cachet from a script or a salt recipe ?

**Comment by mor120** [comment]
Hey, is there an update regarding this? I looked for a way to automate the initial setup of cachet but couldn't find a way.
Thanks.
