### ISSUE TITLE
 2.3.15 reports as 2.3.14-dev in Dashboard

### ISSUE THREAD

**Issue by LyleDodge** [CachetHQ/Cachet#3385]
While running 2.3.11 I upgraded to 2.3.15 per instructions at https://docs.cachethq.io/docs/updating-cachet which went perfectly smooth--thanks!

Then when I re-visit the app I see 2.3.14-dev for the version at url dashboard/settings/setup

I recognize this is very minor display issue but I'm attaching a screenshot here for clarity. 

<img width="469" alt="screen shot 2018-12-30 at 12 22 16 am" src="https://user-images.githubusercontent.com/7726239/50545455-04e59e80-0bc9-11e9-97f2-49eb09756c6e.png">

**Comment by jbrooksuk** [comment]
@GrahamCampbell are you able to push a version change? I wish we could automate the versioning system here.

**Comment by GrahamCampbell** [comment]
2.3.16 will fix this. :)
