### ISSUE TITLE
Downloadable translation packages

### ISSUE THREAD

**Issue by jbrooksuk** [CachetHQ/Cachet#3398]
I think it'd make more sense if the translations were downloadable packages, rather than packaging **every** language within Cachet itself.

Thoughts?

**Comment by jbrooksuk** [comment]
I was just looking at the CrowdIn translations and I think we'd need to mirror this into a separate repository; https://support.crowdin.com/api/download/ as we need an API key.

**Comment by ArchdukeNavaron** [comment]
How does it work currently?
Is it being downloaded on a regular basis?
Or doesn't it get updated automaticaly?

**Comment by GrahamCampbell** [comment]
> I think it'd make more sense if the translations were downloadable packages, rather than packaging every language within Cachet itself.

That could be cool, or maybe simply maintain the translations as a separate repo?

**Comment by GrahamCampbell** [comment]
There is no real advantage in lazy downloading translations as the files are so small, but there may be an advantage so separating them so the noise isn't so bad on the main repo when there's updates.

**Comment by jbrooksuk** [comment]
Downloadable packages would be good. As you say, the main benefit is simply removing the cruft. What’s the best way of installing a package like translations without wrecking the `composer.lock` file?
