### ISSUE TITLE
 [PDOException] could not find driver PROBLEM WHEN INSTALL

### ISSUE THREAD

**Issue by Minemarc98** [CachetHQ/Cachet#3404]
Hello people,

I have a problem when try to install CachetHQ, when put the command

php artisan app:install

Appears:

php artisan app:install
Clearing settings cache...
Settings cache cleared!
Backing up database...
Dumping database and uploading...
Successfully dumped mysql, compressed with gzip and store it to local at /var/www/html/Cachet/database/backups/XXXXXXXXXXX
Backup completed!
Application key [XXXXXXXXXXXXXXXXX] set successfully.
Configuration cache cleared!
Configuration cached successfully!
Route cache cleared!
Routes cached successfully!
Copied Directory [/vendor/roumen/feed/src/views] To [/resources/views/vendor/feed]
Publishing complete for tag []!
  [PDOException]
  could not find driver

How i can solve this? Thanks!

**Comment by leonardotandeli** [comment]
First, install the PHP-MYSQL:

`sudo apt-get install php7.0-mysql`

Then, find the following line and uncomment:

`;extension=php_pdo_mysql.so`

if the above line not exist, just add in without the ";"

**Comment by Minemarc98** [comment]
I have database in other node, its posible?

I install mariadb-server and added extension=php_pdo_mysql.so in to /etc/php.ini, restarts httpd and mariadb and don't work. 

PD: I use CentOs 7

**Comment by Minemarc98** [comment]
Hello?

**Comment by jbrooksuk** [comment]
MariaDB is not technically supported. I'd suggest using MySQL.

**Comment by jbrooksuk** [comment]
Also, yes, you can use a DB that is hosted on another server.
