### ISSUE TITLE
Subscribers not getting scheduled maintenance emails

### ISSUE THREAD

**Issue by bramassendorp** [CachetHQ/Cachet#3409]
Hi,

Im using Cachet v.2.3.15.

It looks like when subscribers are not subscribed to all the components, they are not receiving scheduled maintenance emails. I hope this is not by design.

Am I doing something wrong?

Thank you.

**Comment by bramassendorp** [comment]
Hi,

Still can't figure out why, at the moment it's a big issue for us. Customers are not getting maintenance notices because mostly all customers are only subscribed to components that are useful for them.

Thank you.

**Comment by jbrooksuk** [comment]
What `QUEUE_DRIVER` are you using? See docs at https://github.com/CachetHQ/Cachet/blob/2.4/docs/setup/configuring-queue.md

**Comment by bramassendorp** [comment]
QUEUE_DRIVER=database

But mail are being send, no issues on that. But when a subscriber is not subscribed to all components, no more maintenance mails are being send out to that user.

**Comment by jbrooksuk** [comment]
Oh, I see...

**Comment by bramassendorp** [comment]
Any update?

**Comment by demarant** [comment]
we have same issue cachet v2.3.15.
we use cachet with around 30 components divided in 5 groups and users often will select only some components. they do not get any maintenance notifications via email.
RSS/Atom do have the maintenance notifications but the situation is not intuitive and confusing for users.

Moreover when scheduling maintenance, one should be able to associate it to a specific component (or several of them) so that only subscribers to those components are notified of maintenance.

**Comment by jbrooksuk** [comment]
Does this work on 2.4?

**Comment by mbrother2** [comment]
@jbrooksuk 

No, this does not work on 2.4. No email have been sent when create maintenance!

**Comment by gcommit** [comment]
It does work, when you are subscribed to all components and added a mailserver correctly. 

For incidents it worked this way: CompanyName-mailrelay.adm.CompanyName.de
For incidents AND maintennce it has to be a public one: mail.CompanyName.de

Is there a way, that everyone, who is subscribed, even not to all components (or better to a special component) receiving the maintenances mails ?

**Comment by astrakid** [comment]
we are facing the same issue! any idea of how to solve it?

**Comment by gcommit** [comment]
> we are facing the same issue! any idea of how to solve it?

I don't know any solution here. I am waiting for some important issues for an answer for almost a year now... such as subscribing, wrong timezones, mail settings not working, etc. 

But for your problem: Notifications will only be send to subscribers with global subscription. As soon as you unsubscribe one single little part, no email for you.

**Comment by useesolutions** [comment]
I am on 2.4-dev. I can get the maintenance emails to send, but it is only sending on the first scheduled maintenance. It will not send out on any maintenance that I scheduled after that fist one. Is this typical?

**Comment by kersthien** [comment]
hi everyone, we have the same problem in cachet v 2.4. are there any updates on this?
