### ISSUE TITLE
Convert API documentation to ReadMe.io

### ISSUE THREAD

**Issue by nodesocket** [cachethq/Cachet#341]
Transition from GItHub API docs to [ReadMe](https://readme.io) *(Free for open-source)*.

**Comment by joecohens** [comment]
Thanks! Definitely we look into it :) we where talking about moving it to the website but I think this solution it's better.

**Comment by jbrooksuk** [comment]
ReadMe.io looks really nice! Definitely worth having a good look at.

**Comment by nodesocket** [comment]
Here is the [Commando.io Doc](http://docs.commando.io) for reference on ReadMe.io.

**Comment by jbrooksuk** [comment]
Looks nice! Cachet would definitely benefit from a better API.

**Comment by joecohens** [comment]
It looks great!

**Comment by gdillon** [comment]
Hey guys, love that you're checking out ReadMe. I'm one of the cofounders and am happy to answer any questions. Documentation is obviously a big deal when you're building for the dev community. And, yes, we support open source projects like Cachet with free plans. Just shoot support@readme.io a note and I will hook you up.

**Comment by jbrooksuk** [comment]
@gdillon awesome! I'll send you an email once I'm home in about an hour or so :)

**Comment by jbrooksuk** [comment]
@gdillon emailed :)

**Comment by jbrooksuk** [comment]
I've setup [cachet.readme.io](http://cachet.readme.io) which will soon be setup as `docs.cachethq.io`. I'll spend some time over the next week moving all the documentation there.

Thanks to the awesome guys at Readme.io cc @gdillon

**Comment by GrahamCampbell** [comment]
Wow, that looks so pretty!

**Comment by jbrooksuk** [comment]
It's nice isn't it! :)

**Comment by gdillon** [comment]
An excellent start, @jbrooksuk! Can't wait to see your progress.

**Comment by jbrooksuk** [comment]
Thanks!

I need to signup to the GitHub import notifier ;)

**Comment by gdillon** [comment]
Just enabled it for you, @jbrooksuk. Will send additional info via email.

**Comment by jbrooksuk** [comment]
You're awesome!

**Comment by joecohens** [comment]
Beautiful!!

**Comment by nodesocket** [comment]
@gdillon I'm curious how to you came across this thread to begin with? :) Do you have a service that scans for `ReadMe.io` in GitHub and sends you alerts?

**Comment by gdillon** [comment]
Hey @nodesocket. Yep, you got it. I use mention.net as a Google Alerts replacement and have it keyed to find "readme.io" which allows me to get mentions of the company and any URLs that are pointing to us. Sorry for being creepy, but happy to have found you guys!

**Comment by jbrooksuk** [comment]
I've moved all documentation to ReadMe.io.

Now I need to go through it all properly and format it.
