### ISSUE TITLE
Piwik/Matamo Issue

### ISSUE THREAD

**Issue by scarecr0w12** [CachetHQ/Cachet#3421]
The Analytics page details "URL of your Piwik instance (without http(s)://)". However, when not including the Http(s):// in the url, the loaded page structures the url as such:

https:// < cachet URL > /< piwik/matamo instance URL >/

So a 404 is created. However including the aforementioned http(s)://, everything loads correctly.

**Comment by scarecr0w12** [comment]
Better example:
piwik instance- https://piwik.domain.com
Cachet instance - https://cachet.domain.com

When NOT including the https:// in the analytics page, the page head code for front end loads:

https://cachet.domain.com/piwik.domain.com/

But when including it in analytics page, It loads head code as:
https://piwik.domain.com/

**Comment by jbrooksuk** [comment]
Thanks for reporting. I think we should require the HTTP(s) prefix.

**Comment by jbrooksuk** [comment]
@scarecr0w12 I've just checked and it looks like the string shouldn't include that. I'll remove it now.
