### ISSUE TITLE
Cachet With Plesk Mail Server

### ISSUE THREAD

**Issue by arkhalid1986** [CachetHQ/Cachet#3424]
Hello,

I have setup the cachet on centos 7 but i am getting problem with mail setting i have made the account at mailtrap.io i have setup the email setting in .env it work fine with mailtrap setting i can see subscribe button and can add subscriber too but problem is if i add any client email they won't get any notification all emails are coming into account in mailtrap.io. How can i set email setting with plesk server i did try to many times i am getting 500 ERROR page.

MAIL_DRIVER=smtp
MAIL_HOST=smtp.mydomain.com
MAIL_PORT=25
MAIL_USERNAME=myemail@mydomain.com
MAIL_PASSWORD=emailpassowrd
MAIL_ADDRESS=myemail@mydomain.com
MAIL_NAME="Status"
MAIL_ENCRYPTION=null

Please tell me how can i resolve this issue?

**Comment by arkhalid1986** [comment]
Also i want to update plesk is installed on other server and cachet is installed on other server.

**Comment by jbrooksuk** [comment]
What `QUEUE_DRIVER` are you using?
