### ISSUE TITLE
Unable to login because setup doesn't create users in the database

### ISSUE THREAD

**Issue by Meghamala-T** [CachetHQ/Cachet#3429]
Hi,
I tried to setup Cachet v2.3.15 in my local. I am using PHP v7.0 , Apache v2.4 and MySQL v8.0.
I have completed all the setup steps and arrived at the login page, but unable to login due to "Invalid username/password" error.When I check the laravel logs, nothing gets logged there.When I check the database tables, there are no users created.
Any pointers on how to overcome this?

**Comment by jbrooksuk** [comment]
Are your database settings correct?

Try out the 2.4 branch :smile

**Comment by jbrooksuk** [comment]
I've just tested out this process on 2.4 and I had a user setup for me.
