### ISSUE TITLE
Provide a way for the default subscribe to not select all components

### ISSUE THREAD

**Issue by arthurzenika** [CachetHQ/Cachet#3430]
Maybe a follow up of #2591 

We have three components groups : production, preproduction, demo. 

We would like for the default subcribe to be only "production", then some users might want to add  the other environments/components/groups.

**Comment by jbrooksuk** [comment]
I suppose the use case here is when you have **lots** of components?

**Comment by jbrooksuk** [comment]
Thank you for your input on Cachet 2.x. We are shifting our attention and resources to Cachet 3.x and will no longer be supporting the 2.x version. If your feedback or issue is relevant to the 3.x series, we encourage you to engage with the new branch.

For more information on the Cachet rebuild and our plans for 3.x, you can read the announcement [here](https://github.com/CachetHQ/Cachet/discussions/4342).

We appreciate your understanding and look forward to your contributions to the new version.
