### ISSUE TITLE
Feature request: API endpoint which displays the status in general

### ISSUE THREAD

**Issue by dmnktoe** [CachetHQ/Cachet#3435]
Hey, thinking about a new API endpoint which gives the information, if there are any outages or if all components working properly. Like the banner messages at the top of the page which says "All system are operational". Would use it for a small green/yellow/red indicator embedded on another page.

What do you think?

**Comment by jbrooksuk** [comment]
This is a thing! https://dev.cachethq.io/api/v1/status

🎉

**Comment by dmnktoe** [comment]
Great! But one question, one component was set to an outage but the API still displays `success`. Kinda weird.

**Comment by jbrooksuk** [comment]
🚀
