### ISSUE TITLE
 404 not found  /index.php/setup/step1   -   all.js

### ISSUE THREAD

**Issue by auth1299** [CachetHQ/Cachet#3443]
I can get to the /index.php/setup page but when I try to configure and click NEXT, I get a 404 error trying to go to step1.  I'm using cachet 2.4-dev on windows 2016 using IIS. I have the rewrite module installed. 

PHP Version
PHP 7.1.10 (cli) (built: Sep 26 2017 20:03:48) ( NTS MSVC14 (Visual C++ 2015) x64 )

I tried this on chrome and on a separate computer using firefox, I get the exact same result on both. 

![capture](https://user-images.githubusercontent.com/7773605/52087284-f4816480-2576-11e9-8376-28df7674a52e.PNG)

**Comment by auth1299** [comment]
APP_ENV=production
APP_DEBUG=false
APP_URL=http://status.testurl.net
APP_TIMEZONE=UTC
APP_KEY=base64:***********************************************
DEBUGBAR_ENABLED=false

DB_DRIVER=mysql
DB_HOST=127.0.0.1
DB_UNIX_SOCKET=null
DB_DATABASE=cachet
DB_USERNAME=cachet
DB_PASSWORD=32894623234HJF
DB_PORT=3306
DB_PREFIX=

CACHE_DRIVER=database
SESSION_DRIVER=database
QUEUE_DRIVER=database

CACHET_BEACON=false
CACHET_EMOJI=false
CACHET_AUTO_TWITTER=false

MAIL_DRIVER=mail
MAIL_HOST=127.0.0.1
MAIL_PORT=25
MAIL_USERNAME=
MAIL_PASSWORD=
MAIL_ADDRESS=no-reply@testurl.net
MAIL_NAME=
MAIL_ENCRYPTION=

REDIS_HOST=null
REDIS_DATABASE=null
REDIS_PORT=null

GITHUB_TOKEN=null

NEXMO_KEY=null
NEXMO_SECRET=null
NEXMO_SMS_FROM=Cachet

TRUSTED_PROXIES=

**Comment by auth1299** [comment]
Developer tools shows this:

![capture](https://user-images.githubusercontent.com/7773605/52087693-20e9b080-2578-11e9-84e2-44fac6b4135e.PNG)

**Comment by jbrooksuk** [comment]
You shouldn’t need the `index.php`

Try following the guide at https://docs.cachethq.io/docs/installing-cachet-on-windows

**Comment by auth1299** [comment]
Hi,
You do need the index.php in the url. I went over the windows installation instructions several times. You are missing the storage folder permissions on this page by the way.
I've done it all. Looks like a bug in the all.js file possibly. 
Shaun

Sent from Yahoo Mail on Android 
 
  On Fri, Feb 1, 2019 at 2:35 AM, James Brooks<notifications@github.com> wrote:   
You shouldn’t need the index.php

Try following the guide at https://docs.cachethq.io/docs/installing-cachet-on-windows

**Comment by jbrooksuk** [comment]
@TheoBearman 👋 Are you able to help out above?

**Comment by auth1299** [comment]
I get a 404 if I take out the index.php.

**Comment by auth1299** [comment]
Could the issue be a IIS mod re-write issue on windows?

**Comment by auth1299** [comment]
> 
> 
> You shouldn’t need the `index.php`
> 
> Try following the guide at https://docs.cachethq.io/docs/installing-cachet-on-windows

Removing the index.php gives me a 404
