### ISSUE TITLE
Can't run the Cachet successfully 

### ISSUE THREAD

**Issue by FareedaSaleh** [CachetHQ/Cachet#3454]
Hi 
I flow the https://docs.cachethq.io/docs/installing-cachet to install the cachet app but I can't run the app successfully!!
![screenshot from 2019-02-03 09-18-42](https://user-images.githubusercontent.com/26326307/52173418-633c0900-2795-11e9-96b4-437530abfa89.png)

**Comment by jbrooksuk** [comment]
It looks to me like you’ve not configured PHP properly. 

Which server are you using? Apache or nginx?

**Comment by FareedaSaleh** [comment]
I use Apache

**Comment by FareedaSaleh** [comment]
-

**Comment by jbrooksuk** [comment]
This is a configuration issue on your end. You need to have PHP installed and setup to redirect requests.
