### ISSUE TITLE
This page isn’t working

### ISSUE THREAD

**Issue by FareedaSaleh** [CachetHQ/Cachet#3459]
Hi 
When I run the server I got This page isn’t working
95.177.161.92 is currently unable to handle this request.
HTTP ERROR 500
I use linux 16.04 and apache and PHP 7

![screenshot from 2019-02-04 13-58-48](https://user-images.githubusercontent.com/26326307/52205084-0751ad00-2887-11e9-8a0a-4d324d44e07b.png)

**Comment by FareedaSaleh** [comment]
Hi 
I reinstall the Cachet v2.3.9 on ubuntu 16.4 and using PHP 7.0 and when I run the apache and I have page not found then I run the command  -a2enmod rewrite- and I got (currently unable to handle this request.
HTTP ERROR 500)  I use ( https://docs.cachethq.io/docs/installing-cachet )

**Comment by mipapo** [comment]
Could you check the error logs of the vhost? 
Check that the files files are owned by the users of the webserver

**Comment by cristiancs** [comment]
Are you sure is php 7.0 and not 7.2?, i had the same problem until i noticed with php 7.2 you need to use 2.4

**Comment by GrahamCampbell** [comment]
> V2.3.9

2.3.9 is not the latest in the 2.3.x series. Please use the latest release, and it will work with PHP 7.
