### ISSUE TITLE
Manage subscription after verifying subscriber

### ISSUE THREAD

**Issue by tejaswivinod** [CachetHQ/Cachet#3465]
In current workflow of subscription, If a new subscriber adds his email from  `Subscribe` link on the bottom of status page, he gets verification email and on clicking `Verify` from email, he is directed to statuspage with `Awesome. Your email subscription has been confirmed. Thank you!` message.   
There is no way he can manage the subscription from confirmation page.  He needs to wait for another status update email from cachet, where he gets the `Manage subscription` link and is directed to subscription page. I think there should be an email to after verification to manage subscription or after verification of subscriber, he should be directed to manage subscription page. It will be easier to manage subscription instead of waiting for the link.

**Comment by tejaswivinod** [comment]
I guess this is part  of #3102

**Comment by GrahamCampbell** [comment]
Yeh. :)
