### ISSUE TITLE
Associate a scheduled maintenance with a component.

### ISSUE THREAD

**Issue by thejcannon** [CachetHQ/Cachet#3470]
When I create a scheduled maintenance, it'd be nice if I could associate it with a component, so only that component's subscribers get an email about the scheduled maintenance. Additionally, it would turn into an incident for that component.

Possibly the dashboard would list the maintenance underneath the component as well, but that could be a separate feature request.

Unfortunately this is blocking our team from leveraging this app (which is very nice in pretty much every other aspect 😄)

**Comment by GameMaster2030** [comment]
This would be nice, also add an api reference for this.

**Comment by jbrooksuk** [comment]
Cachet 2.4 actually has built in support for this, but it's not exposed in the dashboard currently, because we're in the process of redesigning the frontend.

**Comment by thejcannon** [comment]
Excellent! Do y'all have an idea of when you expect to release 2.4?

**Comment by rayterrill** [comment]
@jbrooksuk Dang we're looking for this too. Sounds like 2.4 is the place to be. :)

**Comment by gcommit** [comment]
Can you tell me how to use it right now?

**Comment by anthosz** [comment]
@gcommit nothing ready apparently for now ^^ Wait ^^

**Comment by gcommit** [comment]
Okay :) is there at least a way that i can send a maintenance mail to any subscriber even if he/she is not subscribed to every single component?

**Comment by Baumgartl** [comment]
Your feedback is welcome!

In summary, I think other people (including me) really looking forward to have the following feature(s) available in Cachet:

1. Define a new status called **Maintenance** and make it switchable (like [here](https://github.com/CachetHQ/Cachet/blob/5db11d5f7af227a24b59a2338d39ced8bdbd3b54/resources/lang/en-US/cachet.php#L16)) in Dashboard,
2. Allow associate a scheduled maintenance with one or more components,
3. Allow define a maintenance window (e.g. from & till fields) which can be optional,
4. Auto-switch component(s) to status Maintenance _within_ the effective maintenance window,
5. Send maintenance notifications to all subscribers,
6. Extend API reference for the above mentioned integrations.

Please let me know what do you think, @jbrooksuk.

**Comment by MeStrak** [comment]
Everything that @Baumgartl said + the option for recurring maintenance would be great.

Use case would be to suppress alerts during a repeat scheduled maintenance every Sunday for example.

**Comment by Isengo1989** [comment]
Any updates so far? Maintenance is currently kind of useless for us.

**Comment by jbrooksuk** [comment]
Thank you for your input on Cachet 2.x. We are shifting our attention and resources to Cachet 3.x and will no longer be supporting the 2.x version. If your feedback or issue is relevant to the 3.x series, we encourage you to engage with the new branch.

For more information on the Cachet rebuild and our plans for 3.x, you can read the announcement [here](https://github.com/CachetHQ/Cachet/discussions/4342).

We appreciate your understanding and look forward to your contributions to the new version.
