### ISSUE TITLE
Cannot run install step?

### ISSUE THREAD

**Issue by dennusb** [CachetHQ/Cachet#3471]
Hello,

I'm trying to perform a brandnew Cachet 2.4 install on a machine with PHP 7.2.13 but when i run : 

php artisan app:install

  Command "app:install" is not defined.

  Did you mean one of these?
      app:name
      app:reset
      app:update
      cachet:install
      migrate:install

I tried everything, including new clones from repo, cache resets, new machines etc. What is going on?

Dennis

**Comment by cristiancs** [comment]
Based on this commit file
https://github.com/CachetHQ/Cachet/blob/b1de3b6b4e467854130e9c1c71009ae36662155b/app/Console/Commands/InstallCommand.php

I think the command is now php artisan cachet:install

**Comment by dennusb** [comment]
This can be closed!
