### ISSUE TITLE
tags not repopulating on component

### ISSUE THREAD

**Issue by AstroQuick** [CachetHQ/Cachet#3477]
New install on Oracle Linux 7.6. Php 7.2. Cachet 2.4.

Guessing I have missed something somewhere, but I can not find it.

When I create a component, I fill in all the fields including Tags. After saving the component, all fields remain populated except Tags. Same thing happens when I edit a component. After saving all fields remain except Tags. 

I tried this on the demo site, and the tags remain after saving. But that is version 2.3.14-dev.

**Comment by AstroQuick** [comment]
OK, so I have done some testing. 
In creating a new component, after filling out all of the fields including tags, I click save and the tags field is emptied. I can look in the database and the data is there.
If I edit the component and change something else but leaving the tags field alone, when saved the tags data in the database is removed. 
If I edit the component and add tags, when saved, the tags field is emptied but the data does get written to the database. 
The above was done on version 2.4 that was cloned from git on Feb 15th 2019. The VERSION file reads 2.4.0-dev.

**Comment by AstroQuick** [comment]
Some additional testing:

In checking through the API, when getting a components details, the tags field returns null even through there are 3 tags in the db for this component.

curl --insecure --request GET   --url https://REDACTED/api/v1/components/17
{"data":{"id":17,"name":"REDACTED","description":"REDACTED","link":"http:\/\/REDACTED","status":1,"order":15,"group_id":1,"enabled":true,"meta":null,"created_at":"2019-02-18 11:59:12","updated_at":"2019-02-18 14:40:28","deleted_at":null,"status_name":"Operational","tags":{"":null}}}

**Comment by jbrooksuk** [comment]
It looks like we need to spend a bit more time on the tags feature!
