### ISSUE TITLE
Caching / rate limiting for API

### ISSUE THREAD

**Issue by Daniel15** [CachetHQ/Cachet#3479]
I just had an issue where my server got a huge number of hits to the `/api/v1/status` endpoint, which basically killed my PHP-FPM server (it hit the maximum number of workers, preventing people from connecting to any other sites in the same pool).

Does Cachet cache the response to this API call? It would be good to cache its response (even if only for a short period of time, like 30 seconds), so that a large number of hits don't cause any perf issues. If a lot of hits come in at the same time, they could all receive the cached response rather than having to recompute it + hit the DB.

**Comment by jbrooksuk** [comment]
Hey @Daniel15! The API endpoints aren't actually cached at the moment, but they definitely should.

Out of interest, where are you using Cachet? I see you all over the place! 😄

**Comment by Daniel15** [comment]
Thanks for the reply! In theory I could use Nginx FastCGI caching to cache the endpoint, but it seems like Cachet is sending a `Cache-Control: no-cache` header, making the content uncacheable. Is there an easy way to modify /api/v1/status to send a caching header? Then I could just configure Nginx to cache it.

@jbrooksuk Cachet is being used for the status page for Yarn: https://status.yarnpkg.com/

**Comment by jbrooksuk** [comment]
I've addressed this is a Draft PR, so that we can talk about it there and then get this fixed for you.

> Cachet is being used for the status page for Yarn: https://status.yarnpkg.com/

That's where I know you from! 😄
