### ISSUE TITLE
Use Eloquent Resources

### ISSUE THREAD

**Issue by jbrooksuk** [CachetHQ/Cachet#3480]
We should make use of the built in [Eloquent Resources](https://laravel.com/docs/5.7/eloquent-resources) over our custom `AbstractApiController`. Eloquent resources give us more flexibility of what is returned in the results + meta and require far less code to maintain.

As an added side effect, we should be able to switch with little effort because both solutions wrap the results in `meta` and `data`, so the output should remain the same.

**Comment by atymic** [comment]
I've created a WIP pr for this in #3686 😄

**Comment by jbrooksuk** [comment]
Thank you for your input on Cachet 2.x. We are shifting our attention and resources to Cachet 3.x and will no longer be supporting the 2.x version. If your feedback or issue is relevant to the 3.x series, we encourage you to engage with the new branch.

For more information on the Cachet rebuild and our plans for 3.x, you can read the announcement [here](https://github.com/CachetHQ/Cachet/discussions/4342).

We appreciate your understanding and look forward to your contributions to the new version.
