### ISSUE TITLE
Dashboard link on frontpage goes to http

### ISSUE THREAD

**Issue by dennusb** [CachetHQ/Cachet#3482]
Hi,

We just found out that in 2.4 the dashboard link that is in the footer on the index forcefully goes to HTTP even if we are on HTTPS.

**Comment by cristiancs** [comment]
i think it goes to the url specified in yoururl/dashboard/settings/setup "Site URL"

**Comment by jbrooksuk** [comment]
Make sure that if you're using a proxy, you allow this proxy in `./config/trustedproxy.php`
