### ISSUE TITLE
Https redirect problem

### ISSUE THREAD

**Issue by hailahar** [CachetHQ/Cachet#3483]
Hello

I'm trying to add a redirect command to redirects the traffic from http to https
the problem is once I add this command I can't go the dashboard page since the URL will be redirected to https.
Here's is the command I applied it on cachet.conf file: 

> Redirect permanent "/" "https://my IP address/"

**Comment by GrahamCampbell** [comment]
I'd recommend discussing this on a forum perhaps, as this is not a bug in the core codebase. :)
