### ISSUE TITLE
Getting 500 Error while "/subscribers/create"

### ISSUE THREAD

**Issue by dmnktoe** [CachetHQ/Cachet#3490]
I'm getting a 500 error since running the second latest and also the current 2.4.0dev, while I was trying to add a new email subscriber via the dashboard.

Anybody else ran into the same issue?

**Comment by smalik786** [comment]
same issue with me as well

**Comment by GrahamCampbell** [comment]
Does this issue occur with on the latest 2.3.16dev version?

**Comment by dmnktoe** [comment]
@GrahamCampbell I'll let you know when I'm back from holidays and set up a new installation! Thanks.

**Comment by jbrooksuk** [comment]
Can you also share the error log please. I've just checked in the latest v2.4 and I was able to add subscribers.

**Comment by jbrooksuk** [comment]
Closing for now as I'm unable to recreate, but please re-open if you can share the log as well.
