### ISSUE TITLE
Heavy CPU workload after I added a metric

### ISSUE THREAD

**Issue by dmnktoe** [CachetHQ/Cachet#3491]
I just noticed some strange behavior on my server lately, after I added a added the first metric to my dashboard. All pages started to load extremely slow.

I had a look into CPU workload and saw that it was under heavy usage. I displayed the task runner and noticed that it comes from my MySQL process executed in the cachet metrics database.

Did anyone run into the same issue?

**Comment by Tarek1337** [comment]
Yep, can reproduce with 2.3.9.

**Comment by jbrooksuk** [comment]
How many points have you added to your metric?

**Comment by jbrooksuk** [comment]
@dmnktoe can you confirm what version of Cachet you're using?

**Comment by dmnktoe** [comment]
@jbrooksuk 

> How many points have you added to your metric?

The points were constantly updated through the uptime robot api. So I can say that were thousands of points. 

> @dmnktoe can you confirm what version of Cachet you're using?

Sorry. Sure, I'm running on 2.4.0dev. Should be a commit from mid January, I think.

**Comment by Tarek1337** [comment]
I add one point per minute across 3 metrics.

**Comment by GrahamCampbell** [comment]
> Yep, can reproduce with 2.3.9.

2.3.9 is not the latest 2.3.x series. It is 3 years old. Please try with 2.3.15 (or 2.3.16 when it comes out).

**Comment by jbrooksuk** [comment]
Metrics are pretty lightweight. Can you let us know if this is still occurring please.
