### ISSUE TITLE
Update 2.4 to latest

### ISSUE THREAD

**Issue by jayze** [CachetHQ/Cachet#3498]
HI,

I've been updating my installation of 2.4.
Currently all works fine, but I can't make an update of an incident or posting a new incident. I get an error 500.

>This error can be identified by aa07b7b9-f15b-43c6-bb58-3e859cdaf710. You might want to take a note of this code.

Steps I've done

1. cd $CACHET (your Cachet installation directory)
2. git fetch origin
3. git checkout 2.4
4. composer install --no-dev -o
5. php artisan app:update

I ran into issues with Class 'Barryvdh\Debugbar\ServiceProvider' not found, I've commented that line in the app.php, continued the upgrade. Now I'm having these issues. Anywhere I can get more information about this error?

Jay

**Comment by jayze** [comment]
HI,

I've seen in the logs that when trying to post a new incident or update, it tries to send a mail, where it fails. However when testing my mail settings, that works.

Jay

**Comment by jayze** [comment]
Found the solution.
encryption email should be set to ssl, instead of tls.

**Comment by jbrooksuk** [comment]
👍
