### ISSUE TITLE
Error using undocumented Maintenance API

### ISSUE THREAD

**Issue by Lockon2000** [CachetHQ/Cachet#3499]
I am trying to utilise the still undocumented Maintenances API. I tried to infer the correct parameters, but I nearly always get the bad HTTP request error with a description of trailing data.

Can someone provide me with the needed parameters and their format in order to make a successful API call?

**Comment by jbrooksuk** [comment]
@Lockon2000 can you confirm what version of Cachet you're using?

**Comment by jbrooksuk** [comment]
Depending on how familiar you are with the API tests, you may be able to gain some insight from https://github.com/CachetHQ/Cachet/blob/3b9ee670a223059cb2ed70fe07839d0dbd06c2b7/tests/Api/ScheduleTest.php whilst the documentation is outstanding.

**Comment by Lockon2000** [comment]
> 
> 
> @Lockon2000 can you confirm what version of Cachet you're using?

The latest 2.4-dev version. I know it isn't recommended to use a dev version. But the released 2.3.15 version doesn't implement the Mainteneces API at all.



> 
> 
> Depending on how familiar you are with the API tests, you may be able to gain some insight from https://github.com/CachetHQ/Cachet/blob/3b9ee670a223059cb2ed70fe07839d0dbd06c2b7/tests/Api/ScheduleTest.php whilst the documentation is outstanding.

That's great! I will try it out and let you know.

**Comment by Lockon2000** [comment]
Okay, the tests did really help me out.

Thanks!!
