### ISSUE TITLE
Google Analytics code

### ISSUE THREAD

**Issue by jbrooksuk** [cachethq/Cachet#350]
We should have a way to add a Google Analytics code.

**Comment by GrahamCampbell** [comment]
I do this in bootstrap cms if you want to nick my code. :)

**Comment by jbrooksuk** [comment]
Sweet, that'll save some time :)

**Comment by zhil** [comment]
@jbrooksuk @GrahamCampbell sorry for annoying, can you please explain - how do you use Google Analytics code/GoSquared Analytics code/URL of your Piwik instance (without http(s)://) ? 

I didnt founded anything in docs/issues. Are you just add stats gathering code on status page? Just wonder - what benefits from tracking visitors stats on status page?

**Comment by GrahamCampbell** [comment]
If you don't want it, then don't use it. Google analytics is not for us, it's for you to connect to your own google analytics account.

**Comment by GrahamCampbell** [comment]
It's off by default, because of course, we don't know your google tracking data.

**Comment by zhil** [comment]
@GrahamCampbell got it, thanks
