### ISSUE TITLE
500 Internal server error

### ISSUE THREAD

**Issue by jmann05** [CachetHQ/Cachet#3500]
Cachet v.2.3.15
PHP 7.1.26
I've ran rm -rf bootstrap/cache/* from the root of my Cachet installation

My server broke, I have a copy of the database and was able import into a fresh install, but I'm getting a 500 internal server error. I checked the laravel log and saw this:

Next Illuminate\Database\QueryException: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'scheduled_at' in 'where clause' (SQL: select * from `incidents` where (`status` > 0 or (`status` = 0 and (`scheduled_at` is null or `scheduled_at` <= 2019-03-04 15:33:46))) and `visible` >= 1 and `created_at` between 2019-02-26 00:00:00 and 2019-03-04 23:59:59 and `incidents`.`deleted_at` is null order by `scheduled_at` desc, `created_at` desc) in /var/www/cachet/vendor/laravel/framework/src/Illuminate/Database/Connection.php:713

Advice would be greatly appreciated.

**Comment by jbrooksuk** [comment]
Were you previously using Cachet 2.4? Alternatively, you may now need to run `php artisan app:update`.
