### ISSUE TITLE
Theme isn't applied to component list

### ISSUE THREAD

**Issue by Grayda** [CachetHQ/Cachet#3506]
I've just installed v2.3.15 and set some theme colours to match my site's brand, however the component list is white regardless of what colours I set.

I can override these easily with a stylesheet, but it's counter-intuitive for the theme not to cover the component list.

[Settings page screenshot](https://user-images.githubusercontent.com/4891563/54084070-3379b580-4380-11e9-819a-4b6c912c20b4.png)

[How the page looks live](https://user-images.githubusercontent.com/4891563/54084076-560bce80-4380-11e9-995a-635c05f0086c.png)

Clearing the compiled views, forcing a refresh etc. does nothing.

EDIT: This is also happening on 2.4 with a fresh install on a different system.

**Comment by jbrooksuk** [comment]
@ojdon do you think you could address this in the Bootstrap upgrade, please?

**Comment by jbrooksuk** [comment]
Thank you for your input on Cachet 2.x. We are shifting our attention and resources to Cachet 3.x and will no longer be supporting the 2.x version. If your feedback or issue is relevant to the 3.x series, we encourage you to engage with the new branch.

For more information on the Cachet rebuild and our plans for 3.x, you can read the announcement [here](https://github.com/CachetHQ/Cachet/discussions/4342).

We appreciate your understanding and look forward to your contributions to the new version.
