### ISSUE TITLE
Add Canonical tag to meta tags

### ISSUE THREAD

**Issue by MarkoSulamagi** [CachetHQ/Cachet#3513]
Cachet pages are often publicly available so it would be useful to have a canonical link in the meta tags. This is useful for SEO (even if there's only 1 version for each page and there're no duplicates). 
https://moz.com/learn/seo/canonicalization

If you agree then I could create a PR for this myself.

**Comment by jbrooksuk** [comment]
Yep! Agreed. I’d love a PR :)
