### ISSUE TITLE
Marking all components as operational with open incidents

### ISSUE THREAD

**Issue by lorenzoaiello** [CachetHQ/Cachet#3519]
Currently if you have components that are marked as operational on the dashboard but that still have open incidents, the overall status page will be still display as having some issues. It was pretty confusing until I understood what had happened.

It would be great if either you couldn't mark change the state on the dashboard with open incidents, or maybe showing a link on the dashboard to the open incidents (with a count) so it was easy to see if there was conflicting information.

**Comment by jbrooksuk** [comment]
Thank you for your input on Cachet 2.x. We are shifting our attention and resources to Cachet 3.x and will no longer be supporting the 2.x version. If your feedback or issue is relevant to the 3.x series, we encourage you to engage with the new branch.

For more information on the Cachet rebuild and our plans for 3.x, you can read the announcement [here](https://github.com/CachetHQ/Cachet/discussions/4342).

We appreciate your understanding and look forward to your contributions to the new version.
