### ISSUE TITLE
Translations in incorrect places

### ISSUE THREAD

**Issue by SamuelMoraesF** [cachethq/Cachet#352]
It seems that some translations tags are in the incorrect place, on pt-BR, the add component button and the page header is named "Add incident". The components statuses are the same of the Incidents too and the translations on crowdin is ok.

**Comment by jbrooksuk** [comment]
I'll upload the latest English translation tonight and see if we can sync them back. Since CrowdIn doesn't actually integrate with GitHub it makes it really hard to keep them the same.

**Comment by jbrooksuk** [comment]
I've removed the Brazilian translation for now as there are a lot of issues with it.

**Comment by jbrooksuk** [comment]
FWIW, CrowdIn has an up to date `pt-Br` translation for us. Will sync up soon.

**Comment by jbrooksuk** [comment]
I've uploaded the latest language files.

**Comment by pedrommone** [comment]
I see that! :)
