### ISSUE TITLE
Something went wrong updating the component.

### ISSUE THREAD

**Issue by lucrqua** [CachetHQ/Cachet#3522]
Hi guys, I need some help here with this issue please. 

Apache:  Apache/2.4.10 (Debian)
PHP: 5.6.40-0+deb8u1
MySQL: 5.5.62-0+deb8u1

[laravel-2019-03-02.log](https://github.com/CachetHQ/Cachet/files/2969257/laravel-2019-03-02.log)
[laravel-2019-03-15.log](https://github.com/CachetHQ/Cachet/files/2969258/laravel-2019-03-15.log)

Traying to change the status of component on dashboard:
![image](https://user-images.githubusercontent.com/15186323/54404961-d64d6f00-46b3-11e9-948d-cb76978e82a7.png)

How I proceed on this case?

**Comment by jbrooksuk** [comment]
Looking at the logs, it looks like your mail settings aren't correct. Please verify and try again.

**Comment by lucrqua** [comment]
Hi @jbrooksuk 

Sorry for the delay in this case. I set up the email settings and it worked, thank you!
