### ISSUE TITLE
Can Cachet initial setup be automated?

### ISSUE THREAD

**Issue by flaviafm** [CachetHQ/Cachet#3523]
Hi All, 

I’m creating  a cachet template in openshift and wondering in there is a way to automate Cachet setup (GUI step). 
I would like to know if is possible to get all values needed for Cachet initial set up when user select template In OpenShift then use API or script to configure Cachet. And  user do not need to go to /setup page after install.

Thank you,

Flavia

**Comment by jbrooksuk** [comment]
It should now be possible with the `cachet:install` command :) https://github.com/CachetHQ/Cachet/pull/2290
