### ISSUE TITLE
Stick Incident Option - Setting to sticked causes Error 500

### ISSUE THREAD

**Issue by jaymatthews** [CachetHQ/Cachet#3528]
When setting 'Stick Incident' to 'Stickied' I get a Error 500 page. Setting back to 'Not Stickied' resolves the issue.

**Comment by LegalSmeagol** [comment]
I too am receiving this error. Whenever an incident is set to "Not Sticked" the site displays completely fine, whenever I set an incident to "Sticked" I receive a 500 Internal Server Error. A response for this issue would be appreciated.

**Comment by Raphyyy** [comment]
+1 definitely a bug
Sticked incident is not available within the latest release

**Comment by jbrooksuk** [comment]
This is fixed by https://github.com/CachetHQ/Cachet/pull/3525
