### ISSUE TITLE
No supported encrypter found. The cipher and / or key length are invalid.

### ISSUE THREAD

**Issue by jonyking** [CachetHQ/Cachet#3531]
Hello,

when I upload cachet to my server at IONOS  I got the following error: 

No supported encrypter found. The cipher and / or key length are invalid.

I've searched a lot, but no solution worked for me. Does anyone have some suggestions?

**Comment by M0ter** [comment]
Check if you have a app key in your .env file, `APP_KEY=` should not be empty.

**Comment by jbrooksuk** [comment]
@M0ter is correct.
