### ISSUE TITLE
API Versioning

### ISSUE THREAD

**Issue by jbrooksuk** [cachethq/Cachet#354]
Is it possible with Dingo to split the API into routes by version? `https://status.cachethq.io/api/v1/incidents` I know that Dingo lets us version the API, but it's not accessible like that.

There are two reasons for doing this:

1. We can add a new API to the system without affecting any existing integrations, they'd simply update the API version and see what's broken.
2. The documentation is much easier to write on ReadMe.io when the API is versioned.

**Comment by joecohens** [comment]
I think you can't https://github.com/dingo/api/issues/79, if we are only making making token auth on the API maybe we can rewrite it and remove dingo. 

If not:

1. We can make the previews version the default until we announce it's going to be depreciated for the new one, so people who want to upgrade their integrations with the latest release will have to send the `Accept` header, kind of the way Facebook does it.

2. If I'm not wrong the docs can be versioned even if the version needs to be set on the `Accept` header.

**Comment by jbrooksuk** [comment]
Forcing the `Accept` header is ok, but adds friction to making the API requests. Unless of course, we supply some kind of wrapper for a couple of languages?

**Comment by joecohens** [comment]
Like an SDK?

**Comment by jbrooksuk** [comment]
Yeah. We could supply a PHP one by default.

**Comment by jbrooksuk** [comment]
Closing this. We'll just be sure to add to the documents about sending the right `Accept` header for now.
