### ISSUE TITLE
Impossible to login #3339 note resolved for me

### ISSUE THREAD

**Issue by AlexStreaming** [CachetHQ/Cachet#3541]
Hi, i resolve my problem with `php artisan migrate:refresh` but now i can't access with the credentials that I indicated. It is the same problem that #3339

How can i solve this?

**Comment by jbrooksuk** [comment]
`php artisan migrate:refresh` will re-run the migrations and clear the data. You'll need to go to the `/setup` page again.

**Comment by AlexStreaming** [comment]
When I go to /setup it redirects me to /auth/login . How can I go back to /setup?

**Comment by sion934** [comment]
> When I go to /setup it redirects me to /auth/login . How can I go back to /setup?

Restart web service
