### ISSUE TITLE
Maintenance window disappearing when ongoing

### ISSUE THREAD

**Issue by Wouter0100** [CachetHQ/Cachet#3548]
Last time I made a pull request (see [here](https://github.com/CachetHQ/Cachet/pull/3236)) to fix this behaviour, but unfortunately it was rolled back in 1fdb7909d317afcf12f08b2dd9b732b5adab6906 (can't find the related PR).

Regardless, 1fdb7909d317afcf12f08b2dd9b732b5adab6906 unfortunately breaks this issue again. 

The problem: the maintenance window is shown just fine in the beginning. Although, when `scheduled_at` time is hit - it disappears. Honestly, this seems a bit odd - as especially when the maintenance is ongoing (so between `scheduled_at` and `completed_at`), visitors should be aware of it.

**Comment by jimmybrancaccio** [comment]
This seem to work for me

``` diff
--- Schedule.php	2019-05-08 18:19:55.716465292 -0500
+++ Schedule.php.patched	2019-05-08 18:21:18.970523919 -0500
@@ -171,7 +171,7 @@
      */
     public function scopeFutureSchedules($query)
     {
-        return $query->whereIn('status', [self::UPCOMING, self::IN_PROGRESS])->where('scheduled_at', '>=', Carbon::now());
+        return $query->whereIn('status', [self::UPCOMING, self::IN_PROGRESS])->where('scheduled_at', '<>', Carbon::now());
     }
 
     /**
```

I am no coder/developer by any stretch of the imagination so there's probably a better solution.
