### ISSUE TITLE
Metrics point threshold cannot set > 10

### ISSUE THREAD

**Issue by crommcruach** [CachetHQ/Cachet#3549]
Version 2.4.0-dev
Cannot set metrics threshold > 10 although a higher value can be chosen
Error message: 
`Whoops.
The threshold must be between 0 and 10.`

**Comment by jbrooksuk** [comment]
Hi @crommcruach thanks for reporting. Can you please test out https://github.com/CachetHQ/Cachet/pull/3661 for me?
