### ISSUE TITLE
Metrics value suggestion

### ISSUE THREAD

**Issue by crommcruach** [CachetHQ/Cachet#3550]
I suggest following metric values to create individual graphs:

Max Value #max render value for the graph height
Min Value # the min render value for the graph height

Timeline View:
- Minutes
- Hrs
- Days
- Month

a defineable Timeline Length # based on timeline view last x (min,hour,day,month)

Change metrics  threshold: up to 1 month 
Therfore u would be able to create indiviual graphs with individual settings.

**Comment by jbrooksuk** [comment]
Hi @crommcruach, good idea! I'd like to see someone take on the metrics if possible. They're very under-powered and could do with a good overhaul on them.

**Comment by jbrooksuk** [comment]
Thank you for your input on Cachet 2.x. We are shifting our attention and resources to Cachet 3.x and will no longer be supporting the 2.x version. If your feedback or issue is relevant to the 3.x series, we encourage you to engage with the new branch.

For more information on the Cachet rebuild and our plans for 3.x, you can read the announcement [here](https://github.com/CachetHQ/Cachet/discussions/4342).

We appreciate your understanding and look forward to your contributions to the new version.
