### ISSUE TITLE
Managing Subscribers

### ISSUE THREAD

**Issue by Choeoqe** [CachetHQ/Cachet#3551]
Hi, we recently added some new components and noticed current subscribers were not updated to include those. Is there a way to manage subscribers as an admin rather than having to get each subscriber to update their preferences any time additional components are added? 

We ideally just want to be able to manually add all users as subscribers (which we currently do), and ensure they are all subscribed to all components as new ones are added. 

Thank you!

**Comment by jbrooksuk** [comment]
Thank you for your input on Cachet 2.x. We are shifting our attention and resources to Cachet 3.x and will no longer be supporting the 2.x version. If your feedback or issue is relevant to the 3.x series, we encourage you to engage with the new branch.

For more information on the Cachet rebuild and our plans for 3.x, you can read the announcement [here](https://github.com/CachetHQ/Cachet/discussions/4342).

We appreciate your understanding and look forward to your contributions to the new version.
