### ISSUE TITLE
Color maintenance 

### ISSUE THREAD

**Issue by PhilipSteeman** [CachetHQ/Cachet#3552]
In version 2.4 the background color of 'Maintenance' is grey. In version 2.3 it is blue (more logical).
The title in English is also different:
version 2.3: Scheduled Maintenance (more logical)
version 2.4: Maintenance (less logical)

**Comment by GrahamCampbell** [comment]
Thanks for raising this. Ping @jbrooksuk.

**Comment by jbrooksuk** [comment]
Hi @PhilipSteeman, thanks for reporting this.

@ojdon is currently upgrading us to Bootstrap 4 and will then be implementing the new design. This will be addressed within these changes. Thank you!
