### ISSUE TITLE
Recommendation for ping Internal IP Address

### ISSUE THREAD

**Issue by thyspir** [CachetHQ/Cachet#3553]
Could you let me know the third party application that I can use to ping my internal IP Address?
Let says I want to ping monitor IP Address 192.168.0.40.
If I don't get a ping reply, it will change the status to be Major outage.

If there is no third application for this ping method, Can I use Cachet API to perform Ping Method?

Thank in advance

**Comment by MrXermon** [comment]
@thyspir Just write a small script in your favorite programming language to monitor the ping-status and update the status via the Cachet API. Cachet is not made to monitor things, it's just here to propagate the information in case of an outage/planned maintanance.

**Comment by thyspir** [comment]
Hi,
Thank you for your respond.
I will try to check it using Cachet API
