### ISSUE TITLE
Completed_at date maintenance is should be required

### ISSUE THREAD

**Issue by MinThaMie** [CachetHQ/Cachet#3559]
The `completed_at` date  for maintenance is not required, but this will break the showing of the maintenance message on the dashboard. 

There is also no validation on the `completed_at` being after the `scheduled_at`, this should probably also be added.

**Comment by Pimorez** [comment]
I think this issue isn't completely correct. If you fill in the 'completed_at' field, the maintenance will not be shown rather than what you're saying that it is not shown when not filled in.

**Comment by jbrooksuk** [comment]
Also, the completed at is the time that the maintenance completed, not the due date for completion. Maybe we could separate this information though.

**Comment by jbrooksuk** [comment]
Thank you for your input on Cachet 2.x. We are shifting our attention and resources to Cachet 3.x and will no longer be supporting the 2.x version. If your feedback or issue is relevant to the 3.x series, we encourage you to engage with the new branch.

For more information on the Cachet rebuild and our plans for 3.x, you can read the announcement [here](https://github.com/CachetHQ/Cachet/discussions/4342).

We appreciate your understanding and look forward to your contributions to the new version.
