### ISSUE TITLE
Option to not notify subscribers about maintenance 

### ISSUE THREAD

**Issue by MinThaMie** [CachetHQ/Cachet#3562]
When creating an incident you have the option to notify the subscribers. It would be cool if the same could be added for the maintenance

`Dashboard -> Indicents -> Report an incident`

<img width="295" alt="Screenshot 2019-04-25 at 10 19 12" src="https://user-images.githubusercontent.com/5811560/56720685-a5953680-6743-11e9-8825-266c3b8b9a4f.png">

**Comment by MinThaMie** [comment]
Might also be useful to add to the `edit` of a incident, because this is might still be something you want to do at a later stage

**Comment by jbrooksuk** [comment]
Hi @MinThaMie. This is a good idea and I'd love for someone to take this on.

A rough guideline for this:

_Note that you can use incidents as a base to go on for this._

1. Add a column of `notify` to the `schedules` table
2. Add the notify column to the schedules dashboard page
3. Update the bus command to be aware of the new value
4. Update the event handler (`SendScheduleEmailNotificationHandler`) to send the notification based on whether to notify or not

**Comment by jbrooksuk** [comment]
Oh, sorry @MinThaMie, you've already done it! 🙈
