### ISSUE TITLE
Choose template when updating an incident

### ISSUE THREAD

**Issue by MinThaMie** [CachetHQ/Cachet#3566]
When you create an incident you can choose a template, but when you create an update for the incident you cannot choose one. It would be nice if this would be possible.

**Comment by jbrooksuk** [comment]
Agreed! We can add this to the list.

**Comment by jbrooksuk** [comment]
Thank you for your input on Cachet 2.x. We are shifting our attention and resources to Cachet 3.x and will no longer be supporting the 2.x version. If your feedback or issue is relevant to the 3.x series, we encourage you to engage with the new branch.

For more information on the Cachet rebuild and our plans for 3.x, you can read the announcement [here](https://github.com/CachetHQ/Cachet/discussions/4342).

We appreciate your understanding and look forward to your contributions to the new version.
