### ISSUE TITLE
Showing php when trying to browse to the page

### ISSUE THREAD

**Issue by wingZero21** [cachethq/Cachet#357]
Hi,

I have just been working to try and test this out via the install but had some problems with the deps which I think have now been resolved.

Its now just showing the php code when going to the /setup page.Any idea on what needs to be amended to stop this from happening.

Details:
hostname/setup page shows the below
```
<?php
/**
 * Laravel - A PHP Framework For Web Artisans.
 *
 * @author   Taylor Otwell <taylorotwell@gmail.com>
 */

/*
```

**Comment by jbrooksuk** [comment]
You mustn't be running a PHP server on your system. Can you confirm your server setup please.

**Comment by wingZero21** [comment]
Hi,

Just to confirm this looks to be due to missing the libphp5.so apache module so I am just sorting this out now.

Cheers!
