### ISSUE TITLE
Install 500?

### ISSUE THREAD

**Issue by DavidBrockway** [CachetHQ/Cachet#3570]
http://status.strobar.com/setup

Internal Server Error
What does this mean?
Something went wrong on our servers while we were processing your request. An error has occurred and this resource cannot be displayed. This occurrence has been logged, and a highly trained team of monkeys has been dispatched to deal with your problem. We're really sorry about this, and will work hard to get this resolved as soon as possible.

This error can be identified by b89462f4-2084-4c7d-bc1f-8013410abb02. You might want to take a note of this code.

Perhaps you would like to go to our home page?
500?

**Comment by princeofnaxos** [comment]
See #3160. Cachet doesn't support PHP >= 7.2, which is a shame since it's been out there for a while.

**Comment by jbrooksuk** [comment]
The latest version of 2.4 does support PHP 7.2
