### ISSUE TITLE
There is any stable version of Cachet with the latest fixes?

### ISSUE THREAD

**Issue by brunowdev** [CachetHQ/Cachet#3578]
Hi,

We start to use Cachet (v2.3.15) as our status page. After creating some components we face many issues related to mail notifications while doing any change in the component.

By searching here, we find them as solved for version 2.4. The problem is that the recommended version is a stable one, but with version 2.3.15, for example, an email is sent for every component, just by updating the order of one single component. So, we can't let our users subscribe to components since each user will receive hundreds of emails.

For now, I built a version based on branch 2.4 and I have found many untranslated words to pt-br, words that were correct before.

I would like to know if there is any stable version with the most recent fixes or if there is any plan to release a 2.4 version in the next months?

Also, I found some regression points, like [this](https://github.com/CachetHQ/Cachet/commit/65354508be5625b9d1eb1692ad8b0c1d060c03f0#diff-b6076c6c3e78235c19414416651b1b1d).

If needed, I could help with these issues.

**Comment by jbrooksuk** [comment]
2.4 tries to be as stable as possible. Translations can be updated at https://translate.cachethq.io :)
