### ISSUE TITLE
postAutoloadDump

### ISSUE THREAD

**Issue by ehsanhajian** [CachetHQ/Cachet#3579]
Hi all. I got an error during "composer install --no-dev -o"

Illuminate\Foundation\ComposerScripts::postAutoloadDump
PHP Parse error:  syntax error, unexpected '=' in /var/www/html/Cachet/vendor/laravel/framework/src/Illuminate/Support/Arr.php on line 388

Parse error: syntax error, unexpected '=' in /var/www/html/Cachet/vendor/laravel/framework/src/Illuminate/Support/Arr.php on line 388

anyone can help, please?

**Comment by jbrooksuk** [comment]
What version of PHP are you using?

**Comment by ehsanhajian** [comment]
PHP 7.0.33-0ubuntu0.16.04.4 (cli) ( NTS )

**Comment by ehsanhajian** [comment]
any comment @jbrooksuk

**Comment by jbrooksuk** [comment]
You need to be using PHP 7.1 :)
