### ISSUE TITLE
Change API Token authentication

### ISSUE THREAD

**Issue by jbrooksuk** [cachethq/Cachet#358]
Rather than supplying the api token as a URI parameter, we could make it into a header such as `X-Cachet-Token`.

What are peoples thoughts on that? I personally think it's better because it doesn't mess up the request URI.

**Comment by jbrooksuk** [comment]
Also, we're currently using the words **api key** I think token is more apt here.

**Comment by joecohens** [comment]
:+1:

**Comment by svenmueller** [comment]
:+1:

**Comment by jbrooksuk** [comment]
Thanks @svenmueller ;)
