### ISSUE TITLE
Finalize V1 of the API

### ISSUE THREAD

**Issue by jbrooksuk** [cachethq/Cachet#359]
There is still a few endpoints missing from the API:

- [x] Metrics #4 
- [x] Component tags
- [x] Update components
- [x] Created, edit and delete metrics themselves.
- [x] Delete components.

**Comment by jbrooksuk** [comment]
Added component tags.

**Comment by jbrooksuk** [comment]
@GrahamCampbell you mentioned removing of the transformers etc? Is this something we'd benefit from immediately?

**Comment by GrahamCampbell** [comment]
> Is this something we'd benefit from immediately?

No. Removing them would prevent code from diverging. The same effect we were observing with the lang files might be observed here if we're not careful. That was what I was getting at. Only in this case, we really don't need to duplicate this stuff unlike the lang files.

**Comment by jbrooksuk** [comment]
I've made some changes to the Metrics API:

- Endpoints have changed slightly:
    - `GET /api/metrics`
    - `GET /api/metrics/:id`
    - `GET /api/metrics/:id/points`
    - `POST /api/metrics`
    - `POST /api/metrics/:id/points`
- You no longer need to supply the `id` in the JSON body when creating a point.

Other than that, this issue is now done.
