### ISSUE TITLE
Incident status best practice

### ISSUE THREAD

**Issue by muenchdo** [CachetHQ/Cachet#3597]
I'm not sure how incident status are meant to be used. Should I create one incident and keep updating the status or rather create an "investigating incident" and later a separate "fixed incident"?

**Comment by GrahamCampbell** [comment]
> I'm not sure how incident status are meant to be used. Should I create one incident and keep updating the status or rather create an "investigating incident" and later a separate "fixed incident"?

The current workflow is that you should create a new incident for each "update". The modification of an incident should only be used to correct typos, etc. Cachet will not show the history of updates made to incidents.

**Comment by muenchdo** [comment]
Alright, thanks a lot 👍
