### ISSUE TITLE
Interface for integration with others services

### ISSUE THREAD

**Issue by pedrommone** [cachethq/Cachet#36]
Would be nice if we can receive a status from HipChat or w/e. 

- [ ] Hipchat
- [ ] SMS (Twilio)
- [ ] WhatsApp
- [ ] Slack
- [ ] Email (subscribers).

**Comment by jbrooksuk** [comment]
#332 and #317 are working on this. Once we have a Notification system, we'll be able to write more adapters.

**Comment by jeanfrancis** [comment]
The interface for others service should be flexible in a way that it's not just some services that are supported as they are so many others than those listed such as PagerDuty VictorOps, UptimeRobot, StillAlive , Pingdom, Plivo, Mackerel....

**Comment by GrahamCampbell** [comment]
@jeanfrancis Yeh, we're using https://github.com/notifymehq.

**Comment by GrahamCampbell** [comment]
> PagerDuty VictorOps, UptimeRobot, StillAlive , Pingdom, Plivo, Mackerel....

We're only support services we can actually write to. We're not receiving data from other services atm.

**Comment by jbrooksuk** [comment]
Once V1 is out, we'll be in a much better position to integrate directly with other services. Imagine connecting Uptime Robot directly to Cachet etc.

**Comment by GrahamCampbell** [comment]
That would be really cool. I'm wondering if we should totally separate this from cachet, and design a service that can consume uptimerobot etc, and then go and hit cachet's api.

**Comment by GrahamCampbell** [comment]
That said, it would be really cool for cachet to be able to do this - given that we could implement browser based configuration for this.

**Comment by jbrooksuk** [comment]
As some kind of middleman service?

What are the pro's and con's of doing that? Remember that Cachet is a *product* by itself, so we should keep everything together.

**Comment by GrahamCampbell** [comment]
It would still be within the cachethq organisation if we were to do it, I think.

**Comment by GrahamCampbell** [comment]
This stuff might become clearer if we move towards ddd. Who knows. :)

**Comment by jeanfrancis** [comment]
@GrahamCampbell so if i use Opsweekly https://github.com/etsy/opsweekly 
we will get data from notifymehq ?

why not a middleman service that is a addon package to Cachet the product by itself?

**Comment by jeanfrancis** [comment]
anyway if it's for alerting they are others solutions that are already interfacing external services such as Alerta http://alerta.io and Flapjack also https://github.com/flapjack/flapjack

**Comment by jbrooksuk** [comment]
I'd rather keep everything in one system where possible. We offer an API though, so you can choose to do what you wish with it.

**Comment by sammcj** [comment]
May I make a suggestion that rather than writing for proprietary systems like HipChat that instead you just have the ability to send to XMPP(Jabber) users/rooms?

* Many of the proprietary chat systems work with XMPP.
* Reduces the amount of code that has to be maintained.
* Reduces risk of vendor lock-in.
* Is an open and well documented standard.
* There are a *lot* of connectors for XMPP in other products which would open the door for people to easily integrate Cachet notifications into other applications.

Just my 2c...

**Comment by jbrooksuk** [comment]
We're using [NotifyMe](https://github.com/notifymehq/notifyme) which is a library of connector packages for different standards. In the future we'll probably add a XMPP connector and switch out the API versions for that - CC @cachethq/owners

**Comment by anarcat** [comment]
my personnal wishlist here would be IRC, XMPP, twitter, identica (status.net/pump.io) and diaspora.

**Comment by jbrooksuk** [comment]
Hi @anarcat we'll be using the [NotifyMe](https://github.com/notifymehq) system so we'll be able to add adapters ad we need :)

**Comment by anarcat** [comment]
@jbrooksuk what's the timeline for this?

**Comment by jbrooksuk** [comment]
Well @joecohens is working on this, so he'd have to answer.

**Comment by joecohens** [comment]
Hopefully NotifyMe will be released this week and implemented on Cachet this weekend.

**Comment by sammcj** [comment]
If only there was some sort of service that could notify us of these things... ;) heh keep up the great work @joecohens @jbrooksuk !

**Comment by anarcat** [comment]
@joecohens awesome news! can't wait to deploy this here :)

**Comment by jeanfrancis** [comment]
Would like to suggest adding https://telegram.org to NotifyMe

**Comment by anarcat** [comment]
> Hopefully NotifyMe will be released this week and implemented on Cachet this weekend.

Where's my flying car? ;) Anything we can help with? I'd be glad to test something, esp. twitter...

**Comment by jbrooksuk** [comment]
There have been set backs with NotifyMe, but that's because awesome things are happening with it.

**Comment by anarcat** [comment]
still no progress here? where's the awesome sauce? :)

**Comment by jbrooksuk** [comment]
@joecohens will be implementing this ready for V1 :)

**Comment by svenmueller** [comment]
+1

**Comment by svenmueller** [comment]
is there a timeplan when this will be available?

**Comment by jbrooksuk** [comment]
We're still discussing this one between @joecohens, @GrahamCampbell and myself.

**Comment by jbrooksuk** [comment]
We now have Subscribers implemented :)
