### ISSUE TITLE
Improved error pages

### ISSUE THREAD

**Issue by jbrooksuk** [cachethq/Cachet#360]
At the moment any critical error we have gives us Laravel's default error page, we should make this better.

**Comment by GrahamCampbell** [comment]
I have a package for this, for laravel 5 when we get there.

**Comment by jbrooksuk** [comment]
Oh really? Is it user friendly?

**Comment by GrahamCampbell** [comment]
https://github.com/GrahamCampbell/Laravel-Exceptions

**Comment by GrahamCampbell** [comment]
lol how the usage docs for this package were clearly stolen from another one of my packages and i haven't updated it...

**Comment by GrahamCampbell** [comment]
Fixed in https://github.com/GrahamCampbell/Laravel-Exceptions/commit/493778a5c462273483190753ab7806b81f64157f.

**Comment by jbrooksuk** [comment]
Closing this. It's not a massive issue for now.
