### ISSUE TITLE
Error 500 When Trying to View dashboard

### ISSUE THREAD

**Issue by LegacyAngel2K9** [CachetHQ/Cachet#3600]
Hi, 

Tried to enter the dashboard, but get Error 500

Error Identifier: b621662e-650f-4c74-8f1c-c5eb05bfd0d6
Laravel.log: https://gist.github.com/LegacyAngel2K9/f48ed244dc2d40a0c9e96afa5b7caefb

**Comment by jbrooksuk** [comment]
It looks like the `storage` directory isn’t writeable.
