### ISSUE TITLE
v2.3.16: error 500 when loading localization page

### ISSUE THREAD

**Issue by aquadraht** [CachetHQ/Cachet#3602]
Hi,

I recently upgraded via git from 2.3.9 to 2.3.16.
All works fine apart from one page in dashboard. When clicking _/dashboard/settings/localization_
I get an error 500.

Best regards,
a2

**Comment by jbrooksuk** [comment]
Thanks for reporting this. I _might_ have to pick this up tonight, but I'm going to have a quick look now.

**Comment by jbrooksuk** [comment]
This is fixed in 1bc48e0c607dd369bc652f09839a63a0e66b1d50 which has been released as v2.3.18.
