### ISSUE TITLE
Demo broken

### ISSUE THREAD

**Issue by noplanman** [CachetHQ/Cachet#3612]
Just wanted to check out the [demo dashboard](https://dev.cachethq.io/dashboard), but the `.env` file has some syntax error:
`The environment file is invalid: Dotenv values containing spaces must be surrounded by quotes.`

**Comment by jbrooksuk** [comment]
Thanks for reporting @noplanman. I'll investigate this now.

**Comment by jbrooksuk** [comment]
I've fixed the demo, but it looks like we need to fix how Cachet writes these values too.
