### ISSUE TITLE
404 on resources when custom path

### ISSUE THREAD

**Issue by anthosz** [CachetHQ/Cachet#3618]
Hello,

Following issue #2977 and a request to slack. I cannot install cachet with a custom path.

Example: http://127.0.0.1/cachet
APP URL is the same in all case. 

If I add RewriteBase, only page seems to works but 127.0.0.1/cachet/setup/ cannot load ressources (like js/css...etc). Indeed, the browser try to get resources from 127.0.0.1/build/... instead 127.0.0.1/cachet/build/...

If I don't add RewriteBase, I have 404 for all pages but ressources links are ok..

Versions:
Apache 2.4
Php 7.2
Cachet 2.3.18

Best regards,

**Comment by anthosz** [comment]
I just find public/build/rev-manifest.json but it's not absolute path.

The goal is to find where is generated "/build" & to force the root path before..

**Comment by anthonybocci** [comment]
Hello,

Thank you for coming from Slack to here. I'll try to illustrate the issue, and check in the code what we have to do.

Firstly, to illustrate your problem (if I correctly understand it), here is a screenshot of the setup page.

![cachet-setup-no-rewrite-base](https://user-images.githubusercontent.com/7780244/58348087-e629c200-7e5f-11e9-9b19-51e0da6267fc.png)

On my fresh install the URL is `http://localhost/cachet/Cachet/public/index.php/setup`. I've set no virtual host in Apache, I use the default one here.  
The problem on this page is some requests are not using the `APP_BASE`  environment variable as a base path. An example of request is `/dist/css/all-2812406e36.css`, the path is given as absolute and the environment variable is not used.

**Comment by anthosz** [comment]
Thank you @anthonybocci ,

This is exactly the issue that I have.

For now I use this workaround but it's pretty dirty:
>   AddOutputFilterByType SUBSTITUTE text/html text/css application/javascript
>   Substitute "s@/(auth|setup|build|img)@/cachet/$1@i"

After that, once installed & logged, I have an issue with the root page (but seems not related to this topic):
> [2019-05-24 07:33:35] dev.ERROR: ErrorException: count(): Parameter must be an array or an object that implements Countable in /cachet/vendor/laravel/framework/src/Illuminate/Database/Eloquent/
Builder.php:1161


Best regards,

**Comment by anthonybocci** [comment]
@anthosz thank you for sharing your workaround. I've understood the problem, I just need to fix one thing and it will be ok.

The error your said before updating your message about a `count` function waiting for an instance of `Countable` is because you were using PHP 7.2. Cachet is PHP 7.2-compatible from the version 2.4~dev. Not 2.3.X.

**Comment by anthosz** [comment]
@anthonybocci 

I confirm that the error (count) has been fixed in 2.4 (dev).

Please note btw that we have the same issue on 2.4 concerning resources call.

Workaround for 2.4:
>   AddOutputFilterByType SUBSTITUTE text/html text/css application/javascript
>   Substitute "s@/(auth|build|dashboard/api|dist)@/fpfis/webtools/cachet/$1@i"
>   Substitute "s@/(fonts/)@/cachet/$1@i"

But the path of fonts are ok once logged but not ok when not logged (anonymous).

Best regards,

**Comment by anthosz** [comment]
@anthonybocci 

I confirm that the error (count) has been fixed in 2.4 (dev).

Please note btw that we have the same issue on 2.4 concerning resources call.

Workaround for 2.4:
>   AddOutputFilterByType SUBSTITUTE text/html text/css application/javascript
>   Substitute "s@/(auth|build|dashboard/api|dist)@/cachet/$1@i"
>   Substitute "s@/(fonts/)@/cachet/$1@i"

But the path of fonts are ok once logged but not ok when not logged (anonymous).

Best regards,

**Comment by jbrooksuk** [comment]
This should now be fixed!

**Comment by anthosz** [comment]
Dear @jbrooksuk ,

There is only one problem left concerning ionicons.svg & ionicions.woff called by /dist/css/app.css (dashboard anonymous & logged)

The link to woff/svg in the CSS is url("../../../fonts/ionicons.ttf?v=2.0.1" instead url("/a/b/c/fonts/ionicons.ttf?v=2.0.1"

For the rest, all seems fixed now :)

Thx!

**Comment by jbrooksuk** [comment]
I believe @anthonybocci has fixed fonts now?

**Comment by anthonybocci** [comment]
@jbrooksuk I didn't touch the fonts. I'll check during the week-end to remember the problem, reproduce it and see if I can fix it. I'll let you know.

**Comment by anthonybocci** [comment]
I just tested now with 2.3 and 2.4 since I didn't know about what version you were talking about, but I have no 404 in my browser. I guess you are talking about 2.4, so @anthosz could you lead me to reproduce the 404? I checked in my browser's console.

**Comment by anthosz** [comment]
@anthonybocci  it's 2.4 (revision c74193e37e07b7a2858ffc1a26df01c574279afa Sat Jul 13 17:31:27 2019 +0100).

So to summarize, you just need to go on the root page (like example.org/subdirectory/sub2/cachet) (anonymous & logged) and the url is not ok for *.ttf/*.woff :
![image](https://user-images.githubusercontent.com/14294064/61526159-2cdc0880-aa1a-11e9-92d5-aaf7719071ef.png)

In our case, instead to call these resources on example.org/subdirectory/sub2/cachet/fonts/*.*, these resources are called on example.org/subdirectory/sub2/fonts/*.* (missing /cachet)

.env:
APP_URL=http://example.org/subdirectory/sub2/cachet
apache conf:
RewriteBase /subdirectory/sub2/cachet

**Comment by pavanfhw** [comment]
@anthosz @nalysius @jbrooksuk 
I'm having this issue. I'm running on Docker and built using this [Dockerfile](https://github.com/CachetHQ/Docker/blob/main/Dockerfile) with version 2.4. 
I have APP_URL set to `https://mydomain.com/status` but I still get 404 on all request to js and css. 
I trtied adding `RewriteBase /status` to `/var/www/html/public/.htaccess` but no change.

 The setup page is exactly like in the example of this issue. What do I have to do to work?

**Comment by anthosz** [comment]
> @anthosz @nalysius @jbrooksuk I'm having this issue. I'm running on Docker and built using this [Dockerfile](https://github.com/CachetHQ/Docker/blob/main/Dockerfile) with version 2.4. I have APP_URL set to `https://mydomain.com/status` but I still get 404 on all request to js and css. I trtied adding `RewriteBase /status` to `/var/www/html/public/.htaccess` but no change.
> 
> The setup page is exactly like in the example of this issue. What do I have to do to work?

This project is not maintained anymore

**Comment by pavanfhw** [comment]
I know, but should the issue been fixed in the latest version?

**Comment by anthosz** [comment]
> I knwo, but should the issue been fixed in the latest version?

The last version is old of more/less 4 years so.. during this time, laravel/php/composer has been updated so no make sense to use it...

You need to switch to another solution (not found a correct one on our side so switched to commercial solution)

**Comment by pavanfhw** [comment]
You are right. Thank you for answering me!

**Comment by nalysius** [comment]
> @anthosz @nalysius @jbrooksuk I'm having this issue. I'm running on Docker and built using this [Dockerfile](https://github.com/CachetHQ/Docker/blob/main/Dockerfile) with version 2.4. I have APP_URL set to `https://mydomain.com/status` but I still get 404 on all request to js and css. I trtied adding `RewriteBase /status` to `/var/www/html/public/.htaccess` but no change.
> 
> The setup page is exactly like in the example of this issue. What do I have to do to work?

The easiest would be to use a subdomain status.mydomain.com, so no problems with this.
But as said by anthosz, the project has not been maintained for several years, I don't recommend to use it.

The other day I was thinking about creating a status page, way simpler than Cachet, just a Symfony API, a front-end, no JavaScript. An API compatible with Cachet, so the modules would still work. Something easy to maintain and with as few dependencies as possible. I have to think about it, if it's a good idea or not.
