### ISSUE TITLE
Each setting update requires app:update to take effect

### ISSUE THREAD

**Issue by tarreislam** [CachetHQ/Cachet#3625]
Hi!

Every time I make a change thru the settings, I have to run `app:update` for the changes to "take effect".

Whats up with that?

Ive used both redis and file as cache-driver

**Comment by jbrooksuk** [comment]
Hi @tarreislam. What version of Cachet are you using? Settings get cached into `./bootstrap/cachet/production.php`. Do you know if this file is changing when you modify a setting?

**Comment by dsneath** [comment]
I would like to confirm that this is an issue for us as well, 2.4.0-dev

**Comment by tarreislam** [comment]
What more information is needed.

1. Setup a fresh install on ububtu without docker.
2. Try to do anything

**Comment by tarreislam** [comment]
> Hi @tarreislam. What version of Cachet are you using? Settings get cached into `./bootstrap/cachet/production.php`. Do you know if this file is changing when you modify a 

Hi, this was an issue with permissions. Just give `www-data` or whatever your webserver uses. Strange thing is that no error was thrown, try catch mutch?

for the copy-pastos:

`sudo chown administrator:www-data -R bootstrap/`
`sudo chmod 775 -R bootstrap/`
