### ISSUE TITLE
missing translation

### ISSUE THREAD

**Issue by Finkregh** [cachethq/Cachet#364]
Some strings are hardcoded/can not be translated.
e.g. https://github.com/cachethq/Cachet/blob/425244f29e16775a1b70717cdbe81853f374e05a/src/Http/Controllers/DashSettingsController.php#L171

**Comment by jbrooksuk** [comment]
Good catch, a lot of error handling was added before we had translations.

**Comment by jbrooksuk** [comment]
We should create an `errors.php` language file for this.
