### ISSUE TITLE
Installation Problems

### ISSUE THREAD

**Issue by olliware** [CachetHQ/Cachet#3647]
Hey everyone,

I am new to Cachet and although familiar with Composer (Pixelfed also runs with Composer) I tried to follow the installation instructions located at https://docs.cachethq.io/docs/installing-cachet. After checking all prerequisites (MariaDB-db working as well), I do my "php artisan app:install" and get the following error:

> > Clearing settings cache...
> Settings cache cleared!
> Backing up database...
> Dumping database and uploading...
> 
> Successfully dumped mysql, compressed with gzip and store it to local at 2019-06-09 13.35.05
> Backup completed!
> Application key [base64:aSGMeRTDZjQlunoA1TC6V/DN1b4Y3W5XDz7CZIjmOag=] set successfully.
> Configuration cache cleared!
> Configuration cached successfully!
> Route cache cleared!
> Routes cached successfully!
> Copied Directory [/vendor/roumen/feed/src/views] To [/resources/views/vendor/feed]
> Publishing complete for tag []!
> Nothing to migrate.
> Clearing cache...
> PHP Fatal error:  Uncaught ErrorException: count(): Parameter must be an array or an object that implements Countable in /var/www/cachet/vendor/graham-campbell/exceptions/src/ExceptionIdentifier.php:51
> Stack trace:
> #0 [internal function]: Illuminate\Foundation\Bootstrap\HandleExceptions->handleError(2, 'count(): Parame...', '/var/www/cachet...', 51, Array)
> #1 /var/www/cachet/vendor/graham-campbell/exceptions/src/ExceptionIdentifier.php(51): count(NULL)
> #2 /var/www/cachet/vendor/graham-campbell/exceptions/src/ExceptionHandlerTrait.php(47): GrahamCampbell\Exceptions\ExceptionIdentifier->identify(Object(ErrorException))
> #3 /var/www/cachet/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(79): GrahamCampbell\Exceptions\ExceptionHandler->report(Object(ErrorException))
> #4 [internal function]: Illuminate\Foundation\Bootstrap\HandleExceptions->handleException(Object(ErrorException))
> #5 {main}
>   thrown in /var/www/cachet/vendor/graham-campbell/exceptions/src/ExceptionIdentifier.php on line 51
> PHP Fatal error:  Uncaught ErrorException: count(): Parameter must be an array or an object that implements Countable in /var/www/cachet/vendor/graham-campbell/exceptions/src/ExceptionIdentifier.php:51
> Stack trace:
> #0 [internal function]: Illuminate\Foundation\Bootstrap\HandleExceptions->handleError(2, 'count(): Parame...', '/var/www/cachet...', 51, Array)
> #1 /var/www/cachet/vendor/graham-campbell/exceptions/src/ExceptionIdentifier.php(51): count(NULL)
> #2 /var/www/cachet/vendor/graham-campbell/exceptions/src/ExceptionHandlerTrait.php(47): GrahamCampbell\Exceptions\ExceptionIdentifier->identify(Object(Symfony\Component\Debug\Exception\FatalErrorException))
> #3 /var/www/cachet/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(79): GrahamCampbell\Exceptions\ExceptionHandler->report(Object(Symfony\Component\Debug\Exception\FatalErrorException))
> #4 /var/www/cachet/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(118): Illuminate\Foundation\Bootstrap\HandleExceptions->h in /var/www/cachet/vendor/graham-campbell/exceptions/src/ExceptionIdentifier.php on line 51

System is Debian 9 "Stretch", running with Nginx and PHP-PFM 7.3.

Any clues on that?

Thanks in advance,

Oliver

**Comment by anthosz** [comment]
Hi @olliware,

If you use PHP 7.2, you need to use branch 2.4 (current 2.3 doesn't works with PHP 7.2)

Best regards,

**Comment by olliware** [comment]
Thanks for the info, this could help as I am using PHP 7.3 here... Will give it a try, thanks!
