### ISSUE TITLE
Translation issues in some languagages

### ISSUE THREAD

**Issue by MartinHynek** [CachetHQ/Cachet#3655]
It seems that one of strings which should be translated is not in code anymore and now Incidents page could not be loaded. It ends with app error 500. As far as i know, its in Czech translation and some other.

This error can be identified by 83f017e8-8099-4318-b542-29e40d5b674a. You might want to take a note of this code.

Could anyone confirm that? Version 2.3.18

Thx

**Comment by jbrooksuk** [comment]
@MartinHynek I've added you to the Czech translations. Please feel free to adjust them :)
