### ISSUE TITLE
RSS feed

### ISSUE THREAD

**Issue by ebaan** [CachetHQ/Cachet#3657]
Hi, just managed to install Cachet 2.4.0-dev running on Ubuntu using nginx. I see in some of the examples that there is an option of RSS feed? Just does not show in my footer and domain/rss results in error?

New to this all, so please be gentle....

**Comment by jbrooksuk** [comment]
Hi @ebaan, 2.4 has currently removed the RSS feeds, but we're actually in the process of re-implementing them in #3659. Follow progress there :)
