### ISSUE TITLE
A new python 3.6+ client library for Cachet

### ISSUE THREAD

**Issue by einarf** [CachetHQ/Cachet#3658]
Just released a new python 3.6+ client library for Cachet: https://github.com/ZettaIO/cachet-client

The other python library by David Moreau Simard is fairly simple and definitely still very useful for 2.3.x users. There was room for a more complex library that is easier to use when doing more complex interactions with Cachet. We also wanted 2.4 support. (some work remaining + docs)

**Comment by jbrooksuk** [comment]
Hi @einarf! Thanks for creating this! I'll add it to the documentation now.
