### ISSUE TITLE
make language-chooser dynamic

### ISSUE THREAD

**Issue by Finkregh** [cachethq/Cachet#366]
It would be nice if new translation would be available wihtout [further interventions](https://github.com/cachethq/Cachet/pull/365) as soon as there is a directory in app/lang/.

This also includes that the languages' name have to be included in the lang-files.

**Comment by jbrooksuk** [comment]
Yeah, this should be quite easy to do by globbing the `./app/lang` directory. The only thing is working out what that language code relates to. Then use `locale_get_display_language`?

**Comment by jbrooksuk** [comment]
I rebased a few times. Sorry.
