### ISSUE TITLE
Amendments to notifications for maintenance

### ISSUE THREAD

**Issue by misterjaytee** [CachetHQ/Cachet#3665]
For maintenance items, currently subscribers only get a notification that a maintenance item was created.

Please could we make the following amendments to notifications for maintenance items:

- Make sure that the description is in the email so that subscribers don't have to visit the status website to find out more detail about the maintenance item and also let them know what component and/or component group it affects (associating a maintenance item to a component is covered by #3470)

- Send out a notification when a scheduled maintenance item is updated - especially important if the date changes, or if the scheduled maintenance item gets cancelled

- Have the ability to send out an update on completion of the scheduled maintenance with any closing comments (e.g. to let users know that there may be a known issue; or at least to confirm when the maintenance completed)

**Comment by jbrooksuk** [comment]
Your last two points are actively being addressed in https://github.com/CachetHQ/Cachet/pull/3687 by @atymic :)

**Comment by pmkakaci** [comment]
Hello guys, 
I'm pretty interrested about this one too :)
Available for testing it if needed

**Comment by jbrooksuk** [comment]
Thank you for your input on Cachet 2.x. We are shifting our attention and resources to Cachet 3.x and will no longer be supporting the 2.x version. If your feedback or issue is relevant to the 3.x series, we encourage you to engage with the new branch.

For more information on the Cachet rebuild and our plans for 3.x, you can read the announcement [here](https://github.com/CachetHQ/Cachet/discussions/4342).

We appreciate your understanding and look forward to your contributions to the new version.
