### ISSUE TITLE
In-Context translation problem

### ISSUE THREAD

**Issue by MartinHynek** [CachetHQ/Cachet#3666]
It seems Crowdin In-Context translation is not working properly, some strings are taken from selected language (Czech and some others), some are taken from en-UD or not taken at all, why? 

For example 0{0}crwdne305:0 or [Unrecognized text] (String is not loaded. Probably it has been deleted.)

**Comment by jbrooksuk** [comment]
Can you please provide a screenshot?

**Comment by MartinHynek** [comment]
Sure, screen here.. 
![status_site](https://user-images.githubusercontent.com/1277548/61050832-2df0b280-a3e8-11e9-968e-dd379c52855f.png)

**Comment by MartinHynek** [comment]
Any updates? I would like to finish translations

**Comment by jbrooksuk** [comment]
Ah, I think you'll need to use the 2.4 branch as everything works fine there.

![image](https://user-images.githubusercontent.com/246103/63001520-b5a86180-be6b-11e9-9e93-15920a4f2168.png)
