### ISSUE TITLE
Out of Office! (I'm getting married! 🤵🏻)

### ISSUE THREAD

**Issue by jbrooksuk** [CachetHQ/Cachet#3667]
Hey everyone 👋,

I just wanted to leave a quick message here to let you know that I'm getting married on Saturday and so I will be Out Of Office until the 8th July!

During this time, support tickets and issues will not be replied to by myself. Once I'm back, I'll go through all issues and support tickets.

See you when I get back!

Thanks,

James

**Comment by jasoryeh** [comment]
Congrats!

**Comment by jbrooksuk** [comment]
I'm back! I'll be catching up later.
