### ISSUE TITLE
Buttons missing and website shows number code instead of special characters

### ISSUE THREAD

**Issue by mhauptmann** [CachetHQ/Cachet#3668]
Hello everybody,

I have Cachet installed and the website does not translate the special characters properly. Normally "Ticketsystem &#40;Web, Mail&#41;" should be interpreted in "Ticketsystem (Web, Mail)".
![image](https://user-images.githubusercontent.com/35134598/60251626-2bab3600-98c9-11e9-9925-8664c356cfde.png)

In addition, the buttons "Next" and "Back" are missing at the bottom of the website.
![image](https://user-images.githubusercontent.com/35134598/60251665-4382ba00-98c9-11e9-9516-6ab00c924794.png)

PHP version:
![image](https://user-images.githubusercontent.com/35134598/60251327-a3c52c00-98c8-11e9-9a9a-3e5d3716caab.png)

Composer version:
![image](https://user-images.githubusercontent.com/35134598/60251377-b7709280-98c8-11e9-9829-b198b935b487.png)

Apache2 version:
![image](https://user-images.githubusercontent.com/35134598/60251460-db33d880-98c8-11e9-9296-9e05a94aa243.png)

Cachet version:
![image](https://user-images.githubusercontent.com/35134598/60251581-12a28500-98c9-11e9-8d1c-0fdfd9f192e6.png)

Thanks and best regards,
Marcel

**Comment by jbrooksuk** [comment]
> I have Cachet installed and the website does not translate the special characters properly. Normally "Ticketsystem (Web, Mail)" should be interpreted in "Ticketsystem (Web, Mail)".

Hey! What did you enter for this to happen? I copied the text above and can see the names correctly.
![image](https://user-images.githubusercontent.com/246103/61049780-40b1ba00-a3dd-11e9-945f-ade06c91917f.png)

Is there any chance I can get a dump of your `components` table, please?

> In addition, the buttons "Next" and "Back" are missing at the bottom of the website.
> ![image](https://user-images.githubusercontent.com/35134598/60251665-4382ba00-98c9-11e9-9516-6ab00c924794.png)

I assume you have no incidents.

**Comment by mhauptmann** [comment]
Hi!

Thanks for your reply.

> What did you enter for this to happen? I copied the text above and can see the names correctly.

I cannot write the code here because the browser will interpret it as correct writing. So here is a screenshot what I expect (I changed it in the admin panel in the section "components"):

![image](https://user-images.githubusercontent.com/35134598/61057270-369bb580-a3f5-11e9-9a08-52118ae40326.png)

And after I hit the "Save" button that's what I get:

![image](https://user-images.githubusercontent.com/35134598/61057294-49ae8580-a3f5-11e9-9afe-d8fc8140e21a.png)

The only difference to our old instance (we migrated it to a new server) is that the old server used mysql and the new server is running on mariadb. What I checked so far is the charset from the database but thats the same, utf8_unicode_ci.

The old system used php 7.0 and the new one uses php 7.3 but I also switched to php 7.0 with the same result.

> Is there any chance I can get a dump of your components table, please?

Yes, it is possible, could you please provide me an email address?

> I assume you have no incidents.

As you can see in the following screenshots we had some incidents in the past:

![image](https://user-images.githubusercontent.com/35134598/61057677-11f40d80-a3f6-11e9-97ed-bcc003887f16.png)

If I change my local hosts file to the old server, the buttons are visible and I can see messages from the past if I hit the buttons serveral times:

![image](https://user-images.githubusercontent.com/35134598/61057846-613a3e00-a3f6-11e9-9645-36a1ea4816a2.png)

Thanks for your help in advance.

**Comment by jbrooksuk** [comment]
I believe I fixed this :)
