### ISSUE TITLE
Cachet saturating MySQL after 6 months of data

### ISSUE THREAD

**Issue by cristiancs** [CachetHQ/Cachet#3671]
I have been experiencing high cpu usage from MySQL last weeks, after some hours of troubleshooting i found out that a query from cachet was making my CPU spike to 100% every 2 minutes or so.

```SET timestamp=1554227587;
select * from `metric_points` where `metric_id` = 1 and `value` = 8 and `created_at` >= '2019-04-02 17:53:00' limit 1;
# Time: 2019-04-02T18:49:06.678673Z
# User@Host: root[root] @ localhost []  Id: 402760
# Query_time: 1.297839  Lock_time: 0.007619 Rows_sent: 0  Rows_examined: 101831
```

For now i moved the old records to a new table and deleted the data on metric_points, but maybe some indices on the table could help, or at least empty the table every month or something like that.

**Comment by cristiancs** [comment]
Some extra thinkering, i think is related with the insertion of data, i run this script https://github.com/stayallive/pingdom-to-cachet every minute from a cronjob and due a problem the script didn't run for two weeks, this 2 weeks, the CPU usage was 1-2%

**Comment by jbrooksuk** [comment]
The amount of data will definitely impact performance. I'd suggest that you could look at deleting old data where you no longer need it, but Cachet won't do this for you.
