### ISSUE TITLE
Mail settings not save

### ISSUE THREAD

**Issue by duysmil** [CachetHQ/Cachet#3688]
Hey, i run version 2.4 and after i change in settings--->mail all to smtp and save it it reset it to log.

Anyone knew what i do wrong

**Comment by pridit** [comment]
Related to #3625?

**Comment by duysmil** [comment]
I solve this.

Reinstall flesh New cachet.

Please close post.

Thanks.

Em ter, 2 de jul de 2019 20:26, Jordan Heale <notifications@github.com>
escreveu:

**Comment by atymic** [comment]
You can close it your self, just press the close button :)

**Comment by duysmil** [comment]
Solved.

Thanks
