### ISSUE TITLE
URL markdown in incident updates is breaking HTML container

### ISSUE THREAD

**Issue by pridit** [CachetHQ/Cachet#3689]
Within the incident itself this appears as expected. However with updates:

![XQkYsl](https://user-images.githubusercontent.com/12836049/60552510-07b37e80-9d27-11e9-98f1-db58d355acfb.png)
`This a [test](https://google.com) with a URL`

Through inspect element I can observe the following:
```html
<p><a href="#" class="list-group-item incident-update-item">This is a </a><a href="https://google.com">test</a> with a URL</p>
```

**Version**
2.4.0-dev

**Comment by jbrooksuk** [comment]
@ojdon one for you, pal!
