### ISSUE TITLE
Email notification text is not translated

### ISSUE THREAD

**Issue by duysmil** [CachetHQ/Cachet#3690]
How I can Change This Message in subscribe e-mail?

Not locate in lang files this message

"
If you’re having trouble clicking the "Accept" button, copy and paste the URL below into your web browser:
"

**Comment by jbrooksuk** [comment]
You need to edit `/resources/views/vendor/notifications/email.blade.php`. Looks like that's a language string that's missing!

**Comment by duysmil** [comment]
> You need to edit `/resources/views/vendor/notifications/email.blade.php`. Looks like that's a language string that's missing!

Thanks.

**Comment by jbrooksuk** [comment]
r

**Comment by duysmil** [comment]
> Keeping this open so we can fix it.


Oks, there are another files to change...

In e-mails of new and update incidents/schedule, the message say "thanks"  i locate "thanks" in files in this folder

/var/www/cachet/resources/views/notifications/incident
/var/www/cachet/resources/views/notifications/component
/var/www/cachet/resources/views/notifications/schedule

**Comment by goodgunner** [comment]
Hello, i am trying something thats in line with this issue. i want to change the language of the notification emails to dutch but i cant seem to find where i can configure this. halve the teksts are in english when sending a notification. any help on this subject?

**Comment by pavog** [comment]
@goodgunner Hi, have you set the site language to Dutch in Dashboard -> Settings -> Localization?

**Comment by goodgunner** [comment]
ah thank you. it seems i needed to change it from "nederlands" to "nl-NL" its strange how that works

**Comment by pavog** [comment]
@goodgunner Glad it's working now :) Yes, it is a bit strange. We have some translations with just the language code and some with the language and country codes. I think it's because the translations come from Crowdin.

**Comment by DennisSkov** [comment]
How would we go about translating this?
```
@lang('Thanks')
@lang('Regards')
```
Which file would need to be created/edited? I don't see any existing translations for these strings.

**Comment by jbrooksuk** [comment]
Thank you for your input on Cachet 2.x. We are shifting our attention and resources to Cachet 3.x and will no longer be supporting the 2.x version. If your feedback or issue is relevant to the 3.x series, we encourage you to engage with the new branch.

For more information on the Cachet rebuild and our plans for 3.x, you can read the announcement [here](https://github.com/CachetHQ/Cachet/discussions/4342).

We appreciate your understanding and look forward to your contributions to the new version.
