### ISSUE TITLE
Saving Mail-Settings gives Error 500

### ISSUE THREAD

**Issue by ktownmods** [CachetHQ/Cachet#3691]
Hey, if i click on mail settings on save (smtp) it gives me an error 500
Using 2.4
In log is this

`#68 {main} {"identification":{"id":"4864b657-6596-446c-9b16-8230c70674d6"},"exception":"[object] (ErrorException(code: 0): file_put_contents(/var/www/clients/client0/web8/web/.env): failed to open stream: Permission denied at /var/www/clients/client0/web8/web/app/Bus/Handlers/Commands/System/Config/UpdateConfigCommandHandler.php:62)
`

Thanks

**Comment by ktownmods** [comment]
No one an idea?

**Comment by duysmil** [comment]
> No one an idea?

Chmod 664 in  .env file
Chmod 775 in storage and bootstrap folder

**Comment by ktownmods** [comment]
> Chmod 775 in storage and bootstrap folder

chmod 775 onyl the 2 Folders, or the files inside also?

**Comment by jbrooksuk** [comment]
644 should be plenty for the `.env` file. 

755 also works for the `storage` and `bootstrap` directories.

**Comment by ktownmods** [comment]
> 644 should be plenty for the `.env` file.
644 for .env not work, use 664

Another question so i dont open another issue
is there an option now available for gdpr?

**Comment by jbrooksuk** [comment]
Not yet, sorry!

**Comment by ktownmods** [comment]
ok so i have to disable the email sub function, because in germany it is very strong with this shit gdpr
