### ISSUE TITLE
Error 500 when subscribing to email notifications 

### ISSUE THREAD

**Issue by dadall** [CachetHQ/Cachet#3693]
Hi,

I've a fresh install via docker-compose. I can subscribe to the email notification system, confirm it and receive actual notifications but when I click on subscribe, CachetHQ sent me an error 500.

Any idea ?

**Comment by duysmil** [comment]
> Hi,
> 
> I've a fresh install via docker-compose. I can subscribe to the email notification system, confirm it and receive actual notifications but when I click on subscribe, CachetHQ sent me an error 500.
> 
> Any idea ?

Verify if your e-mail configuration is OK.  

Edit .env em root folder to confirm this.

This section, one example.

MAIL_DRIVER=smtp
MAIL_HOST=smtp.gmail.com
MAIL_PORT=587
MAIL_USERNAME=emailusername
MAIL_PASSWORD=emailpassword
MAIL_ADDRESS=emailusername@gmail.com
MAIL_NAME="Infra - Notify"
MAIL_ENCRYPTION=tls

**Comment by jbrooksuk** [comment]
@duysmil is correct. There will be an error only if Cachet was unable to send the email.
