### ISSUE TITLE
Demo page never allows you to login from CNAME URL

### ISSUE THREAD

**Issue by jbrooksuk** [cachethq/Cachet#370]
Something is wrong with the demo site (I've just pushed the latest changes). After setup, if you logout and then back in again, it'll simply redirect you back to the login page without an error message.

https://status.cachethq.io/auth/login

**Comment by jbrooksuk** [comment]
Nevermind. Fully redeployed and it worked.

**Comment by jbrooksuk** [comment]
Nevermind. Fully redeployed and it worked.

**Comment by jbrooksuk** [comment]
Nope. I lied.

The problem occurs when you attempt to login via https://status.cachethq.io but if you login using the https://cachet.herokuapp.com it works fine.

**Comment by joecohens** [comment]
Does this has to be with the proxied domains ? Maybe we should add or change the default domain to status.cachethq.io on the configs.

**Comment by jbrooksuk** [comment]
Perhaps... Let me reset the migrations.

**Comment by jbrooksuk** [comment]
Nope, still doesn't work.

**Comment by jbrooksuk** [comment]
I wonder if it's CloudFlare?

**Comment by joecohens** [comment]
I think CloudFlare it's disabled `Traffic will bypass CloudFlare's network` I'll enable it because we have the rule to force SSL.

**Comment by jbrooksuk** [comment]
I happened to just disable it.

**Comment by joecohens** [comment]
Lol we would need to disable the force SSL on the subdomain if that's the problem.

**Comment by GrahamCampbell** [comment]
Cloudflare cannot be causing this. Don't disable forcing ssl.

**Comment by noahbass** [comment]
^ this

**Comment by GrahamCampbell** [comment]
Also, even if it was cloudflare, we'd need to still get it working. Other people way want to use cachet behind cloudflare.

**Comment by noahbass** [comment]
Yeah. I'm doing a test on heroku + cloudflare right now to try to find some fixes to this

**Comment by GrahamCampbell** [comment]
thx :)

**Comment by jbrooksuk** [comment]
My thoughts on this:

- apcu, some weird config?
- Laravel config is not done properly?
- Sessions?

**Comment by GrahamCampbell** [comment]
Ahh yes. What have you configured the app url as @jbrooksuk?

**Comment by GrahamCampbell** [comment]
It needs to be set to "https://status.cachethq.io".

**Comment by jbrooksuk** [comment]
It's just set as `localhost` in `config.url`. The setup page will ask for the URL, so we should overwrite the setting.

**Comment by GrahamCampbell** [comment]
I think we might need to set it at an earlier point. That might be what's causing the issue.

**Comment by jbrooksuk** [comment]
Like we do with the timezone and locale?

**Comment by jbrooksuk** [comment]
@GrahamCampbell we are actually setting the `app.url` value https://github.com/cachethq/Cachet/blob/master/src/Http/Before/LoadConfigFilter.php#L26

**Comment by GrahamCampbell** [comment]
Oh wow, that stuff does not belong in a filter. It belongs in the register method of a service provider.

**Comment by jbrooksuk** [comment]
Yeah, I was playing with the idea earlier, but ran out of time :(

**Comment by joecohens** [comment]
Sorry my bad :(. @GrahamCampbell so we set a LoadConfigServiceProvider and move the filter code?

**Comment by GrahamCampbell** [comment]
Yeh, sounds like a plan.

**Comment by joecohens** [comment]
Perfect!

**Comment by noahbass** [comment]
Update on possible fixes: (Note: all of these were tested on heroku + cloudflare ssl)

### 1 [the `Request::setTrustedProxies` fix](http://www.laravel-tricks.com/tricks/fix-ssl-in-laravel-4-when-using-cloudflare)

It simply did not work.

### 2 [fideloper/TrustedProxy](https://github.com/fideloper/TrustedProxy)

It simply did not work.

### 3 the `$_SERVER` fix (adapted from [seedprod/laravel-cloudflare](https://github.com/seedprod/laravel-cloudflare))

#### 3.1 Throwing it into a filter

```php
public function filter()
{
    if (isset($_SERVER['HTTP_CF_VISITOR']) && preg_match('/https/i', $_SERVER['HTTP_CF_VISITOR'])) {
        $_SERVER['HTTPS'] = 'On';
        $_SERVER['HTTP_X_FORWARDED_PORT'] = 443;
        $_SERVER['SERVER_PORT'] = 443;
    }
}
```

and adding it to the `RoutingServiceProvider.php` in the `registerFilters` function. Does not work.

#### 3.2 Throwing it into a service provider

Same function as above renamed to `boot` in a new service provider. Then added to `app/config/app.php` providers. Does not work

#### 3.3 Throwing it into a `bootstrap/` file

Throwing this into `autoload.php` or `start.php` will work!!:

```php
if (isset($_SERVER['HTTP_CF_VISITOR']) && preg_match('/https/i', $_SERVER['HTTP_CF_VISITOR'])) {
    $_SERVER['HTTPS'] = 'On';
    $_SERVER['HTTP_X_FORWARDED_PORT'] = 443;
    $_SERVER['SERVER_PORT'] = 443;
}
```

### My conclusion

The fix works in a `bootstrap/` file, but not in a filter or service provider. So I'm thinking that putting this fix in a service provider or filter is too late for laravel to see and generate https urls.

**Comment by jbrooksuk** [comment]
@GrahamCampbell any idea on this? Is there a way to hook into `bootstrap.php` without actually placing the code there?

**Comment by GrahamCampbell** [comment]
There is a better way of doing this. See my cms again. :)

**Comment by GrahamCampbell** [comment]
https://github.com/fideloper/TrustedProxy
https://github.com/BootstrapCMS/CMS/blob/0.8/app/config/packages/fideloper/proxy/config.php

I've used the cloudflare server ips as the default in my cms config there. :)

**Comment by jbrooksuk** [comment]
@noahbass do you want to try it with the TrustedProxy package?

**Comment by pedrommone** [comment]
TrustedProxy is a good one, I use in my projects.

**Comment by noahbass** [comment]
@GrahamCampbell, @jbrooksuk 

Just did a test with https://github.com/fideloper/TrustedProxy. It didn't work.

**Comment by pedrommone** [comment]
Are you using behid a nginx or cloudflare?

**Comment by noahbass** [comment]
It's a heroku + cloudflare setup

**Comment by pedrommone** [comment]
Did you set cloudflare ips on white list? @GrahamCampbell posted one above.

**Comment by noahbass** [comment]
@pedrommone yes I did

**Comment by noahbass** [comment]
Okay. Now this is getting weird. Applying https://github.com/fideloper/TrustedProxy will fix the ssl issues on a *.herokuapp.com host for some reason, but not the cloudflare host.

**Comment by jbrooksuk** [comment]
@noahbass let's get one problem fixed at a time. Now we know TrustedProxy is fixing half of it, let's do that.

**Comment by jbrooksuk** [comment]
I've just pushed with the changes.

**Comment by jbrooksuk** [comment]
Even with the TrustedProxy fix, I'm still unable to login at `https://status.cachethq.io/dashboard` :(

**Comment by noahbass** [comment]
Unless we're doing something wrong on our end, then I guess this is an issue with [fideloper/TrustedProxy](https://github.com/fideloper/TrustedProxy).

**Comment by jbrooksuk** [comment]
Side note; we still need to fix the bloody unsecure forms.

**Comment by jbrooksuk** [comment]
Any other ideas on this? I don't see why we have an issue with logins just because we're running on a different domain?

**Comment by jbrooksuk** [comment]
Since we have no solution on this I replaced the `Form` facades with raw HTML in 5ac5f12d808cf3a6b70289c24acfaf75779ed286. It's now fixed.
