### ISSUE TITLE
Allow users to login to view components, but not have access to dashboard.

### ISSUE THREAD

**Issue by dwtuts** [CachetHQ/Cachet#3700]
Hey guys, 
I am looking into implementing this dashboard as an internal showcase of our services to managers and such. I would like them to be able to have accounts to view the components, but not to be able to get to the internal dashboard to post incidents. Is there a setting that I can change for this? Or some code I can modify? 
Thanks.

**Comment by jbrooksuk** [comment]
Yeah, we need to implement some kind of team permissions for this.
