### ISSUE TITLE
Last Hour on metrics not displaying any data.

### ISSUE THREAD

**Issue by lewisakura** [CachetHQ/Cachet#3707]
Similar issue to #1482, but instead of Postgres I am using MySQL.

**Comment by jbrooksuk** [comment]
Thanks for reporting! I'll investigate this later :)

**Comment by 633kh4ck** [comment]
@jbrooksuk Same here (`docker:2.3.15`), also there are similar issues: #2617, #3708

> I'll investigate this later :)

Are there any progress?

**Comment by voarsh2** [comment]
I get this two.
Workaround: use 12hr for metrics instead :D

**Comment by Ionys320** [comment]
Same issue here, with MySQL too

**Comment by jbrooksuk** [comment]
Thank you for your input on Cachet 2.x. We are shifting our attention and resources to Cachet 3.x and will no longer be supporting the 2.x version. If your feedback or issue is relevant to the 3.x series, we encourage you to engage with the new branch.

For more information on the Cachet rebuild and our plans for 3.x, you can read the announcement [here](https://github.com/CachetHQ/Cachet/discussions/4342).

We appreciate your understanding and look forward to your contributions to the new version.
