### ISSUE TITLE
Metrics not displaying completely.

### ISSUE THREAD

**Issue by flestorres** [CachetHQ/Cachet#3708]
Hello, I'm using the current 2.4 version for the cachet, and I encountered several issues about the metrics;

1. "hourly" metric display doesn't show the graph but data is saved in the database.
2. "12 hour" metric display, has display output, BUT, it saves only up to 4 recent points/hours. It doesn't fill the whole graph.

Are there any workaround of these to make them function well?

Thank you.

**Comment by jbrooksuk** [comment]
Thanks for reporting!

What database driver are you using?

**Comment by flestorres** [comment]
> Thanks for reporting!
> 
> What database driver are you using?

Yup thank you, currently using remote mysql database.

**Comment by jbrooksuk** [comment]
Okay, I'll take a look at this later :+1:

**Comment by flestorres** [comment]
> Okay, I'll take a look at this later 👍

Appreciate it, thank you!

**Comment by jbrooksuk** [comment]
I've had a look at this and I think now is a good opportunity to focus on rewriting the Metrics system as a priority.

This is going to take a bit of time, but in doing so, I reckon we can close off most of the Metrics related issues.

**Comment by flestorres** [comment]
Yup, metrics is somewhat left behind compared to other tools, I'm looking forward to this word from you. 
I'll be closing this, thank you, James.

Fles
