### ISSUE TITLE
Add support for vector images as custom logo

### ISSUE THREAD

**Issue by Pimorez** [CachetHQ/Cachet#3709]
Under the 'Theme' settings tab you can upload images. It would be great if vector images can be added so it can scale without causing artifacts.

![image](https://user-images.githubusercontent.com/4558098/61222220-8c849c00-a71a-11e9-9e37-f93cb44301db.png)

**Comment by jbrooksuk** [comment]
I’d actually like to change this feature to just link to an uploaded file. Currently we store this file in the DB which was dumb. 

However, in doing so, we will break the existing imagery. I guess we could support both for a while anyway.

**Comment by Pimorez** [comment]
A file uploaded to the server running the Cachet application you mean? Yeah
that would be a great solution as well.

**Comment by fredloy** [comment]
Add support for vector images as custom logo 2.4 and windows server 2016 
https://image.noelshack.com/fichiers/2019/33/7/1566164638-problem.png
system xampp database mariadb

**Comment by jbrooksuk** [comment]
Thank you for your input on Cachet 2.x. We are shifting our attention and resources to Cachet 3.x and will no longer be supporting the 2.x version. If your feedback or issue is relevant to the 3.x series, we encourage you to engage with the new branch.

For more information on the Cachet rebuild and our plans for 3.x, you can read the announcement [here](https://github.com/CachetHQ/Cachet/discussions/4342).

We appreciate your understanding and look forward to your contributions to the new version.
