### ISSUE TITLE
Incident and incident updates

### ISSUE THREAD

**Issue by flestorres** [CachetHQ/Cachet#3713]
Hi, so I've encountered this problem wherein the updates are all stuck in the 20th incident.
In my database, I have 24 incidents(id),
and, for incident updates I have already 25.
![Screen Shot 2019-07-17 at 11 57 10 AM](https://user-images.githubusercontent.com/50864583/61346115-30408a00-a88a-11e9-9cf9-d37176721f61.png)

for this image, incident update id is on the left and on the right is the incident id where they appeared. 
But. every time there is a new incident then it will update it, the update always goes to the 20th id.

when I do curl the incidents, it just shows up to 20th
![Screen Shot 2019-07-17 at 12 00 55 PM](https://user-images.githubusercontent.com/50864583/61346253-8f9e9a00-a88a-11e9-9e74-05c573b2d409.png)

I use a curl with jq -r '.data[].id' to get the ids.

Hi there is an additional encountered issue. I set the 1 day display of incidents in the page. So all past days are hidden and it has "<- Previous" button below. Whenever I click the previous button it returns to me an internal error 500.

Anyone experiencing this too?

**Comment by jbrooksuk** [comment]
Thank you for your input on Cachet 2.x. We are shifting our attention and resources to Cachet 3.x and will no longer be supporting the 2.x version. If your feedback or issue is relevant to the 3.x series, we encourage you to engage with the new branch.

For more information on the Cachet rebuild and our plans for 3.x, you can read the announcement [here](https://github.com/CachetHQ/Cachet/discussions/4342).

We appreciate your understanding and look forward to your contributions to the new version.
