### ISSUE TITLE
Can't create a new metric - error 500 internal server error

### ISSUE THREAD

**Issue by narczi** [CachetHQ/Cachet#3715]
[ X] You're running the latest release version of Cachet.
    [ X] Ensure that you're running at least PHP 5.5.9, you can check this by running php -v
    [ X] You've ran rm -rf bootstrap/cache/* from the root of your Cachet installation.

**### Your setup**

    What version of Cachet? 2.4.0
    What database driver? MySQL Ver 14.14 Distrib 5.7.26, for Linux (x86_64)
    What version of PHP? PHP 7.2.19-0ubuntu0.18.04.1

**### Expected behaviour**

Metric creation

### **Actual behaviour**

Whenver I try to create a new metric I get:

Error 500
Internal Server Error

When I try it using curl with the following command:
```
curl --request POST   --url http://192.168.0.10/api/v1/metrics   --data '{"name":"Test Metric","suffix":"s","description":"System Uptime
","default_value":1,"display_chart":1}'
```

I get:
`{"errors":[{"id":"7582bdb2-62f7-491b-aacd-7302fd51f806","status":401,"title":"Unauthorized","detail":"Authentication is required and has failed or has not yet been provided."}]}c`

So I tried it with my token:
```
curl --request POST -H "X-Cachet-Token: efuisdf78efnotrealhe"  --url http://192.168.0.10/api/v1/metrics   --data '{"name":"Test Metric","su
ffix":"s","description":"System Uptime","default_value":1,"display_chart":1}'
```

And I got:
`{"errors":[{"id":"1acc390c-2e3b-4f9b-8392-dfa4be1e75de","status":400,"title":"Bad Request","detail":"The request cannot be fulfilled due to bad syntax.","meta":{"details":["The name field is required.","The suffix field is required.","The default value field is required."]}}]}`

Here's my env file:
```

APP_ENV=production
APP_DEBUG=false
APP_URL=http://localhost
APP_TIMEZONE=UTC
APP_KEY=base64:encodedkey=
DEBUGBAR_ENABLED=false

DB_DRIVER=mysql
DB_HOST=localhost
DB_UNIX_SOCKET=null
DB_DATABASE=cachet
DB_USERNAME=homestead
DB_PASSWORD=veryhardpassword
DB_PORT=null
DB_PREFIX=null

CACHE_DRIVER=apc
SESSION_DRIVER=apc
QUEUE_DRIVER=sync

CACHET_BEACON=true
CACHET_EMOJI=false
CACHET_AUTO_TWITTER=true

MAIL_DRIVER=log
MAIL_HOST=null
MAIL_PORT=null
MAIL_USERNAME=null
MAIL_PASSWORD=null
MAIL_ADDRESS=null
MAIL_NAME=null
MAIL_ENCRYPTION=tls

REDIS_HOST=null
REDIS_DATABASE=null
REDIS_PORT=null

GITHUB_TOKEN=null

NEXMO_KEY=null
NEXMO_SECRET=null
NEXMO_SMS_FROM=Cachet

TRUSTED_PROXIES=
```

How can I authenticate and send a json that has a correct syntax? Also, why doesn't this work from the web interface?

**Comment by narczi** [comment]
Update: I managed to create a metric by adding the following to my second query:

`-H "Content-Type: application/json"`

I can see it in my web interface but I still can't edit, nor can I create a new one.

**Comment by ppmathis** [comment]
I can replicate the same issue with the web interface being unable to create new metrics when running PHP7.3 with Cachet 2.4 (commit `c74193e37e07b7a2858ffc1a26df01c574279afa`). According to the log files an undefined variable called `acceptableThresholds` is being used in the `/resources/views/dashboard/metrics/add.blade.php` Blade template.

Log file created by Laravel which shows a single GET request to `/dashboard/metrics/create` can be found here: https://gist.github.com/ppmathis/8409682cefa01a38cddd1b7f64507e22

Link to the Blade template which references the undefined variable: https://github.com/CachetHQ/Cachet/blob/2.4/resources/views/dashboard/metrics/add.blade.php#L61

It seems that this has been caused by commit 2efbaebe631601cd7d5b5bd96149b29222e1c65b, which removed passing the acceptable thresholds to the view with `->withAcceptableThresholds(Metric::ACCEPTABLE_THRESHOLDS);` inside `showAddMetric()`.

**Comment by warwickw** [comment]
Same error when trying to create a metric.

PHP v7.2.19
Cachet v2.4.0

**Comment by mehalter** [comment]
I also have the same error. Has anyone found a workaround for fix?

PHP v7.2.21
Cachet v2.4.0-dev

**Comment by RhvsW** [comment]
Same problem.

**Comment by jichangfeng** [comment]
Same error.

PHP 7.3.1 + Cachet v2.4 + CentOS release 6.8

**Comment by peter-t-kim** [comment]
Any resolution to this issue?  I have considered reverting the commit but not sure if this is the right approach... 

> I can replicate the same issue with the web interface being unable to create new metrics when running PHP7.3 with Cachet 2.4 (commit `c74193e37e07b7a2858ffc1a26df01c574279afa`). According to the log files an undefined variable called `acceptableThresholds` is being used in the `/resources/views/dashboard/metrics/add.blade.php` Blade template.
> 
> Log file created by Laravel which shows a single GET request to `/dashboard/metrics/create` can be found here: https://gist.github.com/ppmathis/8409682cefa01a38cddd1b7f64507e22
> 
> Link to the Blade template which references the undefined variable: https://github.com/CachetHQ/Cachet/blob/2.4/resources/views/dashboard/metrics/add.blade.php#L61
> 
> It seems that this has been caused by commit [2efbaeb](https://github.com/CachetHQ/Cachet/commit/2efbaebe631601cd7d5b5bd96149b29222e1c65b), which removed passing the acceptable thresholds to the view with `->withAcceptableThresholds(Metric::ACCEPTABLE_THRESHOLDS);` inside `showAddMetric()`.

**Comment by peter-t-kim** [comment]
For anyone still reading this thread, since at this time it seems this still isn't resolved, using the 2.3 branch seems to allow metrics to be created through the dashboard.  Hopefully the fix is added to 2.4 soon.

**Comment by jbrooksuk** [comment]
Fixed. Sorry about that.

**Comment by TheBags** [comment]
Tnx a lot

**Comment by warwickw** [comment]
Thanks

**Comment by Yokutto** [comment]
Hi @jbrooksuk,
I'm using the docker version of Cachet in version 2.4. How I can get the update of metrics working?
