### ISSUE TITLE
2.4 - Unable to create a new component via API: 400 The name field is required.

### ISSUE THREAD

**Issue by anthosz** [CachetHQ/Cachet#3718]
Dear all,

I cannot create a new component via curl API  (via https://docs.cachethq.io/reference#components):
`curl -X POST -H 'X-Cachet-Token:XXXXXX' --url https://XXXXXXX/api/v1/components --data '{"enabled":"true","group_id":3,"status":1,"link":"https://example.org","name":"test"}'`

Output: 
"status":400,"title":"Bad Request","detail":"The request cannot be fulfilled due to bad syntax.","meta":{"details":["The name field is required."]}

If I try to get all components or create/update incident, it works.

Revision used: 8f91f6d92f536745e09ecad36c05cbbf0f992185 Sun Jun 23 16:08:03 2019

**Comment by flestorres** [comment]
Hi, have you tried adding another header for your curl command like 

> -H "Content-Type: application/json;"

**Comment by anthosz** [comment]
thank you @flestorres, works now!
