### ISSUE TITLE
Does it support Bootstrap 4?

### ISSUE THREAD

**Issue by guoyunhe** [CachetHQ/Cachet#3725]
Hi, we have https://status.opensuse.org/ using Cachet. We made a Bootstrap 4 based theme for all openSUSE sites. But Cachet is using Bootstrap 3. Is here any way that we can use Bootstrap 4 with Cachet? Thanks!

**Comment by ojdon** [comment]
Hi @guoyunhe 

I'm currently working through migrating Cachet over to Bootstrap 4. 

If you are interested, you can track my progress over here: https://github.com/ojdon/Cachet/tree/updates/bootstrap 

Thanks
