### ISSUE TITLE
Empowerment 👋

### ISSUE THREAD

**Issue by Dancbeunny98** [CachetHQ/Cachet#3732]
Good day. For what queries you can search for ready-made modules, add-ons, or a bunch of api for specific needs.

For example. Checking the server status and automatically setting the values to the status of the panel. Check ping in the form of a graph in real time and assess the status. Synchronization of events with a discord server in a specific chat.

**Comment by jbrooksuk** [comment]
See https://docs.cachethq.io/docs/addons
