### ISSUE TITLE
Custom Metric Styling

### ISSUE THREAD

**Issue by GHRoss** [CachetHQ/Cachet#3736]
Hello,

We'd like to apply some custom styling to the metric graphs to fall in line with the rest of the branding on the status page, is this possible?

**Comment by jbrooksuk** [comment]
Thank you for your input on Cachet 2.x. We are shifting our attention and resources to Cachet 3.x and will no longer be supporting the 2.x version. If your feedback or issue is relevant to the 3.x series, we encourage you to engage with the new branch.

For more information on the Cachet rebuild and our plans for 3.x, you can read the announcement [here](https://github.com/CachetHQ/Cachet/discussions/4342).

We appreciate your understanding and look forward to your contributions to the new version.
