### ISSUE TITLE
Frequent Session Timeout

### ISSUE THREAD

**Issue by happicamper** [CachetHQ/Cachet#3743]
Version: Docker Image (2.3.15)
OS: CentOS 7
Issue: My Cachet is perfectly working without proxy. But when I use Nginx, it keeps me logged out more frequently, and somehow found that whenever I'm in the dashboard login, it is running on HTTPS but not secure which I think it has HTTP running scripts/files.   
Tried using `TRUSTED_PROXIES` via environment file but seems doesn't work even using a wildcard.

Hope you have time to shed some light on this matter, thank you!

**Comment by jbrooksuk** [comment]
Are you using Cloudflare or something?

**Comment by happicamper** [comment]
@jbrooksuk Hi, but no.

**Comment by jbrooksuk** [comment]
Any similar services? What `SESSION_DRIVER` are you using?

**Comment by happicamper** [comment]
We're just using Route 53. Where can I check the `SESSION_DRIVER`? I don't recall choosing one or just chose the default one.

**Comment by jbrooksuk** [comment]
It'll be in your `.env` file. I imagine you're using `array` or `file`. Try setting up Redis with it :)
