### ISSUE TITLE
Manage subscriber subscriptions from dashboard

### ISSUE THREAD

**Issue by tarreislam** [CachetHQ/Cachet#3747]
Hi.

It would be great if there was a possibility to change the subscription components under `/dashboard/subscribers` because now you can only delete them. Also if you add an component after a person has subscribed, they wont get notifications for the new components.

**PS**
It would be great if the "Allow people to signup to email notifications?"-option only would affect the status page and not the admin page. 

Im on the latest version

**Comment by jbrooksuk** [comment]
Thank you for your input on Cachet 2.x. We are shifting our attention and resources to Cachet 3.x and will no longer be supporting the 2.x version. If your feedback or issue is relevant to the 3.x series, we encourage you to engage with the new branch.

For more information on the Cachet rebuild and our plans for 3.x, you can read the announcement [here](https://github.com/CachetHQ/Cachet/discussions/4342).

We appreciate your understanding and look forward to your contributions to the new version.

**Comment by tarreislam** [comment]
lol I moved to uptimerobot after I didn't get a replay from this

**Comment by jbrooksuk** [comment]
> lol I moved to uptimerobot after I didn't get a replay from this

No hard feelings 😊
