### ISSUE TITLE
Redirect from login to dashboard uses HTTP not HTTPS 

### ISSUE THREAD

**Issue by peter-t-kim** [CachetHQ/Cachet#3760]
Hello Cachet and friends,

I have been stumped for a while, and although using the workaround fix with `\URL::forceSchema('https');` described in 
https://github.com/CachetHQ/Cachet/issues/2522
fixed the 400 errors within the dashboard itself, I still run into errors when logging in at
https://cachet.snc-dev.com:2443/auth/login as the response header location returned is
http://cachet.snc-dev.com:2443/dashboard
not
https://cachet.snc-dev.com:2443/dashboard.

I have tried modifying the nginx conf files, using different versions of the source, etc, all to no avail.

Please, if anyone knows how to solve this issue, I would be very grateful!!

Using:
CachetHQ/Docker 2.3.15
CachetHQ/Cachet 2.3.15

Thanks, Peter

**Comment by jbrooksuk** [comment]
Looks like you need to configure your trusted proxies.
