### ISSUE TITLE
v2.4

### ISSUE THREAD

**Issue by peterlaws** [CachetHQ/Cachet#3773]
Sorry if this has been asked before, however, am I being stupid?
>git clone .../cachethq/Cachet.git
cd Cachet
git tag -l

only lists v2.3.9 as the last version... How do we get v2.4?

**Comment by diegosouza** [comment]
@peterlaws still there is no tag/release for the 2.4 branch. That's why you don't see.

**Comment by peterlaws** [comment]
Ok, so, how do we get it, manually untar it?

**Comment by diegosouza** [comment]
Download it directly: https://github.com/CachetHQ/Cachet/archive/2.4.zip
Or if you've cloned the repo, execute: `git checkout 2.4`

I think now the issue can be closed.
