### ISSUE TITLE
Error pages reveal database password 

### ISSUE THREAD

**Issue by iMstr** [cachethq/Cachet#378]
The Symfony errror page shows the database password right in the Environment Variables. This can be a security threat that allows people who know a bug that they can trigger to display the database connection details.

**Comment by jbrooksuk** [comment]
You need to turn off `app.debug` mode within `./app/local/app.php`.

**Comment by jbrooksuk** [comment]
Ideally you should be putting your `ENV` variable to `production`.

**Comment by robertaspinall** [comment]
Can you please explain this?  There is no /app/local/app.php file, and what do you mean by setting the ENV variable to production?

**Comment by jbrooksuk** [comment]
With the latest version of Cachet, you need to change the `.env` file now. Specifically `APP_DEBUG=false` and `APP_ENV=production`.

**Comment by robertaspinall** [comment]
We've done that, but the verbose error pages persist.


Robert Aspinall

NOAA's National Ocean Service
CO-OPS/Information Systems Division
1305 East-West Highway
Bldg. SSMC4, Station Id 6314
Silver Spring, MD 20910

Robert.Aspinall@noaa.gov

**Comment by GrahamCampbell** [comment]
> We've done that, but the verbose error pages persist.

You need to clear your config cache and/or restart php5-fpm.

**Comment by robertaspinall** [comment]
That did it.  This needs to be in the docs.


Robert Aspinall

NOAA's National Ocean Service
CO-OPS/Information Systems Division
1305 East-West Highway
Bldg. SSMC4, Station Id 6314
Silver Spring, MD 20910

Robert.Aspinall@noaa.gov

**Comment by GrahamCampbell** [comment]
It's in laravel's docs.

**Comment by GrahamCampbell** [comment]
Or, actually, it should happen when you run composer install.

**Comment by GrahamCampbell** [comment]
You're meant to configure that before you run that, that way we cache the correct config.

**Comment by robertaspinall** [comment]
Laravel isn't even mentioned here:

https://docs.cachethq.io/v1.0/docs/installing-cachet

I also spoke too soon, the whole install is crashing now;

PHP Fatal error:  Call to undefined function Illuminate\\Cache\\apc_fetch()
in
/var/www/Cachet/vendor/laravel/framework/src/Illuminate/Cache/ApcWrapper.php
on line 32



Robert Aspinall

NOAA's National Ocean Service
CO-OPS/Information Systems Division
1305 East-West Highway
Bldg. SSMC4, Station Id 6314
Silver Spring, MD 20910

Robert.Aspinall@noaa.gov

**Comment by GrahamCampbell** [comment]
You either need to install the apc extension, or not use the apc driver...

**Comment by robertaspinall** [comment]
Is the APC driver explained somewhere?  I'm trying to follow the install
page, which is very minimal.  It got us up and running, but then we had
verbose error pages that gave up the database password.  This is how we got
to where we are now.

What are we missing?  Is there a list of example .env files somewhere in
the docs?  We'd be happy to use memcached, if we knew what .env settings
were appropriate.



Robert Aspinall

NOAA's National Ocean Service
CO-OPS/Information Systems Division
1305 East-West Highway
Bldg. SSMC4, Station Id 6314
Silver Spring, MD 20910

Robert.Aspinall@noaa.gov

**Comment by GrahamCampbell** [comment]
> Is the APC driver explained somewhere?

You're probably best with the file driver if you want minimal.

**Comment by jbrooksuk** [comment]
Hi Robert,

Everything that you'll want to configure is found in [`.env.example`](https://github.com/cachethq/Cachet/blob/master/.env.example) which you should copy to `.env`.

APC is very easy to install and is lightweight. DigitalOcean have a really useful [help topic](https://www.digitalocean.com/community/tutorials/how-to-install-alternative-php-cache-apc-on-a-cloud-server-running-ubuntu-12-04) on this - I advise you to check it out.

Memcached is fine to use too, but will require more configuration.

Cheers,

James

**Comment by GrahamCampbell** [comment]
The file driver has zero dependencies. :)
