### ISSUE TITLE
HTML entities in translations result in escaped entities

### ISSUE THREAD

**Issue by friek** [CachetHQ/Cachet#3780]
Some translations, for example [Dutch](https://github.com/CachetHQ/Cachet/blob/2.4/resources/lang/nl/pagination.php#L25) and [German](https://github.com/CachetHQ/Cachet/blob/2.4/resources/lang/de/pagination.php#L25) contain HTML entities in the translated text. I'm not sure if it's the case in all templates, but at least in 
[timeline.blade.php:14](https://github.com/CachetHQ/Cachet/blob/2.4/resources/views/partials/modules/timeline.blade.php#L14) the translated text is passed to the template engine as is. The template engine then escapes the '&' resulting in a literal '&amp;laquo' in the contents of the 'back' button in the pagination section, while it should actually be "«".

One possible fix would be to tell the template engine to output the translation content raw:
```blade
{!! trans('pagination.previous') !!}
```

.. but that may introduce unwanted side effects. Another possible solution would be to use html_entity_decode to convert the html entities from the translated text into the corresponding UTF-8 characters:
```blade
{{ html_entity_decode(trans('pagination.previous')) }}
```

**Comment by jbrooksuk** [comment]
I think in what will become v3, we use the JSON translation strings as these are much cleaner to manage and to use.

**Comment by jbrooksuk** [comment]
Thank you for your input on Cachet 2.x. We are shifting our attention and resources to Cachet 3.x and will no longer be supporting the 2.x version. If your feedback or issue is relevant to the 3.x series, we encourage you to engage with the new branch.

For more information on the Cachet rebuild and our plans for 3.x, you can read the announcement [here](https://github.com/CachetHQ/Cachet/discussions/4342).

We appreciate your understanding and look forward to your contributions to the new version.
