### ISSUE TITLE
Able to manage unverified subscriptions

### ISSUE THREAD

**Issue by pkoelemij** [CachetHQ/Cachet#3781]
I'm able to manage subscriptions of subscribers that didn't finish the verification process. This is reproducable by subscribing a test emailaddress. When you try to subscribe the same email address again, you get control over their subscription. If the subscriber is verified it shows an 'already registered' message.

**Comment by jbrooksuk** [comment]
Thank you for your input on Cachet 2.x. We are shifting our attention and resources to Cachet 3.x and will no longer be supporting the 2.x version. If your feedback or issue is relevant to the 3.x series, we encourage you to engage with the new branch.

For more information on the Cachet rebuild and our plans for 3.x, you can read the announcement [here](https://github.com/CachetHQ/Cachet/discussions/4342).

We appreciate your understanding and look forward to your contributions to the new version.
