### ISSUE TITLE
Impersonating other users during API update

### ISSUE THREAD

**Issue by maddprof** [CachetHQ/Cachet#3782]
We're working on integrating a Slack hook with Cachet in such a way we can push incidents directly from our channels. 

The issue is all the updates get posted as a singular user - where we'd like to be able to track which user is posting the incidents + updates. 

Short of building a dictionary of users and their API keys, is there any way to impersonate another person when posting an update?

**Comment by jbrooksuk** [comment]
There is not! Unfortunately, it'll be a case of building the dictionary. This isn't really too different to how other APIs work.

**Comment by maddprof** [comment]
No problem. Was hoping there was a in progress addition to the API for posting incident updates as a specific person ("post as").
