### ISSUE TITLE
Dates are not translated

### ISSUE THREAD

**Issue by yuters** [cachethq/Cachet#379]
Carbon offers the method ->formatLocalized()... but it implies installing the supported locales on the linux box `locale-gen fr_FR fr_FR.utf8`, and setup the php setlocale() function.

Maybe the package below would be easier and a better solution:
https://github.com/jenssegers/laravel-date

What do you think?

**Comment by joecohens** [comment]
Yeah we are using that package, for now we only have the status page dates translated but I would be cool to implement it on all the other places with a presenter.

**Comment by yuters** [comment]
Ha sorry I didn't realize, I was looking at the HomeController which is using Carbon for the [start date in the status page](https://github.com/cachethq/Cachet/blob/master/src/Http/Controllers/HomeController.php#L53).

Maybe the date format could be in the dashboard settings? In french the 'S' in 'jS F Y' isn't recognized.

**Comment by joecohens** [comment]
No problem :), yeah that would be a very good idea can you send a PR?
