### ISSUE TITLE
Maintenances - updated as "finish" even when end point is in future

### ISSUE THREAD

**Issue by gcommit** [CachetHQ/Cachet#3793]
Hello,

as soon as you set an end point for your maintenace, it is not shown anymore, because cachet interpretes it as "finish". Could you change it, that it is shown until the end date is reached?

Best regards

**Comment by jbrooksuk** [comment]
Thank you for your input on Cachet 2.x. We are shifting our attention and resources to Cachet 3.x and will no longer be supporting the 2.x version. If your feedback or issue is relevant to the 3.x series, we encourage you to engage with the new branch.

For more information on the Cachet rebuild and our plans for 3.x, you can read the announcement [here](https://github.com/CachetHQ/Cachet/discussions/4342).

We appreciate your understanding and look forward to your contributions to the new version.
