### ISSUE TITLE
Metrics - Not in timezone

### ISSUE THREAD

**Issue by gcommit** [CachetHQ/Cachet#3794]
Hello,

when you set time zone to your location (CEST for example) metrics are still shown in UTC. Could you change this, so all parts take the time zone as configured?

Best regards

**Comment by joe-eklund** [comment]
I was able to get my metrics to work. I am not sure which of the following was the exact fix, but I believe it was a combination of some of the following:

1. I pulled in #3807 to my fork of Cachet.
1. I passed in  `- /etc/localtime:/etc/localtime:r` as a volume to my Postgres and Cachet containers. Make sure localtime on your host is set correctly. Check that by running `timedatectl`.
1. I also store the metrics in my local time zone. I was hoping that I could store them in UTC, but for some reason no matter what I did they would always display in UTC if I did this. The major downside for storing in local timezone is that if you change your timezone those metrics would need to be changed at the database level I believe. Or maybe some change in cachet would fix it too, Idk.

Everything is working as expected so far, but I will continue to monitor and make sure that my metrics are behaving as expected.

**Comment by si458** [comment]
i had the same issue with UK BST,
in the end i just gave up and just resorted to moment telling me if it was BST and if so add 1 hour to the timestamp, not ideal but does the trick
```
var mytimestamp = moment().tz('Europe/London').unix();
if(moment().tz('Europe/London').isDST()){
  mytimestamp = moment().tz('Europe/London').add(1,'hour').unix();
}
```

**Comment by zanechua** [comment]
Just want to leave more information here for people who stumble upon this.

It looks like Cachet is retrieving Metrics via the Metric Repository class and it'll use the associated repository class based on what database you use. They pull the time from the database instead of passing the time through to the query.

You can see so in https://github.com/CachetHQ/Cachet/blob/2.4/app/Repositories/Metric/PgSqlRepository.php

For those who are using docker to spin up their cachet instance. My suggestion is to use an `docker-compose.override.yml` file.  You have to do this BEFORE your docker containers are created. If your docker containers are created without the `TZ` environment set, you'll have to run `docker-compose build --no-cache` to make sure the postgres container spins up in the correct timezone.

```
version: "3"

services:
  postgres:
    environment:
      - TZ=Asia/Singapore
      - PGTZ=Asia/Singapore
    networks:
      - cachet
  cachet:
    ports:
      - 8000:8000
    environment:
      - TZ=Asia/Singapore
      - APP_TIMEZONE=Asia/Singapore
```


The fix in https://github.com/CachetHQ/Cachet/pull/3807 does hotfix the issue however I must say that it isn't the correct fix. It forces all the metric data to be stored in your current timezone, this will make the data harder to transform properly later on if you want to switch timezones. I'm not sure if we can modify the queries from `now()` to `now() at time zone {Config.get('app.timezone')}` and I wonder if that will work. The transformation shouldn't be done to the data and it should be done only when you're pulling the data which should be the metric repository.

**Comment by zanechua** [comment]
So I tried my own fix above and while I was close. I wasn't right. However I have found a fix for this.

Let's make some assumptions.

* Docker container running postgres is in UTC.
* Postgres is using UTC as the default timezone.
* All timestamps are stored in UTC
* Docker container running cachet is in UTC.
* You've made sure to set `APP_TIMEZONE` to your own timezone.

The `docker-compose.override.yml` file now looks like this:
```docker
version: "3"

services:
  postgres:
    networks:
      - cachet
  cachet:
    ports:
      - 8000:8000
    environment:
      - APP_TIMEZONE=Asia/Singapore
    networks:
      - cachet
```

Based on the existing code without the fix in #3807. 

We can make this modification to the `PgSqlRepository.php` file.

From:
```php
    public function getPointsSinceMinutes(Metric $metric, $minutes)
    {
        $queryType = $this->getQueryType($metric);
        $points = DB::select("SELECT to_char({$this->getMetricPointsTable()}.created_at, 'YYYY-MM-DD HH24:MI') AS key, {$queryType} ".
            "FROM {$this->getMetricsTable()} INNER JOIN {$this->getMetricPointsTable()} ON {$this->getMetricsTable()}.id = {$this->getMetricPointsTable()}.metric_id ".
            "WHERE {$this->getMetricsTable()}.id = :metricId ".
            "AND {$this->getMetricPointsTable()}.created_at >= (NOW() - INTERVAL '{$minutes}' MINUTE) ".
            "AND {$this->getMetricPointsTable()}.created_at <= NOW() ".
            "GROUP BY to_char({$this->getMetricPointsTable()}.created_at, 'YYYY-MM-DD HH24:MI') ".
            "ORDER BY to_char({$this->getMetricPointsTable()}.created_at, 'YYYY-MM-DD HH24:MI')", [
                'metricId' => $metric->id,
            ]);

        return $this->mapResults($metric, $points);
    }
```

To:
```php
    public function getPointsSinceMinutes(Metric $metric, $minutes)
    {
        $timezone = config('app.timezone');
        $queryType = $this->getQueryType($metric);
        $points = DB::select("SELECT to_char((({$this->getMetricPointsTable()}.created_at AT TIME ZONE 'UTC') AT TIME ZONE '{$timezone}'), 'YYYY-MM-DD HH24:MI') AS key, {$queryType} ".
            "FROM {$this->getMetricsTable()} INNER JOIN {$this->getMetricPointsTable()} ON {$this->getMetricsTable()}.id = {$this->getMetricPointsTable()}.metric_id ".
            "WHERE {$this->getMetricsTable()}.id = :metricId ".
            "AND {$this->getMetricPointsTable()}.created_at >= (NOW() - INTERVAL '{$minutes}' MINUTE) ".
            "AND {$this->getMetricPointsTable()}.created_at <= NOW() ".
            "GROUP BY to_char((({$this->getMetricPointsTable()}.created_at AT TIME ZONE 'UTC') AT TIME ZONE '{$timezone}'), 'YYYY-MM-DD HH24:MI') ".
            "ORDER BY to_char((({$this->getMetricPointsTable()}.created_at AT TIME ZONE 'UTC') AT TIME ZONE '{$timezone}'), 'YYYY-MM-DD HH24:MI')", [
                'metricId' => $metric->id,
            ]);

        return $this->mapResults($metric, $points);
    }
```


That should fix it. That fix has to be applied to the other functions too and across the other repository classes. I am actually wondering why this isn't using Eloquent to retrieve the metric, perhaps it's legacy code and hasn't changed much?

If we want to ensure that `NOW()` returns us UTC timing, we can use `timezone('utc', NOW())`

So a more foolproof example would be:

```php
    public function getPointsSinceMinutes(Metric $metric, $minutes)
    {
        $timezone = config('app.timezone');
        $queryType = $this->getQueryType($metric);
        $points = DB::select("SELECT to_char((({$this->getMetricPointsTable()}.created_at AT TIME ZONE 'UTC') AT TIME ZONE '{$timezone}'), 'YYYY-MM-DD HH24:MI') AS key, {$queryType} ".
            "FROM {$this->getMetricsTable()} INNER JOIN {$this->getMetricPointsTable()} ON {$this->getMetricsTable()}.id = {$this->getMetricPointsTable()}.metric_id ".
            "WHERE {$this->getMetricsTable()}.id = :metricId ".
            "AND {$this->getMetricPointsTable()}.created_at >= (timezone('utc', NOW() - INTERVAL '{$minutes}' MINUTE) ".
            "AND {$this->getMetricPointsTable()}.created_at <= timezone('utc', NOW() ".
            "GROUP BY to_char((({$this->getMetricPointsTable()}.created_at AT TIME ZONE 'UTC') AT TIME ZONE '{$timezone}'), 'YYYY-MM-DD HH24:MI') ".
            "ORDER BY to_char((({$this->getMetricPointsTable()}.created_at AT TIME ZONE 'UTC') AT TIME ZONE '{$timezone}'), 'YYYY-MM-DD HH24:MI')", [
                'metricId' => $metric->id,
            ]);

        return $this->mapResults($metric, $points);
    }
```


All in all, I'm not even sure if this fix should be done this way or the existing repository classes should just be converted to use Eloquent. If the repo owners can chime in on their preference, that'll be great.

**Comment by NiTRoeSE** [comment]
@si458 
> i have the same issue with UK BST,
> in the end i just gave up and just resorted to moment telling me if it was BST and if so add 1 hour to the timestamp, not ideal but does the trick
> 
> ```
> var mytimestamp = moment().tz('Europe/London').unix();
> if(moment().tz('Europe/London').isDST()){
>   mytimestamp = moment().tz('Europe/London').add(1,'hour').unix();
> }
> ```

Hi, can you please give a bit more information about where i have to change this. ?
I aso tryed a lot f things to get metrics fixed but non of them worked, so i would try your workaround.

Thanks in advanced!

**Comment by joe-eklund** [comment]
I ran into this issue again, and honestly just gave up on getting my metrics to work. I had gotten them working for a little bit, but daylight savings time broke it again and I didn't have the time to further investigate. I may look at reenabling them at a later time, but for now it just wasn't worth it.

**Comment by PikuZheng** [comment]
Was facing the same issue. Adding tz to docker env didn't work for me.

**Comment by 0981083723** [comment]
PikuZheng ***@***.***> 於 2022年11月4日 週五 晚上9:53寫道：

**Comment by jbrooksuk** [comment]
Thank you for your input on Cachet 2.x. We are shifting our attention and resources to Cachet 3.x and will no longer be supporting the 2.x version. If your feedback or issue is relevant to the 3.x series, we encourage you to engage with the new branch.

For more information on the Cachet rebuild and our plans for 3.x, you can read the announcement [here](https://github.com/CachetHQ/Cachet/discussions/4342).

We appreciate your understanding and look forward to your contributions to the new version.
