### ISSUE TITLE
Metrics - can't change the way it is shown

### ISSUE THREAD

**Issue by gcommit** [CachetHQ/Cachet#3796]
Hello,

i created a metric. I set decimal values to 1 and the threshold between metric points to 5, default is 0. Why is it shown with 0.00 to 1.00 ? I would think the graphs would contain the values 1, 2, 3 etc, so no values after the "," - am i thinking wrong or what am i doing wrong? 

![Bildschirmfoto 2019-09-23 um 15 46 06](https://user-images.githubusercontent.com/18714033/65431146-48e49780-de19-11e9-980c-34ca1bf9e7e0.png)

Best regards!

**Comment by jbrooksuk** [comment]
Thank you for your input on Cachet 2.x. We are shifting our attention and resources to Cachet 3.x and will no longer be supporting the 2.x version. If your feedback or issue is relevant to the 3.x series, we encourage you to engage with the new branch.

For more information on the Cachet rebuild and our plans for 3.x, you can read the announcement [here](https://github.com/CachetHQ/Cachet/discussions/4342).

We appreciate your understanding and look forward to your contributions to the new version.
