### ISSUE TITLE
Metrics - time ranges shown completly wrong

### ISSUE THREAD

**Issue by gcommit** [CachetHQ/Cachet#3797]
Hello,

am i wrong or the behavior in the screenshot wrong? The metric for the range of 1 hour is showing 3 hours. 

I just added the metric and started sending data to it. 

![Bildschirmfoto 2019-09-23 um 15 51 46](https://user-images.githubusercontent.com/18714033/65431676-2737e000-de1a-11e9-9f94-8eb46a16ce4a.png)

Best regards!

**Comment by jbrooksuk** [comment]
Thank you for your input on Cachet 2.x. We are shifting our attention and resources to Cachet 3.x and will no longer be supporting the 2.x version. If your feedback or issue is relevant to the 3.x series, we encourage you to engage with the new branch.

For more information on the Cachet rebuild and our plans for 3.x, you can read the announcement [here](https://github.com/CachetHQ/Cachet/discussions/4342).

We appreciate your understanding and look forward to your contributions to the new version.
