### ISSUE TITLE
Support for RSS

### ISSUE THREAD

**Issue by sharninder** [CachetHQ/Cachet#3798]
Are there plans to support RSS as a mechanism to broadcast news in addition to email?

**Comment by jbrooksuk** [comment]
We'll be re-building RSS back into Cachet, but with a newer library :)

**Comment by sharninder** [comment]
oh well, so no option to have RSS right now with the current version. Just email notifications is a little limiting @jbrooksuk

**Comment by jbrooksuk** [comment]
2.3 has RSS support, but we've removed it in the current 2.4 branch. It will return!

**Comment by ph00lt0** [comment]
@jbrooksuk any update regarding this?
