### ISSUE TITLE
Feature: Integrate with Common Alerting Protocol (CAP)

### ISSUE THREAD

**Issue by mfvetter** [CachetHQ/Cachet#3799]
Hello,

I'm not sure if this system could handle Common Alerting Protocol (CAP) or if is it even possible to develop or integrate such protocol in Cachet? 
More about CAP: [https://www.fema.gov/common-alerting-protocol](url)

I'm pretty new to Cachet and I was thinking of the possibility to adapt Cachet for university campuses, businesses, etc to get alerts in case of some types of incidents such as natural disasters, active shooters, campus or buildings lock-downs, fire alarms, climate alerts, etc...

It would be really cool to have the possibility to integrate notification systems used in universities, government entities, companies, etc that use the CAP protocol to integrate with Cachet. One example of a such system is Rave Notification System: [https://www.ravemobilesafety.com](url)

I know that Rave have the option to use CAP to push public alerts to other systems and this protocol could be an easy way to perhaps integrate with Cachet?

As far as I understood, Cached focuses more on IT related services/systems/hardware, etc... But it would be nice to make it flexible for other types of alerts as mentioned above and get the alerts from external systems via CAP.

Sorry if I'm not in the correct place for a feature suggestion like this.

**Comment by jbrooksuk** [comment]
Thanks for the suggestion! I've not read this yet, but leave it with me :)

**Comment by jbrooksuk** [comment]
Thank you for your input on Cachet 2.x. We are shifting our attention and resources to Cachet 3.x and will no longer be supporting the 2.x version. If your feedback or issue is relevant to the 3.x series, we encourage you to engage with the new branch.

For more information on the Cachet rebuild and our plans for 3.x, you can read the announcement [here](https://github.com/CachetHQ/Cachet/discussions/4342).

We appreciate your understanding and look forward to your contributions to the new version.
