### ISSUE TITLE
Error 500 in Backend

### ISSUE THREAD

**Issue by thueske** [CachetHQ/Cachet#3813]
Hey,

backend throws error 500, because
https://github.com/CachetHQ/Cachet/blob/2.4/app/Integrations/Core/Feed.php#L31
redirects to an twitter account...

**Comment by jbrooksuk** [comment]
Sorry about this! I'll push an update to 2.4 now.

**Comment by jbrooksuk** [comment]
Wait, I'm unable to replicate this issue? The blog posts don't load which is what's expected.

**Comment by thueske** [comment]
Using 2.3 with redis enabled.

**Comment by thueske** [comment]
Is 2.4 stable for production usage?

**Comment by jbrooksuk** [comment]
Thank you for your input on Cachet 2.x. We are shifting our attention and resources to Cachet 3.x and will no longer be supporting the 2.x version. If your feedback or issue is relevant to the 3.x series, we encourage you to engage with the new branch.

For more information on the Cachet rebuild and our plans for 3.x, you can read the announcement [here](https://github.com/CachetHQ/Cachet/discussions/4342).

We appreciate your understanding and look forward to your contributions to the new version.
