### ISSUE TITLE
Integrate status from Google Suite

### ISSUE THREAD

**Issue by RustyIngles** [CachetHQ/Cachet#3814]
Is there anyway to integrate the status of G Suite from this page:

https://www.google.com/appsstatus#hl=en&v=status

We have cachet installed and working, which is working great but would love a way of integrating the status from the above URL for our Google Suite, rather than adding this in manually.

**Comment by jbrooksuk** [comment]
Monitoring of services isn't yet provided by Cachet. You'd need to setup something in the middle to monitor Google Suite and report back to your Cachet installation.
