### ISSUE TITLE
Mail Settings

### ISSUE THREAD

**Issue by 1stRaven** [CachetHQ/Cachet#3817]
Hi,

Been having this issue for a few days and I've run out of ideas and searches on how to fix this so hoping someone can help.

Fresh install of Ubuntu 18.04 LTS with a fresh install on ngix and cachet. The site loads and I can change the theme, add componets, groups, items on the settings page etc but I am unable to change anything on the mail settings. 

If I try via the mail page, it will accept the settings when I click save but the moment I click Test, it falls back to the Log driver. I have also attempted to change the settings in the .env to SMTP/Sendmail etc but while these are saved, they are not used by the site - even after reboots and cache clears. 

I have modified ownership of the bootstrap folder to www-data as well but that hasn't helped. This is the third install (I have tried with apache as well) but i'm now out of ideas. 

Anyone know what else I can try?

**Comment by jbrooksuk** [comment]
@GrahamCampbell any thoughts on this? I'd have thought that making the `bootstrap/cachet` folder writeable would be enough?

**Comment by lotodore** [comment]
I'm also having this issue, it seems that the values specified in the initial setup are used, but cannot be changed later in the dashboard.

**Comment by 1stRaven** [comment]
Still having this issue after several fresh installs, new machines, new databases. Ran out of ideas now...

**Comment by lingej** [comment]
Same here with current DEV Version.

`php artisan serve -vvv --host=0.0.0.0 --port=80`

```
php -v
PHP 7.3.11-1~deb10u1 (cli) (built: Oct 26 2019 14:14:18) ( NTS )
```

**Comment by MatthieuNoirbusson** [comment]
+1

**Comment by lhirlimann** [comment]
Did you try changing the setttings in .env at the root of your install of cachet ?

**Comment by jbrooksuk** [comment]
Thank you for your input on Cachet 2.x. We are shifting our attention and resources to Cachet 3.x and will no longer be supporting the 2.x version. If your feedback or issue is relevant to the 3.x series, we encourage you to engage with the new branch.

For more information on the Cachet rebuild and our plans for 3.x, you can read the announcement [here](https://github.com/CachetHQ/Cachet/discussions/4342).

We appreciate your understanding and look forward to your contributions to the new version.
