### ISSUE TITLE
ImageServiceProvider not found

### ISSUE THREAD

**Issue by Perflyst** [CachetHQ/Cachet#3818]
Today I tried upgrading to latest 2.4 commit ( 212d8076535894e41876bc472964afe9375c46e6 )but I am unable to start the app:update command:

```
$ php artisan app:update

In Application.php line 662:
  Class 'Intervention\Image\ImageServiceProvider' not found  
```

**Comment by jbrooksuk** [comment]
You'll need to run `composer install` first.

**Comment by Perflyst** [comment]
As described here https://docs.cachethq.io/docs/updating-cachet  `composer install --no-dev -o --no-scripts` was run
