### ISSUE TITLE
An error has occured and this resourse cannot be displayed 

### ISSUE THREAD

**Issue by SpeedyCraftah** [CachetHQ/Cachet#3819]
I just installed Cachet, filled the fields out and then hit "Complete Installation" but I got "An error has occured and this recourse cannot be displayed"
I am clueless on how I can get error logs. Thanks

**Comment by jbrooksuk** [comment]
Thank you for your input on Cachet 2.x. We are shifting our attention and resources to Cachet 3.x and will no longer be supporting the 2.x version. If your feedback or issue is relevant to the 3.x series, we encourage you to engage with the new branch.

For more information on the Cachet rebuild and our plans for 3.x, you can read the announcement [here](https://github.com/CachetHQ/Cachet/discussions/4342).

We appreciate your understanding and look forward to your contributions to the new version.
