### ISSUE TITLE
[Feature Request] List of things

### ISSUE THREAD

**Issue by MartinHotmann** [CachetHQ/Cachet#3824]
Hi guys I installed Cachet some monthes ago and would love to give some feedback what would make Cachet more valuable for me.

1. One-Click Backup (at least the DB)
2. One-Click Update (after backing up the DB)
3. System-Info site (something like at freescout, which is also a laravel Application)
4. more customizable by default (like editing the Footer Credits) most people just hide them but want to edit them instead
5. custom templates which will presist after an update

Think these 5 points will make the App more up to date and more usable for the most :)

**Comment by Kopertje** [comment]
+1

**Comment by jbrooksuk** [comment]
Thank you for your input on Cachet 2.x. We are shifting our attention and resources to Cachet 3.x and will no longer be supporting the 2.x version. If your feedback or issue is relevant to the 3.x series, we encourage you to engage with the new branch.

For more information on the Cachet rebuild and our plans for 3.x, you can read the announcement [here](https://github.com/CachetHQ/Cachet/discussions/4342).

We appreciate your understanding and look forward to your contributions to the new version.
