### ISSUE TITLE
[Bug] Cachet v2.3.x is not PHP >=7.2 compatible

### ISSUE THREAD

**Issue by MartinH0** [CachetHQ/Cachet#3825]
I'm currently on Cachet v2.3.18 and I run it on PHP 7.1.32 but as soon as I change it to PHP 7.2 or 7.3 it does not work and gives me a Error 500.

I set Cachet up clean just for this test.
Also I could not get Cachet 2.4 to work, no matter what I tried. I have done it like it is advised in the Docu/Wiki ( https://docs.cachethq.io/docs/installing-cachet )

v2.4 is not working for me and 2.3 just on PHP 7.1

Anyone who can help here? Would love to at least upgrade to PHP 7.3 to be able to delete it from my server as no other service is using such an 'old' PHP Version

**Comment by jbrooksuk** [comment]
This isn’t a bug. Cachet 2.3 is pretty old.
