### ISSUE TITLE
Composer: Base table or view not found

### ISSUE THREAD

**Issue by dspangenberg** [cachethq/Cachet#383]
Composer breaks while optimizing autoload files:

<code>
{"error":{"type":"Illuminate\\Database\\QueryException","message":"SQLSTATE[42S02]: Base table or view not found: 1146 Table 'cachet.settings' doesn't exist (SQL: select * from `settings` where `name` = app_domain limit 1)","file":"\/home\/dspangenberg\/Sites\/cachet.app\/html\/vendor\/laravel\/framework\/src\/Illuminate\/Database\/Connection.php","line":625}}{"error":{"type":"Illuminate\\Database\\QueryException","message":"SQLSTATE[42S02]: Base table or view not found: 1146 Table 'cachet.settings' doesn't exist (SQL: select * from `settings` where `name` = app_domain limit 1)","file":"\/home\/dspangenberg\/Sites\/cachet.app\/html\/vendor\/laravel\/framework\/src\/Illuminate\/Database\/Connection.php","line":625}}
</code>

**Comment by jbrooksuk** [comment]
Have you ran `php artisan migrate`?

**Comment by dspangenberg** [comment]
I know, but I can't run php artisan migrate:

<code>
{"error":{"type":"Illuminate\\Database\\QueryException","message":"SQLSTATE[42S02]: Base table or view not found: 1146 Table 'cachet.settings' doesn't exist (SQL: select * from `settings` where `name` = app_domain limit 1)","file":"\/home\/dspangenberg\/Sites\/cachet.app\/html\/vendor\/laravel\/framework\/src\/Illuminate\/Database\/Connection.php","line":625}}
</code>

**Comment by jbrooksuk** [comment]
Do you have any tables currently? Try this:

- `php artisan migrate:reset`
- `php artisan migrate`

You'll lose any data if you currently have some.

**Comment by dspangenberg** [comment]
Does not work. I can not run any artisan command without optimizing autoload and optimizing autoload doesn't work without existing tables.

**Comment by jbrooksuk** [comment]
What's your environment value for `ENV`?

**Comment by dspangenberg** [comment]
It's not an environment issue. I have not set env, so it uses .env.local.php and the database settings are okay. And yes I've tried php artisan migrate --env=local, too.

With wrong database settings the error is:
<code>
{"error":{"type":"PDOException","message":"SQLSTATE[HY000] [1049] Unknown database 'cachset'","file":"\/home\/dspangenberg\/Sites\/cachet.app\/html\/vendor\/laravel\/framework\/src\/Illuminate\/Database\/Connectors\/Connector.php","line":47}}{"error":{"type":"PDOException","message":"SQLSTATE[HY000] [1049] Unknown database 'cachset'","file":"\/home\/dspangenberg\/Sites\/cachet.app\/html\/vendor\/laravel\/framework\/src\/Illuminate\/Database\/Connectors\/Connector.php","line":47}}
</code>

**Comment by jbrooksuk** [comment]
Ok, one second.

**Comment by jbrooksuk** [comment]
Right, I know where the error is.

**Comment by jbrooksuk** [comment]
Pull from `master` and try again please @dspangenberg :)

**Comment by dspangenberg** [comment]
Thank you, now it works.

**Comment by jbrooksuk** [comment]
Glad to hear it :)

**Comment by ruuter** [comment]
I have same issue, running just `php artisan` results in:
`[Illuminate\Database\QueryException]                                                                                        
  SQLSTATE[42S02]: Base table or view not found: 1146 Table 'testing.settings' doesn't exist (SQL: select * from ``settings``)`
` [PDOException]                                                                              
  SQLSTATE[42S02]: Base table or view not found: 1146 Table 'testing.settings' doesn't exist`
I have removed all migration files and created new empty database, but nothing works.

**Comment by Alhiane** [comment]
I have the same problem and i didn't work with GitHub
