### ISSUE TITLE
Running php artisan app:install Throws error

### ISSUE THREAD

**Issue by altoweb** [CachetHQ/Cachet#3831]
When I attempt to run php artisan app:install I get this error. Any fixes? Running on Ubuntu 18.04 with Cachet v2.1.0 (I've also tried running this without root privileges.

root@friendevo:/var/www/Cachet# php artisan app:install
Publishing complete for tag []!
Nothing to migrate.
Clearing cache...
PHP Fatal error:  Uncaught ErrorException: count(): Parameter must be an array or an object that implements Countable in /var/www/Cachet/vendor/graham-campbell/exceptions/src/ExceptionIdentifier.php:51
Stack trace:
#0 [internal function]: Illuminate\Foundation\Bootstrap\HandleExceptions->handleError(2, 'count(): Parame...', '/var/www/Cachet...', 51, Array)
#1 /var/www/Cachet/vendor/graham-campbell/exceptions/src/ExceptionIdentifier.php(51): count(NULL)
#2 /var/www/Cachet/vendor/graham-campbell/exceptions/src/ExceptionHandlerTrait.php(51): GrahamCampbell\Exceptions\ExceptionIdentifier->identify(Object(ErrorException))
#3 /var/www/Cachet/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(79): GrahamCampbell\Exceptions\ExceptionHandler->report(Object(ErrorException))
#4 [internal function]: Illuminate\Foundation\Bootstrap\HandleExceptions->handleException(Object(ErrorException))
#5 {main}
  thrown in /var/www/Cachet/vendor/graham-campbell/exceptions/src/ExceptionIdentifier.php on line 51
PHP Fatal error:  Uncaught ErrorException: count(): Parameter must be an array or an object that implements Countable in /var/www/Cachet/vendor/graham-campbell/exceptions/src/ExceptionIdentifier.php:51
Stack trace:
#0 [internal function]: Illuminate\Foundation\Bootstrap\HandleExceptions->handleError(2, 'count(): Parame...', '/var/www/Cachet...', 51, Array)
#1 /var/www/Cachet/vendor/graham-campbell/exceptions/src/ExceptionIdentifier.php(51): count(NULL)
#2 /var/www/Cachet/vendor/graham-campbell/exceptions/src/ExceptionHandlerTrait.php(51): GrahamCampbell\Exceptions\ExceptionIdentifier->identify(Object(Symfony\Component\Debug\Exception\FatalErrorException))
#3 /var/www/Cachet/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(79): GrahamCampbell\Exceptions\ExceptionHandler->report(Object(Symfony\Component\Debug\Exception\FatalErrorException))
#4 /var/www/Cachet/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(118): Illuminate\Foundation\Bootstrap\HandleExceptions->h in /var/www/Cachet/vendor/graham-campbell/exceptions/src/ExceptionIdentifier.php on line 51

**Comment by Blizzard098** [comment]
This has happened to me too. Running PHP 7.3.

**Comment by Blizzard098** [comment]
I was able to fix my issue. What PHP version are you using? Also I'd recommend moving up to 2.4 from 2.1.

**Comment by kindlyfire** [comment]
Same issue here when trying to install tag `v2.3.18`, running PHP `7.3.11`.

```
root@status:/opt/status.naido.org# php artisan app:install
Clearing settings cache...
Settings cache cleared!
Backing up database...
Dumping database and uploading...

Successfully dumped mysql, compressed with gzip and store it to local at /opt/status.naido.org/database/backups/2019-10-31 18.53.25
Backup completed!
Application key [<redacted>] set successfully.
Configuration cache cleared!
Configuration cached successfully!
Route cache cleared!
Routes cached successfully!
Copied Directory [/vendor/roumen/feed/src/views] To [/resources/views/vendor/feed]
Publishing complete for tag []!
PHP Fatal error:  Uncaught ErrorException: count(): Parameter must be an array or an object that implements Countable in /opt/status.naido.org/vendor/graham-campbell/exceptions/src/ExceptionIdentifier.php:51
Stack trace:
#0 [internal function]: Illuminate\Foundation\Bootstrap\HandleExceptions->handleError(2, 'count(): Parame...', '/opt/status.nai...', 51, Array)
#1 /opt/status.naido.org/vendor/graham-campbell/exceptions/src/ExceptionIdentifier.php(51): count(NULL)
#2 /opt/status.naido.org/vendor/graham-campbell/exceptions/src/ExceptionHandlerTrait.php(47): GrahamCampbell\Exceptions\ExceptionIdentifier->identify(Object(ErrorException))
#3 /opt/status.naido.org/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(79): GrahamCampbell\Exceptions\ExceptionHandler->report(Object(ErrorException))
#4 [internal function]: Illuminate\Foundation\Bootstrap\HandleExceptions->handleException(Object(ErrorException))
#5 {main}
  thrown in /opt/status.naido.org/vendor/graham-campbell/exceptions/src/ExceptionIdentifier.php on line 51
PHP Fatal error:  Uncaught ErrorException: count(): Parameter must be an array or an object that implements Countable in /opt/status.naido.org/vendor/graham-campbell/exceptions/src/ExceptionIdentifier.php:51
Stack trace:
#0 [internal function]: Illuminate\Foundation\Bootstrap\HandleExceptions->handleError(2, 'count(): Parame...', '/opt/status.nai...', 51, Array)
#1 /opt/status.naido.org/vendor/graham-campbell/exceptions/src/ExceptionIdentifier.php(51): count(NULL)
#2 /opt/status.naido.org/vendor/graham-campbell/exceptions/src/ExceptionHandlerTrait.php(47): GrahamCampbell\Exceptions\ExceptionIdentifier->identify(Object(Symfony\Component\Debug\Exception\FatalErrorException))
#3 /opt/status.naido.org/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(79): GrahamCampbell\Exceptions\ExceptionHandler->report(Object(Symfony\Component\Debug\Exception\FatalErrorException))
#4 /opt/status.naido.org/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(118): Illuminate\Foundation in /opt/status.naido.org/vendor/graham-campbell/exceptions/src/ExceptionIdentifier.php on line 51
```

**Comment by Blizzard098** [comment]
@kindlyfire v2.3.18 isn't compatible with PHP 7.3. You need to use v2.4. When tagging/doing a checkout for 2.4, just do ``2.4`` not ``v2.4``
