### ISSUE TITLE
email notifications are added to mysql jobs table but never need sent.

### ISSUE THREAD

**Issue by eclay11** [CachetHQ/Cachet#3835]
Hello,  We have run into an issue with cachet.io v2.3.18, where if I create an incident and select the option to send to subscribers it put the notification in the jobs table in mysql but never seem to get sent.  This was working before but I'm not sure how to resolve/troubleshoot what is causing this to happen.  The .env file has the following setting for sending emails and mysql .

DB_DRIVER=mysql
DB_HOST=localhost
DB_DATABASE=cachetdb
DB_USERNAME=dbuser
DB_PASSWORD=dbuserpassword
DB_PORT=null
DB_PREFIX=null

MAIL_DRIVER=smtp
MAIL_HOST=mailgw.domain.com
MAIL_PORT=587
MAIL_USERNAME=null
MAIL_PASSWORD=null
MAIL_ADDRESS=no-reply@domain.com
MAIL_NAME="Status"
MAIL_ENCRYPTION=tls

When I create a new incident and select to notify subscribers, if I'm watching the mail servers maillog I do not see any entries added to even try to attempt to send the message.

Crontab has the following in it that I thought would send these messages.
* * * * * php /var/www/Cachet/artisan schedule:run >> /dev/null 2>&1

Not sure what else you might need to help me identify what's wrong.

**Comment by eclay11** [comment]
I just did a test after cleaning the jobs table.  
1. created a new incident enabled to notify subscribers.
2. ran the comand in the crontab manually.  
` php /path/to/artisan schedule:run`
Which returns the following
`Running scheduled command: '/usr/bin/php7.0' 'artisan' queue:work --sleep=3 --tries=3 > '/dev/null' 2>&1 &`

When I check the jobs queue items remain and are not removed.

However if I run the following command the items are sent and queue is purged.

`php artisan queue:work --daemon --delay=2 --sleep=1 --tries=3`

Not sure why or how to resolve this.  I would like to use the cron task but may have to try the supervisor setup found at https://docs.cachethq.io/docs/configuring-the-queue.

**Comment by jbrooksuk** [comment]
Thank you for your input on Cachet 2.x. We are shifting our attention and resources to Cachet 3.x and will no longer be supporting the 2.x version. If your feedback or issue is relevant to the 3.x series, we encourage you to engage with the new branch.

For more information on the Cachet rebuild and our plans for 3.x, you can read the announcement [here](https://github.com/CachetHQ/Cachet/discussions/4342).

We appreciate your understanding and look forward to your contributions to the new version.
