### ISSUE TITLE
Remove email to subscribers when component's tag is changed

### ISSUE THREAD

**Issue by MarkoSulamagi** [CachetHQ/Cachet#3837]
I think it's an odd feature that any time a component is updated (name, tags, etc) then an email goes to all subscribers. I would like to add tags to every component, but this isn't really possible if all customers get 10+ emails as a result.

Maybe there's a use case that I'm not seeing why such emails are sent to subscribers even on minor changes to the component? I understand the email when the component status changes, but not when I add an extra tag.

**Comment by jbrooksuk** [comment]
Thank you for your input on Cachet 2.x. We are shifting our attention and resources to Cachet 3.x and will no longer be supporting the 2.x version. If your feedback or issue is relevant to the 3.x series, we encourage you to engage with the new branch.

For more information on the Cachet rebuild and our plans for 3.x, you can read the announcement [here](https://github.com/CachetHQ/Cachet/discussions/4342).

We appreciate your understanding and look forward to your contributions to the new version.
