### ISSUE TITLE
Dashboard polish

### ISSUE THREAD

**Issue by jbrooksuk** [cachethq/Cachet#384]
The dashboard needs some polish on it :lipstick:

- [x] Increase font sizes for small text.
- [x] Layout forms in the same way, giving them a universal design.
- [ ] The active sidebar item is slightly taller, which when you jump between pages means the sidebar items move slightly. Some kind of `box-sizing: border-box` should fix this.
- [x] Forms need tidying up.
- [x] Show the `ion-social-markdown` icon in the bottom right of the supported textareas rather than having the `.help-block` element below it.
- [x] Inline component status needs cleaning up, making everything uniform and aligned correctly.
- [x] Use `.btn-group` when we have two or more buttons that are linked to something.
- [x] The sub-sidebar found on some pages only ever has a fixed height. If the page scrolls, the sub-sidebar height remains fixed at the top.
- [x] Consistency, buttons, layouts etc.
- [x] Font thickness. I think generally it's too thin all around.
- [x] Switch to Open Sans over Lato. I regret that choice.
- [ ] Make the user profile link more obvious.

**Comment by jbrooksuk** [comment]
@thomasHolman can I pick your brains one of the things on here, on Monday please?

**Comment by thomasHolman** [comment]
Sure 👍

**Comment by jbrooksuk** [comment]
Thanks :)
