### ISSUE TITLE
Metric threshold get applied when new data arrived, but get ignore after next minute

### ISSUE THREAD

**Issue by RankyLau** [CachetHQ/Cachet#3842]
We are using Cahcet v2.4.0 dev and using mysql for the database.
We are encountering a strange problem with metric threshold, we set the threshold at five minutes, which should makes the datapoint to be connected even if there is a five minute difference between them. However what we saw is that the right hand side of the graph applied the metric threshold, but at the next minute the threshold is ignored.
Here is a screenshot to show the problem:
![Screen Shot 2019-11-05 at 9 09 50 AM](https://user-images.githubusercontent.com/28520356/68230020-282d6700-ffad-11e9-9d02-68fea8aed372.png)
Notice the right hand side of the graph where the metric threshold is applied
And here is what happened next minute:
![Screen Shot 2019-11-05 at 9 18 58 AM](https://user-images.githubusercontent.com/28520356/68230318-a984f980-ffad-11e9-965c-0c406ba63568.png)
Here is the .env file that we are using:
APP_ENV=production
APP_DEBUG=false
APP_URL=localhost
APP_TIMEZONE=UTC
APP_KEY=base64:some_random_string
DEBUGBAR_ENABLED=false

DB_DRIVER=mysql
DB_HOST=localhost
DB_UNIX_SOCKET=null
DB_DATABASE=cachet
DB_USERNAME=cachet
DB_PASSWORD=cachet
DB_PORT=3306
DB_PREFIX=

CACHE_DRIVER=apc
SESSION_DRIVER=apc
QUEUE_DRIVER=null

CACHET_BEACON=true
CACHET_EMOJI=false
CACHET_AUTO_TWITTER=true

MAIL_DRIVER=smtp
MAIL_HOST=
MAIL_PORT=25
MAIL_USERNAME=null
MAIL_PASSWORD=null
MAIL_ADDRESS=
MAIL_NAME=null
MAIL_ENCRYPTION=null

REDIS_HOST=null
REDIS_DATABASE=null
REDIS_PORT=null

GITHUB_TOKEN=null

NEXMO_KEY=null
NEXMO_SECRET=null
NEXMO_SMS_FROM=Cachet

TRUSTED_PROXIES=

**Comment by jbrooksuk** [comment]
Thank you for your input on Cachet 2.x. We are shifting our attention and resources to Cachet 3.x and will no longer be supporting the 2.x version. If your feedback or issue is relevant to the 3.x series, we encourage you to engage with the new branch.

For more information on the Cachet rebuild and our plans for 3.x, you can read the announcement [here](https://github.com/CachetHQ/Cachet/discussions/4342).

We appreciate your understanding and look forward to your contributions to the new version.
