### ISSUE TITLE
Incident Update Notification Emails

### ISSUE THREAD

**Issue by hiraku-san** [CachetHQ/Cachet#3843]
Hi,

Sorry if this isn't the correct place to post this. The discussion page on the main website goes to a 404. 

Within my cachet setup new incidents that are set to notify subscribers work perfectly fine, sending the email as expected. However, if I update an incident not email is sent. I couldn't find anything in the documentation or on the frontend to change/manage this behaviour. 

A bit of a dig into the code i found the following:

`        'CachetHQ\Cachet\Bus\Events\Incident\IncidentWasReportedEvent' => [
            'CachetHQ\Cachet\Bus\Handlers\Events\Incident\SendIncidentEmailNotificationHandler',
        ],
        'CachetHQ\Cachet\Bus\Events\Incident\IncidentWasUpdatedEvent' => [
            //
        ],
`

It appears the IncidentWasUpdatedEvent handler has no action. should this be set to SendIncidentEmailNotificationHandler to function?

**Comment by julianze** [comment]
Which cachet version you are using?

**Comment by zulusbg** [comment]
i have same problem with 2.3.9
on  update on incident there is no email with update to subcribers

**Comment by jbrooksuk** [comment]
Thank you for your input on Cachet 2.x. We are shifting our attention and resources to Cachet 3.x and will no longer be supporting the 2.x version. If your feedback or issue is relevant to the 3.x series, we encourage you to engage with the new branch.

For more information on the Cachet rebuild and our plans for 3.x, you can read the announcement [here](https://github.com/CachetHQ/Cachet/discussions/4342).

We appreciate your understanding and look forward to your contributions to the new version.
