### ISSUE TITLE
[2 Feature requests] Subscriber whitelist and send schedules maintance to Slack channel

### ISSUE THREAD

**Issue by Kopertje** [CachetHQ/Cachet#3846]
Hi there,

My first feature request would be a whitelist for email domains that can sign up for the subscribe option. We use Cachet only for our internal landscape to give our users information about an incident. This is hosted externally so we always have a way to reach everyone. But because its reachable for the whole internet and dont want to use a IP whitelist we thought of a domein whitelist with out own email domains in it. Has someone reached this? Or can help me build it?

My other feature request would be able to have a checkbox or something that will allow me to send a message to a slack channel containing the scheduled maintenance.
Ill try to build this myself. But if someone already has this kind of option, that would be great :)

Kind Regards,
Kopertje

**Comment by jbrooksuk** [comment]
Thank you for your input on Cachet 2.x. We are shifting our attention and resources to Cachet 3.x and will no longer be supporting the 2.x version. If your feedback or issue is relevant to the 3.x series, we encourage you to engage with the new branch.

For more information on the Cachet rebuild and our plans for 3.x, you can read the announcement [here](https://github.com/CachetHQ/Cachet/discussions/4342).

We appreciate your understanding and look forward to your contributions to the new version.
