### ISSUE TITLE
2.4-dev not showing CSS

### ISSUE THREAD

**Issue by Larsthesheep** [CachetHQ/Cachet#3847]
I've recently installed Cachet on PHP 7.3. The status page itself is working when importing the dashboard.css as custom CSS. But on the dashboard all styling is gone. Network tools in the browser report a status 200 for the CSS and the file is accessible from the internet.

**Comment by jbrooksuk** [comment]
Thank you for your input on Cachet 2.x. We are shifting our attention and resources to Cachet 3.x and will no longer be supporting the 2.x version. If your feedback or issue is relevant to the 3.x series, we encourage you to engage with the new branch.

For more information on the Cachet rebuild and our plans for 3.x, you can read the announcement [here](https://github.com/CachetHQ/Cachet/discussions/4342).

We appreciate your understanding and look forward to your contributions to the new version.
