### ISSUE TITLE
Class 'Bugsnag\BugsnagLaravel\BugsnagServiceProvider' not found

### ISSUE THREAD

**Issue by Perflyst** [CachetHQ/Cachet#3849]
Tried to re-install my old buggy Cachet setup - stable tag is broken due to https://github.com/CachetHQ/Cachet/issues/3719 and with 2.4 I get this error on composer install

```
Generating optimized autoload files
Carbon 1 is deprecated, see how to migrate to Carbon 2.
https://carbon.nesbot.com/docs/#api-carbon-2
    You can run './vendor/bin/upgrade-carbon' to get help in updating carbon and other frameworks and libraries that depend on it.
> Illuminate\Foundation\ComposerScripts::postAutoloadDump
> @php artisan package:discover

In ProviderRepository.php line 208:
                                                                   
  Class 'Bugsnag\BugsnagLaravel\BugsnagServiceProvider' not found  
                                                                   

Script @php artisan package:discover handling the post-autoload-dump event returned with error code 1
```

**Comment by k-godwin** [comment]
app/config.php

Comment out Bugsnag on line 176
Comment out Debugbar on line 181

That will get things working-ish. That said, I'm not sure I'd suggest relying on it at this point.

**Comment by kienanstewart** [comment]
I worked around this by disabling the application debug in the environment settings

**Comment by jbrooksuk** [comment]
Thank you for your input on Cachet 2.x. We are shifting our attention and resources to Cachet 3.x and will no longer be supporting the 2.x version. If your feedback or issue is relevant to the 3.x series, we encourage you to engage with the new branch.

For more information on the Cachet rebuild and our plans for 3.x, you can read the announcement [here](https://github.com/CachetHQ/Cachet/discussions/4342).

We appreciate your understanding and look forward to your contributions to the new version.
