### ISSUE TITLE
setting a component-status in incident does not update component on frontpage

### ISSUE THREAD

**Issue by Finkregh** [cachethq/Cachet#385]
When i edit an incident and set the components' status, this staus is not shown in the component-list on the frontpage

**Comment by jbrooksuk** [comment]
I've edited a component from the edit component page, then gone back to the dashboard and it's showing me the right status.

Can you confirm your setup?

**Comment by Finkregh** [comment]
?, i've changed an incident via '/dashboard/incidents/3/edit', and there the  component in the form-group with id="component-status"

**Comment by jbrooksuk** [comment]
By "frontpage" do you mean the status page?

**Comment by HiTeN** [comment]
Same problem here, fresh install on heroku.

I tried to change the component status on the "Edit an incident" page, but whatever I do, it's still in "operational" status on the status page and the "Edit an incident" page.

**Comment by jbrooksuk** [comment]
Ok, knowing it's Heroku helps. I'll take a look.

**Comment by jbrooksuk** [comment]
I actually get the "Whoops, something went wrong" error on Heroku when I try to create a component.

**Comment by jbrooksuk** [comment]
I'm getting `invalid text representation: 7 ERROR: invalid input syntax for integer` as an error.

**Comment by jbrooksuk** [comment]
I hate PgSQL.

**Comment by Finkregh** [comment]
frontpage = status-page = /
and is use sqlite :)

**Comment by jbrooksuk** [comment]
Trying something now. One thing at a time :)

**Comment by jbrooksuk** [comment]
Right, fixed the component adder in PgSQL (Heroku).

**Comment by jbrooksuk** [comment]
Can you confirm that this is still an issue for you?

**Comment by Finkregh** [comment]
yep. @cadaa49599ec8746a8a4b312e89c7bf2b7db99ff

**Comment by jbrooksuk** [comment]
Ok, we'll investigate :)

**Comment by jbrooksuk** [comment]
Are you able to export the `components` table for me?

**Comment by Finkregh** [comment]
(you got mail)

**Comment by jbrooksuk** [comment]
Thanks @Finkregh I'll take a look now.

**Comment by jbrooksuk** [comment]
Everything looks fine in the DB.

Can you confirm these details:

1. OS
2. Database
3. Are you using the latest version of Cachet?
4. Did you chmod `./app/storage`?

**Comment by Finkregh** [comment]
OS: Debian 7.8 x86, Linux 3.2.0-4-686-pae
DB: sqlite
version: @6250aec581121730030685520470e58bd4622e12
file/folder rights: webserver-process can 'rwx'

The problem persists, i have an not-okay-icon in the history-list, but not on the component

**Comment by Finkregh** [comment]
fixed via #431 (running gulp, etc.)
