### ISSUE TITLE
Add "noindex" for archive pages and dashboard?

### ISSUE THREAD

**Issue by mmollick** [CachetHQ/Cachet#3855]
We just recently noticed that a bunch of the [past incident pages](https://www.google.com/search?q=site:status.neverbounce.com+inurl:start_date&filter=0&biw=1635&bih=1562) are being indexed by Google. These pages aren't particularly useful when indexed, many of them have no "incidents" at all. 

It would be beneficial to add a `noindex` meta tag on these past incident pages as well as adding a canonical URL to them to prevent them from being indexed. If you'd like, I can submit a PR with these changes.

**Comment by jbrooksuk** [comment]
Thank you for your input on Cachet 2.x. We are shifting our attention and resources to Cachet 3.x and will no longer be supporting the 2.x version. If your feedback or issue is relevant to the 3.x series, we encourage you to engage with the new branch.

For more information on the Cachet rebuild and our plans for 3.x, you can read the announcement [here](https://github.com/CachetHQ/Cachet/discussions/4342).

We appreciate your understanding and look forward to your contributions to the new version.
