### ISSUE TITLE
Emoji Markdown not working on demo site

### ISSUE THREAD

**Issue by gautamkrishnar** [CachetHQ/Cachet#3856]
Please see the screenshot below. Markdown emojis are not working:
https://demo.cachethq.io/
<img width="1429" alt="Screenshot 2019-11-16 at 5 53 01 PM" src="https://user-images.githubusercontent.com/8397274/68993106-34ad9b80-089a-11ea-9c14-d9fa25608e7d.png">

Platform: MacOS 10.15.1, Chrome Version 78.0.3904.97 (Official Build) (64-bit)

**Comment by jbrooksuk** [comment]
Thanks for letting us know! We'll get this fixed.

**Comment by portswigger-tim** [comment]
Did this ever get fixed? `:+1:`
