### ISSUE TITLE
show components' previous status in dashboard

### ISSUE THREAD

**Issue by Finkregh** [cachethq/Cachet#386]
currently i can only set a new status in the dashboard, not see what status a component has at the moment

**Comment by jbrooksuk** [comment]
When I first go into the dashboard, I can see this:

![screen shot 2015-01-15 at 11 45 05](https://cloud.githubusercontent.com/assets/246103/5756830/ff9973e2-9cab-11e4-946c-794036db0954.png)

The radio button is showing me the current status.

Is that not working for you?

**Comment by Finkregh** [comment]
Nope, none of the radio-buttons is active.

**Comment by jbrooksuk** [comment]
Are you able to go into the database, check out the `components` table and show me the rows?

**Comment by jbrooksuk** [comment]
Actually, are you using MySQL? And if so, what version and what PHP driver are you using?

**Comment by jbrooksuk** [comment]
And for a test, pull down `master` and see if it still happens.

**Comment by Finkregh** [comment]
sqlite/PHP 5.4.36-0+deb7u3
and it works now :+1:

**Comment by jbrooksuk** [comment]
Ok, that's interesting. I had to type hint it.
