### ISSUE TITLE
Mail driver reverting to log

### ISSUE THREAD

**Issue by 12nick12** [CachetHQ/Cachet#3862]
For some reason the Mail driver keeps reverting back to log. v2.4.

**Comment by nclonts** [comment]
I have this same issue. I have three different installations on three different operating systems showing the same results.

**Comment by nclonts** [comment]
I resolved my issue by installing an updated apcu.

sudo apt-get install php7.4-apcu -y
sudo php artisan app:update

**Comment by jbrooksuk** [comment]
Thank you for your input on Cachet 2.x. We are shifting our attention and resources to Cachet 3.x and will no longer be supporting the 2.x version. If your feedback or issue is relevant to the 3.x series, we encourage you to engage with the new branch.

For more information on the Cachet rebuild and our plans for 3.x, you can read the announcement [here](https://github.com/CachetHQ/Cachet/discussions/4342).

We appreciate your understanding and look forward to your contributions to the new version.
