### ISSUE TITLE
Trouble with queue for sending notification emails

### ISSUE THREAD

**Issue by joe-eklund** [CachetHQ/Cachet#3863]
Hello-

I am having an issue where I am not getting email notifications for incidents and maintenance. I am using Cachet 2.4 in docker, postgres, and redis.

I _can_ send test emails and subscription confirmation emails. I _cannot_ send notification emails for incidents or maintenance. I have inspected the database and see nothing in the notification, failed_jobs, or jobs table.

I suspect it has something to do with my queue, but I have read through https://docs.cachethq.io/docs/configuring-the-queue about 20 times and don't know what else to try.

Here is my docker-compose:

```
version: "3"

services:
 postgres:
   image: postgres:latest
   networks:
     - traefik_proxy
   volumes:
     - ./postgres:/var/lib/postgresql/data
     - /etc/localtime:/etc/localtime:ro
   environment:
     - POSTGRES_USER={username}
     - POSTGRES_PASSWORD={password}
   labels:
     - traefik.enable=false
   restart: always

 cachet:
   build:
     context: .
     args:
       - cachet_ver=2.4
   container_name: cachet
   ports:
     - 8080:8000
   environment:
     - CACHET_BEACON=false
     - CACHE_DRIVER=redis
     - SESSION_DRIVER=redis
     - QUEUE_DRIVER=database
     - REDIS_HOST=redis
     - REDIS_DATABASE=0
     - REDIS_PORT=6379
     - MAIL_DRIVER=smtp
     - MAIL_HOST={mail domain}
     - MAIL_PORT=587
     - MAIL_USERNAME={mail username}
     - MAIL_PASSWORD={mail password}
     - MAIL_ADDRESS={mail address}
     - MAIL_NAME={mail name}
     - MAIL_ENCRYPTION=tls
     - DB_DRIVER=pgsql
     - DB_HOST=postgres
     - DB_PORT=5432
     - DB_DATABASE=postgres
     - DB_USERNAME={username}
     - DB_PASSWORD={password}
     - DB_PREFIX=chq_
     - APP_KEY={app key}
     - APP_LOG=errorlog
     - APP_URL={url}
     - DEBUG=true
     - APP_DEBUG=true
     - TRUSTED_PROXIES=traefik
   labels:
     - traefik.backend=cachet
     - traefik.network=traefik_proxy
     - traefik.frontend.rule=Host:{domain}
     - traefik.port=8000
   volumes:
     - /etc/localtime:/etc/localtime:ro
   depends_on:
     - postgres
     - redis
   restart: always
   networks:
     - traefik_proxy

 redis:
   image: redis
   environment:
     - PGID=1000
     - PUID=1000
   volumes:
     - ./redis:/data
   labels:
     - traefik.enable=false
   restart: always
   networks:
     - traefik_proxy

networks:
 traefik_proxy:
   external: true
```

Here is the supervisord.conf file section that has to do with the queue:
```
[program:queue-worker]
command=php artisan queue:work --delay=1 --sleep=1 --timeout=1800 --tries=3
directory=/var/www/html/
redirect_stderr=true
autostart=true
autorestart=true
stdout_logfile_maxbytes=0
stderr_logfile_maxbytes=0
stdout_logfile=/dev/stdout
```

**Comment by JoshWeepie** [comment]
Same, although our incidents do send emails, but maintenance creations do not.

**Comment by joe-eklund** [comment]
I ended up fixing this by spinning up a docker container used for sending mail. My configuration ois now as follows:

docker-compose.yml
`postgres:
    image: postgres:12
    container_name: postgres
    networks:
      - traefik_proxy
    volumes:
      - ./postgres:/var/lib/postgresql/data
      - /etc/localtime:/etc/localtime:ro
    environment:
      - POSTGRES_USER={username}
      - POSTGRES_PASSWORD={password}
    labels:
      - traefik.enable=false
    restart: always
cachet:
    build:
      context: .
      args:
        - cachet_ver=2.4
    container_name: cachet
    environment:
      - CACHET_BEACON=false
      - CACHE_DRIVER=redis
      - SESSION_DRIVER=redis
      - QUEUE_DRIVER=redis
      - REDIS_HOST=redis
      - REDIS_DATABASE=0
      - REDIS_PORT=6379
      - MAIL_DRIVER=smtp
      - MAIL_HOST=smtp-relay
      - MAIL_PORT=25
      - MAIL_USERNAME=null
      - MAIL_PASSWORD=null
      - MAIL_ADDRESS=status@{domain.tld}
      - MAIL_NAME=My-Status
      - MAIL_ENCRYPTION=null
      - DB_DRIVER=pgsql
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_DATABASE=postgres
      - DB_USERNAME=postgres
      - DB_PASSWORD={password}
      - DB_PREFIX=chq_
      - APP_KEY={app-key}
      - APP_LOG=errorlog
      - APP_URL={app-url}
      - DEBUG=false
      - APP_DEBUG=false
      - TRUSTED_PROXIES=traefik
    depends_on:
      - postgres
      - redis
    volumes:
      - /etc/localtime:/etc/localtime:ro
    restart: always
    labels:
- traefik.backend=cachet
      - traefik.frontend.rule=Host:{url}
      - traefik.docker.network=traefik_proxy
      - traefik.port=8000
      - traefik.enable=true
    networks:
      - traefik_proxy

  redis:
    image: redis
    container_name: redis
    environment:
      - PGID=1000
      - PUID=1000
    volumes:
      - ./redis:/data
    labels:
      - traefik.enable=false
    restart: always
    networks:
      - traefik_proxy
  smtp:
    image: namshi/smtp
    container_name: smtp-relay
    restart: always
    labels:
      - traefik.enable=false
    networks:
      - traefik_proxy
`

Particularly the important part was changing the queue driver over to redis, adding an additional docker container that houses an smtp server, and then setting up cachet to talk to it through environment variables.

I can now send emails when I open incidents, do maintenance, verify subscriptions, etc.

I have some other bugs that I have noticed, but those can be in separate tickets.
