### ISSUE TITLE
[Bug] Incident Sticky doesn't respect Incident Visibility settings

### ISSUE THREAD

**Issue by bhillebrand-enee** [CachetHQ/Cachet#3864]
**Steps to reproduce:** 
1. Create a Component that is visible to logged in users only.
2. Create a Stickied incident with "Logged in Users Only" visibility set.
3. The Incident will be visible to all users, regardless of whether they are logged in or not.

**Expected Behavior:**
- In reality, an incident sticky should respect the visibility setting and only display to logged in users.

Running 2.4 Dev

**Comment by jbrooksuk** [comment]
Thank you for your input on Cachet 2.x. We are shifting our attention and resources to Cachet 3.x and will no longer be supporting the 2.x version. If your feedback or issue is relevant to the 3.x series, we encourage you to engage with the new branch.

For more information on the Cachet rebuild and our plans for 3.x, you can read the announcement [here](https://github.com/CachetHQ/Cachet/discussions/4342).

We appreciate your understanding and look forward to your contributions to the new version.
