### ISSUE TITLE
[Bug] Global Incident Status doesn't respect Incident visibility.

### ISSUE THREAD

**Issue by bhillebrand-enee** [CachetHQ/Cachet#3865]
**Steps to Produce:** 
1. Create a "logged-in users only" incident.
2. Refresh Dashboard as a logged-out user.
3. The "Some systems are experiencing issues" message will still appear even if the incident and selected component are both hidden.

**Expected behavior:**
1. "Logged-in users only" visibility of the incident should result in "Some systems are experiencing issues" not being displayed to non-logged in users.

**Comment by jbrooksuk** [comment]
Thank you for your input on Cachet 2.x. We are shifting our attention and resources to Cachet 3.x and will no longer be supporting the 2.x version. If your feedback or issue is relevant to the 3.x series, we encourage you to engage with the new branch.

For more information on the Cachet rebuild and our plans for 3.x, you can read the announcement [here](https://github.com/CachetHQ/Cachet/discussions/4342).

We appreciate your understanding and look forward to your contributions to the new version.
