### ISSUE TITLE
allow usage of multiple components per incident

### ISSUE THREAD

**Issue by Finkregh** [cachethq/Cachet#387]
I'd like to choose multiple components for an incident.

e.g. "network-issues" for the components "Desktops" and "Servers"

**Comment by jbrooksuk** [comment]
This will be coming in V2, when we will start to make use of the component tags.

**Comment by jbrooksuk** [comment]
I've had to rewrite the tags implementation before this can even be done.

**Comment by anarcat** [comment]
+1

**Comment by f0o** [comment]
:+1:

**Comment by f0o** [comment]
@jbrooksuk speaking of tags, perhaps make it possible to create incident on tags as well? *puppy-eyes* ;)

**Comment by jbrooksuk** [comment]
;)

**Comment by jbrooksuk** [comment]
Merged into https://github.com/cachethq/Cachet/issues/1176
