### ISSUE TITLE
Maintenance notification not working

### ISSUE THREAD

**Issue by pmkakaci** [CachetHQ/Cachet#3871]
Hello everyone,
First of all, thanks a lot for all work done on Cachet :).
I have some issues when i try to use maintenance planed and notification. We do not receive any mails when we try to create a planed maintenance. Is it normal ? 
Second question : are there any possibilities to have components directly linked to any planed maintenance ? 
Thanks in advance
Kind regards

**Comment by lingej** [comment]
@pmkakaci what kind of QUEUE_DRIVER do you use?

Please check .env file

**Comment by pmkakaci** [comment]
Hello, 
I didn't initiate this one : 

APP_ENV=production
APP_DEBUG=false
APP_URL=http://localhost
APP_TIMEZONE=UTC
APP_KEY=xxxxxxxxxx
DEBUGBAR_ENABLED=false

DB_DRIVER=mysql
DB_HOST=localhost
DB_UNIX_SOCKET=null
DB_DATABASE=cachetdb
DB_USERNAME=xxxxxxxx
DB_PASSWORD=xxxxxxxx
DB_PORT=null
DB_PREFIX=null

CACHE_DRIVER=file
SESSION_DRIVER=file
QUEUE_DRIVER=null

CACHET_BEACON=true
CACHET_EMOJI=false
CACHET_AUTO_TWITTER=true

MAIL_DRIVER=smtp
MAIL_HOST=smtp.xxxx.xxx
MAIL_PORT=25
MAIL_USERNAME=null
MAIL_PASSWORD=null
MAIL_ADDRESS=xxxx@xxxx.com
MAIL_NAME=AppStatus
MAIL_ENCRYPTION=null

REDIS_HOST=null
REDIS_DATABASE=null
REDIS_PORT=null

GITHUB_TOKEN=null

NEXMO_KEY=null
NEXMO_SECRET=null
NEXMO_SMS_FROM=Cachet

TRUSTED_PROXIES=

Is there anything in particular using the queue ?

**Comment by sadortun** [comment]
@pmkakaci did you solve your issue ?

**Comment by pmkakaci** [comment]
Hello, I didn't solve it for the moment :(

**Comment by pmkakaci** [comment]
> @pmkakaci did you solve your issue ?

**Comment by jbrooksuk** [comment]
Thank you for your input on Cachet 2.x. We are shifting our attention and resources to Cachet 3.x and will no longer be supporting the 2.x version. If your feedback or issue is relevant to the 3.x series, we encourage you to engage with the new branch.

For more information on the Cachet rebuild and our plans for 3.x, you can read the announcement [here](https://github.com/CachetHQ/Cachet/discussions/4342).

We appreciate your understanding and look forward to your contributions to the new version.
