### ISSUE TITLE
Disable debugbar when running in Docker

### ISSUE THREAD

**Issue by garygoodger** [CachetHQ/Cachet#3872]
Hello,

I've installed CachetHQ via docker however it has a debugbar at the bottom which I cannot work out how to remove? I have debug set to false etc but nothing seems to get rid of it, any suggestions?

Kind Regards,

**Comment by garygoodger** [comment]
In typical fashion, I've figured it out just after posting. For anyone wondering, add the below to your docker-compose

DEBUGBAR_ENABLED=false

Regards,

**Comment by joe-eklund** [comment]
I fixed this by adding the following to my docker compose:

 APP_DEBUG=false

I guess it accomplished the same thing.

**Comment by stamepicmorg** [comment]
> APP_DEBUG=false
yep
https://docs.cachethq.io/docs/installing-cachet

**Comment by jbrooksuk** [comment]
Thank you for your input on Cachet 2.x. We are shifting our attention and resources to Cachet 3.x and will no longer be supporting the 2.x version. If your feedback or issue is relevant to the 3.x series, we encourage you to engage with the new branch.

For more information on the Cachet rebuild and our plans for 3.x, you can read the announcement [here](https://github.com/CachetHQ/Cachet/discussions/4342).

We appreciate your understanding and look forward to your contributions to the new version.
