### ISSUE TITLE
Maintenances doesn't send mail

### ISSUE THREAD

**Issue by gcommit** [CachetHQ/Cachet#3882]
Hi, 

i am using the 2.4 Version. When i create a Maintenance, the subscribers are not getting an email. 
Even though, how should they subscribe? I can just subscribe to components but i can not pick a component in the maintenance creation

How to fix? 

Best regards

**Comment by Wouter0100** [comment]
I'm also experencing this in 2.4. It did work in an previous version.

**Comment by JoshWeepie** [comment]
We experience the same thing, also running 2.4

**Comment by Wouter0100** [comment]
Sorry, I was mistaken. It works on our side, although they arrive in the spam because they were send from the wrong name and e-mail address.

The issue was that we downgraded from an newer version, where the `.env` changed a bit. In 2.4 the variables are `MAIL_NAME` and `MAIL_ADDRESS` while in a later version they are changed to `MAIL_FROM_NAME` and `MAIL_FROM_ADDRESS`.

**Comment by gcommit** [comment]
Soooooo, any updates here? Welcome to 2021!

**Comment by pavog** [comment]
I think there was a feature planned that would allow you to create scheduled maintenance only for specific components, like you can do with incidents. But this feature was never implemented.

See my comments on the similar issue #4242

**Comment by jerbob92** [comment]
Cachet can get in a confused state where it thinks there is still active maintenance in progress. In that case it won't send out notifications if you have the setting `Suppress notifications when incident occurs during maintenance period?` enabled. I have changed the `inProgress` check to only include maintenance in the IN_PROGRESS state.

**Comment by jbrooksuk** [comment]
Thank you for your input on Cachet 2.x. We are shifting our attention and resources to Cachet 3.x and will no longer be supporting the 2.x version. If your feedback or issue is relevant to the 3.x series, we encourage you to engage with the new branch.

For more information on the Cachet rebuild and our plans for 3.x, you can read the announcement [here](https://github.com/CachetHQ/Cachet/discussions/4342).

We appreciate your understanding and look forward to your contributions to the new version.
