### ISSUE TITLE
Hosting service?

### ISSUE THREAD

**Issue by Ace2213** [CachetHQ/Cachet#3883]
It wouldn't make sense to install a status page on the same server(s) as my services, since the status page needs to remain online even when they aren't.

Do you, like many status page providers, offer a hosting service?

If not, is it simple/static enough to use something free like Github Pages?

**Comment by jbrooksuk** [comment]
We don't at this time, sorry!

You can host on a Digitalocean server for as little as $5 though.

**Comment by Ace2213** [comment]
I didn't ask about Digital ocean. I asked about Github Pages and free hosts.

Did you even read my post?

**Comment by jbrooksuk** [comment]
GitHub Page is for static websites, which Cachet is not. I offered a solution to your question 👍

**Comment by Ace2213** [comment]
Which is why I specifically asked if Cachet is static. You'd know that if you had read my post and didn't hit me with the canned response that you use on every similar post.

It's really not hard to have that little bit of respect for people.

**Comment by Ace2213** [comment]
I'm not even going to comment on the pathetic dick riding behavior of @amondnet
