### ISSUE TITLE
Old php versions/extensions

### ISSUE THREAD

**Issue by LucaTheHacker** [CachetHQ/Cachet#3884]
Cachet in prerequisites says that it's needed php 5.x to work properly, at now I've got 2 servers, one with php7.4.x and one with php7.3.12, both doesn't support mcrypt, cause mcrypt extensions load at max on php 7.3.0.

It's not the time in last month of 2019 to upgrade it and maybe leave php 5 alone?

**Comment by jbrooksuk** [comment]
Thank you for your input on Cachet 2.x. We are shifting our attention and resources to Cachet 3.x and will no longer be supporting the 2.x version. If your feedback or issue is relevant to the 3.x series, we encourage you to engage with the new branch.

For more information on the Cachet rebuild and our plans for 3.x, you can read the announcement [here](https://github.com/CachetHQ/Cachet/discussions/4342).

We appreciate your understanding and look forward to your contributions to the new version.
