### ISSUE TITLE
Verified subscriber

### ISSUE THREAD

**Issue by rdmrm4g00** [CachetHQ/Cachet#3888]
When attempting to add a distribution list in office 365 I cant verify the email address of the distribution list- can I disable verified for an email address as this is a pain?

Thanks

**Comment by haydenjames** [comment]
curious about this as well. Would like to be able to manually add user because the verify email sent by cachet has broken link.

thanks

**Comment by jbrooksuk** [comment]
Thank you for your input on Cachet 2.x. We are shifting our attention and resources to Cachet 3.x and will no longer be supporting the 2.x version. If your feedback or issue is relevant to the 3.x series, we encourage you to engage with the new branch.

For more information on the Cachet rebuild and our plans for 3.x, you can read the announcement [here](https://github.com/CachetHQ/Cachet/discussions/4342).

We appreciate your understanding and look forward to your contributions to the new version.
