### ISSUE TITLE
HTML Content Used In Incidents Message

### ISSUE THREAD

**Issue by arkhalid1986** [CachetHQ/Cachet#3893]
Hello,

I need to know how to use html contents like <b>, </br> <p> in Message Area i find only one thing that how to make bold fonts **Name** will become bold black in user-end. Also i need to know how to use color html code in Message Area. Please review below snapshot link for better understanding.

https://ibb.co/tC4MLwt

Let me know please i am facing this issue.

**Comment by gustavobim** [comment]
The Message Area supports markdown to format the text. 
You can check more about it [here](https://www.markdownguide.org/getting-started/).

**Comment by psbmiller** [comment]
I can't get Markdown tables to work.  Does the message area only support basic syntax?  The documentation seems to be very lacking in this regard.

**Comment by jbrooksuk** [comment]
Thank you for your input on Cachet 2.x. We are shifting our attention and resources to Cachet 3.x and will no longer be supporting the 2.x version. If your feedback or issue is relevant to the 3.x series, we encourage you to engage with the new branch.

For more information on the Cachet rebuild and our plans for 3.x, you can read the announcement [here](https://github.com/CachetHQ/Cachet/discussions/4342).

We appreciate your understanding and look forward to your contributions to the new version.
