### ISSUE TITLE
Issues adding homestead mail - getting 500 error

### ISSUE THREAD

**Issue by djcoleman-dino** [CachetHQ/Cachet#3894]
After installation, was able to edit dashboard, and play around. After changing .env to Mailhog configs, I received a 500 error and haven't been able to get out of it. Version 2.3.9

## Error 
Error 500
Houston, We Have A Problem.
Internal Server Error
What does this mean?
Something went wrong on our servers while we were processing your request. An error has occurred and this resource cannot be displayed. This occurrence has been logged, and a highly trained team of monkeys has been dispatched to deal with your problem. We're really sorry about this, and will work hard to get this resolved as soon as possible.

This error can be identified by eb182a---. You might want to take a note of this code.

## .env file 
APP_ENV=production
APP_DEBUG=false
APP_URL=http://localhost
APP_KEY=key

DB_DRIVER=mysql
DB_HOST=localhost
DB_DATABASE=database
DB_USERNAME=homestead
DB_PASSWORD=secret
DB_PORT=null
DB_PREFIX=null

CACHE_DRIVER=apc
SESSION_DRIVER=apc
QUEUE_DRIVER=sync
CACHET_EMOJI=false
CACHET_BEACON=true

MAIL_DRIVER=smtp
MAIL_HOST=localhost
MAIL_PORT=8025
MAIL_USERNAME=null
MAIL_PASSWORD=null
MAIL_ADDRESS=address@address.com
MAIL_NAME="name"
MAIL_ENCRYPTION=null

REDIS_HOST=null
REDIS_DATABASE=null
REDIS_PORT=null

GITHUB_TOKEN=null

NEXMO_KEY=null
NEXMO_SECRET=null
NEXMO_SMS_FROM=Cachet

## Log File 
[2019-12-15 00:00:00] production.ERROR: ErrorException: Declaration of Jenssege$
Stack trace:
#0 /home/vagrant/code/public/Cachet/vendor/jenssegers/date/src/Date.php(10): Il$
#1 /home/vagrant/code/public/Cachet/vendor/composer/ClassLoader.php(444): inclu$
#2 /home/vagrant/code/public/Cachet/vendor/composer/ClassLoader.php(322): Compo$
#3 [internal function]: Composer\Autoload\ClassLoader->loadClass('Jenssegers\\D$
#4 /home/vagrant/code/public/Cachet/vendor/jenssegers/date/src/DateServiceProvi$
#5 /home/vagrant/code/public/Cachet/vendor/jenssegers/date/src/DateServiceProvi$
#6 [internal function]: Jenssegers\Date\DateServiceProvider->boot()
#7 /home/vagrant/code/public/Cachet/vendor/laravel/framework/src/Illuminate/Con$
#8 /home/vagrant/code/public/Cachet/vendor/laravel/framework/src/Illuminate/Fou$
#9 /home/vagrant/code/public/Cachet/vendor/laravel/framework/src/Illuminate/Fou$
#10 [internal function]: Illuminate\Foundation\Application->Illuminate\Foundati$
#11 /home/vagrant/code/public/Cachet/vendor/laravel/framework/src/Illuminate/Fo$
#12 /home/vagrant/code/public/Cachet/vendor/laravel/framework/src/Illuminate/Fo$
#13 /home/vagrant/code/public/Cachet/vendor/laravel/framework/src/Illuminate/Fo$
#14 /home/vagrant/code/public/Cachet/vendor/laravel/framework/src/Illuminate/Fo$
#15 /home/vagrant/code/public/Cachet/vendor/laravel/framework/src/Illuminate/Fo$
#16 /home/vagrant/code/public/Cachet/vendor/laravel/framework/src/Illuminate/Fo$
#17 /home/vagrant/code/public/Cachet/public/index.php(54): Illuminate\Foundatio$

#0 /home/vagrant/code/public/Cachet/vendor/jenssegers/date/src/Date.php(10): Illuminate\Foundation\Bootstrap\HandleException$
#1 /home/vagrant/code/public/Cachet/vendor/composer/ClassLoader.php(444): include('/home/vagrant/c...')
#2 /home/vagrant/code/public/Cachet/vendor/composer/ClassLoader.php(322): Composer\Autoload\includeFile('/home/vagrant/c...')
#3 [internal function]: Composer\Autoload\ClassLoader->loadClass('Jenssegers\\Date...')
#4 /home/vagrant/code/public/Cachet/vendor/jenssegers/date/src/DateServiceProvider.php(36): spl_autoload_call('Jenssegers\\D$
#5 /home/vagrant/code/public/Cachet/vendor/jenssegers/date/src/DateServiceProvider.php(25): Jenssegers\Date\DateServiceProvi$
#6 [internal function]: Jenssegers\Date\DateServiceProvider->boot()
#7 /home/vagrant/code/public/Cachet/vendor/laravel/framework/src/Illuminate/Container/Container.php(507): call_user_func_arr$
#8 /home/vagrant/code/public/Cachet/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(757): Illuminate\Cont$
#9 /home/vagrant/code/public/Cachet/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(740): Illuminate\Foun$
#10 [internal function]: Illuminate\Foundation\Application->Illuminate\Foundation\{closure}(Object(Jenssegers\Date\DateServi$
#11 /home/vagrant/code/public/Cachet/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(741): array_walk(Arr$
#12 /home/vagrant/code/public/Cachet/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/BootProviders.php(17): Ill$
#13 /home/vagrant/code/public/Cachet/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(203): Illuminate\Fou$
#14 /home/vagrant/code/public/Cachet/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(232): Illuminate\Fou$
#15 /home/vagrant/code/public/Cachet/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(127): Illuminate\Fou$
#16 /home/vagrant/code/public/Cachet/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(99): Illuminate\Foun$
#17 /home/vagrant/code/public/Cachet/public/index.php(54): Illuminate\Foundation\Http\Kernel->handle(Object(Illuminate\Http\$
#18 {main} {"identification":{"id":"0e916565-7c42-4652-8591-cc9c1cc9a45c"}}

**Comment by jbrooksuk** [comment]
Thank you for your input on Cachet 2.x. We are shifting our attention and resources to Cachet 3.x and will no longer be supporting the 2.x version. If your feedback or issue is relevant to the 3.x series, we encourage you to engage with the new branch.

For more information on the Cachet rebuild and our plans for 3.x, you can read the announcement [here](https://github.com/CachetHQ/Cachet/discussions/4342).

We appreciate your understanding and look forward to your contributions to the new version.
