### ISSUE TITLE
Nothing loading after authentication

### ISSUE THREAD

**Issue by redstonedesigner** [CachetHQ/Cachet#3899]
Issue: When accessing any pages on my site, a 500 error code is received.

Expected Behaviour: Pages show on the site.
Actual Behaviour: A 500 error code is received.

Steps to reproduce:
1. Access any page on [http://status.redstonedesigner.com](http://status.redstonedesigner.com)

OS: Debian 9/10

Stack Trace: [https://hastebin.com/logezowifa.shell](https://hastebin.com/logezowifa.shell)

**Comment by jbrooksuk** [comment]
Thank you for your input on Cachet 2.x. We are shifting our attention and resources to Cachet 3.x and will no longer be supporting the 2.x version. If your feedback or issue is relevant to the 3.x series, we encourage you to engage with the new branch.

For more information on the Cachet rebuild and our plans for 3.x, you can read the announcement [here](https://github.com/CachetHQ/Cachet/discussions/4342).

We appreciate your understanding and look forward to your contributions to the new version.
