### ISSUE TITLE
API auth doesnt seem to work always receiving 401 error

### ISSUE THREAD

**Issue by thedom4302** [CachetHQ/Cachet#3900]
Always receive a 401 error for any API post calls: Authentication is required and has failed or has not yet been provided.

[2019-12-19 13:30:43] production.NOTICE: Symfony\Component\HttpKernel\Exception\HttpException in /var/www/cachet/app/Http/Middleware/ApiAuthentication.php:66

Tried regenerating the key a few times no success.
I am including the base64: prefix

ideas?

**Comment by thedom4302** [comment]
user issue!

**Comment by meeximum** [comment]
@thedom4302 hi, what was your solution? I'm facing the same problem :-(
