### ISSUE TITLE
Error 500 on subscribe

### ISSUE THREAD

**Issue by Blade2021** [CachetHQ/Cachet#3902]
Hello,

I'm getting a server error when I attempt to subscribe.  I changed my .env after the initial setup to add the mail server creds.  

Error code: 2827f6d6-75ea-4280-aeee-71e9042afcd6

Is it possible to reload cachet back to the original state or trigger the setup process again?

**Comment by Pimorez** [comment]
Try changing your working directory to the application root directory and then run 'php artisan app:update' that worked for me a few times.

**Comment by jbrooksuk** [comment]
Thank you for your input on Cachet 2.x. We are shifting our attention and resources to Cachet 3.x and will no longer be supporting the 2.x version. If your feedback or issue is relevant to the 3.x series, we encourage you to engage with the new branch.

For more information on the Cachet rebuild and our plans for 3.x, you can read the announcement [here](https://github.com/CachetHQ/Cachet/discussions/4342).

We appreciate your understanding and look forward to your contributions to the new version.
