### ISSUE TITLE
Error 500

### ISSUE THREAD

**Issue by onlimited-msj** [CachetHQ/Cachet#3907]
Hello, i have followed the install instructions and I am getting a 500 Error when I visit the homepage (index.php):

> Error 500
Houston, We Have A Problem.
Internal Server Error

> What does this mean?
Something went wrong on our servers while we were processing your request. An error has occurred and this resource cannot be displayed. This occurrence has been logged, and a highly trained team of monkeys has been dispatched to deal with your problem. We're really sorry about this, and will work hard to get this resolved as soon as possible.

> This error can be identified by 85eb9611-4896-4905-a282-475d725c6c54. You might want to take a note of this code.

> Perhaps you would like to go to our home page?

It is running on a Windows server with PHP 7.4.0 and MySQL 8.
Can someone help me?

**Comment by Pimorez** [comment]
Try checking the logs for the cause of this. The logs are usually located in `storage/logs/laravel.log`.
Otherwise you can try a `php artisan app:update`, that fixed random issues for me a few times.

**Comment by gramakri** [comment]
I think the latest release only work with php 7.1. You have to wait for Cachet 2.4 for php 7.2/7.3 support. @jbrooksuk can correct me if my understanding is incorrect.

**Comment by jbrooksuk** [comment]
Thank you for your input on Cachet 2.x. We are shifting our attention and resources to Cachet 3.x and will no longer be supporting the 2.x version. If your feedback or issue is relevant to the 3.x series, we encourage you to engage with the new branch.

For more information on the Cachet rebuild and our plans for 3.x, you can read the announcement [here](https://github.com/CachetHQ/Cachet/discussions/4342).

We appreciate your understanding and look forward to your contributions to the new version.
