### ISSUE TITLE
Primary key missing during table creation in migrations

### ISSUE THREAD

**Issue by TriP00r** [CachetHQ/Cachet#3911]
Hello,

I have an issue using Percona XtraDB MySQL 5.7 in Master mode, because there is no Primary Key used when creating the database during the initial migrations.

Error:
```
SQLSTATE[HY000]: General error: 1105 Percona-XtraDB-Cluster prohibits use of DML command on a table (monitoring_cachethq.migrations) without an explicit primary key with pxc_strict_mode = ENFORCING or MASTER (SQL: insert into `migrations` (`migration`, `batch`) values (2015_01_05_201324_CreateComponentGroupsTable, 1))
```

I suggest adding a Primary Key when creating tables in the migrations.

**Comment by jbrooksuk** [comment]
Thank you for your input on Cachet 2.x. We are shifting our attention and resources to Cachet 3.x and will no longer be supporting the 2.x version. If your feedback or issue is relevant to the 3.x series, we encourage you to engage with the new branch.

For more information on the Cachet rebuild and our plans for 3.x, you can read the announcement [here](https://github.com/CachetHQ/Cachet/discussions/4342).

We appreciate your understanding and look forward to your contributions to the new version.
