### ISSUE TITLE
Is there a limit to subscribers for a standard Cachet status page system

### ISSUE THREAD

**Issue by ghost** [CachetHQ/Cachet#3917]
Not really an issue, more of a question. Is there a limit on how many subscribers you can have subscribed to your Cachet status page system?

**Comment by jbrooksuk** [comment]
Thank you for your input on Cachet 2.x. We are shifting our attention and resources to Cachet 3.x and will no longer be supporting the 2.x version. If your feedback or issue is relevant to the 3.x series, we encourage you to engage with the new branch.

For more information on the Cachet rebuild and our plans for 3.x, you can read the announcement [here](https://github.com/CachetHQ/Cachet/discussions/4342).

We appreciate your understanding and look forward to your contributions to the new version.
