### ISSUE TITLE
Google 2fa

### ISSUE THREAD

**Issue by jeromeza** [CachetHQ/Cachet#3919]
Hi,

I’m struggling to find a documented source to set this up.

I can see that’s it’s supported in the docs and can see some sample config in some of the php - but I can’t find any way to enable it in the admin panel.

Could you please point me in the right direction?

Cachet 2.4.0-dev

Thanks!

**Comment by jamesmacwhite** [comment]
Try going to /dashboard/user when logged into your user account, you should find the 2FA settings there.

**Comment by jbrooksuk** [comment]
Thank you for your input on Cachet 2.x. We are shifting our attention and resources to Cachet 3.x and will no longer be supporting the 2.x version. If your feedback or issue is relevant to the 3.x series, we encourage you to engage with the new branch.

For more information on the Cachet rebuild and our plans for 3.x, you can read the announcement [here](https://github.com/CachetHQ/Cachet/discussions/4342).

We appreciate your understanding and look forward to your contributions to the new version.
