### ISSUE TITLE
2.4-dev Manage Subscription URLs in email incomplete

### ISSUE THREAD

**Issue by maggiemcfee** [CachetHQ/Cachet#3922]
I'm on 2.4-dev branch and everything is working, but while testing subscription notifications I found an issue with the URLs subscribers receive.

If I subscribe, I get an initial email with a Manage Subscription button whose URL looks like 
https://example.com/subscribe/manage/8ZnzfBTgCDutwrheYOJ8HfkjHlJlX2H8xxxxxukzZ?signature=e65a1f8ieufh90def347a153841049d9f92d2c44c69exxxxxxc8e71efb67da9a
This URL works just fine.

When a component change or incident email is sent, there is, at the bottom, an Unsubscribe URL (that works) and a Manage Subscription URL that does not work. The latter appears to be missing the signature. That URL looks like 
https://example.com/subscribe/manage/8ZnzfBTgCDutwrheYOJ8HfkjHlJlX2H8VEddCukzZ

The log shows:
#49 {main} {"identification":{"id":"d0e57e2b-f4cf-4676-9b27-4901a2d3fe86"},"exception":"[object] (Illuminate\\Routing\\Exceptions\\InvalidSignatureException(code: 0): Invalid signature. at /var/www/Cachet/vendor/laravel/framework/src/Illuminate/Routing/Middleware/ValidateSignature.php:25)
[stacktrace]

**Comment by bartekl** [comment]
It seems that code generating urls for subscribers is incorrect.and in consequence missing signature which is required here.

root@statuspage # git diff app/Notifications/Component/ComponentStatusChangedNotification.php
diff --git a/app/Notifications/Component/ComponentStatusChangedNotification.php b/app/Notifications/Component/ComponentStatusChangedNotification.php
index 47502ed2..f3d62bbd 100644
--- a/app/Notifications/Component/ComponentStatusChangedNotification.php
+++ b/app/Notifications/Component/ComponentStatusChangedNotification.php
@@ -18,6 +18,7 @@ use Illuminate\Notifications\Messages\NexmoMessage;
 use Illuminate\Notifications\Messages\SlackMessage;
 use Illuminate\Notifications\Notification;
 use McCool\LaravelAutoPresenter\Facades\AutoPresenter;
+use Illuminate\Support\Facades\URL;

 /**
  * This is the component status changed notification class.
@@ -83,6 +84,8 @@ class ComponentStatusChangedNotification extends Notification
             'new_status' => trans("cachet.components.status.{$this->status}"),
         ]);

+       $route = URL::signedRoute(cachet_route_generator('subscribe.manage'), ['code' => $notifiable->verify_code]);
+
         return (new MailMessage())
             ->subject(trans('notifications.component.status_update.mail.subject'))
             ->markdown('notifications.component.update', [
@@ -91,7 +94,7 @@ class ComponentStatusChangedNotification extends Notification
                 'unsubscribeText'        => trans('cachet.subscriber.unsubscribe'),
                 'unsubscribeUrl'         => cachet_route('subscribe.unsubscribe', $notifiable->verify_code),
                 'manageSubscriptionText' => trans('cachet.subscriber.manage_subscription'),
-                'manageSubscriptionUrl'  => cachet_route('subscribe.manage', $notifiable->verify_code),
+                'manageSubscriptionUrl'  => $route,
         ]);
     }

Something like above does the trick solving the issue. I identified at least the following require similar patch:
app/Notifications/Component/ComponentStatusChangedNotification.php
app/Notifications/Incident/NewIncidentNotification.php
app/Notifications/IncidentUpdate/IncidentUpdatedNotification.php

Best regards,
BL

**Comment by jbrooksuk** [comment]
Thank you for your input on Cachet 2.x. We are shifting our attention and resources to Cachet 3.x and will no longer be supporting the 2.x version. If your feedback or issue is relevant to the 3.x series, we encourage you to engage with the new branch.

For more information on the Cachet rebuild and our plans for 3.x, you can read the announcement [here](https://github.com/CachetHQ/Cachet/discussions/4342).

We appreciate your understanding and look forward to your contributions to the new version.
