### ISSUE TITLE
[PDOException] could not find driver

### ISSUE THREAD

**Issue by arvinjarvin** [CachetHQ/Cachet#3923]
self explanatory title, happens when i run `php artisan app:update` . running php 7.1 with cachet 2.3.9
500 houston error when entering /setup

**Comment by arvinjarvin** [comment]
`
  Problem 1
    - The requested PHP extension ext-xml * is missing from your system. Install or enable PHP's xml extension.
  Problem 2
    - Installation request for laravel/framework v5.2.39 -> satisfiable by laravel/framework[v5.2.39].
    - laravel/framework v5.2.39 requires ext-mbstring * -> the requested PHP extension mbstring is missing from your system.
  Problem 3
    - Installation request for league/commonmark 0.13.4 -> satisfiable by league/commonmark[0.13.4].
    - league/commonmark 0.13.4 requires ext-mbstring * -> the requested PHP extension mbstring is missing from your system.
  Problem 4
    - Installation request for simplesoftwareio/simple-qrcode 1.3.3 -> satisfiable by simplesoftwareio/simple-qrcode[1.3.3].
    - simplesoftwareio/simple-qrcode 1.3.3 requires ext-gd * -> the requested PHP extension gd is missing from your system.
  Problem 5
    - laravel/framework v5.2.39 requires ext-mbstring * -> the requested PHP extension mbstring is missing from your system.
    - roumen/feed v2.10.4 requires illuminate/support ^5.0 -> satisfiable by laravel/framework[v5.2.39].
    - Installation request for roumen/feed v2.10.4 -> satisfiable by roumen/feed[v2.10.4].
`

**Comment by arvinjarvin** [comment]
```
  Problem 1
    - The requested PHP extension ext-xml * is missing from your system. Install or enable PHP's xml extension.
  Problem 2
    - Installation request for laravel/framework v5.2.39 -> satisfiable by laravel/framework[v5.2.39].
    - laravel/framework v5.2.39 requires ext-mbstring * -> the requested PHP extension mbstring is missing from your system.
  Problem 3
    - Installation request for league/commonmark 0.13.4 -> satisfiable by league/commonmark[0.13.4].
    - league/commonmark 0.13.4 requires ext-mbstring * -> the requested PHP extension mbstring is missing from your system.
  Problem 4
    - Installation request for simplesoftwareio/simple-qrcode 1.3.3 -> satisfiable by simplesoftwareio/simple-qrcode[1.3.3].
    - simplesoftwareio/simple-qrcode 1.3.3 requires ext-gd * -> the requested PHP extension gd is missing from your system.
  Problem 5
    - laravel/framework v5.2.39 requires ext-mbstring * -> the requested PHP extension mbstring is missing from your system.
    - roumen/feed v2.10.4 requires illuminate/support ^5.0 -> satisfiable by laravel/framework[v5.2.39].
    - Installation request for roumen/feed v2.10.4 -> satisfiable by roumen/feed[v2.10.4].

```

**Comment by ajtrichards** [comment]
Does your server have the `gd`, `xml` and `mbstring` extensions installed?

**Comment by jbrooksuk** [comment]
Thank you for your input on Cachet 2.x. We are shifting our attention and resources to Cachet 3.x and will no longer be supporting the 2.x version. If your feedback or issue is relevant to the 3.x series, we encourage you to engage with the new branch.

For more information on the Cachet rebuild and our plans for 3.x, you can read the announcement [here](https://github.com/CachetHQ/Cachet/discussions/4342).

We appreciate your understanding and look forward to your contributions to the new version.
