### ISSUE TITLE
Component field updated_at not updating after API call

### ISSUE THREAD

**Issue by fdcastel** [CachetHQ/Cachet#3928]
I'm updating my components statuses via API making a `PUT` request in `/api/v1/components/$myComponentId` and passing the following json

```json
{
    "status":  1
}
```

Everything is working fine, except the field `updated_at` is not updating.

I found the issue #2802 (from 2 years ago) which appears to be the same problem but it was dismissed as a "support" question. However, I can't find any documentation about the behavior of this field. 

Also, in [this SO answer](https://stackoverflow.com/a/36813265) the Cachet lead developer says:

> All you need to do is update the Component status. Cachet will take care of the updated_at timestamp for you.

I'm doing something wrong? Should I put anything else in the json sent to the API? There is a configuration to change this behavior?  

Please understand I'm very new to Cachet and I'm seeing this as a bug of major loss of functionality (customers expect to see this field updated). If this is really a support question, please explain this behavior better in the documentation. I'm sure many new users would have the same reasoning.

Using `cachethq/docker` image `6d0814fbb73b`.  Api version: `{"meta":{"on_latest":true,"latest":{"tag_name":"v2.3.18","prelease":false,"draft":false}},"data":"2.4.0-dev"}`

**Comment by gustavobim** [comment]
I'm facing a similar scenario running Cachet 2.4.0-dev.
It seems the Laravel ORM component detects there are no changes to the data and decides to not perform any updates in the database.

I noticed the `PUT ` request works fine if you try with any "new" value. Example, if the current status is "1" and you try to run:

PUT https://[my-status-page.com]/api/v1/components/1

```
{
    "status":  2
}

```
The `updated_at` filed will be updated with the current timestamp.

I'm setting up an external monitoring system which will need to update the component to the latest time which was checked. So I'm still trying to find a way to have this timestamp updated even thought there were no status change to the component.

**Comment by pelusanchez** [comment]
As a workaround in 2.4, you can update the `meta` field in order to have the `updated_at` field updated without changing the status:

```
{
    "status":  1,
    "meta": {
       "ts": "1633347447894"
    }
}

```
In this case, the `meta` field has a timestamp to force the ORM update the entity.

**Comment by jbrooksuk** [comment]
Thank you for your input on Cachet 2.x. We are shifting our attention and resources to Cachet 3.x and will no longer be supporting the 2.x version. If your feedback or issue is relevant to the 3.x series, we encourage you to engage with the new branch.

For more information on the Cachet rebuild and our plans for 3.x, you can read the announcement [here](https://github.com/CachetHQ/Cachet/discussions/4342).

We appreciate your understanding and look forward to your contributions to the new version.
