### ISSUE TITLE
2.4-dev When editing a maintenance event, date & time are reset to 'now'

### ISSUE THREAD

**Issue by maggiemcfee** [CachetHQ/Cachet#3929]
On 2.4-dev 
When editing a maintenance event, the scheduled date & time will get reset to "now".
Expected behavior would be to retain the existing value.

**Comment by maggiemcfee** [comment]
Addendum: If you accidentally click in the 'When did this maintenance complete?' it will also auto-set to 'now' and you cannot clear it (if you do clear it, it will fill in 'now' anyway when you save).

**Comment by jbrooksuk** [comment]
Thank you for your input on Cachet 2.x. We are shifting our attention and resources to Cachet 3.x and will no longer be supporting the 2.x version. If your feedback or issue is relevant to the 3.x series, we encourage you to engage with the new branch.

For more information on the Cachet rebuild and our plans for 3.x, you can read the announcement [here](https://github.com/CachetHQ/Cachet/discussions/4342).

We appreciate your understanding and look forward to your contributions to the new version.
