### ISSUE TITLE
Show components groups on status page

### ISSUE THREAD

**Issue by jleroy** [cachethq/Cachet#393]
Hi all :metal:, 

It would be great to show compoments groups on status page, like on [Cloudflare status page](https://www.cloudflarestatus.com/). When collapsed, the component group show status of its component who have the most critical status.
When unfold, there is no status shown next to component group.

:dash:

**Comment by jbrooksuk** [comment]
This will most likely be arriving in V2 of Cachet - we've made headway on it with the component groups feature.

**Comment by nicolabricot** [comment]
:+1:

**Comment by anarcat** [comment]
what use are component groups without this anyways?

**Comment by jbrooksuk** [comment]
This is now a thing ;)
