### ISSUE TITLE
feature request; attach (small) image/logo  to component(group)

### ISSUE THREAD

**Issue by HollandHards** [CachetHQ/Cachet#3933]
it's possible to use the amazing wonderfull emoji's✳️ 🛠 to add distinctive between component(groups) - makes them easy to recognize. 

think would make nice feature to add own (small) image/logo to components and its groups.

**Comment by jbrooksuk** [comment]
Thank you for your input on Cachet 2.x. We are shifting our attention and resources to Cachet 3.x and will no longer be supporting the 2.x version. If your feedback or issue is relevant to the 3.x series, we encourage you to engage with the new branch.

For more information on the Cachet rebuild and our plans for 3.x, you can read the announcement [here](https://github.com/CachetHQ/Cachet/discussions/4342).

We appreciate your understanding and look forward to your contributions to the new version.
