### ISSUE TITLE
Subscribe disable?

### ISSUE THREAD

**Issue by rdmrm4g00** [CachetHQ/Cachet#3934]
Hi.

Can we disable the option to subscribe - ie I would like to add a mailing list via Office 365 to this tool.

I cant as this requires Cachet to authorize / be a subscriber, can I add a subscriber without first email activation so I can add a distribution list as the intended recipient >?

Thanks

**Comment by joe-eklund** [comment]
Unless I am misunderstanding, you want to add a distribution list as the recipient for some subscriptions.

What is stopping you from adding it as a subscriber? It will send a confirmation email, which you should get if you are on the distribution list. Then you can subscribe what you want for that list.

**Comment by rdmrm4g00** [comment]
Hi.

Thanks for coming back.

Basically if you have a distribution list of over 300 people it's not ideal
to send out a confirmation email to that many people just to authorise.

What would be awesome is a way to just be able to add a receiptant without
pre authorization  so you have the options of adding mass dist lists.

Thanks,

Ross

**Comment by joe-eklund** [comment]
Ah I see what you mean. As far as I know no such disable option exists currently. 

Maybe one workaround would be to setup a middleman email. Use this email as the subscription email and confirm it. Then forward all emails from that email to your distribution list after it has been confirmed.

**Comment by jbrooksuk** [comment]
Thank you for your input on Cachet 2.x. We are shifting our attention and resources to Cachet 3.x and will no longer be supporting the 2.x version. If your feedback or issue is relevant to the 3.x series, we encourage you to engage with the new branch.

For more information on the Cachet rebuild and our plans for 3.x, you can read the announcement [here](https://github.com/CachetHQ/Cachet/discussions/4342).

We appreciate your understanding and look forward to your contributions to the new version.
