### ISSUE TITLE
Error 500

### ISSUE THREAD

**Issue by koltl** [CachetHQ/Cachet#3941]
After hours of trying to get everything to work, I went through the setup process in which the dashboard displays this Error 500,

Internal Server Error
What does this mean?

Something went wrong on our servers while we were processing your request. An error has occurred and this resource cannot be displayed. This occurrence has been logged, and a highly trained team of monkeys has been dispatched to deal with your problem. We're really sorry about this, and will work hard to get this resolved as soon as possible.

This error can be identified by 6d84637a-90f9-4784-a294-14359c4661b9. You might want to take a note of this code.

Perhaps you would like to go to our home page? 

Any ideas?

**Comment by joe-eklund** [comment]
Are you able to get into the Dashboard > Settings > Log?

**Comment by koltl** [comment]
Nope, even going to /dashboard gives me the same error

**Comment by joe-eklund** [comment]
Are you running in docker or directly on the machine?

**Comment by koltl** [comment]
Directly on the machine

**Comment by joe-eklund** [comment]
Ok. Are you able to post any additional logs to help narrow down what could be happening? Have you followed the installation instructions at https://docs.cachethq.io/docs/installing-cachet? There is a note in there about a 500 error that may be worth a try.

**Comment by koltl** [comment]
I followed the commands suggestion if getting the 500 error, still no luck.  I followed through that page.  

When I do composer install --no-dev -o , I get

> php artisan optimize --force
Generating optimized class loader
Compiling common classes

                                                                               
  [ErrorException]                                                             
  Invalid characters passed for attempted conversion, these have been ignored  
                                                                               

Script php artisan optimize --force handling the post-install-cmd event returned with error code 1

I don't know what that is about.

Where would I find the logs?

**Comment by koltl** [comment]
I restarted the host and still same 500 error.

**Comment by bartashevich** [comment]
What PHP version are you using?

I found out that for cachet 2.3 the Max PHP version is 7.1

For cachet 2.4 I got it working with PHP 7.3

**Comment by bartashevich** [comment]
This should be well documented in README.

**Comment by koltl** [comment]
I am using 2.3.6 on PHP 7.3.  I am going install php 7.1.  Is there a line code that can download all the necessary components for PHP 7.1 and other things since it's difficult to get everything individually.  Thank you

**Comment by bartashevich** [comment]
I used CentOS 7, but here go…
yum install php php-common php-opcache php-mcrypt php-cli php-gd php-curl php-mysql php-xml php-mbstring

On how to install PHP7.1: https://linuxize.com/post/install-php-7-on-centos-7/#installing-php-71-on-centos-7

**Comment by koltl** [comment]
Uninstall old php and installed the following,
sudo apt-get install -y php7.1 php7.1-fpm php7.1-cli php7.1-common php7.1-mbstring php7.1-gd php7.1-intl php7.1-xml php7.1-mysql php7.1-mcrypt php7.1-zip

My Wordpress site which uses PHP works but still the Cachet install is giving me error 500.  Should I try reinstalling?

**Comment by bartashevich** [comment]
Yeah. remove the cachet and install it from scratch. And don't forget to give permissions, both user and write acess

**Comment by koltl** [comment]
All done and it seems to be working :)  Question, will Cachet automatically set a component offline if it detects the link won't work?  Or do I have to do it manually.  I tried one service that let me use a port to do this automatically.  Thanks

**Comment by bartashevich** [comment]
A cachet is only a visualization tool with API capabilities. If you want to monitor and update you need to create your own script or tools developed by other (https://docs.cachethq.io/docs/addons)

**Comment by jbrooksuk** [comment]
Thank you for your input on Cachet 2.x. We are shifting our attention and resources to Cachet 3.x and will no longer be supporting the 2.x version. If your feedback or issue is relevant to the 3.x series, we encourage you to engage with the new branch.

For more information on the Cachet rebuild and our plans for 3.x, you can read the announcement [here](https://github.com/CachetHQ/Cachet/discussions/4342).

We appreciate your understanding and look forward to your contributions to the new version.
