### ISSUE TITLE
Favicon resolution 

### ISSUE THREAD

**Issue by joe-eklund** [CachetHQ/Cachet#3942]
It looks like the favicon has a resolution that is quite low. I believe it is using [this](https://raw.githubusercontent.com/CachetHQ/Cachet/2.4/public/favicon.ico)?

Is it possible to have an optional higher resolution one? Say 32 x 32 instead of just 16 x 16?

Here is [some good info about favicon sizes](https://github.com/audreyr/favicon-cheat-sheet).

This would make the favicon look much better in today's modern browsers. I know I could make my own and replace it myself, but figured other people would benefit from having an increased resolution.

**Comment by jbrooksuk** [comment]
Thank you for your input on Cachet 2.x. We are shifting our attention and resources to Cachet 3.x and will no longer be supporting the 2.x version. If your feedback or issue is relevant to the 3.x series, we encourage you to engage with the new branch.

For more information on the Cachet rebuild and our plans for 3.x, you can read the announcement [here](https://github.com/CachetHQ/Cachet/discussions/4342).

We appreciate your understanding and look forward to your contributions to the new version.
