### ISSUE TITLE
[2.4-dev][Bug] After component order change (dragging), ALL components tags fields are set to 1

### ISSUE THREAD

**Issue by bartashevich** [CachetHQ/Cachet#3943]
As described in the title, after component order change (dragging) ALL components have the same tags field set to 1.

**Comment by jbrooksuk** [comment]
Thank you for your input on Cachet 2.x. We are shifting our attention and resources to Cachet 3.x and will no longer be supporting the 2.x version. If your feedback or issue is relevant to the 3.x series, we encourage you to engage with the new branch.

For more information on the Cachet rebuild and our plans for 3.x, you can read the announcement [here](https://github.com/CachetHQ/Cachet/discussions/4342).

We appreciate your understanding and look forward to your contributions to the new version.
