### ISSUE TITLE
Consistent Json types

### ISSUE THREAD

**Issue by gaschu95** [CachetHQ/Cachet#3949]
When calling `/api/v1/components/` the returned components' tags contain either an **_object/map_** with the tags or an empty **_list_**. Java doesn't support different datatypes for the same field, so when talking to the API it's now necessary to write custom deserializers which deal with this inconsistency.

Also the JSON in the Docs for /components/:component is invalid:
`{
    "data": {
        "id": 1,
        "name": "Component Name",
        "description": "Description",
        "link": "",
        "status": 1,
        "order": 0,
        "group_id": 0,
        "created_at": "2015-08-01 12:00:00",
        "updated_at": "2015-08-01 12:00:00",
        "deleted_at": null,
        "status_name": "Operational",
        "tags": [
            "slug-of-tag": "Tag Name"
        ]
    }
}`

A List cannot contain key: value pairs.

`"tags": [
            "slug-of-tag": "Tag Name"
        ]`

should be

`"tags": {
            "slug-of-tag": "Tag Name"
        }`

**Comment by jbrooksuk** [comment]
Thank you for your input on Cachet 2.x. We are shifting our attention and resources to Cachet 3.x and will no longer be supporting the 2.x version. If your feedback or issue is relevant to the 3.x series, we encourage you to engage with the new branch.

For more information on the Cachet rebuild and our plans for 3.x, you can read the announcement [here](https://github.com/CachetHQ/Cachet/discussions/4342).

We appreciate your understanding and look forward to your contributions to the new version.
