### ISSUE TITLE
solved - Error 500 randomly when adding incidents

### ISSUE THREAD

**Issue by astrakid** [CachetHQ/Cachet#3951]
hi,
every now and then we get error 500 messages when adding incidents. this also happens when trying to login sometimes. it will fail for some time (lots of seconds, a few minutes - don't know how long exactly).

log:
[2020-02-27 09:34:46] production.ERROR: Swift_TransportException: Expected response code 354 but got code "503", with message "503 5.5.2 Need rcpt command

Any help?

**Comment by defulmere** [comment]
Looks like it's trying to send mail without the necessary info. Are your mail settings all set?

**Comment by astrakid** [comment]
Yes, thanks! Indeed that was the case, although I don't really understand it:
On our exchange the cachet-ip was whitelisted for relaying. This IP had been removed by someone. Nevertheless the mails were actually sent, so I couldn't believe this was the reason.
