### ISSUE TITLE
Http monitoring addon

### ISSUE THREAD

**Issue by maka1000** [CachetHQ/Cachet#3956]
Hi
I would like to run cachethq on my webserver and at the statuspage should be visible if some websites ex. www.mydomain.com is online or not. I have only found some addons written in python but my webserver don't support python. Is there another php script/addon which have the same feature?

**Comment by jbrooksuk** [comment]
Thank you for your input on Cachet 2.x. We are shifting our attention and resources to Cachet 3.x and will no longer be supporting the 2.x version. If your feedback or issue is relevant to the 3.x series, we encourage you to engage with the new branch.

For more information on the Cachet rebuild and our plans for 3.x, you can read the announcement [here](https://github.com/CachetHQ/Cachet/discussions/4342).

We appreciate your understanding and look forward to your contributions to the new version.
