### ISSUE TITLE
Default timezone should be based on the browser local time.

### ISSUE THREAD

**Issue by Zauxst** [CachetHQ/Cachet#3959]
Hi, users in different time zones should be able to see their local time instead of the site time.

**Comment by jbrooksuk** [comment]
Thank you for your input on Cachet 2.x. We are shifting our attention and resources to Cachet 3.x and will no longer be supporting the 2.x version. If your feedback or issue is relevant to the 3.x series, we encourage you to engage with the new branch.

For more information on the Cachet rebuild and our plans for 3.x, you can read the announcement [here](https://github.com/CachetHQ/Cachet/discussions/4342).

We appreciate your understanding and look forward to your contributions to the new version.
