### ISSUE TITLE
Support setting creation on settings config repository

### ISSUE THREAD

**Issue by joecohens** [cachethq/Cachet#396]

**Comment by GrahamCampbell** [comment]
:+1:

**Comment by jbrooksuk** [comment]
Can this be as simple as something like:

```php
public function set($settingName, $settingValue)
{
    return $this->model->updateOrCreate([
        'name' => $settingName,
    ], [
        'value' => $settingValue,
    ]);
}
```

?

**Comment by jbrooksuk** [comment]
It does work and I can't think of anything else that it actually needs to do. Thoughts @GrahamCampbell?

**Comment by GrahamCampbell** [comment]
Yeh, would probably be fine like that. :)

**Comment by GrahamCampbell** [comment]
just name and value, rather than settingName and settingValue though

**Comment by GrahamCampbell** [comment]
then can be: `return $this->model->updateOrCreate(compact('name'), compact('value'));`

**Comment by jbrooksuk** [comment]
On it :)

**Comment by joecohens** [comment]
:+1:
