### ISSUE TITLE
Mail settings option missing 

### ISSUE THREAD

**Issue by djanand2000** [CachetHQ/Cachet#3960]
Hi Team,
The cachet version 2.3.18 is missing the mail options under the settings page. can you please help?
![image](https://user-images.githubusercontent.com/34451983/76405200-10fdec00-6388-11ea-90cc-c6d14231e7df.png)

**Comment by jbrooksuk** [comment]
Thank you for your input on Cachet 2.x. We are shifting our attention and resources to Cachet 3.x and will no longer be supporting the 2.x version. If your feedback or issue is relevant to the 3.x series, we encourage you to engage with the new branch.

For more information on the Cachet rebuild and our plans for 3.x, you can read the announcement [here](https://github.com/CachetHQ/Cachet/discussions/4342).

We appreciate your understanding and look forward to your contributions to the new version.
