### ISSUE TITLE
Authenticated Status Page

### ISSUE THREAD

**Issue by codehimanshu** [CachetHQ/Cachet#3961]
I want to secure my Status Page routs also by the Auth middleware. Tried adding auth to app/Http/Routes/StatusPageRoutes.php, router group. But nothing worked. Is there any other option or we could use a setting for Authenticated Status Pages?

**Comment by jbrooksuk** [comment]
You could use Basic Auth on your server.

**Comment by gustavobim** [comment]
In my use case, we used https://github.com/latchset/mod_auth_mellon in order to setup a "private" status page only for the users authenticated in our single sign on server.
