### ISSUE TITLE
CachetHQ/Windows

### ISSUE THREAD

**Issue by MuthuDE** [CachetHQ/Cachet#3962]
Hi team,

  I have successfully installed cachet in windows system with PHP7.4 & Apache24 ,MSql

  Next step i am trying to setup email subscribers.

 I have issue in email subscribe:

   Errr 500 internal server- when i enter emailid and click Add.

Steps i followed:

   I followed the guide and trying to configuring queue.

  https://docs.cachethq.io/docs/configuring-the-queue

  I created the cachet.conf file and saved in var\www\html\cachet folder. And modified the conf based on my setup location.
 and run php artisan app:update 

  I am using smtp relay email settings so there no username and password so , i make username 

  CACHE_DRIVER=database
SESSION_DRIVER=database
QUEUE_DRIVER=database

CACHET_BEACON=true
CACHET_EMOJI=false
CACHET_AUTO_TWITTER=true

MAIL_DRIVER=smtp
MAIL_HOST=mydomain.com
MAIL_PORT=25
MAIL_USERNAME=null
MAIL_PASSWORD=null
MAIL_ADDRESS=null
MAIL_NAME=Cachet
MAIL_ENCRYPTION=tls

 Do i need to create job in mysql ? if so is there any examples?
 
 Please help to solve this issue.

**Comment by jbrooksuk** [comment]
Thank you for your input on Cachet 2.x. We are shifting our attention and resources to Cachet 3.x and will no longer be supporting the 2.x version. If your feedback or issue is relevant to the 3.x series, we encourage you to engage with the new branch.

For more information on the Cachet rebuild and our plans for 3.x, you can read the announcement [here](https://github.com/CachetHQ/Cachet/discussions/4342).

We appreciate your understanding and look forward to your contributions to the new version.
