### ISSUE TITLE
Access a component group via URI

### ISSUE THREAD

**Issue by sag1** [CachetHQ/Cachet#3963]
Hello,

We have many components groups and each group contains lot of components. Every time, the users are struggling to scroll. I would like to access the  particular component group on the first position based on my parameters in the link. Is it possible to do this via URI ?

Thanks in advance

**Comment by jbrooksuk** [comment]
Thank you for your input on Cachet 2.x. We are shifting our attention and resources to Cachet 3.x and will no longer be supporting the 2.x version. If your feedback or issue is relevant to the 3.x series, we encourage you to engage with the new branch.

For more information on the Cachet rebuild and our plans for 3.x, you can read the announcement [here](https://github.com/CachetHQ/Cachet/discussions/4342).

We appreciate your understanding and look forward to your contributions to the new version.
