### ISSUE TITLE
API Doesn't require Authentication

### ISSUE THREAD

**Issue by MrCarter2959** [CachetHQ/Cachet#3965]
Maybe I'm doing something wrong and thats why its just open, but when i navigate to my URL : https://site_name.domain.name/api/v1/components , It doesn't ask for authentication and is just open.

I haven't authenticated to the api in my web browser only my scripting windows, but even with those, if i use my code and call the API, it doesn't actually need my API Token, it will return data anyway.

I followed the instructions here for setting up apache2 https://docs.cachethq.io/docs/installing-cachet

**Comment by MarcProe** [comment]
https://docs.cachethq.io/docs/api-authentication
> Cachet is built on the belief that your service status is open and transparent, therefore all GET requests are public and require no authentication to access the information.

**Comment by MrCarter2959** [comment]
> https://docs.cachethq.io/docs/api-authentication
> 
> > Cachet is built on the belief that your service status is open and transparent, therefore all GET requests are public and require no authentication to access the information.

OHHH... I am so sorry. I didn't see that in the documentation. Thank you for pointing it out!
