### ISSUE TITLE
ionicons missing on status page

### ISSUE THREAD

**Issue by OstojaOfficial** [CachetHQ/Cachet#3966]
For some reason ionicons are mission on status page but on dashboard they are there.

Status page:
![image](https://user-images.githubusercontent.com/21225822/77184196-c428bc80-6acf-11ea-9ada-ef4ed21e03b4.png)

Dashboard:
![image](https://user-images.githubusercontent.com/21225822/77184325-f20e0100-6acf-11ea-855c-bc242697ef03.png)

**Comment by Carolkolassa** [comment]
I will leave here the solution found.
It is necessary to move the 'fonts' folder out of 'public'. Leaving it in the 'cachet' directory

**Comment by jbrooksuk** [comment]
Thank you for your input on Cachet 2.x. We are shifting our attention and resources to Cachet 3.x and will no longer be supporting the 2.x version. If your feedback or issue is relevant to the 3.x series, we encourage you to engage with the new branch.

For more information on the Cachet rebuild and our plans for 3.x, you can read the announcement [here](https://github.com/CachetHQ/Cachet/discussions/4342).

We appreciate your understanding and look forward to your contributions to the new version.
