### ISSUE TITLE
stylesheet is not visible on setup page

### ISSUE THREAD

**Issue by kathy-ling** [CachetHQ/Cachet#3967]
I use the branch 2.4.

firstly, I can not jump to setup page of cachet.

when using a configuration like this with nginx，it works.

**But my setup page do not have stylesheet**, and i can not make settings and open dashboard.

here is my page:
[https://github.com/kathy-ling/GitLearn/blob/master/issue.jpg](url)

And I have not modified the source code.

```
location ^~ /status {
          alias /var/www/html/cachet/public/;
          try_files $uri $uri/ @cachet;

          location ~ \.php {
              fastcgi_pass unix:/var/run/php-fpm.sock;
              fastcgi_split_path_info ^(.+\.php)(.*)$;

              fastcgi_index index.php;
              fastcgi_param SCRIPT_FILENAME $request_filename;
              fastcgi_param PATH_INFO $fastcgi_path_info;
              fastcgi_param HTTPS on;
              include fastcgi_params;

              # Mitigate https://httpoxy.org/ vulnerabilities
              fastcgi_param HTTP_PROXY "";
          }
      }

      location @cachet {
          rewrite /status/(.*)$ /status/index.php?/$1 last;
      }
```

**Comment by jbrooksuk** [comment]
Thank you for your input on Cachet 2.x. We are shifting our attention and resources to Cachet 3.x and will no longer be supporting the 2.x version. If your feedback or issue is relevant to the 3.x series, we encourage you to engage with the new branch.

For more information on the Cachet rebuild and our plans for 3.x, you can read the announcement [here](https://github.com/CachetHQ/Cachet/discussions/4342).

We appreciate your understanding and look forward to your contributions to the new version.
