### ISSUE TITLE
Move sqlite database to storage folder

### ISSUE THREAD

**Issue by joecohens** [cachethq/Cachet#397]

**Comment by jbrooksuk** [comment]
To write to the SQLite file within `app/database/*.sqlite` the `database` directory also needs to be writeable. We can make sure of this by moving the database to `storage` which is writeable.

**Comment by GrahamCampbell** [comment]
Bad idea. The storage folder is design for stuff that's unimportant, like compiled views and caches, not your db.

**Comment by jbrooksuk** [comment]
Ok, so what we should do then is add a `post-install-cmd` to chmod the directory and the sqlite file?

**Comment by GrahamCampbell** [comment]
Yeh. NB chmod in the composer.json will break installation on windows.

**Comment by jbrooksuk** [comment]
@GrahamCampbell surely it's already broken then due to `scripts.post-install-cmd`?

**Comment by GrahamCampbell** [comment]
Yeh, it is. I was just pointing out that we should move away from it, not add to it.

**Comment by jbrooksuk** [comment]
What other solutions do we have?

**Comment by GrahamCampbell** [comment]
Create a laravel command that changes the file permissions and run that.

**Comment by jbrooksuk** [comment]
:+1: ok.
