### ISSUE TITLE
Can not clean up Incidents and site will not load

### ISSUE THREAD

**Issue by andelhie** [CachetHQ/Cachet#3970]
I some how got 16,000 Incidents in my system and now the main page will not load as it times out.  The dashboard loads ok but when I go to the Incidents and try to delete them I get an error.

```
Error 405
Houston, We Have A Problem.
Method Not Allowed
What does this mean?
Something went wrong on our servers while we were processing your request. A request was made of a resource using a request method not supported by that resource. This occurrence has been logged, and a highly trained team of monkeys has been dispatched to deal with your problem. We're really sorry about this, and will work hard to get this resolved as soon as possible.

This error can be identified by 5d0e72a7-adff-440c-8a3b-4a2ee9c0a389. You might want to take a note of this code.

Perhaps you would like to go to our home page?
```
Is there a way to purge all these incidents so the page loads.  Looks like the php-fpm.sock is having a hard time loading all the incidents.

**Comment by andelhie** [comment]
I was able to get the page to render by changing the display incidents to 1 day but I still need to clean up the incident count.

**Comment by anilkapoorbind** [comment]
Hi, I am facing the same issue, how did you do that.

**Comment by jbrooksuk** [comment]
Thank you for your input on Cachet 2.x. We are shifting our attention and resources to Cachet 3.x and will no longer be supporting the 2.x version. If your feedback or issue is relevant to the 3.x series, we encourage you to engage with the new branch.

For more information on the Cachet rebuild and our plans for 3.x, you can read the announcement [here](https://github.com/CachetHQ/Cachet/discussions/4342).

We appreciate your understanding and look forward to your contributions to the new version.
