### ISSUE TITLE
PHP Fatal error

### ISSUE THREAD

**Issue by AstroHost** [CachetHQ/Cachet#3971]
3 days to try and get this blinking thing working and i've nearly had enough. 

My last ditch attempt 

PHP Fatal error:  Uncaught ErrorException: count(): Parameter must be an array or an object that implements Countable in /var/www/Cachet/vendor/graham-campbell/exceptions/src/ExceptionIdentifier.php:51
Stack trace:
#0 [internal function]: Illuminate\Foundation\Bootstrap\HandleExceptions->handleError(2, 'count(): Parame...', '/var/www/Cachet...', 51, Array)
#1 /var/www/Cachet/vendor/graham-campbell/exceptions/src/ExceptionIdentifier.php(51): count(NULL)
#2 /var/www/Cachet/vendor/graham-campbell/exceptions/src/ExceptionHandlerTrait.php(47): GrahamCampbell\Exceptions\ExceptionIdentifier->identify(Object(Symfony\Component\Debug\Exception\FatalErrorException))
#3 /var/www/Cachet/bootstrap/cache/compiled.php(2163): GrahamCampbell\Exceptions\ExceptionHandler->report(Object(Symfony\Component\Debug\Exception\FatalErrorException))
#4 /var/www/Cachet/bootstrap/cache/compiled.php(2181): Illuminate\Foundation\Bootstrap\HandleExceptions->handleException(Object(Symfony\Component\Debug\Exception\FatalErrorException))
#5 [internal function]: I in /var/www/Cachet/vendor/graham-campbell/exceptions/src/ExceptionIdentifier.php on line 51

**Comment by jbrooksuk** [comment]
You need to use PHP 7.2.

**Comment by AstroHost** [comment]
Thank you, we are / have been. We have also upgraded to v4 and still no luck.
