### ISSUE TITLE
Updates on components alert subscribers even when the status is unchanged in 2.3.x

### ISSUE THREAD

**Issue by aiso-net** [CachetHQ/Cachet#3977]
This was fixed in https://github.com/CachetHQ/Cachet/commit/b40066b

I'm using 2.3.18 and i'm having this issue, any fix for this in the 2.3 branch? Unless 2.4 is stable for production, then what is the upgrade procedure from 2.3.18 to 2.4.x?

_Originally posted by @jbrooksuk in https://github.com/CachetHQ/Cachet/issues/2683#issuecomment-333300619_

**Comment by jbrooksuk** [comment]
Thank you for your input on Cachet 2.x. We are shifting our attention and resources to Cachet 3.x and will no longer be supporting the 2.x version. If your feedback or issue is relevant to the 3.x series, we encourage you to engage with the new branch.

For more information on the Cachet rebuild and our plans for 3.x, you can read the announcement [here](https://github.com/CachetHQ/Cachet/discussions/4342).

We appreciate your understanding and look forward to your contributions to the new version.
