### ISSUE TITLE
Windows Xampp blank page after install

### ISSUE THREAD

**Issue by glewe** [CachetHQ/Cachet#3978]
Hi guys,

I checked the other issues about the plank page problem but could not find help there.

I am using Windows and Xampp, PHP 7.4.1, MySQL. I did the installation by the book with composer and artisan. MySQL runs and DB "cachet" exists. mod_rewrite is on.

What I did not do is adding the vhost in httpd-vhosts.conf. Whatever I tried to enter there made Apache stop with no error telling me why.

When pointing to localhost/cachet/public it redirects to localhost/cachet/public/setup, then plank page.

Any ideas?

Brgds,
George

**Comment by jbrooksuk** [comment]
Thank you for your input on Cachet 2.x. We are shifting our attention and resources to Cachet 3.x and will no longer be supporting the 2.x version. If your feedback or issue is relevant to the 3.x series, we encourage you to engage with the new branch.

For more information on the Cachet rebuild and our plans for 3.x, you can read the announcement [here](https://github.com/CachetHQ/Cachet/discussions/4342).

We appreciate your understanding and look forward to your contributions to the new version.
