### ISSUE TITLE
Some systems are experiencing issues

### ISSUE THREAD

**Issue by yuvarajan1989k** [CachetHQ/Cachet#3987]
Hi,

I have installed cachethq directly on the vm instance. i received 2 incident and got resolved as well. However it shows that the "Some systems are experiencing issues". Any help to investigate deeper ?
I am using 2.4 version.

**Comment by maxhSoe** [comment]
Hey yuvar,

have you checked that all components are set to the status 'Operational'? You can check this by navigating to the Cachet dashboard. As soon as one system is not set to 'Operational' the message you mentioned will be displayed.

Cheers,
Max

**Comment by yuvarajan1989k** [comment]
Hi maxhSoe,

I dont have any components configured. I have used alerta (https://github.com/alerta/alerta-contrib/tree/master/plugins/cachet) plugin to update the cachethq.

**Comment by maxhSoe** [comment]
Oh, I haven't used any plugins yet. You could try to configure (but not display) a component and set its status to operational.

**Comment by yuvarajan1989k** [comment]
@maxhSoe 
i confirmed that all compoents are operational and component_group are operational. But still the status page "Some systems are experiencing issues". Please guide me on this.

**Comment by yuvarajan1989k** [comment]
Scenario:-

Components: Green
Compoenents_group: Green

Under past Incident section:-

there are 2 incident created:-
  - 1 incident was in failing state 
  - another incident was resolved.
(Note: Both incidents related to the same service.)

Dashboard status:- 
Showing Issues but Everything is Operational


is it possible to display status on the dashboard based on component and component_group, instead of incidents?

**Comment by ygwane** [comment]
#2322

**Comment by jbrooksuk** [comment]
Thank you for your input on Cachet 2.x. We are shifting our attention and resources to Cachet 3.x and will no longer be supporting the 2.x version. If your feedback or issue is relevant to the 3.x series, we encourage you to engage with the new branch.

For more information on the Cachet rebuild and our plans for 3.x, you can read the announcement [here](https://github.com/CachetHQ/Cachet/discussions/4342).

We appreciate your understanding and look forward to your contributions to the new version.
