### ISSUE TITLE
Sticky and non-sticky incidents behavior incorrect

### ISSUE THREAD

**Issue by susingh02** [CachetHQ/Cachet#3988]
Case 1:

Under Settings,
  checkbox for "Only show days containing incidents in the timeline?" is SELECTED
  How many days of incidents to show?  = 7

A total of seven incidents were created today:
- 4 sticky
- 3 non-sticky

The 4 sticky ones show under "Stickied Incidents”

Nothing shows under "Past Incidents"

Question : Why non-sticky incidents are not showing anywhere?

Case 2: 
Under Settings,
  checkbox for "Only show days containing incidents in the timeline?" is NOT SELECTED
  How many days of incidents to show? = 7

A total of seven incidents were created today:
- 4 sticky
- 3 non-sticky

The 4 sticky ones show under "Stickied Incidents"

All 7 show under "Past Incidents"

Question : Why sticky one shows under both sections?

**Comment by jbrooksuk** [comment]
Thank you for your input on Cachet 2.x. We are shifting our attention and resources to Cachet 3.x and will no longer be supporting the 2.x version. If your feedback or issue is relevant to the 3.x series, we encourage you to engage with the new branch.

For more information on the Cachet rebuild and our plans for 3.x, you can read the announcement [here](https://github.com/CachetHQ/Cachet/discussions/4342).

We appreciate your understanding and look forward to your contributions to the new version.
