### ISSUE TITLE
Issue when installing

### ISSUE THREAD

**Issue by KnuffelBeestje** [CachetHQ/Cachet#3990]
Okay so, I have installed Cachet successfully and I just need to start the setup process.
But when I visit the URL I just get index.php printed.
You can see if for yourself here: [status.thundernetwork.nl](status.thundernetwork.nl)

I have enabled mod_rewrite because I'm using Apache.
The VPS is running on Ubuntu 18.04.
I've installed Cachet to: /var/www/Cachet
Here's the VirtualHost file: https://gist.github.com/KnuffelBeestje/52a869d4512d73f1f2d2d8dfb0e5de38
I'm using port 8880 instead of 80 for testing. When I visit using my IP & port 8880 I still get the same issue.

Maybe I have missed something?

**Comment by nalysius** [comment]
I am not able to access to your URL. I tried `http://status.thundernetwork.nl:8880` and `104.24.98.52:8880` but the best I had was blank page. Please fix the link in your first comment.
So I don't see what error you get.
Could you post here the error you get so we have the informations we need?

**Comment by KnuffelBeestje** [comment]
Sorry, I'm not longer using Cachet because I got rid of my server.
Going to close this now.
