### ISSUE TITLE
"Current" incidents are not displayed in an intuitive manner

### ISSUE THREAD

**Issue by cwross** [CachetHQ/Cachet#3998]
Hi, I am running Cachet 2.4.0-dev on FreeBSD 12.-1 with PHP 7.4 and using SQLite3 as the database. 

Everything is working wonderfully, but for some reason, when a new incident is created and the "Only show days containing incidents in the timeline?" option is checked in the settings, new incidents will not appear on the main status page _at all_ until they are about 3 or 4 hours old, at which point they show up under "Past Incidents." (They will show up if you set them as a "Stickied Incident")

If you uncheck the "Only show days containing incidents in the timeline?" option in settings, then they immediately show up under "Past Incidents."

Both behaviors seem very counter-intuitive to me. In the first case, the incident not appearing at all is super confusing to users: They wonder, "Why is a component marked as having an outage, but I see no current incidents?" 

In the second case, a user looking for an explanation to an ongoing situation would not find it intuitive to look under "Past Incidents" for something that is occurring now.

Shouldn't there be a "Current Incidents" section that lists any open incidents that haven't been marked as "Fixed"?

**Comment by stephancasas** [comment]
My understanding of the "stickied incidents" section was that it was intended to be used as a "current incidents" category.

To me, the deficiency is having the stickied section so far down the page. I added some JS in the footer customization to move it underneath the overall status and then only display the latest update per incident. Maybe something similar will work for you?

```
// move status overview to after page description
let custom_status = document.querySelector('.section-status');
custom_status.remove();
let custom_about = document.querySelector('.about-app');
custom_about.parentNode.insertBefore(custom_status, custom_about.nextSibling);

// move scheduled maintenance to after status overview
let custom_maint = document.querySelector('.section-scheduled');
if (custom_maint !== null) {
    custom_maint.remove();
    custom_status.parentNode.insertBefore(custom_maint, custom_status.nextSibling);
}

/* re-format ongoing incidents */
let custom_ongoing = document.querySelector('.section-stickied');
if (custom_ongoing !== null) {
    // remove date headers
    let custom_ogDates = [...custom_ongoing.querySelectorAll('h4')];
    custom_ogDates.map(d => { d.remove() });

    // remove all but latest update
    let custom_timelines = [...custom_ongoing.querySelectorAll('.timeline')];
    custom_timelines.map(custom_tl => {
        custom_incUpdates = [...custom_tl.querySelectorAll('.incident-update-item')];
        if (!custom_incUpdates) return;
        custom_incUpdates.map((custom_update, i) => {
            if (i === 0) return;
            custom_update.remove();
        });
    });

    // move ongoing incidents to after status overview
    custom_ongoing.remove();
    custom_status.parentNode.insertBefore(custom_ongoing, custom_status.nextSibling);
}
```

**Comment by nalysius** [comment]
Hi,
I tried to install Cachet 2.4~dev (c7ad51e87645e5a717fb817616424276a8e5345b) with Sqlite, I set the configuration about showing only the days with incidents, and I created an incident. It was immediately visible on the status page, under "Past Incidents".
If I understand well, your problem is the incident does not appear at all during 3-4 hours. It might be a caching issue, hard to know. Do you have more informations to reproduce it?

**Comment by cwross** [comment]
Correct - new incidents don't show up for several hours after they are added when the option to only show days with incidents is checked. I tried clearing the cache, but it made no difference.

**Comment by jbrooksuk** [comment]
Thank you for your input on Cachet 2.x. We are shifting our attention and resources to Cachet 3.x and will no longer be supporting the 2.x version. If your feedback or issue is relevant to the 3.x series, we encourage you to engage with the new branch.

For more information on the Cachet rebuild and our plans for 3.x, you can read the announcement [here](https://github.com/CachetHQ/Cachet/discussions/4342).

We appreciate your understanding and look forward to your contributions to the new version.
