### ISSUE TITLE
Metrics

### ISSUE THREAD

**Issue by jbrooksuk** [cachethq/Cachet#4]
Displaying graphs of incidents per day could be useful for the more visually-inclined. [Chart.js](/nnnick/Chart.js) is super easy to use and produces sweet charts.

**Comment by joecohens** [comment]
Do we know which graphs we want to display?

**Comment by GrahamCampbell** [comment]
Maybe a moving average for uptime would be cool, where we can change the number of points to include?

**Comment by jbrooksuk** [comment]
@joecohens it's up to the admin of the page to add metrics, they can activate the chart for it if they'd like.

@GrahamCampbell yeah I was thinking the same thing as a default chart.
