### ISSUE TITLE
Split up "Enable Third Party Dependencies"

### ISSUE THREAD

**Issue by nijel** [CachetHQ/Cachet#4002]
Right now "Enable Third Party Dependencies" is all or nothing, what might be not the best choice in some setups. For example, the trackers are already configured separately and not included unless configured, so this is additional thing to toggle to enable them. On the other side it pulls also other things.

What I'd like to do is using Matomo tracker (as that is not really third party as it's operated by me), but avoid fetching font from Google (as this actually is a third party).

**Comment by jbrooksuk** [comment]
Thank you for your input on Cachet 2.x. We are shifting our attention and resources to Cachet 3.x and will no longer be supporting the 2.x version. If your feedback or issue is relevant to the 3.x series, we encourage you to engage with the new branch.

For more information on the Cachet rebuild and our plans for 3.x, you can read the announcement [here](https://github.com/CachetHQ/Cachet/discussions/4342).

We appreciate your understanding and look forward to your contributions to the new version.
