### ISSUE TITLE
Show relative timestamps for incident updates

### ISSUE THREAD

**Issue by nijel** [CachetHQ/Cachet#4007]
In most cases the interesting information for past incidents is how fast they have been resolved. Right now Cachet displays ... ago instead of the timestamp, what is quite useless for things more in the past. You see that incident was created at some time, but updates are shown as "3 days later".

Instead, I'd like to see "3 minutes later" as the human-readable timestamp. That makes the important information visible on the first look.

**Comment by maxhSoe** [comment]
It does show the full event time when you hover over the ".... days ago"

**Comment by nijel** [comment]
It indeed does, but I still think it's useful to show the thing which is interesting to user on the page rather than forcing user to hover and compare the timestamps. On the other side, the days ago is useless unless the incident took days to resolve.

**Comment by jbrooksuk** [comment]
Thank you for your input on Cachet 2.x. We are shifting our attention and resources to Cachet 3.x and will no longer be supporting the 2.x version. If your feedback or issue is relevant to the 3.x series, we encourage you to engage with the new branch.

For more information on the Cachet rebuild and our plans for 3.x, you can read the announcement [here](https://github.com/CachetHQ/Cachet/discussions/4342).

We appreciate your understanding and look forward to your contributions to the new version.
