### ISSUE TITLE
Scheduled maintenance doesn't show on Dashboard if completion date is filled out

### ISSUE THREAD

**Issue by Quafi** [CachetHQ/Cachet#4011]
We often have scheduled maintenances from which we'll know in advance at what time they'll be finished.
However, when filling this time out in cachet, the maintenance won't show up in the dashboard at all.

**Comment by Oxima69** [comment]
Same problem here.
Any solution ?

thanks

**Comment by Quafi** [comment]
I wasn't able to solve this and, because of even more issues (like lack of integration with monitoring services, not being able to configure email and many more) I had with cachet, dodged the software completely now.

**Comment by jamesfryer** [comment]
What did you use instead? Having same problems -- cachet was great back in 2015 but seems to be hopelessly buggy now.

**Comment by anthosz** [comment]
@Quafi same question, what are you using now to replace Cachet?

**Comment by Quafi** [comment]
Hey @anthosz & @jamesfryer, sorry for the late response. I'm now using Statping and had great experience with it. It has many more features, runs very smooth and I had zero issues with it so far. Check it out: https://github.com/statping/statping
