### ISSUE TITLE
Feature Request: API able to create and not only view

### ISSUE THREAD

**Issue by denis-ev** [CachetHQ/Cachet#4012]
I'm a Dev with https://gitlab.com/NickBusey/HomelabOS and I'd like to add Cachet, but my main Problem is that all those services would need to be created within Cachet, I would rather create them via an API and combine that with a script or even ansible.

**Comment by jbrooksuk** [comment]
Thank you for your input on Cachet 2.x. We are shifting our attention and resources to Cachet 3.x and will no longer be supporting the 2.x version. If your feedback or issue is relevant to the 3.x series, we encourage you to engage with the new branch.

For more information on the Cachet rebuild and our plans for 3.x, you can read the announcement [here](https://github.com/CachetHQ/Cachet/discussions/4342).

We appreciate your understanding and look forward to your contributions to the new version.
