### ISSUE TITLE
Internal Server Error 500

### ISSUE THREAD

**Issue by Mittin-Singh** [CachetHQ/Cachet#4014]
I am using docker-compose to run v2.3.14 and it throws me an error. i also provided AppKey in docker-compose.yml file. Please suggest how to resolve this issue.

Something went wrong on our servers while we were processing your request. An error has occurred and this resource cannot be displayed. This occurrence has been logged, and a highly trained team of monkeys has been dispatched to deal with your problem. We're really sorry about this, and will work hard to get this resolved as soon as possible.

This error can be identified by e5a30775-6e51-4ff0-8c7a-8871b24b16df. You might want to take a note of this code.

Perhaps you would like to go to our home page?

**Comment by Mittin-Singh** [comment]
Attaching to cachet_23_cachet_1, cachet_23_postgres_1
[33mpostgres_1  |[0m The files belonging to this database system will be owned by user "postgres".
[33mpostgres_1  |[0m This user must also own the server process.
[33mpostgres_1  |[0m 
[33mpostgres_1  |[0m The database cluster will be initialized with locale "en_US.utf8".
[33mpostgres_1  |[0m The default database encoding has accordingly been set to "UTF8".
[33mpostgres_1  |[0m The default text search configuration will be set to "english".
[33mpostgres_1  |[0m Data page checksums are disabled.
[33mpostgres_1  |[0m fixing permissions on existing directory /var/lib/postgresql/data ... ok
[33mpostgres_1  |[0m creating subdirectories ... ok
[33mpostgres_1  |[0m selecting default max_connections ... 100
[33mpostgres_1  |[0m selecting default shared_buffers ... 128MB
[33mpostgres_1  |[0m selecting default timezone ... Etc/UTC
[33mpostgres_1  |[0m selecting dynamic shared memory implementation ... posix
[33mpostgres_1  |[0m creating configuration files ... ok
[33mpostgres_1  |[0m creating template1 database in /var/lib/postgresql/data/base/1 ... ok
[33mpostgres_1  |[0m initializing pg_authid ... ok
[33mpostgres_1  |[0m setting password ... ok
[33mpostgres_1  |[0m initializing dependencies ... ok
[33mpostgres_1  |[0m creating system views ... ok
[33mpostgres_1  |[0m loading system objects' descriptions ... ok
[33mpostgres_1  |[0m creating collations ... ok
[33mpostgres_1  |[0m creating conversions ... ok
[33mpostgres_1  |[0m creating dictionaries ... ok
[33mpostgres_1  |[0m setting privileges on built-in objects ... ok
[33mpostgres_1  |[0m creating information schema ... ok
[33mpostgres_1  |[0m loading PL/pgSQL server-side language ... ok
[33mpostgres_1  |[0m vacuuming database template1 ... ok
[33mpostgres_1  |[0m copying template1 to template0 ... ok
[33mpostgres_1  |[0m copying template1 to postgres ... ok
[33mpostgres_1  |[0m WARNING: enabling "trust" authentication for local connections
[33mpostgres_1  |[0m You can change this by editing pg_hba.conf or using the option -A, or
[33mpostgres_1  |[0m --auth-local and --auth-host, the next time you run initdb.
[33mpostgres_1  |[0m syncing data to disk ... ok
[33mpostgres_1  |[0m Success. You can now start the database server using:
[33mpostgres_1  |[0m     pg_ctl -D /var/lib/postgresql/data -l logfile start
[33mpostgres_1  |[0m waiting for server to start....LOG:  database system was shut down at 2020-05-08 06:40:23 UTC
[33mpostgres_1  |[0m LOG:  MultiXact member wraparound protections are now enabled
[33mpostgres_1  |[0m LOG:  database system is ready to accept connections
[33mpostgres_1  |[0m LOG:  autovacuum launcher started
[33mpostgres_1  |[0m  done
[33mpostgres_1  |[0m server started
[33mpostgres_1  |[0m /usr/local/bin/docker-entrypoint.sh: ignoring /docker-entrypoint-initdb.d/*
[33mpostgres_1  |[0m LOG:  received fast shutdown request
[33mpostgres_1  |[0m waiting for server to shut down....LOG:  aborting any active transactions
[33mpostgres_1  |[0m LOG:  autovacuum launcher shutting down
[33mpostgres_1  |[0m LOG:  shutting down
[33mpostgres_1  |[0m LOG:  database system is shut down
[33mpostgres_1  |[0m server stopped
[33mpostgres_1  |[0m PostgreSQL init process complete; ready for start up.
[33mpostgres_1  |[0m LOG:  database system was shut down at 2020-05-08 06:40:26 UTC
[33mpostgres_1  |[0m LOG:  received smart shutdown request
[33mpostgres_1  |[0m PostgreSQL Database directory appears to contain a database; Skipping initialization
[33mpostgres_1  |[0m LOG:  database system was shut down at 2020-05-08 06:40:52 UTC
[33mpostgres_1  |[0m ERROR:  relation "chq_settings" does not exist at character 29
[33mpostgres_1  |[0m STATEMENT:  select "name", "value" from "chq_settings"
[33mpostgres_1  |[0m LOG:  database system was shut down at 2020-05-08 07:00:44 UTC
[36mcachet_1    |[0m Initializing Cachet container ...
[36mcachet_1    |[0m Attempting to connect to database ...
[36mcachet_1    |[0m 
[36mcachet_1    |[0m Table chq_sessions exists! ...
[36mcachet_1    |[0m Nothing to migrate.
[36mcachet_1    |[0m Starting Cachet! ...
[36mcachet_1    |[0m Configuration cache cleared!
[36mcachet_1    |[0m Configuration cached successfully!
[36mcachet_1    |[0m 2020-05-08 07:00:56,892 WARN For [program:queue-worker], AUTO logging used for stderr_logfile without rollover, set maxbytes > 0 to avoid filling up filesystem unintentionally
[36mcachet_1    |[0m 2020-05-08 07:00:56,896 INFO supervisord started with pid 60
[36mcachet_1    |[0m 2020-05-08 07:00:57,901 INFO spawned: 'nginx' with pid 63
[36mcachet_1    |[0m 2020-05-08 07:00:57,908 INFO spawned: 'php-fpm' with pid 64
[36mcachet_1    |[0m 2020-05-08 07:00:57,914 INFO spawned: 'queue-worker' with pid 65
[36mcachet_1    |[0m [08-May-2020 07:00:58] NOTICE: fpm is running, pid 64
[36mcachet_1    |[0m [08-May-2020 07:00:58] NOTICE: ready to handle connections
[36mcachet_1    |[0m 2020-05-08 07:00:59,094 INFO success: nginx entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
[36mcachet_1    |[0m 2020-05-08 07:00:59,094 INFO success: php-fpm entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
[36mcachet_1    |[0m 2020-05-08 07:00:59,094 INFO success: queue-worker entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
[36mcachet_1    |[0m [08-May-2020 07:01:16] WARNING: [pool www] child 73 said into stderr: "NOTICE: PHP message: [2020-05-08 07:01:16] development.CRITICAL: Symfony\Component\Debug\Exception\FatalThrowableError: Type error: Too few arguments to function Illuminate\Support\Manager::createDriver(), 0 passed in /var/www/html/vendor/laravel/framework/src/Illuminate/Support/Manager.php on line 87 and exactly 1 expected in /var/www/html/vendor/laravel/framework/src/Illuminate/Support/Manager.php:77"
[36mcachet_1    |[0m [08-May-2020 07:01:16] WARNING: [pool www] child 73 said into stderr: "Stack trace:"
[36mcachet_1    |[0m [08-May-2020 07:01:16] WARNING: [pool www] child 73 said into stderr: "#0 /var/www/html/vendor/laravel/framework/src/Illuminate/Support/Manager.php(87): Illuminate\Support\Manager->createDriver()"
[36mcachet_1    |[0m [08-May-2020 07:01:16] WARNING: [pool www] child 73 said into stderr: "#1 /var/www/html/vendor/laravel/framework/src/Illuminate/Support/Manager.php(63): Illuminate\Support\Manager->createDriver('')"
[36mcachet_1    |[0m [08-May-2020 07:01:16] WARNING: [pool www] child 73 said into stderr: "#2 /var/www/html/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(117): Illuminate\Support\Manager->driver()"
[36mcachet_1    |[0m [08-May-2020 07:01:16] WARNING: [pool www] child 73 said into stderr: "#3 /var/www/html/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(100): Illuminate\Session\Middleware\StartSession->getSession(Object(Illuminate\Http\Request))"
[36mcachet_1    |[0m [08-May-2020 07:01:16] WARNING: [pool www] child 73 said into stderr: "#4 /var/www/html/vendor/la..."
[36mcachet_1    |[0m 2020/05/08 07:01:16 [error] 66#66: *1 FastCGI sent in stderr: "PHP message: [2020-05-08 07:01:16] development.CRITICAL: Symfony\Component\Debug\Exception\FatalThrowableError: Type error: Too few arguments to function Illuminate\Support\Manager::createDriver(), 0 passed in /var/www/html/vendor/laravel/framework/src/Illuminate/Support/Manager.php on line 87 and exactly 1 expected in /var/www/html/vendor/laravel/framework/src/Illuminate/Support/Manager.php:77
[36mcachet_1    |[0m Stack trace:
[36mcachet_1    |[0m #0 /var/www/html/vendor/laravel/framework/src/Illuminate/Support/Manager.php(87): Illuminate\Support\Manager->createDriver()
[36mcachet_1    |[0m #1 /var/www/html/vendor/laravel/framework/src/Illuminate/Support/Manager.php(63): Illuminate\Support\Manager->createDriver('')
[36mcachet_1    |[0m #2 /var/www/html/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(117): Illuminate\Support\Manager->driver()
[36mcachet_1    |[0m #3 /var/www/html/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(100): Illuminate\Session\Middleware\StartSession->getSession(Object(Illuminate\Http\Request))
[36mcachet_1    |[0m #4 /var/www/html/vendor/laravel/fr" while reading response header from upstream, client: 192.168.16.1, server: localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "localhost:8001"
[36mcachet_1    |[0m 192.168.16.1 - - [08/May/2020:07:01:16 +0000] "GET / HTTP/1.1" 500 3175 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.138 Safari/537.36" "-"
[36mcachet_1    |[0m [08-May-2020 07:01:16] WARNING: [pool www] child 73 said into stderr: "#2 /var/www/html/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(245): Illuminate\Support\Manager->driver()"
[36mcachet_1    |[0m [08-May-2020 07:01:16] WARNING: [pool www] child 73 said into stderr: "#3 /var/www/html/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(87): Illuminate\Session\Middleware\StartSession->usingCookieSessions()"
[36mcachet_1    |[0m [08-May-2020 07:01:16] WARNING: [pool www] child 73 said into stderr: "#4 /var/www/html/vendor/laravel/framework/src/Ill..."
[36mcachet_1    |[0m [08-May-2020 07:01:19] WARNING: [pool www] child 73 said into stderr: "NOTICE: PHP message: [2020-05-08 07:01:19] development.CRITICAL: Symfony\Component\Debug\Exception\FatalThrowableError: Type error: Too few arguments to function Illuminate\Support\Manager::createDriver(), 0 passed in /var/www/html/vendor/laravel/framework/src/Illuminate/Support/Manager.php on line 87 and exactly 1 expected in /var/www/html/vendor/laravel/framework/src/Illuminate/Support/Manager.php:77"
[36mcachet_1    |[0m [08-May-2020 07:01:19] WARNING: [pool www] child 73 said into stderr: "Stack trace:"
[36mcachet_1    |[0m [08-May-2020 07:01:19] WARNING: [pool www] child 73 said into stderr: "#0 /var/www/html/vendor/laravel/framework/src/Illuminate/Support/Manager.php(87): Illuminate\Support\Manager->createDriver()"
[36mcachet_1    |[0m [08-May-2020 07:01:19] WARNING: [pool www] child 73 said into stderr: "#1 /var/www/html/vendor/laravel/framework/src/Illuminate/Support/Manager.php(63): Illuminate\Support\Manager->createDriver('')"
[36mcachet_1    |[0m [08-May-2020 07:01:19] WARNING: [pool www] child 73 said into stderr: "#2 /var/www/html/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(117): Illuminate\Support\Manager->driver()"
[36mcachet_1    |[0m [08-May-2020 07:01:19] WARNING: [pool www] child 73 said into stderr: "#3 /var/www/html/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(100): Illuminate\Session\Middleware\StartSession->getSession(Object(Illuminate\Http\Request))"
[36mcachet_1    |[0m [08-May-2020 07:01:19] WARNING: [pool www] child 73 said into stderr: "#4 /var/www/html/vendor/la..."
[36mcachet_1    |[0m 2020/05/08 07:01:19 [error] 66#66: *1 FastCGI sent in stderr: "PHP message: [2020-05-08 07:01:19] development.CRITICAL: Symfony\Component\Debug\Exception\FatalThrowableError: Type error: Too few arguments to function Illuminate\Support\Manager::createDriver(), 0 passed in /var/www/html/vendor/laravel/framework/src/Illuminate/Support/Manager.php on line 87 and exactly 1 expected in /var/www/html/vendor/laravel/framework/src/Illuminate/Support/Manager.php:77
[36mcachet_1    |[0m 192.168.16.1 - - [08/May/2020:07:01:19 +0000] "GET / HTTP/1.1" 500 3175 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.138 Safari/537.36" "-"
[36mcachet_1    |[0m [08-May-2020 07:01:19] WARNING: [pool www] child 73 said into stderr: "#2 /var/www/html/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(245): Illuminate\Support\Manager->driver()"
[36mcachet_1    |[0m [08-May-2020 07:01:19] WARNING: [pool www] child 73 said into stderr: "#3 /var/www/html/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(87): Illuminate\Session\Middleware\StartSession->usingCookieSessions()"
[36mcachet_1    |[0m [08-May-2020 07:01:19] WARNING: [pool www] child 73 said into stderr: "#4 /var/www/html/vendor/laravel/framework/src/Ill..."
[36mcachet_1    |[0m [08-May-2020 07:07:58] WARNING: [pool www] child 74 said into stderr: "NOTICE: PHP message: [2020-05-08 07:07:58] development.CRITICAL: Symfony\Component\Debug\Exception\FatalThrowableError: Type error: Too few arguments to function Illuminate\Support\Manager::createDriver(), 0 passed in /var/www/html/vendor/laravel/framework/src/Illuminate/Support/Manager.php on line 87 and exactly 1 expected in /var/www/html/vendor/laravel/framework/src/Illuminate/Support/Manager.php:77"
[36mcachet_1    |[0m [08-May-2020 07:07:58] WARNING: [pool www] child 74 said into stderr: "Stack trace:"
[36mcachet_1    |[0m [08-May-2020 07:07:58] WARNING: [pool www] child 74 said into stderr: "#0 /var/www/html/vendor/laravel/framework/src/Illuminate/Support/Manager.php(87): Illuminate\Support\Manager->createDriver()"
[36mcachet_1    |[0m [08-May-2020 07:07:58] WARNING: [pool www] child 74 said into stderr: "#1 /var/www/html/vendor/laravel/framework/src/Illuminate/Support/Manager.php(63): Illuminate\Support\Manager->createDriver('')"
[36mcachet_1    |[0m [08-May-2020 07:07:58] WARNING: [pool www] child 74 said into stderr: "#2 /var/www/html/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(117): Illuminate\Support\Manager->driver()"
[36mcachet_1    |[0m [08-May-2020 07:07:58] WARNING: [pool www] child 74 said into stderr: "#3 /var/www/html/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(100): Illuminate\Session\Middleware\StartSession->getSession(Object(Illuminate\Http\Request))"
[36mcachet_1    |[0m [08-May-2020 07:07:58] WARNING: [pool www] child 74 said into stderr: "#4 /var/www/html/vendor/la..."
[36mcachet_1    |[0m 2020/05/08 07:07:58 [error] 66#66: *6 FastCGI sent in stderr: "PHP message: [2020-05-08 07:07:58] development.CRITICAL: Symfony\Component\Debug\Exception\FatalThrowableError: Type error: Too few arguments to function Illuminate\Support\Manager::createDriver(), 0 passed in /var/www/html/vendor/laravel/framework/src/Illuminate/Support/Manager.php on line 87 and exactly 1 expected in /var/www/html/vendor/laravel/framework/src/Illuminate/Support/Manager.php:77
[36mcachet_1    |[0m 192.168.16.1 - - [08/May/2020:07:07:58 +0000] "GET / HTTP/1.1" 500 3175 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.138 Safari/537.36" "-"
[36mcachet_1    |[0m [08-May-2020 07:07:58] WARNING: [pool www] child 74 said into stderr: "#2 /var/www/html/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(245): Illuminate\Support\Manager->driver()"
[36mcachet_1    |[0m [08-May-2020 07:07:58] WARNING: [pool www] child 74 said into stderr: "#3 /var/www/html/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(87): Illuminate\Session\Middleware\StartSession->usingCookieSessions()"
[36mcachet_1    |[0m [08-May-2020 07:07:58] WARNING: [pool www] child 74 said into stderr: "#4 /var/www/html/vendor/laravel/framework/src/Ill..."
[36mcachet_1    |[0m [08-May-2020 07:08:00] WARNING: [pool www] child 74 said into stderr: "NOTICE: PHP message: [2020-05-08 07:08:00] development.CRITICAL: Symfony\Component\Debug\Exception\FatalThrowableError: Type error: Too few arguments to function Illuminate\Support\Manager::createDriver(), 0 passed in /var/www/html/vendor/laravel/framework/src/Illuminate/Support/Manager.php on line 87 and exactly 1 expected in /var/www/html/vendor/laravel/framework/src/Illuminate/Support/Manager.php:77"
[36mcachet_1    |[0m [08-May-2020 07:08:00] WARNING: [pool www] child 74 said into stderr: "Stack trace:"
[36mcachet_1    |[0m [08-May-2020 07:08:00] WARNING: [pool www] child 74 said into stderr: "#0 /var/www/html/vendor/laravel/framework/src/Illuminate/Support/Manager.php(87): Illuminate\Support\Manager->createDriver()"
[36mcachet_1    |[0m [08-May-2020 07:08:00] WARNING: [pool www] child 74 said into stderr: "#1 /var/www/html/vendor/laravel/framework/src/Illuminate/Support/Manager.php(63): Illuminate\Support\Manager->createDriver('')"
[36mcachet_1    |[0m [08-May-2020 07:08:00] WARNING: [pool www] child 74 said into stderr: "#2 /var/www/html/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(117): Illuminate\Support\Manager->driver()"
[36mcachet_1    |[0m [08-May-2020 07:08:00] WARNING: [pool www] child 74 said into stderr: "#3 /var/www/html/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(100): Illuminate\Session\Middleware\StartSession->getSession(Object(Illuminate\Http\Request))"
[36mcachet_1    |[0m [08-May-2020 07:08:00] WARNING: [pool www] child 74 said into stderr: "#4 /var/www/html/vendor/la..."
[36mcachet_1    |[0m 2020/05/08 07:08:00 [error] 66#66: *6 FastCGI sent in stderr: "PHP message: [2020-05-08 07:08:00] development.CRITICAL: Symfony\Component\Debug\Exception\FatalThrowableError: Type error: Too few arguments to function Illuminate\Support\Manager::createDriver(), 0 passed in /var/www/html/vendor/laravel/framework/src/Illuminate/Support/Manager.php on line 87 and exactly 1 expected in /var/www/html/vendor/laravel/framework/src/Illuminate/Support/Manager.php:77
[36mcachet_1    |[0m [08-May-2020 07:08:00] WARNING: [pool www] child 74 said into stderr: "#2 /var/www/html/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(245): Illuminate\Support\Manager->driver()"
[36mcachet_1    |[0m [08-May-2020 07:08:00] WARNING: [pool www] child 74 said into stderr: "#3 /var/www/html/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(87): Illuminate\Session\Middleware\StartSession->usingCookieSessions()"
[36mcachet_1    |[0m [08-May-2020 07:08:00] WARNING: [pool www] child 74 said into stderr: "#4 /var/www/html/vendor/laravel/framework/src/Ill..."
[36mcachet_1    |[0m 192.168.16.1 - - [08/May/2020:07:08:00 +0000] "GET / HTTP/1.1" 500 3175 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.138 Safari/537.36" "-"
[36mcachet_1    |[0m [08-May-2020 07:08:02] WARNING: [pool www] child 74 said into stderr: "NOTICE: PHP message: [2020-05-08 07:08:02] development.CRITICAL: Symfony\Component\Debug\Exception\FatalThrowableError: Type error: Too few arguments to function Illuminate\Support\Manager::createDriver(), 0 passed in /var/www/html/vendor/laravel/framework/src/Illuminate/Support/Manager.php on line 87 and exactly 1 expected in /var/www/html/vendor/laravel/framework/src/Illuminate/Support/Manager.php:77"
[36mcachet_1    |[0m [08-May-2020 07:08:02] WARNING: [pool www] child 74 said into stderr: "Stack trace:"
[36mcachet_1    |[0m [08-May-2020 07:08:02] WARNING: [pool www] child 74 said into stderr: "#0 /var/www/html/vendor/laravel/framework/src/Illuminate/Support/Manager.php(87): Illuminate\Support\Manager->createDriver()"
[36mcachet_1    |[0m [08-May-2020 07:08:02] WARNING: [pool www] child 74 said into stderr: "#1 /var/www/html/vendor/laravel/framework/src/Illuminate/Support/Manager.php(63): Illuminate\Support\Manager->createDriver('')"
[36mcachet_1    |[0m [08-May-2020 07:08:02] WARNING: [pool www] child 74 said into stderr: "#2 /var/www/html/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(117): Illuminate\Support\Manager->driver()"
[36mcachet_1    |[0m [08-May-2020 07:08:02] WARNING: [pool www] child 74 said into stderr: "#3 /var/www/html/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(100): Illuminate\Session\Middleware\StartSession->getSession(Object(Illuminate\Http\Request))"
[36mcachet_1    |[0m [08-May-2020 07:08:02] WARNING: [pool www] child 74 said into stderr: "#4 /var/www/html/vendor/la..."
[36mcachet_1    |[0m 2020/05/08 07:08:02 [error] 66#66: *6 FastCGI sent in stderr: "PHP message: [2020-05-08 07:08:02] development.CRITICAL: Symfony\Component\Debug\Exception\FatalThrowableError: Type error: Too few arguments to function Illuminate\Support\Manager::createDriver(), 0 passed in /var/www/html/vendor/laravel/framework/src/Illuminate/Support/Manager.php on line 87 and exactly 1 expected in /var/www/html/vendor/laravel/framework/src/Illuminate/Support/Manager.php:77
[36mcachet_1    |[0m [08-May-2020 07:08:02] WARNING: [pool www] child 74 said into stderr: "#2 /var/www/html/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(245): Illuminate\Support\Manager->driver()"
[36mcachet_1    |[0m [08-May-2020 07:08:02] WARNING: [pool www] child 74 said into stderr: "#3 /var/www/html/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(87): Illuminate\Session\Middleware\StartSession->usingCookieSessions()"
[36mcachet_1    |[0m [08-May-2020 07:08:02] WARNING: [pool www] child 74 said into stderr: "#4 /var/www/html/vendor/laravel/framework/src/Ill..."
[36mcachet_1    |[0m 192.168.16.1 - - [08/May/2020:07:08:02 +0000] "GET / HTTP/1.1" 500 3175 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.138 Safari/537.36" "-"
[36mcachet_1    |[0m [08-May-2020 07:08:32] WARNING: [pool www] child 75 said into stderr: "NOTICE: PHP message: [2020-05-08 07:08:32] development.CRITICAL: Symfony\Component\Debug\Exception\FatalThrowableError: Type error: Too few arguments to function Illuminate\Support\Manager::createDriver(), 0 passed in /var/www/html/vendor/laravel/framework/src/Illuminate/Support/Manager.php on line 87 and exactly 1 expected in /var/www/html/vendor/laravel/framework/src/Illuminate/Support/Manager.php:77"
[36mcachet_1    |[0m [08-May-2020 07:08:32] WARNING: [pool www] child 75 said into stderr: "Stack trace:"
[36mcachet_1    |[0m [08-May-2020 07:08:32] WARNING: [pool www] child 75 said into stderr: "#0 /var/www/html/vendor/laravel/framework/src/Illuminate/Support/Manager.php(87): Illuminate\Support\Manager->createDriver()"
[36mcachet_1    |[0m [08-May-2020 07:08:32] WARNING: [pool www] child 75 said into stderr: "#1 /var/www/html/vendor/laravel/framework/src/Illuminate/Support/Manager.php(63): Illuminate\Support\Manager->createDriver('')"
[36mcachet_1    |[0m [08-May-2020 07:08:32] WARNING: [pool www] child 75 said into stderr: "#2 /var/www/html/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(117): Illuminate\Support\Manager->driver()"
[36mcachet_1    |[0m [08-May-2020 07:08:32] WARNING: [pool www] child 75 said into stderr: "#3 /var/www/html/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(100): Illuminate\Session\Middleware\StartSession->getSession(Object(Illuminate\Http\Request))"
[36mcachet_1    |[0m [08-May-2020 07:08:32] WARNING: [pool www] child 75 said into stderr: "#4 /var/www/html/vendor/la..."
[36mcachet_1    |[0m 2020/05/08 07:08:32 [error] 66#66: *6 FastCGI sent in stderr: "PHP message: [2020-05-08 07:08:32] development.CRITICAL: Symfony\Component\Debug\Exception\FatalThrowableError: Type error: Too few arguments to function Illuminate\Support\Manager::createDriver(), 0 passed in /var/www/html/vendor/laravel/framework/src/Illuminate/Support/Manager.php on line 87 and exactly 1 expected in /var/www/html/vendor/laravel/framework/src/Illuminate/Support/Manager.php:77
[36mcachet_1    |[0m 192.168.16.1 - - [08/May/2020:07:08:32 +0000] "GET / HTTP/1.1" 500 3175 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.138 Safari/537.36" "-"
[36mcachet_1    |[0m [08-May-2020 07:08:32] WARNING: [pool www] child 75 said into stderr: "#2 /var/www/html/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(245): Illuminate\Support\Manager->driver()"
[36mcachet_1    |[0m [08-May-2020 07:08:32] WARNING: [pool www] child 75 said into stderr: "#3 /var/www/html/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(87): Illuminate\Session\Middleware\StartSession->usingCookieSessions()"
[36mcachet_1    |[0m [08-May-2020 07:08:32] WARNING: [pool www] child 75 said into stderr: "#4 /var/www/html/vendor/laravel/framework/src/Ill..."

**Comment by tomck** [comment]
I believe this should be in the Docker project for Cachet. https://github.com/CachetHQ/Docker/issues

**Comment by Mittin-Singh** [comment]
Hi Tomck, is there any stable release for cachet 2.4, if not yet than when will be a suitable release we can expect from the community
