### ISSUE TITLE
Can we omit the $service_output message in nagios integration to cachet

### ISSUE THREAD

**Issue by habeebshk** [CachetHQ/Cachet#4015]
Hi, I am trying to integrate Nagios with my cachet installation and while testing i came to find that with any nagios rule it will also add a incident report on the status page, and i would like to know is there any way where i can omit this and only show the incident like warning and critical on the components table and not add an incident report below. 
I did go through the cachet_notify config and it seems like it is getting a http status code from the cachet server and is not creating any alert without it matching it.
![image](https://user-images.githubusercontent.com/36462909/81463936-9f75ca80-918b-11ea-8f34-e410d152442d.png)
and if the status code is not 200 then it is not creating the warning alert. 
![image](https://user-images.githubusercontent.com/36462909/81463950-bddbc600-918b-11ea-874a-e35e89c195e5.png)
 Is there any way i can change this, any advice would be helpful. Thanks

**Comment by jbrooksuk** [comment]
Thank you for your input on Cachet 2.x. We are shifting our attention and resources to Cachet 3.x and will no longer be supporting the 2.x version. If your feedback or issue is relevant to the 3.x series, we encourage you to engage with the new branch.

For more information on the Cachet rebuild and our plans for 3.x, you can read the announcement [here](https://github.com/CachetHQ/Cachet/discussions/4342).

We appreciate your understanding and look forward to your contributions to the new version.
