### ISSUE TITLE
Setup Page not loading/ seeing the index.php file

### ISSUE THREAD

**Issue by smilebasti** [CachetHQ/Cachet#4016]
Hi, i just tried installing Cachet but as everything worked on the setup i am now stuck at the point of opening the website of Cachet. 
I am at the website where i am just seeing the index.php file (attached picture) and not the setup page. My thought is that the composer is not loading in but i am not sure why? On the LXC where it installed it i also have Prometheus and Grafana running. And the LXC is running behind a Apache reverse Proxy with settings each other running server is working.

I hope you all can help me. Thanks ahead.
![Anmerkung 2020-05-07 191243](https://user-images.githubusercontent.com/60941345/81469539-bcd78280-91e5-11ea-8d3d-a08d3a0b81f9.png)

**Comment by syedimran1272** [comment]
What was the solution for this ? I got a similar issue

@jbrooksuk
