### ISSUE TITLE
Debian 7 Permission Issue

### ISSUE THREAD

**Issue by ApfelUser** [cachethq/Cachet#402]
Hi, I am getting this issue: [Cachet Installation](https://status.minora.me/)

Already changed ownership with **-R** to **www-data**, and have right now no clue why this error is occurring.

**Comment by jbrooksuk** [comment]
You need to run `chmod -R 777 ./app/storage`

**Comment by Finkregh** [comment]
making that directory world-writable should not even be the last resort... imho :fearful:

**Comment by jbrooksuk** [comment]
We have a [command](https://github.com/cachethq/Cachet/blob/master/src/Console/Commands/FixPermissionsCommand.php) which sets the permissions to `0755`.

**Comment by brianjking** [comment]
@jbrooksuk are you saying I need to run chmod -R 777 ./app/storage prior to executing git push heroku?

**Comment by brianjking** [comment]
This is what I'm getting when attempting to update... 

remote:        
remote:          - Installing watson/validating (0.10.6)
remote:            Loading from cache
remote:        
remote:        Generating optimized autoload files
remote:        Generating optimized class loader
remote:        Compiling common classes
remote:        Compiling views
remote:        
remote:        
remote:                                                                                                                                               
remote:          [UnexpectedValueException]                                                                                                           
remote:          DirectoryIterator::__construct(/tmp/build_b46768924e25a6d26abdf37bd113bee1/app/storage/meta): failed to open dir: Permission denied  
remote:                                                                                                                                               
remote:        
remote:        
remote:        cachet:chmod
remote:        
remote:        
remote:        Script php artisan cachet:chmod handling the post-install-cmd event returned with an error
remote: 
remote: 
remote:                                                                                                                                            
remote:   [RuntimeException]                                                                                                                       
remote:   Error Output:                                                                                                                            
remote:                                                                                                                                            
remote:     [UnexpectedValueException]                                                                                                             
remote:     DirectoryIterator::__construct(/tmp/build_b46768924e25a6d26abdf37bd113bee1/app/storage/meta): failed to open dir: Permission denied    
remote:                                                                                                                                            
remote:   cachet:chmod                                                                                                                             
remote:                                                                                                                                            
remote: 
remote: 
remote: install [--prefer-source] [--prefer-dist] [--dry-run] [--dev] [--no-dev] [--no-plugins] [--no-custom-installers] [--no-autoloader] [--no-scripts] [--no-progress] [-v|vv|vvv|--verbose] [-o|--optimize-autoloader] [--ignore-platform-reqs] [packages1] ... [packagesN]
remote: 
remote: 
remote: 
remote:  !     Push rejected, failed to compile PHP (composer.json) app
remote: 
remote: Verifying deploy...
remote: 
remote: !	Push rejected to dockdogsmonitor.
remote: 
To https://git.heroku.com/dockdogsmonitor.git
 ! [remote rejected] master -> master (pre-receive hook declined)
error: failed to push some refs to 'https://git.heroku.com/dockdogsmonitor.git'

**Comment by jbrooksuk** [comment]
Caused by needing to `chmod` the `./app/storage` directory.

**Comment by brianjking** [comment]
I did run this, no dice. The only issue I'm having on my current deployment is I cannot edit components. Thanks for your awesome support and great product...

**Comment by jbrooksuk** [comment]
Are you using SQLite?

**Comment by brianjking** [comment]
HEROKU_POSTGRESQL_SILVER_URL: postgres:

**Comment by jbrooksuk** [comment]
Oh right, that's not what I expected.

Do you get any errors when editing the component?

**Comment by jbrooksuk** [comment]
We did change migrations a few days back for the new tag system.
