### ISSUE TITLE
Getting 500 Error after install

### ISSUE THREAD

**Issue by adrijanb** [CachetHQ/Cachet#4021]
After the /setup, i am getting following error

http://paste.ubuntu.com/p/t8j73BpJwX/

**Comment by Perflyst** [comment]
I can reproduce this, happens here too

**Comment by bpstr** [comment]
`rm -rf bootstrap/cache/*` solved the problem for me [docs](https://docs.cachethq.io/docs/installing-cachet#using-the-install-command)

**Comment by adrijanb** [comment]
Did not help me

**Comment by andelhie** [comment]
I am getting close to the same error but on the setup page.  the delete of the cache did not help at all.

**Comment by hexathos** [comment]
same here

**Comment by JimboJoe** [comment]
Same here

**Comment by andelhie** [comment]
> Same here on Debian Buster with PHP 7.3 (working well on Debian Stretch with PHP 7.0).

Yes this is the problem I seen on CentOS PHP 7.3.  There is some sort of change to php.

What is the latest version of PHP Cachet supports?

**Comment by andelhie** [comment]
So I was able to get it all to work by reinstalling my system and only installing php 7.0 from remi.

There looks to be a problem with 7.4 and laravel that is being used.  There is a lot of chatter on the Laravel help threads.

**Comment by JimboJoe** [comment]
The issue is also reproduced on Debian Stretch, and installing/using PHP 7.3 via Sury repository.

**Comment by Superkooka** [comment]
Same problem

**Comment by Superkooka** [comment]
Juste downgrade your php version

**Comment by SugarD-x** [comment]
> Juste downgrade your php version
That's a bad decision. You're asking for security issues then. This should be fixed by the web application, not PHP.

**Comment by l3d00m** [comment]
You're kinda right @SugarD-x, but as far as I understood it this project isn't very actively maintained and therefore has set PHP<=7.1 as a requirement (in the Readme, docs are outdated as well).
