### ISSUE TITLE
504 Gateway timeout when running Cachet behind a firewall

### ISSUE THREAD

**Issue by backaf** [CachetHQ/Cachet#4023]
We're running Cachet in a restricted network, which has no outbound access by default. The Cachet installation uses the Docker container and nginx is used as a reverse proxy. 

When attempting to access the admin dashboard, after entering the credentials, most of the times the request times out and the following error is shows in the Cachet logs:

```
1.2.3.4 - - [11/May/2020:12:37:25 +0200] "GET /api/v1/version HTTP/1.1" 504 183 "https://status.company.com/dashboard" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:76.0) Gecko/20100101 Firefox/76.0"
```

Was not able to find any other relevant logs even when running with debug loglevel. Sometimes the login works, but the success rate is very low.

After analysing the outbound traffic, we realised Cachet tries to access the following domains/services:
* Github
* Twitter
* blog.alt-three.com

After allowing outbound access to these domains the login always works.

Is there any reason why these domains are needed for Cachet to work? We would prefer to limit outbound access.

**Comment by gusuu1** [comment]
I'm not sure but my guess would be:

* Github - Checking for updates
* Twitter - Social Media integration?
* blog.alt-three.com - Again, checking for updates? I believe this is the blog from the developer.

**Comment by backaf** [comment]
But this would be additional functionality, one which I could live without. The problem is this prevents a user from logging in which means Cachet can't be used at all.

**Comment by ljmsc** [comment]
I have the same issue. How can I disable these outgoing calls?

**Comment by gusuu1** [comment]
> I have the same issue. How can I disable these outgoing calls?

I don't think there is an official/supported way to disable these. Just modify the code yourself.

**Comment by aberhallo** [comment]
Hi, 

we faced the same issue and used the following workaround: if you are building your own image based on latest Cachet tag v2.3.18 you can patch some files: 

```
COPY fix/Credits.php /var/www/html/app/Integrations/Credits.php
COPY fix/Feed.php /var/www/html/app/Integrations/Feed.php
COPY fix/Releases.php /var/www/html/app/Integrations/Releases.php
```

[Get these files from the latest tag v2.3.18 ](https://github.com/CachetHQ/Cachet/tree/v2.3.18/app/Integrations) and replace the function `latest()` simply with this code in all files:

```
public function latest()
{
  return null;
}
```

Since we patched this the error did never occur anymore.

**Comment by jbrooksuk** [comment]
Thank you for your input on Cachet 2.x. We are shifting our attention and resources to Cachet 3.x and will no longer be supporting the 2.x version. If your feedback or issue is relevant to the 3.x series, we encourage you to engage with the new branch.

For more information on the Cachet rebuild and our plans for 3.x, you can read the announcement [here](https://github.com/CachetHQ/Cachet/discussions/4342).

We appreciate your understanding and look forward to your contributions to the new version.
