### ISSUE TITLE
Problem with authentication

### ISSUE THREAD

**Issue by OuFinx** [CachetHQ/Cachet#4033]
Hi, I installed the latest version of Cachet from Docker Hub (which was updated 11 days ago).
And figured out with the next problem.

Hi, I tried to install the previous versions (`2.3.15`, `2.3.14`, `2.3.13`) of Cachet from Docker Hub.
And figured out with the next problem.

- When I enter the admin panel (dashboard) and then open another browser with incognito and enter the site I will see that I already logged to the admin panel. It means all users can enter the admin panel if I already logged.

- If I logged off from the admin panel - nobody can enter the admin panel as should.

This issue has been fixed in the latest version. But I still can not use the latest version due to a problem [#4032](https://github.com/CachetHQ/Cachet/issues/4032)

**Comment by jbrooksuk** [comment]
Thank you for your input on Cachet 2.x. We are shifting our attention and resources to Cachet 3.x and will no longer be supporting the 2.x version. If your feedback or issue is relevant to the 3.x series, we encourage you to engage with the new branch.

For more information on the Cachet rebuild and our plans for 3.x, you can read the announcement [here](https://github.com/CachetHQ/Cachet/discussions/4342).

We appreciate your understanding and look forward to your contributions to the new version.
