### ISSUE TITLE
Feature Request: Options for pre-configured metrics based on incidents recorded in Cachet

### ISSUE THREAD

**Issue by nclonts** [CachetHQ/Cachet#4035]
This may have been asked before, however; an option of pre-built metrics for incidents, maintenance, etc., utilizing the data in Cachet. Daily, Weekly, Monthly, or even Last 6 months.

**Comment by jbrooksuk** [comment]
Thank you for your input on Cachet 2.x. We are shifting our attention and resources to Cachet 3.x and will no longer be supporting the 2.x version. If your feedback or issue is relevant to the 3.x series, we encourage you to engage with the new branch.

For more information on the Cachet rebuild and our plans for 3.x, you can read the announcement [here](https://github.com/CachetHQ/Cachet/discussions/4342).

We appreciate your understanding and look forward to your contributions to the new version.
