### ISSUE TITLE
Multiple Cachethq installations

### ISSUE THREAD

**Issue by ghost** [CachetHQ/Cachet#4036]
Hello :)

I'm trying Cachethq and it's awesome! But I need to install it for 4 different domains, and when I do it, nginx gives me an error who says that php upstream is duplicated. Is there a way to install it on different folders to have a multi-domain cachethq installations?

Thanks in advance :)

**Comment by h1kkan** [comment]
> I'm trying Cachethq and it's awesome! But I need to install it for 4 different domains, and when I do it, nginx gives me an error who says that php upstream is duplicated. Is there a way to install it on different folders to have a multi-domain cachethq installations?

Hi @FedericoGB25 ! 

You're trying to setup 4 separate cachet installations on different domains, right? 

Based on the error you mentioned, im assuming that you following [official installation documentation](https://docs.cachethq.io/docs/installing-cachet#running-cachet-on-nginx), and this issue appears when you create multiple copies of cachet nginx config with different domains. 

This error indicates that you have duplicated named upstream blocks in nginx configuration. Only one upstream with the same name allowed. ([nginx upstream module docs](http://nginx.org/en/docs/http/ngx_http_upstream_module.html#upstream)).

To _fix_ this issue in easy-peasy way - you'll need just to remove upstream block from each cachet nginx config **copy**: 

> ```
> # Upstream to abstract backend connection(s) for php
> upstream php {
>     server unix:/tmp/php-cgi.socket;
>     server 127.0.0.1:9000;
> }
> ```

This block should be defined only once per all cachet nginx configs that you created. Then all cachet installations will share same php upstream (single fpm pool), and on nginx restart you wouldn't get `php upstream is duplicated` error. 

Another _longer_ way, when each cachet installation will be configured to use separate php-fpm pool:
- configure multiple php-fpm pools (one per each cachet installation)
- fix `name` and `server` upstream params in each cachet nginx config
- fix `fastcgi_pass` param in php location block (f.e. `fastcgi_pass your-upstream-name;`) in each cachet nginx config

**Comment by jbrooksuk** [comment]
Thank you for your input on Cachet 2.x. We are shifting our attention and resources to Cachet 3.x and will no longer be supporting the 2.x version. If your feedback or issue is relevant to the 3.x series, we encourage you to engage with the new branch.

For more information on the Cachet rebuild and our plans for 3.x, you can read the announcement [here](https://github.com/CachetHQ/Cachet/discussions/4342).

We appreciate your understanding and look forward to your contributions to the new version.
