### ISSUE TITLE
Status of this project

### ISSUE THREAD

**Issue by jamesfryer** [CachetHQ/Cachet#4037]
Back in 2015 I installed Cachet for a client. It looked like a great product. We used the cachethq/docker container. 

Recently I did an upgrade. I found that with the docker container there are some dependency issues that mean only the latest version will work (otherwise the container goes into an endless restart loop). 

Unfortunately the latest version is not ready for production use.

Consider the new "maintenance" feature. Great, because it makes a lot of sense to separate maintenance events from incidents. But it is just riddled with problems, such as:
 * When a maintenance event is complete, it disappears from the status page. I'd prefer it to stay until I remove it, so users get an honest view of the history.
 * The admin list of maintenance events is sorted oldest first, so I need to scroll down many events if I ever want to edit the current one.
 * When I add a maintenance event, the date pickers are very poor and difficult to use.
 * When I add a maintenance event, if I accidentally click the "end date" picker, the end date is set, there is no way to clear it, and the event will never appear on the status page.
 * When I add a maintenance event, the "Notify Subscribers" checkbox sometimes appears, sometimes not (this could be a migration issue).
 * When I add a maintenance event, I randomly get errors from the API.

My clients are not happy.

Looking at the github page, I see many unaddressed issues, development is sporadic, there is no user documentation, no release schedule or roadmap.

A major QA drive is needed to fix all these issues and the resources don't seem to be available. So it seems to me that this project is close to abandonment.

So although it has a very good profile if you search for a status page tool, I've come to the sad conclusion that Cachet is not a viable product and I need to find an alternative.

I wonder if the team on this project have any comments on this that might restore my confidence. Failing that, a fix for the cachet-docker container that would enable me to use v2.3.18 again.

**Comment by tyteen4a03** [comment]
Yeah I've been looking at the status of this project every now and then for the past year and it really looks like it has been abandoned.

**Comment by blackchineykh** [comment]
Sad. It's built on a great framework that is laravel and maybe we could contribute to the project to get it moving again? Otherwise a fork?

**Comment by gustavobim** [comment]
James (which is the project maintainer) posted a few months ago about getting extra help with the project. Anyone know if this discussion is still happening? Source: https://twitter.com/jbrooksuk/status/1247589628225388551

**Comment by TheoBearman** [comment]
@GrahamCampbell @jbrooksuk can you shed any light on this?

**Comment by GrahamCampbell** [comment]
I'll try to chat with James about Cachet next week. :)

**Comment by TheoBearman** [comment]
Looking forward to hearing any updates :)

**Comment by vsenapathy** [comment]
Ya looking forward for some updates

**Comment by jamesfryer** [comment]
> James (which is the project maintainer) posted a few months [...] https://twitter.com/jbrooksuk/status/1247589628225388551

The suggestion there of a "complete rewrite" makes me even more dismayed for the project. What I see this project needing is a focus on QA, release schedule and finishing the work that has been done.

**Comment by Pimorez** [comment]
Any update on this @GrahamCampbell ?

**Comment by bradjones1** [comment]
The day after, James merged in https://github.com/CachetHQ/Cachet/commit/cfd173cf122d925b70d5133a37528db6120bea67 so he's around; the conversation here really hinges on the problem that faces many open-source packages; overworked maintainers, insecure (if even existent) funding, and the responsibility that comes with creating a thing that becomes bigger than you.

The OP's passion is relatable but the implication is basically that he wants "someone" to update the software that none of us are likely to ever spend real cash on. That's not an indictment of open source but it isn't a helpful approach. For instance, in reviewing this project myself I have reviewed the Docker packaging and found many opportunities for improvement, but this isn't an indictment. Docker best practices have changed a lot over the years too, not to mention we all get better at what we do all the time.

Is Cachet usable right now, and is it better than other open source alternatives? I'm working to find that out myself by spending a few hours playing with it and seeing if there are opportunities for improvement.

As I write this there are 65 open pull requests and 234 open issues. Nobody would dispute this is a sign of a project which contains a good amount of deferred maintenance.

Not trying to read too many tea leaves but it looks like @jbrooksuk [works for Laravel now](https://twitter.com/jbrooksuk/status/1154140169290862596) so he's got a new-ish proverbial day job. As someone who struggles to stay active in open source (even when it's pretty much my day job!) I can relate it's difficult.

Question for him and any other maintainer would be, open to sharing the reins and building out a roadmap for long-term caretaking of the project?

**Comment by jamesfryer** [comment]
> The OP's passion is relatable but the implication is basically that he wants "someone" to update the software that none of us are likely to ever spend real cash on. That's not an indictment of open source but it isn't a helpful approach. For instance, in reviewing this project myself I have reviewed the Docker packaging and found many opportunities for improvement, but this isn't an indictment. Docker best practices have changed a lot over the years too, not to mention we all get better at what we do all the time.

I understand the difficulties of managing a project with limited resources. But when I looked at the latest version which prompted me to write my OP, I saw features that had been added without much strategy or QA, so the product is less usable than it was before. What effort there has been, to me appears to have caused the project to move backwards. That's a failure in planning, not in resourcing.

Now the discussion is of a "complete rewrite". How can this make sense, when there are no resources to get the existing product out the door?

> Question for him and any other maintainer would be, open to sharing the reins and building out a roadmap for long-term caretaking of the project?

I think this or a fork has to be the way forward.

**Comment by jbrooksuk** [comment]
Hey 👋 

Please check out https://github.com/CachetHQ/Cachet/discussions/4342

TLDR; Cachet is back! 🎉
