### ISSUE TITLE
Component not updating the Updated_at if its was in same state

### ISSUE THREAD

**Issue by ritheshrithu** [CachetHQ/Cachet#4047]
Hi All,

I am using the Cachet API to update the component, but let say if the component name is "API" and its current status is "OPERATIONAL", if i update it again to "OPERATIONAL" the last_updated_at time is displaying old time when the component updated from one state to other.

I have tried to modify the **Bus\Handlers\Commands\Component\UpdateComponentCommandHandler** by removing the conditional check,

`if ($command->status && (int) $originalStatus !== (int) $command->status) {
event(new ComponentStatusWasChangedEvent($this->auth->user(), $component, $originalStatus, $command->status, $command->silent));
}`

But still the same. Could someone please assist here

**Comment by jbrooksuk** [comment]
Thank you for your input on Cachet 2.x. We are shifting our attention and resources to Cachet 3.x and will no longer be supporting the 2.x version. If your feedback or issue is relevant to the 3.x series, we encourage you to engage with the new branch.

For more information on the Cachet rebuild and our plans for 3.x, you can read the announcement [here](https://github.com/CachetHQ/Cachet/discussions/4342).

We appreciate your understanding and look forward to your contributions to the new version.
