### ISSUE TITLE
Exception: Class 'Fideloper\Proxy\ProxyServiceProvider' not found

### ISSUE THREAD

**Issue by Finkregh** [cachethq/Cachet#405]
I just switched to @dddb6ed9729c49f0152791ff0e89741929d226d2 and now i get an exception whereever i got ('/' or '/dashboard'):

```
Symfony \ Component \ Debug \ Exception \ FatalErrorException (E_ERROR)
Class 'Fideloper\Proxy\ProxyServiceProvider' not found
```

**Comment by joecohens** [comment]
Have you `composer install`?

**Comment by jbrooksuk** [comment]
Run what @joecohens said and you'll be sorted :)
