### ISSUE TITLE
Mail not working

### ISSUE THREAD

**Issue by klcar** [CachetHQ/Cachet#4051]
Hi, 
I have a fresh setup of cachet and can't get the mail to work.
I've tried the queue drivers database and sync.
Mail is SMTP

Settings in my .env file don't reflect with the settings in cachet, so that's the first issue.
Next is that when I subscribe, and I open the log file in /storage/logs/laravel.log, I can see the verification mail that's being composed, but neither the sender name or address correspond with what I've filled in in my .env file or in the cachet web-section "settings / mail"

thanks

**Comment by jbrooksuk** [comment]
Try running `rm -rf bootstrap/cache{,t}/` and then trying again.
