### ISSUE TITLE
Class 'Bugsnag\BugsnagLaravel\BugsnagServiceProvider' not found

### ISSUE THREAD

**Issue by mcunha98** [CachetHQ/Cachet#4053]
I follow every step of documentation but when I run the generation of key :

[root@centos status]$ php artisan key:generate
In ProviderRepository.php line 208:
  Class 'Bugsnag\BugsnagLaravel\BugsnagServiceProvider' not found

**Comment by l3d00m** [comment]
Which PHP version and which version of cachet are you using?

**Comment by jbrooksuk** [comment]
I've moved Bugsnag into the main dependencies list.
