### ISSUE TITLE
This site can’t be reached when users try to click the confirm subscription link. 

### ISSUE THREAD

**Issue by haydenjames** [CachetHQ/Cachet#4055]
Link example from test subscribe. This is the confirmation link received in email from Cachet: 
http://url7152.stacklinux.com/ls/click?upn=6-2BxEogRA2-2BiD6MYAuwqTl9m2mNCWbZ8Ge-2BgGkrNeppgblzHhl7s4HVqC7FkwRf0zIBbWyEwfml5XqMOmdR5kuNiM3Uo2K-2FtyHRYqNjk78-2BhbeWJ7knEjD6QlNBS8oYA6WdCjbeeD3z1tUuMztuW7nQ-3D-3DxdGC_tu-2BLE3R-2FwiqMT8aVF26-2BiSvQiOBT02A8lWXKJcx2ZHu05bkW3q8RBT2WqdII4Twi9oq-2BFFR7CvzNicexwMjga3pwc-2F90h3cdglMBUoRWnTjX02hX7Iggqs2zvdDNibrj-2FBC27rIsGq-2B5-2FDJ2u5sGijeDqSUUNQdZjD8O-2FHoO0M4t1zNxqbEwhB24WtqN-2Flq5WZKKQoP4Je5vAVG7ydYM7Aa8f5niC-2FoT07JuEFMi7SE-3D

Where is that "url7152" coming from?

Due to the broken link in confirmation email, users are unable to verify. 

Config file:
```
APP_ENV=production
APP_DEBUG=false
APP_URL=https://status.stacklinux.com/
APP_KEY=xxx

DB_DRIVER=mysql
DB_HOST=localhost
DB_DATABASE=xxx
DB_USERNAME=xxx
DB_PASSWORD=xxx
DB_PORT=null
DB_PREFIX=null

CACHE_DRIVER=file
SESSION_DRIVER=file
QUEUE_DRIVER=sync
CACHET_EMOJI=false

MAIL_DRIVER=smtp
MAIL_HOST=smtp.sendgrid.net
MAIL_PORT=587
MAIL_USERNAME=apikey
MAIL_PASSWORD=xxx
MAIL_ADDRESS=xxx@stacklinux.com
MAIL_NAME=StackLinux
MAIL_ENCRYPTION=tls

REDIS_HOST=null
REDIS_DATABASE=null
REDIS_PORT=null

GITHUB_TOKEN=null
```

Running the latest version 2.3.9. The issue started after a previous version update. Has worked without issue for quite some time before that.

**Comment by jbrooksuk** [comment]
Thank you for your input on Cachet 2.x. We are shifting our attention and resources to Cachet 3.x and will no longer be supporting the 2.x version. If your feedback or issue is relevant to the 3.x series, we encourage you to engage with the new branch.

For more information on the Cachet rebuild and our plans for 3.x, you can read the announcement [here](https://github.com/CachetHQ/Cachet/discussions/4342).

We appreciate your understanding and look forward to your contributions to the new version.
