### ISSUE TITLE
OAuth/LDAP settings

### ISSUE THREAD

**Issue by vsenapathy** [CachetHQ/Cachet#4056]
Hey guys,

I am trying to have Oauth enabled in Cachet. Wanted to know if there is any documentation for that.

Thanks,

Vignesh

**Comment by vsenapathy** [comment]
Please let me know if I can have an update on this.

**Comment by stamepicmorg** [comment]
* Implementing SSO with SAML  https://github.com/CachetHQ/Cachet/issues/2930
* LDAP Authentication https://github.com/CachetHQ/Cachet/issues/2108

**Comment by rhysjtevans** [comment]
OAuth / OIDC would be far more beneficial as it's more widely supported from an IdP perspective

**Comment by jbrooksuk** [comment]
Thank you for your input on Cachet 2.x. We are shifting our attention and resources to Cachet 3.x and will no longer be supporting the 2.x version. If your feedback or issue is relevant to the 3.x series, we encourage you to engage with the new branch.

For more information on the Cachet rebuild and our plans for 3.x, you can read the announcement [here](https://github.com/CachetHQ/Cachet/discussions/4342).

We appreciate your understanding and look forward to your contributions to the new version.
