### ISSUE TITLE
Null value in column "reserved" violates not-null constraint

### ISSUE THREAD

**Issue by rpartapsing** [CachetHQ/Cachet#4063]
Hi,

This is me trying to create a maintenance with the "notify subscribers" ticked.
Also I don't see any maintenances showing up in the dashboard.

Please help since this is out main feature.

**Illuminate \ Database \ QueryException (23502)**
SQLSTATE[23502]: Not null violation: 7 ERROR: null value in column "reserved" violates not-null constraint DETAIL: Failing row contains (3, default, {"displayName":"CachetHQ\\Cachet\\Notifications\\Schedule\\NewSc..., 0, null, null, 1595073621, 1595073621). (SQL: insert into "jobs" ("queue", "attempts", "reserved_at", "available_at", "created_at", "payload") values (default, 0, , 1595073621, 1595073621, {"displayName":"CachetHQ\\Cachet\\Notifications\\Schedule\\NewScheduleNotification","job":"Illuminate\\Queue\\CallQueuedHandler@call","maxTries":null,"timeout":null,"timeoutAt":null,"data":{"commandName":"Illuminate\\Notifications\\SendQueuedNotifications","command":"O:48:\"Illuminate\\Notifications\\SendQueuedNotifications\":11:{s:11:\"notifiables\";O:45:\"Illuminate\\Contracts\\Database\\ModelIdentifier\":4:{s:5:\"class\";s:33:\"CachetHQ\\Cachet\\Models\\Subscriber\";s:2:\"id\";i:1;s:9:\"relations\";a:1:{i:0;s:13:\"subscriptions\";}s:10:\"connection\";s:5:\"pgsql\";}s:12:\"notification\";O:62:\"CachetHQ\\Cachet\\Notifications\\Schedule\\NewScheduleNotification\":9:{s:11:\"\u0000*\u0000schedule\";O:44:\"CachetHQ\\Cachet\\Presenters\\SchedulePresenter\":2:{s:8:\"\u0000*\u0000dates\";O:42:\"CachetHQ\\Cachet\\Services\\Dates\\DateFactory\":2:{s:14:\"\u0000*\u0000appTimezone\";s:3:\"UTC\";s:17:\"\u0000*\u0000cachetTimezone\";s:16:\"Europe\/Amsterdam\";}s:16:\"\u0000*\u0000wrappedObject\";O:31:\"CachetHQ\\Cachet\\Models\\Schedule\":30:{s:13:\"\u0000*\u0000attributes\";a:8:{s:6:\"status\";s:1:\"0\";s:12:\"completed_at\";s:19:\"2020-07-25 10:00:00\";s:4:\"name\";s:4:\"rree\";s:7:\"message\";s:4:\"eedd\";s:12:\"scheduled_at\";s:19:\"2020-07-18 10:00:00\";s:10:\"updated_at\";s:19:\"2020-07-18 12:00:21\";s:10:\"created_at\";s:19:\"2020-07-18 12:00:21\";s:2:\"id\";i:4;}s:8:\"\u0000*\u0000casts\";a:5:{s:4:\"name\";s:6:\"string\";s:7:\"message\";s:6:\"string\";s:6:\"status\";s:3:\"int\";s:12:\"scheduled_at\";s:8:\"datetime\";s:12:\"completed_at\";s:8:\"datetime\";}s:11:\"\u0000*\u0000fillable\";a:7:{i:0;s:4:\"name\";i:1;s:7:\"message\";i:2;s:6:\"status\";i:3;s:12:\"scheduled_at\";i:4;s:12:\"completed_at\";i:5;s:10:\"created_at\";i:6;s:10:\"updated_at\";}s:5:\"rules\";a:3:{s:4:\"name\";s:15:\"required|string\";s:7:\"message\";s:15:\"nullable|string\";s:6:\"status\";s:24:\"required|int|between:0,2\";}s:13:\"\u0000*\u0000searchable\";a:3:{i:0;s:2:\"id\";i:1;s:4:\"name\";i:2;s:6:\"status\";}s:11:\"\u0000*\u0000sortable\";a:7:{i:0;s:2:\"id\";i:1;s:4:\"name\";i:2;s:6:\"status\";i:3;s:12:\"scheduled_at\";i:4;s:12:\"completed_at\";i:5;s:10:\"created_at\";i:6;s:10:\"updated_at\";}s:7:\"\u0000*\u0000with\";a:1:{i:0;s:10:\"components\";}s:13:\"\u0000*\u0000connection\";s:5:\"pgsql\";s:8:\"\u0000*\u0000table\";s:9:\"schedules\";s:13:\"\u0000*\u0000primaryKey\";s:2:\"id\";s:10:\"\u0000*\u0000keyType\";s:3:\"int\";s:12:\"incrementing\";b:1;s:12:\"\u0000*\u0000withCount\";a:0:{}s:10:\"\u0000*\u0000perPage\";i:15;s:6:\"exists\";b:1;s:18:\"wasRecentlyCreated\";b:1;s:11:\"\u0000*\u0000original\";a:8:{s:6:\"status\";s:1:\"0\";s:12:\"completed_at\";s:19:\"2020-07-25 10:00:00\";s:4:\"name\";s:4:\"rree\";s:7:\"message\";s:4:\"eedd\";s:12:\"scheduled_at\";s:19:\"2020-07-18 10:00:00\";s:10:\"updated_at\";s:19:\"2020-07-18 12:00:21\";s:10:\"created_at\";s:19:\"2020-07-18 12:00:21\";s:2:\"id\";i:4;}s:10:\"\u0000*\u0000changes\";a:0:{}s:8:\"\u0000*\u0000dates\";a:0:{}s:13:\"\u0000*\u0000dateFormat\";N;s:10:\"\u0000*\u0000appends\";a:0:{}s:19:\"\u0000*\u0000dispatchesEvents\";a:0:{}s:14:\"\u0000*\u0000observables\";a:0:{}s:12:\"\u0000*\u0000relations\";a:0:{}s:10:\"\u0000*\u0000touches\";a:0:{}s:10:\"timestamps\";b:1;s:9:\"\u0000*\u0000hidden\";a:0:{}s:10:\"\u0000*\u0000visible\";a:0:{}s:10:\"\u0000*\u0000guarded\";a:1:{i:0;s:1:\"*\";}s:16:\"\u0000*\u0000forceDeleting\";b:0;}}s:2:\"id\";s:36:\"78753d4f-a7af-46b0-863a-1cdf28ebb003\";s:6:\"locale\";N;s:10:\"connection\";N;s:5:\"queue\";N;s:15:\"chainConnection\";N;s:10:\"chainQueue\";N;s:5:\"delay\";N;s:7:\"chained\";a:0:{}}s:8:\"channels\";a:1:{i:0;s:4:\"mail\";}s:5:\"tries\";N;s:7:\"timeout\";N;s:10:\"connection\";N;s:5:\"queue\";N;s:15:\"chainConnection\";N;s:10:\"chainQueue\";N;s:5:\"delay\";N;s:7:\"chained\";a:0:{}}"}}) returning "id")

**Comment by venkz** [comment]
Facing the same issue. Can someone please look into this.

On cachet-docker  2.4.0-dev

**Comment by peterthomassen** [comment]
I can confirm this issue with a current build.

**Comment by jbrooksuk** [comment]
Thank you for your input on Cachet 2.x. We are shifting our attention and resources to Cachet 3.x and will no longer be supporting the 2.x version. If your feedback or issue is relevant to the 3.x series, we encourage you to engage with the new branch.

For more information on the Cachet rebuild and our plans for 3.x, you can read the announcement [here](https://github.com/CachetHQ/Cachet/discussions/4342).

We appreciate your understanding and look forward to your contributions to the new version.
