### ISSUE TITLE
PHP 7.4.x Support

### ISSUE THREAD

**Issue by SugarD-x** [CachetHQ/Cachet#4065]
From the information I'm finding on the main GitHub page and various issues created by users, Cachet doesn't appear to be PHP 7.4.x-compatible. Is this planned to be fixed? If so, is there a specific issue or discussion I can follow for the progress of this? I really like this project, but I am not willing to downgrade my PHP to an older version and put my entire webserver at risk to fix a compatibility issue. I would absolutely love to use Cachet, so any information regarding this is much appreciated.

**Comment by Dovahkiin-Warrior** [comment]
I have the app working on php 7.4.8, had to download the 2.4 zip then do the install process as described on the wiki.

If you're in disbelieve, go to https://status.firehostredux.com and https://status.firehostredux.com/debug.php 

System specs:
```
SuperMicro X8DTL-iF
2x Xeon L5640
48GB DDR3-10600R
CentOS Linux 8
PHP Ver 7.4.8
Apache Web Server (latest avail from yum)
```

**Comment by SugarD-x** [comment]
Is the current GitHub copy stable enough to work from? Also, are you receiving any errors or noticing any bugs on PHP 7.4.8 with it?

**Comment by jbrooksuk** [comment]
In a couple of hours, I’m going to use Laravel Shift to upgrade the 2.4 branch to Laravel 6.x which fixes this.

**Comment by jbrooksuk** [comment]
Thank you for your input on Cachet 2.x. We are shifting our attention and resources to Cachet 3.x and will no longer be supporting the 2.x version. If your feedback or issue is relevant to the 3.x series, we encourage you to engage with the new branch.

For more information on the Cachet rebuild and our plans for 3.x, you can read the announcement [here](https://github.com/CachetHQ/Cachet/discussions/4342).

We appreciate your understanding and look forward to your contributions to the new version.
