### ISSUE TITLE
Consider implementing Validation Window for Google 2FA key

### ISSUE THREAD

**Issue by boveus** [CachetHQ/Cachet#4067]
Hi folks,

I was looking at the source code of Cachet to see an example implementation of 2FA.  After reviewing the documentation for the Google 2FA library, it seems that you could harden the 2FA implementation by preventing a key that has already been used from being used again.

This seems like an unlikely attack vector, so I am not sure how high priority this would be.

It looks like it would require the addition of a `google2fa_ts` field to the `user` model and to change how the validation mechanism is working here: https://github.com/CachetHQ/Cachet/blob/b431ee3702831df88a669c1909cba02d863b4cef/app/Http/Controllers/AuthController.php#L104

The library's [README](https://github.com/antonioribeiro/google2fa#validation-window.) provides an example and further explanation.

```
$secret = $request->input('secret');

$timestamp = $google2fa->verifyKeyNewer($user->google2fa_secret, $secret, $user->google2fa_ts);

if ($timestamp !== false) {
    $user->update(['google2fa_ts' => $timestamp]);
    // successful
} else {
    // failed
}
```

**Comment by jbrooksuk** [comment]
Thank you for your input on Cachet 2.x. We are shifting our attention and resources to Cachet 3.x and will no longer be supporting the 2.x version. If your feedback or issue is relevant to the 3.x series, we encourage you to engage with the new branch.

For more information on the Cachet rebuild and our plans for 3.x, you can read the announcement [here](https://github.com/CachetHQ/Cachet/discussions/4342).

We appreciate your understanding and look forward to your contributions to the new version.
