### ISSUE TITLE
composer-module removes rights on directory

### ISSUE THREAD

**Issue by Finkregh** [cachethq/Cachet#407]
I dont know if this is the right place or if i should go to the composer-bugtracker or some modules'... so please hit me :)
(this is a follow-up to #405)

when i run `php composer.phar install` i get the following error:
```
Generating autoload files
Generating optimized class loader



  [UnexpectedValueException]
  DirectoryIterator::__construct(/var/www/status/app/storage/meta): failed to open dir: Permission denied



cachet:chmod


Script php artisan cachet:chmod handling the post-install-cmd event returned with an error



  [RuntimeException]
  Error Output:

    [UnexpectedValueException]
    DirectoryIterator::__construct(/var/www/status/app/storage/meta): failed to open dir: Permission denied

  cachet:chmod

```

the directorys' status after running composer:
```
d-wxrw--wt 2 www-data www-data  4096 Jan 19 12:28 .
drwxrwxrwx 7 www-data www-data  4096 Jan 12 11:30 ..
-rwxrwxrwx 1 www-data www-data    13 Jan 12 11:30 .gitignore
-rw-r--r-- 1 www-data www-data 10924 Jan 19 12:28 services.json
```

and before:
```
drwxrwx-wt 2 www-data www-data  4096 Jan 19 12:27 .
drwxrwxrwx 7 www-data www-data  4096 Jan 12 11:30 ..
-rwxrwxrwx 1 www-data www-data    13 Jan 12 11:30 .gitignore
-rw-r--r-- 1 www-data www-data 10924 Jan 19 12:27 services.json

```

why should composer remove read-rights on that directory?

**Comment by jbrooksuk** [comment]
We've added an Artisan command called `chmod` which is automatically ran on [post-install-cmd](https://github.com/cachethq/Cachet/blob/master/composer.json#L66-70) to fix permissions when deployed to Heroku or wherever.

Maybe the rights are too hefty.

**Comment by brianjking** [comment]
@jbrooksuk I believe so! I was having trouble updating a Heroku installation so I attempted a new deploy and was shown the same thing from the "Deploy to Heroku" button.

      
       
       Script php artisan cachet:chmod handling the post-install-cmd event returned with an error


                                                                                                                                                                    
  [RuntimeException]                                                                                                                                                
  Error Output:                                                                                                                                                     
                                                                                                                                                                    
    [UnexpectedValueException]                                                                                                                                      
    DirectoryIterator::__construct(/tmp/build_97d44ab0ee81273457a9356390411360/cachethq-Cachet-1c20463/app/storage/cache): failed to open dir: Permission denied    
                                                                                                                                                                    
  cachet:chmod                                                                                                                                                      
                                                                                                                                                                    


install [--prefer-source] [--prefer-dist] [--dry-run] [--dev] [--no-dev] [--no-plugins] [--no-custom-installers] [--no-autoloader] [--no-scripts] [--no-progress] [-v|vv|vvv|--verbose] [-o|--optimize-autoloader] [--ignore-platform-reqs] [packages1] ... [packagesN]



 !     Push rejected, failed to compile PHP (composer.json) app

**Comment by jbrooksuk** [comment]
Interesting, we've never had issues `chmod`ing on Heroku?

**Comment by jbrooksuk** [comment]
@GrahamCampbell can you think of any reasons why this is failing, but previously with the `chmod` within the `post-install-cmd` it did not?

**Comment by GrahamCampbell** [comment]
it needs to go in the post-update bit too.

**Comment by jbrooksuk** [comment]
Look at the last code block, it seems there is an error though? Will it be fixed by copying into `post-update`?

**Comment by GrahamCampbell** [comment]
Should be. Just add it after the optimize command.

**Comment by jbrooksuk** [comment]
Sure thing.
