### ISSUE TITLE
Environement variables not getting applied on setup page 

### ISSUE THREAD

**Issue by CodrinE** [CachetHQ/Cachet#4070]
Hello there!
I am trying to setup Cachet 2.4 with the next predefined env values (so that it has less user interaction as possible):
`- CACHE_DRIVER=apc
 - SESSION_DRIVER=memcached
 - QUEUE_DRIVER=redis`

But it seems that they don't get applied automatically and fields still remain empty:
![image](https://user-images.githubusercontent.com/37159003/88898131-fd7af100-d254-11ea-9952-8e9e9baf986a.png)

**Comment by jbrooksuk** [comment]
Have you tried running `rm -rf bootstrap/cache{,t}/*`.
