### ISSUE TITLE
log out from dashboard too often

### ISSUE THREAD

**Issue by ferypc** [CachetHQ/Cachet#4086]
just installed cachet in my vps with
- litespeed webserver
- php 7.1
- mariadb 10.1.45

it's log out too often, almost every 2 minutes i got error 400 warning (invalid csrf token)
- change ip address to static (using vpn), no use
- change cachet cache_driver and session_driver parameters to apc, to file, but no use

**Comment by jbrooksuk** [comment]
Thank you for your input on Cachet 2.x. We are shifting our attention and resources to Cachet 3.x and will no longer be supporting the 2.x version. If your feedback or issue is relevant to the 3.x series, we encourage you to engage with the new branch.

For more information on the Cachet rebuild and our plans for 3.x, you can read the announcement [here](https://github.com/CachetHQ/Cachet/discussions/4342).

We appreciate your understanding and look forward to your contributions to the new version.
