### ISSUE TITLE
Seeding tags: error!

### ISSUE THREAD

**Issue by coreation** [cachethq/Cachet#409]
Upon seeding a fresh install of the codebase, things go wrong when seeding the component table. The column tags is no longer in that table it seems, yet the seeder tries to add tags into it resulting in an error. Not sure what the goal is, so I just removed tags from that seeding class.

**Comment by jbrooksuk** [comment]
Good catch. Would you mind making a PR with this fixed in the seeder?

**Comment by coreation** [comment]
Sure!

On Thu, Jan 22, 2015 at 2:34 PM, James Brooks <notifications@github.com>
wrote:

> Good catch. Would you mind making a PR with this fixed in the seeder?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/cachethq/Cachet/issues/409#issuecomment-71020358>.
>



-- 
Met vriendelijke groeten,

Jan Vansteenlandt

**Comment by jbrooksuk** [comment]
Thanks buddy :)

**Comment by coreation** [comment]
Ah, don't mention it, small contribution to make my first install work, now I get to see what this puppy can do ;).

**Comment by coreation** [comment]
Hmm, "Call to undefined function Illuminate\Cache\apc_fetch()" you guys are using L5 so I'm not that surprised to see errors like this, however did you guys encounter this, should I pull the framework of L5 from a certain commit that does work at this time?

**Comment by jbrooksuk** [comment]
Nope, we're using Laravel 4. You'll need the apcu extension installed too.

**Comment by GrahamCampbell** [comment]
@coreation Also, Laravel 5's cache stuff is totally identical to L4's.

**Comment by coreation** [comment]
Alrighty, thanks for the info! I installed the apc extension, clearly
that's not apcu?

On Thu, Jan 22, 2015 at 3:12 PM, Graham Campbell <notifications@github.com>
wrote:

> @coreation <https://github.com/coreation> Also, Laravel 5's cache stuff
> is totally identical to L4's.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/cachethq/Cachet/issues/409#issuecomment-71025392>.
>



-- 
Met vriendelijke groeten,

Jan Vansteenlandt

**Comment by jbrooksuk** [comment]
It's definitely apcu - the error says so too:

> Call to undefined function Illuminate\Cache\**apc_fetch()**

Have you restarted Apache/PHP-FPM since installing the extension?

**Comment by coreation** [comment]
Yep, but I see that my php fails to load the extension, so I know how to
proceed ;)

On Thu, Jan 22, 2015 at 3:42 PM, James Brooks <notifications@github.com>
wrote:

> It's definitely apcu - the error says so too:
>
> Call to undefined function Illuminate\Cache**apc_fetch()**
>
> Have you restarted Apache/PHP-FPM since installing the extension?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/cachethq/Cachet/issues/409#issuecomment-71029725>.
>



-- 
Met vriendelijke groeten,

Jan Vansteenlandt
