### ISSUE TITLE
API call for get group sometimes result in EOF

### ISSUE THREAD

**Issue by kcan** [CachetHQ/Cachet#4098]
I am using go client to do api call to end point "api/v1/components/groups", but sometimes I am getting EOF from the server, do you know why this happens?

Thanks

**Comment by kcan** [comment]
2020/08/28 09:23:17 Get "https://statuspage.io/api/v1/components/groups": EOF
2020/08/28 09:23:17 http: panic serving 6.15.4.54:51762: runtime error: invalid memory address or nil pointer dereference
goroutine 200 [running]:
net/http.(*conn).serve.func1(0xc0000b4b40)
	/usr/local/go/src/net/http/server.go:1800 +0x139
panic(0x6cd4c0, 0x97c1f0)
	/usr/local/go/src/runtime/panic.go:975 +0x3e3
/cachet/alertsp/checkgroupexist.CheckGroupExist(0xc000020590, 0xb, 0x0, 0x0)
	/src/cachet/alertsp/checkgroupexist/CheckGroupExist.go:133 +0x385
main.updateStatusPage(0x797900, 0xc0000ec540, 0xc000064700)
	/src/cachet/alertsp/alertsp.go:89 +0x113b
net/http.HandlerFunc.ServeHTTP(0x73de48, 0x797900, 0xc0000ec540, 0xc000064700)
	/usr/local/go/src/net/http/server.go:2041 +0x44
net/http.(*ServeMux).ServeHTTP(0x988c00, 0x797900, 0xc0000ec540, 0xc000064700)
	/usr/local/go/src/net/http/server.go:2416 +0x1a5
net/http.serverHandler.ServeHTTP(0xc0000ec000, 0x797900, 0xc0000ec540, 0xc000064700)
	/usr/local/go/src/net/http/server.go:2836 +0xa3
net/http.(*conn).serve(0xc0000b4b40, 0x798080, 0xc000162740)
	/usr/local/go/src/net/http/server.go:1924 +0x86c
created by net/http.(*Server).Serve
	/usr/local/go/src/net/http/server.go:2962 +0x35c

**Comment by jbrooksuk** [comment]
Thank you for your input on Cachet 2.x. We are shifting our attention and resources to Cachet 3.x and will no longer be supporting the 2.x version. If your feedback or issue is relevant to the 3.x series, we encourage you to engage with the new branch.

For more information on the Cachet rebuild and our plans for 3.x, you can read the announcement [here](https://github.com/CachetHQ/Cachet/discussions/4342).

We appreciate your understanding and look forward to your contributions to the new version.
