### ISSUE TITLE
cachet docker cachethq/docker matrix does not show 12hour view correctly 

### ISSUE THREAD

**Issue by kcan** [CachetHQ/Cachet#4099]
I am using cachet docker image " latest  6d0814fbb73b " (2.4.0-dev)  and when cachet is up and running, the metrics does not show 12 hours view correctly ,  it only shows "loading data".  also the vertical axis scale does not show correctly if I am using the default value of 100 for example. 

![image](https://user-images.githubusercontent.com/3047481/90638505-b10c4b00-e22d-11ea-9a1c-0a893c079801.png)

What can be the issue?

thanks

**Comment by kcan** [comment]
In the console I can see the error:
`VM396:1 GET https://statuspagedev.eks-eu-central-1-private.dev.bizops.ridedev.io/metrics/1?filter=today 500 (Internal Server Error)
(anonymous) @ VM396:1
(anonymous) @ all.js?id=eb6400680943aee8df85:1
e.exports @ all.js?id=eb6400680943aee8df85:1
e.exports @ all.js?id=eb6400680943aee8df85:9
Promise.then (async)
XmWM.r.request @ all.js?id=eb6400680943aee8df85:8
r.<computed> @ all.js?id=eb6400680943aee8df85:8
(anonymous) @ all.js?id=eb6400680943aee8df85:5
getData @ all.js?id=eb6400680943aee8df85:1
changeView @ all.js?id=eb6400680943aee8df85:1
click @ all.js?id=eb6400680943aee8df85:8
Je @ vendor.js?id=313e4cd2cf600307cb5c:1
n @ vendor.js?id=313e4cd2cf600307cb5c:1
Xa.i._wrapper @ vendor.js?id=313e4cd2cf600307cb5c:1
all.js?id=eb6400680943aee8df85:4 Uncaught (in promise) Error: Request failed with status code 500
    at FtD3.e.exports (all.js?id=eb6400680943aee8df85:4)
    at e.exports (all.js?id=eb6400680943aee8df85:1)
    at XMLHttpRequest.f.onreadystatechange (all.js?id=eb6400680943aee8df85:1)`

**Comment by kcan** [comment]
on cachet log the error is:
`[13:24:34] LOG.error: PDOException: SQLSTATE[42803]: Grouping error: 7 ERROR:  column "metric_points.created_at" must appear in the GROUP BY clause or be used in an aggregate function
LINE 1: SELECT to_char(metric_points.created_at, 'YYYY-MM-DD HH24:00...
                       ^ in /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:117`

**Comment by jbrooksuk** [comment]
Thank you for your input on Cachet 2.x. We are shifting our attention and resources to Cachet 3.x and will no longer be supporting the 2.x version. If your feedback or issue is relevant to the 3.x series, we encourage you to engage with the new branch.

For more information on the Cachet rebuild and our plans for 3.x, you can read the announcement [here](https://github.com/CachetHQ/Cachet/discussions/4342).

We appreciate your understanding and look forward to your contributions to the new version.
