### ISSUE TITLE
504 timeout error when a new incident is created

### ISSUE THREAD

**Issue by mdsp0292** [CachetHQ/Cachet#4100]
Hello, 

I'm new to the cachet. We've recently implement cachet for our company status page. We've around 300+ subscribers in the system.

When I create a new incident in the system, it throws an error 504 after a few minutes and it creates an incident after sending out all the emails. 

Cachet Version: 2.4.0-dev
PHP: 7.4
using Redis Queue driver
Ngninx server on uuntu

**Comment by jbrooksuk** [comment]
Thank you for your input on Cachet 2.x. We are shifting our attention and resources to Cachet 3.x and will no longer be supporting the 2.x version. If your feedback or issue is relevant to the 3.x series, we encourage you to engage with the new branch.

For more information on the Cachet rebuild and our plans for 3.x, you can read the announcement [here](https://github.com/CachetHQ/Cachet/discussions/4342).

We appreciate your understanding and look forward to your contributions to the new version.
