### ISSUE TITLE
API: Subscriber always set to global.

### ISSUE THREAD

**Issue by dwalsh9** [CachetHQ/Cachet#4101]
Hello,

We're testing the API and when you set a subscriber to specific components, it always assigns the subscriber as global in the database, this means they get all notices irrespective. 

API command: 
`{"email":"noreply@example.com","verify":"false","components":["35","12"]}
`
API Response: 
```

    [data] => stdClass Object
        (
            [email] => noreply@example.com
            [verify_code] => *** 
            [updated_at] => 2020-08-24 12:13:32
            [created_at] => 2020-08-24 12:13:32
            [id] => 17
            [verified_at] => Monday 24th August 2020 10:00:00
            [subscriptions] => Array
                (
                    [0] => stdClass Object
                        (
                            [id] => 173
                            [subscriber_id] => 17
                            [component_id] => 12
                            [created_at] => 2020-08-24 02:13:32
                            [updated_at] => 2020-08-24 02:13:32
                        )

                    [1] => stdClass Object
                        (
                            [id] => 174
                            [subscriber_id] => 17
                            [component_id] => 35
                            [created_at] => 2020-08-24 02:13:32
                            [updated_at] => 2020-08-24 02:13:32
                        )

                )

        )

)


```

Database: 

<img width="1263" alt="Screen Shot 2020-08-24 at 12 15 17 pm" src="https://user-images.githubusercontent.com/19158793/90996964-87736b00-e603-11ea-99b3-33f758f2acf7.png">

As you can see, global is set to 1, when it should be 0.

**Comment by dwalsh9** [comment]
Any update on this? I'm just going to have to run a SQL query to fix it at this point

**Comment by jbrooksuk** [comment]
Thank you for your input on Cachet 2.x. We are shifting our attention and resources to Cachet 3.x and will no longer be supporting the 2.x version. If your feedback or issue is relevant to the 3.x series, we encourage you to engage with the new branch.

For more information on the Cachet rebuild and our plans for 3.x, you can read the announcement [here](https://github.com/CachetHQ/Cachet/discussions/4342).

We appreciate your understanding and look forward to your contributions to the new version.
