### ISSUE TITLE
 Why is MAINTENANCE not Visible for the users?

### ISSUE THREAD

**Issue by elvirmuslic** [CachetHQ/Cachet#4104]
This is a pretty straightforward question, I don't see the point of maintenance if I cant inform users or have it displayed on the front page. At least make it an option in settings, perhaps I am not aware of this but I couldn't find this basic option for a status page.

**Comment by elvirmuslic** [comment]
It is not showing on a fresh installation of Cachet, no settings available to make it show or any control over it.

**Comment by rpartapsing** [comment]
I have the same issue. Can someone please look at it

**Comment by wil2005-development** [comment]
Hello,

I have the same issue. I make a Maintenance and I don't see him. Please fix this.

**Comment by rpartapsing** [comment]
@wil2005-development @elvirmuslic  The idea is: don't put an end date to your scheduled maintenance. Then and only then it will be visible on the dashboard.

**Comment by elvirmuslic** [comment]
I know about this but is this the intended working method?

**Comment by rpartapsing** [comment]
IMO not. I think it should shown on dashboard even with a maintenance end slot.

**Comment by elvirmuslic** [comment]
Issue not solved, developers not answering. 

Issue closed till further..

**Comment by dthomson425** [comment]
Has any solved this, would the alt-three.com be willing to quote a fix for this and the metrics showing up issue?

**Comment by frogstarr78** [comment]
I had a similar issue. I'm running v2.4.1 currently. You can fix this by updating the file app/Models/Schedule.php. Update the scopeUncompleted method removing this line (or simply commenting it out): 

```php
return $query->whereNull('completed_at');
```

and replacing it with this line:

```php
return $query->whereNull('completed_at')->orWhere('completed_at', '>', Carbon::now());
```

To try to make things a little more clear, by including the whole function, replace this:

```php
public function scopeUncompleted(Builder $query)
{
    return $query->whereIn('status', [self::UPCOMING, self::IN_PROGRESS])->where(function (Builder $query) {
        return $query->whereNull('completed_at');
    });
}
```
with this

```php
public function scopeUncompleted(Builder $query)
{
    return $query->whereIn('status', [self::UPCOMING, self::IN_PROGRESS])->where(function (Builder $query) {
        return $query->whereNull('completed_at')->orWhere('completed_at', '>', Carbon::now());
    });
}
```
