### ISSUE TITLE
API: Change component status with an incident update

### ISSUE THREAD

**Issue by zipy124** [CachetHQ/Cachet#4116]
In the GUI dashboard when creating an incident update, you can choose a status to update the parent component with. The API however only supports choosing a new status for the incident, not the component. It seems odd that the API does not include the full functionality of the dashboard.

**Comment by jbrooksuk** [comment]
Thank you for your input on Cachet 2.x. We are shifting our attention and resources to Cachet 3.x and will no longer be supporting the 2.x version. If your feedback or issue is relevant to the 3.x series, we encourage you to engage with the new branch.

For more information on the Cachet rebuild and our plans for 3.x, you can read the announcement [here](https://github.com/CachetHQ/Cachet/discussions/4342).

We appreciate your understanding and look forward to your contributions to the new version.
