### ISSUE TITLE
Unable to log in to /dashboard

### ISSUE THREAD

**Issue by chrobotm** [CachetHQ/Cachet#4123]
Just installed cachet using the latest docker image. After going through the setup page when I try to log in, it times out. In the logs I can see:

```
2020/09/23 09:01:36 [error] 78#78: *2430 upstream timed out (110: Operation timed out) while reading response header from upstream, client: 10.x.x.x, server: localhost, request: "GET /dashboard HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "mystatuspage.com", referrer: "https://mystatuspage.com/auth/login"
```

Using postgres v12.3 database 

Also tried using MySQL 8.0.20

Logs:
```
"GET /dashboard HTTP/1.1" 499 ...
WARNING: [pool www] child 97, script '/var/www/html/public/index.php' (request: "GET /index.php") execution timed out (144.301366 sec), terminating
WARNING: [pool www] child 97 exited on signal 15 (SIGTERM) after 270.204353 seconds from start
[23-Sep-2020 09:50:06] NOTICE: [pool www] child 104 started
```

**Comment by sag1** [comment]
Hello,

I am facing the same issues. Why execution timeout ? When I tried for 3rd time, it displays dashboard. But the error is recurrent while doing another action like "Settings > Log". So something is bad. Could you please take into account this problem ? 

 WARNING: [pool www] child 112, script '/var/www/html/public/index.php' (request: "GET /index.php") execution timed out (129.757161 sec), terminating
WARNING: [pool www] child 112 exited on signal 15 (SIGTERM) after 130.341762 seconds from start

**Comment by LazyMaple** [comment]
the same problem with docker env,  too

**Comment by jbrooksuk** [comment]
Thank you for your input on Cachet 2.x. We are shifting our attention and resources to Cachet 3.x and will no longer be supporting the 2.x version. If your feedback or issue is relevant to the 3.x series, we encourage you to engage with the new branch.

For more information on the Cachet rebuild and our plans for 3.x, you can read the announcement [here](https://github.com/CachetHQ/Cachet/discussions/4342).

We appreciate your understanding and look forward to your contributions to the new version.
