### ISSUE TITLE
Change dashboard date st,nd,th etc.

### ISSUE THREAD

**Issue by razerrazer** [CachetHQ/Cachet#4129]
Hi,

We want to change the st,nd,th etc to swedish instead like a,e i can't find any of this in the translation file.

See attached file.
![photo_2020-10-02_11-33-36](https://user-images.githubusercontent.com/17000974/94909432-725fe680-04a3-11eb-8abe-cbe61adaea7c.jpg)

![photo_2020-10-02_11-34-32](https://user-images.githubusercontent.com/17000974/94909443-78ee5e00-04a3-11eb-9938-ce50513390b6.jpg)

Let me know if you need more information

**Comment by NiTRoeSE** [comment]
@razerrazer 
Hi, i have the same problem, did you find any solution for this ?

**Comment by InFerYes** [comment]
Do any of you 2 have this resolved?

**Comment by pavog** [comment]
Hi guys,

I found a way to remove the "English order suffix for the day of the month" (st, nd, rd, th, ...).
As you can see in [incidents.blace.php](https://github.com/CachetHQ/Cachet/blob/2.4/resources/views/partials/incidents.blade.php#L1), it uses the function `formatted_date` to output the date in a human readable format. The function `formatted_date` from [helpers.php](https://github.com/CachetHQ/Cachet/blob/2.4/app/helpers.php#L61) takes the setting `setting.date_format` or the default value `jS F Y` (see [php format reference here](https://www.php.net/manual/en/datetime.format.php)).
You can override the default value by going into your configuration file. The location of the configuration file depends on your app environment.
- bootstrap/cachet/dev.php
- bootstrap/cachet/production.php

There you will find an array with the key `date_format`.
For example, I changed the value for the date_format to `l j F Y`.
You need to restart your application after you have changed the value. You may need to clear your cached configuration.

I don't know if you can change the value for this setting with your .env file.
I tried adding `DATE_FORMAT="l j F Y"` there (and clearing my configuration with artisan config:clear), but it didn't work.
Maybe someone else can find a way for this problem.

**Comment by jbrooksuk** [comment]
Thank you for your input on Cachet 2.x. We are shifting our attention and resources to Cachet 3.x and will no longer be supporting the 2.x version. If your feedback or issue is relevant to the 3.x series, we encourage you to engage with the new branch.

For more information on the Cachet rebuild and our plans for 3.x, you can read the announcement [here](https://github.com/CachetHQ/Cachet/discussions/4342).

We appreciate your understanding and look forward to your contributions to the new version.
