### ISSUE TITLE
Error while trying to validate subscriber on 2.4

### ISSUE THREAD

**Issue by mcharytoniuk** [CachetHQ/Cachet#4134]
Hello,

I am using Cachet from 2.4 branch. I know it's not stable yet, but still I have this error while trying to confirm user subscription:

```
#61 {main} {"identification":{"id":"a7aab18a-a6a2-4e9b-9f73-4fec81c2776f"},"exception":"[object] (ErrorException(code: 0): Undefined var
iable: componentGroup (View: /opt/website/resources/views/subscribe/manage.blade.php) at /opt/website/storage/framework/views/54976ea75b
a23eb67924842ac09d71cbccd4b56c.php:46, ErrorException(code: 0): Undefined variable: componentGroup at /opt/website/storage/framework/vie
ws/54976ea75ba23eb67924842ac09d71cbccd4b56c.php:46)
```

It's happening after clicking subscription confirm link from an email. User is verified after that, only the view itself does not render.

Best wishes

**Comment by sergicastellsague** [comment]
@mcharytoniuk the fix is pretty simple.
Modify the file resources/views/subscribe/manage.blade.php
put this as line 44:             @foreach($componentGroups as $componentGroup)
and this as line 58:             @endforeach
<img width="702" alt="Captura de Pantalla 2020-11-04 a les 13 35 04" src="https://user-images.githubusercontent.com/5736310/98112459-8d5ab780-1ea2-11eb-9bd2-d0976b1657af.png">

It'll then work

**Comment by pdelorme** [comment]
ok. this fixes it.
any idea when is it going to be released ?
thanks. that fix came just in time for me ;-)

**Comment by sergicastellsague** [comment]
No idea. I'm not a maintainer nor even a committer. I just experienced the issue and _found_ the fix.

**Comment by nurunuriyev** [comment]
i have same  issue. your mentioned lines are in my config file at from 21 to 37, but it is not work.it was work 1-2 days before.there is no any OS updates

**Comment by sergicastellsague** [comment]
I don't really know @nurunuriyev, if it used to work a couple days ago, it should work today as well. Clear CAchet's cache, and restart the server.

**Comment by jbrooksuk** [comment]
Thank you for your input on Cachet 2.x. We are shifting our attention and resources to Cachet 3.x and will no longer be supporting the 2.x version. If your feedback or issue is relevant to the 3.x series, we encourage you to engage with the new branch.

For more information on the Cachet rebuild and our plans for 3.x, you can read the announcement [here](https://github.com/CachetHQ/Cachet/discussions/4342).

We appreciate your understanding and look forward to your contributions to the new version.
