### ISSUE TITLE
Cachet takes FORever to update an incident or status

### ISSUE THREAD

**Issue by mfahey79** [CachetHQ/Cachet#4147]
When you click Submit for a new incident, the browser just spins and in the background it emails each users
one by one ever few seconds. Once that process is complete, it then posts the incident on the page.
Also,  httpd uses 100% cpu regardless of how many cores I give it.

This is strange. 

It should post the status/incident immediately then send out the emails.
I only have about 50 users signed up and it takes 5 minutes to send these emails. Very strange.

**Comment by mfahey79** [comment]
Is this project still active? Seems like a ghost town.

**Comment by jsargent7089** [comment]
@jbrooksuk

**Comment by jsargent7089** [comment]
What web server are you using?

**Comment by mfahey79** [comment]
Freebsd 12.1 P10
apache2.4
php 7.2

QUEUE_DRIVER=sync
This takes FOREVER to send emails. It will send an email one by one (I have
40 recipients) and pause inbetween.
The webpage waits to reload until it sends all of the email. I have never
see a php app work like this.

I just want it to send out the emails fast.


 PHP Fatal error:  Uncaught ReflectionException: Class config does not
exist in
/usr/local/www/apache24/data/Cachet/vendor/laravel/framework/src/Illuminate/Container/Container.php:734\nStack
trace:\n#0
/usr/local/www/apache24/data/Cachet/vendor/laravel/framework/src/Illuminate/Container/Container.php(734):
ReflectionClass->__construct('config')\n#1
/usr/local/www/apache24/data/Cachet/vendor/laravel/framework/src/Illuminate/Container/Container.php(629):
Illuminate\\Container\\Container->build('config', Array)\n#2
/usr/local/www/apache24/data/Cachet/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(697):
Illuminate\\Container\\Container->make('config', Array)\n#3
/usr/local/www/apache24/data/Cachet/vendor/laravel/framework/src/Illuminate/Container/Container.php(1178):
Illuminate\\Foundation\\Application->make('config')\n#4
/usr/local/www/apache24/data/Cachet/vendor/laravel/framework/src/Illuminate/Container/Container.php(1223):
Illuminate\\Container\\Container->offsetGet('config')\n#5
/usr/local/www/apache24/data/Cachet/vendor/ in
/usr/local/www/apache24/data/Cachet/vendor/laravel/framework/src/Illuminate/Container/Container.php
on line 734

Mike Fahey

Senior Application/Network Administrator

Nazareth Area School District

One Education Plaza Nazareth, PA 18064

Phone 610.759.1170 ext. 1777

Fax: 610.746.7001

mfahey@nazarethasd.org

**Comment by mfahey79** [comment]
any update? Bout to use different software. Your's doesnt work right.

Mike Fahey

Senior Application/Network Administrator

Nazareth Area School District

One Education Plaza Nazareth, PA 18064

Phone 610.759.1170 ext. 1777

Fax: 610.746.7001

mfahey@nazarethasd.org

**Comment by benperiton** [comment]
@mfahey79 The sync driver processes the queue in the main thread, so yes it would be slow. You would need to use a different driver, then have a seperate script running to process the queue (kept alive by supervisor or similar)

https://docs.cachethq.io/docs/configuring-the-queue

**Comment by lol768** [comment]
> any update? Bout to use different software. Your's doesnt work right.

:man_facepalming: 

@mfahey79 Bit of friendly advice: no OSS maintainers owe you anything - and you look quite silly when it's readily apparent you've failed to read [the](https://laravel.com/docs/8.x/queues#driver-prerequisites) [documentation](https://docs.cachethq.io/docs/configuring-the-queue) and complain about not having received an immediate response.

**Comment by mfahey79** [comment]
@lol768 Great. I'll use something else. Your RTFM is childish.

**Comment by jbrooksuk** [comment]
Thank you for your input on Cachet 2.x. We are shifting our attention and resources to Cachet 3.x and will no longer be supporting the 2.x version. If your feedback or issue is relevant to the 3.x series, we encourage you to engage with the new branch.

For more information on the Cachet rebuild and our plans for 3.x, you can read the announcement [here](https://github.com/CachetHQ/Cachet/discussions/4342).

We appreciate your understanding and look forward to your contributions to the new version.
