### ISSUE TITLE
fix mobile layout of incidents page

### ISSUE THREAD

**Issue by thisisusernameforgithub** [CachetHQ/Cachet#4165]
hi all!
how and where can I fix the layout on the incidents page https://mycachet.domain.com/incidents/XXX
as you can see in the screenshot: the title is long (name of the company) and runs over the link "Главный экран". I would like to add indents after the title

![image](https://user-images.githubusercontent.com/23400417/99768275-8d4eee80-2b15-11eb-8d74-4e34f7b9c04f.png)

**Comment by cp-sumi-k** [comment]
Hi @graceastrid , You can fix layout of incident [here](https://github.com/CachetHQ/Cachet/blob/2.4/resources/views/partials/incidents.blade.php).

**Comment by jbrooksuk** [comment]
Thank you for your input on Cachet 2.x. We are shifting our attention and resources to Cachet 3.x and will no longer be supporting the 2.x version. If your feedback or issue is relevant to the 3.x series, we encourage you to engage with the new branch.

For more information on the Cachet rebuild and our plans for 3.x, you can read the announcement [here](https://github.com/CachetHQ/Cachet/discussions/4342).

We appreciate your understanding and look forward to your contributions to the new version.
