### ISSUE TITLE
Feature Request : Ability to select what email notifications are sent

### ISSUE THREAD

**Issue by tbasten** [CachetHQ/Cachet#4167]
At the moment if a service is marked as down/degraded etc... all subscribers get an email notification. It would be good to turn this off but still allow email notifications for upcoming maintenance and incidents.

**Comment by jbrooksuk** [comment]
Thank you for your input on Cachet 2.x. We are shifting our attention and resources to Cachet 3.x and will no longer be supporting the 2.x version. If your feedback or issue is relevant to the 3.x series, we encourage you to engage with the new branch.

For more information on the Cachet rebuild and our plans for 3.x, you can read the announcement [here](https://github.com/CachetHQ/Cachet/discussions/4342).

We appreciate your understanding and look forward to your contributions to the new version.
