### ISSUE TITLE
504 timeout when creating an incident and notifying subscribers

### ISSUE THREAD

**Issue by Nils-O** [CachetHQ/Cachet#4168]
Hello,

I'm experiencing an issue with Cachet 2.4 which I hope one of you might know how to fix.

There's quite a few subscribers (more than 2000) in my application, and when I create an incident that notifies subscriber, it takes a long time to process and then ends in a 504 error. The component status wasn't changed and incident didn't get created. In the logs I found that the max execution time got exceeded so I increased that, as well as nginx time out values.

After sufficiently increasing the max_execution_time all notifications seem to get sent, the incident gets created and the status gets changed, but I still end up with a 504 error while no error gets logged.

This brings me to two issues:

- What could be the cause of still receiving a 504 error in this case?

- What could be the cause of this request taking such a long time in the first place? I have set up Cachet with QUEUE_DRIVER=database so I'd expect messages to get queued, however this does not seem to be happening.

I'd be happy to receive any suggestions.

**Comment by jbrooksuk** [comment]
Thank you for your input on Cachet 2.x. We are shifting our attention and resources to Cachet 3.x and will no longer be supporting the 2.x version. If your feedback or issue is relevant to the 3.x series, we encourage you to engage with the new branch.

For more information on the Cachet rebuild and our plans for 3.x, you can read the announcement [here](https://github.com/CachetHQ/Cachet/discussions/4342).

We appreciate your understanding and look forward to your contributions to the new version.
