### ISSUE TITLE
cachethq.io domain not resolving?

### ISSUE THREAD

**Issue by victorhooi** [CachetHQ/Cachet#4169]
Is anybody else having issues resolving the cachethq.io domain?

For me, it's not resolving, using Google DNS.

**Comment by kdambekalns** [comment]
It's up again. Still would be nice to know what happened…

**Comment by kdambekalns** [comment]
> Alternatively, email [support@alt-three.com](mailto:support@alt-three.com) for our Professional support service

Oh, and… is that actually still working?
