### ISSUE TITLE
Use Fig instead of raw Docker as default

### ISSUE THREAD

**Issue by dosten** [cachethq/Cachet#417]
Maybe we can use Fig (http://www.fig.sh/) to run Cachet, essentially is the same, but only need to execute `fig up`. This isn't a replacement of docker, only a new way (and optional) to run Catchet.

**Comment by jbrooksuk** [comment]
Fig looks awesome! Make a PR :)

**Comment by dosten** [comment]
Sure! I'll make a PR soon :)

**Comment by jbrooksuk** [comment]
:beers:

**Comment by jbrooksuk** [comment]
Any news on this @dosten? :)

**Comment by dosten** [comment]
@jbrooksuk Not yet, i'll work on it this weekend.

**Comment by jbrooksuk** [comment]
If @dosten or someone else feels like doing this, please do, otherwise it's not something I'll be doing.
