### ISSUE TITLE
count(): Parameter must be an array or an object that implements Countable

### ISSUE THREAD

**Issue by DarkShoro** [CachetHQ/Cachet#4170]
Hello, i've encountered this error after the setup:

`ErrorException thrown with message "count(): Parameter must be an array or an object that implements Countable"

Stacktrace:
#80 ErrorException in /home/foxuaeu/status.dragontech.social/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php:1161
#79 count in /home/foxuaeu/status.dragontech.social/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php:1161
#78 Illuminate\Database\Eloquent\Builder:callScope in /home/foxuaeu/status.dragontech.social/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php:1395
#77 Illuminate\Database\Eloquent\Builder:__call in /home/foxuaeu/status.dragontech.social/bootstrap/cache/compiled.php:11643
#76 call_user_func_array in /home/foxuaeu/status.dragontech.social/bootstrap/cache/compiled.php:11643
#75 Illuminate\Database\Eloquent\Model:__call in /home/foxuaeu/status.dragontech.social/bootstrap/cache/compiled.php:11648
#74 call_user_func_array in /home/foxuaeu/status.dragontech.social/bootstrap/cache/compiled.php:11648
#73 Illuminate\Database\Eloquent\Model:__callStatic in /home/foxuaeu/status.dragontech.social/app/Http/Controllers/StatusPageController.php:85
#72 CachetHQ\Cachet\Http\Controllers\StatusPageController:showIndex in /home/foxuaeu/status.dragontech.social/bootstrap/cache/compiled.php:9419
#71 call_user_func_array in /home/foxuaeu/status.dragontech.social/bootstrap/cache/compiled.php:9419
#70 Illuminate\Routing\Controller:callAction in /home/foxuaeu/status.dragontech.social/bootstrap/cache/compiled.php:9481
#69 Illuminate\Routing\ControllerDispatcher:call in /home/foxuaeu/status.dragontech.social/bootstrap/cache/compiled.php:9461
#68 Illuminate\Routing\ControllerDispatcher:Illuminate\Routing\{closure} in /home/foxuaeu/status.dragontech.social/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php:52
#67 call_user_func in /home/foxuaeu/status.dragontech.social/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php:52
#66 Illuminate\Routing\Pipeline:Illuminate\Routing\{closure} in /home/foxuaeu/status.dragontech.social/bootstrap/cache/compiled.php:9938
#65 call_user_func in /home/foxuaeu/status.dragontech.social/bootstrap/cache/compiled.php:9938
#64 Illuminate\Pipeline\Pipeline:then in /home/foxuaeu/status.dragontech.social/bootstrap/cache/compiled.php:9462
#63 Illuminate\Routing\ControllerDispatcher:callWithinStack in /home/foxuaeu/status.dragontech.social/bootstrap/cache/compiled.php:9449
#62 Illuminate\Routing\ControllerDispatcher:dispatch in /home/foxuaeu/status.dragontech.social/bootstrap/cache/compiled.php:8517
#61 Illuminate\Routing\Route:runController in /home/foxuaeu/status.dragontech.social/bootstrap/cache/compiled.php:8504
#60 Illuminate\Routing\Route:run in /home/foxuaeu/status.dragontech.social/bootstrap/cache/compiled.php:8218
#59 Illuminate\Routing\Router:Illuminate\Routing\{closure} in /home/foxuaeu/status.dragontech.social/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php:52
#58 call_user_func in /home/foxuaeu/status.dragontech.social/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php:52
#57 Illuminate\Routing\Pipeline:Illuminate\Routing\{closure} in /home/foxuaeu/status.dragontech.social/app/Http/Middleware/Localize.php:59
#56 CachetHQ\Cachet\Http\Middleware\Localize:handle in /home/foxuaeu/status.dragontech.social/bootstrap/cache/compiled.php:9953
#55 call_user_func_array in /home/foxuaeu/status.dragontech.social/bootstrap/cache/compiled.php:9953
#54 Illuminate\Pipeline\Pipeline:Illuminate\Pipeline\{closure} in /home/foxuaeu/status.dragontech.social/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php:32
#53 call_user_func in /home/foxuaeu/status.dragontech.social/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php:32
#52 Illuminate\Routing\Pipeline:Illuminate\Routing\{closure} in /home/foxuaeu/status.dragontech.social/app/Http/Middleware/ReadyForUse.php:40
#51 CachetHQ\Cachet\Http\Middleware\ReadyForUse:handle in /home/foxuaeu/status.dragontech.social/bootstrap/cache/compiled.php:9953
#50 call_user_func_array in /home/foxuaeu/status.dragontech.social/bootstrap/cache/compiled.php:9953
#49 Illuminate\Pipeline\Pipeline:Illuminate\Pipeline\{closure} in /home/foxuaeu/status.dragontech.social/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php:32
#48 call_user_func in /home/foxuaeu/status.dragontech.social/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php:32
#47 Illuminate\Routing\Pipeline:Illuminate\Routing\{closure} in /home/foxuaeu/status.dragontech.social/bootstrap/cache/compiled.php:3225
#46 Illuminate\Foundation\Http\Middleware\VerifyCsrfToken:handle in /home/foxuaeu/status.dragontech.social/bootstrap/cache/compiled.php:9953
#45 call_user_func_array in /home/foxuaeu/status.dragontech.social/bootstrap/cache/compiled.php:9953
#44 Illuminate\Pipeline\Pipeline:Illuminate\Pipeline\{closure} in /home/foxuaeu/status.dragontech.social/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php:32
#43 call_user_func in /home/foxuaeu/status.dragontech.social/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php:32
#42 Illuminate\Routing\Pipeline:Illuminate\Routing\{closure} in /home/foxuaeu/status.dragontech.social/bootstrap/cache/compiled.php:13400
#41 Illuminate\View\Middleware\ShareErrorsFromSession:handle in /home/foxuaeu/status.dragontech.social/bootstrap/cache/compiled.php:9953
#40 call_user_func_array in /home/foxuaeu/status.dragontech.social/bootstrap/cache/compiled.php:9953
#39 Illuminate\Pipeline\Pipeline:Illuminate\Pipeline\{closure} in /home/foxuaeu/status.dragontech.social/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php:32
#38 call_user_func in /home/foxuaeu/status.dragontech.social/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php:32
#37 Illuminate\Routing\Pipeline:Illuminate\Routing\{closure} in /home/foxuaeu/status.dragontech.social/bootstrap/cache/compiled.php:11943
#36 Illuminate\Session\Middleware\StartSession:handle in /home/foxuaeu/status.dragontech.social/bootstrap/cache/compiled.php:9953
#35 call_user_func_array in /home/foxuaeu/status.dragontech.social/bootstrap/cache/compiled.php:9953
#34 Illuminate\Pipeline\Pipeline:Illuminate\Pipeline\{closure} in /home/foxuaeu/status.dragontech.social/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php:32
#33 call_user_func in /home/foxuaeu/status.dragontech.social/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php:32
#32 Illuminate\Routing\Pipeline:Illuminate\Routing\{closure} in /home/foxuaeu/status.dragontech.social/bootstrap/cache/compiled.php:13139
#31 Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse:handle in /home/foxuaeu/status.dragontech.social/bootstrap/cache/compiled.php:9953
#30 call_user_func_array in /home/foxuaeu/status.dragontech.social/bootstrap/cache/compiled.php:9953
#29 Illuminate\Pipeline\Pipeline:Illuminate\Pipeline\{closure} in /home/foxuaeu/status.dragontech.social/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php:32
#28 call_user_func in /home/foxuaeu/status.dragontech.social/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php:32
#27 Illuminate\Routing\Pipeline:Illuminate\Routing\{closure} in /home/foxuaeu/status.dragontech.social/bootstrap/cache/compiled.php:13076
#26 Illuminate\Cookie\Middleware\EncryptCookies:handle in /home/foxuaeu/status.dragontech.social/bootstrap/cache/compiled.php:9953
#25 call_user_func_array in /home/foxuaeu/status.dragontech.social/bootstrap/cache/compiled.php:9953
#24 Illuminate\Pipeline\Pipeline:Illuminate\Pipeline\{closure} in /home/foxuaeu/status.dragontech.social/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php:32
#23 call_user_func in /home/foxuaeu/status.dragontech.social/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php:32
#22 Illuminate\Routing\Pipeline:Illuminate\Routing\{closure} in /home/foxuaeu/status.dragontech.social/bootstrap/cache/compiled.php:9938
#21 call_user_func in /home/foxuaeu/status.dragontech.social/bootstrap/cache/compiled.php:9938
#20 Illuminate\Pipeline\Pipeline:then in /home/foxuaeu/status.dragontech.social/bootstrap/cache/compiled.php:8219
#19 Illuminate\Routing\Router:runRouteWithinStack in /home/foxuaeu/status.dragontech.social/bootstrap/cache/compiled.php:8210
#18 Illuminate\Routing\Router:dispatchToRoute in /home/foxuaeu/status.dragontech.social/bootstrap/cache/compiled.php:8200
#17 Illuminate\Routing\Router:dispatch in /home/foxuaeu/status.dragontech.social/bootstrap/cache/compiled.php:2419
#16 Illuminate\Foundation\Http\Kernel:Illuminate\Foundation\Http\{closure} in /home/foxuaeu/status.dragontech.social/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php:52
#15 call_user_func in /home/foxuaeu/status.dragontech.social/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php:52
#14 Illuminate\Routing\Pipeline:Illuminate\Routing\{closure} in /home/foxuaeu/status.dragontech.social/bootstrap/cache/compiled.php:3286
#13 Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode:handle in /home/foxuaeu/status.dragontech.social/bootstrap/cache/compiled.php:9953
#12 call_user_func_array in /home/foxuaeu/status.dragontech.social/bootstrap/cache/compiled.php:9953
#11 Illuminate\Pipeline\Pipeline:Illuminate\Pipeline\{closure} in /home/foxuaeu/status.dragontech.social/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php:32
#10 call_user_func in /home/foxuaeu/status.dragontech.social/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php:32
#9 Illuminate\Routing\Pipeline:Illuminate\Routing\{closure} in /home/foxuaeu/status.dragontech.social/vendor/fideloper/proxy/src/TrustProxies.php:56
#8 Fideloper\Proxy\TrustProxies:handle in /home/foxuaeu/status.dragontech.social/bootstrap/cache/compiled.php:9953
#7 call_user_func_array in /home/foxuaeu/status.dragontech.social/bootstrap/cache/compiled.php:9953
#6 Illuminate\Pipeline\Pipeline:Illuminate\Pipeline\{closure} in /home/foxuaeu/status.dragontech.social/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php:32
#5 call_user_func in /home/foxuaeu/status.dragontech.social/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php:32
#4 Illuminate\Routing\Pipeline:Illuminate\Routing\{closure} in /home/foxuaeu/status.dragontech.social/bootstrap/cache/compiled.php:9938
#3 call_user_func in /home/foxuaeu/status.dragontech.social/bootstrap/cache/compiled.php:9938
#2 Illuminate\Pipeline\Pipeline:then in /home/foxuaeu/status.dragontech.social/bootstrap/cache/compiled.php:2366
#1 Illuminate\Foundation\Http\Kernel:sendRequestThroughRouter in /home/foxuaeu/status.dragontech.social/bootstrap/cache/compiled.php:2350
#0 Illuminate\Foundation\Http\Kernel:handle in /home/foxuaeu/status.dragontech.social/public/index.php:54
`

**Comment by cp-sumi-k** [comment]
Hey @FireWolf-kPanel , try to clear cache using **php artisan config:cache** .

**Comment by FireWolf-kPanel** [comment]
Done, changed nothing

**Comment by rajeevkk32** [comment]
I resolved using

https://github.com/CachetHQ/Cachet/issues/4132#issuecomment-712489727

**Comment by jbrooksuk** [comment]
Thank you for your input on Cachet 2.x. We are shifting our attention and resources to Cachet 3.x and will no longer be supporting the 2.x version. If your feedback or issue is relevant to the 3.x series, we encourage you to engage with the new branch.

For more information on the Cachet rebuild and our plans for 3.x, you can read the announcement [here](https://github.com/CachetHQ/Cachet/discussions/4342).

We appreciate your understanding and look forward to your contributions to the new version.
