### ISSUE TITLE
Update Metric's Default Value Via API

### ISSUE THREAD

**Issue by ThaSami** [CachetHQ/Cachet#4177]
So we are coming to display the UPTIME for a service as a metric which being pushed whenever there is a change in the status. 
however, looks like cachet doesn't have a way to update the default value of metrics via API 
what we are trying to accomplish is simply let the default value = current point value...  so we don't have to keep pushing the value over and over...

**Comment by jbrooksuk** [comment]
Thank you for your input on Cachet 2.x. We are shifting our attention and resources to Cachet 3.x and will no longer be supporting the 2.x version. If your feedback or issue is relevant to the 3.x series, we encourage you to engage with the new branch.

For more information on the Cachet rebuild and our plans for 3.x, you can read the announcement [here](https://github.com/CachetHQ/Cachet/discussions/4342).

We appreciate your understanding and look forward to your contributions to the new version.
