### ISSUE TITLE
Incident not obeying timezone

### ISSUE THREAD

**Issue by jenolan** [cachethq/Cachet#419]
I am in Oz and have set my timezone, when I add an issue the incident is showing as yesterday. Screen shot below, I adding it Oz time 0900 2015-01-25 but it time travelled back to the 24th, I am sure Mr Hawking said that shouldn't happen ;-)
Site is https://jenolan.herokuapp.com/

![screenshot 2015-01-25 09 06 56](https://cloud.githubusercontent.com/assets/1505228/5889275/bd8d31aa-a471-11e4-9b34-642124f48bd8.png)

**Comment by jbrooksuk** [comment]
What timezone did you pick specifically?

**Comment by jenolan** [comment]
Australia/Sydney

**Comment by jbrooksuk** [comment]
That *could* be the problem then. The server time is in America, so the date doesn't change but the time does?

**Comment by jenolan** [comment]
Well the server itself should be UTC, but the PHP may be set to local time, then Cachet is fiddling that again?

**Comment by jbrooksuk** [comment]
In the background Cachet is just setting `app.timezone` to whatever is selected.

CC @GrahamCampbell any advice on this?

**Comment by jenolan** [comment]
By looking at the incident time, it is saying 24/1 2201 that's the UTC time that I posted the incident so the code is calling a UTC function rather than local time?

**Comment by jbrooksuk** [comment]
Seems to be, I think we need to call `Carbon::setTimezone()` or something too. @joecohens any idea on this as you wrote the `LoadConfigServiceProvider`, do you experience it in Mexico?

**Comment by jbrooksuk** [comment]
Alternatively all models need a view presenter for dates, then each date will be chained with:

```php
return $this->resource->created_at->tz(Setting::get('app_timezone'));
```

For example. Thoughts?

**Comment by jbrooksuk** [comment]
Ok, that does seem to make the incident time tooltip show the right time, but the incident is still pulled under the 24th.

Looks like the database server now needs to be aware of the timezone?

**Comment by Jamesking56** [comment]
I think when I had this problem with Laravel before I solved it by setting Laravel's config to UTC and then using Carbon to set the user's timezone when it pulls data from the DB

**Comment by GrahamCampbell** [comment]
@Jamesking56 Yeh, that's what you're meant to do. :)

**Comment by jbrooksuk** [comment]
Ok, so in `LoadConfigServiceProvider` we should call `Carbon::setTimezone()`?

**Comment by GrahamCampbell** [comment]
Maybe, yeh.

**Comment by joecohens** [comment]
I think the solution is to use carbon again to query from the DB and just use the presenter to display the the right TZ https://github.com/cachethq/Cachet/blob/master/src/Http/Controllers/HomeController.php#L31 I'll test this.

**Comment by jbrooksuk** [comment]
I locally tested the presenter by setting the timezone and it did work but then when you fetch the data from the DB, it will still be wrong, especially if in Australia.

**Comment by jbrooksuk** [comment]
Well you can't just call `Carbon::setTimezone` because it's a non-static method and only applies to the instance. This is a paint.

**Comment by jbrooksuk** [comment]
I think we actually need to save the times in the DB with the right timezone.

**Comment by jenolan** [comment]
Normally the database times are UTC for sanity reasons, the displays take the local time zone and modify. Because I could always change timezones ;-)

For the date of the heading (and where the log entries appear) surely the data coming back form the DB select is already date descending, get the newest date form the first record (in UTC) convert that to local time and that is the first heading and the basis for earlier ones.

Dates / timezones and fiddling them always give me a headache.

**Comment by jbrooksuk** [comment]
That makes sense, however the code we currently have wouldn't work that way.

See:

```php
foreach (range(0, $incidentDays) as $i) {
    $date = $startDate->copy()->subDays($i);
    $incidents = Incident::whereBetween('created_at', [
        $date->format('Y-m-d').' 00:00:00',
        $date->format('Y-m-d').' 23:59:59',
    ])->orderBy('created_at', 'desc')->get();
    $allIncidents[] = ['date' => $date->format($dateFormat), 'incidents' => $incidents];
}
```
