### ISSUE TITLE
Icons not Working at all

### ISSUE THREAD

**Issue by Realtox** [CachetHQ/Cachet#4194]
Hey,

i have install CachetHQ on a Debian 10 VM and the Icons not Working.
![cachethqbroken](https://user-images.githubusercontent.com/39673627/103487847-974c5880-4e08-11eb-980e-71bbb54c931e.PNG)
I am using Apache2 with PHP7.3.
Cachet Version: 2.4.0-dev

Can anybody help?

**Comment by Carolkolassa** [comment]
I'm also having this problem. Did you manage to solve it?

**Comment by Carolkolassa** [comment]
I will leave here the solution found.
It is necessary to move the 'fonts' folder out of 'public'. Leaving it in the 'cachet' directory

**Comment by jbrooksuk** [comment]
Thank you for your input on Cachet 2.x. We are shifting our attention and resources to Cachet 3.x and will no longer be supporting the 2.x version. If your feedback or issue is relevant to the 3.x series, we encourage you to engage with the new branch.

For more information on the Cachet rebuild and our plans for 3.x, you can read the announcement [here](https://github.com/CachetHQ/Cachet/discussions/4342).

We appreciate your understanding and look forward to your contributions to the new version.
