### ISSUE TITLE
Improve user management with mass invites and an user api point.

### ISSUE THREAD

**Issue by jerrac** [CachetHQ/Cachet#4199]
I have need to add dozens of users to my Cachet instance. As far as I can tell, you can add users, setting their passwords and other information, or invite users.

Neither option is very easy to use when you get past 10 users. 

My first suggestion is to modify the invite screen to use a textarea. Then admins could paste in lists of emails. Either 1 per line, or use a comma separated list. This would be good for anyone who doesn't mind the accounts being completely specific to their Catchet instance.

My second suggestion is to add an user api endpoint. This would let admins integrate with their other systems and keep the Catchet team member's up to date with whatever source they might use. This would let admins ensure that users are automatically removed, or added, when they should be, and automatically keep passwords up to date.

Let me know if I just missed something that would supersede these ideas. I did search the repo, and peruse the docs and code to try and find a way to do what I want. :)

Thanks!

**Comment by jbrooksuk** [comment]
Thank you for your input on Cachet 2.x. We are shifting our attention and resources to Cachet 3.x and will no longer be supporting the 2.x version. If your feedback or issue is relevant to the 3.x series, we encourage you to engage with the new branch.

For more information on the Cachet rebuild and our plans for 3.x, you can read the announcement [here](https://github.com/CachetHQ/Cachet/discussions/4342).

We appreciate your understanding and look forward to your contributions to the new version.
