### ISSUE TITLE
Syntax error in edit.blade.php

### ISSUE THREAD

**Issue by bimlendu** [cachethq/Cachet#420]
Seems like https://github.com/cachethq/Cachet/blob/master/app/views/dashboard/incidents/edit.blade.php#L31, 
https://github.com/cachethq/Cachet/blob/master/app/views/dashboard/incidents/edit.blade.php#L36 and
https://github.com/cachethq/Cachet/blob/master/app/views/dashboard/incidents/edit.blade.php#L41 are missing a closing brace `}`. This is leading to a syntax error when someone tries to edit an incident from the dashboard.

**Comment by jbrooksuk** [comment]
Thanks :beers:
