### ISSUE TITLE
Add Language Serbian

### ISSUE THREAD

**Issue by elvirmuslic** [CachetHQ/Cachet#4202]
As the title mentiones I've made a post on crowdin or whatever the site is, please add Serbian and let me know when you can integrate it.

**Comment by stamepicmorg** [comment]
i think it is not difficult to add translation by yourself and send PR to authors?

see examples: https://github.com/CachetHQ/Cachet/tree/2.4/resources/lang/en-US

there is just 7 text files with text strings.
