### ISSUE TITLE
Set banner-background-color to empty not working

### ISSUE THREAD

**Issue by weberpatr** [CachetHQ/Cachet#4214]
Hello guys,

I'm using the docker image of Cachet and got one problem, I can't solve without re-installing:
I faulty set a banner-background-color in the UI. Now I want to remove that, so the background is transparent again.
If I remove the value in the UI and save, it does not seem to be saved, as it just stays there.

If I try to set it in the psql database directly, it has also no impact:

```postgres=# select * from chq_settings where id=11;
-[ RECORD 1 ]-----------------------------
id         | 11
name       | style_banner_background_color
value      | #ffffff
created_at | 2021-02-08 14:31:14
updated_at | 2021-02-08 14:38:17

postgres=# update chq_settings set value = '' where id=11;
UPDATE 1
postgres=# select * from chq_settings where id=11;
-[ RECORD 1 ]-----------------------------
id         | 11
name       | style_banner_background_color
value      |
created_at | 2021-02-08 14:31:14
updated_at | 2021-02-08 14:38:17
```
The UI still shows #FFFFFF as color although its not in DB anymore. Restart has also no effect.
Also not able to set the value to NULL:

```
postgres=# update chq_settings set value = NULL where id=11;
ERROR:  null value in column "value" violates not-null constraint
```

Is that a bug in the docker version or its also reproducible in the native version?
Any idea how to solve that?

**Comment by jbrooksuk** [comment]
Thank you for your input on Cachet 2.x. We are shifting our attention and resources to Cachet 3.x and will no longer be supporting the 2.x version. If your feedback or issue is relevant to the 3.x series, we encourage you to engage with the new branch.

For more information on the Cachet rebuild and our plans for 3.x, you can read the announcement [here](https://github.com/CachetHQ/Cachet/discussions/4342).

We appreciate your understanding and look forward to your contributions to the new version.
