### ISSUE TITLE
CORS issue with sharepoint

### ISSUE THREAD

**Issue by nickdrewerbeumer** [CachetHQ/Cachet#4217]
We're currently trying to implement the cachet API in our Microsoft Sharepoint environment.
The target is to show our users an overall status with one sentence on the intranet landing page.

Our current problem is, that we always getting an CORS issue in the browser API when running the request in sharepoint:
![image](https://user-images.githubusercontent.com/68217991/107918217-8e9f8400-6f69-11eb-8906-bc62deb84d9f.png)

`fetch("https://status.beumer.com/api/v1/ping", {
--
  | "method": "GET",
  | "headers": {
  | "X-Cachet-Application": "BEUMERGroup IT Status"
  | }
  | })
  | .then(response => {
  | console.log(response);
  | })
  | .catch(err => {
  | console.error(err);
  | });`

We've tried it with empty security CORS setting which should allow all requests by default and as well with set domain(s) in the security settings.
With Postman the API is working in general.

Does anyone know something which could help or do have anyone knowledge about Cachet API with Sharepoint?

Many thanks in advance!

Kind regards,
Nick Drewer

**Comment by borankoeruek** [comment]
Same issue here.

**Comment by jbrooksuk** [comment]
Thank you for your input on Cachet 2.x. We are shifting our attention and resources to Cachet 3.x and will no longer be supporting the 2.x version. If your feedback or issue is relevant to the 3.x series, we encourage you to engage with the new branch.

For more information on the Cachet rebuild and our plans for 3.x, you can read the announcement [here](https://github.com/CachetHQ/Cachet/discussions/4342).

We appreciate your understanding and look forward to your contributions to the new version.
