### ISSUE TITLE
When editing incident the name is not complet if there is space in it 

### ISSUE THREAD

**Issue by JMousqueton** [cachethq/Cachet#422]
on this line : https://github.com/cachethq/Cachet/blob/master/app/views/dashboard/incidents/edit.blade.php#L21
 you must put double quote for the value {{$incident->name}}

The code must look like this : 

``` <input type="text" class="form-control" name="incident[name]" id="incident-name" required value="{{$incident->name}}">```

**Comment by JMousqueton** [comment]
I propose a pull request #423 to solve this issue

**Comment by GrahamCampbell** [comment]
Thanks.
