### ISSUE TITLE
Username error: not showing the name of the admin

### ISSUE THREAD

**Issue by hks27d** [CachetHQ/Cachet#4230]
There is an error in the incidents reported. 
It is showed username instead of the original name of the administrator who reported the incident.

Cachet 2.4.0-dev, screenshot attached.

![Screenshot_20210302-003059](https://user-images.githubusercontent.com/51793958/109568022-f4a21480-7aee-11eb-923e-24881150856a.jpg)

**Comment by jbrooksuk** [comment]
Thank you for your input on Cachet 2.x. We are shifting our attention and resources to Cachet 3.x and will no longer be supporting the 2.x version. If your feedback or issue is relevant to the 3.x series, we encourage you to engage with the new branch.

For more information on the Cachet rebuild and our plans for 3.x, you can read the announcement [here](https://github.com/CachetHQ/Cachet/discussions/4342).

We appreciate your understanding and look forward to your contributions to the new version.
