### ISSUE TITLE
Ubuntu 20.10, php v7.4.9 cannot install via composer  backup-manager/laravel dev-master requires php ^7.3||^7.4 -> your php version (5.5.9; overridden via config.platform, actual: 7.4.9) does not satisfy that requirement.

### ISSUE THREAD

**Issue by jensolsson** [CachetHQ/Cachet#4234]
Here is the output I get when trying to run composer according to instructions. Seem like there is a limit to php 7.4, is v7.4.9 too high? Dont know if it is even possible to downgrade on Ubuntu 20.10.

```
root@cachet:/var/www/html# sudo -u www-data composer update
Loading composer repositories with package information
Updating dependencies
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Root composer.json requires backup-manager/laravel dev-master#df53f9c9d8c6be5d7a2638f45d54b8fb7bc51e2b -> satisfiable by backup-manager/laravel[dev-master].
    - backup-manager/laravel dev-master requires php ^7.3||^7.4 -> your php version (5.5.9; overridden via config.platform, actual: 7.4.9) does not satisfy that requirement.

Use the option --with-all-dependencies (-W) to allow upgrades, downgrades and removals for packages currently locked to specific versions.
root@cachet:/var/www/html# 

```

Eager to try this out

**Comment by jensolsson** [comment]
Just tried master and it seem to work

**Comment by Sufiyanshaikh123** [comment]
> Just tried master and it seem to work

Can you please provide steps to fix the issue?
I am not sure what you mean by 'master' here.
I will be really thankful

**Comment by jensolsson** [comment]
I just did a
git checkout master

this might be an unstable version though.

**Comment by jbrooksuk** [comment]
https://github.com/behaviorbot/new-issue-welcome

**Comment by jbrooksuk** [comment]
Thank you for your input on Cachet 2.x. We are shifting our attention and resources to Cachet 3.x and will no longer be supporting the 2.x version. If your feedback or issue is relevant to the 3.x series, we encourage you to engage with the new branch.

For more information on the Cachet rebuild and our plans for 3.x, you can read the announcement [here](https://github.com/CachetHQ/Cachet/discussions/4342).

We appreciate your understanding and look forward to your contributions to the new version.
