### ISSUE TITLE
X-Forwarded-Host header spoofing is possible, resulting in the error page linking users to the content of the spoofed header.

### ISSUE THREAD

**Issue by pedramjm** [CachetHQ/Cachet#4236]
**Summary**
When a GET request with the inserted/spoofed header value `X-Forwarded-Host: arbitrary-url.com` is sent to the following endpoint, the **home page** link `<a href>`'s to the content of the `X-Forwarded-Host` value.

https://dev.cachethq.io/non-existent-path i.e. https://dev.cachethq.io/asdfasdf

This affects the error 404 page and seems to be caused by whatever is generating the `$home_url` value:
```
vendor/graham-campbell/exceptions/resources/error.html:     Perhaps you would like to go to our <a href="{{ $home_url }}">home page</a>?
vendor/graham-campbell/exceptions/src/Displayers/HtmlDisplayer.php:     $info['home_url'] = $generator('/');
```

**Example request**
```
GET /asdfasdf HTTP/1.1
Host: dev.cachethq.io
User-Agent: testing
X-Forwarded-Host: evil.com
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
Accept-Language: en-US,en;q=0.5
Accept-Encoding: gzip, deflate
Connection: close
Upgrade-Insecure-Requests: 1
```

![image](https://user-images.githubusercontent.com/22407088/111775300-7d1f0400-88a8-11eb-97a9-e5357c5620f6.png)

**Steps to reproduce**

1. Intercept a GET request to **https://dev.cachethq.io/asdfasdf**, using software such as Burp Suite or Postman
2. Insert the header `X-Forwarded-Host: evil.com`
3. Forward the request
4. Hover over the **home page** link on the displayed page
5. Observe the **https://evil.com** in the bottom of the page

**Comment by jbrooksuk** [comment]
Thank you for your input on Cachet 2.x. We are shifting our attention and resources to Cachet 3.x and will no longer be supporting the 2.x version. If your feedback or issue is relevant to the 3.x series, we encourage you to engage with the new branch.

For more information on the Cachet rebuild and our plans for 3.x, you can read the announcement [here](https://github.com/CachetHQ/Cachet/discussions/4342).

We appreciate your understanding and look forward to your contributions to the new version.
