### ISSUE TITLE
Deploy to Heroku issue

### ISSUE THREAD

**Issue by kylemclaren** [cachethq/Cachet#424]
Getting the following error in the Build step when trying to deploy to Heroku using the button:

```
Build App
There was an issue building your app. This can mean your app.json's project is not a valid Heroku application. Please ensure your app is deployable to Heroku and try again.
```

Cheers.

**Comment by jbrooksuk** [comment]
Can you try again. Heroku pulls this sometimes. I've just deployed a test instance just fine :)

**Comment by kylemclaren** [comment]
Seemed to do the trick, thanks @jbrooksuk!

**Comment by jbrooksuk** [comment]
:)

**Comment by giang757** [comment]
again.
-----> Python app detected
-----> Installing python-3.6.2
-----> Installing pip
-----> Installing requirements with pip
       Collecting Flask==0.10.1 (from -r /tmp/build_84fb4076e2c39ee3c19599819144e05a/twilio-mobile-quickstart-7a9a1e0/requirements.txt (line 1))
         Downloading Flask-0.10.1.tar.gz (544kB)
       Collecting Jinja2==2.7.3 (from -r /tmp/build_84fb4076e2c39ee3c19599819144e05a/twilio-mobile-quickstart-7a9a1e0/requirements.txt (line 2))
         Downloading Jinja2-2.7.3.tar.gz (378kB)
       Collecting MarkupSafe==0.23 (from -r /tmp/build_84fb4076e2c39ee3c19599819144e05a/twilio-mobile-quickstart-7a9a1e0/requirements.txt (line 3))
         Downloading MarkupSafe-0.23.tar.gz
       Collecting Werkzeug==0.9.6 (from -r /tmp/build_84fb4076e2c39ee3c19599819144e05a/twilio-mobile-quickstart-7a9a1e0/requirements.txt (line 4))
         Downloading Werkzeug-0.9.6.tar.gz (1.1MB)
       Collecting httplib2==0.9 (from -r /tmp/build_84fb4076e2c39ee3c19599819144e05a/twilio-mobile-quickstart-7a9a1e0/requirements.txt (line 5))
         Downloading httplib2-0.9.zip (209kB)
       Collecting itsdangerous==0.24 (from -r /tmp/build_84fb4076e2c39ee3c19599819144e05a/twilio-mobile-quickstart-7a9a1e0/requirements.txt (line 6))
         Downloading itsdangerous-0.24.tar.gz (46kB)
       Collecting six==1.* (from -r /tmp/build_84fb4076e2c39ee3c19599819144e05a/twilio-mobile-quickstart-7a9a1e0/requirements.txt (line 7))
         Downloading six-1.10.0-py2.py3-none-any.whl
       Collecting twilio==3.6.9 (from -r /tmp/build_84fb4076e2c39ee3c19599819144e05a/twilio-mobile-quickstart-7a9a1e0/requirements.txt (line 8))
         Downloading twilio-3.6.9-py2.py3-none-any.whl (163kB)
       Collecting wsgiref==0.1.2 (from -r /tmp/build_84fb4076e2c39ee3c19599819144e05a/twilio-mobile-quickstart-7a9a1e0/requirements.txt (line 9))
         Downloading wsgiref-0.1.2.zip
           Complete output from command python setup.py egg_info:
           Traceback (most recent call last):
             File "<string>", line 1, in <module>
             File "/tmp/pip-build-qespbkoj/wsgiref/setup.py", line 5, in <module>
               import ez_setup
             File "/tmp/pip-build-qespbkoj/wsgiref/ez_setup/__init__.py", line 170
               print "Setuptools version",version,"or greater has been installed."
                                        ^
           SyntaxError: Missing parentheses in call to 'print'
           
           ----------------------------------------
       Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-qespbkoj/wsgiref/
 !     Push rejected, failed to compile Python app.
 !     Push failed

**Comment by jbrooksuk** [comment]
Heroku support is no longer https://blog.alt-three.com/dropping-native-heroku-support/
