### ISSUE TITLE
No Emails for Scheduled Maintenance

### ISSUE THREAD

**Issue by kersthien** [CachetHQ/Cachet#4242]
Hi, 

we have an issue with Cachet 2.4.
It doesn't send emails for Scheduled Maintenance, if you did not subscribe to all components.

Could you please help here?

Thank you and best regards,
Kerstin

**Comment by Lurkars** [comment]
For me maintenance mails not send at all, even for subscribers of all components.

Edit: as stated out by @pavog it was an issue with my queue setup (just forgot to enable on reboot), so my bad.

**Comment by pavog** [comment]
> For me maintenance mails not send at all, even for subscribers of all components.

Hello, as scheduled maintenance email notifications are queued, you need to run the queue worker to send the emails. You can start the worker with the Artisan command `php artisan queue:work`.
Alternatively, you can set up a supervisor to (re)start the queue worker. See [Laravel:Queues](https://laravel.com/docs/5.8/queues#supervisor-configuration) documentation for more information on supervisor and queues.


I found this page on the docs: [Configuring the Queue ](https://docs.cachethq.io/docs/configuring-the-queue)

**Comment by pavog** [comment]
So: The SendScheduleEmailNotificationHandler only sends notifications to subscribers who have subscribed globally (for all components), as you can see [here](https://github.com/CachetHQ/Cachet/blob/2.4/app/Bus/Handlers/Events/Schedule/SendScheduleEmailNotificationHandler.php#L59). 
I think there was a feature planned that would allow you to create scheduled maintenance only for specific components, like you can do with incidents. But this feature was never implemented.

We have two ways to solve this problem:
1. Remove the isGlobal() filter from the subscriber list to send scheduled maintenance notifications to all subscribers (regardless of whether they subscribe to a specific component or all components).
2. Implement the function to schedule maintenance for specific components only, and add the function to notify the remaining component-specific subscribers, as in [SendIncidentEmailNotificationHandler](https://github.com/CachetHQ/Cachet/blob/2.4/app/Bus/Handlers/Events/Incident/SendIncidentEmailNotificationHandler.php#L82)

**Comment by jbrooksuk** [comment]
Thank you for your input on Cachet 2.x. We are shifting our attention and resources to Cachet 3.x and will no longer be supporting the 2.x version. If your feedback or issue is relevant to the 3.x series, we encourage you to engage with the new branch.

For more information on the Cachet rebuild and our plans for 3.x, you can read the announcement [here](https://github.com/CachetHQ/Cachet/discussions/4342).

We appreciate your understanding and look forward to your contributions to the new version.
