### ISSUE TITLE
Sorting the component seems broken 

### ISSUE THREAD

**Issue by JMousqueton** [cachethq/Cachet#426]
Since couple of days (I do not know since when exactly) , we cannot  sort the component by moving them and there is no more pop-up on the top saying it's done as previously. 
We just update to the last "master" version. 

I found the following error in error.log from httpd : 
`[Mon Jan 26 20:18:28 2015] [error] [client 192.168.0.71] PHP Fatal error:  Call to a member function update() on null in /var/www/src/Http/Controllers/DashAPIController.php on line 44, referer: http://192.168.0.84/dashboard/components`

**Comment by JMousqueton** [comment]
For me this bug is still present 
And there is nothing in relation with my pull request #427

**Comment by jbrooksuk** [comment]
I forgot to commit a file - whoops.

Your pull request just removes the input, but as I said, it's needed.

**Comment by JMousqueton** [comment]
I understood for the pool request and I agree with you the hidden field is need,

**Comment by jbrooksuk** [comment]
It'll work now though :)

**Comment by JMousqueton** [comment]
thank you, but I think you misunderstood the issue. 
this issue is NOT about group_id it's about the fact that I cannot change the order of the  components

**Comment by jbrooksuk** [comment]
Ok, that's a separate issue. At least half of it is fixed.

**Comment by jbrooksuk** [comment]
Regarding the component order, I'm able to change it via drag and drop on the components page?

**Comment by jbrooksuk** [comment]
What DB are you using?

**Comment by JMousqueton** [comment]
i'm using mysql

**Comment by jbrooksuk** [comment]
Ok, so what happens? Do you get the confirm alert message?

![image](https://cloud.githubusercontent.com/assets/246103/5907644/79e5f7ca-a598-11e4-9cce-cb31ad05b6a3.png)

**Comment by JMousqueton** [comment]
I do not have it> I only an error message in my error.log from httpd
It worked in the past.

**Comment by jbrooksuk** [comment]
What's the error message? That'll help me debug it :)

**Comment by JMousqueton** [comment]
The one from my issue :-1: 

`[Mon Jan 26 20:18:28 2015] [error] [client 192.168.0.71] PHP Fatal error: Call to a member function update() on null in /var/www/src/Http/Controllers/DashAPIController.php on line 44, referer: http://192.168.0.84/dashboard/components`

**Comment by jbrooksuk** [comment]
What browser are you using?

**Comment by JMousqueton** [comment]
Firefox, Safari on Mac
and Chrome and IE on Windows

**Comment by JMousqueton** [comment]
I re-install everything and it work like a charm :+1: 
 
`git clone https://github.com/cachethq/Cachet www
cd  www
npm install -g bower
npm install -g gulp
npm update
bower install
bower install --allow-root
gulp
vi .env.local.php 
composer install --no-dev -o
php artisan migrate
cd ..
chown -R www-data www`

sorry about it

**Comment by jbrooksuk** [comment]
Awesome! No problem, thanks for helping us find another issue in the process :beers:

**Comment by JMousqueton** [comment]
For your information, my team and I were thinking of the same application. We planned to develop it this year and I found by chance your application few weeks ago. So we will begin to use it internally during February and after to all IT dept.

**Comment by jbrooksuk** [comment]
That's great news :) please let us know how you get on. Remember that currently Cachet is in beta, so if you'd like to contribute with issues or even PR's to add missing features etc, that'd be really appreciated!

**Comment by JMousqueton** [comment]
For your information the sorting problem reappear after rebooting the server 

[Mon Jan 26 23:39:26 2015] [error] [client 192.168.0.71] PHP Fatal error:  Call to a member function update() on null in /var/www/src/Http/Controllers/DashAPIController.php on line 44, referer: http://192.168.0.84/dashboard/components
