### ISSUE TITLE
Maintenance shown as incident.

### ISSUE THREAD

**Issue by denisvjcr** [cachethq/cachet#4265]
Hi  People

I just installed Cachet  but today I noticed that when I create a maintenance it is shown as incident , is not happening with every maintenance , i could say 50-50 shows as maintenance.

Am I doing something wrong?

Thanks

<img width="1058" alt="Screen Shot 2021-04-16 at 1 13 25 PM" src="https://user-images.githubusercontent.com/38451060/115073705-f284f100-9eb5-11eb-99bf-383a290f4146.png">
<img width="1423" alt="Screen Shot 2021-04-16 at 1 13 33 PM" src="https://user-images.githubusercontent.com/38451060/115073715-f57fe180-9eb5-11eb-8328-5508b06363d1.png">

**Comment by denisvjcr** [comment]
I just noticed that if the maintenance is created with the date and time older or equal to the actual time , is created as incident.

**Comment by jbrooksuk** [comment]
Thank you for your input on Cachet 2.x. We are shifting our attention and resources to Cachet 3.x and will no longer be supporting the 2.x version. If your feedback or issue is relevant to the 3.x series, we encourage you to engage with the new branch.

For more information on the Cachet rebuild and our plans for 3.x, you can read the announcement [here](https://github.com/CachetHQ/Cachet/discussions/4342).

We appreciate your understanding and look forward to your contributions to the new version.
