### ISSUE TITLE
Request for security contact

### ISSUE THREAD

**Issue by thomas-chauchefoin-sonarsource** [cachethq/cachet#4270]
Hi! [We](https://github.com/SonarSourceResearch/) tried to contact the various email addresses found in `README.md` to report a security issue, but we haven't heard back so far. Is there a specific address where we can send our analysis to? Another solution is to create a [Security Advisory](https://docs.github.com/en/code-security/security-advisories/creating-a-security-advisory) and invite me to it so we can discuss it privately. Thanks!

**Comment by pavog** [comment]
Hi, this might be related to #4271

**Comment by 1resu** [comment]
@thomas-chauchefoin-sonarsource Maybe you can report it to the [fork's](https://github.com/fiveai/Cachet) issue tracker as the original project seams to be inactive.

**Comment by thomas-chauchefoin-sonarsource** [comment]
I sent a message to github@five.ai but no response so far. cc @sedan07 maybe?

**Comment by qwertiko** [comment]
@thomas-chauchefoin-sonarsource I would be happy to discuss. would you care to send a message to support@qwertiko.de, we can then arrange for a meeting to discuss this further.

**Comment by thomas-chauchefoin-sonarsource** [comment]
@qwertiko we will only discuss these bugs with the upstream project or an active fork adopted by the community, sorry.

**Comment by qwertiko** [comment]
@thomas-chauchefoin-sonarsource I appreciate that. I just wanted to point you to the commit history of the fiveai fork, but I did that with my personal account. appologies.

**Comment by dihedral** [comment]
@thomas-chauchefoin-sonarsource I would be interested in fixing the issue with a pull request, as I have provided in the fiveai branch. Please feel free to contact me at support@qwertiko.de
Alternatively, @sedan07 would be your guy. I am just not sure what is availability would be.
If you want, I would listen to your concerns and discuss the fix with fiveai so that we can provide a fix without making the issue known beforehand.

**Comment by thomas-chauchefoin-sonarsource** [comment]
@sedan07 just contacted me by email 👍

**Comment by dihedral** [comment]
perfect.

**Comment by thomas-chauchefoin-sonarsource** [comment]
The issues are being addressed and patches will be available in the [FiveAI fork](https://github.com/fiveai/Cachet/).
