### ISSUE TITLE
Project status of Cachet

### ISSUE THREAD

**Issue by pavog** [cachethq/cachet#4271]
Hello all!
I would like to point out the status of cachet and would like to know (from someone responsible) if it is correct.
I would also like to have the legal status of cachet clarified.
Especially because it is listed as a software project under the BSD-3-Clause License, but the product is owned by a company.

##### I did some research and found the following:
 - Cachet is a software project created by the Alt Three Services Limited (owned by @jbrooksuk). Source: [https://cachethq.io/press](https://cachethq.io/press)
 - In June 2018, apilayer have acquired Cachet. Source: blog.alt-three.com on [web.archive.org](http://web.archive.org/)
 - In Jan 2021 Idera have acquired apilayer. Source: [https://finance.yahoo.com/news](https://finance.yahoo.com/news/idera-inc-acquires-apilayer-140000766.html)

##### To sum it up in a few questions:
 - Is there someone responsible for maintaining this project, or will there be in the future?
 - How is the legal status of this project? I do not want to do work for a (big) company on one of their products when they can decide to shut it down from one day to the next.
 - If someone in the community feels responsible for maintaining this project / a fork, perhaps we should move our work to a fork?
   - And if so, should we use an existing fork (fiveai perhaps) or create a new one?
   - And if so, should we create a "hard" fork or one on GitHub?

Maybe someone responsible for this project is reading along and can clarify some of these points.
Or someone more familiar with the legal issues.
I am also interested in opinions from the community, contributors and users of this project.

---
One more note: 
I like using Cachet and I would like to contribute to its development in the future. 
However, I don't want to be the main/core maintainer of it.
Also, I don't want to spend a lot of my free time on an open source project whose legal situation is not clear (to me). 
I don't want to work for a company without being paid.

**Comment by jamesfryer** [comment]
See #4037, #4197 

There is also a fork at https://github.com/fiveai/Cachet

**Comment by jbrooksuk** [comment]
Hey 👋 

Please check out https://github.com/CachetHQ/Cachet/discussions/4342

TLDR; Cachet is back! 🎉
