### ISSUE TITLE
Metrics not showing on home screen

### ISSUE THREAD

**Issue by vetsolution** [cachethq/cachet#4279]
Hello, 

I setup a metric, added some datas on it,  but I can see the metrics graph on home screen, I canot see it anywhere infact.
I already clear all cache (config/ bootstrap) and give 777 permission) and I have no error in browser and server logs.

Can you help me to identify what is going wrong ?
Link to metrics datas https://status.arkdevel.be/api/v1/metrics/1/points

Also there is no documentation on the official docs, what is the purpose of suffix ? Is it possible to link a metrics to a Components ? 

Regards

**Comment by vetsolution** [comment]
Fixed by enabling  it in APPLICATION SETUP.

An documentation should be a big plus, I spend 10h on this ;)

**Comment by pavog** [comment]
Then you might want to open an issue report on [CachetHQ/Docs](https://github.com/CachetHQ/Docs).
