### ISSUE TITLE
Heroku - Show version information

### ISSUE THREAD

**Issue by jenolan** [cachethq/Cachet#428]
When deploying to HeroKu it can be a bit of a task to 'see' what codebase is actually installed. Would it be possible to somewhere in the dashboard to show the git id (either the sha or full) just to make it easier.

Update: I found in the HeroKu system that the pushes can be seen, but it would be nice if it were visible within Cachet

Thanks
Larry

**Comment by jbrooksuk** [comment]
We could probably integrate this into #109.
