### ISSUE TITLE
Incidents not showing up glitch

### ISSUE THREAD

**Issue by dillfrescott** [cachethq/cachet#4280]
When the box under `settings > Application Setup` titled: `Only show days containing incidents in the timeline?` is checked, no Incidents show up at all.

I am running Cachet via Docker on Ubuntu 20.04 LTS.

**Comment by jbrooksuk** [comment]
Thank you for your input on Cachet 2.x. We are shifting our attention and resources to Cachet 3.x and will no longer be supporting the 2.x version. If your feedback or issue is relevant to the 3.x series, we encourage you to engage with the new branch.

For more information on the Cachet rebuild and our plans for 3.x, you can read the announcement [here](https://github.com/CachetHQ/Cachet/discussions/4342).

We appreciate your understanding and look forward to your contributions to the new version.
