### ISSUE TITLE
Change mail subject

### ISSUE THREAD

**Issue by denisvjcr** [cachethq/cachet#4285]
Hi,

I want to change the email subject but can't find the file notifications.php in Cachet/resources/lang/en-US .

The only files there are :

cachet.php
dashboard.php
forms.php
pagination.php
setup.php
validation.php

I have versión 2.3.18 installed.

Thanks

**Comment by jbrooksuk** [comment]
Thank you for your input on Cachet 2.x. We are shifting our attention and resources to Cachet 3.x and will no longer be supporting the 2.x version. If your feedback or issue is relevant to the 3.x series, we encourage you to engage with the new branch.

For more information on the Cachet rebuild and our plans for 3.x, you can read the announcement [here](https://github.com/CachetHQ/Cachet/discussions/4342).

We appreciate your understanding and look forward to your contributions to the new version.
