### ISSUE TITLE
Cachet v2.3.18 404 on Incident updates

### ISSUE THREAD

**Issue by kromonos** [cachethq/cachet#4288]
As of https://github.com/CachetHQ/Cachet/issues/3529 I have this issue on v2.3.18.
```bash
curl --request GET \
  --url https://status.my.cachet/api/v1/incidents/34/updates \
  --header 'Accept: application/json' \
  --header 'Content-Type: application/json' \
  --header 'X-Cachet-Application: Demo'
```
returns:
```json
{
    "errors":
    [
        {
            "id": "a8b68cb4-4308-49bd-9529-012251847f8f",
            "status": 404,
            "title": "Not Found",
            "detail": "The requested resource could not be found but may be available again in the future."
        }
    ]
}
```

Same error when I want to create an update. Is this feature disabled? I also wasn't able to find something similar in the dashboard.

**Comment by TH3VenGeuR** [comment]
Hey @kromonos, "Updates" feature is not implemented in 2.3.X (https://github.com/CachetHQ/Cachet/issues/2780#issuecomment-339332267). I personally built a docker image with 2.4 version of Cachet and it works fine.
