### ISSUE TITLE
mouseover text on incident status icon 

### ISSUE THREAD

**Issue by JMousqueton** [cachethq/Cachet#429]
This is an  enhancement / design  

In the main page, could you add a text on mouseover the event status icon to explain what the icon means with this  {{ trans('forms.incidents.status') }}  ?

Thanks in advance

**Comment by jbrooksuk** [comment]
I keep meaning to do this :)

**Comment by jbrooksuk** [comment]
Done! I'm not sure on the positioning, but it looks nice.

**Comment by JMousqueton** [comment]
We like.  Thank you so much !

**Comment by jbrooksuk** [comment]
No problem buddy :)
