### ISSUE TITLE
Cachet is using all of my memory

### ISSUE THREAD

**Issue by vanlueckn** [cachethq/cachet#4290]
Since i installed cachet on my php / nginx webserver, i have an issue with a memory leak. The cachet php-fpm processes are consuming all of my free memory:

https://img.tkde.link/H4qohT.png

The cachet instance has very little traffic and currently no registered incidents.

**Comment by timgws** [comment]
What version of PHP are you using? I am using 7.1.33 with nginx, and I can't see this problem. What are your php-fpm settings? Maybe having less children might help? Without more specific information, though, it's hard to diagnose.

What are your:
* php.ini config?
* mysql version
* php version
* nginx version
* kernel version 
* distro/distro release

**Comment by Chrisx84** [comment]
that isnt a cachet issue, that a server issue. either your web server like apache or nginx is configured or installed wrong or your php. I can see apache using up resources and thats why most of us web devs use nginx now.
