### ISSUE TITLE
Metric's not functioning properly.

### ISSUE THREAD

**Issue by PersonalDom** [cachethq/cachet#4294]
Hey there! 

I run a Minecraft Server Network, and I'm currently using Cachet to keep people updated on the status of all of our assets.

I'm using a metric to show the count of players across all of our Minecraft servers. When creating the metric, we've used a 2 minute threshold and 'Sum'.

However, we noticed that if a player is online for 2 minutes, Cachet shows 2 players online.

Duration | Cachet Shows | Actual Count
---------- | --------------- | --------------
2 Minutes | 2 Players | 1 Player
4 Minutes | 4 Players | 1 Player

(you get the idea.)
The best way to explain it is:
The plugin updates the api every 2 minutes with the player count.
Cachet adds 1 player to the total every 2 minutes.

So we tried using Average, but this provides inaccurate data.

We've updated our code to only update the api *if* there's a change in the player count.

This also had an issue. Cachet on update, automatically returns to 0. So.. When the player joins, the first API Update is one, if the player count stays the same, the next 2 minute point returns back to 0. We need to it to stay at 1 to resemble the 1 player that's still online.
![](https://images-ext-1.discordapp.net/external/xdGr426xu55dyV5A8W0tsih7mYOsNoSv-C-Tcm3HuFQ/http/pdom.icu/url/uv6er)

We're also noticing that *only* the past 12 hours view is working. All of the other views including past hour shows no data. (flat line)

**Comment by jbrooksuk** [comment]
Thank you for your input on Cachet 2.x. We are shifting our attention and resources to Cachet 3.x and will no longer be supporting the 2.x version. If your feedback or issue is relevant to the 3.x series, we encourage you to engage with the new branch.

For more information on the Cachet rebuild and our plans for 3.x, you can read the announcement [here](https://github.com/CachetHQ/Cachet/discussions/4342).

We appreciate your understanding and look forward to your contributions to the new version.
