### ISSUE TITLE
Trying to get in touch regarding a security issue

### ISSUE THREAD

**Issue by zidingz** [cachethq/cachet#4297]
Hi there,

I couldn't find a `SECURITY.md` in your repository and am not sure how to best contact you privately to disclose a security issue.

Can you add a `SECURITY.md` file with an e-mail to your repository, so that our system can send you the vulnerability details? GitHub suggests that a [security policy](https://docs.github.com/en/code-security/getting-started/adding-a-security-policy-to-your-repository) is the best way to make sure security issues are responsibly disclosed.

Once you've done that, you should receive an e-mail within the next hour with more info.

Thanks! (cc @huntr-helper)

**Comment by pavog** [comment]
Since the project is more or less abandoned, it probably won't happen.
See
- #4271 
- #4270 

for more info.

**Comment by thomas-chauchefoin-sonarsource** [comment]
@zidingz: you may want to contact @sedan07, who is maintaining the [FiveAI fork](https://github.com/fiveai/Cachet/). I could not get in touch with the upstream maintainers so I sent my security advisories to the fork instead.

**Comment by zidingz** [comment]
@thomas-chauchefoin-sonarsource Thank you very much, appreciate the advice!
