### ISSUE TITLE
PHP 8 compatbility

### ISSUE THREAD

**Issue by 2ge** [cachethq/cachet#4298]
Hi

considering to install this, but can not find if it will run on PHP 8 ? Thanks.

**Comment by mbh-dev** [comment]
Short answer ... no
Unfortunately it doesn't and has issues with PHP 7.*

**Comment by jbrooksuk** [comment]
Thank you for your input on Cachet 2.x. We are shifting our attention and resources to Cachet 3.x and will no longer be supporting the 2.x version. If your feedback or issue is relevant to the 3.x series, we encourage you to engage with the new branch.

For more information on the Cachet rebuild and our plans for 3.x, you can read the announcement [here](https://github.com/CachetHQ/Cachet/discussions/4342).

We appreciate your understanding and look forward to your contributions to the new version.
