### ISSUE TITLE
[Request] Status up/down bar inline

### ISSUE THREAD

**Issue by davidjmorin** [cachethq/cachet#4299]
Not sure how to explain it, but would love to see a status bar inline with the website monitored.  I will post an image for illustration.  Photoshop added info.

![image](https://user-images.githubusercontent.com/9400895/127363516-8480aba2-80ba-46d5-a747-5bf673616f72.png)

**Comment by jbrooksuk** [comment]
Thank you for your input on Cachet 2.x. We are shifting our attention and resources to Cachet 3.x and will no longer be supporting the 2.x version. If your feedback or issue is relevant to the 3.x series, we encourage you to engage with the new branch.

For more information on the Cachet rebuild and our plans for 3.x, you can read the announcement [here](https://github.com/CachetHQ/Cachet/discussions/4342).

We appreciate your understanding and look forward to your contributions to the new version.

(P.s. I'd like to include this option in the 3.x release).
