### ISSUE TITLE
Error in laravel.log on POSTing incident using API.

### ISSUE THREAD

**Issue by bimlendu** [cachethq/Cachet#430]
Hi,

When I try to submit an incident from API, the incident is successfully submitted and reflected in the UI, but this error is reported in `laravel.log`.

```[2015-01-27 21:06:54] production.ERROR: exception 'ErrorException' with message 'Argument 1 passed to Illuminate\Database\Grammar::columnize() must be of the type array, string given, called in /usr/share/nginx/html/status/vendor/laravel/framework/src/Illuminate/Database/Query/Grammars/Grammar.php on line 105 and defined' in /usr/share/nginx/html/status/vendor/laravel/framework/src/Illuminate/Database/Grammar.php:97```

Same error is occurs on POSTing to component API as well. The POSTed data is reflected in CachetHQ though.

Full incident log here: http://pastebin.com/cqs6crHK

I am testing with curl and the response is probably the html dump of the pretty-printed error page.

```curl -X POST -H "Content-Type: application/json" -H "X-Cachet-Token: xxxxxxxxxxxxxxxxxxxx" http://status.example.com/api/incidents -d '{"name":"Something broke.","message":"Something is wrong.","component_id":4,"status":1}'```

**Comment by jbrooksuk** [comment]
Are you using the latest version?

**Comment by jbrooksuk** [comment]
It doesn't matter, I'm experiencing this issue too.

**Comment by jbrooksuk** [comment]
Fixed :) The issue was in the `AllowedDomainsFilter` we hadn't switched the old model out for the new facade repository we use to fetch settings.
