### ISSUE TITLE
S.O.S

### ISSUE THREAD

**Issue by Arthurpeas** [cachethq/cachet#4300]
SQLSTATE[HY000]: General error: 8 attempt to write a readonly database (SQL: create table "migrations" ("id" integer not null primary key autoincrement, "migration" varchar not null, "batch" integer not null))

**Comment by pavog** [comment]
Hi @Arthurpeas, you might want to try using the fork from FiveAI at https://github.com/fiveai/Cachet. I think this problem has been solved.

**Comment by tomck** [comment]
Just a note for future people, the maintainer left fiveAI so that fork is not maintained either. https://github.com/fiveai/Cachet/issues/80#issuecomment-1052440677_

**Comment by jbrooksuk** [comment]
Thank you for your input on Cachet 2.x. We are shifting our attention and resources to Cachet 3.x and will no longer be supporting the 2.x version. If your feedback or issue is relevant to the 3.x series, we encourage you to engage with the new branch.

For more information on the Cachet rebuild and our plans for 3.x, you can read the announcement [here](https://github.com/CachetHQ/Cachet/discussions/4342).

We appreciate your understanding and look forward to your contributions to the new version.
