### ISSUE TITLE
Incident occured_at problem with API

### ISSUE THREAD

**Issue by beratclk** [cachethq/cachet#4303]
Hi,

We share the incident in Cachet application with the help of API. This incident is being sent from the Jira app. We send the date of incident was opened in Jira in the "created_at" field in the body part, but "When did this incident occur?" does not affect the field. With which parameter can I send the date to be entered for this field in the body using the API?

Thanks,

Berat.

**Comment by jbrooksuk** [comment]
Thank you for your input on Cachet 2.x. We are shifting our attention and resources to Cachet 3.x and will no longer be supporting the 2.x version. If your feedback or issue is relevant to the 3.x series, we encourage you to engage with the new branch.

For more information on the Cachet rebuild and our plans for 3.x, you can read the announcement [here](https://github.com/CachetHQ/Cachet/discussions/4342).

We appreciate your understanding and look forward to your contributions to the new version.
