### ISSUE TITLE
Skip Webinstall in Docker

### ISSUE THREAD

**Issue by Bakpfeife** [cachethq/cachet#4309]
Hi,
I have tried doing a docker install and using a Dockerfile with all the Config files included in order to skip the Browser Install,
but I don't seem to be able to skip that step.
What files are created and changed in the Browser Install step?
Can you do such a Docker Install without doing weird php magic?

I could of course just create an Image out of the finished install directly but its bad practice to do that instead of using a Dockerfile so I would prefer not to do that.

Thanks in advance for helping out even if its just a small bit of advice.

**Comment by matiri132** [comment]
I'm looking for a solution on this issue too.
@Bakpfeife have you any solution for this?

**Comment by Bakpfeife** [comment]
Avoided the issue myself honestly.

After you did the web-install once you basically need to save the database as a volume so that it stays permanent.
https://docs.docker.com/storage/volumes/
You can restart the whole stack without issues even though I have about a dozen monitoring dockers that use the cachet-api attached.

I attached a compose file similar to the one I use now that might elaborate on what I mean.


```
version: "3.3"

services:
  postgres-ch:
    image: postgres:12-alpine
    volumes:
      - cachet-db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  cachet:
    image: cachet:2.7 #own edited cachet version
    links:
      - postgres-ch
    volumes:
      - cachet-data:/var/www/html/cachet/bootstrap/cachet/ #my volumes, via portainer, use own paths
      - cachet-data:/var/www/html/cachet/config/

    environment:
      - DB_DRIVER=pgsql
      - DB_HOST=postgres-ch
      - DB_PORT=5432
      - DB_DATABASE=postgres
      - DB_USERNAME=postgres
      - DB_PASSWORD=postgres
      - DB_PREFIX=chq_
      - APP_KEY=base64:<INSERTYOURKEY>
      - APP_URL=website.url.here
      - APP_LOG=errorlog
      - APP_ENV=${APP_ENV:-production}
      - APP_DEBUG=false
      - DEBUG=false
    depends_on:
       - postgres-ch
    restart: always
```

**Comment by matiri132** [comment]
In my case i'm deploying cachet on K8s (in AWS EKS) and i make a Helm Chart that uses RDS as Database. And i'm working with a cachet-url-monitor as sidecar thats set the status of each endpoint.
So what i want to do is a automated configuration of cachet, because i want to run a "helm install ..." and get all the deploy configured .

Maybe if its possible to make the web configuration via API i can make a setup script.

**Comment by jbrooksuk** [comment]
Thank you for your input on Cachet 2.x. We are shifting our attention and resources to Cachet 3.x and will no longer be supporting the 2.x version. If your feedback or issue is relevant to the 3.x series, we encourage you to engage with the new branch.

For more information on the Cachet rebuild and our plans for 3.x, you can read the announcement [here](https://github.com/CachetHQ/Cachet/discussions/4342).

We appreciate your understanding and look forward to your contributions to the new version.
