### ISSUE TITLE
Automated setup

### ISSUE THREAD

**Issue by matiri132** [cachethq/cachet#4310]
Hi! i'm working on a full automated instalation and configuration of cachet in a K8S cluster running in AWS EKS.
The full deploy that i made includes cachet-url-monitor to keep updated the components of cachet.
My problem is what when i deploy i need to make the first instalation via browser, and i'm looking a way to automatizates the first setup and create an admin user.
Talking directly to the database (an AWS RDS PostgreSQL ) i can create an user, and basic settings, but i still getting the /setup page. 
I think this is because the setup creates an entry in the chq_cache table of the PostgreSQL.
So my question is if its possible to configurate Cachet posting directly to the database or running some "setup script" from the Cachet instance.

**Comment by danieljayseelan** [comment]
@matiri132 Were you able to resolve this issue? I am stuck with the exact same situation

**Comment by danieljayseelan** [comment]
@jbrooksuk Can you please suggest onto what can be done for this case?
