### ISSUE TITLE
Update Incident status

### ISSUE THREAD

**Issue by ghost** [cachethq/cachet#4311]
Hello, I would like to know if there is any way to record the events and incidents with start and end date/time of the events in a single incident record. Or if in fact I will have to create new incidents to update the statuses. Attached image demonstrating example.

![image](https://user-images.githubusercontent.com/29412131/149156806-e8332fa7-6357-4afa-b398-85195447f2aa.png)

**Comment by ghost** [comment]
The attached image is from another application we used in the past. At the moment I'm using Cachet I haven't found any possibility to handle this in the same incident. I was able to simulate something close by creating a new incident.

**Comment by jbrooksuk** [comment]
Thank you for your input on Cachet 2.x. We are shifting our attention and resources to Cachet 3.x and will no longer be supporting the 2.x version. If your feedback or issue is relevant to the 3.x series, we encourage you to engage with the new branch.

For more information on the Cachet rebuild and our plans for 3.x, you can read the announcement [here](https://github.com/CachetHQ/Cachet/discussions/4342).

We appreciate your understanding and look forward to your contributions to the new version.
