### ISSUE TITLE
Cachet is advertising href with the port 8000 when being behind a nginx reverse proxy

### ISSUE THREAD

**Issue by JAKAMI99** [cachethq/cachet#4312]
When using Cachet with an NGINX Reverse Proxy which is serving Cachet under a subdomain with https under the port 443, it suddenly starts advertising the path for scripts and the css stylesheet with the default port 8000 which is of course not reachable for an external connection.

![grafik](https://user-images.githubusercontent.com/31528087/150311564-7e551c35-8669-47dd-b07a-096a7332d0cc.png)

Resulting in a total mess of a website and huge loading times until the connection for the scripts times out:

![grafik](https://user-images.githubusercontent.com/31528087/150311193-748d78a3-ad71-4f12-b2e3-a886edf0b9a5.png)

While it works internal in the network since the port makes sense

![grafik](https://user-images.githubusercontent.com/31528087/150311040-dd22e5d6-ba4d-4b7a-b2f9-b291cd33e4ec.png)

This is super weird since I don't have this issue for all my other subdomains and the problem just started appearing for a few weeks now...

Thanks in advance <3

**Comment by schadom** [comment]
Same problem here after upgrading the docker image to latest version today.
Adding all docker subnets `'proxies' => ['172.0.0.0/8']` to `config/trustedproxy.php` had no effect.

Temp fix by adding ` \URL::forceRootUrl("https://status.yoursite.net");` and `\URL::forceScheme('https');` on top of the boot() function in `app/Providers/AppServiceProvider.php`

**Comment by thomasthebro1** [comment]
> Same problem here after upgrading the docker image to latest version today. Adding all docker subnets `'proxies' => ['172.0.0.0/8']` to `config/trustedproxy.php` had no effect.
> 
> Temp fix by adding ` \URL::forceRootUrl("https://status.yoursite.net");` and `\URL::forceScheme('https');` on top of the boot() function in `app/Providers/AppServiceProvider.php`

I am also having the same problem.
Where can I find this file to add the code?

**Comment by schadom** [comment]
> > Same problem here after upgrading the docker image to latest version today. Adding all docker subnets `'proxies' => ['172.0.0.0/8']` to `config/trustedproxy.php` had no effect.
> > Temp fix by adding ` \URL::forceRootUrl("https://status.yoursite.net");` and `\URL::forceScheme('https');` on top of the boot() function in `app/Providers/AppServiceProvider.php`
> 
> I am also having the same problem. Where can I find this file to add the code?

`app/Providers/AppServiceProvider.php`

**Comment by thomasthebro1** [comment]
> > > Same problem here after upgrading the docker image to latest version today. Adding all docker subnets `'proxies' => ['172.0.0.0/8']` to `config/trustedproxy.php` had no effect.
> > > Temp fix by adding ` \URL::forceRootUrl("https://status.yoursite.net");` and `\URL::forceScheme('https');` on top of the boot() function in `app/Providers/AppServiceProvider.php`
> > 
> > 
> > I am also having the same problem. Where can I find this file to add the code?
> 
> `app/Providers/AppServiceProvider.php`

More specifically, where can I find the `app` folder originating from when its a Docker image?

**Comment by JAKAMI99** [comment]
> > > > Same problem here after upgrading the docker image to latest version today. Adding all docker subnets `'proxies' => ['172.0.0.0/8']` to `config/trustedproxy.php` had no effect.
> > > > Temp fix by adding ` \URL::forceRootUrl("https://status.yoursite.net");` and `\URL::forceScheme('https');` on top of the boot() function in `app/Providers/AppServiceProvider.php`
> > > 
> > > 
> > > I am also having the same problem. Where can I find this file to add the code?
> > 
> > 
> > `app/Providers/AppServiceProvider.php`
> 
> More specifically, where can I find the `app` folder originating from when its a Docker image?

Use the console to view all files, if you are using a docker manager like UNRAID.
Then cd into `/var/www/html/app/Providers`  . 
In this directory you should find the `AppServiceProvider.php`.

Edit:
`sudo docker exec –it Cachet /bin/bash` (for a console while using docker with the command line)

**Comment by thomasthebro1** [comment]
Yes it works! Thank you so much everyone :)
Btw sorry about the questions unrelated to the issue, I am still getting my head around docker and I am quite new to the environment.

UPDATE: The only problem I've found when using this method is that after you log into the dashboard the port number still gets appended to the end of the URL when you are running behind a reverse proxy such as Nginx.

**Comment by jbrooksuk** [comment]
Thank you for your input on Cachet 2.x. We are shifting our attention and resources to Cachet 3.x and will no longer be supporting the 2.x version. If your feedback or issue is relevant to the 3.x series, we encourage you to engage with the new branch.

For more information on the Cachet rebuild and our plans for 3.x, you can read the announcement [here](https://github.com/CachetHQ/Cachet/discussions/4342).

We appreciate your understanding and look forward to your contributions to the new version.
