### ISSUE TITLE
Sorting the endpoints based on status

### ISSUE THREAD

**Issue by monu56** [cachethq/cachet#4316]
Hi,
I am looking out for a solution where our Cachet Status Page can sort the components based on the status (For ex: Outage URL should be listed first in the status page UI). I followed the documentation, but not clear where exactly to make changes. Can anyone help please.

Ref: https://docs.cachethq.io/docs/advanced-api-usage

What I think, I should make changes in the config.yml file -> api_url section, but that's giving me an error:

**Config_File:**
![capture](https://user-images.githubusercontent.com/46933368/159307755-4c622cda-1a9f-4596-832c-a43d915b3043.jpg)

**Error:**
Traceback (most recent call last):
File "cachet_url_monitor/scheduler.py", line 160, in
configuration = Configuration(config_data, endpoint_index, client, webhooks)
File "/home/cachet/py3/lib64/python3.7/site-packages/cachet_url_monitor-0.6.11-py3.7.egg/cachet_url_monitor/configuration.py", line 105, in init
self.status = self.client.get_component_status(self.component_id)
File "/home/cachet/py3/lib64/python3.7/site-packages/cachet_url_monitor-0.6.11-py3.7.egg/cachet_url_monitor/client.py", line 82, in get_component_status
return status.ComponentStatus(int(get_status_request.json()["data"]["status"]))
TypeError: list indices must be integers or slices, not str

**Comment by jbrooksuk** [comment]
Thank you for your input on Cachet 2.x. We are shifting our attention and resources to Cachet 3.x and will no longer be supporting the 2.x version. If your feedback or issue is relevant to the 3.x series, we encourage you to engage with the new branch.

For more information on the Cachet rebuild and our plans for 3.x, you can read the announcement [here](https://github.com/CachetHQ/Cachet/discussions/4342).

We appreciate your understanding and look forward to your contributions to the new version.
