### ISSUE TITLE
Twig Link on Template Site is broken

### ISSUE THREAD

**Issue by marcofirsching** [cachethq/cachet#4318]
The link at the bottom of the Template Site is broken/points to an old URL. It can be fixed in the language file, but i can not submit it to crowdin, so i have to open an issue.

The correct URL should be: https://twig.symfony.com

**Comment by jbrooksuk** [comment]
Thank you for your input on Cachet 2.x. We are shifting our attention and resources to Cachet 3.x and will no longer be supporting the 2.x version. If your feedback or issue is relevant to the 3.x series, we encourage you to engage with the new branch.

For more information on the Cachet rebuild and our plans for 3.x, you can read the announcement [here](https://github.com/CachetHQ/Cachet/discussions/4342).

We appreciate your understanding and look forward to your contributions to the new version.
