### ISSUE TITLE
E-Mail success Message after Subscribing to Updates is in wrong Language

### ISSUE THREAD

**Issue by marcofirsching** [cachethq/cachet#4319]
![Bildschirmfoto 2022-03-30 um 15 03 32](https://user-images.githubusercontent.com/65415578/160841073-ee0e8fbd-78de-4d6d-957b-3c96d9dd79d8.png)

The second Part of the Message is in English but not part of the translation in the german lang file.

**Comment by jv-barsuk** [comment]
I completed the german translation. You can use my fork for a full german interface. https://github.com/jv-barsuk/Cachet

**Comment by jbrooksuk** [comment]
Thank you for your input on Cachet 2.x. We are shifting our attention and resources to Cachet 3.x and will no longer be supporting the 2.x version. If your feedback or issue is relevant to the 3.x series, we encourage you to engage with the new branch.

For more information on the Cachet rebuild and our plans for 3.x, you can read the announcement [here](https://github.com/CachetHQ/Cachet/discussions/4342).

We appreciate your understanding and look forward to your contributions to the new version.
