### ISSUE TITLE
Unable to edit components

### ISSUE THREAD

**Issue by brianjking** [cachethq/Cachet#432]
https://www.dropbox.com/s/x3ye76y8rbyxhw4/screenshot1-27-1511.42.png?dl=0

Any ideas? Heroku one button deploy

**Comment by jbrooksuk** [comment]
Woah. Looks like we have a syntax error on our hands.

**Comment by jbrooksuk** [comment]
Is this component linked to a component group?

**Comment by jbrooksuk** [comment]
Actually, are you using the latest version?

**Comment by brianjking** [comment]
:grinning: Let me know if there's anything I can help with. Can't wait for a patch! Thanks!

**Comment by jbrooksuk** [comment]
Just the above ;)

**Comment by brianjking** [comment]
I was until a few minutes ago. I'm re-building now.

**Comment by jbrooksuk** [comment]
Cool :)

**Comment by brianjking** [comment]
Yes, just pushed a new deploy and still having the same issue.

remote: Verifying deploy... done.
To https://git.heroku.com/dockdogsmonitor.git
   6250aec..d9dbfeb  master -> master

**Comment by jbrooksuk** [comment]
PgSQL I take it?

**Comment by brianjking** [comment]
Affirmative.

**Comment by jbrooksuk** [comment]
Are you able to copy the source of the page into a Gist for me or something?

**Comment by jbrooksuk** [comment]
Actually, nevermind, you're not in debug mode :)

**Comment by jbrooksuk** [comment]
Have you ever been able to edit components?

**Comment by brianjking** [comment]
@jbrooksuk yes, until a week or two ago.

**Comment by jbrooksuk** [comment]
It's related to the `tagsList` attribute on the `Component` model.

**Comment by brianjking** [comment]
@jbrooksuk how can I go into debug?

**Comment by jbrooksuk** [comment]
You'd need to manually edit the `./app/config/app.php` file. Don't worry, I'm on it :)

**Comment by jbrooksuk** [comment]
The error itself is actually:

```php
Symfony \ Component \ Debug \ Exception \ FatalErrorException (E_ERROR) 
Call to a member function map() on string
```

**Comment by jbrooksuk** [comment]
I don't know why though because `tags` is a relationship. Why does it make it so hard?

**Comment by jbrooksuk** [comment]
@joecohens any idea on this one? The relationship works beautifully on MySQL.

**Comment by jbrooksuk** [comment]
Annoyingly this works on SQLite too.

**Comment by joecohens** [comment]
Can't reproduce the error on a fresh one click install it might be a migration issue?

**Comment by brianjking** [comment]
@joecohens Yeah, I can't make it happen on a fresh 1 click installation. The install with the issue is also a 1click install. 

@jbrooksuk - If I have to deploy a new installation is there a way yet for me to migrate the database contents?

**Comment by jbrooksuk** [comment]
Unfortunately not yet. You could connect directly to the database and modify the columns?

**Comment by brianjking** [comment]
I'll wait a few days and see if you guys can figure this out before I opt to have to manually migrate the content to a new deploy. 

Thanks, keep up the great work guys!

**Comment by jbrooksuk** [comment]
You should be able to simply drop the tags column from the components table. If you can login to it?

**Comment by brianjking** [comment]
How can I remotely connect is the question?

Thanks,

Brian J King

**Comment by jbrooksuk** [comment]
Login to Heroku and get the env variable for the database. Connect with PgSql.

**Comment by jbrooksuk** [comment]
@brianjking I'm going to close this issue as it's not really a bug - but @joecohens and I have been discussing how we can better the migration path for current users.
