### ISSUE TITLE
Getting Error 500 for enabling 2FA

### ISSUE THREAD

**Issue by sparthe123** [cachethq/cachet#4322]
When I enable 2FA from profile page , i'm getting Error 500 page. 

Screenshot : https://share.anysnap.app/fURUJGboradF

Logs 

production.ERROR: Symfony\Component\Debug\Exception\FatalThrowableError: Call to undefined function chillerlan\QRCode\Output\imagecreatetruecolor() in /var/www/Cachet/vendor/chillerlan/php-qrcode/src/Output/QRImage.php:110
Stack trace:
#0 /var/www/Cachet/vendor/chillerlan/php-qrcode/src/Output/QRImage.php(83): chillerlan\QRCode\Output\QRImage->setImage()
#1 /var/www/Cachet/vendor/chillerlan/php-qrcode/src/QRCode.php(154): chillerlan\QRCode\Output\QRImage->dump()
#2 /var/www/Cachet/storage/framework/views/e81bb2feadc229612cae138c79a3dcf5ecc3bdea.php(64): chillerlan\QRCode\QRCode->render()
.
.
.

Please help me to fix this issue.

**Comment by jbrooksuk** [comment]
Thank you for your input on Cachet 2.x. We are shifting our attention and resources to Cachet 3.x and will no longer be supporting the 2.x version. If your feedback or issue is relevant to the 3.x series, we encourage you to engage with the new branch.

For more information on the Cachet rebuild and our plans for 3.x, you can read the announcement [here](https://github.com/CachetHQ/Cachet/discussions/4342).

We appreciate your understanding and look forward to your contributions to the new version.
