### ISSUE TITLE
composer install message regarding abandoned components

### ISSUE THREAD

**Issue by 0eddie** [cachethq/cachet#4323]
composer install --no-dev -o  --no-scripts runs fine but at the end gives me:

Package alt-three/badger is abandoned, you should avoid using it. Use cachethq/badger instead.
Package alt-three/emoji is abandoned, you should avoid using it. Use cachethq/emoji instead.
Package alt-three/throttle is abandoned, you should avoid using it. No replacement was suggested.
Package graham-campbell/core is abandoned, you should avoid using it. No replacement was suggested.
Package roumen/feed is abandoned, you should avoid using it. Use laravelium/feed instead.
Package phpunit/phpunit-mock-objects is abandoned, you should avoid using it. No replacement was suggested.

Is there something I had to worry about? Thanks

**Comment by 0eddie** [comment]
It seems that after that I get these errors after running php artisan generate:key

PS C:\Apache24\Cachet> php.exe artisan key:generate
PHP Deprecated:  Return type of Illuminate\Container\Container::offsetExists($key) should either be compatible with ArrayAccess::offsetExists(mixed $offset): bool, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in C:\Apache24\Cachet\vendor\laravel\framework\src\Illuminate\Container\Container.php on line 1165

Deprecated: Return type of Illuminate\Container\Container::offsetExists($key) should either be compatible with ArrayAccess::offsetExists(mixed $offset): bool, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in C:\Apache24\Cachet\vendor\laravel\framework\src\Illuminate\Container\Container.php on line 1165
PHP Deprecated:  Return type of Illuminate\Container\Container::offsetGet($key) should either be compatible with ArrayAccess::offsetGet(mixed $offset): mixed, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in C:\Apache24\Cachet\vendor\laravel\framework\src\Illuminate\Container\Container.php on line 1176

Deprecated: Return type of Illuminate\Container\Container::offsetGet($key) should either be compatible with ArrayAccess::offsetGet(mixed $offset): mixed, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in C:\Apache24\Cachet\vendor\laravel\framework\src\Illuminate\Container\Container.php on line 1176
PHP Deprecated:  Return type of Illuminate\Container\Container::offsetSet($key, $value) should either be compatible with ArrayAccess::offsetSet(mixed $offset, mixed $value): void, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in C:\Apache24\Cachet\vendor\laravel\framework\src\Illuminate\Container\Container.php on line 1188

Deprecated: Return type of Illuminate\Container\Container::offsetSet($key, $value) should either be compatible with ArrayAccess::offsetSet(mixed $offset, mixed $value): void, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in C:\Apache24\Cachet\vendor\laravel\framework\src\Illuminate\Container\Container.php on line 1188
PHP Deprecated:  Return type of Illuminate\Container\Container::offsetUnset($key) should either be compatible with ArrayAccess::offsetUnset(mixed $offset): void, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in C:\Apache24\Cachet\vendor\laravel\framework\src\Illuminate\Container\Container.php on line 1208

Deprecated: Return type of Illuminate\Container\Container::offsetUnset($key) should either be compatible with ArrayAccess::offsetUnset(mixed $offset): void, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in C:\Apache24\Cachet\vendor\laravel\framework\src\Illuminate\Container\Container.php on line 1208
PHP Deprecated:  Method ReflectionParameter::getClass() is deprecated in C:\Apache24\Cachet\vendor\laravel\framework\src\Illuminate\Container\Container.php on line 794

Deprecated: Method ReflectionParameter::getClass() is deprecated in C:\Apache24\Cachet\vendor\laravel\framework\src\Illuminate\Container\Container.php on line 794
PHP Deprecated:  Method ReflectionParameter::getClass() is deprecated in C:\Apache24\Cachet\vendor\laravel\framework\src\Illuminate\Container\Container.php on line 849

Deprecated: Method ReflectionParameter::getClass() is deprecated in C:\Apache24\Cachet\vendor\laravel\framework\src\Illuminate\Container\Container.php on line 849
PHP Deprecated:  Method ReflectionParameter::getClass() is deprecated in C:\Apache24\Cachet\vendor\laravel\framework\src\Illuminate\Container\Container.php on line 794

Deprecated: Method ReflectionParameter::getClass() is deprecated in C:\Apache24\Cachet\vendor\laravel\framework\src\Illuminate\Container\Container.php on line 794
PHP Deprecated:  Method ReflectionParameter::getClass() is deprecated in C:\Apache24\Cachet\vendor\laravel\framework\src\Illuminate\Container\Container.php on line 849

Deprecated: Method ReflectionParameter::getClass() is deprecated in C:\Apache24\Cachet\vendor\laravel\framework\src\Illuminate\Container\Container.php on line 849
PHP Deprecated:  auto_detect_line_endings is deprecated in C:\Apache24\Cachet\vendor\vlucas\phpdotenv\src\Loader.php on line 167

Deprecated: auto_detect_line_endings is deprecated in C:\Apache24\Cachet\vendor\vlucas\phpdotenv\src\Loader.php on line 167
PHP Deprecated:  Return type of Illuminate\Config\Repository::offsetExists($key) should either be compatible with ArrayAccess::offsetExists(mixed $offset): bool, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in C:\Apache24\Cachet\vendor\laravel\framework\src\Illuminate\Config\Repository.php on line 118

Deprecated: Return type of Illuminate\Config\Repository::offsetExists($key) should either be compatible with ArrayAccess::offsetExists(mixed $offset): bool, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in C:\Apache24\Cachet\vendor\laravel\framework\src\Illuminate\Config\Repository.php on line 118
PHP Deprecated:  Return type of Illuminate\Config\Repository::offsetGet($key) should either be compatible with ArrayAccess::offsetGet(mixed $offset): mixed, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in C:\Apache24\Cachet\vendor\laravel\framework\src\Illuminate\Config\Repository.php on line 129

Deprecated: Return type of Illuminate\Config\Repository::offsetGet($key) should either be compatible with ArrayAccess::offsetGet(mixed $offset): mixed, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in C:\Apache24\Cachet\vendor\laravel\framework\src\Illuminate\Config\Repository.php on line 129
PHP Deprecated:  Return type of Illuminate\Config\Repository::offsetSet($key, $value) should either be compatible with ArrayAccess::offsetSet(mixed $offset, mixed $value): void, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in C:\Apache24\Cachet\vendor\laravel\framework\src\Illuminate\Config\Repository.php on line 141

Deprecated: Return type of Illuminate\Config\Repository::offsetSet($key, $value) should either be compatible with ArrayAccess::offsetSet(mixed $offset, mixed $value): void, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in C:\Apache24\Cachet\vendor\laravel\framework\src\Illuminate\Config\Repository.php on line 141
PHP Deprecated:  Return type of Illuminate\Config\Repository::offsetUnset($key) should either be compatible with ArrayAccess::offsetUnset(mixed $offset): void, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in C:\Apache24\Cachet\vendor\laravel\framework\src\Illuminate\Config\Repository.php on line 152

Deprecated: Return type of Illuminate\Config\Repository::offsetUnset($key) should either be compatible with ArrayAccess::offsetUnset(mixed $offset): void, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in C:\Apache24\Cachet\vendor\laravel\framework\src\Illuminate\Config\Repository.php on line 152
PHP Deprecated:  Return type of Symfony\Component\Finder\Finder::getIterator() should either be compatible with IteratorAggregate::getIterator(): Traversable, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in C:\Apache24\Cachet\vendor\symfony\finder\Finder.php on line 564

Deprecated: Return type of Symfony\Component\Finder\Finder::getIterator() should either be compatible with IteratorAggregate::getIterator(): Traversable, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in C:\Apache24\Cachet\vendor\symfony\finder\Finder.php on line 564
PHP Deprecated:  Return type of Symfony\Component\Finder\Finder::count() should either be compatible with Countable::count(): int, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in C:\Apache24\Cachet\vendor\symfony\finder\Finder.php on line 621

Deprecated: Return type of Symfony\Component\Finder\Finder::count() should either be compatible with Countable::count(): int, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in C:\Apache24\Cachet\vendor\symfony\finder\Finder.php on line 621
PHP Deprecated:  Return type of Symfony\Component\Finder\Iterator\FilterIterator::rewind() should either be compatible with FilterIterator::rewind(): void, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in C:\Apache24\Cachet\vendor\symfony\finder\Iterator\FilterIterator.php on line 30

Deprecated: Return type of Symfony\Component\Finder\Iterator\FilterIterator::rewind() should either be compatible with FilterIterator::rewind(): void, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in C:\Apache24\Cachet\vendor\symfony\finder\Iterator\FilterIterator.php on line 30
PHP Deprecated:  Return type of Symfony\Component\Finder\Iterator\FileTypeFilterIterator::accept() should either be compatible with FilterIterator::accept(): bool, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in C:\Apache24\Cachet\vendor\symfony\finder\Iterator\FileTypeFilterIterator.php on line 44

Deprecated: Return type of Symfony\Component\Finder\Iterator\FileTypeFilterIterator::accept() should either be compatible with FilterIterator::accept(): bool, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in C:\Apache24\Cachet\vendor\symfony\finder\Iterator\FileTypeFilterIterator.php on line 44
PHP Deprecated:  Return type of Symfony\Component\Finder\Iterator\RecursiveDirectoryIterator::getChildren() should either be compatible with RecursiveDirectoryIterator::getChildren(): RecursiveDirectoryIterator, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in C:\Apache24\Cachet\vendor\symfony\finder\Iterator\RecursiveDirectoryIterator.php on line 87

Deprecated: Return type of Symfony\Component\Finder\Iterator\RecursiveDirectoryIterator::getChildren() should either be compatible with RecursiveDirectoryIterator::getChildren(): RecursiveDirectoryIterator, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in C:\Apache24\Cachet\vendor\symfony\finder\Iterator\RecursiveDirectoryIterator.php on line 87
PHP Deprecated:  Return type of Symfony\Component\Finder\Iterator\RecursiveDirectoryIterator::rewind() should either be compatible with FilesystemIterator::rewind(): void, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in C:\Apache24\Cachet\vendor\symfony\finder\Iterator\RecursiveDirectoryIterator.php on line 115

Deprecated: Return type of Symfony\Component\Finder\Iterator\RecursiveDirectoryIterator::rewind() should either be compatible with FilesystemIterator::rewind(): void, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in C:\Apache24\Cachet\vendor\symfony\finder\Iterator\RecursiveDirectoryIterator.php on line 115
PHP Deprecated:  Return type of Symfony\Component\Finder\Iterator\RecursiveDirectoryIterator::current() should either be compatible with FilesystemIterator::current(): SplFileInfo|FilesystemIterator|string, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in C:\Apache24\Cachet\vendor\symfony\finder\Iterator\RecursiveDirectoryIterator.php on line 67

Deprecated: Return type of Symfony\Component\Finder\Iterator\RecursiveDirectoryIterator::current() should either be compatible with FilesystemIterator::current(): SplFileInfo|FilesystemIterator|string, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in C:\Apache24\Cachet\vendor\symfony\finder\Iterator\RecursiveDirectoryIterator.php on line 67
PHP Deprecated:  Return type of Symfony\Component\Finder\Iterator\ExcludeDirectoryFilterIterator::accept() should either be compatible with FilterIterator::accept(): bool, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in C:\Apache24\Cachet\vendor\symfony\finder\Iterator\ExcludeDirectoryFilterIterator.php on line 56

Deprecated: Return type of Symfony\Component\Finder\Iterator\ExcludeDirectoryFilterIterator::accept() should either be compatible with FilterIterator::accept(): bool, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in C:\Apache24\Cachet\vendor\symfony\finder\Iterator\ExcludeDirectoryFilterIterator.php on line 56
PHP Deprecated:  Return type of Symfony\Component\Finder\Iterator\ExcludeDirectoryFilterIterator::hasChildren() should either be compatible with RecursiveIterator::hasChildren(): bool, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in C:\Apache24\Cachet\vendor\symfony\finder\Iterator\ExcludeDirectoryFilterIterator.php on line 72

Deprecated: Return type of Symfony\Component\Finder\Iterator\ExcludeDirectoryFilterIterator::hasChildren() should either be compatible with RecursiveIterator::hasChildren(): bool, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in C:\Apache24\Cachet\vendor\symfony\finder\Iterator\ExcludeDirectoryFilterIterator.php on line 72
PHP Deprecated:  Return type of Symfony\Component\Finder\Iterator\ExcludeDirectoryFilterIterator::getChildren() should either be compatible with RecursiveIterator::getChildren(): ?RecursiveIterator, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in C:\Apache24\Cachet\vendor\symfony\finder\Iterator\ExcludeDirectoryFilterIterator.php on line 77

Deprecated: Return type of Symfony\Component\Finder\Iterator\ExcludeDirectoryFilterIterator::getChildren() should either be compatible with RecursiveIterator::getChildren(): ?RecursiveIterator, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in C:\Apache24\Cachet\vendor\symfony\finder\Iterator\ExcludeDirectoryFilterIterator.php on line 77
PHP Deprecated:  Return type of Symfony\Component\Finder\Iterator\FilterIterator::rewind() should either be compatible with Iterator::rewind(): void, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in C:\Apache24\Cachet\vendor\symfony\finder\Iterator\FilterIterator.php on line 30

Deprecated: Return type of Symfony\Component\Finder\Iterator\FilterIterator::rewind() should either be compatible with Iterator::rewind(): void, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in C:\Apache24\Cachet\vendor\symfony\finder\Iterator\FilterIterator.php on line 30
PHP Deprecated:  Return type of Symfony\Component\Finder\Iterator\FilenameFilterIterator::accept() should either be compatible with FilterIterator::accept(): bool, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in C:\Apache24\Cachet\vendor\symfony\finder\Iterator\FilenameFilterIterator.php on line 28

Deprecated: Return type of Symfony\Component\Finder\Iterator\FilenameFilterIterator::accept() should either be compatible with FilterIterator::accept(): bool, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in C:\Apache24\Cachet\vendor\symfony\finder\Iterator\FilenameFilterIterator.php on line 28
PHP Deprecated:  Return type of Symfony\Component\Finder\Iterator\PathFilterIterator::accept() should either be compatible with FilterIterator::accept(): bool, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in C:\Apache24\Cachet\vendor\symfony\finder\Iterator\PathFilterIterator.php on line 27

Deprecated: Return type of Symfony\Component\Finder\Iterator\PathFilterIterator::accept() should either be compatible with FilterIterator::accept(): bool, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in C:\Apache24\Cachet\vendor\symfony\finder\Iterator\PathFilterIterator.php on line 27
PHP Deprecated:  Return type of Illuminate\Http\Request::offsetExists($offset) should either be compatible with ArrayAccess::offsetExists(mixed $offset): bool, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in C:\Apache24\Cachet\vendor\laravel\framework\src\Illuminate\Http\Request.php on line 992

Deprecated: Return type of Illuminate\Http\Request::offsetExists($offset) should either be compatible with ArrayAccess::offsetExists(mixed $offset): bool, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in C:\Apache24\Cachet\vendor\laravel\framework\src\Illuminate\Http\Request.php on line 992
PHP Deprecated:  Return type of Illuminate\Http\Request::offsetGet($offset) should either be compatible with ArrayAccess::offsetGet(mixed $offset): mixed, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in C:\Apache24\Cachet\vendor\laravel\framework\src\Illuminate\Http\Request.php on line 1003

Deprecated: Return type of Illuminate\Http\Request::offsetGet($offset) should either be compatible with ArrayAccess::offsetGet(mixed $offset): mixed, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in C:\Apache24\Cachet\vendor\laravel\framework\src\Illuminate\Http\Request.php on line 1003
PHP Deprecated:  Return type of Illuminate\Http\Request::offsetSet($offset, $value) should either be compatible with ArrayAccess::offsetSet(mixed $offset, mixed $value): void, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in C:\Apache24\Cachet\vendor\laravel\framework\src\Illuminate\Http\Request.php on line 1015

Deprecated: Return type of Illuminate\Http\Request::offsetSet($offset, $value) should either be compatible with ArrayAccess::offsetSet(mixed $offset, mixed $value): void, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in C:\Apache24\Cachet\vendor\laravel\framework\src\Illuminate\Http\Request.php on line 1015
PHP Deprecated:  Return type of Illuminate\Http\Request::offsetUnset($offset) should either be compatible with ArrayAccess::offsetUnset(mixed $offset): void, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in C:\Apache24\Cachet\vendor\laravel\framework\src\Illuminate\Http\Request.php on line 1026

Deprecated: Return type of Illuminate\Http\Request::offsetUnset($offset) should either be compatible with ArrayAccess::offsetUnset(mixed $offset): void, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in C:\Apache24\Cachet\vendor\laravel\framework\src\Illuminate\Http\Request.php on line 1026
PHP Fatal error:  During inheritance of IteratorAggregate: Uncaught ErrorException: Return type of Symfony\Component\HttpFoundation\ParameterBag::getIterator() should either be compatible with IteratorAggregate::getIterator(): Traversable, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in C:\Apache24\Cachet\vendor\symfony\http-foundation\ParameterBag.php:224
Stack trace:
#0 C:\Apache24\Cachet\vendor\symfony\http-foundation\ParameterBag.php(19): Illuminate\Foundation\Bootstrap\HandleExceptions->handleError(8192, 'Return type of ...', 'C:\\Apache24\\Cac...', 224)
#1 C:\Apache24\Cachet\vendor\composer\ClassLoader.php(571): include('C:\\Apache24\\Cac...')
#2 C:\Apache24\Cachet\vendor\composer\ClassLoader.php(428): Composer\Autoload\includeFile('C:\\Apache24\\Cac...')
#3 C:\Apache24\Cachet\vendor\symfony\http-foundation\Request.php(240): Composer\Autoload\ClassLoader->loadClass('Symfony\\Compone...')
#4 C:\Apache24\Cachet\vendor\symfony\http-foundation\Request.php(222): Symfony\Component\HttpFoundation\Request->initialize(Array, Array, Array, Array, Array, Array, NULL)
#5 C:\Apache24\Cachet\vendor\symfony\http-foundation\Request.php(1913): Symfony\Component\HttpFoundation\Request->__construct(Array, Array, Array, Array, Array, Array, NULL)
#6 C:\Apache24\Cachet\vendor\symfony\http-foundation\Request.php(398): Symfony\Component\HttpFoundation\Request::createRequestFromFactory(Array, Array, Array, Array, Array, Array, NULL)
#7 C:\Apache24\Cachet\vendor\laravel\framework\src\Illuminate\Foundation\Bootstrap\SetRequestForConsole.php(20): Symfony\Component\HttpFoundation\Request::create('http://localhos...', 'GET', Array, Array, Array, Array)
#8 C:\Apache24\Cachet\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(203): Illuminate\Foundation\Bootstrap\SetRequestForConsole->bootstrap(Object(Illuminate\Foundation\Application))
#9 C:\Apache24\Cachet\vendor\laravel\framework\src\Illuminate\Foundation\Console\Kernel.php(219): Illuminate\Foundation\Application->bootstrapWith(Array)
#10 C:\Apache24\Cachet\vendor\laravel\framework\src\Illuminate\Foundation\Console\Kernel.php(105): Illuminate\Foundation\Console\Kernel->bootstrap()
#11 C:\Apache24\Cachet\artisan(35): Illuminate\Foundation\Console\Kernel->handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#12 {main} in C:\Apache24\Cachet\vendor\symfony\http-foundation\ParameterBag.php on line 19
PHP Fatal error:  Uncaught ErrorException: Method ReflectionParameter::getClass() is deprecated in C:\Apache24\Cachet\vendor\laravel\framework\src\Illuminate\Container\Container.php:794
Stack trace:
#0 C:\Apache24\Cachet\vendor\laravel\framework\src\Illuminate\Container\Container.php(794): Illuminate\Foundation\Bootstrap\HandleExceptions->handleError(8192, 'Method Reflecti...', 'C:\\Apache24\\Cac...', 794)
#1 C:\Apache24\Cachet\vendor\laravel\framework\src\Illuminate\Container\Container.php(774): Illuminate\Container\Container->getDependencies(Array, Array)
#2 C:\Apache24\Cachet\vendor\laravel\framework\src\Illuminate\Container\Container.php(629): Illuminate\Container\Container->build('GrahamCampbell\\...', Array)
#3 C:\Apache24\Cachet\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(697): Illuminate\Container\Container->make('GrahamCampbell\\...', Array)
#4 C:\Apache24\Cachet\vendor\laravel\framework\src\Illuminate\Container\Container.php(230): Illuminate\Foundation\Application->make('GrahamCampbell\\...', Array)
#5 C:\Apache24\Cachet\vendor\laravel\framework\src\Illuminate\Container\Container.php(731): Illuminate\Container\Container->Illuminate\Container\{closure}(Object(Illuminate\Foundation\Application), Array)
#6 C:\Apache24\Cachet\vendor\laravel\framework\src\Illuminate\Container\Container.php(629): Illuminate\Container\Container->build(Object(Closure), Array)
#7 C:\Apache24\Cachet\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(697): Illuminate\Container\Container->make('Illuminate\\Cont...', Array)
#8 C:\Apache24\Cachet\vendor\laravel\framework\src\Illuminate\Foundation\Bootstrap\HandleExceptions.php(154): Illuminate\Foundation\Application->make('Illuminate\\Cont...')
#9 C:\Apache24\Cachet\vendor\laravel\framework\src\Illuminate\Foundation\Bootstrap\HandleExceptions.php(79): Illuminate\Foundation\Bootstrap\HandleExceptions->getExceptionHandler()
#10 C:\Apache24\Cachet\vendor\laravel\framework\src\Illuminate\Foundation\Bootstrap\HandleExceptions.php(118): Illuminate\Foundation\Bootstrap\HandleExceptions->handleException(Object(Symfony\Component\Debug\Exception\FatalErrorException))
#11 [internal function]: Illuminate\Foundation\Bootstrap\HandleExceptions->handleShutdown()
#12 {main}
  thrown in C:\Apache24\Cachet\vendor\laravel\framework\src\Illuminate\Container\Container.php on line 794

**Comment by jbrooksuk** [comment]
Thank you for your input on Cachet 2.x. We are shifting our attention and resources to Cachet 3.x and will no longer be supporting the 2.x version. If your feedback or issue is relevant to the 3.x series, we encourage you to engage with the new branch.

For more information on the Cachet rebuild and our plans for 3.x, you can read the announcement [here](https://github.com/CachetHQ/Cachet/discussions/4342).

We appreciate your understanding and look forward to your contributions to the new version.
