### ISSUE TITLE
Setup Page not loading/ seeing the index.php file

### ISSUE THREAD

**Issue by 0eddie** [cachethq/cachet#4324]
Unable to see the set up page. Stuck on index.php
Apache 2.4.53
PHP 7.4
MariaDB
Composer 2.3.5

Exact same issue as closed  · Issue #4016 but there is not published solution

**Comment by adamb53** [comment]
If it's just showing the contents of the php file in plain text then you likely do not have the Apache php module installed / enabled

**Comment by jbrooksuk** [comment]
Thank you for your input on Cachet 2.x. We are shifting our attention and resources to Cachet 3.x and will no longer be supporting the 2.x version. If your feedback or issue is relevant to the 3.x series, we encourage you to engage with the new branch.

For more information on the Cachet rebuild and our plans for 3.x, you can read the announcement [here](https://github.com/CachetHQ/Cachet/discussions/4342).

We appreciate your understanding and look forward to your contributions to the new version.
