### ISSUE TITLE
500 error while verifying the subscription

### ISSUE THREAD

**Issue by heloisme** [cachethq/cachet#4328]
I have installed cachet in docker in the ubuntu system, I am facing two-issue right now
1. while I add the Subscribers, it sends a verification email but while trying to verify, it outputs me with a 500 error. but in server I can see that the email address is verified and we are able to get the notification. 
2. I am trying to add users(clients) who can log in to the dashboard using their email address or username and they get access to the cachethq dashboard to look at the status of their domain. 
here is the link to the screenshot
https://ibb.co/bgGXLRx

**Comment by jbrooksuk** [comment]
Thank you for your input on Cachet 2.x. We are shifting our attention and resources to Cachet 3.x and will no longer be supporting the 2.x version. If your feedback or issue is relevant to the 3.x series, we encourage you to engage with the new branch.

For more information on the Cachet rebuild and our plans for 3.x, you can read the announcement [here](https://github.com/CachetHQ/Cachet/discussions/4342).

We appreciate your understanding and look forward to your contributions to the new version.
