### ISSUE TITLE
Enable debug mode via env

### ISSUE THREAD

**Issue by jbrooksuk** [cachethq/Cachet#433]
This would make it easy to switch on debug mode when you deploy to Heroku etc.

**Comment by joecohens** [comment]
Store a setting `debug_mode` and override in LoadConfig?

**Comment by jbrooksuk** [comment]
I was trying to make it harder for the average user to edit it. That is a solution though. Do you think it's better?

**Comment by joecohens** [comment]
Oh I thought it was for everyone. Laravel 5 will let you easy do this directly on the env.

**Comment by jbrooksuk** [comment]
We don't really want to advocate it, but we could put it under some kind of **Danger zone**?

**Comment by joecohens** [comment]
Nah I think it's better on the env only for advanced user.

**Comment by jbrooksuk** [comment]
:+1:

**Comment by jbrooksuk** [comment]
See #434
