### ISSUE TITLE
This project is dead. Any recommendations for alternatives?

### ISSUE THREAD

**Issue by max-rocket-internet** [cachethq/cachet#4338]
See:

- https://github.com/CachetHQ/Cachet/issues/4326
- https://github.com/CachetHQ/Cachet/issues/4329

Please suggest any alternatives 🙂

**Comment by steffjenl** [comment]
There is an team that have made an fork of this project.

https://github.com/Okazanta/okazanta-legacy

I have upgraded this project to Laravel 8 an PHP 8.0.

https://github.com/Okazanta/okazanta-legacy/issues/39
https://github.com/Okazanta/okazanta-legacy/pull/40

**Comment by max-rocket-internet** [comment]
Awesome, thanks @steffjenl

**Comment by ppuschmann** [comment]
@max-rocket-internet Maybe check https://github.com/ivbeg/awesome-status-pages

**Comment by HLeithner** [comment]
[Uptime-Kuma](https://github.com/louislam/uptime-kuma) looks promising.

**Comment by jbrooksuk** [comment]
Hey 👋 

Please check out https://github.com/CachetHQ/Cachet/discussions/4342

TLDR; Cachet is back! 🎉
