### ISSUE TITLE
REPLACEMENT CHARACTER (U+FFFD) when posting an incident 

### ISSUE THREAD

**Issue by ramsbats** [cachethq/cachet#4339]
Hello, 

When posting a message to incidents, certain characters are converted into �. When I pull that data through an API, I get a 500 error. 

Example: {"errors":[{"id":"","status":500,"title":"Internal Server Error","detail":"An error has occurred and this resource cannot be displayed."}]}

Is there a way to avoid this error?

**Comment by jbrooksuk** [comment]
Thank you for your input on Cachet 2.x. We are shifting our attention and resources to Cachet 3.x and will no longer be supporting the 2.x version. If your feedback or issue is relevant to the 3.x series, we encourage you to engage with the new branch.

For more information on the Cachet rebuild and our plans for 3.x, you can read the announcement [here](https://github.com/CachetHQ/Cachet/discussions/4342).

We appreciate your understanding and look forward to your contributions to the new version.
