### ISSUE TITLE
Fork from okazanta-legacy (cachet) -> Laravel 10.x and PHP 8.1 and security fixes

### ISSUE THREAD

**Issue by steffjenl** [cachethq/cachet#4341]
I have created an stand-alone fork from okazanta (a fork from cachet)

- Laravel 10.x
- PHP 8.1
- Security updates (composer & yarn)
- SQL Injection fix
- Widget support (get status on your website or ticket system)
- RSS Feed support
- Some fixes in layout

Upcoming features
- Realtime server and website monitoring
- Component status webhook for monitoring software (DataDog, PRTG, etc...)

https://github.com/steffjenl/okazanta

**Comment by jbrooksuk** [comment]
Hey 👋 Thanks for the fork!

Please check out https://github.com/CachetHQ/Cachet/discussions/4342

TLDR; Cachet is back! 🎉

**Comment by Tensibai** [comment]
@jbrooksuk I understand the will to get 3.x running first, but maybe an interim 2.5 integrating pull request making the 2.x branch up to date could be a nice move.

As is, it looks like you're not interested on what people did to keep cachet alive during these 5 last years and go blindly on your own path.

**Comment by jbrooksuk** [comment]
@steffjenl would you be open to collaborating on getting this into an official 2.5 release?

**Comment by steffjenl** [comment]
@jbrooksuk no problem I will help with this.

**Comment by jbrooksuk** [comment]
@steffjenl great! Can you email me at james@alt-three.com and we'll discuss this further?
