### ISSUE TITLE
maintenance not displayed on the timeline

### ISSUE THREAD

**Issue by npracht** [cachethq/cachet#4357]
Hello,

i've created a maintenance and i cant find the way to display it on the home page. Future, current, past date. scheduled, current, closed.
Nothing changes.

It there something i am missing ? There is no documentation about it.

by the way, i'm glad to complete the documentation (which is quite poor for end-users) once i understand better how it works. So if you are able to explain me about the maintenance feature, i'll PR documentation direct after your comment :D

**Comment by DennisSkov** [comment]
Don't set the "When did this maintenance complete?" field.
When that field is set, Cachet sees the maintenance as being completed already.

**Comment by jbrooksuk** [comment]
I believe @DennisSkov' has the solution there 👍

**Comment by npracht** [comment]
Thanks folks !

**Comment by tomck** [comment]
You can't remove the complete time if you already set it. If you click and just hit backspace, it just clears to the start of the day.

Also some people (like me) may think it means PLANNED completion time, most maintenance has a window. If status is anything other than "Completed", it should be listed.

**Comment by DennisSkov** [comment]
I agree with @tomck. My immediate thought was that it meant the planned completion time.
I hope it'll be changed for v3!

**Comment by jbrooksuk** [comment]
We should definitely make sure this is fixed for v3! Give https://v3.cachethq.io a go :)
