### ISSUE TITLE
mail not working 

### ISSUE THREAD

**Issue by matthew42904** [cachethq/cachet#4358]
I keep get a 500 error when I try to use smtp to my email server. I have followed videos and documents and still cant find out why its not working. my mail app is not showing any throughput 

php-7.3.14
cachet - 2.4.0-dev

` Timed Out at /var/www/html/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Transport/StreamBuffer.php:166)`

![image](https://github.com/cachethq/cachet/assets/43304608/4363282e-5ee4-4ee2-a35f-3ea9951314b7)
![image](https://github.com/cachethq/cachet/assets/43304608/5de1bd83-fa39-48b2-bcf8-07d1fbdcb5f1)

**Comment by jbrooksuk** [comment]
It looks like a configuration issue. A timeout means that the connection to your SMTP server was not possible quickly enough. This probably means that there is an error in the configuration.

Please check and try again.
