### ISSUE TITLE
Can't install Cachet - version 2.4

### ISSUE THREAD

**Issue by MrBigbee** [cachethq/cachet#4363]
Hello,

When i try to finalize installation into web, nothing happen, when I'm clicking on Next button.
I tried with Firefox and Edge.
I tried with some different options (file, database etc)

Command result with php artisan cachet:install was okay
Tables are created into database (Postgresql 15)

I saw also there is no link into /var/www/cachet/storage/app/public. Maybe, it could explain my problem ?

Php artisan result
![php_artisan_result](https://github.com/cachethq/cachet/assets/10130262/8f1cd0ae-281e-41bc-bb8b-7f44f39f54ba)

When I'm clicking on next button
![Web_installation](https://github.com/cachethq/cachet/assets/10130262/1c3282aa-cbe2-4d09-b83f-5ead59b4a246)

Link missing
![Link_missing_storage](https://github.com/cachethq/cachet/assets/10130262/54fad7b4-48a9-4687-86b7-36702de04359)

**Comment by walrus1234** [comment]
The same problem here with Cachet 2.4. When I press the next button after filling in the values in the setup form nothing happens. In the browser inspector the following Javascript error message is shown:

Uncaught ReferenceError: goToStep is not defined

System environment: Debian 12.2, PHP 7.3.33 from packages.sury.org

**Comment by babandiaye** [comment]
Hello i have the same issue when I'm clicking on Next button.

**Comment by jbrooksuk** [comment]
Sorry about that, this is now fixed in https://github.com/cachethq/cachet/releases/tag/v2.4.1
