### ISSUE TITLE
Maintenance planification does not appear into dashboard

### ISSUE THREAD

**Issue by MrBigbee** [cachethq/cachet#4365]
Hello,

I have created a fictionnal shedule maintenance. But it seems it does not appear into dashboard

Maintenance scheduled :
![image](https://github.com/cachethq/cachet/assets/10130262/86b2522f-b3c2-495f-ac64-2af03fcef7fd)

I have also 1 fictionnal incident
![image](https://github.com/cachethq/cachet/assets/10130262/30056f0b-bc17-486d-abb5-060c9e2ec714)

Into my dashboard, only my incident is visible. Not my scheduled maintenance
![image](https://github.com/cachethq/cachet/assets/10130262/b300a4eb-1c15-4add-9ca4-a454076a947f)

System informations:
OS : Red Hat Enterprise Linux release 8.8 (Ootpa)

PHP Version:
PHP 7.2.24 (cli) (built: Oct 22 2019 08:28:36) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.2.0, Copyright (c) 1998-2018 Zend Technologies

**Comment by DennisSkov** [comment]
Did you set a value for "When did this maintenance complete"? Don't do that until the maintenance is complete. See https://github.com/cachethq/cachet/issues/4357

**Comment by MrBigbee** [comment]
Yes, i set a value for "When did this maintenance complete".

Now, it's working without doing this.

My mistake, i should have read others issues.

Thanks for your answer
