### ISSUE TITLE
Error 500

### ISSUE THREAD

**Issue by linuxgokan** [cachethq/cachet#4368]
Hello

i use Php version: 7.2, Nginx, mariadb. When I want to add a new event, I get an error like the one below.
How can I solve the problem? There is curl and php-curl in the system.

`#87 /var/www/cachet/public/index.php(54): Illuminate\Foundation\Http\Kernel->handle(Object(Illuminate\Http\Request))
#88 {main} {"identification":{"id":"363bb184-dedc-4825-9b8e-651983e45668"},"exception":"[object] (RuntimeException(code: 0): GuzzleHttp requires cURL, the allow_url_fopen ini setting, or a custom HTTP handler. at /var/www/cachet/vendor/guzzlehttp/guzzle/src/functions.php:119)
[stacktrace]
`
Php extensions:

`calendar
Core
ctype
curl
date
dom
exif
FFI
fileinfo
filter
ftp
gd
gettext
hash
iconv
igbinary
imap
json
libxml
mbstring
memcached
msgpack
mysqli
mysqlnd
openssl
pcntl
pcre
PDO
pdo_mysql
pdo_sqlite
Phar
posix
readline
Reflection
session
shmop
SimpleXML
soap
sockets
sodium
SPL
sqlite3
standard
sysvmsg
sysvsem
sysvshm
tokenizer
xml
xmlreader
xmlwriter
xsl
Zend OPcache
zip
zlib
`

**Comment by jbrooksuk** [comment]
Can you please let me know what the output of `php -i | grep allow_url_fopen` is?

**Comment by linuxgokan** [comment]
as follows:
`allow_url_fopen => On => On
`

**Comment by linuxgokan** [comment]
Can you support me on this issue?

**Comment by steffjenl** [comment]
> as follows: `allow_url_fopen => On => On `

Can you look if curl and allow_url_dopen is enabled for php fpm? Maybe curl is not enabled for php-fpm.

**Comment by linuxgokan** [comment]
php7.2 - php.ini:
https://paste.ubuntu.com/p/gVCcRJrc77/plain/

**Comment by jbrooksuk** [comment]
@linuxgokan is it possible to share this into a Gist or something? I don't have a Ubuntu Paste account, sorry.

I think @steffjenl is on to something in that PHP-FPM may have different extensions enabled.
