### ISSUE TITLE
Composer Base table or view not found

### ISSUE THREAD

**Issue by 0147500** [cachethq/Cachet#438]
Hello,

When i do a clean install with Cachet and run the command php composer.phar install --no-dev -o I got the following error:
```
{"error":{"type":"Illuminate\\Database\\QueryException","message":"SQLSTATE[42S02]: Base table or view not found: 1146 Table 'cachet.settings' doesn't exist (SQL: select * from `settings`)","file":"\/usr\/share\/nginx\/html\/status\/vendor\/laravel\/framework\/src\/Illuminate\/Database\/Connection.php","line":625}}{"error":{"type":"Illuminate\\Database\\QueryException","message":"SQLSTATE[42S02]: Base table or view not found: 1146 Table 'cachet.settings' doesn't exist (SQL: select * from `settings`)","file":"\/usr\/share\/nginx\/html\/status\/vendor\/laravel\/framework\/src\/Illuminate\/Database\/Connection.php","line":625}}
``` 
Any idear on how to resolve this? I saw a issue before but that didn't solve it.

Btw.
I like the project, keep up the great work!

**Comment by jbrooksuk** [comment]
You need to run `php artisan migrate` to get the tables created. Before that though you'll want to set your environment settings.

See the [install docs](https://docs.cachethq.io/v1.0/docs/installing-cachet#configuring-a-database-without-heroku).

Thanks for your kind words :)

**Comment by 0147500** [comment]
I can't run ```php artisan migrate``` because i can't run ```composer install..``` :)

I fllowed your docs step by step. Have create a .env.local.php with the correct settings. The $ENV is empty.

**Comment by jbrooksuk** [comment]
Hah, whoops. I misread your issue.

**Comment by 0147500** [comment]
okay i will see if i can do some debugging myself. Never had this before?

**Comment by jbrooksuk** [comment]
I think I know why. One second.

**Comment by jbrooksuk** [comment]
All fixed for :smile:

**Comment by 0147500** [comment]
Im sorry but that still dind't fix it. :(

**Comment by jbrooksuk** [comment]
You'll need to run `composer update` too. I had to fix Laravel Segment.

**Comment by 0147500** [comment]
okay will try that :)

**Comment by 0147500** [comment]
Nope sorry that still didn't fix it :(

**Comment by jbrooksuk** [comment]
What error are you getting now?

**Comment by 0147500** [comment]
```
{"error":{"type":"Illuminate\\Database\\QueryException","message":"SQLSTATE[42S02]: Base table or view not found: 1146 Table 'cachet.settings' doesn't exist (SQL: select * from `settings`)","file":"\/usr\/share\/nginx\/html\/status\/vendor\/laravel\/framework\/src\/Illuminate\/Database\/Connection.php","line":625}}{"error":{"type":"Illuminate\\Database\\QueryException","message":"SQLSTATE[42S02]: Base table or view not found: 1146 Table 'cachet.settings' doesn't exist (SQL: select * from `settings`)","file":"\/usr\/share\/nginx\/html\/status\/vendor\/laravel\/framework\/src\/Illuminate\/Database\/Connection.php","line":625}}
```

**Comment by jbrooksuk** [comment]
Urgh, I forgot to commit a file.

**Comment by 0147500** [comment]
Okay :)

**Comment by jbrooksuk** [comment]
Pull down again :)

**Comment by 0147500** [comment]
okay ^.^

**Comment by 0147500** [comment]
That did the trick :) need to give my vm a 1GB Ram to do the composer update but it worked THX. I think i will see if i can contribute to your project asswell :)

**Comment by jbrooksuk** [comment]
Try adding [swap](https://www.digitalocean.com/community/tutorials/how-to-add-swap-on-ubuntu-12-04) to it.
