### ISSUE TITLE
composer.lock needing php8.2

### ISSUE THREAD

**Issue by 99kennetn** [cachethq/cachet#4383]
When testing the new 3.x branch i found that i could not make a composer install.
The requirements says php8.1^ is needed, but when i run composer install with php 8.1 it gives me an error as it needs 8.2.
I am fine with it being 8.2^ but i think either the composer.lock file should be updated or the requirements in the README should be adjusted to reflect this :)
![image](https://github.com/cachethq/cachet/assets/38552536/7eab3634-04d4-4bb7-9a21-08d2645185da)

**Comment by jbrooksuk** [comment]
Thanks for reporting! This should be fixed now.
