### ISSUE TITLE
3.x branch unusable because there is no route?

### ISSUE THREAD

**Issue by fbouynot** [cachethq/cachet#4388]
Hello,

I tried to install the 3.x branch of cachet, although I only get the 404 Laravel error page.

[Here](https://gist.github.com/fbouynot/e6c38194277976347c010deee70f474c) are the steps I tried to have a basic install on Fedora39.
I had to comment `fastcgi_intercept_errors on;` in `/etc/nginx/default.d/php.conf` in order to see the Laravel 404 instead of the nginx 404.
There is no log in `storage/logs` after I get a 404, although I could see some logs in other cases (eg trying app:install) so the file can be written.
If I set `APP_ENV=local` and `APP_DEBUG=true` I get the same page, no dump, no more info, it looks like it's a real 404.

I can see that there is no route in neither [cachet](https://github.com/cachethq/cachet/blob/3.x/routes/web.php) or [core](https://github.com/cachethq/core/tree/main/routes), so that explains the 404.
Since there is a [v3 demo](https://v3.cachethq.io/), I think there is a way for v3 to work.

**Questions**:
- Is there a way to setup 3.x already?
- If so, could someone please give me a hint on how to do it? (or a link to some doc or repo or branch)

**Comment by jbrooksuk** [comment]
The `core` package registers a route, but you'll need to set `CACHET_PATH=/` to get Cachet running on the root domain.

**Comment by jbrooksuk** [comment]
By the way, you can always run `php artisan route:list` to see all registered routes within a Laravel application.

**Comment by fbouynot** [comment]
Thanks a lot for your guidance, I could see all routes with `php artisan route:list` and try to move the root with `CACHET_PATH=/`.
This solves my issue.

I couldn't use the setup helper because of a csrf issue I guess (419 page expired whatever I try), although by using Tinker I could make an admin account and have a cachet status page working.
I updated my gist in case it could help someone.

**Comment by jbrooksuk** [comment]
Ah, the setup wizard is not complete yet.
