### ISSUE TITLE
MFA activation gives HTTP 500

### ISSUE THREAD

**Issue by Artic6** [cachethq/cachet#4391]
I am unable to enable to factor authentication because I get an internal server error (500) I would imagine it’s missing a module or plug-in to be able to interact with Google authenticator to get the QR code that I need to scan - this is what I get in the logs

When you go to enable MFA, you do not get a QR code to Scan you getting an internal server error but on your next login it prompt you for a code which you don’t have because you can’t set it up?

This is all I get from the logs, If I need to look in other places, please let me know

[2024-05-31 12:46:09] production.NOTICE: Symfony\Component\HttpKernel\Exception\HttpException in /var/www/html/Cachet/app/Http/Middleware/Authenticate.php:58
Stack trace:
#0 /var/www/html/Cachet/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(163): CachetHQ\Cachet\Http\Middleware\Authenticate->handle()
#1 /var/www/html/Cachet/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#2 /var/www/html/Cachet/vendor/laravel/framework/src/Illuminate/Routing/Middleware/SubstituteBindings.php(41): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}()
#3 /var/www/html/Cachet/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(163): Illuminate\Routing\Middleware\SubstituteBindings->handle()
#4 /var/www/html/Cachet/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#5 /var/www/html/Cachet/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/VerifyCsrfToken.php(75): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}()
#6

**Comment by Artic6** [comment]
Reading the previous closures of this it would appear your focusing on v3

but if you look at your demo site of v3 it’s not fully released and when you look at the v3 demo - it’s still actually v2

**Comment by jbrooksuk** [comment]
@Artic6 that's correct, v3 is the version we're actively working on. However, if you'd like to make a PR to fix this issue I'd happily accept it and release a patch.

**Comment by jbrooksuk** [comment]
By the way, I was not able to replicate this in the [live demo](https://demo.cachethq.io).

![CleanShot 2024-06-03 at 05 36 40@2x](https://github.com/cachethq/cachet/assets/246103/d8cbf8ba-4788-43e0-a569-a61bde4e2373)

**Comment by Artic6** [comment]
I don’t get the QR code. I just get an internal server error.

do I need to download a component that I’m missing?

**Comment by jbrooksuk** [comment]
The package that generates the QR code is already required by default. Can you provide information on the server you're running Cachet on? What version of PHP etc?

**Comment by Artic6** [comment]
Ubuntu 20.04 and its PHP 7.4 - I had trouble getting it working on PHP 8.2

*Lee Croucher *
*🐻*| ***@***.*** | w:https://a6n.co.uk <http://www.a6n.co.uk/>
  <http://facebook.com/artic6>  <http://us.linkedin.com/in/artic6>
<http://twitter.com/artic6>  <http://flickr.com/photos/croucher_lee>
<http://itunes.apple.com/app/artic6>  <http://drive.google.com/artic6>

**Comment by Artic6** [comment]
I’m not on v3 because it’s not released, I don’t think it justifies the
video the moment you click on Google authenticator you immediately get the
internal serve error

It does not show you the QR code and then it prevents you logging in
because the next time you login it asked for your authentication token

The problem with this is you don’t get a QR code to scan what would cause
it not to generate that QR code?


*Lee Croucher *
*🐻*| ***@***.*** | w:https://a6n.co.uk <http://www.a6n.co.uk/>
  <http://facebook.com/artic6>  <http://us.linkedin.com/in/artic6>
<http://twitter.com/artic6>  <http://flickr.com/photos/croucher_lee>
<http://itunes.apple.com/app/artic6>  <http://drive.google.com/artic6>
