### ISSUE TITLE
Creating maintenance tasks, fail to show

### ISSUE THREAD

**Issue by Artic6** [cachethq/cachet#4392]

**Comment by Artic6** [comment]
If I create a maintenance task for within my time zone and within the date specified as today

It successfully saves the maintenance task, I can see that maintenance task in the database, but it doesn’t seem to appear on the page website, on your demo website, I would expect it to be above the incidents

**Comment by Artic6** [comment]
I’ve gone back through the previous issues and it would appear if you set the end maintenance it considers it Complete

might it be an idea to add in the next version? A note to say? Do not set the completion until you’re ready to close the maintenance task?

**Comment by jbrooksuk** [comment]
@Artic6 yeah, this was always confusing in v2.x. I would like to change this in v3.
