### ISSUE TITLE
Incident update page : HTTP 500

### ISSUE THREAD

**Issue by Artic6** [cachethq/cachet#4393]
I’m using the latest version, however, what I have noticed is when I create an incident and provide updates it works very well, When you click on the update, you see the incident page, which is absolutely fine

I have created three individual incidents that are all working absolutely fine, However, at some point when you click on one of the instant pages rather than seeing the incident status, you will get an internal server error, Which I don’t understand, It seems to be working one minute and then all of a sudden you can’t click on the update or the history updates because the website categorically assumes as a server error, this was after creating an incident in the past?

I do wonder if as the Code seems to go /incident/5 then the next one will be /incident/6

If you then put an update that predates the date of one of your incidents does that incorrectly override the record and you get the server error?

I like the quite a lot, however it would appear v3 is not released and version 2.4 seems to be very buggy?

**Comment by jbrooksuk** [comment]
@Artic6 sorry for the delay in getting back to you, I was on holiday last week. Cachet 3.x is still under active development, so we're still working out these bugs. 2.4 is a few years old and also a bit buggy in places.

3.x aims to fix all issues, while making Cachet simpler to use (and maintain) and more powerful.

I noticed you closed this issue, did you figure it out?
