### ISSUE TITLE
Incident limited to one component

### ISSUE THREAD

**Issue by Artic6** [cachethq/cachet#4394]
****Updated

When you go to create an incident it seems to be limited so you can only choose one component,  can you add the option to be able to choose multiple components

I presume this is a feature coming in v3

**Comment by matthewcostin3125** [comment]
I would like to see this feature also. 
There has been a few times there been incident that has taken a few components out with it

**Comment by jbrooksuk** [comment]
This is different in v3 👍🏻

**Comment by Artic6** [comment]
When is that actually available though?

Regards,

Lee Croucher

📧: ***@***.***
🚦: http://a6n.co.uk

**Comment by jbrooksuk** [comment]
@Artic6 v3 is still under development. v2 won't be receiving any additional updates, but this **is coming** to Cachet.
