### ISSUE TITLE
Subscribers get additional unnecessary emails

### ISSUE THREAD

**Issue by Artic6** [cachethq/cachet#4395]
When you were a subscriber to a particular component is there a way to only get the incident update and not the message to save a component has changed state

I really need the incident updates going out to people not the fact that the component status has changed, is there a way to turn this off from the configuration?

furthermore is there an option so you can customise the email that gets sent out when you click the notify subscriber button?

**Comment by Artic6** [comment]
I have looked at that, seems like to you need to set "true" in this file 

true   // Silent mode

However it still tries to send the email : 

Connection could not be established with host in-v3.mailjet.com :stream_socket_client(): unable to connect to tcp://in-v3.mailjet.com:587 (Connection timed out) at /var/www/html/Cachet/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Transport/StreamBuffer.php:261)

The server is not allowed via firewall yet, but it should not do this ?

**Comment by ppomes** [comment]
I just found the fix was not complete, I cannot edit issue to re-open it. Can you reopen-it?

My fix is working when editing components on the dashboard. But when creating incidents, components are also updated, and email are sent

**Comment by Artic6** [comment]
Reopening issue - it is not fixed like previously reported

**Comment by Artic6** [comment]
I have opened a new issue based on your comment

*Lee Croucher *
*🐻*| ***@***.*** | w:https://a6n.co.uk <http://www.a6n.co.uk/>
  <http://facebook.com/artic6>  <http://us.linkedin.com/in/artic6>
<http://twitter.com/artic6>  <http://flickr.com/photos/croucher_lee>
<http://itunes.apple.com/app/artic6>  <http://drive.google.com/artic6>
