### ISSUE TITLE
Asia/Tehran timezone 1 hour shift

### ISSUE THREAD

**Issue by erfantkerfan** [cachethq/cachet#4399]
Hi,
Timezone of Asia/Tehran was updated couple of months ago (the DST was removed) but this update is not reflected in the app.
I don't know where the changes should be updated otherwise I would have made a PR myself.
thanks

**Comment by jbrooksuk** [comment]
Which version of Cachet are you running, please?

**Comment by erfantkerfan** [comment]
> Which version of Cachet are you running, please?

2.4 since it was the recommended version in docker deoloyment

**Comment by jbrooksuk** [comment]
I think you need to update your timezone lists in either MySQL or check that your server is displaying the right time (likewise, the Docker instance).
