### ISSUE TITLE
I just found the fix was not complete, I cannot edit issue to re-open it. Can you reopen-it?

### ISSUE THREAD

**Issue by Artic6** [cachethq/cachet#4400]
I just found the fix was not complete, I cannot edit issue to re-open it. Can you reopen-it?

My fix is working when editing components on the dashboard. But when creating incidents, components are also updated, and email are sent

_Originally posted by @ppomes in https://github.com/cachethq/cachet/issues/4395#issuecomment-2166550590_

**Comment by Artic6** [comment]
Just to be clear on the requirement because this is caught me up before with issues

When you are sending an incident update and you change the status of a component I do not want those emails going to subscribers, what happens is when you have an incident update and you degrade a component? You get a component update change email you also get the actual updates that the subscribers want to read.

Then when the incident is over and resolved and change the component state back to resolved you get two further emails one with the resolved status and then another stating that the component has been updated

When sending out incident you should only be getting the instant updates you’re sending and not the additional component update emails

I originally had an issue for this but it got closed as been fixed when it’s not actually been fixed which is why it’s reopened

**Comment by Artic6** [comment]
Any updates on this?

what I’m trying to turn off as I’ve said before is when you send an incident I don’t also want the component status changes emails going

**Comment by ppomes** [comment]
Waiting to https://github.com/cachethq/cachet/pull/4403 to be merged to have a full working code.

@Jamesking56, can you have a look at this PR ?

Thanks !

**Comment by Artic6** [comment]
Am I able to manually make the change if you give me the code updates?

*Lee Croucher *
*🐻*| ***@***.*** | w:https://a6n.co.uk <http://www.a6n.co.uk/>
  <http://facebook.com/artic6>  <http://us.linkedin.com/in/artic6>
<http://twitter.com/artic6>  <http://flickr.com/photos/croucher_lee>
<http://itunes.apple.com/app/artic6>  <http://drive.google.com/artic6>

**Comment by ppomes** [comment]
Three solutions in the meanwhile:

- The code update is in the PR, you can apply the same diff. 
- You can clone https://github.com/ppomes/cachet
- If you are using Docker, you can pull hudson13/ppomescachet:2.4.1-20240614-1447

**Comment by Jamesking56** [comment]
> Waiting to #4403 to be merged to have a full working code.
> 
> @Jamesking56, can you have a look at this PR ?
> 
> Thanks !

Did you mean to ping me or the other James 🤣

**Comment by ppomes** [comment]
> > Waiting to #4403 to be merged to have a full working code.
> > @Jamesking56, can you have a look at this PR ?
> > Thanks !
> 
> Did you mean to ping me or the other James 🤣

Lol !!! Sorry, I meant @jbrooksuk   ;-)

**Comment by Artic6** [comment]
I took a look at the file referenced in your code update and I don’t seem to have this bit

function postUpdateComponent(Component $component)

it looks like you want some lines from that code removing?

**Comment by Artic6** [comment]
Has this been fixed now - if so how can I get the updated code ?

**Comment by ppomes** [comment]
Please have a look and try https://github.com/ppomes/cachet - This will help to test if the fix is ok.

**Comment by Artic6** [comment]
If I clean up and reconfigure my environment variables Will all my
configuration remain the same?

I just want to check it will, but I’m sure it will because that’s all
controlled with the database?

Regards,

Lee Croucher

📧: ***@***.***
🚦: http://a6n.co.uk

**Comment by ppomes** [comment]
You can switch between both versions without any config or db loss.

**Comment by Artic6** [comment]
Thanks thanks works as intended

**Comment by Artic6** [comment]
solved by @ppomes
