### ISSUE TITLE
Modify incident email to HTML code?

### ISSUE THREAD

**Issue by Artic6** [cachethq/cachet#4408]
if I send an instant update is there a way I can change the code so that Rowson send the default email. It sends one to a certain HTML file located on the server?

we are looking to brand emails that send out and at the moment I can’t see which file I need to update apply them to the emails received by the end users?

**Comment by jbrooksuk** [comment]
Which version of Cachet are you currently using?

**Comment by Artic6** [comment]
V2.4.1

**Comment by Artic6** [comment]
what would be nice is if you could tell me the file where I can customise the outbound email for an incident or if I can call another file that has the HTML content in it

**Comment by Artic6** [comment]
I have found files called new.blade.php and new.blade.php in this folder:

/var/www/html/Cachet/resources/views/notifications/incident

the new.blade.php has the contents of this:

@component('mail::message')
# {{ trans('notifications.incident.new.mail.greeting', ['app_name' => Config::get('setting.app_name')]) }}

{{ $incident->message }}

@component('mail::button', ['url' => $actionUrl])
{{ $actionText }}
@endcomponent

@lang('Thanks,')<br>
{{ Config::get('setting.app_name') }}

@include('notifications.partials.subscription')

@endcomponent

However that does not look like HTML at all but it does refer to @component('mail::message') - where is this file located ?

**Comment by Artic6** [comment]
Looks like the folder I require is this : 

/var/www/html/Cachet/resources/views/vendor/mail/html

If I ammend the header.blade.php I can add in an image with html, but I cannot tell how the rest of the email is formatted with the content ?

**Comment by Artic6** [comment]
I figured this problem out myself so I’m closing it
