### ISSUE TITLE
Upgrade from 2.3.9 to 2.4.1 throwing error

### ISSUE THREAD

**Issue by catalincolesnicov** [cachethq/cachet#4418]
Hello,

i get following error when I want to upgrade to v2.4.1:

php73 composer.phar install --no-dev -o
Installing dependencies from lock file
Verifying lock file contents can be installed on current platform.
Warning: The lock file is not up to date with the latest changes in composer.json. You may be getting outdated depen                                                                                                                                               dencies. It is recommended that you run `composer update` or `composer update <package name>`.
Nothing to install, update or remove
Package alt-three/bus is abandoned, you should avoid using it. No replacement was suggested.
Package alt-three/validator is abandoned, you should avoid using it. No replacement was suggested.
Package barryvdh/laravel-cors is abandoned, you should avoid using it. No replacement was suggested.
Package chillerlan/php-traits is abandoned, you should avoid using it. No replacement was suggested.
Package jakub-onderka/php-console-color is abandoned, you should avoid using it. Use php-parallel-lint/php-console-c                                                                                                                                               olor instead.
Package jakub-onderka/php-console-highlighter is abandoned, you should avoid using it. Use php-parallel-lint/php-con                                                                                                                                               sole-highlighter instead.
Package laravel/nexmo-notification-channel is abandoned, you should avoid using it. Use laravel/vonage-notification-                                                                                                                                               channel instead.
Package swiftmailer/swiftmailer is abandoned, you should avoid using it. Use symfony/mailer instead.
Package symfony/debug is abandoned, you should avoid using it. Use symfony/error-handler instead.
Package zendframework/zend-diactoros is abandoned, you should avoid using it. Use laminas/laminas-diactoros instead.
Package alt-three/testbench is abandoned, you should avoid using it. No replacement was suggested.
Package fzaninotto/faker is abandoned, you should avoid using it. No replacement was suggested.
Package phpunit/php-token-stream is abandoned, you should avoid using it. No replacement was suggested.
Generating optimized autoload files
Carbon 1 is deprecated, see how to migrate to Carbon 2.
https://carbon.nesbot.com/docs/#api-carbon-2
    You can run './vendor/bin/upgrade-carbon' to get help in updating carbon and other frameworks and libraries that depend on it.
> Illuminate\Foundation\ComposerScripts::postAutoloadDump
> @php artisan package:discover
PHP Fatal error:  Uncaught Symfony\Component\Debug\Exception\FatalThrowableError: Class 'AltThree\Badger\BadgerServiceProvider' not found in /data/web/e130115/html/Cachet/bootstrap/cache/compiled.php:7651
Stack trace:
#0 /data/web/e130115/html/Cachet/bootstrap/cache/compiled.php(7637): Illuminate\Foundation\ProviderRepository->createProvider('AltThree\\Badger...')
#1 /data/web/e130115/html/Cachet/bootstrap/cache/compiled.php(7613): Illuminate\Foundation\ProviderRepository->compileManifest(Array)
#2 /data/web/e130115/html/Cachet/bootstrap/cache/compiled.php(1802): Illuminate\Foundation\ProviderRepository->load(Array)
#3 /data/web/e130115/html/Cachet/bootstrap/cache/compiled.php(2220): Illuminate\Foundation\Application->registerConfiguredProviders()
#4 /data/web/e130115/html/Cachet/bootstrap/cache/compiled.php(1666): Illuminate\Foundation\Bootstrap\RegisterProviders->bootstrap(Object(Illuminate\Foundation\Application))
#5 /data/web/e130115/html/Cachet/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(297): Il in /data/web/e130115/html/Cachet/bootstrap/cache/compiled.php on line 7651
PHP Fatal error:  Uncaught Symfony\Component\Debug\Exception\FatalErrorException: Uncaught Symfony\Component\Debug\Exception\FatalThrowableError: Class 'AltThree\Badger\BadgerServiceProvider' not found in /data/web/e130115/html/Cachet/bootstrap/cache/compiled.php:7651
Stack trace:
#0 /data/web/e130115/html/Cachet/bootstrap/cache/compiled.php(7637): Illuminate\Foundation\ProviderRepository->createProvider('AltThree\\Badger...')
#1 /data/web/e130115/html/Cachet/bootstrap/cache/compiled.php(7613): Illuminate\Foundation\ProviderRepository->compileManifest(Array)
#2 /data/web/e130115/html/Cachet/bootstrap/cache/compiled.php(1802): Illuminate\Foundation\ProviderRepository->load(Array)
#3 /data/web/e130115/html/Cachet/bootstrap/cache/compiled.php(2220): Illuminate\Foundation\Application->registerConfiguredProviders()
#4 /data/web/e130115/html/Cachet/bootstrap/cache/compiled.php(1666): Illuminate\Foundation\Bootstrap\RegisterProviders->bootstrap(Object(Illuminate\Foundation\Application))
#5 /data/web/e130115/html/Cachet/vendor/laravel in /data/web/e130115/html/Cachet/bootstrap/cache/compiled.php on line 7651
Script @php artisan package:discover handling the post-autoload-dump event returned with error code 255

**Comment by jbrooksuk** [comment]
It looks like the `BadgerServiceProvider` package wasn't discovered properly. Can you try running `rm -rf bootstrap/cache/*` and then `composer du`?

**Comment by catalincolesnicov** [comment]
Hello after trying to restart the upgrade process. i get follwoing error:

Generating optimized autoload files
Carbon 1 is deprecated, see how to migrate to Carbon 2.
https://carbon.nesbot.com/docs/#api-carbon-2
    You can run './vendor/bin/upgrade-carbon' to get help in updating carbon and other frameworks and libraries that depend on it.
> Illuminate\Foundation\ComposerScripts::postAutoloadDump
> @php artisan package:discover

In ProviderRepository.php line 208:

  Class 'Barryvdh\Debugbar\ServiceProvider' not found


Script @php artisan package:discover handling the post-autoload-dump event returned with error code 1
