### ISSUE TITLE
Installation documentation incomplete

### ISSUE THREAD

**Issue by dakotawashok** [cachethq/cachet#4422]
Hello I hope you are all doing well. I'm having an issue installing Cachet in my local dev environment to do some testing before using Cachet 3.x in an AWS environment, but I'm having problems verifying my installation. For reference, I'm using Windows 11, developing on WSL2 and PHPStorm. I'm following the instructions on this page https://docs.cachethq.io/installation/guide.html. After following the guide, and some other steps, I can get Laravel running, but the url endpoints don't work, and I get a 404 on every page.

I'm running locally via Laravel Sail. 

`php -v`
```
PHP 8.2.12 (cli) (built: Nov  3 2023 15:38:45) (NTS)
Copyright (c) The PHP Group
Zend Engine v4.2.12, Copyright (c) Zend Technologies
```

`composer --version`
```
Composer version 2.7.2 2024-03-11 17:12:18
PHP version 8.2.12 (/home/dakota/.phpbrew/php/php-8.2.12/bin/php)
```

Some things I've noticed, is that the Prerequisites for the 3.x page seem wrong, since you need PHP 8.1 or higher to run this version of Laravel.

**Comment by dakotawashok** [comment]
I can run `php artisan migrate`, but I cannot run the wrapper as described in the docs `php artisan app:install`.

**Comment by jbrooksuk** [comment]
Thanks for checking out Cachet! The documentation is still targeting 2.x, which is no longer supported. 

It's not quite the same, but you should be able to check out Cachet locally by following my development environment tutorial. https://x.com/jbrooksuk/status/1845087763835633898?s=46

By the way, we have a demo for the new version at https://v3.cachethq.io

**Comment by dakotawashok** [comment]
Is assisting with updating the documentation as simple as opening a PR in the [docs repo](https://github.com/cachethq/docs) that targets the 3.x branch?

**Comment by jbrooksuk** [comment]
Yes, please!
