### ISSUE TITLE
Components Tags

### ISSUE THREAD

**Issue by JanBlatter** [cachethq/cachet#4423]
Hello I'm new to Cachet and I'm working on my first status page. 

I have a major problem with components and their tags. 
When I drag and drop to reorder a component several times, an error message appears saying "ordering not updated".

![Issue1](https://github.com/user-attachments/assets/e564b9f7-9a4d-4b43-8606-c5aba307822f)

And when I check the Tags array in Postman, i see some sort of duplicates 
![Issue2](https://github.com/user-attachments/assets/e76a7acc-84ff-4b35-83d8-3358f6a3ee62)

Do you have a solution for this ? 

Thanks in advance.

**Comment by ppomes** [comment]
@jbrooksuk  - probably the same issue as #4415, and probably solved by #4403

**Comment by ppomes** [comment]
@JanBlatter - maybe you can try #4403 to validate?

**Comment by JanBlatter** [comment]
I tried #4403 but it didn't work for me. However, I can close this issue because i resolved it with another solution.

I simply changed the $tags in postUpdateComponentOrder function

**Comment by ppomes** [comment]
Hi,

Can you show your diff?

Thanks!
Pierre

**Comment by JanBlatter** [comment]
Hello,

I added  in `/var/www/html/app/Http/Controllers/Dashboard/ApiController.php`

+   $tags = Binput::get('tags'. []);
+   $tags,         

try {                                      
            $tags = Binput::get('tags'. []);
            execute(new UpdateComponentCommand( 
                $component,                          
                $component->name,
                $component->description,                          
                Binput::get('status'),                                      
                $component->link,                              
                $component->order,   
                $component->group_id,                       
                $component->enabled,             
                $component->meta,                          
                $tags,                                  
                true   // Silent mode           `
