### ISSUE TITLE
Blank page after installation

### ISSUE THREAD

**Issue by lubrell** [cachethq/cachet#4424]
Similar to #931 I have a blank page after the installation. I have followed the tips in the installation instructions and the public and bootstrap folders each have rwx rwx rwx

```
chmod -R 777 storage
rm -rf bootstrap/cache/*
chmod -R 777 bootstrap/
```

I installed Cachet on a shared webhosting and I got the “Cachet is installed” message:

```
git clone https://github.com/cachethq/Cachet.git
mv Cachet status
cd status
curl -sS https://getcomposer.org/installer | /usr/local/php73/bin/php
COMPOSER_MEMORY_LIMIT=512M /usr/local/php73/bin/php -d memory_limit=512M composer.phar install --no-dev -o
cp .env.example .env
nano .env
git tag -l
git checkout v2.4.1
/usr/local/php73/bin/php artisan key:generate
/usr/local/php73/bin/php artisan cachet:install
```

There is nothing in the error logs. Are there any solutions for this?

**Comment by jbrooksuk** [comment]
@lubrell we're not actively support v2.x any longer. If you email support@cachethq.io, we could talk sponsored support or something? :)
