### ISSUE TITLE
Show "Last Checked" timestamp in status page

### ISSUE THREAD

**Issue by sidt4** [cachethq/cachet#4425]
Here is the screenshot capture today (`Oct 29`). It's displaying a `Updated` date which was from few days ago.

![status gnome-timestamp](https://github.com/user-attachments/assets/bef61536-61c4-46ee-82c7-c099914e7d9c)

Is `Updated` timestamp the last time there was a state change (`failed` to `operational` or vice versa) ?

If yes, I think adding a `Last Checked` timestamp (e.g Last checked: `30 minutes ago`) would be very useful, as one doesn't know if they are looking at a working or a broken status page, if the only timestamps shown in the status page are somewhere in the past.

An old timestamp creates the impression that the status checks have stopped working.

**Comment by jbrooksuk** [comment]
> Is Updated timestamp the last time there was a state change (failed to operational or vice versa) ?

Yes, we show the `updated_at` timestamp value here. By default, Cachet doesn't actively check anything, so there is no "last checked" it's more just "changed at" I guess.

**Comment by sidt4** [comment]
Hi,

What you're trying to say is an implementation detail, which I don't have idea about. So, let me specify the use case.

1. One of the components in our infrastructure is having issues. (say, GitLab is slow to respond for by browser requests).
2. As a user of GitLab, I immediately check the status page (say, for e.g. https://status.gnome.org/) , to see if it's an issue with the server / CDN, or my local network / ISP.
3. But there is no indication in https://status.gnome.org/, if it's actively monitoring GitLab. If it's monitoring when did it last check GitLab status (meaning the timestamp when GitLab was last checked and known to be in `Operational` state).

What's the recommended way to get this information in the status page ?

Thanks!

**Comment by jbrooksuk** [comment]
@sidt4 I've changed the wording on this to show that it was "Last Updated XXXX" instead.

**Comment by sidt4** [comment]
Hi James,

The issue was not about the wording, but about no hint of recency in the status page.

If I'm monitoring a website status, and it was last updated (`Major Outage` -> `Operational`) 2 months ago, having

- Last Updated: 2 months ago  + `Operational`

 is not very helpful. It would be helpful to show

- Last Updated: 2 months ago  + Last Checked: 30 minutes ago + `Operational`
