### ISSUE TITLE
Subscription by component

### ISSUE THREAD

**Issue by HerveMARTIN** [cachethq/cachet#4427]
Is there any way to subscribe to incidents only for a specific component or component group?
If not possible, do you think it could be a future feature?
For us, multiple dev teams don't want to be notified for other teams outage.
Regards

**Comment by jbrooksuk** [comment]
@HerveMARTIN we could look into implementing this in v3.x. We'd actually want to provide a subscription center where you can pick what you're interested in being updated about.

Alternatively, we could add an RSS feed for components too!
