### ISSUE TITLE
ERROR  There are no commands defined in the "app" namespace. 

### ISSUE THREAD

**Issue by lubrell** [cachethq/cachet#4429]
I am currently trying to install version 3.x, but am failing at app:install. Here is my .env
```
APP_NAME=Cachet
APP_ENV=local
APP_KEY=base64:sEcReT;)
APP_DEBUG=true
APP_TIMEZONE=CET
APP_URL=https://example.com

APP_LOCALE=de
APP_FALLBACK_LOCALE=en
APP_FAKER_LOCALE=de_DE

APP_MAINTENANCE_DRIVER=file
# APP_MAINTENANCE_STORE=database

BCRYPT_ROUNDS=12

LOG_CHANNEL=stack
LOG_STACK=single
LOG_DEPRECATIONS_CHANNEL=null
LOG_LEVEL=debug

DB_CONNECTION=mysql
DB_HOST=XX.XX.XX.XX
DB_PORT=3306
DB_DATABASE=cachet
DB_USERNAME=status
DB_PASSWORD=sEcReT;)

SESSION_DRIVER=database
SESSION_LIFETIME=120
SESSION_ENCRYPT=false
SESSION_PATH=/
SESSION_DOMAIN=null

BROADCAST_CONNECTION=log
FILESYSTEM_DISK=local
QUEUE_CONNECTION=database

CACHE_STORE=database
CACHE_PREFIX=

MEMCACHED_HOST=127.0.0.1

REDIS_CLIENT=phpredis
REDIS_HOST=127.0.0.1
REDIS_PASSWORD=null
REDIS_PORT=6379

MAIL_MAILER=log
MAIL_HOST=smtp.example.com
MAIL_PORT=465
MAIL_USERNAME=status@example.com
MAIL_PASSWORD=sEcReT;)
MAIL_ENCRYPTION=SSL
MAIL_FROM_ADDRESS="status@example.com"
MAIL_FROM_NAME="${APP_NAME}"

AWS_ACCESS_KEY_ID=
AWS_SECRET_ACCESS_KEY=
AWS_DEFAULT_REGION=us-east-1
AWS_BUCKET=
AWS_USE_PATH_STYLE_ENDPOINT=false

VITE_APP_NAME="${APP_NAME}"

CACHET_BEACON=false
CACHET_EMOJI=false
CACHET_AUTO_TWITTER=true
```
What have I done wrong?
```
bash-5.1$ /usr/local/php82/bin/php artisan app:install

   ERROR  There are no commands defined in the "app" namespace.
```
How can I solve this error?

**Comment by jbrooksuk** [comment]
The documentation is currently for v2.4, which is no longer supported.

v3 actually should be much easier to install, though we haven't documented it in full yet (sorry!).

1. Clone the `cachethq/cachet` repository with 3.x branch.
2. Install composer dependencies.
3. Configure the `.env` with your database settings etc (and run `php artisan key:generate` ).
4. Run `php artisan migrate`.

You should be good to go from there, I think!

**Comment by lubrell** [comment]
Thank you, that worked (at least in the console). However, when I call up the page, I see an empty page, even the source code is empty. 

The console itself did not report any errors, and the database was also described. The “old” tips from the documentation, chmod for storage and bootsrap did not help either.

Any tips? :)

**Comment by jbrooksuk** [comment]
@lubrell thanks for your patience! I've just ran through the entire process myself, and these are the steps and commands that I took.

1. `git clone -b 3.x git@github.com:cachethq/cachet.git cachet`
2. `cd cachet`
3. `composer install`
4. `cp .env.example .env`
5. Update any `.env` variables for database settings
7. `php artisan key:generate`
7. Update `.env` to set `CACHET_PATH=/`
8. `php artisan vendor:publish --tag=cachet`
9. `php artisan migrate`

I hope this helps!

I will improve on this for the official documentation soon enough.

**Comment by lubrell** [comment]
@jbrooksuk I tried your procedure, even though I had to change it a little, because otherwise it wouldn't work with the provider I was using:

1. `git clone -b 3.x https://github.com/cachethq/cachet.git`
2. `cd cachet`
3. `curl -sS https://getcomposer.org/installer | /usr/local/php82/bin/php`
4. `COMPOSER_MEMORY_LIMIT=512M /usr/local/php82/bin/php -d memory_limit=512M composer.phar install --no-dev -o`
5. `cp .env.example .env`
6. `nano .env` to change the database and more
7. `/usr/local/php82/bin/php artisan key:generate`
8. `nano .env` o set `CACHET.PATH=/`, but this was not necessary
9. `/usr/local/php82/bin/php artisan vendor:publish --tag=cachet`
10. `/usr/local/php82/bin/php artisan migrate`

As before, everything seemed to work smoothly. But when I call up the subdomain (which points to the public folder), I only get a blank page... Have I forgotten anything or even done something wrong?

**Comment by jbrooksuk** [comment]
@lubrell I think it may be best if we video call at some point to figure this out. Can you email james@alt-three.com and we'll find a time?

**Comment by lubrell** [comment]
@jbrooksuk Hey James, I sent you an email a few days ago. Did you receive it?
