### ISSUE TITLE
A bunch of bugs

### ISSUE THREAD

**Issue by wfjsw** [cachethq/Cachet#443]
First, when i was upgrading my heroku install, it gives me 
```
remote:        PHP Fatal error:  Class 'CachetHQ\Segment\SegmentServiceProvider' not found in /tmp/build_a9b08c9b7fcf159
cba5ea83dee39e9e8/vendor/laravel/framework/src/Illuminate/Foundation/ProviderRepository.php on line 157
remote:        {"error":{"type":"Symfony\\Component\\Debug\\Exception\\FatalErrorException","message":"Class 'CachetHQ\\
Segment\\SegmentServiceProvider' not found","file":"\/tmp\/build_a9b08c9b7fcf159cba5ea83dee39e9e8\/vendor\/laravel\/fram
ework\/src\/Illuminate\/Foundation\/ProviderRepository.php","line":157}}Script php artisan optimize handling the post-in
stall-cmd event returned with an error
remote:
remote:
remote:

remote:   [RuntimeException]

remote:   Error Output: PHP Fatal error:  Class 'CachetHQ\Segment\SegmentServiceProvider' not found in /tmp/build_a9b08c
9b7fcf159cba5ea83dee39e9e8/vendor/laravel/framework/src/Illuminate/Foundation/ProviderRepository.php on line 157
```

I want to access API but I got this(debug mode):(want more access: http://status.nyanyanya.moe/api/incidents )
```
ErrorException (E_UNKNOWN)

Argument 1 passed to Illuminate\Database\Grammar::columnize() must be of the type array, string given, called in /app/vendor/laravel/framework/src/Illuminate/Database/Query/Grammars/Grammar.php on line 105 and defined 
```
have a look at it plz

**Comment by GrahamCampbell** [comment]
Have you run composer install after your upgrade?

**Comment by wfjsw** [comment]
unable to manual "composer install" in heroku upgrade progress.

**Comment by wfjsw** [comment]
BTW when i install it on linode it throws
ApcWrapper: not defined function(i have disabled it in config)
app/database/meta/services.json: Unable to open stream--Permission Denied

**Comment by jbrooksuk** [comment]
1. You need to be running `composer update` on your existing installation.
2. I'll take a look at the bug in the incident API.
3. You need php-apcu installed.
4. You need to chmod the `app/storage` directory.

**Comment by GrahamCampbell** [comment]
@jbrooksuk We can't recommend running `composer update` because it means people are using untested dependencies in production.

**Comment by jbrooksuk** [comment]
Good point. Will update my comment.

**Comment by jbrooksuk** [comment]
What database are you running?

**Comment by wfjsw** [comment]
i am using "deploy to heroku" button

**Comment by jbrooksuk** [comment]
If you're on the latest version the error does seem to be fixed. See the [demo](http://cachet.herokuapp.com/api/incidents).

**Comment by GrahamCampbell** [comment]
@jbrooksuk We should probably pretty print the json too.

**Comment by jbrooksuk** [comment]
Using `Response::json`?

**Comment by GrahamCampbell** [comment]
Yeh, we can do.

**Comment by GrahamCampbell** [comment]
TBH, I think laravel should pretty print by default.

**Comment by GrahamCampbell** [comment]
I think I'll send a pull to 5.0 to do that actually.

**Comment by jbrooksuk** [comment]
:D

**Comment by wfjsw** [comment]
I will do an update 12 hours later. Keep in touch.

**Comment by wfjsw** [comment]
i really don't think i can ```composer update```when i am pushing to an *heroku* repo.

**Comment by jbrooksuk** [comment]
Please see the [Upgrading on Heroku](https://docs.cachethq.io/v1.0/docs/upgrading-on-heroku) documentation.

**Comment by GrahamCampbell** [comment]
Yeh, about that...

![image](https://cloud.githubusercontent.com/assets/2829600/5988572/fc8fa13a-a95d-11e4-88df-021d079d3dda.png)

**Comment by jbrooksuk** [comment]
God damn it Cloudflare... http://cachet.readme.io/v1.0/docs/upgrading-on-heroku
