### ISSUE TITLE
Is the cache with Redis working?

### ISSUE THREAD

**Issue by danlucioprada** [cachethq/cachet#4430]
I am trying to configure Cachet to use Redis for both session storage and caching, but it doesn't seem to be taking effect. Even with debug enabled, I haven't found any clues, and no records were created in Redis either.

I tried investigating Redis usage in the source code and saw that it uses the Predis client; I attempted to find any usage references in the source code but was also unsuccessful.

I am using v2.4 with the following environment variables:

```
SESSION_DRIVER=redis
CACHE_DRIVER=redis
REDIS_HOST=<MY-REDIS-IP>
```

**Comment by jbrooksuk** [comment]
Cachet doesn't really do any caching in 2.x. I hope to resolve this at some point in 3.x though, so that we pull status page data from the cache.
