### ISSUE TITLE
Cachet v3.x

### ISSUE THREAD

**Issue by kash1983** [cachethq/cachet#4432]
Hello,

is it possible to test the V3.x?
Can you explain an short step by step or Dockerfile for build?

I build the 2.4 with the old Dockerfile of the docker repo.
It all works, i then tried it with the same dockerfile with php8 and V3.x git clone, but the failed with errors.

Thanks Björn

**Comment by jbrooksuk** [comment]
Hey @kash1983, thanks for checking out Cachet v3.x! I've just updated the installation documentation which should get you going https://docs.cachethq.io/v3.x/installation
