### ISSUE TITLE
Database QueryException 

### ISSUE THREAD

**Issue by Saady03** [cachethq/cachet#4437]
Hello I'm trying to install the version 3 of the projet cachet. I use laravel 11 and php 8.3.
Unfortunately i'm struggling with many issues.
Firstly when i initiate with php artisan migrate  I had
SQLSTATE[42P07]: Duplicate table: 7 ERROR:  relation "tags" already exists (Connection: pgsql, SQL: create table "tags" ("id" serial not null primary key, "name" varchar(255) not null, "slug" varchar(255) not null, "created_at" timestamp(0) without time zone null, "updated_at" timestamp(0) without time zone null))
Secondly 
 Illuminate\Database\QueryException 

SQLSTATE[42703]: Undefined column: 7 ERROR:  column "status_id" of relation "incident_components" does not exist (Connection: pgsql, SQL: comment on column "incident_components"."status_id" is NULL)  currently

**Comment by jbrooksuk** [comment]
@Saady03 thanks for reporting this. Two questions:

1. Are you upgrading an existing Cachet 2.x instance?
2. Are you installing this into an existing Laravel project **or** are you installing Cachet via `cachethq/cachet:3.x`?

**Comment by Saady03** [comment]
No @jbrooksuk, distinctly, Before trying to install Cachet 3x I was interested to Cachet 2x  so i used the documentation and cloned the project, but I I was confronted to deprecreated version of php 7.1 with ubuntu 22.Besides, I tried to install it with docker  abortively

**Comment by Saady03** [comment]
When i type composer update cachethq/core, it seems that it doesn't work because when i launch the migrate command i still have 
 SQLSTATE[42703]: Undefined column: 7 ERROR: column "status_id" of relation "incident_components" does not exist (Connection: pgsql, SQL: comment on column "incident_components"."status_id" is NULL) currently

**Comment by jbrooksuk** [comment]
@Saady03 are you able to run the migrations with a new database and then recreate the components again?

**Comment by Saady03** [comment]
Yes i I think that the issues are about some mistakes in the migrations files, for example the down function of  schedules tables talks about incidents or integer in the up wchich becomes boolean i tried to fix them and now I successfully run migration but my problem now is about the type of status which change from unsignedInteger or unisgnedTinyInteger....

When i run php artisan serve now i have this erros 
SQLSTATE[42P08]: Ambiguous parameter: 7 ERROR: inconsistent types deduced for parameter $1 LINE 1: select count(*) as total, sum(case when $1 in (incidents.sta... ^ DETAIL: integer versus smallint (Connection: pgsql, SQL: select count(*) as total, sum(case when 4 in (incidents.status, latest_update.status) then 1 else 0 end) as resolved, sum(case when 4 not in (incidents.status, latest_update.status) then 1 else 0 end) as unresolved from "incidents" inner join (select "iu1"."updateable_id", "iu1"."status" from "updates" as "iu1" inner join (select "updateable_id", max(id) as max_id from "updates" where "updates"."updateable_type" = incident group by "updateable_id") as "iu2" on "iu1"."id" = "iu2"."max_id") as "latest_update" on "latest_update"."updateable_id" = "incidents"."id" where "incidents"."deleted_at" is null limit 1)
![cachet](https://github.com/user-attachments/assets/919160a6-eb57-4a24-9438-231cc0e2f39e)

**Comment by jbrooksuk** [comment]
Interesting. It looks like we may have some issues in Postgres we're not testing for currently. I'll need to dig into this some more, unless you're able to make a PR in the meantime :)

**Comment by Saady03** [comment]
Finally, I can have the index page. 
![index](https://github.com/user-attachments/assets/5484e9e5-a716-4548-bcc9-febd25f73ddc)
 I changed the the tinyInteger to integer respectively in the migration files 2024_10_13_214300_drop_schedule_status and 2024_10_11_150422_add_morphable_columns_to_incident_updates.

**Comment by jbrooksuk** [comment]
Fixed in https://github.com/cachethq/core/commit/7cc746923b6619163ee809e9e23ae212ab4ddd4b
