### ISSUE TITLE
Admin User

### ISSUE THREAD

**Issue by diogorocha18** [cachethq/cachet#4439]
I'm new to the project and I installed it to see how it works, however, I realized that after installation I can't create an account.. And in the documentation I don't think there's anything about it either..

Version 3.x

**Comment by jbrooksuk** [comment]
Thanks for checking out Cachet! Currently we don't have a way to set up Cachet once it's first installed. I'd recommend running the seeder to generate the test user and then updating it. It's a pain, but Cachet is still under development.

**Comment by diogorocha18** [comment]
> Thanks for checking out Cachet! Currently we don't have a way to set up Cachet once it's first installed. I'd recommend running the seeder to generate the test user and then updating it. It's a pain, but Cachet is still under development.

Can you tell me how to install "seeder" and use it to generate a new user?
Or tell me how to generate a user when installing again?

**Comment by jbrooksuk** [comment]
Okay, I've just created a new `cachet:make:user` command that you can run to create the first user.

We don't currently handle admin / super users within Cachet, so this command isn't fully fleshed out yet.
