### ISSUE TITLE
Issue creating incidents

### ISSUE THREAD

**Issue by Iratu2** [cachethq/cachet#4440]
Heya, I've been running into this error

```Filament\Support\Services\RelationshipJoiner::prepareQueryForNoConstraints(): Argument #1 ($relationship) must be of type Illuminate\Database\Eloquent\Relations\Relation, null given, called in /home/website.org/vendor/filament/forms/src/Components/Select.php on line 765 ```

Full error: [laravel.log](https://github.com/user-attachments/files/18117000/laravel.log)

Running version 3 fresh install tried wiping cache couple of times as well.

**Comment by jbrooksuk** [comment]
Thanks for reporting this, it looks like the relation was incorrectly removed. It's now fixed in https://github.com/cachethq/core/commit/91c4aaad7ce363b2619611edbf1b1f2ecccd80c1
