### ISSUE TITLE
Tried loading settings 'Cachet\Settings\ThemeSettings', and following properties were missing: accent, accent_content, accent_pairing

### ISSUE THREAD

**Issue by classictnl** [cachethq/cachet#4445]
Dear,

Getting different errors when installing the new V3.x

![image](https://github.com/user-attachments/assets/50c2e8c2-f145-4058-8891-0b6c4b3a4bfb)

![image](https://github.com/user-attachments/assets/fa4360e9-5365-4163-93fb-6109bb801923)

**Comment by jbrooksuk** [comment]
I think you're upgraded from a previous revision. Can you try running `php artisan migrate`

**Comment by classictnl** [comment]
Done this. It works nice!

**Comment by jbrooksuk** [comment]
> Done this. It works nice!

Great! I'll close this issue. Let me know if you have any other questions.
