### ISSUE TITLE
Dashboard Login

### ISSUE THREAD

**Issue by guilhermehschmitt** [cachethq/cachet#4446]
Hello!

I've been trying to test version 3 of the cachet, but the dashboard and login page seem to be missing.

Is this correct?

When I try to access http://x.x.x.x/dashboard/login I get a page not found error.

**Comment by jbrooksuk** [comment]
Weird! What's your `CACHET_PATH` set to in your `.env` file?

Did you follow https://docs.cachethq.io/v3.x/installation?

**Comment by guilhermehschmitt** [comment]
Hi, 
Yeah, I have followed the link:https://docs.cachethq.io/v3.x/installation

My CACHET_PATH is: CACHET_PATH=/opt/cachet/

Is that wrong?
I understood that it would be the path to the folder where the files are.

Detail: Only the dashboard or administration page does not open, it returns a 404 error.
The Cachet initial status page works normally.

**Comment by jbrooksuk** [comment]
Ah, the `CACHET_PATH` setting is the web directory. So for it to be at the root of your site, you should set it to just `/`. Hope that helps!

**Comment by sirmelonchen** [comment]
Hey, same Issue here.

My `CACHET_PATH` is `/`. 

Thanks for the Response.

**Comment by jbrooksuk** [comment]
@sirmelonchen can you try running `php artisan route:list` and let me know the full output, please?

**Comment by sirmelonchen** [comment]
[routes (1).txt](https://github.com/user-attachments/files/18421175/routes.1.txt)
These are my routes.

**Comment by jbrooksuk** [comment]
Thanks! I would try running `php artisan route:cache` as the routes are defined for `/dashboard/login`.

**Comment by sirmelonchen** [comment]
It isn't working with your command either.

**Comment by jbrooksuk** [comment]
@sirmelonchen can you try running the following, please:

1. `git pull origin 3.x`
2. `composer install -o --no-dev`
3. `rm -rf storage/cache`
