### ISSUE TITLE
Exception: components.tags may not be NULL

### ISSUE THREAD

**Issue by Finkregh** [cachethq/Cachet#446]
When i try to add a component i get the following error:
```
SQLSTATE[23000]: Integrity constraint violation: 19 components.tags may not be NULL (SQL: insert into "components" ("order", "group_id", "name", "status", "description", "link", "user_id", "updated_at", "created_at") values (0, , Firewalls, 1, , , 1, 2015-02-04 07:19:17, 2015-02-04 07:19:17))
```

POST data:
```
component	Array ( [name] => Firewalls [status] => 1 [description] => [group_id] => [link] => [tags] => Hardware [user_id] => 1 [order] => 0 )
```

I still use sqlite, cachet @367af86f0b8d38043ff5ec4d08219e34aa79b2fc, npm, bower, etc. up2date

**Comment by jbrooksuk** [comment]
CC @cachethq/owners we really need to come up with a way of handling these `NULL` values better.

**Comment by jbrooksuk** [comment]
Did you upgrade from a previous version? You need to drop the `components.tags` column.

**Comment by Finkregh** [comment]
i did; should that not be handled by `artisan migrate`?

**Comment by jbrooksuk** [comment]
You'd think so, but since we're in beta, we change the existing migrations I'm afraid. We're actually going to work on a package to merge migrations.

**Comment by Finkregh** [comment]
well, i suspected an answer like that ;)

anybody got a sqlite-command handy for that?

**Comment by jbrooksuk** [comment]
Unfortunately not. You'll need to connect via some GUI tool and remove them with that I'm afraid. After V1, running Cachet from `master` will be much easier so long as we get the migration package written.

I am sorry for this inconvenience though.
