### ISSUE TITLE
Chinese is unable to display

### ISSUE THREAD

**Issue by wfjsw** [cachethq/Cachet#447]
Due to fonts reason, when an Asian language is installed, the char will just disappeared. They cannot display properly in that environment.

I am using the Crowdin's translate file.

**Comment by jbrooksuk** [comment]
Thanks for reporting this. I guess that's to do with Open Sans? Or is the font displaying as Lato for you? It depends on if you pulled recently.

**Comment by wfjsw** [comment]
first, open sans never supports chinese.
second, it seems that google fonts' charset have some problem with processing it :(

**Comment by jbrooksuk** [comment]
I'm not sure how we can fix this then I'm afraid.

**Comment by wfjsw** [comment]
simply change an charset-friendly font when selecting asian language.

**Comment by jbrooksuk** [comment]
I'm wondering if we make it so that if the language is Chinese or anything with other unsupported diacritics etc use a different font.

We can't drop Open Sans easily as it's part of the consistent branding for Cachet.

**Comment by wfjsw** [comment]
Fine.

**Comment by jbrooksuk** [comment]
> I'm wondering if we make it so that if the language is Chinese or anything with other unsupported diacritics etc use a different font.

What do you think about that @wfjsw

**Comment by wfjsw** [comment]
Exactly the same. System Fonts did well in it.

**Comment by jbrooksuk** [comment]
Do you have any ideas on how we can fix this without losing the font for the other languages?

**Comment by wfjsw** [comment]
I am now wondering what cause that problem. Google Fonts or CSS?
My solution is using php to dynamic output an override-css ('!important' may help) file when using these languages. 

And another problem is that google is blocked in Mainland China. Any query to their services will slow down whole page. (We use mirrors or complete remove them)

**Comment by jbrooksuk** [comment]
Closed by #570.

**Comment by wfjsw** [comment]
@jbrooksuk 
Crazy things happened on Crowdin: My translations all disappeared:
![sshot1](https://cloud.githubusercontent.com/assets/2220320/7016336/d525ae60-dd14-11e4-8edb-77c01118815a.JPG)
![sshot2](https://cloud.githubusercontent.com/assets/2220320/7016337/d727a376-dd14-11e4-893d-868481117fb1.JPG)
But......
![sshot3](https://cloud.githubusercontent.com/assets/2220320/7016339/db0e9f6c-dd14-11e4-9301-f0dcd8efc35b.JPG)
What is happening in the world......

**Comment by jbrooksuk** [comment]
That is strange @wfjsw... I don't remember doing anything to them.

**Comment by wfjsw** [comment]
@jbrooksuk
Website is okay now. But I found that Crowdin won't export unvalidated translations :( Maybe there is somethings wrong with the settings

**Comment by wfjsw** [comment]
@jbrooksuk
Website is okay now. But I found that Crowdin won't export unvalidated translations :( Maybe there is somethings wrong with the settings

**Comment by jbrooksuk** [comment]
> Website is okay now. But I found that Crowdin won't export unvalidated translations :( Maybe there is somethings wrong with the settings.

I'll add you to the team, so you can validate them :)

**Comment by jbrooksuk** [comment]
@wfjsw I've added you as a proofreader, so you should now be able to accept translations.

**Comment by wfjsw** [comment]
@jbrooksuk
Website is okay now. But I found that Crowdin won't export unvalidated translations :( Maybe there is somethings wrong with the settings

**Comment by wfjsw** [comment]
@jbrooksuk
Website is okay now. But I found that Crowdin won't export unvalidated translations :( Maybe there is somethings wrong with the settings

**Comment by wfjsw** [comment]
@jbrooksuk
Website is okay now. But I found that Crowdin won't export unvalidated translations :( Maybe there is somethings wrong with the settings

**Comment by jbrooksuk** [comment]
@wfjsw you're spamming us...

**Comment by wfjsw** [comment]
@jbrooksuk  sorry but i have a really low network latency......

**Comment by jbrooksuk** [comment]
I gather, with you being in China :)

**Comment by wfjsw** [comment]
@jbrooksuk kick off the crowdin build please :)

**Comment by jbrooksuk** [comment]
On it :)

**Comment by jbrooksuk** [comment]
Done.
