### ISSUE TITLE
Docker should use nginx

### ISSUE THREAD

**Issue by jbrooksuk** [cachethq/Cachet#448]
This would make it more lightweight and easier to configure. Plus, we should really be advising use of a better web server anyway.

**Comment by joecohens** [comment]
:+1:

**Comment by sammcj** [comment]
+1

**Comment by jbrooksuk** [comment]
I've no experience with Docker, so if somebody fancies doing this, that'd be lovely.

**Comment by GrahamCampbell** [comment]
Docker is apparently an arse to configure. For example, if we had our db in a different container, we've got no way of knowing that other container's ip or hostname before we've booted it so our web container is kind of screwed.

**Comment by sammcj** [comment]
We've got lots of docker & nginx experience @infoxchange but almost no PHP experience - I'll take a look though and see what I can come up with this week unless work gets busier.

**Comment by jbrooksuk** [comment]
@GrahamCampbell can you get on Slack for a minute? :)

**Comment by sammcj** [comment]
@grahamcampbell - it's not an arse to configure at all? Docker is very easy to work with compared to say - deploying with multiple package managers for all the crazy languages out there.  

With the database, you can just require the use of another upstream database container which you connect to via environment variables or a config file presented to the container.

Anyway, if I get time this week I'll take a look at it.

**Comment by GrahamCampbell** [comment]
@sammcj That's not what I've been told. I too have little experience with docker though.

**Comment by sammcj** [comment]
One of its main advantages is that it makes deployment easy and reproducible.

We moved all our applications, old and new alike from VMs into containers last year many of them are highly complex with many relaionships and dependant services - I'll tell you what - it's been a BIG win for us, it's sped up development, increased the frequency of feature deployments, made CI and testing easier, made load balancing an failover easier, reduced DR times by over 600% and the list goes on.

Don't get me wrong, it's not all roses, but it certainly makes it easier for devs and ops to do the right thing.

Maybe not the best example but: http://codesamplez.com/web-server/dockerize-an-application-from-scratch

**Comment by sammcj** [comment]
@jbrooksuk ,

I've just given @frconil from our systems engineering team @infoxchange an initial one day on sorting out Nginx and the Dockerfile for Cachet.

**Comment by jbrooksuk** [comment]
You rock! Thanks @sammcj :beers:

**Comment by frconil** [comment]
Hi,

I've done some work in https://github.com/frconil/Cachet/commit/d132eec54b2c35eb4cb906b9eb525bdad16bc7a5 

We're still in the process of testing internally (it's only a first commit) so don't be afraid if it breaks. The image builds successfully but I haven't tested what would happen when you run the newly built image.

I'm using the docker registry debian:jessie as its base, and as many system packages as possible instead of recompiling php extensions (since I couldn't use the php:56-fpm base image as it would add another container for nginx)

It only expose the nginx port on 8000 and not fpm FWIW.

**Comment by sammcj** [comment]
That's looking great @frconil ! Can't wait to see it running tomorrow :+1:

**Comment by jbrooksuk** [comment]
Nice, great work @frconil!

**Comment by frconil** [comment]
Just an update:
I have an image building, deploying etc, still trying to get Cachet going past the setup page (which returns an error 500)

At this point I'm investigating whether it's a misconfiguration in nginx or fpm, or simply a parameter I didn't set properly in the dockerfile.

**Comment by jbrooksuk** [comment]
Closed in #456.
