### ISSUE TITLE
Heroku build failing

### ISSUE THREAD

**Issue by jenolan** [cachethq/Cachet#457]
Trying to do an update to Heroku and it is failing at loading SASS... any hints?

Thanks,
Larry

```
remote:        [05:22:31] Starting 'sass'...
remote:        [05:22:31] 'sass' errored after 17 ms
remote:        [05:22:31] Error: Module did not self-register.
remote:            at Error (native)
remote:            at Module.load (module.js:355:32)
remote:            at Function.Module._load (module.js:310:12)
remote:            at Module.require (module.js:365:17)
remote:            at require (module.js:384:17)
remote:            at Object.<anonymous> (/tmp/build_81a0b6e673a5d29c7d95b8b3e8c3f8b9/node_modules/laravel-elixir/node_modules/gulp-sass/node_modules/node-sass/lib/index.js:211:15)
remote:            at Module._compile (module.js:460:26)
remote:            at Object.Module._extensions..js (module.js:478:10)
remote:            at Module.load (module.js:355:32)
remote:            at Function.Module._load (module.js:310:12)
remote:        Error running task sequence: { task: 'sass',
remote:          message: 'sass catch',
remote:          duration: 0.016768349,
remote:          hrDuration: [ 0, 16768349 ],
remote:          err: [Error: Module did not self-register.] }
remote:        [05:22:31] Finished 'default' after 26 ms
remote: 
remote:  !     Push rejected, failed to compile PHP (composer.json) app
```

**Comment by jbrooksuk** [comment]
Can you try again please, Heroku is stupid sometimes and just fails to build sporadically.

**Comment by jenolan** [comment]
Exact same error (just tried)

**Comment by brianjking** [comment]
@jbrooksuk My builds stopped compiling properly on Heroku as well.

''''code
-----> Fetching custom git buildpack... done
-----> PHP (composer.json) app detected
-----> Bundling NGINX 1.6.2
       Checksums match. Fetching from cache.
-----> Bundling PHP 5.6.4
       Checksums match. Fetching from cache.
-----> Bundling extensions
       apcu
       Checksums match. Fetching from cache.
       phpredis
       Checksums match. Fetching from cache.
-----> NODE (package.json) app detected

       TIP: Specify a node version in package.json

-----> Defaulting to latest stable node: 0.12.0
-----> Downloading and installing node

       TIP: Use npm shrinkwrap to lock down dependency versions

-----> package.json unchanged since last build
-----> Restoring node_modules from cache
/tmp/build_d7a97de3dca9324c0e1e8bd70415e306/vendor/node/bin/bower -> /tmp/build_d7a97de3dca9324c0e1e8bd70415e306/vendor/node/lib/node_modules/bower/bin/bower
bower@1.3.12 /tmp/build_d7a97de3dca9324c0e1e8bd70415e306/vendor/node/lib/node_modules/bower
????????? is-root@1.0.0
????????? junk@1.0.0
????????? stringify-object@1.0.0
????????? which@1.0.8
????????? abbrev@1.0.5
????????? chmodr@0.1.0
????????? osenv@0.1.0
????????? archy@0.0.2
????????? opn@1.0.1
????????? rimraf@2.2.8
????????? bower-logger@0.2.2
????????? lru-cache@2.5.0
????????? bower-endpoint-parser@0.2.2
????????? graceful-fs@3.0.5
????????? lockfile@1.0.0
????????? nopt@3.0.1
????????? retry@0.6.0
????????? tmp@0.0.23
????????? q@1.0.1
????????? request-progress@0.3.0 (throttleit@0.0.2)
????????? chalk@0.5.0 (escape-string-regexp@1.0.2, ansi-styles@1.1.0, supports-color@0.2.0, strip-ansi@0.3.0, has-ansi@0.1.0)
????????? shell-quote@1.4.2 (array-filter@0.0.1, array-reduce@0.0.0, array-map@0.0.0, jsonify@0.0.0)
????????? semver@2.3.2
????????? fstream@1.0.4 (inherits@2.0.1)
????????? bower-json@0.4.0 (intersect@0.0.3, deep-extend@0.2.11, graceful-fs@2.0.3)
????????? p-throttler@0.1.0 (q@0.9.7)
????????? promptly@0.2.0 (read@1.0.5)
????????? mkdirp@0.5.0 (minimist@0.0.8)
????????? bower-config@0.5.2 (osenv@0.0.3, graceful-fs@2.0.3, optimist@0.6.1)
????????? fstream-ignore@1.0.2 (inherits@2.0.1, minimatch@2.0.1)
????????? tar-fs@0.5.2 (pump@0.3.5, tar-stream@0.4.7)
????????? decompress-zip@0.0.8 (nopt@2.2.1, mkpath@0.1.0, touch@0.0.2, readable-stream@1.1.13, binary@0.3.0)
????????? glob@4.0.6 (inherits@2.0.1, once@1.3.1, minimatch@1.0.0)
????????? request@2.42.0 (caseless@0.6.0, json-stringify-safe@5.0.0, aws-sign2@0.5.0, forever-agent@0.5.2, stringstream@0.0.4, oauth-sign@0.4.0, tunnel-agent@0.4.0, qs@1.2.2, node-uuid@1.4.2, mime-types@1.0.2, bl@0.9.4, form-data@0.1.4, http-signature@0.10.1, tough-cookie@0.12.1, hawk@1.1.1)
????????? cardinal@0.4.0 (redeyed@0.4.4)
????????? update-notifier@0.2.0 (semver-diff@0.1.0, string-length@0.1.2, latest-version@0.2.0, configstore@0.3.2)
????????? bower-registry-client@0.2.3 (graceful-fs@2.0.3, request-replay@0.2.0, lru-cache@2.3.1, async@0.2.10, mkdirp@0.3.5, request@2.51.0)
????????? mout@0.9.1
????????? handlebars@2.0.0 (optimist@0.3.7, uglify-js@2.3.6)
????????? insight@0.4.3 (object-assign@1.0.0, chalk@0.5.1, async@0.9.0, lodash.debounce@2.4.1, os-name@1.0.3, tough-cookie@0.12.1, configstore@0.3.2, inquirer@0.6.0)
????????? inquirer@0.7.1 (figures@1.3.5, mute-stream@0.0.4, through@2.3.6, readline2@0.1.1, lodash@2.4.1, cli-color@0.3.2, rx@2.3.25)
/tmp/build_d7a97de3dca9324c0e1e8bd70415e306/vendor/node/bin/gulp -> /tmp/build_d7a97de3dca9324c0e1e8bd70415e306/vendor/node/lib/node_modules/gulp/bin/gulp.js
gulp@3.8.11 /tmp/build_d7a97de3dca9324c0e1e8bd70415e306/vendor/node/lib/node_modules/gulp
????????? v8flags@2.0.2
????????? pretty-hrtime@0.2.2
????????? interpret@0.3.10
????????? deprecated@0.0.1
????????? archy@1.0.0
????????? tildify@1.0.0 (user-home@1.1.1)
????????? minimist@1.1.0
????????? semver@4.3.0
????????? chalk@0.5.1 (escape-string-regexp@1.0.2, ansi-styles@1.1.0, supports-color@0.2.0, strip-ansi@0.3.0, has-ansi@0.1.0)
????????? orchestrator@0.3.7 (stream-consume@0.1.0, sequencify@0.0.7, end-of-stream@0.1.5)
????????? gulp-util@3.0.3 (object-assign@2.0.0, array-differ@1.0.0, beeper@1.0.0, array-uniq@1.0.2, replace-ext@0.0.1, lodash.reescape@3.0.1, lodash.reinterpolate@3.0.1, lodash.reevaluate@3.0.1, vinyl@0.4.6, through2@0.6.3, lodash.template@3.2.0, multipipe@0.1.2, dateformat@1.0.11)
????????? liftoff@2.0.1 (extend@1.3.0, flagged-respawn@0.3.1, resolve@1.0.0, findup-sync@0.2.1)
????????? vinyl-fs@0.3.13 (graceful-fs@3.0.5, strip-bom@1.0.0, defaults@1.0.0, vinyl@0.4.6, mkdirp@0.5.0, through2@0.6.3, glob-stream@3.1.18, glob-watcher@0.0.6)
-----> Installing dependencies
       npm WARN package.json @ No repository field.
-----> Pruning unused dependencies
       npm WARN package.json @ No repository field.
-----> Caching node_modules for future builds
-----> Cleaning up node-gyp and npm artifacts
-----> Building runtime environment
       Node  v0.12.0
-----> Vendoring Composer
-----> Bundling additional extensions mbstring
mcrypt
openssl
       mbstring
Checksums match. Fetching from cache.
       mcrypt
Checksums match. Fetching from cache.
       openssl
Checksums match. Fetching from cache.
Updating to version 833ce984264204e7d6576ab082660105c7d8f04c.
    Downloading: connection...    Downloading: 0%               Downloading: 5%    Downloading: 10%    Downloading: 15%    Downloading: 20%    Downloading: 25%    Downloading: 30%    Downloading: 35%    Downloading: 40%    Downloading: 45%    Downloading: 50%    Downloading: 55%    Downloading: 60%    Downloading: 65%    Downloading: 70%    Downloading: 75%    Downloading: 80%    Downloading: 85%    Downloading: 90%    Downloading: 95%    Downloading: 100%
Use composer self-update --rollback to return to version 28c65b5425f7f8722c260e3787b74c1ea6b37e3b
-----> Installing application dependencies with Composer
       Loading composer repositories with package information
       Installing dependencies from lock file
         - Installing segmentio/analytics-php (1.1.1)
           Loading from cache
       
         - Installing symfony/translation (v2.5.10)
           Loading from cache
       
         - Installing symfony/security-core (v2.5.10)
           Loading from cache
       
         - Installing symfony/routing (v2.5.10)
           Loading from cache
       
         - Installing symfony/process (v2.5.10)
           Loading from cache
       
         - Installing symfony/http-foundation (v2.5.10)
           Loading from cache
       
         - Installing symfony/event-dispatcher (v2.6.4)
           Loading from cache
       
         - Installing symfony/debug (v2.5.10)
           Loading from cache
       
         - Installing psr/log (1.0.0)
           Loading from cache
       
         - Installing symfony/http-kernel (v2.5.10)
           Loading from cache
       
         - Installing symfony/finder (v2.5.10)
           Loading from cache
       
         - Installing symfony/dom-crawler (v2.5.10)
           Loading from cache
       
         - Installing symfony/css-selector (v2.5.10)
           Loading from cache
       
         - Installing symfony/console (v2.5.10)
           Loading from cache
       
         - Installing symfony/browser-kit (v2.5.10)
           Loading from cache
       
         - Installing swiftmailer/swiftmailer (v5.3.1)
           Loading from cache
       
         - Installing stack/builder (v1.0.3)
           Loading from cache
       
         - Installing predis/predis (v0.8.7)
           Loading from cache
       
         - Installing phpseclib/phpseclib (0.3.10)
           Loading from cache
       
         - Installing patchwork/utf8 (v1.2.1)
           Loading from cache
       
         - Installing nesbot/carbon (1.14.0)
           Loading from cache
       
         - Installing monolog/monolog (1.12.0)
           Loading from cache
       
         - Installing nikic/php-parser (v0.9.5)
           Loading from cache
       
         - Installing jeremeamia/superclosure (1.0.2)
           Loading from cache
       
         - Installing ircmaxell/password-compat (v1.0.4)
           Loading from cache
       
         - Installing filp/whoops (1.1.3)
           Loading from cache
       
         - Installing d11wtq/boris (v1.0.8)
           Loading from cache
       
         - Installing symfony/filesystem (v2.6.4)
           Loading from cache
       
         - Installing classpreloader/classpreloader (1.0.2)
           Loading from cache
       
         - Installing laravel/framework (v4.2.17)
           Loading from cache
       
         - Installing cachethq/segment (1.0.0)
           Loading from cache
       
         - Installing league/fractal (0.11.0)
           Loading from cache
       
         - Installing dingo/api (v0.8.2)
           Loading from cache
       
         - Installing doctrine/lexer (v1.0.1)
           Loading from cache
       
         - Installing doctrine/annotations (v1.2.3)
           Loading from cache
       
         - Installing doctrine/cache (v1.4.0)
           Loading from cache
       
         - Installing doctrine/collections (v1.2)
           Loading from cache
       
         - Installing doctrine/inflector (v1.0.1)
           Loading from cache
       
         - Installing doctrine/common (v2.4.2)
           Loading from cache
       
         - Installing doctrine/dbal (v2.5.1)
           Loading from cache
       
         - Installing fideloper/proxy (2.1.1)
           Loading from cache
       
         - Installing graham-campbell/security (v2.1.3)
           Loading from cache
       
         - Installing graham-campbell/binput (v2.1.3)
           Loading from cache
       
         - Installing erusev/parsedown (1.1.4)
           Loading from cache
       
         - Installing erusev/parsedown-extra (0.2.6)
           Loading from cache
       
         - Installing graham-campbell/markdown (v2.0.7)
           Loading from cache
       
         - Installing graham-campbell/throttle (v2.0.2)
           Loading from cache
       
         - Installing react/promise (v2.2.0)
           Loading from cache
       
         - Installing guzzlehttp/streams (3.0.0)
           Loading from cache
       
         - Installing guzzlehttp/ringphp (1.0.5)
           Loading from cache
       
         - Installing guzzlehttp/guzzle (5.1.0)
           Loading from cache
       
         - Installing jenssegers/date (v2.0.15)
           Loading from cache
       
         - Installing mccool/laravel-auto-presenter (2.2.2)
           Loading from cache
       
         - Installing pragmarx/google2fa (v0.1.0)
           Loading from cache
       
         - Installing roumen/feed (v2.8.1)
           Loading from cache
       
         - Installing thujohn/rss (1.0.3)
           Loading from cache
       
         - Installing watson/validating (0.10.6)
           Loading from cache
       
       Generating optimized autoload files
       Generating optimized class loader
       Compiling common classes
       Compiling views
       Nothing to migrate.
-----> Detected Laravel app
-----> Setting up Laravel app
-----> Running compile commands
       Running 'bower install'
       bower jquery#~2.1.1         not-cached git://github.com/jquery/jquery.git#~2.1.1
       bower jquery#~2.1.1            resolve git://github.com/jquery/jquery.git#~2.1.1
       bower bootstrap-sass-official#~3.3.1       not-cached git://github.com/twbs/bootstrap-sass.git#~3.3.1
       bower bootstrap-sass-official#~3.3.1          resolve git://github.com/twbs/bootstrap-sass.git#~3.3.1
       bower animate-sass#~0.6.2                  not-cached git://github.com/tgdev/animate-sass.git#~0.6.2
       bower animate-sass#~0.6.2                     resolve git://github.com/tgdev/animate-sass.git#~0.6.2
       bower jquery-minicolors#~2.1.10            not-cached git://github.com/claviska/jquery-minicolors.git#~2.1.10
       bower jquery-minicolors#~2.1.10               resolve git://github.com/claviska/jquery-minicolors.git#~2.1.10
       bower jquery-serialize-object#~2.4.3       not-cached git://github.com/macek/jquery-serialize-object.git#~2.4.3
       bower jquery-serialize-object#~2.4.3          resolve git://github.com/macek/jquery-serialize-object.git#~2.4.3
       bower moment#~2.9                          not-cached git://github.com/moment/moment.git#~2.9
       bower moment#~2.9                             resolve git://github.com/moment/moment.git#~2.9
       bower messenger#~1.4.1                     not-cached git://github.com/HubSpot/messenger.git#~1.4.1
       bower messenger#~1.4.1                        resolve git://github.com/HubSpot/messenger.git#~1.4.1
       bower ionicons#~2.0.0                      not-cached git://github.com/driftyco/ionicons.git#~2.0.0
       bower ionicons#~2.0.0                         resolve git://github.com/driftyco/ionicons.git#~2.0.0
       bower humane-js#~3.2.2                     not-cached git://github.com/wavded/humane-js.git#~3.2.2
       bower humane-js#~3.2.2                        resolve git://github.com/wavded/humane-js.git#~3.2.2
       bower lodash#~2.4                          not-cached git://github.com/lodash/lodash.git#~2.4
       bower lodash#~2.4                             resolve git://github.com/lodash/lodash.git#~2.4
       bower Sortable#~1.0.0                      not-cached git://github.com/RubaXa/Sortable.git#~1.0.0
       bower Sortable#~1.0.0                         resolve git://github.com/RubaXa/Sortable.git#~1.0.0
       bower livestampjs#~1.1.2                   not-cached git://github.com/mattbradley/livestampjs.git#~1.1.2
       bower livestampjs#~1.1.2                      resolve git://github.com/mattbradley/livestampjs.git#~1.1.2
       bower jquery-minicolors#~2.1.10              download https://github.com/claviska/jquery-minicolors/archive/2.1.10.tar.gz
       bower bootstrap-sass-official#~3.3.1         download https://github.com/twbs/bootstrap-sass/archive/v3.3.3.tar.gz
       bower jquery#~2.1.1                          download https://github.com/jquery/jquery/archive/2.1.3.tar.gz
       bower ionicons#~2.0.0                        download https://github.com/driftyco/ionicons/archive/v2.0.1.tar.gz
       bower messenger#~1.4.1                       download https://github.com/HubSpot/messenger/archive/v1.4.1.tar.gz
       bower moment#~2.9                            download https://github.com/moment/moment/archive/2.9.0.tar.gz
       bower jquery-serialize-object#~2.4.3         download https://github.com/macek/jquery-serialize-object/archive/2.4.5.tar.gz
       bower animate-sass#~0.6.2                    download https://github.com/tgdev/animate-sass/archive/v0.6.3.tar.gz
       bower lodash#~2.4                            download https://github.com/lodash/lodash/archive/2.4.1.tar.gz
       bower humane-js#~3.2.2                       download https://github.com/wavded/humane-js/archive/3.2.2.tar.gz
       bower livestampjs#~1.1.2                     download https://github.com/mattbradley/livestampjs/archive/1.1.2.tar.gz
       bower Sortable#~1.0.0                        download https://github.com/RubaXa/Sortable/archive/1.0.1.tar.gz
       bower livestampjs#~1.1.2                      extract archive.tar.gz
       bower animate-sass#~0.6.2                     extract archive.tar.gz
       bower humane-js#~3.2.2                        extract archive.tar.gz
bower livestampjs#~1.1.2                 invalid-meta livestampjs is missing "main" entry in bower.json
bower livestampjs#~1.1.2                 invalid-meta livestampjs is missing "ignore" entry in bower.json
       bower jquery-serialize-object#~2.4.3          extract archive.tar.gz
       bower Sortable#~1.0.0                         extract archive.tar.gz
       bower livestampjs#~1.1.2                     resolved git://github.com/mattbradley/livestampjs.git#1.1.2
bower humane-js#~3.2.2                   invalid-meta humane-js is missing "ignore" entry in bower.json
       bower humane-js#~3.2.2                       resolved git://github.com/wavded/humane-js.git#3.2.2
       bower jquery-serialize-object#~2.4.3         resolved git://github.com/macek/jquery-serialize-object.git#2.4.5
       bower jquery#>=1.2                         not-cached git://github.com/jquery/jquery.git#>=1.2
       bower jquery#>=1.2                            resolve git://github.com/jquery/jquery.git#>=1.2
       bower jquery#>=1.2                           download https://github.com/jquery/jquery/archive/2.1.3.tar.gz
       bower moment#~2.9                             extract archive.tar.gz
       bower jquery-minicolors#~2.1.10               extract archive.tar.gz
       bower bootstrap-sass-official#~3.3.1          extract archive.tar.gz
       bower messenger#~1.4.1                        extract archive.tar.gz
       bower jquery-minicolors#~2.1.10              resolved git://github.com/claviska/jquery-minicolors.git#2.1.10
       bower lodash#~2.4                             extract archive.tar.gz
       bower Sortable#~1.0.0                        resolved git://github.com/RubaXa/Sortable.git#1.0.1
       bower jquery#~2.1.1                           extract archive.tar.gz
       bower jquery#>=1.2                            extract archive.tar.gz
       bower animate-sass#~0.6.2                    resolved git://github.com/tgdev/animate-sass.git#0.6.3
       bower lodash#~2.4                            resolved git://github.com/lodash/lodash.git#2.4.1
       bower ionicons#~2.0.0                         extract archive.tar.gz
       bower messenger#~1.4.1                       resolved git://github.com/HubSpot/messenger.git#1.4.1
       bower jquery#*                             not-cached git://github.com/jquery/jquery.git#*
       bower jquery#*                                resolve git://github.com/jquery/jquery.git#*
       bower jquery#*                               download https://github.com/jquery/jquery/archive/2.1.3.tar.gz
       bower bootstrap-sass-official#~3.3.1         resolved git://github.com/twbs/bootstrap-sass.git#3.3.3
       bower jquery#>= 1.9.0                      not-cached git://github.com/jquery/jquery.git#>= 1.9.0
       bower jquery#>= 1.9.0                         resolve git://github.com/jquery/jquery.git#>= 1.9.0
       bower jquery#>= 1.9.0                        download https://github.com/jquery/jquery/archive/2.1.3.tar.gz
       bower jquery#>=1.2                           resolved git://github.com/jquery/jquery.git#2.1.3
       bower moment#~2.9                            resolved git://github.com/moment/moment.git#2.9.0
       bower jquery#*                                extract archive.tar.gz
       bower jquery#>= 1.9.0                         extract archive.tar.gz
       bower jquery#~2.1.1                          resolved git://github.com/jquery/jquery.git#2.1.3
       bower jquery#*                               resolved git://github.com/jquery/jquery.git#2.1.3
       bower jquery#>= 1.9.0                        resolved git://github.com/jquery/jquery.git#2.1.3
bower ionicons#~2.0.0                        mismatch Version declared in the json (2.0.0) is different than the resolved one (2.0.1)
       bower ionicons#~2.0.0                        resolved git://github.com/driftyco/ionicons.git#2.0.1
bower jquery                         extra-resolution Unnecessary resolution: jquery#~2.1.1
       bower livestampjs#~1.1.2                      install livestampjs#1.1.2
       bower humane-js#~3.2.2                        install humane-js#3.2.2
       bower jquery-serialize-object#~2.4.3          install jquery-serialize-object#2.4.5
       bower jquery-minicolors#~2.1.10               install jquery-minicolors#2.1.10
       bower Sortable#~1.0.0                         install Sortable#1.0.1
       bower animate-sass#~0.6.2                     install animate-sass#0.6.3
       bower lodash#~2.4                             install lodash#2.4.1
       bower messenger#~1.4.1                        install messenger#1.4.1
       bower bootstrap-sass-official#~3.3.1          install bootstrap-sass-official#3.3.3
       bower jquery#>=1.2                            install jquery#2.1.3
       bower moment#~2.9                             install moment#2.9.0
       bower ionicons#~2.0.0                         install ionicons#2.0.1
       
       livestampjs#1.1.2 app/assets/bower_components/livestampjs
       
       humane-js#3.2.2 app/assets/bower_components/humane-js
       
       jquery-serialize-object#2.4.5 app/assets/bower_components/jquery-serialize-object
       ????????? jquery#2.1.3
       
       jquery-minicolors#2.1.10 app/assets/bower_components/jquery-minicolors
       
       Sortable#1.0.1 app/assets/bower_components/Sortable
       
       animate-sass#0.6.3 app/assets/bower_components/animate-sass
       
       lodash#2.4.1 app/assets/bower_components/lodash
       
       messenger#1.4.1 app/assets/bower_components/messenger
       ????????? jquery#2.1.3
       
       bootstrap-sass-official#3.3.3 app/assets/bower_components/bootstrap-sass-official
       ????????? jquery#2.1.3
       
       jquery#2.1.3 app/assets/bower_components/jquery
       
       moment#2.9.0 app/assets/bower_components/moment
       
       ionicons#2.0.1 app/assets/bower_components/ionicons
       Running 'gulp'
       [12:50:25] Warning: gulp version mismatch:
       [12:50:25] Global gulp is 3.8.11
       [12:50:25] Local gulp is 3.8.10
       [12:50:25] Using gulpfile /tmp/build_d7a97de3dca9324c0e1e8bd70415e306/gulpfile.js
       [12:50:25] Starting 'default'...
       [12:50:26] Finished 'default' after 684 ms
       [12:50:26] Starting 'default'...
       [12:50:26] Starting 'sass'...
       [12:50:26] 'sass' errored after 14 ms
       [12:50:26] Error: Module did not self-register.
           at Error (native)
           at Module.load (module.js:355:32)
           at Function.Module._load (module.js:310:12)
           at Module.require (module.js:365:17)
           at require (module.js:384:17)
           at Object.<anonymous> (/tmp/build_d7a97de3dca9324c0e1e8bd70415e306/node_modules/laravel-elixir/node_modules/gulp-sass/node_modules/node-sass/lib/index.js:211:15)
           at Module._compile (module.js:460:26)
           at Object.Module._extensions..js (module.js:478:10)
           at Module.load (module.js:355:32)
           at Function.Module._load (module.js:310:12)
       Error running task sequence: { task: 'sass',
         message: 'sass catch',
         duration: 0.014480655,
         hrDuration: [ 0, 14480655 ],
         err: [Error: Module did not self-register.] }
       [12:50:26] Finished 'default' after 22 ms

 !     Push rejected, failed to compile PHP (composer.json) app

**Comment by jbrooksuk** [comment]
I hate Heroku.

**Comment by jbrooksuk** [comment]
Well it builds now:

![image](https://cloud.githubusercontent.com/assets/246103/6283487/2aa62b8c-b8dd-11e4-9aa6-33b11bfdfcf8.png)

But the `rev-manifest.json` file didn't get written - https://cachet-dev.herokuapp.com/setup

**Comment by jbrooksuk** [comment]
It builds locally just fine.

**Comment by jbrooksuk** [comment]
I think this is being caused by the bower asset for `bootstrap-sass-official` no longer existing... Just deploying a test.

**Comment by jbrooksuk** [comment]
Nope, even after fixing the bootstrap code, nadda.

**Comment by jbrooksuk** [comment]
It's working again! :)

**Comment by wfjsw** [comment]
@jbrooksuk same problem, latest version of the code, doing update.
```
remote:        Running 'gulp'
remote:        [13:37:49] Warning: gulp version mismatch:
remote:        [13:37:49] Global gulp is 3.8.11
remote:        [13:37:49] Local gulp is 3.8.10
remote:        [13:37:50] Using gulpfile /tmp/build_44d73de7b8cc0f59ff8909a1f89977d9/gulpfile.js
remote:        [13:37:50] Starting 'default'...
remote:        [13:37:50] Finished 'default' after 714 ms
remote:        [13:37:50] Starting 'default'...
remote:        [13:37:50] Starting 'sass'...
remote:        [13:37:50] 'sass' errored after 18 ms
remote:        [13:37:50] Error: Module did not self-register.
remote:            at Error (native)
remote:            at Module.load (module.js:355:32)
remote:            at Function.Module._load (module.js:310:12)
remote:            at Module.require (module.js:365:17)
remote:            at require (module.js:384:17)
remote:            at Object.<anonymous> (/tmp/build_44d73de7b8cc0f59ff8909a1f89977d9/node_modules/laravel-elixir/node_m
odules/gulp-sass/node_modules/node-sass/lib/index.js:211:15)
remote:            at Module._compile (module.js:460:26)
remote:            at Object.Module._extensions..js (module.js:478:10)
remote:            at Module.load (module.js:355:32)
remote:            at Function.Module._load (module.js:310:12)
remote:        Error running task sequence: { task: 'sass',
remote:          message: 'sass catch',
remote:          duration: 0.017983414,
remote:          hrDuration: [ 0, 17983414 ],
remote:          err: [Error: Module did not self-register.] }
remote:        [13:37:50] Finished 'default' after 26 ms
remote:
remote:  !     Push rejected, failed to compile PHP (composer.json) app
remote:
```

**Comment by jbrooksuk** [comment]
We no longer use gulp for installation. Can you pull the latest version and try again please?

**Comment by wfjsw** [comment]
well i pulled just a minute ago.

**Comment by wfjsw** [comment]
oops forgive me i merged a wrong branch.

**Comment by jbrooksuk** [comment]
Is it working now for you @wfjsw?

**Comment by wfjsw** [comment]
@jbrooksuk nope. 503 is presented and no logs can be acquired. (heroku sucks......)

**Comment by wfjsw** [comment]
```
2015-02-28T14:30:23.977803+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/favicon.ico" hos
t=nyancat-status-59178.herokuapp.com request_id=e7297c78-05c1-4304-99eb-1b23c8096905 fwd="106.187.34.17" dyno= connect=
service= status=503 bytes=
2015-02-28T14:36:29.757865+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/" host=nyancat-s
tatus-59178.herokuapp.com request_id=1c59818a-834e-408e-81ab-7e1cfd353455 fwd="106.187.34.17" dyno= connect= service= st
atus=503 bytes=
2015-02-28T14:36:35.801764+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/favicon.ico" hos
t=nyancat-status-59178.herokuapp.com request_id=c930c853-f21a-4212-bd71-2ad3fadc8842 fwd="106.187.34.17" dyno= connect=
service= status=503 bytes=
2015-02-28T15:03:56.748388+00:00 heroku[web.1]: State changed from crashed to starting
2015-02-28T15:04:05.853184+00:00 heroku[web.1]: Starting process with command `vendor/bin/heroku-php-nginx -C nginx.conf
 public`
2015-02-28T15:04:06.825475+00:00 app[web.1]: vendor/bin/heroku-php-nginx: line 7: /app/run: No such file or directory
2015-02-28T15:04:07.511927+00:00 heroku[web.1]: Process exited with status 127
2015-02-28T15:04:07.524900+00:00 heroku[web.1]: State changed from starting to crashed
2015-02-28T15:52:17.736912+00:00 heroku[web.1]: State changed from crashed to starting
2015-02-28T15:52:26.855905+00:00 heroku[web.1]: Starting process with command `vendor/bin/heroku-php-nginx -C nginx.conf
 public`
2015-02-28T15:52:28.154806+00:00 app[web.1]: vendor/bin/heroku-php-nginx: line 7: /app/run: No such file or directory
2015-02-28T15:52:28.800690+00:00 heroku[web.1]: Process exited with status 127
2015-02-28T15:52:28.822206+00:00 heroku[web.1]: State changed from starting to crashed
2015-02-28T16:12:38.432185+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/" host=status.ny
anyanya.moe request_id=e7588bda-e562-4a18-ba37-b49e7d434121 fwd="119.188.14.59" dyno= connect= service= status=503 bytes
=
2015-02-28T17:18:23.266034+00:00 heroku[web.1]: State changed from crashed to starting
2015-02-28T17:18:50.219051+00:00 heroku[web.1]: Starting process with command `vendor/bin/heroku-p
hp-nginx -C nginx.conf public`
2015-02-28T17:18:52.370110+00:00 app[web.1]: vendor/bin/heroku-php-nginx: line 7: /app/run: No such file or directory
2015-02-28T17:18:53.227472+00:00 heroku[web.1]: Process exited with status 127
2015-02-28T17:18:53.235549+00:00 heroku[web.1]: State changed from starting to crashed
2015-02-28T20:10:21.766810+00:00 heroku[web.1]: State changed from crashed to starting
2015-02-28T20:10:33.979928+00:00 heroku[web.1]: Starting process with command `vendor/bin/heroku-php-nginx -C nginx.conf
 public`
2015-02-28T20:10:35.937276+00:00 app[web.1]: vendor/bin/heroku-php-nginx: line 7: /app/run: No such file or directory
2015-02-28T20:10:36.771456+00:00 heroku[web.1]: Process exited with status 127
2015-02-28T20:10:36.775816+00:00 heroku[web.1]: State changed from starting to crashed
2015-03-01T00:17:19.064506+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/dashboard" host=
nyancat-status-59178.herokuapp.com request_id=1771a1f7-2e0d-4c82-b1c1-75d6cc84423d fwd="27.192.241.133" dyno= connect= s
ervice= status=503 bytes=
2015-03-01T00:17:21.141225+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/favicon.ico" hos
t=nyancat-status-59178.herokuapp.com request_id=f14bc9b4-38f0-4899-9eb6-91327f93c6d9 fwd="27.192.241.133" dyno= connect=
 service= status=503 bytes=
```
What a mess..

**Comment by jbrooksuk** [comment]
Ah... Can you tell me what the `BUILDPACK_URL` environment variable is?

**Comment by wfjsw** [comment]
Here you are
https://github.com/cachethq/cachet-buildpack

**Comment by jbrooksuk** [comment]
Right, you need to change that to `https://github.com/heroku/heroku-buildpack-php` and deploy again :)

**Comment by wfjsw** [comment]
I am out now. will deploy in a moment.

**Comment by wfjsw** [comment]
ok now :)
