### ISSUE TITLE
Setup Github -> Docker Hub automation

### ISSUE THREAD

**Issue by sammcj** [cachethq/Cachet#459]
This will mean people can simply run `docker pull cachethq/cachet` without needing to check out the git repo and build the docker image etc....

It looks really easy to setup too - you pretty much just bind your Github repo to your Docker account:

1) Setup a cachethq account on the Docker hub (you can signup with Github) - https://hub.docker.com/account/signup/
2) Visit - https://registry.hub.docker.com/builds/add/
3) Add the build trigger and githook
4) Profit!

The docs and screenshots are available here, but it should be pretty self-explanatory: http://docs.docker.com/docker-hub/builds/

Note: I'd do it myself, but you need to be a member of cachethq so someone internal will need to.
Note 2: I'd consider this low priority and just a 'nice to have'.

**Comment by jbrooksuk** [comment]
I have indeed set this up.

**Comment by jbrooksuk** [comment]
https://registry.hub.docker.com/u/cachethq/cachet/
