### ISSUE TITLE
API errors -  Not null violation in column "description"

### ISSUE THREAD

**Issue by georgehansper** [cachethq/Cachet#461]
The /api/components interface does not seem to be working.

The command:

curl -u 'test@test.com:test123' -H "Content-Type: application/json" -d '{"name":"API 2","status":1}' -H 'User-Agent: Mozilla/5.0 (but really curl)' https://status.cachethq.io/api/components -v -o /dev/null

Fails as follows:
HTTP/1.1 500 Internal Server Error

SQLSTATE[23502]: Not null violation: 7 ERROR: null value in column "description" violates not-null constraint DETAIL: Failing row contains (15, API 2, null, null, 1, 0, 0, 1, 2015-02-19 22:58:40, 2015-02-19 22:58:40, null). (SQL: insert into "components" ("order", "group_id", "name", "status", "user_id", "updated_at", "created_at") values (0, 0, API 2, 1, 1, 2015-02-19 22:58:40, 2015-02-19 22:58:40) returning "id”)

I've tried adding a "description" but it then complains about the column "link"

**Comment by jbrooksuk** [comment]
I think I've fixed this but I've since broken deployment to Heroku, are you able to test locally?

**Comment by georgehansper** [comment]
I've tried to install Cachet on a Debian wheezy system, but it fails at the 'bower install' step
The error message is 
bower bootstrap-sass-official#~3.3.1 ECMDERR Failed to execute "git ls-remote --tags...
fatal: unable to connect to github.com

I'm not sure what it's trying to do here or why, but things like 'git pull' work.

In short, not I can't test locally (yet)

**Comment by jbrooksuk** [comment]
Try now - it seems to be working for me :)
