### ISSUE TITLE
Include compiled assets in repo, drop building with Node

### ISSUE THREAD

**Issue by jbrooksuk** [cachethq/Cachet#463]
We've had **a lot** of reoccurring issues with Heroku deployment due to not including the compiled assets within the repo.

This should give us the following benefits:

- Hopefully be able to drop the custom buildpack.
- Reduce the size of the deployed application on Heroku.
- Removes the need for people installing Cachet to have Node, Bower, Gulp etc installed.

**Comment by joecohens** [comment]
:+1:

**Comment by GrahamCampbell** [comment]
:+1:

**Comment by GrahamCampbell** [comment]
This only works if there's not much going on, otherwise we've going to have a crap load of merge conflicts again.

**Comment by jbrooksuk** [comment]
I said to @joecohens that we can probably do this for V1 - or start now as there is less changes happening.

**Comment by jbrooksuk** [comment]
@sammcj @frconil would you guys be able to help with the Docker changes that would be required by this?

**Comment by frconil** [comment]
Sure, I'll submit a PR when you move to prebuilt assets.

On 21 Feb 2015, at 08:57, James Brooks <notifications@github.com<mailto:notifications@github.com>> wrote:


@sammcj<https://github.com/sammcj> @frconil<https://github.com/frconil> would you guys be able to help with the Docker changes that would be required by this?

-

**Comment by jbrooksuk** [comment]
Thanks!

I hope you're not annoyed, since you've just done it, but after all the hassle I've had with asset compilation today, it's not worth it - only for development.

**Comment by frconil** [comment]
It's ok, I was complaining about npm timing out all the time while building the docket image.

I will have a look at it first thing Monday.

On 21 Feb 2015, at 10:30, James Brooks <notifications@github.com<mailto:notifications@github.com>> wrote:


Thanks!

I hope you're not annoyed, since you've just done it, but after all the hassle I've had with asset compilation today, it's not worth it - only for development.

-

**Comment by sammcj** [comment]
I'm so glad this is happening, so sick of all the NPM and Composer building, especially when I get rate-limited by Github :angry:

**Comment by jbrooksuk** [comment]
Composer will still need to run, but NPM and Bower won't :)
