### ISSUE TITLE
Javascript Errors

### ISSUE THREAD

**Issue by Duffleman** [cachethq/Cachet#466]
`Uncaught TypeError: undefined is not a function - all-23bbb8a2.js:29286`

Line that is referenced:
`$('[data-toggle="tooltip"]').tooltip();`

That will break the installer script, stops you pressing the "Next" button.

If I remove that, the next line that errors:

`$btn.button('loading');`
From line `29391` of `all.js`

After that, no errors present themselves.

**Comment by jbrooksuk** [comment]
This should no longer be an issue for you, if you use the latest version as all of the assets are compiled with the distribution :smile:

**Comment by Duffleman** [comment]
This is no longer an issue for me, the precompiled assets work perfectly.
