### ISSUE TITLE
API - Cannot update a component status - always creates a new component

### ISSUE THREAD

**Issue by georgehansper** [cachethq/Cachet#468]
When using the `/api/components` API, it is not possible to update the status of an existing component.

Instead, a new component with the same name is created every time.

This occurs for both of the following JSON payloads:

```
{"status":"2","name":"test2"}
```

```
{"status":"2","name":"test2","id":2}
```

**Comment by jbrooksuk** [comment]
Can you confirm which version of Cacht you're using?

**Comment by jbrooksuk** [comment]
Sorry, I misread your issue. This is in the list for #359.

**Comment by jbrooksuk** [comment]
Could you try now please?

**Comment by georgehansper** [comment]
Posted data to https://status.cachethq.io/api/components
{"status":"2","name":"Website","id":3}

New result:
{"data":[{"id":1,"name":"API","description":"Used by third-parties to connect to us","status_id":1,"status":"Operational","incident_count":0,"created_at":1424680368,"updated_at":1424680368},{"id":2,"name":"Payments","description":"Backed by Stripe","status_id":1,"status":"Operational","incident_count":0,"created_at":1424680368,"updated_at":1424680368},{"id":3,"name":"Website","description":"","status_id":1,"status":"Operational","incident_count":0,"created_at":1424680368,"updated_at":1424680368},{"id":4,"name":"Website","description":"","status_id":2,"status":"Performance Issues","incident_count":0,"created_at":1424686692,"updated_at":1424686692}]}

ie a new component with id=4 was created, with the name 'Website' and the status 2 'Performance Issues'

I'm happy to send you the perl script I'm using, or add it in to the project somewhere.

**Comment by jbrooksuk** [comment]
@joecohens as part of #359

**Comment by joecohens** [comment]
Roger :)

**Comment by jbrooksuk** [comment]
@georgehansper sorry for the delay in this. You are sending the request as a `PUT` method, right?

**Comment by jbrooksuk** [comment]
I've just tested with a `PUT` method and the component updated just fine :)

**Comment by jbrooksuk** [comment]
If you can confirm, I'll close this issue.

**Comment by jbrooksuk** [comment]
I'm going to close this @georgehansper if it's still a problem for you, please re-open and we'll take another look :+1:

**Comment by georgehansper** [comment]
Actually, I'm using the POST method as per the API described in:
https://docs.cachethq.io/v1.0/docs/components-api

There is no mention of a PUT method for updating components.

Can you please post a sample of the working code?

When I change the method to 'PUT' in Perl LWP, I get the following error message:

{"message":"405 Method Not Allowed","status_code":405}

The response headers include:
Server: cloudflare-nginx
Allow: GET, HEAD, POST

Are we using the same API ?

**Comment by jbrooksuk** [comment]
I really need to sort out the documentation :/

**Comment by tomer-h** [comment]
Commenting as I am also encountering this issue and want to stay updated. Adding my experience below:

The following creates a new component with status 2:

curl -X POST -H "Content-Type: application/json" -H "X-Cachet-Token: SECRET" http://myurl.com/api/components -d '{"status":"2","name":"Homepage","id":"1"}'

The following receives a 405 Method Not Allowed response:

curl -X PUT -H "Content-Type: application/json" -H "X-Cachet-Token: SECRET" http://myurl.com/api/components -d '{"status":"2","name":"Homepage","id":"1"}'

Changing the payload to remove the name attribute has no effect. 

Would appreciate an example of what this should look like in order be able to update from API. I get the same 405 response on any update attempt (metrics too).

**Comment by jbrooksuk** [comment]
When you're updating a component you need to use this endpoint:

```
PUT https://demo.cachethq.io/api/components/:component_id
```

**Comment by tomer-h** [comment]
Hi, thank you for the quick response, I got it working!

For anyone else who might get stuck and reach this thread the following command is what worked:

curl -X PUT -H "Content-Type: application/json" -H "X-Cachet-Token: SECRET" http://myurl.com/api/components/1 -d '{"status":"2","id":"1"}'

**Comment by jbrooksuk** [comment]
Thanks @tomer-h I'm working on the documentation now too; http://docs.cachethq.io

**Comment by jbrooksuk** [comment]
@tomer-h just noticed that you don't need to send through the `id` key/value pair anymore.

**Comment by georgehansper** [comment]
When sending data to a webserver, normally there are 2 approaches:

* PUT - all the data is in the URL
* POST - all the data is in the body

(this is actually a requirement for the application to be 'restful'. See http://en.wikipedia.org/wiki/Representational_state_transfer)

If the Cachet API is accepting data in the body of the HTTP request, POST is a more appropriate method than PUT.

PUT should look something like:
http://myurl.com/api/components/1?status=2
or
http://myurl.com/api/components?status=2&id=1

and have no data in the body. The header can still contain 'X-Cachet-Token: SECRET'

**Comment by jbrooksuk** [comment]
In our API we're using `POST` to create and `PUT` to update. http://cachet.readme.io/v1.0/docs/post-parameters

**Comment by jbrooksuk** [comment]
The usual docs link is far too cached again...

**Comment by sammcj** [comment]
@jbrooksuk I think Cloudflare is denying PUT requests on the 'try it out' page: http://cachet.readme.io/v1.0/docs/update-a-component

```
server: cloudflare-nginx
date: Mon, 16 Mar 2015 03:40:00 GMT
content-type: application/json
transfer-encoding: chunked
connection: close
set-cookie: __cfduid=dddf66179e6b0f971ba4b8ca8af959e321426477200; expires=Tue, 15-Mar-16 03:40:00 GMT; path=/; domain=.cachethq.io; HttpOnly,cachet_session=eyJpdiI6IjU4a01QdjM3ajF3OGJXeGFEOEdwTUE9PSIsInZhbHVlIjoia09HXC9jOWRaK0dXcGdXYlNTVXoxU2RnaEYxVWhHRmhLQmxneitqNXFHYU9hYUREek5yNXZON3VWMGM1Y1IyYnNpeDNMWVYyUlBcL09TdU9LdFcyVzRiQT09IiwibWFjIjoiNjEyMGE1ZmZmNTllYWMxNWM5NjIzZjBjNjYyMjMwY2JhODA2NjA1ZGQ3ZjhiZTAzNmMzNjk3NDFmN2Y0NTQzMyJ9; expires=Mon, 16-Mar-2015 13:40:00 GMT; Max-Age=36000; path=/; httponly
x-powered-by: PHP/5.6.6
cache-control: no-cache
via: 1.1 vegur
cf-ray: 1c7d6f23cb860f21-IAD
```

**Comment by jbrooksuk** [comment]
Urgh, CloudFlare.

Could you try and add a `_method=PUT` parameter please?

**Comment by sammcj** [comment]
I don't think you should be running Cloudflare on the API though - I can't see any value in doing so anyway - Cloudflare is meant to cache static content and help protect against malicious traffic to websites. It's not really designed to MITM an API. Why not just have the API access directly but the websites cached behind Cloudflare?

**Comment by jbrooksuk** [comment]
I could turn off CloudFlare for some routes I guess.

**Comment by sammcj** [comment]
It might be wise to have the API on a domain prefix, I.e. api.demo.cachethq.com and not have that on Cloudflare.

**Comment by jbrooksuk** [comment]
Perhaps in the future we'll allow the API to run from a subdomain.

Could you try with a `PUT` request now please?

**Comment by sammcj** [comment]
No difference:

```
server: cloudflare-nginx
date: Mon, 16 Mar 2015 08:22:59 GMT
content-type: application/json
transfer-encoding: chunked
connection: close
set-cookie: __cfduid=dea8ad9763962860a9b8f8502953884ad1426494179; expires=Tue, 15-Mar-16 08:22:59 GMT; path=/; domain=.cachethq.io; HttpOnly,cachet_session=eyJpdiI6ImJGTGxKbTNQcm84Q0g0U2pPT0ROYlE9PSIsInZhbHVlIjoiS2cwdzQ5dFpUN2k1d001TkxJSVZOMEZsQWZsQ2w0UWpGMldUaDY4Njd1S1ZuU1BjbGE0cTFPSjlLOVFXOVF4Vk52Z3VNc3F0T2ZRSHdSTzVkM3BzUEE9PSIsIm1hYyI6IjI5ZGUyNTA4MzFjY2JkMjdmZDQ3NDFjYjQyNWM0ZWIwMjFmNWJiMzg2ZGQzMjQ2YjJiZmU0ZTliYzFjMjQyNDIifQ%3D%3D; expires=Mon, 16-Mar-2015 18:22:59 GMT; Max-Age=36000; path=/; httponly
x-powered-by: PHP/5.6.6
cache-control: no-cache
via: 1.1 vegur
cf-ray: 1c7f0dad45dd0f03-IAD
```
I don't know this system at all but is `domain=.cachethq.io` correct? I thought it was demo.cachethq.io ?

**Comment by jbrooksuk** [comment]
It's a CNAME under `cachethq.io`.

**Comment by jbrooksuk** [comment]
Might be taking a little bit to update.

**Comment by sammcj** [comment]
OK - if you need a hand with cloudflare I'm happy to login and take a look

**Comment by jbrooksuk** [comment]
That may be a good idea @sammcj I'll email you the deets.

**Comment by sammcj** [comment]
ok cool, can't promise anything but I won't break anything else.
