### ISSUE TITLE
Metrics don't work on Heroku

### ISSUE THREAD

**Issue by jbrooksuk** [cachethq/Cachet#473]
```
SQLSTATE[42601]: Syntax error: 7 ERROR: syntax error at or near "0" LINE 1: ...%Y%c%e%H") = DATE_FORMAT(DATE_SUB(NOW(), INTERVAL 0 HOUR), "... ^ (SQL: select sum("value") as aggregate from "metric_points" where "metric_points"."metric_id" = 1 and DATE_FORMAT(created_at, "%Y%c%e%H") = DATE_FORMAT(DATE_SUB(NOW(), INTERVAL 0 HOUR), "%Y%c%e%H") and HOUR(created_at) = HOUR(DATE_SUB(NOW(), INTERVAL 0 HOUR)) group by HOUR(created_at)) (View: /app/app/views/partials/graphs.blade.php) (View: /app/app/views/partials/graphs.blade.php)
```

Well that's a massive pain.

**Comment by jbrooksuk** [comment]
This is probably some stupid PgSQL query error.

**Comment by sammcj** [comment]
I know you usually use MySQL for your projects but have you considered moving to PostgreSQL?

After years of working with databases of varying flavours I can honestly say that MySQL is a mess. Through its sloppy transaction handling and consistency problems the default these days is quickly becoming PostgreSQL.

I could go on for hours, and I'm certainly not suggesting this as a blocker for 1.0 but it might be worth considering moving forward.

Worth reading: http://grimoire.ca/mysql/choose-something-else

**Comment by sammcj** [comment]
Are you able to provide me with the SQL that's being run? (I'm assuming Heroku can log transactions somewhere?)

**Comment by jbrooksuk** [comment]
Yes and no, the problem is that I'm using Eloquent to build the query. https://github.com/cachethq/Cachet/blob/master/src/Models/Metric.php#L73-89

I'm going to read that article later on :smile:

**Comment by sammcj** [comment]
Yeah and sorry I don't want to sound like a troll - but MySQL has bitten so many people I think that's half the reason new databases are popping up every week!

Anyway, if you can get me that query I should be able to spot any syntactical errors.

**Comment by jbrooksuk** [comment]
Definitely not trolling, I appreciate any ways that I can improve both Cachet and myself :smile: 

I'll have to pull it out later I think, is that ok?

**Comment by sammcj** [comment]
Sure - it's 8PM here in Melbourne so I'll probably reply first thing in the morning.

**Comment by jbrooksuk** [comment]
Yeah, no problem :)

**Comment by michaelw90** [comment]
Pretty sure PostgreSQL doesn't have a `date_sub()` method. Looking at latest master, seems fixed?

**Comment by jbrooksuk** [comment]
I pushed live (to Heroku) and it doesn't work still, must be a syntax error.

**Comment by michaelw90** [comment]
Do you have an updated error report for it on Heroku?

**Comment by jbrooksuk** [comment]
Not to hand I'm afraid.

**Comment by sammcj** [comment]
^ Ping ^ - query please!

**Comment by jbrooksuk** [comment]
You need the PgSQL one right?

**Comment by sammcj** [comment]
Yes if that's the one throwing the error.
It's 12.15 here and I've got to be up at 5.45AM for a network change so
I'll look at it after that.

-- 
Sam McLeod
@s_mcleod[https://twitter.com/s_mcleod]

**Comment by jbrooksuk** [comment]
```
select * from "metric_points" where "metric_points"."metric_id" = ? and to_char(created_at, "YYYYMMDDHH") = 2015022513 and DATE_PART("hour", created_at) = DATE_PART("hour", NOW() - INTERVAL "0 hour") group by DATE_PART("hour", created_at)
```

**Comment by jbrooksuk** [comment]
I think I know what it is actually.

**Comment by jbrooksuk** [comment]
Nope. But I've fixed half of it.

**Comment by jbrooksuk** [comment]
Done in 33f1948adde4eb561773b3c546d7cb7826c133a7. Can someone check that the query is efficient?

**Comment by szechyjs** [comment]
Not sure if it is working, I've added about 100 points to a metric and the status page chart shows nothing but 0s.

**Comment by jbrooksuk** [comment]
Are you able to see the tables?

**Comment by szechyjs** [comment]
Sorry, it appears it is working and I just misunderstood how the metrics work. It seems that the metric values are summed each hour and then plotted. I was anticipating each point to be plotted. The metrics I was planning on adding do not make sense to be aggregated like this, i.e. page load time, number of database connections, etc.

**Comment by jbrooksuk** [comment]
:+1: 

Although metrics are finished in V1, we're going to be rewriting them from scratch in V2. This will mean we can:

- Specify both X and Y minimum values.
- Decide on aggregation of data, sum, count, average, mode, median etc.

It'll be a huge rewrite in V2.
