### ISSUE TITLE
Unable to update a metric

### ISSUE THREAD

**Issue by oovoo** [cachethq/Cachet#477]
Guys i am trying to update metric using following command:

curl -k -XPOST 'https://localhost/api/metrics/points' -d '{"_token":"blablabla", "id":1, "value":1}'

Any ideas why it doesn't work?

it says 

[2015-02-26 17:31:26] local.ERROR: exception 'CachetHQ\Cachet\Repositories\InvalidModelValidationException' with message 'Validation failed on the model.' in /var/www/html/Cachet/src/Repositories/EloquentRepository.php:151
Stack trace:
#0 /var/www/html/Cachet/src/Repositories/MetricPoint/EloquentMetricPointRepository.php(40): CachetHQ\Cachet\Repositories\EloquentRepository->validate(Object(CachetHQ\Cachet\Models\MetricPoint))
#1 /var/www/html/Cachet/src/Http/Controllers/Api/MetricPointController.php(61): CachetHQ\Cachet\Repositories\MetricPoint\EloquentMetricPointRepository->create(Array)
#2 [internal function]: CachetHQ\Cachet\Http\Controllers\Api\MetricPointController->postMetricPoints()
#3 /var/www/html/Cachet/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(231): call_user_func_array(Array, Array)
#4 /var/www/html/Cachet/bootstrap/compiled.php(5843): Illuminate\Routing\Controller->callAction('postMetricPoint...', Array)
#5 /var/www/html/Cachet/bootstrap/compiled.php(5831): Illuminate\Routing\ControllerDispatcher->call(Object(CachetHQ\Cachet\Http\Controllers\Api\MetricPointController), Object(Dingo\Api\Routing\Route), 'postMetricPoint...')
#6 /var/www/html/Cachet/bootstrap/compiled.php(5036): Illuminate\Routing\ControllerDispatcher->dispatch(Object(Dingo\Api\Routing\Route), Object(Illuminate\Http\Request), 'CachetHQ\\Cachet...', 'postMetricPoint...')
#7 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}()
#8 /var/www/html/Cachet/bootstrap/compiled.php(5394): call_user_func_array(Object(Closure), Array)
#9 /var/www/html/Cachet/bootstrap/compiled.php(5061): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request))
#10 /var/www/html/Cachet/bootstrap/compiled.php(5049): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
#11 /var/www/html/Cachet/vendor/dingo/api/src/Routing/Router.php(231): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#12 /var/www/html/Cachet/bootstrap/compiled.php(715): Dingo\Api\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#13 /var/www/html/Cachet/bootstrap/compiled.php(696): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#14 /var/www/html/Cachet/bootstrap/compiled.php(7821): Illuminate\Foundation\Application->handle(Object(Illuminate\Http\Request), 1, true)
#15 /var/www/html/Cachet/bootstrap/compiled.php(8428): Illuminate\Session\Middleware->handle(Object(Illuminate\Http\Request), 1, true)
#16 /var/www/html/Cachet/bootstrap/compiled.php(8375): Illuminate\Cookie\Queue->handle(Object(Illuminate\Http\Request), 1, true)
#17 /var/www/html/Cachet/bootstrap/compiled.php(11038): Illuminate\Cookie\Guard->handle(Object(Illuminate\Http\Request), 1, true)
#18 /var/www/html/Cachet/bootstrap/compiled.php(657): Stack\StackedHttpKernel->handle(Object(Illuminate\Http\Request))
#19 /var/www/html/Cachet/public/index.php(48): Illuminate\Foundation\Application->run()

**Comment by joecohens** [comment]
We are not accepting json input atm on the API can you try like this? `curl -H "X-Cachet-Token: YOURTOKEN" -X POST -d 'id=1&value=1' http://cachet.app:8000/api/metrics/points`

**Comment by dcoeurjo** [comment]
@joecohens, with your example, I'm getting an ```wWhoops, looks like something went wrong.```web page 

(command: ```curl -H "X-Cachet-Token: MYSECRET" -X POST -d 'id=1&value=1' 'http://MYHEROKUDEPLOYEDAPP/api/metrics/points'```)

**Comment by oovoo** [comment]
It looks much better but graph still didn't present the values which i am pushing 


curl -k -H "X-Cachet-Token: pnUxF5qERmmKhoOJV5wv" -X POST -d 'metric_id=1&value=100' https://localhost/api/metrics/points
{"metric_point":{"metric_id":"1","value":"100","updated_at":"2015-02-27 12:20:57","created_at":"2015-02-27 12:20:57","id":8}}

curl -k -H "X-Cachet-Token: pnUxF5qERmmKhoOJV5wv" -X POST -d 'id=1&value=100' https://localhost/api/metrics/points
{"metric_point":{"value":"100","updated_at":"2015-02-27 12:30:44","created_at":"2015-02-27 12:30:44","id":15}}

**Comment by oovoo** [comment]
If i perform like this:

curl -k -H "X-Cachet-Token: pnUxF5qERmmKhoOJV5wv" -X POST -d 'metric_id=1&value=100' https://localhost/api/metrics/points
{"metric_point":{"metric_id":"1","value":"100","updated_at":"2015-02-27 12:20:57","created_at":"2015-02-27 12:20:57","id":8}}

then it looks like right:

mysql> select * FROM cachet.metrics;
+----+------+----------------------------+----------------------------+---------------+---------------+---------------------+---------------------+
| id | name | suffix                     | description                | default_value | display_chart | created_at          | updated_at          |
+----+------+----------------------------+----------------------------+---------------+---------------+---------------------+---------------------+
|  1 | SDK: | SDK: API SDK RESPONSE TIME | SDK: API SDK RESPONSE TIME |             0 |             1 | 2015-02-26 12:41:57 | 2015-02-27 12:19:35 |
+----+------+----------------------------+----------------------------+---------------+---------------+---------------------+---------------------+
1 row in set (0.00 sec)

mysql> select * FROM cachet.metric_points;
+----+-----------+-------+---------------------+---------------------+
| id | metric_id | value | created_at          | updated_at          |
+----+-----------+-------+---------------------+---------------------+
|  1 |         1 |   100 | 2015-02-27 12:38:35 | 2015-02-27 12:38:35 |
+----+-----------+-------+---------------------+---------------------+
1 row in set (0.00 sec)

but graph still doesn't present the data

**Comment by oovoo** [comment]
I just figure out  why metrics weren't presenting properly on the graph so i found two issues (BTW my time zone is Asia/Jerusalem)

1. Because %c presents month without 0, so right choose as following ( %m	Month, numeric (00-12) inside actual query)

2. You should present average and not sum for one hour since sum it is pointless 

so i changed from 

this src/Models/Metric.php):
$value = (int) $this->points()->whereRaw('DATE_FORMAT(created_at, "%Y%c%e%H") = '.$dateTime->format('YmdH'))->whereRaw('HOUR(created_at) = HOUR(DATE_SUB(NOW(), INTERVAL '.$hour.' HOUR))')->groupBy(DB::raw('HOUR(created_at)'))->sum('value');


to this (src/Models/Metric.php):

$value = (int) $this->points()->whereRaw('DATE_FORMAT(created_at, "%Y%m%e%H") = '.$dateTime->format('YmdH'))->whereRaw('HOUR(created_at) = HOUR(DATE_SUB(NOW(), INTERVAL '.$hour.' HOUR))')->groupBy(DB::raw('HOUR(created_at)'))->avg('value');

Please advise, let me know if u want i'll submit my code.

**Comment by jbrooksuk** [comment]
Please submit a PR and I'll check it out @oovoo :)

**Comment by oovoo** [comment]
and %e replace to %d

**Comment by oovoo** [comment]
ok i will submit

**Comment by jbrooksuk** [comment]
@oovoo any news on this? :)

**Comment by oovoo** [comment]
we will provide an answer, it looks like it about your default date formatting. 

details are coming soon.

**Comment by jbrooksuk** [comment]
Ah... Sorry, updating a metric point?

**Comment by jbrooksuk** [comment]
Right, this is done now - get it from `master`.

```
PUT /api/metrics/:metric_id/points/:metric_point_id
```

Then just send through the same information and the metric point will be updated.

**Comment by oovoo** [comment]
Guys i am so sorry we just can't get to this

**Comment by jbrooksuk** [comment]
@oovoo are you still having the same issue?

**Comment by oovoo** [comment]
i didn't have a chance to check it i hope tommorow
