### ISSUE TITLE
An option to hide the 'Nothing to report' days must be added

### ISSUE THREAD

**Issue by MichaelBanks** [cachethq/Cachet#486]

**Comment by maanas** [comment]
+1

**Comment by anarcat** [comment]
+1

**Comment by jeremypruitt** [comment]
+1

**Comment by jbrooksuk** [comment]
I'll briefly explain the reasoning behind the current design and why I'm not sure if this will work.

The current design shows empty days as reinforcement that the service is performing well. If you see a list of components and no incidents you'll be thinking "oh yeah, this service is solid" whereas if we show just a list of incidents labelled with random dates, the status page could look broken itself.

What would you, as a customer, rather see? A list of empty days, with an incident or two dotted around or would you prefer to see a list of incidents?

**Comment by jbrooksuk** [comment]
With that said, if there is a genuine need (which there seems to be) to hide all empty dates, we'll add this in for V2 - but I'm only inclined to do so if people understand why it could be a bad idea?

**Comment by anarcat** [comment]
as a user, i don't want shiny things. i want the truth. and a list of empty dates doesn't tell me that. a calendar might, but having an easily accessible list of outages is more useful to me than a supposedly impressive list of non-failures. :)

**Comment by jbrooksuk** [comment]
I'd say that a list of empty dates shows that there are no incidents on those days, maybe we add a toggle?

**Comment by anarcat** [comment]
yeah, adding a toggle (even client-side) would fix this for me. "tools not policy"...

**Comment by jeremypruitt** [comment]
Toggle would be perfect as both are useful for different reasons.

**Comment by maanas** [comment]
How about showing a just a graphical bar with Green blocks  (containing date) indicating every thing is well. 
We can represent the period where there has been no incident in just one line indicating all is well for that period

**Comment by jbrooksuk** [comment]
@maanas could you make a mockup?

**Comment by anarcat** [comment]
a few ideas here: 

* [github](https://status.github.com/messages) - one per day min (custom)
* [disqus](https://status.disqus.com/history) - one entry per month min ([statuspages.io](http://www.statuspage.io/))
* [amazon](http://status.aws.amazon.com/) - grid, one cell per day min (custom?)
* [gandi](https://status.gandi.net/) - graph, one node per day min (custom?)
* [wikipedia](http://status.wikimedia.org/) - like amazon, more or less ([nimsoft's public status pages](http://www.nimsoft.com/feature/public-status-page.html))

i like discus' way, for example. if you have one incident per day, you have a problem. plus having per day entries makes it really hard to go back further in time. if we want to have empty entries, i would suggest making those months at most.

**Comment by jbrooksuk** [comment]
Thanks for the ideas @anarcat. Disqus looks good to me, but we'd have to enable grouping incidents by day, week and month (year would be too excessive).

**Comment by maanas** [comment]
https://jsfiddle.net/33x2m9jq/1/

This is a close approximation indicating the days when all is ok. We can show all the days where there is no incidence.

**Comment by jbrooksuk** [comment]
But what if there are multiple incidents, some of which aren't resolved on a component? Now you can't have a block as one colour, it needs to be two or more.

**Comment by maanas** [comment]
For the day we have incidence the current schema of vertical bar looks great. The day we do not have incidence we can have a horizontal like with dates in the circle with green.

**Comment by jbrooksuk** [comment]
Are you suggesting that we mix both the timeline view and your idea?

**Comment by maanas** [comment]
Not a mix but two distinct views.
A) For incidence the current one, with vertical time line which appears like escalation
B) A horizontal one for all the dates where there is no incidence.
That way we will have all dates appearing in horizontal line without any incidence in green. And when we have incidence it is shown as vertical line till it resolves. And the next day we again go back to horizontal line.

**Comment by jbrooksuk** [comment]
Hmm I think that's a little confusing. You'd have to cross reference the views to see what day didn't have an incident. 

To be honest, I'm all for having different layouts in V2 anyway. So you'll be able to pick how it's laid out.

**Comment by jbrooksuk** [comment]
I've played with this and I really don't like it much, at least not right now. If you start hiding empty days, then the pagination doesn't work as it should because you can't simply add/subtract days if there are days missing.

We may implement this in the future if we change the timeline view, but it's not something we'll be adding as a setting.

**Comment by anarcat** [comment]
"well that sucks."

**Comment by jbrooksuk** [comment]
I *may* introduce this in the future, depending on what happens with V2. It's not out forever.

**Comment by jeremypruitt** [comment]
+1

**Comment by aliasfalse** [comment]
soooo, never happened?

**Comment by jbrooksuk** [comment]
It didn't but the new design we're working on actually does this anyway.

**Comment by aliasfalse** [comment]
Excellent, thank you!

**Comment by jbrooksuk** [comment]
:)

**Comment by omtr** [comment]
+1

**Comment by omtr** [comment]
:)

**Comment by GLundh** [comment]
Perhaps we can just mark these days with a special css class, to make is easy to hide them using custom css?

**Comment by jbrooksuk** [comment]
@GLundh feel free to submit a PR :)
