### ISSUE TITLE
Wont work in Azure

### ISSUE THREAD

**Issue by ashii007** [cachethq/Cachet#487]
I tried to install the software on windows azure. AFter all said and done, install.php is not working. Here is the error.

[01-Mar-2015 16:19:11 America/Los_Angeles] PHP Warning:  PHP Startup: Unable to load dynamic library 'C:\DWASFiles\Sites\rhcs-cachet\VirtualDirectory0\site\wwwroot\bin\php_apc.dll' - The specified module could not be found.
 in Unknown on line 0
[02-Mar-2015 00:19:13 UTC] PHP Fatal error:  Call to undefined function Illuminate\Cache\apc_fetch() in D:\home\site\wwwroot\vendor\laravel\framework\src\Illuminate\Cache\ApcWrapper.php on line 30

I did validate that APC module was loaded. phpinfo() shows following messsage:

PHP_EXTENSIONS	bin\php_apc.dll
APPSETTING_PHP_EXTENSIONS	bin\php_apc.dll
WEBSITE_SITE_NAME	rhcs-cachet
APPSETTING_WEBSITE_SITE_NAME	rhcs-cachet

Has anyone successfully installed this software on Microsoft Azure.

**Comment by jbrooksuk** [comment]
We've never actually tested Cachet on Azure, with that said, it'd be awesome to support it. It seems to be that Azure hasn't setup the APC driver properly here. I don't know much about it, but we require APC for caching.

**Comment by jbrooksuk** [comment]
@ashii007 have you had any luck with this?

**Comment by vincent** [comment]
Hi. We also use use Azure here.. 
The OP didn't specified so I guess he also uses Azure Websites. On these, only Wincache is available.
Maybe you could use a cache abstraction lib ?

Cheers

**Comment by jbrooksuk** [comment]
Hey @vincent, thanks for your reply.

What I may do is allow switching of the cache driver by an environment variable.

**Comment by jbrooksuk** [comment]
@vincent and @ashii007 if you use the latest version you'll be able to set an environment variable of `CACHE_DRIVER` instead of Cachet using `apc`. Thanks :)
