### ISSUE TITLE
SQL error on using sqlite db driver.

### ISSUE THREAD

**Issue by bimlendu** [cachethq/Cachet#488]
sqlite does not have `NOW()` method as used in  https://github.com/cachethq/Cachet/blob/master/src/Models/Incident.php . So on using sqlite as db driver cachet fails with this error.

```
Next exception 'Illuminate\Database\QueryException' with message 'SQLSTATE[HY000]: General error: 1 no such function: NOW (SQL: select * from "incidents" where "incidents"."deleted_at" is null and "status" = 0 and scheduled_at >= NOW() order by "scheduled_at" asc)' in /usr/share/nginx/html/cachethq/vendor/laravel/framework/src/Illuminate/Database/Connection.php:625
```

Full stack trace here: http://pastebin.com/PZVp67qy

`NOW()` depends on the database that we use, instead using `date("Y-m-s H:i:s", time())` in place of `NOW()`, resolves the issue and should work with all dbs.

Thanks.

**Comment by jbrooksuk** [comment]
Would you mind making a Pull Request?

**Comment by jbrooksuk** [comment]
Fixed.
