### ISSUE TITLE
installation of snipe-it issue

### ISSUE THREAD

**Issue by umerafridi** [cachethq/Cachet#489]
Dear All,
migrating of database error please help me 
php artisan migrate
entering this command following error prompt

  [Illuminate\Database\QueryException]
  SQLSTATE[42S02]: Base table or view not found: 1146 Table 'snipeit.assets'
  doesn't exist (SQL: truncate `assets`)

  [PDOException]
  SQLSTATE[42S02]: Base table or view not found: 1146 Table 'snipeit.assets'
  doesn't exist

**Comment by jbrooksuk** [comment]
This is not a Cachet issue, please open an issue on the [Snipe-It project](https://github.com/snipe/snipe-it).
