### ISSUE TITLE
Incident Templates, templating system

### ISSUE THREAD

**Issue by jbrooksuk** [cachethq/Cachet#490]
I'm imagining that incident templates could make use of a templating system, by use of variables. For example, imagine this template text:

```
We've experienced an incident at $TIMESTAMP on the $COMPONENT side of the system.
```

Which could be translated to:

```
We've experienced an incident at 20:10 on the API side of the system.
```

Just by sending the variables to the API. This would make it much easier to integrate with the incident API.

**Comment by lnxslck** [comment]
@jbrooksuk was this implemented? I tried $COMPONENT on 2.3.9 and it didn't work

**Comment by jbrooksuk** [comment]
Yes, but we don't document them very well to be honest.

**Comment by lnxslck** [comment]
I can help you with that if you want. Just point me in the right direction

**Comment by ConnorVG** [comment]
:point_left:
