### ISSUE TITLE
"Whoops, looks like something went wrong." on home page

### ISSUE THREAD

**Issue by mkody** [cachethq/Cachet#491]
Hello,

Tried to deploy from the Heroku button but the front-end is showing a *"Whoops, looks like something went wrong."*. 
But looks like that others' Cachet websites are showing the same, like at http://cachet.herokuapp.com/ or http://monitor.dockdogs.com/ (found when searching a bit about this issue here).

Is it just me or is there something broken at the moment?

Thanks for any future help!

**Comment by jbrooksuk** [comment]
Interesting! I'll take a look.

**Comment by jbrooksuk** [comment]
Fixed in 6bbdd864e744942379648fa508c359e0448b530f - sorry about that.
