### ISSUE TITLE
Explain metrics screen?

### ISSUE THREAD

**Issue by brianjking** [cachethq/Cachet#492]
While it's not a bug I'm not sure I understand what the metrics screen setup can do. I don't see it presently used at your demo at https://demo.cachethq.io. Do you have this shown as a sample setup anywhere?

Thanks!

**Comment by jbrooksuk** [comment]
Example metrics:

![image](https://cloud.githubusercontent.com/assets/246103/6462960/cce4a2b8-c1a5-11e4-949a-917b9bf459d8.png)

They can only be accessed via the API (although there is a default value option if you want to specify). I'm going to be working on the docs in the evenings.

**Comment by brianjking** [comment]
Gotcha, that's what I figured. I currently have http://health.dockdogs.com using UptimeRobot in addition to a Cachet installation deployed on Heroku. 

So I can theoretically use the metrics API in Cachet with the UptimeRobot.com service to merge everything into one, correct?

https://uptimerobot.com/api

Thanks!

**Comment by jbrooksuk** [comment]
Exactly @brianjking the API can be setup to add incidents for you or change a component status :)

**Comment by jbrooksuk** [comment]
The documentation will be updated to properly explain metrics etc.

**Comment by ApfelUser** [comment]
@jbrooksuk Is it now possible to display a chart connected to UptimeRobot? And if yes, how do I do that? There seems to be no explanation in the docs.

**Comment by jbrooksuk** [comment]
@ApfelUser it's not something we have functionality built in for - as in there isn't a "Connect to UptimeRobot" button. If the docs are being funny, can you try using http://cachet.readme.io please. It'll have more information.
