### ISSUE TITLE
API Tokens

### ISSUE THREAD

**Issue by jbrooksuk** [CachetHQ/Cachet#496]
Currently API tokens are generated per-user. This approach is fine, but there may times when someone wants to use the API via a different token so that they can easily manage individual connections.

**Comment by insom** [comment]
Hi @jbrooksuk - I've started working on this, hope to have a PR over to you in the next few days. I just wanted to make sure I'm not stepping on anyone's toes with it.

**Comment by jbrooksuk** [comment]
:+1: I look forward to seeing it @insom! Thanks buddy :)

**Comment by jbrooksuk** [comment]
@insom did you get any further with this? :)

**Comment by insom** [comment]
@jbrooksuk [I did a few commits](https://github.com/insom/Cachet/commits/master), but I've stalled. At this point, I've got some other things coming up, it's probably best to open this back up to other contributors, sorry.

**Comment by jbrooksuk** [comment]
That's a shame :) Open a PR if you'd like with `[WIP]` I'm sure someone will add to it.

**Comment by jbrooksuk** [comment]
Closing this as it'll be part of https://github.com/CachetHQ/Cachet/issues/2086
