### ISSUE TITLE
Schedule component not working

### ISSUE THREAD

**Issue by bbcorp** [cachethq/Cachet#503]
Hey there,
I did recently test Cachet and I have an issue for comitting a schedule maintenance.
When I click on scheduled maintenance it shows "Error in exception handler."
PHP message is : "PHP Parse error:  syntax error, unexpected '$scheduledAt' (T_VARIABLE) in /var/www/Cachet/src/Http/Controllers/DashScheduleController.php on line 162"
I looked at this line but It don't see the point.

Thanks in advance

**Comment by jbrooksuk** [comment]
Whoops! All fixed, thanks!

**Comment by bbcorp** [comment]
Nice, that was quick.
Keep it up, I'll support you as I can ;)

**Comment by jbrooksuk** [comment]
Thanks! :)
