### ISSUE TITLE
d11wtq/boris, ext-readline and TokenMismatchException error [Debian 7]

### ISSUE THREAD

**Issue by ApfelUser** [cachethq/Cachet#505]
Hello,

I am trying to install Cachet on Debian 7:

```
composer install --no-dev -o
```

I am getting this error then:

```
Warning: The lock file is not up to date with the latest changes in composer.json. You may be getting outdated dependencies. Run update to update them.
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for d11wtq/boris v1.0.9 -> satisfiable by d11wtq/boris[v1.0.9].
    - d11wtq/boris v1.0.9 requires ext-readline * -> the requested PHP extension readline is missing from your system.
  Problem 2
    - d11wtq/boris v1.0.9 requires ext-readline * -> the requested PHP extension readline is missing from your system.
    - laravel/framework v4.2.17 requires d11wtq/boris ~1.0 -> satisfiable by d11wtq/boris[v1.0.9].
    - Installation request for laravel/framework v4.2.17 -> satisfiable by laravel/framework[v4.2.17].
```

I can solve this by using:

```
composer update
```

But then I am getting **this**:

![Error](https://cloud.githubusercontent.com/assets/7549136/6482214/151b485c-c264-11e4-930c-deac95a0b765.png)

Some facts:

* Debian 7 x64
* PHP5
* php5-readline **is installed**, I know - it said it is missing, but it definitely is installed
* I use the default **APC** (`'driver' => 'apc'`) as session driver

Anyone know how to fix this?

Help would be very appreciated.

**Comment by GrahamCampbell** [comment]
> php5-readline is installed, I know - it said it is missing, but it definitely is installed

That maybe so, but you can't have enabled it correctly.

**Comment by GrahamCampbell** [comment]
You know there is a dirty hack you can use if you want to force the install even if php version requirements and extentions aren't met by the system. Run the composer install with the `--ignore-platform-reqs` flag.

**Comment by ApfelUser** [comment]
@GrahamCampbell Same **TokenMismatchException** if I use `--ignore-platform-reqs`

**Comment by GrahamCampbell** [comment]
What if you use a different session driver?

**Comment by ApfelUser** [comment]
Could you explain me how I can configure Redis for that?

**Comment by ApfelUser** [comment]
@GrahamCampbell because I don't find any settings/explanation for that. I can change `'driver' => 'apc'` to `'driver' => 'redis'`. But how do I configure the **host**, **password** and **database name**?

**Comment by jbrooksuk** [comment]
Try using `file` driver for now?

**Comment by jbrooksuk** [comment]
Any luck?

**Comment by ApfelUser** [comment]
@jbrooksuk :+1: Oh, I am really sorry. It didn't send my reply somehow. Yeah, it works with the `file` driver right now, thanks! Should I close this now, or is this still some bug in your eyes?

**Comment by jbrooksuk** [comment]
I think it's an environment issue personally.
