### ISSUE TITLE
SSL broken on https://docs.cachethq.io/

### ISSUE THREAD

**Issue by sammcj** [cachethq/Cachet#509]
The website looks *great* but SSL is borked on https://docs.cachethq.io

![ssl](https://cloud.githubusercontent.com/assets/862951/6617764/3930476c-c910-11e4-8529-25d1ec0b194b.png)

**Comment by jbrooksuk** [comment]
Ah yes, I've turned it off because CloudFlare is caching it too heavily and none of my updates were being shown.

**Comment by sammcj** [comment]
Ah just turn SSL on but set cloud flare to dev mode.
Also you can use their api to flush cache upon deploys.

-- 
Sam McLeod
@s_mcleod[https://twitter.com/s_mcleod]

**Comment by jbrooksuk** [comment]
Thanks, I've done that now. https://docs.cachethq.io/

We use Readme.io so there are no deploys to act upon.
