### ISSUE TITLE
Add new metric point

### ISSUE THREAD

**Issue by szechyjs** [cachethq/Cachet#511]
How do you add a new metric point through the API? The endpoint does not seem to be documented. And from looking at the source code the `POST /api/metrics/{id}/points` endpoint doesn't seem to be working as all I get is `{"status_code":400,"message":"Bad Request"}` responses.

**Comment by sammcj** [comment]
@georgehansper might know or want to know this too

**Comment by jbrooksuk** [comment]
What data are you sending through? Are you sending the `X-Cachet-Token` header too?

**Comment by jbrooksuk** [comment]
I've been adding points via the API just yesterday, it's weird that it's broken.

**Comment by szechyjs** [comment]
I figured it out, it was a combination of 2 things. I was missing the content-type header on my request, and the values have to be an integer. I was trying to push a decimal value.

Can we add support for decimal values?

**Comment by jbrooksuk** [comment]
Hmm, yeah, it should definitely allow for decimals. Would you like to make a PR?

**Comment by jbrooksuk** [comment]
@szechyjs can you check out @joecohens change please? You'll have to re-run the migrations though I'm afraid (the joys of using beta software).
