### ISSUE TITLE
Metric points not displayed on graph

### ISSUE THREAD

**Issue by matejkramny** [cachethq/Cachet#515]
I'm writing a [third party plugin](https://github.com/CastawayLabs/cachet-monitor) that hits a url and `POST`s the lag to cachet as a metric point (every second).

I found that the points get created in the mysql database, but are never displayed on the actual graph.

I started logging the metric points to cachet's demo, you can get the metrics via `https://demo.cachethq.io/api/metrics/1/points` (you need to use Postman or curl, setting the api token).

Any ideas what could be wrong?

**Comment by jbrooksuk** [comment]
Are you testing this solely on the demo instance or do you have your own version?

**Comment by matejkramny** [comment]
I installed a local version and that doesn't work either.I tailored it for the demo so it is easier to test.Matej KramnyOn Mon, Mar 16, 2015 at 9:36 am,  James Brooks <notifications@github.com> wrote:            Are you testing this solely on the demo instance or do you have your own version?

**Comment by jbrooksuk** [comment]
You need to [setup a metric](https://demo.cachethq.io/dashboard/metrics) to actually send data to. Remember that the demo resets every half hour.

**Comment by matejkramny** [comment]
James, i did create a metric, and the api call returned 200 with json representation of the metric point.

The points were also present in the database.

Please reopen?

**Comment by matejkramny** [comment]
I am not near my laptop, so writing from my phone.

Steps to reproduce:

1. Log into cachet demo
2. Create a metric, note the id
3. Go to settings and enable graphs to be shown on the homepage
4. Start Postman app (available in chrome app store)
5. Set url to POST to https://demo.cachethq.io/api/metrics/1/points
6. Add the required header for authentication
7. Click the Raw tab, enter {"value":100} and then send
8. Make a get with the same url to confirm it has been created
9. See cachet uptime dashboard (root url). The graph is there but no data.

**Comment by joecohens** [comment]
@matejkramny Is the raw tab sending the request data has JSON? If it is you should set the `Content-Type: application/json` header if not you need to send it like form values ex. `value=10`.

**Comment by matejkramny** [comment]
I am on my laptop so i'll try & verify.

**Comment by matejkramny** [comment]
It will if you select JSON from the dropdown (its by the `...| raw | binary` tabs).

What i get back from `/api/metrics/2/points`:

```
{
  "metric_points": [
    {
      "id": "2482",
      "metric_id": "2",
      "value": "320.000",
      "created_at": "2015-03-16 19:38:44",
      "updated_at": "2015-03-16 19:38:44"
    }
  ]
}
```

The status page:

![screen shot 2015-03-16 at 20 41 21](https://cloud.githubusercontent.com/assets/797608/6674867/e825dfde-cc1c-11e4-8e7b-a7814dbcef87.png)

**Comment by matejkramny** [comment]
That `window.onload` setter will also cause the first graph to be blank (as seen on the screenshot)

**Comment by joecohens** [comment]
Thanks for the info, we will investigate it.

**Comment by jbrooksuk** [comment]
So the data is being logged now?

**Comment by matejkramny** [comment]
The data was always logged in the database (correctly). The issue is that it isn't displayed on the graphs.

**Comment by jbrooksuk** [comment]
All fixed in `master`.

**Comment by matejkramny** [comment]
Seems to be back :/.

![screen shot 2015-03-18 at 00 35 42](https://cloud.githubusercontent.com/assets/797608/6699915/ef1ea830-cd06-11e4-926a-2540ed673fc5.png)
