### ISSUE TITLE
Metrics adding up instead of averaging

### ISSUE THREAD

**Issue by craftbyte** [cachethq/Cachet#517]
I am trying to set up so that metrics are pushed every second to the server (ping). The server is just adding them up instead of averaging them out.

![Image of graph area](https://i.imgur.com/afoYtyT.png)
![Image of points](https://i.imgur.com/lbLquAk.png)

**Comment by jbrooksuk** [comment]
This is a tough one. Some metrics would need to be a sum, whilst others average etc.

**Comment by craftbyte** [comment]
Perhaps make that an option at the settings?

**Comment by jbrooksuk** [comment]
If you'd like to submit a PR for this I'd happily accept it :)
