### ISSUE TITLE
Incident form incorrect

### ISSUE THREAD

**Issue by matejkramny** [cachethq/Cachet#521]
The edit incident form displays the component modifier radios when no component is selected.

![screen shot 2015-03-17 at 19 03 09](https://cloud.githubusercontent.com/assets/797608/6694191/c1e147e8-ccd8-11e4-8350-c443ee4a5b49.png)

*Steps to reproduce:*

1. Create an incident, do not set the Component
2. Edit the created incident
3. Form shows a set of radios below the Component input box when no component is selected. After selecting a component, the form disappears

*Expected behaviour:*

Same as adding the incident, the set of radio buttons should only appear when a component is selected

**Comment by jbrooksuk** [comment]
Strange, it's working locally. What browser are you using?

![efd0xb7siv](https://cloud.githubusercontent.com/assets/246103/6695680/f4628892-ccda-11e4-9776-da51252b422e.gif)

**Comment by jbrooksuk** [comment]
Oh sorry, it's on edit.

**Comment by jbrooksuk** [comment]
Actually, even when I go to edit the component, it's not set.

**Comment by jbrooksuk** [comment]
Can you try out the [demo](https://demo.cachethq.io)?

**Comment by matejkramny** [comment]
Hmm works fine from mobile safari. Used chrome mac when testingMatej KramnyOn Tue, Mar 17, 2015 at 8:24 pm,  James Brooks <notifications@github.com> wrote:            Can you try out the demo?

**Comment by jbrooksuk** [comment]
Can you try again on Chrome for Mac, as that's what I use.

**Comment by matejkramny** [comment]
Strange, doesn't happen on demo but happens on my local copy, even after updating the docker image.

**Comment by jbrooksuk** [comment]
@matejkramny what version of Chrome are you using? Does it happen in Safari?
