### ISSUE TITLE
show link to dashboard even when not logged in

### ISSUE THREAD

**Issue by anarcat** [cachethq/Cachet#526]
it took me a while to find the link to the dashboard in the demo. in fact, i had to be told how to login on twitter.

considering this provides zero security (assuming that was the idea) because an attacker could easily find information and makes the product much harder to use for regular users, it seems to me the link should just be always present.

**Comment by jbrooksuk** [comment]
This is a fair point.

**Comment by anarcat** [comment]
thanks!
