### ISSUE TITLE
Server Monitoring app

### ISSUE THREAD

**Issue by matejkramny** [cachethq/Cachet#527]
I've decided to write a [server app](https://github.com/CastawayLabs/cachet-monitor) (for fun) that integrates Cachet's API.

It is now at a stage where 'it works' and creates an incident if a monitor goes offline. It then resolves the incident should the monitor go back up.. There are more features such as ping logging however that seems broken at the moment.

- Would you think its a good idea to list the addon in readme?
- Can you share some guidance that matches your vision for cachet?
- Your thoughts on third party plugins. I can't find any at the moment

The issues created in the project are goals for v1 (irrelevant of cachet's version).

**Comment by jbrooksuk** [comment]
This is awesome! Good work @matejkramny.

- I could absolutely add a link to the readme. If you'd like to make a PR I'd be happy to add it.
- What would you like to know?
- We don't have many plugins at the moment, but I'd love to see what people do with the API.

**Comment by matejkramny** [comment]
Thanks @jbrooksuk

- What is the long term goal of cachet?

**Comment by jbrooksuk** [comment]
@matejkramny this is a good question. We're going to continue working towards making **the best** status page system out there. Once V1 has shipped we'll be in a better position to lay out our goals and what to expect from V2.

Is that ok?

**Comment by matejkramny** [comment]
Thats good, thanks.

**Comment by apogre** [comment]
+1

**Comment by jbrooksuk** [comment]
@apogre what's the +1 in relation to?

**Comment by apogre** [comment]
@jbrooksuk I am trying to integrate cachet api to moniter my servers and I found this interesting.
