### ISSUE TITLE
Error in RSS/Atom feed when setting app_locale to de

### ISSUE THREAD

**Issue by maltorfer** [cachethq/Cachet#528]
I'm getting an Undefined offset error in src/Models/Incident.php line 118 when setting the default language to 'de'. Perhaps some translation strings missing?

**Comment by jbrooksuk** [comment]
Translations should fall back to `en` if they're missing. I'll take a look.

**Comment by jbrooksuk** [comment]
Fixed :)

**Comment by maltorfer** [comment]
you're fast ..
