### ISSUE TITLE
Failed to install on Ubuntu 14.04, PHP 5.5.9

### ISSUE THREAD

**Issue by jrthib** [cachethq/Cachet#533]
I'm having a lot of issues getting this installed. My server has php-apcu and all of the requirements. Database driver is MySQL.

Steps I have performed are as follows: 
1) `composer install --no-dev -o` (success)
2) `php artisan migrate` (success)
3) created `.env.production.php` and `.env.php` with identical information.
4) `bower install && npm install && gulp` (success)
5) Navigate to `http://<my-domain-name>/setup` and receive the error "Whoops, looks like something went wrong."

My php error logs show no errors as well. Previously I was getting an error saying `apc_fetch()` was an undefined function, so I installed APCu since APC doesn't work with PHP 5.5+ and that solved it. Now I'm just getting nothing.

Any ideas?

**Comment by GrahamCampbell** [comment]
Make sure your file permissions are correct, and check your php level logs.

**Comment by jrthib** [comment]
My file permissions seem to be ok. Files are owned by the correct user. Files are set to 644, directories set to 755. Could you elaborate more on the php level logs?

**Comment by ApfelUser** [comment]
Can you open:

```
app/config/app.php
```

and switch `'debug' => getenv('APP_DEBUG')` from **false** to **true**?

It should look like:

```
'debug' => getenv('APP_DEBUG') ?: true,
```

you'll get better error messages then

**Comment by jbrooksuk** [comment]
You shouldn't need to build any assets, so the whole `bower install && npm install && gulp` line was unnecessary.

Can you run `chmod 755 app/storage` please.

**Comment by jrthib** [comment]
Wow, what an incredible debug screen. It said it couldn't find the PDO driver. Turns out I needed to set the environment variables in my php5-fpm pool.d config. Does the `.env.php` file ever get used? Whenever I would change values there, it doesn't seem to affect anything. Maybe I'm doing it wrong?

**Comment by jbrooksuk** [comment]
It's [whoops!](http://filp.github.io/whoops/) which is what Laravel 4 uses by default - it's pretty epic.

Yes, the `.env.php` file gets used if you're in production mode. You may want to create a `.env.local.php` file instead?

**Comment by jrthib** [comment]
I agree, that is pretty great! Maybe I'm not setting production mode correctly. From my understanding you just set a ENV=production in the PHP environment variables?

**Comment by ApfelUser** [comment]
@jrthib You also should **turn off** the debug screen if it works now, as it displays data like the MySQL password etc.

**Comment by jrthib** [comment]
@ApfelUser I did, thanks for reminding me.
