### ISSUE TITLE
"Error in exception handler" on HEAD

### ISSUE THREAD

**Issue by anarcat** [cachethq/Cachet#534]
i tried to do an upgrade here and after doing a `git pull` (which updated from [39f2bc1] to [1b60d00]) and a `php artisan migrate` (which did nothing), the frontpage of the site is totally broken. I only see this in plaintext (without any HTML tags):

```
Error in exception handler.
```

**Comment by GrahamCampbell** [comment]
https://github.com/cachethq/Cachet/compare/39f2bc1021140e1607cece7295a4b1b2542c47d8...1b60d00bba564444de89fb3ba79d85113f997f2a

**Comment by jbrooksuk** [comment]
Can you set `APP_DEBUG` to `1` in your environment variables please?

**Comment by anarcat** [comment]
hmm... reverting the changes in git didn't fix the problem, so maybe there's something else going on here, sorry for the noise.

**Comment by anarcat** [comment]
the problem was that i had the wrong permissions on the source code (to do the deployment, i chown'd everything to my user). doing `chown -R www-data /var/www/Cachet` fixed the problem, but it seems sub-optimal - what are the proper permissions anyways?

**Comment by jbrooksuk** [comment]
You should only need to chmod the `app/storage` directory to `755`.

**Comment by anarcat** [comment]
`755` and owned by `www-data`, i assume?

**Comment by jbrooksuk** [comment]
Yeah.

**Comment by anarcat** [comment]
thanks.
