### ISSUE TITLE
component groups not really removed

### ISSUE THREAD

**Issue by anarcat** [cachethq/Cachet#535]
if I create a component group "foo"  then delete it, when i try to recreate it i get:

```
Oups. Il s'est passé quelque chose avec ce composantgroupe de composants.

Le champ name est déjà utilisé.
```

that translates to `this field name is already used`.

**Comment by jbrooksuk** [comment]
We soft delete components, but have no way of reviving them.

**Comment by anarcat** [comment]
confirmed as working, thanks.
