### ISSUE TITLE
RSS feed is backwards

### ISSUE THREAD

**Issue by anarcat** [cachethq/Cachet#540]
The RSS feed has the right date, but shows the last items first, which is somewhat unexpected, to say the least. :)

**Comment by jbrooksuk** [comment]
The current implementation is correct. Check out the [GitHub status feed](https://status.github.com/messages.rss).

**Comment by anarcat** [comment]
wait, then there's a problem with my install. in both the demo and the github status feed, latest iterms are shown first. in *our* RSS feeds, most recent items are *last*.

sorry if my description wasn't clear...

**Comment by jbrooksuk** [comment]
![image](https://cloud.githubusercontent.com/assets/246103/6845547/c898baf4-d3ad-11e4-93df-a07538eff4c0.png)

That's the demo, it looks fine to me?

**Comment by anarcat** [comment]
that's what i am saying: the demo looks fine, the order is correct. but i notice the `<pubDate>` field are all the same. if you add a new element, it will *not* show up on top of the feed, but at the *bottom*! here's the current RSS output:

```
<?xml version="1.0" encoding="UTF-8"?>
<rss xmlns:content="http://purl.org/rss/1.0/modules/content/" xmlns:wfw="http://wellformedweb.org/CommentAPI/" xmlns:dc="http://purl.org/dc/elements/1.1/" xmlns:atom="http://www.w3.org/2005/Atom" xmlns:sy="http://purl.org/rss/1.0/modules/syndication/" xmlns:slash="http://purl.org/rss/1.0/modules/slash/" version="2.0"><channel><title>Cachet Demo</title><description>Status Feed</description><link>https://demo.cachethq.io</link><item><title>Awesome</title><description>We totally nailed the fix.</description><status>Fixed</status><pubDate>Thu, 26 Mar 2015 11:30:44 +0000</pubDate></item><item><title>Monitoring the fix</title><description>We're checking that our fix will first work.</description><status>Watching</status><pubDate>Thu, 26 Mar 2015 11:30:44 +0000</pubDate></item><item><title>Update</title><description>We've found the problem, so we're looking at it.</description><status>Identified</status><pubDate>Thu, 26 Mar 2015 11:30:44 +0000</pubDate></item><item><title>test</title><description>test</description><status>Investigating</status><pubDate>Thu, 26 Mar 2015 12:00:30 +0000</pubDate></item></channel></rss>
```

my test is at the end.

**Comment by jbrooksuk** [comment]
In the demo they will be correct because everything is seeded at the same time.

**Comment by anarcat** [comment]
right, which is why we don't see the bug there, but I am now pretty sure it's a bug. :)

**Comment by jbrooksuk** [comment]
This is fixed now.

**Comment by jbrooksuk** [comment]
83e979cc251673a79ef4ad7262ddb85e2cae0b6f

**Comment by anarcat** [comment]
great, thanks!
