### ISSUE TITLE
components menu in incident creation should mention component group

### ISSUE THREAD

**Issue by anarcat** [cachethq/Cachet#542]
when i create an incident, i see a flat list of components, not sorted by component group, which makes it ambiguous which component I report against if multiple components have the same name under different groups (think "web" in different clusters).

this would be a [`<optgroup>`](http://www.w3.org/wiki/HTML/Elements/optgroup#Example_A) tag.

**Comment by anarcat** [comment]
aaaaaaweesome?

please do tell me if i file too many annoying bugs, but I gotta say i am thoroughly impressed by the response time here.

thank you so much!

**Comment by jbrooksuk** [comment]
Hey, if I didn't like a suggestion, I'd give you the reason as to why I can't/won't implement something, then close it. And even if I don't do something, I truly appreciate the feedback and the time spent adding the issue in the first place.

This is a great suggestion and something I've overlooked, so thank you :)

**Comment by anarcat** [comment]
great, glad we're on the same page. i'll keep those issues and silly translation patches coming then. :)

**Comment by jbrooksuk** [comment]
Translation patches are definitely not silly :)
