### ISSUE TITLE
less agressive cookie timeouts

### ISSUE THREAD

**Issue by anarcat** [cachethq/Cachet#543]
it seems i get logged out after around 5 minutes in Cachet. while I can appreciate the effort to secure the software, I actually think that, in specific case of *this* software, being permanently logged in would actually be *more* useful than aggressively logged out.

in fact, what I was thinking here was that i would preventively login my phone, laptop, workstation and so on in advance, so that i don't need to scramble to find the password when i have an emergency update to send out.

at least having this configurable would be helpful.

**Comment by GrahamCampbell** [comment]
This is configurable. :)

**Comment by GrahamCampbell** [comment]
https://github.com/cachethq/Cachet/blob/master/app/config/session.php#L32

**Comment by GrahamCampbell** [comment]
The default lifetime is 600 seconds, which is 30 mins. That seems like a good default to me.

**Comment by jbrooksuk** [comment]
@GrahamCampbell 600 seconds = 10 minutes ;)

**Comment by jbrooksuk** [comment]
I'm in agreement that we should increase this though.

**Comment by anarcat** [comment]
oh i see. then maybe there's some documentation improvements to be done here, as i didn't find this on the documentation site... 

how do i configure this anyways? in env.local.php?

**Comment by GrahamCampbell** [comment]
> 600 seconds = 10 minutes ;)

Ha ha ha. I can math really, lol.

**Comment by jbrooksuk** [comment]
You can't configure the login expiration from Cachet itself, it's a Laravel thing.

**Comment by jbrooksuk** [comment]
> Ha ha ha. I can math really, lol.

I hope so, Mr Maths ;)

**Comment by anarcat** [comment]
ah, so those are hardcoded defaults? would there need to be a patch to get this from the environment if i would want to make that customizable?

how about [`secure` cookies](https://github.com/cachethq/Cachet/blob/master/app/config/session.php#L138)? are those hardcoded as well?

**Comment by jbrooksuk** [comment]
I'd rather we just increase this value ourselves. At least then everyone is on the same page.

Secure cookies aren't handled either actually.

**Comment by anarcat** [comment]
or to put this another way: it looks like there's a shitton and a half of awesome settings I could tweak in [`app/config`](https://github.com/cachethq/Cachet/blob/master/app/config) - do i need to learn Laravel first? :)

**Comment by jbrooksuk** [comment]
Yeah, but I'd look at L5, we're migrating to it pretty soon.

**Comment by anarcat** [comment]
ok.

as for a default, if we are to [bikeshed](http://bikeshed.com/) for the default timeout, i would argue for 24h+ (`86400s`), personnally i would set it to "one week" (`604800s`). (Yes, mr. math replacement is in tha house! ;)

**Comment by jbrooksuk** [comment]
@GrahamCampbell what do you think about 24 hours? I think that's a good value, because ideally people will be logging back in to update the status of something anyway.

**Comment by GrahamCampbell** [comment]
Let me check what the laravel default is. I think I lowered it in cachet.

**Comment by GrahamCampbell** [comment]
https://github.com/laravel/laravel/blob/v4.2.11/app/config/session.php#L32

**Comment by GrahamCampbell** [comment]
Ohhh, the time out is in mins, lol. Then we have a 600 min timeout. No where near to 5 mins!

**Comment by jbrooksuk** [comment]
:laughing:

**Comment by anarcat** [comment]
ok, then something else is kicking me out. are we sure it's minutes there? the comment seems to say so...

**Comment by anarcat** [comment]
i can confirm i was logged out in less than 10 hours. i was logged in when i posted the last comment here, and now i am logged out. even though on the frontpage of the site, i had a "disconnect" link, when i clicked on the dashboard link, i was presented with a login screen.

**Comment by jbrooksuk** [comment]
This seems to be fixed in the L5 branch. I've been kept logged into the dashboard for 4 hours now and still going.
