### ISSUE TITLE
metrics failure

### ISSUE THREAD

**Issue by anarcat** [cachethq/Cachet#544]
i get `Whoops, looks like something went wrong.` on the frontpage when trying to configure a new metric in the dashboard.

I used the following settings:

* Name: test
* Suffix: test
* Description: test
* Calculation of metrics: sum
* Default value: 100
* Display chart on status page? checked

Saving the metric and visiting the frontpage gives me the error. Removing the metric fixes it.

I can't reproduce on the demo site, unsure why.

**Comment by urtho** [comment]
Change this int Metric.php solved my issue with metrics:

=== self::CALC_SUM to == self::CALC_SUM 
and 
=== self::CALC_AVG to == self::CALC_AVG
