### ISSUE TITLE
RSS feeds should link to the announcement

### ISSUE THREAD

**Issue by anarcat** [cachethq/Cachet#546]
RSS feeds usually have items pointing to specific links. i think the RSS feeds produced by cachet should point to the announcement directly, or at least to the website.

**Comment by jbrooksuk** [comment]
This isn't possible in the current architecture because there isn't a single incident view, they're only ever listed on the status page. This will change in V2 when incidents tell a story, with updated content etc.

**Comment by anarcat** [comment]
right, understood - thanks!

**Comment by jbrooksuk** [comment]
Closed by b037965c355555513de611a88ad9cf43c929624a
