### ISSUE TITLE
per component group RSS feeds

### ISSUE THREAD

**Issue by anarcat** [cachethq/Cachet#548]
It would be nice to have multiple RSS feeds in Cachet. In our use case, we have differents services with varying user bases, and we need to tailor announcements for them independently. We regroup the different components of those services in component groups which act as "services".

Right now we use the same RSS feeds for all services, but it would be nice to have distinct RSS feeds for those different services / component groups.

This, of course, would be more useful alongside #495.

**Comment by jbrooksuk** [comment]
Nice idea! Let's get this done.

**Comment by anarcat** [comment]
thanks!

**Comment by mritzmann** [comment]
How can I use this function? Version: 2.3.13
