### ISSUE TITLE
feed ordering broke grouped feed display

### ISSUE THREAD

**Issue by anarcat** [cachethq/Cachet#550]
before 83e979cc251673a79ef4ad7262ddb85e2cae0b6f, i had the grouped RSS feeds working, but after the commit i get the less and less amusing `Whoops, looks like something went wrong.` :)

normal feeds work fine.

reverting the commit fixes the problem.

**Comment by anarcat** [comment]
with debugging, i get:

```
Symfony \ Component \ Debug \ Exception \ FatalErrorException (E_ERROR)
Call to undefined method Illuminate\Database\Eloquent\Collection::orderBy()
Open: /var/www/Cachet/src/Http/Controllers/RssController.php
            'title'       => Setting::get('app_name'),
            'description' => trans('cachet.feed'),
            'link'        => Setting::get('app_domain'),
        ]);
 
        if ($group) {
            $group->components->map(function ($component) use ($feed) {
                $component->incidents->orderBy('created_at', 'desc')->map(function ($incident) use ($feed) {
                    $this->feedAddItem($feed, $incident);
                });
```

**Comment by jbrooksuk** [comment]
Are you still getting this @anarcat?

**Comment by jbrooksuk** [comment]
Bump.

**Comment by anarcat** [comment]
yes, i am.

**Comment by anarcat** [comment]
the only thing that changed in the code since you asked is the metric fix and polish translation, not sure how i see this could have been fixed...

**Comment by jbrooksuk** [comment]
Ah, I forgot to push it then. The code will be on my Mac, so I'll have to look at this again.

**Comment by jbrooksuk** [comment]
Fixed.

**Comment by anarcat** [comment]
fix confirmed, thanks.

**Comment by jbrooksuk** [comment]
:+1:
