### ISSUE TITLE
Rendered text for planned maintenance need more spacing for titles

### ISSUE THREAD

**Issue by lelutin** [cachethq/Cachet#551]
When a planned maintenance is added, the Markdown text is rendered on the main page.

The titles should get a little more spacing (e.g. a little tuning to the CSS) to make the result easier to read.

Here's a simple example of text to render to see the spacing issue:

~~~
## What
Our system administrators are going on a boat ride .... in the data center!

## How
Pray for the best, there may be crocodiles or sharks in there.

## Why

Servers usually don't go along too well with crocodiles.

## How

* take a boat
* row all the way up to the crocs
* use eloquent speach to convince crocs to leave the DC
* Make sharks tag along the crocs
* Pump water out
* Get out with the boat
~~~

**Comment by jbrooksuk** [comment]
The Markdown is rendered into HTML for me, is this not the case for you?

**Comment by lelutin** [comment]
@jbrooksuk yes it is. the issue is with presentation (css). titles would look better if they were spaced more from the text.

**Comment by jbrooksuk** [comment]
We welcome pull requests (to the `L5` branch please).
