### ISSUE TITLE
Text boxes are too small, especially for scheduled maintenance

### ISSUE THREAD

**Issue by lelutin** [cachethq/Cachet#552]
For some incidents and especially for scheduled maintenance, it's great to put in some more detail and write some text that's a bit longer.

The text box for writing that text (e.g. "Incidents" -> "Scheduled maintenance" -> "Add Scheduled Maintenance") is too small. Some web apps fix this by letting users resize the textbox dynamically.

**Comment by jbrooksuk** [comment]
I like the idea of the dynamically resized textareas. I'll get this done in the `L5` branch.

**Comment by jbrooksuk** [comment]
For what it's worth @lelutin the text fields aren't limited in size.

**Comment by lelutin** [comment]
@jbrooksuk right, the length is not limited. it's mostly a visibility issue: on a browser with a "non-mobile" computer, the visible area is a bit too small and makes it harder to review what one's written.

thanks a lot for your help with this. I've never looked at the code yet and it would take me much more time to get a patch together.

**Comment by jbrooksuk** [comment]
Closed by 191e17b1a6c444cdbf608840a49896366bec30aa

Thanks!
