### ISSUE TITLE
make cachet cacheable

### ISSUE THREAD

**Issue by anarcat** [cachethq/Cachet#553]
right now, cachet is pretty agressive about tracking users and its content. out of the box, it sets a cookie for every visitor and explicitely forbids caching:

```
HTTP/1.1 200 OK
Date: Fri, 27 Mar 2015 17:27:50 GMT
Server: Apache/2.2.22 (Debian)
Cache-Control: no-cache
Set-Cookie: cachet_session=eyJpdiI6IkxDRTBPdFwvTUpkTHduSzNLUVFYQjVnPT0iLCJ2YWx1ZSI6IkQ4bmFJMTlpWnU0enN4SHBLaG9xMUpIU2M2RXZ5YW45T0FOUGdcL3ZFN3lQK3JjeDZBbHlSd2dsTEdJWVhkYVdLY1l2aDFPQk5IWTJOeEVmVm9MZlFuZz09IiwibWFjIjoiODUyZTRjMTFjMjg4NjE0YzFkZjQyMDExNmM0NWI3Njc1N2U1NGY5Yzk3ZjllNDA5MzkwZjFkMjM4NDVjMTRjOCJ9; expires=Sat, 28-Mar-2015 03:27:52 GMT; path=/; httponly
Vary: Accept-Encoding
Content-Type: text/html; charset=UTF-8
```

The idea here would be to get rid of the `Set-Cookie` directive and remove the `Cache-control` header, or set it to a good value. Example of a more properly configured site:

```
HTTP/1.1 200 OK
Server: Apache/2.2.22 (Debian)
Cache-Control: public, max-age=3600
Last-Modified: Fri, 27 Mar 2015 16:34:03 +0000
Expires: Sun, 11 Mar 1984 12:00:00 GMT
Vary: Cookie,Accept-Encoding
ETag: "1427474043"
Content-Type: text/html; charset=utf-8
Date: Fri, 27 Mar 2015 17:31:56 GMT
X-Varnish: 691902615 691819374
Age: 3472
Via: 1.1 varnish
Connection: keep-alive
```

above, the `Cache-Control` header allows for caching up to 1h, and tells the caching systems that different `Cookie` and `Accept-Encoding` will end up invalidating the cache. You can also notice that Varnish is caching the page properly (`Age: 3472`).

considering Cachet can be used in critical situations with lots of traffic, it would be nice to optimise this in such a way. then Nginx or Varnish could cache the content and serve it without loading the PHP stack at all.

**Comment by ApfelUser** [comment]
:+1:

**Comment by jbrooksuk** [comment]
Are you checking the demo? It could be CloudFlare doing this?

**Comment by anarcat** [comment]
it's native to the app, ie. it's not juste on the demo. it does happen on the demo, which makes me wonder how cloudflare would cache that stuff while still making logins work at all:

```
cache-control:no-cache
cf-ray:1cfd2a557d200fab-YYZ
content-encoding:gzip
content-type:text/html; charset=UTF-8
date:Tue, 31 Mar 2015 15:42:39 GMT
server:cloudflare-nginx
set-cookie:cachet_session=eyJpdiI6InB2NDR5UzArY1piZ3NTa25UZnNoZ0E9PSIsInZhbHVlIjoiWVRtbTV3Q29nNFNuOEltb1JIamdncmJYY3FQMXRkdmNTQzJPTEcwaVRaWUFqK2N1T3pKdG1DaXZ0WjlTMkFLMk1nMnhpeFFGN2kwRmVRMzB0YzFFUFE9PSIsIm1hYyI6IjE5NGQzZTM5ZWZiZDhkN2Q3MGRkNTA1ZjY4OGJjYTY1MmViNTFhZjc5NDkxY2FjNTRmMWI3MGU2OWRkNTE5YjEifQ%3D%3D; expires=Wed, 01-Apr-2015 01:42:39 GMT; Max-Age=36000; path=/; httponly
```

**Comment by jbrooksuk** [comment]
@GrahamCampbell is there a decent way to fix this issue? Breaking caching isn't a good thing to be doing.

**Comment by GrahamCampbell** [comment]
> how cloudflare would cache that stuff while still making logins work at all:

I have no idea what you mean? Coudflare behaves like any other proxy server, and followed the http spec with respect to caching, though you can ask it to override the caching headers and even ignore them if you want.

**Comment by jbrooksuk** [comment]
Is this even a Cachet issue?

**Comment by anarcat** [comment]
yes, it is. cachet doesn't send the right HTTP headers.

**Comment by Lavoaster** [comment]
It could be related this part in Symfony's HttpFoundation, it attempts to calculate a default for Cache-Control. [ResponseHeaderBag.php:301](https://github.com/symfony/HttpFoundation/blob/30a9abe5d6c509a92dbca6fca5ad6d0f84484f91/ResponseHeaderBag.php#L301)

To me it looks like it prevents caching of the page as it is not specified specifically. Realistically I would think caching only needs to be enabled on the index page, so, a good solution to be implemented would be to set the Last-Modified header on each page to the latest incident updated_at, or metric point if shown.

**Comment by ApfelUser** [comment]
In NodeJS you have to do:

```javascript
res.set('Cache-Control', 'public, max-age=10');
```

in order to achieve a NGINX server being able to cache your content. But I have no idea how you'd do that in PHP.

**Comment by wfjsw** [comment]
You may use 
```php
Header('');
``` 
:)

**Comment by jbrooksuk** [comment]
Rather than a `header` call @wfjsw, we can use Laravel's internals :)

**Comment by jbrooksuk** [comment]
Why do we remove the `Set-cookie` header?

**Comment by anarcat** [comment]
cookies invalidate caches like Varnish, ie. varnish won't cache a page that has a Cookie header by default.

also, for privacy reasons: why track users by default? create cookies on a need-to basis...

**Comment by jbrooksuk** [comment]
Laravel is doing it by default. Cookies aren't just for tracking, it's matching up sessions.

**Comment by anarcat** [comment]
I know what sessions are. Call it sessions, call it tracking, it's the same thing! Why do anonymous users have sessions? Is there a shopping cart of some sort that i missed?

**Comment by jbrooksuk** [comment]
I'll accept a PR to fix this.
