### ISSUE TITLE
Can not unbind docker container from port 80

### ISSUE THREAD

**Issue by jdgriffith** [cachethq/Cachet#554]
Let me begin by saying I am not too familiar with the docker process. I followed your steps to get the container up and running. I should mention I have development applications being served from apache on port 80 as well and I can hit several of those. After successfully hitting the app in a browser, (unfortunately from one of my predefined localhost ServerNames) that particular site always hits the bound docker port and I get a screen of "Be right back.".  I have tried several things to resolve this: removing all docker images, killing docker processes, restarting my machine, etc. What simple step am I missing here?

**Comment by jdgriffith** [comment]
Figured this out and the port binding was not the case. Closing.

**Comment by jbrooksuk** [comment]
Awesome :)
