### ISSUE TITLE
About monitor

### ISSUE THREAD

**Issue by tvvocold** [cachethq/Cachet#569]
hi there,
Thx for create this cool software, I had submit cachet.io to hacker news [1] and it rocks.But i had notice that  Cachet does not monitor  services.But without that it just a "front end".Do you have any plan to add this feature? like uptime [2]?

[1] https://news.ycombinator.com/item?id=9323488
[2] https://github.com/brantje/uptime

Regards,
Ray

**Comment by jbrooksuk** [comment]
Hi Ray,

Firstly, thank you for submitting Cachet to HN. We made first page (again!) your support is very much appreciated!

Well, since Cachet has an API, it should be fairly easy to make Uptime work with Cachet.

**Comment by tvvocold** [comment]
Emm, i need to test it first. So can u merged [PR562](https://github.com/cachethq/Cachet/pull/562) so we can test it in Openshift?(a free PAAS)
See https://github.com/StartledPhoenix/openshift-diy-cachet/issues/2#issuecomment-89867382
