### ISSUE TITLE
Change order of component groups

### ISSUE THREAD

**Issue by ApfelUser** [cachethq/Cachet#573]
Exactly the same feature is available at the components, would be great if you could do the same with the groups.

**Comment by jbrooksuk** [comment]
That makes sense. It'll probably be in V2 now though as we're already taking too long fixing bugs etc.

**Comment by jenolan** [comment]
If you have access to the underlying tables you can change the 'id' number to suit, just did it.

**Comment by jbrooksuk** [comment]
What @jenolan suggested will work for the time being :smile:
