### ISSUE TITLE
Sensu handler for CachetHQ

### ISSUE THREAD

**Issue by bimlendu** [cachethq/Cachet#574]
I have written a [sensu](http://sensuapp.org/) handler for cachethq.

https://github.com/bimlendu/sensu-cachethq

It updates cachethq based on sensu check output. I am using it to monitor [aws status page](http://status.aws.amazon.com/) and reflect the changes there to update components which we use, it works as of now.

Probably this can be added to Addons section.

**Comment by jbrooksuk** [comment]
This is really nice! We'd love a pull request to add your handler to our Addons list :)

**Comment by bimlendu** [comment]
Sent in a pull request.

**Comment by jbrooksuk** [comment]
Closed in #575
