### ISSUE TITLE
curl_multi_exec - too slow

### ISSUE THREAD

**Issue by unixengineer** [cachethq/Cachet#576]
As seen in the profiler screenshot, http://imgur.com/XC0xln7, the pages are too slow to load. curl_multi_exec seems to be the issue, and I am not sure how to go about locating the issue further. 

anyone running into the same issue ? any solution ?

**Comment by GrahamCampbell** [comment]
That should only be executed once. What caching are you using?

**Comment by unixengineer** [comment]
I tried with APCU and APC
my .env.local.php:
```
<?php

return [
    'DB_DRIVER'   => 'mysql',
    'DB_HOST'     => 'localhost',
    'DB_DATABASE' => 'cachet',
    'DB_USERNAME' => 'cachet',
    'DB_PASSWORD' => 'cachet',
    'CACHE_DRIVER' => 'apcu',
];
```

**Comment by jbrooksuk** [comment]
Do you have `apcu` or `apc` installed?

**Comment by GrahamCampbell** [comment]
> 'CACHE_DRIVER' => 'apcu',

That is not a valid cache driver. Laravel requires you to write "apc".

**Comment by GrahamCampbell** [comment]
@unixengineer It looks to me like laravel is not actually reading your environment file because you would have got an exception when you put in an invalid cache driver.

**Comment by unixengineer** [comment]
@GrahamCampbell I followed the documentation to set this up. I have now APC installed (I had, when opened this ticket, used apcu). 
app/config/database.php
```
'default' => getenv('DB_DRIVER') ?: 'mysql',

 'mysql' => [
            'driver'    => 'mysql',
            'host'      => getenv('DB_HOST') ?: localhost,
            'database'  => getenv('DB_DATABASE') ?: cachet,
            'username'  => getenv('DB_USERNAME') ?: cachet,
            'password'  => getenv('DB_PASSWORD') ?: cachet,
            'charset'   => 'utf8',
            'collation' => 'utf8_unicode_ci',
            'prefix'    => '',
        ],
```
app/config/cache.php
```
'driver' => getenv('CACHE_DRIVER') ?: 'apc',
```

**Comment by unixengineer** [comment]
I have fixed the issues. It looks to be one of :
1. APCU was not setup properly
2. The env files were wrong. So composer did not deploy/setup the config files properly.

The issues has been resolved. It seems to be working fine now

Thanks for the help in fixing this issue.
