### ISSUE TITLE
Metrics values are not displayed

### ISSUE THREAD

**Issue by arminus** [cachethq/Cachet#577]
This seems to be the same as #515 - which is marked Closed. However, I observe the same behavior as documented there (latest pull as of today). I do have metrics points in the database but the graph is empty, i.e. the generated data array is all 0 (data: [0,0,0,0,0,0,0,0,0,0,0]).

**Comment by arminus** [comment]
That's interesting. I let the monitor run since yesterday ~ 4pm, producing metric points every 15 minutes, the graph now renders starting at 2am this morning (the metric points from 4pm to 2am are missing though). The metric calculation is set to average, so I assume it needs a certain amount of points before it produces anything?

**Comment by jbrooksuk** [comment]
Well if you have one data point, then the average of it is still the value, no? @GrahamCampbell

**Comment by arminus** [comment]
That's how the graph looks like (to be clear: there are non zero metric points before 2am)

![2015-04-09_093611](https://cloud.githubusercontent.com/assets/683680/7062283/fb249de6-de9b-11e4-80ce-545d266b5865.png)

**Comment by jbrooksuk** [comment]
What timezone are you in?

**Comment by arminus** [comment]
CEST

**Comment by arminus** [comment]
Ok, more strange behavior: Since 2 hours, the graph is back at 0

![2015-04-09_170120](https://cloud.githubusercontent.com/assets/683680/7069732/ca4d7e1a-deda-11e4-90b7-ba0d46826984.png)

But there are metric points in the Postgres database (time there is GMT I suppose):

![2015-04-09_170528](https://cloud.githubusercontent.com/assets/683680/7069749/e90570a6-deda-11e4-87ec-97534cfed51f.png)

**Comment by arminus** [comment]
Sure enough, this morning, the graph starts to be ok again at 2am. i.e. 0 values in the graph (but not in the metric points table) from 3pm to 2am.

**Comment by jbrooksuk** [comment]
Very interesting. @arminus would you be able to email me a CSV of the `metric` and `metric_points` table? james@cachethq.io

**Comment by arminus** [comment]
Done

**Comment by jbrooksuk** [comment]
I wonder if we can fix it by changing the timestamps. @arminus are you able to modify [`Metric.php`](https://github.com/cachethq/Cachet/blob/master/src/Models/Metric.php#L87) and change the `%Y%m%e%H` to `%Y%m%d%H` please?

**Comment by arminus** [comment]
That appears to be in a mysql specific block... I have my DB in Postgres as mentioned above...

**Comment by jbrooksuk** [comment]
Sorry, same applies on [Line 89](https://github.com/cachethq/Cachet/blob/master/src/Models/Metric.php#L89).

**Comment by arminus** [comment]
Really? IMHO this is still in the 
`if (Config::get('database.default') === 'mysql') {`
block.

Anyway, I changed it, no change. (the site this runs on by the way is status.xctrails.org)

**Comment by jbrooksuk** [comment]
Doh. Sorry. I've had a stressful morning and been up a long time now, so I was being stupid.

**Comment by arminus** [comment]
Never mind, I also tried copying the metrics and metric_points table with squirrel sql from the postgres database into a mysql cachet db on a dev vm, but apparently cachet doesn't like that. says "Whoops, looks like something went wrong." after the copy (although the table contents look ok).

Anyway, if I have time later today, I'll probably try with mysql further to see if it works there.

**Comment by jbrooksuk** [comment]
Did you change the `DB_DRIVER` setting?

**Comment by arminus** [comment]
On the dev vm with mysql, yes. But apparently, the fact that I changed mysql's listen address to 0.0.0.0 meant that cachet couldn't access it anymore. back to 127.0.0.1, it loads again now, but the metrics values I've copied from the pgsql db don't show up either (i.e. flat 0 line)

**Comment by jbrooksuk** [comment]
To be honest, I've never tried connecting to MySQL over `0.0.0.0`, I'm not even sure if that should work?

**Comment by arminus** [comment]
yes, it should. https://dev.mysql.com/doc/refman/5.5/en/ipv6-server-config.html "If the address is 0.0.0.0, the server accepts TCP/IP connections on all server host IPv4 interfaces."

but that's really beside the point ;-) I now also inserted a couple of metric points via the API into the mysql db on the dev vm, they don't show up on the graph either

**Comment by jbrooksuk** [comment]
Heh sorry @arminus I'll take a look at this now.

**Comment by jbrooksuk** [comment]
What a derp piece of code.

**Comment by arminus** [comment]
hmmm, have a look at status.xctrails.org... doesn't look right to me yet... or do I need to wait for new metrics points being inserted?

**Comment by jbrooksuk** [comment]
Have you got any metrics over the last few hours?

**Comment by arminus** [comment]
yes, they get sent automatically every ~ 15 minutes (timestamps in the table are GMT I suppose)

![2015-04-11_210021](https://cloud.githubusercontent.com/assets/683680/7102809/e2314570-e08d-11e4-94d2-58585e1bc6b0.png)

**Comment by arminus** [comment]
Ok, I found the problem. Turns out that for Postgres, 
`to_char(metric_points.created_at, 'YYYYMMDDHH')`
[produces timestamps in 12h format] (http://www.postgresql.org/docs/8.2/static/functions-formatting.html), while the metric points are stored in 24 hour format in the table!

For me, changing Metric.php, line 101 to use
`to_char(metric_points.created_at, 'YYYYMMDDHH24')`
works.

The next issue is though, that the graph always drops to 0 at the end, I "fixed" that by adding an 
`$hour++`
right above line 101

**Comment by jbrooksuk** [comment]
Ah-ha! Well done @arminus good find.

Could you open a PR with this fix?

**Comment by arminus** [comment]
Not really, because IMHO my change is not yet a full fix. I haven't checked it with Sqlite and maybe in some other environment metric points are in fact stored with 12h timestamps. So I think this has to be somehow made dependent on the actual storage approach - but my PHP know-how is really thin...

**Comment by arminus** [comment]
at any rate, I created two separate tickets

**Comment by jbrooksuk** [comment]
Thanks, you've narrowed the bug down so we'll continue in the other issues.
