### ISSUE TITLE
setup.blade.php fails on Ubuntu 14.04

### ISSUE THREAD

**Issue by rinchen** [cachethq/Cachet#582]
Hi,

I'm trying to install Cachet on Ubuntu 14.04 using apache2 and mysql under php 5.5.9

In the browser I get stuck at /setup.  I enter the details, language, etc. and press next and I get a 404 error that /step/step1 is not found.  Also of interest is that the logo is cachet-log.svg instead of cachet-log.png.

Anyway, my installation is stuck at this point. I'm not a php person but I think it's failing inside setup.blade.php.

**Comment by rinchen** [comment]
There's also another error there but I think it's unrelated

Uncaught TypeError: Cannot read property 'errors' of undefined all-d4baa2f5.js:13
(anonymous function)all-d4baa2f5.js:2
K.Callbacks.d all-d4baa2f5.js:2
K.Callbacks.c.fireWithall-d 4baa2f5.js:3 
n all-d4baa2f5.js:3 
K.ajaxTransport.X.cors.e.crossDomain.send.t all-d4baa2f5.js:3

**Comment by jbrooksuk** [comment]
Hey @rinchen thanks for the bug report. Couple of questions:

- Do you have JavaScript enabled?
- What browser are you using?

We should be using the SVG logo because of the lossless quality.

**Comment by rinchen** [comment]
Hi @jbrooksuk,   Google Chrome Version 41.0.2272.118 (64-bit) on OS 10.10.3

**Comment by jbrooksuk** [comment]
With JavaScript enabled?

**Comment by rinchen** [comment]
Yes.

**Comment by jbrooksuk** [comment]
Ok, thanks buddy. I'll spin up a VM and take a look tonight :smile:

**Comment by jbrooksuk** [comment]
@rinchen what's your setup? Ubuntu 14.04 with nginx/Apache? FPM? What extensions do you have loaded?

**Comment by jbrooksuk** [comment]
Also is this Desktop or Server?

**Comment by jbrooksuk** [comment]
@rinchen could you answer the questions above for me please? It'll speed up the bug hunt :)

**Comment by rinchen** [comment]
@jbrooksuk 14.04 Server with Apache, php, mycrypt etc as per the docs.

**Comment by jbrooksuk** [comment]
Thanks, we'll take a look.

**Comment by jbrooksuk** [comment]
Do you have any Apache error logs I could take a look at?

**Comment by rinchen** [comment]
I don't. I uninstalled everything. I'm reinstalling it now to see if I get the same error.

**Comment by jbrooksuk** [comment]
Any update on this? :)

**Comment by rinchen** [comment]
I got stuck on problem with artisian not recognizing the database this time and ran out of time this weekend to trouble shoot it. :-(

**Comment by jbrooksuk** [comment]
I assumed you pulled down `master`? The environment configuration has changed here, basically:

1. Copy `.env.example` to `.env`
2. Update `.env` values to match what you had in `.env.php` 
3. `composer install`

Try again :)

**Comment by rinchen** [comment]
> On May 18, 2015, at 09:28 , James Brooks <notifications@github.com> wrote:
> 
> I assumed you pulled down master? The environment configuration has changed here, basically:
> 
> 	• Copy .env.example to .env
> 	• Update .env values to match what you had in .env.php
> 	• composer install
> Try again :)


Yeah that’s what failed.

**Comment by jbrooksuk** [comment]
All working now?

**Comment by rinchen** [comment]
> On May 18, 2015, at 10:04 , Joey Stanford <joey@stan4d.net> wrote:
> 
> Yeah that’s what failed.

Well that wasn’t a helpful update was it. :-)

What I meant to say was yes, I did that and I’m failing as per my other email now. I can’t get migrate to recognize SQL. I’m using the same essential setup as before and I can login to SQL and interrogate the database. I even went so far as to purge the DB and Tables from the original migrate run and retry…with no luck.

**Comment by jbrooksuk** [comment]
> Well that wasn’t a helpful update was it. :-)

Definitely not on my top 5 helpful comments :wink: 

Ok, did you happen to email me or the support email regarding this?

**Comment by jbrooksuk** [comment]
@joecohens is running Homestead (Ubuntu) and I run Cachet at work on Ubuntu, both without issues. We're putting this down to an environment thing, especially since there are JS errors. We can only suggest updating to the latest version and trying again. Ensure you have cookies and AJAX settings.

We'll close this issue, but if you do get it again after updating please let us know :smile:
