### ISSUE TITLE
Graph creation partially fails with Postgres DB

### ISSUE THREAD

**Issue by arminus** [cachethq/Cachet#583]
As described in #577 , there seems to be a mismatch between the time format of metric points as stored in the table and as retrieved from it with the respective query in Metric.php, line 101.

In my case, the values are stored in 24hour time format which means that the 
`to_char(metric_points.created_at, 'YYYYMMDDHH')`
fails for hours > 12

A first fix approach would be to use
`to_char(metric_points.created_at, 'YYYYMMDDHH24')`
instead - but that may break if for some reason the values are stored in 12h time format in another (e.g. US) environment.

For a real fix, these two formats need to be fully synchronized.

**Comment by jbrooksuk** [comment]
Everything is stored in 24H timestamps so this change is fine.
