### ISSUE TITLE
Graph drops to 0 values at the end

### ISSUE THREAD

**Issue by arminus** [cachethq/Cachet#584]
The time range for the Metric.php getValues function goes from 0 to 10, I think it needs to go from 1 to 11 instead so that the average of the current period (i.e. the last value in the graph) still gets reported and is not set to 0.

**Comment by jbrooksuk** [comment]
I'll have a play with that :)

**Comment by jbrooksuk** [comment]
Yeah, this is far better. Thanks :beers:
