### ISSUE TITLE
Metrics graph calculation does not consider more than one metric

### ISSUE THREAD

**Issue by arminus** [cachethq/Cachet#585]
To repro just add a 2nd metric -> the graph for the 2nd metric will look the same as the graph for the first metric.

My fix is only partial for the non-mysql query in Metric.php:

`$query = DB::select("select {$queryType} as aggregate FROM metrics JOIN metric_points ON metric_points.metric_id = metrics.id WHERE metric_points.metric_id = {$this->id} and to_char(metric_points.created_at, 'YYYYMMDDHH24') = :timestamp GROUP BY to_char(metric_points.created_at, 'H')", [
                'timestamp' => $dateTime->sub(new DateInterval('PT'.$hour.'H'))->format('YmdH'),
]);`

i.e. add an additional constraint **metric_points.metric_id = {$this->id}** - not sure how to do this in the mysql query construct

**Comment by jbrooksuk** [comment]
Heh, bit of an oversight on my part.
