### ISSUE TITLE
Install docs are wrong. 

### ISSUE THREAD

**Issue by mzupan** [cachethq/Cachet#586]
Following this

  https://docs.cachethq.io/v1.0/docs/installing-cachet

The docs want you to do a 
  
```
git clone https://github.com/cachethq/Cachet.git
```

That is fine except the default branch is L5 and most of the docs explain how to set it up for L4 from my understanding. That took a good 60 minutes away from my life figuring out why things weren't where they said they were.

**Comment by GrahamCampbell** [comment]
You need to checkout the master branch after cloning.

**Comment by GrahamCampbell** [comment]
You are reading the docs for the L5 version, clearly indicated by the branch name "L5" on the main page on github.

**Comment by jbrooksuk** [comment]
I'll update the docs to reflect this for now.
