### ISSUE TITLE
Unable to Use Pcntl.php on Windows Server 2008 R2

### ISSUE THREAD

**Issue by TheoBearman** [cachethq/Cachet#587]
Good evening,

I am trying to install Cachet on my Windows Server 2008 R2 box. Unfortunately, one of the PHP dependencies to run Cachet is 'pcntl.php', which is not compatible on Windows. This is to run 'Boris'.

Is there any way that the program could be changed to be compatible for Windows or there is an alternative .dll I can use that has the same effect? Do I need to run Boris to for Cachet to work or are there maybe some lines in the composer.lock file I can remove?

Thanks,

Theo.

**Comment by jbrooksuk** [comment]
Are you doing this under IIS?

**Comment by TheoBearman** [comment]
@jbrooksuk No. Xampp.

**Comment by jbrooksuk** [comment]
Weird, since my colleague is able to run another Laravel app under Xampp with zero problems. It may be one of the dependencies (aside from Boris) is requiring it.

**Comment by TheoBearman** [comment]
Skype? You can add me theo.bearman and we can try and work it out. According to my command line it's Boris.

**Comment by jbrooksuk** [comment]
I'm unavailable today, but could spend some time looking tomorrow night with you? Unless of course @GrahamCampbell has any ideas?

**Comment by TheoBearman** [comment]
I'm not around tomorrow night I'm afraid. No chance you could have a quick peek now?

**Comment by jbrooksuk** [comment]
Unfortunately not, I'm afraid. I'm currently at work and no access to a Windows machine.

**Comment by jbrooksuk** [comment]
Labelled as "help wanted" though in case anybody can pick this up in the mean time.

**Comment by TheoBearman** [comment]
![cmd](https://cloud.githubusercontent.com/assets/6546590/7214620/18288eb8-e5ac-11e4-8418-879254d4ea57.JPG)

This is a screenshot of my command line if it helps.

**Comment by wfjsw** [comment]
since this is a windows kernel problem, there is no easy way to solve this. we will have to replace this dep with an alternate one.

**Comment by jbrooksuk** [comment]
Actually, you could try out the `L5` branch @TheoBearman, as I believe this doesn't use Boris anymore?

**Comment by TheoBearman** [comment]
@jbrooksuk I'll give it a go now.

**Comment by TheoBearman** [comment]
Ok. It has installed but now the `php artisan migrate` command isn't working.

This is the command line:

![cmd](https://cloud.githubusercontent.com/assets/6546590/7214831/b54fd838-e5b4-11e4-8bb3-4ae7174d4473.JPG)

The `env.php` is made up of the following:

`<?php

return [
    'DB_DRIVER'   => 'mysql',
    'DB_HOST'     => 'localhost',
    'DB_DATABASE' => 'cachet',
    'DB_USERNAME' => 'cachet',
    'DB_PASSWORD' => 'INTENTIONALLY BLANK',
];`

**Comment by jbrooksuk** [comment]
You need to create a database on your host called `cachet` (as taken from your config).

**Comment by TheoBearman** [comment]
@jbrooksuk I have.

**Comment by jbrooksuk** [comment]
Ok, rather than using `localhost`, try `127.0.0.1` as the host.

**Comment by jbrooksuk** [comment]
Ah, sorry the config in `L5` has changed. Check out https://github.com/cachethq/Cachet/blob/L5/.env.example

**Comment by TheoBearman** [comment]
@jbrooksuk Ok, the `.env.php` file now contains:

    APP_ENV=local
    APP_DEBUG=true
    APP_KEY=SomeRandomString

     DB_DRIVER=mysql
     DB_HOST=localhost
     DB_DATABASE=cachet
     DB_USERNAME=cachet
     DB_PASSWORD=secret

    CACHE_DRIVER=apc
    SESSION_DRIVER=file
    QUEUE_DRIVER=sync

    MAIL_DRIVER=smtp
    MAIL_HOST=mailtrap.io
    MAIL_PORT=2525
    MAIL_USERNAME=null
    MAIL_PASSWORD=null

And I am getting the same error.

**Comment by jbrooksuk** [comment]
You don't need the `.php` extension.

**Comment by TheoBearman** [comment]
Ok, that worked. Now look at [this...](http://www.theobearman.com/cachet/public/setup).

**Comment by jbrooksuk** [comment]
You shouldn't install Cachet under a directory, can you move it to a sub-domain?

**Comment by TheoBearman** [comment]
@jbrooksuk Not really no.

**Comment by jbrooksuk** [comment]
Unfortunately we can't really do much then as the whole system relies on not being under a sub-directory.

**Comment by TheoBearman** [comment]
@jbrooksuk I'll look into it.

**Comment by GrahamCampbell** [comment]
> Not really no.

Laravel doesn't even support subdirectory installs officially anyway.

**Comment by TheoBearman** [comment]
@jbrooksuk Got it working, thanks!.

You may want to put somewhere in the docs to use the `L5` branch for setup instead of the `master` branch if you are using Windows Server.

Thanks so much.

Theo.

**Comment by jbrooksuk** [comment]
We'll be fully switching to the L5 branch soon anyway.

**Comment by TheoBearman** [comment]
@jbrooksuk What about [this](https://status.theobearman.com/api) now?

**Comment by jbrooksuk** [comment]
Currently undocumented (although explained in the blog post), is that the API is now versioned in the URL; https://status.theobearman.com/api/v1/incidents

**Comment by TheoBearman** [comment]
Ok. Also, is there a way that I can change the links to direct to the [ssl version](https://http://status.theobearman.com/dashboard/). For example as by default it links to the [http version]( http://status.theobearman.com/dashboard/)

**Comment by jbrooksuk** [comment]
https://status.theobearman.com/auth/login

Everything is relative, so if you're on HTTPS, all links will follow HTTPS.

**Comment by TheoBearman** [comment]
I am using Cloudflare Flexible SSL so the links to not follow HTTPS as default apart from on the status page which I have setup in Cloudflare.

**Comment by GrahamCampbell** [comment]
> I am using Cloudflare Flexible SSL so the links to not follow HTTPS as default apart from on the status page which I have setup in Cloudflare.

You haven't setup your trusted proxies correctly.

**Comment by TheoBearman** [comment]
@GrahamCampbell Where do I set that up and what do I need to put in?

**Comment by GrahamCampbell** [comment]
Something like this: https://i.starbs.net/NaO7.

**Comment by TheoBearman** [comment]
@GrahamCampbell Can you send me that file? Where do I put it into my Cachet install?

**Comment by TheoBearman** [comment]
@GrahamCampbell ?

**Comment by jbrooksuk** [comment]
It is actually within Cachet, https://github.com/cachethq/Cachet/blob/L5/config/trustedproxy.php

**Comment by TheoBearman** [comment]
@jbrooksuk So I just have to update that file with the Cloudflare IPs from the screenshot above?

**Comment by jbrooksuk** [comment]
I believe so. They were up to date at one point. If you could make it a PR that'd be brilliant.

**Comment by TheoBearman** [comment]
PR?

**Comment by TheoBearman** [comment]
@jbrooksuk @GrahamCampbell In any case, I uncommented `'proxies' => '*', and the SSL issue has still not resolved.

**Comment by jbrooksuk** [comment]
Can you open this as a new issue please.
