### ISSUE TITLE
Error build status at the Docker registry

### ISSUE THREAD

**Issue by EdeMeijer** [cachethq/Cachet#590]
https://registry.hub.docker.com/u/cachethq/cachet/builds_history/122451/

The last 2 builds have an error status.

**Comment by EdeMeijer** [comment]
I just saw you fixed the Travis build, so I'm sure the Docker build will be fine too.

**Comment by jbrooksuk** [comment]
It could be related, let's see :)

**Comment by jbrooksuk** [comment]
@sammcj hey buddy, can I somehow add you to the Registry and let you handle it? :)

**Comment by sammcj** [comment]
Hey @jbrooksuk - sorry I'm in the middle of moving house at the moment!

**Comment by jbrooksuk** [comment]
This no longer seems to be an issue now? https://registry.hub.docker.com/u/cachethq/cachet/builds_history/122451/
