### ISSUE TITLE
CloudFlare Flexible SSL Support

### ISSUE THREAD

**Issue by TheoBearman** [cachethq/Cachet#592]
Good morning,

I have CloudFlare flexible SSL activated on my domain that is running my Cachet [install](https://status.theobearman.com/). As you can see the flexible SSL appears to be running on the status page but the links to the [login](http://status.theobearman.com/auth/login) page for example from the footer is redirecting to the HTTP version.

I have tried uncommenting `'proxies' => '*', ` in the [trusted proxy.php file](https://github.com/cachethq/Cachet/blob/L5/config/trustedproxy.php) to no effect.

Thanks in advance for any suggestions,

Theo.

**Comment by jbrooksuk** [comment]
You're on the L5 branch, right? Could you try pulling the latest version and see if it helps?

**Comment by 0147500** [comment]
I had this problem before. It's because with flexible SSL laravel doesn't see the connection is https, because the connection to the server is just http.

**Comment by GrahamCampbell** [comment]
> I had this problem before. It's because with flexible SSL laravel doesn't see the connection is https, because the connection to the server is just http.

That's what setting the trusted proxies correctly fixes.

**Comment by 0147500** [comment]
Aa okay :)

**Comment by jbrooksuk** [comment]
> That's what setting the trusted proxies correctly fixes.

Should do... We've always had issues :) The L5 branch now registers the service provider for TrustedProxies, so it should actually work.

**Comment by TheoBearman** [comment]
@jbrooksuk I'll pull the latest Branch and try it out. Thanks.

**Comment by TheoBearman** [comment]
@jbrooksuk I've replaced the `trustedproxy.php` with [this one](https://github.com/cachethq/Cachet/blob/8714f4643dbfbca89be18e47c58d7dc2612d0491/config/trustedproxy.php0 and I am still getting the same problem. Is there another file I need to update? I don't want to pull the whole branch as I assume it will overwrite my current install.

**Comment by jbrooksuk** [comment]
@TheoBearman you will need to update to the latest commit on the L5 branch please.

**Comment by jbrooksuk** [comment]
What else have you changed then?

**Comment by jbrooksuk** [comment]
You could stash the changes, pull down and pop them on again.

**Comment by TheoBearman** [comment]
@jbrooksuk If I update to the latest commit, will it overwrite my install?

**Comment by jbrooksuk** [comment]
Stash your changes first.

**Comment by TheoBearman** [comment]
@jbrooksuk Decided to do a fresh install and now I have this issue...

![dafv](https://cloud.githubusercontent.com/assets/6546590/7219240/9f31c428-e68e-11e4-886a-d802c41f050b.JPG)

**Comment by jbrooksuk** [comment]
Ah you're on Windows, so chmod is useless for you.

**Comment by TheoBearman** [comment]
Yeah... workaround?

**Comment by GrahamCampbell** [comment]
run composer with `--no-scripts`

**Comment by jbrooksuk** [comment]
There you go ;)

**Comment by GrahamCampbell** [comment]
or just delete the chmod step from the composer.json

**Comment by TheoBearman** [comment]
What, so `composer install --no-dev -o --no scripts`?

**Comment by jbrooksuk** [comment]
`composer install --no-dev -o --no-scripts`.

**Comment by TheoBearman** [comment]
Ok, well after all that. The HTTPS issue still hasn't resolved! See [here](http://status.theobearman.com/auth/login).

**Comment by jbrooksuk** [comment]
Ah. It's the really annoying `url` helpers. Pull down latest changes, the links are fixed.

**Comment by TheoBearman** [comment]
@jbrooksuk Pulled down the changes. Still nothing.

**Comment by jbrooksuk** [comment]
It won't auto-detect for some reason, this has been the case for a long time :/ you'll need to go back to the status page and click the link, or just visit it directly. https://status.theobearman.com/auth/login

**Comment by TheoBearman** [comment]
@jbrooksuk Ok. Hopefully you guys will find a fix. Thanks anyway!

**Comment by jbrooksuk** [comment]
Yeah, me too. it's a right pain.

**Comment by ApfelUser** [comment]
@TheoBearman @jbrooksuk @GrahamCampbell you could just create your own certificate and enable "Full SSL" which then also sends a HTTPS request to your server who also has to listen for SSL. So you'd have to disable port 80 and enable port 433 with this here in the *server* block:

```
###
# LISTENERS
###
listen 443 ssl spdy;
listen [::]:443 ssl spdy;
```

and this in your *nginx.conf*

**Comment by TheoBearman** [comment]
@ApfelUser I'm on windows server. XAMPP not NGINX.

**Comment by ApfelUser** [comment]
Well, I don't know how XAMPP works, but you probably can enable SSL on XAMPP too. And there is also a NGINX version for Windows.

**Comment by ApfelUser** [comment]
http://nginx.org/en/docs/windows.html

**Comment by GrahamCampbell** [comment]
Quite honestly, this issue is totally unrelated to cachet.

**Comment by TheoBearman** [comment]
Just in case anyone else is having this problem, I finally found a fix.

    # Copy and paste into your .htaccess file or include in your apache conf files

    RewriteCond %{HTTP:CF-Visitor} '"scheme":"http"' [OR]
    RewriteCond %{HTTP_HOST} !^example.com$ [NC]
    RewriteRule ^(.*)$ https://example.com/$1 [R=301,L]
 
    # And remember to always use https for future requests
    Header set Strict-Transport-Security "max-age=16070400; includeSubDomains"

**Comment by GrahamCampbell** [comment]
> Just in case anyone else is having this problem, I finally found a fix.

This is not a proper fix. The correct fix is to set the trusted proxies.

**Comment by TheoBearman** [comment]
@GrahamCampbell How is this not 'proper' ?

**Comment by GrahamCampbell** [comment]
Anyone can sent a pretend CF-Visitor header in their requests. For this case, the security implications are minimal, but for other things, they could be more major, so hacks like this should not be encouraged.

**Comment by TheoBearman** [comment]
@GrahamCampbell Well, seeing as the TrustedProxies fix did not work for me, this is the only working fix for me as it stands.
