### ISSUE TITLE
CPanel & APCU

### ISSUE THREAD

**Issue by jenolan** [cachethq/Cachet#600]
Seeing as Heroku support is going away I setup a CPanel server to act for my various sites, problem is that Cachet is wanting non-standard php libraries, most especially APCU.

Come on guys ;-) you are making it real hard to just plugin and run on one of the most commonly available platforms. A shared host isn't going to do all the machinations to let a client run the wonderful status tool!

Most normal users will also find it difficult to repoint the root directory.... If you are going to drop Heroku at least make it easy to deploy on normal shared hosting ... please!

Larry

**Comment by jbrooksuk** [comment]
You don't have to use APC, you can switch to Redis, files, database etc. There may be some issues, but it's trial and error :)

**Comment by jenolan** [comment]
Ha .. BUT you have it as a requirement in the composer file! It means if it isn't there composer pukes!


Larry

**Comment by jbrooksuk** [comment]
We do, but it's because it's default in the config file. I'll have a look.

**Comment by jenolan** [comment]
That's what I am saying. apcu is NOT available by default in a CPanel environment.

Having it reduces the availability for normal hoomans.

FWIW .. my sysadmin has added apcu and we seem to be running, what I am saying is that Cachet should be installable in a bog standard CPanel shared web host so that the maximum number of people have the enormous pleasure of a nice status system .. please not for me but others.

Larry

**Comment by jbrooksuk** [comment]
Cachet is a modern web application. It's hard to make it backwards compatible with older hosts that can't provide the extensions we need.

But yes, we'll do our best to make it work.

**Comment by jbrooksuk** [comment]
@jenolan what caching alternatives would you suggest then?

**Comment by jbrooksuk** [comment]
@jenolan, @joecohens @GrahamCampbell and I are working on a solution to make the default cache driver file or database based (we're undecided). In the future this *may* change as our requirements grow, but for now we're making changes to avoid this.

**Comment by jenolan** [comment]
@jbrooksuk Sorry didn't see your request. As in reality there is not much data a file with all of the stuff wouldn't be very big would it? Otherwise DB, with the option to have it onto APC(etc).

What I am wondering, how much data is really being cached? Surely even a busy status system would be hard put to have the serialised data go over a few K?

**Comment by jbrooksuk** [comment]
At the moment the caching is used for the login throttling which we're limited by. @GrahamCampbell has refactored the package not to rely on tags (which require anything but file caching). Once we're able to use this package we can default to file.

**Comment by jbrooksuk** [comment]
Cachet should now work on cPanel by using the `file` drivers :)
