### ISSUE TITLE
why forcing using APCU?

### ISSUE THREAD

**Issue by Grummfy** [cachethq/Cachet#601]
I'm wondering why you are forcing people to use apcu?
There is lot cache system and this part can be configured. So except i you start documenting that this is mandatory and forcing for a real good reason, I think you should remove it.

thanks

**Comment by GrahamCampbell** [comment]
We're not forcing it.

**Comment by Grummfy** [comment]
when it's a requirement in composer and you need to use composer to install it... yes your are forcing

**Comment by GrahamCampbell** [comment]
> when it's a requirement in composer and you need to use composer to install it... yes your are forcing

No we're not. You can just remove it from that file. It's designed to be editied.

**Comment by Grummfy** [comment]
Sorry, but for me it's a stupid way to act, It's just slow down adoption and installation.... but if you think it's a good way to act ...ok

**Comment by jbrooksuk** [comment]
I disagree. Cachet has had **hundreds** of installations. APCU is a perfect, light-weight caching system which is ideal for Cachet. Like @GrahamCampbell said, you can easily change it within the `composer.json` file.
