### ISSUE TITLE
Issue component and component status updates bug

### ISSUE THREAD

**Issue by EdeMeijer** [cachethq/Cachet#603]
There are a couple of problems/bugs with updating issues, I think they're all related.

First, create a new issue, and select a component and a component status when doing so. Then edit the issue. The following things are strange:
- The component is not selected anymore, but the component status is
- When I update the component status (without re-selecting the component), it doesn't actually get updated. In fact, when you go back to editing yet again, the component status option also disappeared.
- When I try to re-select the component, the component status selection bar disappears. After saving and editing again, still no component is selected

In general, it's not possible to alter a component's status by updating an issue.

**Comment by jbrooksuk** [comment]
I've classified this as a bug, but hear me out.

You can't edit a component status when editing an incident because the component status is changed directly. If it's since been resolved or whatever, then you should add a new incident.

**Comment by EdeMeijer** [comment]
Yeah I know. In my case what i was trying to do is resetting a component status to OK when I update the issue status to solved.

**Comment by jbrooksuk** [comment]
In which case you can go to the dashboard and click on the status relating to the component:

![image](https://cloud.githubusercontent.com/assets/246103/7365116/0ceb88c6-ed85-11e4-9cf5-c1fd021a7b89.png)

**Comment by EdeMeijer** [comment]
Okay, but if you're required to exclusively change component statuses on the home page, then I think the UI when editing an issue shouldn't have a component status selection bar.

**Comment by jbrooksuk** [comment]
That's a good point.

**Comment by jbrooksuk** [comment]
Done :smile:

**Comment by EdeMeijer** [comment]
Well, alright then :P
