### ISSUE TITLE
Error when adding an issue without component status

### ISSUE THREAD

**Issue by EdeMeijer** [cachethq/Cachet#604]
When you add an issue and select a component, but don't select a component status, you get a `Whoops, looks like something went wrong.` 500 internal error. I would expect to get a normal error message saying I should select a component status, just like when you don't select an issue status.

**Comment by jbrooksuk** [comment]
Is this on the `master` branch or `L5`?

**Comment by jbrooksuk** [comment]
This doesn't happen under L5, could you update please.

**Comment by EdeMeijer** [comment]
This one seems to be fixed indeed, thanks :)
