### ISSUE TITLE
[API] Scheduled maintenance - date

### ISSUE THREAD

**Issue by itscassa** [cachethq/Cachet#607]
Hi,

It might be handy to add the planned date for a scheduled maintenance to the api incidents endpoint. Is this planned already? If not, will this be added?

**Comment by jbrooksuk** [comment]
Thanks for the suggestion. I'll take a look at this :smile:

**Comment by jbrooksuk** [comment]
Although undocumented, there is no reason why you couldn't supply a timestamp for `scheduled_at` to create a scheduled incident.
