### ISSUE TITLE
API Issues

### ISSUE THREAD

**Issue by Craytor** [cachethq/Cachet#608]
When I go and access the API url for my cachet installation, I get an error saying the route doesnt exist. The dashboard works fine, it's just the api that's not working. Here's a better look at the error:

![Image](http://shots.tjyouschak.me/1PMQ)

**Comment by Craytor** [comment]
I'm getting this issue on the L5 branch.

**Comment by TheoBearman** [comment]
@Craytor Same with me.

**Comment by jbrooksuk** [comment]
The endpoint for the L5 branch has now changed: `https://demo.cachethq.io/api/v1/endpoint`

**Comment by jbrooksuk** [comment]
Documentation will be updated to reflect this as soon as V1 is released.

**Comment by Craytor** [comment]
Alright, thanks @jbrooksuk, update the docs!!!! :P Joking....

**Comment by Craytor** [comment]
`https://demo.cachethq.io/api/v1/endpoint` fixed it!

**Comment by jbrooksuk** [comment]
I need to go back through the documentation soon.
