### ISSUE TITLE
[L5] Metrics

### ISSUE THREAD

**Issue by Craytor** [cachethq/Cachet#609]
Are metrics complete on the 'master' branch? I've put some metrics to the url, and they're in the database, but they are not displaying on the actual page. Is this done?

**Comment by jbrooksuk** [comment]
What do you mean by not displaying? Is the graph displaying?

**Comment by Craytor** [comment]
The points on the graph are all displaying 0, even though some of the latest points should have another other than 0 since I am taking the sum. Does that make sense?

**Comment by Craytor** [comment]
Actually, they are working. But I think there is a bug. For example, the points loading between the hour 18:00-19:00 (this is only an example) is a total of 790. That data is being displayed for the hour 19, not 18, is this correct?

**Comment by jbrooksuk** [comment]
Can you send me your `metrics` and `metric_points` table?

**Comment by Craytor** [comment]
Alright, I've got the stuff for you. I also would like to mention, that between hours the points for the hours actually change vertically, like sometimes the points will be higher up then the next hour, really confusing.

Here's a look at the site, before the next hour:
![First](http://shots.tjyouschak.me/eoyb)

After the hour:
![Second](http://shots.tjyouschak.me/AW2o)

Here you can look at my metric_points and metric table, you can download them and open them in Excel to quickly view them! https://onedrive.live.com/redir?resid=dd498fb8335650e%215975

**Comment by Craytor** [comment]
@jbrooksuk Have you looked into this at all?

**Comment by jbrooksuk** [comment]
Has this not been fixed by my other metrics fox?

**Comment by jbrooksuk** [comment]
@Craytor how's this now?

**Comment by jbrooksuk** [comment]
Doh, I missed the master branch above, but then switched the title to L5?

**Comment by jbrooksuk** [comment]
Closing this. @Craytor if it's still an issue, re-open please.
