### ISSUE TITLE
[L5] Login Not Working

### ISSUE THREAD

**Issue by Craytor** [cachethq/Cachet#611]
After pressing login on the login form (on the L5 branch), it throws an error. Not sure if it's related to #608

**Comment by jbrooksuk** [comment]
No error here. Are you on the absolute latest commit on the L5 branch?

**Comment by Craytor** [comment]
Yeah, completely sure. I just ran it again and got a 500 Internal Server Error. Here's an image when I turn APP_DEBUG to true...

![stuff](http://shots.tjyouschak.me/A0qR)

**Comment by GrahamCampbell** [comment]
You can't use the file cache. I thought we documented that?

**Comment by Craytor** [comment]
@jbrooksuk: @GrahamCampbell's solution worked! I think this should be more clearly documented.

**Comment by jbrooksuk** [comment]
https://docs.cachethq.io/v1.0/docs/caching
