### ISSUE TITLE
Date not translated previous incidents

### ISSUE THREAD

**Issue by TECHMAUS** [cachethq/Cachet#614]
When using Cachet in another language the dates on the homepage are not translated. 
![schermafbeelding 2015-04-30 om 01 38 54](https://cloud.githubusercontent.com/assets/9018689/7403834/58089b86-eeda-11e4-8b9e-47dfbc732abd.png)

**Comment by TECHMAUS** [comment]
Looked a bit closer into this and found out that dates of incidents and scheduled are in fact translated, only the ordinal indicator is superfluous. 
The date format in the timeline can be set in the dashboard, but doesn't support strftime. 
![schermafbeelding 2015-04-30 om 14 59 31](https://cloud.githubusercontent.com/assets/9018689/7413211/06b74c44-ef4a-11e4-8f44-ceb0410909ca.png)

**Comment by jbrooksuk** [comment]
Closed by #626.

**Comment by TECHMAUS** [comment]
Thanks guys. The dates in the timeline itself is showing fine now. But still got the superfluous ordinal indictor when hovering over the 'time ago' message in the timeline. Like in the image in my previous comment.

**Comment by jbrooksuk** [comment]
Could you open a new issue specific to this *secondary* bug? :)

**Comment by TECHMAUS** [comment]
Sure! See https://github.com/cachethq/Cachet/issues/644
