### ISSUE TITLE
Allow change the incident time when add/edit  incident

### ISSUE THREAD

**Issue by ninehills** [cachethq/Cachet#615]
For migrate history data from other statuspage-like system.

**Comment by svenmueller** [comment]
that would be very important!

**Comment by jbrooksuk** [comment]
I guess this would be useful if you were manually adding an incident that occurred earlier in the day?

**Comment by beberlei** [comment]
Yes and after installation you might add some incidents from the past.

**Comment by jbrooksuk** [comment]
CC @joecohens
