### ISSUE TITLE
HTTP Request to gist with Segment Key

### ISSUE THREAD

**Issue by beberlei** [cachethq/Cachet#618]
We installed Cachet for the status page of [tideways.io](https://tideways.io) and disabled segment collection during installation, however while monitoring the status page there are still some requests that request the segment key from a Gist Public URL:

![tideways_cachet_segment](https://cloud.githubusercontent.com/assets/26936/7428482/8e0335e4-eff1-11e4-8536-2ae295c1a33a.png)

700ms is an unacceptable amount of time making a http request. usually it takes just 100ms, but that is still way too much.

a.) Couldn't this information be cached forever? I regularly see requests having this.
b.) Could this http call be disabled completely if you disabled to collect segments.

**Comment by jbrooksuk** [comment]
1. No. In the event that the key is used for malicious purposes we need to be able to update it.
2. Sort of. You can disable the `app_track` setting, but this won't turn off fetching of the key.
