### ISSUE TITLE
Changing number of incidents to show

### ISSUE THREAD

**Issue by silverxp** [cachethq/Cachet#619]
On the status page you can see earlier incidents with the buttons provided, but when you enter less than 7 days in the dasboard (i.e. 3) and you browse back ... You keep seeing the first 3 days of the week and the rest of the weekdays are never displayed.

I don't know if this was meant this way, but it looks like it always browses 7 days back in time.

**Comment by jbrooksuk** [comment]
This bug led to a few things:

1. The fix that @Lavoaster made in #597 wasn't 100% complete. Dates weren't ordered properly to begin with. I had all sorts of crazy date ordering. That's been fixed.
2. The `$daysToShow` variable is `0-n` so if you had set `app_incident_days` to 3, it'd show 4 days.
3. We still had code for `subWeek()` which would always jump you back a week, leading to lost days.
