### ISSUE TITLE
[L5] Metrics and New Months

### ISSUE THREAD

**Issue by Craytor** [cachethq/Cachet#621]
Ever since May 1st rolled around my metrics graphs have quit working - well kind of. My points are all (time, 0). I know my service is still posting them to the api, and you can see all of the points here: [http://status.myweather.today/api/v1/metrics/1/points](http://status.myweather.today/api/v1/metrics/1/points). I'm using the sum way to calculate the points.

**Comment by jbrooksuk** [comment]
Can you export the table for me and I'll take a look whilst on my dinner.

**Comment by jbrooksuk** [comment]
(So now) :)

**Comment by jbrooksuk** [comment]
Both `metrics` and `metric_points` tables :)

**Comment by Craytor** [comment]
How do you want them exported? CSV, SQL, etc?

**Comment by jbrooksuk** [comment]
CSV is perfect :)

**Comment by Craytor** [comment]
Alright, [https://onedrive.live.com/?cid=0dd498fb8335650e&id=DD498FB8335650E%215975](https://onedrive.live.com/?cid=0dd498fb8335650e&id=DD498FB8335650E%215975) Download the files with the _5-2, they are the ones you want!

**Comment by jbrooksuk** [comment]
Are you on MySQL or PgSQL?

**Comment by Craytor** [comment]
MySQL

**Comment by jbrooksuk** [comment]
Thanks!

**Comment by Craytor** [comment]
#thatwasquick ;) Thanks!
