### ISSUE TITLE
Artisan failing on master

### ISSUE THREAD

**Issue by ALinuxNinja** [cachethq/Cachet#623]
Currently producing following error message:

Verified that MySQL host and DB exists.

```
composer install --no-dev -o
Loading composer repositories with package information
Installing dependencies from lock file
Warning: The lock file is not up to date with the latest changes in composer.json. You may be getting outdated dependencies. Run update to update them.
Nothing to install or update
Generating optimized autoload files


                              
  [InvalidArgumentException]  
  Database does not exist.
```

**Comment by jbrooksuk** [comment]
Make sure you have all of the following keys set in the `.env.php` configuration file (if on L5 it's `.env`)

- `DB_DRIVER`
- `DB_HOST`
- `DB_DATABASE`
- `DB_USERNAME`
- `DB_PASSWORD`

**Comment by jbrooksuk** [comment]
It's working here, so you're likely missing the environment configuration.
