### ISSUE TITLE
Metric Points are not shown in Graph

### ISSUE THREAD

**Issue by Arcticwolf** [cachethq/Cachet#625]
Hi,

I have a small problem with saving and showing metric points. I think in the end there is a mix of two problems.

1. When saving new metric points the created_at and updated_at fields of the points are not the same like local time. I added two new points today add 11:40 local time and when I retrieve the metric points via a GET request, I get:

```json
{"metric_points": [
      {
      "id": "1",
      "metric_id": "1",
      "value": "90.000",
      "created_at": "2015-05-06 09:40:43",
      "updated_at": "2015-05-06 09:40:43"
   },
      {
      "id": "2",
      "metric_id": "1",
      "value": "80.000",
      "created_at": "2015-05-06 09:40:56",
      "updated_at": "2015-05-06 09:40:56"
   }
]}
```

The time differs about two hours. So first I thought that I had maybe set the wrong time zone, but I checked it in the configurations and I have set the correct one.

Additionally, why do these values here have a different format than the other created_at and updated_at properties (e.g. of the components and the metrics)?

2. Even though the points don't have exactly the correct time, they are still not shown in the graph:
![figure](https://cloud.githubusercontent.com/assets/673494/7491208/63dd5192-f3e7-11e4-968f-4488d4f5f2fb.png)

About my setup: I use the docker image referenced at the README, so that I could quickstart to use this application.

I think that I just oversee something and that this is the root problem. Maybe you could help me?

Best regards,
Felix

**Comment by Arcticwolf** [comment]
Additional Information: I POST points to the URL {cachetUrl}/api/metrics/1/points with the correct token header and the json message:
{
  "value": 80
}

**Comment by jbrooksuk** [comment]
Is this still an issue on the latest version? We've changed how metric points are calculated, so this may be fixed.

**Comment by Arcticwolf** [comment]
Hi, I've tried it so far only with the docker image. I hope I can manage to try it out with the latest version today. I'll let you know.

Kind regards,
Felix

**Comment by Arcticwolf** [comment]
Ok, I've checked out this project, built the docker file and started the image like described in the README file. Everything starts, the components and metrics I've added are all there. Also the dashboard works. But when I try to access the REST api, I only get 404 Errors. But the paths are exactly the same like the ones I used with the docker image from your server (e.g. localhost/api/components). Are there now different paths?

**Comment by jbrooksuk** [comment]
Ah, if you're using the new master, you'll need to version the API. `localhost/api/v1/components`.

**Comment by Arcticwolf** [comment]
Thanks, that worked. Now I can access the REST services again : ) but unfortunately I still have the same issue. Here is the result of the rest call to /api/v1/metrics/1/points:

[
      {
      "id": "1",
      "metric_id": "1",
      "value": "80.000",
      "created_at": "2015-05-05 17:32:34",
      "updated_at": "2015-05-05 17:32:34"
   },
      {
      "id": "2",
      "metric_id": "1",
      "value": "90.000",
      "created_at": "2015-05-06 09:40:43",
      "updated_at": "2015-05-06 09:40:43"
   },
      {
      "id": "3",
      "metric_id": "1",
      "value": "80.000",
      "created_at": "2015-05-06 09:40:56",
      "updated_at": "2015-05-06 09:40:56"
   },
      {
      "id": "4",
      "metric_id": "1",
      "value": "80.000",
      "created_at": "2015-05-11 09:40:14",
      "updated_at": "2015-05-11 09:40:14"
   },
      {
      "id": "5",
      "metric_id": "1",
      "value": "90.000",
      "created_at": "2015-05-11 09:40:19",
      "updated_at": "2015-05-11 09:40:19"
   }
]

and the graph looks still like this:
![screen](https://cloud.githubusercontent.com/assets/673494/7562236/10aca9c4-f7d3-11e4-8238-4c357d0ee2e7.png)

**Comment by jbrooksuk** [comment]
A temporary solution is to manually send through the `created_at` and `updated_at` timestamps.

**Comment by Arcticwolf** [comment]
I posted now in this format:

{
	"value" : 90,
	"created_at" : "2015-05-11 11:30:00",
	"updated_at" : "2015-05-11 11:30:00"
}

and afterwards in that format:
{
	"value" : 90,
	"created_at" : 1431343800,
	"updated_at" : 1431343800
}

in both cases it seems that the api just overwrites the sent data. This is the result of the point listing:
[
      {
      "id": "1",
      "metric_id": "1",
      "value": "80.000",
      "created_at": "2015-05-05 17:32:34",
      "updated_at": "2015-05-05 17:32:34"
   },
      {
      "id": "2",
      "metric_id": "1",
      "value": "90.000",
      "created_at": "2015-05-06 09:40:43",
      "updated_at": "2015-05-06 09:40:43"
   },
      {
      "id": "3",
      "metric_id": "1",
      "value": "80.000",
      "created_at": "2015-05-06 09:40:56",
      "updated_at": "2015-05-06 09:40:56"
   },
      {
      "id": "4",
      "metric_id": "1",
      "value": "80.000",
      "created_at": "2015-05-11 09:40:14",
      "updated_at": "2015-05-11 09:40:14"
   },
      {
      "id": "5",
      "metric_id": "1",
      "value": "90.000",
      "created_at": "2015-05-11 09:40:19",
      "updated_at": "2015-05-11 09:40:19"
   },
      {
      "id": "6",
      "metric_id": "1",
      "value": "90.000",
      "created_at": "2015-05-11 09:58:21",
      "updated_at": "2015-05-11 09:58:21"
   },
      {
      "id": "7",
      "metric_id": "1",
      "value": "90.000",
      "created_at": "2015-05-11 09:58:41",
      "updated_at": "2015-05-11 09:58:41"
   }
]

also, even if the point timestamp differs two hours, shouldn't the points be displayed in the graph 2 hours before?

**Comment by Arcticwolf** [comment]
A small update: I just had a look at the graph and now some values are shown in the graph. But I don't know why (I havn't add new points since my last comment). Seems like the points are shown about 6 hours later than the date they have in the database. I assume there is somewhere a problem with the dates concerning the time zones.

![screen](https://cloud.githubusercontent.com/assets/673494/7570942/7df11376-f814-11e4-859c-45bc2548239c.png)

**Comment by joecohens** [comment]
Both issues solved on https://github.com/cachethq/Cachet/pull/638 if you keep having trouble let us know :)

**Comment by Arcticwolf** [comment]
Thanks :) I'll let you know as soon as I have time to test it.

Kind regards
Felix
