### ISSUE TITLE
CORS Only Returns Last Domain If List is Provided

### ISSUE THREAD

**Issue by blaskovicz** [cachethq/Cachet#628]
Under `settings > security > allowed domains` I have listed two websites:

`http://website.company.com,http://website2.company.com`

When I do an ajax GET to `<cachet host>/api/components` from the first origin, Cachet sends back the second origin (`http://website2.company.com`) in the `access-control-allow-origin` header.

**Comment by jbrooksuk** [comment]
I believe that we're actually [working with CORS incorrectly](http://stackoverflow.com/questions/1653308/access-control-allow-origin-multiple-origin-domains) and this is something that needs fixing ASAP.

**Comment by jbrooksuk** [comment]
You'll also need to start using the L5 branch for the fix I'm afraid.

**Comment by jbrooksuk** [comment]
CC @joecohens
