### ISSUE TITLE
Installed but blank screen

### ISSUE THREAD

**Issue by philshil** [cachethq/Cachet#632]
i followed the documentation however when i run the page i get a black white page..
![screen shot 2015-05-13 at 12 11 33](https://cloud.githubusercontent.com/assets/12427777/7609256/3bb2aa50-f969-11e4-9ed3-447bf32af831.png)

**Comment by jbrooksuk** [comment]
Try running `chmod 755 -R storage`.

**Comment by philshil** [comment]
made the change still getting a blank screen....

**Comment by jbrooksuk** [comment]
Did you run `composer install`?

**Comment by philshil** [comment]
after the change?

**Comment by philshil** [comment]
Run composer install before the change.. and just tried running it again but still no luck.

**Comment by philshil** [comment]
is there a recommended os to install on ?? I'm using centos 7

**Comment by jbrooksuk** [comment]
CentOS 7 should work fine. Did Composer work ok? Did you get any errors? Do you have the `.env` file setup?

**Comment by philshil** [comment]
Had an error originally because I missed off the ' ' on the database config but fixed that. I have my .env.local.php file in place in the root of the Cachet folder.... The database.php file though I couldn't find in the /app/config folder it was in the root/config folder instead....

Other than that no errors

**Comment by jbrooksuk** [comment]
Ah the env has changed, just needs to be .env

Take a look at .env.example

I need to update the docs.

**Comment by philshil** [comment]
okay
 i have updated the .env.example and resaved it as .env still no luck....
 

> On 15 May 2015 at 12:15 James Brooks <notifications@github.com> wrote:
> 
>  Ah the env has changed, just needs to be .env
> 
>  Take a look at .env.example
> 
>  I need to update the docs.
> 
>  > On 15 May 2015, at 07:32, philshil <notifications@github.com> wrote:
>  >
>  > Had an error originally because I missed off the ' ' on the database config
>  > but fixed that. I have my .env.local.php file in place in the root of the
>  > Cachet folder.... The database.php file though I couldn't find in the
>  > /app/config folder it was in the root/config folder instead....
>  >
>  > Other than that no errors
>  >
>  > > On 15 May 2015, at 07:28, James Brooks <notifications@github.com> wrote:
>  > >
>  > > CentOS 7 should work fine. Did Composer work ok? Did you get any errors?
>  > > Do you have the .env file setup?
>  > >
>  > > —
>  > > Reply to this email directly or view it on GitHub.
>  > >
>  > —
>  > Reply to this email directly or view it on GitHub.
>  >
> 
>  —
>  Reply to this email directly or view it on GitHub
> <https://github.com/cachethq/Cachet/issues/632#issuecomment-102372248> .
> 
>   
> 

 
Thanks
Phil Shilling

**Comment by philshil** [comment]
removed the password for security reasons but... if you see any errors please let me know 
![screen shot 2015-05-15 at 16 18 23](https://cloud.githubusercontent.com/assets/12427777/7655837/4bacb548-fb1e-11e4-9490-994772000b89.png)

**Comment by jbrooksuk** [comment]
Ok, now that you have that, have you ran `php artisan migrate`?

**Comment by philshil** [comment]
yup still getting a blank screen...

**Comment by jbrooksuk** [comment]
Are you running Apache? If so, make sure you have `mod_rewrite` enabled.

**Comment by RossMBoswell330** [comment]
This is working fine for me under CentOS 7. I ran the below without any errors.

composer install;
npm install;
bower --allow-root install;
gulp;
php artisan migrate; #(after I edited the .env file)

Does this work fine if you run php artisan serve ?

**Comment by jbrooksuk** [comment]
FYI you only need to run Bower if you're developing Cachet 👍🏻

**Comment by philshil** [comment]
I installed Apache php and MySQl
Download and installed composer 
Then git cloned into directory 
Edited the database.php
Edited the .env
Then php artisan migrate 
Am I missing something?

**Comment by RossMBoswell330** [comment]
Have you type the below?

$ composer install

I have follow your instructions you have provided and also get a blank page. 


Ross

**Comment by jbrooksuk** [comment]
Have you ran composer install?

**Comment by RossMBoswell330** [comment]
Type in php artisan serve or php -S localhost:8080 -t public. That way we can figure out whether this is a cachet/laravel issue or a apache setup issue.

**Comment by philshil** [comment]
Sorry yeah done composer install and composer install --no-dev -o I must be missing something because I get the same results across installs of centOS Debian and opensuse 
I have also set mod_rewrite on with the opensuse install and also have set the vhost as well....
When I'm on my machine in the morning I'll try that one Ross.

**Comment by philshil** [comment]
If someone could post a example of their database.php and .env
File that would be great to compare...
Obviously leaving out the password etc

**Comment by jbrooksuk** [comment]
@philshil there is no `database.php` file that you need to edit now. Your `.env` file should look like the [`.env.example`](https://github.com/cachethq/Cachet/blob/master/.env.example) file.

**Comment by RossMBoswell330** [comment]
@philshil Have you added the virtual host properly as per this link https://docs.cachethq.io/v1.0/docs/installing-cachet? After that when you restart apache do you get any errors. 

@jbrooksuk  in any case, I don't think this issue is a bug in Cachet.

**Comment by philshil** [comment]
okay so i moved to opensuse 13.2 as i like the Yast2 interface
these are my steps i took following the install docs…
ensured mysql, php5.6 and apache2 is installed
installed git and composer
git cloned into /srv/www/Cachet (as /srv/www is root for opensuse)
created a mysql database called cachet
edited the .env.example file (screenshot attached)
saved as just .env
run composer install —no-dev -o
php artisan migrate
mod_rewrite enabled
added cachet.conf to /etc/apache2/vhosts.d copied from the docs site
edited the hosts file
restarted service apache2 
still getting a blank screen… I’m stumped :/ 

i don’t think it is too just can’t seem to see where I’m going wrong….

**Comment by philshil** [comment]
![screen shot 2015-05-17 at 20 33 54](https://cloud.githubusercontent.com/assets/12427777/7671906/564ee64e-fcd9-11e4-8e92-fa743fef4a88.png)
![screen shot 2015-05-17 at 20 30 43](https://cloud.githubusercontent.com/assets/12427777/7671907/58edf390-fcd9-11e4-958c-6e5e2287b3d2.png)

**Comment by jbrooksuk** [comment]
You have a `PDOException` being thrown in the Terminal. What does it say?

**Comment by philshil** [comment]
oh i mistyped the password for the mysql connection, fixed that but still the same problem

**Comment by jbrooksuk** [comment]
Can we Skype tonight?

**Comment by philshil** [comment]
what time were you thinking?

**Comment by jbrooksuk** [comment]
7PM GMT?

**Comment by philshil** [comment]
im afraid i can't make 7PM, i won't be available until about 10:30PM GMT or tomorrow i could do 7PM

**Comment by jbrooksuk** [comment]
Is 7PM tomorrow ok then? We'll get this sorted for you, sorry that it's being so troublesome.

**Comment by philshil** [comment]
7PM works okay tomorrow. Its not a problem, i work in a school and just thought it would be useful for staff and students so its not a rush job :) . It must obviously be something I'm missing or not doing right

**Comment by jbrooksuk** [comment]
We'll find out tomorrow :) send me an email james@cachethq.io with your Skype ID :)

**Comment by philshil** [comment]
okay will do, shall i create a fresh virtual machine? openness 13.2 okay?

**Comment by jbrooksuk** [comment]
Stick with what you have currently and we'll make that work.

**Comment by philshil** [comment]
okay will do

**Comment by philshil** [comment]
James.. i think i have it working now..
i run these commands
# Group Writable (Group, User Writable)
$ sudo chmod -R gu+w storage

# World-writable (Group, User, Other Writable)
$ sudo chmod -R guo+w storage

it was this last one 
$ sudo chmod -R o+w storage/ that seemed to cure it...

**Comment by jbrooksuk** [comment]
That's great news!

Are we able to close this issue now?

**Comment by philshil** [comment]
i believe so. if i run into a problem il'l let you know..

**Comment by philshil** [comment]
have just got an incorrect integer value error but i think thats a problem my side

**Comment by philshil** [comment]
![screen shot 2015-05-18 at 14 43 45](https://cloud.githubusercontent.com/assets/12427777/7681984/573bccf0-fd6c-11e4-9a9a-e27c19bad2bf.png)

**Comment by jbrooksuk** [comment]
Are you using MySQL?

**Comment by philshil** [comment]
Yeah i added a component Group, added a component to that group, now if i try to add a component not in the group i get the error

**Comment by jbrooksuk** [comment]
This same error has been reported in #606. @philshil can you pull down the latest master and see if it still occurs? I've made a minor change.

**Comment by philshil** [comment]
how should i pull down the latest master, forgive me I'm new to github....

**Comment by jbrooksuk** [comment]
1. `cd` into the Cachet directory.
2. `git pull`

Then try again :)

**Comment by philshil** [comment]
still got the same error 
![screen shot 2015-05-18 at 16 24 44](https://cloud.githubusercontent.com/assets/12427777/7683983/967e18c4-fd7a-11e4-8551-b4bc453c4c05.png)

**Comment by jbrooksuk** [comment]
Sorry, pull again. I've just pushed a fix.

**Comment by philshil** [comment]
okay that seems to work :) :+1:

**Comment by jbrooksuk** [comment]
Smashing!

**Comment by donniekane** [comment]
Hey guys, if it's not too late, I had this same blank screen problem and I started my installation from scratch using this [article](https://www.rosehosting.com/blog/install-cachethq-on-centos-7/). 
Everything went smoothly. I hope someone will find it useful.
