### ISSUE TITLE
failure to upgrade to master

### ISSUE THREAD

**Issue by anarcat** [cachethq/Cachet#633]
i tried to get to the latest head (to test #524) and failed. i did a git pull, and the webapp gives me:

```
[Wed May 13 13:59:56 2015] [error] [client 199.58.80.81] PHP Warning:  require(/var/www/Cachet/src/helpers.php): failed to open stream: No such file or directory in /var/www/Cachet/vendor/composer/autoload_real.php on line 58
[Wed May 13 13:59:56 2015] [error] [client 199.58.80.81] PHP Fatal error:  require(): Failed opening required '/var/www/Cachet/src/helpers.php' (include_path='/var/www/Cachet/vendor/phpseclib/phpseclib/phpseclib:.:/usr/share/php:/usr/share/pear') in /var/www/Cachet/vendor/composer/autoload_real.php on line 58
```

how do we upgrade cachet anyways?

**Comment by jbrooksuk** [comment]
You're now on the L5 branch, if you were previously using L4, this is a bit different.

**Comment by anarcat** [comment]
that's an understatement. even trying to merge into my prod branch failed.

how different? how can i upgrade cachet? shouldn't there be upgrade instructions?

**Comment by jbrooksuk** [comment]
Completely different. It may be easier to remove the existing source, re-clone and set your config again as no data will be lost. If you're using SQLite then you'll need to back up the DB.

**Comment by anarcat** [comment]
well, that's really confusing. i am pretty sure i will backup my DB anyways, so that's a good idea. but how do i migrate the database? i assume database structures are going to happen?

anyways, i think it's not right that this is not documented properly, so i opened #637 to followup on that.

**Comment by jbrooksuk** [comment]
Database structure is fine, we've just switched to using Laravel 5 over L4, but it means we had to start a new branch.
