### ISSUE TITLE
provide Cachet upgrade instructions

### ISSUE THREAD

**Issue by anarcat** [cachethq/Cachet#637]
i have had this situation at first with cachet that i didn't know at all how to upgrade it when new code would come in. at first i just [ran git-pull](https://wiki.koumbit.net/CachetMaintenance#Upgrade) but now this completely failed with the L5 branch merge (see #633). Besides, this doesn't run the database structure changes which I assume are needed with the new code.

So how does one upgrade Cachet anyways? Is it like installing completely anew? If so, how to migrate the DB?

Note that this is blocking the creation of a Debian package (#610).

**Comment by jbrooksuk** [comment]
New documentation is available at https://docs.cachethq.io/v1.0/docs/upgrading-from-laravel-4

**Comment by jbrooksuk** [comment]
Link is found in the README file now.

**Comment by anarcat** [comment]
the idea here was to provide generic upgrade instructions. then specific releases can provide specific upgrade steps. for example, it seems that the generic upgrade process is:

```
git remote update
git reset --hard origin/master
# do some version-specific changes here
php artisan migrate
composer install -o --no-dev
```

Then this would be useful for upgrades not touching Laravel or for people that don't (want to) know what laravel is.

Also, shouldn't the composer job run before the migrate?
