### ISSUE TITLE
$this->auth is not defined in API controllers

### ISSUE THREAD

**Issue by ecentinela** [cachethq/Cachet#640]
IncidentController::postIncidents and ComponentController::postComponents relays in the auth data, but it seems that does not exists:

```
'Undefined property: CachetHQ\Cachet\Http\Controllers\Api\IncidentController::$auth' in /vagrant/app/Http/Controllers/Api/IncidentController.php:68
```

**Comment by jbrooksuk** [comment]
@joecohens can we fix this in https://github.com/cachethq/Cachet/pull/638 as well?

**Comment by joecohens** [comment]
Yes we can :smile: we need to update the responses as well so we will inject the auth on this one.

**Comment by jbrooksuk** [comment]
@joecohens moved this into the V1.0.0 milestone and assigned to you because this can be fixed in #638 :)

**Comment by joecohens** [comment]
:+1:

**Comment by joecohens** [comment]
Fixed by https://github.com/cachethq/Cachet/pull/654 and https://github.com/cachethq/Cachet/pull/638
