### ISSUE TITLE
"About this page" section shows escaped HTML entities

### ISSUE THREAD

**Issue by svenmueller** [cachethq/Cachet#641]
- escaped paragraph tag is added around text
- contained html tags are escaped and not rendered properly

![bildschirmfoto 2015-05-18 um 10 40 15](https://cloud.githubusercontent.com/assets/131689/7677205/71523952-fd4a-11e4-8bcc-e9b4c1d49435.png)

**Comment by svenmueller** [comment]
that was fast :+1:

**Comment by jbrooksuk** [comment]
This same bug probably plagues a lot of Cachet since the upgrade to L5. If you find anymore, let me know :)

**Comment by svenmueller** [comment]
@jbrooksuk same problems for notifications (used latest docker container version)

![bildschirmfoto 2015-05-20 um 20 42 11](https://cloud.githubusercontent.com/assets/131689/7733662/d900ecaa-ff30-11e4-81fd-5d5b80efc57f.png)

**Comment by jbrooksuk** [comment]
@joecohens at some point we need to switch all results to a single view.

**Comment by jbrooksuk** [comment]
Oh we do :)

**Comment by svenmueller** [comment]
Btw, should i create a new issue for that?

**Comment by jbrooksuk** [comment]
Please :)
