### ISSUE TITLE
Superfluous ordinal indictor timeline incidents

### ISSUE THREAD

**Issue by TECHMAUS** [cachethq/Cachet#644]
When hovering over the '.. time ago' message in the timeline, there is a superfluous ordinal indicator when using Cachet in another language (in my case Dutch). 

![schermafbeelding 2015-04-30 om 14 59 31](https://cloud.githubusercontent.com/assets/9018689/7413211/06b74c44-ef4a-11e4-8f44-ceb0410909ca.png)

It would be nice if this date would be shown in the format as set in the settings in the dashboard.

**Comment by jbrooksuk** [comment]
@joecohens what's weird here is that we're setting the tooltip title to be `created_at_formatted` which should already be formatted with the setting, no?

**Comment by jbrooksuk** [comment]
Found it @joecohens:

```php
public function created_at_formatted()
{
    return ucfirst((new Date($this->wrappedObject->created_at))
        ->setTimezone($this->tz)
        ->format('l jS F Y H:i:s'));
}
```

We should use the setting or fallback to this format.

**Comment by joecohens** [comment]
Yep :)

**Comment by jbrooksuk** [comment]
On it.
