### ISSUE TITLE
Fatal Error after Syncing the Latest Commits

### ISSUE THREAD

**Issue by TheoBearman** [cachethq/Cachet#649]
Windows Server 2008 R2 with XAMPP.

https://status.theobearman.com/

**Comment by GrahamCampbell** [comment]
Did you run composer update?

**Comment by jbrooksuk** [comment]
Looks to be fine?

**Comment by TheoBearman** [comment]
It is now. Thanks Graham. Apologies @jbrooksuk.

**Comment by jbrooksuk** [comment]
:)

**Comment by TheoBearman** [comment]
I take it back.

Commits synced, composer update executed. Dashboard is working fine but I am getting errors when I try to log in.The login page itself is fine but I get errors after putting in my email and password.

https://status.theobearman.com/auth/login

![gfwf](https://cloud.githubusercontent.com/assets/6546590/7721460/bb336e34-fecf-11e4-9f66-9ad468efbe3a.PNG)

**Comment by jbrooksuk** [comment]
Can you add a `APP_URL` key to `.env` with your `https://status.theobearman.com` domain as the value please:

```
APP_URL=https://status.theobearman.com
```

**Comment by jbrooksuk** [comment]
Before you do that, pull down the latest `master` and try again.

**Comment by TheoBearman** [comment]
Pulled down the latest `master` which is now working. Thanks James!

**Comment by TheoBearman** [comment]
Reopened. This is to do with yesterday's commits. I have run composer update.

**Comment by jbrooksuk** [comment]
Yeah, Laravel has changed some cipher stuff.

**Comment by TheoBearman** [comment]
What do I do to fix it?

**Comment by TheoBearman** [comment]
Working again. Just ran install and then update.
