### ISSUE TITLE
Notification messages contain escaped HTML entities

### ISSUE THREAD

**Issue by svenmueller** [cachethq/Cachet#653]
![bildschirmfoto 2015-05-20 um 20 42 11](https://cloud.githubusercontent.com/assets/131689/7736409/d5b25ab2-ff43-11e4-87e7-cedb606fc9ec.png)

(btw, where can i find the version information in the dashboard? would be nice to be able to add it when reporting issues)

**Comment by svenmueller** [comment]
thx a lot! :rocket:

**Comment by jbrooksuk** [comment]
This is the easier way of fixing it for now. The dashboard will get a good going over in V2 :smile:
