### ISSUE TITLE
Upgrade 500 Error

### ISSUE THREAD

**Issue by jenolan** [cachethq/Cachet#655]
After following the instruction to upgrade this is being logged (500 fake error on front end).

[2015-05-20 23:14:48] production.ERROR: exception 'ErrorException' with message 'call_user_func_array() expects parameter 1 to be a valid callback, class 'Illuminate\Cache\FileStore' does not have a method 'tags'' in /home/statusj/Cachet/vendor/laravel/framework/src/Illuminate/Cache/Repository.php:366
Stack trace:
#0 [internal function]: Illuminate\Foundation\Bootstrap\HandleExceptions->handleError(2, 'call_user_func_...', '/home/statusj/C...', 366, Array)
#1 /home/statusj/Cachet/vendor/laravel/framework/src/Illuminate/Cache/Repository.php(366): call_user_func_array(Array, Array)
#2 /home/statusj/Cachet/vendor/graham-campbell/throttle/src/Factories/CacheFactory.php(53): Illuminate\Cache\Repository->__call('tags', Array)
#3 /home/statusj/Cachet/vendor/graham-campbell/throttle/src/Factories/CacheFactory.php(53): Illuminate\Cache\Repository->tags('throttle', '116.250.210.52')
#4 /home/statusj/Cachet/vendor/graham-campbell/throttle/src/Throttle.php(73): GrahamCampbell\Throttle\Factories\CacheFactory->make(Object(GrahamCampbell\Throttle\Data))
#5 [internal function]: GrahamCampbell\Throttle\Throttle->get(Object(Illuminate\Http\Request), 10, 10)
#6 /home/statusj/Cachet/vendor/graham-campbell/throttle/src/Throttle.php(111): call_user_func_array(Array, Array)
#7 /home/statusj/Cachet/vendor/compiled.php(5372): GrahamCampbell\Throttle\Throttle->__call('check', Array)
#8 /home/statusj/Cachet/vendor/compiled.php(5372): GrahamCampbell\Throttle\Throttle->check(Object(Illuminate\Http\Request), 10, 10)
#9 /home/statusj/Cachet/app/Http/Middleware/LoginThrottling.php(40): Illuminate\Support\Facades\Facade::__callStatic('check', Array)
#10 /home/statusj/Cachet/app/Http/Middleware/LoginThrottling.php(40): GrahamCampbell\Throttle\Facades\Throttle::check(Object(Illuminate\Http\Request), 10, 10)
#11 /home/statusj/Cachet/vendor/compiled.php(9059): CachetHQ\Cachet\Http\Middleware\LoginThrottling->handle(Object(Illuminate\Http\Request), Object(Closure))
#12 /home/statusj/Cachet/vendor/compiled.php(2492): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#13 /home/statusj/Cachet/app/Http/Middleware/VerifyCsrfToken.php(31): Illuminate\Foundation\Http\Middleware\VerifyCsrfToken->handle(Object(Illuminate\Http\Request), Object(Closure))
#14 /home/statusj/Cachet/vendor/compiled.php(9059): CachetHQ\Cachet\Http\Middleware\VerifyCsrfToken->handle(Object(Illuminate\Http\Request), Object(Closure))
#15 /home/statusj/Cachet/app/Http/Middleware/RedirectIfAuthenticated.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#16 /home/statusj/Cachet/vendor/compiled.php(9059): CachetHQ\Cachet\Http\Middleware\RedirectIfAuthenticated->handle(Object(Illuminate\Http\Request), Object(Closure))
#17 /home/statusj/Cachet/app/Http/Middleware/HasSetting.php(48): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#18 /home/statusj/Cachet/vendor/compiled.php(9059): CachetHQ\Cachet\Http\Middleware\HasSetting->handle(Object(Illuminate\Http\Request), Object(Closure))
#19 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#20 /home/statusj/Cachet/vendor/compiled.php(9050): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#21 /home/statusj/Cachet/vendor/compiled.php(7056): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#22 /home/statusj/Cachet/vendor/compiled.php(7045): Illuminate\Routing\Router->runRouteWithinStack(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request))
#23 /home/statusj/Cachet/vendor/compiled.php(7030): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
#24 /home/statusj/Cachet/vendor/compiled.php(1989): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#25 [internal function]: Illuminate\Foundation\Http\Kernel->Illuminate\Foundation\Http\{closure}(Object(Illuminate\Http\Request))
#26 /home/statusj/Cachet/vendor/compiled.php(9067): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#27 /home/statusj/Cachet/vendor/compiled.php(12216): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#28 /home/statusj/Cachet/vendor/compiled.php(9059): Illuminate\View\Middleware\ShareErrorsFromSession->handle(Object(Illuminate\Http\Request), Object(Closure))
#29 /home/statusj/Cachet/vendor/compiled.php(10917): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#30 /home/statusj/Cachet/vendor/compiled.php(9059): Illuminate\Session\Middleware\StartSession->handle(Object(Illuminate\Http\Request), Object(Closure))
#31 /home/statusj/Cachet/vendor/compiled.php(11922): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#32 /home/statusj/Cachet/vendor/compiled.php(9059): Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse->handle(Object(Illuminate\Http\Request), Object(Closure))
#33 /home/statusj/Cachet/vendor/compiled.php(11871): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#34 /home/statusj/Cachet/vendor/compiled.php(9059): Illuminate\Cookie\Middleware\EncryptCookies->handle(Object(Illuminate\Http\Request), Object(Closure))
#35 /home/statusj/Cachet/vendor/compiled.php(2532): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#36 /home/statusj/Cachet/vendor/compiled.php(9059): Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode->handle(Object(Illuminate\Http\Request), Object(Closure))
#37 /home/statusj/Cachet/vendor/fideloper/proxy/src/TrustProxies.php(47): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#38 /home/statusj/Cachet/vendor/compiled.php(9059): Fideloper\Proxy\TrustProxies->handle(Object(Illuminate\Http\Request), Object(Closure))
#39 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#40 /home/statusj/Cachet/vendor/compiled.php(9050): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#41 /home/statusj/Cachet/vendor/compiled.php(1945): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#42 /home/statusj/Cachet/vendor/compiled.php(1932): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter(Object(Illuminate\Http\Request))
#43 /home/statusj/Cachet/public/index.php(56): Illuminate\Foundation\Http\Kernel->handle(Object(Illuminate\Http\Request))
#44 {main}

**Comment by GrahamCampbell** [comment]
You can't use the file driver. You need to use one that support tags.

**Comment by jenolan** [comment]
Huh?
What do I need to change? If it is different from previous shouldn't it be a step in the upgrade process instructions?

**Comment by jenolan** [comment]
OK got past that ...
1. SQLSTATE[42S22]: Column not found: 1054 Unknown column 'order' in 'order clause' (SQL: select * from `component_groups` where `id` in (1, 2, 3, 4) order by `order` asc) 

2. How do I set it to use the internal meail() instead of smtp nothing in the install docs about mail ;-)

**Comment by jenolan** [comment]
OK Now for 1 - you need to add "run  php artisan migrate" to the upgrade instructions

**Comment by jbrooksuk** [comment]
Added to docs.
