### ISSUE TITLE
Error after following the setup.

### ISSUE THREAD

**Issue by Lumiahna** [cachethq/Cachet#656]
Hello, 
I'm on debian 7/64 with apache2+mysql-server.
I followed the installation guide here (https://docs.cachethq.io/v1.0/docs/installing-cachet ) but every time I've got this page: http://status.2fy.eu ...
Every steps works fine, I don't understand this final result ...

root@status:/var/www/Cachet# composer install --no-dev -o
Loading composer repositories with package information
Installing dependencies from lock file
  - Installing vlucas/phpdotenv (v1.1.0)
    Downloading: 100%         

  - Installing symfony/var-dumper (v2.6.7)
    Downloading: 100%         

  - Installing symfony/translation (v2.6.7)
    Downloading: 100%         

  - Installing symfony/security-core (v2.6.7)
    Downloading: 100%         

  - Installing symfony/routing (v2.6.7)
    Downloading: 100%         

  - Installing symfony/process (v2.6.7)
    Downloading: 100%         

  - Installing symfony/http-foundation (v2.6.7)
    Downloading: 100%         

  - Installing symfony/event-dispatcher (v2.6.7)
    Downloading: 100%         

  - Installing psr/log (1.0.0)
    Downloading: 100%         

  - Installing symfony/debug (v2.6.7)
    Downloading: 100%         

  - Installing symfony/http-kernel (v2.6.7)
    Downloading: 100%         

  - Installing symfony/finder (v2.6.7)
    Downloading: 100%         

  - Installing symfony/console (v2.6.7)
    Downloading: 100%         

  - Installing swiftmailer/swiftmailer (v5.4.0)
    Downloading: 100%         

  - Installing nikic/php-parser (v1.3.0)
    Downloading: 100%         

  - Installing jakub-onderka/php-console-color (0.1)
    Downloading: 100%         

  - Installing jakub-onderka/php-console-highlighter (v0.3.1)
    Downloading: 100%         

  - Installing dnoegel/php-xdg-base-dir (0.1)
    Downloading: 100%         

  - Installing psy/psysh (v0.4.4)
    Downloading: 100%         

  - Installing nesbot/carbon (1.17.0)
    Downloading: 100%         

  - Installing mtdowling/cron-expression (v1.0.4)
    Downloading: 100%         

  - Installing monolog/monolog (1.13.1)
    Downloading: 100%         

  - Installing league/flysystem (1.0.3)
    Downloading: 100%         

  - Installing jeremeamia/superclosure (2.1.0)
    Downloading: 100%         

  - Installing ircmaxell/password-compat (v1.0.4)
    Downloading: 100%         

  - Installing doctrine/inflector (v1.0.1)
    Downloading: 100%         

  - Installing danielstjules/stringy (1.9.0)
    Downloading: 100%         

  - Installing symfony/filesystem (v2.6.7)
    Downloading: 100%         

  - Installing classpreloader/classpreloader (1.3.0)
    Downloading: 100%         

  - Installing laravel/framework (v5.0.31)
    Downloading: 100%         

  - Installing asm89/stack-cors (0.2.1)
    Downloading: 100%         

  - Installing barryvdh/laravel-cors (dev-master 7de71aa)
    Downloading: 100%         

  - Installing segmentio/analytics-php (1.1.3)
    Downloading: 100%         

  - Installing cachethq/segment (2.0.0)
    Downloading: 100%         

  - Installing doctrine/lexer (v1.0.1)
    Downloading: 100%         

  - Installing doctrine/annotations (v1.2.4)
    Downloading: 100%         

  - Installing doctrine/cache (v1.4.1)
    Downloading: 100%         

  - Installing doctrine/collections (v1.3.0)
    Downloading: 100%         

  - Installing doctrine/common (v2.5.0)
    Downloading: 100%         

  - Installing doctrine/dbal (v2.5.1)
    Downloading: 100%         

  - Installing fideloper/proxy (3.0.0)
    Downloading: 100%         

  - Installing graham-campbell/security (v3.0.0)
    Downloading: 100%         

  - Installing graham-campbell/binput (v3.0.0)
    Downloading: 100%         

  - Installing filp/whoops (1.1.5)
    Downloading: 100%         

  - Installing graham-campbell/exceptions (v1.0.0)
    Downloading: 100%         

  - Installing league/commonmark (0.8.0)
    Downloading: 100%         

  - Installing graham-campbell/markdown (v3.0.2)
    Downloading: 100%         

  - Installing graham-campbell/throttle (v3.0.0)
    Downloading: 100%         

  - Installing react/promise (v2.2.0)
    Downloading: 100%         

  - Installing guzzlehttp/streams (3.0.0)
    Downloading: 100%         

  - Installing guzzlehttp/ringphp (1.0.7)
    Downloading: 100%         

  - Installing guzzlehttp/guzzle (5.2.0)
    Downloading: 100%         

  - Installing illuminate/html (v5.0.0)
    Downloading: 100%         

  - Installing jenssegers/date (v2.0.21)
    Downloading: 100%         

  - Installing mccool/laravel-auto-presenter (3.0.0)
    Downloading: 100%         

  - Installing pragmarx/google2fa (v0.1.0)
    Downloading: 100%         

  - Installing roumen/feed (v2.9.1)
    Downloading: 100%         

  - Installing watson/validating (1.0.0)
    Downloading: 100%         

Generating optimized autoload files
Generating optimized class loader
root@status:/var/www/Cachet# php artisan migrate
Migration table created successfully.
Migrated: 2015_01_05_201324_CreateComponentGroupsTable
Migrated: 2015_01_05_201444_CreateComponentsTable
Migrated: 2015_01_05_202446_CreateIncidentTemplatesTable
Migrated: 2015_01_05_202609_CreateIncidentsTable
Migrated: 2015_01_05_202730_CreateMetricPointsTable
Migrated: 2015_01_05_202826_CreateMetricsTable
Migrated: 2015_01_05_202929_CreateServicesTable
Migrated: 2015_01_05_203014_CreateSettingsTable
Migrated: 2015_01_05_203235_CreateSubscriptionsTable
Migrated: 2015_01_05_203341_CreateUsersTable
Migrated: 2015_01_09_083419_AlterTableUsersAdd2FA
Migrated: 2015_01_16_083825_CreateTagsTable
Migrated: 2015_01_16_084030_CreateComponentTagTable
Migrated: 2015_02_28_214642_UpdateIncidentsAddScheduledAt
Migrated: 2015_05_19_214534_AlterTableComponentGroupsAddOrder
root@status:/var/www/Cachet#

Can you tell me what's wrong ?
Cheers,
Lumiahna

**Comment by jbrooksuk** [comment]
You need to run `sudo chmod -R 755 storage` if that fails, change 755 to 777.

Also in your `.env` file you should make `APP_DEBUG=0`.

**Comment by Lumiahna** [comment]
Thanx for your reply (: .
Done the chmod to storage directory and modify .env but now ... Blank Page :( .
I check if someone has the same issue

**Comment by jbrooksuk** [comment]
Try `sudo chmod -R 777 storage` instead?

**Comment by Lumiahna** [comment]
Done, no change ...

**Comment by ApfelUser** [comment]
Try:

`git stash && git pull && composer install --no-dev -o && chmod -R 777 storage`

or with **sudo**:

`sudo -s && git stash && git pull && composer install --no-dev -o && chmod -R 777 storage`

Also check that you have only 1 environment file which is called `.env`. **Not** e.g. `.env.local`!

**Comment by Lumiahna** [comment]
root@status:/var/www/Cachet# git stash && git pull && composer install --no-dev -o && chmod -R 777 storage
No local changes to save
Already up-to-date.
Loading composer repositories with package information
Installing dependencies from lock file
Nothing to install or update
Generating optimized autoload files
Generating optimized class loader
Compiling common classes
root@status:/var/www/Cachet# 

My .env looks like
APP_ENV=production
APP_DEBUG=0
APP_URL=http://status.2fy.eu
APP_KEY=SomeRandomString

DB_DRIVER=mysql
DB_HOST=localhost
DB_DATABASE=cachet
DB_USERNAME=cachet
DB_PASSWORD=CacherMotDePasse90

CACHE_DRIVER=apc
SESSION_DRIVER=file
QUEUE_DRIVER=sync

MAIL_DRIVER=smtp
MAIL_HOST=mailtrap.io
MAIL_PORT=2525
MAIL_USERNAME=null

**Comment by ApfelUser** [comment]
You posted the database password. Try `php artisan migrate`

**Comment by Lumiahna** [comment]
root@status:/var/www/Cachet# php artisan migrate
**************************************
*     Application In Production!     *
**************************************

Do you really wish to run this command? [y/N] Y
Nothing to migrate.
root@status:/var/www/Cachet# 

Should I change APP_ENV ?

**Comment by ApfelUser** [comment]
Try

```
APP_ENV=local
APP_DEBUG=true
```

that is how mine looks, but I doubt that it will help.

**Comment by Lumiahna** [comment]
We're back to the problem: http://status.2fy.eu

**Comment by ApfelUser** [comment]
Okay, when we're done you should change the `APP_DEBUG` to `0` again. But now we have an error @jbrooksuk can work with:

```
        $callback = function ($match) {
            if (method_exists($this, $method = 'compile' . ucfirst($match[1]))) {
                $match[0] = $this->{$method}(array_get($match, 3));
            }
            return isset($match[3]) ? $match[0] : $match[0] . $match[2];
        };
        return preg_replace_callback('/\\B@(\\w+)([ \\t]*)(\\( ( (?>[^()]+) | (?3) )* \\))?/x', $callback, $value);
    }
    protected function compileRawEchos($value)
    {
```

**Comment by Lumiahna** [comment]
I don't understand why does it fail .. I reinstalled my vps 3 times today and still have this blank page :/

**Comment by ApfelUser** [comment]
It has something to do with your OS. What do you use? CentOS?

**Comment by ApfelUser** [comment]
Try adding these package sources to your sources.list file: Enter the file via

```
sudo nano /etc/apt/sources.list
```
and add these lines at the end of the file (right click pastes):

```
deb http://packages.dotdeb.org wheezy-php55 all
deb-src http://packages.dotdeb.org wheezy-php55 all
```

Then:

```
sudo apt-get update && sudo apt-get upgrade
```

**Comment by Lumiahna** [comment]
Debian 7 64 bits actually but I can reinstall to centos 6 64 bits .
And I'm already using these deb ^^

**Comment by ApfelUser** [comment]
I updated the comment. No, please don't use CentOS. Keep Debian :+1:

**Comment by ApfelUser** [comment]
Also maybe try:

```
composer update
```

**Comment by Lumiahna** [comment]
root@status:/var/www/Cachet# composer update
Loading composer repositories with package information
Updating dependencies (including require-dev)
  - Removing graham-campbell/security (v3.0.0)
  - Installing graham-campbell/security (v3.1.0)
    Downloading: 100%         

  - Removing graham-campbell/binput (v3.0.0)
  - Installing graham-campbell/binput (v3.1.0)
    Downloading: 100%         

  - Removing graham-campbell/markdown (v3.0.2)
  - Installing graham-campbell/markdown (v3.1.0)
    Downloading: 100%         

  - Removing guzzlehttp/ringphp (1.0.7)
  - Installing guzzlehttp/ringphp (1.1.0)
    Downloading: 100%         

  - Removing guzzlehttp/guzzle (5.2.0)
  - Installing guzzlehttp/guzzle (5.3.0)
    Downloading: 100%         

  - Removing mccool/laravel-auto-presenter (3.0.0)
  - Installing mccool/laravel-auto-presenter (3.0.1)
    Downloading: 100%         

  - Installing sebastian/version (1.0.5)
    Downloading: 100%         

  - Installing sebastian/global-state (1.0.0)
    Downloading: 100%         

  - Installing sebastian/recursion-context (1.0.0)
    Downloading: 100%         

  - Installing sebastian/exporter (1.2.0)
    Downloading: 100%         

  - Installing sebastian/environment (1.2.2)
    Downloading: 100%         

  - Installing sebastian/diff (1.3.0)
    Downloading: 100%         

  - Installing sebastian/comparator (1.1.1)
    Downloading: 100%         

  - Installing symfony/yaml (v2.6.7)
    Downloading: 100%         

  - Installing doctrine/instantiator (1.0.4)
    Downloading: 100%         

  - Installing phpdocumentor/reflection-docblock (2.0.4)
    Downloading: 100%         

  - Installing phpspec/prophecy (v1.4.1)
    Downloading: 100%         

  - Installing phpunit/php-text-template (1.2.0)
    Downloading: 100%         

  - Installing phpunit/phpunit-mock-objects (2.3.1)
    Downloading: 100%         

  - Installing phpunit/php-timer (1.0.5)
    Downloading: 100%         

  - Installing phpunit/php-token-stream (1.4.1)
    Downloading: 100%         

  - Installing phpunit/php-file-iterator (1.4.0)
    Downloading: 100%         

  - Installing phpunit/php-code-coverage (2.0.16)
    Downloading: 100%         

  - Installing phpunit/phpunit (4.6.6)
    Downloading: 100%         

  - Installing hamcrest/hamcrest-php (v1.2.2)
    Loading from cache

  - Installing mockery/mockery (0.9.4)
    Loading from cache

sebastian/global-state suggests installing ext-uopz (*)
phpdocumentor/reflection-docblock suggests installing dflydev/markdown (~1.0)
phpdocumentor/reflection-docblock suggests installing erusev/parsedown (~1.0)
phpunit/php-code-coverage suggests installing ext-xdebug (>=2.2.1)
phpunit/phpunit suggests installing phpunit/php-invoker (~1.1)
Writing lock file
Generating autoload files
Generating optimized class loader
Compiling common classes
root@status:/var/www/Cachet#

**Comment by ApfelUser** [comment]
Could you give me the output of `php -v`?

**Comment by Lumiahna** [comment]
PHP 5.6.9-1~dotdeb+7.1 (cli) (built: May 15 2015 16:14:09) 
Copyright (c) 1997-2015 The PHP Group
Zend Engine v2.6.0, Copyright (c) 1998-2015 Zend Technologies
    with Zend OPcache v7.0.4-dev, Copyright (c) 1999-2015, by Zend Technologies
root@status:/var/www/Cachet#

**Comment by ApfelUser** [comment]
Very strange. There seems to be something like a fix on [Stackoverflow] (http://stackoverflow.com/questions/24094899/preg-replace-callback-compilation-failed-laravel-4-2) but I think there should be a different solution.

**Comment by Lumiahna** [comment]
Yes it's strange .. Like I said I did it 3 times, and every time the same issue and I reinstalled every time..
Maybe I did something wrong, I don't know ...

**Comment by ApfelUser** [comment]
@Lumiahna I can help you set up NGINX  with PHP-FPM if you want. This works on my system. Maybe over TeamViewer or something else. I am in Europe right now, so it is 11:00 PM GMT+1 here. I sadly don't have time today anymore but I am available from 11:00 AM GMT+1 to 8:00 PM GMT+1 tomorrow.

**Comment by Lumiahna** [comment]
Alright @ApfelUser , do you have a mail / skype or something ?
(:

**Comment by ApfelUser** [comment]
My E-Mail is silas.rech@icloud.com

**Comment by jbrooksuk** [comment]
Can you pull down the latest version and see if that helps? I've pushed some fixes here and there this morning. They may or may not help. 

Kind regards,

James Brooks

Founder

**Comment by Lumiahna** [comment]
Hey @jbrooksuk and thx
Ok just tested on a fresh vps install.
Now I've a /setup not found
take a look on http://status.2fy.eu

**Comment by jbrooksuk** [comment]
Are you on Skype @Lumiahna?

**Comment by Lumiahna** [comment]
yes my skype is borisdu78 .

**Comment by jbrooksuk** [comment]
This error isn't Cachet, but related to the regex used to parse Blade templates. It seems that Laravel is causing the issue.

I've suggested to @Lumiahna to try and use `php55` rather than the `php56` packages, just in case.

**Comment by Lumiahna** [comment]
Hello,
root@status:/var/www/Cachet# php -v
PHP 5.5.25-1~dotdeb+7.1 (cli) (built: May 15 2015 17:16:36)
Copyright (c) 1997-2015 The PHP Group
Zend Engine v2.5.0, Copyright (c) 1998-2015 Zend Technologies
    with Zend OPcache v7.0.4-dev, Copyright (c) 1999-2015, by Zend Technologies

Now still have the blank page with app_debug enabled.

**Comment by jbrooksuk** [comment]
@Lumiahna if you setup the same details as we had yesterday so that I can login, I'll take another look.

**Comment by Lumiahna** [comment]
Same setup as yesterday, you can login (:

**Comment by jbrooksuk** [comment]
Done! http://status.2fy.eu/setup

**Comment by Lumiahna** [comment]
Wow thanks, can you explain me what did you do ?

**Comment by jbrooksuk** [comment]
Fucked it up. Nearly fixed it. Fucked it up again. Fixed it.

Basically, I removed Apache and PHP5-FPM and re-installed it all.

**Comment by Lumiahna** [comment]
Oh ok, I'll try to install it on another VPS to see this fuck/fixe :p
Thanks again dude,
Issues fixed (:

**Comment by jbrooksuk** [comment]
Use Ubuntu, always works for me.

**Comment by Lumiahna** [comment]
Last ubuntu release ?

**Comment by jbrooksuk** [comment]
I know it works on 14.04 - both our demo and status page use it.
