### ISSUE TITLE
Incident on group

### ISSUE THREAD

**Issue by dennusb** [CachetHQ/Cachet#668]
Hi,

You can create component groups but you can't create an incident for a group. That would be awesome, because 1 group can mean 1 server with different services (and all are down)! :)

Could that be added?

**Comment by jbrooksuk** [comment]
This is something that we will be addressing in V2. Currently we have tags but they're not used properly yet.

**Comment by f0o** [comment]
:+1:

**Comment by jbrooksuk** [comment]
Merged into https://github.com/CachetHQ/Cachet/issues/1176
