### ISSUE TITLE
Change Order of Components Within Groups

### ISSUE THREAD

**Issue by TheoBearman** [cachethq/Cachet#670]
As above.

**Comment by svenmueller** [comment]
+1

**Comment by ApfelUser** [comment]
+1

**Comment by jbrooksuk** [comment]
Technically we kind of do this, but it's a pain to work out manually:

```php
$usedComponentGroups = Component::where('group_id', '>', 0)->groupBy('group_id')->lists('group_id');
$componentGroups = ComponentGroup::whereIn('id', $usedComponentGroups)->orderBy('order')->get();
$ungroupedComponents = Component::where('group_id', 0)->orderBy('order')->orderBy('created_at')->get();
```

So basically everything we pull out is still ordered by `order`, which means that you should be able to order your components already and they'll be ordered when they're pulled into the groups.

**Comment by TheoBearman** [comment]
@jbrooksuk If you're talking about trying to re-arrange the components in the components page, that doesn't work, at least for me. When you refresh the page the components return to their previous positions and do not change on the status page. Hence, this feature request.

**Comment by jbrooksuk** [comment]
Can you pull down the latest `master` please @TheoBearman :)

**Comment by TheoBearman** [comment]
@jbrooksuk I just have every morning as I always do. Now, I am getting a `Component Order Updated` message and the order is saving in my `components` section. However, on my [status page](https://status.theobearman.com/), the order has not changed in the `Infrastructure` section to reflect the order in the `components` section.

**Comment by jbrooksuk** [comment]
I've fixed the bug with ordering of components within component groups :)

**Comment by TheoBearman** [comment]
@jbrooksuk Cheers again James!

**Comment by jbrooksuk** [comment]
In V2 we'll make it easier to order within the given group, which will be a natural expansion of this feature anyway.

**Comment by TheoBearman** [comment]
@jbrooksuk https://status.theobearman.com/. Do I need to run something in the command prompt too?

**Comment by jbrooksuk** [comment]
Err, re-pull? That looks like it's missing another change.

**Comment by TheoBearman** [comment]
I just did. Same error.

**Comment by jbrooksuk** [comment]
This is really weird, it's all hunky dorky here, but both our status page and demo are broken too. One second.

**Comment by jbrooksuk** [comment]
Ok, pull down again. Fixed :)

**Comment by TheoBearman** [comment]
All good. Thanks!
