### ISSUE TITLE
Not able to see on which server the incident was?

### ISSUE THREAD

**Issue by dennusb** [cachethq/Cachet#671]
Hi,

When i create an incident i select the server/service on which the issue is occuring, after it's fixed it is nicely displayed in the "timeline", with text/date/time etc, but the server/service name can't be found anymore... is it a good "improvement" to place the component name there?

**Comment by jbrooksuk** [comment]
This will be something that we address in V2, as we'll be addressing a lot of the incident timeline issues we're now seeing :)

**Comment by jbrooksuk** [comment]
Closed by 9515d874bf49b3ef0c94022141cfde427a6fb75d
