### ISSUE TITLE
Allow users to sign up and recieve system status alerts

### ISSUE THREAD

**Issue by jrgifford** [cachethq/Cachet#673]
I think it would be very useful to have a user sign up to receive status updates, rather than having to subscribe to the RSS feed.

**Comment by jrgifford** [comment]
Forgive me, I wasn't searching correctly. Figures after an hour I would post, and then find it. This seems to be related to https://github.com/cachethq/Cachet/pull/662.

**Comment by jbrooksuk** [comment]
No problem :)
