### ISSUE TITLE
Recurring maintenance

### ISSUE THREAD

**Issue by dennusb** [CachetHQ/Cachet#674]
I would be very very cool if you can have recurring maintenance, like every first Tuesday of the month or something like that ! :)

**Comment by jbrooksuk** [comment]
I've never thought about this feature! We'll address it in V2 :)

**Comment by override-chaos** [comment]
:+1: Would love to see this as well !

**Comment by Galexrt** [comment]
+1

**Comment by svenmueller** [comment]
+1

**Comment by DivineOmega** [comment]
I did a quick mock-up of how I thought adding recurring maintenances could work within the dashboard.

![screenshot from 2015-05-30 02 43 18](https://cloud.githubusercontent.com/assets/650645/7895168/3b81ea2c-0676-11e5-9488-d8f73d7cb57a.png)

I figure we may need additional options under the 'When to repeat [...]' question to cover all requirements.

Thoughts?

**Comment by jbrooksuk** [comment]
@DivineOmega I like it! My one thought about it is that we should probably implement it within the existing **Scheduled Maintenance** form as it'd be essentially the same stuff happening anyway.

**Comment by TheoBearman** [comment]
^ agreed.

**Comment by divious1** [comment]
Team did this feature ever made it to v2, we also have a requirement to schedule maintenance for multiple days. Currently implementation I believe is limited to 1 day. Thank you for everything.

**Comment by gpilla** [comment]
+1

**Comment by jbrooksuk** [comment]
Merged into https://github.com/CachetHQ/Cachet/issues/1176

**Comment by bjshively** [comment]
+1 to this. Several of our teams have standard maintenance windows that would be great to configure. Should be similar to creating a Recurring event in Google Calendar, ideally.
