### ISSUE TITLE
Image 7d45c793165e gives 500 errors

### ISSUE THREAD

**Issue by Galexrt** [cachethq/Cachet#676]
Hi,
A week ago I installed Cachet on my server using the docker image.
Everything was working fine, until I "updated" the image.
I repulled the "cachethq/cachet:latest" image and after that I get 500 errors when accessing "/", "/dashboard", "/dashboard/components/groups", component editing and adding to a group works.

I copied the logs from nginx and php-fpm out of the container but no errors/exceptions were shown in the logs. The only "error" was that the "access.log" was showing the 500 responses to my ip.

I use Swarm to deploy my containers, but on my local dev machine I get the 500 error too.
Both systems use Debian 8 (testing).

Docker Version:
```
Client version: 1.6.2
Client API version: 1.18
Go version (client): go1.4.2
Git commit (client): 7c8fca2
OS/Arch (client): linux/amd64
Server version: swarm/0.2.0
Go version (server): go1.3.3
Git commit (server): 48fd993
OS/Arch (server): linux/amd64
```
If you need anymore info, please let me know.

Greetings
Alexander

**Comment by daxingplay** [comment]
I met the same problem. My docker version is:

```
Client version: 1.6.0
Client API version: 1.18
Go version (client): go1.4.2
Git commit (client): 4749651
OS/Arch (client): linux/amd64
Server version: 1.6.0
Server API version: 1.18
Go version (server): go1.4.2
Git commit (server): 4749651
OS/Arch (server): linux/amd64
```

My host is Ubuntu Server 14.04 LTS

**Comment by ervansetiawan** [comment]
I am also getting 500 error using the latest Docker image

**Comment by jbrooksuk** [comment]
Pinging @sammcj

**Comment by jbrooksuk** [comment]
Can you try all of this again please?

**Comment by jbrooksuk** [comment]
I think you just need to set the database settings and you'll be fine as it seems the Docker image isn't doing this by default.
