### ISSUE TITLE
Migrate from ac4a5c926d26878fa6ee6cf0c22fee5297a1634b to current

### ISSUE THREAD

**Issue by bbcorp** [cachethq/Cachet#679]
Hey there,
I had Cachet commit ac4a5c926d26878fa6ee6cf0c22fee5297a1634b (from 8 March) and now I want to upgrade to current commit.
When I do **php artisan migrate** I have this error :
*PHP Warning:  require(/var/www/Cachet/src/helpers.php): failed to open stream: No such file or directory in /var/www/Cachet/vendor/composer/autoload_real.php on line 58
PHP Fatal error:  require(): Failed opening required '/var/www/Cachet/src/helpers.php' (include_path='/var/www/Cachet/vendor/phpseclib/phpseclib/phpseclib:.:/usr/share/php:/usr/share/pear') in /var/www/Cachet/vendor/composer/autoload_real.php on line 58*

Thanks in advance

**Comment by jbrooksuk** [comment]
You need to run `composer install`. Follow these instructions :) https://docs.cachethq.io/v1.0/docs/upgrading-from-laravel-4
