### ISSUE TITLE
Upgrade To Elixir 2.x

### ISSUE THREAD

**Issue by GrahamCampbell** [cachethq/Cachet#683]
We're still on Elixir 0.x.

**Comment by jbrooksuk** [comment]
We did have some issues the other day once we upgraded Elixir. I'll sort them.

**Comment by GrahamCampbell** [comment]
Yeh, the same is true for StyleCI.

**Comment by jbrooksuk** [comment]
Let's not do this for V1, we'll be redesigning in V2 and make sure Elixir works with it.

**Comment by jbrooksuk** [comment]
Closed by 28110f5c8e77733cd24ed5a1426b8f0fc178d010

**Comment by GrahamCampbell** [comment]
:)
