### ISSUE TITLE
Metrics are not working

### ISSUE THREAD

**Issue by ecentinela** [cachethq/Cachet#684]
Every time I open the form to update a metric, the "calculation of metrics" is set to the "sum" value and the graph is not been shown correctly for the "average" mode. All the points are in "0" in the graph, regardless the real value I have in the database (1.080, 0.880, 0.920, etc).

**Comment by jbrooksuk** [comment]
Are you on MySQL or PgSQL, or something else?

**Comment by jbrooksuk** [comment]
Our demo (which is MySQL) is correctly storing the metric calculation value when I switch between sum and average, likewise the average is being correctly calculated.

**Comment by ecentinela** [comment]
Mysql

**Comment by ecentinela** [comment]
And my code is in sync with master. Which version is using the demo?

**Comment by jbrooksuk** [comment]
Both the demo and our status page are automatically kept up to date :)

I have a few more questions for you:

- What version of MySQL do you use?
- What version of PHP are you using?

**Comment by ecentinela** [comment]
The last stable version in both in an Ubuntu 14.04 with nginx.

**Comment by GrahamCampbell** [comment]
> The last stable version in both in an Ubuntu 14.04 with nginx.

That's not too helpful. Could you post the actual versions please?

**Comment by ecentinela** [comment]
MySQL 5.5 & php 5.5.25

**Comment by jbrooksuk** [comment]
You've ran all of the latest migrations too?

**Comment by ecentinela** [comment]
"Nothing to migrate".

This is a complete dump from my database http://expirebox.com/download/ecabc4e4820887f70567abac00e1dd23.html

**Comment by ecentinela** [comment]
Do you need some other info to address this issue?

**Comment by ecentinela** [comment]
@jbrooksuk any news about this?

**Comment by jbrooksuk** [comment]
I'm going to look into this tonight :+1: it's weird because our metrics, both in the demo and our own status page are working as expected.

**Comment by jbrooksuk** [comment]
@ecentinela I did look at this, I just forgot to update the issue. I've genuinely no idea what's happening here. Maybe @joecohens can shed some light?

**Comment by ecentinela** [comment]
@jbrooksuk thank you. I don't have idea what this could be. If you need some other information that can help to debug this, please let me know. In the meantime I'm updating the project from time to time praying to be solved magically :)

**Comment by jbrooksuk** [comment]
Out of interest, are you able to upgrade to PHP 5.6?

**Comment by jbrooksuk** [comment]
This is such a strange issue as:

1. Both our own status and demo pages work fine with metrics.
2. Our local instances also work.
3. Metrics are staying updating in MySQL, PostgreSQL and SQLite.

I'm convinced this is an installation issue. Are you getting anything in the logs? Can you completely re-install Cachet?

**Comment by ecentinela** [comment]
Sorry, I cannot upgrade to 5.6 in our production servers.

Have you used the database dump I posted some days ago? It works for you?

**Comment by jbrooksuk** [comment]
Yeah, I'm pretty sure everything worked. Can you upload again so I can run against the latest version?

**Comment by jbrooksuk** [comment]
I've been unable to replicate this issue altogether @ecentinela.

I'm going to close this as I can only come to the conclusion that it's an environment issue. Can you setup a new Cachet instance and see if that helps please.
