### ISSUE TITLE
No newlines in incident

### ISSUE THREAD

**Issue by dennusb** [cachethq/Cachet#685]
Hi,

If you create an incident it would be nice to show newlines on the status page, so that you can enter more details or even update's. Now everything is showed on 1 line! :(

**Comment by dennusb** [comment]
More info : In the "create incident" screen you CAN insert newlines by using enter, and when you edit an incident you still see the newlines. So they are saved, but only not displayed on the status page.

**Comment by GrahamCampbell** [comment]
Right, that's because your browser doesn't render newline characters as newline characters. Could be fixed by us using `nl2br`.

**Comment by jbrooksuk** [comment]
@dennusb do you mean that when you just press enter once, it renders on one line? 
![image](https://cloud.githubusercontent.com/assets/246103/7914214/84f22e9e-086d-11e5-9630-16b6cd5ddd14.png)

**Comment by jbrooksuk** [comment]
Because that's correct. This is common Markdown behaviour.

**Comment by GrahamCampbell** [comment]
> This is common Markdown behaviour.

Normally **2** newline characters will give the behaviour you want?

**Comment by jbrooksuk** [comment]
Exactly. My screen shot above should actually be written as:

```
This

Is

Foo

Bar
```

**Comment by dennusb** [comment]
@jbrooksuk The problem is that when i created an incident :
"Test
2
3
"

And on the status page is shows as :
"Test 2 3"

**Comment by jbrooksuk** [comment]
Yeah, that's exactly what should happen, because that's how Markdown deals with single lines. If you want a single line break, then end your line with `<br>` and you'll have one line and not two :)
