### ISSUE TITLE
Dynamic favicon

### ISSUE THREAD

**Issue by njetten** [cachethq/Cachet#686]
Hi,

I thought it would be a nice feature if the favicon would dynamically change from the green checkbox to a yellow/red exclamation mark as soon as an incident was created

**Comment by TheoBearman** [comment]
+1.

**Comment by ApfelUser** [comment]
+1

**Comment by jbrooksuk** [comment]
Personally, I'd prefer this over #327 as it provides better usage.

**Comment by svenmueller** [comment]
+1

**Comment by jbrooksuk** [comment]
Closed by 54011d76356ef3ceca19c08799d32af141982ee7

**Comment by jbrooksuk** [comment]
Thanks @DivineOmega!

**Comment by svenmueller** [comment]
cool! :rocket:

**Comment by DivineOmega** [comment]
Great! :+1:
