### ISSUE TITLE
API version endpoint

### ISSUE THREAD

**Issue by clarkeash** [cachethq/Cachet#687]
Would is be possible to have an end point that will give the version of the api, as if an app is consuming the api, we can know if a feature that you added in a particular version is supported.

**Comment by jbrooksuk** [comment]
What do you mean by this, sorry?

Our API is now versioned, so you now have to do `http://demo.cachethq.io/api/v1/ENDPOINT`

**Comment by clarkeash** [comment]
I have an app that uses the api that users can log into (domain, email etc)

Lets imagine John's API is on v1, and Jane's is on v2

I need to be able to limit what features are shown to them based on the api version.
If you add a new feature in v2 then, I dont want that feature to be shown to John as he wont be able to use it, but I do want to show it to Jane.

Does that clear things up?

**Comment by clarkeash** [comment]
Or the version could be returned during the authentication etc.

**Comment by jbrooksuk** [comment]
The API version is within the URL now though? Or are you referring to something else?

**Comment by clarkeash** [comment]
Yeah, we are not quite on the same page, I am struggling with how to explain this clearly.

**Comment by clarkeash** [comment]
I can't see any APIs in production that do what I am asking so it must be me missing something.

**Comment by jbrooksuk** [comment]
I'm really sorry @clarkeash, but I've no idea what you mean :laughing: 

Let's try clear this up:

1. What do you mean by John and Jane having different API's?
2. What is their API pointing to?
3. What is Cachet supposed to be doing here?

**Comment by clarkeash** [comment]
So John has cachet installed at http://example.org and Jane has hers installed at http://domain.com.

In the future, you release v2 of cachet (with new features) and add the v2 endpoint to the cachet API.

John doesn't upgrade and stays on v1, but Jane upgrades and has the v2 endpoint on her domain.

When they try and use the app I am creating (they both use the same app from the app store), they login with their domain for cachet as well as their usernames and passwords)

Now the app knows that in v2 you added "some awesome feature", and now this is where the issue is..... if when John (who is on v1) tries to use this feature it won't work as cachet on his domain doesn't know about this feature, but when Jane wants to use it she can because she is up to date on v2.

This is why I think being able to know what version they are using would be beneficial, so that "my app" could only show features to users where their installation of cachet would support it.

**Comment by jbrooksuk** [comment]
:zap: I get you!

I think the easiest way to determine this is to ping each versioned endpoint, to determine if a feature is there. We could add a `/api/v1/ping` endpoint which will return something so you know what version they're on?

**Comment by clarkeash** [comment]
woohoo! :smile: 

That would be a good approach.

Thanks for bearing with me :P

**Comment by jbrooksuk** [comment]
Done :)

**Comment by clarkeash** [comment]
wow! that was fast thanks :)

**Comment by jbrooksuk** [comment]
https://docs.cachethq.io/v1.0/docs/ping :)
