### ISSUE TITLE
Drop user_id column from components and incidents

### ISSUE THREAD

**Issue by jbrooksuk** [cachethq/Cachet#688]
Do we even need them?

**Comment by jbrooksuk** [comment]
CC @cachethq/owners?

**Comment by GrahamCampbell** [comment]
Hmmm, I guess we don't need them.

**Comment by jbrooksuk** [comment]
I think my plan was to show who logged the incident, but that's not really important in V1. Removing.

**Comment by joecohens** [comment]
:+1:
