### ISSUE TITLE
Error after upgrading

### ISSUE THREAD

**Issue by dennusb** [cachethq/Cachet#694]
Hi,

I've just pulled the latest version with the subscriber thingy, but when i want to run an upgrade :
php composer.phar update
PHP Fatal error:  Class 'Illuminate\Broadcasting\BroadcastServiceProvider' not found in /var/www/Cachet/vendor/laravel/framework/src/Illuminate/Foundation/ProviderRepository.php on line 150

  [Symfony\Component\Debug\Exception\FatalErrorException]
  Class 'Illuminate\Broadcasting\BroadcastServiceProvider' not found

Script php artisan clear-compiled handling the pre-update-cmd event returned with an error

  [RuntimeException]
  Error Output: PHP Fatal error:  Class 'Illuminate\Broadcasting\BroadcastServiceProvider' not found in /var/www/Cachet/vendor/laravel/framework/src/Ill
  uminate/Foundation/ProviderRepository.php on line 150

update [--prefer-source] [--prefer-dist] [--dry-run] [--dev] [--no-dev] [--lock] [--no-plugins] [--no-custom-installers] [--no-autoloader] [--no-scripts] [--no-progress] [--with-dependencies] [-v|vv|vvv|--verbose] [-o|--optimize-autoloader] [--ignore-platform-reqs] [--prefer-stable] [--prefer-lowest] [packages1] ... [packagesN]

Bug? Or am i doing something wrong?

**Comment by GrahamCampbell** [comment]
Never run `composer update`.

**Comment by jbrooksuk** [comment]
Ah yes, you should be running `composer install --no-dev -o`.

**Comment by GrahamCampbell** [comment]
You need to run `composer install --no-dev --no-scripts`, then `composer install --no-dev -o`.

**Comment by GrahamCampbell** [comment]
The no scripts bit is important. It'll fix the crashing. :)

**Comment by jbrooksuk** [comment]
Removed my comment so that it's not so confusing :+1:
