### ISSUE TITLE
Cannot send message without a sender address

### ISSUE THREAD

**Issue by dennusb** [cachethq/Cachet#695]
Hi,

I've updated to the subscriber version, subscribed myself and then ran the queue handler from Laravel, but it is echo'ing :
[Swift_TransportException]
  Cannot send message without a sender address

Is it a bug or is a setting missing from the docs?

**Comment by jbrooksuk** [comment]
Ping @cachethq/owners we never set the config for the address/name.

**Comment by GrahamCampbell** [comment]
We probably should do that. :)

**Comment by dennusb** [comment]
Hehe, that would be cool :)

**Comment by jbrooksuk** [comment]
@dennusb pull down the latest `master` and add two environment keys: `MAIL_ADDRESS` and `MAIL_FROM` :)

**Comment by jbrooksuk** [comment]
@joecohens I think we also need a check to disable subscribers if it's not configured properly.

**Comment by dennusb** [comment]
@jbrooksuk Thanks. That is working. Fixed very very fast, awesome :)

**Comment by jbrooksuk** [comment]
:)

**Comment by joecohens** [comment]
@jbrooksuk Totally that would be cool :)
