### ISSUE TITLE
Error After Inputting Email Into Subscribe Section

### ISSUE THREAD

**Issue by TheoBearman** [cachethq/Cachet#698]
I have got this error after putting in an email address and then submitting it on the Subscribe section of my site:

![error](https://cloud.githubusercontent.com/assets/6546590/8089917/c9d7c6f4-0fa2-11e5-8d54-081ecc8f39cd.JPG)

I have run `php artisan migrate` and `composer update` since pulling the latest commits.

**Comment by jbrooksuk** [comment]
You need to check our documentation for the new environment settings. Uhttps://docs.cachethq.io/v1.0/docs/subscribers

**Comment by TheoBearman** [comment]
@jbrooksuk I can't see anything...

**Comment by jbrooksuk** [comment]
Sorry @TheoBearman CloudFlare breaks Readme.io

http://cachet.readme.io/v1.0/docs/subscribers

**Comment by TheoBearman** [comment]
@jbrooksuk I cannot see the **Allow people to signup to email notifications?** option in my Application Setup page.

**Comment by jbrooksuk** [comment]
You may need to pull down again, I had to add the feature.

**Comment by TheoBearman** [comment]
@jbrooksuk Now I've lost the subscribe button!

**Comment by jbrooksuk** [comment]
That's because you need to enable the setting and then set both `MAIL_NAME` and `MAIL_ADDRESS`. We needed a way to turn the setting off (and it's off by default).

**Comment by TheoBearman** [comment]
I have done, my ENV file is:

`APP_ENV=local
APP_DEBUG=true
APP_KEY=SomeRandomString

DB_DRIVER=mysql
DB_HOST=localhost
DB_DATABASE=cachet
DB_USERNAME=cachet
DB_PASSWORD=secret

CACHE_DRIVER=apc
SESSION_DRIVER=file
QUEUE_DRIVER=sync

MAIL_DRIVER=smtp
MAIL_HOST=smtp.zoho.com
MAIL_PORT=587
MAIL_USERNAME=status@theobearman.com
MAIL_PASSWORD=**INTENTIONALLY HIDDEN**
MAIL_ADDRESS=status@theobearman.com
MAIL_FROM=TheoBearman.com Status`

**Comment by jbrooksuk** [comment]
And you went into the dashboard and enabled the setting too?

**Comment by TheoBearman** [comment]
@jbrooksuk. Yep, just checked again now.

**Comment by jbrooksuk** [comment]
Ah, `MAIL_FROM` needs to be `MAIL_NAME`.

**Comment by TheoBearman** [comment]
@jbrooksuk You need to update the Docs then ;)

**Comment by jbrooksuk** [comment]
Good shout, my apologies :)

**Comment by TheoBearman** [comment]
You're forgiven!

**Comment by jbrooksuk** [comment]
https://docs.cachethq.io/v1.0/docs/subscribers

**Comment by TheoBearman** [comment]
@jbrooksuk Fantastic. Just did a test incident and it works a charm. Thanks as always!

**Comment by jbrooksuk** [comment]
:tada:
