### ISSUE TITLE
PHP page after installtion

### ISSUE THREAD

**Issue by Vialaxy** [cachethq/Cachet#703]
Hello,

As a  linux's neophyte user i tried to follow some tutorials to installl CachetHQ:
Your documentation -> not enough complete for a neophyte like  me
https://www.rosehosting.com/blog/install-cachethq-on-debian-7-vps/ -> doesn't work
http://trevormanternach.com/2015/03/24/installing-cachet/ -> This is the one i currently use

With the one i use after following all the steps i always come to a weird php page after the installation:
![6456d5e43f5030174a6d3f3f315f1351](https://cloud.githubusercontent.com/assets/12834975/8103516/658434a8-1029-11e5-932f-506dd9aa64ca.png)

Hope you'll be able to help me :)

Kind regards,
Vialaxy

**Comment by jbrooksuk** [comment]
Looks like you don't have PHP installed with the Apache modules. If that's the case, you'll also need to enable the `rewrite` module with `a2enmod rewrite` as it'll likely be disabled.

**Comment by Vialaxy** [comment]
PHP already installled and rewrite already enalbled too :/

I've exactly follow this tutorial : http://trevormanternach.com/2015/03/24/installing-cachet/

Just added the .env config before the php artison migrate  as you state it in your documentation

**Comment by jbrooksuk** [comment]
1. Do you get any errors when running migrate?
2. Have you setup the `DocumentIndex` to include PHP?

This is an environment issue rather than Cachet, so I'm closing the issue, but will continue to help.
