### ISSUE TITLE
Only allow logins from specific IP ranges

### ISSUE THREAD

**Issue by spencerryan** [cachethq/Cachet#704]
This is a feature enhancement request.

We want the ability to have our status page available publicly, but only allow login to the dashboard from IP ranges we specify.

**Comment by jbrooksuk** [comment]
This is something that you can probably setup from within your Apache/nginx config. Only allow access to certain routes from an IP range.

- [Apache](http://www.cyberciti.biz/faq/apache-restrict-access-based-on-ip-address-to-selected-directories/) (this may be incorrect)
- [Nginx](http://serverfault.com/questions/611311/restricting-multiple-directories-to-same-ip-ranges)
