### ISSUE TITLE
Empty RSS and Atom feeds

### ISSUE THREAD

**Issue by ldidry** [cachethq/Cachet#706]
Disclaimer: our cachet is available on <https://status.framasoft.org>, and I patched our cachet in order to have items in rss (<https://status.framasoft.org/rss>) and atom (<https://status.framasoft.org/atom>) feeds, so our feeds works.

When asking for the rss or atom feed on our cachet, we got no items in it. The problem is in `app/Http/Controllers/RssController.php` and `app/Http/Controllers/AtomController.php`, line 37:

```php
        if ($group) {
```

Indeed, `if ($group) {` is always true, even if the ComponentGroup `$group` is a null one. In other words, `$group` is not null, it's a ComponentGroup with null values.

Instead of that condition, you should use

```php
        if ($group->exists) {
```

**Comment by jbrooksuk** [comment]
- https://status.framasoft.org/rss
- https://status.framasoft.org/atom

They're both working?

**Comment by jbrooksuk** [comment]
We'd accept a PR to fix this too :)

**Comment by ldidry** [comment]
As I said:
>  I patched our cachet in order to have items in rss

I patched it with `if ($group->exists) {`.

Since I have an other problem on the RSS feed (no langage and html encoding issue: <https://validator.w3.org/feed/check.cgi?url=https%3A%2F%2Fstatus.framasoft.org%2Frss>), I can unpatch the RSS feed so you can see it not working.

**Comment by jbrooksuk** [comment]
It's ok, I re-read your issue.
