### ISSUE TITLE
Accent in incident title makes RSS feed unvalid

### ISSUE THREAD

**Issue by ldidry** [cachethq/Cachet#708]
This is the fault of roumen/feed library, so I created a [pull-request](https://github.com/RoumenDamianoff/laravel-feed/pull/29) for it.

Could you please update the version of this library in `composer.lock` as soon as possible after a release with my PR included ? Thanks.

**Comment by jbrooksuk** [comment]
Ping me when it's merged and I'll be on it.

**Comment by ldidry** [comment]
Ok :+1:

**Comment by ldidry** [comment]
It's merged and released in 2.9.3.
