### ISSUE TITLE
Unable to Add Scheduled Maintenance

### ISSUE THREAD

**Issue by x0SiN0x** [cachethq/Cachet#710]
after installing (fresh install) the latest Cachet release I am unable to create a scheduled maintenance.  After filling out the form and clicking "Add" im presented with a screen that simply says "The visible field is required." followed by "Whoops. - Something went wrong adding the schedule.".  At this point the form is still populated except for the date/time.  Nothing being logged to the apache logs nor the internal laravel log.

![image](https://cloud.githubusercontent.com/assets/6784214/8137464/d66e0112-1100-11e5-9a73-451740b75ed7.png)

**Comment by GrahamCampbell** [comment]
Also a bug that the "Whoops" thing is green isn't it @jbrooksuk?

**Comment by rtrauntvein** [comment]
Confirming this issue (running via docker)

**Comment by jbrooksuk** [comment]
Sorry guys, looks like I missed a field out!

@GrahamCampbell yeah, also an issue :P
