### ISSUE TITLE
Make .bottom-menu-sidebar disappear on small devices

### ISSUE THREAD

**Issue by ldidry** [cachethq/Cachet#712]
`.bottom-menu-sidebar` is hidden on tablets, but not on smartphones. This is annoying since it make it hard to hit the "save" buttons.

I see what I should do to hide it on smartphones, but I was wondering if I need to compile sass files myself and add it to my commit (seems to be no since `public/dist` is in the `.gitignore`) or if it was compiled by some continuous integration robot.

Once I know, I'll do a PR.

**Comment by jbrooksuk** [comment]
We use `public/build` rather than `dist`. If you can compile the SCSS files (just run `gulp`) then we merge in both the source and compiled files.

**Comment by ldidry** [comment]
Sorry, I've mistaken build and dist, in the issue, but not in my branch. I suppose I have to delete the old compiled css?

**Comment by jbrooksuk** [comment]
Sometimes it's easier to, yeah.
