### ISSUE TITLE
Automatic Update to Component Status When Issue is Set to Fixed

### ISSUE THREAD

**Issue by TheoBearman** [cachethq/Cachet#721]
Can we have a feature so that when an incident is set to `Fixed` that the component status is automatically set to `Operational`.

**Comment by jbrooksuk** [comment]
You can change the component status through the dashboard whilst you're adding a new "incident".

![image](https://cloud.githubusercontent.com/assets/246103/8157311/c02e5eae-134b-11e5-8503-2aadc6da2fb0.png)

**Comment by TheoBearman** [comment]
I know, I'm talking about when I'm editing an incident to show it is fixed. For example:

![djs](https://cloud.githubusercontent.com/assets/6546590/8157982/db6afe52-1350-11e5-8f20-ed19729a1a73.PNG)

**Comment by jbrooksuk** [comment]
Ah I see, you're using Cachet differently to how it's intended (which goes back to #715 - I can't wait to redo everything!).

**Comment by TheoBearman** [comment]
@jbrooksuk I can't wait for you to as well. Please hurry!
