### ISSUE TITLE
Ability to Change Login Page Image

### ISSUE THREAD

**Issue by TheoBearman** [cachethq/Cachet#729]
As above. Especially important if there is a banner image set.

**Comment by jbrooksuk** [comment]
Personally, I wouldn't class this as important.

We brand your homepage with a supplied logo, we optionally allow you to support Cachet on your status page, so it's nice to retain some of our "Cachet" brand, given that the logo is shown on a private page. Wordpress do the same thing.

**Comment by TheoBearman** [comment]
Fair point. Disregard this then.

**Comment by jbrooksuk** [comment]
Thanks for the suggestion though, keep them coming!
