### ISSUE TITLE
Docker APP_KEY setting

### ISSUE THREAD

**Issue by rtrauntvein** [cachethq/Cachet#732]
It doesn't look like [this line](https://github.com/cachethq/Cachet/blob/master/Dockerfile#L27) in the Dockerfile is working as intended.  Nothing is being replaced it looks like.

Would we be able to just pass in an environment variable such as `-e APP_KEY=<key>` when running the container instead of hard coding this?

```
Step 5 : RUN sed -i "s/'key' => '\w.*/'key' => 'f20d3e5ae02125a94bd60203a4edfbde',/" config/app.php &&     grep key config/app.php
 ---> Running in 2bbff0e3eb37
    | This key is used by the Illuminate encrypter service and should be set
    'key' => env('APP_KEY', 'SomeRandomString'),
```

**Comment by jbrooksuk** [comment]
We could alternatively just run `php artisan key:generate`?

**Comment by rtrauntvein** [comment]
That may work.. Where does that key get stored if we do the `php artisan key:generate`? 

Sorry I am new to laravel, not really sure how all of the pieces fit together yet :)

**Comment by jbrooksuk** [comment]
The key is stored in `.env` :)

**Comment by rtrauntvein** [comment]
There does not seem to be a `.env` in the Dockerized version that I can find.

**Comment by GrahamCampbell** [comment]
@rtrauntvein It's called .env.example. It's renamed on install to .env.

**Comment by rtrauntvein** [comment]
Hmm, that doesn't seem to be the case when running via docker.  I have no file named `.env` inside of my running container (page is functional though). Maybe it was created during the initial setup, but once the container was redeployed it goes away, as there is no volume to persist that file.

I am passing in the DB credentials via docker ENV variables currently.  I guess my question is: Can one pass in all of the possible attributes from `.env.example` as docker ENV variables instead?

**Comment by jbrooksuk** [comment]
Looks like it's been missed off.

**Comment by rtrauntvein** [comment]
The database env variables via `docker run -e` seem to be fine without the `.env` file in place. 

If possible it would be nice to just set them all via ENV vars with `docker -e`

**Comment by jbrooksuk** [comment]
Is this something that you can do @rtrauntvein?

**Comment by rtrauntvein** [comment]
I can take a stab at it, hopefully should have some time next week.  There are some other Dockerfile optimizations I have in mind also.  Wanted to wait for the 1.0 release to settle a bit first though.

**Comment by jbrooksuk** [comment]
Awesome, thank you! :)

**Comment by rtrauntvein** [comment]
Was at dockercon this week, just catching up on some work issues then hope to get back into this ;)

**Comment by jbrooksuk** [comment]
That's handy! :laughing:
