### ISSUE TITLE
Subscribe to specific components

### ISSUE THREAD

**Issue by dennusb** [CachetHQ/Cachet#734]
I have some cool ideas for V2 :

- Might be cool to subscribe to specific components only for some users
- Multiple client dashboards (separated)?

If this is not the place for ideas, please let me know haha!

**Comment by jbrooksuk** [comment]
Ideas are most certainly welcome :smile: 

1. Yeah, this is something we'll definitely be doing. It's important as some people may only be concerned with the API, whilst others may need to only watch the payment platform or whatever it may be.
2. Does #236 cover this?

**Comment by dennusb** [comment]
Cool! :)

Yeah, 2 is covered by #236 i think!

**Comment by jasonwilk** [comment]
+1 for component specific subscriptions

**Comment by keizer-soze1** [comment]
Any updates as to when this feature would be added? It says milestone 3.0.0? Is that expected in the next few months? We currently support a ton of internal and external sites for development and Qa testing as well as production and not having to manage individual sites per application would be great. Having one centralized status server with the ability to subscribe to components or component groups is a huge advantage.

**Comment by jbrooksuk** [comment]
It's definitely within the next few months. V2 will be arriving VERY soon. We've had to push it back a little bit due to life and bugs etc.

**Comment by jbrooksuk** [comment]
This will be coming in the next release.

**Comment by joecohens** [comment]
Almost ready ;)
