### ISSUE TITLE
No e-mail send when creating incident?

### ISSUE THREAD

**Issue by dennusb** [cachethq/Cachet#737]
Hi,

We are using the subscriber thingy, and when someone is subscribing the receive the e-mails as should. But when i create an incident and check the "Notify subscribers" box, nobody receives an e-mail... bug?

**Comment by GrahamCampbell** [comment]
Is your email config setup correctly?

**Comment by TheoBearman** [comment]
Have you added the environment variables as suggested [here](https://docs.cachethq.io/v1.0/docs/subscribers)?

**Comment by dennusb** [comment]
Yep, because e-mail when subscribing is working fine! It seems that nothing is added to the jobs table in the database

**Comment by dennusb** [comment]
If the SMTP wasn't fine the "confirm" mail would not work also, right?

**Comment by TheoBearman** [comment]
Paste the contents of your .env file?

**Comment by dennusb** [comment]
CACHE_DRIVER=apc
SESSION_DRIVER=apc
QUEUE_DRIVER=database

MAIL_DRIVER=smtp
MAIL_HOST=relay.domain.nl
MAIL_PORT=25
MAIL_USERNAME=
MAIL_PASSWORD=
MAIL_ADDRESS=bla@domain.nl
MAIL_NAME=Operations

**Comment by dennusb** [comment]
Confirmed btw, if i create the incident the jobs table is still empty...

**Comment by TheoBearman** [comment]
So you haven't included.

```
MAIL_ADDRESS=support@cachethq.io
MAIL_NAME=Cachet HQ
```

**Comment by dennusb** [comment]
MAIL_ADDRESS=bla@domain.nl
MAIL_NAME=Operations

What is wrong with that?

**Comment by TheoBearman** [comment]
Sorry, didn't see that.

Have you run `composer update` and then `php artisan migrate`?

**Comment by dennusb** [comment]
No, didn't run composer update. Do i need to after pulling a new version?

**Comment by TheoBearman** [comment]
Not every time I don't think. But, try and it and then `php artisan migrate` and see what happens.

**Comment by dennusb** [comment]
Done. It downloaded some things. Let me try!

**Comment by jbrooksuk** [comment]
Don't run `composer update` unless you're developing Cachet. You'll end up with out of sync dependencies. Only run `composer install -o --no-dev --no-scripts` in production.

**Comment by dennusb** [comment]
Lol. Okay. But anyways, it's still not working. It's not adding anything into the job table. What to do?

**Comment by GrahamCampbell** [comment]
Whar queue driver do you have?

**Comment by dennusb** [comment]
database

**Comment by dennusb** [comment]
When subscribing i can see a new entry in the jobs table, when creating an incident i see nothing in the database. So i still think it's a bug somewhere... because it worked before with the exact same config!

**Comment by dennusb** [comment]
It IS working when creating scheduled maintenance, so it really sounds like a bug to me.

**Comment by jbrooksuk** [comment]
Assigned to @joecohens for tonight so we can ship tomorrow :)

**Comment by dennusb** [comment]
Thanks!

**Comment by jbrooksuk** [comment]
Pull down and try again?

**Comment by jbrooksuk** [comment]
It's working for me :)
