### ISSUE TITLE
Weird e-mail template

### ISSUE THREAD

**Issue by dennusb** [cachethq/Cachet#739]
When i schedule maintenance subscribers receive an e-mail with this as the first 2 lines : 
"New maintenance has been scheduled on *Name of system*.

Thank you, *Name of system*

*Maintenance details*"

What is that "Thank you" doing there?

**Comment by jbrooksuk** [comment]
It's courteous? :)

**Comment by dennusb** [comment]
Yeah, but the thank you needs to be at the end of the e-mail, not before the maintenance details. Right? :P
