### ISSUE TITLE
Error when moving to new server

### ISSUE THREAD

**Issue by dennusb** [cachethq/Cachet#740]
Hi,

I tried to move Cachet to a new virtual, Ubuntu 14.04 LTS with Apache2, PHP5 and Mysql-server, cloned the source, editted the .env, imported the database from the old machine but now i'm getting :

No supported encrypter found. The cipher and / or key length are invalid.

What to do?

**Comment by jbrooksuk** [comment]
@GrahamCampbell what's the deal with the cipher stuff?

**Comment by override-chaos** [comment]
You need to have a 32 character length string for ```APP_KEY= ```.

**Comment by dennusb** [comment]
Then why is it working on the old server...? The .env file is exactly the same.

**Comment by jbrooksuk** [comment]
It could be down to your old server having mcrypt?

**Comment by dennusb** [comment]
Ah, yeah.. it seemed to be a missing mcrypt add-on.

**Comment by jbrooksuk** [comment]
The thing is, you should no longer need it...

**Comment by dennusb** [comment]
But if i remove it, generate a key with artisan (which automatically puts it in the .env file) it still does not work.

**Comment by jbrooksuk** [comment]
@GrahamCampbell any idea on this cipher stuff? I thought that mcrypt was no longer needed.

**Comment by TheoBearman** [comment]
I don't know if [this](https://status.theobearman.com/dashboard) is linked but Huston, we have a problem.

**Comment by dennusb** [comment]
What should we see? I only get a 401 :P Or is that the problem?

**Comment by jbrooksuk** [comment]
@GrahamCampbell what broke?

**Comment by TheoBearman** [comment]
@dennusb That is the problem! This is after pulling the latest master.

**Comment by rtrauntvein** [comment]
@TheoBearman I think it may be a new issue. @jbrooksuk maybe something introduced in #738 ? My Dashboard is giving a 401 now also running latest master.

**Comment by TheoBearman** [comment]
@rtrauntvein Could well be. Better that we find this issues now so @jbrooksuk and @GrahamCampbell  can sort it out rather than these issues occurring after the v1 release tomorrow!

**Comment by jbrooksuk** [comment]
Ok, so by the HTTP spec, this is actually the correct behaviour. But as we've found out, this isn't the expected behaviour when you're not logged in.

@GrahamCampbell, @joecohens and I are discussing this now.

**Comment by TheoBearman** [comment]
#SecretSkypeMeetings

**Comment by jbrooksuk** [comment]
*Slack.

**Comment by GrahamCampbell** [comment]
I'll be pushing a commit shortly. You're going to love my solution, i hope...

**Comment by TheoBearman** [comment]
@GrahamCampbell I'm sure I will - it means I can go to sleep with no worries!

**Comment by jbrooksuk** [comment]
You can actually just do `/auth/login` and after you've logged in you'll be able to access the dashboard.

**Comment by GrahamCampbell** [comment]
https://github.com/cachethq/Cachet/pull/744

**Comment by jbrooksuk** [comment]
Closed by #744

**Comment by Mebus** [comment]
I get the same error. What needs to be done to fix this?

(Ubuntu Trusty)

**Comment by jbrooksuk** [comment]
@Mebus can you open a new ticket please. You'll need to include the version you're running too.
