### ISSUE TITLE
Display of Maintenances

### ISSUE THREAD

**Issue by mbo18** [cachethq/Cachet#754]
It would be nice to be able to choose when to display maintenances. Currently, all maintenances are displayed even those planned in 3 or 4 weeks/months.

So it would be nice to have a setting like:

Display maintenances : 
    - All 
    - At scheduled date and time
    - X minutes/days/months before scheduled date and time

Thanks!

**Comment by jbrooksuk** [comment]
Tagged to V2. We're going to redo scheduled maintenance. We'll also add a way to show/hide maintenance to the public too.

**Comment by prolix21** [comment]
Would also be nice to set the duration on both incidents and maintenance. Right now you can set date/time but can't relay how long the maintenance window is, or how long an incident lasted.

**Comment by jbrooksuk** [comment]
@prolix21 this is a very good point. Could you add another issue for this please.

**Comment by berlic** [comment]
In version 1.2 maintenance appears in event list on the date it was added, not on the date of event itself.
We scheduled the event two weeks in advance and today users need to scroll back in history to find today's maintenance event. A bit confusing...

**Comment by jbrooksuk** [comment]
@berlic could you add a separate issue for this? We'll release a bug fix on 1.2 for this later.

**Comment by berlic** [comment]
@jbrooksuk done. https://github.com/cachethq/Cachet/issues/934

**Comment by jbrooksuk** [comment]
Merged into https://github.com/cachethq/Cachet/issues/1176
