### ISSUE TITLE
Incident that last for more than one day

### ISSUE THREAD

**Issue by mbo18** [cachethq/Cachet#755]
For an incident that is not solved the same day it has been created, it is still displayed and "attached" to the day it has been created in the "Past incidents" timeline. So we can think that the incident is old and fixed.

It would be nice to be able to see easily incidents that are still ongoing. Maybe by displaying them like a scheduled maintenance? (in a specific panel below Components status?)
And then, when the incident status is changed to "fixed", move it from the "Ongoing incident panel" to the Past incidents timeline. I don't know if the incident should be duplicated to each day it last or not but we may need to see that it last for 2 days or more. 

Also, it would be nice to be able to display, in the Past Incidents section, only days with an event.

**Comment by jbrooksuk** [comment]
This is something we're addressing in V2. Since we have this within other issues, I'm going to close this one :)
