### ISSUE TITLE
feature: better incident search api

### ISSUE THREAD

**Issue by blaskovicz** [cachethq/Cachet#756]
Looking at the [api docs](https://docs.cachethq.io/v1.0/docs/get-incidents) and [the code](https://github.com/cachethq/Cachet/blob/master/app/Http/Controllers/Api/IncidentController.php#L33) for incidents, I can't seem to find a way to allow sorting incidents via `GET /api/v1/incidents` (they default to being sorted by id, ascending). Along with this, the incidents are paginated by `(total rows / num per page) = num pages`.

My use case is that I would like to be able to get the most recent incidents that I haven't yet processed with my poller (ie, those I haven't seen and need to post to our slack channel).

A few solutions:
* allow adding incident id range to the api for `/incidents` instead of page number. This would allow pagination by already seen ids.
* allow sorting incidents by `id DESC`. This would allow me to at least ask for the most recent incidents and work my way backwards.
* add configurable webhooks that allow my site to be triggered on new incident creation. This is the most flexible and would have a lot of benefit for other sites that want the data "in real time."

**Comment by DivineOmega** [comment]
Regarding the sorting, what do people think about URLs like the following?

```
/api/v1/incidents?sort=id&order=desc
```

**Comment by jbrooksuk** [comment]
@DivineOmega this is something @joecohens and I spoke about. Paging is easy to add too.

**Comment by jbrooksuk** [comment]
Actually, paging is already done. http://cachet.io.dev/api/v1/incidents?per_page=1&page=1

**Comment by jbrooksuk** [comment]
Actually, rather than `order` I'd call it `direction`.

**Comment by GrahamCampbell** [comment]
Out of bounds pages don't behave correctly.

**Comment by jbrooksuk** [comment]
What are you expecting?

**Comment by GrahamCampbell** [comment]
An error page.

**Comment by GrahamCampbell** [comment]
If i ask for page 99, and there are 2 pages, we should be returning 404 or something.

**Comment by blaskovicz** [comment]
Personally, I would not expect a `404` by just changing the query parameters.

I would expect a `404` on such things as missing restful resources (eg: `/incidents/1`).

**Comment by jbrooksuk** [comment]
I'm with @blaskovicz on this. Parameters are filtering, whereas the URI itself is a resource.

**Comment by GrahamCampbell** [comment]
Hmmm, we need to indicate the client made an error with an error response. Shame php doesn't have an out of bounds http exception. Maybe we need a 400 then?

**Comment by blaskovicz** [comment]
Could the "error" just that that the json body tells you that there are only 2 pages, and that your current slice of the data is empty (ie, the current thing that happens now)?

**Comment by GrahamCampbell** [comment]
Nah, we need an actual error. I'll prep a PR. I do agree 404 isn't the way to do though.

**Comment by chaseconey** [comment]
I believe people usually use just a regular status code 400 to denote a page out of bounds issue.

**Comment by DivineOmega** [comment]
My vote would be for a HTTP 400 in the header with a more detailed error present in the JSON response.

**Comment by jbrooksuk** [comment]
Closed by 1779ac40c9bad7977b04406e41b2203602891a32
