### ISSUE TITLE
Email subscription not visible

### ISSUE THREAD

**Issue by svenmueller** [cachethq/Cachet#761]
I enabled "Allow people to signup to email notifications?" in the settings view, but it's not showing up on the status page. Did i miss something?

**Comment by GrahamCampbell** [comment]
Have you cached the config? If so, you need to clear the cache - normally done by just caching it again.

**Comment by GrahamCampbell** [comment]
> in the settings view

Ahhh, missed that...

**Comment by svenmueller** [comment]
any idea how to solve that?

**Comment by jbrooksuk** [comment]
1. Enable the setting in the dashboard.
2. Set the `.env` settings for `MAIL_NAME` and `MAIL_ADDRESS`.
3. Clear the cache `php artisan config:clear`

Done :)

**Comment by svenmueller** [comment]
would be nice to have some info in the README ;) thx will try it out!

**Comment by jbrooksuk** [comment]
We do have documentation at https://docs.cachethq.io/v1.0/docs/subscribers :)

**Comment by svenmueller** [comment]
thx! i just tried tried it...even after setting all required env variables and clearing existing cache configuration (even after reboot) it's not visible (i'm running cachet in the docker container)

**Comment by jbrooksuk** [comment]
Is the Docker build up to date?

**Comment by jbrooksuk** [comment]
We don't do much with Docker, it's left to contributors.

**Comment by svenmueller** [comment]
I'm using the lastest available docker container. I enabled the function in the settings, cleared the cache, defined the required env variables. What else could be the reason for not showing up on the status page? Any idea?

**Comment by rtrauntvein** [comment]
Hi @svenmueller, are you setting those variables via the `docker run -e MAIL_NAME=Email` ?

I am still trying to determine the behavior of the ENV variables in the Docker container version. It seems like there is some dependency on the `.env` file existing per the Cachet design, but it is not present in the current iteration of the Dockerfile and resulting image.  (Some discussion on this in #732)

**Comment by svenmueller** [comment]
@rtrauntvein yes, i think this is the underlying cause (#732) the passed variable (via `-e`) are simply not used as expected

**Comment by rtrauntvein** [comment]
Ok that confirms my suspicions.  

We will need to figure out how the Database variables work currently for the Docker version, and if this can be extended to the other variables.

Otherwise there may be some re-working required to make the docker version actually use a `.env` within the container.

**Comment by jbrooksuk** [comment]
Is there any reason why Docker can't use the `.env` file?

**Comment by rtrauntvein** [comment]
It could use an `.env` file. 

It is a pretty common convention in the docker world to set environment variables dynamically at container runtime.  That way we don't statically create an external file then mount it into the container, or build it into the image. Then we can do cool things with orchestration tools like have different DB credentials or other `.env` settings based on your environment etc.

If the application can directly read and use the system ENV variables - like with php's `getenv()` or something it just makes it easy, and no additional work is needed to support this.

That being said, it is pretty simple to add an init script of sorts that can inject the provided variables into a file in the container such as `.env` - Just requires a little sed and bash voodoo ;)

**Comment by jbrooksuk** [comment]
Closed by https://github.com/cachethq/Cachet/pull/788

**Comment by rtrauntvein** [comment]
Confirming that I am now seeing the subscribe button running the new docker image.

**Comment by jbrooksuk** [comment]
:+1:
