### ISSUE TITLE
Indicate the time zone of the timestamps

### ISSUE THREAD

**Issue by nealmcb** [cachethq/Cachet#763]
Cachet has had support for configuring the time zone to be used since #281.

But I don't see how a user can reliably figure that time zone out.  The timestamps don't come with time zone designators. https://en.wikipedia.org/wiki/ISO_8601#Time_zone_designators

Of course in many cases the user can assume that the service is up-to-date, and thus that some of the graphs and api results will end with something close to the current time, providing strong hints of the time zone, but that is hard for clients to do and won't work for the API in general.

When space is at a premium, e.g. in graphs, it would help to have the time zone indicated somewhere else on the page, for human consumption.

**Comment by jbrooksuk** [comment]
@nealmcb how would you imagine this working?

**Comment by nealmcb** [comment]
The first time I saw a cachet web page, it was one with graphs, and the graphs had times specified, but no timezone shown, so I didn't really know if it was up-to-date, and since the zone was different than mine, it was confusing.

So I imagine the HTML having a clear timezone, showing a time zone designator.
And every place that time is shown, it should show the timezone also.

A simple approach would be to just display a fixed time-zone designator and stick to it.  Or at least somehow automatically make that information available to users.

It would be great if the zone was easily customizable by each user, and could be set by each user according to how they want to report times, and allow them to see the times in their preferred zone.
But again, just being clear about the time data being presented would go a long way.

**Comment by jbrooksuk** [comment]
Closed by 0194dbb634fd087ef3af21a9845ed2b98643fd1b, we now show the timezone in the footer.
