### ISSUE TITLE
[Feature Request]Telegram Notification

### ISSUE THREAD

**Issue by wfjsw** [cachethq/Cachet#766]
Telegram has recently released their [Very Simple Bot API](https://core.telegram.org/bots), so can we  notif user in this way (may be in 2.0) :smiley:

**Comment by wfjsw** [comment]
bad idea due to long polling

**Comment by borgogelli** [comment]
Please could you explain better why is a bad idea ?

**Comment by jbrooksuk** [comment]
Telegram notifications can come later, simply with https://github.com/laravel-notification-channels/telegram

**Comment by scysys** [comment]
I know its an old request. But an Telegram Integration would be great. So status messages can be posted on Telegram channels.
