### ISSUE TITLE
No url works, /setup throws a 404

### ISSUE THREAD

**Issue by melsom** [cachethq/Cachet#767]
Hi!

Tried upgrading our Cachet installation to not much of a success. It suddenly redirects us to /setup, which in turn throws a 404. Tried a fresh install based on the 1.0 docs, but we're still experiencing the same problem. 

Only thing that seems to work is /img, /dashboard etc does not work and throws a 404. Nothing in the error logs. 

When we tried a fresh install I did the following:
clone from repo, rename .env.example to .env and edit mysql settings, composer --no-dev -o and php artisan migrate.

**Comment by melsom** [comment]
Found the problem. This is embarrassing, mod_rewrite was not enabled. This must have changed from previous versions as my Apache config has not been changed and no modules have been disabled.

**Comment by jbrooksuk** [comment]
I'm glad you were able to figure it out :)
