### ISSUE TITLE
php artisan migrate fails

### ISSUE THREAD

**Issue by sr78ger** [cachethq/Cachet#768]
`php artisan migrate` fails with

>SQLSTATE[42000]: Syntax error or access violation: 1071 Specified key was too long; max key length is 1000 bytes (SQL: alter table `tags` add unique tags_name_slug_unique(`name`, `slug`))

MySQL version is 5.6.19

**Comment by sr78ger** [comment]
changing `database/migrations/2015_01_16_083825_CreateTagsTable.php`

```php
$table->string('name',150);
$table->string('slug',150);
```

solved it.

**Comment by GrahamCampbell** [comment]
150 is too low. What about `512`? Does it still work then?

**Comment by sr78ger** [comment]
The default is 255 chars and that caused the weird problem

**Comment by cenourinha** [comment]
That change solved my problem. Thank you!

**Comment by GrahamCampbell** [comment]
Ping @jbrooksuk.

**Comment by jbrooksuk** [comment]
Weird. PR?

**Comment by sr78ger** [comment]
This is because the table is created using MyISAM as the storage engine, not InnoDb

**Comment by jbrooksuk** [comment]
The database or the table?

**Comment by sr78ger** [comment]
`SHOW CREATE TABLE tags`
```sql
CREATE TABLE `tags` (
 `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
 `name` varchar(150) COLLATE utf8_unicode_ci NOT NULL,
 `slug` varchar(150) COLLATE utf8_unicode_ci NOT NULL,
 `created_at` timestamp NOT NULL DEFAULT '0000-00-00 00:00:00',
 `updated_at` timestamp NOT NULL DEFAULT '0000-00-00 00:00:00',
 PRIMARY KEY (`id`),
 UNIQUE KEY `tags_name_slug_unique` (`name`,`slug`)
) ENGINE=MyISAM AUTO_INCREMENT=3 DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci
```

with my modifications to `VARCHAR(150)`

`SHOW CREATE DATABASE cachet`

```sql
CREATE DATABASE `cachet` /*!40100 DEFAULT CHARACTER SET utf8 */
```

**Comment by jbrooksuk** [comment]
This is strange because my tables have been created using InnoDB.

**Comment by jbrooksuk** [comment]
We should probably recommend InnoDB on the installation guide...

**Comment by sr78ger** [comment]
What does `SHOW ENGINES;` tell you? My MySQL server has InnoDb and MyISAM support, but the MyISAM engine is the default engine.

**Comment by sr78ger** [comment]
```sql
SHOW VARIABLES LIKE 'storage_engine';
```

> MyISAM

**Comment by sr78ger** [comment]
You might solve it with `SET GLOBAL storage_engine='InnoDb';` before the migration, but the connecting user has to have the `SUPER` privilege

**Comment by sr78ger** [comment]
...or define the storage engine directly:

http://laravel.com/docs/4.2/schema#storage-engines

```php
Schema::create('users', function($table)
{
    $table->engine = 'InnoDB';

    $table->string('email');
});
```

**Comment by jbrooksuk** [comment]
I'll accept a PR to set the engine :)
