### ISSUE TITLE
How to change 

### ISSUE THREAD

**Issue by cenourinha** [cachethq/Cachet#770]
Hi there,

I'm trying to install it on a cPanel based server. We have a /home/username/public_html/ dir. How can i install it there? It seems that the script is only prepared to be instaled in a "public/" folder.

**Comment by jbrooksuk** [comment]
Clone/copy Cachet into `/home/username/public_html/cachet` then setup a host that points to `/home/username/public_html/cachet/public` I believe.

@jenolan has experience with Cachet and cPanel, are you able to confirm?

**Comment by cenourinha** [comment]
In cPanel we are not supposed to change the "root directory" for a website. I understand this is not a bug, but would probably help most of the ones who are trying to install Cachet in a shared environment.

**Comment by jbrooksuk** [comment]
I believe that @jenolan is running Cachet under cPanel.

With Laravel everything runs from `public`, it's not something we can change. You should be setting up a VirtualHost?

**Comment by cenourinha** [comment]
Hi there,

I was able to install at my cPanel Account with this changes:
http://laravel.io/forum/03-06-2015-how-to-setup-laravel-5-in-shared-hosting?page=1#reply-22996

Also needed to change the public_path here:
Cachet/vendor/laravel/framework/src/Illuminate/Foundation/helpers.php
