### ISSUE TITLE
Slack notifications

### ISSUE THREAD

**Issue by DivineOmega** [cachethq/Cachet#771]
Slack offers a simple API to allow the Slackbot to notify people of events.

Slackbot Remote integration info.: https://api.slack.com/slackbot

My suggestion is that when any significant event occurs in a Cachet instance, it sends a request to the Slackbot Remote integration URL. This action would cause the Slackbot to notify users (in a specific channel) of status changes.

This would require:

* A dashboard page or section in settings to allow users to enter their (team unique) Slackbot Remote integration URL
* Code to submit a request to this URL when any significant changes occur.

Slackbot Remote integrations URLs look similar to: https://my.slack.com/services/hooks/slackbot?token=oLqLmTpxS5rDKghRQe5qbd9K&channel=%23general <-- Note the channel name, which could be considered as a customisable option.

I believe Slack integration would help large teams, that may rely on certain services, to all be simultaneously notified of any status changes without the need to manually visit the status page itself.

**Comment by GrahamCampbell** [comment]
This is already on our internal road map. Expect to hear more about it soon. :)

**Comment by DivineOmega** [comment]
Great stuff! :smile:

**Comment by jbrooksuk** [comment]
Ah yeah, you'll really like what we have planned!

**Comment by brianjking** [comment]
Did this ever make it into Cachet? @jbrooksuk 

Thanks!

**Comment by GrahamCampbell** [comment]
Not in Cachet yet, sorry. As James said though, it is something we really want to see in Cachet at some point soon.

**Comment by ekandreas** [comment]
Slack is very popular and Cachet should have a simple Slack integration implemented. Why not merge an external package?

**Comment by jbrooksuk** [comment]
> Slack is very popular and Cachet should have a simple Slack integration implemented. Why not merge an external package?

We'd like to have a native notification system rather than hacking something else in.

**Comment by ekandreas** [comment]
And you are not ok with the not.sys in Laravel?

**Comment by jbrooksuk** [comment]
That's the one we'll be implementing 👍

**Comment by roycepope** [comment]
+1 on Slack integration, can't wait for this!

**Comment by amjad** [comment]
how long until this is implemented? been requested 2 yrs ago!

**Comment by jbrooksuk** [comment]
https://github.com/CachetHQ/Cachet/commit/b8a9f41ae482a3b3e6f9d5748e44dd54cf3a8694

**Comment by amjad** [comment]
👍🏻

**Comment by fia5000** [comment]
@jbrooksuk Is there any documentation on how to actually use the Slack notifications?

**Comment by sergiovier** [comment]
+1 to slack integration!

Is there some timeline to stable? Can I test  this feature from 2.4?

**Comment by jbrooksuk** [comment]
2.4 is not yet near stable, there's a lot of work left I'm afraid. Unfortunately, a lack of time is keeping me from really focusing on this.

**Comment by RVN-BR** [comment]
Just wanted to ping in to see if this is something stable now? very interested in checking it out

**Comment by miquelbarbero** [comment]
+1 to slack integration

**Comment by GrahamCampbell** [comment]
Slack support is already implemented.

**Comment by miquelbarbero** [comment]
Great news!

Thanks a lot for your confirmation

**Comment by tejaswivinod** [comment]
@GrahamCampbell  Where do I set the slack urls for user from cachet? Is there any environment var I need to set for slack token. I can see slack webhook url in dbs but not sure how can I make use of it? Any leads will be appreciated thanks.

**Comment by miquelbarbero** [comment]
+1 to the @tejaswivinod request. I haven't see nothing related in the documentation.

Thanks and kind regards

**Comment by jorgeperezc** [comment]
@miquelbarbero Although it is not the best solution as a workaround if you define the field slack_webhook_url for any subscriber in the table subscribers of the database, it works for you

Regards !!

**Comment by yfried** [comment]
Hi, how do I setup slack integration?
