### ISSUE TITLE
500 Error

### ISSUE THREAD

**Issue by MiteshShah** [cachethq/Cachet#774]
I'd take back up of file and deleted line no 15 which cause 500 error

```
cp -v 25f8d5f423da40767b5cb74f379fbaa7 25f8d5f423da40767b5cb74f379fbaa7.org
'25f8d5f423da40767b5cb74f379fbaa7' -> '25f8d5f423da40767b5cb74f379fbaa7.org'
[root@status views]# vim /var/www/Cachet/storage/framework/views/25f8d5f423da40767b5cb74f379fbaa7 +15
[root@status views]# diff 25f8d5f423da40767b5cb74f379fbaa7 25f8d5f423da40767b5cb74f379fbaa7.org 
14a15
> 				<strong><?php echo e($incident->name); ?></strong><?php echo e($incident->isScheduled ? trans("cachet.incidents.scheduled_at", ["timestamp" => $incident->scheduled_at->diffForHumans()]) : null); ?>
```

**Comment by jbrooksuk** [comment]
Try running `php artisan cache:clear`

**Comment by MiteshShah** [comment]
@jbrooksuk Same issue 500 error

**Comment by MiteshShah** [comment]
[30-Jun-2015 12:52:13 UTC] PHP Fatal error:  Call to a member function diffForHumans() on string in /25f8d5f423da40767b5cb74f379fbaa7 on line 15

**Comment by MiteshShah** [comment]
:[2015-06-30 11:36:44] local.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'Call to a member function diffForHumans() on string' in /var/www/Cachet/storage/framework/views/25f8d5f423da40767b5cb74f379fbaa7:15

**Comment by jbrooksuk** [comment]
Have you ran `composer install -o --no-dev`?

**Comment by MiteshShah** [comment]
@jbrooksuk Its working fine till yesterday.

I run composer install -o --no-dev at the time of setup.
You want me to run that command again ?

**Comment by jbrooksuk** [comment]
Please :)

**Comment by jbrooksuk** [comment]
At any rate, this isn't an issue with Cachet itself, it's your environment :)
