### ISSUE TITLE
SSL Site

### ISSUE THREAD

**Issue by jenolan** [cachethq/Cachet#777]
In my settings I have the site URL set to https://status.jenolan.org, if a user goes to the normal address (ie http://status.jenolan.org Non-SSL) the whole site reverts to being insecure. As an interim measure I have mod'd the .htaccess to force SSL thusly;
```
<IfModule mod_rewrite.c>
    <IfModule mod_negotiation.c>
        Options -MultiViews
    </IfModule>

    RewriteEngine On

    # Force SSL
    RewriteCond %{HTTPS} !=on
    RewriteRule ^.*$ https://%{SERVER_NAME}%{REQUEST_URI} [R,L]
    RewriteCond %{SERVER_PORT} ^80$
    RewriteRule ^.*$ https://%{SERVER_NAME}%{REQUEST_URI} [R=301,L]

    # Redirect Trailing Slashes...
    RewriteRule ^(.*)/$ /$1 [L,R=301]

    # Handle Front Controller...
    RewriteCond %{REQUEST_FILENAME} !-d
    RewriteCond %{REQUEST_FILENAME} !-f
    RewriteRule ^ index.php [L]
</IfModule>
```
the issue now of course is that on upgrade this will be clobbered. I do not have any preference as such as to how to handle, my stuff I have the SSL force commented and during install if 'Require SSL' is on I uncomment the .htaccess ReWrites.

But I would like the ability to make sure the status sites are always running SSL.

**Comment by GrahamCampbell** [comment]
> But I would like the ability to make sure the status sites are always running SSL.

That's something you should handle at thr webserver level. If you're using CloudFlare, they make it super easy to force https.

**Comment by GrahamCampbell** [comment]
You can also set "secure" to true to only send sessions over https in the config folder.

**Comment by jenolan** [comment]
In CPanel AFAIK you do it in the .htaccess as above, I will add it to mu upgrade script then ;-)
