### ISSUE TITLE
Put method for incidents not in api documentation

### ISSUE THREAD

**Issue by foobarable** [cachethq/Cachet#780]
The documentation at https://docs.cachethq.io/v1.0/docs/  is lacking an entry for PUT for the /incidents endpoint although it is there in the code.

**Comment by jbrooksuk** [comment]
Good spot, I hadn't published the page: https://docs.cachethq.io/v1.0/docs/update-an-incident

**Comment by foobarable** [comment]
Have you checked the metrics api as well? There is no PUT method and I havent verified that is is implemented in the sources.

**Comment by jbrooksuk** [comment]
We do indeed have `PUT` methods on metrics but no documentation - that's an oversight on my part. I'll fix this today.
