### ISSUE TITLE
Manual install instructions?

### ISSUE THREAD

**Issue by Jamesking56** [cachethq/Cachet#783]
Hey everyone,

I'm trying to install Cachet on Pagodabox (which doesn't allow the use of automated setups).

Can someone list for me the manual steps to installing cachet?

**Comment by jbrooksuk** [comment]
I don't know anything about Pagodabox but you should be able to [follow these instructions](https://docs.cachethq.io/v1.0/docs/installing-cachet), assuming you have access to:

1. Apache/nginx config
2. Composer install
3. PHP
