### ISSUE TITLE
Redis support?

### ISSUE THREAD

**Issue by Jamesking56** [cachethq/Cachet#785]
Hello,

I think it would be great if Cachet would support caching and adding session values to a Redis server. Maybe also in the future moving the queue to Redis also.

**Comment by GrahamCampbell** [comment]
It does support this.

**Comment by Jamesking56** [comment]
When I installed cachet, on the first page of the installation it asks what cache you want to use and Redis isn't listed...

**Comment by Jamesking56** [comment]
Plus the `predis/predis` package is not required in composer.json

**Comment by GenPage** [comment]
It is my understanding the cachet supports Redis through the Laravel framework. 

https://github.com/cachethq/Cachet/blob/master/config/cache.php#L25
https://github.com/cachethq/Cachet/blob/master/config/cache.php#L68

CACHE_DRIVER=redis

http://laravel.com/docs/5.1/cache#configuration

**Comment by GrahamCampbell** [comment]
> Plus the predis/predis package is not required in composer.json

That's because you need to require it yourself if you want it.

**Comment by jbrooksuk** [comment]
We'd add a lot of bloat by adding every possible dependency to `composer.json`.

That said, we could add some documentation how to do configure these changes?

**Comment by lifehome** [comment]
Any update on supporting Redis password?

**Comment by jbrooksuk** [comment]
2.3 will support Redis passwords with no modification. You'll need to supply a `REDIS_PASSWORD` key in your `.env` file: 812160839f72a376ab07637bc0791829502e5dde
