### ISSUE TITLE
CentOS 7 + Docker 1.6.2 doesn't work with the documentation

### ISSUE THREAD

**Issue by LinHub** [cachethq/Cachet#786]
docker exec -it cachet_cachet_1 php artisan migrate --force

                                                                                                               
  [PDOException]                                                                                               
  SQLSTATE[HY000] [2002] Can't connect to local MySQL server through socket '/var/run/mysqld/mysqld.sock' (2)  
                                                                                                               

I have tried to build it several times. It stopped working very recently.

**Comment by gabrielR0** [comment]
Looks like it's trying to connect locally instead of the mysql container (maybe a missing $DB_HOST somewhere)

**Comment by rtrauntvein** [comment]
This should be fixed in my PR #788 - The Docker image will now utilize a `.env` file for configuration.
