### ISSUE TITLE
Send component name within subscriber emails

### ISSUE THREAD

**Issue by dennusb** [cachethq/Cachet#794]
Hi,

When you create an incident and you have subscribers, they receive an e-mail with only the status and the message. Why not show the component and the name in the e-mail? :-)

**Comment by jbrooksuk** [comment]
We'll accept a PR on this :)

**Comment by n0mer** [comment]
link #799

**Comment by jbrooksuk** [comment]
Closed by 905445d0ca4b40aa9a9f08858cf86d5e624a71da
