### ISSUE TITLE
cachethq not loading up

### ISSUE THREAD

**Issue by adithyakhamithkar** [cachethq/Cachet#796]
Hi,

I am trying to deploy cachethq on nginx but it fails to load, I have made sure that all the requirements are met.
This is my virtual host configuration https://github.com/adithyakhamithkar/ansible/blob/master/roles/cachethq/templates/virtualhost_cachethq_ssl.j2
Could you please help me?

Thanks,

**Comment by jbrooksuk** [comment]
What is `server_name {{hostname}}.{{domain_name}};` for?

**Comment by adithyakhamithkar** [comment]
That is my JINJA2 file {{hostname}} gets replaced my the host name of the
system and then dot my domain name.



Adithya Khamithkar
[image: http://]about.me/adithyakhamithkar
<http://about.me/adithyakhamithkar?promo=email_sig>

**Comment by GrahamCampbell** [comment]
You need to set the app name then in your env file.

**Comment by adithyakhamithkar** [comment]
Where can i find the env file?

If your referring to the the virtual host that has been taken care.


Adithya Khamithkar
[image: http://]about.me/adithyakhamithkar
<http://about.me/adithyakhamithkar?promo=email_sig>

**Comment by jbrooksuk** [comment]
Copy `.env.example` to `.env`.

**Comment by adithyakhamithkar** [comment]
Got it I'll make a copy and enter the details on it. And give it a try.

Thanks,


Adithya Khamithkar
[image: http://]about.me/adithyakhamithkar
<http://about.me/adithyakhamithkar?promo=email_sig>

**Comment by adithyakhamithkar** [comment]
Still not working.


Adithya Khamithkar
[image: http://]about.me/adithyakhamithkar
<http://about.me/adithyakhamithkar?promo=email_sig>

**Comment by GrahamCampbell** [comment]
you need to clear the config cache

**Comment by adithyakhamithkar** [comment]
Could you please guide me how to clear the config cache. I am not that
familiar with the technology used in the app. I evaluated it by deploying
on heroku.


Adithya Khamithkar
[image: http://]about.me/adithyakhamithkar
<http://about.me/adithyakhamithkar?promo=email_sig>

**Comment by jbrooksuk** [comment]
`php artisan config:clear`.
