### ISSUE TITLE
Question: Where can i find relevant log files on the docker container?

### ISSUE THREAD

**Issue by svenmueller** [cachethq/Cachet#797]
Currently whenever a customer subscribes via email, the notification/confirmation email never arrives. Any tips where i can look for the underlying problem?

Thanks Sven

**Comment by GrahamCampbell** [comment]
@svenmueller What queue driver are you using?

**Comment by GrahamCampbell** [comment]
If it's anything else but sync, you actually need to setup a queue worker.

**Comment by svenmueller** [comment]
thx for pointung out @GrahamCampbell 
any idea how this would work in the cachet docker setup?

**Comment by rtrauntvein** [comment]
You should be able to pass in the `QUEUE_DRIVER` environment variable at runtime.  It can also be added to the `docker-compose.yml` if you are using docker compose. 

`docker run -d -p 80:8000 -e QUEUE_DRIVER=sync cachethq/cachet`

@GrahamCampbell currently we are defaulting to `database` as the queue driver in the docker image. Would `sync` be more appropriate as a default?

**Comment by rtrauntvein** [comment]
@svenmueller [docker-exec](https://docs.docker.com/reference/commandline/exec/) can be used to get an interactive shell inside of the docker container.

`docker exec -it <containerid> bash -i` 

System logs should be in their normal locations such as `/var/log/`

**Comment by svenmueller** [comment]
@rtrauntvein yes, i was looking in the container but couldn't find any related logs

btw, i just tried adding `-e QUEUE_DRIVER=sync` but then the container fails

**Comment by svenmueller** [comment]
ok, i was too fast. adding `-e QUEUE_DRIVER=sync` works!

**Comment by svenmueller** [comment]
but would be interesting which log files i should have a look when there is another problem

**Comment by jbrooksuk** [comment]
:)
