### ISSUE TITLE
Scheduled maintenance emails don't contain the time at which the maintenance is to occur

### ISSUE THREAD

**Issue by tullis** [cachethq/Cachet#799]
I've just set a couple of test scheduled maintenance windows and chosen to alert my subscribers to the event.

The emails came through, but it doesn't include the time at which the event is scheduled to happen.

**Comment by n0mer** [comment]
+1

the more metadata in e-mail - the better :)

**Comment by n0mer** [comment]
link #763

**Comment by jbrooksuk** [comment]
Closed by ee0899f5c31e7d33f0df347ee6671f43aff1c516.
