### ISSUE TITLE
No documentation on how to reset lost password

### ISSUE THREAD

**Issue by LinHub** [cachethq/Cachet#803]
There is no documentation on how to reset the cachet administrator password once it has been lost. This is an issue as it is currently easier to completely reinstall than it is to attempt to figure out how to reset the password. I have not found any documentation on that point at all.

**Comment by Jamesking56** [comment]
If you've still got access to the command line of your server I would just do it manually using `php artisan tinker`

**Comment by jbrooksuk** [comment]
https://docs.cachethq.io/docs/frequently-asked-questions#section-how-do-i-reset-a-forgotten-password-
