### ISSUE TITLE
Memcached / Redis usability

### ISSUE THREAD

**Issue by Herve-M** [cachethq/Cachet#805]
Hello,

As I know, Laravel provide memcached / redis for many things like : 
> Session driver
> Cache driver

At first see, the DotEnv don't have memcached / redis variables. 
It will be a nice feature ! 

HerveM

**Comment by matejkramny** [comment]
look in config/database.php

**Comment by Herve-M** [comment]
For session driver, it's this file https://github.com/cachethq/Cachet/blob/master/config/session.php#L28
And for cache, it's this file https://github.com/cachethq/Cachet/blob/master/config/cache.php

But yes, redis config info must be set in config/database.php as said in [Laravel doc](http://laravel.com/docs/5.1/redis)

I think I will do a PR for adding this to .env file etc..

**Comment by jbrooksuk** [comment]
Thanks!

**Comment by rtrauntvein** [comment]
If this gets added into the `.env` file I can also add a Redis container to the docker-compose setup.

**Comment by jbrooksuk** [comment]
Done :)
