### ISSUE TITLE
artisan migrate error

### ISSUE THREAD

**Issue by matejkramny** [cachethq/Cachet#807]
Following the instructions & Using:
- docker (not composer)
- fresh setup
- all db env vars declared

Getting:

```
  [InvalidArgumentException]
  Database [{{DB_DRIVER}}] not configured.
```

I tried declaring DB_DRIVER env variable as mysql in case it was missing but doesn't help.

Am i missing something obvious?

Thanks!

**Comment by matejkramny** [comment]
some progress, but something still incorrect.

<img width="573" alt="screen shot 2015-07-19 at 18 12 54" src="https://cloud.githubusercontent.com/assets/797608/8766903/d167e06c-2e41-11e5-8f55-712ea04b0fc4.png">

**Comment by rtrauntvein** [comment]
You will need to clear the cache I think. 

I believe it is 'php artisan cache:clear'

**Comment by matejkramny** [comment]
Prints:

```
  [InvalidArgumentException]
  Cache store [{{CACHE_DRIVER}}] is not defined.
```

There's something about resolving variables since they are defined in my environment but not passed to the application somehow

**Comment by rtrauntvein** [comment]
May need to do a `/usr/bin/php composer.phar install --no-dev -o`

The entrypoint.sh should be doing this already however.

**Comment by matejkramny** [comment]
ha thats it!

That fixed the migration issue. The trouble is im bypassing the entrypoint when doing migration (it only runs when running cachethq/cachet w/o additional arguments)

**Comment by rtrauntvein** [comment]
Ah that makes sense. Maybe we should adjust that part of the readme a bit.

I had only tested it via docker-compose so hadn't ran into that yet

**Comment by matejkramny** [comment]
Oh right. How about running the composer install step in the dockerfile?

**Comment by rtrauntvein** [comment]
The problem is that whatever is in the `.env` file gets saved to cache when the `/usr/bin/php composer.phar install --no-dev -o` command is run.

During build, no `ENV` variables are passed to the docker build context.  That is why you see the `{{DB_HOST}}` in the error message. That string hasn't been replaced in cache yet.

This is why it runs again in the entrypoint, after we inject the provided runtime variables into the container.

**Comment by matejkramny** [comment]
oh right that makes sense..

It might be possible if the dockerfile uses ENTRYPOINT that runs composer install. The script would then pass any arguments to bash.

**Comment by pellaeon** [comment]
If you follow "Quickstart with Docker" section you will still get this error, is the documentation up to date?
I'm not familiar with Docker so I don't really understand the above discussion.

**Comment by mohannad-b** [comment]
Just ran into the same issue as well using the Quickstart with docker.

**Comment by jbrooksuk** [comment]
CC @cachethq/docker

**Comment by rtrauntvein** [comment]
I will run through the quickstart guide this afternoon and suggest edits.

**Comment by n0mer** [comment]
@mohannad-b , to help you troubleshoot this issue - are you 100% sure that `/sbin/entrypoint.sh` script was called?

@wfjsw we need to update this entrypoint.sh script so it can be called as ENTRYPOINT, not just CMD.

Otherwise issues like this will continue to pop.

**Comment by wfjsw** [comment]
@n0mer OK, but /sbin/entrypoint.sh contains supervisord start script that I think it should be moved to somewhere else.

**Comment by wfjsw** [comment]
@rtrauntvein I suggested using `--no-scripts` in Dockerfile before, any opinions?

**Comment by GrahamCampbell** [comment]
Using no scripts is a bad idea. We run scripts because they're actually needed.

**Comment by wfjsw** [comment]
The scripts will run in entrypoint.sh.

**Comment by n0mer** [comment]
@wfjsw i think Docker enforces clear separation of concerns. So, probably individual container to do 'maintenance' stuff (for now it is to initialize database) and separate 'runtime' (or 'prod') container, with `supervisord` - to actually run Cachet.

**Comment by rtrauntvein** [comment]
Simple solution is to just create a couple functions in the entrypoint.sh and a case statement to do some of these other functions like init the DB etc.

An example is the sameersbn/docker-gitlab image's entrypoint.sh - https://github.com/sameersbn/docker-gitlab/blob/master/entrypoint.sh
