### ISSUE TITLE
Feature Request: Integration with UptimeRobot

### ISSUE THREAD

**Issue by Jamesking56** [cachethq/Cachet#808]
Hey,

UptimeRobot offers 50 site monitors for free offering a really good way for monitoring site uptime and sending alerts if a site is down.

They have a good API for this and it would be great if when a site was detected as down in UptimeRobot, a Cachet incident could be raised.

Cheers.

**Comment by jbrooksuk** [comment]
I'll speak to Uptime Robot, however this issue is out of the scope of Cachet (since it's on their end). Leave it with me.

**Comment by camilonova** [comment]
I'll leave this here https://github.com/Axiacore/cachet-uptime-robot

**Comment by jbrooksuk** [comment]
Thanks @camilonova!
