### ISSUE TITLE
Adding users to subscribers, After deletion, unable to readd.

### ISSUE THREAD

**Issue by jfeulner** [cachethq/Cachet#810]
Hey all,
After adding an email manually to the subscribers list for testing, when I remove the user via the website, if I attempt to re-add them, it errors with:

>Whoops. Something went wrong with the component.
>The email has already been taken.

Red Hat Linux, 7.1

**Comment by jbrooksuk** [comment]
This is because the `Subscriber` model soft deletes rather than a complete removal. @joecohens what can we do about this? :)

**Comment by joecohens** [comment]
We could reactivate the subscriber if you attempt to subscribe again. What do you think?

**Comment by jbrooksuk** [comment]
Yeah a good idea to me :)
