### ISSUE TITLE
Branding

### ISSUE THREAD

**Issue by murendie** [cachethq/Cachet#812]
How do I add Header ? & also how do I add text on footer.

Thanks

**Comment by jbrooksuk** [comment]
1. By header, do you mean the custom logo?
2. You can't modify the footer in this version.

**Comment by murendie** [comment]
want to add the backround to the header

**Comment by jbrooksuk** [comment]
You can apply a custom stylesheet from within the Dashboard.

**Comment by murendie** [comment]
yes I did that for the footer but i can't find the class used at the top

**Comment by jbrooksuk** [comment]
What header sorry?

**Comment by murendie** [comment]
want to add the background where there is the logo

**Comment by jbrooksuk** [comment]
There is a div with a class of `.app-banner` if that's useful.
