### ISSUE TITLE
Instruction in Docker part should be upgraded.

### ISSUE THREAD

**Issue by wfjsw** [cachethq/Cachet#813]
The instruction in Docker install is too old to run Cachet properly.
I use sqlite for DB_DRIVER, and when I run `php artisan migrate`, an error showed up to me with the following thing:
```DB_DRIVER not configured```
and it cannot read the db as well (but the database file is exist and configured)

**Comment by rtrauntvein** [comment]
Are you using the `docker-compose` instructions or the manual docker run method?

**Comment by rtrauntvein** [comment]
Actually I just realized you said sqlite - I only have tested the Docker setup using a MySQL Database driver. 

I think we could add support for sqlite to the docker image by creating the `touch storage/database.sqlite` file and unsetting `DB_HOST` with `-e DB_HOST`

I will give this a test run and see how it works.

**Comment by rtrauntvein** [comment]
Looks like may be a little more difficult than I thought.  For now I would just stick with using a MySQL database, going to need to do a bit more testing to get sqlite supported for the Docker image.

**Comment by rtrauntvein** [comment]
@n0mer since you  seem to be doing most the new docker stuff:

Do we want to do the needful to make sqlite work in docker? Or just stick with SQL for now?

**Comment by jbrooksuk** [comment]
You may also need to clear the config if you've changed it?

**Comment by n0mer** [comment]
@rtrauntvein, i use remote MySQL server (Amazon RDS).

Sorry, have no idea what sqlite is :)

**Comment by rtrauntvein** [comment]
Cool, I use RDS also in production ;)

I have no experience with sqlite either, so I think for now we should just say that if you are using the docker version of Cachet, you should be using MySQL database. 

(Unless someone does a PR and documents how to use sqlite, of course)

**Comment by n0mer** [comment]
@wfjsw, in order to ensure that your settings were properly applied - i would suggest you the following hack:

1) start Cachet with debug enabled
2) open non-existing page (like "http://<cachet host>:port/123") and observe debug output.

Ensure that DB_DRIVER is set sqlite, and other DB-related environment variables are set as well (if any).

If this is fine  - then execute `docker -it cachet /bin/bash` and explore container filesystem.
You might want to install additional software , let's say `apt-get -qy update && apt-get install file mc`

**Comment by n0mer** [comment]
@jbrooksuk , do you think that admin webpage that displays basic 

```php
<?php phpinfo(); ?>
```

would help with troubleshooting like this?

It is always possible to put this line in the `./publis/index.html`, but this is yet another hack :)

**Comment by jbrooksuk** [comment]
Something like that would be cool, a *debug* menu that we can show.

**Comment by n0mer** [comment]
yeah, at least values for configuration variables like `DB_HOST` etc.

For v2.0/3.0 it would be handy to allow modifications of those values, but for now - just read-only display would help as well in configuration troubleshoot situations like this

**Comment by wfjsw** [comment]
I build my own Docker Image to include my .env. Web interface gives out No such file warnings but I have touched that.

I will test @n0mer 's idea in 3 days

**Comment by jbrooksuk** [comment]
We're looking for some new documentation for Docker on our [documentation](https://docs.cachethq.io/docs/docker). Please suggest edits :)

**Comment by n0mer** [comment]
for some reason "suggest edits" button is red

![image](https://cloud.githubusercontent.com/assets/1862997/9082564/42b00e40-3b65-11e5-91c7-60e8e0602b25.png)

**Comment by jbrooksuk** [comment]
> for some reason "suggest edits" button is red

Pinging @gdillon (Gabriel runs the fantastic Readme.io).

**Comment by wfjsw** [comment]
failed even mysql:
```
jsw@Server:~$ docker run --rm -e DB_HOST=192.168.1.3 -e DB_DATABASE=cachet -e DB_USERNAME=cachet -e DB_PASSWORD=cachet -e DB_DRIVER=mysql cachethq/cachet:latest php artisan migrate --force


                                            
  [InvalidArgumentException]                
  Database [{{DB_DRIVER}}] not configured.  
```

**Comment by n0mer** [comment]
this command is working for me

```bash
docker run -d --name cachet \
    -p 80:8000 \
    -e APP_ENV=some_env \
    -e APP_DEBUG=true \
    -e APP_URL=http://status.some.url \
    -e APP_KEY=key \
    -e CACHE_DRIVER=redis \
    -e SESSION_DRIVER=redis \
    -e QUEUE_DRIVER=redis \
    -e REDIS_HOST=some.host \
    -e REDIS_DATABASE=1 \
    -e REDIS_PORT=6379 \
    -e DB_DRIVER=mysql \
    -e DB_HOST=rds.some.host \
    -e DB_DATABASE=cachet \
    -e DB_USERNAME=some_user \
    -e DB_PASSWORD=pass \
    -e MAIL_DRIVER=smtp \
    -e MAIL_HOST=email-smtp.eu-west-1.amazonaws.com \
    -e MAIL_PORT=25 \
    -e MAIL_USERNAME=user \
    -e MAIL_PASSWORD=pass \
    -e MAIL_ADDRESS=em@i.l \
    -e MAIL_NAME="First Last" \
    cachethq/cachet:latest
```

What is the output of  `docker images` command?

If your `latest` image is older than timestamp at https://registry.hub.docker.com/u/cachethq/cachet/builds_history/122451/

then please pull newer image via 

`docker pull cachethq/cachet:latest`

And, this 'latest' tag is okay, but @jbrooksuk please ask someone responsible for this docker build, to create "1.1"  tag on Docker Hub.

**Comment by n0mer** [comment]
also, in spirit of being 'good citizen' - please pay attention to #872

**Comment by n0mer** [comment]
@wfjsw

proper way of seeding database (at least that worked for me) that uses external database (w/out docker images for mysql)

1. run Cachet image

2. !important! go inside container

```bash
$ docker exec -it cachet /bin/bash
```

and then
3. seed database like this

```bash
root@dc16dcd7a725:/var/www/html# php artisan migrate --force
```

**Comment by wfjsw** [comment]
@n0mer Hmm successed

**Comment by jbrooksuk** [comment]
@n0mer we're planning on handing off Docker support to someone else. We're waiting on two things:

1. New GitHub org permissions.
2. Release 2.0.0

Basically we're going to split out the Docker and Vagrant support and let someone/a couple of people support it for us.

**Comment by wfjsw** [comment]
It should be easy if things don't change much

**Comment by n0mer** [comment]
@wfjsw , a little bit of off-topic - but how did you do this?? :)

![image](https://cloud.githubusercontent.com/assets/1862997/9090774/7af0a79c-3b9c-11e5-875e-ee1620d00327.png)

**Comment by n0mer** [comment]
i mean "hello world" :)

**Comment by ApfelUser** [comment]
@n0mer It was generated with the **[GitHub Contributions](https://github.com/IonicaBizau/github-contributions)** generator.

**Comment by jbrooksuk** [comment]
@wfjsw we'll be keeping the core Cachet code and the Vagrant/Docker features separate :)

**Comment by wfjsw** [comment]
so now we should suggest user using bash to migrate databases?
I didn't test the sqlite situation but I think it is the same issue.

**Comment by rtrauntvein** [comment]
I can review the docket instructions. I really only tested the docker-compose setup

**Comment by n0mer** [comment]
@wfjsw , if you are not using database driver directly , that you'll use `bash` anyway )

**Comment by jbrooksuk** [comment]
If you could, please submit suggestions to https://docs.cachethq.io/docs/get-started-with-docker, thanks!

**Comment by n0mer** [comment]
" the various Redis drivers" - what does it mean? What drivers other than Predis is it possible to use? What is the finite list of drivers

**Comment by jbrooksuk** [comment]
Copy and paste from the README.

**Comment by n0mer** [comment]
@jbrooksuk this page https://github.com/nrk/predis/blob/v1.0/README.md does not contain line "various Redis drivers"

**Comment by jbrooksuk** [comment]
@n0mer our README, see 1.1
