### ISSUE TITLE
Custom Statuses

### ISSUE THREAD

**Issue by prolix21** [cachethq/Cachet#815]
Is there anyway to add custom statuses or edit existing statuses? I want to be able to change the way the statuses are worded or add custom ones.

**Comment by jbrooksuk** [comment]
There isn't a way to do this at the moment. One way you could do this is to manually edit the language files to change the statuses.

`./resources/lang/{lang}/cachet.php`

**Comment by dmsimard** [comment]
This was closed and later set to milestone 1.1.0. We're at 2.3.0 and I don't see how we could create a custom status instead of the default ones.

@jbrooksuk, @GrahamCampbell, @prolix21 .. can we re-open this issue ? Why would it be closed if it hasn't been implemented ?

**Comment by GrahamCampbell** [comment]
Sorry, but this was closed as a "not planned", rather than an "implemented".

**Comment by dmsimard** [comment]
@GrahamCampbell I'm going to argue that it'd be a great feature to have in cachet IMHO.
Some things monitored do not fit well under the wording provided by default by the statuses (i.e, Operational, Performance Issues, etc.)
