### ISSUE TITLE
Landing page times out due to graphs

### ISSUE THREAD

**Issue by matejkramny** [CachetHQ/Cachet#819]
There is a bug with the graphs. I've got a program logging uptime to cachet (every second). Cachet displays about 10 hours worth of data, so at any time it loads up to 36000 data points per graph from the database.

When I request the main page with two graphs, containing 72000 data points, the page loads for so long that nginx halts the requests rendering the 504 gateway timeout..

I wouldn't want to know what would happen if this were public-facing. Its obvious that the data aggregation shouldn't be happening when someone requests the page, that should already be done by a cronjob regularly..

I have absolutely no experience with laravel therefore call upon the maintainers to consider this issue. I am happy to help anyone get set up with the monitoring tools

**Comment by robdn** [comment]
I think I have related problem. After upgrade I've noticed unusually long loading times. As soon as graphs are removed the site loads lightning fast.

**Comment by jbrooksuk** [comment]
@GrahamCampbell pointed out that we're not lazy loading the relationships. This should be a fairly easy fix.

**Comment by Dids** [comment]
As far as I can see, I'm now experiencing this too. The public status page loads for a long time, and Pingdom keeps reporting that it's down for 15-30 minutes at a time, testing it every minute.
I can get the page to load 50% of the time, the other 50% though it's just reporting back a 504 bad gateway error.
I'll also add that I've probably accumulated a lot of data in the past few weeks of using Cachet, but I have no idea if Cachet is eg. pruning old data.

**Comment by jbrooksuk** [comment]
Ping @joecohens we need some caching on metrics

**Comment by GrahamCampbell** [comment]
@jbrooksuk We need to lazy load the metrics like I suggested too.

**Comment by GrahamCampbell** [comment]
With the ajax shizzle.

**Comment by jbrooksuk** [comment]
We did change to eager-loading the metrics which helped a bit, obviously we need to do more :)

**Comment by GrahamCampbell** [comment]
When i said lazy load, i didn't mean in the db component, I literaly meant load the page without the graphs, then send a request in the js to get them.

**Comment by joecohens** [comment]
Just get the metric points via ajax or the actual html partial with the graph?

**Comment by GrahamCampbell** [comment]
> Just get the metric points via ajax or the actual html partial with the graph?

The actual html partial is probably fastest, like we do on StyleCI.

**Comment by GrahamCampbell** [comment]
We could probably cache the entire thing and just expire it when a metric changes too.

**Comment by joecohens** [comment]
:+1:

**Comment by Dids** [comment]
Any news on this yet?
