### ISSUE TITLE
durations both incidents and maintenance

### ISSUE THREAD

**Issue by prolix21** [cachethq/Cachet#820]
It would be nice to set durations on both normal incidents and maintenance scheduled. At the moment we can set the time of an event, but not how long an incident lasted or how long a particular maintenance window might last.

**Comment by jbrooksuk** [comment]
I'm pushing this back to V3, where we'll have a better structure in place :)

**Comment by jbrooksuk** [comment]
Merged into https://github.com/cachethq/Cachet/issues/1176
