### ISSUE TITLE
Current master seems to ignore the .env file

### ISSUE THREAD

**Issue by gregkare** [cachethq/Cachet#821]
I got the v1.0.0 tag running but I wanted to update to the latest master to see if the component API now returns a text status like the doc says: https://docs.cachethq.io/docs/get-a-component.

It looks like the .env file is ignored in the current master, I'm getting messages like `Database (/srv/cachet/releases/bfe2b6ca48dd99d93d801fcbe9ae00e5219539e5/storage/database.sqlite) does not exist.` when running `artisan migrate`

Am I doing something wrong? Thanks in advance

Here's part of my `.env` file that works in the v1.0.0 tag:

```
DB_DRIVER=mysql
DB_HOST=localhost
DB_DATABASE=cachet
DB_USERNAME=cachet
DB_PASSWORD=<snip>
```

**Comment by jbrooksuk** [comment]
Have you ran `php artisan config:clear`?

**Comment by GrahamCampbell** [comment]
Or better, config:cache, for significantly improved performance.

**Comment by jbrooksuk** [comment]
Even better.

**Comment by gregkare** [comment]
Thanks, I'll try that. I've never used artisan before

**Comment by gregkare** [comment]
Cheers, that fixed it. Sorry about that
