### ISSUE TITLE
Symbols displayed incorrectly in graphs

### ISSUE THREAD

**Issue by robdn** [cachethq/Cachet#822]
Symbols are displayed incorrectly in graphs, while being displayed correctly in the dashboard.

For example °C is displayed on graph suffix as &deg;C

**Comment by jbrooksuk** [comment]
Erm, your example doesn't work :laughing: 

![image](https://cloud.githubusercontent.com/assets/246103/8913926/e5260162-3493-11e5-8bf0-14a721dfed7d.png)

Can I see a picture or a link please?

**Comment by robdn** [comment]
Sure, that's https://clouviderstatus.net/

**Comment by GrahamCampbell** [comment]
Displaying right for me.

**Comment by jbrooksuk** [comment]
Sorry pal, it's fine here too. What browser do you use?

![image](https://cloud.githubusercontent.com/assets/246103/8913995/63f67ada-3494-11e5-87fc-df56174ad8d7.png)

**Comment by robdn** [comment]
Hm. Chrome 44.0.2403.107.

Apparently when I changed it on https://demo.cachethq.io/ it displays incorrectly for me...

![image](https://cloud.githubusercontent.com/assets/13004856/8914019/9785d6c0-3494-11e5-98e3-bd86f26c28ac.png)

![image](https://cloud.githubusercontent.com/assets/13004856/8914034/ac6a59e4-3494-11e5-87e7-2fc958591bba.png)

**Comment by jbrooksuk** [comment]
Ohhh! The tooltips.

**Comment by robdn** [comment]
***Ohhh! The tooltips.***

Sorry, should have been more precise :)

**Comment by jbrooksuk** [comment]
Heh don't worry. I'll look at this now.

**Comment by robdn** [comment]
Thanks @jbrooksuk !

**Comment by jbrooksuk** [comment]
Pull down the `master` branch.

**Comment by robdn** [comment]
![image](https://cloud.githubusercontent.com/assets/13004856/8914326/830d13be-3496-11e5-9221-18185569acae.png)

Thanks. One more left.

**Comment by GrahamCampbell** [comment]
https://github.com/cachethq/Cachet/commit/7f0c2a772d1d4363942b17b7e553b3d5277cfd7b

**Comment by GrahamCampbell** [comment]
Try now. :)

**Comment by robdn** [comment]
Thanks @GrahamCampbell

**Comment by jbrooksuk** [comment]
Oh ok, yeah the name makes sense to not encode too :)
