### ISSUE TITLE
Ability to set decimal places in metrics

### ISSUE THREAD

**Issue by robdn** [cachethq/Cachet#823]
Feature request.

Since the API and DB accepts values with up to 4 decimal places it would be a great feature to allow more accurate displaying of the results. 

Would it be possible to add number of decimal places per metric in the dash and then display appropriate results on the graph ?

**Comment by jbrooksuk** [comment]
@GrahamCampbell what's the best way of doing this?

**Comment by GrahamCampbell** [comment]
PHP has functions to do this.

**Comment by jbrooksuk** [comment]
Closed by 68a41ae49fa169860fc791e45357008a82be502c
