### ISSUE TITLE
Y axis unit and range 

### ISSUE THREAD

**Issue by robdn** [cachethq/Cachet#824]
Feature request.

It would be a great feature if we could setup a unit and range of the Y axis. 

At the moment Cachet is not displaying scale on the Y axis and it is impossible to set a range for the graph. As a result of that if the values are very close to each other, drop by -1 look like this: 

![image](https://cloud.githubusercontent.com/assets/13004856/8914971/0e4c2250-349a-11e5-84cf-c8d4674ba232.png)

![image](https://cloud.githubusercontent.com/assets/13004856/8914981/18bff9f0-349a-11e5-8218-065ee61c0714.png)

Which suggest there is an issue as it looks like there is a significant drop of values, while the drop is only marginal.

**Comment by jbrooksuk** [comment]
@joecohens do you think we can safely set the Y-axis to display in most circumstances?

**Comment by joecohens** [comment]
@jbrooksuk We will have to take a look, but I'm thinking it's possible :)

**Comment by jbrooksuk** [comment]
In 2.0 the y axis will show the labels.

**Comment by robdn** [comment]
Will it have range too ?

**Comment by jbrooksuk** [comment]
It's self-calculating.

**Comment by GrahamCampbell** [comment]
Backporting to 1.2.

**Comment by robdn** [comment]
I understand it's at the moment, but that causes problems when the values are very consistent and there is a minimum variation from time to time, so it would be beneficial to be able to set range manually.

Also, as in my original post it would be grate to be able to set the number of decimal places to be displayed.
