### ISSUE TITLE
SMS notifications

### ISSUE THREAD

**Issue by robdn** [cachethq/Cachet#825]
Feature request.

It would be a great option if we could offer SMS notifications on top of email notifications, that are already implemented, for the incidents.

Users could perhaps subscribe to individual or all modules on the status page and get real time notification of any critical problems.

http://clickatell.com has a quite easy API and reasonable prices for SMS messages.

What do you think ?

**Comment by GrahamCampbell** [comment]
Notifications are on our roadmap, yes. :)

**Comment by mjebrini** [comment]
@GrahamCampbell is there any update on this SMS support?

**Comment by jbrooksuk** [comment]
@mjebrini we've technically started to support this using Nexmo, in 2.4 which is still in dev.
