### ISSUE TITLE
update docker config for Redis

### ISSUE THREAD

**Issue by n0mer** [cachethq/Cachet#826]
Follow-up to #805 

please also update 

* https://github.com/cachethq/Cachet/blob/master/docker/.env.docker
* https://github.com/cachethq/Cachet/blob/master/docker/entrypoint.sh

for

REDIS_HOST, REDIS_DATABASE and REDIS_PORT

**Comment by jbrooksuk** [comment]
Accepting a PR for this.

**Comment by n0mer** [comment]
@jbrooksuk , sure

https://github.com/cachethq/Cachet/pull/827

**Comment by jbrooksuk** [comment]
Closed by https://github.com/cachethq/Cachet/pull/827
