### ISSUE TITLE
Improve translations handling

### ISSUE THREAD

**Issue by jbrooksuk** [CachetHQ/Cachet#832]
Whilst CrowdIn really helps out with translations, if we ever have to manually add a translation string, we have to add it to **every** file.

I get annoyed with this myself (and sometimes just don't do it) - so I can imagine developers/translators getting frustrated when adding a new feature.

**Comment by jbrooksuk** [comment]
@cachethq/owners any ideas on how to do this?

**Comment by AntoineAugusti** [comment]
This package seems interesting and provide useful commands to at least add new strings everywhere

**Comment by jbrooksuk** [comment]
Yeah, we're going to need to modify the package though, so that it uses short-array syntax etc.

**Comment by GrahamCampbell** [comment]
And fix the wrong indentation.

**Comment by jbrooksuk** [comment]
No longer accepting PR's for langs except English. Only CrowdIn. I'll keep 'em in sync.
