### ISSUE TITLE
404 error if you click on "unsubscribe" in maintenance emal

### ISSUE THREAD

**Issue by andygrunwald** [cachethq/Cachet#833]
If you subscribe incidients in https://demo.cachethq.io/ and you receive an email about a new one and click unsubscribe in the email you will get a 404 error (https://demo.cachethq.io/unsubscribe).

See picture.
<img width="872" alt="screen shot 2015-07-29 at 07 43 36" src="https://cloud.githubusercontent.com/assets/320064/8950727/8e57126c-35c5-11e5-89bb-109ac28d2f2b.png">

**Comment by jbrooksuk** [comment]
I'll try and look at this a bit later. @joecohens I think the unsub link isn't working.

**Comment by joecohens** [comment]
Yeah I think we are not getting the `?code=` part.

**Comment by jbrooksuk** [comment]
Weird though since we're passing through the `code` value.

**Comment by andygrunwald** [comment]
My unsubscribe link looks like `http://mandrillapp.com/track/click/30254010/demo.cachethq.io?p=eyJzIjoiTENRemRIREJDNU5ESFJWQlRmc1hLbERyT19BIiwidiI6MSwicCI6IntcInVcIjozMDI1NDAxMCxcInZcIjoxLFwidXJsXCI6XCJodHRwczpcXFwvXFxcL2RlbW8uY2FjaGV0aHEuaW9cXFwvdW5zdWJzY3JpYmVcIixcImlkXCI6XCJhZTUzYmE0NmQzNmE0YjMzYmNkYmVmODgzOWZmOTExZFwiLFwidXJsX2lkc1wiOltcImIyNDk3MGJkZjFmNWYyZThmMDQ3MWM5MmQ3NjkwODVlMjYyNGJkY2RcIl19In0`

**Comment by jbrooksuk** [comment]
I think that the `p` parameter is Mandrill's doing.

**Comment by GrahamCampbell** [comment]
Instead of using a query string, we should just use a url parameter.

**Comment by jbrooksuk** [comment]
I don't think we're using a query string @GrahamCampbell?

**Comment by GrahamCampbell** [comment]
> Yeah I think we are not getting the ?code= part.

**Comment by GrahamCampbell** [comment]
?

**Comment by jbrooksuk** [comment]
https://github.com/cachethq/Cachet/blob/master/app/Http/Routes/StatusPageRoutes.php#L48

We're not using a param :)

**Comment by GrahamCampbell** [comment]
Sure. :P
