### ISSUE TITLE
Components API doesn't behave as documented

### ISSUE THREAD

**Issue by gregkare** [cachethq/Cachet#834]
[The documentation for the components API endpoint](https://docs.cachethq.io/docs/get-a-component) doesn't match the current code.

Here's the sample from the doc:

```json
{
    "data":{
        "id":1,
        "name":"API",
        "description":"This is the Cachet API.",
        "status_id":1,
        "status":"Operational",
        "incident_count":0,
        "created_at":1425630835,
        "updated_at":1425719658
    }
}
```

And what you're actually getting with the current master:

```json
{
    "data": 
    {
        "id": "2",
        "name": "API",
        "description": "This is the Cachet API.",
        "link": "link",
        "status": "1",
        "order": "2",
        "group_id": "0",
        "created_at": "2015-07-22 16:47:20",
        "updated_at": "2015-07-28 17:46:15",
        "deleted_at": null
    }
}
```

`status` is a numeric ID and there's no textual representation of the status. It would be really useful to have a human readable message, for example to announce a partial outage on a site.

**Comment by jbrooksuk** [comment]
The documentation is out of date here. I'll update it as soon as I can. Sorry for this.

**Comment by gregkare** [comment]
Thanks.

Are we supposed to parse the list of incidents to find the ones for a component instead of getting the status?

**Comment by jbrooksuk** [comment]
> Are we supposed to parse the list of incidents to find the ones for a component instead of getting the status?

Sorry, do you mean that you want to find incidents for a certain status?

**Comment by gregkare** [comment]
I would like to get the status (human readable) for a component from the API. As far as I understand I can only get that from the incidents API, not the components API (you only get a numeric status ID)

**Comment by jbrooksuk** [comment]
Docs are being updated.

**Comment by jbrooksuk** [comment]
Docs are done :) We've now added `status_name`.
