### ISSUE TITLE
i18n support on the Status Page

### ISSUE THREAD

**Issue by fcorriveau** [cachethq/Cachet#835]
Status page is always displayed in the language selected in the CachetHQ's Settings.

Since users from all around the world can access this page to check the Status of the system its a MUST that they can view it in their own language.

Detection of the browser Locale must be made to ensure the page is displayed in the client language.

**Comment by jbrooksuk** [comment]
I'd love to see a PR on this. I have got an idea on how we could do this.

**Comment by foobarable** [comment]
I'd also love to have this feature. Regarding the technical details, maybe you could lard at phpMyFaQ. They also have a feature like this (they also use PHP and Laravel:
http://www.phpmyfaq.de/

**Comment by jbrooksuk** [comment]
Closed by 59e1b22e18b281809fc57e0882f827e89daecd6a
