### ISSUE TITLE
Subscriber Emails not sending

### ISSUE THREAD

**Issue by jfeulner** [cachethq/Cachet#836]
Hey All,

After following directions on how to setup the Subscriber system. I have configure the .ENV file, I can see the jobs listed in the SQLite file. The Crontab job is set and running, but I am not receiving any verification or Incident emails.

.env Configuration
>MAIL_DRIVER=smtp
>MAIL_HOST=[REDACTED]
>MAIL_PORT=25
>MAIL_ADDRESS=noreply@[REDACTED].com
>MAIL_NAME=System Status

I have made sure that the server can reach the SMTP server, but nothing seems to come of it.

Any thoughts or ways to pursue?

**Comment by GrahamCampbell** [comment]
Is the queue driver set to sync?

**Comment by GrahamCampbell** [comment]
If you set it to database, you have to run a queue worker. That's not the same as a cron.

**Comment by jfeulner** [comment]
I followed the documentation to set a queue, and have the cron job set as per the documentation that y'all have set.

Let me try sync and see what happens!

**Comment by GrahamCampbell** [comment]
> I followed the documentation to set a queue

So you have a script running `php artisan queue:listen`, or `php artisan queue:work --daemon`?

**Comment by jfeulner** [comment]
I have it set to schedule:run 1

The documentation may need to be updated to list that command. Once I set it to Sync, worked like a charm!

**Comment by GrahamCampbell** [comment]
> I have it set to schedule:run 1

That's not how you execute queue jobs. That's how you run the command scheduler. They are two different things.

**Comment by jfeulner** [comment]
I understand that, but I'm just letting y'all know that the documentation does not have any of that information. Had I know that I needed to run that command, I would have been more than happy haha :)

https://cachet.readme.io/docs/setup-subscribers

>The default installation of Cachet sets the queue type to database which means that all jobs are >stored within your database and is then processed by a cron job which calls an artisan command >from within the project directory.

>You'll need to create a new cron job, in Ubuntu it's a case of running crontab -e and adding this line:

>* * * * * php /path/to/artisan schedule:run 1>> /dev/null 2>&1
>Close the file and the cron job will now begin running, processing any confirmation and incident >emails.
