### ISSUE TITLE
403 error on home page

### ISSUE THREAD

**Issue by n0mer** [cachethq/Cachet#837]
Hi,

after fresh install, logging in to dashboard - home page still displays the following stacktrace:

```
GuzzleHttp\Exception\ClientException thrown with message "Client error: 403"

Stacktrace:
#88 GuzzleHttp\Exception\ClientException in /var/www/html/vendor/guzzlehttp/guzzle/src/Middleware.php:69
#87 GuzzleHttp\Middleware:GuzzleHttp\{closure} in /var/www/html/vendor/guzzlehttp/promises/src/Promise.php:199
#86 GuzzleHttp\Promise\Promise:callHandler in /var/www/html/vendor/guzzlehttp/promises/src/Promise.php:152
#85 GuzzleHttp\Promise\Promise:GuzzleHttp\Promise\{closure} in /var/www/html/vendor/guzzlehttp/promises/src/TaskQueue.php:60
#84 GuzzleHttp\Promise\TaskQueue:run in /var/www/html/vendor/guzzlehttp/guzzle/src/Handler/CurlMultiHandler.php:96
#83 GuzzleHttp\Handler\CurlMultiHandler:tick in /var/www/html/vendor/guzzlehttp/guzzle/src/Handler/CurlMultiHandler.php:123
#82 GuzzleHttp\Handler\CurlMultiHandler:execute in /var/www/html/vendor/guzzlehttp/promises/src/Promise.php:240
#81 GuzzleHttp\Promise\Promise:invokeWaitFn in /var/www/html/vendor/guzzlehttp/promises/src/Promise.php:217
#80 GuzzleHttp\Promise\Promise:waitIfPending in /var/www/html/vendor/guzzlehttp/promises/src/Promise.php:261
#79 GuzzleHttp\Promise\Promise:invokeWaitList in /var/www/html/vendor/guzzlehttp/promises/src/Promise.php:219
#78 GuzzleHttp\Promise\Promise:waitIfPending in /var/www/html/vendor/guzzlehttp/promises/src/Promise.php:62
#77 GuzzleHttp\Promise\Promise:wait in /var/www/html/vendor/guzzlehttp/guzzle/src/Client.php:130
#76 GuzzleHttp\Client:request in /var/www/html/vendor/guzzlehttp/guzzle/src/Client.php:88
#75 GuzzleHttp\Client:__call in /var/www/html/vendor/alt-three/emoji/src/EmojiServiceProvider.php:47
#74 GuzzleHttp\Client:get in /var/www/html/vendor/alt-three/emoji/src/EmojiServiceProvider.php:47
#73 AltThree\Emoji\EmojiServiceProvider:AltThree\Emoji\{closure} in /var/www/html/vendor/laravel/framework/src/Illuminate/Cache/Repository.php:199
#72 Illuminate\Cache\Repository:remember in <#unknown>:0
#71 call_user_func_array in /var/www/html/vendor/laravel/framework/src/Illuminate/Cache/CacheManager.php:310
#70 Illuminate\Cache\CacheManager:__call in /var/www/html/vendor/alt-three/emoji/src/EmojiServiceProvider.php:48
#69 Illuminate\Cache\CacheManager:remember in /var/www/html/vendor/alt-three/emoji/src/EmojiServiceProvider.php:48
#68 AltThree\Emoji\EmojiServiceProvider:AltThree\Emoji\{closure} in /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Container.php:733
#67 Illuminate\Container\Container:build in /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Container.php:626
#66 Illuminate\Container\Container:make in /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Application.php:674
#65 Illuminate\Foundation\Application:make in /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Container.php:1157
#64 Illuminate\Container\Container:offsetGet in /var/www/html/vendor/alt-three/emoji/src/EmojiServiceProvider.php:66
#63 AltThree\Emoji\EmojiServiceProvider:AltThree\Emoji\{closure} in /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Container.php:1018
#62 Illuminate\Container\Container:fireCallbackArray in /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Container.php:976
#61 Illuminate\Container\Container:fireResolvingCallbacks in /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Container.php:645
#60 Illuminate\Container\Container:make in /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Application.php:674
#59 Illuminate\Foundation\Application:make in /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Container.php:1157
#58 Illuminate\Container\Container:offsetGet in /var/www/html/vendor/graham-campbell/markdown/src/MarkdownServiceProvider.php:157
#57 GrahamCampbell\Markdown\MarkdownServiceProvider:GrahamCampbell\Markdown\{closure} in /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Container.php:733
#56 Illuminate\Container\Container:build in /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Container.php:626
#55 Illuminate\Container\Container:make in /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Application.php:674
#54 Illuminate\Foundation\Application:make in /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Container.php:1157
#53 Illuminate\Container\Container:offsetGet in /var/www/html/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php:149
#52 Illuminate\Support\Facades\Facade:resolveFacadeInstance in /var/www/html/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php:118
#51 Illuminate\Support\Facades\Facade:getFacadeRoot in /var/www/html/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php:203
#50 Illuminate\Support\Facades\Facade:__callStatic in /var/www/html/app/Http/Controllers/HomeController.php:110
#49 GrahamCampbell\Markdown\Facades\Markdown:convertToHtml in /var/www/html/app/Http/Controllers/HomeController.php:110
#48 CachetHQ\Cachet\Http\Controllers\HomeController:showIndex in <#unknown>:0
#47 call_user_func_array in /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Controller.php:256
#46 Illuminate\Routing\Controller:callAction in /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php:164
#45 Illuminate\Routing\ControllerDispatcher:call in /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php:112
#44 Illuminate\Routing\ControllerDispatcher:Illuminate\Routing\{closure} in <#unknown>:0
#43 call_user_func in /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:139
#42 Illuminate\Pipeline\Pipeline:Illuminate\Pipeline\{closure} in <#unknown>:0
#41 call_user_func in /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:103
#40 Illuminate\Pipeline\Pipeline:then in /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php:114
#39 Illuminate\Routing\ControllerDispatcher:callWithinStack in /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php:69
#38 Illuminate\Routing\ControllerDispatcher:dispatch in /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Route.php:201
#37 Illuminate\Routing\Route:runWithCustomDispatcher in /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Route.php:134
#36 Illuminate\Routing\Route:run in /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Router.php:704
#35 Illuminate\Routing\Router:Illuminate\Routing\{closure} in <#unknown>:0
#34 call_user_func in /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:139
#33 Illuminate\Pipeline\Pipeline:Illuminate\Pipeline\{closure} in /var/www/html/app/Http/Middleware/HasSetting.php:46
#32 CachetHQ\Cachet\Http\Middleware\HasSetting:handle in <#unknown>:0
#31 call_user_func_array in /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:124
#30 Illuminate\Pipeline\Pipeline:Illuminate\Pipeline\{closure} in <#unknown>:0
#29 call_user_func in /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:103
#28 Illuminate\Pipeline\Pipeline:then in /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Router.php:706
#27 Illuminate\Routing\Router:runRouteWithinStack in /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Router.php:671
#26 Illuminate\Routing\Router:dispatchToRoute in /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Router.php:631
#25 Illuminate\Routing\Router:dispatch in /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php:237
#24 Illuminate\Foundation\Http\Kernel:Illuminate\Foundation\Http\{closure} in <#unknown>:0
#23 call_user_func in /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:139
#22 Illuminate\Pipeline\Pipeline:Illuminate\Pipeline\{closure} in /var/www/html/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php:54
#21 Illuminate\View\Middleware\ShareErrorsFromSession:handle in <#unknown>:0
#20 call_user_func_array in /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:124
#19 Illuminate\Pipeline\Pipeline:Illuminate\Pipeline\{closure} in /var/www/html/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php:62
#18 Illuminate\Session\Middleware\StartSession:handle in <#unknown>:0
#17 call_user_func_array in /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:124
#16 Illuminate\Pipeline\Pipeline:Illuminate\Pipeline\{closure} in /var/www/html/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php:37
#15 Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse:handle in <#unknown>:0
#14 call_user_func_array in /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:124
#13 Illuminate\Pipeline\Pipeline:Illuminate\Pipeline\{closure} in /var/www/html/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php:59
#12 Illuminate\Cookie\Middleware\EncryptCookies:handle in <#unknown>:0
#11 call_user_func_array in /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:124
#10 Illuminate\Pipeline\Pipeline:Illuminate\Pipeline\{closure} in /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/CheckForMaintenanceMode.php:42
#9 Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode:handle in <#unknown>:0
#8 call_user_func_array in /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:124
#7 Illuminate\Pipeline\Pipeline:Illuminate\Pipeline\{closure} in /var/www/html/vendor/fideloper/proxy/src/TrustProxies.php:47
#6 Fideloper\Proxy\TrustProxies:handle in <#unknown>:0
#5 call_user_func_array in /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:124
#4 Illuminate\Pipeline\Pipeline:Illuminate\Pipeline\{closure} in <#unknown>:0
#3 call_user_func in /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:103
#2 Illuminate\Pipeline\Pipeline:then in /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php:123
#1 Illuminate\Foundation\Http\Kernel:sendRequestThroughRouter in /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php:88
#0 Illuminate\Foundation\Http\Kernel:handle in /var/www/html/public/index.php:54
```

I would blame Emoji service:

![image](https://cloud.githubusercontent.com/assets/1862997/9002039/6732eec2-375f-11e5-9797-f0f2fb501637.png)

**Comment by n0mer** [comment]
```bash

root@2ad4fbb8ada7:/var/www/html# curl https://api.github.com/emojis
{
  "message": "API rate limit exceeded for 151.80.118.88. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.)",
  "documentation_url": "https://developer.github.com/v3/#rate-limiting"
}
```

**Comment by n0mer** [comment]
got this message during installation:

```
  - Installing mockery/mockery (0.9.4)
    Downloading: Connecting...
Could not fetch https://api.github.com/repos/padraic/mockery/zipball/70bba85e4aabc9449626651f48b9018ede04f86b, please create a GitHub OAuth token to go over the API rate limit
Head to https://github.com/settings/tokens/new?scopes=repo&description=Composer+on+2ad4fbb8ada7+2015-07-31+0604
to retrieve a token. It will be stored in "/root/.composer/auth.json" for future use by Composer.
Token (hidden):
Token stored successfully.
```

**Comment by n0mer** [comment]
so, basically the issue was that `auth.json` was created as `/root/.composer/auth.json` , but `php-fpm` was running as `www-data`.

Moving `auth.json` to `/var/www/.composer/auth.json` (and `chown www-data`) solved problem

**Comment by jbrooksuk** [comment]
@GrahamCampbell don't we cache the emoji API?

**Comment by GrahamCampbell** [comment]
We do cache it. The rate limit must have already been bust by the composer install on that server.

**Comment by n0mer** [comment]
@GrahamCampbell , actually i had an issue with cache:

* My .env file contains 

```
CACHE_DRIVER=redis
```

* i installed "Predis" manually by specifying `"predis/predis": "^1.0.3",` in `composer.json` 

* `export | grep -i cache` displays 
```bash
declare -x CACHE_DRIVER="redis"
```

But debug page listed that "CACHE_DRIVER=file"

**Comment by n0mer** [comment]
like this:

![image](https://cloud.githubusercontent.com/assets/1862997/9004831/b99540c4-3779-11e5-9ceb-65043e8b0134.png)

**Comment by n0mer** [comment]
![image](https://cloud.githubusercontent.com/assets/1862997/9005011/f6ee813c-377a-11e5-8c6c-4df2cb780a8b.png)


![image](https://cloud.githubusercontent.com/assets/1862997/9005000/e6c1fc26-377a-11e5-9b8f-573ce46c615b.png)

**Comment by willdurand** [comment]
Any solution when API rate has been reached? Setting a GitHub token in Cachet would be nice for instance...

**Comment by jbrooksuk** [comment]
@willdurand for now you can comment out the `EmojiServiceProvider`. We'll add a way to add a GitHub token though - it's helpful!

**Comment by jbrooksuk** [comment]
Almost done with this, just waiting on @GrahamCampbell to merge in the PR I have so that you can supply a GitHub oAuth token. Once it's merged, we'll add this in although it will require a `.env` change.

**Comment by jbrooksuk** [comment]
Oh this will be fixed in 2.0 - https://github.com/cachethq/Cachet/commit/bbaa1fbfa615161bfd1112af6e74627defca8c69

@GrahamCampbell is it worth back porting this to 1.2?

**Comment by clreinki** [comment]
I am having this exact same issue but I am not understanding how to fix it.  @jbrooksuk , can you clarify what you mean by commenting out the EmojiServiceProvider?  I just keep getting an error 500 on the homepage and the exact 403 error @n0mer has

**Comment by jbrooksuk** [comment]
What version are you running on?

**Comment by clreinki** [comment]
v1.1.1

**Comment by n0mer** [comment]
@clreinki , do you have a file ${HOME}/.composer/auth.json ?

${HOME} is your web app user home. For apache/debian this will be, most probably, home direcctory of`www-data`.

To check home directory - run this 

```bash
finger www-data
```

(if `finger` package is installed).

If `finger` is not installed - do this:
```bash
cat /etc/passwd | grep www-data
```

**Comment by clreinki** [comment]
@n0mer I have a /root/.composer/auth.json but nothing under www-data.  I am running apache/debian 7

**Comment by n0mer** [comment]
and what is the user that apache and php (or php-fpm) is running ?

**Comment by n0mer** [comment]
do 

```bash
ps auxww | grep apache2
```

and 

```bash
ps auxww | grep php
```

to find out

**Comment by clreinki** [comment]
I see multiple instances of apache - one under root and a couple under
www-data

On Fri, Aug 14, 2015 at 9:46 AM, Nikolay Gorylenko <notifications@github.com

**Comment by n0mer** [comment]
... and?

can you @clreinki please be a little bit more specific around "multiple instances of apache"?

**Comment by n0mer** [comment]
did you do the step

```
Head to https://github.com/settings/tokens/new?scopes=repo&description=Composer+on+2ad4fbb8ada7+2015-07-31+0604
to retrieve a token
``` 

?

Do you have your token in `/root/.composer/auth.json` ?

**Comment by clreinki** [comment]
@n0mer Below are the results of the auxww:
> root@status:/home/escservers# ps auxww | grep apache2
> root       500  0.0  2.5 320472 25768 ?        Ss   14:53   0:00 /usr/sbin/apache2 -k start
> www-data   850  0.0  0.8 320504  8368 ?        S    14:53   0:00 /usr/sbin/apache2 -k start
> www-data   851  0.0  0.8 320504  8368 ?        S    14:53   0:00 /usr/sbin/apache2 -k start
> www-data   852  0.0  0.8 320504  8368 ?        S    14:53   0:00 /usr/sbin/apache2 -k start
> www-data   853  0.0  0.8 320504  8368 ?        S    14:53   0:00 /usr/sbin/apache2 -k start
> www-data   854  0.0  0.8 320504  8368 ?        S    14:53   0:00 /usr/sbin/apache2 -k start
> root      1305  0.0  0.2  12720  2228 pts/0    S+   14:57   0:00 grep apache2
> root@status:/home/escservers# ps auxww | grep php
> root      1307  0.0  0.2  12720  2192 pts/0    S+   14:57   0:00 grep php

I have no idea why there are so many apache2 processes since this is a clean debian install.

Also as for the github token, I do have the token but it's not in my auth.json file.  I can add it but I saw a previous issue that James added that for 2.0 but hadn't backported it yet.

Over the weekend, I was able to get Cachet running with Docker - I'd still like to figure out what went wrong.  If I could, I'd contribute to the Cachet documentation to get a more straightforward installation guide written.

**Comment by n0mer** [comment]
@clreinki , as for apache2 - it uses different  ("thread-per-request") threading model than nginx.

Thus - tons of pre-started "worker" processes. For my own website (which does not have tons of traffic, hosted on $5/mo digital ocean) i decrease amount of workers from default 150 to 50.

Containerized version of Cachet uses nginx to serve static, and uses php-fpm in CGI mode to do PHP processing.

From your `ps` output (thanks for it) i assume that you're having mod_php. Just to be sure - please tell us what does this command say to you:

```bash

dpkg -l | grep php

```

So, i fixed the same situation by creating auth.json file in web user's home directory. In Docker situattion it was `www-data`'s home as well.

Just create file `~www-data/.composer/auth.json` and put your GitHub token in it.

Here is how this `auth.json` might look like

```json
{
    "http-basic": {},
    "github-oauth": {
        "github.com": "__TOKEN__"}
}
```

I say `might`, because previously i hit that problem during several attempts to install Cachet (it was 1st day i've discovered Cachet :) ). Now installation requires less attempts, so i do not face this issue, thus do not have exact `auth.json` file - sorry for that. 

But hope this will help you to nail this GitHub auth issue.

**Comment by clreinki** [comment]
@n0mer , thanks for all your help.  I'll give that github token a try in the morning.  Below is the output of the dpkg command:

> root@status:/home# dpkg -l | grep php
> ii  libapache2-mod-php5            5.6.9+dfsg-0+deb8u1         amd64        server-side, HTML-embedded scripting language (Apache 2 module)
> ii  php-db                         1.7.14-3                    all          PHP PEAR Database Abstraction Layer
> ii  php-pear                       5.6.9+dfsg-0+deb8u1         all          PEAR - PHP Extension and Application Repository
> ii  php5                           5.6.9+dfsg-0+deb8u1         all          server-side, HTML-embedded scripting language (metapackage)
> ii  php5-apcu                      4.0.7-1                     amd64        APC User Cache for PHP 5
> ii  php5-cli                       5.6.9+dfsg-0+deb8u1         amd64        command-line interpreter for the php5 scripting language
> ii  php5-common                    5.6.9+dfsg-0+deb8u1         amd64        Common files for packages built from the php5 source
> ii  php5-intl                      5.6.9+dfsg-0+deb8u1         amd64        internationalisation module for php5
> ii  php5-json                      1.3.6-1                     amd64        JSON module for php5
> ii  php5-mcrypt                    5.6.9+dfsg-0+deb8u1         amd64        MCrypt module for php5
> ii  php5-mysql                     5.6.9+dfsg-0+deb8u1         amd64        MySQL module for php5
> ii  php5-readline                  5.6.9+dfsg-0+deb8u1         amd64        Readline module for php5

**Comment by n0mer** [comment]
@clreinki , okay - so you use mod_php.

This way it will work.

I had to check this, because there were possibility (although unlikely, but just to be sure) that you're running some FastCGI setup for PHP.

For mod_php scenario - put `auth.json` to the home of apache's user (`www-data`).

**Comment by clreinki** [comment]
@n0mer Wonderful news - that solved it!  Thank you so much for all your assistance!

**Comment by n0mer** [comment]
:+1: 

hope this advice will be included in documentation, for future reference

**Comment by jbrooksuk** [comment]
Edits should be able to be suggested :)
