### ISSUE TITLE
 ConnectException on https://api.github.com/emojis

### ISSUE THREAD

**Issue by jclamy** [cachethq/Cachet#841]
Hi all,

After a fresh install on a server with no internet access I have the following error on the dashboard page.

![cachet](https://cloud.githubusercontent.com/assets/13056416/9004488/b1f2f60c-3776-11e5-948e-b4a64533fddc.png)
 

Is it mandatory to load emojis ? could I use a proxy with cachet to use github api?

thanks

**Comment by jbrooksuk** [comment]
If you don't have Internet support on your status page, you can edit `config/app.php` and remove the:

```
'AltThree\Emoji\EmojiServiceProvider',
```

Line 152.

**Comment by GrahamCampbell** [comment]
Remember to run the config clear command too, and you should be sorted.
