### ISSUE TITLE
Avoid use of Config and Setting

### ISSUE THREAD

**Issue by GrahamCampbell** [cachethq/Cachet#843]
They make for poor design.

**Comment by jbrooksuk** [comment]
:+1:

**Comment by LinHub** [comment]
Avoid use of anything that requires more than a text editor to change.

**Comment by jbrooksuk** [comment]
Graham and I were speaking about refactoring the settings and config altogether. Stay tuned :)

**Comment by GrahamCampbell** [comment]
Done well enough for now.
