### ISSUE TITLE
DDD Refactor

### ISSUE THREAD

**Issue by GrahamCampbell** [cachethq/Cachet#845]
For really reals this time.

**Comment by GrahamCampbell** [comment]
Still todo is the update commands.

**Comment by GrahamCampbell** [comment]
Not sure what else?

**Comment by GrahamCampbell** [comment]
Oh yeh, and some tests. I'll write some tests for us. Will use the base stuff that I wrote for StyleCI.

**Comment by jbrooksuk** [comment]
Remember that we're going to do both the create and update in one for now.

**Comment by GrahamCampbell** [comment]
:-1: for doing that. That defeats the object.
