### ISSUE TITLE
Blank Screen After Syncing v1.1 Commits

### ISSUE THREAD

**Issue by TheoBearman** [cachethq/Cachet#849]
Install at: https://status.theobearman.com/

Thoughts?

**Comment by GenPage** [comment]
Your site is returning a 500 response (Internal Server Error)

I would check your web server error logs for details on whats causing the issue.

**Comment by TheoBearman** [comment]
@GenPage Nothing looks abnormal. Is there any way of knowing whether it's something to do with my server it the new changes?

**Comment by jbrooksuk** [comment]
Check your error logs and also the `./storage/logs` directory for any output.

**Comment by TheoBearman** [comment]
@jbrooksuk https://theobearman.com/cachet.txt

**Comment by GrahamCampbell** [comment]
@TheoBearman You need to update your config folder too.

**Comment by GrahamCampbell** [comment]
And you need to clear the config cache.

**Comment by GrahamCampbell** [comment]
DId you forget to run `composer install --no-dev` or something?

**Comment by GrahamCampbell** [comment]
You need to run that everytime you update.

**Comment by TheoBearman** [comment]
@GrahamCampbell How do I do that?

**Comment by TheoBearman** [comment]
No I did that.

**Comment by GrahamCampbell** [comment]
> @GrahamCampbell How do I do that?

In you console, run `composer install --no-dev`.

**Comment by GrahamCampbell** [comment]
You can't have run that command, because you error contain logs that could only exist because you haven't run that command.

**Comment by TheoBearman** [comment]
I always run "composer install -o --no-dev --no-scripts"

**Comment by GrahamCampbell** [comment]
You need to run with script.

**Comment by GrahamCampbell** [comment]
Get rid of the no scripts, and it will work.

**Comment by TheoBearman** [comment]
http://imgur.com/J01qzo7

**Comment by GrahamCampbell** [comment]
You need to manually run the windows equilivent of what our scripts do then.

**Comment by TheoBearman** [comment]
The console doesn't recognise "composer install -o --no-dev" or "composer install --no-dev".

**Comment by TheoBearman** [comment]
How can I do that? Surely there can be some better support for windows? What changed in v1.1 which is giving me these problems?

**Comment by GrahamCampbell** [comment]
> Surely there can be some better support for windows?

Nothing planned. I use windows and get along just fine. It's really very simple. Go and delete those files our script deletes, and then manually run the commands our script runs after install.

**Comment by GrahamCampbell** [comment]
Delete the stuff in https://github.com/cachethq/Cachet/tree/1.1/bootstrap/cache.

**Comment by TheoBearman** [comment]
Ok done. Now what scripts am I running?

**Comment by TheoBearman** [comment]
*Commands

**Comment by GrahamCampbell** [comment]
Please read the composer.json.

**Comment by TheoBearman** [comment]
Trying now...

![dj](https://cloud.githubusercontent.com/assets/6546590/9025220/73b02a9e-38f3-11e5-89a7-242004a249c7.PNG)

**Comment by jbrooksuk** [comment]
1. Delete everything from `./bootstrap/cache`.
2. Run `composer install -o --no-dev`.

Anything? :)

**Comment by TheoBearman** [comment]
@jbrooksuk This appeared in my console:

![dj](https://cloud.githubusercontent.com/assets/6546590/9025248/ea38cecc-38f4-11e5-95a7-c1e675f617e5.PNG)

**Comment by jbrooksuk** [comment]
Ah yes, Windows doesn't know about the `rm` command. Try `del /S C:\cachet\bootstrap\cache\*` or wherever Cachet is installed.

**Comment by GrahamCampbell** [comment]
Don't use composer to run the script.

**Comment by GrahamCampbell** [comment]
Run them yourself.

**Comment by TheoBearman** [comment]
@jbrooksuk I manually deleted the contents of the /cache folder but the composer install -o --no-dev command is not recognised by my console.

**Comment by jbrooksuk** [comment]
@TheoBearman if you don't have Composer installed, how did you get Cachet installed originally?

**Comment by TheoBearman** [comment]
@jbrooksuk I do have composer installed and it works. For some reason however, composer isn't recognising the command you referred to above.

**Comment by jbrooksuk** [comment]
Did you run `composer install -o --no-dev --no-scripts`?

**Comment by TheoBearman** [comment]
@jbrooksuk I did. I usually do and it works. Apparently I need to run it without the --no-scripts bit for v1.1 and that is what is causing the issue. I have attempted to run the scripts individually and that isn't working either.

**Comment by GrahamCampbell** [comment]
You need to run WITH scripts for EVERY update, otherwise you've only partially updated, and you might as well just stay on a stable tag.

**Comment by jbrooksuk** [comment]
I've looked into @TheoBearman's server, the `.env` file is no longer configured.
