### ISSUE TITLE
Not sending email via SMTP and The email has already been taken.

### ISSUE THREAD

**Issue by LinHub** [cachethq/Cachet#851]
The system will not allow me to remove and add an email address after setup with the docker file and editing the .env to include SMTP information.

The email has already been taken.

It is also connecting to SMTP, but not sending any email. It does not seem to give an error as to why it is failing. I also can't find logs on why it is failing.

**Comment by n0mer** [comment]
+1 here - trying to find out any SMTP-related logs.

Basic question - how to enforce Cachet to send any e-mail?

In case of "ses" e-mail driver - what are necessary credentials?
In case of "smtp" (default) driver - where is the log? :)

**Comment by n0mer** [comment]
I tried to subscribe/unsubscribe, to see "e-mail verification" email.

But immediately after subscription user in question is visible as "Verified", so i assume no e-mails sent.

**Comment by n0mer** [comment]
folder ./storage/logs is empty as well (for "daily" logging mode)

**Comment by n0mer** [comment]
#836 - cron setup is necessary

**Comment by n0mer** [comment]
@LinHub take a look at #810
