### ISSUE TITLE
Avoid Redirect::back

### ISSUE THREAD

**Issue by GrahamCampbell** [cachethq/Cachet#867]
It is inherently insecure, and should be avoided.

**Comment by jbrooksuk** [comment]
This will require all routes to be named.

**Comment by GrahamCampbell** [comment]
Either that or we just redirect "to".

**Comment by jbrooksuk** [comment]
Named routes would be good. I've started this locally, but in the mean time `to` is good.

**Comment by jbrooksuk** [comment]
Closed by b393557c8a45a45812fda3838227f0ba1275e0b0
