### ISSUE TITLE
Avoid Binput::all/except

### ISSUE THREAD

**Issue by GrahamCampbell** [cachethq/Cachet#868]
We should use `only` or `get` to select specifics. This is also in the interest of security.

**Comment by jbrooksuk** [comment]
FWIW I had to wrap `Binput::only` with `array_filter` to account for values that hadn't been sent through.

**Comment by jbrooksuk** [comment]
No point in this until the commands are done, since we'll need to go through every method anyway.

**Comment by GrahamCampbell** [comment]
Yeh.

**Comment by GrahamCampbell** [comment]
I think this is done?
