### ISSUE TITLE
"No supported encrypter found." using docker-compose

### ISSUE THREAD

**Issue by pellaeon** [cachethq/Cachet#869]
Following "docker-compose" section in the readme, when visiting the website, it'll show

    No supported encrypter found. The cipher and / or key length are invalid.

OS: Ubuntu 14.04 amd64

**Comment by jbrooksuk** [comment]
You need to run `php artisan key:generate` followed by `php artisan config:cache`.

**Comment by pellaeon** [comment]
I suggest adding those 2 commands in the docker-compose section of readme.

**Comment by jbrooksuk** [comment]
@pellaeon Docker and Vagrant support is handled by the community. We're looking at improving the docs for both at:

- [Getting started with Docker](https://docs.cachethq.io/docs/get-started-with-docker)
- [Getting started with Vagrant](https://docs.cachethq.io/docs/get-started-with-vagrant)

We'd love for support with this.

**Comment by pellaeon** [comment]
I'm looking to improve the documentation, a few questions:
1. Should I add `docker-compose` instructions to "Get started with Docker" section on docs.cachethq.io or shoud I add a new section called "Get started with docker-compose"?
2. What is the policy regarding `README.md` and docs.cachethq.io ? should I improve both? from your saying it seems you emphasize more on docs.cachethq.io

**Comment by jbrooksuk** [comment]
Awesome, thanks @pellaeon.

1. Add a sub heading for it.
2. Once we have actual documentation at `docs.cachethq.io` I'll be removing the info from the readme and linking there instead.

**Comment by pellaeon** [comment]
OK, understood.

**Comment by jbrooksuk** [comment]
Thanks :)
