### ISSUE TITLE
Allow configuring of subscriptions

### ISSUE THREAD

**Issue by jbrooksuk** [CachetHQ/Cachet#871]
Subscribers should have the ability to manage their subscription to a status page. This would allow them to opt in and out of:

- Scheduled maintenance
- Incidents
- Components (once #870 is implemented)

From here we'd also allow them to unsubscribe altogether.

**Comment by robdn** [comment]
It would be great if they could subscribe with email, as they can now,  and with SMS too :)

**Comment by jbrooksuk** [comment]
Ping @joecohens we did this :)

**Comment by avimar** [comment]
Is there a reason someone subscribed to everything can't change the options?

**Comment by jbrooksuk** [comment]
They can, they just need to grab the link from the email they would have received.

**Comment by avimar** [comment]
I've got:

> Manage your subscription.
>Unsubscribe from email updates.

Manage just tells me that I'm subscribed to all, without an unsubscribe link.
Unsubscribe removes me from everything without confirmation.

I'm on orionian with version 2.2.2

**Comment by jbrooksuk** [comment]
Ah, this is different in v2.3.0.

Try using one of the RC's to experience it.
