### ISSUE TITLE
Teams

### ISSUE THREAD

**Issue by jbrooksuk** [CachetHQ/Cachet#876]
We should add proper team support, so that you can make a team who are solely able to change component statuses, or create a new incident etc. I don't know how useful this feature is for the masses though. Feedback?

**Comment by wngravette** [comment]
Could be very useful to assign a certain component to a certain team, giving them free access to change status and issue incidents. Certainly would decentralise the management of the status page and for larger implementations of Cachet it may remove a middle-man bottle-neck.

**Comment by ephillipe** [comment]
This feature is awesome. I need this today :)
I have a status page, http://status.alterdata.com.br/, that contains services from three teams. Without a better team management all users can open incidents in any component.

**Comment by gpilla** [comment]
+1

**Comment by jhamilton09** [comment]
Definitely need this feature. It would be nice to separate Admins from Service Owners. Anybody that has access to update a status can also change the site wording, theme, add/remove components, or change component order. A role for only creating or modifying incidents would be great. Then, isolating those members to certain components or component groups would be awesome.

**Comment by jbrooksuk** [comment]
Further, we should add a better ACL.

**Comment by MartinHynek** [comment]
Any updates? Or where to find what's worked on?
