### ISSUE TITLE
No supported encrypter found. The cipher and / or key length are invalid

### ISSUE THREAD

**Issue by svenmueller** [cachethq/Cachet#879]
Currently in our prod environment we are seeing the following error. The error started after pulling the latest cachet image:

<img width="1398" alt="bildschirmfoto 2015-08-06 um 22 06 15" src="https://cloud.githubusercontent.com/assets/131689/9122343/bb8fc8e0-3c88-11e5-9a80-f51966e1c61f.png">

Any hints how to proceed here?

Btw, this (DEBUG) site exposes lots of sensible information. How can we disable it and instead show a regular error page?

**Comment by GrahamCampbell** [comment]
Please set an encryption key.

**Comment by GrahamCampbell** [comment]
> How can we disable it and instead show a regular error page?

This should be disabled by default.

**Comment by GrahamCampbell** [comment]
Unless you're using an old version.

**Comment by svenmueller** [comment]
> Unless you're using an old version.
the image is from today. the following info is shown when using `docker inspect`
`"Created": "2015-08-06T13:31:04.223848703Z",`

**Comment by GrahamCampbell** [comment]
All docker issues are managed by the community.

**Comment by svenmueller** [comment]
>    /*
    |--------------------------------------------------------------------------
    | Encryption Key
    |--------------------------------------------------------------------------
    |
    | This key is used by the Illuminate encrypter service and should be set
    | to a random, 32 character string, otherwise these encrypted strings
    | will not be safe. Please do this before deploying an application!
    |
    */
    'key' => env('APP_KEY', 'SomeRandomString'),
    'cipher' => 'AES-256-CBC',

(https://github.com/cachethq/Cachet/blob/master/config/app.php#L81)

why do i need to set an encryption key after pulling the latest image? was there a change? cachet was running before without issues.

**Comment by GrahamCampbell** [comment]
You've always needed to set an encryption key in your env settings.

**Comment by rtrauntvein** [comment]
Right, we don't seed one in the docker `.env` at this point. The docker setup is defaulted to be suited for a development environment. 

To disable debug and get it "production" ready you need to set an APP_KEY as well as:

APP_ENV=production
APP_DEBUG=false


We can work on better documenting what needs to happen for a "production" setup once the repos are split etc.

**Comment by svenmueller** [comment]
@rtrauntvein thx again! i really appreciate your effort :)
