### ISSUE TITLE
ErrorException (E_WARNING) installing from cachethq/cachet:latest Docker

### ISSUE THREAD

**Issue by ephillipe** [cachethq/Cachet#880]
```
ErrorException (E_WARNING)
HELP
Missing argument 1 for AltThree\Emoji\EmojiServiceProvider::AltThree\Emoji\{closure}(), called in /var/www/html/vendor/laravel/framework/src/Illuminate/Cache/Repository.php on line 199 and defined
```

**Comment by GrahamCampbell** [comment]
Yeh, we just reset the 1.1 branch to an old release.

**Comment by GrahamCampbell** [comment]
Check out 1.2.

**Comment by rtrauntvein** [comment]
There is currently only a Docker hub build setup for master branch (cachethq/cachet:latest) - So this is pulling master branch.  Should be able to configure the docker hub automated builds to also build tags for the releases

**Comment by GrahamCampbell** [comment]
We're working on docker. We're announcing something soon. In the meantime I'd recommend NOT using latest, and ALWAYS use a tagged release.

**Comment by ephillipe** [comment]
Thanks
