### ISSUE TITLE
No supported encrypter found. The cipher and / or key length are invalid. 

### ISSUE THREAD

**Issue by Mebus** [cachethq/Cachet#881]
Hallo,

on Ubuntu 14.04 LTS, using Apache2 and PHP5, I get this error message:

"No supported encrypter found. The cipher and / or key length are invalid. "

I am using a fresh Cachet Version 1.1 with sqlite as database.

Mebus

**Comment by jbrooksuk** [comment]
Ah you'll need to run `php artisan key:generate` followed by `php artisan config:cache`.
