### ISSUE TITLE
500 error on status page

### ISSUE THREAD

**Issue by thedaftbadger** [cachethq/Cachet#904]
Cachet installed ok and working properly from the admin console but the status page is showing a 500 error....

`This error can be identified by d55bb28a-6f65-4e2f-a5ad-e86447f09016. You might want to take a note of this code.`

Any ideas on this one?

**Comment by thedaftbadger** [comment]
I have also just noticed that if I try to open `Settings` > `Stylesheet` then my Apache HTTP Server crashes.

`[Fri Aug 14 11:57:15.896712 2015] [mpm_winnt:notice] [pid 3564:tid 408] AH00428: Parent: child     process 300 exited with status 3221225725 -- Restarting.
httpd.exe: Syntax error on line 72 of C:/xampp/apache/conf/httpd.conf: Cannot load modules/mod_access_compat.so into server: Invalid access to memory location.`

Apache auto-restarts ok it only crashes when trying to access the `Stylesheet` option in the Dashboard.
Could this be related to the same issue I am having with the status page not loading (error 500)?

Other web apps on the same server are running fine and I have all the requirements for Cachet installed. The only thing I had to do was run the command 

    composer install --no-dev -o --no-scripts

as I am on a Windows server.

**Comment by GrahamCampbell** [comment]
> This error can be identified by d55bb28a-6f65-4e2f-a5ad-e86447f09016. You might want to take a note of this code.

That error code isn't unique to the type of error. That code is unique to the particular error occurrence, that's all. :)

**Comment by GrahamCampbell** [comment]
Please could you show us your logs.

**Comment by GrahamCampbell** [comment]
What version of Cachet, and what version of php too.

**Comment by GrahamCampbell** [comment]
> --no-scripts

You still need to run the scripts manually though.

**Comment by GrahamCampbell** [comment]
That's probably what's causing you issues.

**Comment by jbrooksuk** [comment]
We should better document Windows installations...

**Comment by thedaftbadger** [comment]
How and what scripts would I run manually on Windows?

**Comment by thedaftbadger** [comment]
That would be helpful :)

I would have used Linux but that's only for Dev not production.

**Comment by GrahamCampbell** [comment]
The ones in the composer file.

**Comment by jbrooksuk** [comment]
Basically Windows doesn't have an `rm` command, so you'll need to manually delete the files.

**Comment by GrahamCampbell** [comment]
Though windows does in some environments. :)

**Comment by GrahamCampbell** [comment]
Cygwin, or some fancy git thing.

**Comment by jbrooksuk** [comment]
@thedaftbadger I'm closing this issue as it's not Cachet directly, but feel free to continue updating the thread. We'll help you.

**Comment by thedaftbadger** [comment]
Ok so I am still struggling :(

I am running Cachet on Windows Server 2012 R2 using XAMPP. Several other web applications are also running on this server but I have checked that all the prerequisites for Cachet are installed correctly.

The install directory for the files are.... `C:\xampp\htdocs\cachet`
Composer is installed and working properly as it was used for some of the the other web apps hosted on this server.

1. I have downloaded the master release from GitHub and places the files here `C:\xampp\htdocs\cachet`

2. Configured the .env.example file for the MySQL database I wish to use (hosted on same server).

3. Ran the following windows command to rename `.env.example` to `.env`
` rename C:\xampp\htdocs\cachet\.env.example .env`

4. Ran composer in `C:\xampp\htdocs\cachet` with this command `composer install --no-dev -o --no-scripts`

5. Composer installed correctly. Then ran this to add database tables `php artisan migrate` which completes ok.

6. Generated security key using `php artisan key:generate`

7. Configured my `httpd-vhosts.conf` file
```
<VirtualHost *:80>
ServerName ukstatus.example.local
DocumentRoot "C:\xampp\htdocs\cachet\public"
<Directory "C:\xampp\htdocs\cachet\public">
Options Indexes FollowSymLinks
AllowOverride All
Order allow,deny
Allow from all
</Directory>
</VirtualHost>
```
8. Configured windows host file under `C:\Windows\System32\drivers\etc\hosts` with `127.0.0.1 ukstatus.example.local`

9. Restarted windows and checked that Apache and MySQL are running correctly.

10. Navigated to http://ukstatus.example.local and ran the Cachet setup utility. Dashboard runs correctly but unable to access the status page as I get a 500 error.

I am guessing this is because some of the scripts required in the installation have not ran properly. What scripts need running and how do I run them, through composer I guess?

I have noticed that if I try and access the Theme settings page then my `Apache HTTP Server` stops working.

```
[Mon Aug 17 08:16:16.824059 2015] [mpm_winnt:notice] [pid 3888:tid 404] AH00428: Parent: child process 3324 exited with status 3221225725 -- Restarting.
[Mon Aug 17 08:16:16.995922 2015] [ssl:warn] [pid 3888:tid 404] AH01909: server.example.com:443:0 server certificate does NOT include an ID which matches the server name
[Mon Aug 17 08:16:17.042795 2015] [mpm_winnt:notice] [pid 3888:tid 404] AH00455: Apache/2.4.12 (Win32) OpenSSL/1.0.1m PHP/5.6.11 configured -- resuming normal operations
[Mon Aug 17 08:16:17.042795 2015] [mpm_winnt:notice] [pid 3888:tid 404] AH00456: Apache Lounge VC11 Server built: Mar 20 2015 12:12:41
[Mon Aug 17 08:16:17.042795 2015] [core:notice] [pid 3888:tid 404] AH00094: Command line: 'c:\\xampp\\apache\\bin\\httpd.exe -d C:/xampp/apache'
[Mon Aug 17 08:16:17.042795 2015] [mpm_winnt:notice] [pid 3888:tid 404] AH00418: Parent: Created child process 2588
AH00548: NameVirtualHost has no effect and will be removed in the next release C:/xampp/apache/conf/extra/httpd-vhosts.conf:20
```

**Comment by jbrooksuk** [comment]
Don't use master, use a tagged release. See the installation instructions on our docs: https://docs.cachethq.io/docs/installing-cachet

**Comment by thedaftbadger** [comment]
Sorry I worded it wrongly :)
I am using tagged release version 1.1.1


On Aug 17, 2015, at 10:58 AM, James Brooks <notifications@github.com> wrote:

Don't use master, use a tagged release. See the installation instructions on our docs: https://docs.cachethq.io/docs/installing-cachet

**Comment by thedaftbadger** [comment]
What scripts do I need to run manually?

**Comment by thedaftbadger** [comment]
So I have ran the following commands manually....

```
php artisan optimize --force
php artisan config:cache
php artisan route:cache
```
And now I guess I need to delete these files but I am not sure on their location...
`compiled.php` `config.php` `routes.php` `services.json`

I have noticed that even though these files have been deleted and I have ran the above scripts manually I cant get the status page to not 500 error. The dashboard still works fine.

**Comment by jbrooksuk** [comment]
You need to delete from `./bootstrap/cache/`

**Comment by thedaftbadger** [comment]
Ok thanks @jbrooksuk Would the files in `./bootstrap/cache/` cause my status page not to work?
