### ISSUE TITLE
Tracking

### ISSUE THREAD

**Issue by jbrooksuk** [cachethq/Cachet#91]
I'm wondering whether it'd be worth adding some kind of internal tracking that gets sent to directly back to us, to see how often something happens.

We'd only need to track:

- Installs
- Components; added, edited, deleted
- Incidents; added, edited, deleted
- Notifications

Then we'd have enough data to use as "we've had x installs" etc.

Of course, there are things like:

- Security
- Privacy

That we'd need to take care of.

**Comment by jbrooksuk** [comment]
I had a reply from Segment regarding having the API write key in the source code:

> In general revealing the write key isn't too much of a concern. Of course when others know your write key it's possible for them to send analytics events to Segment without your permission, but we haven't seen any malicious behavior around that in the past.
> 
> Usually just adding the tracking with your key in there is alright. If you prefer to hide the key a layer deeper in a config file that's one option, or depending on the type of project you're working on you could make an API call to your server to retrieve the write key when a new project is started with your open-source software.
> 
> Any client-side javascript tracking calls will reveal the write key by default, so there's not a lot we can do for that, but again we've never seen any malicious behavior in that regard.
> 
> If you have some more detailed questions about the architecture of your project we'd be happy to help make some suggestions about best practices.

Looks like we're good just to implement Segment.io straightaway.

**Comment by jbrooksuk** [comment]
@GrahamCampbell you don't know of any Laravel adapters for [this](https://github.com/segmentio/analytics-php) do you?

**Comment by GrahamCampbell** [comment]
I could write one if needed.

**Comment by jbrooksuk** [comment]
I've not been able to find one, but it'd be good to have if you've got the time? If not, I'll have a go by checking out your adapters and stuff :)

**Comment by willdurand** [comment]
Sounds like a bad idea to me. Or make it optional and disabled by default.

**Comment by foxted** [comment]
@willdurand I think @jbrooksuk was talking about an 'opt-in' thing, which means it would be deactivated by default unless you choose to give some feedback.

Seems like a cool idea, would love to work with you guys on the adapter :)

**Comment by GrahamCampbell** [comment]
I think we should have a check box which is enabled by default on the setup page.

**Comment by GrahamCampbell** [comment]
I'm pretty sure WordPress tracking is actually non optional too.

**Comment by joecohens** [comment]
:+1: Checkbox on Setup like the one we have now to show support.

**Comment by jbrooksuk** [comment]
Definitely a checkbox. 

One thing we could do is fetch the key when they say yes to tracking and decrypt it. This way we aren't giving it away easily.

**Comment by willdurand** [comment]
WP does not care about privacy, doing silly stuff. Does this mean Cachet should do the same? Nope.

By the way what showing support actually does? And why can't I enable it later?

**Comment by jbrooksuk** [comment]
It's not even tracking as such, because we aren't tracking a user in particular just usage stats. No component or incident data would be included. 

@willdurand it adds a link in the footer to Cachet.

**Comment by jbrooksuk** [comment]
Thoughts:

- We'll need some a privacy policy.
- We need to highlight that we **don't** track any personal information.
- All collected data is anonymous.
- List exactly what we're tracking.
- Rather than tracking, it should be "Usage stats" since that is what it is.

**Comment by foxted** [comment]
I am surprised they didn't think about such feature!

**Comment by jbrooksuk** [comment]
Ok, then we just pull down the key from the server and store it somewhere in plain text (also advisable as a solution from Segment) that way, if the key ever gets abused, we can re-issue quickly.

**Comment by jbrooksuk** [comment]
Heh, looks like someone is [making a wrapper](https://github.com/dmitrymomot/laravel-segmentio-wrapper).

**Comment by GrahamCampbell** [comment]
They've misused facade, and been calling config in their class. Bad. :(

**Comment by jbrooksuk** [comment]
Yeah I took a look through and it's not great, we'd be better off with our own version.

**Comment by jbrooksuk** [comment]
I've started work on [this](https://github.com/cachethq/Laravel-Segment).

**Comment by jbrooksuk** [comment]
[Package is done](https://github.com/cachethq/Laravel-Segment).

Now we need to work out how we can assign each user within a Cachet setup a unique ID for anonymous tracking and of course, only do the tracking if the administrator allows us to.

**Comment by jbrooksuk** [comment]
I have an idea regarding the unique ID. We don't actually care what user of what status page does what. So let's use `app.key` as the unique ID. This also means that we don't need track *just* the logged in users, but people just viewing the homepage etc.
