### ISSUE TITLE
Cronjob issue

### ISSUE THREAD

**Issue by peterlaws** [cachethq/Cachet#911]
When the cron kicks in:

eg  /usr/bin/php -q /var/www/Cachet/artisan schedule:run 1 >> /dev/null 2>&1

I get

[2015-08-16 11:31:02] production.ERROR: exception 'RuntimeException' with message 'Too many arguments.' in /var/www/Cachet/vendor/symfony/console/Input/ArgvInput.php:181

**Comment by jbrooksuk** [comment]
Use:

```
/usr/bin/php -q /var/www/Cachet/artisan schedule:run >> /dev/null 2>&1
```

**Comment by peterlaws** [comment]
I also noticed that it sets the 'subscribers' table fields 'created_at' and 'updated_at' in the database an hour behind my server system time.

**Comment by jbrooksuk** [comment]
Have you set the timezone correctly at setup?

**Comment by peterlaws** [comment]
Yes, everything is set to 'Europe/London', system, php.ini and cachet.

Would this interfere with the cron? As it's not even sending via smtp when testing with a personal external email address. I do have google apps, so I use their smtp - sometimes I have to use ssl:// with the host, I tried with and without.

What actually 'app_debug=true' do? Nothing is being logged except script errors.

**Comment by jbrooksuk** [comment]
Can you open a new issue please.
