### ISSUE TITLE
Client error: 403 - Docker install failed?

### ISSUE THREAD

**Issue by LinHub** [cachethq/Cachet#915]
GuzzleHttp \ Exception \ ClientException (403)

Client error: 403 

The install says something about keys. I run the following:

$ docker exec -it cachet_cachet_1 php artisan key:generate
$ docker exec -it cachet_cachet_1 php artisan config:cache

and it gives the error at the top. This is after completely blowing it away and trying again from scratch due to various database related errors that I could never solve.

How do I fix this?

**Comment by LinHub** [comment]
The way this is running/built:

cd /usr/src

git clone https://github.com/cachethq/Cachet.git

cd Cachet

docker-compose build

docker-compose up



$ docker exec -it cachet_cachet_1 php artisan migrate --force
$ docker exec -it cachet_cachet_1 php artisan key:generate
$ docker exec -it cachet_cachet_1 php artisan config:cache

What am I missing?

**Comment by LinHub** [comment]
It looks like this is because of the API hit limit.

It would be nice if someone would put an error message in that says, "Due to our design choices, the software cannot install correctly more than one or two times in X number of hours. ERROR" It would save us some searching..

**Comment by wfjsw** [comment]
This will be fixed by using git if cannot download dist in coming 1.2 version.

**Comment by jbrooksuk** [comment]
1.2 now has separated Docker support. Please see https://docs.cachethq.io/docs/get-started-with-docker
