### ISSUE TITLE
Status changes when editing component

### ISSUE THREAD

**Issue by jenolan** [cachethq/Cachet#916]
If the status of a component is not 'Operational' and you edit it then save, it will be set to operational unless you remember to change the loaded 'default'.

The 'Status' field in the component edit should reflect the current status, not simply always set to 'Operational' as it is nasssty if you change a detail field for a component and its status changes when you didn't mean it to do so.

**Comment by jbrooksuk** [comment]
Closed by bf4ebcde45496d5011ee878a00ac3cb551338d32
