### ISSUE TITLE
I want cachet to show the components only and the current state

### ISSUE THREAD

**Issue by murendie** [cachethq/Cachet#920]
How do I make my status page look like this ? Without showing pas incidents but current incidents & planned, something like attached.
![screen shot 2015-08-18 at 9 00 28 pm](https://cloud.githubusercontent.com/assets/5470145/9339771/2f73d8ca-45ec-11e5-84c7-88ccac2eef4d.png)

**Comment by jbrooksuk** [comment]
Unfortunately this isn't possible right now. I may change it so that you *can* configure 0 days of incidents to show.

**Comment by jbrooksuk** [comment]
Closed by 885c17054fcf80f6f8f91022ee53591c35c91979
