### ISSUE TITLE
SQLSTATE[HY000]: General error: 1 no such function: to_char

### ISSUE THREAD

**Issue by jgrossiord** [cachethq/Cachet#921]
When adding a metric, the status page is crashing 
Cachet 1.2.0
Database : sqlite

ErrorException thrown with message "SQLSTATE[HY000]: General error: 1 no such function: to_char (SQL: select sum(metric_points.value) as aggregate FROM metrics JOIN metric_points ON metric_points.metric_id = metrics.id WHERE metric_points.metric_id = 2 AND to_char(metric_points.created_at, 'YYYYMMDDHH24') = :timestamp GROUP BY to_char(metric_points.created_at, 'H')) (View: /var/www/Cachet/resources/views/partials/metrics.blade.php) (View: /var/www/Cachet/resources/views/partials/metrics.blade.php)"

**Comment by jbrooksuk** [comment]
@cachethq/owners I'm thinking of writing a repository system for metrics. It'll allow us to write different code for the different DB drivers. What do you think?

**Comment by GrahamCampbell** [comment]
Might be a bit overkill?

**Comment by jbrooksuk** [comment]
Closed by f13b8debe4f2d097f40676f272c8892825452f7f
