### ISSUE TITLE
Metrics/Sub pages

### ISSUE THREAD

**Issue by sahaka** [cachethq/Cachet#922]
I saw the issue/request for Cachet to support multiple applications and I think this partly would be addressed by that. 

Right now we use it to display the status of multiple services and each service has tons of metrics that we graph on our own using highcharts pulling from a mysql database. It would be awesome for Cachet to have sub-pages for each service or groups of services that we can put charts for each of the metrics we have. It would also be nice to sort of filter out the issues for that particular service as well.

We like the idea of having one location (subdomain) that shows the basic status of everything at a glance but we really want to be able to show more data than we have. Prometheus does a pretty good job depicting what we envision (it just looks so horrible compared to the look of Cachet). http://prometheus.io/assets/promdash_event_processor.png

With all that said we would also like to have more advanced graphing capabilities. Right now it seems that the metrics chart intelligently builds itself but there are times where we would want multiple metrics shown on one graph to save space while still effectively delivering the information needed. Also the ability to show all/some data points instead of averages or sums would also be nice.

**Comment by jbrooksuk** [comment]
Truthfully, I don't think that Cachet is a good fit for your needs I'm afraid. Not without some customisation on your part anyway.
