### ISSUE TITLE
TimeZone Support

### ISSUE THREAD

**Issue by sahaka** [cachethq/Cachet#927]
When we create scheduled maintenance it shows the exact time on the set timezone on mouseover and by default it shows a relative time (if within the same day). It would be really nice to convert the time to the user that is accessing the site while still showing the original time set by our timezone(just incase their timezone isn't properly found).

**Comment by Lightman32** [comment]
I m planning to contribute to this project, would that be ok if i pick this up and start working on it? i m sorry if i m not following the right procedure, could your please point me to the right direction. Cheers

**Comment by jbrooksuk** [comment]
Feel free! :)

**Comment by jbrooksuk** [comment]
This should be able to be fixed by implementing https://github.com/cachethq/Cachet/issues/1011, so closing this issue.
