### ISSUE TITLE
Blank Page after install

### ISSUE THREAD

**Issue by Sindresgaming** [cachethq/Cachet#931]
Hey, i installed it following the https://docs.cachethq.io/docs/installing-cachet instructions
and i get a blank white page but the favicon showing.

Am running CentOS 7.1
PHP Version: 5
Apache Version: 2.4.6
MySQL Version: 5.5.44-MariaDB

**Comment by JoeCurrie** [comment]
I'm having the same issue.

**Comment by GrahamCampbell** [comment]
> PHP Version: 5

Can you be more specific please?

**Comment by GrahamCampbell** [comment]
Are the file permissions wrong on your storage folder/

**Comment by Sindresgaming** [comment]
PHP 5.5.28 (cli) (built: Aug  9 2015 12:22:11)
Copyright (c) 1997-2015 The PHP Group
Zend Engine v2.5.0, Copyright (c) 1998-2015 Zend Technologies

**Comment by GrahamCampbell** [comment]
Your storage folder must belong to the wrong user then.

**Comment by GrahamCampbell** [comment]
The user running php must have write access to the storage folder.

**Comment by GrahamCampbell** [comment]
If you like, you can just recursively set the permissions to 755 or something, but I'd consider that to be insecure given that code injected into the storage folder can endup being executed by php (compiled views).

**Comment by Sindresgaming** [comment]
i tryd doing "chmod 755 -R storage" still blank page

**Comment by Sindresgaming** [comment]
"root:root" got access to everything in the folder

**Comment by JoeCurrie** [comment]
I'm getting same issue and I'm using nginx.

**Comment by GrahamCampbell** [comment]
I can't do anything unless you actually give me logs.

**Comment by Sindresgaming** [comment]
In Apache logs its showing:


[Sat Aug 29 08:18:21.103380 2015] [:error] [pid 19762] [client <myip>] PHP Fatal error:  Uncaught exception 'UnexpectedValueException' with message 'The stream or file "/var/www/Cachet/storage/logs/laravel-2015-08-29.log" could not be opened: failed to open stream: Permission denied' in /var/www/Cachet/bootstrap/cache/compiled.php:12857\nStack trace:\n#0 /var/www/Cachet/bootstrap/cache/compiled.php(12945): Monolog\\Handler\\StreamHandler->write(Array)\n#1 /var/www/Cachet/bootstrap/cache/compiled.php(12795): Monolog\\Handler\\RotatingFileHandler->write(Array)\n#2 /var/www/Cachet/bootstrap/cache/compiled.php(12558): Monolog\\Handler\\AbstractProcessingHandler->handle(Array)\n#3 /var/www/Cachet/bootstrap/cache/compiled.php(12662): Monolog\\Logger->addRecord(500, Object(Symfony\\Component\\Debug\\Exception\\FatalErrorException), Array)\n#4 /var/www/Cachet/vendor/graham-campbell/exceptions/src/ExceptionHandler.php(79): Monolog\\Logger->critical(Object(Symfony\\Component\\Debug\\Exception\\FatalErrorException), Array)\n#5 /var/www/Cachet/bootstrap/cache/compiled.php(1850): GrahamCampbell\\Exceptions\\ExceptionHandler->report(O in /var/www/Cachet/bootstrap/cache/compiled.php on line 12857


Any suggestion/fixes?

**Comment by GrahamCampbell** [comment]
Yeh, you're file permissions are wrong.

**Comment by Sindresgaming** [comment]
by doing "chown -R apache:apache /var/www/Cachet" i got it fixed :) thanks for the help :+1:
