### ISSUE TITLE
Scheduled event displayed on date of creation, not date of actual event

### ISSUE THREAD

**Issue by berlic** [cachethq/Cachet#934]
In version 1.2 maintenance appears in event list on the date it was added, not on the date of event itself.
We scheduled the event two weeks in advance and today users need to scroll back in history to find today's maintenance event. A bit confusing...

**Comment by jbrooksuk** [comment]
Is this the list of maintenance items, or once it pops into the timeline?

**Comment by mbabker** [comment]
Once it pops into the timeline.  Had a similar experience with this scheduling an item last week (we created it on Thursday evening for a Saturday window and when it published in the timeline it had the timestamp from when it was created on Thursday).

**Comment by berlic** [comment]
Updated my installation with https://github.com/cachethq/Cachet/commit/0851427f2d495f8bfe3d161f1fe5337ee13dbcec

There are sill some issues with scheduled items:

First page screen (today is Sep 17th):
![2015-09-17 22 31 51](https://cloud.githubusercontent.com/assets/2950241/9943813/55d8065a-5d8c-11e5-98c0-9c5f22fcb266.png)

Previous week page:
![2015-09-17 22 32 06](https://cloud.githubusercontent.com/assets/2950241/9943828/670e427c-5d8c-11e5-87b4-57b3a3b4950b.png)

Scheduled item should appear just before (below) the "job's done" event on Sep 16th.
Why is it shown on previous page (week from Sep 4th till Sep 9th) with date of Sep 16th?
May be because it was created on the previous week?

**Comment by jbrooksuk** [comment]
Could

**Comment by jbrooksuk** [comment]
This is really weird, it *seems* to be working fine here. Can you give me a possible DB export of incidents?

**Comment by berlic** [comment]
Sure:
```
INSERT INTO `incidents` VALUES
(1,0,'03.09.2015 – Технические работы на серверах «Облака»',0,1,'Плановые работы по обновлению сервиса.','2015-09-03 09:00:00','2015-09-03 09:00:00','2015-09-04 12:08:46','2015-09-04 12:08:46'),
(2,8,'Медленная обработка очереди на обновление ПО в приборах',2,1,'Некоторые устройства не могут подключиться для загрузки обновления',NULL,'2015-08-26 15:00:00','2015-08-26 15:00:00',NULL),
(3,8,'Обновление ПО приборов работает в штатном режиме',4,1,'Теперь все в порядке',NULL,'2015-08-26 16:00:00','2015-08-26 16:00:00',NULL),
(4,0,'Обновление системы выполнено.',4,1,'Все системы работают штатно.',NULL,'2015-09-03 09:09:00','2015-09-04 12:08:51','2015-09-04 12:08:51'),
(5,0,'Обновление сервисов',0,1,'Плановое обновление облачных сервисов – некоторые сервисы могут временно не работать.','2015-09-16 09:00:00','2015-09-09 11:48:40','2015-09-09 12:01:21',NULL),
(6,0,'Обновление сервисов завершено',4,1,'Все сервисы работают в штатном режиме',NULL,'2015-09-16 11:00:00','2015-09-16 11:00:00',NULL);
```

**Comment by berlic** [comment]
https://github.com/cachethq/Cachet/blob/v1.2.1/app/Http/Controllers/HomeController.php#L65
Am I correct that `whereBetween('created_at'` would select only incidents `created_at` the current week? And if it was created on the previous week and scheduled at the day on the current week – it will not be shown?

**Comment by jbrooksuk** [comment]
Ah, good catch. I may have buggered up the "fix" then.

**Comment by jbrooksuk** [comment]
@joecohens are you able to look into this please?

**Comment by GrahamCampbell** [comment]
This needs moving milestones I guess.

**Comment by jbrooksuk** [comment]
This really does seem to be ok in 2.0?

**Comment by jbrooksuk** [comment]
```
INSERT INTO `incidents` (`id`, `component_id`, `name`, `status`, `visible`, `message`, `scheduled_at`, `created_at`, `updated_at`, `deleted_at`)
VALUES
	(1, 0, '03.09.2015 – Технические работы на серверах «Облака»', 0, 1, 'Плановые работы по обновлению сервиса.', '2015-10-20 21:43:33', '2015-10-20 21:43:28', '2015-09-04 12:08:46', '2015-09-04 12:08:46'),
	(2, 8, 'Медленная обработка очереди на обновление ПО в приборах', 2, 1, 'Некоторые устройства не могут подключиться для загрузки обновления', NULL, '2015-10-20 21:43:29', '2015-08-26 15:00:00', NULL),
	(3, 8, 'Обновление ПО приборов работает в штатном режиме', 4, 1, 'Теперь все в порядке', NULL, '2015-10-20 21:43:29', '2015-08-26 16:00:00', NULL),
	(4, 0, 'Обновление системы выполнено.', 4, 1, 'Все системы работают штатно.', NULL, '2015-10-20 21:43:30', '2015-09-04 12:08:51', '2015-09-04 12:08:51'),
	(5, 0, 'Обновление сервисов', 0, 1, 'Плановое обновление облачных сервисов – некоторые сервисы могут временно не работать.', '2015-10-19 21:43:32', '2015-10-20 21:43:30', '2015-09-09 12:01:21', NULL),
	(6, 0, 'Обновление сервисов завершено', 4, 1, 'Все сервисы работают в штатном режиме', NULL, '2015-10-20 21:43:31', '2015-09-16 11:00:00', NULL);
```

This gives me this:

![image](https://cloud.githubusercontent.com/assets/246103/10622058/a60e79ba-777c-11e5-8b31-4abb5233c06e.png)

Which is right?

**Comment by jbrooksuk** [comment]
Closing, because this genuinely looks fine to me now. If it's not, re-open :)

**Comment by mbabker** [comment]
The display of the timestamps looks awkward in that October 19 entry, otherwise from a data perspective it seems right to me too.

**Comment by jbrooksuk** [comment]
Yeah, I could probably improve that :)

**Comment by jbrooksuk** [comment]
Oh it's because Chrome silently translated it for me:

![image](https://cloud.githubusercontent.com/assets/246103/10622173/8f6a387e-777d-11e5-95b7-5def1c81b990.png)

**Comment by mbabker** [comment]
:+1:
