### ISSUE TITLE
MySQL SSL Support

### ISSUE THREAD

**Issue by Kickball** [cachethq/Cachet#936]
This project does not currently support MySQL SSL.

Could it be adapted or upgraded to support MySQL SSL please?

**Comment by jbrooksuk** [comment]
MySQL with SSL support requires some manual changes to the `./config/database.php` file from yourself.

You need to add:

```php
'options' => [
    PDO::MYSQL_ATTR_SSL_CA => storage_path('database.pem'),
],
```

Create a file in `./storage/database.pem` or something and make sure that the PHP process has permissions.
