### ISSUE TITLE
Enabling metrics throws 500 error

### ISSUE THREAD

**Issue by melinmel** [cachethq/Cachet#937]
After enabling 'Display graphs on status page?', cachet throws a 500 error, complaining that there is no such function: 'to_char'. Here's the error message in full:

```
SQLSTATE[HY000]: General error: 1 no such function: to_char (SQL: select sum(metric_points.value) as
aggregate FROM metrics JOIN metric_points ON metric_points.metric_id = metrics.id WHERE
metric_points.metric_id = 1 AND to_char(metric_points.created_at, 'YYYYMMDDHH24') = :timestamp
GROUP BY to_char(metric_points.created_at, 'H')) (View:
/home/forge/www/resources/views/partials/metrics.blade.php) (View:
/home/forge/www/resources/views/partials/metrics.blade.php)
```
I'm using SQLite, and I've defined a metric and populated the DB with some data. This is the only error I'm encountering. everything else is working AOK :smile:

**Comment by melinmel** [comment]
Actually, I've just noticed #921 which seems to be an identical issue, and there some commits that purported to fix the issue. Those were 8 days ago, the latest release was 4 days ago, but I'm not if thats from the same branch. anyways let me know :smiley:

**Comment by jbrooksuk** [comment]
Hmm @GrahamCampbell, maybe we should backport 7136457b4936317aebc901537fa6c8355b3bbfbb to 1.2?

**Comment by jbrooksuk** [comment]
Also thanks @melinmel for reminding me that we needed to do this.

**Comment by melinmel** [comment]
@jbrooksuk pleasure, ill keep my eye on this. a fix will be hugely appreciated! :kissing_cat:

**Comment by GrahamCampbell** [comment]
Don't think backporting is worth it given how close 2.0 is.

**Comment by melinmel** [comment]
how close is 2.0? PS @GrahamCampbell I'm your 1,000th follower :smirk:

**Comment by GrahamCampbell** [comment]
> how close is 2.0?

We expect between 1 and 3 weeks. :)

@cachethq/owners Maybe we should do a v2.0.0-beta1 this weekend?

> I'm your 1,000th follower :smirk:

Awesome. ;)

**Comment by jbrooksuk** [comment]
> @cachethq/owners Maybe we should do a v2.0.0-beta1 this weekend?

Yeah - finishing DDD won't change anything, so all should be good.

**Comment by jbrooksuk** [comment]
@melinmel for now, is it possible that you don't use SQLite?

**Comment by melinmel** [comment]
@jbrooksuk sure, but I wont -- I'll just disable metrics for now :+1:

**Comment by jbrooksuk** [comment]
@melinmel awesome, I like your thinking! :smile:

**Comment by melinmel** [comment]
@jbrooksuk :wink:

**Comment by jbrooksuk** [comment]
@melinmel can we close this issue then, knowing that V2 will fix it?

**Comment by melinmel** [comment]
indeed we can, I'll keep an eye out for v2

**Comment by smithkyle** [comment]
Not sure if there is a duplicate of this for v2, but it is still present in v2-beta 2. Drove me nuts pulling my hair out because I had also made a change to nginx so I thought it was related to that.

**Comment by jbrooksuk** [comment]
Could you open another issue for this please @smithkyle?
