### ISSUE TITLE
Password Strength Indicator When Adding a New Team Member and When Changing Passwords

### ISSUE THREAD

**Issue by TheoBearman** [cachethq/Cachet#940]
Might be nice to have [this](https://github.com/dropbox/zxcvbn) implemented in the above sections of Cachet as a bit of added security.

**Comment by jbrooksuk** [comment]
I'm putting this into V3, but feel free to implement it sooner if you'd like.

**Comment by GrahamCampbell** [comment]
Moving to 2.1. ;)

**Comment by TheoBearman** [comment]
Awwww yiss

**Comment by AntoineAugusti** [comment]
Will try to tackle this this weekend

**Comment by jbrooksuk** [comment]
:+1:

**Comment by GrahamCampbell** [comment]
Moving this to v2.0.0 then.

**Comment by jbrooksuk** [comment]
Closed by 1914e54def55a78789bad0a3c600169ed3aa5eb6
