### ISSUE TITLE
Gulp problems.

### ISSUE THREAD

**Issue by hyfox** [cachethq/Cachet#946]
Hey - I really like the application you've made. However - I've made som edits to the css and templates and wanted to rebuild the files.

I don't know anything specific about Sass (or Laravel for that sake); however when I try to rebuild it, I get the following:

[root@status01 Cachet]# sudo gulp
[09:41:22] Using gulpfile /var/www/Cachet/gulpfile.js
[09:41:22] Starting 'default'...
[09:41:22] Starting 'sass'...

Fetching Sass Source Files...
   - resources/assets/sass/app.scss

Saving To...
   - public/dist/css/app.css

[09:41:23] Finished 'default' after 702 ms
[09:41:23] gulp-notify: [Laravel Elixir] Sass Compilation Failed: resources/assets/sass/app.scss
  4:9  file to import not found or unreadable: ./vendor/bower_components/ionicons/scss/ionicons
Current dir: 
[09:41:23] gulp-notify: [Error running notifier] Could not send message: not found: notify-send
{ [Error: resources/assets/sass/app.scss
  4:9  file to import not found or unreadable: ./vendor/bower_components/ionicons/scss/ionicons
Current dir: ]
  message: 'resources/assets/sass/app.scss\n  4:9  file to import not found or unreadable: ./vendor/bower_components/ionicons/scss/ionicons\nCurrent dir: ',
  column: 9,
  line: 4,
  file: 'stdin',
  status: 1,
  messageFormatted: '\u001b[4mresources/assets/sass/app.scss\u001b[24m\n\u001b[90m  4:9\u001b[39m  file to import not found or unreadable: ./vendor/bower_components/ionicons/scss/ionicons\nCurrent dir: ',
  name: 'Error',
  stack: 'Error: resources/assets/sass/app.scss\n  4:9  file to import not found or unreadable: ./vendor/bower_components/ionicons/scss/ionicons\nCurrent dir: \n    at options.error (/var/www/Cachet/node_modules/laravel-elixir/node_modules/gulp-sass/node_modules/node-sass/lib/index.js:276:32)',
  showStack: false,
  showProperties: true,
  plugin: 'gulp-sass' }
[09:41:23] Finished 'sass' after 741 ms
[09:41:23] Starting 'styles'...

Fetching Styles Source Files...
   - vendor/bower_components/jquery-minicolors/jquery.minicolors.css <-- Not Found
   - public/dist/css/app.css <-- Not Found

Saving To...
   - public/dist/css/all.css

[09:41:23] Finished 'styles' after 17 ms
[09:41:23] Starting 'scripts'...

Fetching Scripts Source Files...
   - vendor/bower_components/jquery/dist/jquery.js <-- Not Found
   - vendor/bower_components/bootstrap-sass/assets/javascripts/bootstrap.js <-- Not Found
   - vendor/bower_components/moment/min/moment-with-locales.js <-- Not Found
   - vendor/bower_components/eonasdan-bootstrap-datetimepicker/src/js/bootstrap-datetimepicker.js <-- Not Found
   - vendor/bower_components/lodash/dist/lodash.js <-- Not Found
   - vendor/bower_components/autosize/dest/autosize.js <-- Not Found
   - vendor/bower_components/messenger/build/js/messenger.js <-- Not Found
   - vendor/bower_components/Sortable/Sortable.js <-- Not Found
   - vendor/bower_components/livestampjs/livestamp.js <-- Not Found
   - vendor/bower_components/jquery-minicolors/jquery.minicolors.js <-- Not Found
   - vendor/bower_components/jquery-serialize-object/jquery.serialize-object.js <-- Not Found
   - vendor/bower_components/chartjs/Chart.js <-- Not Found
   - resources/assets/js/app.js
   - resources/assets/js/**/*.js

Saving To...
   - public/dist/js/all.js

[09:41:24] gulp-notify: [Laravel Elixir] Scripts Merged!
[09:41:24] gulp-notify: [Error in notifier] Error in plugin 'gulp-notify'
Message:
    notify-send must be installed on the system.
[09:41:24] Finished 'scripts' after 1.5 s
[09:41:24] Starting 'version'...

Fetching Version Source Files...
   - public/dist/css/all.css <-- Not Found
   - public/dist/js/all.js

Saving To...
   - public/build

[09:41:25] Finished 'version' after 40 ms
[09:41:25] Starting 'copy'...

Fetching Copy Source Files...
   - vendor/bower_components/ionicons/fonts//**/*

Saving To...
   - public/fonts/

[09:41:25] Finished 'copy' after 7.35 ms

Could you point me in the right direction? 
Thank you! :)

**Comment by jbrooksuk** [comment]
You're missing some steps :)

1. `npm install`
2. `bower install`
3. `gulp`

You've missed out the Bower stage, which is required to pull in the assets we use.
