### ISSUE TITLE
No supported encrypter found. The cipher and / or key length are invalid. on latest release

### ISSUE THREAD

**Issue by dennusb** [cachethq/Cachet#948]
Hi,

I just wanted to upgrade from 1.x to 1.2.1, worked well (db migrations etc) but now i get a "No supported encrypter found. The cipher and / or key length are invalid." in the browser. 
In the config/app.php things are set to : 

" 'key' => env('APP_KEY', 'SomeRandomString'),

    'cipher' => 'rijndael-256',
"

What can i do to get it to work again?

**Comment by kurt---** [comment]
Running composer again worked for me.

Kurt
Am 18.09.2015 10:35 schrieb "dennusb" <notifications@github.com>:

**Comment by dennusb** [comment]
Which command exactly did you run Kurt?

**Comment by GrahamCampbell** [comment]
NEVER change the cipher from `'cipher' => 'AES-256-CBC',`.

**Comment by dennusb** [comment]
The default is also not working...

**Comment by GrahamCampbell** [comment]
You MUST set a 32 character private key in the .env file.

**Comment by dennusb** [comment]
In the old version (1.x) it was not set to a 32 char key, working perfectly. If i change it now all the data is gone right?

**Comment by GrahamCampbell** [comment]
> If i change it now all the data is gone right?

No. Nothing in the database is encrypted.

> In the old version (1.x) it was not set to a 32 char key, working perfectly.

Yeh, that was a security bug...

**Comment by dennusb** [comment]
So a php artisan key:generate should fix the problem? Because it does not.

**Comment by GrahamCampbell** [comment]
It won't fix it if you've not got a .env file. NB, .env.example isn't good enough.

**Comment by dennusb** [comment]
I have an .env file :)

**Comment by GrahamCampbell** [comment]
Well, just type out 32 chars of crap then. Nothing beats human random. :)

**Comment by dennusb** [comment]
And what does 'ciper' in the config needs to be?

**Comment by GrahamCampbell** [comment]
What ever it's set as in our code on github on the 1.2 branch. ;)

**Comment by dennusb** [comment]
Done. And set 32 chars of bullshit, still not working : 
APP_KEY=CHtK4tTSgcxSlgcEsm2L7Fr6RHgqVFd9

**Comment by GrahamCampbell** [comment]
Did you run the config cache command?

**Comment by dennusb** [comment]
What command is that?

**Comment by GrahamCampbell** [comment]
Also, you'll need to change that key because now you've put it on github. That key should be treated like a password.

**Comment by dennusb** [comment]
I know :)

**Comment by GrahamCampbell** [comment]
http://laravel.com/docs/5.0/configuration#configuration-caching

**Comment by dennusb** [comment]
That fixed it. Thanks. Might be a good idea to put it in the documentation :)

**Comment by GrahamCampbell** [comment]
Well, it is in docs. http://laravel.com/docs/

**Comment by GrahamCampbell** [comment]
Anything in laravel's docs applies to cachet,

**Comment by dennusb** [comment]
Users don't want to open Laravel docs, it should be in the Cachet docs.

**Comment by GrahamCampbell** [comment]
Hmm, well, there's plenty of other stuff users will need larvel's docs for in cachet, and I don't really see why we should duplicate it.

**Comment by jbrooksuk** [comment]
2.0 simplifies a lot of the installation.
