### ISSUE TITLE
unix_socket for named instance myslq

### ISSUE THREAD

**Issue by lcc2207** [cachethq/Cachet#949]
I've added the following but it still trys to connect to the default instances

/config/database.php

        'mysql' => [
            'driver'    => 'mysql',
            'host'      => env('DB_HOST', null),
            'unix_socket'    => '/var/run/mysql-cachet/mysqld.sock',
            'database'  => env('DB_DATABASE', null),
            'username'  => env('DB_USERNAME', null),
            'password'  => env('DB_PASSWORD', null),
            'charset'   => 'utf8',
            'collation' => 'utf8_unicode_ci',
            'prefix'    => '',
            'strict'    => false,
        ],

Error
SQLSTATE[HY000] [2002] Can't connect to local MySQL server through socket '/var/run/mysqld/mysqld.sock' (2)

**Comment by jbrooksuk** [comment]
Try clearing your config cache `php artisan config:cache`.

**Comment by lcc2207** [comment]
That seems to have fixed it.. thank you
