### ISSUE TITLE
Cachet in Intranet - Issue with proxy

### ISSUE THREAD

**Issue by unixengineer** [cachethq/Cachet#956]
I am trying to setup cachet in intranet, and everything needs a proxy to go out to the internet. After setting up cachet, it looks like the when you hit the index, it tries to ping/poll github, and the page takes a very long time to load.

```
storage/logs/laravel-2015-09-24.log:[2015-09-24 04:59:48] production.ERROR: exception 'GuzzleHttp\Exception\ConnectException' with message 'cURL error 7: Failed connect to api.github.com:443; Operation now in progress (see http://curl.haxx.se/libcurl/c/libcurl-errors.html)' in /var/www/html/cachet/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php:168
```

Is there a way to disable this call to api.github.com ?

**Comment by jbrooksuk** [comment]
There sure is, you can go into `./config/app.php` and remove the `EmojiServiceProvider` line :)

**Comment by TheoBearman** [comment]
It seems it's causing quite a few issues.

**Comment by jbrooksuk** [comment]
We'll probably have a configuration option for this soon.

**Comment by TheoBearman** [comment]
I was hoping you would say that.

**Comment by TheoBearman** [comment]
Will open an issue.
