### ISSUE TITLE
Metric graph not in local time

### ISSUE THREAD

**Issue by durzo** [cachethq/Cachet#959]
I have a metric where i pull Amazon CloudWatch data and push into Cachet, the timestamps are in the servers local time in USA (UTC)

The browser I view those graphs on is GMT+8, but the graph renders the data according to UTC so while it is currently 13:00 here, the latest datapoint says 05:00 and is almost out of the viewable graph area on the very left side.

This gives the impression that my graphs have not updated in several hours, and is confusing for our customers.

Screenshot attached

![screenshot from 2015-09-25 13 03 58](https://cloud.githubusercontent.com/assets/346775/10093511/f9aab364-6385-11e5-8ba5-7da83077d2f5.png)

**Comment by jbrooksuk** [comment]
Are you using 1.2?

**Comment by durzo** [comment]
I was not, however I have just upgraded to v1.2.1 and the issue persists

**Comment by jbrooksuk** [comment]
@joecohens what are we doing wrong here? Everything looks to be good.

**Comment by durzo** [comment]
My status page is public if you would like to see it: https://status.moodlecloud.com/

**Comment by joecohens** [comment]
Hey @durzo thanks! what's your configured datetime zone on the Cachet settings?

**Comment by durzo** [comment]
The timezone was set to Perth, Australia (GMT+8)

I changed it to the same timezone as the CloudWatch metrics and now the graphs look correct, but this changes the date/times of incidents on the page, shifting the issue from metrics to incidents. incidents that occur at 13:00 now show as 05:00.

I guess it would be easier for me to change the metric data before inserting into Cachet, its just annoying.

**Comment by joecohens** [comment]
Yeah I guess we don't have that functionality yet. The request to the Cachet API should be formatted on the configured datetime. @jbrooksuk Should we make it UTC by default? Still people will have to convert it to a default one, unless we add a new param on the request to capture the timezone.

**Comment by jbrooksuk** [comment]
I thought we stored everything in UTC currently?

**Comment by joecohens** [comment]
Oh yeah I mean in the request, not in the storage.

**Comment by jbrooksuk** [comment]
Ah right, I see. Then yes, probably should default to UTC :)

**Comment by jbrooksuk** [comment]
I like the idea of a timezone parameter. It doesn't break anything and it's up to the API consumer to do the right thing.

**Comment by billmn** [comment]
I think that could be better using header instead of a parameter, like Github: https://developer.github.com/v3/#timezones

**Comment by jbrooksuk** [comment]
I'd prefer that. If you'd like to implement it, I'm happy to check it.

**Comment by billmn** [comment]
@jbrooksuk I see now that this conversation is about on Metrics only, right?

I proposed to use header because I thought you would convert dates for all API endpoints but, from what I understand, it is not so ;)

**Comment by jbrooksuk** [comment]
There is no reason why we wouldn't implement timezones in this way across the board.

**Comment by billmn** [comment]
@jbrooksuk Can you clarify me what should we do to solve this?

In addition to allow a timezone parameter on the API (for metrics) we have to handle it on the index, right?

**Comment by jbrooksuk** [comment]
Closed in favour of https://github.com/cachethq/Cachet/issues/1011
