### ISSUE TITLE
Windows Install

### ISSUE THREAD

**Issue by thedaftbadger** [cachethq/Cachet#961]
Any luck with instructions on how to install Cachet in Windows running Apache?

**Comment by jbrooksuk** [comment]
@theobearman is running Cachet on Windows - would you be able to write up some instructions?

**Comment by TheoBearman** [comment]
@jbrooksuk. Potentially yes. Email me?

**Comment by jbrooksuk** [comment]
Sure :+1:

**Comment by TheoBearman** [comment]
@thedaftbadger Keep an eye on docs.cachet.io today. I will try and get some Windows-specific install docs up tonight.

**Comment by thedaftbadger** [comment]
@TheoBearman Perfect, thanks :)
We run Apache on Windows, no IIS :smile:

**Comment by TheoBearman** [comment]
As do I.

**Comment by TheoBearman** [comment]
[Here we go!](https://docs.cachethq.io/docs/installing-cachet-on-windows)

**Comment by thedaftbadger** [comment]
Thanks. I'll give it a go tomorrow afternoon and see how I get on.

**Comment by jbrooksuk** [comment]
Closing this as a non-issue.

**Comment by cemerson** [comment]
If anyone has Cachet.io running on Windows with IIS (not Apache) let me know. I've done all the steps in @TheoBearman's Windows guide but am stuck at the end unsure how to finish (for IIS).

**Comment by coventryollie** [comment]
Sorry for bumping a previous post - but did anyone ever get this working on iis?
