### ISSUE TITLE
Erreur 500 | Internal Server Error | Debian 8

### ISSUE THREAD

**Issue by BadBlockDev** [cachethq/Cachet#962]
Hello,

I have a 500 error when I go to my page status http://launcher.badblock.fr/

Here are the stamp logs

[2015-09-28 22:49:27] production.ERROR: exception 'RuntimeException' with message 'No supported encrypter found. The cipher and / or key length are invalid.' in /var/www/Cachet/bootstrap/cache/compiled.php:6784
Stack trace:
#0 /var/www/Cachet/bootstrap/cache/compiled.php(1086): Illuminate\Encryption\EncryptionServiceProvider->Illuminate\Encryption\{closure}(Object(Illuminate\Foundation\Application), Array)
#1 /var/www/Cachet/bootstrap/cache/compiled.php(1039): Illuminate\Container\Container->build(Object(Closure), Array)
#2 /var/www/Cachet/bootstrap/cache/compiled.php(1577): Illuminate\Container\Container->make('encrypter', Array)
#3 /var/www/Cachet/bootstrap/cache/compiled.php(1131): Illuminate\Foundation\Application->make('Illuminate\\Cont...')
#4 /var/www/Cachet/bootstrap/cache/compiled.php(1115): Illuminate\Container\Container->resolveClass(Object(ReflectionParameter))
#5 /var/www/Cachet/bootstrap/cache/compiled.php(1101): Illuminate\Container\Container->getDependencies(Array, Array)
#6 /var/www/Cachet/bootstrap/cache/compiled.php(1039): Illuminate\Container\Container->build('Illuminate\\Cook...', Array)
#7 /var/www/Cachet/bootstrap/cache/compiled.php(1577): Illuminate\Container\Container->make('Illuminate\\Cook...', Array)
#8 /var/www/Cachet/bootstrap/cache/compiled.php(9279): Illuminate\Foundation\Application->make('Illuminate\\Cook...')
#9 /var/www/Cachet/bootstrap/cache/compiled.php(2776): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#10 [internal function]: Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode->handle(Object(Illuminate\Http\Request), Object(Closure))
#11 /var/www/Cachet/bootstrap/cache/compiled.php(9279): call_user_func_array(Array, Array)
#12 /var/www/Cachet/vendor/fideloper/proxy/src/TrustProxies.php(47): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#13 [internal function]: Fideloper\Proxy\TrustProxies->handle(Object(Illuminate\Http\Request), Object(Closure))
#14 /var/www/Cachet/bootstrap/cache/compiled.php(9279): call_user_func_array(Array, Array)
#15 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#16 /var/www/Cachet/bootstrap/cache/compiled.php(9269): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#17 /var/www/Cachet/bootstrap/cache/compiled.php(2053): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#18 /var/www/Cachet/bootstrap/cache/compiled.php(2036): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter(Object(Illuminate\Http\Request))
#19 /var/www/Cachet/public/index.php(54): Illuminate\Foundation\Http\Kernel->handle(Object(Illuminate\Http\Request))
#20 {main} {"identification":{"id":"4ba4332a-aacc-46d6-a152-1f5162c01cc9"}} 
[2015-09-28 22:49:27] production.ERROR: exception 'RuntimeException' with message 'No supported encrypter found. The cipher and / or key length are invalid.' in /var/www/Cachet/bootstrap/cache/compiled.php:6784
Stack trace:
#0 /var/www/Cachet/bootstrap/cache/compiled.php(1086): Illuminate\Encryption\EncryptionServiceProvider->Illuminate\Encryption\{closure}(Object(Illuminate\Foundation\Application), Array)
#1 /var/www/Cachet/bootstrap/cache/compiled.php(1039): Illuminate\Container\Container->build(Object(Closure), Array)
#2 /var/www/Cachet/bootstrap/cache/compiled.php(1577): Illuminate\Container\Container->make('encrypter', Array)
#3 /var/www/Cachet/bootstrap/cache/compiled.php(1131): Illuminate\Foundation\Application->make('Illuminate\\Cont...')
#4 /var/www/Cachet/bootstrap/cache/compiled.php(1115): Illuminate\Container\Container->resolveClass(Object(ReflectionParameter))
#5 /var/www/Cachet/bootstrap/cache/compiled.php(1101): Illuminate\Container\Container->getDependencies(Array, Array)
#6 /var/www/Cachet/bootstrap/cache/compiled.php(1039): Illuminate\Container\Container->build('Illuminate\\Cook...', Array)
#7 /var/www/Cachet/bootstrap/cache/compiled.php(1577): Illuminate\Container\Container->make('Illuminate\\Cook...', Array)
#8 /var/www/Cachet/bootstrap/cache/compiled.php(2060): Illuminate\Foundation\Application->make('Illuminate\\Cook...')
#9 /var/www/Cachet/public/index.php(57): Illuminate\Foundation\Http\Kernel->terminate(Object(Illuminate\Http\Request), Object(Illuminate\Http\Response))
#10 {main} {"identification":{"id":"dadb51c4-730c-4942-8654-85779914feed"}} 

Thanks good.

Translated by Google Translate

Best regards
micro_maniaque

**Comment by jbrooksuk** [comment]
You need to run `php artisan key:generate` then `php artisan config:cache`.
