### ISSUE TITLE
Incident notifications as events

### ISSUE THREAD

**Issue by mrbase** [cachethq/Cachet#963]
I'm in the process of setting up Cachet for a client of mine, but they want "true incident notifications" - that means notifications on:
- new incidents
- updated incidents
- closed/fixed incidents

Same goes for Component state changes. Also the client wishes to have notifications send to Slack.

I have done all this as a addon package which hooks into Eloquent events ala:

```php
public function boot() {
    Incident::saving(xxx\IncidentEvents::class);
    Component::updated(xxx\ComponentEvents::class);
}
```

This however is not optimal.

I propose to change the "email notification event" to a more generic event - which fires `onIncidentCreated`, `onIncidentUpdated`, `onIncidentDeleted`, `onComponentStateChanged` ect.

That way any addon package can easily hook into the system and allows for more integrations (HipChat, SMS ect.)

If it sounds like something you could use let me know - and I will see if I can't find the time to create a PR for it.

**Comment by jbrooksuk** [comment]
We'd accept a well written PR on this.

**Comment by jbrooksuk** [comment]
2.0 has a bunch of events that get fired when things happen, it should be really easy to hook into.

**Comment by mrbase** [comment]
ok, will look into that :)

**Comment by mrbase** [comment]
Ok, I'm going to close this issue and start working on a slack addon using the events in 2.0
