### ISSUE TITLE
Use translations on JS labels

### ISSUE THREAD

**Issue by billmn** [CachetHQ/Cachet#974]
I noticed that JS doesn't use translated labels, like here: https://github.com/cachethq/Cachet/blob/eadedeecbf4c43256c883efb98e9a1dd2db5f906/resources/assets/js/app.js#L172

What about create a specific lang file that contains labels for JS?
This array can be converted into JSON and used in a JS variable.

Suggestions?

**Comment by jbrooksuk** [comment]
Yeah, it's always annoyed us that we've never translated them. Alternatively we could use a data attribute with the translation string somewhere?

**Comment by billmn** [comment]
@jbrooksuk I'm not sure I understand what you intend to do, can you give me an example?

An example of my proposal:

```html
    <script type="text/javascript">
        var Global = {};
        Global.locale = '{{ Setting::get('app_locale') }}';

        // Extract translations from a Lang file
        Global.transl = {!! json_encode(trans('auth')) !!};

        // Result: "These credentials do not match our records."
        console.log(Global.transl.failed);
    </script>
```

**Comment by AntoineAugusti** [comment]
Could https://github.com/laracasts/PHP-Vars-To-Js-Transformer be useful?

**Comment by jbrooksuk** [comment]
Ah, I see. That's a good idea @billmn.

**Comment by jbrooksuk** [comment]
@AntoineAugusti I'm really sorry that I didn't reply! I think that yes, it'd be really useful!

**Comment by jbrooksuk** [comment]
Thank you for your input on Cachet 2.x. We are shifting our attention and resources to Cachet 3.x and will no longer be supporting the 2.x version. If your feedback or issue is relevant to the 3.x series, we encourage you to engage with the new branch.

For more information on the Cachet rebuild and our plans for 3.x, you can read the announcement [here](https://github.com/CachetHQ/Cachet/discussions/4342).

We appreciate your understanding and look forward to your contributions to the new version.
