### ISSUE TITLE
Steps to launch

### ISSUE THREAD

**Issue by jbrooksuk** [cachethq/Cachet#99]
Once Cachet is setup, I think that we could display "steps to launch" in the dashboard index, it'll basically walk them through the things they've left to do:

1. Setup Cachet (ticked obviously)
2. Login to dashboard (ticked, because they should be auto logged in).
3. Add components (ticked once there are > 0 components in the DB).
4. Add first incident (ticked once there are > 0 incidents in the DB).
5. Customize Cachet with theme settings.

Then a button to hide the steps.

By adding this kind of feature we're showing the user how to use Cachet in a non-invasive way.

I'm thinking of something like this:

![screenshot 2014-12-28 10 27 55](https://cloud.githubusercontent.com/assets/246103/5563620/7fc96e3e-8e7c-11e4-9b3a-95c5ec1dceb7.png)

**Comment by joecohens** [comment]
See https://github.com/cachethq/Cachet/pull/403
