### ISSUE TITLE
Error 500 Internal Server Error

### ISSUE THREAD

**Issue by Hiddenx** [cachethq/Cachet#991]
Followed the entire doc at - https://docs.cachethq.io/docs/installing-cachet , still getting the below ERROR 500 page.

<img width="901" alt="screen shot 2015-10-04 at 9 32 10 am" src="https://cloud.githubusercontent.com/assets/5173950/10266385/5580f92c-6a7b-11e5-81dd-b8a1a445860d.png">

Also looked at the thread #656, didn't help either. 
Thanks for any help.

**Comment by GrahamCampbell** [comment]
Please show is your log file. That generic 500 page is as useless to us as you saying "it's broke".

**Comment by jbrooksuk** [comment]
We're closing this as it's very likely a non-issue with Cachet, however if you show us your logs, we'll be happy to help.

**Comment by srikanth88infy** [comment]
Hi @jbrooksuk ,  even I'm encountered by a http 500. Following is the laravel log. Could you please help me out! 

[2015-10-22 23:16:24] local.CRITICAL: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'Call to undefined function Illuminate\Cache\apc_fetch()' in C:\wamp\www\cloudfire.status\vendor\laravel\framework\src\Illuminate\Cache\ApcWrapper.php:32
Stack trace:
#0 C:\wamp\www\cloudfire.status\vendor\laravel\framework\src\Illuminate\Foundation\Bootstrap\HandleExceptions.php(133): Symfony\Component\Debug\Exception\FatalErrorException->__construct()
#1 C:\wamp\www\cloudfire.status\vendor\laravel\framework\src\Illuminate\Foundation\Bootstrap\HandleExceptions.php(118): Illuminate\Foundation\Bootstrap\HandleExceptions->fatalExceptionFromError()
#2 C:\wamp\www\cloudfire.status\vendor\laravel\framework\src\Illuminate\Foundation\Bootstrap\HandleExceptions.php(0): Illuminate\Foundation\Bootstrap\HandleExceptions->handleShutdown()
#3 C:\wamp\www\cloudfire.status\vendor\laravel\framework\src\Illuminate\Cache\ApcStore.php(44): Illuminate\Cache\ApcWrapper->get()
#4 C:\wamp\www\cloudfire.status\vendor\laravel\framework\src\Illuminate\Cache\Repository.php(97): Illuminate\Cache\ApcStore->get()
#5 C:\wamp\www\cloudfire.status\vendor\laravel\framework\src\Illuminate\Session\CacheBasedSessionHandler.php(58): Illuminate\Cache\Repository->get()
#6 C:\wamp\www\cloudfire.status\vendor\laravel\framework\src\Illuminate\Session\Store.php(124): Illuminate\Session\CacheBasedSessionHandler->read()
#7 C:\wamp\www\cloudfire.status\vendor\laravel\framework\src\Illuminate\Session\Store.php(108): Illuminate\Session\Store->readFromHandler()
#8 C:\wamp\www\cloudfire.status\vendor\laravel\framework\src\Illuminate\Session\Store.php(92): Illuminate\Session\Store->loadSession()
#9 C:\wamp\www\cloudfire.status\vendor\laravel\framework\src\Illuminate\Session\Middleware\StartSession.php(102): Illuminate\Session\Store->start()
#10 C:\wamp\www\cloudfire.status\vendor\laravel\framework\src\Illuminate\Session\Middleware\StartSession.php(57): Illuminate\Session\Middleware\StartSession->startSession()
#11 C:\wamp\www\cloudfire.status\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(124): Illuminate\Session\Middleware\StartSession->handle()
#12 C:\wamp\www\cloudfire.status\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(124): call_user_func_array:{C:\wamp\www\cloudfire.status\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php:124}()
#13 C:\wamp\www\cloudfire.status\vendor\laravel\framework\src\Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse.php(37): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#14 C:\wamp\www\cloudfire.status\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(124): Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse->handle()
#15 C:\wamp\www\cloudfire.status\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(124): call_user_func_array:{C:\wamp\www\cloudfire.status\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php:124}()
#16 C:\wamp\www\cloudfire.status\vendor\laravel\framework\src\Illuminate\Cookie\Middleware\EncryptCookies.php(59): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#17 C:\wamp\www\cloudfire.status\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(124): Illuminate\Cookie\Middleware\EncryptCookies->handle()
#18 C:\wamp\www\cloudfire.status\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(124): call_user_func_array:{C:\wamp\www\cloudfire.status\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php:124}()
#19 C:\wamp\www\cloudfire.status\vendor\laravel\framework\src\Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode.php(42): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#20 C:\wamp\www\cloudfire.status\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(124): Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode->handle()
#21 C:\wamp\www\cloudfire.status\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(124): call_user_func_array:{C:\wamp\www\cloudfire.status\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php:124}()
#22 C:\wamp\www\cloudfire.status\vendor\fideloper\proxy\src\TrustProxies.php(47): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#23 C:\wamp\www\cloudfire.status\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(124): Fideloper\Proxy\TrustProxies->handle()
#24 C:\wamp\www\cloudfire.status\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(124): call_user_func_array:{C:\wamp\www\cloudfire.status\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php:124}()
#25 C:\wamp\www\cloudfire.status\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(103): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#26 C:\wamp\www\cloudfire.status\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(103): call_user_func:{C:\wamp\www\cloudfire.status\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php:103}()
#27 C:\wamp\www\cloudfire.status\vendor\laravel\framework\src\Illuminate\Foundation\Http\Kernel.php(122): Illuminate\Pipeline\Pipeline->then()
#28 C:\wamp\www\cloudfire.status\vendor\laravel\framework\src\Illuminate\Foundation\Http\Kernel.php(87): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter()
#29 C:\wamp\www\cloudfire.status\public\index.php(54): Illuminate\Foundation\Http\Kernel->handle()
#30 C:\wamp\www\cloudfire.status\public\index.php(0): {main}()
#31 {main} {"identification":{"id":"86fba186-facb-4603-9e0d-c568d0f06718"}}
