### ISSUE TITLE
CSRF token validation failed

### ISSUE THREAD

**Issue by peterlaws** [cachethq/Cachet#992]
I only did a 
#php ./artisan config:clear
#php ./artisan config:cache

and I'm unable to log in anymore, what did I break?

------
Symfony\Component\HttpKernel\Exception\BadRequestHttpException thrown with message "CSRF token validation failed."

Stacktrace:
5 Symfony\Component\HttpKernel\Exception\BadRequestHttpException in /var/www/Cachet/vendor/graham-campbell/exceptions/src/Transformers/CsrfTransformer.php:36
4 GrahamCampbell\Exceptions\Transformers\CsrfTransformer:transform in /var/www/Cachet/vendor/graham-campbell/exceptions/src/ExceptionHandler.php:132
3 GrahamCampbell\Exceptions\ExceptionHandler:getTransformed in /var/www/Cachet/vendor/graham-campbell/exceptions/src/ExceptionHandler.php:112
2 GrahamCampbell\Exceptions\ExceptionHandler:render in /var/www/Cachet/bootstrap/cache/compiled.php:2106
1 Illuminate\Foundation\Http\Kernel:renderException in /var/www/Cachet/bootstrap/cache/compiled.php:2022
#0 Illuminate\Foundation\Http\Kernel:handle in /var/www/Cachet/public/index.php:54

**Comment by GrahamCampbell** [comment]
Did you refresh the login page first before trying to login?

**Comment by peterlaws** [comment]
Yep, even tried another browser....

**Comment by jbrooksuk** [comment]
I take it you're all setup?

**Comment by peterlaws** [comment]
Well, it was set up 2 months ago....  Wished I never touched it  now.

What does this error really mean?

**Comment by jbrooksuk** [comment]
Most forms have a hidden input field called `_token`. The server checks that the `_token` value matches a server-side token. If it doesn't, then validation fails.

What version are you running on?

**Comment by peterlaws** [comment]
The form has a _token, is is meant to match the .env's APP_KEY?

**Comment by jbrooksuk** [comment]
Nope, the `APP_KEY` value is there to encrypt data like sessions.

Try the following:

- Run `php artisan config:cache`.
- `rm -rf bootstrap/cache/*`

Anything?

**Comment by peterlaws** [comment]
Still nothing...... Is it that easy to break?

What is the best way to upgrade? Is it just like an install? eg. git clone blah

**Comment by GrahamCampbell** [comment]
Maybe try clearing your sessions?

**Comment by GrahamCampbell** [comment]
> What is the best way to upgrade? Is it just like an install? eg. git clone blah

Did you run `artisan app:update`?

**Comment by GrahamCampbell** [comment]
Are you on 2.x?

**Comment by peterlaws** [comment]
Clearing browser sessions? I've tried 3 separate browsers though. About to give up.

app:update is unknown so I'm guessing I'm on an old version?

All this because I'm trying to find out why it wont connect to Google's SMTP server (G Apps)

**Comment by GrahamCampbell** [comment]
> Clearing browser sessions?

Clear the session storage on the server side.

**Comment by peterlaws** [comment]
Still errors

**Comment by jbrooksuk** [comment]
`php artisan cache:clear`?

**Comment by peterlaws** [comment]
Ditto.

**Comment by GrahamCampbell** [comment]
What session driver?

**Comment by peterlaws** [comment]
from .env:

CACHE_DRIVER=array
SESSION_DRIVER=array
QUEUE_DRIVER=database

Not sure!

**Comment by jbrooksuk** [comment]
Can you try using `apc` as your `SESSION_DRIVER`?

**Comment by peterlaws** [comment]
That worked! 

What version am I using, how do I check?

**Comment by jbrooksuk** [comment]
You could do `git log -n1` and tell us what the SHA-1 commit is?

**Comment by peterlaws** [comment]
14ec134ac1e30249a2953e973c2fdf3be22ea111

**Comment by jbrooksuk** [comment]
Looks like you're using 2.0-beta1.

**Comment by GrahamCampbell** [comment]
> SESSION_DRIVER=array

You deficiently don't want that! That turns sessions off essentially.

**Comment by jbrooksuk** [comment]
Is this in the docs, I wonder?

**Comment by GrahamCampbell** [comment]
Why would anyone choose array?

**Comment by GrahamCampbell** [comment]
We don't suggest that anyone uses it...

**Comment by peterlaws** [comment]
Well, I didn't actually add array to them, I assume it did it by itself, and as it worked, I just left them.

I've set both to 'apc' now.
