### ISSUE TITLE
Google SMTP

### ISSUE THREAD

**Issue by peterlaws** [cachethq/Cachet#999]
Sorry if this isn't an issue, but I'm having a tough time with this:

in my .env I have
> MAIL_DRIVER=smtp
> MAIL_HOST=smtp.gmail.com
> MAIL_PORT=465
> MAIL_ENCRYPTION=ssl

However, I get a
> production.ERROR: exception 'Swift_TransportException' with message 'Connection to tcp://smtp.gmail.com:465 Timed Out' in
> /var/www/Cachet/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Transport/AbstractSmtpTransport.php:404

Normally, connecting with, eg PHP Mailer, you add ssl:// to the host, even if I add ssl:// to the host, the above still displays.

**Comment by jbrooksuk** [comment]
Have you set `MAIL_USERNAME` and `MAIL_PASSWORD`?

**Comment by peterlaws** [comment]
Yep, sorry I left them out of the above post as they aren't really needed here.

Playing with this issue yesterday lead to my other issue :P

**Comment by jbrooksuk** [comment]
> Yep, sorry I left them out of the above post as they aren't really needed here.
Sure, just wanted to make sure you have them.

I'll take a look at this tonight :)

**Comment by peterlaws** [comment]
Thanks

**Comment by jbrooksuk** [comment]
I'm on this now.

**Comment by jbrooksuk** [comment]
Weird, it all worked fine here.

**Comment by jbrooksuk** [comment]
Nope, I get this;

> local.ERROR: exception 'Swift_TransportException' with message 'Expected response code 250 but got code "530", with message "530-5.5.1 Authentication Required. Learn more at
530 5.5.1  https://support.google.com/mail/answer/14257 fv13sm16070089wic.7 - gsmtp
"' in /Users/jamesbrooks/Code/CachetHQ/Cachet/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Transport/AbstractSmtpTransport.php:383

**Comment by peterlaws** [comment]
At least you can connect... What's weird, I can even connect via telnet, at first I thought it was ipv6 iptables.

Maybe it's the version I have?

**Comment by jzielke** [comment]
Might try Port 587/TLS

Where does MAIL_ENCRYPTION come from?  I can't find Cachet docs on it.  Is that something Cachet will pass through to swift?  Is the a swift config setting?

I have no idea but poking around and looking at mail.php, it appears to be hard coded to TLS.  Might want to just change the port to 587 and see what happens.

**Comment by jzielke** [comment]
Ahhh it is fixed in Master but not the V1.2 release.  What version of Cachet are you on?

**Comment by peterlaws** [comment]
> Where does MAIL_ENCRYPTION come from? 
the example [.env](https://github.com/cachethq/Cachet/blob/master/.env.example), although its set to tls I thought ssl would work too.

>  What version of Cachet are you on?
Someone said v2.0.beta1 (sha1 ``14ec134ac1e30249a2953e973c2fdf3be22ea111``) <shrugs>

**Comment by GrahamCampbell** [comment]
v2.0.0 isn't far off now.

**Comment by GrahamCampbell** [comment]
There will be another beta or RC release in the near future, and soon after. a stable release.
